### ISSUE TITLE
[Feature Request] additional repository 

### ISSUE THREAD

**Issue by roock** [oerdnj/deb.sury.org#1004]
It would be helpful if you could add at least one unique value to the release description in the release file e.g.:

``` 
Component: debsury
Origin: packages.sury.org
Label: debsury
```

Background: We are mirroring your repository on our own mirror in a sub directory, so we cannot use apt pin like "Pin: origin "mirror.ourowndomain.com" (because it would match all other repos too). When adding these values we could do something like "Pin: release o=debsruyorg"

**Comment by nuxwin** [comment]
@roock 

There is already the repository origin field there.

```
jenkins@jenkins:/usr/local/src/SCM/php$ apt-cache policy |grep sury
 500 https://packages.sury.org/php stretch/main armhf Packages
     origin packages.sury.org
 500 https://packages.sury.org/php stretch/main arm64 Packages
     origin packages.sury.org
 500 https://packages.sury.org/php stretch/main i386 Packages
     origin packages.sury.org
 500 https://packages.sury.org/php stretch/main amd64 Packages
     origin packages.sury.org
```

This should be far sufficient for APT pinning.

**Comment by roock** [comment]
@nuxwin no, the origin field you are referring to depends on the mirror you are using. As already stated, we are using our own mirror, so this origin value is set to our own mirror, e.g.:

```
$ apt-cache policy
[....]
 500 https://mirror.example.com/puppetlabs stretch/puppet5 all Packages
     release o=Puppetlabs,a=stretch,n=stretch,l=Puppetlabs,c=puppet5,b=all
     origin mirror.example.com
 500 https://mirror.example.com/debsuryorg stretch/main amd64 Packages
     release o=deb.sury.org,n=stretch,c=main,b=amd64
     origin mirror.example.com
[...]
```
I just saw that there is a origin value in the Release file (deb.sury.org) which wasn't there two days ago.

**Comment by oerdnj** [comment]
> I just saw that there is a origin value in the Release file (deb.sury.org) which wasn't there two days ago. Was I really blind or was it added in the last two days? Anyway, I think the issue can be closed

It was added.  I don't know why it was missing, because I had it elsewhere.  I just haven't gotten to reply here.

**Comment by roock** [comment]
:+1: thanks @oerdnj
