### ISSUE TITLE
Illegal exceptions on Pi after updating packages

### ISSUE THREAD

**Issue by CoolSilver** [oerdnj/deb.sury.org#1006]
Preparing to unpack .../libpcre3_2%3a8.41-1+0~20180928072106.2+stretch~1.gbp97d153_armhf.deb ...
Unpacking libpcre3:armhf (2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153) over (2:8.39-3) ...
E: Sub-process /usr/bin/dpkg exited unexpectedly

SSH is broken as well as other functions on PI
pi@nextcloudpi:~ $ sudo apt-get upgrade php7.2-fpm
Illegal instruction

**Comment by CoolSilver** [comment]
https://packages.sury.org/php stretch/main armhf libpcre3 armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [320 kB]
https://packages.sury.org/php stretch/main armhf openssl armhf 1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86 [803 kB]
https://packages.sury.org/php stretch/main armhf libssl1.1 armhf 1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86 [1,310 kB]

Packages fetched that created the issue.

**Comment by oerdnj** [comment]
Whoever at Raspbian thought it’s ok to keep the architecture name armhf, but don’t require ARMv7-a to be in sync in Debian haven’t really thought it through.

You need at least armv7-a to mix Raspbian with Debian armhf packages.

**Comment by nachoparker** [comment]
> Whoever at Raspbian thought it’s ok to keep the architecture name armhf, but don’t require ARMv7-a to be in sync in Debian haven’t really thought it through.

indeed :(
