### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR after migration to Apache 2.4.37 from 2.4.7

### ISSUE THREAD

**Issue by Wilkun** [oerdnj/deb.sury.org#1007]
Hello, 

I have a specific issue that happens on my `Ubuntu 14.04` installation after upgrading `Apache` from `2.4.7` to `2.4.37` using the `ppa:ondrej/apache2` repository. At the same time I've updated the `openssl` to `1.1.1`.

In short, approx. 1/4 of requests sent to the server return `ERR_SSL_PROTOCOL_ERROR`, it happens at the same time on all enabled sites, then returns to normal just to happen again, in some loop.

Here is a more detailed explanation: [AskUbutnu][1]

[1]: https://askubuntu.com/questions/1094832/ssl-issues-after-migration-to-apache-2-4-37-from-2-4-7-using-ppaondrej-apache2

**Comment by oerdnj** [comment]
Is there a pattern? Perhaps the failing clients don’t have support for modern algorithms or TLS versions...
