### ISSUE TITLE
libcurl4 and php7.2-curl

### ISSUE THREAD

**Issue by vilppuvuorinen** [oerdnj/deb.sury.org#1008]
Thx for your great work,

using ~~ubuntu 18.04~~ debian stretch in evaluation its currently impossible to install php7.2-curl and curl (because second depends on libcurl4, but first one seems to use libcurl3):

```
$ sudo apt install curl php7.2-curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 curl : Depends: libcurl4 (= 7.62.0-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Can you provide for ~~ubuntu bionic~~debian stretch a php-curl version using libcurl4 please?

**Comment by oerdnj** [comment]
There’s no libcurl4 in Debian stretch. Unbreak your system and you will be fine.

**Comment by vilppuvuorinen** [comment]
And there we have closure for #831. If you are experiencing similar issues on stretch, `curl` has been installed from unstable for some reason.
