### ISSUE TITLE
apache2: openssl 1.1.1 vulnerabilities

### ISSUE THREAD

**Issue by obendev** [oerdnj/deb.sury.org#1009]
Hey Ondřej!
You should update openssl 1.1.1 to 1.1.1**a** since 1.1.1 has some vulnerabilities that are now fixed in 1.1.1a.
Changes: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/CHANGES

**Comment by Nosxxx** [comment]
Push

**Comment by oerdnj** [comment]
Those are low severity issues: https://www.openssl.org/news/secadv/20181029.txt

The fix and the vulnerability is public for a month. There’s no rush in updating the OpenSSL (e.g. I will do the update when I have a little bit of free time...)

**Comment by oerdnj** [comment]
Updated.
