### ISSUE TITLE
The following packages have unmet dependencies (apache2-mpm-prefork)

### ISSUE THREAD

**Issue by tersmitten** [oerdnj/deb.sury.org#101]
```
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2-mpm-prefork : Depends: apache2 (= 2.4.12-1+deb.sury.org~trusty+5) but 2.4.16-3+deb.sury.org~trusty+1 is to be installed

apt-get install 'apache2-mpm-prefork'  failed: E: Unable to correct problems, you have held broken packages.
```

It seems that installing `apache2-mpm-prefork` fails since the last PHP 5.6 update. Is that possible?

**Comment by oerdnj** [comment]
Looks like latest apache2 packages has dropped transitional packages. Do you need apache2-mpm-prefork for anything?

**Comment by tersmitten** [comment]
Not really, `mod_php` works fine without it. But I was installing it (in on of our [Ansible roles](http://docs.ansible.com/ansible/playbooks_roles.html)) to be explicit about dependencies.

Are there more packages dropped?

**Comment by geerlingguy** [comment]
Same thing here, but I've just removed the package from the list of required apache installations, and `mod_php` is still working fine without it explicitly defined.

**Comment by oerdnj** [comment]
JFTR since the switch to apache2 2.4 packaging, those *-mpm-* were just transitional packages:
```
Package: apache2-mpm-prefork
Description-en: transitional prefork MPM package for apache2
 This is a transitional package to apache2 for users of apache2-mpm-prefork and
 can be safely removed after the installation is complete.
```

Also you didn't have to have it in explicit dependencies as mod_php would pull the correct package.
