### ISSUE TITLE
OpenSSL 1.1.1 in ppa:ondrej/php causes issues with Nginx built with OpenSSL 1.1.0g

### ISSUE THREAD

**Issue by myfirstnameispaul** [oerdnj/deb.sury.org#1011]
I hadn't initially noticed that I now have OpenSSL 1.1.1 installed via ppa:ondrej/php, which is now causing issues with Nginx built with OpenSSL 1.1.0g.

The only behavior I have noticed so far is that I cannot disable TLSv1.3 in nginx.conf or otherwise affect any settings for TLSv1.3 (including available ciphers).

[TLS v1.3 active despite not being enabled in Nginx config](https://serverfault.com/q/941390/153188)

**Comment by oerdnj** [comment]
I don’t understand why this as problem, but you can always use the nginx from my repositories, as those are compiled against up-to-date OpenSSL.
