### ISSUE TITLE
Nginx 1.14.2 & 1.15.7 & OpenSSL 1.1.1a update

### ISSUE THREAD

**Issue by S8Cloud** [oerdnj/deb.sury.org#1012]
Plz update these latest packages

**Comment by oerdnj** [comment]
It should be done.

**Comment by oerdnj** [comment]
Hmm, Ubuntu is done, but there's been some problem in the DPA.

**Comment by S8Cloud** [comment]
```
nginx version: nginx/1.15.7
built with OpenSSL 1.1.1  11 Sep 2018 (running with OpenSSL 1.1.1a  20 Nov 2018)
```
Maybe nginx or apache packages should be built with latest openssl?

**Comment by oerdnj** [comment]
That exact patch version of OpenSSL doesn't really matter.
