### ISSUE TITLE
[Update] php-mongodb to 1.5.3

### ISSUE THREAD

**Issue by zolech** [oerdnj/deb.sury.org#1013]
Due to a serious bug with BSON serialization https://github.com/mongodb/mongo-php-driver/issues/873 we are experiencing many segfaults. This problem was fixed in version 1.5.3 so I kindly ask to update this module in a repository. Right now we are using pecl installed module but it would be awesome to continue using it with Your repository.

Thanks in advance!

**Comment by oerdnj** [comment]
Could you provide more information like distribution and version of the package (`apt-cache policy php-mongodb` will give you both...)

**Comment by zolech** [comment]
Sure

php-mongodb:
  Zainstalowana: 1.5.2-1+0~20180910132746.4+stretch~1.gbp2a1cd2
  Kandydująca:   1.5.2-1+0~20180910132746.4+stretch~1.gbp2a1cd2
  Tabela wersji:
 *** 1.5.2-1+0~20180910132746.4+stretch~1.gbp2a1cd2 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.3-1 500
        500 http://ftp.pl.debian.org/debian stretch/main amd64 Packages

**Comment by zolech** [comment]
@oerdnj Do you consider upgrading it ?
