### ISSUE TITLE
Status of support for the PHP 7.0 parts of some packages because PHP 7.0 is EOL

### ISSUE THREAD

**Issue by ewasser** [oerdnj/deb.sury.org#1014]
I'm curious about this repository and what happens to it because according to their [webpage](https://secure.php.net/eol.php) PHP `7.0` is reaching _today_ the status of EOL.

Will you support PHP `7.0` beyond this point in time (read: _tomorrow_)?

I'm asking because they are at least least 2 packages (e.g. `php-redis` and `php-apcu`) with support for multiple versions of PHP. The packages `php-redis` and `php-apcu` are supporting PHP versions from `5.6`, `7.0`, `7.1`, `7.2` up to `7.3`.

What happens to the support of the PHP version `7.0` for these packages?

1. Will you drop the PHP 7.0 support for these packages?
2. Or do continue with the PHP 7.0 support for these packages?
3. ???

Greetings and thank you for your work.

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/ubuntu-14-04-php-22093917

**Comment by ewasser** [comment]
Thanks I totally missed that article.
