### ISSUE TITLE
Recommended way to depend on PHP packages

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1015]
Hi,

What's the recommended way to depend on PHP packages?
For example adminer has:
```
Depends:
 libapache2-mod-php | php-cgi | php-fpm | php,
 php-mysql | php-sqlite3 | php-pgsql,
 ${misc:Depends},
Recommends:
 php-cli,
 php-mysql,
 php-pgsql,
 php-sqlite3,
Suggests:
 default-mysql-server | virtual-mysql-server | postgresql | sqlite3,

```

but it doesn't feel quite right. 
Also, what's the recommended way to use php with Apache? Is it still mod-php or would fpm be recommended?

https://salsa.debian.org/lamby/pkg-adminer/blob/debian/sid/debian/control

**Comment by oerdnj** [comment]
`Depends: php, php-mysql | php-sqlite3 | php-pgsql, ${misc:Depends}` should be enough as `php` depends on `phpX.Y` and `phpX.Y` depends on:

`Depends: libapache2-mod-phpX.Y | phpX.Y-fpm | phpX.Y-cgi, phpX.Y-common`

**Comment by OlafvdSpek** [comment]
> `Depends: php, php-mysql | php-sqlite3 | php-pgsql, ${misc:Depends}` should be enough as `php` depends on `phpX.Y` and `phpX.Y` depends on:

I assume `php-mysql` depends on `php` the explicit mention of `php` isn't required is it?
 
> `Depends: libapache2-mod-phpX.Y | phpX.Y-fpm | phpX.Y-cgi, phpX.Y-common`

Why is `phpX.Y-common` used there, doesn't each of the other packages already depend on it?
