### ISSUE TITLE
Jessie / Stretch libssl1.1 and python-httplib2 conflict

### ISSUE THREAD

**Issue by pierrehenrymuller** [oerdnj/deb.sury.org#1019]
Hi,
I open a ticket related to this post closed

Possible to make python-httplib2 package for Jessie and Stretch too?
Actually Ansible can't be installed in both distro.

Thanks

_Originally posted by @pierrehenrymuller in https://github.com/oerdnj/deb.sury.org/issue_comments#issuecomment-445451107_

**Comment by oerdnj** [comment]
Stretch has been updated to correct version, I am hesitant to update Jessie too, as things may break.  But you could try installing the version from Stretch and if that just works, I'll add the package.

**Comment by pierrehenrymuller** [comment]
Yes I have check and all works fine.
Thanks

**Comment by oerdnj** [comment]
Ok, then. I will provide updated python-httplib2 for Jessie.
