### ISSUE TITLE
Typo in 20-uprofiler.ini extension with Ubuntu 14.04 package

### ISSUE THREAD

**Issue by deviantintegral** [oerdnj/deb.sury.org#102]
In `/etc/php5/cli/conf.d/20-uprofiler.ini`:

```
[uprofiler]
extension=profiler.so
```

It should be `extension=uprofiler.so`.

**Comment by oerdnj** [comment]
Fixed in `uprofiler_0.11.0+8-g483c1e5-1+deb.sury.org~*+1` upload.
