### ISSUE TITLE
Build php-memcached for 7.3

### ISSUE THREAD

**Issue by xPaw** [oerdnj/deb.sury.org#1020]
Looks like it needs to be built from master right now, as there's no new release.

**Comment by xPaw** [comment]
That's a good label!

Just to add some info, basically theres' no memcached binary for the php 7.3 version, so this happens:

```$ php7.3 -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20180731/memcached.so (/usr/lib/php/20180731/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcached.so.so (/usr/lib/php/20180731/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Checking the `php-memcached` package, it doesn't provide a binary for that version:
```$ dpkg-query -L php-memcached | grep lib
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/memcached.so
/usr/lib/php/20151012
/usr/lib/php/20151012/memcached.so
/usr/lib/php/20160303
/usr/lib/php/20160303/memcached.so
/usr/lib/php/20170718
/usr/lib/php/20170718/memcached.so
```

**Comment by oerdnj** [comment]
That’s slightly better, but I still miss the distribution used and php-memcached package version.

**Comment by xPaw** [comment]
Using Debian 9

`php-memcached 3.0.4+2.2.0-3+0~20180910140656.5+stretch~1.gbpa130f3`

**Comment by xPaw** [comment]
Looks like you've update the package, thank you very much!

memcached loads correctly on php 7.3 now.
