### ISSUE TITLE
Size of [...] is not what the server reported

### ISSUE THREAD

**Issue by anthonykgross** [oerdnj/deb.sury.org#1024]
Hi guys !

When I do the following commands, I get this error. What's wrong ? Did I do something wrong ? 

```
# curl https://packages.sury.org/php/apt.gpg | apt-key add
# echo 'deb https://packages.sury.org/php/ jessie main' >> /etc/apt/sources.list
# apt-get update 
...
Size of file /var/lib/apt/lists/partial/packages.sury.org_php_dists_jessie_InRelease is not what the server reported 6921 185 
```

**Comment by anthonykgross** [comment]
# curl https://packages.sury.org/php/apt.gpg | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    842      0 --:--:-- --:--:-- --:--:--   844
gpg: no valid OpenPGP data found.

**Comment by todeveni** [comment]
The documentation should be updated for `curl` to follow redirects (and while at it, use silent mode, but show possible errors). I don't know where those instructions are, since https://packages.sury.xyz/php/README.txt uses wget for apt-key.

`curl -sSL https://packages.sury.org/php/apt.gpg | apt-key add -`

**Comment by oerdnj** [comment]
I have updated the instructions.

**Comment by anthonykgross** [comment]
Still the same issue : 

```
# curl -sSL https://packages.sury.org/php/apt.gpg | apt-key add
# echo 'deb https://packages.sury.org/php/ jessie main' >> /etc/apt/sources.list
# apt-get update 
...
Reading package lists... Done
W: Size of file /var/lib/apt/lists/partial/packages.sury.org_php_dists_jessie_InRelease is not what the server reported 6921 185
W: Size of file /var/lib/apt/lists/partial/packages.sury.org_php_dists_jessie_main_binary-amd64_Packages.gz is not what the server reported 63074 805 
```

Should I do something specific ? 

Have a great day and thanks you for your amazing work

**Comment by oerdnj** [comment]
I am going to revert the redirect to sury.xyz for now as I am working with a proper CDN provider now to provide a service to packages.sury.org.
