### ISSUE TITLE
add-apt-repository -y ppa:ondrej/php7 causes key errors

### ISSUE THREAD

**Issue by ChristopherBrand** [oerdnj/deb.sury.org#1027]
Adding ppa:ondrej/php creates GPG key errors. When I run the following:

`apt -y update && \
apt -y install software-properties-common && \
add-apt-repository -y ppa:ondrej/php`

results in the following errors:

`gpg: unknown option 'show-only'
gpg: invalid import options
Got '0' fingerprints, expected only one`

**Comment by oerdnj** [comment]
That's your gpg configuration, not mine.
