### ISSUE TITLE
Respin 7.3.0 to address zend optimizer bug?

### ISSUE THREAD

**Issue by GreenReaper** [oerdnj/deb.sury.org#1028]
There's what seems to be [an optimizer issue](https://bugs.php.net/bug.php?id=77275) which I think we are running into on our production website - we figured the GA version would be stable, but apparently not. ^_^

Is it feasible to respin 7.3.0 from the current 7.3 branch, or perhaps [cherry-pick part of this commit](http://git.php.net/?p=php-src.git;a=commit;h=93aabf1533bd3af673bb59cf283e6599ced3ab9a)?
[Note that it is also reverting [a prior commit](http://git.php.net/?p=php-src.git;a=commit;h=b8ffa3707c07e6edbe5db5a3fdf5516ba1f6bef0) intended to fix [the integer-specific instance of the failure](https://bugs.php.net/bug.php?id=76711).]

Disabling literal compaction [pass 11: `opcache.optimization_level=0x7FFFBBFF`] helped, but I figure if we're hitting it, and they've had several reports, others are. (Maybe related to #1022 as opcache is involved?) Also there's the obvious issue that it removes that optimization. 😅

[There is also a [nasty regexp infinite loop](https://bugs.php.net/bug.php?id=77193&edit=2) which did not quite make the cutoff for PHP 7.3.0.]

**Comment by oerdnj** [comment]
Pulled the two fixes and the packages are building now.  It would be interesting to see whether this fixed the Xdebug issue...
