### ISSUE TITLE
[FR]: Previous Release Repository

### ISSUE THREAD

**Issue by Reiner030** [oerdnj/deb.sury.org#1029]
To have a rollback possibility if latest release breaks important functionality like 7.2.12 has it with ftp_close within ssl connections (https://bugs.php.net/bug.php?id=77151).

As I remember from other packages the creation of multiple version repositories could be complex and initial time-consuming so that this is no practical task.
But since the content is relative it should be easy to add a simple step before rollout of latest version which moves the content from https://packages.sury.org/php to e.g. https://packages.sury.org/php-previous .

**Comment by oerdnj** [comment]
This is something you can do yourself.  I don't want to complicate my infrastructure even more.  Again, don't forget this is something I do in my free time.
