### ISSUE TITLE
PHP Bug 68532 reported as fixed as of 5.6.5 but 5.6.12 package still exhibits behavior.

### ISSUE THREAD

**Issue by mrubinsk** [oerdnj/deb.sury.org#103]
Bug with base64-encode stream filter in PHP (https://bugs.php.net/bug.php?id=68532) is resolved in PHP since 5.6.5. Verified fixed with https://3v4l.org/jr2Mi 

The following test code from the original bug report still fails with the PHP 5.6.12 package from the PPA:

echo phpversion() . "\r";
$testString = 'test';
$stream = fopen('php://memory','r+');
fwrite($stream, $testString);
rewind($stream);
$filter = stream_filter_append($stream, 'convert.base64-encode');
echo "memoryStream = " . stream_get_contents($stream).PHP_EOL;

$fileStream = fopen('/tmp/base64test.txt','w+');
fwrite($fileStream , $testString);

Results:

5.6.12-1+deb.sury.org~trusty+1
memoryStream = dGVz
fileStream = dGVzdA==

**Comment by oerdnj** [comment]
The fix for 68532 unfortunately broke Horde3 and other applications as it introduces BC imcompatible change: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778374, so this is a wontfix.

If you need the fixed behavior, use PHP 5.6 or 7.0 from ppa:ondrej/php that doesn't carry this patch.
