### ISSUE TITLE
Failed to fetch ppa source : 404 Not found

### ISSUE THREAD

**Issue by Chouette3000** [oerdnj/deb.sury.org#1032]
Hello Everybody

I followed the instructions to install php7 using ppa 
LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2

this works (correctly imported, no error reported)

but when I run : sudo apt-get update
I have the following error 
Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/maya/main/source/Sources  404  Not Found
Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/dists/maya/main/source/Sources  404  Not Found

Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/dists/maya/main/binary-amd64/Packages  404  Not Found

Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/dists/maya/main/binary-i386/Packages  404  Not Found

Are the ppa for php7 outdated ?

**Comment by oerdnj** [comment]
There’s no Ubuntu maya
