### ISSUE TITLE
Buster packages?

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1034]
Hi,

https://packages.sury.org/php/dists/buster/main/binary-amd64/ looks kinda empty.. are Buster packages not available yet?

**Comment by oerdnj** [comment]
I am reluctant to provide packages for Buster before transition freeze.

**Comment by oerdnj** [comment]
I added the buster to the series, but it will take a while to rebuild the whole archive. There’s unfortunatele drawback in using Jenkins that the full matrix has to be built every time there’s a change.

If anyone knows Jenkins good enough to help please contact me.

**Comment by EvilBMP** [comment]
Sorry for beeing annoying. But are there any news on this topic?

**Comment by OlafvdSpek** [comment]
https://packages.sury.org/php/dists/buster/main/binary-amd64/ isn't empty anymore..

**Comment by oerdnj** [comment]
It's not full either :-). But slowly getting there.  I had some build failures with tidy-html5

**Comment by oerdnj** [comment]
So, if anyone wants to help the ICU pkg-config patch needs to be backported to 5.6, 7.0 and 7.1 (the 7.2 patch would be a good start) while I am gone for a week.

**Comment by oerdnj** [comment]
PHP 7.1 has been patched to build with libicu in buster, so since that's cleared up, I issued a rebuild for all extensions: https://jenkins.rfc1925.org/view/PHP/

There will be no PHP 5.6 and 7.0 for buster.

Some of the extensions might fail to build at first because there are some dependencies between extensions that can't be expressed in a standard dpkg way - that will clear up when the extensions are bootstrapped for all available PHP versions.

**Comment by drsect0r** [comment]
@oerdnj Awesome work, as always! 👍 Do you think it would be possible to have a release for nginx-mainline of buster anytime soon?

**Comment by EvilBMP** [comment]
@oerdnj I have a little prolem to install php7.2 from the buster repo

`php7.2-fpm : Depends: libpcre3 (>= 2:8.41) but 2:8.39-11 is to be installed`

Any idea how to update the libpcre3 in buster? Or is the dependency wrong?

**Comment by oerdnj** [comment]
@evilBMP don’t hijack issues and fix your pinning.

**Comment by EvilBMP** [comment]
Well this issue was about buster packages. And I was already involved in the discussion. And I am not able to install the packages in buster... Shall I create a new issue?

**Comment by oerdnj** [comment]
Yes, create new issue and follow the template.
