### ISSUE TITLE
Nginx 1.15.8 released

### ISSUE THREAD

**Issue by S8Cloud** [oerdnj/deb.sury.org#1039]
http://nginx.org/en/CHANGES

**Comment by stamepicmorg** [comment]
@oerdnj 

> The following packages have unmet dependencies:
>  nginx-extras : Depends: libnginx-mod-http-perl (= 1.15.8-0.1+ubuntu18.10.1+deb.sury.org+1) but it is not going to be installed
>                 Depends: libnginx-mod-nchan (= 1.15.8-0.1+ubuntu18.10.1+deb.sury.org+1) but it is not going to be installed
> 

there are 1.15.**7** in your repositoy :(
