### ISSUE TITLE
[RFC][PHP] Add support for php5-uuid

### ISSUE THREAD

**Issue by lyrixx** [oerdnj/deb.sury.org#104]
Hello.

The pecl uuid for php [link](https://pecl.php.net/package/uuid) is quite common and useful. 
That's why we would love to see it in your ppa.

Do you think it's doable ?

**Comment by lyrixx** [comment]
ping @oerdnj

**Comment by oerdnj** [comment]
Uploaded to `ppa:ondrej/php` to support both PHP 5.6 and 7.0. I am sorry, but I won't be releasing the packaged extension for older packaging system as it would duplicate a lot of work.

**Comment by lyrixx** [comment]
I'm not sure tu understand your answer.

**Comment by oerdnj** [comment]
There's `ppa:ondrej/php` that has new packaging infrastructure that allow multiple version of PHP co-installation (right now there's PHP 5.6 and PHP 7.0). I have created package just for this new packaging infrastructure as it's not possible to have both at the same time. Thus `php-uuid` package will not be available neither from `ppa:ondrej/php5` nor `ppa:ondrej/php5-5.6` (as the PECL extensions are very easily built by running `apt-get install php5-dev <extension_deps> && cd <sourcedir> && phpize && ./configure && make && make install`).

**Comment by lyrixx** [comment]
ok. Got it. thanks.

Anyway, thanks a lot for your PPA. ;)
