### ISSUE TITLE
[Feature Request] Keep old package versions specifically for ppa:ondrej/nginx

### ISSUE THREAD

**Issue by raags** [oerdnj/deb.sury.org#1042]
Hello, we have automations that use the ppa:ondrej/nginx which fail when a new version of nginx is pushed in the repo. This is because we pin the nginx version to ensure stability and reliability. 

Would it be possible to not remove old versions when a new build is pushed? I'm not sure if this is a limitation of PPA or the build system.

**Comment by oerdnj** [comment]
Unfortunately, doesn’t have such feature. You can probably achieve something like this by keeping a local mirror.
