### ISSUE TITLE
short_open_tag = true

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1043]
Upstream's default is true.. could you follow upstream?

**Comment by todeveni** [comment]
`short_open_tag = Off` on all branches of PHP (5.6, 7.x) with `php.ini-production`

**Comment by oerdnj** [comment]
I am quite sure I changed this to match upstream several years ago.

**Comment by todeveni** [comment]
The default is `true`, if no `php.ini` is defined (and PHP isn't with compiled `--disable-short-tag`).

But upstream has used/recommended `short_open_tag = Off` since PHP 5.1 in supplied `php.ini-(development|production|recommended)` files - even though the default is true 🤷🏼‍♂️

**Comment by OlafvdSpek** [comment]
Right.. silly upstream.
