### ISSUE TITLE
php-phalcon v3.4.2

### ISSUE THREAD

**Issue by MichaelGooden** [oerdnj/deb.sury.org#1045]
Please can you build the latest version of Phalcon [v3.4.2](https://github.com/phalcon/cphalcon/releases/tag/v3.4.2) including now for PHP 7.3?

I have personally successfully built Phalcon v3.4.2 for PHP 7.3 on Bionic using your provided `php7.3-dev`.

**Comment by oerdnj** [comment]
Uploaded.
