### ISSUE TITLE
php-ds for PHP 7.3

### ISSUE THREAD

**Issue by aboks** [oerdnj/deb.sury.org#1046]
Would it be possible to release a version of `php-ds` that is (marked as) compatible with PHP 7.3? According to https://blog.remirepo.net/post/2018/07/02/PHP-extensions-status-with-upcoming-PHP-7.3 it should work as of version 1.2.6. Right now, the line
```
Depends: php-common (>= 1:7.0+33~), phpapi-20170718 | phpapi-20160303 | phpapi-20151012, libc6 (>= 2.14)
```
(which does not include `phpapi-20180731` provided by PHP 7.3) causes PHP 7.2 to be installed when installing `php-ds`.

**Comment by oerdnj** [comment]
Since you didn't really specify what distribution you are using, I rebuilt the packages for Debian. Hope it helps.

**Comment by aboks** [comment]
Thank you, works like a charm!
