### ISSUE TITLE
php-ssh2 for PHP 7.3

### ISSUE THREAD

**Issue by aboks** [oerdnj/deb.sury.org#1047]
Is it possible to release a version of `php-ssh2` that is suitable for use with PHP 7.3? Currently there is no released upstream version compatible with PHP 7.3. However, according to https://blog.remirepo.net/post/2018/07/02/PHP-extensions-status-with-upcoming-PHP-7.3 the current master should be compatible with 7.3, and IIRC the current (7.2-compatible) version of the `php-ssh2` package is not based off an 'official' release either.

**Comment by oerdnj** [comment]
Uploaded the patched version, it should built in couple of minutes.
