### ISSUE TITLE
PPA description says it uses openssl 1.0.2 but actually uses 1.1.1

### ISSUE THREAD

**Issue by Synchro** [oerdnj/deb.sury.org#1048]
I was looking for an nginx mainline build that supported openssl 1.1.1 and found [yours](https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline), but initially dismissed it because its description on launchpad says:

> This branch follows latest NGINX Mainline packages compiled against OpenSSL 1.0.2 for HTTP/2 support with ALPN.

Later I noticed that it's actually built against 1.1.1 and not 1.0.2 - please could you update the description?

**Comment by oerdnj** [comment]
Good catch, thanks.
