### ISSUE TITLE
Unmet dependencies: apache2-mpm-event

### ISSUE THREAD

**Issue by rrashkov** [oerdnj/deb.sury.org#105]
The following packages have unmet dependencies:
 apache2-mpm-event : Depends: apache2 (= 2.4.10-9ubuntu1.1) but 2.4.16-3+deb.sury.org~vivid+1 is to be installed

**Comment by oerdnj** [comment]
*-mpm-* were just transitional packages. You don't have to install them. 

Ondřej 

On August 21, 2015 6:27:05 AM GMT+02:00, rrashkov <notifications@github.com> wrote:
>The following packages have unmet dependencies:
>apache2-mpm-event : Depends: apache2 (= 2.4.10-9ubuntu1.1) but
>2.4.16-3+deb.sury.org~vivid+1 is to be installed
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/105

-- 
Ondřej Surý

**Comment by rrashkov** [comment]
Ah, ok, I was trying to boot up a VM from a ready made script and this is the place it dies.
Thank you very much for the answer.
