### ISSUE TITLE
Package `libssl 1.1` conflicts with some packages on GCE

### ISSUE THREAD

**Issue by ccclin** [oerdnj/deb.sury.org#1050]
Hi
I use this PHP repository on Google Cloud Engine(Google Cloud Platform service) with OS `debian-9-stretch-v20181210`.
We notice this repository will also install package `libssl 1.1`.
The problem is package `libssl 1.1` conflicts with those packages `google-compute-engine, python-boto, python-google-compute-engine, python3-boto, python3-google-compute-engine`.

Therefore, `google-compute-engine`, `python-boto`, `python-google-compute-engine`, `python3-boto`, `python3-google-compute-engine` will be remove after install `libssl 1.1`.
It will result in no longer being able to connect by SSH.

Can you please fix this conflict issue?

Many thanks,

**Comment by oerdnj** [comment]
Dup of #1041 and #1049.

It's the `libssl-dev` that conflicts with `python-boto`.  Unless you need phpX.Y-dev package installed, you can avoid the issue completely.

If you need phpX.Y-dev installed, you can pin `libssl-dev` to the version in stretch.

**Comment by ryanlai** [comment]
It's work! thanks.

**Comment by ccclin** [comment]
I got it, thanks boss.
