### ISSUE TITLE
latest libssl1.1 update breaks common python package dependencies

### ISSUE THREAD

**Issue by Reiner030** [oerdnj/deb.sury.org#1054]
Suddenly our Saltstack complains about missing boto function to setup DNS ... and it's caused by libssl1.1 update which disallows the common Debian Stretch package.

```
# aptitude install python-boto
The following NEW packages will be installed:
  python-boto
0 packages upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 741 kB of archives. After unpacking 5,263 kB will be used.
The following packages have unmet dependencies:
 libssl1.1 : Breaks: python-boto (< 2.44.0-1.1) but 2.44.0-1 is to be installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     python-boto [Not Installed]

Accept this solution? [Y/n/q/?] n
The following actions will resolve these dependencies:

     Downgrade the following packages:
1)     libssl-dev [1.1.1a-2~20181219073610.6+stretch (<NULL>, now) -> 1.1.0j-1~deb9u1 (stable)]
2)     libssl1.1 [1.1.1a-2~20181219073610.6+stretch (<NULL>, now) -> 1.1.0j-1~deb9u1 (stable)]
3)     openssl [1.1.1a-2~20181219073610.6+stretch (<NULL>, now) -> 1.1.0j-1~deb9u1 (stable)]
```

"Best" is: there is no newer package than 2.44.0-1.1 available in all versions:
https://packages.debian.org/search?keywords=python-boto&searchon=names&suite=all&section=all
and since python is "script" based there should be no reason to disallow versions?

```
# aptitude show libssl1.1
Package: libssl1.1
Version: 1.1.1a-2~20181219073610.6+stretch
State: installed
Automatically installed: no
Multi-Arch: same
Priority: optional
Section: libs
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 4,130 k
Depends: libc6 (>= 2.17), debconf (>= 0.5) | debconf-2.0
Breaks: isync (< 1.3.0-2), lighttpd (< 1.4.49-2), python-boto (< 2.44.0-1.1), python-httplib2 (< 0.11.3-1), python-imaplib2 (<
        2.57-5), python3-boto (< 2.44.0-1.1), python3-imaplib2 (< 2.57-5)
Description: Secure Sockets Layer toolkit - shared libraries
 This package is part of the OpenSSL project's implementation of the SSL and TLS cryptographic protocols for secure
 communication over the Internet.

 It provides the libssl and libcrypto shared libraries.
Homepage: https://www.openssl.org/
Tags: role::shared-lib
```
mmh, it's confusing that your compiled package show also "Debian OpenSSL Team" as maintainer but check shows clearly the ownership:
```
# apt-cache policy openssl
openssl:
  Installed: 1.1.1a-2~20181219073610.6+stretch
  Candidate: 1.1.1a-2~20181219073610.6+stretch
  Version table:
 *** 1.1.1a-2~20181219073610.6+stretch 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0j-1~deb9u1 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
     1.1.0f-3+deb9u2 500
        500 http://cdn-aws.deb.debian.org/debian stretch/main amd64 Packages
```

So normally you have to put such packages in a separate repository or have supported equivalents.
**It's clear that's your private time and such extra package compilations are not the task you are interested in (and not paid for).**

**But it would be very nice to have a reliable "stable compatible" repository.**
Additional there could be a "newest feature" repository where people know that using this repository could break their systems.

While writing this issue also issue #1037 came up.
I can only support this writer (and others with similar problems) of this issue that these update behaviour is very disappointing **even your PHP packages are very good and thanks for your compilations.**

Your package
* is breaking whole python / Debian (and I guess also Ubuntu) package system
* is automatically cleaned up from older versions.
  That was the reason I asked in #1029 to make a simple "mv repo archive" to have also the previous package version available to get back to a stable version.
* If you don't know about autocleaning check e.g. this configuration file:
```
# dpkg -S /etc/apt/apt.conf.d/01autoremove
apt: /etc/apt/apt.conf.d/01autoremove
```
Since your packages/paths are not in the "not autoremove" list the apt system autocleans older packages.

The main problem here for most of the users would be also the knowledge if all of your packages are needed to setup. 

**=> e.g. Can we use php x.x without using your libssl/openssl selfcompiled packages?**
* If so we could pin packages... 
  => it would be nice to have a small example configuration
  Actual I have this one but it's not sufficient to avoid this conflict:
```
/etc/apt/preferences.d/sury.pref:
Package: *php*
Pin: origin packages.sury.org
Pin-Priority: 940
```
* If not then we have to run broken systems to get your PHP version running... 
This is not the fine art to offer the packages in the way ```"It's sink or swim."```
 Not without writing it publically in front of the repository offer 😄

**Comment by oerdnj** [comment]
I uploaded fixed version of python-boto to the Debian stretch repository. Hope this resolves the problem.

**Comment by chrisboulton** [comment]
> I uploaded fixed version of python-boto to the Debian stretch repository. Hope this resolves the problem.

Thanks! Any chance of doing the same for the Wheezy repo?

**Comment by oerdnj** [comment]
What? You mean Jessie, I guess?

**Comment by chrisboulton** [comment]
Sorry - I'm having a morning.. 🤦‍♂️ I did indeed mean Jessie

**Comment by oerdnj** [comment]
Done, hopefully, this doesn't break anything.
