### ISSUE TITLE
ppa:ondrej/nginx doesn't provide package "openssl" for xenial (Ubuntu 16.04)

### ISSUE THREAD

**Issue by lindwurm** [oerdnj/deb.sury.org#1055]
* xenial: https://launchpad.net/~ondrej/+archive/ubuntu/nginx/+sourcepub/9666394/+listing-archive-extra
    - no `openssl_*.deb`
* bionic: https://launchpad.net/~ondrej/+archive/ubuntu/nginx/+sourcepub/9666395/+listing-archive-extra
    - `openssl_1.1.1a-2+ubuntu18.04.1+deb.sury.org+1_${arch}.deb ` here

log:

```sh
ubuntu@host:~⟫ sudo apt-cache policy openssl
openssl:
  Installed: 1.0.2g-1ubuntu4.14
  Candidate: 1.0.2g-1ubuntu4.14
  Version table:
 *** 1.0.2g-1ubuntu4.14 500
        500 http://jp.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4 500
        500 http://jp.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
ubuntu@host:~⟫
```

**Comment by oerdnj** [comment]
Yes, that’s correct, openssl package is provided only on systems that already had OpenSSL >= 1.1.0.

**Comment by lindwurm** [comment]
I understand.
