### ISSUE TITLE
PHP Update

### ISSUE THREAD

**Issue by S8Cloud** [oerdnj/deb.sury.org#1057]
PHP 7.3.1 along with PHP 7.2.14 (a security release)

**Comment by anamba** [comment]
7.1.26 (security+bugfix) and 5.6.40 (security) are also out now.

**Comment by dhpowrhost** [comment]
The same for php5.6.40 and php7.2.14

**Comment by MalikKrak** [comment]
Hi

php 7.3 is marked as "current stable release", please switch package "php" from 7.2 to 7.3.1, thank you

**Comment by oerdnj** [comment]
@MalikKrak please don’t hijack issues, thank you

The packages (except 7.0) has been updated.  It will take some time to cherry-pick security patches for PHP 7.0, so bear with me for a little while.
