### ISSUE TITLE
courier-base requires Dialog unless man files exist

### ISSUE THREAD

**Issue by colearendt** [oerdnj/deb.sury.org#1058]
Related to #208 ?

The failure is similar, and the solution I found is [here](https://askubuntu.com/questions/1054233/courier-base-fails-to-install-on-ubuntu-16-04-4-lts-base-install) (in a comment on the question)

Something strange is going on in Ubuntu Bionic (18.04) where it is impossible to install `courier-base` without an interactive session (i.e. fails in a scripted install b/c it cannot initialize the Dialog interface).

Hopeful that it is a bug somewhere, but it also seems unclear to me that this is the appropriate GitHub repository to report. Apologies if this is misplaced - wanted to report in case it helps someone else or gets the bug resolved.

```
# adding these lines allows courier-base to install noninteractively
touch /usr/share/man/man5/maildir.courier.5.gz
touch /usr/share/man/man8/deliverquota.courier.8.gz
touch /usr/share/man/man1/maildirmake.courier.1.gz
touch /usr/share/man/man7/maildirquota.courier.7.gz
touch /usr/share/man/man1/makedat.courier.1.gz
```

**Comment by oerdnj** [comment]
I no Langer maintain courier-imap, if there’s a bug, please report it directly to your distribution.
