### ISSUE TITLE
No openssl1.1.1a debian files for Ubuntu 16.03

### ISSUE THREAD

**Issue by evanskinner** [oerdnj/deb.sury.org#1060]
The only openssl .deb file at http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/o/openssl/ for Ubuntu 16.04 is still the openssl 1.0.1h version. Ubuntu 18.04 and 18.10 have the .deb file for openssl 1.1.1.a but not Ubuntu 16.04. Is it possible to build it for Ubuntu 16.04 please? If not then a newer version of openssl1.0.1 would be great as openssl 1.0.1j appears to be the latest.

**Comment by oerdnj** [comment]
Yes, only libraries are provided for distributions that are still on OpenSSL 1.1.0.  Too many things broke in the openssl command line utility.

**Comment by evanskinner** [comment]
Thanks for the quick answer.
