### ISSUE TITLE
Getting older PHP packages (archieve)

### ISSUE THREAD

**Issue by Talkless** [oerdnj/deb.sury.org#1061]
Hi,

First of all, thanks for your great job maintaining this repo!

Is there anywhere deb.sury.org PHP package archive that would allow to revert to older release - like installing 5.6.39 for example?

**Comment by oerdnj** [comment]
You can build the packages yourself using `git-buildpackage` from the git repository at https://salsa.debian.org/php-team/php/, it's all there.

**Comment by Talkless** [comment]
Good point, yeah. Thanks @oerdnj
