### ISSUE TITLE
php-amqp is outdated and missing build for 7.3

### ISSUE THREAD

**Issue by aleho** [oerdnj/deb.sury.org#1064]
The package `php-amqp` is missing a build for 7.3 (1.9.3 doesn't compile on Stretch for me).

I suggest updating to [1.9.4](https://pecl.php.net/package-changelog.php?package=amqp&release=1.9.4), which seems to build and run fine here.

Thanks!

```
/.
/etc
/etc/php
/etc/php/5.6
/etc/php/5.6/mods-available
/etc/php/5.6/mods-available/amqp.ini
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/amqp.ini
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/amqp.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/amqp.ini
/usr
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/amqp.so
/usr/lib/php/20151012
/usr/lib/php/20151012/amqp.so
/usr/lib/php/20160303
/usr/lib/php/20160303/amqp.so
/usr/lib/php/20170718
/usr/lib/php/20170718/amqp.so
/usr/share
/usr/share/doc
/usr/share/doc/php-amqp
/usr/share/doc/php-amqp/changelog.Debian.gz
/usr/share/doc/php-amqp/copyright
```

**Comment by oerdnj** [comment]
I actually had a patch to build amqp 1.9.3 for PHP 7.3, but perhaps I never triggered a rebuild for Debian?  It would really help if you at least specify the version of the affected package in the report.

Nevertheless, 1.9.4 has been uploaded and it's building right now.

**Comment by aleho** [comment]
Sorry! I thought
> 1.9.3 doesn't compile …

would be enough. Will do better next time.

Thanks for the fast response!
