### ISSUE TITLE
Upgrade apache2 to mod_http2 v1.12.1

### ISSUE THREAD

**Issue by felixbuenemann** [oerdnj/deb.sury.org#1065]
The currently bundled mod_http2 in apache2 2.4.37-1 does not properly handle HEAD requests over HTTP/2 when CGI is involved (eg. PHP-FPM via FastCGI).

The problem has been fixed in mod_http v1.12.1.

See icing/mod_h2#167 for details.

**Comment by oerdnj** [comment]
Apache 2.4.38-2 uploaded and it's building now.  Sorry for the delay.

**Comment by felixbuenemann** [comment]
@oerdnj Please  re-open.

The problem still exists on  Trusty with 2.4.38-2+ubuntu14.04.1+deb.sury.

The file size for `/usr/lib/apache2/modules/mod_http2.so` is identical between 2.4.38-1 and 2.4.38-2, so I think mod_http2 was not updated.

**Comment by felixbuenemann** [comment]
Oh, I think it's probably missing, because it has not yet been backported to apache 2.4.x branch, although it has been proposed.

The changes are in apache trunk [r1852339](https://svn.apache.org/viewvc?view=revision&revision=1852339) (https://github.com/apache/httpd/commit/620aedfd6132874afaf08ab10087772f431f2d97).

I'll update this issue, once the backport has landed in 2.4.x.

**Comment by felixbuenemann** [comment]
The fix is included in Apache 2.4.39.
