### ISSUE TITLE
Add php7.3-gmagick (debian/stretch) 

### ISSUE THREAD

**Issue by beavis** [oerdnj/deb.sury.org#1069]
**Is your feature request related to a problem? Please describe.**
php-gmagick package is missing 7.3 version

**Describe the solution you'd like**
Provide php7.3-gmagick in php-gmagick package

**Describe alternatives you've considered**
I guess gmagick 2.0.5RC1 can be installed from PECL in 7.3 but packages make life easier for upgrades

**Distribution:**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
```
php-gmagick:
  Installed: 2.0.5~rc1+1.1.7~rc3-2+0~20180910132509.4+stretch~1.gbpc10515
  Candidate: 2.0.5~rc1+1.1.7~rc3-2+0~20180910132509.4+stretch~1.gbpc10515
  Version table:
 *** 2.0.5~rc1+1.1.7~rc3-2+0~20180910132509.4+stretch~1.gbpc10515 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.4~rc1+1.1.7~rc3-1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
```

Thanks for your time

**Comment by oerdnj** [comment]
Done, I believe.
