### ISSUE TITLE
php-imagick, webp support

### ISSUE THREAD

**Issue by dominikzogg** [oerdnj/deb.sury.org#1071]
**Is your feature request related to a problem? Please describe.**
We would like to save webp with imagick instead of gd.

**Describe the solution you'd like**
Compile the webp support into imagick extension.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

```
apt-cache policy php-imagick
php-imagick:
  Installiert:           3.4.3-4+ubuntu18.04.1+deb.sury.org+1
  Installationskandidat: 3.4.3-4+ubuntu18.04.1+deb.sury.org+1
  Versionstabelle:
 *** 3.4.3-4+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.3~rc2-2ubuntu4 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by mpesari** [comment]
AFAIK WebP support is not related to the php-imagick extension. See https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1117481 for workarounds.

We rebuilt the imagemagick packages with libwebp-dev installed and it works fine with the sury repo.

**Comment by dominikzogg** [comment]
@mpesari would be cool if it would be already build with libwebp-dev installed within the repo

**Comment by oerdnj** [comment]
ImageMagick is undermaintained in Debian and I don't have enough resources to help with ImageMagick packaging, it's too complex to have it as a side-project, so I am just closing this issue. Once ImageMagick 7 is packaged, I might backport it, but I am not going to do the packaging myself.
