### ISSUE TITLE
PHP 7.3 module support for gearman, solr, http, raphf, propro

### ISSUE THREAD

**Issue by arkadicolson** [oerdnj/deb.sury.org#1073]
**Is your feature request related to a problem? Please describe.**
The packages for modules gearman, raphf, http, solr and propro are not build for php7.3

**Describe the solution you'd like**
Is it possible to build following packages for php 7.3
php-gearman
php-solr
php-raphf
php-http
php-propro

**Describe alternatives you've considered**
none

**Distribution (please complete the following information):**
 - OS: Debian stretch and jessie
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php-gearman:
  Installed: (none)
  Candidate: 2.0.5+1.1.2-2+0~20180910132507.6+stretch~1.gbp164588
  Version table:
     2.0.5+1.1.2-2+0~20180910132507.6+stretch~1.gbp164588 600
php-solr:
  Installed: (none)
  Candidate: 2.4.0-6+0~20180910140729.3+stretch~1.gbp378cce
  Version table:
     2.4.0-6+0~20180910140729.3+stretch~1.gbp378cce 600
php-raphf:
  Installed: (none)
  Candidate: 2.0.0+1.1.2-3+0~20180910132753.3+stretch~1.gbpa4be3e
  Version table:
     2.0.0+1.1.2-3+0~20180910132753.3+stretch~1.gbpa4be3e 600
php-http:
  Installed: (none)
  Candidate: 3.2.0+2.6.0-1+0~20180928073709.3+stretch~1.gbp68dd0d
  Version table:
     3.2.0+2.6.0-1+0~20180928073709.3+stretch~1.gbp68dd0d 600
php-propro:
  Installed: (none)
  Candidate: 2.1.0+1.0.2-1+0~20180910132751.3+stretch~1.gbpb51adb
  Version table:
     2.1.0+1.0.2-1+0~20180910132751.3+stretch~1.gbpb51adb 600

**Additional context**
No additional info

**Comment by TCB13** [comment]
Related https://github.com/oerdnj/deb.sury.org/issues/1063

**Comment by TCB13** [comment]
@oerdnj thanks for the update.

**Comment by oerdnj** [comment]
PHP 7.1 has been patched to build with libicu in buster, so since that's cleared up, I issued a rebuild for all extensions: https://jenkins.rfc1925.org/view/PHP/

The queue is quite long and I found that it's safer to have only one build at time due arm* qemu builds failing quite often when the machine is overloaded.
