### ISSUE TITLE
How can I rebuild PHP 7.3 package with zts support ?

### ISSUE THREAD

**Issue by scramatte** [oerdnj/deb.sury.org#1074]
Hi,

Anybody know how can I rebuild PHP 7.3 package with zts support ?
I need to enable pthreads  and ZTS is requirement.

Into debian/rules files   it looks that  DEB_SOURCE variable must ends with -zts
But I have no idea about where and how  I can set DEB_SOURCE ...

Regards

**Comment by oerdnj** [comment]
There was some preliminary work - rename the source package to phpX.Y-zts in debian/control and debian/changelog and run “debian/rules debian/control”. That should serve at least as a preliminary base for the zts packages, but most probably it’s broken as of this moment.

**Comment by scramatte** [comment]
Hello,

I've tried to achieve the same thing with PHP 8.1 but I got an issue.
It's look that parameters to enable zts on php 8.x are different from 7.x

Can you give me an hand?

Regards
