### ISSUE TITLE
php7.3-intl: undefined symbol: spoofchecker_register_constants

### ISSUE THREAD

**Issue by briellie** [oerdnj/deb.sury.org#1075]
**Describe the bug**
PHP Warning when attempting to load intl.so from php7.3-intl.

PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (/usr/lib/php/20180731/intl.so: undefined symbol: spoofchecker_register_constants), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**To Reproduce**
1) Install php7.3-intl package

**Expected behavior**
No warning or error loading intl.so

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php7.3-intl:
  Installed: 7.3.1-2+0~20190204160533.27+stretch~1.gbp1b9ae6
  Candidate: 7.3.1-2+0~20190204160533.27+stretch~1.gbp1b9ae6
  Version table:
 *** 7.3.1-2+0~20190204160533.27+stretch~1.gbp1b9ae6 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status

**Additional context**
Possibly same issue as here:
https://bugs.launchpad.net/ubuntu/+source/php7.3/+bug/1813438

Thank you!

**Comment by rseffner** [comment]
Same here with Debian jessie packages.

**Comment by oerdnj** [comment]
I can reproduce the issue, I'll look into it.  The way how icu libraries are detected has changed from icu-config to plain pkg-config, so there might be an issue in detecting the available feature set.

**Comment by fodger** [comment]
Hi,
Same on debian stretch 9.7.

ICU version : 57.1.

**Comment by do-web** [comment]
maybe this helps:

https://github.com/php/php-
src/commit/20fa2e7b58c519cc148d9658456b695884b1ecf4

**Comment by oerdnj** [comment]
That's exactly the commit that broke the build when backported.

**Comment by oerdnj** [comment]
The build is slow because of the arm* in QEMU takes a time: https://jenkins.rfc1925.org/view/PHP/job/php_php7.3-binaries/30/

**Comment by MalikKrak** [comment]
Apt offered me the new update 20190205120933 for my php packages after the problematic one 20190204160533, and the issue is gone.

**Comment by oerdnj** [comment]
Only armhf Debian stretch doesn't build right now, but it seems like problem directly in Debian.  I'll probably look into the issue when I have more time.

**Comment by nikic** [comment]
Just to check, is there anything that needs to be fixed in php-src with regard to the mentioned commit?
