### ISSUE TITLE
Apache 2.4.37

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1077]
Hi there,

currently there is a bug with Apache 2.4.37 & OpenSSL 1.1.1 -> https://bz.apache.org/bugzilla/show_bug.cgi?id=63052

Are there any chances to compile the new Apache 2.4.38 webserver for the PPA packages?

Best regards,
Mathias

**Comment by daniejstriata** [comment]
Following

**Comment by Ayesh** [comment]
Duplicate of #1068.

**Comment by oerdnj** [comment]
Apache 2.4.38-2 uploaded and it's building now.  Sorry for the delay.
