### ISSUE TITLE
Upgraded php-7.2 on stretch, errors with libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed

### ISSUE THREAD

**Issue by bstin** [oerdnj/deb.sury.org#1079]
**Describe the bug**

Upgraded my server (apt update; apt ugprade), but the install has failed and now apache / php won't start. 

The error is that libpcre3 installed version is different than what php=7.2 depends on. But there seems to be no way to install the newer version 

**To Reproduce**
1. apt update
2. apt upgrade newest 7.2

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org/php/

**Package(s) (please complete the following information):**
Output of `apt-cache policy php7.2` works best.

apt-cache policy php7.2
php7.2:
  Installed: (none)
  Candidate: 7.2.14-1+0~20190205200805.15+stretch~1.gbpd83c69
  Version table:
     7.2.14-1+0~20190205200805.15+stretch~1.gbpd83c69 500
        500 https://packages.sury.org/php stretch/main amd64 Packages

**Additional context**

**Comment by oerdnj** [comment]
There's not a single error message in the bug report you just send.

Output of `apt-cache policy libpcre3 libpcre3v5` might be helpful.

**Comment by bstin** [comment]
apt-cache policy libpcre3 libpcre3v5
libpcre3:
  Installed: 2:8.39-3
  Candidate: 2:8.39-3
  Version table:
     2:8.42-1+0~20190203125157.5+stretch~1.gbp79d75d 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
 *** 2:8.39-3 900
        900 http://mirror.steadfast.net/debian stable/main amd64 Packages
        900 http://ftp.us.debian.org/debian stable/main amd64 Packages
        100 /var/lib/dpkg/status
N: Unable to locate package libpcre3v5

**Comment by oerdnj** [comment]
Fix your pinning.

**Comment by bstin** [comment]
Thank you

**Comment by Adambean** [comment]
> Fix your pinning.

I did this with `apt-get install libpcre3=2:8.42-1+0~20190203125157.5+stretch~1.gbp79d75d` (for anyone searching) but the FPM service refuses to start.

**Comment by Adambean** [comment]
FYI I also recently had issues with packages "libzip4" and "libpcre2-8-0" conflicting on Debian Stretch. To resolve this I did the following:

```
apt-get install libzip4=1.5.1-4+0~20190318173229.9+stretch~1.gbp333132
apt-get install libpcre2-8-0=10.32-4+0~20190202200700.3+stretch~1.gbpd4ef41
```

You can of course combine these 3 issues into 1 line:

```
apt-get install libpcre2-8-0=10.32-4+0~20190202200700.3+stretch~1.gbpd4ef41 libpcre3=2:8.42-1+0~20190203125157.5+stretch~1.gbp79d75d libzip4=1.5.1-4+0~20190318173229.9+stretch~1.gbp333132
```

**Comment by Adambean** [comment]
Found another cause of this...

On some of my Stretch VMs I had (badly) reverted the addition of some Buster packages. To do this I set the "stable" repository to priority 1001 in file `/etc/apt/preferences`, which means that packages from Stretch took priority over Sury.

As this was the only change I had made to repository priorities I simply removed file `/etc/apt/preferences`, then all was well.
