### ISSUE TITLE
Missing mbstring extension

### ISSUE THREAD

**Issue by JanJakes** [oerdnj/deb.sury.org#108]
We're using PHP 5.6 with Ubuntu 14.04 LTS but it seems the package comes without `mbstring` extension that is used by many frameworks. I also couldn't find `php5-mbstring` package. Is it so that there's no way to have mbstring with PHP 5.6?

Thanks,
Jan

**Comment by oerdnj** [comment]
I am quite sure that mbstring is compiled in and the buildlog agrees with me:
https://launchpadlibrarian.net/214616882/buildlog_ubuntu-trusty-amd64.php5_5.6.12%2Bdfsg-1%2Bdeb.sury.org~trusty%2B1_BUILDING.txt.gz

How do you know that mbstring is not there?

**Comment by JanJakes** [comment]
Oh, my bad! One of my Docker images was installed directly from the official PHP image and not your PPA (and by default `mbstring` is apparently not there). Thanks and sorry for your time!
