### ISSUE TITLE
strftime not using timezone in 7.3.2

### ISSUE THREAD

**Issue by jflambert** [oerdnj/deb.sury.org#1084]
**Describe the bug**
strftime no longer using timezone as of 7.3.2. [Logged a bug](https://bugs.php.net/bug.php?id=77582) on php.net but it's clear it's an issue on this build, not pure source.

**To Reproduce**
php -a
Interactive mode enabled

php > var_dump(ini_get('date.timezone'));
php shell code:1:
string(16) "America/New_York"
php > echo strftime('%F %T %z');
2019-02-07 22:24:27 +0000
php > echo strftime('%Z');
GMT

**Expected behavior**
EST instead of GMT

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Architecture: amd64
 - Repository: deb.sury.org

**Package(s) (please complete the following information):**
PHP 7.3.2-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  7 2019 18:01:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0rc1, Copyright (c) 2002-2019, by Derick Rethans

**Additional context**
[Works perfectly on 7.3.1. Updated to 7.3.2 and started failing.](https://pastebin.com/2bNcXGHa)

**Comment by oerdnj** [comment]
7.3.2-3 will have the update systzdata patch to fix the issue.  Thanks for the report.

**Comment by oerdnj** [comment]
Uploaded, could you confirm that helped when it builds and close the issue? Thanks.

**Comment by hebbet** [comment]
> Uploaded, could you confirm that helped when it builds and close the issue? Thanks.

yes it is working again with 7.3.2-3 running on ubuntu 16.04

**Comment by jflambert** [comment]
Looking good! Thanks for the fast fix @oerdnj !!!
