### ISSUE TITLE
Broken dependency: libapache2-mod-php7.2:  Depends: apache2-api-20120211

### ISSUE THREAD

**Issue by elpraga** [oerdnj/deb.sury.org#1086]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by derritter88** [comment]
+1
