### ISSUE TITLE
Upgrade to Apache 2.4.38

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1087]
Since upgrading to Apache 2.4.38 it is no longer working as some libaries are having issues:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libapache2-mod-php7.3 : Hängt ab von: apache2-api-20120211
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

Translated this means that libapache2-mod-php7.3 depends on apache2-api-20120211
E: Problems cannot be fixed.

**Comment by derritter88** [comment]
In addition to my bug report and for clarification:
apt show libapache2-mod-php7.2
shows the dependencies of the project.

For libapache2-mod-php7.2 would be: Depends: libmagic1, libpcre3 (>= 2:8.41), mime-support, php7.2-cli, php7.2-common (= 7.2.15-1+ubuntu16.04.1+deb.sury.org+1), php7.2-json, php7.2-opcache, tzdata, ucf, **apache2-api-20120211,** apache2-bin, libargon2.0), libxml2 (>= 2.8.0), zlib1g (>= 1:1.1.4)

and this seems to be missing in the newly build apache2-bin package.

**Comment by m-ueberall** [comment]
I saw similar errors (on Ubuntu 16.04.5 aka Xenial Xerus):
```
root@host:/tmp# LANG=C apt install apache2 apache2-bin apache2-data apache2-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libyajl2 modsecurity-crs
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom
The following packages will be REMOVED:
  libapache2-mod-fcgid libapache2-mod-qos libapache2-mod-security2 libapache2-mod-wsgi-py3
The following packages will be upgraded:
  apache2 apache2-bin apache2-data apache2-utils
4 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
Need to get 1685 kB of archives.
After this operation, 2636 kB disk space will be freed.
Do you want to continue? [Y/n] N
Abort.
root@host:/tmp# dpkg --list libapache2-mod-fcgid libapache2-mod-qos libapache2-mod-security2 libapache2-mod-wsgi-py3 | grep ^ii
ii  libapache2-mod-fcgid     1:2.3.9-1                            amd64        FastCGI interface module for Apache 2
ii  libapache2-mod-qos       11.21-1                              amd64        quality of service module for the apache2
ii  libapache2-mod-security2 2.9.2-1+ubuntu16.04.1+deb.sury.org+2 amd64        Tighten web applications security for Apache
ii  libapache2-mod-wsgi-py3  4.5.2-1+deb.sury.org~xenial+1        amd64        Python 3 WSGI adapter module for Apache
```

On another host, the following packages are affected:
```root@host:/tmp# dpkg --list libapache2-mod-fastcgi libapache2-mod-fcgid libapache2-mod-php7.2 | grep ^ii
ii  libapache2-mod-fastcgi 2.4.7~0910052141-1.2                  amd64        Apache 2 FastCGI module for long-running CGI scripts
ii  libapache2-mod-fcgid   1:2.3.9-1                             amd64        FastCGI interface module for Apache 2
ii  libapache2-mod-php7.2  7.2.15-1+ubuntu16.04.1+deb.sury.org+1 amd64        server-side, HTML-embedded scripting language (Apache 2 module)
```

This means a large number of modules need to be rebuilt--maybe some of the above modules without a "deb.sury.org" could be included in the repository as well?

**Comment by oerdnj** [comment]
The issue template I prepared is there not for fun, but to actually have the information needed to fix the bugs in the packages.
