### ISSUE TITLE
Apache 2.4.38 - apache2-api-20120211 is missing at apache2-bin

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1088]
**Describe the bug**

**To Reproduce**
1. Go to 'current version of Ubuntu 16.04 and install the actual apache2 package'
2. Enter 'apt install libapache2-mod-php7.2'
3. See error:

root@wwwubuntu:/home/user# apt install libapache2-mod-php7.2
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libapache2-mod-php7.2 : Hängt ab von: apache2-api-20120211
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

The problem comes from "apache2-api-20120211" which should be included in "apache2-bin" -> apache2-bin/xenial,now 2.4.38-2+ubuntu16.04.1+deb.sury.org+1 amd64

**Expected behavior**
Package gets installed and can be used with apache2 2.4.38

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: deb.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

Currently my "standard" apache2 packages does not work - I have selecte the package where the issues comes from -> apache2-bin & one example package -> libapache2-mod-fastcgi

apache2-bin:
  Installiert:           2.4.38-2+ubuntu16.04.1+deb.sury.org+1
  Installationskandidat: 2.4.38-2+ubuntu16.04.1+deb.sury.org+1
  Versionstabelle:
 *** 2.4.38-2+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.18-2ubuntu3.9 500
        500 http://at.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     2.4.18-2ubuntu3.8 500
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.4.18-2ubuntu3 500
        500 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

libapache2-mod-fastcgi:
  Installiert:           (keine)
  Installationskandidat: 2.4.7~0910052141-1.2
  Versionstabelle:
     2.4.7~0910052141-1.2 500
        500 http://at.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
        100 /var/lib/dpkg/status

**Additional context**
It seems when building apache2-bin it was forgot to add "apache2-api-20120211" to the apache2-bin package.

Now most of the apache2-mods do not work as they all need the apache2-api.

>_apt show libapache2-mod-fastcgi_
Package: libapache2-mod-php7.2
Version: 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
Priority: optional
Section: httpd
Source: php7.2
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 4.773 kB
Provides: libapache2-mod-php, phpapi-20170718
Depends: libmagic1, libpcre3 (>= 2:8.41), mime-support, php7.2-cli, php7.2-common (= 7.2.15-1+ubuntu16.04.1+deb.sury.org+1), php7.2-json, php7.2-opcache, tzdata, ucf, **apache2-api-20120211,** apache2-bin, libargon2-0 (>= 0~20160406~), libc6 (>= 2.15), libsodium23 (>= 1.0.14), libssl1.1 (>= 1.1.0), libxml2 (>= 2.8.0), zlib1g (>= 1:1.1.4)

**Comment by oerdnj** [comment]
Much better, thanks.

It seems like a glitch in Xenial dpkg - because clearly the `apache2-api-20120211` is correctly added in Trusty and Bionic, and the script that's responsible for creating the variables can be seen in the build.log.

It also happens only for amd64 build, the i386 build has the variables.

**Comment by derritter88** [comment]
No problem & sorry that I have ignored your "bug-receipt" in the 1st time.

What I have tried so far: reinstalled apache2 & apache2-bin + removed it and installed it again. Both approaches did not work for me.

**Comment by oerdnj** [comment]
There’s definitely bug in dpkg and friends, but I have no idea yet what triggers it.

**Comment by derritter88** [comment]
hmmm another interessting thing - not sure it this is useful for you:
when entering _apt show apache2-bin -a_ I can see the different versions of apache2-bin:

Package: apache2-bin
Version: 2.4.38-2+ubuntu16.04.1+deb.sury.org+1
Priority: optional
Section: httpd
Source: apache2
Maintainer: Debian Apache Maintainers <debian-apache@lists.debian.org>
Installed-Size: 4.424 kB
Depends: perl, libapr1 (>= 1.6.2), libaprutil1 (>= 1.6.0), libaprutil1-dbd-sqlite3 | libaprutil1-dbd-mysql | libaprutil1-dbd-odbc | libaprutil1-dbd-pgsql | libaprutil1-dbd-freetds, libaprutil1-ldap, libbrotli1 (>= 0.6.0), libc6 (>= 2.14), libcurl3 (>= 7.16.2), libjansson4 (>= 2.4), libldap-2.4-2 (>= 2.4.7), liblua5.2-0, libnghttp2-14 (>= 1.15.0), libpcre3, libssl1.1 (>= 1.1.1), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4)
Suggests: apache2-doc, apache2-suexec-pristine | apache2-suexec-custom, www-browser
Breaks: gridsite (<< 3.0.0~20170225gitd51b2fd-1~), libapache2-mod-dacs (<= 1.4.38a-2), libapache2-mod-proxy-uwsgi (<< 2.4.33)
Replaces: libapache2-mod-proxy-uwsgi (<< 2.4.33)
Download-Size: 1.210 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages
Description: Apache HTTP Server (modules and other binary files)
 The Apache HTTP Server Project's goal is to build a secure, efficient and
 extensible HTTP server as standards-compliant open source software. The
 result has long been the number one web server on the Internet.
 .
 This package contains the binaries only and does not set up a working
 web-server instance. Install the "apache2" package to get a fully working
 instance.

Package: apache2-bin
Version: 2.4.18-2ubuntu3.9
Priority: optional
Section: httpd
Source: apache2
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Apache Maintainers <debian-apache@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3.688 kB
**Provides: apache2-api-20120211**
Depends: libapr1 (>= 1.5.0), libaprutil1 (>= 1.5.0), libaprutil1-dbd-sqlite3 | libaprutil1-dbd-mysql | libaprutil1-dbd-odbc | libaprutil1-dbd-pgsql | libaprutil1-dbd-freetds, libaprutil1-ldap, libc6 (>= 2.14), libldap-2.4-2 (>= 2.4.7), liblua5.1-0, libpcre3, libssl1.0.0 (>= 1.0.2~beta3), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4), perl


The "**Provides: apache2-api-20120211**" line is also mentioned for the other official Ubuntu packages. But it is missing at yours.
Maybe this is were the error occurs?

**Comment by derritter88** [comment]
I have downloaded the Apache 2.4.37 .deb files - _apt show apache2-bin -a_ shows also 
Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1

**Comment by m-ueberall** [comment]
@oerdnj: For the record, upgrading ``dpkg``, ``debhelper``, and ``dh-autoreconf`` to the versions used in Bionic (by building/installing them along with their dependencies in a Xenial container) before tackling ``apache2`` produces an ``apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_amd64.deb`` archive which does contain the ``Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1`` line.  Hardcoding this for the time being would seem easier, though.

According to the dpkg changelog, deb-substvars related code has been added after the original dpkg package for Xenial had been published, but this does not explain why i386/Trusty builds worked (I did not track backported code, however).

_(I originally feared that ``apache2-api-20120211`` was_ supposed _to be removed in order to trigger a recompilation of_ all apache2 _modules, but looking at Debian Sid and the associated messages, this is luckily not the case.)_

**Comment by oerdnj** [comment]
What I don't really understand is that it's broken only on amd64:
```
apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_amd64.deb
apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_arm64.deb
 Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1
apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_armhf.deb
 Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1
apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_i386.deb
 Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1
apache2-bin_2.4.38-2+ubuntu16.04.1+deb.sury.org+6_ppc64el.deb
 Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1
```

**Comment by oerdnj** [comment]
Ok, so it’s a definitely bug in dpkg (and friends) - the generated apache2-bin.substvars file gets overwritten by other stuff when arch independent packages are built.

It’s possible that the bug is there for a long time, but previously the arch-indep packages were built on i386, so nobody has notice that because nobody uses i386 nowadays.

**Comment by PascalZajac** [comment]
I've also encountered this issue on a production server that updated this morning. I can't find a link to the 2.4.37 DEBs to reinstall that version in the meantime, can someone point me to them?

**Comment by PascalZajac** [comment]
I answered my own question eventually: https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+build/15580679

**Comment by oerdnj** [comment]
I think I found it, the original debian/rules had the binary-arch binary-indep and other targets declared as PHONY and it messed up debhelper ability to track progress.

The +6.3 version has correct provides both in i386 and amd64 builds.

**Comment by derritter88** [comment]
apache2-bin contains now 'Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1' - so the newest version works together with other Apache2 modules.

**Comment by werk21** [comment]
Once again for 16.04 on 2.4.41-1+ubuntu16.04
Can you please fix it?
thx ky.
