### ISSUE TITLE
Document how to build deb.sury.org style packages

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1092]
**Is your feature request related to a problem? Please describe.**

Hi, sorry to bring this conversation to a third place, but it seems like an issue is a more appropriate way to pursue it. 

You've decided to remove php 5.6 and 7.0 from your repos in April; that's a reasonable thing to do. 

However, there are other users who need older PHP for various things (and things that are not necessarily impacted by security concerns). I work on [ddev](https://github.com/drud/ddev), a PHP local development environment. In the development world, there are always sites that have been neglected and are dependent on an old version of PHP. And development environments end up having to (or wanting to) support them. So ddev would like to continue support of PHP 5.6 and 7.0. This is a non-security-sensitive situation, local development only. Functionality matters, security patches don't.

**Describe the solution you'd like**

We'd love to just be able to build older PHP packages that end up working with the Sury organization style (multiple PHPs on one box, etc). If there is documentation on how to do that, that's mostly what's needed. If there's not documentation yet, I'd be happy to help with it, but of course need coaching on the methodology.

**Describe alternatives you've considered**

* Convincing you to continue with 5.6 and 7.0 (knowing no security coverage) Failed :(

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

php5.6
php7.0

If I figure out how to build 5.4 and 5.3 it will make some random people happy over the long term.

**Additional context**

Related issue in ddev repo: https://github.com/drud/ddev/issues/1448
Related issue in drud/hosting: https://github.com/drud/hosting/issues/986
Twitter conversation: https://twitter.com/randyfay/status/1094957723739799552
Patreon conversation: https://www.patreon.com/posts/ubuntu-14-04-php-22093917

**Comment by rfay** [comment]
Hoping that there's a way to go forward on this. It will probably help ongoing PHP versions as well.

**Comment by OlafvdSpek** [comment]
>  In the development world, there are always sites that have been neglected and are dependent on an old version of PHP.

What do you mean by `sites`? If websites, why wouldn't security matter?

**Comment by oerdnj** [comment]
So, the packaging is pretty standard using [git-buildpackage](https://wiki.debian.org/PackagingWithGit) and the Debian git repositories are kept inside the [php-team](https://salsa.debian.org/php-team/) at salsa.debian.org:

* [php](https://salsa.debian.org/php-team/)
* [php-defaults](https://salsa.debian.org/php-team/php-defaults/)
* Every PECL extension has own repository under [pecl](https://salsa.debian.org/php-team/pecl/) subgroup at salsa.

I use some extra scripts located in the [packaging-tools](https://salsa.debian.org/ondrej/packaging-tools) repository - they are mostly for the Ubuntu PPA.

For Debian DPA, I use excellent [jenkins-debian-glue](https://jenkins-debian-glue.org/) with [jenkins-job-builder](https://docs.openstack.org/infra/jenkins-job-builder/).  The jenkins-job-builder configuration is mostly in this repository: https://github.com/pkg-php/jenkins-job-builder

A little bit local configuration:
```
root@howl:~# cat /etc/jenkins/debian_glue | grep -Ev '^(#|$)'
KEY_ID=DF3D585DB8F0EB658690A554AC0E47584A7A714D
PBUILDER_CONFIG=/etc/jenkins/pbuilderrc
REMOVE_FROM_RELEASE=false
ADT='skip'
USE_EATMYDATA=true
USE_CCACHE=true
DEBEMAIL="Ondřej Surý <ondrej@sury.org>"
```

and

```
root@howl:~# cat /etc/jenkins/pbuilderrc | grep -Ev '^(#|$)'
MIRRORSITE=http://deb.debian.org/debian
PBUILDERSATISFYDEPENDSCMD="/usr/lib/pbuilder/pbuilder-satisfydepends-classic"
```

**Comment by oerdnj** [comment]
I understand it's not exactly turnkey project, but every component is out there and it can be built fairly quickly if you know what you are doing.

**Comment by rfay** [comment]
Thanks so much for taking the time to do that.

Don't I remember that you introduced the excellent ability to use `phpX.Y-<extension>` long ago, where the traditional packages assumed exactly one php version on a machine?  Is that accounted for in your instructions?

**Comment by oerdnj** [comment]
Look at the difference between `master` and `master-coinst` branch in the `php-defaults` git repository.  The main Debian package (just PHP 7.3) is built from `master` branch while the PPA/DPA uses `master-coinst`.

**Comment by rfay** [comment]
Thanks!

**Comment by maethor** [comment]
What about "non versionned packages" (I don't know how to call them), like `php-redis` or `php-memcached`, packages that provides extensions for all the versions provided by Sury? Can you explain why you didn't split theses packages into `phpX.Y-<extension>` packages?

Thanks.

**Comment by oerdnj** [comment]
That's outside the scope of this ticket and it has been explained several times in the closed tickets.

**Comment by oerdnj** [comment]
Feel free to ping me if you get seriously stuck and you are unable to unstuck yourself for some time. The Slack might be viable alternative to get answers quickly (when I am actually online and have time).

**Comment by oerdnj** [comment]
And of course, it would be appreciated if somebody would turn this into wiki page here...

**Comment by rfay** [comment]
Thanks, yeah, looks like a major project. Our short-term technique will be to download the deb files and tar them up and install them that way. But would love to pursue this longer term.

**Comment by oerdnj** [comment]
There’s rsync available at howl.rfc1925.org (or packages.sury.xyz)

**Comment by rfay** [comment]
A note to those who might land on this issue: For *now*, @oerdnj has relented and php5.6 and 7.0 will remain in the deb.sury.org repos. The ongoing support is uncertain of course, and dependent on upstream work, see https://www.patreon.com/posts/php-5-6-and-php-25226448?utm_medium=social&utm_source=twitter&utm_campaign=postshare . Nobody should be continuing to use the obsolete versions.
