### ISSUE TITLE
Ubuntu 16.04 and apache2-dev

### ISSUE THREAD

**Issue by RamCZ** [oerdnj/deb.sury.org#1094]
Hello.

i am using your PPAs:
deb http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial main
deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main

on Ubuntu 16.04.5 LTS
with i-MSCP (1.5.3) i got this errors:

"The following packages have unmet dependencies:
 apache2-dev : Depends: debhelper (>= 10) but 9.20160115ubuntu3 is to be installed"

and instaled apache package is:
"apache2:amd64/xenial 2.4.38-2+ubuntu16.04.1+deb.sury.org+6.3 uptodate
apache2:i386 not installed"

Thank you.

**Comment by oerdnj** [comment]
xenial-backports has debhelper >= 10
