### ISSUE TITLE
Debian 9.8 Stretch - PHP 7.1 - Broken after upgrade

### ISSUE THREAD

**Issue by ufoonline** [oerdnj/deb.sury.org#1096]
Hello,

I just update my server and it has broken the installation of PHP7.1, it just removed some packages and when I try to install them again it says:
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-cgi : Depends: libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed
 php7.1-cli : Depends: libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed
 php7.1-fpm : Depends: libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed
E: Unable to correct problems, you have held broken packages.

For solve the problem I had to install libpcre 2.8.42 from deb.sury.org with follow command:
apt-get install libpcre3=2:8.42-1+0~20190203125157.5+stretch~1.gbp79d75d  

And then installed again the php7.1* needed packages.

Regards

**Comment by oerdnj** [comment]
Yes, you described it accurately, you also need to install dependencies.
