### ISSUE TITLE
Ubuntu/ISPConfig3 warning

### ISSUE THREAD

**Issue by bestinspain** [oerdnj/deb.sury.org#1097]

**Comment by bestinspain** [comment]
Hi
Just installed a new server with 18.04 ubuntu and ispconfig3.
During the course of that, as I want php7.2 and php5.6, I added in packages from your repository as listed in your tutorial.
All seems to be fine (havent actually tested the multiple php versions yet) but ubuntu shell is reporting all packages up to date, however, ispconfig is giving me a warning as follows:
That these packages need updating....
Inst libssl-doc [1.1.0g-2ubuntu4.3] (1.1.1a-2+ubuntu18.04.1+deb.sury.org+1 PPA for Apache 2.x:18.04/bionic [all])
Inst openssl [1.1.0g-2ubuntu4.3] (1.1.1a-2+ubuntu18.04.1+deb.sury.org+1 PPA for Apache 2.x:18.04/bionic [amd64])
Conf libssl-doc (1.1.1a-2+ubuntu18.04.1+deb.sury.org+1 PPA for Apache 2.x:18.04/bionic [all])
Conf openssl (1.1.1a-2+ubuntu18.04.1+deb.sury.org+1 PPA for Apache 2.x:18.04/bionic [amd64])

Could you point me in the right direction to eliminate the problem do you think ?

Cheers

**Comment by oerdnj** [comment]
And what exactly is the problem?
