### ISSUE TITLE
apt-update error due to certificate verification failure

### ISSUE THREAD

**Issue by vansart1** [oerdnj/deb.sury.org#1098]
I followed the steps on here to install the repo on a new debian 9 installation: https://cdn.sury.org/php/README.txt

But running `sudo apt-get update` seems to fail with the following error:
```
Ign:8 https://cdn.sury.org/php stretch/main all Packages
Err:9 https://cdn.sury.org/php stretch/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists... Done
W: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I also noticed on twitter that the debian packages are now served by a CDN and I was wondering if the issue that I was seeing might be related to it.

Distribution:
 - OS: Debian 9
 - Architecture: amd64
 - Repository:  packages.sury.org

**Comment by oerdnj** [comment]
Could you try running `:|gnutls-cli packages.sury.org:443`

**Comment by oerdnj** [comment]
Works for me, it must be a local configuration problem.

**Comment by vansart1** [comment]
It seems to be working now for me as well even though I haven't changed anything since last night.

I was also getting an error when running: `sudo wget https://packages.sury.org/php/apt.gpg` as it was responding with:
```
ERROR: The certificate of ‘cdn.sury.org’ is not trusted.
ERROR: The certificate of ‘cdn.sury.org’ is not yet activated.
```
This error is not happening any more either, so maybe the certificate for cdn.sury.org got activated overnight?

**Comment by sgrayban** [comment]
Not working again.........

- Certificate[1] info:
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', key-ID `sha256:60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18'
- Status: The certificate is NOT trusted. The name in the certificate does not match the expected. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** handshake has failed: Error in the certificate.

**Comment by sgrayban** [comment]
Cert CN is being set as **howl.rfc1925.org**

**Comment by sgrayban** [comment]
I found a way around the bad NO RELEASE issue with apt by modifying the line
deb [trusted=yes] https://packages.sury.org/php/ stretch main

For the bad SSL CN name mismatch edit /etc/apt/apt.conf and add these 2 lines
Acquire::https::packages.sury.org::Verify-Peer "false";
Acquire::https::packages.sury.org::Verify-Host "false";

**!!ATTENTION!! DO THIS AT YOUR OWN RISK as this defeats the whole idea of a secure deb repo.**

**Comment by oerdnj** [comment]
It’s your DNS that’s faulty and returning stale address.

**Comment by sgrayban** [comment]
You are correct. Strange I had that old dns cache for that long.
