### ISSUE TITLE
php-msgpack is missing module for php5.6 

### ISSUE THREAD

**Issue by xals** [oerdnj/deb.sury.org#1099]
**Describe the bug**
After last upgrade, memcached module doesn't load.

**To Reproduce**
1. Upgrade msgpack to last version (`2.0.3-1+0~20190218104454.8+stretch~1.gbp45df08_amd64`)
2. Run command `php5.6 -m`
3. Look at first lines
4. See message:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcached.so' - /usr/lib/php/20131226/memcached.so: undefined symbol: php_msgpack_serialize in Unknown on line
0`   
5. `memcached` module is missing
 
**Expected behavior**
Message should not be displayed and memcached module should be loaded.

**Distribution (please complete the following information):**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: `deb https://packages.sury.org/php/ stretch main`

**Package(s) (please complete the following information):**
```
# apt-cache policy php-memcached
php-memcached:
  Installé : 3.1.3+2.2.0-1+0~20190104095850.7+stretch~1.gbpb26597
  Candidat : 3.1.3+2.2.0-1+0~20190104095850.7+stretch~1.gbpb26597
 Table de version :
 *** 3.1.3+2.2.0-1+0~20190104095850.7+stretch~1.gbpb26597 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.1+2.2.0-1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
# apt-cache policy php-msgpack
php-msgpack:
  Installé : 2.0.3-1+0~20190218104454.8+stretch~1.gbp45df08
  Candidat : 2.0.3-1+0~20190218104454.8+stretch~1.gbp45df08
 Table de version :
 *** 2.0.3-1+0~20190218104454.8+stretch~1.gbp45df08 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.2+0.5.7-1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
```

**Additional context**
Websites using memcached on php5.6 are broken.

**Comment by oerdnj** [comment]
Hmm, some bad timing between upgrading the Jenkins scripts and repository has happened, the fixed build is building now: https://jenkins.rfc1925.org/job/php_php-msgpack-binaries/15/

**Comment by xals** [comment]
Ok, thank you very much for your quick reply!

**Comment by oerdnj** [comment]
Also read: https://www.patreon.com/posts/ubuntu-14-04-php-22093917

**Comment by xals** [comment]
I had to download the package directly from Jenkins because it is not uploaded on the repository.
It fixed my issue, thank you very much!

**Comment by tijsverwest** [comment]
I have exactly the same issue, but with different package versions:

php-msgpack: 2.1.1+0.5.7-2+ubuntu18.04.1+deb.sury.org+4
php-memcached: 3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4

OS: Ubuntu 18.04

**Comment by stathis** [comment]
Exact same issue here. My versions:

```
php8.0-msgpack/bionic,now 2.1.2+0.5.7-6+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php8.0-memcached/bionic,now 3.1.5+2.2.0-9+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
```

**Comment by oerdnj** [comment]
It's not the same issue. Fill a new one a provide all the details.
