### ISSUE TITLE
Error during fetching packages from repo

### ISSUE THREAD

**Issue by sargitcom** [oerdnj/deb.sury.org#1101]
**Describe the bug**

During running of apt-get update I recive such an error:

E: Failed to fetch https://cdn.sury.org/php/dists/stretch/main/source/Sources.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:26370 [weak]
    - SHA256:3a5a3941791968951d989323c880160d4d2d341504f09467a7a9d3c160e3587a
    - SHA1:b5fbe5612ede82e386b8519b8d3875c4592b8003 [weak]
    - MD5Sum:251086bfdc89fff53008407115c37527 [weak]
   Hashes of received file:
    - SHA256:372ece46bc4545beb297ab7c4eb0c29e94ed435b3b599d2fa93412045cdb5d21
    - SHA1:d5b8c5bc8b02dab3f68d4127807e9cab48dc0609 [weak]
    - MD5Sum:18fe2ee5e09ddc72cfc3c0a485acf135 [weak]
    - Filesize:26362 [weak]
   Last modification reported: Wed, 20 Feb 2019 00:10:08 +0000
   Release file created at: Tue, 19 Feb 2019 09:12:38 +0000

**To Reproduce**
1. Go to terminal in debian 9 stretch
2. run apt-get update
3. see an error in apt logs

**Expected behavior**
Download packakge from repository

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: x86-64
 - Repository: cdn.sury.org/php/dists/stretch/main/source/

**Comment by oerdnj** [comment]
I switched the CDN to the push method, so this should not happen anymore.

**Comment by tomascassidy** [comment]
I was still experiencing this issue now until I switched from packages.sury.org to cdn.sury.org, ran apt-get update, and then switched back to packages.sury.org.  After this, I could run apt-get update without errors.  This might help other people that still see a problem.

**Comment by oerdnj** [comment]
Did you try to turn it off and on again? ;)

(I guess commenting out then updating would have the same effect.)
