### ISSUE TITLE
Apt Update Error

### ISSUE THREAD

**Issue by doggukan** [oerdnj/deb.sury.org#1103]
**Describe the bug**
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Get:3 https://cdn.sury.org/php stretch InRelease [6,934 B]
Get:5 https://cdn.sury.org/php stretch/main armhf Packages [105 kB]
Err:5 https://cdn.sury.org/php stretch/main armhf Packages
  Writing more data than expected (105909 > 105151)
  Hashes of expected file:
   - Filesize:105151 [weak]
   - SHA256:2c5d4e706d8db40ba6962ce7823294fc42c1d8d31d007e8db02c3bf1e1231e58
   - SHA1:e46c8171e93b39ed82898430a25803fa31eabcd1 [weak]
   - MD5Sum:0137ede3c005d95f6163713a1139aef0 [weak]
  Release file created at: Tue, 19 Feb 2019 09:12:38 +0000
Fetched 6,934 B in 9s (740 B/s)
Reading package lists... Done
E: Failed to fetch https://cdn.sury.org/php/dists/stretch/main/binary-armhf/Packages.gz  Writing more data than expected (105909 > 105151)
   Hashes of expected file:
    - Filesize:105151 [weak]
    - SHA256:2c5d4e706d8db40ba6962ce7823294fc42c1d8d31d007e8db02c3bf1e1231e58
    - SHA1:e46c8171e93b39ed82898430a25803fa31eabcd1 [weak]
    - MD5Sum:0137ede3c005d95f6163713a1139aef0 [weak]
   Release file created at: Tue, 19 Feb 2019 09:12:38 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**To Reproduce**
1. Add repo to sources.list
2. run apt-get update
3. See error

**Distribution (please complete the following information):**
 - OS: Raspbian Stretch
 - Architecture: armhf
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

**Comment by oerdnj** [comment]
I switched the CDN to the push method, so this should not happen anymore.

**Comment by HOSTED-POWER** [comment]
Problems here:

Err:15 https://packages.sury.org/php stretch/main amd64 Packages
  Writing more data than expected (111903 > 111896)
  Hashes of expected file:
   - Filesize:111896 [weak]
   - SHA256:0c29f6482b2875eddb99aedb45ec662f0d906873f57233eed96658b93cc80bf8
   - SHA1:f9d4632e7cd069a2ff93ddd926599f377f4283fa [weak]
   - MD5Sum:efc9757b23177fe90b0b156f2aceee39 [weak]
  Release file created at: Fri, 03 May 2019 11:31:04 +0000
Hit:19 http://packages.blackfire.io/debian any InRelease
Hit:17 https://packagecloud.io/varnishcache/varnish41/debian stretch InRelease
Fetched 6760 B in 1s (4233 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (111903 > 111896)
   Hashes of expected file:
    - Filesize:111896 [weak]
    - SHA256:0c29f6482b2875eddb99aedb45ec662f0d906873f57233eed96658b93cc80bf8
    - SHA1:f9d4632e7cd069a2ff93ddd926599f377f4283fa [weak]
    - MD5Sum:efc9757b23177fe90b0b156f2aceee39 [weak]
   Release file created at: Fri, 03 May 2019 11:31:04 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by NicholasKirchner** [comment]
Echoing HOSTED-POWER:
```
Get:4 https://packages.sury.org/php stretch/main armhf Packages [110 kB]
Err:4 https://packages.sury.org/php stretch/main armhf Packages
  Writing more data than expected (110414 > 110375)
  Hashes of expected file:
   - Filesize:110375 [weak]
   - SHA256:e856de74cc562c80457a9292bec23dbbe7ea981397710b515e1b87db96275530
   - SHA1:a57ef08bc0bf7f8ffc643ea2916407cc21395a56 [weak]
   - MD5Sum:e63a77feed89e7434700890c720be7aa [weak]
  Release file created at: Sat, 04 May 2019 22:47:25 +0000
Fetched 6,760 B in 1s (5,041 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-armhf/Packages.gz  Writing more data than expected (110414 > 110375)
   Hashes of expected file:
    - Filesize:110375 [weak]
    - SHA256:e856de74cc562c80457a9292bec23dbbe7ea981397710b515e1b87db96275530
    - SHA1:a57ef08bc0bf7f8ffc643ea2916407cc21395a56 [weak]
    - MD5Sum:e63a77feed89e7434700890c720be7aa [weak]
   Release file created at: Sat, 04 May 2019 22:47:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by oerdnj** [comment]
When did this happen last time? I disabled all the caching couple hours ago, so I need to know whether it was before or after that.

**Comment by NicholasKirchner** [comment]
It failed once more shortly after posting the issue above, so 4-5 hours ago (maybe 7PM Central Daylight Time).  Tried again around 9PM and it worked.

**Comment by oerdnj** [comment]
I am going to close this again, and let's reopen the issue if that happens again.
