### ISSUE TITLE
php -> php 7.3?

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1105]
php 7.2 appears to be the default, isn't it time to make 7.3 the default?

**Comment by oerdnj** [comment]
Perhaps, I tend to wait ~3 months from the initial release before I do the switch.

**Comment by wioxjk** [comment]
Was this switch done today or yesterday by any chance?
Is seems like php7.2-mysql was remove for some reason from my systems :)

**Comment by oerdnj** [comment]
Yes, the switch has been done yesterday.

The only reason why it would remove any package would be if you run `apt-get autoremove` blindly...

**Comment by wioxjk** [comment]
Thanks for your answer. The update was made by unattended upgrades, which looks like this:

> Unattended-Upgrade::Origins-Pattern {
>         "o=*";
> };
> Unattended-Upgrade::Automatic-Reboot "false";
> Unattended-Upgrade::Mail "root";
> Unattended-Upgrade::Remove-Unused-Dependencies "false";

Must be that I installed php-mysql instead of specifying php7.2-mysql.
