### ISSUE TITLE
OpenSSL 1.1.1b & Nginx 1.15.9 released

### ISSUE THREAD

**Issue by S8Cloud** [oerdnj/deb.sury.org#1107]
https://www.openssl.org/news/newslog.html
OpenSSL 1.1.1b & OpenSSL 1.0.2r

**Comment by oerdnj** [comment]
JFTR there's nothing really important in the OpenSSL 1.1.1b update, so this is low priority.

**Comment by S8Cloud** [comment]
Update：Nginx 1.15.9 mainline released. Maybe it is a little bit more important.
https://github.com/nginx/nginx/releases/tag/release-1.15.9

**Comment by butaford** [comment]
And please add support for ngx_http_js_module. Thx

**Comment by oerdnj** [comment]
OpenSSL and nginx has been updated to latest upstream versions in Ubuntu, and it will take a while to build them in Debian, but it's in the queue, so I am closing the bug now.

(Also I am ignoring people hijacking issues...)
