### ISSUE TITLE
[php-7.0] gd.so: undefined symbol: gdJpegGetVersion

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#111]
FWIW...

    ~ php -i | tail -1
    php: symbol lookup error: /usr/lib/php/20141001/gd.so: undefined symbol: gdJpegGetVersionString
    JPEG Support => enabled

**Comment by oerdnj** [comment]
https://github.com/php/php-src/pull/1507

**Comment by oerdnj** [comment]
Fixed when Built-Using: php7.0-modules-src = 7.0.0~rc2-2~<dist>+1 (e.g. in php-modules = 10)
