### ISSUE TITLE
Elaborate on apache2 PPA policies

### ISSUE THREAD

**Issue by mikini** [oerdnj/deb.sury.org#1110]
**Is your feature request related to a problem? Please describe.**
In the [main PHP PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) it is recommended that:

> 2. If you are using apache2, you are advised to add ppa:ondrej/apache2

However, there are no arguments as to why this is recommended, what benefits this apache build will have and what risks systems might be exposed to by doing so. The [apache 2 PPA](https://launchpad.net/~ondrej/+archive/ubuntu/apache2) itself does not provide any more hints than "latest Apache2 packages as maintained by the Debian Apache2 team with couple of compatibility patches".
This might be technically correct but not knowing the details of "latest packages", "couple of patches" and the workflow of the Debian Apache2 team I'm not very informed about what software is published in this PPA and not able to assess advantages/disadvantages of adhering to this recommendation.

For xenial I currently see the versions:
* ppa:ondrej/apache2: [2.4.38-2+ubuntu16.04.1+deb.sury.org+6.3](https://launchpad.net/~ondrej/+archive/ubuntu/apache2?field.series_filter=xenial)
* xenial-updates: [2.4.18-2ubuntu3.9](https://packages.ubuntu.com/xenial-updates/apache2)

Obviously there will be major differences between codebases forked from 2.4.18 ([svn tagged 2015-12-08](https://svn.apache.org/viewvc?view=revision&revision=1718693), [released ~11-December-2015](https://www.apachelounge.com/Changelog-2.4.html)) and 2.4.38 ([svn tagged 2019-01-17](https://svn.apache.org/viewvc?view=revision&revision=1851569), [released 21-January-2019]()).

Basicly by rereading the documentation I'm wondering if I'm exposing systems only using the php PPA to a risk (security or update stability wise) by not using the apache2 PPA. The obvious fix is to follow the recommendation but I'm not convinced how that will affect systems and I'm not inclined to do that without understanding the implications. 

Is the 2.4.38 package set as complete as the set provided by Ubuntu xenial? Does it include all apache/php modules and/or PECL/PEAR tools for building any missing modules?

**Describe the solution you'd like**
A more elaborate description of what the purpose of the apache2 PPA is and how it relates to the php PPA.

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: ppa:ondrej/apache2 & ppa:ondrej/php

Thanks,
Mikkel

**Comment by oerdnj** [comment]
apache2 has all the fancy stuff like modern crypto, HTTP/2.0 and TLS/3.

For the rest, you need to do your own research (I provide couple of updated modules that has been requested) and maybe submit a patch for the description if you want to see it improved.
