### ISSUE TITLE
PHP PPA wants to upgrade apache2-tools and remove apache2

### ISSUE THREAD

**Issue by AleksCee** [oerdnj/deb.sury.org#1111]
Today an apt-get upgrade need dist-Upgrade and then wants to remove Apache.

Die folgenden Pakete sind zurückgehalten worden:
  apache2 apache2-bin apache2-data
Die folgenden Pakete werden aktualisiert (Upgrade):
  apache2-utils
1 aktualisiert, 0 neu installiert, 0 zu entfernen und 3 nicht aktualisiert.
Es müssen 147 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 3.072 B Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] n
Abbruch.

Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  apache2-data apache2-utils python-dnspython
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  apache2 mailman
Die folgenden Pakete werden aktualisiert (Upgrade):
  apache2-data apache2-utils
2 aktualisiert, 0 neu installiert, 2 zu entfernen und 0 nicht aktualisiert.
Es müssen 314 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 39,2 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] n
Abbruch.

A deeper look at the source shows that newly (since 1h) the apache2 packed is in the PPA for PHP... is this right?

I want only use the php version and the description say, if I want Apache also a should use the other PPA Apache... so I thought it's not what is wanted...?

Thanks, Alex

**Comment by AleksCee** [comment]
My workaround for today:

```
/etc/apt/preferences.d# cat ondrej-php 

Package: apache2*
Pin: release o=LP-PPA-ondrej-php
Pin-Priority: -1
```

**Comment by oerdnj** [comment]
Argh, apache2 was uploaded to `ppa:ondrej/php` by error.  I have deleted the package from the PPA now.
