### ISSUE TITLE
Debian Stretch & PHP 7.0

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1113]
AFAIK Debian Stretch is supported until about April 2020.. and Stretch has 7.0 (currently). What's the plan here?

**Comment by oerdnj** [comment]
PHP 7.0 will be supported inside Debian as usual for any other software with the help of security team.  The security patches will be cherry-picked from 7.1 (or 7.2) and applied to the the latest release.

As for deb.sury.org the plan still holds, I am stopping to provide PHP 5.6 and PHP 7.0 from the PPA and DPA (however I am not going to delete the git repository).
