### ISSUE TITLE
Open Slack workspace: DEB.SURY.ORG

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1114]
```
This invite link is no longer active.

Please check with the person who shared it with you to see if there's a new link available.
```

https://github.com/oerdnj/deb.sury.org

**Comment by oerdnj** [comment]
Here's the new link that never expires and I updated the front page as well: https://join.slack.com/t/debsuryorg/shared_invite/enQtNTY2MTg0MDg2NjI4LWEwNDliMWIyY2U0OWJjOTQ1YzFhNzc3OGMzY2U4NWM5MDE4OWJhNGE2OTNhNDkwZDkzNzY2ZWNiMzgyY2Y5ZTI

**Comment by fruitl00p** [comment]
@oerdnj Sorry to bug you about this, but the link has indeed expired... thanks!
