### ISSUE TITLE
Build Broken! 7.2-common installing 7.3-common

### ISSUE THREAD

**Issue by jreason** [oerdnj/deb.sury.org#1117]
**Describe the bug**
When building my container using php 7.2, 7.3-common is installing instead of 7.2 breaking the build.
The first occurrence of this was yesterday afternoon.

Please see some extracts from the build log.

Dockerfile:

> RUN apt-get update && \
    apt-get install -y software-properties-common && \
    LC_ALL=C.UTF-8 add-apt-repository -y -u ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y \
        curl \
        imagemagick \
        nano \
        libapache2-mod-php7.2 \
        php7.2 \
        php7.2-common \
        php7.2-curl \
        php7.2-gd \
        php7.2-mbstring \
        php7.2-mysql \
        php7.2-simplexml \
        php7.2-zip \
        php-imagick \
        php-gettext \
        wget

Build log extract:

>...
Creating config file /etc/php/7.2/apache2/php.ini with new version
Module mpm_event disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
apache2_invoke: Enable module php7.2
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up libpixman-1-0:amd64 (0.33.6-1) ...
Setting up libxcb-render0:amd64 (1.11.1-1ubuntu1) ...
Setting up libxcb-shm0:amd64 (1.11.1-1ubuntu1) ...
Setting up libxrender1:amd64 (1:0.9.9-0ubuntu1) ...
Setting up libcairo2:amd64 (1.14.6-1) ...
Setting up libcroco3:amd64 (0.6.11-1) ...
Setting up libcurl3:amd64 (7.47.0-1ubuntu2.12) ...
Setting up libdatrie1:amd64 (0.2.10-2) ...
Setting up libdjvulibre-text (3.5.27.1-5) ...
Setting up libdjvulibre21:amd64 (3.5.27.1-5) ...
Setting up libwebp6:amd64 (0.6.0-4+ubuntu16.04.1+deb.sury.org+1) ...
Setting up libxpm4:amd64 (1:3.5.11-1ubuntu0.16.04.1) ...
Setting up libgd3:amd64 (2.2.5-5+ubuntu16.04.1+deb.sury.org+1) ...
Setting up libgdk-pixbuf2.0-common (2.32.2-1ubuntu1.5) ...
Setting up libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.5) ...
Setting up libgraphite2-3:amd64 (1.3.10-0ubuntu0.16.04.1) ...
Setting up libharfbuzz0b:amd64 (1.0.1-1ubuntu0.1) ...
Setting up libilmbase12:amd64 (2.2.0-11ubuntu2) ...
Setting up libopenexr22:amd64 (2.2.0-10ubuntu2) ...
Setting up libthai-data (0.1.24-2) ...
Setting up libthai0:amd64 (0.1.24-2) ...
Setting up libpango-1.0-0:amd64 (1.38.1-1) ...
Setting up libpangoft2-1.0-0:amd64 (1.38.1-1) ...
Setting up libpangocairo-1.0-0:amd64 (1.38.1-1) ...
Setting up librsvg2-2:amd64 (2.40.13-3) ...
Setting up libwmf0.2-7:amd64 (0.2.8.4-10.5ubuntu1) ...
Setting up libmagickcore-6.q16-2-extra:amd64 (8:6.8.9.9-7ubuntu5.13) ...
Setting up libnetpbm10 (2:10.0-15.3) ...
Setting up libpaper-utils (1.1.24+nmu4ubuntu1) ...
Setting up libpcre2-8-0:amd64 (10.31-3+ubuntu16.04.1+deb.sury.org+1) ...
Setting up librsvg2-common:amd64 (2.40.13-3) ...
Setting up libxslt1.1:amd64 (1.1.28-2.1ubuntu0.1) ...
Setting up libzip5:amd64 (1.3.2-1+ubuntu16.04.1+deb.sury.org+1) ...
Setting up netpbm (2:10.0-15.3) ...
Setting up php7.3-common (7.3.2-3+ubuntu16.04.1+deb.sury.org+1) ...
 Creating config file /etc/php/7.3/mods-available/calendar.ini with new version
 Creating config file /etc/php/7.3/mods-available/ctype.ini with new version
 Creating config file /etc/php/7.3/mods-available/exif.ini with new version
 Creating config file /etc/php/7.3/mods-available/fileinfo.ini with new version
 Creating config file /etc/php/7.3/mods-available/ftp.ini with new version
 Creating config file /etc/php/7.3/mods-available/gettext.ini with new version
 Creating config file /etc/php/7.3/mods-available/iconv.ini with new version
 Creating config file /etc/php/7.3/mods-available/pdo.ini with new version
 Creating config file /etc/php/7.3/mods-available/phar.ini with new version
 Creating config file /etc/php/7.3/mods-available/posix.ini with new version
 Creating config file /etc/php/7.3/mods-available/shmop.ini with new version
 Creating config file /etc/php/7.3/mods-available/sockets.ini with new version
 Creating config file /etc/php/7.3/mods-available/sysvmsg.ini with new version
 Creating config file /etc/php/7.3/mods-available/sysvsem.ini with new version
 Creating config file /etc/php/7.3/mods-available/sysvshm.ini with new version
 Creating config file /etc/php/7.3/mods-available/tokenizer.ini with new version
Setting up php7.3-json (7.3.2-3+ubuntu16.04.1+deb.sury.org+1) ...
 Creating config file /etc/php/7.3/mods-available/json.ini with new version
Setting up php7.3-opcache (7.3.2-3+ubuntu16.04.1+deb.sury.org+1) ...
 Creating config file /etc/php/7.3/mods-available/opcache.ini with new version
Setting up php7.3-readline (7.3.2-3+ubuntu16.04.1+deb.sury.org+1) ...
 Creating config file /etc/php/7.3/mods-available/readline.ini with new version
Setting up php7.3-cli (7.3.2-3+ubuntu16.04.1+deb.sury.org+1) ...
update-alternatives: using /usr/bin/php7.3 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar7.3 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: using /usr/bin/phar.phar7.3 to provide /usr/bin/phar.phar (phar.phar) in auto mode
 Creating config file /etc/php/7.3/cli/php.ini with new version
Setting up php-cli (2:7.3+69+ubuntu16.04.1+deb.sury.org+2+php7.3) ...
Setting up php7.2-xml (7.2.15-1+ubuntu16.04.1+deb.sury.org+1) ...
 Creating config file /etc/php/7.2/mods-available/dom.ini with new version
 Creating config file /etc/php/7.2/mods-available/simplexml.ini with new version
...

**Comment by jreason** [comment]
Any idea on when this might get fixed?

At the moment, i cannot push to my production servers.

Thanks

**Comment by oerdnj** [comment]
There’s nothing to be fixed here, read the FAQ: 
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#why-is-php73-cli-always-installed
