### ISSUE TITLE
Let's encrypt certificate expired on packages.sury.xyz

### ISSUE THREAD

**Issue by Mossman1215** [oerdnj/deb.sury.org#1118]
Has support for packages.sury.xyz been removed?
![screenshot from 2019-03-08 10-37-52](https://user-images.githubusercontent.com/3606406/53990969-58a6d200-418e-11e9-9a46-e44c938d004a.png)

**Comment by S8Cloud** [comment]
Seems packages.sury.xyz no longer uses Cloudflare and packages.sury.org has turned to KeyCDN.
Hoping Cloudflare CDN can be back as it seems much faster than KeyCDN.

**Comment by oerdnj** [comment]
Cloudflare did nothing for big packages.

**Comment by Mossman1215** [comment]
@oerdnj so .xyz is defunct permanently?

**Comment by oerdnj** [comment]
It was never primary URL, but no, it's not permanently defunct.

The acme.sh nginx method just failed to use correct server configuration and it was failing renewal.  I switched to webroot method and all should be fine now.
