### ISSUE TITLE
[php-7.0] Wrong compiled in include_path

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#112]
It seems the the compiled in include_path of **.::/usr/share/pear** is incorrect because of the double colon which prevents the **.** current dir part from working. I'd suggest **.:/usr/share/php** as a more sensible default but I have no idea about the status of PEAR packages with php-7.0. I would use composer packages in preference to PEAR anyway.

**Comment by oerdnj** [comment]
The double colon is artifact that got created when I dropped building PEAR packages from src:php-7.0.

This has been fixed in 7.0.0~rc2-1 release (to be uploaded soon).
