### ISSUE TITLE
PHP 7.2 packages removed while updating

### ISSUE THREAD

**Issue by codmdu** [oerdnj/deb.sury.org#1120]
Hello,

yesterday we updated our server (`apt upgrade`).
While the update some php 7.2 Packages was removed, which broke our application(s).

Why some php packages was removed ?
To fix that we had to install the packages again.

Greetings,
codmdu

**Comment by oerdnj** [comment]
You have autoremovals enabled, f.e. documented here: https://help.ubuntu.com/community/RemoveOldKernels

E.g. it's your local configuration, not the packages.

**Comment by codmdu** [comment]
Its enabled, but the packages are not unused.

**Comment by oerdnj** [comment]
"used" is in the context of package interdependencies, so there's no other package that depends on the specific version then 7.2 packages will be removed when php-defaults switched from PHP 7.2 to PHP 7.3.
