### ISSUE TITLE
Can not find ext_skel script

### ISSUE THREAD

**Issue by flip111** [oerdnj/deb.sury.org#1121]
I was expecting to find the `ext_skel` script for developing extensions in `php7.3-dev` but it isn't there. Maybe it could be added?

https://secure.php.net/manual/en/internals2.buildsys.skeleton.php

https://github.com/php/php-src/blob/master/ext/ext_skel.php

https://github.com/php/php-src/blob/master/README.EXT_SKEL

**Comment by oerdnj** [comment]
The `ext_skel.php` script isn't installed by upstream build system anywhere.  You are expected to use it from the sources, not from the binary packages, even the documentation link shows source directory.

**Comment by flip111** [comment]
@oerdnj could you clarify which upstream build system? Which link are you referring to when you say `show source directory`?
