### ISSUE TITLE
provide vesioned libssl-dev packages in jessie

### ISSUE THREAD

**Issue by r4sas** [oerdnj/deb.sury.org#1122]
**Is your feature request related to a problem? Please describe.**
Using repository overwrites libssl-dev package with newer 1.1.1 version.
But because jessie contain old version of boost libraries (1.57.0) its make impossible compile software which use libssl-dev due to incompotability of boost with new openssl versions.

**Describe the solution you'd like**
Add versioned libssl1.0-dev package, like in stretch.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: any
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
libssl-dev:
  Установлен: 1.1.1b-1+0~20190228092431.10+jessie~1.gbp729d89
  Кандидат:   1.1.1b-1+0~20190228092431.10+jessie~1.gbp729d89
  Таблица версий:
 *** 1.1.1b-1+0~20190228092431.10+jessie~1.gbp729d89 0
        500 https://packages.sury.org/php/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2l-1~bpo8+1 0
        100 http://ftp.ru.debian.org/debian/ jessie-backports/main amd64 Packages
     1.0.1t-1+deb8u11 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
     1.0.1t-1+deb8u8 0
        500 http://ftp.ru.debian.org/debian/ jessie/main amd64 Packages
```

**Comment by oerdnj** [comment]
Sorry, but no. You not mixing various Dev enironments and using isolation (even cheroot would do) than me doing such intrusive change to the package name.
