### ISSUE TITLE
zend_mm_heap corrupted when executing xdebug in php7.3

### ISSUE THREAD

**Issue by davefx** [oerdnj/deb.sury.org#1123]
**Describe the bug**
Whenever I launch a XDebug session, with get parameter XDEBUG_SESSION_START, I get zend_mm_heap corrupted messages in the apache error log, and the execution is aborted with a segmentation fault.

**To Reproduce**
1. Create a phpinfo.php file, with just a call to phpinfo().
2. Configure Xdebug with the Start a Xdebug session, getting the xdebug session ID.
3. Via Apache with modphp 7.3, access the created phpinfo.php file with the options
```
xdebug.remote_enable=1
xdebug.profiler_enable_trigger=1
```
4. From a browser, try to access /phpinfo.php?XDEBUG_SESSION_START=<xdebug-session-ID>

**Expected behavior**

The PHPInfo page should be shown.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
php-xdebug:
  Installed: 2.7.0+2.5.5-1+ubuntu18.10.1+deb.sury.org+1
  Candidate: 2.7.0+2.5.5-1+ubuntu18.10.1+deb.sury.org+1
  Version table:
 *** 2.7.0+2.5.5-1+ubuntu18.10.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.0-0ubuntu1 500
        500 http://mirror.switch.ch/ftp/mirror/ubuntu cosmic/universe amd64 Packages
libapache2-mod-php7.3:
  Installed: 7.3.3-1+ubuntu18.10.1+deb.sury.org+1
  Candidate: 7.3.3-1+ubuntu18.10.1+deb.sury.org+1
  Version table:
 *** 7.3.3-1+ubuntu18.10.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
php7.3-opcache:
  Installed: 7.3.3-1+ubuntu18.10.1+deb.sury.org+1
  Candidate: 7.3.3-1+ubuntu18.10.1+deb.sury.org+1
  Version table:
 *** 7.3.3-1+ubuntu18.10.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by davefx** [comment]
The problem happens even if I downgrade to PHP 7.2, keeping the last php-xdebug package.
If I also downgrade to a previous php-xdebug 2.6 package, everything returns to work properly.

**Comment by oerdnj** [comment]
You’ll need to report this to xdebug developers. This has nothing to do with packaging.
