### ISSUE TITLE
Upgrade libzip on Bionic

### ISSUE THREAD

**Issue by arhue** [oerdnj/deb.sury.org#1124]
libzip was upgraded on Xenial due to this: https://github.com/oerdnj/deb.sury.org/issues/752

But this change wasn't made on Bionic. Any chance for the upgrade?

**Comment by oerdnj** [comment]
I uploaded libzip to the repositories, but the php still needs to be rebuilt.  I'll leave it until next upstream release (unless something else pops up).

**Comment by teluka** [comment]
@oerdnj Are you going to build new Bionic packages with updated zip extension for both 7.2 and 7.3 releases ?

Thanks

**Comment by oerdnj** [comment]
>  I'll leave it until next upstream release (unless something else pops up).

^^^ The next upstream release should generally happen in two weeks, so I believe it would be waste of time for everybody to upgrade the packages (twice).

**Comment by oerdnj** [comment]
This should have happened today.
