### ISSUE TITLE
Apache stopped during upgrade

### ISSUE THREAD

**Issue by mfb** [oerdnj/deb.sury.org#1125]
**Describe the bug**

On Ubuntu trusty, when upgrading apache for some reason it was stopped rather than restarting:
Preparing to unpack .../apache2_2.4.38-2+ubuntu14.04.1+deb.sury.org+8_amd64.deb ...
 * Stopping Apache httpd web server apache2                                         

**To Reproduce**

`apt dist-upgrade`

**Expected behavior**

Apache is restarted rather than stopped.

**Distribution:**
 - OS: Trusty
 - Architecture: amd64
 - Repository: http://ppa.launchpad.net/ondrej/apache2/ubuntu trusty main

**Package(s):**

apt-cache policy apache2
apache2:
  Installed: 2.4.38-2+ubuntu14.04.1+deb.sury.org+8
  Candidate: 2.4.38-2+ubuntu14.04.1+deb.sury.org+8
  Version table:
 *** 2.4.38-2+ubuntu14.04.1+deb.sury.org+8 0
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.10-1ubuntu1.1~ubuntu14.04.2 0
        100 http://us.archive.ubuntu.com/ubuntu/ trusty-backports/main amd64 Packages
     2.4.7-1ubuntu4.21 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
     2.4.7-1ubuntu4.20 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     2.4.7-1ubuntu4 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by oerdnj** [comment]
I am sorry, but Ubuntu 14.04 is almost EOL, so I am not going to invest any time into fixing minor issues like this.

**Comment by mfb** [comment]
Understandable.  I'm not sure if it's a Trusty-specific issue, but it could be.

**Comment by oerdnj** [comment]
Trusty is last non-systemd release (e.g. upstart).
