### ISSUE TITLE
Not able to install php7.2-cli or php7.2-fpm from buster repo

### ISSUE THREAD

**Issue by EvilBMP** [oerdnj/deb.sury.org#1126]
**Describe the bug**
I am not able to install php7.2 from the buster repo. After adding the repository to my apt sources and doing an:

`apt update && apt install php7.2-cli`

I get:

`php7.2-cli : Depends: libpcre3 (>= 2:8.41) but 2:8.39-11 is to be installed`

I am already on buster testing repository. Any idea how to update the libpcre3 in buster? Or is the php7.2-cli dependency wrong?

PS: same happens with the php7.2-fpm package

**Distribution (please complete the following information):**
 - OS: Debian Buster (WLinux - WSL)
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy php7.2-cli`

```
php7.2-cli:
  Installed:           (none)
  Candidate: 7.2.16-1+0~20190307202327.17+buster~1.gbpa7be82
  Version table:
     7.2.16-1+0~20190307202327.17+buster~1.gbpa7be82 500
        500 https://packages.sury.org/php buster/main amd64 Packages
```

**Comment by oerdnj** [comment]
What’s the apt-cache policy output for the libpcre3?

**Comment by EvilBMP** [comment]
```
libpcre3:
  Installed:           2:8.39-11
  Candidate: 2:8.39-11
  Version table:
     2:8.42-1+0~20190203125152.5+buster~1.gbp79d75d 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     2:8.39-12 500
        500 https://deb.debian.org/debian unstable/main amd64 Packages
 *** 2:8.39-11 990
        990 https://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by EvilBMP** [comment]
Alright, thanks for pointing me in the right direction 👍 

`apt install libpcre3=2:8.42-1+0~20190203125152.5+buster~1.gbp79d75d` updated the package correctly and afterwards I was able to install php7.2

Thanks :-)

**Comment by oerdnj** [comment]
I told you to fix your pinning in the first message, you know...

**Comment by EvilBMP** [comment]
Sorry, I didn't understand what you ment with "fix your pinning" in the first message.
