### ISSUE TITLE
Frequent timeouts connecting to packages.sury.org via IPv6

### ISSUE THREAD

**Issue by plinss** [oerdnj/deb.sury.org#1127]
**Describe the bug**
For the past few weeks I've been seeing frequent timeouts when running apt-get update. The machine in question has both IPv4 and IPv6 network connections. Testing on the command line shows connections via IPv4 work fine, however connections via IPv6 timeout.

**To Reproduce**
curl -6 https://packages.sury.org/

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Now tell me, how do you think one could debug a network issue when you provided virtually no information at all.

**Comment by plinss** [comment]
For starters, I'd try to reproduce the problem (using the provided information) to see if it was local or a routing issue somewhere in between the machines in question. 

If I didn't find a local issue, I'd thank the issue reporter, let them know the problem wasn't local, and politely ask for specific additional information that I felt would help me identify the problem.

What I wouldn't do is respond rudely to someone who was politely trying to help me out.

Now, please tell me, what information would you find useful?

**Comment by oerdnj** [comment]
Just as a general warning - if you wilfully waste my time by deliberately not providing vital information and then you will act like the guy here, you will not get any help and I will block you.
