### ISSUE TITLE
Phalcon 3-4-3 For Php 7.3 Ubuntu 18

### ISSUE THREAD

**Issue by tidytrax** [oerdnj/deb.sury.org#1130]
Hello it's possible to do the package for new phalcon, now works on PHP 7.3
Thanks

https://blog.phalconphp.com/post/phalcon-3-4-3-released

**Comment by oerdnj** [comment]
JFTR I would appreciate if you've used the templates, but that will do.

**Comment by oerdnj** [comment]
Uploaded and building.

**Comment by tidytrax** [comment]
What template? Sorry,

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/new/choose

But maybe github doesn’t show those in the mobile version...  it doesn’t matter now.

**Comment by tidytrax** [comment]
Sorry, and thanks, You know when will be avaiable at apt install? thanks

**Comment by oerdnj** [comment]
When it builds: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=phalcon&field.status_filter=published&field.series_filter=

just be a little patient and try in about an hour...

**Comment by tidytrax** [comment]
WOw nice, so fast, very thanks man, will work at ubuntu 18.0.4?
