### ISSUE TITLE
Question: How to switch to default Debian packages once Buster is released?

### ISSUE THREAD

**Issue by demetris** [oerdnj/deb.sury.org#1135]
What is the recommended way of switching from the sury PHP 7.3 Debian packages to the default Debian packages when Buster is released?

Is this documented somewhere?

Thanks for reading!

**Comment by oerdnj** [comment]
Not really, but there’s no reason to do so, they are built from the same sources. The only difference is that I keep some of the libraries more up to date.

**Comment by demetris** [comment]
Thanks for the reply and the explanation, Ondřej!
