### ISSUE TITLE
Apache 2.4.39

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1137]
**Is your feature request related to a problem? Please describe.**
With regards to the official Apache HTTP server newsletter there are a few important updates which have been fixed with the new HTTP server version: https://httpd.apache.org/security/vulnerabilities_24.html

**Describe the solution you'd like**
Compile the newest version for the Debian/Ubuntu repositories.
(Please keep [issue](https://github.com/oerdnj/deb.sury.org/issues/1088) in mind.)

**Describe alternatives you've considered**
n/a

**Distribution (please complete the following information):**
Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
`apache2:
  Installiert:           2.4.38-2+ubuntu16.04.1+deb.sury.org+8
  Installationskandidat: 2.4.38-2+ubuntu16.04.1+deb.sury.org+8
  Versionstabelle:
 *** 2.4.38-2+ubuntu16.04.1+deb.sury.org+8 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.18-2ubuntu3.9 500
        500 http://at.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     2.4.18-2ubuntu3.8 500
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.4.18-2ubuntu3 500
        500 http://at.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
mathias@wwwubuntu:~$
`
Thanks!

**Comment by derritter88** [comment]
Thanks for the update!

**Comment by oerdnj** [comment]
I still need to update DPA.

**Comment by oerdnj** [comment]
Debian armhf build has failed, but nobody uses that yet, so I am closing the bug and will investigate the failure to build independently.
