### ISSUE TITLE
[Feature Request] PHP Extension pcov

### ISSUE THREAD

**Issue by bcremer** [oerdnj/deb.sury.org#1138]
I would love to have the pcov PHP Extension by @krakjoe and @remicollet in the Ubuntu PPA and the Debian Repostiory available.

Pcov is a self contained php-code-coverage compatible driver for PHP7 which is also supported by phpunit.

https://pecl.php.net/package/pcov
https://github.com/krakjoe/pcov
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=php-pcov
https://blog.krakjoe.ninja/2019/01/running-for-coverage.html

Is there anything I can do to support you with that?

**Comment by Slamdunk** [comment]
It would be great to have PCOV extension provided by deb.sury.org :+1:

**Comment by krakjoe** [comment]
Call me self interested ... but +42

**Comment by oerdnj** [comment]
Packaged and uploaded.
