### ISSUE TITLE
when can apache2 be updated from your armhf repository?

### ISSUE THREAD

**Issue by tigernero79** [oerdnj/deb.sury.org#1139]
having installed the apache2 version 2.4.25 of the basic raspbian os,  is not possible to upgrade to today the 2.4. 39 of your repository to 2.4.39, goes to conflict with raspbian version. is there a way to update or wait?

**Comment by oerdnj** [comment]
The second rebuild finished just fine, so the arc:apache2 packages are available from the repository.

**Comment by tigernero79** [comment]
@oerdnj I tried to install apache2 on raspberry with your repositories enabled but I always get the same error as you can see in the attached image.

![Screenshot_20190410-083147](https://user-images.githubusercontent.com/35575744/55856712-5fe54500-5b6b-11e9-8b4a-7e547ca125fe.png)

**Comment by oerdnj** [comment]
That's why there's a template in the Issue tracking:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
Add any other context about the problem here.
```

What is the output of `apt-cache policy apache2-bin` and what happens if you do `apt-get install apache2-bin`

**Comment by tigernero79** [comment]
@oerdnj 

command: sudo apt-cache policy apache2-bin

output:= apache2-bin:
  Installato: (nessuno)
  Candidato:  2.4.39-1+0~20190407123313.4+stretch~1.gbpec65d0
  Tabella versione:
     2.4.39-1+0~20190407123313.4+stretch~1.gbpec65d0 500
        500 https://packages.sury.org/apache2 stretch/main armhf Packages
     2.4.25-3+deb9u7 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages

![Immagine](https://user-images.githubusercontent.com/35575744/55868870-9e87f900-5b85-11e9-8ddb-91fdd6624d0d.png)

-------------------------

try sudo apt-get install apache2-bin

output= 

Generazione albero delle dipendenze
Lettura informazioni sullo stato... Fatto
Alcuni pacchetti non possono essere installati. Questo può voler dire
che è stata richiesta una situazione impossibile oppure, se si sta
usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
non sono ancora stati creati o sono stati rimossi da Incoming.
Le seguenti informazioni possono aiutare a risolvere la situazione:

I seguenti pacchetti hanno dipendenze non soddisfatte:
 apache2-bin : Dipende: libbrotli1 (>= 0.6.0) ma non è installabile
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

![Immagine2](https://user-images.githubusercontent.com/35575744/55868886-a34cad00-5b85-11e9-9709-3de67e0f69f1.png)

**Comment by oerdnj** [comment]
You need `stretch-backports` for `libbrotli1`

**Comment by tigernero79** [comment]
@oerdnj can I install backport on raspbian os? for raspberry? being debian derivative?

**Comment by tigernero79** [comment]
@oerdnj 
Add backports to your sources.list

deb http://deb.debian.org/debian stretch-backports main 

is correct?

sudo apt-get -t stretch-backports install libbrotli1

**Comment by tigernero79** [comment]
I have this error after adding rposity stretch backports:

Err: 1 http://deb.debian.org/debian stretch-backports InRelease
Future signatures have not been verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010

**Comment by oerdnj** [comment]
I am sorry, I can't possibly do an user support.

Anyway libbrotli backport should be available from the packages.sury.org repository, so just remove the stretch-backports.

That said, mixing Debian and Raspbian usually doesn't end well, so this is not supported mode of operation.

**Comment by tigernero79** [comment]
@oerdnj 

I solved this way:

I added backport repository in source.list

1) sudo nano /etc/apt/sources.list

I added

deb http://deb.debian.org/debian stretch-backports main

I installed dirmngr

2) sudo apt install dirmngr

added the following keys taken from ubuntu

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553

I imported them in the apt-key

sudo gpg -a --export 7638D0442B90D010 | sudo apt-key add -

sudo gpg -a --export 8B48AD6246925553 | sudo apt-key add -

installed the dependency that was missing

sudo apt-get -t stretch-backports install libbrotli1


and I tried to install apache2 from your repository and it worked

i have apache 2.4.39 running.

![Immagine3](https://user-images.githubusercontent.com/35575744/55873371-c7ad8700-5b8f-11e9-8315-3afbc7dc510b.png)

**Comment by tigernero79** [comment]
@oerdnj I solved, however, a pity that for a debbrbli file1 you need to install debian backports
