### ISSUE TITLE
Dependency issue when updating Apache 2.4 on Ubuntu 12.04

### ISSUE THREAD

**Issue by tschikarski** [oerdnj/deb.sury.org#114]
I would very much appreciate a hint for the following problem. Many thanks in advance!

In detail: On my Ubuntu 12.04 server I have to update Apache 2.4 packages "apache2", "apache2-bin" and "apache2-data". Doing this with "apt-get dist-upgrade" exposes a dependeny problem:

    The following packages have unmet dependencies:
      apache2-mpm-prefork : Depends: apache2 (= 2.4.12-1+deb.sury.org~precise+5) but 2.4.16-4+deb.sury.org~precise+4 is to be installed.

This is the relevant part of the "apt sources":

    deb http://ppa.launchpad.net/ondrej/php5/ubuntu precise main
    deb-src http://ppa.launchpad.net/ondrej/php5/ubuntu precise main

Here are the php5 and apache2 related packages, as installed at the moment. This represents the state after doing an "apt-get upgrade", which left 3 packages not updated:

    root@myserver:/etc/apt/sources.list.d# dpkg -l | grep php
    ii  libapache2-mod-php5              5.5.29+dfsg-1+deb.sury.org~precise+3  server-side, HTML-embedded scripting language (Apache 2 module)
    ii  php5                             5.5.29+dfsg-1+deb.sury.org~precise+3  server-side, HTML-embedded scripting language (metapackage)
    ii  php5-cli                         5.5.29+dfsg-1+deb.sury.org~precise+3  command-line interpreter for the php5 scripting language
    ii  php5-common                      5.5.29+dfsg-1+deb.sury.org~precise+3  Common files for packages built from the php5 source
    ii  php5-curl                        5.5.29+dfsg-1+deb.sury.org~precise+3  CURL module for php5
    ii  php5-gd                          5.5.29+dfsg-1+deb.sury.org~precise+3  GD module for php5
    ii  php5-json                        1.3.7-1+deb.sury.org~precise+1        JSON module for php5
    ii  php5-mysql                       5.5.29+dfsg-1+deb.sury.org~precise+3  MySQL module for php5

    root@myserver:/etc/apt/sources.list.d# dpkg -l | grep apache
    ii  apache2                          2.4.12-1+deb.sury.org~precise+5       Apache HTTP Server
    ii  apache2-bin                      2.4.12-1+deb.sury.org~precise+5       Apache HTTP Server (modules and other binary files)
    ii  apache2-data                     2.4.12-1+deb.sury.org~precise+5       Apache HTTP Server (common files)
    ii  apache2-mpm-prefork              2.4.12-1+deb.sury.org~precise+5       transitional prefork MPM package for apache2
    ii  apache2-utils                    2.4.16-4+deb.sury.org~precise+4       Apache HTTP Server (utility programs for web servers)
    ii  libapache2-mod-php5              5.5.29+dfsg-1+deb.sury.org~precise+3  server-side, HTML-embedded scripting language

**Comment by oerdnj** [comment]
Just install apache2, you don't need to install apache2-mpm-prefork any more.
