### ISSUE TITLE
PHP 7.2.17 and 7.3.4

### ISSUE THREAD

**Issue by BrookeDot** [oerdnj/deb.sury.org#1140]
**Describe the solution you'd like**
PHP 7.3.4 and 7.2.17 were released yesterday April 4th and does not currently appear to be packaged in PPA. Opening this issue to track the progress of these releases.

I don't have a server running 7.1.x but it's possible that also needs to be updated to 7.1.28 which was also released yesterday.

### PHP 7.3
**Distribution:**
 - OS: Debian 9, Stretch.
 - Architecture: x86_64 
 - Repository:  Packages  (`https://packages.sury.org/php stretch InRelease`)
 - `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch
```
**Package(s) (please complete the following information):**
```
$ apt-cache policy php7.3-common
php7.3-common:
  Installed: 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2
  Candidate: 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2
  Version table:
 *** 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```
---

### PHP 7.2
**Distribution:**
 - OS: Ubuntu 18.04.2 LTS
 - Architecture: x86_64 
 - Repository:  Ubuntu `http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease`
 - `Linux  4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Package(s) (please complete the following information):**
```
 apt-cache policy php7.2-common
$ php7.2-common:
  Installed: 7.2.16-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.2.16-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.2.16-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     7.2.15-0ubuntu0.18.04.2 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     7.2.3-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages

```

**Comment by oerdnj** [comment]
You can expect updated packages this week (most probably on Tuesday).

**Comment by keeshoekzema** [comment]
If you're building: Xdebug also has a new release out :) 2.7.1

**Comment by oerdnj** [comment]
Xdebug have been updated.

PHP builds will take some time as I am syncing icu library to latest upstream and the arm* builds are taking ages to build: https://jenkins.rfc1925.org/view/PHP/job/php_icu-binaries/5/

**Comment by oerdnj** [comment]
You can monitor the build progress for Debian packages here:
* PHP 5.6: https://jenkins.rfc1925.org/view/BIND/job/php_php5.6-binaries/14/
* PHP 7.0: https://jenkins.rfc1925.org/view/BIND/job/php_php7.0-binaries/11/
* PHP 7.1: https://jenkins.rfc1925.org/view/BIND/job/php_php7.1-binaries/16/
* PHP 7.2: https://jenkins.rfc1925.org/view/BIND/job/php_php7.2-binaries/22/
* PHP 7.3: https://jenkins.rfc1925.org/view/BIND/job/php_php7.3-binaries/36/

(Blinking dot - building, Transparent dot - not yet build, Blue dot - built, Red dot - build failure).

It will take couple of hours to finish the builds as the arm builds are done using qemu and that's slooooow.

**Comment by BrookeDot** [comment]
Looks like several of these builds failed :(

**Comment by oerdnj** [comment]
Jenkins.log sometimes eats whole disk space.  The builds are running again...

**Comment by oerdnj** [comment]
* https://jenkins.rfc1925.org/job/php_php5.6-binaries/16/
* https://jenkins.rfc1925.org/job/php_php7.0-binaries/13/
* https://jenkins.rfc1925.org/job/php_php7.1-binaries/18/
* https://jenkins.rfc1925.org/job/php_php7.2-binaries/24/
* https://jenkins.rfc1925.org/job/php_php7.3-binaries/38/

**Comment by oerdnj** [comment]
I made the arch == "amd64" and arch == "i386" builds as "touchstone" builds in Jenkins, and hopefully this means (if I read the documentation right) that those needs to finish first before the rest is even executed.  That should make the fast builds out first and not blocked by arm* builds.

**Comment by oerdnj** [comment]
I will reopen the issue now, since the packages haven't been fully delivered yet.

**Comment by oerdnj** [comment]
Done.
