### ISSUE TITLE
Supply latest (or later than standard) composer from Sury

### ISSUE THREAD

**Issue by Adambean** [oerdnj/deb.sury.org#1141]
Hello,

Would it be in scope for the Sury repository to supply the latest (or a later than Debian/Ubuntu standard) version of the [Composer](https://packages.debian.org/stretch/php/composer) package?

I request this because the version distributed with Debian Stretch is outdated and is not quite compatible with PHP 7.3:

`"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

I have already verified that downloading Composer directly and using the latest version of it (currently 1.8.4) definitely resolves this.

Obviously we can get Composer ourselves but then usually have to distribute it with each application. A package update would be the most splendid approach. (Particularly for CRON jobs.)

 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
If it were just one package, I would probably do that, but look:

```
dep: php-cli-prompt (<< 2~~)
dep: php-cli-prompt (>= 1.0)
dep: php-composer-ca-bundle (<< 2~~)
dep: php-composer-ca-bundle (>= 1.0)
dep: php-composer-semver (<< 2~~)
dep: php-composer-semver (>= 1.0)
dep: php-composer-spdx-licenses (<< 2~~)
dep: php-composer-spdx-licenses (>= 1.0)
dep: php-json-schema
dep: php-psr-log (<< 2~~)
dep: php-psr-log (>= 1.0)
dep: php-symfony-console (>= 2.5)
dep: php-symfony-filesystem (>= 2.5)
dep: php-symfony-finder (>= 2.4)
dep: php-symfony-process (>= 2.4)
```

I am sorry, this is beyond free time I have.

**Comment by Adambean** [comment]
Oh wow, that's a lot of dependencies!

Fair enough. :)

**Comment by rudiservo** [comment]
@oerdnj what about the .phar, it needs unzip and that is about it. Not a very clean solution, but it's something.
