### ISSUE TITLE
PHP7.3 INTL issue

### ISSUE THREAD

**Issue by Webonaute** [oerdnj/deb.sury.org#1142]
I am using symfony with php 7.3.
Since this morning update (php7.3.4.1), my api containing language validation start crashing with memory exhausted.

Symfony\Component\Validator\Constraints\LanguageValidator
$languages = Intl::getLanguageBundle()->getLanguageNames(); 

This line cause the memory leak.

using ubuntu 18.04

**Comment by oerdnj** [comment]
I bumped the icu version to 64.1 during the day. Could you upgrade to latest (+3) version and if that still leaks report this to the upstream bug database?

Also please use the issue template next time, it asks all the right questions...

**Comment by Webonaute** [comment]
php7.3-intl/bionic,now 7.3.4-1+ubuntu18.04.1+deb.sury.org+3 amd64 [installed]

how do I report issue to upstream database?

**Comment by tlacroix** [comment]
Hi, we're already running +3 here, and we have the same problem:

```
$ apt list --installed | grep php7.3-intl
php7.3-intl/bionic,now 7.3.4-1+ubuntu18.04.1+deb.sury.org+3 amd64 [installed]
```

Also, we seem to be running the proper version of ICU (64.1):
```
Internationalization support    enabled
version    1.1.0
ICU version    64.1
ICU Data version    64.1
ICU TZData version    2018i
ICU Unicode version    12.0
```

**Comment by Webonaute** [comment]
seem that Updating symfony/intl (v4.2.4 => v4.2.5) fix our issue

**Comment by oerdnj** [comment]
Thanks for letting us know!

**Comment by oerdnj** [comment]
Looks like symfony/intl has it's own copy of icu data: https://github.com/symfony/intl/commit/d2ac83703951bc3206e9ea3f6114b355de14e3ce
