### ISSUE TITLE
impossible to dowload php-zip extension

### ISSUE THREAD

**Issue by LukaAyel** [oerdnj/deb.sury.org#1143]
Hi guys,

Firstly, I'm sorry for my english.
Secondly, I want to make a project around "Moodle LMS", to do it, I need to download "php-zip extension from sury repo".

But when I use this command : apt-get install php-zip, I get this error =

```
Err:1 https://packages.sury.org/php stretch/main amd64 libzip4 amd64 1.5.1-2+0~20190203094433.5+stretch~1.gbp77bdd3
  404  Not Found
E: Impossible de récupérer https://packages.sury.org/php/pool/main/libz/libzip/libzip4_1.5.1-2+0~20190203094433.5+stretch~1.gbp77bdd3_amd64.deb  404  Not Found
E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?
```
So I can't download this package...

Just to notice you, I could download php-curl or php-intl easy. Juste this extension has a problem.

thank you for your help.

Luka.

**Comment by oerdnj** [comment]
Jenkins log ate all disk space, so it looks like some packages got corrupted.  Just give it a while it will recover in a bit as packages get rebuilt again.

**Comment by oerdnj** [comment]
Also make sure that you run `apt-get update` first.

**Comment by LukaAyel** [comment]
I tried apt-update and got some message error with "sury".
I decident to comeback on previous version php7.0 during the time that doesn't work

**Comment by oerdnj** [comment]
> got some message error with "sury".

Which error?  Those are the important bits...

Also please use Bug template when filling issue with this repository.

**Comment by LukaAyel** [comment]
I'm sorry... But thank you for your help.
`Après cette opération, 236 ko d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] o
Err:1 https://packages.sury.org/php stretch/main amd64 libzip4 amd64 1.5.1-2+0~2                                                                                        0190203094433.5+stretch~1.gbp77bdd3
  404  Not Found
E: Impossible de récupérer https://packages.sury.org/php/pool/main/libz/libzip/l                                                                                        ibzip4_1.5.1-2+0~20190203094433.5+stretch~1.gbp77bdd3_amd64.deb  404  Not Found
E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-                                                                                        get update ou essayer avec --fix-missing ?
root@nomdedomaine:/home/Luka# apt update
Atteint:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Atteint:3 http://deb.debian.org/debian stretch-updates InRelease
Atteint:4 http://deb.debian.org/debian stretch-backports InRelease
Atteint:5 http://deb.debian.org/debian stretch Release
Réception de:6 https://packages.sury.org/php stretch InRelease [6 760 B]
Err:6 https://packages.sury.org/php stretch InRelease
  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est                                                                                         pas disponible : NO_PUBKEY B188E2B695BD4743
6 760 o réceptionnés en 0s (11,2 ko/s)
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
All packages are up to date.
W: An error occurred during the signature verification. The repository is not up                                                                                        dated and the previous index files will be used. GPG error: https://packages.sur                                                                                        y.org/php stretch InRelease: Les signatures suivantes n'ont pas pu être vérifiée                                                                                        s car la clé publique n'est pas disponible : NO_PUBKEY B188E2B695BD4743
W: Impossible de récupérer https://packages.sury.org/php/dists/stretch/InRelease                                                                                          Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est                                                                                         pas disponible : NO_PUBKEY B188E2B695BD4743
W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés,                                                                                         ou les anciens ont été utilisés à la place.`

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1129
