### ISSUE TITLE
php7.2-intl on Stretch is not installable anymore (gets removed on update => breaks system!)

### ISSUE THREAD

**Issue by wackerm** [oerdnj/deb.sury.org#1144]
First: thanks a lot for all your efforts keeping the php and debian world happy!!!

**Describe the bug**
After update from 10th april 2019 the current php7.2 setup our debian stretch server broke on one of our production web servers, we experienced problems and had to downgrade.

The package php7.2-intl has been removed during the update, because it needs libicu64, but for stretch the current version is 57(!). the previous version of php7.2-intl was running fine and the php7.0-intl is also working good.

**To Reproduce**
Try to install php7.2-common and php7.2-intl from sury (apt-get install...) on a plain debian stretch system.

**Expected behavior**
1.) System should never break on simple apt-get upgrade
2.) If there is a need to depend on libicu64, please provide this as package so it could be found and upgraded during php7.2-intl-upgrade and php7.2-intl will not be removed
3.) if there is no really need to use a newer libicu-version, please stick to the available version (57 for debian stretch)

**Distribution:**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org/php

**Package(s):**
apt-cache policy php7.2-intl:
```
php7.2-intl:
  Installiert:           (keine)
  Installationskandidat: 7.2.17-1+0~20190410151005.18+stretch~1.gbp23a36d
  Versionstabelle:
     7.2.17-1+0~20190410151005.18+stretch~1.gbp23a36d 100
         -1 https://packages.sury.org/php stretch/main amd64 Packages
     7.2.16-1+0~20190307202415.17+stretch~1.gbpa7be82 -1
        100 /var/lib/dpkg/status
````

**Comment by oerdnj** [comment]
> 1.) System should never break on simple apt-get upgrade

It does not. Only dist-upgrade would do that and it must be confirmed by the operator.

> 2.) If there is a need to depend on libicu64, please provide this as package so it could be found and upgraded during php7.2-intl-upgrade and php7.2-intl will not be removed

It is provided, I suggest you fix your apt pinning.
