### ISSUE TITLE
Opcache symlink issue with PHP 7.3.4 upgrade

### ISSUE THREAD

**Issue by vigneshgurusamy** [oerdnj/deb.sury.org#1145]
**Describe the bug**

After upgrading from PHP 7.3.3 to PHP 7.3.4, I started to see warnings like `Cannot load Zend OPcache - it was already loaded` on both fpm and cli.

When I checked fpm and cli conf.d folders, the opcache configuration file is symlinked again to a new file `20-opcache.ini` after the upgrade.

So there are two symlinked files `10-opcache.ini` and `20-opcache.ini` in conf.d folders and I had to remove one of the files to solve this issue.

Until PHP 7.3.3 opcache.ini file was symlinked as `10-opcache.ini`. After PHP 7.3.4 upgrade, opcache.ini file symlinked as `20-opcache.ini` without deleting the old one.

is this change intentional?

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture:  amd64
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**

Output of `apt-cache policy php7.3-opcache`

```
php7.3-opcache:
  Installed: 7.3.4-1+ubuntu18.04.1+deb.sury.org+3
  Candidate: 7.3.4-1+ubuntu18.04.1+deb.sury.org+3
  Version table:
 *** 7.3.4-1+ubuntu18.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Definitely not, but I can't reproduce it.

Could you check what are the contents of the `20-opcache.ini` target?  Do `10-opcache.ini` and `20-opcache.ini` symlinks point to the same file?

**Comment by oerdnj** [comment]
The file should look like this:
```
# cat /etc/php/7.3/mods-available/opcache.ini
; configuration for php opcache module
; priority=10
zend_extension=opcache.so
```

**Comment by vigneshgurusamy** [comment]
Both symlink targets were the same.

I just checked my `opcache.ini` and somehow my priority flag was missing.

```
# cat /etc/php/7.3/mods-available/opcache.ini
; Enable Zend OPcache extension
zend_extension=opcache.so
```

I guess that the reason it created a new file. So the default priority is 20?

**Comment by oerdnj** [comment]
Yes, the default priority is 20. Thanks, looks like a local configuration problem.
