### ISSUE TITLE
Unmet dependency on libpcre3 for php5.6-cli and php5.6-fpm on Debian Stretch

### ISSUE THREAD

**Issue by apydo** [oerdnj/deb.sury.org#1147]
**Describe the bug**
Upgrade on php5.6-cli and php5.6-fpm on Debian Stretch fails on libpcre3 unmet dependency

**To Reproduce**
1. sudo apt-get install php5.6-cli php5.6-fpm

**Expected behavior**
Upgrade of installed packages (currently 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9) to new version (5.6.40-6+0~20190412071127.13+stretch~1.gbp7ce36b).

**Distribution (please complete the following information):**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
$ apt-cache policy php5.6-fpm
php5.6-fpm:
  Installé : 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9
  Candidat : 5.6.40-6+0~20190412071127.13+stretch~1.gbp7ce36b
 Table de version :
     5.6.40-6+0~20190412071127.13+stretch~1.gbp7ce36b 400
        400 https://packages.sury.org/php stretch/main amd64 Packages
 *** 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9 100
        100 /var/lib/dpkg/status
$ apt-cache policy php5.6-cli
php5.6-cli:
  Installé : 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9
  Candidat : 5.6.40-6+0~20190412071127.13+stretch~1.gbp7ce36b
 Table de version :
     5.6.40-6+0~20190412071127.13+stretch~1.gbp7ce36b 400
        400 https://packages.sury.org/php stretch/main amd64 Packages
 *** 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9 100
        100 /var/lib/dpkg/status
$ apt-cache policy libpcre3
libpcre3:
  Installé : 2:8.39-3
  Candidat : 2:8.39-3
 Table de version :
     2:8.42-1+0~20190203125157.5+stretch~1.gbp79d75d 400
        400 https://packages.sury.org/php stretch/main amd64 Packages
 *** 2:8.39-3 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

**Additional context**
apt-get install fails on :
php5.6-cli : Depends: libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed
php5.6-fpm : Depends: libpcre3 (>= 2:8.41) but 2:8.39-3 is to be installed

**Comment by oerdnj** [comment]
Your too strict apt pinning is most probably the culprit.

apt-cache policy libpcre3

would be helpful here.

**Comment by oerdnj** [comment]
I just double checked, and libpcre3 is available from the repository.
