### ISSUE TITLE
Support Ubuntu 19.04

### ISSUE THREAD

**Issue by gjm** [oerdnj/deb.sury.org#1148]
Please add better support for Ubuntu 19.04, especially for PHP 7.3. There are only a few packages available for disco dingo.

**Comment by SeinopSys** [comment]
I'm missing the php-redis package as well, when I try to install it it pulls in php7.2-* packages

**Comment by gjm** [comment]
Just edited the issue title. No extensions are available for any version. In my particular case I need both 7.3 and 5.6 support.

**Comment by oerdnj** [comment]
I'll add Ubuntu 19.04 when Ubuntu 14.04 is removed - it should have already happened, but the announce email wasn't sent yet.

**Comment by rcapile** [comment]
after upgrading the extensions redis, memcached and igbinary are not available in PHP 7.1 and PHP 7.3, only in 7.2. The SO files are not present in 20160303 and 20180731 folders.

**Comment by oerdnj** [comment]
I updated the php-igbinary to 3.0.1+2.0.8, so this should not be a problem.

**Comment by oerdnj** [comment]
Most of the extensions have been uploaded and built.  I will deal with occasional build failures later.
