### ISSUE TITLE
recent mysql update fails

### ISSUE THREAD

**Issue by sztanpet** [oerdnj/deb.sury.org#115]
Linux feanor 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

only thing I changed was having a custom systemd service file, full logs at http://hastebin.com/taxeditoqo.avrasm

    Setting up mysql-server-5.6 (5.6.25-3+deb.sury.org~vivid+1) ...
    flag provided but not defined: -p
    Usage of logger:
      -config string
            config path
    flag provided but not defined: -p
    Usage of logger:
      -config string
            config path
    dpkg: error processing package mysql-server-5.6 (--configure):
     subprocess installed post-installation script returned error exit status 2
    dpkg: dependency problems prevent configuration of mysql-server:
     mysql-server depends on mysql-server-5.6; however:
      Package mysql-server-5.6 is not configured yet.

    dpkg: error processing package mysql-server (--configure):
     dependency problems - leaving unconfigured
    No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                              Errors were encountered while processing:
     mysql-server-5.6
     mysql-server
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by oerdnj** [comment]
Could you edit `/var/lib/dpkg/info/mysql-server-5.6.postinst` add -x to exec stanza (first line) and run `dpkg --configure mysql-server-5.6`?

**Comment by oerdnj** [comment]
That should give us more hints on what has happened. I have recently synced the package with Debian version, so there might be some quirks...

**Comment by sztanpet** [comment]
sure thing, here you go http://hastebin.com/sededuzava.md

**Comment by oerdnj** [comment]
Could you try changing:
```ERR_LOGGER='logger -p daemon.err -t mysqld_safe -i'```
to
```ERR_LOGGER='logger -t mysqld_safe -i'```

Perhaps there's an incompatible logger on vivid?

**Comment by sztanpet** [comment]
it complained about both `-t` and both `-i` too, so i just removed everything

http://hastebin.com/ojepanurap.md

**Comment by sztanpet** [comment]
i do not quite know why its complaining about it, the manual for logger shows the arguments just fine, so maybe its something with my packages?

**Comment by oerdnj** [comment]
Hmm, now something complains about invalid config path, what happens if you run:
```
/usr/sbin/mysqld --bootstrap --user=mysql --skip-grant-tables
```
manually?

**Comment by sztanpet** [comment]
it runs fine, http://hastebin.com/ojapokafum.vbs had mysql running so had to stop it while it tried to run, but it finished fine

**Comment by oerdnj** [comment]
Perhaps that was the error? Could you retry the postinst script with stopped MySQL 5.6?

**Comment by sztanpet** [comment]
yes, it ran and finished fine

**Comment by oerdnj** [comment]
Hmm, then I suppose the postinst script didn't handle the custom systemd script and it failed to stop mysql server before the installation. All hidden behind cryptic errors from logger... :(

**Comment by sztanpet** [comment]
hmm, the custom service file is just running mysqld directly instead of mysqld_safe,
oh well, at least i know what to do next time :)

    # MySQL systemd service file

    [Unit]
    Description=MySQL Community Server
    After=network.target

    [Install]
    WantedBy=multi-user.target

    [Service]
    User=mysql
    Group=mysql
    PermissionsStartOnly=true
    ExecStartPre=/usr/share/mysql/mysql-systemd-start pre
    ExecStart=/usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --open-files-limit=100000 --pid
    ExecStartPost=/usr/share/mysql/mysql-systemd-start post
    TimeoutSec=600
    Restart=on-failure
    RuntimeDirectory=mysqld
    RuntimeDirectoryMode=755

**Comment by oerdnj** [comment]
No worries, glad to help to debug the issue :)
