### ISSUE TITLE
Installing php7.2-memcached from the Ubuntu PPA brings in PHP 7.3

### ISSUE THREAD

**Issue by choult** [oerdnj/deb.sury.org#1150]
**Describe the bug**

In assembling a Docker container running Ubuntu 16.04 Xenial, I'm looking to specifically install PHP 7.2 from your PPA. Mostly this functions entirely as expected, but when installing the `php7.2-memcached` extension, its requirement for `php-igbinary` appears to bring in PHP 7.3, and also establishes configuration directories under `/etc/php` for `5.6`, `7.0`, `7.1`, `7.2` and `7.3`. Running `php -v` verifies the CLI is using `7.3`.

The only workaround I've found is to use `update-alternatives` to point `php` etc to the 7.2 binaries.

This appears to be a similar issue to #968 but my understanding is that was quickly resolved in October 2018.

**To Reproduce**

Given I have not attempted to recreate on a VM or bare metal, here are the relevant `RUN` lines from the Dockerfile:

```
FROM ubuntu:xenial
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
RUN apt-get update
RUN apt-get -y install php7.2 php7.2-common php7.2-mysql curl php7.2-curl php7.2-memcached php7.2-simplexml php7.2-dom php7.2-soap
```

This results in:

```
Step 14/51 : RUN apt-get -y install php7.2 php7.2-common php7.2-mysql curl php7.2-curl php7.2-memcached php7.2-simplexml php7.2-dom php7.2-soap
 ---> Running in 3ae4e65dcf67
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapache2-mod-php7.2 libargon2-0 libbsd0 libcurl3 libedit2 libmemcached11
  libpcre2-8-0 libpcre3 libphp7.3-embed libsodium23 libssl1.1 libxslt1.1
  php-common php-igbinary php-msgpack php7.2-cli php7.2-json php7.2-opcache
  php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-opcache
  php7.3-readline psmisc tzdata
```

Removing `php7.2-memcached` from the installation list results in:

```
Step 14/51 : RUN apt-get -y install php7.2 php7.2-common php7.2-mysql curl php7.2-curl php7.2-simplexml php7.2-dom php7.2-soap
 ---> Running in 6b7827bc54e6
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapache2-mod-php7.2 libargon2-0 libbsd0 libcurl3 libedit2 libpcre3
  libsodium23 libssl1.1 libxslt1.1 php-common php7.2-cli php7.2-json
  php7.2-opcache php7.2-readline psmisc tzdata
```

**Expected behavior**

 - PHP 7.3 should not be installed

**Distribution (please complete the following information):**

 - OS: Ubuntu 16.04 Xenial
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

```php-memcached:
  Installed: 3.1.3+2.2.0-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 3.1.3+2.2.0-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 3.1.3+2.2.0-1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.0-51-ge573a6e+2.2.0-2build2 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#why-is-php73-cli-always-installed

**Comment by choult** [comment]
Thank you for the link, but adding `--no-install-recommends` as per point 1 makes no difference (see below); also note that point 2 suggests using the explicit PHP version package name, and my process was already doing this.

Any other background you can help with @oerdnj ?

```Step 14/51 : RUN apt-get -y --no-install-recommends install php7.2 php7.2-common php7.2-mysql curl php7.2-curl php7.2-memcached php7.2-simplexml php7.2-dom php7.2-soap
 ---> Running in fc71a6b708fd
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapache2-mod-php7.2 libargon2-0 libbsd0 libcurl3 libedit2 libmemcached11
  libpcre2-8-0 libpcre3 libphp7.3-embed libsodium23 libssl1.1 libxslt1.1
  php-common php-igbinary php-msgpack php7.2-cli php7.2-json php7.2-opcache
  php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-opcache
  php7.3-readline psmisc tzdata
```

**Comment by oerdnj** [comment]
Actually, point 2) exactly describes your use case.

**Comment by choult** [comment]
You are quite right, that's a total   comprehension fail on my part - I
focused on the explicit versioning part not the dependency part.

Thanks for your patience...

**Comment by choult** [comment]
For posterity, requiring `php7.2-cli` fixes this:

```
Step 14/51 : RUN apt-get -y --no-install-recommends install php7.2 php7.2-common php7.2-mysql curl php7.2-curl php7.2-simplexml php7.2-dom php7.2-soap     php7.2-cli php7.2-memcached
 ---> Running in 7addf5438e04
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapache2-mod-php7.2 libargon2-0 libbsd0 libcurl3 libedit2 libmemcached11
  libpcre3 libsodium23 libssl1.1 libxslt1.1 php-common php-igbinary
  php-msgpack php7.2-json php7.2-opcache php7.2-readline psmisc tzdata
```

**Comment by oerdnj** [comment]
Not really, it was the php7.2-json as described in the link. php7.2-cli pulls php7.2-json, so that’s why it helped.
