### ISSUE TITLE
When Php 7.1 openssl version changed from 1.0 to 1.1 ?

### ISSUE THREAD

**Issue by Cyrille37** [oerdnj/deb.sury.org#1151]
Hello,
and thanks a lot for your great work.

Can you tell me when your Ph7.1 package changed from openssl 1.0.x to openssl 1.1.x please ?

Cheers,
Cyrille.

**Comment by oerdnj** [comment]
Quite a long time ago, the issue tracker might give you some hints:

https://github.com/oerdnj/deb.sury.org/issues?page=2&q=is%3Aissue+openssl&utf8=✓
