### ISSUE TITLE
PHP 7.3.5 / 7.2.18

### ISSUE THREAD

**Issue by natenate19** [oerdnj/deb.sury.org#1152]
PHP 7.3.5 and 7.2.18 are out.  Please update the ppa and dpa when you have the time.

https://www.php.net/ChangeLog-7.php#7.3.5

Thanks as always.

**Comment by oerdnj** [comment]
PPA is almost updated for all archs, and DPA is building:

https://calcifer.rfc1925.org/view/PHP/job/php_php7.3-binaries/39/
https://calcifer.rfc1925.org/view/PHP/job/php_php7.2-binaries/25/
https://calcifer.rfc1925.org/view/PHP/job/php_php7.1-binaries/19/
https://calcifer.rfc1925.org/view/PHP/job/php_php7.0-binaries/14/
https://calcifer.rfc1925.org/view/PHP/job/php_php5.6-binaries/17/
