### ISSUE TITLE
Missing php7.2-cli for ubuntu/trusty 

### ISSUE THREAD

**Issue by klipach** [oerdnj/deb.sury.org#1153]
Looks like after todays update repository for ubuntu/trusty is broken.

**Comment by oerdnj** [comment]
Trusty is EOL: https://www.patreon.com/posts/ubuntu-14-04-php-22093917
https://lists.ubuntu.com/archives/ubuntu-announce/2019-May/000244.html

**Comment by cerw** [comment]
Is there archive of old repo? somwhere? prosim?

**Comment by koshatul** [comment]
> Is there archive of old repo? somwhere? prosim?

Also interested, using Travis CI Enterprise and the trusty build images can't be rebuilt now, trusty is still the default docker image for builds.
