### ISSUE TITLE
Problem with repo

### ISSUE THREAD

**Issue by HOSTED-POWER** [oerdnj/deb.sury.org#1154]
Debian Stretch

Err:15 https://packages.sury.org/php stretch/main amd64 Packages
  Writing more data than expected (111903 > 111896)
  Hashes of expected file:
   - Filesize:111896 [weak]
   - SHA256:0c29f6482b2875eddb99aedb45ec662f0d906873f57233eed96658b93cc80bf8
   - SHA1:f9d4632e7cd069a2ff93ddd926599f377f4283fa [weak]
   - MD5Sum:efc9757b23177fe90b0b156f2aceee39 [weak]
  Release file created at: Fri, 03 May 2019 11:31:04 +0000
Hit:19 http://packages.blackfire.io/debian any InRelease
Hit:17 https://packagecloud.io/varnishcache/varnish41/debian stretch InRelease
Fetched 6760 B in 1s (4233 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (111903 > 111896)
   Hashes of expected file:
    - Filesize:111896 [weak]
    - SHA256:0c29f6482b2875eddb99aedb45ec662f0d906873f57233eed96658b93cc80bf8
    - SHA1:f9d4632e7cd069a2ff93ddd926599f377f4283fa [weak]
    - MD5Sum:efc9757b23177fe90b0b156f2aceee39 [weak]
   Release file created at: Fri, 03 May 2019 11:31:04 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by HOSTED-POWER** [comment]
Now a few minutes later it seems to work.

**Comment by oerdnj** [comment]
The repo is behind CDN, so there might be occasional synchronization issue.

**Comment by tigerlinux** [comment]
Good afternoon,

I think it is happening again. Look (this is from a Debian9 machine just now):

root@XXXXXXX:~# apt clean
root@XXXXXXX~# apt update
Get:1 https://packages.sury.org/php stretch InRelease [6,760 B]
Ign:2 http://ftp.us.debian.org/debian stretch InRelease                                                         
Hit:3 http://files.freeswitch.org/repo/deb/debian-release stretch InRelease
Hit:4 http://ftp.us.debian.org/debian stretch-updates InRelease
Hit:5 http://ftp.us.debian.org/debian stretch Release
Get:6 https://packages.sury.org/php stretch/main amd64 Packages [134 kB]
Err:6 https://packages.sury.org/php stretch/main amd64 Packages                                    
  Writing more data than expected (133734 > 133677)
  Hashes of expected file:
   - Filesize:133677 [weak]
   - SHA256:cee3d783f205d7205c225d4a6223114769e6c07e388e5de3260bfcf8f24b7caf
   - SHA1:989a450eab3803987757c8a40340690f0cf51398 [weak]
   - MD5Sum:ae16b8c96e6ef5f717869b16903de029 [weak]
  Release file created at: Thu, 23 Jan 2020 17:09:55 +0000
Hit:7 http://security.debian.org/debian-security stretch/updates InRelease                         
Hit:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease                     
Fetched 6,760 B in 0s (7,536 B/s)    
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (133734 > 133677)
   Hashes of expected file:
    - Filesize:133677 [weak]
    - SHA256:cee3d783f205d7205c225d4a6223114769e6c07e388e5de3260bfcf8f24b7caf
    - SHA1:989a450eab3803987757c8a40340690f0cf51398 [weak]
    - MD5Sum:ae16b8c96e6ef5f717869b16903de029 [weak]
   Release file created at: Thu, 23 Jan 2020 17:09:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

The machine is located at Detroit.
