### ISSUE TITLE
Some PHP 7.1 packages not installable

### ISSUE THREAD

**Issue by jasoooon** [oerdnj/deb.sury.org#1155]
**Describe the bug**
Hello, as of this morning, we are unable to install PHP 7.1 packages, including php7.1-mysql, php7.1-curl, php7.1-gd, and php7.1-imap. We see errors like this:

```
apt-get install php7.1-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php7.1-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

I don't see those individual packages listed here: https://launchpad.net/~ondrej/+archive/ubuntu/php/+index?batch=75&memo=150&start=150

The core PHP7.1 package installs fine.

May they have been removed?

**To Reproduce**
1. apt-get install php7.1-mysql
2. See error: Package php7.1-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Expected behavior**
php7.1-mysql is installed

**Distribution (please complete the following information):**
 - OS: Ubuntu 14.04
 - Architecture: amd64
 - Repository: deb.sury.org ppa:ondrej/php

**Package(s) (please complete the following information):**
php7.1-curl
php7.1-gd
php7.1-imap

**Comment by jasoooon** [comment]
Sorry, we just came across https://www.patreon.com/posts/ubuntu-14-04-php-22093917, which probably explains the problem.

**Comment by oerdnj** [comment]
Dup of #1153
