### ISSUE TITLE
Entities excepted

### ISSUE THREAD

**Issue by Nulos** [oerdnj/deb.sury.org#1156]
**Describe the bug**
We have a problem with php-intl since version PHP 7.2.17.
When we use the NumberFormatter class, special characters are put in place of space.

**To Reproduce**

Our PHP version:
```
#php -v
PHP 7.2.18-1+0~20190503103213.21+stretch~1.gbp101320 (cli) (built: May  3 2019 10:32:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18-1+0~20190503103213.21+stretch~1.gbp101320, Copyright (c) 1999-2018, by Zend Technologies

```

Create php file with this code:
```
echo "<?php
\$numberFormatter = new NumberFormatter( \"fr_FR\", NumberFormatter::CURRENCY );
\$numberFormatter->setAttribute( NumberFormatter::MAX_FRACTION_DIGITS, 2 );
\$formatedNumber = \$numberFormatter->format( abs( '85537.54' ) );
var_dump(\$formatedNumber);" > /tmp/test.php

```
Execute the file (with putty):
```
# php /tmp/test.php
string(16) "85?537,54 €"
```

**Expected behavior**

$formatedNumber returns the amount with a special character.
The correct answer should have a space : string(16) "85 537,54 €"

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64 / OpenStack VM
 - Repository: deb https://packages.sury.org/php/ stretch main

**Additional context**
We have no problem when we compile PHP

Thanks for the help!

**Comment by todeveni** [comment]
I bet that special character is a (narrow) non-breaking space, which is used as a thousands separator on some locales.

**Comment by Nulos** [comment]
Thank you for your answer. 
But we do not have the problem when PHP is compiled.

**Comment by oerdnj** [comment]
Are you using current icu library for the custom build?

**Comment by oerdnj** [comment]
You can install updated libicu-dev from the ppa

**Comment by Nulos** [comment]
Thank you for your help!.
libicu-dev is not installed on the server. Even when installing it, I always have an empty rectangle at the palce of a space.

**Comment by oerdnj** [comment]
I am asking whether you are compiling your custom PHP version with updated icu package.  Simply installing libicu-dev on the server doesn't do anything.

**Comment by Nulos** [comment]
Hello
Thank you for your help. This is how I compile PHP:
`apt install -y apt-transport-https lsb-release ca-certificates curl screen vim rsync
apt update && \
apt install -y libzip-dev bison autoconf build-essential pkg-config git-core \
libltdl-dev libbz2-dev libxml2-dev libxslt1-dev libssl-dev libicu-dev \
libpspell-dev libenchant-dev libmcrypt-dev libpng-dev libjpeg-dev \
libfreetype6-dev default-libmysqlclient-dev libreadline-dev libcurl4-openssl-dev

wget http://fr2.php.net/get/php-7.2.18.tar.gz/from/this/mirror -O php-7.2.18.tar.gz
tar xzvf php-7.2.18.tar.gz
cd php-7.2.18
./buildconf --force
CONFIGURE_STRING="--prefix=/etc/php7 --with-bz2 --with-zlib --enable-zip --disable-cgi \
   --enable-soap --enable-intl --with-openssl --with-readline --with-curl \
   --enable-ftp --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
   --enable-sockets --enable-pcntl --with-pspell --with-enchant --with-gettext \
   --with-gd --enable-exif --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl \
   --enable-bcmath --enable-mbstring --enable-calendar --enable-simplexml --enable-json \
   --enable-hash --enable-session --enable-xml --enable-wddx --enable-opcache \
   --with-pcre-regex --with-config-file-path=/etc/php7/cli \
   --with-config-file-scan-dir=/etc/php7/etc --enable-cli --enable-maintainer-zts \
   --with-tsrm-pthreads --enable-debug"
./configure $CONFIGURE_STRING
make && make install

chmod o+x /etc/php7/bin/phpize
chmod o+x /etc/php7/bin/php-config

cd $HOME/php-7.2.18
mkdir -p /etc/php7/cli/
cp php.ini-production /etc/php7/cli/php.ini
echo "zend_extension=opcache.so" | tee -a /etc/php7/cli/php.ini
ln -s /etc/php7/bin/php /usr/bin/php`
