### ISSUE TITLE
php 5.6 ubuntu 14.04 apache dependency

### ISSUE THREAD

**Issue by sdwarwick** [oerdnj/deb.sury.org#116]
our server uses nginx exclusively - 
have been looking to upgrade to php 5.6 using  ppa:ondrej/php5-5.6

the dependency list seems to include the entire apache server executable.   Is this necessary? 

apache2 apache2-bin apache2-data apache2-utils libapache2-mod-php5 libapr1
  libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.1-0 libonig2
  libqdbm14 php5-cli php5-common php5-curl php5-fpm php5-gd php5-json
  php5-mcrypt php5-mysql php5-readline

**Comment by oerdnj** [comment]
It does not. it's just an apt quirk. Install "apt-get install php5 php5-fpm" and you'll be fine.
