### ISSUE TITLE
PHP packages lists empty on Ubuntu 14.04, can't install PHP 5.6

### ISSUE THREAD

**Issue by ThomasBeagle** [oerdnj/deb.sury.org#1161]
I am trying to install PHP5.6 on Ubuntu 14.04.6 LTS

I have run the following commands:

```
sudo apt-get install software-properties-common
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```

The addition of the repository seemed to work without error.

However I still cannot install php5.6 as it is not found by apt-get or apt-cache search

Upon examining /var/lib/apt/lists I found the following files:

```
-rw-r--r-- 1 root root 20898 May  3 10:10 ppa.launchpad.net_ondrej_php_ubuntu_dists_trusty_InRelease
-rw-r--r-- 1 root root     0 May  3 10:10 ppa.launchpad.net_ondrej_php_ubuntu_dists_trusty_main_binary-amd64_Packages
-rw-r--r-- 1 root root     0 May  3 10:10 ppa.launchpad.net_ondrej_php_ubuntu_dists_trusty_main_binary-i386_Packages
-rw-r--r-- 1 root root     0 May  3 10:10 ppa.launchpad.net_ondrej_php_ubuntu_dists_trusty_main_i18n_Translation-en
```

The Packages and Translation-en files are 0 bytes in length. I assume this is the source of the problem.

This is on Ubuntu 14.04.6 LTS running on Linode in Tokyo. 

Output of uname -a "Linux meegoreng 4.18.16-x86_64-linode118 #1 SMP PREEMPT Mon Oct 29 15:38:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"

**Comment by todeveni** [comment]
#1153

**Comment by ThomasBeagle** [comment]
Oh. As todeveni kindly pointed out, Trusty (14.04) support has been [dropped as of April 2019](https://www.patreon.com/posts/ubuntu-14-04-php-22093917).
