### ISSUE TITLE
Trusty PHP7 repository became empty, it is no longer possible to install anything

### ISSUE THREAD

**Issue by shurkaxaa** [oerdnj/deb.sury.org#1162]
**Describe the bug**
It is no longer possible to install anything on Ubuntu 14.04 Trusty from ppa:ondrej/php PPA repository. For some reason repository is empty now.
Two weeks ago repository was functioning properly.

**To Reproduce**
1. add-apt-repository ppa:ondrej/php
2. apt update
3. apt install php7.0
4. Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0
E: Couldn't find any package by regex 'php7.0'

**Expected behavior**
Package installed

**Distribution (please complete the following information):**
 - OS: Ubuntu 14.04.6 LTS trusty
 - Architecture: amd64
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
root@web01:/etc/apt/sources.list.d# apt-cache policy php7.0
N: Unable to locate package php7.0
N: Couldn't find any package by regex 'php7.0'

**Additional context**
On server installed two weeks ago package is installed properly.
Right now packages are missing at URL pointed by repository for Ubuntu 14.04
http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.0/

vagrant@the-hpo-www:/var/cache/apt/archives$ apt-cache policy php7.0
php7.0:
  Installed: 7.0.33-6+ubuntu14.04.1+deb.sury.org+3
  Candidate: 7.0.33-6+ubuntu14.04.1+deb.sury.org+3
  Version table:
 *** 7.0.33-6+ubuntu14.04.1+deb.sury.org+3 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by todeveni** [comment]
#1153
