### ISSUE TITLE
Adding the APT key fails with 403 Forbidden when using ansible apt_key module (doesn't set User-Agent header)

### ISSUE THREAD

**Issue by sebastic** [oerdnj/deb.sury.org#1164]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
Adding the APT key fails with 403 Forbidden when using ansible:
```
fatal: [host.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at https://packages.sury.org/php/apt.gpg: HTTP Error 403: Forbidden"}
```

**To Reproduce**

Get https://packages.sury.org/php/apt.gpg without setting the User-Agent header:

1. `apt-get install libwww-perl`
2. `GET -USe https://packages.sury.org/php/apt.gpg | less`

**Expected behavior**
The file is downloaded even when no User-Agent is set in the request.

**Distribution:**
 - OS: Debian (stretch)
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
```
ansible:
  Installed: 2.2.1.0-2+deb9u1
  Candidate: 2.2.1.0-2+deb9u1
  Version table:
     2.7.5+dfsg-1~bpo9+1 100
        100 http://ftp.nl.debian.org/debian stretch-backports/main amd64 Packages
        100 http://ftp.nl.debian.org/debian stretch-backports/main i386 Packages
 *** 2.2.1.0-2+deb9u1 500
        500 http://ftp.nl.debian.org/debian stretch/main amd64 Packages
        500 http://ftp.nl.debian.org/debian stretch/main i386 Packages
        500 http://security.debian.org stretch/updates/main amd64 Packages
        500 http://security.debian.org stretch/updates/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
The Debian repository is actually behind Cloudflare and hosted on KeyCDN, so let's stick to whatever protection they are providing to the repository.  Adding User-Agent to HTTP headers is not really a big deal and the key could be downloaded normally with tools like wget or curl.

**Comment by oerdnj** [comment]
What I am saying is that this needs to be fixed in `ansible_apt_module`, not here, because the protection here is a sensible thing to do.

**Comment by sebastic** [comment]
It would be great if there was an option to set the User-Agent, but there isn't in the ansible version in stretch.

I guess you can't change the Cloudflare configuration to allow requests without a User-Agent header, because that's not much protection. The content of the request is much more important to determine if it's a requests that needs blocking or not.

**Comment by todeveni** [comment]
I tried this and it worked ok

```
tasks:
  - name: Add key
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
```
The default User-Agent in Ansible is actually `ansible-httpget`.

You could add the key from keyserver.

```
tasks:
  - name: Add key
    apt_key:
      id: B188E2B695BD4743
      keyserver: keyserver.ubuntu.com
```
