### ISSUE TITLE
Nginx TLS 1.3: alert protocol version (70) - PPA NGINX Mainline with HTTP/2

### ISSUE THREAD

**Issue by konstantingoretzki** [oerdnj/deb.sury.org#1166]
Hey there,
I am using the [PPA for NGINX Mainline with HTTP/2](https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline) for my server running Ubuntu 18.04.02 on x86_64/ amd64.

### The problem
However TLS 1.3 does not work. I've also tried the other [PPA for NGINX with HTTP/2](https://launchpad.net/~ondrej/+archive/ubuntu/nginx) and it did not work either.

If I connect to my server via openssl I get `alert protocol version - SSL alert number 70`:
```
$ openssl s_client -connect domain.tld:443 -tls1_3
CONNECTED(00000003)
140521092600320:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1536:SSL alert number 70
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 236 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
``` 
### What I did
I've enabled TLS 1.3 and the needed ciphers inside my vhost.conf, `nginx -t` does not show any errors:
```
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name XXX;

        access_log /var/log/nginx/XXX.log;
        error_log  /var/log/nginx/XXX.log;

        ssl_certificate     /etc/nginx/tls/cert.pem;
        ssl_certificate_key /etc/nginx/tls/key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on; 
        ssl_dhparam /etc/nginx/dhparam.pem;
        ssl_ciphers TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512;
        
        ...
}
```

I have installed the following versions of `nginx` and `openssl`:
**nginx**:
```
$ nginx -V
nginx version: nginx/1.15.9
built with OpenSSL 1.1.1a  20 Nov 2018 (running with OpenSSL 1.1.1b  26 Feb 2019)
[...]
```

```
$ apt-cache policy nginx
nginx:
  Installed: 1.15.9-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 1.15.9-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 1.15.9-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu bionic/main amd64 Packages
        500 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status
     1.14.0-0ubuntu1.2 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages
     1.14.0-0ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu bionic/main i386 Packages
```

**openssl**:
```
$ openssl version
OpenSSL 1.1.1b  26 Feb 2019
```

```
$ apt-cache policy openssl
openssl:
  Installed: 1.1.1b-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 1.1.1b-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 1.1.1b-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0g-2ubuntu4.3 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     1.1.0g-2ubuntu4 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

Client and server support the needed TLS 1.3 ciphers, I've also tested with SSL Labs and `testssl`.

I've installed multiple times the packages from the PPA and also removed `nginx` before installing. 
I did this by using the `add-ppa-repository` cmd:
```
$ sudo add-apt-repository ppa:ondrej/nginx-mainline
$ sudo apt update
```

Unfortunately I am out of ideas what causes the `alert protocol version` , hope someone can help. 

Thanks.

**Comment by moderndeveloperllc** [comment]
@konstantingoretzki Not getting that error, but I don't see anything obviously wrong with your configuration. Have you checked the error logs to see if it mentions anything? Do you get the error if you do:
```
openssl s_client -connect www.allcarepharmacy.com:443 -tls1_3
```

**Comment by konstantingoretzki** [comment]
@moderndeveloperllc Neither the error logs nor the access logs get filled with openssl and the tls1_3 parameter. Probably because the connection can not get established.

However it works perfectly for the website you've provided.

I've also set the SSL config temporarily inside the nginx.conf, also changed the order of TLS 1.2 and TLS 1.3, but without success.

Did you use the exact same PPA and installed `openssl` and `nginx` from it?

**Comment by konstantingoretzki** [comment]
Unfortunately I was not able to figure out why it did not work.
However with the recent updates of the openssl and nginx package of the official Ubuntu Bionic Beaver repo TLS 1.3 does now finally work, so I do not need the extra PPA anymore.

**Comment by maltris** [comment]
For anyone reading this:

The "nginx" teams launchpad version (https://launchpad.net/~nginx/+archive/ubuntu/stable) of 1.18.x nginx has this problem and is not able to support TLSv1.3. Best switch to original 1.14.x (18.04) or 1.18.x (20.04) of Ubuntu. I mailed the "nginx team, but did not receive any answer yet.

**Comment by teward** [comment]
> For anyone reading this:
> 
> The "nginx" teams launchpad version (https://launchpad.net/~nginx/+archive/ubuntu/stable) of 1.18.x nginx has this problem and is not able to support TLSv1.3. Best switch to original 1.14.x (18.04) or 1.18.x (20.04) of Ubuntu. I mailed the "nginx team, but did not receive any answer yet.

Completely irrelevant to Ondrej's repositories, and your issue needs reported to the nginx team on Launchpad (me).

I can't replicate this issue for Ondrej's PPA or the NGINX PPA that maltris is referring to either - pointing at a likely local configuration problem.  Out of the box, TLS 1.3 works provided you have the updated libssl installed from the main Ubuntu repositories (or Ondrej's nginx ppa), and I remember testing this hard-core for the NGINX PPA on Launchpad (by the "nginx team")

**Comment by maltris** [comment]
> Completely irrelevant to Ondrej's repositories, and your issue needs reported to the nginx team on Launchpad (me).

This is the thread I found while looking up the symptoms. Therefore I added a note, so don't tell me whats completely irrelevant.

**Comment by PELock** [comment]
I have similar problems:

```
CONNECTED(00000003)
139800735507584:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../ssl/record/rec_layer_s3.c:1544:SSL alert number 70
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 240 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

OpenSSL v1.1.1d
NGINX 1.19.8

I have tried every possible combination of algorithms in my config file. It just fails every time.

I'm wondering if I need ECDSA keys from Letsencrypt to make TLS v1.3 work

```
openssl ciphers -s -v
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
DHE-RSA-AES256-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA256
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
ECDHE-RSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-RSA-AES128-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-ECDSA-AES256-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1
ECDHE-RSA-AES256-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES128-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA1
ECDHE-RSA-AES128-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA1
DHE-RSA-AES128-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA1
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
```
So the TLS 1.3 is there in openssl, nginx doesn't throw any errors from the configuration files, I'm not sure what could I check to find the cause of the problems? Any ideas?
