### ISSUE TITLE
php7.3-fpm packages completely bricks ARMv6 (RPi) systems

### ISSUE THREAD

**Issue by MichaIng** [oerdnj/deb.sury.org#1167]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
- **Occurs on ARMv6 devices only: Current reports RPi Zero and RPi 1B**
- When installing the current `php7.3-fpm` package from deb.sury.org repo, APT fails to configure the package when trying to start the service:
```
Setting up php7.3-fpm (7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b) ...

Creating config file /etc/php/7.3/fpm/php.ini with new version
Created symlink /etc/systemd/system/multi-user.target.wants/php7.3-fpm.service → /lib/systemd/system/php7.3-fpm.service.
Job for php7.3-fpm.service failed because a fatal signal was delivered to the control process.
See "systemctl status php7.3-fpm.service" and "journalctl -xe" for details.
invoke-rc.d: initscript php7.3-fpm, action "start" failed.
● php7.3-fpm.service - The PHP 7.3 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.3-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2019-05-14 01:09:43 BST; 165ms ago
     Docs: man:php-fpm7.3(8)
  Process: 11107 ExecStart=/usr/sbin/php-fpm7.3 --nodaemonize --fpm-config /etc/php/7.3/fpm/php-fpm.conf (code=killed, signal=ILL)
 Main PID: 11107 (code=killed, signal=ILL)

May 14 01:09:43 DietPi systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
May 14 01:09:43 DietPi systemd[1]: php7.3-fpm.service: Main process exited, code=killed, status=4/ILL
May 14 01:09:43 DietPi systemd[1]: Failed to start The PHP 7.3 FastCGI Process Manager.
May 14 01:09:43 DietPi systemd[1]: php7.3-fpm.service: Unit entered failed state.
May 14 01:09:43 DietPi systemd[1]: php7.3-fpm.service: Failed with result 'signal'.
dpkg: error processing package php7.3-fpm (--configure):
 subprocess installed post-installation script returned error exit status 1
```
- No log file is created yet, so currently no idea how to debug.
- This alone would be a minor issue, but the main problem is that the whole system is broken afterwards. Several system commands (systemctl, journalctl, reboot, shutdown, ...) fail with `Illegal instruction`. Currently all these seem to be `systemd` commands. We'll investigate further.
- When plugging off power and attempting boot, it fails with `kernel painc!`, possibly when attempting to initiate systemd.

**To Reproduce**
https://github.com/MichaIng/DietPi/issues/2794#issuecomment-492032163

**Expected behavior**
It should install successfully. Failing at some point can happen, but a whole system brick that requires a complete fresh OS install of course is a major critical issue!

**Distribution (please complete the following information):**
 - OS: DietPi (mainly Debian (Raspbian on RPi), using official Debian (Raspbian) repo packages)
 - Architecture: armv6l
 - Repository: https://packages.sury.org/php/dists/stretch/

**Package(s) (please complete the following information):**
`php7.3-fpm php7.3-apcu php7.3-curl php7.3-gd php7.3-mbstring php7.3-xml php7.3-zip` (current versions)
- But `php7.3-fpm` seems to cause the brick.

**Additional context**
Related discussion: https://github.com/MichaIng/DietPi/issues/2794

**Comment by oerdnj** [comment]
Raspbian isn’t Debian, this has been discussed many times in the past (check closed issues).

**Comment by MichaIng** [comment]
@oerdnj 
You mean your repo may cause such issues on Raspbian in general? That should be possibly communicated more prominent on the website, since generally most people assume that Debian and Raspbian are mostly identical. I never found a hint about this, instead found your repo to be THE PHP repository for RPi when doing web search.

However good to know.

**Comment by oerdnj** [comment]
> generally most people assume that Debian and Raspbian are mostly identical.

They are not mostly identical and never were - the explanation was given in a previous ticket. It exactly same as saying that i586 code is mostly identical to i386.

**Comment by MichaIng** [comment]
@oerdnj 
Jep understood. Practically this means that `deb.sury.org` does not support ARMv6 at all, since there are no `armel` packages, right? I read a bid through the Debian docs and looks like ARM-Hard-float is as you said just assured to run on ARMv7, while `armel` is for older ARM versions.

So ARMv6-Hard-float is then indeed just an RPi/Raspbian special. I never really realized this since there are so much 3rd party repos and packages where `armhf` works on the ARMv6 RPis as well. However I guess these builds are done due to the high share of RPis on the marked, but do not follow what is intended by Debian.
