### ISSUE TITLE
[extension request] php-rdkafka PHP extension

### ISSUE THREAD

**Issue by weeclemans** [oerdnj/deb.sury.org#1168]
Hello oerdnj,
Please add php-rdkafka to your PPA

sources is here https://github.com/weeclemans/php-rdkafka

But have a little problem with a package.xml file, original source file https://pecl.php.net/get/rdkafka-3.1.0.tgz included 2 files (package.xml and package2.xml).  The file package.xml is  incorrect for a parser /usr/share/dh-php/pkg-pecl.mk.

What I need to do?

**Comment by oerdnj** [comment]
php-rdkafka has been packaged and uploaded.
