### ISSUE TITLE
[php7.0] php-ast module (for phan)

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#117]
I know you are probably overworked but this would be worth tinkering with...

_This extension exposes the abstract syntax tree generated by PHP 7. This extension is experimental and the representation of the syntax tree is not final._

https://github.com/nikic/php-ast

It's needed for this delicious project which takes using and investigating php7 to another level...

_Phan is a static analyzer for PHP. It requires PHP 7 with the php-ast extension loaded. The code you analyze with it can be written for any version of PHP._

https://github.com/rlerdorf/phan

**Comment by oerdnj** [comment]
Fixed in `php-ast_0.1.1-1+deb.sury.org~*+1` upload.
