### ISSUE TITLE
CloudFlare prevents apt update

### ISSUE THREAD

**Issue by lukavia** [oerdnj/deb.sury.org#1170]
I have a headless server without a browser. 
When I try to apt update I get: 

> Err:10 https://packages.sury.org/php stretch Release                                      
>   403  Forbidden
> Reading package lists... Done
> 

When I tried to curl the address I get a page from cloudflare. 
How should we overcome this?

**Comment by oerdnj** [comment]
The most probable reason would be suspicious activity has happened in the past from that said IP address (not necessarily from you) and it has a bad reputation. You can use IPv6, get different IPv4 address, connect via Tor, or rsync your own mirror copy from rsync://rsync.rfc1925.org

Or you can try opening ticket with CF.

**Comment by gkkovacs** [comment]
We are having the same issue. One of our firewalls suddenly got flagged by Cloudflare, now none of the Debian machines are able to download fresh keys via wget or the Release file via apt. Both result in 403 Forbidden errors, which is a Cloudflare captcha page btw.

Using a regular web browser (tested with Firefox) through the same firewall, and solving the captcha does not clear the IP from the blacklist for other user agents. Probably Cloudflare has no idea that these user agents are not attackers, 

I wonder if there is a way to whitelist them in the Cloudflare configuration, or probably you could lower the security level a notch.
