### ISSUE TITLE
Building PHP 7.1 container but including php7.1-redis updates to php 7.3

### ISSUE THREAD

**Issue by ktwbc** [oerdnj/deb.sury.org#1171]
**Unsupported distributions**
 - [X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
Very strange behavior, but I have a docker container being built on Ubuntu 18.4 installing php.71 which works fine, but I was originally missing php7.1-redis. When I added it, suddenly php 7.3 is being pulled in.

**To Reproduce**
1. Use the following Dockerfile:

```
FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Update apt-get local index
RUN apt-get -qq update

# Install
RUN apt-get update -y \
    && apt-get install awscli -y \
    && apt-get install software-properties-common -y --allow-unauthenticated \
    && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get install -y openjdk-8-jdk \
    && apt-get install -y redis-server wget curl git supervisor g++ make \
    && apt-get install -y php7.1 php7.1-xmlrpc php7.1-xml php7.1-mbstring php7.1-gmp php7.1-zip php7.1-json php7.1-curl php7.1-intl php7.1-mcrypt php7.1-gd php7.1-common php7.1-ldap php7.1-mysql --allow-unauthenticated
```

2. go into the container with a "docker run -it container_name /bin/bash'
3. Run php -v to test version
4. Change docker file to include php7.1-redis package
i.e. changing the last apt-get line to:
 && apt-get install -y php7.1 php7.1-xmlrpc php7.1-xml php7.1-mbstring php7.1-gmp php7.1-zip php7.1-json php7.1-redis php7.1-curl php7.1-intl php7.1-mcrypt php7.1-gd php7.1-common php7.1-ldap php7.1-mysql --allow-unauthenticated
5. Rerun docker build
6. again go into container with a docker run
7. php -v again

(If I then remove that package from the apt-get and then update the container, it will actually then downgrade back to php 7.1)

**Expected behavior**
Should be a flavor of 7.1
i.e. before including redis:
[ec2-user@ip-172-31-56-250 ~]$ docker run -it ec2-user_codebuild /bin/bash
root@2e682935d728:/tmp/node# php -v
PHP 7.1.29-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 09:51:29) ( NTS )

after including redis with no other changes and rebuilding container
[ec2-user@ip-172-31-56-250 ~]$ docker run -it ec2-user_codebuild /bin/bash
root@6af543e3193a:/tmp/node# php -v
PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

Instead by including php7.1-redis the php-v will now say 7.3.x

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
Described here: https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#why-is-php73-cli-always-installed

You’ll need to debug the container to see what package is pulling the version you don’t want.
