### ISSUE TITLE
segmentation error on pizero w armv6

### ISSUE THREAD

**Issue by tigernero79** [oerdnj/deb.sury.org#1172]
I tried to put PHP repository as I always did on a clean raspbian armv6 installation without gui, as I try to update the packages with sudo apt update && sudo apt dist-upgrade the vs system in brick giving me a segmentation error.  simply updating after entering your repository.  I speak of pizero w armv6

**Comment by todeveni** [comment]
See #988 

armv6 isn't supported, you need at least armv7-a
