### ISSUE TITLE
Fetal error: A TLS fetal alert has been received. 

### ISSUE THREAD

**Issue by yasirrose** [oerdnj/deb.sury.org#1174]
I am working on updating the PHP version 5.5.9 to 7.1 but the server is facing issues while connecting to package.sury.og. 

I am getting unable to fetch PHP repository with gnutls handshake error. I have searched and also updated the openssl version. But still, I am facing the same issue. After installing gnutls-cli and running command, I got the following error. Can any one help me with this issue? 

![Clipboard - May 21, 2019 5_22 PM](https://user-images.githubusercontent.com/5586359/58096329-444f6e80-7bee-11e9-98d5-ddb3787b5f28.png)

**Comment by oerdnj** [comment]
What is the distro version?

**Comment by yasirrose** [comment]
It is ubuntu 14.04.6 LTS

**Comment by oerdnj** [comment]
Ubuntu Trusty is EOL and not supported.

**Comment by yasirrose** [comment]
Is there any workaround for Trusty?
