### ISSUE TITLE
NumberFormatter Behavior

### ISSUE THREAD

**Issue by wandersonwhcr** [oerdnj/deb.sury.org#1176]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
The `NumberFormatter` class has an unexpected behavior when parsing currency values. When we use the Debian default PHP package, everything works fine.

**To Reproduce**
1. Save this code into `test.php` file:

```php
<?php

$formatter = new NumberFormatter('pt_BR', NumberFormatter::CURRENCY);
var_dump(PHP_VERSION);
var_dump($formatter->getPattern());
var_dump($formatter->parseCurrency('R$99,99', $currency));
var_dump($currency);
var_dump($formatter->getErrorMessage());
```

2. Run this source code with PHP CLI and check the output:

```
string(48) "7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991"
string(12) "¤ #,##0.00"
bool(false)
NULL
string(36) "Number parsing failed: U_PARSE_ERROR"
``` 

**Expected behavior**
We expect a correct parsing, like this output with default Debian PHP Package.

```
string(15) "7.0.33-0+deb9u3"
string(10) "¤#,##0.00"
float(99.99)
string(3) "BRL"
string(12) "U_ZERO_ERROR"
```

**Distribution (please complete the following information):**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

```
php7.0-intl:
  Installed: 7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991
  Candidate: 7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991
  Version table:
 *** 7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.33-0+deb9u3 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
```

**Comment by wandersonwhcr** [comment]
Other info about `intl`.

`php -i` from `7.0.33-0+deb9u3`

```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 57.1
ICU Data version => 57.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

`php -i` from `7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991`

```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 64.1
ICU Data version => 64.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

ICU version is not the same. Do we have a problem here? Yes, I think :(

**Comment by wandersonwhcr** [comment]
Other info about `intl`.

`php -i` from `7.0.33-0+deb9u3`

```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 57.1
ICU Data version => 57.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

`php -i` from `7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991`

```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 64.1
ICU Data version => 64.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

ICU version is not the same. Do we have a problem here? Yes, I think :(

**Comment by todeveni** [comment]
Don't know where to find correct changelogs (ICU? CLDR?) to see when/why the change has been made, but the later version is correct. According to `pt_BR` [locale](https://lh.2xlibre.net/locale/pt_BR/) `LC_MONETARY` there should be a space between currency symbol and value (`p_sep_by_space=1`). So the stock Debian version is apparently the bad result.

**Comment by wandersonwhcr** [comment]
Hello @todeveni. Thank you for the response :)

But I added a space between monetary symbol and value, and it didn't work.

```php
<?php

$formatter = new NumberFormatter('pt_BR', NumberFormatter::CURRENCY);
var_dump(PHP_VERSION);
var_dump($formatter->getPattern());
var_dump($formatter->parseCurrency('R$ 99,99', $currency));
var_dump($currency);
var_dump($formatter->getErrorMessage());
```

Output:

```
string(48) "7.0.33-7+0~20190503101027.13+stretch~1.gbp26f991"
string(12) "¤ #,##0.00"
bool(false)
NULL
string(36) "Number parsing failed: U_PARSE_ERROR"
```

PS: Sorry for the closed/reopened issue, I just clicked the wrong button :)

**Comment by todeveni** [comment]
It's actually a non-breaking space :)  (U+00A0)

```
$formatter = new NumberFormatter('pt_BR', NumberFormatter::CURRENCY);
var_dump(PHP_VERSION);
var_dump($formatter->getPattern());
var_dump($formatter->parseCurrency('R$ 99,99', $currency));
var_dump($currency);
var_dump($formatter->getErrorMessage());
```

```
string(5) "7.3.5"
string(12) "¤ #,##0.00"
float(99.99)
string(3) "BRL"
string(12) "U_ZERO_ERROR"
```

**Comment by wandersonwhcr** [comment]
Really?!

It works!

But I just question myself: will users insert a nbsp? :laughing: 

BTW, thank you!
