### ISSUE TITLE
php7.3-cli openssl on Xenial

### ISSUE THREAD

**Issue by aloonj** [oerdnj/deb.sury.org#1177]
**Describe the bug**
The Xenial package of php7.3-cli appears to be missing openssl, yet openssl is enabled fine in php-FPM.

**To Reproduce**
1. php -r "phpinfo();" | grep -i openssl
OpenSSL support => disabled (install ext/openssl)

**Expected behavior**
Openssl support should be enabled without any php.ini enabling required. Enabling in php.ini does not solve the problem.

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main

**Package(s) (please complete the following information):**
apt-cache policy php7.3-cli
php7.3-cli:
  Installed: 7.3.5-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 7.3.5-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
It's not the PHP from the repository, the OpenSSL is not missing:
```
# php -r "phpinfo();" | grep -i openssl
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.1b  26 Feb 2019
OpenSSL Header Version => OpenSSL 1.1.1b  26 Feb 2019
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
```

**Comment by oerdnj** [comment]
```
# php --version
PHP 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
