### ISSUE TITLE
[library request] librdkafka

### ISSUE THREAD

**Issue by weeclemans** [oerdnj/deb.sury.org#1179]
Hello oerdnj,

Please add a library package librdkafka to your PPA. The source of a package is here https://github.com/weeclemans/librdkafka
files debian/control and debian/changelog is changed

The original source is here
https://github.com/edenhill/librdkafka/archive/v1.0.1.tar.gz

Thank You

**Comment by todeveni** [comment]
Why would he package your fork of the original, which has already Debian packages built in [Confluent](https://docs.confluent.io/current/installation/available_packages.html).

**Comment by oerdnj** [comment]
I'm not doing this. The PHP-rdkafka packages build fine with stock Debian/Ubuntu librdkafka libraries.
