### ISSUE TITLE
[feature request] Apache compiled against more fresh openssl (Trusty Tahr)

### ISSUE THREAD

**Issue by olmari** [oerdnj/deb.sury.org#118]
I'd have basically one wish for apache2 PPA (for 14.04/ trusty tahr) you provide.
I'd be more than happy if it would be linked against openssl 1.0.2d (or whatever is latest at the times), for more recent mod_ssl, to be able to use "SSLOpenSSLConfCmd DHParameters" directive.
Currently mod_ssl is done against 1.0.1f.

**Comment by oerdnj** [comment]
I am sorry, but that would practically mean also backporting OpenSSL and I don't want to do that. The article https://weakdh.org/sysadmin.html says:

> If you are using Apache with LibreSSL, or Apache 2.4.7 and OpenSSL 0.9.8a or later, you can append the DHparams you generated earlier to the end of your certificate file.

So since this has a very simple workaround, thus the burden of taking care of OpenSSL is not worth it.

**Comment by oerdnj** [comment]
I have upgraded openssl in ppa:ondrej/apache2 due HTTP/2 support (for trusty and higher):
https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+packages
@olmari could you try upgrading if the DHParams works for you with those packages. I will do the same with php5 and php5-5.6 PPAs if everything is ok.

**Comment by olmari** [comment]
I updated and tested this just now, and now the SSLOpenSSLConfCmd works as expected! Thank you for this :heart: So you're good to go too :+1:
