### ISSUE TITLE
php7.1/7.2 libicu63 / libicu64 linkage ..

### ISSUE THREAD

**Issue by pickert** [oerdnj/deb.sury.org#1181]
I've tested with the freshest ubuntu 19.04 and debian-testing images as of today 5/29...

The php-intl is getting linked against your libicu64 package while the rest of the other packages (-common, -fpm etc) secondarily link against your libicu63 package via libxml2 .. As a result, it seems I'm having issues with applications getting memory leaks/infinite loops because of locale detection style problems.

Is there a regression that made this double versioning necessary by chance?

I can attach versions and output if necessary but this is all the freshest/most active versioning available.

**Comment by DennisBirkholz** [comment]
Libicu63 is the version provided by [Debian Testing/Buster](https://packages.debian.org/buster/libicu63). I have a similar problem with Debian Stable (aka Stretch): https://github.com/oerdnj/deb.sury.org/issues/1165

**Comment by pickert** [comment]
Indeed, quite messy .. Ended up going over a minimal ubu 19.04 image on
google cloud and building things out there.. =\

**Comment by oerdnj** [comment]
I have an updated libxml2 build ready. I’ll try to push it some time soon.

**Comment by oerdnj** [comment]
I think this has been solved by libxml2 update I did in the repository.  Can you confirm?

**Comment by pickert** [comment]
Debian buster has been handling it well lately I think, I'm waiting on your
19.10 builds to test on my other setup.. =)
https://github.com/oerdnj/deb.sury.org/issues/1262

**Comment by oerdnj** [comment]
The Ubuntu 19.10 packages are up, if you have a time to test those, I would appreciate it.

**Comment by pickert** [comment]
I'm testing currently with a PHP/doctrine/symphony application and am
having quality results with regards to the libicu and libxml2 includes...
Thank you Ondrej, I'll be continuing to stress and work on this throughout
the rest of the week and will keep you posted.
Again, thanks for all of your efforts and time man!

**Comment by oerdnj** [comment]
Thanks. I am closing the issue now, but feel free to reopen if you discover anything.  The `ldd` command should be your friend when looking at what links with what.
