### ISSUE TITLE
PHP 7.2.19

### ISSUE THREAD

**Issue by rmccullagh** [oerdnj/deb.sury.org#1183]
This is not a bug report, but it's a question. PHP 7.2.19 was released today with an essential security patch. https://www.php.net/ChangeLog-7.php#7.2.19

Does this PPA automatically build the release from the official PHP group?

**Comment by todeveni** [comment]
There's no automatic building. Also duplicate of #1182

**Comment by oerdnj** [comment]
What is "an essential security patch"?

**Comment by oerdnj** [comment]
Also closing as dup of #1182
