### ISSUE TITLE
[extension update]php-redis

### ISSUE THREAD

**Issue by radykal-com** [oerdnj/deb.sury.org#1184]
Hi,

Since 13th March there is a new version of the php-redis extension (v4.3.0).

Could be possible to update to it?

Regards,

**Comment by chalasr** [comment]
Having some blocking issues with the current available version, upgrading would be great.

**Comment by byan** [comment]
The new major stable version (v5.0.x) has been released at July 12.

**Comment by oerdnj** [comment]
Updated and uploaded.

**Comment by chalasr** [comment]
Thank you @oerdnj.
