### ISSUE TITLE
Debian 10 buster php-memcached build

### ISSUE THREAD

**Issue by imifarago** [oerdnj/deb.sury.org#1186]
The php-memcached package only available for arm in Debian 10 buster.
Can you please build for the amd64 architecture in debian 10 buster, so php-memcached module then can be used for php7.2 7.1 and 5.6?

**Comment by imifarago** [comment]
It was fast, thanks :)

**Comment by oerdnj** [comment]
Well, I haven't noticed it was missing the builds, so it was just one click... ;-)
