### ISSUE TITLE
LUA module not working with PHP7.3

### ISSUE THREAD

**Issue by alemax-xyz** [oerdnj/deb.sury.org#1187]
LUA module doesn't work with PHP7.3 any more. This is due to some [internal API changes](https://raw.githubusercontent.com/php/php-src/PHP-7.3/UPGRADING.INTERNALS).
```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'lua.so' (tried: /usr/lib/php/20180731/lua.so (/usr/lib/php/20180731/lua.so: undefined symbol: ZEND_HASH_GET_APPLY_COUNT), /usr/lib/php/20180731/lua.so.so (/usr/lib/php/20180731/lua.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
It seems like the issue was [fixed](https://github.com/laruence/php-lua/commit/f588c88528065af29095f01d8606a80d314376f7) upstream a while ago. After building the module from sources it worked just fine.

Is it possible to update the module to the latest release? Thanks!

**Comment by oerdnj** [comment]
Updated and uploaded.
