### ISSUE TITLE
PHALCON module not working with PHP7.3

### ISSUE THREAD

**Issue by kess78** [oerdnj/deb.sury.org#1188]
PHALCON module returns a Segmentation fault with PHP 7.3

**To Reproduce**
1. Install a standard Debian 9 amd64 Server
2. Run
`apt install libphp5.6-embed php5.6-bcmath php5.6-bz2 php5.6-cgi php5.6-cli php5.6-common php5.6-curl php5.6-dba php5.6-enchant php5.6-fpm php5.6-gd php5.6-gmp php5.6-imap php5.6-interbase php5.6-intl php5.6-json php5.6-ldap php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-odbc php5.6-opcache php5.6-pgsql php5.6-phpdbg php5.6-pspell php5.6-readline php5.6-recode php5.6-snmp php5.6-soap php5.6-sqlite3 php5.6-sybase php5.6-tidy php5.6-xml php5.6-xmlrpc php5.6-zip php5.6 libphp7.0-embed php7.0-bcmath php7.0-bz2 php7.0-cgi php7.0-cli php7.0-common php7.0-curl php7.0-dba php7.0-enchant php7.0-fpm php7.0-gd php7.0-gmp php7.0-imap php7.0-interbase php7.0-intl php7.0-json php7.0-ldap php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-odbc php7.0-opcache php7.0-pgsql php7.0-phpdbg php7.0-pspell php7.0-readline php7.0-recode php7.0-snmp php7.0-soap php7.0-sqlite3 php7.0-sybase php7.0-tidy php7.0-xml php7.0-xmlrpc php7.0-zip php7.0 libphp7.1-embed php7.1-bcmath php7.1-bz2 php7.1-cgi php7.1-cli php7.1-common php7.1-curl php7.1-dba php7.1-enchant php7.1-fpm php7.1-gd php7.1-gmp php7.1-imap php7.1-interbase php7.1-intl php7.1-json php7.1-ldap php7.1-mbstring php7.1-mcrypt php7.1-mysql php7.1-odbc php7.1-opcache php7.1-pgsql php7.1-phpdbg php7.1-pspell php7.1-readline php7.1-recode php7.1-snmp php7.1-soap php7.1-sqlite3 php7.1-sybase php7.1-tidy php7.1-xml php7.1-xmlrpc php7.1-zip php7.1 libphp7.2-embed php7.2-bcmath php7.2-bz2 php7.2-cgi php7.2-cli php7.2-common php7.2-curl php7.2-dba php7.2-enchant php7.2-fpm php7.2-gd php7.2-gmp php7.2-imap php7.2-interbase php7.2-intl php7.2-json php7.2-ldap php7.2-mbstring php7.2-mysql php7.2-odbc php7.2-opcache php7.2-pgsql php7.2-phpdbg php7.2-pspell php7.2-readline php7.2-recode php7.2-snmp php7.2-soap php7.2-sqlite3 php7.2-sybase php7.2-tidy php7.2-xml php7.2-xmlrpc php7.2-zip php7.2 libphp7.3-embed php7.3-bcmath php7.3-bz2 php7.3-cgi php7.3-cli php7.3-common php7.3-curl php7.3-dba php7.3-enchant php7.3-fpm php7.3-gd php7.3-gmp php7.3-imap php7.3-interbase php7.3-intl php7.3-json php7.3-ldap php7.3-mbstring php7.3-mysql php7.3-odbc php7.3-opcache php7.3-pgsql php7.3-phpdbg php7.3-pspell php7.3-readline php7.3-recode php7.3-snmp php7.3-soap php7.3-sqlite3 php7.3-sybase php7.3-tidy php7.3-xml php7.3-xmlrpc php7.3-zip php7.3`
3. Run
`apt install php-amqp php-apcu php-apcu-bc php-ast php-ds php-gearman php-geoip php-igbinary php-imagick php-mailparse php-memcache php-mongo php-mongodb php-msgpack php-oauth php-pear php-pecl-http php-pinba php-propro php-radius php-raphf php-redis php-rrd php-smbclient php-sodium php-solr php-ssh2 php-stomp php-uploadprogress php-uuid php-yaml php-zmq ghostscript memcached ttf-dejavu-core`
4. Result OK
`root@php:~# /usr/bin/php-cgi5.6 -v
PHP 5.6.40-8+0~20190531120521.15+stretch~1.gbpa77d1d (cgi-fcgi)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.0 -v
PHP 7.0.33-8+0~20190531121058.14+stretch~1.gbpe7d4ff (cgi-fcgi) (built: May 31 2019 12:10:58)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-8+0~20190531121058.14+stretch~1.gbpe7d4ff, Copyright (c) 1999-2017, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.1 -v
PHP 7.1.30-1+0~20190531112602.19+stretch~1.gbpab9d28 (cgi-fcgi) (built: May 31 2019 11:26:03)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30-1+0~20190531112602.19+stretch~1.gbpab9d28, Copyright (c) 1999-2018, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.2 -v
PHP 7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b (cgi-fcgi) (built: May 31 2019 11:26:38)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b, Copyright (c) 1999-2018, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.3 -v
PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cgi-fcgi) (built: May 31 2019 11:27:35)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7, Copyright (c) 1999-2018, by Zend Technologies`
5. Run
`apt install php-phalcon`
6. Result NOT OK on PHP 7.3, other versions are OK
`root@php:~# /usr/bin/php-cgi5.6 -v
PHP 5.6.40-8+0~20190531120521.15+stretch~1.gbpa77d1d (cgi-fcgi)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.0 -v
PHP 7.0.33-8+0~20190531121058.14+stretch~1.gbpe7d4ff (cgi-fcgi) (built: May 31 2019 12:10:58)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-8+0~20190531121058.14+stretch~1.gbpe7d4ff, Copyright (c) 1999-2017, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.1 -v
PHP 7.1.30-1+0~20190531112602.19+stretch~1.gbpab9d28 (cgi-fcgi) (built: May 31 2019 11:26:03)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30-1+0~20190531112602.19+stretch~1.gbpab9d28, Copyright (c) 1999-2018, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.2 -v
PHP 7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b (cgi-fcgi) (built: May 31 2019 11:26:38)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b, Copyright (c) 1999-2018, by Zend Technologies`
`root@php:~# /usr/bin/php-cgi7.3 -v
PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cgi-fcgi) (built: May 31 2019 11:27:35)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7, Copyright (c) 1999-2018, by Zend Technologies`
`Segmentation fault`

**Distribution:**
 - OS: Debian 9
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by Danack** [comment]
You should probably report this type of bug at php.net. It's doubtful that segfaults are going to be the result of a packaging problem. 

In particular, there were at least a couple of OPcache bugs that caused segfaults that have been fixed (though apparently at least one remains) in 7.3.7.

You should try that version, and then report your issue at bugs.php.net if it still remains, and post a backtrace so that it can be investigated.

**Comment by oerdnj** [comment]
I've updated the phalcon to latest version (it will take some time to build). If it still segfaults, you need to report this to upstream.
