### ISSUE TITLE
php7.1-dev instalation fails on libpcre3-dev dependency

### ISSUE THREAD

**Issue by ttraskback** [oerdnj/deb.sury.org#1189]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
Php7.1-dev depends on libpcre3-dev (>= 2:8.35) wich comes from ubuntu repos.
This in turn has a exact dependency on older libpcre3:
libpcre3-dev :
Depends: libpcre3 (= 2:8.39-12) but 2:8.42-1+ubuntu18.10.1+deb.sury.org+1 is to be installed
Depends: libpcrecpp0v5 (= 2:8.39-12) but 2:8.42-1+ubuntu18.10.1+deb.sury.org+1 is to be installed

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php7.1-dev:
  Installed: (none)
  Candidate: 7.1.30-1+ubuntu19.04.1+deb.sury.org+1
  Version table:
     7.1.30-1+ubuntu19.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu disco/main amd64 Packages

**Additional context**
apt policy php7.2-dev libpcre3-dev
php7.2-dev:
  Installed: (none)
  Candidate: 7.2.19-1+ubuntu19.04.1+deb.sury.org+1
  Version table:
     7.2.19-1+ubuntu19.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu disco/main amd64 Packages
     7.2.19-0ubuntu0.19.04.1 500
        500 http://fi.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu disco-security/main amd64 Packages
     7.2.15-0ubuntu3 500
        500 http://fi.archive.ubuntu.com/ubuntu disco/main amd64 Packages
libpcre3-dev:
  Installed: (none)
  Candidate: 2:8.39-12
  Version table:
     2:8.39-12 500
        500 http://fi.archive.ubuntu.com/ubuntu disco/main amd64 Packages

**Comment by todeveni** [comment]
Are you using pinning? `libpcre3-dev` should come from deb.sury.org repo too.

```
~ > apt policy libpcre3-dev
libpcre3-dev:
  Installed: 2:8.42-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2:8.42-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2:8.42-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2:8.39-9 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by ttraskback** [comment]
Hi @todeveni,
Not to my knowledge. There is no reference in /etc/apt to "Pin:"

**Comment by todeveni** [comment]
My bad. I quickly glanced that you're using `18.10`, but you're actually using `19.04`.

**Comment by todeveni** [comment]
There's something fishy going on, so I decided to do a clean install Ubuntu Disco with PHP PPA.
All `php7.x-dev` packages install fine.
You have a 18.10 to 19.04 upgrade with mixed packages?

**Comment by ttraskback** [comment]
I did have a reference to "deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main" but even after removing that it still doesn't pick libpcre3-dev the from deb.sury.org repo

**Comment by todeveni** [comment]
There's no `libpcre3-dev` in deb.sury.org repo for Disco, it depends on the package from Ubuntu.

**Comment by ttraskback** [comment]
Ok i se the problem the newer version of libpcre3 was only in a older version of the repo. And was just still installed. after downgrading to the ubunut version everything worked
