### ISSUE TITLE
Update xdebug extension to 2.3.3

### ISSUE THREAD

**Issue by willydee** [oerdnj/deb.sury.org#119]
In June 2015 a maintenance release of xdebug was released. It includes some important bug fixes like ArrayObject property inspection. See http://xdebug.org/updates.php#x_2_3_3. Please upgrade PPA to latest xdebug version. Thank you so much for all your efforts!

**Comment by oerdnj** [comment]
Updated ppa:ondrej/php5 and ppa:ondrej/php5-5.6 to xdebug_2.3.3.

ppa:ondrej/php-7.0 and ppa:ondrej/php is already at xdebug_2.4.0~rcX
