### ISSUE TITLE
Instructions to downgrade to previous version (7.2.18)

### ISSUE THREAD

**Issue by lourdas** [oerdnj/deb.sury.org#1191]
**Describe the bug**
After upgrading my servers to PHP 7.2.19 (the server OS is Ubuntu 18.04.2 64-bit), we started experiencing memory exhaustion issues. Searching the PHP bugs database, a few related issues came up which reveal that the problem exists in 7.2.19. One is [this](https://bugs.php.net/bug.php?id=78106) and [this](https://bugs.php.net/bug.php?id=78147).

**To Reproduce**
The issue is reproducable if you make several concurrent requests at your application. At some point, you will get a stack trace and the PHP error log will show something like:

    PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4047968968097232088 bytes) in ...

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04.2 64-bit
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

    php7.2:
      Installed: 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
      Candidate: 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
      Version table:
     *** 7.2.19-1+ubuntu18.04.1+deb.sury.org+1 500
            500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
            500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main i386 Packages
            100 /var/lib/dpkg/status
         7.2.19-0ubuntu0.18.04.1 500
            500 http://gr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
            500 http://gr.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
            500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
            500 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages
         7.2.3-1ubuntu1 500
            500 http://gr.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
            500 http://gr.archive.ubuntu.com/ubuntu bionic/main i386 Packages

So, I'd like to downgrade to 7.2.18. Could you please provide information on how to do this?

Thank you.

**Comment by oerdnj** [comment]
Unless you have a local copy, it’s not possible that to downgrade the packages. The purpose of this repository is to provide latest version of PHP.
