### ISSUE TITLE
libcurl4 and php7.3-curl

### ISSUE THREAD

**Issue by Yivan** [oerdnj/deb.sury.org#1193]
Hello,

First thanks a lot for providing this repository.

I would like to report a problem with php7.3-curl on debian buster.
Using deb.sury.org to install php7.3 on debian buster work fine, excepted for php7.3-curl.

I get:
```
The following packages have unmet dependencies:
 php7.3-curl : Depends: libcurl3 (>= 7.44.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I saw this problem was existing in this issue for php7.2-curl: https://github.com/oerdnj/deb.sury.org/issues/831

Debian buster has only libcurl4. There is no possibility to install libcurl3. Trying `apt-get install libcurl3` send:
```
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4

E: Package 'libcurl3' has no installation candidate
```

So i have try to install libcurl4 with `apt-get install libcurl4`, install went fine, but always the same message when trying to install php7.3-curl.

How can the problem be handled ?
(i don't want to use native php7.3 from buster)

For information, `apt policy php7.3-curl` return:
```
php7.3-curl:
  Installed: (none)
  Candidate: 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
  Version table:
     7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
     7.3.4-2 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
```

Thanks.

**Comment by todeveni** [comment]
You're using stretch packages in buster. That might be a problem.

**Comment by Yivan** [comment]
@todeveni Thanks, you are totaly right, i forgot to change it when adding the rpo ( good version is now: `sh -c 'echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/php.list'`).
All is ok now.

Thanks!
I close this issue.

**Comment by Adambean** [comment]
That was a quick search for me too. I had upgraded Stretch to Buster in place, just needed to do `sed -i /etc/apt/sources.list.d/php.list -e 's/stretch/buster/g'`, then apt update/upgrade again.

**Comment by rafaelricardo-rj** [comment]
It helped me a lot guys! Thanks a million!

**Comment by wni5378** [comment]
> 
> 
> You're using stretch packages in buster. That might be a problem.

This helped me solve my problem. Thank you very much.

**Comment by Adambean** [comment]
For those of you upgrading Ubuntu 18.04 to 20.04 in place, because the 20.04.1 LTS is now available, you'll need this:
`sed -e 's/bionic/focal/g' -i /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list`
then apt update/upgrade again.
