### ISSUE TITLE
Debian DPA repository giving 404

### ISSUE THREAD

**Issue by DaveLiddament** [oerdnj/deb.sury.org#1195]
**Unsupported distributions**
 - [ X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
apt-get update fails also. 
Link to https://packages.sury.org/php/ is giving either 404 or 5XX errors.

**To Reproduce**
Visit https://packages.sury.org/php/

**Expected behavior**
HTTP 200
and apt-get update works

**Distribution (please complete the following information):**
 - Debian stretch
 - Architecture: amd64
 - Repository: https://packages.sury.org/php/

**Comment by oerdnj** [comment]
I updated the settings for the KeyCDN zone (disabling blocking of "bad bots"), and seems like it broke the whole CDN Zone. #sigh 
I am looking into it.

**Comment by bronikowski** [comment]
I was just wondering why my provisioning went to poo. Take your time @oerdnj

**Comment by oerdnj** [comment]
I raised the ticket with them, hopefully someone will report rather sooner than later.

**Comment by wb7** [comment]
Thank you very much for the quick investigation! @oerdnj

**Comment by kescherCode** [comment]
I just wanted to upgrade an existing Debian Stretch system to Buster (yes, before the official release). apt gives me this:

```
[...]
Ign:5 https://packages.sury.org/php buster InRelease
Err:6 https://packages.sury.org/php buster Release
  520  Origin Error
[...]
E: The repository 'https://packages.sury.org/php buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Anyway, thanks for the quick investigation, @oerdnj!

**Comment by joaoubaldo** [comment]
Thanks for the quick fix!

**Comment by oerdnj** [comment]
I reverted the CDN and pointed the repository to the master server for time being.

**Comment by ondrejkopka** [comment]
Thank you!

But now i cannot install repository on new server, it throws:
Err:7 https://packages.sury.org/php stretch Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Hit:9 http://repo.saltstack.com/apt/debian/9/amd64/latest stretch InRelease
Reading package lists... Done
E: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Debian GNU/Linux 9.9 (stretch)

I did follow https://packages.sury.org/php/README.txt, i tried to reinstall ca-certificates, time is ok ...

**Comment by DaveLiddament** [comment]
@oerdnj Thanks for your quick response at fixing. Much appreciated.

**Comment by xhuljo313** [comment]
@oerdnj is the CDN issue fully fixed from http://ppa.launchpad.net/ondrej/php/ubuntu i cannot get any php package !
```bash
root@backup:~# cat d.sh
apt install software-properties-common -y
apt install python-software-properties -y
sudo add-apt-repository ppa:ondrej/php -y
apt update; apt upgrade -y
apt install -y php7.0
apt-cache search php | grep "7"

E: Unable to locate package php7.0
E: Couldn't find any package by regex 'php7.0'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by regex 'php7.0-fpm'
php-horde-text-flowed - Horde API for flowed text as per RFC 3676
```
OS : Ubuntu 14.04
