### ISSUE TITLE
installation of packages with population of dont wanted packages

### ISSUE THREAD

**Issue by mckaygerhard** [oerdnj/deb.sury.org#1196]
**Describe the bug**

when we install the default packages those are not enought to provide some others.. by example, php-gettex are nee by phpmyadmin but that requires the debian oficial php-api package but already we have the deb.sury packages installed.. 

so to install phpmyadmin we install a lot of packages dont wanted

**To Reproduce**
added repos of sury and debian
apt-get install php

then 

apt-get install phpmyadmin

here will install again php but from debian due php-gettex dependencies

**Expected behavior**
only php sury package of php already installed

**Distribution (please complete the following information):**

**NOTES**

i noted that maybe are not a "fatal" bug, but in some limited environments could give headhaches.. 

maybe including those php packages that triggers the problem or providing the already debian pacakge default api can be solved easyle

**Comment by oerdnj** [comment]
a) Providing packages in PHP is out of the scope for this repository.
b) The “API” is provided.

**Comment by mckaygerhard** [comment]
now we will begin to see how much we have lost with the cessation of "dotdeb.org"

**Comment by oerdnj** [comment]
Welcome to my block list.
