### ISSUE TITLE
current 7.1-fpm release also looks like it doesn't have dbg symbols

### ISSUE THREAD

**Issue by twobombs** [oerdnj/deb.sury.org#1198]
See https://github.com/oerdnj/deb.sury.org/issues/512

<img width="863" alt="Screenshot 2019-06-25 at 16 18 58" src="https://user-images.githubusercontent.com/12692227/60106735-3b097280-9755-11e9-96ef-b72230e86236.png">

Seems to have no dbgsym package.

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Debugging-Symbols
