### ISSUE TITLE
Php-7.3-gd not available anymore on trusty ?

### ISSUE THREAD

**Issue by heyyoyo** [oerdnj/deb.sury.org#1199]
I was surprised to see that Ubuntu could not find any more the php7.3-gd on trusty.
It was still here last few days ago. Other packages of ph7.3 are still available.

**Comment by olegdon** [comment]
Can confirm. Was trying to install php7.3-gd on my Ubuntu 14.04 few days ago and got no success

**Comment by todeveni** [comment]
Can confirm that Trusty is EOL. #1153

**Comment by oerdnj** [comment]
Few days ago? You mean end of April?

**Comment by olegdon** [comment]
nope, last Sunday. Didn't know that it's eol
