### ISSUE TITLE
[PHP 7.0] Possible broken after latest update

### ISSUE THREAD

**Issue by jazzfog** [oerdnj/deb.sury.org#120]
Yesterday it worked, but today I observe errors when I try to install php 7.0
Also I can not build redis module for php7

I think it may be result of latest update (somewhere near September 23 17:00 Czech Republic time)

```
add-apt-repository -y ppa:ondrej/php-7.0
apt-get update
apt-get install php -y
```

Results in error

```
Errors were encountered while processing:
 php7.0-cli
 libapache2-mod-php7.0
 php7.0
 php
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Full log @ Pastebin: http://pastebin.com/SU3EZaz8

Another attempt to install `apt-get install -y php7.0`
```
Setting up php7.0-cli (7.0.0~rc3-2+deb.sury.org~trusty+1) ...
update-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in auto mode
update-alternatives: error: alternative path /usr/bin/phar7.0 doesn't exist
dpkg: error processing package php7.0-cli (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of libapache2-mod-php7.0:
 libapache2-mod-php7.0 depends on php7.0-cli; however:
  Package php7.0-cli is not configured yet.
```

Full log on pastebin http://pastebin.com/jiKCevKe

As a result (probably) I can not build php-redis module anymore (btw It would be great If you could include it in your repo)

```
apt-get install php7.0-dev -y

mkdir -p /vagrant/redis_build
cd /vagrant/redis_build
git clone https://github.com/phpredis/phpredis.git
cd phpredis
git checkout php7

# Build extension
phpize
./configure
make && make install
```

`configure: error: Cannot find php-config. Please use --with-php-config=PATH`
Not sure it is connected but, again, if I remember correctly - it worked yesterday.

**Comment by oerdnj** [comment]
Thanks for the report, this has been fixed in 7.0.0~rc3-3 version that has been upload right now.

As for the external extensions, I will work on them to have it finished this year.
