### ISSUE TITLE
Nginx 1.17.1 update

### ISSUE THREAD

**Issue by S8Cloud** [oerdnj/deb.sury.org#1200]
Nginx 1.17.1 released

**Comment by asrob** [comment]
Nginx 1.17.2: http://nginx.org/en/CHANGES

**Comment by jflebeau** [comment]
Nginx 1.17.3, fixing 3 CVE : https://nginx.org/en/CHANGES

**Comment by asrob** [comment]
There are updated packages in mainline repository, see: https://launchpad.net/~ondrej/+archive/ubuntu/nginx?field.series_filter=bionic
