### ISSUE TITLE
[extension request] pcov https://pecl.php.net/package/pcov

### ISSUE THREAD

**Issue by Danack** [oerdnj/deb.sury.org#1203]
Please can you package up the [pcov extension](https://pecl.php.net/package/pcov) for at least Debian and I guess also Ubuntu.

Pcov allows generating code coverage reports for unit (and other) tests but doesn't make code run more slowly like xdebug does.

According to Sebastian Bergmann, an example time difference for a large project is:
```
PHP 7.3.1 with Xdebug - Time: 15.32 minutes
PHP 7.3.1 with PCOV - Time: 1.67 minutes
```

**Describe alternatives you've considered**
--- I tried to install it through Pecl, but couldn't figure out how to install pecl.....and then realised it would make building my containers be a lot slower. As it's a really useful extension I might as well just ask for it to be added, so that everyone can access it easily. ---

Someone pointed me to install `apt install php-dev` to have pecl available.....it would still be good to have it as directly installable extension.

**Comment by iget-master** [comment]
@oerdnj Would be nice to have this extension on your repository

**Comment by oerdnj** [comment]
Packaged and uploaded.
