### ISSUE TITLE
php packages are not upgraded from stretch to buster

### ISSUE THREAD

**Issue by 1player** [oerdnj/deb.sury.org#1206]
**Unsupported distributions**
 - [X] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**

I have an old machine I've dist-upgraded from jessie to stretch. Now I'm trying to dist-upgrade from stretch to the newly released buster.

All system packages have been upgraded successfully except the PHP ones from this repo, which from my limited understanding is because the version number of the stretch packages are lower than the buster ones.

In fact, some packages have been removed altogether during the upgrade, such as `php7.3-curl`, because apt couldn't find a valid candidate

```
# apt-cache policy php7.3-curl
php7.3-curl:
  Installed: (none)
  Candidate: 7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7
  Version table:
     7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 -1
        100 /var/lib/dpkg/status
     7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     7.3.4-2 500
        500 http://ftp.us.debian.org/debian buster/main amd64 Packages

# apt install php7.3-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.3-curl : Depends: php7.3-common (= 7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7) but 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 is to be installed
E: Unable to correct problems, you have held broken packages.

# apt-cache policy php7.3-common
php7.3-common:
  Installed: 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
  Candidate: 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
  Version table:
 *** 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 100
        100 /var/lib/dpkg/status
     7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     7.3.4-2 500
        500 http://ftp.us.debian.org/debian buster/main amd64 Packages
```

**To Reproduce**
1. Fully upgrade a stretch machine
2. Upgrade to buster
3. Notice that php packages from this repo haven't been updated, and some have been removed

**Expected behavior**
php packages upgraded from stretch to buster

**Distribution (please complete the following information):**
 - OS: Debian Stretch 9.9
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
https://www.debian.org/releases/buster/amd64/release-notes/ch-upgrading.en.html#unofficial-sources

**Comment by 1player** [comment]
I don't get why this is closed. Yes, I've noticed that line, that also states "If these packages were installed by adding an extra package archive in your APT source-list files, you should check if that archive also offers packages compiled for buster and change the source item accordingly at the same time as your source items for Debian packages."

In fact my sources.list.d/php.list file reads: `deb https://packages.sury.org/php/ buster main` so I would expect the packages to be updated accordingly.

Do I have to manually delete and reinstall all the php packages, forcing them to the buster version, as apt considers it a downgrade?

**Comment by oerdnj** [comment]
Sorry, I missed the information about changed stretch -> buster in the extra repo.

**Comment by dupondje** [comment]
It seems like the version number of Buster packages is lower than Stretch versions.
Guess because your CI first builds Buster and then Stretch.

If you reverse that, it should be fine :)

**Comment by oerdnj** [comment]
The problem is that the Jenkins CI picks the order "randomly". I can take a look whether it's possible to configure that.

I had a different solution in preparation - instead of "stretch" or "buster", I will use "debian9" or "debian10" and move the distro version before the timestamp.

**Comment by dupondje** [comment]
7.3.6-1+0~20190531.10+buster~1.gbp6131b7
7.3.6-1+0~20190531.9+stretch~1.gbp6131b7

Could also be an option :)
Anyway, for people stuck:
Add the following to /etc/apt/preferences.d/sury
`Package: php*
Pin: version 7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7
Pin-Priority: 1200
`

**Comment by oerdnj** [comment]
I'll be updating the PHP version soon, so I will get this sorted out before I get the releases out.

**Comment by oerdnj** [comment]
Turns out that this would just include setting env variable TIMESTAMP_FORMAT to `%Y%m%d`, so together with using `debian9` and `debian10` it involved just changing the configuration and not the jenkins-debian-glue scripts, which is optimal.

**Comment by natenate19** [comment]
Tangentially and fwiw, nginx packages and some libs also appear affected by this on dist-upgrade from stretch to buster.  Easy enough to pin or uninstall / install the affected packages, but the latter was not an option with affected libs due to dependency chains:

libpcre3
libargon2

Look to be affected at minimum.  I just "downgraded" manually using `dpkg -i` for these but I suppose pinning might work.

**Comment by mklooss** [comment]
thanks for changing :)

**Comment by oerdnj** [comment]
It still needs some more rebuilds, but the bulk of it should be done today.

**Comment by jeffgeorge** [comment]
I can confirm this is back to working now, the `7.3.7-1+0~20190710.40+debian10~1.gbp032aec` builds just installed fine for me, and I can now reinstall `php7.3-curl`. Thanks for getting it sorted!

**Comment by oerdnj** [comment]
I've just issued a rebuild of all extension, it's just the build queue is very looong: https://jenkins.rfc1925.org/view/PHP/, so it will take some time to rebuild all of them.
