### ISSUE TITLE
Include revert of breaking change in 7.2.20

### ISSUE THREAD

**Issue by ToBee94** [oerdnj/deb.sury.org#1208]
Yesterday you start to provide the php version 7.2.20 for debian stretch. This new version includes a breaking change that makes unable to run symfony (https://github.com/symfony/symfony/issues/32395). Php already released a patch which will be included in the new version 7.2.21. It would be nice if you can provide a new version of 7.2.20 including the revert of this breaking change, until 7.2.21 is released.

Patch: https://github.com/php/php-src/commit/22ed362810c1b3a5ecb54ebd1d50d804c7fc3159

**Comment by EkoMcCloud** [comment]
This also affects PHP 7.3.7

**Comment by ahilles107** [comment]
7.3.8RC1 was tagged today http://git.php.net/?p=php-src.git;a=tag;h=27265a358a4f0d505a192607cbd26d60862ed6cf

**Comment by gempir** [comment]
7.2.21 aswell https://github.com/php/php-src/releases/tag/php-7.2.21RC1

**Comment by arturslogins** [comment]
Any progress on this issue?

**Comment by Prometee** [comment]
Is there a way to revert to `php 7.2.19` ?
No previous version is available : `apt-cache policy php7.2` so no way to revert...

**Comment by ToBee94** [comment]
@Prometee you can remove sury repository from apt sources list and install all debian packages over dpkg manually. But you need the 7.2.19 packages

**Comment by Prometee** [comment]
@ToBee94 default php version of debian 9 : https://packages.debian.org/stretch/php7.0

**Comment by ToBee94** [comment]
@Prometee this is no solution if you have code which only runs with 7.1/7.2/7.3. Between mayor version exists breaking changes which makes unable tu run 7.3/7.2 applications on 7.0.

Also symfony 4.x requires php version 7.1.3 or grater.

**Comment by drAlberT** [comment]
@Prometee I'm taking them from here: `https://launchpad.net/~ondrej/+archive/ubuntu/php/+files/php7.2-mysql_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb`

I don't know if there is a repo to access those packages via apt instead of having to get them and install manualli via dpkg ... but for now it could help I guess

**Comment by drAlberT** [comment]
@oerdnj we are all summoning you! :D Please appear!

**Comment by Wiaf** [comment]
> @Prometee I'm taking them from here: `https://launchpad.net/~ondrej/+archive/ubuntu/php/+files/php7.2-mysql_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb`
> 
> I don't know if there is a repo to access those packages via apt instead of having to get them and install manualli via dpkg ... but for now it could help I guess

Are you running this on a live environment? 
We have just encountered the same issue on some of our live microservices and have fallen back to replacing our Debian9 Machines with Debian8. I have major concerns when installing ubuntu packages onto debian machines. :/
Do you have more experience in that?

**Comment by migmolrod** [comment]
Does anyone know how much it normally takes from when a new RC is tagged to when the actual release is out? Or it varies a lot from version to version?

**Comment by Wiaf** [comment]
> @Prometee I'm taking them from here: `https://launchpad.net/~ondrej/+archive/ubuntu/php/+files/php7.2-mysql_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb`
> 
> I don't know if there is a repo to access those packages via apt instead of having to get them and install manualli via dpkg ... but for now it could help I guess

Are you running this on a live environment?
I have major concerns when installing ubuntu packages onto debian machines. :/
Do you have more experience in that?

**Comment by ahilles107** [comment]
> Does anyone know how much it normally takes from when a new PHP RC is tagged to when the actual release is out? Or it varies a lot from version to version?

7.3.8 is planned for 1st of August

**Comment by drAlberT** [comment]
> > @Prometee I'm taking them from here: `https://launchpad.net/~ondrej/+archive/ubuntu/php/+files/php7.2-mysql_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb`
> > I don't know if there is a repo to access those packages via apt instead of having to get them and install manualli via dpkg ... but for now it could help I guess
> 
> Are you running this on a live environment?
> I have major concerns when installing ubuntu packages onto debian machines. :/
> Do you have more experience in that?

Sorry I have them live on Ubuntu, no debian installations right now

**Comment by migmolrod** [comment]
@ahilles107 tyvm. Where do you get that info from? I tried to find a PHP roadmap or whatever but no luck.

Also, is there any clean and up to date RSS or mailing list to get notified when new PHP minor versions are released? Because I'm taking a look at php mailing lists and for instance [php.announce](https://news-web.php.net/php.announce) seems outdated. Last announced releases there are 7.1.30 and 7.3.6 back on may 30th.
And [php.general](https://news-web.php.net/php.general) looks like a mix between newer releases (I can see 7.2.20 and 7.4.0beta1 there, for example) and some random questions about PHP.

**Comment by ahilles107** [comment]
@migmolrod it's defined in source code ;) http://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=b42a13b08ae59e686dafcd70eac37c917b1a6792

**Comment by oerdnj** [comment]
I'm sorry, I've been too busy. The patches packages have been uploaded to both Ubuntu and Debian.
