### ISSUE TITLE
Update version of php-solr to 2.5.0 for PHP 7.3 support

### ISSUE THREAD

**Issue by ktardif** [oerdnj/deb.sury.org#1209]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
Using the PHP solr extension with version 2.4.0 under PHP 7.3 will cause a segfault when SolrQueryResponse getResponse() is called.

**To Reproduce**
Call getResponse() on a SolrQueryResponse object when running under PHP 7.3.

**Expected behavior**
PHP not to segfault.

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php-solr:
  Installed: 2.4.0-6+ubuntu16.04.1+deb.sury.org+10
  Candidate: 2.4.0-6+ubuntu16.04.1+deb.sury.org+10
  Version table:
 *** 2.4.0-6+ubuntu16.04.1+deb.sury.org+10 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.0-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Additional context**
A new version (2.5.0) of the extension was released on 2019-07-04 adding PHP 7.3 support. Updating the extension version in the repo would fix this issue.

**Comment by oerdnj** [comment]
solr has been updated to 2.5.0

**Comment by ktardif** [comment]
Thanks a lot.
