### ISSUE TITLE
Update php-ast module (for phan) to v1.0.1+

### ISSUE THREAD

**Issue by tersmitten** [oerdnj/deb.sury.org#1210]
I would be nice if the `php-ast` extension can be updated from `v0.1.6` to `v1.0.1+`, as this is required to use the latest version of [etsy/phan](https://packagist.org/packages/etsy/phan).

```
ERROR: Phan 2.x requires php-ast 1.0.1+ because it depends on AST version 70. php-ast 0.1.6 is installed.
Exiting without analyzing files.
```

Let me know if I can do anything to realize this

**Comment by oerdnj** [comment]
Updated and uploaded.

**Comment by tersmitten** [comment]
Thanks a lot
