### ISSUE TITLE
php-memcached for php5.6 and php7.0 for buster?

### ISSUE THREAD

**Issue by dpeca** [oerdnj/deb.sury.org#1211]
```
# cat /etc/apt/sources.list.d/php.list
deb https://packages.sury.org/php/ buster main

# apt install php5.6-memcached
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php5.6-memcached
E: Couldn't find any package by glob 'php5.6-memcached'
E: Couldn't find any package by regex 'php5.6-memcached'

# apt install php7.0-memcached
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.0-memcached
E: Couldn't find any package by glob 'php7.0-memcached'
E: Couldn't find any package by regex 'php7.0-memcached'
```

Any idea why php-memcached not exists for php5.6 and php7.0 in Buster?
(for 7.1, 7.2 and 7.3 everything is fine)

On Stretch everything is fine for php-memchached for php5.6 and php7.0:
```
# apt install php7.0-memcached
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php-memcached' instead of 'php7.0-memcached'
php-memcached is already the newest version (3.1.3+2.2.0-1+0~20190606080312.9+stretch~1.gbpb26597).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by oerdnj** [comment]
I have issued a rebuild which should fix the problem, it will take some time though, as there's a huge build queue right now: https://jenkins.rfc1925.org/view/PHP/

**Comment by imifarago** [comment]
Thank you, waiting for it then :)

**Comment by dpeca** [comment]
@oerdnj 
No problem, we will wait as long as it is rquired - we just wanted information if it will be fixed or not.
We are planing to migrate old Deb8 servers (to Deb10) with bunch of sites that is mostly using php5.6 or 7.0... and it will be huge mess if php-memcached suddenly disappear for those sites... 

No need to hurry, we will wait.

**Comment by juokelis** [comment]
As for now, it looks like php-memcache is only available for php7.3:
```
apt-cache depends  php-memcached
php-memcached
  PreDepends: php-common
  Depends: php-igbinary
  Depends: php-msgpack
  Depends: ucf
  Depends: <phpapi-20180731>
    libapache2-mod-php7.3
    libphp7.3-embed
    php7.3-cgi
    php7.3-cli
    php7.3-fpm
    php7.3-phpdbg
  Depends: libc6
  Depends: libmemcached11
  Depends: libmemcachedutil2
  Depends: libsasl2-2
  Depends: zlib1g
```

Lot's better on stretch:
```
apt-cache depends  php-memcached
php-memcached
  PreDepends: php-common
  Depends: php-igbinary
  Depends: php-msgpack
  Depends: ucf
 |Depends: <phpapi-20180731>
    libapache2-mod-php7.3
    libphp7.3-embed
    php7.3-cgi
    php7.3-cli
    php7.3-fpm
    php7.3-phpdbg
 |Depends: <phpapi-20170718>
    libapache2-mod-php7.2
    libphp7.2-embed
    php7.2-cgi
    php7.2-cli
    php7.2-fpm
    php7.2-phpdbg
 |Depends: <phpapi-20160303>
    libapache2-mod-php7.1
    libphp7.1-embed
    php7.1-cgi
    php7.1-cli
    php7.1-fpm
    php7.1-phpdbg
 |Depends: <phpapi-20151012>
    libapache2-mod-php7.0
    libphp7.0-embed
    php7.0-cgi
    php7.0-cli
    php7.0-fpm
    php7.0-phpdbg
  Depends: <phpapi-20131226>
    libapache2-mod-php5.6
    libphp5.6-embed
    php5.6-cgi
    php5.6-cli
    php5.6-fpm
    php5.6-phpdbg
  Depends: libc6
  Depends: libmemcached11
  Depends: libmemcachedutil2
  Depends: libsasl2-2
  Depends: zlib1g
```

Waiting for a new build! Thank you for your great work!

**Comment by todeveni** [comment]
Is it because PHP 5.6 and 7.0 are EOL and not supported anymore?

FWIW, php-memcached has 7.1, 7.2 and 7.3 depends on my Buster.

```
~> apt-cache depends php-memcached
php-memcached
  PreDepends: php-common
  Depends: php-igbinary
  Depends: php-msgpack
  Depends: ucf
 |Depends: <phpapi-20180731>
    libapache2-mod-php7.3
    libphp7.3-embed
    php7.3-cgi
    php7.3-cli
    php7.3-fpm
    php7.3-phpdbg
 |Depends: <phpapi-20170718>
    libapache2-mod-php7.2
    libphp7.2-embed
    php7.2-cgi
    php7.2-cli
    php7.2-fpm
    php7.2-phpdbg
  Depends: <phpapi-20160303>
    libapache2-mod-php7.1
    libphp7.1-embed
    php7.1-cgi
    php7.1-cli
    php7.1-fpm
    php7.1-phpdbg
  Depends: libc6
  Depends: libmemcached11
  Depends: libmemcachedutil2
  Depends: libsasl2-2
  Depends: zlib1g

~> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by oerdnj** [comment]
My guess is the php-memcached from stock Debian.

**Comment by juokelis** [comment]
You're right. My bad. Though php-memcached still not available for php5.6 on buster from your repo:
```
root@server:/#apt-cache policy php-memcached
php-memcached:
  Installed: 3.1.3+2.2.0-1+0~20190606080312.9+stretch~1.gbpb26597
  Candidate: 3.1.3+2.2.0-1+0~20190606080318.9+buster~1.gbpb26597
  Version table:
     3.1.3+2.2.0-1+0~20190606080318.9+buster~1.gbpb26597 500
        500 https://packages.sury.org/php buster/main amd64 Packages
 *** 3.1.3+2.2.0-1+0~20190606080312.9+stretch~1.gbpb26597 100
        100 /var/lib/dpkg/status
     3.0.1+2.2.0-1 500
        500 http://debian.balt.net/debian stretch/main amd64 Packages

root@server:/#apt-cache depends php-memcached=3.1.3+2.2.0-1+0~20190606080318.9+buster~1.gbpb26597
php-memcached
  PreDepends: php-common
  Depends: php-igbinary
  Depends: php-msgpack
  Depends: ucf
 |Depends: <phpapi-20180731>
    libapache2-mod-php7.3
    libphp7.3-embed
    php7.3-cgi
    php7.3-cli
    php7.3-fpm
    php7.3-phpdbg
 |Depends: <phpapi-20170718>
    libapache2-mod-php7.2
    libphp7.2-embed
    php7.2-cgi
    php7.2-cli
    php7.2-fpm
    php7.2-phpdbg
  Depends: <phpapi-20160303>
    libapache2-mod-php7.1
    libphp7.1-embed
    php7.1-cgi
    php7.1-cli
    php7.1-fpm
    php7.1-phpdbg
  Depends: libc6
  Depends: libmemcached11
  Depends: libmemcachedutil2
  Depends: libsasl2-2
  Depends: zlib1g
```

And there's no php5.6-memcached or something like that:
```
root@server:/#apt-cache search memcached | grep php
php-apcu - APC User Cache for PHP
php-igbinary - igbinary PHP serializer
php-memcache - memcache extension module for PHP
php-memcached - memcached extension module for PHP, uses libmemcached
php-memcached-dbgsym - debug symbols for php-memcached

```

**Comment by oerdnj** [comment]
I see now - there was a build failure: https://jenkins.rfc1925.org/view/PHP/job/php_php-memcached-binaries/12/

I’ll fix that when I am back home next week.

Please use PECL meanwhile.

**Comment by juokelis** [comment]
Sure, we'll wait! Thank You! Just trying to help :)
There's the same story with PECL though :)
```
# apt-cache search pecl | grep php
dh-php - debhelper add-on to handle PHP PECL extensions
php-memcache - memcache extension module for PHP
php-http - PECL HTTP module for PHP Extended HTTP Support
php-pecl-http - pecl_http module for PHP Extended HTTP Support [dummy]
php-pecl-http-dev - pecl_http module for PHP Extended HTTP Support [dummy]
php-propro - propro module for PHP
php-radius - radius client library for PHP
php-raphf - raphf module for PHP
php-solr - PHP extension for communicating with Apache Solr server
pkg-php-tools - various packaging tools and scripts for PHP packages
php-remctl - PECL module for Kerberos-authenticated command execution
# apt-cache policy php-http
php-http:
  Installed: (none)
  Candidate: 3.2.1+2.6.0-1+0~20190808.6+debian10~1.gbpbd8342
  Version table:
     3.2.1+2.6.0-1+0~20190808.6+debian10~1.gbpbd8342 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     3.2.0+2.6.0-2+b1 500
        500 http://debian.balt.net/debian buster/main amd64 Packages
# apt-cache depends php-http=3.2.1+2.6.0-1+0~20190808.6+debian10~1.gbpbd8342
php-http
  PreDepends: php-common
  Depends: php-propro
  Depends: php-raphf
 |Depends: <phpapi-20180731>
    libapache2-mod-php7.3
    libphp7.3-embed
    php7.3-cgi
    php7.3-cli
    php7.3-fpm
    php7.3-phpdbg
 |Depends: <phpapi-20170718>
    libapache2-mod-php7.2
    libphp7.2-embed
    php7.2-cgi
    php7.2-cli
    php7.2-fpm
    php7.2-phpdbg
  Depends: <phpapi-20160303>
    libapache2-mod-php7.1
    libphp7.1-embed
    php7.1-cgi
    php7.1-cli
    php7.1-fpm
    php7.1-phpdbg
  Depends: libc6
  Depends: libcurl4
  Depends: libevent-2.1-6
  Depends: libidn11
  Depends: libssl1.1
  Depends: zlib1g
  Breaks: php-pecl-http
  Breaks: php-pecl-http-dev
  Replaces: php-pecl-http
  Replaces: php-pecl-http-dev

```

**Comment by oerdnj** [comment]
Could you try now? I did some debugging on the mobile today and I found the culprit (missing php-defaults build for buster).

**Comment by dpeca** [comment]
I think that's it.
In both 5.6 and 7.0 in phpinfo() I can see it's loaded as module.
I didn't try if it works, but I guess it's working since it's loaded.

**Comment by dpeca** [comment]
btw, is php-memcache (not php-memcached with 'd') totally depricated for 5.6 and 7.0?
I see buster is using php-memcached instead of php-memcache

**Comment by imifarago** [comment]
Now php-memcached works fine for me. Buster + php5.6, 7.1 and 7.3 also.
However, after I installed the new build of the php-memcached package I had to reinstall the php7.3-fpm :) In 7.3 only the cli had the memcached module.

**Comment by dpeca** [comment]
I have both memcache and memcached in 7.3-fpm
Maybe somehow you uninstalled it.

**Comment by oerdnj** [comment]
> However, after I installed the new build of the php-memcached package I had to reinstall the php7.3-fpm :) In 7.3 only the cli had the memcached module.

I would be interested in seeing apt logs from the time when it has failed. Both apt.log and console.log. I thought I did solve all the race conditions, but it’s just a software it’s main feature is that it’s buggy... ;)

**Comment by imifarago** [comment]
> > However, after I installed the new build of the php-memcached package I had to reinstall the php7.3-fpm :) In 7.3 only the cli had the memcached module.
> 
> I would be interested in seeing apt logs from the time when it has failed. Both apt.log and console.log. I thought I did solve all the race conditions, but it’s just a software it’s main feature is that it’s buggy... ;)

history.log https://pastebin.com/ESbeZBFG
term.log https://pastebin.com/p0GWcsRq

**Comment by dpeca** [comment]
Just to ask once again, is it possible to get also php5.6-memcache and php7.0-memcache ?

Stretch has both php-memcache and php-memcached

**Comment by oerdnj** [comment]
@dpeca the latest package should have them

**Comment by dpeca** [comment]
@oerdnj unfortunately:
```
Note, selecting 'php5.6-memcached' for regex 'php5.6-memcache'
Note, selecting 'php7.0-memcached' for regex 'php7.0-memcache'
```
So it's always end up with memcached, that is already installed.

Looks like some apt alias or apt itself is looking for similar package when exact match does not exists?

**Comment by oerdnj** [comment]
php-memcached package provide extension for all supported PHP versions.

**Comment by dpeca** [comment]
@oerdnj I'm not talking about php-memchached
Talking about php-memcache (without 'd' on end), that's a separated library.
Stretch has both php-memcache and php-memcached - but on buster php-memcache is not avaible for 5.6 and 7.0
It exists for 7.1, 7.2 and 7.3, but missing for 5.6 and 7.0

I hope I was not confusing you.

**Comment by oerdnj** [comment]
It can be a bit confusing when you mix the issues in one ticket...

Nevertheless, I rebuilt php-memcache for buster as well and it has extensions for all supported PHP versions.

**Comment by dpeca** [comment]
@oerdnj sorry man, I just thought that it's better to not to create another ticket since the roots of issue are problably the same for both packages.
However, thanks a lot for resolving this <3
