### ISSUE TITLE
update-alternatives: warning: 

### ISSUE THREAD

**Issue by hellreturn** [oerdnj/deb.sury.org#1212]
Seeing below error upon upgrades on php 7.3.x series each time - 

update-alternatives: warning: forcing reinstallation of alternative /usr/bin/phar7.3 because link group phar is broken
update-alternatives: warning: not replacing /usr/bin/phar with a link
update-alternatives: warning: not replacing /usr/share/man/man1/phar.1.gz with a link

**Comment by oerdnj** [comment]
The seems like a local problem to me, somebody (presumably you) I installed /usr/bin/phar that doesn’t come from the package.
