### ISSUE TITLE
Ubuntu 16.04: added ppa:ondrej/php and updated; apt is offering mysterious updates

### ISSUE THREAD

**Issue by jrmain** [oerdnj/deb.sury.org#1214]
I created a new VMWare VM just to test this. New Ubuntu 16.04 64-bit server install, with LAMP stack added. Updated and upgraded everything. Added ppa:ondrej/php and updated; apt immediately started showing a bunch of available updates that make no sense to me. Note that I haven't even installed anything from the ppa:ondrej/php source yet. Here are the updates it's telling me about:

```
libapache2-mod-php/xenial,xenial 2:7.3+69+ubuntu16.04.1+deb.sury.org+2+php7.3 all [upgradable from: 1:7.0+35ubuntu6.1]
libapache2-mod-php7.0/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
libjbig0/xenial 2.1-3.1+deb.sury.org~xenial+1 amd64 [upgradable from: 2.1-3.1]
libpcre3/xenial 2:8.43-1+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 2:8.38-3.1]
libxml2/xenial 2.9.4-1+deb.sury.org~xenial+2 amd64 [upgradable from: 2.9.3+dfsg1-1ubuntu0.6]
openssl/xenial 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 1.0.2g-1ubuntu4.15]
php-common/xenial,xenial 2:69+ubuntu16.04.1+deb.sury.org+2+php7.3 all [upgradable from: 1:35ubuntu6.1]
php-mysql/xenial,xenial 2:7.3+69+ubuntu16.04.1+deb.sury.org+2+php7.3 all [upgradable from: 1:7.0+35ubuntu6.1]
php7.0-cli/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
php7.0-common/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
php7.0-json/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
php7.0-mysql/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
php7.0-opcache/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]
php7.0-readline/xenial 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 amd64 [upgradable from: 7.0.33-0ubuntu0.16.04.5]

```
It's possible that these updates all make sense somehow, and are safe to install. Perhaps I'm being overly-cautious.

**Comment by oerdnj** [comment]
I am not sure my goal here is to understand what makes and what doesn’t make sense to you.

Could you please clearly describe the problem you are having? Yes, those are packages provided by the PPA, you either have trust or don’t have trust in the PPA.

**Comment by jrmain** [comment]
I want to be able to run PHP 5.6 for one Apache site and PHP 7.x for all others on my Ubuntu 16.04 LTS server. I had expected that I would be able to install just the php5.6 package (and related packages) from ondrej/php, but the ondrej source seems to be taking over, replacing Ubuntu packages with ondrej packages for all other PHP versions, including some I don't need, as well as openssl and various LIB packages.

It's not that I don't trust ondrej/php, I was just surprised at all those additional updates, and wasn't sure whether it meant something was not quite right on my server.

I've used the ondrej/php PPA in the past for this purpose, and don't recall this happening. Hence my concern that something is broken at my end. I suppose I'm just looking for some reassurance that this is perfectly normal, and expected.

Questions:

1. It seems that once you start using the ondrej/php PPA, you end up using it for all (still-supported) PHP packages, as well as a few others (presumably related) like openssl. Am I right about that?

2. Is there any way around this? Or is it happening for good reasons (in which case I should just stop worrying about it)?

3. On a related topic: I see that you recommend using the ondrej/apache2 source for Apache as well ("If you are using apache2, you are advised to add ppa:ondrej/apache2"). Can you give me an idea of the risks of **not** using ondrej/apache2 if I'm using ondrej/php?

**Comment by oerdnj** [comment]
> It seems that once you start using the ondrej/php PPA, you end up using it for all (still-supported) PHP packages, as well as a few others (presumably related) like openssl. Am I right about that?

Yes. But those are not "random" packages, they are build and runtime dependencies for PHP.

> Is there any way around this?

For some packages, the pinning might help, but for some, they are strictly required.

> Or is it happening for good reasons (in which case I should just stop worrying about it)?

Yes, some PHP features are enabled only if using the newer libraries.

> On a related topic: I see that you recommend using the ondrej/apache2 source for Apache as well ("If you are using apache2, you are advised to add ppa:ondrej/apache2"). Can you give me an idea of the risks of not using ondrej/apache2 if I'm using ondrej/php?

The apache2 from PPA is up-to-date, has better HTTP/2 support, has TLS1.3 support.  There are no risk per se.
