### ISSUE TITLE
PHP-Redis RedisArray keys function segfaults on 5.0.2 release

### ISSUE THREAD

**Issue by TuningYourCode** [oerdnj/deb.sury.org#1217]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
RedisArray keys-function are broken with release of "php-redis 5.0.2+4.3.0-1+0~20190808.13+debian9~1.gbpcc7e06":
https://github.com/phpredis/phpredis/issues/1618

**To Reproduce**
See issue on phpredis repo.
$redisArray->keys('*') results in segementation fault.

**Expected behavior**
$redisArray->keys('*') does not result in segmentation fault.

**Distribution (please complete the following information):**
 - OS: Debian Stretch
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php-redis:
  Installed: 5.0.2+4.3.0-1+0~20190808.13+debian9~1.gbpcc7e06
  Candidate: 5.0.2+4.3.0-1+0~20190808.13+debian9~1.gbpcc7e06
  Version table:
 *** 5.0.2+4.3.0-1+0~20190808.13+debian9~1.gbpcc7e06 990
        990 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.1-1 990
        990 http://deb.debian.org/debian stretch/main amd64 Packages
```

**Additional context**
This is more or less as information. It would probably a good idea to remove the broken version as long as the phpredis-Teams tagged a new version. As alternative the bugfix is already merged into the development branch of phpredis extentsion repository.

**Comment by oerdnj** [comment]
Uploaded a fixed source package.  Again, the Debian builder is still building lot of packages, so it will take a while before the update redis package will be available, but it's in the queue.

**Comment by TuningYourCode** [comment]
Thx for your quick response and work you are doing for us all :)

**Comment by elnur** [comment]
This update broke Redis for session storage in PHP 7.3 on Ubuntu 18.04.

**Comment by todeveni** [comment]
> This update broke Redis for session storage in PHP 7.3 on Ubuntu 18.04.

Same as #1218 ?

**Comment by elnur** [comment]
No, @todeveni. We don't have Redis packages like `redis-server` and `redis-tools` installed on those machines. Never needed that.

PHP sessions broke with both a standalone Redis on a separate machine and AWS Elasticache: 

```
E_WARNING: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: tcp://foo.bar.0001.use1.cache.amazonaws.com)
```

**Comment by elnur** [comment]
The problem started Aug 8/9 — 3 days ago.

**Comment by todeveni** [comment]
Works for me with standalone Redis.

```
php 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
php-redis 5.0.2+4.3.0-2+ubuntu18.04.1+deb.sury.org+1
redis-server 4.0.9-1ubuntu0.2
```

```php
<?php
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://localhost:6379');

session_start();
```

```
ubuntu@ip-172-31-26-3:~# redis-cli
127.0.0.1:6379> keys *
1) "PHPREDIS_SESSION:o851hb59d17km07ngmm1vodh0c"
```

**Comment by elnur** [comment]
So we are being forced to upgrade to Redis 5? Why such a sudden breaking change?

**Comment by elnur** [comment]
Never mind. Our standalone Redis is 4.0.9. Hmm.

**Comment by elnur** [comment]
Well, I don't know exactly why yet, but it broke exactly when the Redis packages of this repo got updated.

**Comment by elnur** [comment]
Oh! Our `save_path` didn't have the port number specified. The default worked fine before this update. I've specified it now, and it got fixed. Is this a regression or not?

**Comment by elnur** [comment]
In any case, thanks for the help, @todeveni! It's all working now with the port specified, and that's what we needed.

**Comment by oerdnj** [comment]
JFTR You’ll need to report this to upstream. I am just a “messenger” here.
