### ISSUE TITLE
Missing php7.3-mcrypt

### ISSUE THREAD

**Issue by webieseo** [oerdnj/deb.sury.org#1221]
HI can't seem to find php7.3-mcrypt via apt install phpmyadmin plugin fails with error E: Unable to locate package php73-mcrypt do apt-cache search php7.3-mcrypt not found.

do you plan to add php7.3-mcrypt module ?

Kind Regards

**Comment by oerdnj** [comment]
No, see https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt
