### ISSUE TITLE
Apache 2.4.41

### ISSUE THREAD

**Issue by anamba** [oerdnj/deb.sury.org#1222]
Apache 2.4.41 is out and includes a number of important http2 security fixes.

Thank you for your work in maintaining this PPA!

**Comment by oerdnj** [comment]
18.04 and 19.04 has been updated, however there are missing build-deps on 16.04, so it will required a bit more work on my side.

**Comment by kadai** [comment]
Greetings, the builds for Ubuntu 16.04 seems to be broken.

They require the apache2-data package but they try to install the version 2.4.39 rather than the 2.4.41

**Comment by m-ueberall** [comment]
FYI: At the moment, one should resist the temptation to simply trigger/force the installation on Ubuntu 16.04 (Xenial Xerus) w/o checking dependencies ...
```# head -2 /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
# LANG=C apt install apache2 apache2-bin apache2-data apache2-utils
Reading package lists... Done
[...]
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom
The following packages will be REMOVED:
  libapache2-mod-fastcgi libapache2-mod-fcgid libapache2-mod-php7.3 libapache2-mod-security2 libapache2-mod-wsgi
The following packages will be upgraded:
  apache2 apache2-bin apache2-data apache2-utils
4 upgraded, 0 newly installed, 5 to remove and 2 not upgraded.```

**Comment by werk21** [comment]
This problem is the same issue as https://github.com/oerdnj/deb.sury.org/issues/1088
We ran also in this problem... LAMP without P is evel.
Can you fix this please?

**Comment by oerdnj** [comment]
Please open a separate issue for the API problem. This needs more work as the packages can’t support two Apache API versions still the same time.
