### ISSUE TITLE
php-(imagick|memcached) (maybe others) only support PHP 7.(1|2|3)

### ISSUE THREAD

**Issue by fretb** [oerdnj/deb.sury.org#1223]
**Describe the bug**
php-imagick (3.4.4) supports php 5.6 through 7.3, though I only find .so files in the extension dirs of PHP 7.1, 7.2 and 7.3

```
root@multi-version-debian-10:~# dpkg -S imagick.so
php-imagick: /usr/lib/php/20160303/imagick.so
php-imagick: /usr/lib/php/20180731/imagick.so
php-imagick: /usr/lib/php/20170718/imagick.so
```

php-memcached (3.1.3) supports php 7.0 through 7.3, though no .so files for 7.0

```
root@multi-version-debian-10:~# dpkg -S memcached.so | grep php
php-memcached: /usr/lib/php/20160303/memcached.so
php-memcached: /usr/lib/php/20170718/memcached.so
php-memcached: /usr/lib/php/20180731/memcached.so
```

**To Reproduce**
1. Install php-memcached and php-imagick.

**Expected behavior**
I would expect php-imagick to be compatible with PHP 5.6 through 7.3 and php-memcached to be compatible with PHP 7.0 through 7.3.

**Distribution (please complete the following information):**
 - OS: Debian Buster
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
root@multi-version-debian-10:~# apt-cache policy php-imagick
php-imagick:
  Installed: 3.4.4-1+0~20190808.10+debian10~1.gbpc5da26
root@multi-version-debian-10:~# apt-cache policy php-memcached
php-memcached:
  Installed: 3.1.3+2.2.0-1+0~20190606080318.9+buster~1.gbpb26597
```

**Comment by oerdnj** [comment]
I believe most of the extensions have been rebuilt now.

**Comment by fretb** [comment]
Awesome. I'll test this right away. Thank you!

**Comment by fretb** [comment]
Hi @oerdnj , Debian 9 seems fine now, however, Debian 10 still seems to have issues. I'll look into it more and report back.

**Comment by fretb** [comment]
@oerdnj Ignore my last comment, all is working fine. Both on Stretch and Buster. Thank you for your hard work!
