### ISSUE TITLE
PHP 7.4-beta2: session save handler for redis missing

### ISSUE THREAD

**Issue by mfn** [oerdnj/deb.sury.org#1224]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
Installed PHP 7.4 beta 2 and I'm using the redis session save handle and get this error:
`session_start(): Cannot find save handler 'redis' - session startup failed `

**To Reproduce**
1. Install `php7.4-fpm` and `php-redis`
2. Configure the redis session save handler, e.g. this in your `php.ini`:
  ```
  session.save_handler = redis
  session.save_path = "tcp://localhost:6379"
  ```
3. Open a test page/project and get the error

**Expected behavior**
It should work and session should be stored/fetch in redis.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: `deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main`

**Package(s) (please complete the following information):**
```
$ apt-cache policy php7.4-fpm php-redis
php7.4-fpm:
  Installed: 7.4.0~beta2-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.4.0~beta2-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.4.0~beta2-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
php-redis:
  Installed: 5.0.2+4.3.0-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 5.0.2+4.3.0-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 5.0.2+4.3.0-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.6-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Additional context**
It seems the whole redis module is not yet missing/ready? No mention of 7.4:
```
$ dpkg -L php-redis
/.
/etc
/etc/php
/etc/php/5.6
/etc/php/5.6/mods-available
/etc/php/5.6/mods-available/redis.ini
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/redis.ini
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/redis.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/redis.ini
/etc/php/7.3
/etc/php/7.3/mods-available
/etc/php/7.3/mods-available/redis.ini
/usr
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/redis.so
/usr/lib/php/20151012
/usr/lib/php/20151012/redis.so
/usr/lib/php/20160303
/usr/lib/php/20160303/redis.so
/usr/lib/php/20170718
/usr/lib/php/20170718/redis.so
/usr/lib/php/20180731
/usr/lib/php/20180731/redis.so
/usr/share
/usr/share/doc
/usr/share/doc/php-redis
/usr/share/doc/php-redis/changelog.Debian.gz
/usr/share/doc/php-redis/copyright
```

**Comment by oerdnj** [comment]
It’s beta2, no external extensions till at least RC or final.

**Comment by mfn** [comment]
> It’s beta2, no external extensions till at least RC or final.

Oh, sorry, wasn't aware 🤷‍♀️

**Comment by oerdnj** [comment]
It’s all or nothing, and many extensions usually needs an update. It’s a lot of work to do for beta release...

**Comment by pimjansen** [comment]
@oerdnj since PHP7.4 is now released last thursday, is this still coming? Since i don't see it being there yet

**Comment by oerdnj** [comment]
All extensions should be already available for PHP 7.4 since last week...

**Comment by pimjansen** [comment]
@oerdnj Somehow im not getting it pushed though. Missing anything here?

![image](https://user-images.githubusercontent.com/1457219/69954474-affa8880-14fb-11ea-9e74-4ba769163967.png)

**Comment by oerdnj** [comment]
Using bash completion isn't really way to check for a package.  Try installing it (`apt install`) or searching for it (`apt-cache search`)...

**Comment by pimjansen** [comment]
@oerdnj can it be that it is called `php-redis` instead?

```
➜  $ sudo apt-cache search php7.4-redis
php-redis - PHP extension for interfacing with Redis
```

**Comment by mfn** [comment]
> can it be that it is called `php-redis` instead?

It always has: it's a single package including `redis.so` for each PHP version
