### ISSUE TITLE
upgrade php7.3 on ubuntu 14.04

### ISSUE THREAD

**Issue by Kydybets** [oerdnj/deb.sury.org#1225]
I trying to install php7.3 on my ubuntu 14.04 and wasn't lucky to do that successfully.
After that I reach you repo with packages https://launchpad.net/~ondrej/+archive/ubuntu/php/
and didn't find any package for ubuntu 14.04.
Am I right that I need to use a new machine at least ubuntu 18.04 or AWS ec2 machine?

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/ubuntu-14-04-php-22093917
