### ISSUE TITLE
apache2-bin 2.4.41-1+ubuntu16.04.1+deb.sury.org+3 does not provide apache2-api-20120211

### ISSUE THREAD

**Issue by Mezzle** [oerdnj/deb.sury.org#1227]
**Describe the bug**
apache2-bin 2.4.41-1+ubuntu16.04.1+deb.sury.org+3 does not provide apache2-api-20120211
This means that it is impossible to install `libapache2-mod-fastcgi`

**To Reproduce**
1. Add PPA (tested on Xenial) to base system
2. Install apache2
3. Attempt to install libapache2-mod-fastcgi

**Expected behavior**
Package to provide api

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Output of `apt-cache policy apache2-bin`

```apache2-bin:
  Installed: 2.4.41-1+ubuntu16.04.1+deb.sury.org+3
  Candidate: 2.4.41-1+ubuntu16.04.1+deb.sury.org+3
  Version table:
 *** 2.4.41-1+ubuntu16.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.18-2ubuntu3.10 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.4.18-2ubuntu3 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

**Additional context**
Output of `apt-cache showpkg apache2-bin` shows this does not provide the api

```
<snip>
Provides:
2.4.41-1+ubuntu16.04.1+deb.sury.org+3 -
2.4.18-2ubuntu3.10 - apache2-api-20120211 (= )
2.4.18-2ubuntu3 - apache2-api-20120211 (= )
<snip>

**Comment by sysadmin1139** [comment]
As of the +5 build of the .deb packages, this seems to be resolved.

**Comment by werk21** [comment]
> As of the +5 build of the .deb packages, this seems to be resolved.

can i confirm.

ty, ky.

**Comment by oerdnj** [comment]
This seems like a weird interaction between backported debhelper, so I added the patch to downgrade the compat level to debhelper 9 again and it works again.
