### ISSUE TITLE
PHP7: zend_mm_heap corrupted

### ISSUE THREAD

**Issue by alecpl** [oerdnj/deb.sury.org#123]
Last package update broke my php installation. Almost every execution of composer or my application gives "zend_mm_heap corrupted" in error log and scripts just exit on that. How can I debug this?

**Comment by alecpl** [comment]
I created a PHP bug ticket https://bugs.php.net/bug.php?id=70657 with steps to reproduce. Could anyone try to reproduce with these packages? I will not compile latest snapshots.

**Comment by bugalot** [comment]
Hello there !

I have the same problem, and also created an issue about it on https://bugs.php.net/bug.php?id=70688. I just missed yours ;) !

Dimitry from PHP.net suggested me to run the steps to reproduce using php -n (no php.ini), but the error still persists!

Thanks a lot for all these very useful packages!

**Comment by nikic** [comment]
Another person on Reddit mentioning this issue: https://www.reddit.com/r/PHP/comments/3oubk5/php_700_rc_5_released/cw0rqlb

**Comment by oerdnj** [comment]
Right onto it.

**Comment by oerdnj** [comment]
Uploaded rc5, if this bug is not fixed, please reopen the bug.

**Comment by bugalot** [comment]
Unfortunately, it seems it is still buggy in the packages for PHP7-RC5 (7.0.0~rc5-1+deb.sury.org~trusty+2)

the same test script as reported on bugs.php.net,

```php
<?php
$date = new \DateTime('2000-01-01');
echo $date->format('Y-m-d') . "\n";
```

still throws the error on my Xubuntu 14.04 LTS (fully upgraded, up to date).

Expected result:
----------------
// -- Expected output is simple as:
2000-01-01


Actual result:
--------------
// -- Output when php.ini's directive date.timezone is commented (using ;)
2000-01-01
zend_mm_heap corrupted
// OR (randomly)
2000-01-01
Segmentation fault (core dumped)


// -- Output when php.ini's directive date.timezone = Europe/Brussels
2000-01-01
zend_mm_heap corrupted
// OR (randomly)
2000-01-01
Segmentation fault (core dumped)

Thanks again for your wonderful packages!

**Comment by bugalot** [comment]
As I did not close the issue myself, I cannot re-open it.
I will repost the issue in another track. Sorry for the duplicate!
