### ISSUE TITLE
php-yaml  / bionic / php7.4

### ISSUE THREAD

**Issue by ktomk** [oerdnj/deb.sury.org#1231]
Hi Ondřej,

would it be possible to make builds of php-yaml / bionic / php7.4?

- OS: Ubuntu 18.04.3 LTS (Bionic Beaver)
- Architecture: amd64.
. Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1224#issuecomment-523191081

**Comment by ktomk** [comment]
ack. I also didn't get it working locally, even I'm not that trained with building php extensions, I can imagine it is quite some work.

**Comment by ktomk** [comment]
Can confirm pecl build for yaml on Ubuntu 18.04 LTS and PHP 7.4.0RC3 (cli) (built: Oct  8 2019 06:09:37) ( NTS ).

Thanks a lot.
---

~~~
sudo apt install php7.4-dev
#
sudo update-alternatives --set php /usr/bin/php7.4
sudo update-alternatives --set php-config /usr/bin/php-config7.4
sudo update-alternatives --set phpize /usr/bin/phpize7.4
#
sudo pecl install yaml
echo "extension=yaml.so" | sudo tee "/etc/php/7.4/cli/conf.d/20-yaml.ini"
~~~

**Comment by oerdnj** [comment]
I'll start looking into enabling the extensions before the 7.4.0-final
