### ISSUE TITLE
Broken php-redis version

### ISSUE THREAD

**Issue by pimjansen** [oerdnj/deb.sury.org#1233]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
With the upgrade from php7.3.7 to php 7.3.8 the PHP-Redis version was bumped from 4.3 to 5.0 as well. However a lot of third party software is not compatible with 5.0 and therefor throwing a lot of deprecation errors and so on.

**To Reproduce**
https://github.com/zendframework/zend-cache/issues/185
https://phabricator.wikimedia.org/T230273
https://www.drupal.org/project/redis/issues/3068810

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
php-redis:
  Installed: 5.0.2+4.3.0-2+0~20190814.15+debian9~1.gbp070358
  Candidate: 5.0.2+4.3.0-2+0~20190814.15+debian9~1.gbp070358
  Version table:
 *** 5.0.2+4.3.0-2+0~20190814.15+debian9~1.gbp070358 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.1-1 500
        500 http://ftp.nl.debian.org/debian stretch/main amd64 Packages

**Additional context**
Overall i can not find a proper way to even downgrade to 4.x version of php-redis what maybe also would work.

**Comment by oerdnj** [comment]
Well, that's most unfortunate, but the goal of this repository is to provide latest upstream versions, and not juggle with whatever is compatible with what...

You can always install the required old version of redis by hand from PECL.

**Comment by pimjansen** [comment]
I manage to do this @oerdnj thanks for the clarification
