### ISSUE TITLE
PHP 5.6 - Solr module not present/working

### ISSUE THREAD

**Issue by gianpaolom** [oerdnj/deb.sury.org#1235]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
After the latest update of packages from the repo, `php-solr` is not working anymore on PHP 5.6

**To Reproduce**
1. have the most recent packages from the repo
2. use php 5.6
3. create a page with a simple `phpinfo()` function, and see that there is no solr module loaded

**Expected behavior**
Solr module is loaded and working 

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - Architecture: amd64
 - Repository: `http://ppa.launchpad.net/ondrej/php/ubuntu xenial main`

**Package(s) (please complete the following information):**
```
# apt-cache policy php-solr 
php-solr:
  Installed: 2.5.0-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 2.5.0-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 2.5.0-1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.0-1 500
        500 http://rackspace.clouds.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```
**Additional context**
From PHP error log:
```
27-Aug-2019 12:39:07 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/solr.so' - /usr/lib/php/20131226/solr.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by oerdnj** [comment]
Could you do: `dpkg -L php-solr`?

**Comment by oerdnj** [comment]
Oh, I see, they removed PHP 5 support from solr 2.5.0 release.

**Comment by gianpaolom** [comment]
```
# dpkg -L php-solr
/.
/etc
/etc/php
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/solr.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/solr.ini
/etc/php/7.3
/etc/php/7.3/mods-available
/etc/php/7.3/mods-available/solr.ini
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/solr.ini
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php-solr
/usr/share/doc/php-solr/copyright
/usr/share/doc/php-solr/changelog.Debian.gz
/usr/share/doc/php-solr/TODO
/usr/share/doc/php-solr/CREDITS
/usr/lib
/usr/lib/php
/usr/lib/php/20160303
/usr/lib/php/20160303/solr.so
/usr/lib/php/20151012
/usr/lib/php/20151012/solr.so
/usr/lib/php/20180731
/usr/lib/php/20180731/solr.so
/usr/lib/php/20170718
/usr/lib/php/20170718/solr.so
```

**Comment by gianpaolom** [comment]
> Oh, I see, they removed PHP 5 support from solr 2.5.0 release.

I reckon then the only solution would be rolling back to a previous version and set a hold on the package?

**Comment by oerdnj** [comment]
2.5.0+2.4.0-1 version of the package will have PHP 5.6 module too.  But you should upgrade to PHP 7 sooner than later.

**Comment by gianpaolom** [comment]
> 2.5.0+2.4.0-1 version of the package will have PHP 5.6 module too. But you should upgrade to PHP 7 sooner than later.

@oerdnj you are totally right, however the PHP application is pretty old and based on a framework, so upgrading to PHP 7.x is not so striaghtforward

Thank you for adding a package with 2.4 version. Do you suggest I mark it for hold?

**Comment by oerdnj** [comment]
No, you don't have to.
