### ISSUE TITLE
PHP 7.4 cannot build extensions

### ISSUE THREAD

**Issue by kmdm** [oerdnj/deb.sury.org#1236]
**Unsupported distributions**
 - [ X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
When attempting to build extensions with the PHP 7.4 beta packages it fails with the following error:

```
Configuring for:
PHP Api Version: 20190529
Zend Module Api No: 20190529
Zend Extension Api No: 320190529
configure.ac:161: warning: LTOPTIONS_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure:5667: error: possibly undefined macro: m4_ifval
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:9136: error: possibly undefined macro: _LT_SET_OPTIONS
configure:9136: error: possibly undefined macro: LT_INIT
```

**To Reproduce**
1. Download an extension
2. Run phpize

**Expected behavior**
It successfully creates the configure and associated files

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: N/A packages built directly from salsa.d.o/php-team/php

**Package(s) (please complete the following information):**
N/A since the packages were built off the salsa.d.o repo but with the latest php upstream (beta4) imported.

**Additional context**
This is caused by `d/p/0003-libtool-2.2.patch`, this patch copies files which create a dependency on aclocal however the php 7.4 build system abandons the use of aclocal. 

It seems like this patch could be removed or prior to `m4_include`'ing `libtool.m4` the various required files could be included first, such as: `ltoptions.m4`, `ltversion.m4`, `ltsugar.m4` and `lt~obsolete.m4`. 

Both options appeared to work when I tested during the shell handler of `gbp buildpackage`.

**Comment by kmdm** [comment]
(Also reported against xdebug from the Ubuntu PPA packaging here: https://bugs.xdebug.org/view.php?id=1695)

**Comment by oerdnj** [comment]
Should be fixed (well, I just removed the patch) in beta4 that I uploaded yesterday.

**Comment by kmdm** [comment]
Yeah that should work. In my packages I created a patch that reverted it so it'd intentionally conflict with anything you changed.

Thus, removing it should achieve the same effect. 

Thanks!
