### ISSUE TITLE
ZTS-Enabled PHP Package

### ISSUE THREAD

**Issue by robfrawley** [oerdnj/deb.sury.org#124]
Is it possible for you to offer a `php5-zts` package with Zend Thread Safety enabled? (I need support for the PECL `pthreads` library)

**Comment by robfrawley** [comment]
@oerdnj Just noticed your previous responses... Thanks.

**Comment by oerdnj** [comment]
Folks, if you want to shoot yourself in foot, the new packaging infrastructure I built for PHP 7.0 allows to build variants quite easily, so here's experimental, totally unsupported PPA with PHP 7.0 ZTS: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts

No external modules, no batteries, no support (patches accepted and welcomed).
