### ISSUE TITLE
The repository 'http://ppa.launchpad.net/ondrej/pkg-gearman/ubuntu bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by ozsynergy** [oerdnj/deb.sury.org#1244]
**Describe the bug**

pkg-gearman is has not been built for ubuntu 18.04

**To Reproduce**

Dockerfile
In ubuntu 18.04
Run  `add-apt-repository -y ppa:ondrej/pkg-gearman`

The repository 'http://ppa.launchpad.net/ondrej/pkg-gearman/ubuntu bionic Release' does not have a Release file.

**Expected behavior**
No error

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository:   ppa:ondrej/pkg-gearman

**Comment by oerdnj** [comment]
Uploaded 1.1.18 for Ubuntu 16.04 and up.

**Comment by ozsynergy** [comment]
Thank you
