### ISSUE TITLE
libidn 2.2 breaks Bionic

### ISSUE THREAD

**Issue by programmador** [oerdnj/deb.sury.org#1248]
**Bug description**
libidn2-0 2.2 seems incompatible with Ubuntu Bionic. Half of OS stops working. For example, `apt-get update` tells that it couldn't find some symbol in libidn *so.

**Distribution:**
 - OS: Ubuntu Bionic (18.04 LTS)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Temporary fix:**
Downgraded manually (fortunately firefox was still working though first I had to run `dhclient` manually) and prevented upgrades by creating a file `/etc/apt/preferences.d/libidn2-0` with next content:

```
Package: libidn2-0
Pin: origin "ppa.launchpad.net/ondrej/php/ubuntu"
Pin-Priority: -1
```

**Comment by oerdnj** [comment]
#1247
