### ISSUE TITLE
Debian Buster php5.6-curl canno't be installed because it depends on libcurl3

### ISSUE THREAD

**Issue by flojug** [oerdnj/deb.sury.org#1249]
Debian Buster amd64

apt install php5.6-curl
..
 php5.6-curl : depends on libcurl3 (>= 7.18.0) but it is not installable

Can it be linked with libcurl4 ?

**Comment by MaryanShvets** [comment]
the same problem was fixed by adding
to the source list such line

 deb https://packages.sury.org/php/ buster main

and after that

sudo apt update
sudo apt install php5.6-curl

**Comment by realtebo** [comment]
I confirm same solution for the new Debian 11 bullseye

changed `/etc/apt/sources.list.d/php.lst` to refelect new version

`deb https://packages.sury.org/php/ buster main`

and after that

```
sudo apt update
sudo apt install php5.6-curl
```
