### ISSUE TITLE
Apache 2.4.17 w/ HTTP2 support

### ISSUE THREAD

**Issue by danielcolchete** [oerdnj/deb.sury.org#125]
Hi Ondřej!

I'm really anxious to have an Apache 2.4.17 running with HTTP2 support on my Ubuntu 14.04 LTS server. 

I did some tests here and did a plain ./configure compilation and it works great. The problem with generating a package for trusty is that it requires openssl 1.0.2+ and libnghttp2 1.0+, both not available in trusty. With openssl I backported from willy, but libnghttp2 is not available even in willy.

But I assure you its worth it! HTTP2 makes sites load up to 50% faster, specially on mobile networks.

It would be great with we could use ready made packages from your ppa.

Thank you very much

Best,
Daniel Colchete

**Comment by danielcolchete** [comment]
Btw, if you are going to get nghttp2 from debian (they have version 1.3.2 on sid) you will need to run the following command before building the package:

pip install sphinxcontrib-rubydomain --pre

This python module is required in order to build package, although it doesn't have a package anywhere (so it's not a build dependency).

**Comment by oerdnj** [comment]
If I go this way, I will have to drop the support for Ubuntu Precise as there are several packages missing it's hard to backport.  I am preparing something in ppa:ondrej/apache2, so might check it there.

**Comment by oerdnj** [comment]
Yes, I tried to backport some more stuff, but it would result in pulling python3, so I am definitely not going to support http/2 on Ubuntu Precise.

**Comment by oerdnj** [comment]
@danielcolchete, could you test with apache2 from https://launchpad.net/~ondrej/+archive/ubuntu/apache2
(it's almost built)

**Comment by nemiah** [comment]
Hi, I downloaded the current packages to my 14.04 and things are looking good: https://cloud2.furtmeier.it/app_Furtmeier (ipv6 only, sorry ;)

I'll try the http2 module as soon as it is ready.

Nemi

**Comment by oerdnj** [comment]
The http2 module should be already included on trusty and upwards. Just no precise.

And BTW I also packaged the sphinxcontrib-rubydomain, so it doesn't need the pip installation.

**Comment by nemiah** [comment]
LoadModule http2_module /usr/lib/apache2/modules/mod_http2.so works!
