### ISSUE TITLE
Debian 10 PHP install fails with missing Release Files

### ISSUE THREAD

**Issue by old-engr** [oerdnj/deb.sury.org#1250]
**Unsupported distributions**
 - [] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/ubuntu-14-04-php-22093917)

**Describe the bug**
-- I apologize up front if all of this is due to my ignorance --
I have attempted to follow the instructions for upgrading PHP from 7.1 for testing; then want to move to 7.2 and 7.3. I started on a Debian 8 system following the the instructions from https://www.mysterydata.com/how-to-upgrade-php-7-0-to-php-7-1-or-php-7-2-on-ubuntu-vestacp/ but apt-get update kept reporting errors (missing files). So I first updated to Debian 9 and then Debian 10. I then attempted the PHP installs again from https://tecadmin.net/install-php-debian-9-stretch/. Here is the output:

dev:~# apt install apt-transport-https lsb-release ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20190110).
ca-certificates set to manually installed.
lsb-release is already the newest version (10.2019051400).
lsb-release set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
...
dev:~# wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
OK
dev:~# echo "deb https://packages.sury.org/php/ buster main" | tee /etc/apt/sources.list.d/php.list deb https://packages.sury.org/php/ buster main
dev:~# apt update
Hit:1 http://ftp.us.debian.org/debian buster InRelease
Hit:2 http://ftp.us.debian.org/debian buster-updates InRelease
Ign:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu jessie InRelease
Hit:4 http://security.debian.org buster/updates InRelease
Ign:5 http://packages.dotdeb.org buster InRelease
Err:6 http://packages.dotdeb.org buster Release
  404  Not Found [IP: 195.154.242.153 80]
Get:7 https://packages.sury.org/php buster InRelease [6,759 B]
Ign:8 http://ppa.launchpad.net/ondrej/php/ubuntu jessie InRelease
Ign:9 http://ppa.launchpad.net/ondrej/apache2/ubuntu eoan InRelease
Get:10 https://packages.sury.org/php buster/main amd64 Packages [125 kB]
Ign:11 http://ppa.launchpad.net/ondrej/php/ubuntu eoan InRelease
Err:12 http://ppa.launchpad.net/ondrej/apache2/ubuntu jessie Release
  404  Not Found [IP: 91.189.95.83 80]
Err:13 http://ppa.launchpad.net/ondrej/php/ubuntu jessie Release
  404  Not Found [IP: 91.189.95.83 80]
Err:14 http://ppa.launchpad.net/ondrej/apache2/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
Err:15 http://ppa.launchpad.net/ondrej/php/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://packages.dotdeb.org buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ondrej/apache2/ubuntu jessie Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu jessie Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ondrej/apache2/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64 [AMD Athlon(tm) II X2 250 Processor]
 - Repository: Ubuntu PPA or packages.sury.org -- I have tried both

**Package(s) (please complete the following information):**
Please see output above. I am sorry if the above is not enough information, I am not sure what else to do.

**Additional context**
Please see connents at beginning of submission.

**Comment by oerdnj** [comment]
Your system is a mess. There’s a mix a repositories for Jessie, Buster and Eoan
