### ISSUE TITLE
The repository 'https://packages.sury.org/php buster Release' no longer has a Release file.

### ISSUE THREAD

**Issue by erbap** [oerdnj/deb.sury.org#1251]
After a dist-upgrade from Debian 9 to 10 (witch works without errors) I receive followin error:
`root@vm-deb-pydio:~# apt update
Hit:1 http://ftp.be.debian.org/debian buster InRelease
Ign:2 https://packages.sury.org/php buster InRelease                                                                
Hit:3 http://ftp.be.debian.org/debian buster-updates InRelease                                                      
Hit:4 http://security.debian.org/debian-security buster/updates InRelease
Err:5 https://packages.sury.org/php buster Release                       
  Could not handshake: A TLS fatal alert has been received. [IP: 104.31.94.169 443]
Reading package lists... Done                      
E: The repository 'https://packages.sury.org/php buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
My configuration is not changed after the update
`root@vm-deb-pydio:~# cat /etc/apt/sources.list.d/sury.list
deb https://packages.sury.org/php/ buster main
`

I have tried to re-add the key without any difference
`root@vm-deb-pydio:~# apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B188E2B695BD4743
Executing: /tmp/apt-key-gpghome.N2Qsu0A64u/gpg.1.sh --keyserver ha.pool.sks-keyservers.net --recv-keys B188E2B695BD4743
gpg: key B188E2B695BD4743: "DEB.SURY.ORG Automatic Signing Key <deb@sury.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
`

**Comment by oerdnj** [comment]
There’s error when establishing TLS, you’ll need to debug that first...

Could not handshake: A TLS fatal alert has been received. [IP: 104.31.94.169 443]

**Comment by erbap** [comment]
I have several servers wit Debian 10 and only a few of them give this
error, after I did an dist-upgrade.
I'm not an apt/gpg/tls expert but is this a problem on my site (client) or
on the server side (repo)?

> root@vm-deb-pydio:~# gnutls-cli -V -V packages.sury.org:443
> Processed 128 CA certificate(s).
> Resolving 'packages.sury.org:443'...
> Connecting to '104.31.94.169:443'...
> *** Fatal error: A TLS fatal alert has been received.
> *** Received alert [49]: Access was denied

**Comment by erbap** [comment]
I have 2 different Debian 10 servers, one OK the other with this error.
When I run 'gnutls-cli -V -d9 packages.sury.org:443' on both the I receive on the BAD host:
`> |<5>| REC[0x559fb1395a30]: SSL 3.1 Alert packet received. Epoch 0, length: 2
> |<5>| REC[0x559fb1395a30]: Expected Packet Handshake(22)
> |<5>| REC[0x559fb1395a30]: Received Packet Alert(21) with length: 2
> |<5>| REC[0x559fb1395a30]: Decrypted Packet[0] Alert(21) with length: 2
> |<5>| REC[0x559fb1395a30]: Alert[2|49] - Access was denied - was received
> |<3>| ASSERT: ../../lib/record.c[record_add_to_buffers]:878
> |<3>| ASSERT: ../../lib/record.c[record_add_to_buffers]:885
> |<3>| ASSERT: ../../lib/record.c[_gnutls_recv_in_buffers]:1577
> |<3>| ASSERT: ../../lib/buffers.c[_gnutls_handshake_io_recv_int]:1448
> |<3>| ASSERT: ../../lib/handshake.c[_gnutls_recv_handshake]:1506
> |<3>| ASSERT: ../../lib/handshake.c[handshake_client]:2998
> *** Fatal error: A TLS fatal alert has been received.`

And on the GOOD host I receive:
`< |<5>| REC[0x5590c6be6af0]: SSL 3.3 Handshake packet received. Epoch 0, length: 90
< |<5>| REC[0x5590c6be6af0]: Expected Packet Handshake(22)
< |<5>| REC[0x5590c6be6af0]: Received Packet Handshake(22) with length: 90
< |<5>| REC[0x5590c6be6af0]: Decrypted Packet[0] Handshake(22) with length: 90
< |<4>| HSK[0x5590c6be6af0]: SERVER HELLO (2) was received. Length 86[86], frag offset 0, frag length: 86, sequence: 0`

Do you have any idee why I receive to different SSL packet versions? Can I force SSL 3.3 and tell the server that I'm not interested in 3.1?

**Comment by erbap** [comment]
Hoera, problem solved.
On the fortigate FW there was an outgoing rule that inspect the certificates and that give us this problem. By disabling this rule everything works great.

Many thanks for your quick reply.
