### ISSUE TITLE
dbg symbols php7.0.33-11 missing

### ISSUE THREAD

**Issue by Huweh** [oerdnj/deb.sury.org#1252]
Hi,

php7.0-cli-dbgsym is not in the repo for 7.0.33-11

dpkg: dependency problems prevent configuration of php7.0-cli-dbgsym:
 php7.0-cli-dbgsym depends on php7.0-cli (= 7.0.33-10+0~20190807.18+debian10~1.gbp5452d8); however:
  Version of php7.0-cli on system is 7.0.33-11+0~20190902.19+debian8~1.gbpd05c7e. 
(Debian Jessie)

The cli version is ahead of the package. 
When i check https://packages.sury.org/php/pool/main/p/php7.0/ , there is no dbg package for 7.0.33-11

Thanks

**Comment by dupondje** [comment]
Seems like dh_strip in Jessie doesn't support the options passed:
dh_strip --dbgsym-migration='php7.0-dbg' || dh_strip
dh_strip: unknown option; aborting

**Comment by oerdnj** [comment]
Yes, debugging symbols are not supported on Jessie. You should be upgrading sooner than later anyway. Even Jessie LTS will be EOL in less than year.
