### ISSUE TITLE
Debian buster and wine32 AND libidn2-0.

### ISSUE THREAD

**Issue by verberden** [oerdnj/deb.sury.org#1254]
Hello, the problem is:
if i got installed wine32 then i couldn't upgrade libidn2-0 from 'apt upgrade'.
If i do manually 'apt install  libidn2-0' then it's seems like some packeges would be deleted:
'libcups2:i386 libgnutls30:i386 libidn2-0:i386 libldap-2.4-2:i386 libwine:i386 wine32:i386'.

As far as i could understand it because of missing new version of libidn2-0 i386 package. So i'm just hold a stable version of libidn2-0. 

Thanks.

**Comment by mbretter** [comment]
IMHO this is a problem with 32bit dependencies, I have the same problem, when trying to install wine32.
 libjbig0 : Breaks: libjbig0:i386 (!= 2.1-3.1+deb.sury.org~xenial+1) but 2.1-3.1build1 is to be installed
 libjbig0:i386 : Breaks: libjbig0 (!= 2.1-3.1build1) but 2.1-3.1+deb.sury.org~xenial+1 is to be installed

**Comment by oerdnj** [comment]
I just started the `ruby-ronn` build that's required to build new libidn-2-0 and should solve the problem.

**Comment by verberden** [comment]
Yeh, i made an apt update-upgrade and everything is fine. So, issue could be closed now, i guess. Thanks.

**Comment by verberden** [comment]
Yeh, i made an apt update-upgrade and everything is fine. So, issue could be closed now, i guess. Thanks.
