### ISSUE TITLE
PHP 7.3.10, 7.2.23

### ISSUE THREAD

**Issue by anamba** [oerdnj/deb.sury.org#1256]
PHP 7.3.10 (security) and 7.2.23 (bugfix) are out. I'm using the Ubuntu PPA. Thank you for the work you do here!

**Comment by janreges** [comment]
Also, a new version of Nginx 1.17.4 was released.

@oerdnj, thank you for your work! :-)

**Comment by gregorg** [comment]
cipher aes-256-cbc-hmac-sha256 is missing in this release. Was available in 7.3.9.

**Comment by gregorg** [comment]
downgraded libssl1.1 from 1.1.1d to 1.1.1c and aes-256-cbc-hmac-sha256 is now available.

**Comment by oerdnj** [comment]
Uploaded all, nginx is building.  Unfortunately, for Ubuntu 16.04, it required updated luajit package, so it needs to be built first.
