### ISSUE TITLE
Unnecessary parsing of tmpfiles.d config in FPM init script

### ISSUE THREAD

**Issue by onlime** [oerdnj/deb.sury.org#1258]
In FPM init scripts (e.g. `/etc/init.d/php7.3-fpm`), you're doing an unnecessary parsing of the following tmpfiles.d config, `/usr/lib/tmpfiles.d/php7.3-fpm.conf`:

```
#Type Path        Mode UID      GID      Age Argument
    d /run/php    0755 www-data www-data -   -
```

The `/run/php` directory then gets created manually in init script. I don't get the point here, as this is already done automagically by tmpfiles.d upon system startup, before actually launching the init script.

Proposed change (for all PHP versions):

```diff
--- /etc/init.d/php7.3-fpm.DIST	2019-10-03 08:11:30.033158095 +0200
+++ /etc/init.d/php7.3-fpm	2019-10-03 08:13:26.174071771 +0200
@@ -93,40 +93,16 @@
 	return 0
 }
 
-do_tmpfiles() {
-    local type path mode user group
-
-    [ "$1" != no ] && V=-v
-    
-    TMPFILES=/usr/lib/tmpfiles.d/php7.3-fpm.conf
-
-    if [ -r "$TMPFILES" ]; then
-	while read type path mode user group age argument; do
-	    if [ "$type" = "d" ]; then
-		mkdir $V -p "$path"
-		chmod $V "$mode" "$path"
-		chown $V "$user:$group" "$path"
-	    fi
-	done < "$TMPFILES"
-    fi
-}
-
 case "$1" in
     start)
 	if init_is_upstart; then
 	    exit 1
 	fi
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_tmpfiles $VERBOSE
+	do_start
 	case "$?" in
-	    0)
-		do_start
-		case "$?" in
-		    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-	    1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
     stop)
```

**To Reproduce**
1. Remove above sections from `/etc/ini.d/php7.3-fpm`
2. Reboot
3. `/run/php` was created with correct ownership/perms

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Packages:**

```
php7.3-fpm 7.3.9-1+0~20190902.44+debian9~1.gbpf8534c
php7.2-fpm 7.2.22-1+0~20190902.26+debian9~1.gbpd64eb7
php7.1-fpm 7.1.32-1+0~20190902.23+debian9~1.gbp9d1be7

**Comment by onlime** [comment]
ok, as I understand, you don't want people to depend on Systemd, as this functionality only comes with **systemd-tmpfiles**. Is that the reason?

**Comment by oerdnj** [comment]
When systemd is used the init.d script is not. The package need to support both init systems...

**Comment by onlime** [comment]
True. Thanks for explanation and sorry about the noise.
