### ISSUE TITLE
Apache 2.4.17 has problems with SCRIPT_NAME

### ISSUE THREAD

**Issue by tdm4** [oerdnj/deb.sury.org#126]
After upgrading to Apache 2.4.17 this morning, Drupal site broke. It was redirecting from https://www.example.com to https://www.example.comhttps/install.php.

It's as if the SCRIPT_NAME (in $_SERVER) was messed up. Downgrading back to Apache 2.4.16 fixed the problem.

**Comment by oerdnj** [comment]
Interesting, could you perhaps take this to apache2 bugzilla here?
https://bz.apache.org/bugzilla/

The only difference (on trusty+) I did between the packages was enabling the mod_http2.

**Comment by tdm4** [comment]
This is on Ubuntu Precise (12.04)

**Comment by oerdnj** [comment]
Ubuntu Precise is just new upstream version. No changes to compilation then.

**Comment by oerdnj** [comment]
+ new OpenSSL version to DHParams

**Comment by tdm4** [comment]
I got some more information.

Using print_r($_SERVER['SCRIPT_NAME']) on Apache 2.4.16, it came back as 'index.php'
On Apache 2.4.17, it comes back as 'https://www.example.com')

I'm just wondering if something changed, perhaps it wasn't Apache but libapache2-mod-fastcgi?
(Something changed between 2.4.7~0910052141-1.1+debphp.org~precise+1 and 2.4.7~0910052141-1.2+deb.sury.org~precise+3?

At this point I'm not sure if it's the Apache binary or the libapache2-mod-fastcgi. I don't think I can update one without updating the other, can I?

**Comment by oerdnj** [comment]
Nah, libapache2-mod-fastcgi 1.1 to 1.2 was just about packaging (dropping dpatch and some minor nits).

But libapache2-mod-fastcgi could use some deprecated structures, etc...

Have you tried:
https://httpd.apache.org/docs/trunk/mod/mod_proxy_fcgi.html

**Comment by tdm4** [comment]
OK I've narrowed it down to Apache itself (not libapache2-mod-fastcgi).

Printing out $_SERVER variables (the ones that changed):

REDIRECT_URL:
   2.4.16 = /index.php
   2.4.17 = http://www.example.com/

SCRIPT_NAME:
   2.4.16 = /index.php
   2.4.17 = http://www.example.com/

PHP_SELF:
   2.4.16 = /index.php
   2.4.17 = http://www.example.com/

All other variables are the same. The 2.4.16 variables are correct, the 2.4.17 variables are totally wrong and break the site horribly.

Also found this:
http://stackoverflow.com/questions/21265469/php-serverscript-name-is-wrong-when-loading-php-via-mod-fcgid

Does this mean I need to change FcgidFixPathinfo to 0?

**Comment by oerdnj** [comment]
To tell the truth, I run php5-fpm with nginx for several years now, so I can't help you much here.

**Comment by tdm4** [comment]
Setting cgi.fix_pathinfo = 0 in /etc/php5/fpm/php.ini appears to fix the problem on Apache 2.4.7.
But the PHP docs say:

cgi.fix_pathinfo boolean
Provides real PATH_INFO/ PATH_TRANSLATED support for CGI. PHP's previous behaviour was to set PATH_TRANSLATED to SCRIPT_FILENAME, and to not grok what PATH_INFO is. For more information on PATH_INFO, see the CGI specs. Setting this to 1 will cause PHP CGI to fix its paths to conform to the spec. A setting of zero causes PHP to behave as before. **It is turned on by default. You should fix your scripts to use SCRIPT_FILENAME rather than PATH_TRANSLATED.**

(emphasis mine)

So this variable should be turned on to conform to spec.. but Apache 2.4.7 breaks it now?

**Comment by tdm4** [comment]
I spoke too soon. Setting cgi.fix_pathinfo = 0 still breaks the site in places.
I guess I will just have to downgrade and hold the package at 2.4.6 for now.

**Comment by voku** [comment]
@tdm4 I also had some trouble with the upgrade, so my site breaks because %{REQUEST_FILENAME}  wasn't correct, I think so, but I am not sure?! So I switch from PHP-FPM to FastCGI and now it works! But again I am not sure why?

**Comment by voku** [comment]
"Revert REDIRECT_URL to pre-2.4.17 behavior for now. The change broke lots of web-apps. Closes: #803353" - https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1367427.html

from https://packages.debian.org/de/sid/apache2 -> http://metadata.ftp-master.debian.org/changelogs//main/a/apache2/apache2_2.4.17-2_changelog

**Comment by tdm4** [comment]
Wow. That is a spectacular FAIL.

**Comment by oerdnj** [comment]
Uploaded 2.4.17-2

**Comment by voku** [comment]
thx @oerdnj :)

**Comment by tdm4** [comment]
Thanks for this @oerdnj !
