### ISSUE TITLE
Build php-memcached for PHP 7.4

### ISSUE THREAD

**Issue by daiwai** [oerdnj/deb.sury.org#1260]
Seems like the php-memcached extension has not been updated yet for PHP 7.4 on Ubuntu 19.04.

Running PHP gives:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object`

The version of the installed php-memcached package is: `3.1.3+2.2.0-1+ubuntu19.04.1+deb.sury.org+1`

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1224#issuecomment-523191081

**Comment by ruudk** [comment]
@oerdnj Thanks for all your work on this. Now that RC6 is released and PHP 7.4 will be released soon, is it possible to get `php-memcached` to install on PHP7.4?

**Comment by Trainmaster** [comment]
@ruudk @oerdnj Now that PHP 7.4 has been released it's time to update `php-memcached`.
