### ISSUE TITLE
PECL Imagick 3.4.4 extension is not compatible with Imagick 6 (ubuntu xenial)

### ISSUE THREAD

**Issue by rafaeltovar** [oerdnj/deb.sury.org#1261]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**
On Ubuntu Xenial 16.04 the PECL Imagick extension was upgrade to last version (3.4.4) with PHP 7.1, but this package is not backward compatible, because use Imagemagick 7, and this is not included on Ubuntu Xenial.

**To Reproduce**

Obtain an Deprecated exception on some functions. The list of functions is here: http://pecl.php.net/package-changelog.php?package=imagick&release=3.4.4

**Expected behavior**
Work well. :)

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: http://ppa.launchpad.net/ondrej/php/ubuntu xenial main

**Package(s) (please complete the following information):**
```
php-imagick:
  Installed: 3.4.4-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 3.4.4-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 3.4.4-1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.0~rc6-1ubuntu3 500
        500 http://mirrors.digitalocean.com/ubuntu xenial/universe amd64 Packages
```
**Additional context**

Code compatible with Imagemagick 6.* is not compatible with pecl imagick 3.4.4.

**Comment by oerdnj** [comment]
I don't really know what you are trying to say and what you want to accomplish with this issue?

Are you saying that Imagemagick 7 is required to support some functionality of php-imagick, and you want me to package it?  It needs to be first packaged at least in Debian/Ubuntu latest and that's still on 6.9.x. I don't have time to add yet another package with high risk of breakage to the portfolio of my packages.

**Comment by rafaeltovar** [comment]
Ok, imagine this code:

```
if (version_compare(phpversion('imagick'), '3.4.3', '>=')) {
  $imagick->setImageAlpha($pixel->getColorValue(\Imagick::COLOR_ALPHA));
} else {
  $imagick->setImageOpacity($pixel->getColorValue(\Imagick::COLOR_ALPHA));
}
```

`SetImageAlpha` was added on 3.4.3RC2 PECL Imagick extension replacing `SetImageOpacity`.

```
3.4.3RC2 Changelog
...
- Added:
* function Imagick::setImageAlpha() which replaces Imagick::setOpacity()
```
(I think this is a typo error, they mean `Imagick::setImageOpacity`).

http://pecl.php.net/package-changelog.php?package=imagick&release=3.4.3

But on 3.4.4RC2 PECL Imagick extension `SetImageOpacity` was deprecated:

```
3.4.4RC2 Changelog
..
* The following functions have been deprecated:
ImagickDraw, matte
....
Imagick::setimagemattecolor
Imagick::setimagebiasquantum
> Imagick::setimageopacity
Imagick::transformimage
```
http://pecl.php.net/package-changelog.php?package=imagick&release=3.4.4

The new method `SetImageAlpha` only works with ImageMagick 7, and, by default, Ubuntu 16.04 and 18.04 has Imagemagick 6.8.9.x

https://packages.ubuntu.com/search?keywords=imagemagick

Then, if I use `setImageOpacity` I obtain a deprecated exception, and if I use the new method `setImageAlpha` I obtain a not found method exception.

Then the only way that I have to workaround with opacity is in Imagemagick 6.8.9.x with PECL 3.4.3 or in Imagemagick 7.x with PECL 3.4.4. Is this correct?

If this is correct, then there is a backward incompatibility between PECL 3.4.4 Imagick package, and the version of Imagemagick on Ubuntu 16.04 and 18.04, as well.

**Comment by oerdnj** [comment]
ImageMagick is undermaintained in Debian and I don't have enough resources to help with ImageMagick packaging, it's too complex to have it as a side-project, so I am just closing this issue.  Once ImageMagick 7 is packaged, I might backport it, but I am not going to do the packaging myself.
