### ISSUE TITLE
libssl1.1 : Breaks: isync (< 1.3.0-2)

### ISSUE THREAD

**Issue by ubuntupunk** [oerdnj/deb.sury.org#1263]
**Describe the bug**
libssl1.1 : Breaks: isync (< 1.3.0-2) but 1.3.0-1ubuntu0.18.04.0 is to be installed

**To Reproduce**

Install isync

**Expected behavior**

**Distribution (please complete the following information):**
 -Ubuntu Bionic
amd64 

ubuntu ppa

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
apt-cache policy libssl1.1 
libssl1.1:
  Installed: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
     1.1.1-1ubuntu2.1~18.04.4 500
        500 http://za.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     1.1.0g-2ubuntu4 500
        500 http://za.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

apt-cache policy isync
isync:
  Installed: (none)
  Candidate: 1.3.0-1ubuntu0.18.04.0
  Version table:
     1.3.0-1ubuntu0.18.04.0 500
        500 http://za.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
     1.3.0-1build1 500
        500 http://za.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

https://answers.launchpad.net/ubuntu/+question/684828

**Comment by oerdnj** [comment]
Yes, the new libssl1.1 can’t be installed with isync. You can’t have it all, use isolation or hold back libssl1.1.
