### ISSUE TITLE
basename() function trims first cyrillic letters

### ISSUE THREAD

**Issue by infra-hdc** [oerdnj/deb.sury.org#1266]
**Describe the bug**
Under apache2, trims base name of string, if it begins with cyrillic letters.
Under CLI, it is OK.

**To Reproduce**
1. Make file /var/www/my-cool-site/basename.php with the following contents:
```
<?php
Header("content-type: text/plain;");
function bname($a) {
        echo "base name of ".$a." is ".basename($a)."\n";
}

bname("/etc/fstab");
bname("/path/to/111.txt");
bname("hello fstab");
bname("fstab");
bname("мир");
bname("привет мир");
bname("/путь/к/привет мир");
bname("статистика-20190910T070336Z-001.zip");

?>
```
3. See no error in CLI
```
$ php ./basename.php 
base name of /etc/fstab is fstab
base name of /path/to/111.txt is 111.txt
base name of hello fstab is hello fstab
base name of fstab is fstab
base name of мир is мир
base name of привет мир is привет мир
base name of /путь/к/привет мир is привет мир
base name of статистика-20190910T070336Z-001.zip is статистика-20190910T070336Z-001.zip
```
4. See error in web browser
```
base name of /etc/fstab is fstab
base name of /path/to/111.txt is 111.txt
base name of hello fstab is hello fstab
base name of fstab is fstab
base name of мир is 
base name of привет мир is  мир
base name of /путь/к/привет мир is  мир
base name of статистика-20190910T070336Z-001.zip is -20190910T070336Z-001.zip
```

**Distribution:**
 - OS: Debian GNU/Linux 10.1.0 (Buster) AMD64 + all updates
 - Architecture: AMD64
 - Repository: packages.sury.org

**Package(s):**
```
$ LANG=C apt-cache policy php5.6
php5.6:
  Installed: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Candidate: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Version table:
 *** 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ LANG=C apt-cache policy apache2
apache2:
  Installed: 2.4.38-3+deb10u3
  Candidate: 2.4.38-3+deb10u3
  Version table:
 *** 2.4.38-3+deb10u3 500
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.38-3+deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
$ LANG=C apt-cache policy libapache2-mod-php5.6
libapache2-mod-php5.6:
  Installed: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Candidate: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Version table:
 *** 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ LANG=C apt-cache policy php5.6-cli
php5.6-cli:
  Installed: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Candidate: 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b
  Version table:
 *** 5.6.40-13+0~20191026.22+debian10~1.gbp37e45b 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
In other environment, Ubuntu 18.04.3 LTS AMD64, it is OK.

**Comment by oerdnj** [comment]
Why do you expect the locale settings to be same for CLI and Apache? This doesn’t seem like a problem in packaging.

**Comment by infra-hdc** [comment]
> Why do you expect the locale settings to be same for CLI and Apache? This doesn’t seem like a problem in packaging.

Hello! I am sorrry. I was tested this bugreport in a clear VMs, that set up today. In both cases, environment variable LANG=C. Please See proof attachments. What LANG= value is correct to fix this?

[phpinfo-debian-failed.pdf](https://github.com/oerdnj/deb.sury.org/files/3775147/phpinfo-debian-failed.pdf)
[phpinfo-ubuntu-passed.pdf](https://github.com/oerdnj/deb.sury.org/files/3775148/phpinfo-ubuntu-passed.pdf)

**Comment by infra-hdc** [comment]
> Why do you expect the locale settings to be same for CLI and Apache? This doesn’t seem like a problem in packaging.

Thanks a lot! Change apache locale solves the problem.

**Comment by oerdnj** [comment]
I don’t know, try any UTF-8 locale if you are using UTF-8 strings.

I afraid I can help you with debugging the problem, as I said earlier, this is not directly related to packaging.

**Comment by oerdnj** [comment]
Glad to hear that, my guess was just a hunch because you compared apache2 running as system unit with CLI usually run under a user.
