### ISSUE TITLE
Request to provide PSR extension

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1267]
**Is your feature request related to a problem? Please describe.**
No, just that it would be great to have `PSR` extension as a package

**Describe the solution you'd like**
Please provide `PSR` extension as a package from `deb.sury.org`

**Describe alternatives you've considered**
compile and Install
```bash
git clone https://github.com/jbboehr/php-psr.git
cd php-psr
/usr/local/bin/phpize
./configure --with-php-config=/usr/local/bin/php-config
make
make test
sudo make install
```

**Distribution (please complete the following information):**
 - OS: ubuntu
 - Repository: https://github.com/jbboehr/php-psr
 - PECL: https://pecl.php.net/package/psr

**Comment by oerdnj** [comment]
dup of #1067

**Comment by shivammathur** [comment]
Thanks
