### ISSUE TITLE
Request to provide uopz extension

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1269]
**Is your feature request related to a problem? Please describe.**
No, Please provide `uopz` extension as a package

**Describe the solution you'd like**
Please provide `uopz` extension as a package from deb.sury.org

**Describe alternatives you've considered**
compile and install
```
git clone https://github.com/krakjoe/uopz.git
cd uopz
phpize
./configure --enable-uopz  [ --enable-uopz-coverage ] [ --with-uopz-sanitize ]
make
make test
make install
```
**Distribution (please complete the following information):**
 - OS: ubuntu
 - Git Repository: https://github.com/krakjoe/uopz
 - PECL: https://pecl.php.net/package/uopz

**Comment by oerdnj** [comment]
Done for Ubuntu, packages for Debian are in the build queue.

**Comment by shivammathur** [comment]
Thanks 👍
