### ISSUE TITLE
apt update failure: 'https://packages.sury.org/php bionic Release' does not have a Release file

### ISSUE THREAD

**Issue by abcondas** [oerdnj/deb.sury.org#1270]
**Unsupported distributions**
 - [X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [X ] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**
I have found similar issues but nothing exactly like mine.  Thanks in advance for the assistance.
_Please note: This is occurring on Windows 10/Ubuntu Subsystem (WSL) - this is working for other team members using this same setup, AFAIK_
First, I installed the WSL, ran an `apt-get update` (worked fine), then ran an `apt-get upgrade` (worked fine).
Then I ran through the commands: https://packages.sury.org/php/README.txt
Upon the next `apt-get update` I encountered this error:
`Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                      Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                                  Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                                                    Ign:4 https://packages.sury.org/php bionic InRelease                                                                                                         Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                                                  Err:6 **https://packages.sury.org/php bionic Release                                                                                                             404  Not Found [IP: 104.31.95.169 443]**                                                                                                                     Reading package lists... Done                                                                                                                                E: The repository **'https://packages.sury.org/php bionic Release' does not have a Release file**.                                                               N: Updating from such a repository can't be done securely, and is therefore disabled by default.                                                             N: See apt-secure(8) manpage for repository creation and user configuration details.`

**To Reproduce**
Same as above

**Expected behavior**
`apt-get update` succeeds

**Distribution (please complete the following information):**
 - OS: [Ubuntu/WSL (Debian10/buster) through Windows 10]
 - Architecture: [intel 64-bit]
 - Repository: [packages.sury.org]

**Package(s) (please complete the following information):**
output of apt list --installed:
lsb-release/bionic,now 9.20170808ubuntu1 all [installed]
apt-transport-https/bionic-updates,now 1.6.12 all [installed]
ca-certificates/bionic,bionic-updates,now 20180409 all [installed]

Output of `apt-cache policy <package>` works best.
lsb-release:
Installed: 9.20170808ubuntu1                                                                                                                                 Candidate: 9.20170808ubuntu1                                                                                                                                 Version table:                                                                                                                                              *** 9.20170808ubuntu1 500                                                                                                                                           500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages                                                                                              100 /var/lib/dpkg/status 

apt-transport-https:
Installed: 1.6.12                                                                                                                                            Candidate: 1.6.12                                                                                                                                            Version table:                                                                                                                                              *** 1.6.12 500                                                                                                                                                      500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages                                                                                  100 /var/lib/dpkg/status                                                                                                                                  1.6.6ubuntu0.1 500                                                                                                                                              500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages                                                                             1.6.1 500                                                                                                                                                       500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

ca-certificates:
Installed: 20180409                                                                                                                                          Candidate: 20180409                                                                                                                                          Version table:                                                                                                                                              *** 20180409 500                                                                                                                                                    500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages                                                                                              500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages                                                                                      100 /var/lib/dpkg/status 

**Additional context**
If I remove the /etc/apt/sources.list.d/sury_php.list file then that `apt-get update` works just fine.

**Comment by oerdnj** [comment]
Why do you think using Debian repositories with Ubuntu will work?

https://deb.sury.org/#packages

**Comment by meli07-sudo** [comment]
debian ppa also does't work

**Comment by meli07-sudo** [comment]
```
Atteint :1 https://deb.parrot.sh/parrot parrot InRelease                                                      
Atteint :2 https://debrepo.freedownloadmanager.org bionic InRelease                                
Atteint :3 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Atteint :4 https://deb.parrot.sh/parrot parrot-backports InRelease
Lecture des listes de paquets... Fait
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
apt-transport-https est déjà la version la plus récente (2.2.4).
ca-certificates est déjà la version la plus récente (20210119).
curl est déjà la version la plus récente (7.74.0-1.3+deb11u1).
lsb-release est déjà la version la plus récente (11.1.0).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 2 non mis à jour.
Atteint :1 https://deb.parrot.sh/parrot parrot InRelease                                                                              
Atteint :2 https://debrepo.freedownloadmanager.org bionic InRelease                                     
Ign :3 https://packages.sury.org/php lts InRelease                    
Atteint :4 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Atteint :5 https://deb.parrot.sh/parrot parrot-backports InRelease    
Err :6 https://packages.sury.org/php lts Release                      
  404  Not Found [IP : 143.244.38.130 443]
Lecture des listes de paquets... Fait
E: Le dépôt https://packages.sury.org/php lts Release n'a pas de fichier Release.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.

```

**Comment by meli07-sudo** [comment]
After exec code in  this => [https://packages.sury.org/php/README.txt](https://packages.sury.org/php/README.txt)  in a bash script
