### ISSUE TITLE
[Update] xdebug 2.8.0

### ISSUE THREAD

**Issue by KacerCZ** [oerdnj/deb.sury.org#1273]
Xdebug 2.8.0 (https://pecl.php.net/package/xdebug) was released.
It adds support for PHP 7.4.

**Comment by oerdnj** [comment]
Uploaded

**Comment by KacerCZ** [comment]
Thank you.

**Comment by rfay** [comment]
I'm pretty sure this isn't working as intended yet, it seems xdebug.so is not found?

```
rfay@d8composer-web:/var/www/html/web$ php --version
PHP Warning:  Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20190902/xdebug.so (/usr/lib/php/20190902/xdebug.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/xdebug.so.so (/usr/lib/php/20190902/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20190902/xdebug.so (/usr/lib/php/20190902/xdebug.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/xdebug.so.so (/usr/lib/php/20190902/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.0RC4 (cli) (built: Oct 26 2019 14:20:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0RC4, Copyright (c), by Zend Technologies
```

**Comment by oerdnj** [comment]
@rfay How should know when you skipped all the important details?  Like package versions installed...

**Comment by KacerCZ** [comment]
@rfay Today I've updated xdebug package and it's working.

**Comment by rfay** [comment]
Followup on php7.4/xdebug in https://github.com/oerdnj/deb.sury.org/issues/1275

@KacerCZ if you made xdebug+php7.4 work please explain your technique over there, thanks.

**Comment by KacerCZ** [comment]
@rfay I just updated xdebug package.

    $ php7.4 --version
    PHP 7.4.0RC4 (cli) (built: Oct 26 2019 10:48:28) ( NTS )
    Copyright (c) The PHP Group
    Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
        with Zend OPcache v7.4.0RC4, Copyright (c), by Zend Technologies
        with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans

Maybe it works because I have also installed all PHP versions from 7.0 to 7.4RC.

**Comment by rfay** [comment]
Also works because he just updated based on #1275 :) Thanks @oerdnj
