### ISSUE TITLE
OAuth extension v2.0.2 not compatible with PHP 7.3

### ISSUE THREAD

**Issue by BHSPitMonkey** [oerdnj/deb.sury.org#1274]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**

The `oauth` extension provided by `php-oauth` (currently at version 2.0.2 for all <19.10 releases) is unusable with PHP 7.3 due to [an upstream bug](http://git.php.net/?p=pecl/web_services/oauth.git;a=commit;h=0828b70df7606b599785b3de1c15248d3e463b95). 

The bug has been patched in the 2.0.3 and 2.0.4 releases of the extension, but these are not yet being offered here for Ubuntus 16.04 through 19.04 causing dependent projects to break when PHP 7.3 is used.

**To Reproduce**

In PHP 7.3, run the following:

```php
echo urldecode(oauth_get_sbs('GET', 'https://www.example.com/uri')) . PHP_EOL;
```

The following malformed Signature Base String appears:

```
GET&://&
```

**Expected behavior**

The output should be:

```
GET&https://www.example.com/uri&
```

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: PPA

**Package(s) (please complete the following information):**

```
php-oauth:
  Installed: 2.0.2+1.2.3-2+ubuntu16.04.1+deb.sury.org+10
```

**Additional context**

The `oauth_get_sbs` function referenced above is the basis for how the extension produces its HMAC signatures. Because the wrong Signature Base String is generated, all calls to `getRequestToken()` on OAuth instances will send an incorrect signature to the server, which compliant servers will reject.

**Comment by oerdnj** [comment]
Uploaded.
