### ISSUE TITLE
php7.4/xdebug anomalies

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1275]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**

I'm working on installing newly supported php-xdebug 2.8 on Debian 10 Buster and not successful yet. 

With a standard clean Debian 10 Buster, never had php of any kind on it, install deb.sury.org repos as in https://packages.sury.org/php/README.txt

* No xdebug.ini is created in /etc/php/7.4/
* There seems to be no xdebug.so provided that works
* A number of additional (inappropriate?) packages are installed when installing php7.4-cli or php7.4

**To Reproduce**

```
$ sudo apt-get install php7.4-cli php-xdebug
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
libpcre2-8-0 php-common php7.3-cli php7.3-common php7.3-json php7.3-opcache
php7.3-phpdbg php7.3-readline php7.4-common php7.4-json php7.4-opcache
php7.4-readline
Suggested packages:
php-pear
The following NEW packages will be installed:
php-common php-xdebug php7.3-cli php7.3-common php7.3-json php7.3-opcache
php7.3-phpdbg php7.3-readline php7.4-cli php7.4-common php7.4-json
php7.4-opcache php7.4-readline
The following packages will be upgraded:
libpcre2-8-0
1 upgraded, 13 newly installed, 0 to remove and 15 not upgraded.
Need to get 7,669 kB of archives.
After this operation, 39.0 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

* Note that for a php7.4 install only, it's installing "php-common php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-phpdbg php7.3-readline". That's not expected is it?

**Expected behavior**

* I don't expect php7.3 stuff to be installed when installing php7.4
* I expect an xdebug.ini in /etc/php/7.4/mods-available. Maybe there's something I don't understand about this being done differently than in previous releases?
* I expect a usable xdebug.so somewhere in /usr/lib/php. AFAICT there's no xdebug.so that works with php7.4. Although several xdebug.so files have been installed, none of them seem to work with php7.4:

```
$ find  /usr/lib/php -name "*xdebug*.so" -ls
  2514138   1828 -rw-r--r--   1 root     root      1871536 Nov 16 19:15 /usr/lib/php/20160303/xdebug.so
  2514136   1804 -rw-r--r--   1 root     root      1843936 Nov 16 19:15 /usr/lib/php/20151012/xdebug.so
  2514141   1856 -rw-r--r--   1 root     root      1898784 Nov 16 19:15 /usr/lib/php/20180731/xdebug.so
  2514134   1500 -rw-r--r--   1 root     root      1535496 Nov 16 19:15 /usr/lib/php/20131226/xdebug.so
  2514140   1836 -rw-r--r--   1 root     root      1879136 Nov 16 19:15 /usr/lib/php/20170718/xdebug.so
```

**Distribution (please complete the following information):**
 - OS: Debian 10 Buster
 - Architecture:  amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

```
$ apt-cache policy php7.4-cli php-xdebug
php7.4-cli:
  Installed: 7.4.0~rc4-1+0~20191026.5+debian10~1.gbp301a07
  Candidate: 7.4.0~rc4-1+0~20191026.5+debian10~1.gbp301a07
  Version table:
 *** 7.4.0~rc4-1+0~20191026.5+debian10~1.gbp301a07 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
php-xdebug:
  Installed: 2.8.0+2.5.5-1+0~20191117.13+debian10~1.gbp6fa14c
  Candidate: 2.8.0+2.5.5-1+0~20191117.13+debian10~1.gbp6fa14c
  Version table:
 *** 2.8.0+2.5.5-1+0~20191117.13+debian10~1.gbp6fa14c 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     2.7.0~rc2+2.6.1+2.5.5-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
```

**Additional context**

Please be gentle on your fans and supporters.

**Comment by oerdnj** [comment]
That, I can work with.  You are absolutely right, the Debian `php-defaults` package hasn't been updated to build modules for PHP 7.4 even though I thought I already did that.  I am going to fix that.  Just a moment.

**Comment by oerdnj** [comment]
Thanks for bringing this to my attention.

**Comment by oerdnj** [comment]
This should have been now built.

**Comment by rfay** [comment]
It's great, thanks so much.
