### ISSUE TITLE
Funny stretch to buster upgrade problem

### ISSUE THREAD

**Issue by lukavia** [oerdnj/deb.sury.org#1276]
**Describe the bug**
After upgrade of the debian distribution from stretch to buster the php packages doesn't get upgraded.
If I try to force to upgrade php7.1-curl I get:
`The following packages have unmet dependencies:
 php7.1-curl : Depends: php7.1-common (= 7.1.33-1+0~20191026.27+debian10~1.gbpd10139) but 7.1.33-1+0~20191027.27+debian9~1.gbpd10139 is to be installed
E: Unable to correct problems, you have held broken packages.
`
It seams that stretch packages ware build on the 27-th and buster on the 26-th, so thinks stretch packages are newer than buster. 

**Expected behavior**
php packages gets updated along with the hole distribution

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php7.1-curl:
  Installed: (none)
  Candidate: 7.1.33-1+0~20191026.27+debian10~1.gbpd10139
  Version table:
     7.1.33-1+0~20191027.27+debian9~1.gbpd10139 -1
     7.1.33-1+0~20191026.27+debian10~1.gbpd10139 500

**Comment by oerdnj** [comment]
Hopefully, that has now cleared with new versions...
