### ISSUE TITLE
PHP 7.3.12 and 7.2.25 packages

### ISSUE THREAD

**Issue by vkhramtsov** [oerdnj/deb.sury.org#1277]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**
New php versions released but no packages in repository. Would you be so kind to build packages for new versions?
Thank you

**To Reproduce**
1. sudo apt-get update
2. sudo apt-get upgrade or sudo apt-get install php7.3-fpm

**Expected behavior**
New version of php 7.3 installed

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by pesselbach** [comment]
PHP 7.4.0 (final) packages for Debian would be also nice ;)

**Comment by vkhramtsov** [comment]
@oerdnj  Would you be so kind to take a look?

**Comment by oerdnj** [comment]
Sure, but there’s no security issue in these releases, so they should be updated by the end of the week. Earlier if I can find time today...

**Comment by vkhramtsov** [comment]
Thank you for feedback. We are planning to update php on Monday, so I'm looking forward for updated php packages.

**Comment by vkhramtsov** [comment]
@oerdnj Thank you for php 7.3.12 packages

**Comment by vkhramtsov** [comment]
Closing, because packages for php 7.4 are in repository.
