### ISSUE TITLE
php-xdebug 2.8.0+2.5.5-1+0~20191118.14+debian9~1.gbp6fa14c shows no version info

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [oerdnj/deb.sury.org#1279]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**
Calling `phpversion('xdebug')` should result in the version of XDebug installed on the system. It returns false because no version information is associated.

**To Reproduce**
1. Install PHP7.4 via 
```bash
apt-get install php7.4-cli php7.4-curl php7.4-intl php-redis php7.4-mysql php7.4-sqlite3 php7.4-xml php7.4-mbstring php7.4-gd php7.4-bcmath php7.4-zip php-imagick libmagickcore-6.q16-3-extra inkscape poppler-utils php7.4-xdebug
```
2. Ensure that XDebug is loaded via `php -m | grep xdebug`
3. Execute `var_dump(phpversion('xdebug'));`

**Expected behavior**
It should return the version of the extension (2.8.0?).

**Actual behavior**
It returns false.

**Distribution (please complete the following information):**
 - OS: Debian Stretch as a Docker Container
 - Architecture: amd64
 - Repository: "deb https://packages.sury.org/php/ stretch main"

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
```
php-xdebug:
  Installed: 2.8.0+2.5.5-1+0~20191118.14+debian9~1.gbp6fa14c
  Candidate: 2.8.0+2.5.5-1+0~20191118.14+debian9~1.gbp6fa14c
  Version table:
 *** 2.8.0+2.5.5-1+0~20191118.14+debian9~1.gbp6fa14c 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.5.0-1 500
        500 http://mirror/debian stretch/main amd64 Packages
```

**Additional context**
I dont know if this is a problem of the debian package or the extension itself.

**Comment by oerdnj** [comment]
It would be a problem in packaging only if the package would not contain necessary files. And I can see all required files for PHP 7.4 are there:
```
.
./etc
./etc/php
./etc/php/7.2
./etc/php/7.2/mods-available
./etc/php/7.2/mods-available/xdebug.ini
./etc/php/7.4
./etc/php/7.4/mods-available
./etc/php/7.4/mods-available/xdebug.ini
./etc/php/7.1
./etc/php/7.1/mods-available
./etc/php/7.1/mods-available/xdebug.ini
./etc/php/5.6
./etc/php/5.6/mods-available
./etc/php/5.6/mods-available/xdebug.ini
./etc/php/7.0
./etc/php/7.0/mods-available
./etc/php/7.0/mods-available/xdebug.ini
./etc/php/7.3
./etc/php/7.3/mods-available
./etc/php/7.3/mods-available/xdebug.ini
./usr
./usr/share
./usr/share/doc
./usr/share/doc/php-xdebug
./usr/share/doc/php-xdebug/copyright
./usr/share/doc/php-xdebug/changelog.Debian.gz
./usr/lib
./usr/lib/php
./usr/lib/php/20190902
./usr/lib/php/20190902/xdebug.so
./usr/lib/php/20131226
./usr/lib/php/20131226/xdebug.so
./usr/lib/php/20170718
./usr/lib/php/20170718/xdebug.so
./usr/lib/php/20180731
./usr/lib/php/20180731/xdebug.so
./usr/lib/php/20151012
./usr/lib/php/20151012/xdebug.so
./usr/lib/php/20160303
./usr/lib/php/20160303/xdebug.so
```
