### ISSUE TITLE
Ubuntu 19.10 + php-phalcon Unable to locate package

### ISSUE THREAD

**Issue by takealook-global** [oerdnj/deb.sury.org#1281]
Linux Ubuntu 19.10
PHP 7.4
`sudo apt instal php-phalcon
`
Error : Unable to locate package

**Comment by takealook-global** [comment]
Something? @oerdnj

**Comment by oerdnj** [comment]
I think it should be available now.

**Comment by takealook-global** [comment]
Hi, thanks, but still not find, i have tried

sudo apt install php-phalcon
sudo apt install php7.4-phalcon

thank you.

**Comment by oerdnj** [comment]
There’s no phalcon for PHP 7.4.

**Comment by oerdnj** [comment]
I see, the builds have failed. I’ll look into this.

**Comment by oerdnj** [comment]
The builds are fine now. (No PHP 7.4 version yet - there's no upstream support for it.)

**Comment by takealook-global** [comment]
Hi, thanks, so don't have phalcon support for php 7.4?

**Comment by oerdnj** [comment]
I am positive that you can type phalcon.io to your browser, go to forums and use search yourself, and I don't have to do it for you, right?

**Comment by takealook-global** [comment]
I already did this on the day ( 21 day ago ) when I ask your help.
You don't need to be ironic, and for sure don't need to do it for me.
Maybe you need to type better, google may help you.

But I already compiled, so thanks.

**Comment by oerdnj** [comment]
https://berthub.eu/articles/posts/anonymous-help/
