### ISSUE TITLE
Long time and 100% cpu use with cover test

### ISSUE THREAD

**Issue by mazarini** [oerdnj/deb.sury.org#1283]
Since some days (one week ?), when using test with cover report, it's very long.

 - OS: Debian buster (up to date)
 - Architecture: amd64
 - Repository: packages.sury.org

symfony 5.0 / phpunit 8.3
1) php 7.2 : normal test : 300ms / cover test 20 minutes
2) php 7.3 : long time with cover (never wait)
3) php 7.4 : normal test : 280ms / cover test 11s (was ko with 7.4rc)

php-xdebug   2.8.0+2.5.5-1+0~20191118.14+debian10~1.gbp6fa14c
PHP 7.2.25-1+0~20191128.32+debian10~1.gbp108445
PHP 7.4.0 built: Nov 28 2019 07:26:14

**Comment by oerdnj** [comment]
Do you have any reason to believe this is a problem with packaging?

**Comment by mazarini** [comment]
Not really. I wanted you know it in case you do something in relation.
That's because it's work know with 7.4, I post this issue.
Note that on TravisCI it's work with 7.2.

**Comment by Jamesking56** [comment]
See my issue #1286 

There is a bug with XDebug version 2.8.0: https://bugs.xdebug.org/view.php?id=1717

You need to either downgrade to 2.7.2 or wait until this PPA adds 2.8.1

**Comment by Jamesking56** [comment]
PPA has been updated with xdebug 2.8.1
