### ISSUE TITLE
PPA for Apache2 for Ubuntu 19.10

### ISSUE THREAD

**Issue by jastubbs** [oerdnj/deb.sury.org#1284]
Linux newbie here. Setting up new machine, installed 19.10. But it appears that the Apache2 ppa isn't yet available for this Ubuntu release.

**Comment by joglomedia** [comment]
@jastubbs this PPA is for PHP

**Comment by oerdnj** [comment]
I also have PPA for Apache2 and nginx (and couple of minor ones). Why do you need the Apache2 PPA on 19.10 anyway? I mean right now it should be pretty up to date in stock Ubuntu.

**Comment by jastubbs** [comment]
@oerdnj , I'm combining two ancient servers into one box. The web guy wants to work with PHP 7.4 ( I just admin the postfix install ). The caveats on the PHP PPA overview page advises using your Apache2 PPA. I noticed that the stock Ubuntu is up to date, but... being a newbie, just wanted to clarify. If I can use the PHP7.4 PPA with the Ubuntu stock Apache2, I'm motoring forward. Close the issue please.
Thanks!!!

**Comment by oerdnj** [comment]
I'll update the Apache2 eventually (with next Apache2 release), but you don't have to use it at the moment if there's no new feature in more recent versions of Apache2 not available from the official repositories.

The more ancient your installation is the more is likely you need both.
