### ISSUE TITLE
php-http for 7.4?

### ISSUE THREAD

**Issue by stephenreay** [oerdnj/deb.sury.org#1285]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Extensions for unreleased PHP version**
- [x] I'm *not* requesting PECL extensions for pre-release version of PHP (PHP 7.4.0 is OK, PHP 7.4.0RC is not)

**Describe the bug**
The `php-http` package, which provides the PECL `http` extension, does not provide `php7.4-http`

**To Reproduce**
1. Setup DebSury repo for Debian Stretch
2. Update apt
3. Install `php7.4` and `php-http`
4. Check `php7.4 -m` for existence of `http` module.

**Expected behavior**
PHP 7.4 should have the `http` module loaded.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

```
php-http:
  Installed: 3.2.1+2.6.0-1+0~20190808.6+debian9~1.gbpbd8342
  Candidate: 3.2.1+2.6.0-1+0~20190808.6+debian9~1.gbpbd8342
  Version table:
 *** 3.2.1+2.6.0-1+0~20190808.6+debian9~1.gbpbd8342 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.0+2.6.0-4 500
        500 https://deb.debian.org/debian stretch/main amd64 Packages
```

**Comment by stephenreay** [comment]
It seems like the updated packages are built now?

**Comment by oerdnj** [comment]
I hope so ;)

**Comment by stephenreay** [comment]
Thanks again Ondřej, your efforts are very much appreciated. Closing this now!
