### ISSUE TITLE
php-curl Depends on libcurl3 and Debian Stable Uses libcurl4

### ISSUE THREAD

**Issue by j-ki** [oerdnj/deb.sury.org#1289]
**Describe the bug**
PHP 7.x curl packages (e.g. php7.3-curl) depends on libcurl3. However, it seems the latest Debian stable is using libcurl4.

So after performing an update, Debian package manager removes php7.3-curl because the required libraries are not present.

libcurl3 is not available and manually trying to install libcurl3, conflicts with libcurl4. Also, libcurl3 depends on openssl1.0.2 and Debian uses openssl1.1.0. So it seems I'll be going down a rabbit hole, trying to install libcurl3.

Would it be possible to reconfigure or recompile PHP packages to use either libcurl3 or libcurl4?

**Comment by oerdnj** [comment]
No, it doesn’t.

**Comment by j-ki** [comment]
I have an installation of Debian 10 and libcurl3 isn't available in the default repositories.

When I add your repositories and try to add php7.3-curl, apt throws a dependency error, saying it needs libcurl3.

**Comment by j-ki** [comment]
> 
> 
> No, it doesn’t.

I have an installation of Debian 10 and libcurl3 isn't available in the default repositories.

When I add your repositories and try to add php7.3-curl, apt throws a dependency error, saying it needs libcurl3.
