### ISSUE TITLE
Updating version depended on by php-* packages

### ISSUE THREAD

**Issue by alexwhitman** [oerdnj/deb.sury.org#1290]
When do the versions depended on by the `php-` packages get bumped to 7.4?  Currently they depend on 7.3.
```
$ apt show php-cli
Package: php-cli
Version: 2:7.3+70+ubuntu18.04.1+deb.sury.org+6
Priority: optional
Section: php
Source: php-defaults (70+ubuntu18.04.1+deb.sury.org+6)
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 12.3 kB
Depends: php7.3-cli
Download-Size: 6,172 B
APT-Sources: http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
```
No demands or expectations, just curiosity.  Thanks.

**Comment by oerdnj** [comment]
Usually with .1 or .2 release. There are exactly two groups of people: the first group wants the change as soon as possible, the second group will start filling bugs when the default change because it breaks their scripts. ;)

**Comment by alexwhitman** [comment]
From a development perspective I fall into the first group but I can understand why others wouldn't want it to happen that quick.  Thanks for the info.

**Comment by oerdnj** [comment]
The default packages are now pointing to PHP 7.4

**Comment by cweiske** [comment]
Now that everything got switched to 7.4, I have core dumps on one cli tool and cannot go back to 7.3 where everything worked because matomo depends on the php-* packages, which depend on 7.4 :/
