### ISSUE TITLE
Repostory don't work

### ISSUE THREAD

**Issue by msamgar** [oerdnj/deb.sury.org#1291]
Hi, I am trying to run the following code with Ubuntu 18.4 and I get the following error. Please help me.

Code : sudo sudo add-apt-repository ppa:ondrej/php
Error: retrieving gpg key timed out.

**Comment by oerdnj** [comment]
Fix your network.

**Comment by msamgar** [comment]
Hello again,
I do not have any problems going out on the internet. I can view all websites. I don't use a firewall. but I still can't access the repo.
