### ISSUE TITLE
repository is not signed

### ISSUE THREAD

**Issue by msamgar** [oerdnj/deb.sury.org#1293]
Hello again,
# 1291 and # 1292 is still the problem I've described. if you test on a virtual machine, you may encounter problems. On the basis of the problem, I think it could be due to the incompatibility of the passwords in the InRelease and Release.gpg files at http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/.

InRelease file;
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iJwEAQEKAAYFAl3ngJ8ACgkQT06gquUmemwqoQQAgH0FgRkVyMCODb7i7CXpTdwC
EDfkefNfGkO9As83aYcIdx8ahm9vfy2175IKLALi+0iX0kZ2vd5YWewHiqLtDWon
QuTkQCu7Xde5jYaJsF8ydsO1dREWEFNemOsVIH7jf5XPD5dvM8sOvydjT4Yscw1j
ID/fyDIqXPHTx3HWLF4=
=noWR
-----END PGP SIGNATURE-----

Release.gpg file;

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iJwEAQEKAAYFAl3ngJ8ACgkQT06gquUmemwqoQQAgH0FgRkVyMCODb7i7CXpTdwC
EDfkefNfGkO9As83aYcIdx8ahm9vfy2175IKLALi+0iX0kZ2vd5YWewHiqLtDWon
QuTkQCu7Xde5jYaJsF8ydsO1dREWEFNemOsVIH7jf5XPD5dvM8sOvydjT4Yscw1j
ID/fyDIqXPHTx3HWLF4=
=noWR
-----END PGP SIGNATURE-----

W: GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease: The following signatures could not be verified because the public key does not exist: NO_PUBKEY 4F4EA0AAE5267A6C
E: 'http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease' repository is not signed.
N: You cannot safely update from such a repository, so the repository is disabled.

**Comment by oerdnj** [comment]
JFTR This is **not** a place to learn basics of system administration. There are better places like AskUbuntu that are friendly to new Linux users and administrators.  This is a place to report issues with the repositories and packages.
