### ISSUE TITLE
Wrong depends for install php7.1-dev on libpcre3

### ISSUE THREAD

**Issue by keks55** [oerdnj/deb.sury.org#1296]
Hi,
I try install **php7.1-dev** (Debian jessie) but getting an error
<pre>
# apt-get install php7.1-dev
The following packages have unmet dependencies:
 php7.1-dev : Depends: libpcre3-dev (>= 2:8.35) but it is not going to be installed
              Depends: php7.1-cli (>= 7.1.33-2+0~20191128.28+debian9~1.gbpc60685) but it is not going to be installed
              Depends: libtool (>= 2.4.6-0.1~) but it is not going to be installed
              Recommends: pkg-php-tools but it is not going to be installed
</pre>
I have installed libpcre3
<pre>
# apt-cache policy libpcre3
libpcre3:
  Installed: 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f
  Candidate: 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f
  Version table:
 *** 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f 0
        500 https://packages.sury.org/php/ stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2:8.43-1+0~20190710.6+debian8~1.gbpbfc49f 0
        500 https://packages.sury.org/php/ jessie/main amd64 Packages
     2:8.35-3.3+deb8u4 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
</pre>
How can I fix this?

**Comment by oerdnj** [comment]
> How can I fix this?

By carefully reviewing the output you just sent me.
