### ISSUE TITLE
The PHP packages with php7.4 switch apache to mpm_prefork

### ISSUE THREAD

**Issue by AleksCee** [oerdnj/deb.sury.org#1297]
**Unsupported distributions**
 - [X] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Excessive usage of the repositories**
- [x] I'm am not abusing the repositories to download excessive numbers of packages per day, or checking repository more than once an hour (like every minute) (see https://packages.sury.org/error403.html).

**Describe the bug**

I'm using the default Ubuntu 16.04 apache2 package with your php7.2 version. With the update today of the PHP/PHP-Common the Version 7.4 was installed and the apache was switched to mpm_prefork - but I use php7.2 with php-fpm and mpm_event. I have to switch back manually and switch the alternatives to 7.2 also because the cron of nextCloud can't handle php7.4 - but this is incidental. The most work I had to do is switching back to mpm_event.
Please don't switch this in a configured system. The php7.3 packaged has always say "switching is disabled by maintainer" - is this a option for the 7.4 packaged to?

Thanks, Alex

**Comment by oerdnj** [comment]
Only the libapache2-mod-phpX.Y does the switching, so perhaps it was pulled in and you haven’t been paying attention?

**Comment by AleksCee** [comment]
ok, but ist the libapache2-mod-phpX.Y in the php-common includet? I have only updated the pakages and the libapache2 was installed for php7.4. php.7.2 has only the fpm installed.

**Comment by oerdnj** [comment]
It’s not, it’s just a first alternative.

**Comment by AleksCee** [comment]
Sorry for the stupid question, but how can you determine the alternative to install?
I found the documentation https://www.debian.org/doc/debian-policy/ch-relationships.html but no way to select the alternative by upgrating from for example 7.3 to 7.4.
Thanks Alex

**Comment by oerdnj** [comment]
`apt install php php7.4-fpm` would do the trick. Or just remove the `php` package and keep only `php-fpm`, the `php` is just a dummy dependency package with no content.
