### ISSUE TITLE
php-gearman isn't loaded after recent update

### ISSUE THREAD

**Issue by arkste** [oerdnj/deb.sury.org#1298]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Describe the bug**
after updating `php-gearman`, the extension isn't loaded anymore.

`PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:48:49) ( NTS )`

**To Reproduce**
1. `sudo add-apt-repository ppa:ondrej/php`
2. `sudo add-apt-repository ppa:ondrej/pkg-gearman`
3. `sudo apt install php7.3-cli php-gearman`
4. `php -m | grep -i gearman` doesn't show the loaded module

`/etc/php/7.3/mods-available/gearman.ini` & `/usr/lib/php/20180731/gearman.so` are both missing.

**Expected behavior**
`php -m | grep -i gearman` should show the loaded extension, the `gearman.ini` and the dynamic library `gearman.so` should both exist.

**Distribution:**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: ppa:ondrej/pkg-gearman & ppa:ondrej/php

**Package(s):**
```
php-gearman:
  Installed: 2.0.6+1.1.2-5+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.0.6+1.1.2-5+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2.0.6+1.1.2-5+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.3+1.1.2+-1build3 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages bionic/universe amd64 Packages
```

**Comment by vkhramtsov** [comment]
Also command  `apt-cache search php7.3-gearman` return empty result. Removing and installing `php-gearman` package does not change anything

**Comment by vkhramtsov** [comment]
It looks like in my setup everything is ok now. @arkste would you be so kind to check your setup?

**Comment by oerdnj** [comment]
The extension for 7.x has kind of messed package.xml file, and I patched it wrong to exclude 7.4, and I excluded 7.3 as well. Sorry, this is fixed now.

**Comment by vkhramtsov** [comment]
@oerdnj Thank you. Merry Christmas!

**Comment by arkste** [comment]
oh wow, i didnt expect it to be fixed that fast 👍 
i can confirm, its working as expected now. 

ty @oerdnj for your work!
