### ISSUE TITLE
Problem with Phusion passenger in Apache 2.4.17

### ISSUE THREAD

**Issue by antenno** [oerdnj/deb.sury.org#130]
Upgrading to Apache 2.4.17 I ran into the problem that my Redmine-Application is not running any more. A lot of reinstalling, upgrading and research brought me to this:
https://groups.google.com/forum/#!topic/phusion-passenger/jiOpv9Isua4
which leads to this bug report:
https://bz.apache.org/bugzilla/show_bug.cgi?id=58498

Is there a way to deplaoy a version that does not contain this bug? It is critical, as passenger apps might not be running at all with the currently deployed version 2.4.17.

Thank you
-antenno

**Comment by oerdnj** [comment]
`passenger_5.0.22-1+deb.sury.org~*+1` in `ppa:ondrej/apache2` should have the fix (the bug was in passenger).
