### ISSUE TITLE
hello and excuse my bad english Ubuntu 18.10 ( cosmic )

### ISSUE THREAD

**Issue by NextGenerationcloud** [oerdnj/deb.sury.org#1300]
in the console (Putty)

I say

sh -c 'echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu cosmic main" >> /etc/apt/sources.list' 
sh -c 'echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu cosmic main" >> /etc/apt/sources.list' 

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update

apt-cache search php7.3

Result: NO php7.3

I test it again Ubuntu bionic main (18.04)

sh -c 'echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main" >> /etc/apt/sources.list' 
sh -c 'echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu bionic main" >> /etc/apt/sources.list' 

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update

apt-cache search php7.3

Result: i can install php7.3

is ubuntu 18.10 finished?

Or am I doing something wrong ?

**Comment by oerdnj** [comment]
Using release 5+ month past its EOL is a kind of definition of wrong, so yes, you are doing something wrong.

https://fridge.ubuntu.com/2019/07/19/ubuntu-18-10-cosmic-cuttlefish-end-of-life-reached-on-july-18-2019/

**Comment by muava12** [comment]
So now there is no way to install php 7,4 in Ubuntu 18.10? 
I hope still there is a way to do it

**Comment by drkskwlkr** [comment]
> So now there is no way to install php 7,4 in Ubuntu 18.10? I hope still there is a way to do it

Ubuntu 18.10 has been EOL for nearly 3.5 years. You should not be using this product. If you want to run PHP 7.4 (another product that will go EOL in 23 days) on top of that, you can try [building from source](https://php.watch/articles/compile-php-ubuntu). See [PHP releases](https://www.php.net/releases).

IMO, your time will be spent much better upgrading to a supported Ubuntu release.

**Comment by muava12** [comment]
> > So now there is no way to install php 7,4 in Ubuntu 18.10? I hope still there is a way to do it
> 
> Ubuntu 18.10 has been EOL for nearly 3.5 years. You should not be using this product. If you want to run PHP 7.4 (another product that will go EOL in 23 days) on top of that, you can try [building from source](https://php.watch/articles/compile-php-ubuntu). See [PHP releases](https://www.php.net/releases).
> 
> IMO, your time will be spent much better upgrading to a supported Ubuntu release.

I did manulaly add repo to .list, using bionic's repo. and updating php to 8.1 successfully in cosmic

is there a possible problem in near future?
