### ISSUE TITLE
Focal aka 20.04

### ISSUE THREAD

**Issue by ser** [oerdnj/deb.sury.org#1303]
I would suggest start working on Ubuntu 20.04 Focal - as release date is slowly approaching and it's worth to have it tested before release.

**Comment by oerdnj** [comment]
No, it’s not worth the trouble until it’s frozen.

https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

**Comment by marcelloinfoweb** [comment]
What do you suggest to install php5.6?

**Comment by hswong3i** [comment]
I try to enable eoan repo for focal + php 7.4/7.3/7.2 and most likely functioning; BTW, some package are in conflict status, e.g. php-geoip, php-apcu-bc, etc.

As long as Ubuntu 20.04 will be released on 2020 April 23rd, shall we start prepare for that now?
