### ISSUE TITLE
Unable to load mailparse for PHP 5.6

### ISSUE THREAD

**Issue by jclaveau** [oerdnj/deb.sury.org#1304]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
The issue doesn't occurre with another php version.

**To Reproduce**
1. install php5.6-cli and php-mailparse
2. In bash do php5.6 -v
3. See error
```shell
php5.6 -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/mailparse.so' - /usr/lib/php/20131226/mailparse.so: undefined symbol: mbfl_convert_filter_flush in Unknown on line 0
PHP 5.6.40-15+ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Expected behavior**
No warning should happend

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04. 
```shell
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```shell 
apt-cache policy php5.6-cli
php5.6-cli:
  Installed: 5.6.40-15+ubuntu16.04.1+deb.sury.org+1
  Candidate: 5.6.40-15+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 5.6.40-15+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

apt-cache policy php-mailparse
php-mailparse:
  Installed: 3.0.3+2.1.7~dev20160128-2+ubuntu16.04.1+deb.sury.org+20191129
  Candidate: 3.0.3+2.1.7~dev20160128-2+ubuntu16.04.1+deb.sury.org+20191129
  Version table:
 *** 3.0.3+2.1.7~dev20160128-2+ubuntu16.04.1+deb.sury.org+20191129 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
I have this issue in a docker image based on https://github.com/phusion/baseimage-docker.

My Dockerfile is here https://github.com/jclaveau/docker-php-multiversion/blob/master/Dockerfile

It's not a hurry for me and I can disable mailparse. I open this bug mainly to notice you this case. Thanks a lot for your work!

**Comment by oerdnj** [comment]
mailparse needs to be enabled after mbstring, which should be the case as mailparse priority is 25 and mbstring should be default (20). Check /etc/php/5.6/*/conf.d whether the symlinks have correct priority (it should be 20-mbstring.ini and 25-mailparse.ini).

**Comment by jclaveau** [comment]
```
ls /etc/php/5.6/*/conf.d
/etc/php/5.6/apache2/conf.d:
10-opcache.ini  20-calendar.ini  20-ftp.ini      20-iconv.ini     20-lua.ini      20-oauth.ini   20-raphf.ini     20-sockets.ini  20-sysvmsg.ini    20-uploadprogress.ini  25-memcached.ini
10-pdo.ini      20-ctype.ini     20-geoip.ini    20-igbinary.ini  20-mcrypt.ini   20-phar.ini    20-readline.ini  20-solr.ini     20-sysvsem.ini    20-xdebug.ini
20-amqp.ini     20-exif.ini      20-gettext.ini  20-imagick.ini   20-mongodb.ini  20-posix.ini   20-redis.ini     20-ssh2.ini     20-sysvshm.ini    20-zmq.ini
20-apcu.ini     20-fileinfo.ini  20-gnupg.ini    20-json.ini      20-msgpack.ini  20-radius.ini  20-shmop.ini     20-stomp.ini    20-tokenizer.ini  25-mailparse.ini

/etc/php/5.6/cli/conf.d:
10-opcache.ini  20-calendar.ini  20-ftp.ini      20-iconv.ini     20-lua.ini      20-oauth.ini   20-raphf.ini     20-sockets.ini  20-sysvmsg.ini    20-uploadprogress.ini  25-memcached.ini
10-pdo.ini      20-ctype.ini     20-geoip.ini    20-igbinary.ini  20-mcrypt.ini   20-phar.ini    20-readline.ini  20-solr.ini     20-sysvsem.ini    20-xdebug.ini
20-amqp.ini     20-exif.ini      20-gettext.ini  20-imagick.ini   20-mongodb.ini  20-posix.ini   20-redis.ini     20-ssh2.ini     20-sysvshm.ini    20-zmq.ini
20-apcu.ini     20-fileinfo.ini  20-gnupg.ini    20-json.ini      20-msgpack.ini  20-radius.ini  20-shmop.ini     20-stomp.ini    20-tokenizer.ini  25-mailparse.ini
```

Mbstring is missing. I installed it and it works now (My new issue is that mbstring should have been installed before, but this is not related to your packages). Wouldn't it be interesting to make mbstring a dependency of mailparse? 

Thanks again for your work and your time!

**Comment by oerdnj** [comment]
It does depend on `php-mbstring`, the problem here is that you install all PHP versions and the dependency is satisfied by the first `phpX.Y-mbstring` the dependency solver finds.  Unless the `php-mailparse` is split into individual packages, there's not much you can do as there's no way to express: _if phpX.Y-fpm is install, also depend on phpX.Y-mbstring_
