### ISSUE TITLE
PHP suddenly stops logging PHP related errors until manual restart

### ISSUE THREAD

**Issue by TimonZ98** [oerdnj/deb.sury.org#1305]
**Unsupported distributions**
 - [X] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [X] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**

I'm using PHP 7.4.1 with Apache2 (libapache2-mod-php7.4) on my Debian 10.2 system and I'm facing an issue since about December 23. Because I upgraded from PHP 7.4.0 to 7.4.1 on December 19 and I never experienced this issue before, I guess this issue/bug is related to PHP 7.4.1 or the corresponding Apache2 PHP module.

The logging works fine but after a few days it suddenly stops to log PHP errors, warnings etc. in my "error.log" file. Apache2 logging still works, but just the PHP errors aren't logged anymore. I'm also getting no error or exception when calling the "error_log" function manually and I can't find anything in other logs that could explain this. I already tried rebooted the whole Debian server a few times.

When I restart the Apache2 server (and thus also the PHP module), the logging starts working but after a few days it'll stop logging PHP errors again.

I've changed nothing in the last months. I just upgraded from PHP 7.4.0 to 7.4.1 on December 19 and then this issue started to happen. So it looks like it could be the new PHP version but I need the logging to work without suddenly stopping...

**Distribution:**
 - OS: Debian 10.2
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
`libapache2-mod-php7.4 (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php-common (2:71+0~20191219.19+debian10~1.gbpefc769 all)`
`php-geoip (1.1.1-4+0~20191119.10+debian10~1.gbp6de4a0 amd64)`
`php-pear (1:1.10.9+submodules+notgz-1+0~20191119.13+debian10~1.gbp296d25 all)`
`php7.4-bz2 (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-cli (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-common (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-curl (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-gd (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-intl (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-json (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-mbstring (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-mysql (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-opcache (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-readline (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-soap (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-xml (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4-xsl (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e all)`
`php7.4-zip (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e amd64)`
`php7.4 (7.4.1-1+0~20191218.8+debian10~1.gbp21c50e all)`

**Comment by oerdnj** [comment]
Hi, this doesn't seem like an error in packaging.  There was no change in the packaging between 7.4.0-1 and 7.4.1-1, so you need to report the issue to [PHP issue tracker](https://bugs.php.net). Feel free to report the upstream issue number here, when you fill the bug with them.
