### ISSUE TITLE
[NFR] Add Phalcon 4.0 extension to PHP 7.4

### ISSUE THREAD

**Issue by joglomedia** [oerdnj/deb.sury.org#1307]
**Is your feature request related to a problem? Please describe.**
Phalcon extension is included in PHP version 7.3 but not yet in PHP 7.4. Phalcon 4 stable is already released 20 days ago in it is fully compatible with PHP 7.4

**Describe the solution you'd like**
Build Phalcon 4 & PSR extension

**Distribution (please complete the following information):**
 - OS: Debian & Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA and packages.sury.org

**Package(s) (please complete the following information):**

```
$ apt-cache policy php7.4-phalcon
N: Unable to locate package php7.4-phalcon
N: Couldn't find any package by glob 'php7.4-phalcon'
N: Couldn't find any package by regex 'php7.4-phalcon'

$ apt-cache policy php7.4-psr
N: Unable to locate package php7.4-psr
N: Couldn't find any package by glob 'php7.4-psr'
N: Couldn't find any package by regex 'php7.4-psr'
```

Thanks for the continuously maintaining this repo

**Comment by oerdnj** [comment]
How much is phalcon 4 compatible with phalcon 3?

**Comment by ustmaestro** [comment]
There are many compatibility breaks between version 3 and 4.
They say "THIS RELEASE IS NOT BACKWARDS COMPATIBLE" and all is described here
https://blog.phalcon.io/post/merry-christmas-and-phalcon-4.0.0-alpha1-released

**Comment by oerdnj** [comment]
So basically, this is more request to create a new package called `php-phalcon4` than replacing the old one, right?

**Comment by joglomedia** [comment]
@oerdnj  basically yes, because Phalcon4 API has changed too much and not backward compatible to Phalcon3, and as stated in their release page, Phalcon4 is the latest maintained version and it is recommended for php 7.2, 7.3, and 7.4

**Comment by oerdnj** [comment]
Ok, so I did following:
* Added php-phalcon4 source package that builds php-phalcon4 binary package
* Renamed php-phalcon source and binary package to php-phalcon3 source and binary package
* Added dummy php-phalcon package that depends on php-phalcon3 (for backwards compatibility)
* Both php-phalcon3 and php-phalcon4 binary package Provides/Breaks/Replaces php-phalcon, so the transition from one package to the other works seamlessly

I haven’t had time to test it yet, so please test it and report back successes or failures. I’ll fix it quickly now.

**Comment by ruudboon** [comment]
thnx @oerdnj

**Comment by joglomedia** [comment]
thanks @oerdnj I'll test it and report back when something happen

**Comment by shivammathur** [comment]
@oerdnj Thanks for providing this. Whenever you have time, please add PHP 7.4 package for `ext-psr`, then `phalcon4` installation would be seamless on PHP 7.4.

**Comment by oerdnj** [comment]
Should be in the build queue now.  psr used non standard specification of the maximum PHP version. I have removed the constraint now.

**Comment by oerdnj** [comment]
I am also interested in hearing about php-phalcon -> php-phalcon3 upgrades, if there's anybody who had the old version installed.
