### ISSUE TITLE
PHP redis package depends on igbinary

### ISSUE THREAD

**Issue by bittylicious** [oerdnj/deb.sury.org#1309]
At least with PHP 7.4, there should be a dependency on php-igbinary when php-redis is installed, otherwise you get:

```
user@computer:/etc/php# php
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by oerdnj** [comment]
There’s a reason why I have issue templates...  If you followed the template instructions you would find that:
```
 apt-cache show php-redis
Package: php-redis
Version: 5.1.1+4.3.0-1+0~20191219.18+debian10~1.gbp1a44ee
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 3621
Pre-Depends: php-common (>= 2:69~)
Depends: php-igbinary, phpapi-20190902 | phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226, libc6 (>= 2.14)
```

**Comment by bittylicious** [comment]
I'm not sure how to explain it, but when I installed php-redis, it did **not** install php-igbinary. I had to apt-get install php-igbinary for this to work. I wouldn't have submitted the issue if not.

I can't explain it, but it is (as apt-cache suggests) installing the dependency just fine at the moment, so indeed this is not an issue as I can't reproduce it.
