### ISSUE TITLE
Add libapache2-svn on  Apache2.4 PPA

### ISSUE THREAD

**Issue by ynuyasha** [oerdnj/deb.sury.org#131]
it is possible to add libapache2-svn on ubuntu 12.04 lts?

If you want help, i can build this for you if you give me instructions

**Comment by ynuyasha** [comment]
I do it myself and create a PPA
https://launchpad.net/~antonio-falzarano/+archive/ubuntu/subversion

**Comment by oerdnj** [comment]
I am deprecating Ubuntu 12.04 in anything else than PHP 5.4 repository, so sorry and glad you were able to create package for yourself.
