### ISSUE TITLE
php-recode no longer available since 7.4

### ISSUE THREAD

**Issue by Adambean** [oerdnj/deb.sury.org#1310]
It appears that Recode is no longer available since PHP 7.4 has arrived.

I get daily emails from 21 Debian VPSes (11x Stretch and 10x Buster) of the following:

```
An update to php-recode from 7.3+70+0~20191118.18+debian9~1.gbp66b4ed to 7.4+71+0~20191219.19+debian9~1.gbpefc769 is available.
```

However when I proceed to `apt upgrade` for this it never arrives. I've tried installing this explicitly too.

`apt install php-recode` yields:
```
The following packages have unmet dependencies:
 php-recode : Depends: php7.4-recode but it is not installable
E: Unable to correct problems, you have held broken packages.
```

`apt install php7.4-recode` yields:
```
Package php7.4-recode is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Package 'php7.4-recode' has no installation candidate
```

Output of `apt-cache policy php-recode` on a Buster VPS:
```
php-recode:
  Installed: 2:7.3+70+0~20191118.18+debian10~1.gbp66b4ed
  Candidate: 2:7.4+71+0~20191219.19+debian10~1.gbpefc769
  Version table:
     2:7.4+71+0~20191219.19+debian10~1.gbpefc769 500
        500 https://packages.sury.org/php buster/main amd64 Packages
 *** 2:7.3+70+0~20191118.18+debian10~1.gbp66b4ed 100
        100 /var/lib/dpkg/status
     2:7.3+69 500
        500 http://ftp.uk.debian.org/debian buster/main amd64 Packages
```
_(Stretch VPSes show the same but with "buster/main" swapped for "stretch/main".)_

**Comment by oerdnj** [comment]
Yes, read the documentation and PHP 7.4 upgrade notes.

**Comment by Adambean** [comment]
https://www.php.net/manual/en/intro.recode.php

> Note: This extension is unbundled and moved to » PECL as of PHP 7.4.0.

Fair enough. To be honest I don't recall **any** of my PHP applications even using it, so I'll just remove the package.

Thanks for your quick reply. :)
