### ISSUE TITLE
php-igbinary 3.0.1 doesn't support PHP 7.4

### ISSUE THREAD

**Issue by A5hleyRich** [oerdnj/deb.sury.org#1311]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
Installing `php-redis` installs version `3.0.1` of igbinary, which does not support PHP 7.4. igbinary `3.1.0` has been released which supports PHP 7.4:

https://github.com/igbinary/igbinary/releases

**To Reproduce**
```
$ sudo apt-get install php-redis
...
Setting up php-igbinary (3.0.1+2.0.8-2+ubuntu18.04.1+deb.sury.org+20191129) ...
Setting up php-redis (5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1) ...
```

**Expected behavior**
Version `3.1.0` of igbinary installed.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
$ sudo apt-cache policy php-igbinary
php-igbinary:
  Installed: 3.0.1+2.0.8-2+ubuntu18.04.1+deb.sury.org+20191129
  Candidate: 3.0.1+2.0.8-2+ubuntu18.04.1+deb.sury.org+20191129
  Version table:
 *** 3.0.1+2.0.8-2+ubuntu18.04.1+deb.sury.org+20191129 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.5-1build1 500
        500 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 Packages
```

Sidenote: Thanks for all the work you do maintaning these PPAs Ondřej.

**Comment by oerdnj** [comment]
Uploaded, it should be building right now.

**Comment by A5hleyRich** [comment]
Awesome! Thanks for such a quick turnaround.
