### ISSUE TITLE
Packages are getting uninstalled all the time

### ISSUE THREAD

**Issue by azurit** [oerdnj/deb.sury.org#1312]
Your packages are getting uninstall automatically with some upgrades, which i don't understand. Last time this happened on 13.1.2020, attaching history.log.
[history.log](https://github.com/oerdnj/deb.sury.org/files/4064377/history.log)

Any ideas why is this happening? I'm doing aptitude update + aptitude upgrade. When i'm upgrading 30+ servers, i simply don't notice this until something stops working. Debian Stretch.

**Comment by oerdnj** [comment]
Sorry, this is a issue tracker for reporting bugs in the packages, not for user support.  I simply don't have time to provide this kind of service for free.

**Comment by azurit** [comment]
This cloud be a problem with repository/packages settings, i'm not asking for user support.

**Comment by azurit** [comment]
I don't see any reason on my side for this to happen, all packages were installed by hand and not as dependences, so there's no reason for aptitue itself to uninstall them with upgrades. Maybe it thinks that PHP 7.3 is a replacement for PHP 7.3?

**Comment by oerdnj** [comment]
You haven't done your debugging and you are asking me to debug your problem that you don't understand. That's user support.  Use appropriate forum for help with how apt and Debian works.

**Comment by azurit** [comment]
Ok, can you for 100% tell that this cannot be a problem with some kind of settings related to repository and/or packages? I will then start digging into it deeply. Thank you.

**Comment by azurit** [comment]
For example, i see these packages installed:
php-curl
php7.3-curl
php7.4-curl

I never wanted to install php7.4-curl, i don't any PHP 7.4 on that server. To me it looks that this happened:
1.) php-curl was installed which has dependency for php7.3-curl.
2.) You upgraded php-curl to 7.4, removed dependency for php7.3 and added dependency for php7.4.
3.) aptitude installed php7.4-curl and removed php7.3-curl (which i didn't want at all, i just wanted to upgarde my php 7.3)

**Comment by oerdnj** [comment]
Could you chitchat in appropriate forum please?  I am not your user support, I am not your sounding board, I am not your rubber ducky.  Come back when you have an issue to report.
