### ISSUE TITLE
Cannot install php-gearman for PHP 7.4

### ISSUE THREAD

**Issue by vdmitrydev** [oerdnj/deb.sury.org#1314]
Hi!

I have fresh Ubuntu 18.04.3 LTS, add `ppa:ondrej/php` and `ppa:ondrej/pkg-gearman` repositories and try to install `php-gearman`, but it is installed for PHP 7.3.

Steps to reproduce:
1. `add-apt-repository ppa:ondrej/php`
2. `add-apt-repository ppa:ondrej/pkg-gearman`
3. `apt-get update`
4. `apt-get install php`
5. `php -v` to make sure that PHP 7.4 is installed. I have the following output: `PHP 7.4.1 (cli) (built: Dec 18 2019 14:44:22) ( NTS )`
6. `apt-get install php-gearman`

The last command output:
<img width="646" alt="gearman" src="https://user-images.githubusercontent.com/7867682/72663008-b5098d80-39fe-11ea-814d-073d48763b6a.png">

Gearman extension is installed into PHP 7.3 directory, so i have to run my workers by `php7.3 worker.php`. `php worker.php` crushes with GearmanWorker class not found exception.

```
apt-cache policy php-gearman
php-gearman:
  Installed: 2.0.6+1.1.2-6+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.0.6+1.1.2-6+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2.0.6+1.1.2-6+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.3+1.1.2+-1build3 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages bionic/universe amd64 Packages
```

Seems like php-gearman is installed from `ppa:ondrej/php`, not `ppa:ondrej/pkg-gearman`. 

Some more info if it is important.
1. There is no `..._Packages` file
```
ls -la /var/lib/apt/lists | grep gearman
-rw-r--r-- 1 root root    15370 Nov 17 03:40 ppa.launchpad.net_ondrej_pkg-gearman_ubuntu_dists_bionic_InRelease
```
2. On https://launchpad.net/~ondrej/+archive/ubuntu/pkg-gearman/+packages page there is a build failure notification for Ubuntu 18.04
<img width="1261" alt="failure" src="https://user-images.githubusercontent.com/7867682/72664448-0f124f00-3a0f-11ea-97bf-8f02e7077abf.png">

Thanks for any help;

**Comment by oerdnj** [comment]
Could you try now?  I rebuilt php-gearman yesterday and I think the issue should be gone, but I don't really have time to check it now.

**Comment by vdmitrydev** [comment]
Yeah, now it is installed for PHP 7.4, thanks a lot.

P.S. Any use of `php-gearman` in 7.4 causes `Segmentation fault (core dumped)` error. Waiting for https://github.com/wcgallego/pecl-gearman/pull/74, maybe you will have to rebuild again :)

**Comment by oerdnj** [comment]
Create a new issue when there's at least working patch please.
