### ISSUE TITLE
PHP 7.0 xdebug left out in latest builds

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1316]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**

Thank you for building xdebug 2.9.1 per #1313 

However, PHP 7.0 was left out of the build, so can't install xdebug at all. Everything else from 5.6 through 7.4 works

**To Reproduce**

```
# sudo apt-get install php7.0-xdebug
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php7.0-xdebug is a virtual package provided by:
  php-xdebug 2.5.0-1 [Not candidate version]

E: Package 'php7.0-xdebug' has no installation candidate
```

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by samlin86** [comment]
Same issue here as of this morning.

**Comment by oerdnj** [comment]
Seems like upstream has removed support for PHP 7.0. I’ll see what I can do.

**Comment by oerdnj** [comment]
And yes, it doesn't compile :-(.  So, the question is - should I carry the last working version for PHP 7.0 of downgrade to xdebug 2.5.5 (same as of PHP 5.6)?

**Comment by rfay** [comment]
I would be fine with last working, same as 5.6. Sounds like a great solution. Thanks!

**Comment by derickr** [comment]
Upstream **support** has been removed since Xdebug 2.8: https://xdebug.org/docs/compat — it'll probably still compile from source. It's just that the `package.xm`l now has a `min` of `7.1.0`: https://github.com/xdebug/xdebug/blob/master/package.xml#L188

**Comment by oerdnj** [comment]
2.9.0 compiled, 2.9.1 doesn’t.

**Comment by derickr** [comment]
Yup, 2.8 dropped support for PHP 7.0, but it only stopped compiling with a bug fix in 2.9.1.

**Comment by oerdnj** [comment]
@derickr: So, if I want to keep PHP 7.0 supported with a older version of xdebug - should I go for latest 2.8, or stick to 2.9.0?

(Of course, it would be best if people would just upgrade to PHP 7.2+, but given the experience, that's not happening any time soon :-( )

**Comment by oerdnj** [comment]
Anyway, the issue has been fixed now.

**Comment by rfay** [comment]
Thanks so much! Preparing ddev release now.  Everything seems good.

**Comment by rfay** [comment]
Thanks so much for your work on this @oerdnj - I'd suggest that next time around PHP7.0 should use xdebug 2.5.5. Against all odds, there are people still using 7.0 in development, and they immediately hit the xdebug 2.9 problem that started this all off. And @derickr says he's going to try to make xdebug 2.9.0 not compile with php 7.0 I think.  Anyway, PHP7.0 as currently packaged makes all of those-who-shouldn't-be-using-it-anyway unhappy with extra breakpoints at every function header.
