### ISSUE TITLE
PHP 7.4.2, 7.3.14, 7.2.27 out

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1317]
Latest PHP versions tagged in git yesterday and [tarballs rolled](https://git.php.net/?p=web/php-distributions.git;a=log). No official announcements yet though.

As always, appreciate the service 🙃

**Comment by oerdnj** [comment]
The tarballs are not yet up on the distributions site.

**Comment by oerdnj** [comment]
But I released patches 5.6, 7.0 and 7.1 to Ubuntu PPAs.  I'll wait with Debian, as I need to sync the releases, so the amd64 builds are built first.
