### ISSUE TITLE
Repo apparently out of sync - Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz 

### ISSUE THREAD

**Issue by tigerlinux** [oerdnj/deb.sury.org#1318]
Good afternoon there,

We are getting this when trying to use the repo today (just now):

apt clean
apt update
Get:1 https://packages.sury.org/php stretch InRelease [6,760 B]
Ign:2 http://ftp.us.debian.org/debian stretch InRelease                                                         
Hit:3 http://files.freeswitch.org/repo/deb/debian-release stretch InRelease
Hit:4 http://ftp.us.debian.org/debian stretch-updates InRelease
Hit:5 http://ftp.us.debian.org/debian stretch Release
Get:6 https://packages.sury.org/php stretch/main amd64 Packages [134 kB]
Err:6 https://packages.sury.org/php stretch/main amd64 Packages                                    
  Writing more data than expected (133734 > 133677)
  Hashes of expected file:
   - Filesize:133677 [weak]
   - SHA256:cee3d783f205d7205c225d4a6223114769e6c07e388e5de3260bfcf8f24b7caf
   - SHA1:989a450eab3803987757c8a40340690f0cf51398 [weak]
   - MD5Sum:ae16b8c96e6ef5f717869b16903de029 [weak]
  Release file created at: Thu, 23 Jan 2020 17:09:55 +0000
Hit:7 http://security.debian.org/debian-security stretch/updates InRelease                         
Hit:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease                     
Fetched 6,760 B in 0s (7,536 B/s)    
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (133734 > 133677)
   Hashes of expected file:
    - Filesize:133677 [weak]
    - SHA256:cee3d783f205d7205c225d4a6223114769e6c07e388e5de3260bfcf8f24b7caf
    - SHA1:989a450eab3803987757c8a40340690f0cf51398 [weak]
    - MD5Sum:ae16b8c96e6ef5f717869b16903de029 [weak]
   Release file created at: Thu, 23 Jan 2020 17:09:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

Machine is a Debian 9 just installed and updated. The repo file was added as:

cat /etc/apt/sources.list.d/php.list 
deb https://packages.sury.org/php/ stretch main

I think this happened before (seen a similar issue already closed from 2019 and just added a comment there).

Is that behind a CDN right? The machine is in a datacenter at Detroit, USA. Should we just wait for the CDN to be refreshed or is there something we can do to help here??

Thanks in advance!

**Comment by oerdnj** [comment]
The rest can happens every hour (cron.hourly). I manually forced sync now.

**Comment by tigerlinux** [comment]
Thanks a lot. It is working now!

**Comment by anatoliiopw** [comment]
@tigerlinux probably the same issue again

Err:16 https://packages.sury.org/php stretch/main amd64 Packages                    
  Writing more data than expected (136068 > 135908)
  Hashes of expected file:
   - Filesize:135908 [weak]
   - SHA256:98fdc4415e3893d0945fb9a29189cd19ab652101bf0b3b254348b27a9f797738
   - SHA1:561b2093ab35eeba7573d3d83d662cc3deb02c83 [weak]
   - MD5Sum:607b17710a1e597da1ff3f5bb60e0741 [weak]
  Release file created at: Tue, 07 Jul 2020 07:20:43 +0000
Fetched 6760 B in 1s (6321 B/s)                               
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (136068 > 135908)
   Hashes of expected file:
    - Filesize:135908 [weak]
    - SHA256:98fdc4415e3893d0945fb9a29189cd19ab652101bf0b3b254348b27a9f797738
    - SHA1:561b2093ab35eeba7573d3d83d662cc3deb02c83 [weak]
    - MD5Sum:607b17710a1e597da1ff3f5bb60e0741 [weak]
   Release file created at: Tue, 07 Jul 2020 07:20:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
