### ISSUE TITLE
Add http2.load and http2.conf files to apache2 package

### ISSUE THREAD

**Issue by paulschreiber** [oerdnj/deb.sury.org#132]
Something like this should work:

/etc/apache2/mods-available/http2.conf:

    ProtocolsHonorOrder On
    Protocols h2 h2c http/1.1

/etc/apache2/mods-available/http2.load:

    LoadModule http2_module /usr/lib/apache2/modules/mod_http2.so

**Comment by oerdnj** [comment]
I think this got fixed with 2.4.17-2+deb.sury.org~*+1 upload, right? If not, please reopen the issue.
