### ISSUE TITLE
Issue with curl after updating PHP 7.3 to 

### ISSUE THREAD

**Issue by drkskwlkr** [oerdnj/deb.sury.org#1322]
Hi everyone,

I am having an issue with cURL after updating an Ubuntu 18.04 LTS to the latest version of PHP 7.3
(**`PHP Version 7.3.14-1+ubuntu18.04.1+deb.sury.org+1`**)

Since the update php7.3 seems to have lost cURL functionality even though the module seems to be installed.

A **`php7.3 -m`** command does not list curl among the available modules; the list itself is prepended by the following error message:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'curl.so' (tried: /usr/lib/php/20180731/curl.so (/usr/lib/php/20180731/curl.so: symbol curl_mime_addpart version CURL_OPENSSL_4 not defined in file libcurl.so.4 with link time reference), /usr/lib/php/20180731/curl.so.so (/usr/lib/php/20180731/curl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

I don't even know how to explain to myself the 'symbol curl_mime_addpart version CURL_OPENSSL_4 not defined in file libcurl.so.4 with link time reference' thing, and Google searches have not been useful (this error appears quite infrequently, and the most similar thing I found was a discussion about libcurl3 and libcurl4, and '[how Ubuntu toolchain works](https://github.com/desktop/dugite-native/issues/109)' which isn't at all helpful.)

Anyone else observing a similar issue? Any chance this is related to the recent update or should I look for the problem elsewhere? If the latter, could somebody point me in the right direction?

Thanks everyone for your time.

**Comment by todeveni** [comment]
I've got one intance of 18.04 LTS and it's running fine after update. `php -m` lists curl.

`php7.3-curl 7.3.14-1+ubuntu18.04.1+deb.sury.org+1`
`libcurl4 7.58.0-2ubuntu3.8`

**Comment by drkskwlkr** [comment]
Yes, libcurl is installed on my machine as well, same version as yours
`libcurl4 is already the newest version (7.58.0-2ubuntu3.8)`

**Comment by todeveni** [comment]
And `ldd /usr/lib/php/20180731/curl.so` output?

**Comment by drkskwlkr** [comment]
```
/usr/lib/php/20180731/curl.so: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/lib/php/20180731/curl.so)
        linux-vdso.so.1 (0x00007ffcdb5e5000)
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f026622c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0265e3b000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f0265bae000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f02656e2000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f02654c5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f02666a9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f02652a6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f02650a2000)
```

**Comment by todeveni** [comment]
And there's your problem.

**Comment by drkskwlkr** [comment]
```
dpkg -S /usr/lib/php/20180731/curl.so
php7.3-curl: /usr/lib/php/20180731/curl.so

```
```
apt-cache policy php7.3-curl
php7.3-curl:
  Installed: 7.3.14-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.3.14-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.3.14-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

Please excuse my ongoing cluelessness. I don't know how to use this information to fix my problem, or whether it is just a confirmation of a problem found with both php7.3 and php7.4 that requires intervention from @oerdnj

**Comment by FliegenKLATSCH** [comment]
`/usr/local/lib/libcurl.so.4` exists (as a symlink to libcurl.so.4.4.0), according to some googling this means that the version used to compile the curl.so was too new!? libcurl4 is on default debian/buster version 7.64.0-4.

**Comment by todeveni** [comment]
> Please excuse my ongoing cluelessness. I don't know how to use this information to fix my problem

You've got libcurl in /usr/local/lib, which clashes with the one Ubuntu provides.

**Comment by drkskwlkr** [comment]
I see.

```
root@micro:/usr/local/lib# ls -l | grep 'curl'
-rw-r--r-- 1 root root  907790 Sep 11 03:54 libcurl.a
-rwxr-xr-x 1 root root     950 Sep 11 03:54 libcurl.la
lrwxrwxrwx 1 root root      16 Sep 11 03:54 libcurl.so -> libcurl.so.4.4.0
lrwxrwxrwx 1 root root      16 Sep 11 03:54 libcurl.so.4 -> libcurl.so.4.4.0
-rwxr-xr-x 1 root root  472768 Sep 11 03:54 libcurl.so.4.4.0
```
I renamed libcurl.so.4.4.0 to something different and now `php7.3 -m` correctly displays the curl module. Why only PHP 7.3 is complaining about this and the PHP 5.6 and PHP 7.2 I also have installed on that machine work fine, I still have no idea...

Anyway: thanks @todeveni for bearing with me and pointing me in the right direction. I consider the matter resolved.

**Comment by mkdizajn** [comment]
I've solved this issue by removing curl lib 4 and installed ver3 with:

    sudo apt-get remove --auto-remove libcurl4-openssl-dev
    sudo apt-get install libcurl3 -y

leaving answer here because this was first search result so to help other fellow developer

**Comment by NgesBrian** [comment]
facing the exact same problem with pdo_pgsql

**Comment by hanyoonLDA** [comment]
> I've solved this issue by removing curl lib 4 and installed ver3 with:
> 
> ```
> sudo apt-get remove --auto-remove libcurl4-openssl-dev
> sudo apt-get install libcurl3 -y
> ```
> 
> leaving answer here because this was first search result so to help other fellow developer

Plesk users.... do NOT run this command. It will wipe everything.

**Comment by ichwill100** [comment]
Whoever faced this issue with php7.3 or php7.4 and curl not loading dynamically in Debian Buster (10).

I have sorted out this issue by installing libcurl4 and creating the ln to  /usr/local/lib/:
`apt-get install libcurl4`
`ln -fs /usr/lib/libcurl.so.4 /usr/local/lib/`
