### ISSUE TITLE
curl extension broken?

### ISSUE THREAD

**Issue by FliegenKLATSCH** [oerdnj/deb.sury.org#1323]
# php -v
PHP Warning: PHP Startup: Unable to load dynamic library 'curl.so' (tried: /usr/lib/php/20190902/curl.so (/usr/lib/php/20190902/curl.so: symbol curl_mime_addpart version CURL_OPENSSL_4 not defined in file libcurl.so.4 with link time reference), /usr/lib/php/20190902/curl.so.so (/usr/lib/php/20190902/curl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

# dpkg -S /usr/lib/php/20190902/curl.so
php7.4-curl: /usr/lib/php/20190902/curl.so

# apt-cache policy php7.4-curl

php7.4-curl: Installed: 7.4.2-1+0\~20200123.9+debian10\~1.gbp74d994 Candidate: 7.4.2-1+0\~20200123.9+debian10\~1.gbp74d994 Version table: *** 7.4.2-1+0\~20200123.9+debian10\~1.gbp74d994 500 500 https://packages.sury.org/php buster/main amd64 Packages 100 /var/lib/dpkg/status

**Comment by todeveni** [comment]
See #1322
