### ISSUE TITLE
PDO PGsql 12

### ISSUE THREAD

**Issue by tidytrax** [oerdnj/deb.sury.org#1324]
Hello, could you build a version with pgsql 12 ? instead of 11.5

Thanks

**Comment by oerdnj** [comment]
No, not really. The package needs to use default system libraries otherwise it will become madness. You can always recompile extensions locally - just copy the directory out and run: `phpize && ./configure && make && make install`

**Comment by tidytrax** [comment]
Oh thanks, so i can install all your packages, and just pdo_pgsql recompile in my system?
