### ISSUE TITLE
BIRD Repo GPG Key out of date

### ISSUE THREAD

**Issue by peerau** [oerdnj/deb.sury.org#1325]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
BIRD repo GPG key not up-to-date

```
Get:5 http://bird.network.cz/debian buster InRelease [4,037 B]
Err:5 http://bird.network.cz/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
```

**To Reproduce**
1. Go to 'https://bird.network.cz/?download&tdir=debian/'
2. Follow instructions to quickly setup the repository

**Expected behavior**
```
Get:5 http://bird.network.cz/debian buster InRelease [4,037 B]
Get:6 http://bird.network.cz/debian buster/main amd64 Packages [1,953 B]
```

**Distribution (please complete the following information):**
 - Debian 10 [buster]

**Package(s) (please complete the following information):**
Anything in the bird repo

**Additional context**
I know this isn't specifically for the BIRD repo, but it does say it's maintained by you, if this is wrong, I'm sorry!

**Comment by oerdnj** [comment]
I think you might be missing the update key, meanwhile get try this instead:
```
wget -O /etc/apt/trusted.gpg.d/bird.gpg http://bird.network.cz/debian/apt.gpg
```

**Comment by jmcclelland** [comment]
I've been [following these directions](https://packages.sury.org/php/README.txt) and using https://packages.sury.org/. Should we be using http://bird.network.cz instead?

**Comment by jmcclelland** [comment]
Also, I get the error reported on this ticket on Debian stretch machines, but not Debian buster machines (when using the packages.sury.org repo).

**Comment by oerdnj** [comment]
packages.sury.org is fine, I doubt this is the same error...  you posted instructions for PHP and the OP was talking about BIRD repositories. Fill a new issue with more details if you have problems with different repository.

**Comment by peerau** [comment]
> I think you might be missing the update key, meanwhile try this instead:
> 
> ```
> wget -O /etc/apt/trusted.gpg.d/bird.gpg http://bird.network.cz/debian/apt.gpg
> ```

```
root@bng1:~# wget -O - http://bird.network.cz/debian/apt.key | apt-key add -
--2020-02-03 15:52:44--  http://bird.network.cz/debian/apt.key
Resolving bird.network.cz (bird.network.cz)... 81.91.84.116, 2001:1568:b::145, 2001:1568:b:145::1
Connecting to bird.network.cz (bird.network.cz)|81.91.84.116|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3149 (3.1K)
Saving to: ‘STDOUT’

-                                                    100%[===================================================================================================================>]   3.08K  --.-KB/s    in 0s

2020-02-03 15:52:45 (13.6 MB/s) - written to stdout [3149/3149]

OK
root@bng1:~# apt update
Hit:6 http://bird.network.cz/debian buster InRelease
Err:6 http://bird.network.cz/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
Fetched 44.4 kB in 1s (34.4 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://bird.network.cz/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Failed to fetch http://bird.network.cz/debian/dists/buster/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@bng1:~# apt-key list | grep bird
Warning: apt-key output should not be parsed (stdout is not a terminal)
root@bng1:~# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2014-09-09 [SC]
      DF3D 585D B8F0 EB65 8690  A554 AC0E 4758 4A7A 714D
uid           [ unknown] CZ.NIC Labs Archive Automatic Signing Key <ftpmaster@labs.nic.cz>
sub   rsa4096 2014-09-09 [E]
```

the key in the repository itself is still old.

```
root@bng1:~# wget -O - https://packages.sury.org/bird/apt.gpg | apt-key add -
--2020-02-03 15:55:12--  https://packages.sury.org/bird/apt.gpg
Resolving packages.sury.org (packages.sury.org)... 104.31.94.169, 104.31.95.169, 2606:4700:3030::681f:5ea9, ...
Connecting to packages.sury.org (packages.sury.org)|104.31.94.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1769 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                                    100%[===================================================================================================================>]   1.73K  --.-KB/s    in 0s

2020-02-03 15:55:13 (35.4 MB/s) - written to stdout [1769/1769]

OK
root@bng1:~# apt update
Hit:5 http://bird.network.cz/debian buster InRelease
```

the key on your repository is fine however. some mirror mishap perhaps?

**Comment by Paktosan** [comment]
Half a year later, https://bird.network.cz/download/debian/apt.key still is a revoked key that is not the same key as the one used to sign the content of https://bird.network.cz/download/debian. Can you please put the correct key there?

**Comment by oerdnj** [comment]
I can't. I don't have write access there, you need to contact maintainers of the bird project.

**Comment by Paktosan** [comment]
That's surprising to hear. They were stating on their website(https://bird.network.cz/?download&tdir=debian/) that you are responsible for the Debian repository.

**Comment by oerdnj** [comment]
I left CZ.NIC three years ago, and I still update the packages in my repositories when they ask me to do so and they sync back the contents to bird.network.cz, but I do not proactively maintain the repository there.

**Comment by Paktosan** [comment]
Okay, so I tried your repository at packages.sury.org/bird which works absolutely fine.
