### ISSUE TITLE
Problems with ICU and symfony

### ISSUE THREAD

**Issue by HOSTED-POWER** [oerdnj/deb.sury.org#1326]
Hello,

We're having problems with INTL and symfony. Basically we need a newer INTL, we experience problems with Brazilian timezones atm because of the ICU which is too old. 

It's quite urgent for us to get the newer ICU because of these problems.

It looks a bit like : https://github.com/oerdnj/deb.sury.org/issues/1142

But it's outdated again:
```

php symfony_requirements

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Checking Symfony requirements:
  ...............................W........
...

 * intl ICU version installed on your system is outdated (64.1) and
   does not match the ICU data bundled with Symfony (65.1)
   > To get the latest internationalization data upgrade the ICU
   > system package and the intl PHP extension.


```

**Comment by todeveni** [comment]
In the meantime you can [use your own ICU data](https://github.com/oerdnj/deb.sury.org/issues/956#issuecomment-425557018) by using `ICU_DATA` environment variable and timezone data from ICU.

**Comment by HOSTED-POWER** [comment]
Hello @todeveni 

Thanks a lot for your quick reply!

Trying to download: https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-data.zip

Is that correct file?

I put contents into /opt/icu/icudt65l , but it doesn't seem to work:

```
/opt/icu# ICU_DATA=/opt/icu/icudt65l/ php -i | grep ICU
ICU version => 64.1
ICU Data version => 64.1
ICU TZData version => 2018i
ICU Unicode version => 12.0
ICU_DATA => /opt/icu/icudt65l/

MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
/opt/icu# ICU_DATA=/opt/icu php -i | grep ICU
ICU version => 64.1
ICU Data version => 64.1
ICU TZData version => 2018i
ICU Unicode version => 12.0
ICU_DATA => /opt/icu


```

**Comment by todeveni** [comment]
You need [these four *.res files](https://github.com/unicode-org/icu-data/tree/master/tzdata/icunew/2019c/44/le) into `/opt/icu/icudt64l` directory and `ICU_DATA=/opt/icu`

**Comment by HOSTED-POWER** [comment]
Wow thanks a lot for all your help!!

It's working now, just adding for reference:

```
cd /opt
git clone https://github.com/unicode-org/icu-data
mkdir -p /opt/icu/icudt64l
cp /opt/icu-data/tzdata/icunew/2019c/44/le/* /opt/icu/icudt64l/
```

**Comment by todeveni** [comment]
Destination directory `icudtXXY` name depends on your system and the directory where you copy resource files from.

 * `XX` = ICU library version used (`64` in this case)
 * `Y` = system endianness (for x86_64 this is `l`, as in little endian and you copy resource files from little endian `le` directory)

**Comment by oerdnj** [comment]
The ICU has been updated to 65.1
