### ISSUE TITLE
Error installing phpX.Y-fpm packages

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#1327]
The installation of FPM fails with:

```
Setting up php7.4-fpm (7.4.2-2+ubuntu16.04.1+deb.sury.org+1) ...
update-alternatives: error: alternative path /run/php/php7.4-fpm.sock doesn't exist
dpkg: error processing package php7.4-fpm (--configure):
 subprocess installed post-installation script returned error exit status 2
```

or

```
Setting up php7.2-fpm (7.2.27-3+ubuntu16.04.1+deb.sury.org+1) ...
touch: cannot touch '/run/php/php7.2-fpm.sock': No such file or directory
dpkg: error processing package php7.2-fpm (--configure):
 subprocess installed post-installation script returned error exit status 1
```

or a different weird error.

I am aware of the issue and I am working on a fix.

**Comment by gordboy** [comment]
I am quite sure we are all very happy with your hard work and timely updates. And we understand the warranty.

However, breaking the integrity of the package system (and also breaking everything else that depends on it) for me at least causes concern. To push out updates without even checking they are kosher seems to me a bit irresponsible. And this is not the first time unintended breakage has resulted in broken systems, downtime and unnecessary repair work.

I was called out to fix a system today, which involved rolling things back and also changing the nginx config amongst other things. People get annoyed when their stuff breaks, and they tend to blame me. So much for having a day off.

I am not happy at all. And as for your emails telling me to 'fuck off', you may be certain that I will remain 'fucked off' and never touch your amateur hour BS ever again.

**Comment by oerdnj** [comment]
@gordboy, well, I am not here to make you happy, and you haven't paid a dime for a service, but you came entitled requesting things from me. Let me tell you that I am very happy to not provide a service to rude people. That includes you.

**Comment by oerdnj** [comment]
JFTR I already have a fix ready, but currently can't upload to Ubuntu PPA because of the 16GB limit (`20.9 GiB (100.00%) of 16.0 GiB`).  I am trying to get the limit raised, so I can fix the problem rather sooner than later.

**Comment by oerdnj** [comment]
Fixed packages should be building as of this moment with even better fix in the queue, but I want to get the first fix to people as quickly as I can.

**Comment by oerdnj** [comment]
The fixed versions are:
* php5.6 - 5.6.40-19
* php7.0 - 7.0.33-18
* php7.1 - 7.1.33-7
* php7.2 - 7.2.27-4
* php7.3 - 7.3.14-4
* php7.4 - 7.4.2-4

**Comment by oerdnj** [comment]
From the feedback, I got, I think this can be closed now.
