### ISSUE TITLE
Php 7.* FPM install problem

### ISSUE THREAD

**Issue by PrzemoVi** [oerdnj/deb.sury.org#1329]
Hi.
I'm using ubuntu-server 18.04.3.
I tried reinstall of entire os 30 minutes ago, didn't help.
My production server is fcking down because I wanted to reinstall php from 7.2 to 7.4...

apt-get install php7.4-fpm / apt-get install --fix-missing fails with:

```
Konfigurowanie pakietu php7.4-fpm (7.4.2-3+ubuntu18.04.1+deb.sury.org+1) ...
/var/lib/dpkg/info/php7.4-fpm.postinst: 32: /var/lib/dpkg/info/php7.4-fpm.postinst: /run/php/php7.4-fpm.sock: Permission denied
dpkg: błąd przetwarzania pakietu php7.4-fpm (--configure):
 installed php7.4-fpm package post-installation script subprocess returned error exit status 126
Wystąpiły błędy podczas przetwarzania:
 php7.4-fpm
```

I tried to create /run/php folder with permissions 777, didn't help.
I`m gonna die if I didn't get this running today.

Thanks for your time.

**Comment by Sopsy** [comment]
Already fixed with build in progress. Try again in an hour.

https://github.com/oerdnj/deb.sury.org/issues/1327
https://launchpad.net/~ondrej/+archive/ubuntu/php/+builds?build_text=&build_state=building

**Comment by cybercoder** [comment]
Thanks it is fixed.
Regards

**Comment by oerdnj** [comment]
Dup of #1327
