### ISSUE TITLE
Issue with LetsEncrypt certificates on OpenSSL: unable to get local issuer certificate

### ISSUE THREAD

**Issue by wolfy1339** [oerdnj/deb.sury.org#1330]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
OpenSSL fails to verify Lets Encrypt certificates, even tough both the ISRG Root X1 and DST Root CA X3 are in the system CA certificate store

**To Reproduce**
1. Add the apache2 ppa
2. Install/Upgrade OpenSSL and it's requirements
3. Use `openssl s_client -connect letsencrypt.org:443` to check the SSL handshake details.
4. Look at the beginning of the output, and check for `verify error:num=20:unable to get local issuer certificate`

**Expected behavior**
For OpenSSL to be able to complete the chain to verify LetsEncrypt certificates and not error out

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu] Ubuntu 18.04
 - Architecture: [e.g. amd64 or armhf or ...] amd64
 - Repository: [e.g. Ubuntu PPA or packages.sury.org] PPA

**Package(s) (please complete the following information):**
```
$ apt-cache policy openssl libssl1.1 libssl-dev
openssl:
  Installed: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu bionic/main amd64 Packages
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
     1.1.1-1ubuntu2.1~18.04.5 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-updates/main amd64 Packages
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-security/main amd64 Packages
     1.1.0g-2ubuntu4 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic/main amd64 Packages
libssl1.1:
  Installed: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu bionic/main amd64 Packages
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
     1.1.1-1ubuntu2.1~18.04.5 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-updates/main amd64 Packages
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-security/main amd64 Packages
     1.1.0g-2ubuntu4 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic/main amd64 Packages
libssl-dev:
  Installed: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu bionic/main amd64 Packages
     1.1.1d-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
     1.1.1-1ubuntu2.1~18.04.5 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-updates/main amd64 Packages
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic-security/main amd64 Packages
     1.1.0g-2ubuntu4 500
        500 http://ubuntu.bhs.mirrors.ovh.net/ubuntu bionic/main amd64 Packages
```

**Additional context**
This doesn't happen with the OpenSSL packages provided by Ubuntu

**Comment by wolfy1339** [comment]
I seem to have figured out the problem by poking around my system.
`openssl version -d` returns `/opt/openssl/ssl` instead of `/usr/lib/ssl`

**Comment by oerdnj** [comment]
Can you do `ldd $(which openssl)`?

**Comment by oerdnj** [comment]
> I seem to have figured out the problem by poking around my system.
> `openssl version -d` returns `/opt/openssl/ssl` instead of `/usr/lib/ssl`

This would point to the fact that you might have a different copy of openssl installed in `/opt/openssl` as the packages don't set `/opt` anywhere at all.

**Comment by oerdnj** [comment]
Did not receive any additional info, closing the bug.
