### ISSUE TITLE
downloading some debs from stretch repos fails

### ISSUE THREAD

**Issue by FalzoMAD** [oerdnj/deb.sury.org#1331]
heyhey, I just noticed that on a stretch system with dist-upgrade fails due to not being able to fetch some files:

`E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-common_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-mysql_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-opcache_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-intl_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-json_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-readline_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-cli_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-soap_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-mbstring_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-curl_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-zip_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-fpm_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-xml_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-gd_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-bcmath_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.2/php7.2-common_7.2.27-5+0~20200202.35+debian9~1.gbp2925f8_amd64.deb  404  Not Found
`

I get the same on other stretch servers as well.

also after uninstalling php7.4 from another stretch box and trying to reinstall again, a few more php7.4 packages are giving that message:

`E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-bz2_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-curl_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-mysql_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-soap_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
E: Fehlschlag beim Holen von https://packages.sury.org/php/pool/main/p/php7.4/php7.4-xml_7.4.2-5+0~20200202.10+debian9~1.gbp3a5fde_amd64.deb  404  Not Found
`

when browsing the repo with e.g. chrome the files seem to be there and I can download them...
I did not check any other distros yet, only deb 9.11 - maybe you wanna check your latest release. it's all files from this morning as it seems...

**Comment by lonesomewalker** [comment]
This is because of the f*cking cloudflare stuff...

Download the Packages file, you get the correct filenames and can download these files directly.
So did i today, REALLY annoying.

Whos idea was it to stick this with cloudflare?

**Comment by oerdnj** [comment]
Congratulations @lonesomewalker, you just earned yourself a block!

**Comment by oerdnj** [comment]
Hi @FalzoMAD, this usually happens when the rsync from the build server happens while the new build is in progress.

Usually this resolves within hour when new sync is launched.

I will rework this to trigger the sync from the build script instead of from cron which should fix the issue.

**Comment by FalzoMAD** [comment]
@oerdnj thanks for clarifying. looks like it's working again now.

**Comment by oerdnj** [comment]
I just rewrote the build scripts to do push on successful build and purge whole `/dists/` in the Cloudflare cache. This should help with the synchronization issues.
