### ISSUE TITLE
phpX-fpm.service references non-absolute path to update-alternatives

### ISSUE THREAD

**Issue by glitsj16** [oerdnj/deb.sury.org#1332]
**Unsupported distributions**
 - [X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [ X] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
All `phpX-fpm.service` packages for Xenial (16.04 LTS) and Bionic (18.04 LTS) could be improved upon by using the **full path** to the `update-alternatives` command. Support for non-absolute paths in systemd was [introduced in v239](https://github.com/systemd/systemd/commit/5008da1ec1cf2cf8c15b702c4052e3a49583095d). Both Xenial and Bionic have an older systemd version by default and throw warnings when starting the phpX-fpm service.

**To Reproduce**
1. Install php7.4-fpm
2. Check php7.4-fpm service status

**Expected behavior**
No warnings about not finding `update-alternatives` should show in `sudo systemctl status php7.4-fpm.service`.

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Architecture: amd64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

$ apt-cache policy systemd
systemd:
  Installed: 229-4ubuntu21.23
  Candidate: 229-4ubuntu21.23
  Version table:
 *** 229-4ubuntu21.23 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     229-4ubuntu21.21 500
        500 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     229-4ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

$  apt-cache policy php7.4-fpm
php7.4-fpm:
  Installed: 7.4.2-5+ubuntu16.04.1+deb.sury.org+2
  Candidate: 7.4.2-5+ubuntu16.04.1+deb.sury.org+2
  Version table:
 *** 7.4.2-5+ubuntu16.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

$ which -a update-alternatives
/usr/bin/update-alternatives

**Additional context**
$ cat /lib/systemd/system/php7.4-fpm.service
[Unit]
Description=The PHP 7.4 FastCGI Process Manager
Documentation=man:php-fpm7.4(8)
After=network.target

[Service]
Type=notify
PIDFile=/run/php/php7.4-fpm.pid
ExecStart=/usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf
ExecStartPost=-update-alternatives --quiet --install /run/php/php-fpm.sock php-fpm.sock /run/php/php7.4-fpm.sock 74
ExecStopPost=-update-alternatives --quiet --remove php-fpm.sock /run/php/php7.4-fpm.sock
ExecReload=/bin/kill -USR2 $MAINPID

[Install]
WantedBy=multi-user.target

The prepended '-' takes care of not putting the service into failed state. Still, IMHO it is nicer to use '/usr/bin/update-alternatives ...' in both ExecStartPost and ExecStopPost stanzas (at least on Xenial/Bionic).

I've tested this on 'amd64' only, but this would be similar on all arches. It also affects php5.6-fpm, php7.0-fpm, php7.1-fpm, php7.2-fpm and php7.3-fpm.

Regards

**Comment by oerdnj** [comment]
Thanks, that’s a very good bug report. I appreciate it!

**Comment by oerdnj** [comment]
This should be fixed now on Ubuntu.

**Comment by glitsj16** [comment]
@oerdnj Confirming this is indeed fixed on Ubuntu. Thank you for the speedy response.
