### ISSUE TITLE
debian packages unpacking slow

### ISSUE THREAD

**Issue by olaulau** [oerdnj/deb.sury.org#1335]
**Unsupported distributions**
 - [X] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [X] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
when updating PHP packages from your repository, thius seems very slow (about 1 extraction per second, on a good computer with SSD). This seems very slow compared to other packages updates, even comparing to PHP packages from ubuntu / debian official repo.

**To Reproduce**
- add deb sury repo
- use many of his packages (severals PHP versions with many modules)
- wait for a new minor PHP release to come
- do upgrade
- this takes about half an hour !
(tested on severals computers)

**Expected behavior**
faster unpacking !

**Distribution (please complete the following information):**
 - OS:  ubuntu 18.04 / 19.10 / debian 10
 - Architecture: amd64
 - Repository: Ubuntu PPA  & packages.sury.org

**Package(s) (please complete the following information):**
many many ...

**Additional context**
mostly upgrading (forgot if it was faster the first time using the repository)

I don't know if it is possible to change something on the packaging side, maybe there is a tip on my side to speed it up ?

**Comment by oerdnj** [comment]
That's most certainly problem on your local machines, as I don't see this behavior:

Debian buster:
```
time apt -y install php5.6-fpm php7.0-fpm php7.1-fpm php7.2-fpm php7.3-fpm php7.4-fpm
[...]
1 upgraded, 52 newly installed, 0 to remove and 4 not upgraded.
Need to get 32.2 MB of archives.
[...]
real	0m29.580s
user	0m27.394s
sys	0m4.983s
```

Ubuntu bionic:
```
time apt -y install php5.6-fpm php7.0-fpm php7.1-fpm php7.2-fpm php7.3-fpm php7.4-fpm
[...]
1 upgraded, 47 newly installed, 0 to remove and 5 not upgraded.
Need to get 26.0 MB of archives.
After this operation, 107 MB of additional disk space will be used.
[...]
real	0m28.643s
user	0m26.501s
sys	0m4.789s
```

The `ucf` takes some time when creating the new config files, but it's still manageable.

Make sure you are using `noatime,nodiratime,relatime` and no `discard` on your SSD mounts, read here about `discard`: https://www.isc.org/blogs/a-curious-case-of-intermittent-bind-system-test-failures/

**Comment by giovannifour** [comment]
Hi,
I have the same problem. No "discard" related.
The problem is only SURY php package.
Thanks.
