### ISSUE TITLE
session_create_id throw warning

### ISSUE THREAD

**Issue by Pchol** [oerdnj/deb.sury.org#1336]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
session_create_id throw error ```PHP Warning:  session_create_id(): Failed to create new ID``` if session already started

**To Reproduce**
run this php code:
```
<?php                     
                          
session_start();          
session_create_id();      
```

**Expected behavior**
script completed without warning

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04, Ubuntu 19.04
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
apt-cache policy php7.1-cli
php7.1-cli:
  Installed: 7.1.33-9+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.1.33-9+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.1.33-9+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Additional context**
version 7.1.33-3+ubuntu19.04.1+deb.sury.org+1 worked fine
the same problem exist in 7.2 and newer

**Comment by oerdnj** [comment]
I am sorry, but that’s not a bug in packaging, so you need to report it to upstream bug tracker.
