### ISSUE TITLE
Unable to start php7.4-fpm after installation on Debian 10 Buster.

### ISSUE THREAD

**Issue by LeShadow** [oerdnj/deb.sury.org#1338]
**Describe the bug**
When I try to install php7.4-fpm on Debian 10 (Buster), php-fpm always fails to start with the following error:

> Job for php7.4-fpm.service failed because the control process exited with error code.
> See "systemctl status php7.4-fpm.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript php7.4-fpm, action "restart" failed.
> ● php7.4-fpm.service - The PHP 7.4 FastCGI Process Manager
>    Loaded: loaded (/lib/systemd/system/php7.4-fpm.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2020-02-11 23:58:56 CET; 10ms ago
>      Docs: man:php-fpm7.4(8)
>   Process: 17358 ExecStart=/usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf (code=exited, status=78)
>   Process: 17359 ExecStopPost=/usr/bin/update-alternatives --quiet --remove php-fpm.sock /run/php/php7.4-fpm.sock (code=exited, status=0/SUCCESS)
>  Main PID: 17358 (code=exited, status=78)
> 
> Feb 11 23:58:56 hostname.tld systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
> Feb 11 23:58:56 hostname.tld php-fpm7.4[17358]: [11-Feb-2020 23:58:56] ERROR: failed to open configuration file '/etc/php/7.4/fpm/php-fpm.conf': No such file or directory (2)
> Feb 11 23:58:56 hostname.tld php-fpm7.4[17358]: [11-Feb-2020 23:58:56] ERROR: failed to load configuration file '/etc/php/7.4/fpm/php-fpm.conf'
> Feb 11 23:58:56 hostname.tld php-fpm7.4[17358]: [11-Feb-2020 23:58:56] ERROR: FPM initialization failed
> Feb 11 23:58:56 hostname.tld systemd[1]: php7.4-fpm.service: Main process exited, code=exited, status=78/CONFIG
> Feb 11 23:58:56 hostname.tld systemd[1]: php7.4-fpm.service: Failed with result 'exit-code'.
> Feb 11 23:58:56 hostname.tld systemd[1]: Failed to start The PHP 7.4 FastCGI Process Manager.
> dpkg: error processing package php7.4-fpm (--configure):
>  installed php7.4-fpm package post-installation script subprocess returned error exit status 1
> 

**To Reproduce**
1. `apt install php7.4-fpm` or `aptitude install php7.4-fpm`
2. The command will fail because of missing files.

**Expected behavior**
The behavior that we expect is that php-fpm to start with the default configuration

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

> apt-cache policy php7.4-fpm
> php7.4-fpm:
>   Installed: 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde
>   Candidate: 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde
>   Version table:
>      7.4.2-7 90
>          90 http://deb.debian.org/debian unstable/main amd64 Packages
>  *** 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde 500
>         500 https://packages.sury.org/php buster/main amd64 Packages
>         100 /var/lib/dpkg/status

**Additional context**
My apologies if this is a bad bug report, it is my first :)

**Comment by oerdnj** [comment]
Well, the missing configuration file didn’t disappear by itself:
ERROR: failed to open configuration file '/etc/php/7.4/fpm/php-fpm.conf': No such file or directory (2)

**Comment by LeShadow** [comment]
@oerdnj What do you mean by that?
Originally I wiped all PHP installations from that server because I wanted a clean slate, which meant also removing /etc/php/*

And now when I try to install php7.4 I get that error (every single old installation of php has been removed for now). And I don't get the error when I try to install php7.3-fpm?

**Comment by LeShadow** [comment]
@oerdnj And the output you gave is literally the last part of the installation process. it appears right after I execute:
`aptitude install php7.4-fpm`

I didn't touch any files yet and this error pops up

**Comment by LeShadow** [comment]
@oerdnj my apologies, due to the installation of multiple php versions and some errors on my part (I didn't purge old installations), the installation failed somehow every time. 

I purged my server from all php packages, reinstalled it and now it works!
