### ISSUE TITLE
Problem upgrading Apache on Precise

### ISSUE THREAD

**Issue by synack42** [oerdnj/deb.sury.org#134]
Hi,

First thanks for maintaining these PPAs, they are a great asset!

We're using the php5 PPA on 12.04/Precise (64).

We've found ourselves stuck on version 2.4.12-1 of apache due to an apache2-mpm-prefork dependency issue.  Issue #114 appears identical, however we cannot uninstall that package without breaking other official apache modules that depend on the transitional package:

> libapache2-mod-log-sql
> libapache2-mod-log-sql-dbi
> libapache2-mod-log-sql-mysql
> libapache2-mod-log-sql-ssl

Sorry if this is a really basic question, but is there any easy way to remove the transitional package without breaking apt moving forward?

If it helps, here are all of the apache and php packages installed:

>  apache2                          2.4.12-1+deb.sury.org~precise+5
>  apache2-bin                      2.4.12-1+deb.sury.org~precise+5
>  apache2-data                     2.4.12-1+deb.sury.org~precise+5
>  apache2-mpm-prefork              2.4.12-1+deb.sury.org~precise+5
>  apache2-utils                    2.4.16-4+deb.sury.org~precise+4
>  libapache2-mod-log-sql           1.100-15
>  libapache2-mod-log-sql-dbi       1.100-15
>  libapache2-mod-log-sql-mysql     1.100-15
>  libapache2-mod-log-sql-ssl       1.100-15
>  libapache2-mod-php5              5.5.30+dfsg-1+deb.sury.org~precise+1
>  libapache2-mod-php5              5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5                             5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-apcu                        4.0.6-1+deb.sury.org~precise+1
>  php5-cli                         5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-common                      5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-curl                        5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-gd                          5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-gmp                         5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-intl                        5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-json                        1.3.7-1+deb.sury.org~precise+1
>  php5-ldap                        5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-mcrypt                      5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-memcached                   2.2.0-2+deb.sury.org~precise+1
>  php5-mysql                       5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-pgsql                       5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-pspell                      5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-readline                    5.5.30+dfsg-1+deb.sury.org~precise+1
>  php5-xmlrpc                      5.5.30+dfsg-1+deb.sury.org~precise+1

**Comment by oerdnj** [comment]
Support for Ubuntu Precise for PHP 5.5+ has been dropped.
