### ISSUE TITLE
Error installing phpX.Y-fpm packages -  still persists on latest-latest  7.1.33-9 and 7.3.14-6

### ISSUE THREAD

**Issue by zaskokus** [oerdnj/deb.sury.org#1340]
Issue identical to Error installing phpX.Y-fpm packages #1327 
Issue was closed, and I'm not sure whether author is aware or not, the latest available versions are still affected with exact same issue. My system is latest patched xenial.

**Comment by oerdnj** [comment]
You haven’t really provided any details, so how do you think anybody could try to help you?

**Comment by zaskokus** [comment]
I was just updating the issue, my bad. It turns out is directly related to the PID issue from all the other closed tickets. I had it set up in my php-fpm.conf file, once I've changed it to /run/php/php7.1-fpm.pid it all works fine. I'm still wrapping my mind around the reason why did it occur to me right now and not earlier.

**Comment by oerdnj** [comment]
It’s some quirk in systemd which I also don’t fully understand.

**Comment by zaskokus** [comment]
Can we get this fixed somehow? Because so far many people have bumped into this issue. Apparently no custom PIDs are working at all, and that's not a small thing to just ignore.

**Comment by zaskokus** [comment]
Ha. i found the REAL issue. Ownership of pidfile stayed root:root, starting with new versions it's whatever user is php-fpm running with!

**Comment by oerdnj** [comment]
I am not sure what you did to your installation, but the pid file is owned by root:root here:
```
$ ls -l /run/php/*
-rw-r--r-- 1 root     root      3 Feb 11 04:39 /run/php/php7.4-fpm.pid
srw-rw---- 1 www-data www-data  0 Feb 11 04:39 /run/php/php7.4-fpm.sock
lrwxrwxrwx 1 root     root     30 Feb 11 04:39 /run/php/php-fpm.sock -> /etc/alternatives/php-fpm.sock
```

This is with the latest PHP 7.4
```
$ apt-cache policy php7.4-fpm
php7.4-fpm:
  Installed: 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde
  Candidate: 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde
  Version table:
 *** 7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

systemd is more picky when the pidfile is not owned by root according to the documentation, but it doesn't seem to be caused by the package.

**Comment by zaskokus** [comment]
I'll try to replicate the issue with my cached versions tomorrow to make it clear. But I'm sure what I've seen.
