### ISSUE TITLE
Systemd now required?

### ISSUE THREAD

**Issue by cafn** [oerdnj/deb.sury.org#1343]
**Unsupported distributions**
 - [X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [X] I'm *not* trying to mirror the repositories using wget, curl, mozilla. 

**Describe the bug**
Did an "apt dist-upgrade" a few minutes ago, like I have many times while in a testing virtual machine, not production.   Afterwards I noticed that php7.3-fpm and php7.4-fpm did not work.  A server status check showed nothing at all.  There is not a .sock file at /var/run/php/ .  

This is most unusual as I have been using your repository in Devuan for a few years now.  I then read your tweet from today saying, 
"This means that phpX.Y-fpm package now depends on systemd package."

Does this mean that your repo will no longer be of use with Devuan or any non-systemd distro?
Naturally, systemd is blocked from being installed.

**Expected behavior**
Was expecting the update to successfully complete, with the services running afterward.

**Distribution (please complete the following information):**
 - OS:  Devuan beowulf (not-released-yet), using buster packages, minus systemd and deps
 - Architecture:  amd64
 - Repository:  packages.sury.org  buster  main

**Package(s) (please complete the following information):**
root@localhost:/home/user# apt-cache policy php7.3-fpm
php7.3-fpm:
  Installed: (none)
  Candidate: 7.3.15-1+0~20200220.53+debian10~1.gbp931d08
  Version table:
     7.3.15-1+0~20200220.53+debian10~1.gbp931d08 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     7.3.14-5+0~20200202.52+debian10~1.gbpa71879 -1
        100 /var/lib/dpkg/status
     7.3.14-1~deb10u1 500
        500 http://deb.devuan.org/merged beowulf-security/main amd64 Packages
     7.3.11-1~deb10u1 500
        500 http://deb.devuan.org/merged beowulf/main amd64 Packages

**Additional context**
Is it mandatory to go back to using debian's repositories, or is this situation temporary?

snippet of apt logfile:
Start-Date: 2020-02-20  14:44:51
Commandline: apt dist-upgrade
Requested-By: user (1000)
Install: libapache2-mod-php7.4:amd64 (7.4.3-1+0~20200220.11+debian10~1.gbpe23899, automatic)
Upgrade: php7.3-xml:amd64 (7.3.14-5+0~20200202.52+debian10~1.gbpa71879, 7.3.15-1+0~20200220.53+debian10~1.gbp931d08), php7.4-cli:amd64 
(many notations removed to save space here)
(7.3.14-5+0~20200202.52+debian10~1.gbpa71879, 7.3.15-1+0~20200220.53+debian10~1.gbp931d08)
Remove: php7.4-fpm:amd64 (7.4.2-5+0~20200202.10+debian10~1.gbp3a5fde), php7.3-fpm:amd64 (7.3.14-5+0~20200202.52+debian10~1.gbpa71879), php-fpm:amd64 (2:7.4+72+0~20200122.20+debian10~1.gbpcd96c7)
End-Date: 2020-02-20  14:48:11

**Comment by oerdnj** [comment]
Yes, the package rely on systemd-tmpfiles.

**Comment by szutt** [comment]
This is bad news :-(

**Comment by szutt** [comment]
https://github.com/oerdnj/pkg-php/pull/1

**Comment by szutt** [comment]
@oerdnj I think you can you add
```
ifeq (devuan,$(DPKG_VENDOR))
  ENABLE_SYSTEMD = no
endif
```
to debian/rules

**Comment by oerdnj** [comment]
It's more than enough to have support for Distributions 4 years old. I am not going to complicate code purely on ideological reasons.  Devuan needs to supply shims for the non-init parts like `systemd-tmpfiles`.  When (and if) Debian splits `systemd-tmpfiles` into a separate package and add `opentmpfiles`, I will happily adapt the packages to use it. Until the time it is what it is.

**Comment by szutt** [comment]
@oerdnj  Thank you for your response. I understand, sir. I won't bother you again, I'm truly sorry.

**Comment by oerdnj** [comment]
You don't have to apologize, it's not your fault that Devuan people decided to be "pure" instead of taking the pragmatic approach.

Also the snippet you supplied won't work because it needs to be applied at compile time.

You can use `equivs` package and symlink to `opentmpfiles-tmpfiles` from `opentmpfiles` package to workaround the dependency.

**Comment by oerdnj** [comment]
See https://github.com/oerdnj/deb.sury.org/issues/1347#issuecomment-589666279 and following comments on workarounds.

**Comment by tdrnetworks** [comment]
A kind soul has reverted the changes for PHP v5.6 right through to v7.4.3:

http://dev1galaxy.org/viewtopic.php?id=3331

**Comment by tdrnetworks** [comment]
### PHP Rebuilds (5.6/7.0/7.1/7.2/7.3/7.4 for Devuan Jessie
deb https://pkgs.tdrnetworks.com/apt/devuan jessie main

**Comment by tdrnetworks** [comment]
This should complete the set (for now). 

We've just added builds for beowulf;   so we have jessie, ascii and beowulf all rebuilt without systemd references.

The repo gpg public key is here: 
http://pkgs.tdrnetworks.com/apt/devuan/gpg.key

The repo offers AMD64 debs, and DPKG sources.

### PHP Rebuilds for Devuan Jessie
deb https://pkgs.tdrnetworks.com/apt/devuan jessie main
deb-src https://pkgs.tdrnetworks.com/apt/devuan jessie main

### PHP Rebuilds for Devuan Ascii
deb https://pkgs.tdrnetworks.com/apt/devuan ascii main
deb-src https://pkgs.tdrnetworks.com/apt/devuan ascii main

### PHP Rebuilds for Devuan Beowulf
deb https://pkgs.tdrnetworks.com/apt/devuan beowulf main
deb-src https://pkgs.tdrnetworks.com/apt/devuan beowulf main
