### ISSUE TITLE
PHP-FPM doesn't start if not using unix sockets

### ISSUE THREAD

**Issue by bashgeek** [oerdnj/deb.sury.org#1344]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**To Reproduce**
Install PHP-FPM change the actual configs to not use unix sockets but IP sockets instead, try restarting it.

**Expected behavior**
PHP-FPM actually starts ,-)

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64
 - Repository: sury.org

**Package(s) (please complete the following information):**
php7.4-fpm:
  Installed: 7.4.3-1+0~20200220.11+debian10~1.gbpe23899
  Candidate: 7.4.3-1+0~20200220.11+debian10~1.gbpe23899
  Version table:
 *** 7.4.3-1+0~20200220.11+debian10~1.gbpe23899 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status

**Additional context**
Alright, with an update around 3 versions ago (3-4 weeks) a few new lines made it to your systemd file:
```
ExecStartPost=-/usr/bin/update-alternatives --quiet --install /run/php/php-fpm.sock php-fpm.sock /run/php/php7.4-fpm.sock 74 2>/dev/null || /bin/true
ExecStopPost=-/usr/bin/update-alternatives --quiet --remove php-fpm.sock /run/php/php7.4-fpm.sock 2>/dev/null || /bin/true
```

While it's certainly nice to have those around in some cases, it'll completely break starting PHP7.4 on our systems, because we do not use unix sockets, but IP sockets instead for network connections in our cluster. Apparently update-alternatives waits for the file/socket to become available, but it'll never be so eventually the starting process will timeout. We fixed this manually by removing these two lines from the service file, but they obviously come back after every update from your repo.

Not sure what to do here and if these lines are somehow required, but it really breaks our setup and I'm sure we're not the only ones not using unix sockets. I saw a few other issues having similar issues like us and a lot of talk about PID files (and nope, we never changed anything here), maybe that's actually also the reason for their issues.

Let me know if you need any further input.

**Comment by bashgeek** [comment]
Never mind - just saw your post on Patreon :-)

**Comment by byan** [comment]
Is any fix release for binding ip & port ?

**Comment by oerdnj** [comment]
@bashgeek JFTR the easy way would be running `systemctl edit phpX.Y-fpm` and typing:

```
[Unit]
ExecStartPost=
ExecStopPost=
```

That will add a permanent override.  But you are right, the `update-alternatives` needs a little wrapper to make it a bit smarter.

**Comment by mphilipps** [comment]
Here we have slightly different issue with the update. It appears that the update-alternative call does not terminate within 30secs whereupon systemd kills it and marks the service as failed.  

In prior versions update-alternatives wasn't called with an absolute path and as such the ExecStartPost and ExecStopPost were immediately skipped by systemd.

Why are you calling update-alternatives during the service start anyway? As far as I know multiple php versions at the same time isn't supported anymore and as such there should be no reason to call it at every start/stop.

**Comment by oerdnj** [comment]
> Why are you calling update-alternatives during the service start anyway? As far as I know multiple php versions at the same time isn't supported anymore and as such there should be no reason to call it at every start/stop.

That's not true. Multiple PHP versions are supported at the same time.

> E: Also it should be [Service] not [Unit]

Thanks, I was writing that from top of my head. I'll fix that in my comment.

**Comment by bashgeek** [comment]
@oerdnj Just fyi, the systemd service-file update (with your socket-helper wrapper) yesterday solved the issues for me on all systems without having to override the mentioned parameters.

Thanks! :-)
