### ISSUE TITLE
rsync does not work anymore.

### ISSUE THREAD

**Issue by Kraeutergarten** [oerdnj/deb.sury.org#1345]
Hello,
since yesterday i get the following error:
`rsync: failed to connect to rsync.sury.org (78.141.220.255): Connection refused (111)`

I tried it on different servers, so i guess there is something wrong with your rsync server.

command:
`rsync rsync://rsync.sury.org/repositories/php/dists/`

**Comment by oerdnj** [comment]
Sorry, I made a typo in rsyncd configuration, it should be working now:
```
Feb 21 08:33:43 himiko.rfc1925.org rsyncd[16269]: rsyncd version 3.1.3 starting, listening on port 873
```

**Comment by Kraeutergarten** [comment]
Thanks!
