### ISSUE TITLE
update-alternatives: error: unknown argument '2>/dev/null'

### ISSUE THREAD

**Issue by leofeyer** [oerdnj/deb.sury.org#1346]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

**Describe the bug**
Since the [February updates](https://www.patreon.com/posts/february-updates-34189046) mentioned on Patreon, we see a lot of `update-alternatives: error: unknown argument '2>/dev/null'` in the log files. I have searched the service files and found the following difference:

```
# PHP 7.1, 7.2, 7.3
ExecStartPost=-/usr/bin/update-alternatives --quiet --install /run/php/php-fpm.sock php-fpm.sock /run/php/php7.3-fpm.sock 73
ExecStopPost=-/usr/bin/update-alternatives --quiet --remove php-fpm.sock /run/php/php7.3-fpm.sock
```

```
# PHP 7.4
ExecStartPost=-/usr/bin/update-alternatives --quiet --install /run/php/php-fpm.sock php-fpm.sock /run/php/php7.4-fpm.sock 74 2>/dev/null || /bin/true
ExecStopPost=-/usr/bin/update-alternatives --quiet --remove php-fpm.sock /run/php/php7.4-fpm.sock 2>/dev/null || /bin/true
```

I figured that the error must be caused by the `php7.4-fpm.service` file, so I removed the `2>/dev/null || /bin/true` part and ran `sudo systemctl daemon-reload` and `sudo systemctl restart php*`. That made the error disappear.

Can you confirm that removing the `2>/dev/null || /bin/true` part was the correct fix?

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by mphilipps** [comment]
That won't work. `Exec*` instructions in service files get directly executed and won't be passed through a shell. As such any shell specific instructions like `2>` or `|| `won't work. If you want to use them you need to explicitly start a shell like` /bin/sh -c ‘/do/something 2> /dev/null || whatever'`

**Comment by oerdnj** [comment]
I already have a `/usr/lib/php/php-fpm-socket-helper` ready in the `php-common` package ready as replacement, but the it’s-not-shell hint was very useful anyway. Thank you.

**Comment by oerdnj** [comment]
The Ubuntu packages have been updated.  Debian is still building a previous round and I need it to finish to start icu transition.

**Comment by oerdnj** [comment]
This should have been fixed both for Ubuntu and Debian.

**Comment by leofeyer** [comment]
Yes, it is. Thank you very much @oerdnj.
