### ISSUE TITLE
php 5.6 and 7.2 started to require systemd

### ISSUE THREAD

**Issue by oktayaa** [oerdnj/deb.sury.org#1348]
Debian Strech with systemd gutted. I have no systemd on this box except one process /lib/systemd/systemd-udevd --daemon .

Both php 5.6 and php 7.2 updates worked fine  from your repository until now. Today both seem to try to pull in systemd. Any recommendations?

Please do let me know if the requirement was always there. I might have force installed without and forgot about it.

# aptitude dist-upgrade
The following packages will be upgraded:
  php5.6 php5.6-cli php5.6-common php5.6-curl php5.6-curl-dbgsym php5.6-fpm{b} php5.6-gd php5.6-imap php5.6-intl php5.6-json php5.6-ldap
  php5.6-mbstring php5.6-mysql php5.6-opcache php5.6-readline php5.6-soap php5.6-xml php5.6-zip php7.2 php7.2-cli php7.2-common php7.2-curl
  php7.2-fpm{b} php7.2-gd php7.2-intl php7.2-json php7.2-ldap php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-phpdbg php7.2-readline php7.2-xml
  php7.2-zip
34 packages upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 10.8 MB of archives. After unpacking 0 B will be used.
The following packages have unmet dependencies:
 php7.2-fpm : Depends: systemd but it is not installable
 php5.6-fpm : Depends: systemd but it is not installable
The following actions will resolve these dependencies:

     Remove the following packages:
1)     php5.6-fpm [5.6.40-20+0~20200202.28+debian9~1.gbp8308eb (now)]
2)     php7.2-fpm [7.2.27-5+0~20200202.35+debian9~1.gbp2925f8 (now)]

     Install the following packages:
3)     php5.6-cgi [5.6.40-22+0~20200220.29+debian9~1.gbpb0fe8a (<NULL>)]
4)     php7.2-cgi [7.2.28-1+0~20200220.36+debian9~1.gbpcf4a75 (<NULL>)]

Accept this solution? [Y/n/q/?] ^C

**Comment by oktayaa** [comment]
I found this post on patreon

"This means that phpX.Y-fpm package now depends on systemd package. This should not affect your defaut /sbin/init in any way (those would be systemd-sysv and sysvinit-core packages). I have also removed now obsolete support for upstart from the packaging and init scripts."

Does this mean I can go ahead and have it install systemd without messing with the way my box is currently set up?

**Comment by oktayaa** [comment]
I do get the following when I try to install systemd alone.

root@virt01:/etc/apt/sources.list.d# apt install systemd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package systemd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  udev systemd-journal-remote systemd-coredump systemd-container libnss-resolve libnss-mymachines libnss-myhostname libsystemd-dev systemd-bootchart
  ifupdown

E: Package 'systemd' has no installation candidate
root@virt01:/etc/apt/sources.list.d#

**Comment by xwni** [comment]
Yep, Sury (bless'im he's been so helpful so far) has made a bad and poorly thought out change.. but it seems he's being an asshole about it and has introduced breakage for everyone who has the sense not to use systemd.  :/     grr.

**Comment by oerdnj** [comment]
@xwni welcome to my blocklist

**Comment by oerdnj** [comment]
Duplicate of #1347 and #1343

**Comment by oktayaa** [comment]
@oerdnj Thanks. The info I need is in #1347
