### ISSUE TITLE
php 7 dependency problem

### ISSUE THREAD

**Issue by adrianmihalko** [oerdnj/deb.sury.org#135]
Dear Ondrej,

I got this error:

```
@ubuntu:~$ sudo apt-get install php7.0
[sudo] password for madrian: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0 : Depends: libapache2-mod-php7.0 (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going to be installed or
                   php7.0-cgi (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going to be installed or
                   php7.0-fpm (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going to be installed
          Depends: php7.0-common (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by oerdnj** [comment]
What does `apt-get install php7.0-common php7.0-cli` says? 

O. 

On October 28, 2015 8:51:39 PM GMT+01:00, adrianmihalko <notifications@github.com> wrote:
>Dear Ondrej,
>
>I got this error:
>
>```
>@ubuntu:~$ sudo apt-get install php7.0
>[sudo] password for madrian: 
>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>Some packages could not be installed. This may mean that you have
>requested an impossible situation or if you are using the unstable
>distribution that some required packages have not yet been created
>or been moved out of Incoming.
>The following information may help to resolve the situation:
>
>The following packages have unmet dependencies:
>php7.0 : Depends: libapache2-mod-php7.0 (>=
>7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going to be installed
>or
>php7.0-cgi (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going
>to be installed or
>php7.0-fpm (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it is not going
>to be installed
>Depends: php7.0-common (>= 7.0.0~rc5-6+deb.sury.org~trusty+1~) but it
>is not going to be installed
>E: Unable to correct problems, you have held broken packages.
>
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/135

-- 
Ondřej Surý

**Comment by oerdnj** [comment]
Not enough information from OP, closing.
