### ISSUE TITLE
Rebuild libxml2 with libicu65

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1350]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
`libxml2` currently depends on `libicu64` while the `icu 65.1` is the latest version in the PPA.

**Describe the solution you'd like**
Rebuild `libxml2` with `libicu65` as dependency

**Describe alternatives you've considered**
Install both `libicu64` and `libicu65`

**Distribution (please complete the following information):**
 - OS: ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
```
> apt-cache policy libxml2
libxml2:
  Installed: 2.9.4+dfsg1-6.1ubuntu1.3
  Candidate: 2.9.9+dfsg-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
     2.9.9+dfsg-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
 *** 2.9.4+dfsg1-6.1ubuntu1.3 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.4+dfsg1-6.1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages

> apt-cache depends libxml2
libxml2
  Depends: libc6
  Depends: libicu64
  Depends: liblzma5
  Depends: zlib1g
```
**Additional context**
N/A

**Comment by oerdnj** [comment]
Yes, thanks for reminder, I was waiting for new icu to be built and the life got into a way. I’ll upload new libxml2 shortly.

**Comment by oerdnj** [comment]
Just uploaded 2.9.10, it should be built in couple of minutes...
