### ISSUE TITLE
Build apache2 packages in ppa against 19.10 (eaon)

### ISSUE THREAD

**Issue by areis422** [oerdnj/deb.sury.org#1353]
**Frequently asked questions**

- [ X ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
Availability of packages in apache2, nginx, nginx-mainline, php PPA repos for use on Ubuntu 19.10 (Eaon)

**Distribution (please complete the following information):**
 - OS: Ubuntu 19.10
 - Architecture: amd64
 - Repository: packages.sury.org (ppa:ondrej/apache2)

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
N/A

**Additional context**
running: `apt-add-repository ppa:ondrej/apache2` results in 404s on next `apt update`. Launchpad shows no packages built against 19.10 (eaon)

**Comment by Ayesh** [comment]
Ubuntu 19.10 comes with apache2 version 2.4.41, which is the latest version available in the `ondrej/apache2` PPA too. So using apache2 package from the distro wouldn't make much of a difference either. 

Apache v2.4.43 is now released, which will be available in Ubuntu 20.04. Hopefully we can get that version in this PPA soon too. Thank you.

**Comment by oerdnj** [comment]
That coincidentally happened with recent apache2 update: https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+packages?field.name_filter=&field.status_filter=published&field.series_filter=eoan
