### ISSUE TITLE
PHP 7.3 upgrade failed on Devuan Ascii

### ISSUE THREAD

**Issue by alex9434** [oerdnj/deb.sury.org#1354]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Updated with apt-get update & apt-get dist-upgrade on Devuan Ascii. System is now unusable because php7.3-fpm failed to install with the following error:
```
dpkg: php7.3-fpm: dependency problems, but removing anyway as you requested:
 php7.3 depends on libapache2-mod-php7.3 | php7.3-fpm | php7.3-cgi; however:
  Package libapache2-mod-php7.3 is not configured yet.
  Package php7.3-fpm is to be removed.
  Package php7.3-cgi is not installed.
```
When I tried to install php7.3-fpm I get the following message:
```
The following packages have unmet dependencies:
php7.3-fpm : Depends: systemd but it is not installable
```

**To Reproduce**
1. apt-get install php7.3-fpm on Devuan Ascii 

**Expected behavior**
Install on Devuan Ascii with init.d startfile

**Distribution (please complete the following information):**
 - OS: Devuan
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php7.3-fpm:
  Installed: (none)
  Candidate: 7.3.15-4+0~20200224.55+debian9~1.gbpbea824
  Version table:
     7.3.15-4+0~20200224.55+debian9~1.gbpbea824 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
     7.3.14-5+0~20200202.52+debian9~1.gbpa71879 -1
        100 /var/lib/dpkg/status

**Additional context**
Devuan is a Debian derivate that does not use systemd. It also has no systemd package in the repository. Removing the dependency on systemd from the control file makes it possible to install and run the package without any problems.

Could you be so kind as to remove the dependency on systemd from the package so that the update on Devuan does not break? The dependency must be new because I did not have the issue earlier.

I also noted that /etc/init.d/php7.3-fpm changed and now has a dependency on systemd. Could you be so kind as to revert back to the old one that does not has this dependency?

**Comment by oerdnj** [comment]
You haven’t read the FAQ, closing.

**Comment by alex9434** [comment]
I have actually read the FAQ. However, I cannot install systemd on Devuan (as suggested in your FAQ)
```
dpkg: dependency problems prevent configuration of systemd:
 sysv-rc (2.88dsf-59.9+devuan2) breaks systemd (<< 215) and is installed.
  Version of systemd to be configured is 0.2+2019.05.21.git.44a55796ba-2.
 sysvinit-utils (2.88dsf-59.9+devuan2) breaks systemd (<< 215) and is installed.
  Version of systemd to be configured is 0.2+2019.05.21.git.44a55796ba-2.
 init-system-helpers (1.48+devuan2.0) breaks systemd (<< 44-12) and is installed.
  Version of systemd to be configured is 0.2+2019.05.21.git.44a55796ba-2.
 ifupdown (0.8.19) breaks systemd (<< 228-3~) and is installed.
  Version of systemd to be configured is 0.2+2019.05.21.git.44a55796ba-2.
```
I was able to install and use your php7.3-fpm before on Devuan Ascii without any problems. Why did you decide to introduce the systemd dependency, that was not there a few weeks ago? The old init.d file without the systemd dependency still works without any problems. Any chance you can go back to that version?

**Comment by elctoo** [comment]
The single line that uses systemd-tmpfiles can be replaced with
`install --directory --owner=www-data --group=www-data --mode=0755 /run/php`

The install program is part of coreutils package so is on everything.

Requiring all of systemd just to make a directory is excessive. Production systems shouldn't have packages installed on them which aren't used.

Attached is equivs package systemd-dummy to replace systemd-tmpfiles with a single line call to install. Not used by anything else so just does the /run/php directory each time. gunzip it to use it with `dpkg -i systemd-dummy_1.0_all.deb`
[systemd-dummy_1.0_all.deb.gz](https://github.com/oerdnj/deb.sury.org/files/4317374/systemd-dummy_1.0_all.deb.gz)


Here's the control file used to build it:
<pre>
Section: misc
Priority: optional
Standards-Version: 3.9.2

Package: systemd-dummy
Version: 1.0
Maintainer: user <user@devuan>
Provides: systemd,systemd-tmpfiles
File: /usr/bin/systemd-tmpfiles 755
 #!/bin/sh
 # Dud replacement of systemd-tmpfiles. If you want something functional,
 # delete this file and symlink opentmpfiles in its place. This is a stopgap
 # to get what phpX.Y-fpm desires which is creating a directory owned by
 # www-data. Do the same with already installed coreutils programs.
 install --directory --owner=www-data --group=www-data --mode=0755 /run/php
 exit 0
Description: Mitigate systemd requirement of phpX.Y-fpm.
 Package phpX-Y-fpm now requires systemd to make a directory during startup.
 Do the same using already installed install program from coreutis.
</pre>
