### ISSUE TITLE
Cannot load the memcache module anymore, php 5.6

### ISSUE THREAD

**Issue by Arbakkinn** [oerdnj/deb.sury.org#1355]
On a recent installation of Debian 9, I cannot load the memcache module anymore:

System
```
$ sudo lsb_release -sir
Debian
9.12
```

PHP version
```
5.6.40
```
php-memcache version
```
$ apt-cache policy php-memcache
php-memcache:
  Installed: 4.0.5.2+3.0.8-1+0~20200302.13+debian9~1.gbp4747c4
  Candidate: 4.0.5.2+3.0.8-1+0~20200302.13+debian9~1.gbp4747c4
  Version table:
 *** 4.0.5.2+3.0.8-1+0~20200302.13+debian9~1.gbp4747c4 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.9~20160311.4991c2f-5 500
        500 http://cdn-aws.deb.debian.org/debian stretch/main amd64 Packages
```

Listing the enabled module of my php installation produce the following error:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcache.so' - /usr/lib/php/20131226/memcache.so: undefined symbol: mmc_queue_remove in Unknown on line 0
```

I used the exact same step of installation several weeks ago without any issue, the error appeared today as I recreated my environment, so I'm not sure if the issue is very very recent or no. But I can see that the package was updated today at 02-Mar-2020 14:24 : https://packages.sury.org/php/pool/main/p/php-memcache/

**Comment by oekelly** [comment]
+1

Updated to 4.0.5.2+3.0.8-1+ubuntu16.04.1+deb.sury.org+1 last night:

`/var/log/dpkg.log:2020-03-02 20:19:36 upgrade php-memcache:amd64 3.0.9~20170802.e702b5f-3+ubuntu16.04.1+deb.sury.org+20191129 4.0.5.2+3.0.8-1+ubuntu16.04.1+deb.sury.org+1`

And am now seeing the same error on PHP 5.6:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcache.so' - /usr/lib/php/20131226/memcache.so: undefined symbol: mmc_queue_remove in Unknown on line 0`

I can't test PHP 7.0+ at the moment sorry, as this particular code only works successfully in PHP 5.6. I can confirm PHP 5.6 is also from this rpo thought:

`php5.6-common 5.6.40-24+ubuntu16.04.1+deb.sury.org+1`

**Comment by todeveni** [comment]
A possible reason for breakage from memcache changelog:
` - Support for PHP 5.x has been removed, please use memcache extension ver. 3.x`

**Comment by oerdnj** [comment]
I took the last official memcache release for PHP 5.6 and it's broken. I'll be reuploading the 3.0.9 from git for PHP 5.6 shortly.
