### ISSUE TITLE
PHP 7.4 SOAP request segfaults when any parameter is omitted

### ISSUE THREAD

**Issue by rovanicek** [oerdnj/deb.sury.org#1356]
PHP 7.4 builds provided by your repository (all the dot versions up to 7.4.3) crash with segfault when making SOAP requests with any parameter of SOAP function omitted instead of throwing an exception.

Your PHP 7.3 builds work fine and also PHP 7.4.3 build made from the sources myself on Ubuntu 18.04 LTS work fine.

The atteched file is a testing script against a very simple public SOAP service (calculator).
[calc.zip](https://github.com/oerdnj/deb.sury.org/files/4292331/calc.zip)

**Comment by rovanicek** [comment]
Update: I have found that this is not a build/packaging issue. It is probably a bug in the PHP SOAP module itself (but it happens in shared soap module only, not in a static build). I have reported this bug on the bugs.php.net. Thank you.

**Comment by oerdnj** [comment]
Thanks for the update. Feel free to share the exact link here, so people have the pointer to upstream bugzilla if they encounter the same problem.

**Comment by rovanicek** [comment]
Update: I have found that this is not a build/packaging issue. It is probably a bug in the PHP SOAP module itself (but it happens in shared soap module only, not in a static build). I have reported this bug on the bugs.php.net (https://bugs.php.net/bug.php?id=79357). Thank you.
