### ISSUE TITLE
php-gearman for php 7.4

### ISSUE THREAD

**Issue by bigwillystyle42** [oerdnj/deb.sury.org#1357]
The php-gearman package in your repository does not appear to work against php7.4. It depends on the api versions for all the previous php versions, but not 7.4. Is that just a matter of re-packaging it? I see a 7.4 compatible version was uploaded to the official Debian repositories a few weeks ago.

**Comment by oerdnj** [comment]
Which repository? There are at least two. You know, the issue template is there for a reason. Sure, I can go looking, but you already have the information.

**Comment by bigwillystyle42** [comment]
Sorry, I wasn't sure how best to classify my question, so I went with a blank bug.

The deb file here: https://packages.sury.org/php/pool/main/p/php-gearman/ for Debian 9 does not support php 7.4. The deb file here for Debian 11 does support php 7.4: https://packages.debian.org/bullseye/php-gearman

**Comment by oerdnj** [comment]
Much better, appreciated. I now issued a rebuild, so check in hour if that helps.

**Comment by bigwillystyle42** [comment]
I've installed the updated packages on our php 7.4 dev servers, they look to be working as expected. Thanks
