### ISSUE TITLE
 Hash Sum mismatch:  Proxy cache propagation broken? 

### ISSUE THREAD

**Issue by SchizoDuckie** [oerdnj/deb.sury.org#1359]
I'm trying to install php7.2 extension packages the ppa and i've been having hash sum mismatch problems that haven't disappeared since I started to try to setup a new box about 3 hours ago:

![image](https://user-images.githubusercontent.com/111710/76772647-8e1ecc00-67a1-11ea-9866-313ad3f02ee6.png)

What's the general timeframe for the cache to completely flush?

Looking into setting up our own deb mirror now to see if that can mitigate this for the future.

**Comment by oerdnj** [comment]
I purged the cache manually, there's 1w period for metadata and max period for packages.

**Comment by SchizoDuckie** [comment]
Thanks! Love you long time! <3

**Comment by oerdnj** [comment]
The cache flush is triggered only after the sync is completed, so it’s a push event, and generally the manual cache flush should not be needed at all. But perhaps there was some expiry race or something.

**Comment by SchizoDuckie** [comment]
That definitely helped. Only one mismatch left:
![image](https://user-images.githubusercontent.com/111710/76795588-dd78f280-67c9-11ea-86d1-e70b45d71691.png)
