### ISSUE TITLE
Hash sum mismatch (again), also on rsync'd mirror?

### ISSUE THREAD

**Issue by SchizoDuckie** [oerdnj/deb.sury.org#1361]
Hello,

I have been trying to get a grip on my reported issue #1359 all week.

To prevent this from happening in our infrastructure i've set up our own deb mirror using rsync after figuring out how to build one without taking down your servers or exploding your bandwidth costs.

This has worked nicely. Unfortunately, the problem persists there too, which means...  I think.. That your original source has the same problems and my idea to bypass the http cache headers via rsync is not sufficient?? 

![image](https://user-images.githubusercontent.com/111710/77177192-68593600-6ac5-11ea-912c-083612940366.png)

**Comment by oerdnj** [comment]
This looks like your local problem, and not the problem on the mirror:
```
$ rsync rsync://rsync.rfc1925.org/repositories/php/pool/main/p/php7.2/php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb ./
$ sha256sum php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb
c0e9c3abba4b2593cba559930859206e277015ca9fef3b2d6dda31abc4d9ccf6  php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb
```

**Comment by oerdnj** [comment]
Also the installation works fine:
```
# rm /var/cache/apt/archives/php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb
# dpkg --purge php7.2-cli
(Reading database ... 193816 files and directories currently installed.)
Removing php7.2-cli (7.2.28-4+0~20200224.38+debian10~1.gbp1ca010) ...
Purging configuration files for php7.2-cli (7.2.28-4+0~20200224.38+debian10~1.gbp1ca010) ...
Processing triggers for man-db (2.8.5-2) ...
# apt-get install php7.2-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libicu64 php5.6-cli php5.6-common php5.6-dev php5.6-json php5.6-opcache php5.6-readline php7.0-cli php7.0-common php7.0-dev php7.0-json php7.0-opcache php7.0-readline php7.1-cli php7.1-common
  php7.1-dev php7.1-json php7.1-opcache php7.1-readline php7.3-cli php7.3-common php7.3-dev php7.3-json php7.3-opcache php7.3-readline php7.4-dev python-yaml shtool
Use 'apt autoremove' to remove them.
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php7.2-cli
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 1,447 kB of archives.
After this operation, 5,074 kB of additional disk space will be used.
Get:1 https://packages.sury.org/php buster/main amd64 php7.2-cli amd64 7.2.28-4+0~20200224.38+debian10~1.gbp1ca010 [1,447 kB]
Fetched 1,447 kB in 0s (7,635 kB/s)
Selecting previously unselected package php7.2-cli.
(Reading database ... 193803 files and directories currently installed.)
Preparing to unpack .../php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb ...
Unpacking php7.2-cli (7.2.28-4+0~20200224.38+debian10~1.gbp1ca010) ...
Setting up php7.2-cli (7.2.28-4+0~20200224.38+debian10~1.gbp1ca010) ...

Creating config file /etc/php/7.2/cli/php.ini with new version
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for php7.2-cli (7.2.28-4+0~20200224.38+debian10~1.gbp1ca010) ...
# sha256sum /var/cache/apt/archives/php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb
c0e9c3abba4b2593cba559930859206e277015ca9fef3b2d6dda31abc4d9ccf6  /var/cache/apt/archives/php7.2-cli_7.2.28-4+0~20200224.38+debian10~1.gbp1ca010_amd64.deb
```

My guess is that you have faulty harddrive.

**Comment by SchizoDuckie** [comment]
Oof. That wasn't something that was even on my mind.
I will get a new drive and see if that changes anything. Thanks for your continued support.

**Comment by oerdnj** [comment]
Or corrupted file system...

**Comment by SchizoDuckie** [comment]
But still, It makes no sense, It happens only on sury packages. I have
reinstalled and downloaded full OS images in the meantime, downloaded all
other packages for my installations over and over with no problems.

>

**Comment by SchizoDuckie** [comment]
I did order a new ssd to make sure that's not part of the problem.

**Comment by oerdnj** [comment]
I actually don’t know what’s the problem on your side, but I am sure it’s not the mirror here for the packages listed. I’ve seen all kinds of weird stuff in my life including failed backups because the tar.gz contained a specific bit sequence that an optical receiver was unable to transmit/receive. (And if you pulled the cable just a little bit it fixed the problem...)

**Comment by SchizoDuckie** [comment]
Yeah i've been around too. I've seen cpu usage spike to 100% when a desk was moved 2mm off of a network cable... 

I'll try to work to the source of problem by excluding moving (or static) parts bit by bit as is always the one and only solution. I also would have expected shit to have really hit the fan on your side if there were many more people with just this problem. Thanks again for your insights.
