### ISSUE TITLE
armhf package is missing for php-memcached 3.1.5

### ISSUE THREAD

**Issue by h1618** [oerdnj/deb.sury.org#1362]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions) yes

**Describe the bug**
apt show -a php-memcached only shows me 3.1.3 that doesn't work with php7.4 on my sunxi device, and without it nextcloud throws 500 error

**To Reproduce**
1. upgrade to php7.4
2. remove php7.3
3. try to install php-memcached for php7.4
4. None offered by packages.sury.org

**Expected behavior**
php-memcached 3.1.5 is offered

**Distribution (please complete the following information):**
 - OS: Armbian
 - Architecture: armhf
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
php-memcached:
  Installiert:           (keine)
  Installationskandidat: 3.1.3+2.2.0-2+0~20191128.16+debian10~1.gbp5d60d1
  Versionstabelle:
     3.1.3+2.2.0-2+0~20191128.16+debian10~1.gbp5d60d1 500
        500 https://packages.sury.org/php buster/main armhf Packages
     3.1.3+2.2.0-1 500
        500 http://httpredir.debian.org/debian buster/main armhf Packages

**Additional context**
in the php-memcached pool directory I see many php-memcached_3.1.5+2.2.0-1+0~20200302.17+debian8~1.gbpb3c6fc packages, namely amd64 and arm64, but no armhf

**Comment by oerdnj** [comment]
For some reason the non-amd64 builds failed the last time: https://jenkins.rfc1925.org/view/PHP/job/php_php-memcached-binaries/20/

I’ve issued a rebuild now, it will be in the queue for some time because the main PHP packages are building now.
