### ISSUE TITLE
Dockerfile php:7.4.3-apache - No installation candidate

### ISSUE THREAD

**Issue by krajcikondra** [oerdnj/deb.sury.org#1363]
Hi,

I have dockerfile based on php:7.4.3-apache (Debian 10) and I am trying to install php7.4-cgi but I get ever following error

```
root@eafa0aac715a:/var/www/html# apt-get install php7.4-cgi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php7.4-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php7.4-cgi' has no installation candidate
```

Here is my dockerfile for demonstrate issue
```
FROM php:7.4.3-apache

RUN apt-get -y install apt-transport-https lsb-release ca-certificates curl
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update
RUN apt install php7.4-cgi
```

What am I doing bad?

**Comment by oerdnj** [comment]
I don't know, you need to do debugging on your side first. If you have actually used the issue template for bug report you would see:

> Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

**Comment by mattford** [comment]
For anyone who happens on this in the future, the `php` docker images pin all `php*` packages to `-1` i.e., not installable, you can resolve this error by removing `/etc/apt/preferences.d/no-debian-php`
