### ISSUE TITLE
php7.4-mbstring has broken dependency on libonig4

### ISSUE THREAD

**Issue by spiffin** [oerdnj/deb.sury.org#1364]
When trying to install php7.4-mbstring:

php7.4-mbstring : Depends: libonig4 (>= 5.9.5) but it is not installable

**Comment by oerdnj** [comment]
Please use the issue template when filling bug. This problem contains literally zero information I can work with.

**Comment by guillaumeperes** [comment]
Hi @spiffin I just got the same problem.

If you run PHP on Debian 10 Buster, you have to check that the content of the file `/etc/apt/sources.list.d/php.list` is  `deb https://packages.sury.org/php/ buster main`

You have probably upgraded your debian distribution and this file is no longer up to date.

**Comment by trombipeti** [comment]
I didn't want to open a new issue, but maybe I can provide more information from my side:

We have a server with Debian GNU/Linux 9.6 (stretch), and can't install php7.4-mbstring:

```
$ lsb_release -d
Description:	Debian GNU/Linux 9.6 (stretch)
$ uname -r
4.9.0-6-amd64
$ cat /etc/apt/sources.list.d/php.list 
deb https://packages.sury.org/php/ stretch main
$ sudo apt update
...
$ LANG=C sudo apt install php7.4-mbstring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.4-mbstring : Depends: libonig4 (>= 5.9.5) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Does this provide enough info for you? If not, then please tell me what else you need.

**Comment by oerdnj** [comment]
You system is broken. The libonig4 is available from stretch: https://packages.debian.org/search?keywords=libonig4

**Comment by trombipeti** [comment]
You are right, the sysadmin didn't upgrade the server for idk how long. Now it works fine.

**Comment by surajk63** [comment]
> Your system is broken. The libonig4 is available from stretch: https://packages.debian.org/search?keywords=libonig4

If you follow this, then it is resolved.

Thank you

I had the same issue, when the php was upgraded from 7.4.7 to 7.4.8 in debian 10 buster.

**Comment by czesio** [comment]
I've had related problem, Maybe somebody will need solution anyway:
`wget http://archive.ubuntu.com/ubuntu/pool/universe/libo/libonig/libonig4_6.7.0-1_amd64.deb
sudo dpkg -i libonig4_6.7.0-1_amd64.deb
sudo apt-get install php7.4-mbstring`

**Comment by ersanjay5991** [comment]
@czesio   thanks for your solution. I am still getting error.

`sudo apt-get install php7.4-mbstring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.4-mbstring : Depends: libonig5 (>= 6.8.1) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by henningsieh** [comment]
Yup, same here... the third command fails (german, but same!).

`root@myserver:~# sudo apt-get install php7.4-mbstring
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 php7.4-mbstring : Hängt ab von: libonig5 (>= 6.8.1) ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.`

**Comment by henningsieh** [comment]
> 



> The following packages have unmet dependencies:
> php7.4-mbstring : Depends: libonig5 (>= 6.8.1) but it is not installable
> E: Unable to correct problems, you have held broken packages.`

Te following lines did it for me:

sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"

sudo apt-get update #to update my system
