### ISSUE TITLE
Package 404 Not Found

### ISSUE THREAD

**Issue by WestNab** [oerdnj/deb.sury.org#1366]
I am attempting to install LAMP on Deepin Linux, running on a MacBook. My web site is down because of a hardware failure on my old web server (running from home using DDNS). I searched and found your web site because Deepin doesn't seem to have a source listed for PHP. I read https://packages.sury.org/php/README.txt and copied the 4 commands into Deepin manually. The first issue was with the 3rd command, which failed with:
bash: /etc/apt/sources.list.d/php.list: Permission denied
rather a stab in the dark - I repeated the command with 'sudo' after the redirection and lo! It appeared to work. However, then running 'sudo apt-get update' gave:
Failed to fetch https://packages.sury.org/php/dists/stable/main/binary-amd64/Packages 404 Not Found
Admittedly I am in deeper than my limited knowledge. What have I done wrong, or is there an error in the package?

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#supported-distributions
