### ISSUE TITLE
Support HEIC in Imagick

### ISSUE THREAD

**Issue by RikudouSage** [oerdnj/deb.sury.org#1367]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Cannot work with HEIC images in Imagick

**Describe the solution you'd like**
Include Imagick (and ImageMagick) with heic support

**Describe alternatives you've considered**
Currently I need to compile them myself.

**Distribution (please complete the following information):**
 - OS: Ubuntu 16.04, Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php-imagick

**Comment by SoftCreatR** [comment]
HEIC support depends on ImageMagick, not Imagick.

**Comment by RikudouSage** [comment]
That's why I wrote this: Include Imagick (and ImageMagick) with heic support

**Comment by loeffelpan** [comment]
I would love to see HEIC-support as well.
For my own compile I‘m stucked with this tutorial:
https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

Uncommenting the „deb-src“ repos result in some errors while updating package-lists.

**Comment by SoftCreatR** [comment]
Try this: https://github.com/SoftCreatR/imei

**Comment by loeffelpan** [comment]
Thanks a lot.
Compiling finished with that script.
After that I followed the last steps of above tutorial. And got working HEIC support.

**Comment by oerdnj** [comment]
ImageMagick is undermaintained in Debian and I don't have enough resources to help with ImageMagick packaging, it's too complex to have it as a side-project, so I am just closing this issue.  Once ImageMagick 7 is packaged, I might backport it, but I am not going to do the packaging myself.
