### ISSUE TITLE
Unable to install php7.3-zip in Ubuntu 19.04 (disco)

### ISSUE THREAD

**Issue by arborrow** [oerdnj/deb.sury.org#1370]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
apt install php7.3-zip 
produces: E: Unable to locate package php7.3-zip

I am currently using PHP 7.2 and everything works on an Ubuntu 19.04 install running via Linode.

The software package (CiviCRM) I am using recommends 7.3 but I am unable to get the zip extension to install for 7.3.

I read https://www.digitalocean.com/community/questions/unable-to-install-php7-3-zip and reviewed my sources.list. 
ondrej-ubuntu-php-disco.list

**To Reproduce**
1. On Ubuntu 19.04 (disco) add the repository and then try to run apt install php7.3-zip
2. See error that it cannot find the package

**Expected behavior**
I would expect the php7.3-zip package to be installed on Ubuntu (disco) - it works for 7.2.

**Distribution (please complete the following information):**
 - OS:  Ubuntu
 - Architecture: from lshw - AMD EPYC 7501 32-Core Processor
 - Repository: ondrej-ubuntu-php-disco.list
 http://ppa.launchpad.net/ondrej/php/ubuntu disco InRelease 

**Package(s) (please complete the following information):**
n/a - cannot install php7.3-zip package

**Comment by todeveni** [comment]
Did you really read FAQ? 19.04 is unsupported since january when it hit end of life.

https://www.patreon.com/posts/january-round-of-33387816

**Comment by arborrow** [comment]
Yes, I did read https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions but hadn't considered or realized that 19.04 already reached EOL. I failed to follow the link to https://wiki.ubuntu.com/Releases - mea culpa.
