### ISSUE TITLE
You cannot start a Redis session with php7.2-fpm

### ISSUE THREAD

**Issue by schieffahrer** [oerdnj/deb.sury.org#1372]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
You cannot start a Redis session with php7.2-fpm.

**To Reproduce**
1. Create a script:
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://127.0.0.1:6379?auth=foobar');
session_start();
$count = isset($_SESSION['count']) ? $_SESSION['count'] : 1;
echo $count;
$_SESSION['count'] = ++$count;

2. Load the website and reload it several times. The counter should always increase by one.
3. See error in Apachelog: AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: redis 

**Expected behavior**
A problem-free session handling with redis.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
# LC_ALL=C.UTF-8 apt-cache policy php-redis
php-redis:
  Installed: 5.2.1+4.3.0-1+0~20200321.20+debian9~1.gbp9fe0ce
  Candidate: 5.2.1+4.3.0-1+0~20200321.20+debian9~1.gbp9fe0ce
  Version table:
 *** 5.2.1+4.3.0-1+0~20200321.20+debian9~1.gbp9fe0ce 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.1-1 500
        500 http://ftp.de.debian.org/debian stretch/main amd64 Packages

**Additional context**
In the other PHP versions there is no problem.

**Comment by MatthiasKuehneEllerhold** [comment]
Is it the same bug as https://github.com/phpredis/phpredis/issues/1626?

**Comment by schieffahrer** [comment]
No, the problem is not the same. There the problem was solved by specifying the port. This does not work here.

**Comment by oerdnj** [comment]
You need to report the problem with Redis. This is not a problem with packaging.
