### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by fulldecent** [oerdnj/deb.sury.org#1375]
This is how I found out about this project.

https://www.cloudbooklet.com/upgrade-php-version-to-php-7-4-on-ubuntu/

You may consider to steal this documentation and host on your site

**Comment by oerdnj** [comment]
> You may consider to steal

No, I might not consider to *steal* anything.  People can contribute as much documentation they have IP rights to into the wiki, but I can't possible take other people's work and host it on my site.

**Comment by fulldecent** [comment]
Got it, found docs in wiki, added there
