### ISSUE TITLE
Release PHP 7.4.5, 7.3.17, 7.2.30 Debian and Ubuntu

### ISSUE THREAD

**Issue by BrookeDot** [oerdnj/deb.sury.org#1376]
- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

Opening this to track builds of the latest PHP versions released on April 16th and 17th. 
 [7.4.5](https://www.php.net/archive/2020.php#2020-04-16-2), [7.3.17](https://www.php.net/archive/2020.php#2020-04-16-1), [7.2.30](https://www.php.net/archive/2020.php#2020-04-17-1). For 7.4 and 7.3 this release includes bug fixes and security; for 7.2 this is solely a security release.

Note, I am currently only using PHP 7.4. However, I have checked [jenkins](https://jenkins.rfc1925.org/view/PHP/) and did not find builds for the other releases either.

**Describe the solution you'd like**
Updated packages in the PPA and at `packages.sury.org`

**Distribution:**

**Ubuntu (18.04 LTS)**
 - OS: `lsb_release -a` 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
 - Architecture: amd64
```
$ uname -a
Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Repository: `http://ppa.launchpad.net/ondrej/php/ubuntu bionic main`
- Package(s):
```
$ apt-cache policy php7.4-common
php7.4-common:
  Installed: 7.4.4-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.4.4-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.4.4-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Debian (buster)**

 - OS: `lsb_release -a` 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
 - Architecture: amd64
```
$ uname -a
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

```
 - Repository: `deb https://packages.sury.org/php/ buster main`
- Package(s):
```
$ apt-cache policy php7.4-common
php7.4-common:
  Installed: 7.4.4-1+0~20200320.15+debian10~1.gbpf8dc20
  Candidate: 7.4.4-1+0~20200320.15+debian10~1.gbpf8dc20
  Version table:
 *** 7.4.4-1+0~20200320.15+debian10~1.gbpf8dc20 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Uploaded and building.

**Comment by oerdnj** [comment]
Done

**Comment by iget-esoares** [comment]
@oerdnj could you please explain me why the latest releases (patches) of 7.4 is not on official ubuntu repository? The last available version there is 7.4.3

**Comment by BrookeDot** [comment]
@iget-esoares What version of Ubuntu? I would recommend you could open a new issue using the template. I'm running 7.4.6 on Ubuntu 18.04.4. You can see from the output above that in April I was successfully running `7.4.4-1+ubuntu18.04.1+deb.sury.org+1` so something must be up with your specific install.

**Comment by iget-esoares** [comment]
Ubuntu 20.04 lts, at official repository. See:

https://packages.ubuntu.com/focal/php7.4

I didn't opened a issue because is not related to ondrej repo, but maybe he can help/explain me.

**Comment by oerdnj** [comment]
This is off topic, but here’s a link: https://wiki.ubuntu.com/StableReleaseUpdates

**Comment by iget-esoares** [comment]
That's what I was looking for. Thanks and sorry for the off topic.

Best regards

Em qua, 27 de mai de 2020 00:31, Ondřej Surý <notifications@github.com>
escreveu:
