### ISSUE TITLE
Fix for #76601

### ISSUE THREAD

**Issue by luborj** [oerdnj/deb.sury.org#1379]
Hello Ondřej,

in PHP 7.1 is nasty bug [#76601](https://bugs.php.net/bug.php?id=76601), which have been solved in PHP 7.2 with this commit https://github.com/php/php-src/pull/4461/commits/3eb15725dfda7412b624465b371b5d4f1fefd348 .

I merged this commit into my build based on your repository and it works very well.
Could you add this fix into your repository?

**Comment by oerdnj** [comment]
I have pulled the patch to PHP 7.0 and PHP 7.1 packages. Thanks for pointing this out.

It will be released in the next month round of updates.

**Comment by oerdnj** [comment]
Fixed packages uploaded and building.
