### ISSUE TITLE
libapache2-mod-php5filter doesn't return responce bodies

### ISSUE THREAD

**Issue by AnrDaemon** [oerdnj/deb.sury.org#138]
I've been trying to upgrade my test system to see how it behave under new Apache/PHP, but to my surprize it wasn't working at all.
After much fiddling, I had to conclude that the issue is in php5filter Apache module or around it. The applications will start, process input, but only headers would be returned properly - no body content being sent at all.

**Comment by oerdnj** [comment]
apache2filter has been deprecated in PHP 7.0, and I am dropping the package in the new PHP 5.6 packages. So please just use standard libapache2-mod-php5 or even better php5-fpm.

**Comment by AnrDaemon** [comment]
Your "standard" module is based on ancient Apache 1.x "handler" API which I'm surprised it is still supported by Apache.
Neither it, not FPM let me chain multiple page filters.
