### ISSUE TITLE
libcurl4 and php-curl

### ISSUE THREAD

**Issue by mkasimd** [oerdnj/deb.sury.org#1381]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Description:**
`php-*-curl` packages depend on `libcurl3` whereas `curl` (on cli) depends on libcurl4. Thus, one cannot install both at the same time.

Also see #831 ([libcurl4 and php7.2-curl](https://github.com/oerdnj/deb.sury.org/issues/831)). It's basically the same issue as back then.

**Expected behavio:r**
To be able to install both packages without dependency conflicts.

**Distribution:**
 - OS: Debian stretch
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
```
php:
  Installed: 2:7.4+75+0~20200327.22+debian9~1.gbp7ccdd5
  Candidate: 2:7.4+75+0~20200327.22+debian9~1.gbp7ccdd5
  Version table:
 *** 2:7.4+75+0~20200327.22+debian9~1.gbp7ccdd5 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
php-curl:
  Installed: (none)
  Candidate: 2:7.4+75+0~20200327.22+debian9~1.gbp7ccdd5
  Version table:
     2:7.4+75+0~20200327.22+debian9~1.gbp7ccdd5 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
php7.4-curl:
  Installed: (none)
  Candidate: 7.4.5-1+0~20200419.16+debian9~1.gbpc40fd0
  Version table:
     7.4.5-1+0~20200419.16+debian9~1.gbpc40fd0 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
curl:
  Installed: 7.68.0-1
  Candidate: 7.68.0-1
  Version table:
 *** 7.68.0-1 100
        100 /var/lib/dpkg/status
```

**Suggestion:**
In the linked issue, you have fixed it by rebuilding the packages. See [here](https://github.com/oerdnj/deb.sury.org/issues/831#issuecomment-374912474).

**Comment by oerdnj** [comment]
There's no `libcurl4` in Debian stretch: https://packages.debian.org/stretch/libcurl4 only libcurl3: https://packages.debian.org/stretch/libcurl3

**Comment by mkasimd** [comment]
Thanks for your response. You are right, and the issue was apparently because of this:

```
libcurl3:
  Installed: (none)
  Candidate: 7.52.1-5+deb9u10
  Version table:
     7.52.1-5+deb9u10 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
     7.52.1-5+deb9u9 500
        500 http://ftp.us.debian.org/debian stretch/main amd64 Packages
libcurl4:
  Installed: 7.68.0-1
  Candidate: 7.68.0-1
  Version table:
 *** 7.68.0-1 500
        500 http://ftp.de.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```
I kept sid uncommented there after having installed a few updates on other applications apparently. Just adding this info in case anybody makes the same mistake as I did 😆
