### ISSUE TITLE
Backport support for numeric IDs in FPM listen.{owner,group}

### ISSUE THREAD

**Issue by andrenth** [oerdnj/deb.sury.org#1383]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

FPM used to allow only user and group names in the `listen.owner` and `listen.group` settings until PHP 7.4.5, despite allowing numeric IDs in the `user` and `group` directives.

Numeric IDs are useful to prevent bringing the FPM daemon down when using some sort of remote authentication (LDAP, MySQL, etc). For example, when creating a new FPM pool assigned to a new user, there will be problems if the pool is created and FPM is reloaded before the account is created in the remote authentication system. FPM will exit during the reload due to the nonexistent user name, while a numeric user ID wouldn't cause the problem.

I've managed to get a PR merged in PHP 7.4.5 which allows numeric IDs in the settings mentioned above.

**Describe the solution you'd like**

I'd like the changes that were merged in PHP 7.4.5 to be backported to other PHP versions supported in the PPA so that they can also support numeric IDs in `listen.owner` and `listen.group`.

**Comment by andrenth** [comment]
In fact I was working on submitting patches to the repository at https://salsa.debian.org/php-team/php but I couldn't find a way to submit a merge request there.

**Comment by oerdnj** [comment]
I would be happy to, could you point me to the upstream patch(es) that I can pull?

**Comment by andrenth** [comment]
Hi

These are the merged patches: https://github.com/php/php-src/commit/0b4e80b8c1462a17ab758e600e2a5ddb39d80c06

There was a later fix to the tests due to path length limits for unix sockets, though I'm not sure how relevant it is for packaging: https://github.com/php/php-src/pull/5336

**Comment by oerdnj** [comment]
Fixed packages uploaded and building.

**Comment by andrenth** [comment]
Thanks!
