### ISSUE TITLE
add-apt-repository ppa:ondrej/php - spelling: advised

### ISSUE THREAD

**Issue by jsoref** [oerdnj/deb.sury.org#1384]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

There's a `d` missing at the end of `advise` in the `3.` point of the `CAVEATS:` list. 

**To Reproduce**
1. Run:
    ```
    add-apt-repository ppa:ondrej/php
    ```

See:
```
CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advise to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx
```

**Expected behavior**
```
3. If you are using nginx, you are advised to add ppa:ondrej/nginx-mainline
```
Note the extra `d` at the end of *advise***d**

**Distribution (please complete the following information):**
 - OS: ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
Fixed, thanks for caring.
