### ISSUE TITLE
Unable to Install PHP 7.3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by apblack96** [oerdnj/deb.sury.org#1385]
**Describe the bug**
Unable to install PHP 7.3 on Ubuntu 20.04

**To Reproduce**
1. Install Ubuntu 20.04 
2. Attempt to install PHP 7.3 
3. See error (PHP 7.3 not found)

**Expected behavior**
The ability to install PHP 7.3 on Ubuntu 20.04
**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: Virtual Machine
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
Our Owncloud server has been upgraded to Ubuntu 20.04 however we are unable to re-install php 7.3 on it only 7.4 which is not compatible with the latest version of owncloud.

**Comment by rocsx** [comment]
The only way I found is compiling it myself. I'm also waiting for that answer. Although right now this solution is giving me a lot of problems

**Comment by oerdnj** [comment]
It was released *yesterday*! Just be patient the packages will come.

**Comment by rickschippers** [comment]
@oerdnj Which versions will become available for 20.04. 7.2 and up?

**Comment by ranrinc** [comment]
@oerdnj hi there, when will 7.2 available for ubuntu 20.04. Hope to have it available soon. Thank you for all the good work

**Comment by oerdnj** [comment]
> @oerdnj hi there, when will 7.2 available for ubuntu 20.04. Hope to have it available soon. Thank you for all the good work

https://github.com/oerdnj/deb.sury.org/issues/1385#issuecomment-618789612

**Comment by higuerrero** [comment]
Hello @oerdnj , any news about this?  I tried to install php7.3, the repository was added, but the php7.3 is not avalible.

**Comment by AnrDaemon** [comment]
Guys, have some brain?
https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=focal

Do you see any binary packages available? No? Just sit back and wait.

**Comment by oerdnj** [comment]
@AnrDaemon Please don't be rude to people.

**Comment by ranrinc** [comment]
@oerdnj Thank you for the update.. can't wait to be able to used 20.04 in full...

**Comment by apblack96** [comment]
@oerdnj Yeah. I was able to re-install php7.3 with the majority of the extensions I needed. I was wondering if you had any idea when the following extensions would be available.

php7.3-imagick
php7.3-redis
php7.3-apcu
php7.3-ssh2

**Comment by glennjacobs** [comment]
> @oerdnj I was able to re-install php7.3 with the majority of the extensions I needed. I was wondering if you had any idea when the following extensions would be available.
> 
> php7.3-imagick
> php7.3-redis
> php7.3-apcu
> php7.3-ssh2

If you read @oerdnj's April update, you'll see he's aiming for the end of the week.

**Comment by apblack96** [comment]
Ahh my apologies, I skipped right over that...

**Comment by penh** [comment]
This is worked for me 
https://gitlab.com/khuchpenh/php-ubuntu20.04

**Comment by oerdnj** [comment]
@penh: The sources.list you linked here is horrible, and you should not be recommending something that mashes focal sources on Cambodian mirror with bionic sources on US mirror + xenial sources on US mirror again. I am removing that comment.

**Comment by penh** [comment]
@oerdnj I'm  sorry , i confuse with my country , and now i have  changed  the mirror to us of focal sources . I just recommend every one try this , because it's worked for me   https://gitlab.com/khuchpenh/php-ubuntu20.04/-/tree/master

**Comment by AnrDaemon** [comment]
@penh please remove this atrocity from the internet.
Default source lists are easily retrievable from the distribution.
Mixing multiple distributions in a single file will destroy your system.

**Comment by oerdnj** [comment]
@penh: I will block you if you don't stop posting this here.

**Comment by oerdnj** [comment]
The packages should be available since roughly last Sat/Sun. Ping me if there's anything missing in a separate issue.
