### ISSUE TITLE
Unable to install php7.0 in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by alcalpcr** [oerdnj/deb.sury.org#1386]
Problem with php 7 in Ubuntu 20.04:

	apt install language-pack-en-base
	LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
	apt install php7.0 php7.0-common php7.0-mysql libmcrypt-dev mcrypt php7.0-mcrypt php7.0-gd php7.0-xml php7.0-curl php7.0-soap libapr1 libaprutil1-dbd-sqlite3 libaprutil1-ldap php7.0-dev php-pear php-gettext libapache2-mod-php7.0 php7.0-json php7.0-cgi php7.0-mbstring php7.0-fpm php7.0-cli php7.0-bz2 php7.0-intl

Out:

    The php7.0-common package is not available, but some other package references it
    to the. This can mean that the package is missing, obsolete, or just
    is available from some other source

    The php7.0-curl package is not available, but some other package references it
     to the. This can mean that the package is missing, obsolete, or just
     is available from some other source

    The php7.0-dev package is not available, but some other package references it
    to the. This can mean that the package is missing, obsolete, or just
    is available from some other source

    The php7.0-json package is not available, but some other package references it
    to the. This can mean that the package is missing, obsolete, or just
    is available from some other source

    E: Failed to locate package php7.0
    E: The "php7.0-common" package does not have a candidate for installation
    E: Failed to locate package php7.0-mysql
    E: Failed to locate package php7.0-mcrypt
    E: Failed to locate package php7.0-gd
    E: Failed to locate package php7.0-xml
    E: Package "php7.0-curl" does not have a candidate for installation
    E: Failed to locate package php7.0-soap
    E: Package "php7.0-dev" does not have a candidate for installation
    E: Failed to locate php-gettext package
    E: Failed to locate package libapache2-mod-php7.0
    E: Package "php7.0-json" does not have a candidate for installation
    E: Failed to locate package php7.0-cgi
    E: Failed to locate package php7.0-mbstring
    E: Failed to locate package php7.0-fpm
    E: Failed to locate php7.0-cli package
    E: Failed to locate package php7.0-bz2
    E: Failed to locate package php7.0-intl

**Comment by oerdnj** [comment]
Please stop opening duplicate issues: #1385

**Comment by alcalpcr** [comment]
sorry. thanks
