### ISSUE TITLE
Update nginx stable to 1.18 

### ISSUE THREAD

**Issue by rakanskiy** [oerdnj/deb.sury.org#1387]
**Describe the bug**
Current Nginx stable is 1.18. Please conciser to update packages in nginx repo.

**Comment by oerdnj** [comment]
Done few days ago.

**Comment by natenate19** [comment]
I'm assuming this might have been built for the PPA, but the DPA doesn't look like it's there:

https://packages.sury.org/nginx/pool/main/n/nginx/

Latest I see for buster is still 1.16.1.  Could you update this to 1.18.0 when you have the time?

Thanks.
