### ISSUE TITLE
PHP 5.6 - Bug #72333 - fwrite() on non-blocking SSL sockets doesn't work

### ISSUE THREAD

**Issue by heuri** [oerdnj/deb.sury.org#1389]
First of all, many thanks for this repository.

Is there anything to be said against applying the fix for the php bug #72333 (fwrite() on non-blocking SSL sockets doesn't work) to your php 5.6 branch as well?

Bug: https://bugs.php.net/bug.php?id=72333
Fix: php/php-src@17e9fc9 (Was applied for php 7 branches only)

Bug still occurs in PHP 5.6.40-27+0~20200419.33+debian10~1.gbp02e670 because the php.net team unfortunately no longer included the bug in the php 5.6 branch and the microsoft team only applies security patches only.

- Package: php5.6
- OS: Debian 10
- Architecture: amd64
- Repository: https://packages.sury.org/php/

Thank you very much.

Test script (Taken from https://bugs.php.net/bug.php?id=72333):
---------------
```
<?php
	$context = stream_context_create();
	$fp = stream_socket_client("tls://www.google.com:443", $errornum, $errorstr, 300, STREAM_CLIENT_CONNECT, $context);
var_dump($fp);
var_dump($errornum);
var_dump($errorstr);

	stream_set_blocking($fp, 0);

	$str = "GET / HTTP/1.1\r\n";
	$str .= str_repeat("a", 1048576);

	$result = fwrite($fp, $str);
var_dump($result);

	$result = fwrite($fp, $str);
var_dump($result);
?>
```

Expected result:
----------------
The first fwrite() to not break the underlying stream.

The second fwrite() to not fail with a PHP Warning.

Actual result:
--------------
The first fwrite() breaks the underlying stream due to the loss of a valid pointer to pass to SSL_write() later to resume operations.

The second fwrite() subsequently fails with the PHP Warning:
```
$ php -v
PHP 5.6.40-27+0~20200419.33+debian10~1.gbp02e670 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

heuri@test:~/$ php bug72333.php
resource(5) of type (stream)
int(0)
string(0) ""
int(40960)
PHP Warning:  fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1409F07F:SSL routines:ssl3_write_pending:bad write retry in /home/heuri/bug72333.php on line 16
int(0)
```

**Comment by oerdnj** [comment]
I pulled the patch into the git repository and it will be released in the next round for releases in May.

**Comment by oerdnj** [comment]
Fixed packages uploaded and building.
