### ISSUE TITLE
[libgd3] imagettfbbox() returning false for empty string input

### ISSUE THREAD

**Issue by markdwhite** [oerdnj/deb.sury.org#1390]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

On 27th Mar the following packages were upgraded:

libgd3:amd64 (2.2.5-5.2+ubuntu18.04.1+deb.sury.org+1, 2.3.0-1+ubuntu18.04.1+deb.sury.org+1)
libgd3:i386 (2.2.5-5.2+ubuntu18.04.1+deb.sury.org+1, 2.3.0-1+ubuntu18.04.1+deb.sury.org+1)

On the same date, the following error message began to be reported in unit tests on a project:

"ErrorException: imagettfbbox(): Problem doing text layout"

This appears to be when (string) $text is empty which now causes "false" to be returned whereas previously a populated array was returned. It's difficult to know if the new behaviour is intended or buggy, but as the PHP docs specify an array return type, this seems buggy.

**To Reproduce**

    > $font = '/path/to/font.ttf';
    > imagettfbbox(8, 0, $font, '')
    > false
    > imagettfbbox(8, 0, $font, 'test')
    > [0,  0,  16,  0,  16,  -6,  0,  -6 ]

**Expected behavior**
Consistent, backwards-compatible behaviour

Using PHP 7.2.24 with libgd 2.2.5 (the only other version I have available)

    > $font = '/path/to/font.ttf';
    > imagettfbbox(8, 0, $font, '')
    > [  -1,  1,  1,  1,  1,  -1,  -1,  -1 ]

**Distribution (please complete the following information):**
 - Ubuntu 18.04.4
 - Architecture: amd64
 - Repository: deb.sury.org

**Package(s) (please complete the following information):**
libgd3:
  Installed: 2.3.0-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 2.3.0-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 2.3.0-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.5-4ubuntu0.4 500
        500 http://th.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     2.2.5-4 500
        500 http://th.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Additional context**

None

**Comment by oerdnj** [comment]
This needs to be reported to the upstream issue tracker here: https://github.com/libgd/libgd (please report the issue number back here).

It's not a problem in the packaging itself, but it's a regression in the new upstream version.

**Comment by markdwhite** [comment]
https://github.com/libgd/libgd/issues/632

**Comment by markdwhite** [comment]
Fixed in libgd3:amd64 (2.3.0-1)
