### ISSUE TITLE
PHP-ZTS unavailable for bionic

### ISSUE THREAD

**Issue by Austinb** [oerdnj/deb.sury.org#1392]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

PHP-ZTS unavailable for bionic

**To Reproduce**
Install using the following command on Ubuntu 18.04
`LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php-zts`

Result:
```bash
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:3 https://dl.yarnpkg.com/debian stable InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu bionic InRelease
Hit:5 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease
Hit:6 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease
Ign:7 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 InRelease
Hit:8 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Hit:9 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release
Ign:10 http://ppa.launchpad.net/ondrej/php-zts/ubuntu bionic InRelease
Err:11 http://ppa.launchpad.net/ondrej/php-zts/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ondrej/php-zts/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

The repo is added but there is no Release file.  Looking at http://ppa.launchpad.net/ondrej/php-zts/ubuntu/dists/ there is no directory for bionic there.

**Expected behavior**
The repo should be added without issue. 

**Distribution (please complete the following information):**
```bash
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Package(s) (please complete the following information):**
Unable to get any apt information as the repo is not usable on bionic

**Additional context**
None

**Comment by oerdnj** [comment]
Yes, I should have deleted the PPA long time ago. Fixed now.

**Comment by Austinb** [comment]
Ok.  Was unaware the project was no longer being supported/maintained.  I assume now the only way to add ZTS is to compile it in?
