### ISSUE TITLE
php-fpm has dependency systemd since last update => does not work on devuan!

### ISSUE THREAD

**Issue by sh-dvl** [oerdnj/deb.sury.org#1393]
is there any really functional need for inclusion of systemd-dependency in php-fpm?
I don't think so (even systemd may include full php-implementation some day).

so, please remove this dependency as soon as possible, because it's now unsable with devuan!

**Comment by oerdnj** [comment]
If you had used the issue templates it would have navigated you to FAQ - https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#supported-distributions

**Comment by elctoo** [comment]
There is a work-around to this stupidity in #1354
