### ISSUE TITLE
Update nginx to 1.18.0 in the DPA

### ISSUE THREAD

**Issue by natenate19** [oerdnj/deb.sury.org#1395]
Creating a new issue for visibility, since I commented on the original request for this once it was already closed:

https://github.com/oerdnj/deb.sury.org/issues/1387#issuecomment-623223620

In short I see nginx 1.18.0 present in the PPA:

https://launchpad.net/~ondrej/+archive/ubuntu/nginx

But not the DPA:

https://packages.sury.org/nginx/pool/main/n/nginx/

Could you get 1.18.0 built for the DPA when you have the time?

Thanks as always.

**Comment by oerdnj** [comment]
I got the original comment, but thanks for the new issue for transparency.

**Comment by oerdnj** [comment]
Done
