### ISSUE TITLE
php-memcached package is missing on Ubuntu 20.04

### ISSUE THREAD

**Issue by elkbullwinkle** [oerdnj/deb.sury.org#1397]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
It seems that php-memcached extension is missing on Ubuntu 20.04

Looks like it's not present among packages at launchpad.
![Launchpad packages screenshot](https://user-images.githubusercontent.com/10330416/81615821-657c2100-9436-11ea-9b19-6e105c2721ba.png)

And installing php-memcached will install the default one that comes from Ubuntu and it will work only with the bundled by default php-7.4

**To Reproduce**
On Ubuntu 20.04
1. `sudo apt install php-memcached`
2. `apt-cache policy php-memcached
php-memcached:
  Installed: 3.1.4+2.2.0-1
  Candidate: 3.1.4+2.2.0-1
  Version table:
 *** 3.1.4+2.2.0-1 500
        500 http://ftp.citylink.co.nz/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status`

**Expected behavior**
The php-memcached should be offered from Ubuntu PPA

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA 

**Additional context**
I know that Ubuntu 20.04 just been released, but the search brought that all the packages should be there by now. Thanks for your work on this anyways. :)

**Comment by oerdnj** [comment]
Uploaded. The `php-memcached` is in the third tier of dependencies, so it needs a manual upload. Thanks for the poke.
