### ISSUE TITLE
php-uploadprogress broken in latest 

### ISSUE THREAD

**Issue by maniac0s** [oerdnj/deb.sury.org#1398]
There is obviously a bug in the latest pecl version of uploadprogress that occurs since the last php update.
Someone reported it on the pecl issue tracker:
https://bugs.php.net/bug.php?id=79584

I had the same problem and tried various things and the only solution that worked was taking the official sources from stretch from
https://packages.debian.org/source/stretch/php-uploadprogress
and compiled it with phpize which worked.

Apparently what ever the stretch version does seems not to cause issues while the commit to the official pecl repository obviously seems to be broken.

**Comment by oerdnj** [comment]
Ew, thanks for ruining my morning with really bad C code :-). But I also made worse mistakes in the past...

I uploaded a package with a fix and added a patch to the PHP bug tracker.

**Comment by oerdnj** [comment]
@remicollet ^^^ you might be interested in this one too.

**Comment by remicollet** [comment]
@ramsey ping

**Comment by ramsey** [comment]
Thanks for pinging me. I'll take a look.

**Comment by ramsey** [comment]
@oerdnj Can you link to the patch in the PHP bug tracker, please?

**Comment by ramsey** [comment]
Nevermind... found it: https://bugs.php.net/bug.php?id=79584

@cmb69 assigned it to me, but I don't recall receiving an email about. Hmm.

**Comment by oerdnj** [comment]
@ramsey hope the patch helps.
