### ISSUE TITLE
Debian update HttpError404

### ISSUE THREAD

**Issue by mentamarindos** [oerdnj/deb.sury.org#1399]
Hi friend here's my report:

OS: Debian 8
Architecture: amd64
Repository: (both) PPA & packages.sury.org

Output of Virtualmin Update Packages tool:

` E: Failed to fetch https://packages.sury.org/php/pool/main/p/pcre3/libpcre3_8.41-1+0~20170825202309.5+jessie~1.gbp97d153_amd64.deb  HttpError404 `

` E: Failed to fetch https://packages.sury.org/php/pool/main/o/openssl/openssl_1.0.2l-1+0~20171112082041.3+jessie~1.gbp75a296_amd64.deb  HttpError404 `

Output of ` sudo apt-get update ` on debian:

` W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.sury.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY `

` W: Failed to fetch https://packages.sury.org/php/dists/jessie/InRelease `

Additional context

Like 3 days before I've make a fresh installation of Virtualmin but php doesn't install correctly (I didn't notice until today)

Today (05/13/2020) I've try to update Virtualmin but errors show up (the ones I just describe)

**Comment by oerdnj** [comment]
What does `curl --verbose  -SLO https://packages.sury.org/php/pool/main/p/pcre3/libpcre3_8.41-1+0~20170825202309.5+jessie~1.gbp97d153_amd64.deb` show?

**Comment by mentamarindos** [comment]
` curl --verbose -SLO https://packages.sury.org/php/pool/main/p/pcre3/libpcre3_8.41-1+0~20170825202309.5+jessie~1.gbp97d153_amd64.deb `

SHOWS:

```
* Hostname was NOT found in DNS cache

< HTTP/1.1 403 Forbidden
< Date: Wed, 13 May 2020 14:55:55 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: keep-alive
< Set-Cookie: __cfduid=d2a04e8a867d493a15ec92648f00d61589381755; expires=Fri, 12-Jun-20 14:55:55 GMT; path=/; domain=.sury.org; HttpOnly; SameSite=Lax; Secure
< Cache-Control: max-age=15
< Expires: Wed, 13 May 2020 14:56:10 GMT
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
* Server cloudflare is not blacklisted
< Server: cloudflare
< CF-RAY: 592d39260e26ee44-CDG
< alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
< cf-request-id: 02b0220bc30000ee445837a200000001
< 
{ [data not shown] 
```

**Comment by oerdnj** [comment]
Well, the "HTTP/1.1 403 Forbidden" kind of explains the problems you are having.  What's your client IP address?

**Comment by mentamarindos** [comment]
I think Cloudflare is the problem, because I've tried from different IPs (I even ask a friend of mine to try it too) and the same error message appears.

` HTTP/1.1 403 Forbidden `

Please try to fix it.

**Comment by oerdnj** [comment]
Feel free to reopen the issue when you provide the information I have asked for.

**Comment by Fr33man85** [comment]
Hi,
i followed this howto, to (try to) update my php to 7.3 (7.4):
https://computingforgeeks.com/how-to-install-php-7-3-on-debian-9-debian-8/

Using Debian Jessie 

very same issue with small difference:

`apt-get update`
run´s without error

but:
`apt-get install -y php7.3`

 show the following error:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libapache2-mod-php7.3 libargon2-1 libpcre2-8-0 libsodium23 libssl1.1 php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  libapache2-mod-php7.3 libargon2-1 libpcre2-8-0 libsodium23 libssl1.1 php7.3 php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-readline
0 upgraded, 11 newly installed, 0 to remove and 21 not upgraded.
Need to get 3773 kB/5483 kB of archives.
After this operation, 22.6 MB of additional disk space will be used.
Get:1 https://packages.sury.org/php/ jessie/main php7.3-common amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [571 kB]
Err https://packages.sury.org/php/ jessie/main php7.3-common amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:2 https://packages.sury.org/php/ jessie/main php7.3-json amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [18.5 kB]
Err https://packages.sury.org/php/ jessie/main php7.3-json amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:3 https://packages.sury.org/php/ jessie/main php7.3-opcache amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [178 kB]
Err https://packages.sury.org/php/ jessie/main php7.3-opcache amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:4 https://packages.sury.org/php/ jessie/main php7.3-readline amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [12.2 kB]
Err https://packages.sury.org/php/ jessie/main php7.3-readline amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:5 https://packages.sury.org/php/ jessie/main libargon2-1 amd64 0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167 [20.5 kB]
Err https://packages.sury.org/php/ jessie/main libargon2-1 amd64 0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167
  HttpError404
Get:6 https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9 [228 kB]
Err https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9
  HttpError404
Get:7 https://packages.sury.org/php/ jessie/main php7.3-cli amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [1374 kB]
Err https://packages.sury.org/php/ jessie/main php7.3-cli amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:8 https://packages.sury.org/php/ jessie/main libapache2-mod-php7.3 amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [1325 kB]
Err https://packages.sury.org/php/ jessie/main libapache2-mod-php7.3 amd64 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
Get:9 https://packages.sury.org/php/ jessie/main php7.3 all 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1 [44.1 kB]
Err https://packages.sury.org/php/ jessie/main php7.3 all 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
  HttpError404
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-common_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-json_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-opcache_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-readline_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/a/argon2/libargon2-1_0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/pcre2/libpcre2-8-0_10.34-7+0~20191220.5+debian8~1.gbp555bb9_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-cli_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/libapache2-mod-php7.3_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3_7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1_all.deb  HttpError404

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```


an 
```
curl --verbose -SLO https://packages.sury.org/php/pool/main/libg/libgd2/libgd3_2.2.5-5.2+0~20190808.4+debian8~1.gbp6d9343_amd64.deb
```

shows:

```
Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.31.95.169...
* Connected to packages.sury.org (104.31.95.169) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*        start date: 2020-07-10 00:00:00 GMT
*        expire date: 2021-07-10 12:00:00 GMT
*        subjectAltName: packages.sury.org matched
*        issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*        SSL certificate verify ok.
> GET /php/pool/main/libg/libgd2/libgd3_2.2.5-5.2+0~20190808.4+debian8~1.gbp6d9343_amd64.deb HTTP/1.1
> User-Agent: curl/7.38.0
> Host: packages.sury.org
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Sat, 11 Jul 2020 14:38:53 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: keep-alive
< Set-Cookie: __cfduid=dbd10f92c71a21599b58220645dbd65511594478333; expires=Mon, 10-Aug-20 14:38:53 GMT; path=/; domain=.sury.org; HttpOnly; SameSite=
< X-Frame-Options: SAMEORIGIN
< Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< cf-request-id: 03dfe9a7ed0000d41bef9cf200000001
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
* Server cloudflare is not blacklisted
< Server: cloudflare
< CF-RAY: 5b1345531a63d41b-BUD
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
<
{ [data not shown]
100    16  100    16    0     0     87      0 --:--:-- --:--:-- --:--:--    88
* Connection #0 to host packages.sury.org left intact
```
Same error, if i try to install php7.4

My clientIP is: 5.45.109.113


If i try to download the deb-packages directly to my windows-pc, i have no problem to download the package

**Comment by todeveni** [comment]
@Fr33man85 

> Using Debian Jessie

**Comment by Fr33man85** [comment]
> @Fr33man85
> 
> > Using Debian Jessie

This should me tell *what*?

Jessie is not working?

If i go to https://packages.sury.org/php/dists/ there is a "jessie" folder in the list..

**Comment by todeveni** [comment]
> That should me tell _what_?
> 
> Jessie is not working?

If you'd used the issue template and read the FAQ instead of commenting on a closed issue, you'd maybe seen that EOL distributions aren't supported. Apparently packages are already removed, even though the [announcement mentioned end of july](https://www.patreon.com/posts/debian-jessie-of-39058626).

**Comment by Fr33man85** [comment]
Yes, ok.. maybe you are right.. i dont readed this annoucement in front of my comment. But i used this "closed" issue, because it fits much to my actual issue. If i opend a "new issue", someone else will say "why not comment in an existing issue"... so, no matter how i do it, i´ll never pleased everyone.

Now i readed the announcement and:
he say, that there are no updates to the packages and they get removed on *end* of july. 
whe are not on the end of july and i can still download the packages by copy the links from the console to my browser, so that means to me, that the packages are still there and accessable. 

for me are no updates of an newer version iam using now are better then no installation at all.

and sure, i have to update to a newer debian release in future anyway, but right now, this is not an option to me.

I dont have an angry-mood in this post, but only want to understand some things. (like: why its still there, but can not installed by jessie)

**Comment by ajavor** [comment]
ok i understand there will be no newer php (7.3+) versions for debian jessie. but why was the last available working version 7.2 for jessie removed? it was probably the only place on the web where you could download it.

**Comment by oerdnj** [comment]
The policy is listed here: https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#supported-distributions

**Comment by oerdnj** [comment]
Hi, if you are interested in the PHP packages for Debian Jessie, please see: https://www.patreon.com/posts/deb-sury-org-and-40238414

**Comment by ilanfreoua** [comment]
So, just to be clear, you are offering php packages for the latest debian versions, and then we must pay when new debian versions are coming ?

**Comment by ilanfreoua** [comment]
=> for ex:  jessie folder has been removed 
https://packages.sury.org/php/dists/

**Comment by oerdnj** [comment]
You don’t HAVE TO pay, nobody is forcing you, you could also upgrade to a Debian version that’s still supported and not past the end-of-life.

**Comment by Hsam11** [comment]
W: Failed to fetch https://packages.sury.org/php/dists/jessie/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://packages.sury.org/php/dists/jessie/main/binary-i386/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

I have the above problem, trying to fix it for last 3 days I am using debian

**Comment by ilanfreoua** [comment]
oerdnj removed the jessie packages folder ... so now we have to pay or upgrade to a newer debian version.
nobody is forcing nobody, but this looks like more a marketing strategy than a probono "open source" initiative.

what does cost you to keep the jessie folder in the FTP ?
we all know many enterprises take their time to upgrade the OS and will prefer to pay instead of taking risks in production...
anyways ...


> You don’t HAVE TO pay, nobody is forcing you, you could also upgrade to a Debian version that’s still supported and not past the end-of-life.

**Comment by oerdnj** [comment]
What else do you think you are entitled too? Should I also mow your lawn?

These are the rules (no packages for unsupported distributions) and **I** make the rules how do I want to spend my time and what service I want to provide for free, and where are the limits. It’s my free time and you are not entitled to even a little bit of it.

I don’t see you complaining on Debian lists that the volunteers stopped supporting the Debian Jessie.

Stop shifting the costs and blaming other people for your mistakes. The end-of-life for Debian Jessie was publicly known for years, there’s simply no excuse to act surprised now.

**Comment by ilanfreoua** [comment]
Calm down @oerdnj ,
You make the rules but getting feedback is important, and might allow you to change decisions. 
this is the reason why we are called a "community". 

> Stop shifting the costs and blaming other people for your mistakes. The end-of-life for Debian Jessie was publicly known for years, there’s simply no excuse to act surprised now.

Its not a matter of mistakes, many of our clients wants to keep a Jessie at the moment, it's not because of us,
it's the real life in the IT of big companies. 
I totally understand you don't want to spare your time on Jessie, 
but i am not talking about your support, but I am talking about keeping the jessie folder on the packages.
Many volunteers stopped supporting the Debian Jessie, but for many of them, the package is still available 
for download or use.

**Comment by oerdnj** [comment]
> many of our clients wants to keep a Jessie at the moment

And again you are saying that I should carry the costs.  Just no.

**Comment by wowfingers** [comment]
I just spent an hour trawling through the web looking for an answer as to why a Client can't get their PHP from 5.6 to 7.2 and wound up here. 

@oerdnj I just want to thank you for your years of support and stand behind your decision to take your IP and make a little return on it. 
(also, for the laughs reading this thread - imagine for a second, those "big companies" were told by their IT support company that they can continue to mitigate the risk by paying the chap who has helped 'run' their webservers for years, a couple dollars..)

**Comment by BonBonSlick** [comment]
Same issue 
deb https://packages.sury.org/php/ buster main // or
deb https://packages.sury.org/php/ jessie main

`https://packages.sury.org/php/pool/main/p/php7.2/php7.2-zip_7.2.34-18+0~20210223.60+debian10~1.gbpb21322_amd64.deb?__cf_chl_jschl_tk__=pmd_128ca755c5a3ba9499a672ca6e15f00d105a91df-1626873159-0-gqNtZGzNAnijcnBszQZ6
`
_E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-zip_7.2.34-18+0~20210223.60+debian10~1.gbpb21322_amd64.deb  404  Not Found [IP: 172.67.182.150 443]_

**404**

**Comment by BonBonSlick** [comment]
UPD, redownloading gpg key solved my issue.
```

wget https://packages.sury.org/php/apt.gpg

sudo apt-key add apt.gpg
```

**Comment by todeveni** [comment]
> Debian 10, seems not supported anymore 2021 or repos are dead
> eg https://packages.sury.org/php/dists/jessie

@BonBonSlick jessie is Debian 8. It's dead.

**Comment by george-ax** [comment]
> UPD, redownloading gpg key solved my issue.
> 
> ```
> 
> wget https://packages.sury.org/php/apt.gpg
> 
> sudo apt-key add apt.gpg
> ```

You are a saviour. This is the only thing that made it work. Thanks a ton.
