### ISSUE TITLE
php7 RC 6  released on 29 Oct 2015

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#140]
RC 6 has 10 serious bugfixes.

**Comment by Code-Name-Debian** [comment]
PHP 7.0 Final will be released 6 days from now (November 12).   It is safe enough to forget about RC6.

**Comment by voku** [comment]
PHP 7.0 Final will be not be released on november 12 - "After doing the last evaluations in the RMs circle before going for 7.0.0 RTM preparations, we came to the conclusion that the current state does not look reasonable to be packaged as the final release." http://news.php.net/php.internals/89100

**Comment by oerdnj** [comment]
I'll prepare a new update this or next week. I was quite busy last month or so...

**Comment by Code-Name-Debian** [comment]
@voku I got that notice after replying here. ;)   

Nov 12 looks to be RC7. :P

**Comment by pinepain** [comment]
@oerdnj Hi, thanks for your awesome PHP PPAs! Do you have any estimate about packaging major PHP extension like curl and so on and dev tools like xdebug with PHP 7?

**Comment by oerdnj** [comment]
@pinepain curl is already packaged as php-curl; for xdebug I have no idea for the moment, we need to stabilize php 7.0 coinstallable packaging first.

**Comment by pinepain** [comment]
@oerdnj thanks for reply, my bad, I was looking for php7 prefixed curl. Thanks again.

**Comment by pinepain** [comment]
@oerdnj do you package pear itself with php7?

**Comment by oerdnj** [comment]
I have finally finished PHP 7.0.0 rc8; the modules are back as phpX.Y-module, so the package is only available from php-7.0 PPA now.

php 5.6 has to be yet converted to this new structure.
