### ISSUE TITLE
ZipArchive::open fails on empty file with libzip >= 1.6.0

### ISSUE THREAD

**Issue by gwolkerstorfer** [oerdnj/deb.sury.org#1400]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Hi Ondřej,

since the release of libzip 1.6.1 the behavior of ZipArchive::open changed in PHP 7.2. (the issue is described in detail here: [https://bugs.php.net/bug.php?id=79296](https://bugs.php.net/bug.php?id=79296))

For PHP 7.3 and 7.4 a workaround was introduced to restore backward compatibility: [http://git.php.net/?p=php-src.git;a=blobdiff;f=ext/zip/php_zip.c;h=48af712b9c23b05066c193bb98ac9a401e7f5559;hp=f65f70621e84f52308e9b872583420cf45ec0658;hb=8aab43c85d67fc1c1935f91bc64db800c4ef4754;hpb=d70058a139f3a45898e1f270c840fb64ea1a09f0]( http://git.php.net/?p=php-src.git;a=blobdiff;f=ext/zip/php_zip.c;h=48af712b9c23b05066c193bb98ac9a401e7f5559;hp=f65f70621e84f52308e9b872583420cf45ec0658;hb=8aab43c85d67fc1c1935f91bc64db800c4ef4754;hpb=d70058a139f3a45898e1f270c840fb64ea1a09f0)

Could you please backport this workaround to your 7.2 packages to keep backwards compatibility? (or maybe as an alternative provide a libzip4 package <1.6 for use with php7.2_zip)

Thank you very much!

**Distribution (please complete the following information):**
 - Ubuntu 18.04

**Package(s) (please complete the following information):**
php7.2-zip:
  Installed: 7.2.30-1+ubuntu18.04.1+deb.sury.org+1
libzip4:
  Installed: 1.6.1-3+ubuntu18.04.1+deb.sury.org+2

**Comment by oerdnj** [comment]
I have added patch to PHP 5.6 - PHP 7.2. Thanks for the links.

**Comment by oerdnj** [comment]
Fixed packages uploaded and building.

**Comment by reinholdfuereder** [comment]
Thanks for the extremely quick response/fix (or "fix", because it is a workaround for compatibility of old PHP with newer libzip): it works like a charm!
