### ISSUE TITLE
armhf: php7.4 api missing for php-apcu php-igbinary php-msgpack

### ISSUE THREAD

**Issue by h1618** [oerdnj/deb.sury.org#1402]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
those packages list phpapi-20180731 as most recent (which is PHP 7.3), but miss phpapi-20190902 for PHP 7.4

**To Reproduce**
1. Upgrade PHP from 7.3 to 7.4
2. try to install one of those packages
3. they try to install PHP7.3
4. workaround: I use the packages (same version) from debian sid armhf, they _are_ built against phpapi-20190902

**Expected behavior**
php-apcu php-igbinary php-msgpack should be built against the PHP 7.4 API (phpapi-20190902) and install along a PHP7.4 installation (especially recent builds - 20200225 or 20191219)

**Distribution (please complete the following information):**
 - OS: Armbian buster with Linux 5.4.35-sunxi
 - Architecture: armhf
 - Repository: packages.sury.org/php buster

**Package(s) (please complete the following information):**
apt-cache policy php-apcu php-igbinary php-msgpack
php-apcu:
  Installiert:           5.1.18+4.0.11-1
  Installationskandidat: 5.1.18+4.0.11-1+0~20191219.13+debian10~1.gbpa99079
  Versionstabelle:
     5.1.18+4.0.11-1+0~20191219.13+debian10~1.gbpa99079 500
        500 https://packages.sury.org/php buster/main armhf Packages
 *** 5.1.18+4.0.11-1 100
        100 /var/lib/dpkg/status
     5.1.17+4.0.11-1 500
        500 http://httpredir.debian.org/debian buster/main armhf Packages
php-igbinary:
  Installiert:           3.1.2+2.0.8-1
  Installationskandidat: 3.1.2+2.0.8-1+0~20200225.15+debian10~1.gbp1a098b
  Versionstabelle:
     3.1.2+2.0.8-1+0~20200225.15+debian10~1.gbp1a098b 500
        500 https://packages.sury.org/php buster/main armhf Packages
 *** 3.1.2+2.0.8-1 100
        100 /var/lib/dpkg/status
     3.0.0-1 500
        500 http://httpredir.debian.org/debian buster/main armhf Packages
php-msgpack:
  Installiert:           2.1.0+0.5.7-1
  Installationskandidat: 2.1.0+0.5.7-1+0~20200302.13+debian10~1.gbp2567f1
  Versionstabelle:
     2.1.0+0.5.7-1+0~20200302.13+debian10~1.gbp2567f1 500
        500 https://packages.sury.org/php buster/main armhf Packages
 *** 2.1.0+0.5.7-1 100
        100 /var/lib/dpkg/status
     2.0.3-1 500
        500 http://httpredir.debian.org/debian buster/main armhf Packages

**Additional context**
'nuff said

**Comment by oerdnj** [comment]
Could you please test now?
