### ISSUE TITLE
Repository issue with Raspberry Pi 1

### ISSUE THREAD

**Issue by iosoft** [oerdnj/deb.sury.org#1404]
Hello,

I am facing some issue if I add your SURY deb repository in my **Raspberry Pi 1** and try to install and do full upgrade nginx, php5.6 php7.x etc.

After long update process, it suddenly gives me  error - "Invalid Instruction"
and then the entire OS is crashed.

If I reboot, then also, it shows me "Invalid Instruction" and hangs. 

Pls suggest....

P.S. I want to run a clone of my forums as load balanced and my Nextcloud cloud server from my home.

**Comment by oerdnj** [comment]
I suggest you don't ignore the Issue templates as that would lead you directly to the answer.  Even searching the closed issues would directly lead you to the answer.
