### ISSUE TITLE
Request to package php-pear for Ubuntu 20.04

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1405]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
`php-pear` is not available for `Ubuntu 20.04` in the PPA.

**Describe the solution you'd like**
`php-pear` re-packaged for `Ubuntu 20.04`.

**Describe alternatives you've considered**
Installing using [`go-pear.phar`](https://pear.php.net/go-pear.phar).

**Distribution (please complete the following information):**
 - OS: `Ubuntu 20.04`
 - Architecture: `amd64`
 - Repository: `Ubuntu PPA`

**Comment by oerdnj** [comment]
It will be only when there's update. There's no need to repackage it when the version in main archives is fine: https://github.com/oerdnj/deb.sury.org/issues/1405
