### ISSUE TITLE
Update php-pear to version 1.10.12

### ISSUE THREAD

**Issue by coleaeason** [oerdnj/deb.sury.org#1406]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Could you please update the version of php-pear packages available to the [latest](https://github.com/pear/pear-core/releases/latest), 1.10.12? Version 1.10.11 includes a fix for https://github.com/pear/pear-core/pull/102 (also https://github.com/pear/pear-core/pull/104 and also https://bugs.php.net/bug.php?id=78890), which causes PHP Notice warnings when running PHP 7.4. 

**Describe the solution you'd like**
php-pear package versions to be updated to the latest release, 1.10.12

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by kells64000** [comment]
+1

Distribution (please complete the following information):

    OS: Debian
    Architecture: amd64
    Repository: Debian DPA

**Comment by oerdnj** [comment]
Done
