### ISSUE TITLE
Please provide updated pcre3 and libpcre3-dev packages for Ubuntu 20.04

### ISSUE THREAD

**Issue by jeffstoner** [oerdnj/deb.sury.org#1407]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
I'm using Pop!_OS, a Ubuntu derivative. When I upgraded from 19.10 to 20.04, I found that libpcre3-dev could not be installed. The libpcre3 I have installed is from your PPA and there is no libpcre3-dev package. Additionally, the pcre3 package is for 19.10 with no package available for 20.04. This is causing some applications to fail to install or upgrade (example: pop-shop.)

**Describe the solution you'd like**
If you could build pcre3 for Ubuntu 20.04 and make the libpcre3-dev package available for 20.04, too, I believe that would solve the problem.

**Describe alternatives you've considered**
My only alternative is to use ppa-purge to completely remove your PPA, reverting back to the system pcre3 libraries.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Architecture: amd64
 - Repository: http://ppa.launchpad.net/ondrej/php/ubuntu focal main

**Package(s) (please complete the following information):**
# apt-cache policy libpcre3
libpcre3:
  Installed: 2:8.43-1+ubuntu19.10.1+deb.sury.org+1
  Candidate: 2:8.43-1+ubuntu19.10.1+deb.sury.org+1
  Version table:
 *** 2:8.43-1+ubuntu19.10.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     2:8.39-12build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

# apt-cache policy libpcre3-dev
libpcre3-dev:
  Installed: (none)
  Candidate: 2:8.39-12build1
  Version table:
     2:8.39-12build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Additional context**
When trying to install libpcre3-dev to satisfy an app dependency, I get this:

# apt-get install libpcre3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-12build1) but 2:8.43-1+ubuntu19.10.1+deb.sury.org+1 is to be installed
                Depends: libpcrecpp0v5 (= 2:8.39-12build1) but 2:8.43-1+ubuntu19.10.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by oerdnj** [comment]
Done.
