### ISSUE TITLE
MySQL 5.6 package ignores DEBCONF settings

### ISSUE THREAD

**Issue by sbscomp** [oerdnj/deb.sury.org#141]
I just took over maintenance on a project which uses vagrant + ansible for deploys, and uses the sury MySQL 5.6 PPA. When trying to spin up the local environment, I found that the MySQL install hung every time. Logging into the box, it appears that regardless of the presence of debconf being used to set the expected password values or setting a debconf interface environment variable, the oerdnj package ignores both and insists on requiring a user input (which of course won't work with a scripted install).

I was forced to remove the sury PPA from the script for now and go back to the stock Ubuntu packaged version, which works as expected.

**Comment by oerdnj** [comment]
Thanks for the report, I will look into that. As far as I remember I switched the MySQL 5.6 packaging to stock Debian, so it might have been fixed since.

**Comment by oerdnj** [comment]
Hi @sbscomp, I upgraded the MySQL 5.6 packaging to the latest Debian package. Could you please retry?

**Comment by oerdnj** [comment]
No reply withing 24 days, closing the bug.
