### ISSUE TITLE
[FEATURE REQUEST] Update nginx mainline to 1.19.0

### ISSUE THREAD

**Issue by MetalBreaker** [oerdnj/deb.sury.org#1410]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Nginx mainline on the ondrej/nginx-mainline Ubuntu PPA is outdated.

**Describe the solution you'd like**
Please update nginx mainline on the ondrej/nginx-mainline Ubuntu PPA.

**Distribution (please complete the following information):**
 - OS: Ubuntu Server (20.04 Focal Fossa)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
nginx:
  Installed: 1.17.10-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 1.17.10-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 1.17.10-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu focal/main amd64 Packages

**Comment by oerdnj** [comment]
The nginx-1.19.0 has been uploaded and it's building now.
