### ISSUE TITLE
Open Source package compiling scripts

### ISSUE THREAD

**Issue by surjit** [oerdnj/deb.sury.org#1413]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions]
Yes, I have read

**Is your feature request related to a problem? Please describe.**
It's just to learn, source code compiling

**Describe the solution you'd like**
I would to know, How source code compiled and published on launchpad

**Describe alternatives you've considered**
Available guides for making Ubuntu Packages, but want right way to get this done and ppa on launchpad

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64 
 - Repository: I want to create new ppa

**Package(s) (please complete the following information):**
N/A

**Additional context**
N/A

I just want to create own PHP source code compiled ppa, and contribute exising ones

**Comment by oerdnj** [comment]
>  I have read [Frequenty Asked Questions]
> Yes, I have read

You haven’t
