### ISSUE TITLE
php-phalcon3 package is missing for Ubuntu 20.04

### ISSUE THREAD

**Issue by panaceya** [oerdnj/deb.sury.org#1414]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Package php-phalcon3 is missing:

```
# apt show php-phalcon3
N: Unable to locate package php-phalcon3
N: Unable to locate package php-phalcon3
E: No packages found
```
Not problem with phalcon4
```
# apt show php-phalcon4
Package: php-phalcon4
Version: 4.0.6-1+ubuntu20.04.1+deb.sury.org+1
Priority: optional
Section: php
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 18.2 MB
Provides: php-phalcon, php7.2-phalcon4, php7.3-phalcon4, php7.4-phalcon4
Pre-Depends: php-common (>= 2:69~)
Depends: ucf, php-psr, phpapi-20190902 | phpapi-20180731 | phpapi-20170718, libc6 (>= 2.14)
Breaks: php-phalcon (<< 3.4.5-2)
Replaces: php-phalcon (<< 3.4.5-2)
Download-Size: 2635 kB
APT-Sources: http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
Description: full-stack PHP framework delivered as a C-extension
 Phalcon is an open source full stack framework for PHP, written as a
 C-extension. Phalcon is optimized for high performance. Its unique architecture
 allows the framework to always be memory resident, offering its functionality
 whenever it’s needed, without expensive file stats and file reads that
 traditional PHP frameworks employ.
```
 
**To Reproduce**
1. add ppa `add-apt-repository ppa:ondrej/php`
2. update cache `apt update`
3. `apt install php-phalcon3`

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Yes, you need to upgrade to `php-phalcon4`, the 3.x is no longer supported by upstream as it has reached end-of-life. The old package was just kept in the old repositories to not break people's existing installation, but there will be no new releases.

**Comment by oerdnj** [comment]
https://blog.phalcon.io/post/phalcon-v4-why-upgrade

**Comment by panaceya** [comment]
I not need upgrade to v4 for incompatibility reasons.

**Comment by oerdnj** [comment]
Well, tough luck, you can't have both the latest greatest and not wanting to upgrade at the same time.

**Comment by panaceya** [comment]
You do not know the difference between the two versions, and are trying to prove something to me. Do not do this without knowledge.

**Comment by MatthiasKuehneEllerhold** [comment]
You can always package phalcon3 yourself if you do not like @oerdnj approach. :)

**Comment by panaceya** [comment]
This is a stubborn ram approach. The package is already assembled and delivered.

**Comment by MatthiasKuehneEllerhold** [comment]
Look into your '/var/cache/apt/archives/' directory. There should be the .deb file. You can save this and use it to install it.
You can use aptly to create an internal repository yourself easily.
Should be similar in ubuntu as well.

**Comment by panaceya** [comment]
>> Look into your '/var/cache/apt/archives/' directory. There should be the .deb file you need. You can save it and install the package with it.

New installed OS cannot have this package. As i said before, i`m already build phalcon ext manually. But normally have this version in PPA.

**Comment by oerdnj** [comment]
> You do not know the difference between the two versions, and are trying to prove something to me. Do not do this without knowledge.

Thank you for enlightening me. Oh, you forgot to demand I package it and what I do with my time!
