### ISSUE TITLE
Update phpredis to 5.2.2

### ISSUE THREAD

**Issue by micaelmendes-flymaster** [oerdnj/deb.sury.org#1415]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
[phpredis](https://github.com/phpredis/phpredis) latest version includes a bug fix for connection problems. I am facing this exact problem using Laravel.

**Describe the solution you'd like**
Update phpredis to 5.2.2.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php-redis:
  Installed: 5.2.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 5.2.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 5.2.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.6-1build1 500
        500 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

**Comment by oerdnj** [comment]
Updated 5.3.0, uploaded and building...
