### ISSUE TITLE
Ubuntu 20.04 repo must have dependency on libzip5 instead of libzip4

### ISSUE THREAD

**Issue by dsame** [oerdnj/deb.sury.org#1417]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Ubuntu 20.04 has not libzip4 (see https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libzip) package but php7 does. 

This does not create a problem for php7 itself but having the oerdnj's repo in the list of apt sources makes the subsequent installs of libzip-dev to be resolved by libzip4. As the result the binaries built on the Ubuntu with oerdnj's repo are linked to libzip4 and crash on the Ubuntu without libzip4 installed.

**To Reproduce**
1. Go to console of Ubuntu 20.04
2. Issue `dpkg -s libzip-dev`
3. With oerdnj's repo it shows
```
Package: libzip-dev
Status: install ok installed
...
Version: 1.6.1-3+ubuntu20.04.1+deb.sury.org+2
Depends: libzip4 (= 1.6.1-3+ubuntu20.04.1+deb.sury.org+2), zlib1g-dev
```

**Expected behavior**
Ideally php7 should not contain libzip-dev at all and it would be better if php7 depends on libzip5 on focal

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04

**Package(s) (please complete the following information):**
```
apt-cache policy libzip-dev
libzip-dev:
  Installed: 1.6.1-3+ubuntu20.04.1+deb.sury.org+2
  Candidate: 1.6.1-3+ubuntu20.04.1+deb.sury.org+2
  Version table:
 *** 1.6.1-3+ubuntu20.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1.5.1-0ubuntu1 500
        500 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Additional context**
Original issue: https://github.com/actions/virtual-environments/issues/1084

Currently we have to remove the php7 repo after php7 has been installed that is far not the best we should do

**Comment by oerdnj** [comment]
I am sorry, but you haven't described what the actual problem is here.  Of course, the binaries built on system where PPA is enabled will use packages from the ppa.  You should be using pbuilder (cowbuilder) or sbuild to build packages in a clean chroot.

**Comment by shivammathur** [comment]
@oerdnj Please consider repackaging `libzip-dev` and 'php7.4-zip' to use `libzip5`. The issue here is that folks at microsoft who maintain the azure images ship them with PHP installed using the PPA. On Ubuntu 20.04 they are removing the PPA as it installs `libzip4` instead of `libzip5`.

I know this is best solved at project level which is packaging software on the azure images, but as azure images are general purpose, the decision seems to be to remove the PPA instead of shipping both versions of the `libzip` library.

Removing the PPA would mean older version of PHP packages will be there on Ubuntu 20.04 azure images and would affect PHP projects using Azure Pipelines or GitHub Actions. PHP projects would have to keep using Ubuntu 18.04 or It would take extra time to add the PPA and upgrade packages in each CI/CD run. It would be nice if this removal of PPA is avoided.

**Comment by oerdnj** [comment]
> On Ubuntu 20.04 they are removing the PPA as it installs libzip4 instead of libzip5.

They should stop doing that. So far, nobody has described why it should be a problem to have libzip4 and libzip5 installed. That’s why Debian has versioned package names.

**Comment by shivammathur** [comment]
Yes they should, I see no issue as well in having both libraries installed, I suggested the same. Hope good sense prevails. #1104

**Comment by shivammathur** [comment]
Yes they should, I see no issue as well in having both libraries installed, I suggested the same. Hope good sense prevails. actions/virtual-environments#1104

**Comment by dsame** [comment]
> > On Ubuntu 20.04 they are removing the PPA as it installs libzip4 instead of libzip5.
> 
> They should stop doing that. So far, nobody has described why it should be a problem to have libzip4 and libzip5 installed. That’s why Debian has versioned package names.

It seems i buried the problem among the explanations. The key wording is ```having the oerdnj's repo in the list of apt sources makes the subsequent installs of libzip-dev to be resolved by libzip4```

The situation:

1. There's an Ubuntu image the others use to build their apps
2. This images has oerdnj's repo among APT sources
3. A guy issues `apt install libzip-dev`
4. Everything seems ok despite libzip-dev goes from oerdnj's repo and thus it is of lizbip4 and a rare person can notice that
5. The guy builds the binary linked to (of course) libzip4
6. The binary is deployed to the production environment of Ubuntu 20.04 which has no libzip4 installed 
7. Oops.

And from this point i see not perfect solution indeed because of the different paradigms: oerdnj's repo should have minimal dependencies on the outer environment and this way it "just works" - it is good and it is that i wanted by myself if i had hosted PHP site, but we are making the Image to be used by many people who should have the standard packages as much as possible and be able to run builds of virtually any set of tools. 

Having oerdnj's repo as apt source brings many (not only libzip) packages potentially not compatible with Ubuntu system without (or with the same names) those packages.

This the reason we have no choice but move to Ubuntu php on 20.04.

**Comment by oerdnj** [comment]
Well, you just can’t have both - the latest greatest and the stable. If somebody uses the PPA to build the binaries, they need to make sure the PPA is enabled on the target system.

The other option is to use APT Pining to pull the libzip-dev compatible with the target system.

**Comment by dsame** [comment]
> Well, you just can’t have both - the latest greatest and the stable.

The problem is there's the same name 'libzip-dev" both in PPA and Ubuntu 20.04 used for different versions of libzip. 

So, a build on Ubuntu 20.04 + PPA produces libzip4 binaries that segfault on Ubuntu 20.04. 

> If somebody uses the PPA to build the binaries, they need to make sure the PPA is enabled on the target system.
> 
> The other option is to use APT Pining to pull the libzip-dev compatible with the target system.

But it is impossible to make thousands of users to be picky about how to use apt. 

Actually even repackaging PPA with Ubuntu20.04 requirements won't solve the problem perfectly - you are hardly able to continue to maintain the dependencies alongside with Ubuntu packages.

Silly question - is it necessary to have the libzip-dev in your repo? Or/and the others we have in Ubuntu?

**Comment by oerdnj** [comment]
> But it is impossible to make thousands of users to be picky about how to use apt.

What? Are you suggesting that thousands of users are building binaries that depend on libzip and they must have the PPA enabled at the same time?

> Silly question - is it necessary to have the libzip-dev in your repo? Or/and the others we have in Ubuntu?

Yes.

**Comment by dsame** [comment]
> What? Are you suggesting that thousands of users are building binaries that depend on libzip and they must have the PPA enabled at the same time?

We are producing the base images for CI and this the case indeed. 
I agree there's nothing you can do on your side.

**Comment by oerdnj** [comment]
> Silly question - is it necessary to have the libzip-dev in your repo? Or/and the others we have in Ubuntu?

Let me elaborate a little bit more on this one, since I opened a device with real keyboard. I am trying to keep this simple - the packages cover the range from Ubuntu 16.04 (it was 14.04 in the past) and Debian Jessie on one end and Ubuntu 20.04 and Debian unstable on the other end.

And people actually want to have new features (like TLS 1.3 in Apache PPA) or new php-zip features that need newer library and for that I need to keep the dependency libraries unified across all supported distributions just to not get crazy and keep the number of "it works here, but doesn't work here" bugreports to minimum. It's always all about compromises, and this is one of those.
