### ISSUE TITLE
Seems like packages.sury.org checksums is bad

### ISSUE THREAD

**Issue by manoaratefy** [oerdnj/deb.sury.org#1421]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Seems like the checksum for https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz is bad:
```
Atteint:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease
Atteint:3 http://ftp.debian.org/debian stretch-updates InRelease
Atteint:4 http://ftp.debian.org/debian stretch Release
Réception de:7 https://packages.sury.org/php stretch/main amd64 Packages [136 kB]
Err:7 https://packages.sury.org/php stretch/main amd64 Packages
  Somme de contrôle de hachage incohérente
  Hashes of expected file:
   - Filesize:135911 [weak]
   - SHA256:47c638cc27413b6c173804fef3742e0ecf3098185da7d906de1101b0283c8ed6
   - SHA1:8c2119e98f4d39c8b03e780d30425470506fe4a4 [weak]
   - MD5Sum:166d763455afab94fdc54733ada609b7 [weak]
  Hashes of received file:
   - SHA256:d236c63b55ff47fc55e61be8d0bcd1fb764c3ed675482b83b22eaf43ed93952a
   - SHA1:7398543810ad3d6b1bbc6a75eb16246994cd7946 [weak]
   - MD5Sum:3f42720533b77e83a379bab3bc64532c [weak]
   - Filesize:135893 [weak]
  Last modification reported: Fri, 12 Jun 2020 08:55:54 +0000
  Release file created at: Fri, 03 Jul 2020 08:28:59 +0000
136 ko réceptionnés en 0s (151 ko/s)
Lecture des listes de paquets... Fait
E: Impossible de récupérer https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz  Somme de contrôle de hachage incohérente
   Hashes of expected file:
    - Filesize:135911 [weak]
    - SHA256:47c638cc27413b6c173804fef3742e0ecf3098185da7d906de1101b0283c8ed6
    - SHA1:8c2119e98f4d39c8b03e780d30425470506fe4a4 [weak]
    - MD5Sum:166d763455afab94fdc54733ada609b7 [weak]
   Hashes of received file:
    - SHA256:d236c63b55ff47fc55e61be8d0bcd1fb764c3ed675482b83b22eaf43ed93952a
    - SHA1:7398543810ad3d6b1bbc6a75eb16246994cd7946 [weak]
    - MD5Sum:3f42720533b77e83a379bab3bc64532c [weak]
    - Filesize:135893 [weak]
   Last modification reported: Fri, 12 Jun 2020 08:55:54 +0000
   Release file created at: Fri, 03 Jul 2020 08:28:59 +0000
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.
```
I already cleaned up my `apt` cache.
**To Reproduce**
1. Add the repository into the server:
```
curl -sSL https://packages.sury.org/php/README.txt | sudo bash -x
```
2. Run `apt-get update`:
```
apt-get update
```

**Expected behavior**
This error shouldn't happen.

**Distribution:**
 - OS: Debian 9
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
Not applicable.

**Comment by zorrobiwan** [comment]
Got it also few minutes ago.
Just retry now and it's ok.
And you?

**Comment by manoaratefy** [comment]
> Got it also few minutes ago.
> Just retry now and it's ok.
> And you?

Still have issues. Maybe it concern just the **Debian 9 x64** branch on the repository?

**Comment by pasanja49** [comment]
same problem / Debian 9

**Comment by manoaratefy** [comment]
Seems to be fixed right now.

Can @pasanja49 confirm this?

**Comment by reecebenson** [comment]
Was having the same issue - resolved for me.

**Comment by pasanja49** [comment]
I confirm, it's ok, thanks everyone.

**Comment by oerdnj** [comment]
Folks, the repository is behind a CloudFlare cache and the sync is never that atomic. It becomes a concern only if the cache is out of sync longer than hour.

**Comment by oerdnj** [comment]
Update: Cloudflare has changed the API, so you can't flush more than 30 files at once now. I have split the cache purging to go by individual Debian releases, so the cache flushing should work now again.

**Comment by sebfie** [comment]
Still get this issue

**Comment by cpuch** [comment]
I'm facing the same problem for Debian 10

**Comment by krw901** [comment]
I'm facing the same problem for Debian 11.
