### ISSUE TITLE
PHP-REDIS

### ISSUE THREAD

**Issue by CHazz** [oerdnj/deb.sury.org#1422]
ahoj,mrkni na poslední z ppa php-redis..musel jsem ho holdnout tak nějak přestalo fungovat s ním posléze vše :)

**Frequently asked questions**

- [ ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **problem** accurately (where the template below will help), I might be able to help you.

**To Reproduce**

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
This is not even an attempt at a bug report.
