### ISSUE TITLE
Repo out of sync

### ISSUE THREAD

**Issue by anatoliiopw** [oerdnj/deb.sury.org#1425]
Probaby the same as issue  #1318 Please check.

Err:16 https://packages.sury.org/php stretch/main amd64 Packages
Writing more data than expected (136068 > 135908)
Hashes of expected file:
Filesize:135908 [weak]
SHA256:98fdc4415e3893d0945fb9a29189cd19ab652101bf0b3b254348b27a9f797738
SHA1:561b2093ab35eeba7573d3d83d662cc3deb02c83 [weak]
MD5Sum:607b17710a1e597da1ff3f5bb60e0741 [weak]
Release file created at: Tue, 07 Jul 2020 07:20:43 +0000
Fetched 6760 B in 1s (6321 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages.gz Writing more data than expected (136068 > 135908)
Hashes of expected file:
- Filesize:135908 [weak]
- SHA256:98fdc4415e3893d0945fb9a29189cd19ab652101bf0b3b254348b27a9f797738
- SHA1:561b2093ab35eeba7573d3d83d662cc3deb02c83 [weak]
- MD5Sum:607b17710a1e597da1ff3f5bb60e0741 [weak]
Release file created at: Tue, 07 Jul 2020 07:20:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by oerdnj** [comment]
Dup of #1423

**Comment by anatoliiopw** [comment]
Probably it somehow have been fixed. Just checked now at the same machine:

Get:17 https://packages.sury.org/php stretch/main amd64 Packages [136 kB]
Fetched 146 kB in 1s (136 kB/s)                             
Reading package lists... Done

**Comment by cloudiercom** [comment]
Still an issue for me
