### ISSUE TITLE
System is screwed up after forced upgrade to libssl1.1

### ISSUE THREAD

**Issue by rxng** [oerdnj/deb.sury.org#1426]
Hi,

I am unable to run my apps and QT after sury forced upgrade my libssl1.0.2 to 1.1 , my system cannot function and I am having a lot of trouble with my packages. What can I do to just stop libssl1.1 from popping up?

I have also lost the ability to install libssl-dev for 1.0

Please, help me because this is a critical issue.

Thank you @oerdnj

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#what-to-report-in-the-issue-tracker
