### ISSUE TITLE
Session Handling is broken with php-redis 5.3.0, fix available in php-redis 5.3.1

### ISSUE THREAD

**Issue by kubicgruenfeld** [oerdnj/deb.sury.org#1428]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Session Handling is broken in php-redis 5.3.0, a fix is available in 5.3.1 which was just released.

**To Reproduce**
1. update to php-redis 5.3.0
2. try to use session handling with redis

**Expected behavior**
a session is stored in redis

**Distribution (please complete the following information):**
 - OS: all OS
 - Architecture: probably also all
 - Repository: all repos which include php-redis 5.3.0

**Package(s) (please complete the following information):**

```
php-redis:
  Installed: 5.3.0+4.3.0-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 5.3.0+4.3.0-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 5.3.0+4.3.0-1+ubuntu16.04.1+deb.sury.org+1 100
```

**Additional context**
https://github.com/phpredis/phpredis/issues/1807

**Comment by oerdnj** [comment]
Uploaded and building.
