### ISSUE TITLE
[mysql-5.6] Build failed for 12.04

### ISSUE THREAD

**Issue by slauber** [oerdnj/deb.sury.org#143]
The current build of https://launchpad.net/~ondrej/+archive/ubuntu/mysql-5.6 / 5.6.25-3+deb.sury.org~precise+1 is broken, see build log 

`https://launchpadlibrarian.net/216673569/buildlog_ubuntu-precise-amd64.mysql-5.6_5.6.25-3%2Bdeb.sury.org~precise%2B1_BUILDING.txt.gz`

    dh clean --parallel --with systemd
    dh: unable to load addon systemd: Can't locate Debian/Debhelper/Sequence/systemd.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 17) line 2.
    BEGIN failed--compilation aborted at (eval 17) line 2.

    make: *** [clean] Error 2
    dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
    ────────────────────────────────────────────────────────────────────────────────
    Build finished at 20150908-1503

    Finished
    ────────

    E: Build failure (dpkg-buildpackage died)

Could you please retry the build process

**Comment by oerdnj** [comment]
I am just going to retire precise builds (almost) everywhere.  Next LTS is due next year and it's just not feasible to maintain packages for so old system.
