### ISSUE TITLE
SoapClient Missing in PHP 7.2

### ISSUE THREAD

**Issue by mfisher31** [oerdnj/deb.sury.org#1430]
Hi I've installed PHP7 with your PPA on an Ubuntu trusty machine.  There isn't a php7.2-soap package, and it isn't included with the main php7.2 package.  When I enable soap in php.ini  `extension=soap`,  I get this.
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'soap' (tried: /usr/lib/php/20170718/soap (/usr/lib/php/20170718/soap: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/soap.so (/usr/lib/php/20170718/soap.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /home/mfisher/test.php:1
Stack trace:
#0 {main}
  thrown in /home/mfisher/test.php on line 1
```

My test.php file looks like:
```php
<?php $s = new SoapClient(); ?>
```

Am I missing something here?

**Comment by oerdnj** [comment]
> Hi I've installed PHP7 with your PPA on an Ubuntu trusty machine.

I pretty much doubt that, I don't provide Ubuntu Trusty packages anymore for couple of month.

You also skipped the issue templates that have many useful questions that helps to solve the issue like the [FAQ](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#what-to-report-in-the-issue-tracker) that explicitly says:

> Please note that I can't possibly do any user support

If you tried even a little bit and typed `apt search php soap` you would know the answer.

**Comment by mfisher31** [comment]
Well... I did infact install it several months ago

```
libapache2-mod-php7.2/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  server-side, HTML-embedded scripting language (Apache 2 module)

php7.2/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 all [installed,local]
  server-side, HTML-embedded scripting language (metapackage)

php7.2-bz2/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  bzip2 module for PHP

php7.2-cli/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  command-line interpreter for the PHP scripting language

php7.2-common/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  documentation, examples and common module for PHP

php7.2-curl/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  CURL module for PHP

php7.2-gd/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  GD module for PHP

php7.2-json/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  JSON module for PHP

php7.2-mbstring/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  MBSTRING module for PHP

php7.2-mysql/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  MySQL module for PHP

php7.2-opcache/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  Zend OpCache module for PHP

php7.2-readline/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  readline module for PHP

php7.2-xml/now 7.2.15-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,local]
  DOM, SimpleXML, WDDX, XML, and XSL module for PHP
```
The info above comes from my server running trusty... with your packages installed.  I understand you can't offer support, but please don't insult my intelligence.  have a good day.

**Comment by mfisher31** [comment]
and also 
```
mfisher@php-app1:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by oerdnj** [comment]
You are running Ubuntu release that reached End-Of-Life more than year ago (**April 30, 2019**), you ignored all the prominent notices to read the FAQ first, you ignored the Issue Templates, so you can spend *my* free time instead and yet you feel offended.

**Comment by mfisher31** [comment]
Well, why would I go looking for a non-support notice when it successfully installed and is working except for SOAP?  I found the ppa on stackoverflow. I apologize for skipping the templates, but didn't see SOAP when I searched the FAQ and open issues.  I assumed this was a legit bug.

Anyhow, have a good one sorry to have wasted your time.
