### ISSUE TITLE
PHP 7.4.8 packages missing for Debian

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1431]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
PHP 7.4.8 packages missing for Debian

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Additional context**
Also, [Jenkins](https://jenkins.rfc1925.org/) is reporting 502 Bad Gateway

**Comment by oerdnj** [comment]
Oh, well, the upstream has changed the phar binary naming and I am fighting the change in between the builds. I should have the packages ready soonish.

**Comment by oerdnj** [comment]
(And coincidentally Jenkins crashed :))

Here are the builds for:
* [Debian](https://jenkins.rfc1925.org/job/php_php7.4-binaries/18/)
* [Ubuntu](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php7.4&field.status_filter=published&field.series_filter=)
