### ISSUE TITLE
Package files for PHP 7.2.31 are missing

### ISSUE THREAD

**Issue by zurborg** [oerdnj/deb.sury.org#1432]
Several files for PHP 7.2.31 are missing. The following error appears after `apt-get clean && apt-get update && apt-get upgrade php7.2`

```
Get:2 https://packages.sury.org/php/ jessie/main php-common all 2:76+0~20200511.26+debian8~1.gbpc9beb6 [16.0 kB]
Err https://packages.sury.org/php/ jessie/main php-common all 2:76+0~20200511.26+debian8~1.gbpc9beb6
  HttpError404
Get:3 https://packages.sury.org/php/ jessie/main libpcre3 amd64 2:8.43-1+0~20200703.7+debian8~1.gbpbfc49f [339 kB]
Get:4 https://packages.sury.org/php/ jessie/main php7.2-opcache amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b [162 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-opcache amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b
  HttpError404
Get:5 https://packages.sury.org/php/ jessie/main php7.2-bcmath amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b [15.6 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-bcmath amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b
  HttpError404
Get:6 https://packages.sury.org/php/ jessie/main php7.2-soap amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b [113 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-soap amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b
  HttpError404
Get:7 https://packages.sury.org/php/ jessie/main php7.2-curl amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b [28.0 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-curl amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b
  HttpError404
Get:8 https://packages.sury.org/php/ jessie/main php7.2-xml amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b [108 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-xml amd64 7.2.31-1+0~20200514.41+debian8~1.gbpe2a56b
  HttpError404
```

(Some some more packages seems to be affected; full list now shown above)

I'm using Debian 8 on amd64 with the following repository:
```
deb [Enabled=yes] https://packages.sury.org/php/ jessie main
```

Besides, the most recent version is 7.2.32 (released some days ago), when will be this version available through this repository? Maybe providing this latest version instaed of fixing the old release of 7.2.31 could be fine.

**Comment by yoramvandevelde** [comment]
We see the same for libicu-dev and icu-devtools. If you stop support for debian 8 could you remove the packages from your https://packages.sury.org/php/dists/jessie/main/binary-amd64/Packages as this is breaking some flows for us.

**Comment by ikolubr** [comment]
I believe the problem is cloudflare. If you access using your browser it is asking for captcha. But files are there. Something is going up with repo.

**Comment by oerdnj** [comment]
> I believe the problem is cloudflare

Right, i forgot I need to purge the cache after Jessie removal. All the file should be gone properly now.

**Comment by ikolubr** [comment]
Still happening @oerdnj...

`The following NEW packages will be installed:
  libargon2-1 libicu65 libpcre2-8-0 libsodium23 libzip4 php7.4-bcmath php7.4-bz2 php7.4-cli php7.4-common php7.4-curl
  php7.4-fpm php7.4-gd php7.4-imap php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php7.4-opcache
  php7.4-readline php7.4-soap php7.4-xml php7.4-zip
0 upgraded, 22 newly installed, 0 to remove and 44 not upgraded.
Need to get 13.4 MB/13.5 MB of archives.
After this operation, 56.3 MB of additional disk space will be used.
Get:1 https://packages.sury.org/php/ jessie/main libargon2-1 amd64 0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167 [20.5 kB]
Err https://packages.sury.org/php/ jessie/main libargon2-1 amd64 0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167
  HttpError404
Get:2 https://packages.sury.org/php/ jessie/main libicu65 amd64 65.1-1+0~20200223.8+debian8~1.gbp519cf3 [8,453 kB]
Err https://packages.sury.org/php/ jessie/main libicu65 amd64 65.1-1+0~20200223.8+debian8~1.gbp519cf3
  HttpError404
Get:3 https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9 [228 kB]
Err https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9
  HttpError404
Get:4 https://packages.sury.org/php/ jessie/main libsodium23 amd64 1.0.18-1+0~20191009.1+debian8~1.gbpb6823f [160 kB]
Err https://packages.sury.org/php/ jessie/main libsodium23 amd64 1.0.18-1+0~20191009.1+debian8~1.gbpb6823f
  HttpError404
Get:5 https://packages.sury.org/php/ jessie/main libzip4 amd64 1.5.1-4+0~20190318173156.9+jessie~1.gbp333132 [50.8 kB]
Err https://packages.sury.org/php/ jessie/main libzip4 amd64 1.5.1-4+0~20190318173156.9+jessie~1.gbp333132
  HttpError404
Get:6 https://packages.sury.org/php/ jessie/main php7.4-common amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [628 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-common amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:7 https://packages.sury.org/php/ jessie/main php7.4-bcmath amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [15.2 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-bcmath amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:8 https://packages.sury.org/php/ jessie/main php7.4-bz2 amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [10.4 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-bz2 amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:9 https://packages.sury.org/php/ jessie/main php7.4-json amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [18.9 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-json amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:10 https://packages.sury.org/php/ jessie/main php7.4-opcache amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [193 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-opcache amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:11 https://packages.sury.org/php/ jessie/main php7.4-readline amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [12.2 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-readline amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:12 https://packages.sury.org/php/ jessie/main php7.4-cli amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [1,392 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-cli amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:13 https://packages.sury.org/php/ jessie/main php7.4-curl amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [28.1 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-curl amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:14 https://packages.sury.org/php/ jessie/main php7.4-fpm amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [1,404 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-fpm amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:15 https://packages.sury.org/php/ jessie/main php7.4-gd amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [27.6 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-gd amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:16 https://packages.sury.org/php/ jessie/main php7.4-imap amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [29.0 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-imap amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:17 https://packages.sury.org/php/ jessie/main php7.4-intl amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [124 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-intl amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:18 https://packages.sury.org/php/ jessie/main php7.4-mbstring amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [392 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-mbstring amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:19 https://packages.sury.org/php/ jessie/main php7.4-mysql amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [119 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-mysql amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:20 https://packages.sury.org/php/ jessie/main php7.4-soap amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [112 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-soap amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get:21 https://packages.sury.org/php/ jessie/main php7.4-zip amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [21.1 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-zip amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
E: Failed to fetch https://packages.sury.org/php/pool/main/a/argon2/libargon2-1_0~20190702-0.1+0~20190710.3+debian8~1.gbp2fb167_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/i/icu/libicu65_65.1-1+0~20200223.8+debian8~1.gbp519cf3_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/pcre2/libpcre2-8-0_10.34-7+0~20191220.5+debian8~1.gbp555bb9_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/libs/libsodium/libsodium23_1.0.18-1+0~20191009.1+debian8~1.gbpb6823f_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/libz/libzip/libzip4_1.5.1-4+0~20190318173156.9+jessie~1.gbp333132_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-common_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-bcmath_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-bz2_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-json_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-opcache_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-readline_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-cli_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-curl_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-fpm_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-gd_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-imap_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-intl_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-mbstring_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-mysql_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-soap_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-zip_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb  HttpError404`

**Comment by TobiasBales** [comment]
I think the issue is that the server it self does not have the 8.1 (jessie) images from what I found but it could be that cloudflare still had cached versions, probably?

**Comment by oerdnj** [comment]
Yes, @ikolubr, that’s correct. Read what I wrote in the previous message.

**Comment by TobiasBales** [comment]
@oerdnj do you know of a place where the files might still be? We probably need a week or three more to finish the last upgrades and it is not breaking some builds

**Comment by ikolubr** [comment]
Ohh... Sorry @oerdnj, didn't realized you are dropping Jessie support. -.-

**Comment by oerdnj** [comment]
Well:
* https://www.patreon.com/posts/33387816
* https://www.patreon.com/posts/36493585
* https://www.patreon.com/posts/36988601
* https://www.patreon.com/posts/39058626
* https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#supported-distributions

**Comment by yoramvandevelde** [comment]
Thanks for the reply.

**Comment by benpro** [comment]
Can we have access to an archive for Debian Jessie?

**Comment by oerdnj** [comment]
Can we stop having these discussions every time a release goes EOL?

**Comment by oerdnj** [comment]
Hi, if you are interested in the PHP packages for Debian Jessie, please see: https://www.patreon.com/posts/deb-sury-org-and-40238414

**Comment by aristipp** [comment]
Since the announcement on https://www.patreon.com/posts/deb-sury-org-and-40238414 I couldn't find anything else if the PHP repositories for Debian 8 are now available via Freexian. Are there any news?

**Comment by oerdnj** [comment]
FTR the PHP LTS by Freexian and DEB.SURY.ORG is now available: https://www.patreon.com/posts/43526354
