### ISSUE TITLE
pkg-gearman ppa not available for focal (20.04)

### ISSUE THREAD

**Issue by daum** [oerdnj/deb.sury.org#1435]
After running add-apt-repository ppa:ondrej/pkg-gearman I get the following:
```
Err:14 http://ppa.launchpad.net/ondrej/pkg-gearman/ubuntu focal Release  
  404  Not Found [IP: 91.189.95.83 80]
```
Looking at the dist directory it doesn't look like there is any support for focal.

**Comment by oerdnj** [comment]
I updated the package to 1.1.19.1 and uploaded it also to focal
