### ISSUE TITLE
nginx-1.19.0 is broken: undefined symbol: ngx_stream_add_variable

### ISSUE THREAD

**Issue by Whissi** [oerdnj/deb.sury.org#1437]
Today, `apt-get upgrade` upgraded nginx from `1.17.10-1+0~20200423.14+debian9~1.gbp1f7c3d` to `1.19.0-1+0~20200707.15+debian9~1.gbpc351f0`. After the upgrade, nginx was unable to start:
```
nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_stream_geoip_module.so" failed (/usr/share/nginx/modules/ngx_stream_geoip_module.so: undefined symbol: ngx_stream_add_variable) in /etc/nginx/modules-enabled/70-mod-stream-geoip.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I had to remove the two symlinks in `/etc/nginx/modules-enabled` to get the server started again.

See also: https://bugs.launchpad.net/nginx/+bug/1887645

**Comment by todeveni** [comment]
I'm not using nginx-mainline myself, but stable nginx from deb.sury.org. Just checking that you have geoip packages installed?

`apt-cache policy libnginx-mod-http-geoip`
`apt-cache policy libnginx-mod-stream-geoip`

**Comment by oerdnj** [comment]
This particular module and several others require `libnginx-mod-stream_1.19.0-1_amd64.deb` to be installed and enabled. Can you confirm this is the case?

**Comment by Whissi** [comment]
Yes, the following packages were installed and upgraded together causing the failure:
```
# dpkg -l | grep nginx
ii  libnginx-mod-http-auth-pam           1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        PAM authentication module for Nginx
ii  libnginx-mod-http-dav-ext            1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        WebDAV missing commands support for Nginx
ii  libnginx-mod-http-echo               1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Bring echo and more shell style goodies to Nginx
ii  libnginx-mod-http-geoip              1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        GeoIP HTTP module for Nginx
ii  libnginx-mod-http-geoip2             1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        GeoIP2 HTTP module for Nginx
ii  libnginx-mod-http-image-filter       1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        HTTP image filter module for Nginx
ii  libnginx-mod-http-subs-filter        1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Substitution filter module for Nginx
ii  libnginx-mod-http-upstream-fair      1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Nginx Upstream Fair Proxy Load Balancer
ii  libnginx-mod-http-xslt-filter        1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        XSLT Transformation module for Nginx
ii  libnginx-mod-mail                    1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Mail module for Nginx
ii  libnginx-mod-ssl-ct                  1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Certificate Transparency support for Nginx
ii  libnginx-mod-stream                  1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        Stream module for Nginx
ii  libnginx-mod-stream-geoip            1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        GeoIP Stream module for Nginx
ii  libnginx-mod-stream-geoip2           1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        GeoIP2 Stream module for Nginx
iU  nginx                                1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      all          small, powerful, scalable web/proxy server
ii  nginx-common                         1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      all          small, powerful, scalable web/proxy server - common files
iF  nginx-core                           1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      amd64        nginx web/proxy server (standard version)
iU  nginx-full                           1.19.0-1+0~20200707.15+debian9~1.gbpc351f0      all          nginx web/proxy server (standard version with 3rd parties)
```

**Comment by oerdnj** [comment]
What happens when you run `dpkg --configure -a` now? It seems that the main packages are not in fully upgraded state.

**Comment by Whissi** [comment]
Configure failed because system was unable to launch service due to this failure.
Now that I manually fixed the problem to allow nginx to start again, configure will succeed:
```
# dpkg --configure -a
Setting up nginx-core (1.19.0-1+0~20200707.15+debian9~1.gbpc351f0) ...
[ ok ] Upgrading binary: nginx.
Setting up nginx (1.19.0-1+0~20200707.15+debian9~1.gbpc351f0) ...
Setting up nginx-full (1.19.0-1+0~20200707.15+debian9~1.gbpc351f0) ...
```

**Comment by oerdnj** [comment]
Can you confirm that all modules from `libnginx-mod-stream` are enabled and loaded in nginx?  This might be a load-ordering problem.

**Comment by Whissi** [comment]
As soon as I re-add symlink in `/etc/nginx/modules-enabled`
```
ln -s /usr/share/nginx/modules-available/mod-stream-geoip2.conf 50-mod-stream-geoip2.conf
```
nginx will be unable to start again:
```
nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_stream_geoip2_module.so" failed (/usr/share/nginx/modules/ngx_stream_geoip2_module.so: undefined symbol: ngx_stream_compile_complex_value) in /etc/nginx/modules-enabled/50-mod-stream-geoip2.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Changing order, i.e.  from
```
50-mod-http-geoip2.conf
50-mod-ssl-ct.conf
50-mod-stream-geoip2.conf
```
to
```
50-mod-http-geoip2.conf
50-mod-ssl-ct.conf
60-mod-stream-geoip2.conf
```
or
```
40-mod-stream-geoip2.conf
50-mod-http-geoip2.conf
50-mod-ssl-ct.conf
```
doesn't change anything -- same error.

**Comment by oerdnj** [comment]
That doesn't answer my question.  Do you have `50-mod-stream.conf` enabled?

**Comment by Whissi** [comment]
Thougt this was clear like I listed `/etc/nginx/modules-enabled` in my previous posting and there was no `50-mod-stream.conf`.
I now compared against a fresh installation of this package and after re-creating missing symlinks in `/etc/nginx/modules-enabled`, including `50-mod-stream.conf`, it's now working again:
```
# ls -al /etc/nginx/modules-enabled/
total 8
drwxr-xr-x 2 root root 4096 Jul 16 14:51 .
drwxr-xr-x 8 root root 4096 Jul 16 02:09 ..
lrwxrwxrwx 1 root root   57 Jul 16 14:48 50-mod-http-auth-pam.conf -> /usr/share/nginx/modules-available/mod-http-auth-pam.conf
lrwxrwxrwx 1 root root   56 Jul 16 14:48 50-mod-http-dav-ext.conf -> /usr/share/nginx/modules-available/mod-http-dav-ext.conf
lrwxrwxrwx 1 root root   53 Jul 16 14:48 50-mod-http-echo.conf -> /usr/share/nginx/modules-available/mod-http-echo.conf
lrwxrwxrwx 1 root root   55 Feb 28  2019 50-mod-http-geoip2.conf -> /usr/share/nginx/modules-available/mod-http-geoip2.conf
lrwxrwxrwx 1 root root   54 Jul 16 14:49 50-mod-http-geoip.conf -> /usr/share/nginx/modules-available/mod-http-geoip.conf
lrwxrwxrwx 1 root root   61 Jul 16 14:49 50-mod-http-image-filter.conf -> /usr/share/nginx/modules-available/mod-http-image-filter.conf
lrwxrwxrwx 1 root root   60 Jul 16 14:50 50-mod-http-subs-filter.conf -> /usr/share/nginx/modules-available/mod-http-subs-filter.conf
lrwxrwxrwx 1 root root   62 Jul 16 14:50 50-mod-http-upstream-fair.conf -> /usr/share/nginx/modules-available/mod-http-upstream-fair.conf
lrwxrwxrwx 1 root root   60 Jul 16 14:50 50-mod-http-xslt-filter.conf -> /usr/share/nginx/modules-available/mod-http-xslt-filter.conf
lrwxrwxrwx 1 root root   48 Jul 16 14:50 50-mod-mail.conf -> /usr/share/nginx/modules-available/mod-mail.conf
lrwxrwxrwx 1 root root   50 Feb 28  2019 50-mod-ssl-ct.conf -> /usr/share/nginx/modules-available/mod-ssl-ct.conf
lrwxrwxrwx 1 root root   50 Jul 16 14:51 50-mod-stream.conf -> /usr/share/nginx/modules-available/mod-stream.conf
lrwxrwxrwx 1 root root   57 Jul 16 14:51 70-mod-stream-geoip2.conf -> /usr/share/nginx/modules-available/mod-stream-geoip2.conf
lrwxrwxrwx 1 root root   56 Jul 16 14:51 70-mod-stream-geoip.conf -> /usr/share/nginx/modules-available/mod-stream-geoip.conf
```
So I was went through our backups and noticed that we disabled (=deleted that symlink) in 2018 already which makes sense because this nginx instance is just a simple reverse proxy which doesn't need all of the available modules.

But did we do anything wrong? Did we miss a tool like `a2dismod` for nginx which would prevent an issue like that in apache world on Debian?

**Comment by oerdnj** [comment]
> But did we do anything wrong? Did we miss a tool like a2dismod for nginx which would prevent an issue like that in apache world on Debian?

That would be actually a question for the Debian nginx maintainer, but my recommendation would be to actually remove the packages with modules that you are not using.

> So I went through our backups and noticed that we disabled (=deleted that symlink) in 2018 already which makes sense because this nginx instance is just a simple reverse proxy which doesn't need all of the available modules.

Ok, so there's nothing really wrong with the packaging per se, it just doesn't handle well new modules being pulled while dependencies have been disabled.  Again this is a bug better solved directly in Debian, in fact there's already a bug report related to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953034

**Comment by cfw34683** [comment]
I can confirm that ugrading to 1.19 nginx produced the same error as OP.

to fix:
`cd /etc/nginx/modules-enabled/
sudo ln -s /usr/share/nginx/modules-available/50-mod-stream.conf 50-mod-stream.conf
sudo dpkg --configure -a
sudo apt update
sudo systemctl reload nginx`

These steps got it to work for me

**Comment by sganzerla** [comment]
@cfw34683 eu estava com o mesmo problema. 

`
ubuntu@ip-172-31-90-227:~$ sudo nginx -t
nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_stream_geoip_module.so" failed (/usr/share/nginx/modules/ngx_stream_geoip_module.so: undefined symbol: ngx_stream_add_variable) in /etc/nginx/modules-enabled/70-mod-stream-geoip.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
`

Eu tinha uma instalação padrão do nginx funcionando normalmente porém tive que fazer a remoção manualmente nos diretórios. Para funcionar novamente reinstalei adicionando o repositório `sudo add-apt-repository ppa:nginx/stable && sudo apt-get update && sudo apt-get -f install nginx ` .

A origem do meu problema foi ter feito essa instalação.

Eu tentei criar o atalho do módulo como você sugeriu,  mas criei outro problema.

Então resolvi excluir os dois e voltar a rodar normalmente.

`
sudo rm /etc/nginx/modules-enabled/70-mod-stream-geoip.conf
sudo nginx -t
`

Ubuntu 18.04


![image](https://user-images.githubusercontent.com/22710963/101627546-4447d700-39fd-11eb-9ca0-6c347cc42f77.png)

Meu problema foi resolvido.

**Comment by cristihainic** [comment]
@sganzerla that's my workaround as well, whatever works :shrug:

**Comment by sepehr-safaeian** [comment]
None of these worked for me so I did this:

`dpkg -l | grep nginx-full`
`sudo dpkg --remove --force-remove-reinstreq cloudpanel`
`sudo apt-get update`
`sudo apt-get -f install`
`sudo dpkg-reconfigure nginx-full`

be happy

**Comment by TechnologyClassroom** [comment]
@ghost got me most of the way there, but there is a slight mistake on the `ln` line. This worked for me:

```
cd /etc/nginx/modules-enabled/
sudo ln -s /usr/share/nginx/modules-available/mod-stream.conf 50-mod-stream.conf
sudo dpkg --configure -a
sudo systemctl start nginx
```
