### ISSUE TITLE
Phalcon extension needs rebuilding against PHP 7.4.8 to prevent segfault

### ISSUE THREAD

**Issue by IMSoP** [oerdnj/deb.sury.org#1438]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Upgrading to PHP 7.4.8 using an existing binary of Phalcon causes a reproducible segfault, as discussed here: https://github.com/phalcon/cphalcon/issues/15107

Re-building the php-phalcon4 package from source with the php7.4-dev package seems to fix the issue. Would it be possible to upload a new build of the package to the PPA?

Thank you very much for maintaining these packages!

**To Reproduce**

1. `sudo apt install php7.4-cli php-phalcon4`
2. `php -r 'var_dump(new class(new Phalcon\Di\FactoryDefault) extends Phalcon\Mvc\Model {});'`
3. Will die with either `zend_mm_heap corrupted` or `Segmentation fault (core dumped)`

To re-build, I ran this:

```
sudo apt install dh-php libexporter-tiny-perl liblist-moreutils-perl libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 php7.4-dev xml2
sudo apt source php-phalcon4
cd php-phalcon4-4.0.6/build
sudo ./install
php -r 'var_dump(new class(new Phalcon\Di\FactoryDefault) extends Phalcon\Mvc\Model {});
```

Command then runs successfully (outputting the content of the object).

**Distribution:**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s):**

```
php7.4:
  Installed: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Candidate: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Version table:
 *** 7.4.8-1+ubuntu18.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
php7.4-cli:
  Installed: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Candidate: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Version table:
 *** 7.4.8-1+ubuntu18.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
php7.4-dev:
  Installed: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Candidate: 7.4.8-1+ubuntu18.04.1+deb.sury.org+3
  Version table:
 *** 7.4.8-1+ubuntu18.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
php-phalcon4:
  Installed: 4.0.6-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 4.0.6-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 4.0.6-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Ok, rebuild issued.

**Comment by IMSoP** [comment]
Looks good, thank you!

**Comment by PhilippHandle** [comment]
is the ubuntu package rebuild?

**Comment by IMSoP** [comment]
@PhilippHandle You can see the new packages on the PPA's web page here: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=phalcon&field.status_filter=published&field.series_filter=  Note the `+2` suffix, and the build date of 17th July.

**Comment by PhilippHandle** [comment]
@IMSoP Thanks. I cleaned ip some mess. Now it works!
Thanks for sour help and work

**Comment by vchk** [comment]
@IMSoP Thank you.
Same here. Also experienced this bug. You saved my day! :)
But, it will be nice to not remove previous version of PHP packages, at least for few weeks.
Intentional or unintentional update may crash the system and there is no way to roll back,
because previous working packages version are gone from repository.
