### ISSUE TITLE
php7.4 imagick missing

### ISSUE THREAD

**Issue by tsdogs** [oerdnj/deb.sury.org#1443]
Debian 10:
php7.4-imagick missing (and also the imagick.so in the php-imagick package for php7.4)

I had to install it with pecl.
It would be nice to have it packaged.

**Comment by oerdnj** [comment]
And it would be nice if you used the issue templates and filled the required fields, so I would not have to guess.

**Comment by tsdogs** [comment]
ok, I'll reopen a new one and use the template, I erroneously thought  it was clear enough.
