### ISSUE TITLE
php7.4-imagick library and package missing

### ISSUE THREAD

**Issue by tsdogs** [oerdnj/deb.sury.org#1444]
**Frequently asked questions**

- [X ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

When using the repository to install php7.4 on debian 10 the php7.4-imagick is missing.
Also the php-imagick package which contains the various versions of the actual library is missing the 7.4 version of imagick.so

**To Reproduce**
1. Follow this guide to add the repository on debian 10
https://www.cloudbooklet.com/install-php-7-4-on-debian-10/
2.  Try install php7.4-imagik

**Expected behavior**
The package installs

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: i386
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
php-imagick:
  Installed: 3.4.4-4+0~20200302.14+debian10~1.gbp2925ae
  Candidate: 3.4.4-4+0~20200302.14+debian10~1.gbp2925ae
  Version table:
 *** 3.4.4-4+0~20200302.14+debian10~1.gbp2925ae 500
        500 https://packages.sury.org/php buster/main i386 Packages
        100 /var/lib/dpkg/status
     3.4.3-4.1 500
        500 http://ftp.it.debian.org/debian buster/main i386 Packages
apt-cache policy php7.4-imagick
N: Unable to locate package php7.4-imagick
N: Couldn't find any package by glob 'php7.4-imagick'
N: Couldn't find any package by regex 'php7.4-imagick'

**Additional context**
Hope it's clear enough

**Comment by oerdnj** [comment]
Please provide output of `apt-cache show php-imagick` and `dpkg -L php-imagick`.

**Comment by tsdogs** [comment]
Interesting enough, I upgraded to an amd64 version of debian 10 and now imagick.so is present also for php7.4

If I download deb from here: https://packages.sury.org/php/pool/main/p/php-imagick/ 
Checking the data.tar.xz from various architectures it seems it's missing from all except amd64

I'm sorry but currently don't have the i386 vm anymore. If needed anyway I might bring a new up again.

**Comment by oerdnj** [comment]
That's much better, although it's weird, as there's only armhf build failure: https://jenkins.rfc1925.org/view/PHP/job/php_php-imagick-binaries/20/

I'll issue a rebuild of the package.

**Comment by tsdogs** [comment]
Now package content seem to be complete (even debian 9 and armhf).
Cannot test i386 though, let me know if needed.
