### ISSUE TITLE
[extension request] php-ext-lz4 PHP extension

### ISSUE THREAD

**Issue by zench1k** [oerdnj/deb.sury.org#1446]
Hello oerdnj,
Please add php-ext-lz4 to your PPA

sources is here https://github.com/kjdev/php-ext-lz4

**Comment by oerdnj** [comment]
This has no official PECL releases.  Is it still useful?

**Comment by zench1k** [comment]
Yes, we use this extension, I compile it every time, we considered the option with zstd, but it was not there either. Therefore, I made 2 requests. Thanks for adding zstd

**Comment by Hagabard** [comment]
Same here, we have to manually compile for our app

**Comment by oerdnj** [comment]
Ok, done.

**Comment by oerdnj** [comment]
And now the repository for the extension is gone. I am going to remove the package unless there's new authoritative source somewhere.

**Comment by oerdnj** [comment]
(Actually, it was my mistake, I used the wrong path in `debian/watch` probably as copy&paste typo.)
