### ISSUE TITLE
Error on Upgrade

### ISSUE THREAD

**Issue by tk7936** [oerdnj/deb.sury.org#1447]
Im getting this error when i try to upgrade to php 7.4

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  libpcre2-8-0 php7.4-opcache php7.4-json php7.4-readline php7.4 php7.4-cli libapache2-mod-php7.4 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": Yes
Get: 1 https://packages.sury.org/php/ jessie/main php7.4-json amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [18.9 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-json amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get: 2 https://packages.sury.org/php/ jessie/main php7.4-opcache amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [193 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-opcache amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get: 3 https://packages.sury.org/php/ jessie/main php7.4-readline amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [12.2 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-readline amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get: 4 https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9 [228 kB]
Err https://packages.sury.org/php/ jessie/main libpcre2-8-0 amd64 10.34-7+0~20191220.5+debian8~1.gbp555bb9
  HttpError404
Get: 5 https://packages.sury.org/php/ jessie/main php7.4-cli amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [1392 kB]
Err https://packages.sury.org/php/ jessie/main php7.4-cli amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get: 6 https://packages.sury.org/php/ jessie/main libapache2-mod-php7.4 amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [1337 kB]
Err https://packages.sury.org/php/ jessie/main libapache2-mod-php7.4 amd64 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
Get: 7 https://packages.sury.org/php/ jessie/main php7.4 all 7.4.7-1+0~20200612.18+debian8~1.gbp671911 [39.0 kB]
Err https://packages.sury.org/php/ jessie/main php7.4 all 7.4.7-1+0~20200612.18+debian8~1.gbp671911
  HttpError404
0% [Working]E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-json_7.4.7-1+0~20200612.18+debian8~1.gbp671911_amd64.deb: HttpError404

Does this mean the server is down ?

**Comment by oerdnj** [comment]
Hi,

the Debian Jessie is no longer available in the community edition, if you are interested in the PHP packages for Debian Jessie, please see: https://www.patreon.com/posts/deb-sury-org-and-40238414

**Comment by oerdnj** [comment]
FTR the offer by Freexian and DEB.SURY.ORG is now live: https://www.patreon.com/posts/43526354
