### ISSUE TITLE
Update php-igbinary to 3.1.4

### ISSUE THREAD

**Issue by sschuerz** [oerdnj/deb.sury.org#1448]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
There was an bug in [igbinary](https://github.com/igbinary/igbinary) regarding (de)serialization of objects in connection with PHP 7.4: https://github.com/igbinary/igbinary/issues/281.
In our context, this bug makes it impossible to upgrade to PHP 7.4.
However, the bug is already fixed in ignbinary 3.1.4.

**Describe the solution you'd like**
Update php-igbinary to 3.1.4 (currently 3.1.2 is available).

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php-igbinary:
  Installed: 3.1.2+2.0.8-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 3.1.2+2.0.8-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 3.1.2+2.0.8-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.5-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

**Comment by sschuerz** [comment]
Is there any progress on this issue?
Unfortunately, as mentioned above, we are prevented from upgrading to PHP 7.4 until we can use ignbinary 3.1.4. :frowning_face:
So we would very much appreciate a solution here.

**Comment by alecpl** [comment]
I see php-igbinary 3.1.5 at https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by sschuerz** [comment]
Thank you, we got php-igbinary 3.1.5:

```
root@XXX:~# apt-cache policy php-igbinary
php-igbinary:
  Installed: 3.1.5+2.0.8-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 3.1.5+2.0.8-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 3.1.5+2.0.8-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.5-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

This issue can be closed.
