### ISSUE TITLE
php7.4-acpu-bc not available on arm64 architecture

### ISSUE THREAD

**Issue by dennisameling** [oerdnj/deb.sury.org#1449]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
It looks like the `php7.4-acpu-bc` package is not available for the `arm64` architecture: `Unable to locate package php7.4-apcu-bc`.

From https://packages.sury.org/php/dists/buster/main/binary-arm64/Packages (`php7.3-apcu-bc` is the highest available version):

```
Package: php-apcu-bc
Version: 1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0
Architecture: arm64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 102
Pre-Depends: php-common (>= 2:69~)
Depends: php-apcu, phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012, libc6 (>= 2.17)
Provides: php7.0-apcu-bc, php7.1-apcu-bc, php7.2-apcu-bc, php7.3-apcu-bc
Homepage: http://pecl.php.net/package/apcu_bc
Priority: optional
Section: php
Filename: pool/main/p/php-apcu-bc/php-apcu-bc_1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0_arm64.deb
Size: 11152
SHA256: 1912322fe07a163bfdc988e43cc1b858dd3b4f268ae50dc6068c1f12c4bb35d1
SHA1: ee84a78c4d2c9b70ee562e1c4b90ad879fc131dd
MD5sum: 2d2325a12dbf161285ab9e0ef28d7748
Description: APCu Backwards Compatibility Module
 This module provides a backwards APC compatible API using APCu.
```

This package is available for the `amd64` architecture though. From https://packages.sury.org/php/dists/buster/main/binary-amd64/Packages:

```
Package: php-apcu-bc
Version: 1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 141
Pre-Depends: php-common (>= 2:69~)
Depends: php-apcu, phpapi-20190902 | phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012, libc6 (>= 2.4)
Provides: php7.0-apcu-bc, php7.1-apcu-bc, php7.2-apcu-bc, php7.3-apcu-bc, php7.4-apcu-bc
Homepage: http://pecl.php.net/package/apcu_bc
Priority: optional
Section: php
Filename: pool/main/p/php-apcu-bc/php-apcu-bc_1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0_amd64.deb
Size: 11420
SHA256: f57cacc3481c841cc7a43081ffe7ae198168b6b57e2671dc35efd7f0025fc969
SHA1: a34769853ce56abe148449739099a59d2278c821
MD5sum: b87b203742642e61fd21db8b38259244
Description: APCu Backwards Compatibility Module
 This module provides a backwards APC compatible API using APCu.
```

**To Reproduce**
1. Use Debian Buster on an arm64 device
2. Try `apt-get install php7.4-apcu-bc`
3. You'll get an error: `Unable to locate package php7.4-apcu-bc`

**Expected behavior**
I would expect `php7.4-apcu-bc` to be available, but I'm not sure if I'm missing something. I checked https://www.patreon.com/posts/may-update-for-36988601 which _might_ be related, but I'm not sure. Apologies if I missed some announcement and/or news item about this specific package on `arm64`.

**Distribution (please complete the following information):**
 - OS: Debian (Docker: debian:buster-slim)
 - Architecture: arm64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
N/A I believe, https://github.com/drud/ddev-images/blob/ff42f17c7e5dde08ee4a29e41c859bd41d5df045/Dockerfile shows all the packages that we use in our Dockerfile

**Additional context**
We came across this issue while adding support for the `arm64` architecture in DDEV. Just linking the PR here for visibility: https://github.com/drud/ddev-images/pull/16

Please let me know if there's anything I can do to help from my side, happy to help!

**Comment by rfay** [comment]
Hoping that we could get this added into current work.

**Comment by rfay** [comment]
I note that php-apcu-bc is there for arm64. Perhaps it's just a missing pseudo-package for php7.4-apcu-bc ? Not sure how that works out with the current reorganization of packages like that.

**Comment by rfay** [comment]
I note that php7.4-apcu-bc is in there in the Ubuntu aarch64 PPA, but missing on Debian (although currently it switches to php-apcu-bc):

```
root@23fba237b438:/# uname -a
Linux 23fba237b438 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 aarch64 aarch64 GNU/Linux
root@23fba237b438:/# apt-get install php7.4-apcu-bc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php-apcu-bc' instead of 'php7.4-apcu-bc'
The following additional packages will be installed:
  libbsd0 libedit2 libsodium23 php-apcu php-common php7.0-apcu php7.1-apcu
  php7.2-apcu php7.3-apcu php7.4-apcu php7.4-cli php7.4-common php7.4-json
  php7.4-opcache php7.4-phpdbg php7.4-readline php8.0-apcu psmisc
Suggested packages:
  php-gd php-pear
The following NEW packages will be installed:
  libbsd0 libedit2 libsodium23 php-apcu php-apcu-bc php-common php7.0-apcu
  php7.1-apcu php7.2-apcu php7.3-apcu php7.4-apcu php7.4-cli php7.4-common
  php7.4-json php7.4-opcache php7.4-phpdbg php7.4-readline php8.0-apcu psmisc
0 upgraded, 19 newly installed, 0 to remove and 11 not upgraded.
Need to get 4408 kB of archives.
After this operation, 20.0 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by oerdnj** [comment]
It should be there now.

**Comment by rfay** [comment]
As far as I can tell php7.4-apcu-bc isn't available on either amd64 or arm64 at this point.  It used to be there on amd64. Please reopen? Thanks!

**Comment by oerdnj** [comment]
* https://jenkins.rfc1925.org/view/PHP/job/php_php-apcu-binaries/architecture=arm64,distribution=buster/
* https://jenkins.rfc1925.org/view/PHP/job/php_php-apcu-bc-binaries/architecture=arm64,distribution=buster/

**Comment by rfay** [comment]
Yup, got it, thanks!
