### ISSUE TITLE
[php7.0] Ubuntu 12.04 support

### ISSUE THREAD

**Issue by lastguru1** [oerdnj/deb.sury.org#145]
Please make PHP 7.0 for Ubuntu 12.04 as well, if it is not too hard

**Comment by dlancea** [comment]
:thumbsup:

**Comment by oerdnj** [comment]
I don't currently plan to support Ubuntu 12.04 LTS, but I might revisit this when the dust settles and I have a solid packaging for trusty upwards.

**Comment by oerdnj** [comment]
Folks, is there any solid reason why just not upgrade to trusty? 12.04 needs apache2 backport which I would like to avoid since it's a slight annoyance since you need to backport a lot of apache2 modules with it.

**Comment by lastguru1** [comment]
Honestly, I don't use apache there (I use nginx), so I don't really care is apache works with php7 :) I understand that this is a bit selfish, but still - php7 without apache support is better than no php7 at all...

**Comment by dlancea** [comment]
If it's too much work, don't worry about it.

This might be the push we need to update to 14.04.

**Comment by oerdnj** [comment]
@lastguru1 having two different source packages of php with different binary packages (with and without) is the worst possible scenario as it require non-minimal amount of work. I still haven't heard of any real use case that would prevent upgrading to Ubuntu trusty.

**Comment by oerdnj** [comment]
Next Ubuntu LTS (16.04) is due next year and Ubuntu 14.04 LTS was released a year and half ago. I am just going to deprecate all Ubuntu 12.04 packages with PHP 5.4 as an exception (as PHP 5.4 has been EOLed by upstream and it's going away as well in its due time...)
