### ISSUE TITLE
Phalcon3 package for Focal

### ISSUE THREAD

**Issue by jellisii** [oerdnj/deb.sury.org#1450]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
PHP7.3 is missing Phalcon 3 on Focal

**Describe the solution you'd like**
Phalcon3 to be added to Focal repos.  

**Describe alternatives you've considered**
Since Eoan had Phalcon3 installed, I'm not sure exactly how much of a lift this is.  I can build and supply it myself if this is too onerous.  

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04]
 - Architecture: AMD64
 - Repository: Ubuntu PPA

Thanks for the work you do here.  It's greatly appreciated.

**Comment by oerdnj** [comment]
The building of the phalcon3 packages has been restored now.

As a side note, phalcon3 has been discontinued by upstream and it's not getting any updates.
