### ISSUE TITLE
php-rrd not available for php 7.4 on armhf

### ISSUE THREAD

**Issue by fossibaer76** [oerdnj/deb.sury.org#1451]
Hi,

It seems the php-rrd_2.0.1+1.1.3-7+0_20191119.9+debian10_1.gbpa30cb3_armhf.deb package is not available for php 7.4 API version

dpkg --contents php-rrd_2.0.1+1.1.3-7+0_20191119.9+debian10_1.gbpa30cb3_armhf.deb
drwxr-xr-x root/root         0 2019-11-19 04:09 ./
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/5.6/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/5.6/mods-available/
-rw-r--r-- root/root        52 2019-11-19 04:09 ./etc/php/5.6/mods-available/rrd.ini
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.0/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.0/mods-available/
-rw-r--r-- root/root        52 2019-11-19 04:09 ./etc/php/7.0/mods-available/rrd.ini
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.1/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.1/mods-available/
-rw-r--r-- root/root        52 2019-11-19 04:09 ./etc/php/7.1/mods-available/rrd.ini
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.2/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.2/mods-available/
-rw-r--r-- root/root        52 2019-11-19 04:09 ./etc/php/7.2/mods-available/rrd.ini
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.3/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./etc/php/7.3/mods-available/
-rw-r--r-- root/root        52 2019-11-19 04:09 ./etc/php/7.3/mods-available/rrd.ini
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/20131226/
-rw-r--r-- root/root     22472 2019-11-19 04:09 ./usr/lib/php/20131226/rrd.so
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/20151012/
-rw-r--r-- root/root     22472 2019-11-19 04:09 ./usr/lib/php/20151012/rrd.so
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/20160303/
-rw-r--r-- root/root     22472 2019-11-19 04:09 ./usr/lib/php/20160303/rrd.so
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/20170718/
-rw-r--r-- root/root     22472 2019-11-19 04:09 ./usr/lib/php/20170718/rrd.so
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/lib/php/20180731/
-rw-r--r-- root/root     22472 2019-11-19 04:09 ./usr/lib/php/20180731/rrd.so
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/share/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/share/doc/
drwxr-xr-x root/root         0 2019-11-19 04:09 ./usr/share/doc/php-rrd/
-rw-r--r-- root/root      1073 2019-11-19 04:09 ./usr/share/doc/php-rrd/changelog.Debian.gz
-rw-r--r-- root/root      2644 2019-08-08 18:43 ./usr/share/doc/php-rrd/copyright

API version 20190902/ is missing

Actually this prevents me from upgrading to php 7.4 on my weatherstation. 

Would be great to have a new package.

Thanks a lot for your outstanding work.

**Comment by oerdnj** [comment]
Try it now, I see all the modules are built.

**Comment by fossibaer76** [comment]
Its working fine now. Thank you very much
