### ISSUE TITLE
Feature request: Upstream patch (bug 62044) Apache 2.4.46

### ISSUE THREAD

**Issue by iiPing** [oerdnj/deb.sury.org#1454]
**Frequently asked questions**

- [ x ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Yes, this is related to a bug filed at http://bz.apache.org/bugzilla/show_bug.cgi?id=62044 , TLDR if you have a lot of vhosts and loadbalancer the Apache will exceed the default Linux kernel max semaphore SEMVMX (sem.h) which is 32k  (32767) then apache will crash.

**Describe the solution you'd like**
Would like the newer patch to be added to your DPA and or PPA as the bug was marked as fix, so highly likely the upstream patch is already added but will be a batch update and might take some time for distributions to pickup the patch.

**Describe alternatives you've considered**
 1. Modifying sem.h with SEMVMX to 64k and recompiling the linux kernel.
 1. Use a different HTTP server.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```bash
apt-cache policy apache2
apache2:
  Installed: 2.4.46-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.4.46-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2.4.46-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.29-1ubuntu4.14 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     2.4.29-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Additional context**
I have recompiled the older Apache 2.4.43 and the issue was still present.

**Comment by oerdnj** [comment]
2.4.48 is now packaged, so this should resolve the issue.
