### ISSUE TITLE
PHP 7.1 and certain libraries not installing ARMv6 (cross compile for kerberos.io Docker image)

### ISSUE THREAD

**Issue by dbwest** [oerdnj/deb.sury.org#1455]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Hi, all. This bug happens when trying to do a Docker build for ARMv6 arch. The particular Docker build using sury.org for PHP packages and libraries. Specifically it tries to install PHP 7.1 with mcrypt and some other things on ARMv6 Debian Stretch.

**To Reproduce**
1. Clone https://github.com/kerberos-io/kerberos-docker.git
2. Use Docker Desktop (may need Edge version not stable) with Experimental Mode enabled for the following cross-compile build. Also possible with regular Docker-CE or Docker-EE on Linux?
3. 
```
docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d

docker buildx create --name nubuilder --driver docker-container

docker buildx use nubuilder

docker buildx inspect --bootstrap

docker buildx build --platform linux/arm/v6 -t kerberos-io-armv6 .
```
4. See error "packages not found from packages.sury.org" . If I change the PHP version to 7.3 it gets another error install PHP-mcrypt

**Expected behavior**
Docker Cross Build should create an image and should be able to find all needed packages for ARMv6 on packages.sury.org (provided you intend to support ARMv6 PHP7.1)

**Distribution (please complete the following information):**
 - OS: Debian Stretch and Stretch-Lite
 - Architecture: armv6
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
maybe packages were not genned for armv6 PHP 7.1?

**Comment by todeveni** [comment]
See #988

armv6 isn't supported, you need at least armv7-a

**Comment by dbwest** [comment]
why?
