### ISSUE TITLE
curl missing is missing on PHP 7.4 cli

### ISSUE THREAD

**Issue by umefarooq** [oerdnj/deb.sury.org#1456]
Hi i have updated PHP 7.4.9 from this repository. in my previous PHP 7.4.2 curl was missing completely, with this repository update php-curl is available i can see output in browser but on cli its still missing curl. Because of this problem i cannot run composer update as some packages need php-curl.

with following commands

`php -m `

and 

`php --ini`

no curl or /etc/php/7.4/cli/conf.d/20-curl.ini file

What i am doing wrong with this update.

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#what-to-report-in-the-issue-tracker

**Comment by umefarooq** [comment]
i have removed comment for curl in php.ini and it work fine for me
