### ISSUE TITLE
Feature Request: Enable PHP7 Huge Pages support

### ISSUE THREAD

**Issue by acsfer** [oerdnj/deb.sury.org#1459]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**

`./configure --enable-huge-code-pages  (... etc.)`

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Huge pages are enabled by default and also already enabled in the package, so I don't understand what is the problem here?
