### ISSUE TITLE
php7.0-common suggests php-user-cache, but this virtual package has no installation candidate

### ISSUE THREAD

**Issue by alexdenvir** [oerdnj/deb.sury.org#146]
Possible patch?:
[php7.0-common-php-user-cache.patch.txt](https://github.com/oerdnj/deb.sury.org/files/51963/php7.0-common-php-user-cache.patch.txt)

**Comment by oerdnj** [comment]
This will get fixed when php-apcu is packaged for php 7.0 since it will provide the virtual package.

**Comment by alexdenvir** [comment]
:+1: Fair enough :smile:
