### ISSUE TITLE
php7.x-redis missing?

### ISSUE THREAD

**Issue by DirkBlade** [oerdnj/deb.sury.org#1461]
**Frequently asked questions**

I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Applies to php7.0-redis to php7.4-redis
During `apt install 7.0-redis` 

> Note, selecting 'php-redis' instead of 'php7.0-redis'
> php-redis is already the newest version (5.3.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1)

(I assume php-redis is version 7.2 for this OS release.)

Followed by missing module when executing PHP
e.g.
`php7.0 -v`

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: undefined symbol: igbinary_serialize in Unknown on line 0
> PHP 7.0.33-30+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:47:32) ( NTS )

or
`php7.4 -v`

> PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/redis.so.so (/usr/lib/php/20190902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**To Reproduce**
```
apt install 7.0-redis 
php7.0 -v
```

**Expected behavior**
Version specific php-redis is installed e.g. php7.x-redis and php7.x is not missing module

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS (Bionic Beaver)
 - Architecture: amd64
 - Repository: Ubuntu PPA via add-apt-repository ppa:ondrej/php

**Package(s) (please complete the following information):**
Should be version specific, seems like only default 7.2 php-redis package exists

> php-redis:
>   Installed: 5.3.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
>   Candidate: 5.3.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
>   Version table:
>  *** 5.3.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1 500
>         500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
>         100 /var/lib/dpkg/status
>      3.1.6-1build1 500
>         500 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 Packages
>

**Comment by mfn** [comment]
`php-redis` contains multi-PHP-version modules for redis for PHP:
```
vagrant@swatio-dev /vagrant/tmp $ dpkg -L php-redis
/.
/etc
/etc/php
/etc/php/5.6
/etc/php/5.6/mods-available
/etc/php/5.6/mods-available/redis.ini
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/redis.ini
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/redis.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/redis.ini
/etc/php/7.3
/etc/php/7.3/mods-available
/etc/php/7.3/mods-available/redis.ini
/etc/php/7.4
/etc/php/7.4/mods-available
/etc/php/7.4/mods-available/redis.ini
/usr
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/redis.so
/usr/lib/php/20151012
/usr/lib/php/20151012/redis.so
/usr/lib/php/20160303
/usr/lib/php/20160303/redis.so
/usr/lib/php/20170718
/usr/lib/php/20170718/redis.so
/usr/lib/php/20180731
/usr/lib/php/20180731/redis.so
/usr/lib/php/20190902
/usr/lib/php/20190902/redis.so
/usr/share
/usr/share/doc
/usr/share/doc/php-redis
/usr/share/doc/php-redis/changelog.Debian.gz
/usr/share/doc/php-redis/copyright
```

**Comment by DirkBlade** [comment]
Apologies, didn't read the error properly as it seemed odd that there wasn't a specific package.

Error had :

> undefined symbol: igbinary_serialize

`apt-get install -y php-igbinary` sorted it - is that a missing dependency?

**Comment by todeveni** [comment]
> `apt-get install -y php-igbinary` sorted it - is that a missing dependency?

`php-redis` should depend on it already.

```
Version: 5.3.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
Depends: php-igbinary, phpapi-20190902 | phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226, libc6 (>= 2.14)
```

**Comment by DirkBlade** [comment]
Yes, dependency is on the package on my system so some sort of apt issue? Closing issue.  Thanks.
```
php-redis
  PreDepends: php-common
  Depends: php-igbinary

```
