### ISSUE TITLE
PHP 7.4.11 and PHP 7.3.23 for Debian

### ISSUE THREAD

**Issue by BrookeDot** [oerdnj/deb.sury.org#1462]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
[PHP 7.4.11](https://www.php.net/archive/2020.php#2020-10-01-2) was recently released, the [Ubuntu PPAs have been updated](https://launchpad.net/~ondrej/+archive/ubuntu/php), however, the Debian packages have not yet been built and are currently PHP 7.4.10 in Jenkins:
https://jenkins.rfc1925.org/view/PHP/

**Describe the solution you'd like**
Updated PHP Debian packages available from`packages.sury.org`

**Describe alternatives you've considered**

**Distribution:**
 - OS: **Debian 10.6**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
$ cat /etc/debian_version
10.6
```
 - Architecture: **AMD64**
```
$ uname -a
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
 - Repository: `deb https://packages.sury.org/php/ buster main`

**Package(s) (please complete the following information):**
```
apt-cache policy php7.4-common
php7.4-common:
  Installed: 7.4.10-1+0~20200909.25+debian10~1.gbpe666e1
  Candidate: 7.4.10-1+0~20200909.25+debian10~1.gbpe666e1
  Version table:
 *** 7.4.10-1+0~20200909.25+debian10~1.gbpe666e1 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Right, thanks for the poke, I forgot to schedule the builds. It has been very busy week for me.

**Comment by BrookeDot** [comment]
> I forgot to schedule the builds. It has been very busy week for me.

No worries, when I saw the Ubuntu builds come through I figured you were just busy and wanted to give it a few days to come through. Hopefully, you get some time to relax this weekend.
