### ISSUE TITLE
AH00052: child pid exit signal Segmentation fault

### ISSUE THREAD

**Issue by manfred77** [oerdnj/deb.sury.org#1463]
After updating php to the last and penultimate update, the server gives the following error:
[core:notice] [pid 27710] AH00052: child pid 2840 exit signal Segmentation fault (11).

The error repeats itself constantly until it stops working and the web pages are unresponsive.
The problem occurs randomly and it may take days or hours for it to fail again.

There is no clear record of the source of the failure, but it did happen after updating the php versions.
I have integrated apache with php, and I have several versions installed, but the sites respond to version 7.4

current configuration:
PHP 7.4.10 (cli) (built: Sep  9 2020 06:55:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

Server version: Apache/2.4.25 (Debian)
Server built:   2019-10-13T15:43:54

Linux mailserver 4.9.0-13-686-pae #1 SMP Debian 4.9.228-1 (2020-07-05) i686 GNU/Linux

I have looked for solutions, but it seems some conflict or error in php

**Comment by mfn** [comment]
See https://github.com/oerdnj/deb.sury.org/issues/300#issuecomment-196866807 as a guide how to debug this

**Comment by manfred77** [comment]
Thanks Markus, I had already seen that article and of course, in this case it would be best to debuggers to find the problem. However, he hoped to find something less invasive; something like updating some files or commands to run to solve the problem.
On the internet there are many reported cases, but none with a logical solution, others without a solution. I was hoping to find something more punctual on this website.
In any case, I will wait for new updates to fix the problem.

**Comment by oerdnj** [comment]
If the problem still happens we need more info and most likely this is upstream issue, but we can't know without backtrace with debugging symbols installed.
