### ISSUE TITLE
Dedicated repository for PHP version

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1467]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be a nice feature to have a dedicated repository for each PHP version - e.g.:
- PHP 7.1
- PHP 7.2
- PHP 7.3
- ...

**Describe alternatives you've considered**
Using `apt-mark hold xxx` but that does not always work so well.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: http://ppa.launchpad.net/ondrej/php/ubuntu focal main

**Comment by oerdnj** [comment]
It would also complicate the packaging a lot, so sorry, no, this is not going to happen.

**Comment by derritter88** [comment]
Okay thanks anyway for having a look.
Could you suggest any other possiblity to stick with one PHP version?

I have found `apt-mark hold` yesterday but Ubuntu still seems to "ignore" that as some e.g. PHP7.4 packages come as regular `php-xx` packages and Ubuntu installs them without any hickups.
