### ISSUE TITLE
apt warnings: "Ignoring Provides line with non-equal DepCompareOp for package phpX.X-yac"

### ISSUE THREAD

**Issue by candlerb** [oerdnj/deb.sury.org#1469]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
On Ubuntu 18.04, ondrej/php PPA is generating warnings when the list of packages is updated

**To Reproduce**
Starting with a fresh vanilla Ubuntu 18.04.5 container (can reproduce easily under lxd):
1. `add-apt-repository -y ppa:ondrej/php`
2. `apt-get update`

```
root@blah:~# apt-get update
Hit:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
W: Ignoring Provides line with non-equal DepCompareOp for package php5.6-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php7.0-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php7.1-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php7.2-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php7.3-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php7.4-yac
W: Ignoring Provides line with non-equal DepCompareOp for package php8.0-yac
root@blah:~#
```

**Expected behavior**
No packaging warnings to be shown

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Warning occurs even if no packages are installed, just the PPA

**Additional context**
N/A

**Comment by oerdnj** [comment]
Thanks, typo fixed in `php-yac_2.2.1+0.9.2-3`
