### ISSUE TITLE
You use libzip4, whereas Ubuntu 20.04 uses libzip5 : Problem with php7.4-zip

### ISSUE THREAD

**Issue by jradxl** [oerdnj/deb.sury.org#1470]
Ubuntu 20.04.1
If I add your repository I get this problem with php7.4-zip
If I purge all of PHP and return to the versions provide by Ubuntu I have no problems

I see that Ubuntu's PHP uses libzip5, whereas you use libzip4, and that might be related

 php --version
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib/php/20190902/zip.so (/usr/lib/php/20190902/zip.so: undefined symbol: zip_libzip_version), /usr/lib/php/20190902/zip.so.so (/usr/lib/php/20190902/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.11 (cli) (built: Oct 17 2020 07:30:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

Purge PHP with
sudo apt-get purge `dpkg -l | grep php| awk '{print $2}' |tr "\n" " "`

**Comment by oerdnj** [comment]
I created the issue templates for a reason, use them, so I don’t have to ask the questions that are already in there.

**Comment by xoroz** [comment]
sorry I happen to have the same problem...
I search in the FAQ but  Where can I find the issue templates!?
