### ISSUE TITLE
libtool broken since latest update (18 Oct)

### ISSUE THREAD

**Issue by simPod** [oerdnj/deb.sury.org#1472]
**Describe the bug**

libtool is somehow not working correctly in latest dist update from 18 Oct.

Eg. running `pecl install` with extension that requires build through libtool fails. I have created a minimal reproducible example.

```
#9 8.024 config.status: executing libtool commands
#9 8.083 running: make
#9 8.087 /bin/bash /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool --mode=compile cc  -I. -I/tmp/pear/temp/ds -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/include -I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/main -I/tmp/pear/temp/ds -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/ds/src/common.c -o src/common.lo
#9 8.115 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 933: X--mode=compile: command not found
#9 8.139 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1100: *** Warning: inferring the mode of operation is deprecated.: command not found
#9 8.141 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1101: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
#9 8.143 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: Xcc: command not found
#9 8.146 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I.: command not found
#9 8.149 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/ds: No such file or directory
#9 8.152 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-DPHP_ATOM_INC: command not found
#9 8.157 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/include: No such file or directory
#9 8.160 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/main: No such file or directory
#9 8.163 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/ds: No such file or directory
#9 8.166 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902: No such file or directory
#9 8.169 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/main: No such file or directory
#9 8.173 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/TSRM: No such file or directory
#9 8.176 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/Zend: No such file or directory
#9 8.180 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/ext: No such file or directory
#9 8.183 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/ext/date/lib: No such file or directory
#9 8.186 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-DHAVE_CONFIG_H: command not found
#9 8.190 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-g: command not found
#9 8.194 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-O2: command not found
#9 8.197 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-c: command not found
#9 8.200 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1297: Xsrc/common.lo: No such file or directory
#9 8.204 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1302: libtool: compile: cannot determine name of library object from `': command not found
#9 8.205 make: *** [Makefile:191: src/common.lo] Error 1
#9 8.206 ERROR: `make' failed
```

**To Reproduce**

```dockerfile
FROM debian:buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        gcc \
        gnupg2 \
        libtool \
        make

RUN curl -sS https://packages.sury.org/php/apt.gpg | apt-key add -
RUN echo 'deb https://packages.sury.org/php/ buster main' > /etc/apt/sources.list.d/deb.sury.org.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        php-pear \
        php7.4-cli \
        php7.4-dev

RUN pecl install ds
```

**Expected behavior**

No error

**Distribution (please complete the following information):**
 - OS: debian
 - Architecture: 🤷‍♀️ 
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

<details>
<summary>Log</summary>
 > [6/6] RUN pecl install ds:
#9 1.743 WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
#9 2.268 downloading ds-1.3.0.tgz ...
#9 2.268 Starting to download ds-1.3.0.tgz (52,494 bytes)
#9 2.395 .............done: 52,494 bytes
#9 2.597 96 source files, building
#9 2.598 running: phpize
#9 2.609 Configuring for:
#9 2.610 PHP Api Version:         20190902
#9 2.610 Zend Module Api No:      20190902
#9 2.610 Zend Extension Api No:   320190902
#9 3.532 building in /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0
#9 3.532 running: /tmp/pear/temp/ds/configure --with-php-config=/usr/bin/php-config
#9 3.723 checking for grep that handles long lines and -e... /bin/grep
#9 3.726 checking for egrep... /bin/grep -E
#9 3.737 checking for a sed that does not truncate output... /bin/sed
#9 3.750 checking for pkg-config... /usr/bin/pkg-config
#9 3.754 checking pkg-config is at least version 0.9.0... yes
#9 3.756 checking for cc... cc
#9 3.887 checking whether the C compiler works... yes
#9 3.887 checking for C compiler default output file name... a.out
#9 3.928 checking for suffix of executables...
#9 3.983 checking whether we are cross compiling... no
#9 4.019 checking for suffix of object files... o
#9 4.048 checking whether we are using the GNU C compiler... yes
#9 4.084 checking whether cc accepts -g... yes
#9 4.751 checking for cc option to accept ISO C89... none needed
#9 4.790 checking how to run the C preprocessor... cc -E
#9 4.834 checking for icc... no
#9 4.845 checking for suncc... no
#9 4.847 checking for system library directory... lib
#9 4.864 checking if compiler supports -R... no
#9 4.912 checking if compiler supports -Wl,-rpath,... yes
#9 5.011 checking build system type... x86_64-pc-linux-gnu
#9 5.011 checking host system type... x86_64-pc-linux-gnu
#9 5.011 checking target system type... x86_64-pc-linux-gnu
#9 5.110 checking for PHP prefix... /usr
#9 5.110 checking for PHP includes... -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib
#9 5.110 checking for PHP extension directory... /usr/lib/php/20190902
#9 5.110 checking for PHP installed headers prefix... /usr/include/php/20190902
#9 5.154 checking if debug is enabled... no
#9 5.193 checking if zts is enabled... no
#9 5.193 checking for gawk... no
#9 5.193 checking for nawk... nawk
#9 5.196 checking if nawk is broken... no
#9 5.197 checking whether to enable ds support... yes, shared
#9 5.615 checking how to print strings... printf
#9 5.616 checking for a sed that does not truncate output... (cached) /bin/sed
#9 5.621 checking for fgrep... /bin/grep -F
#9 5.630 checking for ld used by cc... /usr/bin/ld
#9 5.637 checking if the linker (/usr/bin/ld) is GNU ld... yes
#9 5.648 checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
#9 5.699 checking the name lister (/usr/bin/nm -B) interface... BSD nm
#9 5.699 checking whether ln -s works... yes
#9 5.707 checking the maximum length of command line arguments... 1572864
#9 5.713 checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
#9 5.713 checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
#9 5.714 checking for /usr/bin/ld option to reload object files... -r
#9 5.715 checking for objdump... objdump
#9 5.716 checking how to recognize dependent libraries... pass_all
#9 5.717 checking for dlltool... no
#9 5.718 checking how to associate runtime and link libraries... printf %s\n
#9 5.719 checking for ar... ar
#9 5.770 checking for archiver @FILE support... @
#9 5.771 checking for strip... strip
#9 5.772 checking for ranlib... ranlib
#9 5.773 checking for gawk... (cached) nawk
#9 5.876 checking command to parse /usr/bin/nm -B output from cc object... ok
#9 5.879 checking for sysroot... no
#9 5.889 checking for a working dd... /bin/dd
#9 5.895 checking how to truncate binary pipes... /bin/dd bs=4096 count=1
#9 5.920 checking for mt... no
#9 5.925 checking if : is a manifest tool... no
#9 6.087 checking for ANSI C header files... yes
#9 6.133 checking for sys/types.h... yes
#9 6.188 checking for sys/stat.h... yes
#9 6.232 checking for stdlib.h... yes
#9 6.275 checking for string.h... yes
#9 6.322 checking for memory.h... yes
#9 6.364 checking for strings.h... yes
#9 6.416 checking for inttypes.h... yes
#9 6.485 checking for stdint.h... yes
#9 6.556 checking for unistd.h... yes
#9 6.620 checking for dlfcn.h... yes
#9 6.629 checking for objdir... .libs
#9 6.780 checking if cc supports -fno-rtti -fno-exceptions... no
#9 6.780 checking for cc option to produce PIC... -fPIC -DPIC
#9 6.822 checking if cc PIC flag -fPIC -DPIC works... yes
#9 6.926 checking if cc static flag -static works... yes
#9 6.970 checking if cc supports -c -o file.o... yes
#9 6.970 checking if cc supports -c -o file.o... (cached) yes
#9 6.984 checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
#9 7.030 checking whether -lc should be explicitly linked in... no
#9 7.112 checking dynamic linker characteristics... GNU/Linux ld.so
#9 7.112 checking how to hardcode library paths into programs... immediate
#9 7.115 checking whether stripping libraries is possible... yes
#9 7.116 checking if libtool supports shared libraries... yes
#9 7.116 checking whether to build shared libraries... yes
#9 7.117 checking whether to build static libraries... no
#9 7.219 configure: patching config.h.in
#9 7.224 configure: creating ./config.status
#9 8.014 config.status: creating config.h
#9 8.024 config.status: executing libtool commands
#9 8.083 running: make
#9 8.087 /bin/bash /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool --mode=compile cc  -I. -I/tmp/pear/temp/ds -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/include -I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/main -I/tmp/pear/temp/ds -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/ds/src/common.c -o src/common.lo
#9 8.115 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 933: X--mode=compile: command not found
#9 8.139 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1100: *** Warning: inferring the mode of operation is deprecated.: command not found
#9 8.141 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1101: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
#9 8.143 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: Xcc: command not found
#9 8.146 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I.: command not found
#9 8.149 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/ds: No such file or directory
#9 8.152 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-DPHP_ATOM_INC: command not found
#9 8.157 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/include: No such file or directory
#9 8.160 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/main: No such file or directory
#9 8.163 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/tmp/pear/temp/ds: No such file or directory
#9 8.166 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902: No such file or directory
#9 8.169 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/main: No such file or directory
#9 8.173 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/TSRM: No such file or directory
#9 8.176 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/Zend: No such file or directory
#9 8.180 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/ext: No such file or directory
#9 8.183 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-I/usr/include/php/20190902/ext/date/lib: No such file or directory
#9 8.186 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-DHAVE_CONFIG_H: command not found
#9 8.190 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-g: command not found
#9 8.194 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-O2: command not found
#9 8.197 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1244: X-c: command not found
#9 8.200 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1297: Xsrc/common.lo: No such file or directory
#9 8.204 /tmp/pear/temp/pear-build-defaultuserj3uJL1/ds-1.3.0/libtool: line 1302: libtool: compile: cannot determine name of library object from `': command not found
#9 8.205 make: *** [Makefile:191: src/common.lo] Error 1
#9 8.206 ERROR: `make' failed
</details>

**Comment by oerdnj** [comment]
Dup of #1471

**Comment by oerdnj** [comment]
Fixed in `php7.4_7.4.11-6` and `php8.0_8.0.0~rc1-6` (just uploaded and building).
