### ISSUE TITLE
In php7.1-dev, phpize --clean also delete files provided by libtool package

### ISSUE THREAD

**Issue by aleroyer** [oerdnj/deb.sury.org#1474]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Since [this commit](https://salsa.debian.org/php-team/php/-/commit/5be5d8429a95ebbb2cc4c268234440f235dae5bc#b38975f1cd4d213236183ae11dc46f7826820447), when you run `phpize --clean` it also delete files provided by `libtool` package.
You then need to reinstall `libtool` to get those files back.

Tested on Debian 9 and 10 with PHP 7.1. I didn't have the bug with 7.4.

**To Reproduce**
1. Use a user that have enough privileges to delete something in `/usr` (try that in a container)
2. `ls /usr/share/libtool/build-aux/ltmain.sh`
3. In a php extension source directory, `phpize --clean`
4. `ls /usr/share/libtool/build-aux/ltmain.sh` return not found

**Expected behavior**

Do not delete files provided by libtool package.

**Distribution (please complete the following information):**
 - OS: Debian 9 and 10
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
- php7.1-dev

**Additional context**
N/A

**Comment by oerdnj** [comment]
Running phpize as root is really bad practice. Nevertheless it’s fixed as of the last upload.
