### ISSUE TITLE
PECL broken after recent update for PHP 5.6 to PHP 7.3 on Ubuntu

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1478]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Installing extensions via PECL is not working.
For example pecl install -f xdebug gives the following error
```configure: error: cannot run /bin/bash /tmp/pear/temp/xdebug/config.sub```
https://github.com/shivammathur/test-setup-php/runs/1336323786?check_suite_focus=true#step:5:37

**To Reproduce**
1. Update lists and install `php7.3`, `php7.3-dev`, `php7.3-xml` and `php-pear`.
2. Then run `pecl install -f xdebug`
4. See error `cannot run /bin/bash /tmp/pear/temp/xdebug/config.sub`

**Expected behavior**
It should install the extension via `PECL`.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: `amd64`
 - Repository: `Ubuntu PPA`

**Package(s) (please complete the following information):**
```
php7.3:
  Installed: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 7.3.24-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
php7.3-dev:
  Installed: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 7.3.24-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
php7.3-xml:
  Installed: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 7.3.24-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 7.3.24-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
php-pear:
  Installed: 1:1.10.12+submodules+notgz-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 1:1.10.12+submodules+notgz-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 1:1.10.12+submodules+notgz-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.10.9+submodules+notgz-1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by oerdnj** [comment]
Thanks for the report, I have a bad day, but I think the latest upload should fix this.

The decision to copy these files into PHP distribution just so people don't have to install three extra packages (libtool, shtool and pkg-config) wasn't really the greatest of them all, but given the tendency to bundle everything in PHP sources it's not really surprising.

**Comment by shivammathur** [comment]
@oerdnj Thanks for fixing it again very quickly.
