### ISSUE TITLE
php7 mysqli library on ubuntu

### ISSUE THREAD

**Issue by iwelch** [oerdnj/deb.sury.org#148]
I just installed the "dual" version, and php7 core works just great on ubuntu 15.10.

alas, except mysqli is not part of it, I think.  could you please add to the installation instructions a note on how to add mysqli for php7 when updating a ubuntu system?

regards,

/iaw

**Comment by oerdnj** [comment]
Install php-mysql? 

On 4 Dec 2015, ivo welch <notifications@github.com> wrote:
>
>I just installed the "dual" version, and php7 core works just great on
>ubuntu 15.10.
>
>alas, except mysqli is not part of it, I think.  could you please add
>to the installation instructions a note on how to add mysqli for php7
>when updating a ubuntu system?
>
>regards,
>
>/iaw
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/148

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by iwelch** [comment]
funny.  mysqli was previously installed and running on the same machine (php5, of course).  http://stackoverflow.com/questions/7250356/how-to-install-mysqli doesn't have much info, but says that mysqli should be part of php.  alas, this is now php7.  how about a hint?  ;-)

**Comment by iwelch** [comment]
but of course, never mind, as my 15 attempts earlier failed, but apt-get install php-mysql did the job.  argh
