### ISSUE TITLE
x86_64 Debian 10: php8.0-redis package is missing

### ISSUE THREAD

**Issue by brainexe** [oerdnj/deb.sury.org#1480]
**Frequently asked questions**
- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
First thx for providing the PHP8.0 packages already! 

But at least one package seems to be missing on Debian: *php8.0-redis*

**To Reproduce**
- use `debian:buster-slim` docker image
- add `deb https://packages.sury.org/php/ buster main` source properly
- `apt install php8.0-redis`
-> `Couldn't find any package by glob 'php8.0-redis'`

```
apt-cache policy php8.0-redis
N: Unable to locate package php8.0-redis
N: Couldn't find any package by glob 'php8.0-redis'
N: Couldn't find any package by regex 'php8.0-redis'
```

**Expected behavior**
Have the php8.0-redis package available

**Distribution (please complete the following information):**
 - OS: Debian (`debian:buster-slim` docker image)
 - Architecture: amd64
 - Repository: `deb https://packages.sury.org/php/ buster main` 

**Packages**
```
apt-cache policy php8.0-redis
N: Unable to locate package php8.0-redis
N: Couldn't find any package by glob 'php8.0-redis'
N: Couldn't find any package by regex 'php8.0-redis'
```

**Additional context**
- on `ubuntu:xenial` it works fine with the `ppa:ondrej/php`
- Some examples which are working already quite fine: php8.0-xdebug php8.0-bcmath php8.0-pgsql php8.0-dom php8.0-curl

**Comment by EdisonJwa** [comment]
seems the name is `php-redis`

**Comment by brainexe** [comment]
hey @oerdnj! 
Any rough idea when this extension could be added?

**Comment by SeinopSys** [comment]
I am also looking for the redis package and not able to find it unfortunately

**Comment by marmichalski** [comment]
This package is available for a few days now. You might want to check and close this issue 😎

**Comment by brainexe** [comment]
indeed, it's looking fine now :nerd_face: 

```bash
docker run --rm -it debian:buster-slim
...
root@8def1907ffa6:/# apt-cache policy php8.0-redis
php8.0-redis:
  Installed: (none)
  Candidate: 5.3.2+4.3.0-1+0~20201207.28+debian10~1.gbp404a40
  Version table:
     5.3.2+4.3.0-1+0~20201207.28+debian10~1.gbp404a40 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
