### ISSUE TITLE
php7.4-redis module upgraded to RC version

### ISSUE THREAD

**Issue by vigneshgurusamy** [oerdnj/deb.sury.org#1481]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
`php7.4-redis` installs a RC version instead of stable version.

**To Reproduce**
- `add-apt-repository -y ppa:ondrej/php && apt update`
- `apt install php7.4-redis`

**Expected behavior**
I expect the command to install stable version of `php-redis`

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04 & 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA (ppa:ondrej/php)

**Package(s) (please complete the following information):**
```sh
root@4fff307903d5:/var/www# apt-cache policy php7.4-redis
php7.4-redis:
  Installed: 5.3.2~rc1+4.3.0-2+ubuntu20.04.1+deb.sury.org+4
  Candidate: 5.3.2~rc1+4.3.0-2+ubuntu20.04.1+deb.sury.org+4
  Version table:
 *** 5.3.2~rc1+4.3.0-2+ubuntu20.04.1+deb.sury.org+4 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by oerdnj** [comment]
> I expect the command to install stable version of php-redis

There's no such guarantee provided in the repository.

**Comment by vigneshgurusamy** [comment]
@oerdnj is there any way to control the installation only to stable release?
