### ISSUE TITLE
Ubuntu 18.04 Loading PHP7.4-zip fails

### ISSUE THREAD

**Issue by Ponyboy47** [oerdnj/deb.sury.org#1483]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The php 7.4 zip module on Ubuntu 18.04 does not work for me. Running any php command with the zip module installed results in the following warning:
```
$ php7.4 -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib/php/20190902/zip.so (/usr/lib/php/20190902/zip.so: undefined symbol: zip_libzip_version), /usr/lib/php/20190902/zip.so.so (/usr/lib/php/20190902/zip.so.so: cannot open shared object file:
No such file or directory)) in Unknown on line 0
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```
And `php7.4 -m` does not report that the zip module is installed.

**To Reproduce**
1. Install Ubuntu 18.04
2. Add the PPA: `sudo apt-add-repository ppa:ondrej/php`
3. Install php 7.4 with the zip module: `sudo apt install php7.4 php7.4-zip php7.4-cli`
4. Try running php: `php7.4 -v`
5. See error

**Expected behavior**
Installing the zip module should not cause runtime errors and `php7.4 -m` should report that the zip module is correctly loaded/installed.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: x86-64
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**
```
$ apt-cache policy php7.4-zip
php7.4-zip:
  Installed: 7.4.12-3+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.4.12-3+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.4.12-3+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
I tried installing `php7.3-zip`, `php7.4-zip`, and `php8.0-zip`, but all resulted in the same warning message.

I have been using php 7.2, but today I was upgrading to 7.4 when I encountered the issue.

Manually compiling the zip module with `pecl install zip` resolves the issue, but this shouldn't be necessary IMO.

**Comment by oerdnj** [comment]
What is the output of `ldd /usr/lib/php/20190902/zip.so`?

My guess is that you have extra libzip library in `/usr/local`

**Comment by oerdnj** [comment]
Closing as there's no response from OP.
