### ISSUE TITLE
Debian 9.x and multiple versions...

### ISSUE THREAD

**Issue by christophenouvel** [oerdnj/deb.sury.org#1484]
Hi,

I'm trying to use multi php versions via php-fpm on Debian 9.x.

But I do not want to break anything, so I want to keep php 7.0 as a default version for any existing virtualhost, or any new virtualhost which declares nothing about a specific php version.

php 7.0 works as Apache module, and php 7.1, 7.2, 7.3 and 7.4 as php-fpm packages.

All is working as expected :
old sites are php 7.0,
sites defining for example :

        <FilesMatch \.php$>
                # For Apache version 2.4.10 and above, use SetHandler to run PHP as a fastCGI process server
                SetHandler "proxy:unix:/run/php/php7.3-fpm.sock|fcgi://localhost"
        </FilesMatch>
will run with php 7.3.

Perfect.

But, if I try to install php8.0-fpm, it become mandatory version, for each and every site? Old ones, or those specifyong a specific version?

I missed something?

  Thank you,

    Christophe.

**Comment by oerdnj** [comment]
I am sorry, but I don't have time to answer questions. You should try it in a chroot/docker/container and see yourself.
