### ISSUE TITLE
Upgrade nginx mainline to 1.19.5

### ISSUE THREAD

**Issue by GregOriol** [oerdnj/deb.sury.org#1488]
- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

Hi,

Could you upgrade nginx mainline to the latest 1.19.5?
It seems that the ppa is now a few versions behind at 1.19.0.

**Comment by oerdnj** [comment]
Should be done together with some of the external modules refresh.
