### ISSUE TITLE
Are there plans to support gmagick in PHP8?

### ISSUE THREAD

**Issue by leofeyer** [oerdnj/deb.sury.org#1489]
Hi Ondřej, are there any plans to support PHP 8 in the `php-gmagick` package in the future? It is a great imagick alternative and you have already made packages for PHP 7 so I figured I ask. 😊 

Thank you and keep up the good work.

**Comment by oerdnj** [comment]
Sure, when there's upstream support for it.

**Comment by leofeyer** [comment]
Great. Thanks Ondřej.
