### ISSUE TITLE
/var/lib/php/sessions

### ISSUE THREAD

**Issue by iwelch** [oerdnj/deb.sury.org#149]
probably needs to be oug+rw or owned by the right party.  this can easily be done by hand, and/or by script request.

**Comment by joppuyo** [comment]
Can confirm, sessions stopped working after I updated to PHP 7. Running `chmod oug+rw` on the session directory fixed the issue.

**Comment by mpalourdio** [comment]
chmod 1733 fixed the session problem too here after upgrading to php7

**Comment by oerdnj** [comment]
Folks, don't do ugo+rw, this is horribly insecure; I'll fix this and release fixed version after the weekend.

Cheers,
Ondrej

**Comment by oerdnj** [comment]
This has been fixed in -3

**Comment by mpalourdio** [comment]
Thanks ! You're doing a very appreciated job !
