### ISSUE TITLE
php-memcache for 7.4

### ISSUE THREAD

**Issue by alek13** [oerdnj/deb.sury.org#1491]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Problem**
Can't upgrade to 7.4.

Seems like extension **`php-memcache`** have no version for php **`7.4`**.
PHP Error:
```
Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20190902/memcache.so (/usr/lib/php/20190902/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/memcache.so.so (/usr/lib/php/20190902/memcache.so.so: cannot open shared object
```
When trying to `# apt install php-memcache` got "already installed" `4.0.5.2+3.0.9~20170802.e702b5f9-1+0~20200303.14+debian10~1.gbp6b104d`  

When trying to `# apt install php7.4-memcache` got:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting «php-memcache:amd64» instead of «php7.4-memcache:amd64»
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php-memcache:amd64 : Pre-Depends: php-common:amd64 (>= 2:69~) but it can not be installed
                      Depens: phpapi-20190902:amd64 or
                                      phpapi-20180731:amd64 or
                                      phpapi-20170718:amd64 or
                                      phpapi-20160303:amd64 or
                                      phpapi-20151012:amd64 or
                                      phpapi-20131226:amd64
E: Unable to correct problems, you have held broken packages.
```

And finally `php-memcache` does not provide `php7.4-memcache`:
```
    # apt show php-memcache
    Package: php-memcache
    Version: 4.0.5.2+3.0.9~20170802.e702b5f9-1+0~20200303.14+debian10~1.gbp6b104d
    Priority: optional
    Section: php
    Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
    Installed-Size: 684 kB
>>> Provides: php5.6-memcache, php7.0-memcache, php7.1-memcache, php7.2-memcache, php7.3-memcache    <<<
    Pre-Depends: php-common (>= 2:69~)
    Depends: phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226, libc6 (>= 2.25), zlib1g (>= 1:1.1.4)
    Suggests: memcached
    Homepage: https://github.com/websupport-sk/pecl-memcache
    Download-Size: 126 kB
    APT-Manual-Installed: yes
    APT-Sources: https://packages.sury.org/php buster/main i386 Packages
    Description: memcache extension module for PHP
     Memcached is a caching daemon designed especially for dynamic web applications
     to decrease database load by storing objects in memory.
     .
     This extension allows you to work with memcached through handy OO and
     procedural interfaces in your php5 applications.
     .
     This is an updated version for PHP 7 with non-blocking I/O taken from
     https://github.com/websupport-sk/pecl-memcache
```

**Distribution (please complete the following information):**
 - OS: [Debian 10 buster]
 - Architecture: [amd64]
 - Repository: [deb https://packages.sury.org/php/ buster main]

**Comment by tvvpm** [comment]
You have to use php-memcached ... ending with d. As far as I know development of php-memcache has been abandoned

**Comment by alek13** [comment]
@tvvpm Code of my projects use exactly `php-memcache` (without 'd').
[Release 4.0.5.2 (of `php-memcache`)](https://pecl.php.net/package/memcache) - was builded for php 7+.
We need just add it to `7.4` (like it was added to `7.0`, `7.1`, `7.2` & `7.3`)

**Comment by jult** [comment]
Same goes for php-imagick, php-dev and a couple of other php7.4 modules. Can't get them installed in debian 10 using sury's repo.

**Comment by oerdnj** [comment]
The memcache has been updated with PHP 8.0 support and with that the `php7.4-memcache` is also back.

**Comment by oerdnj** [comment]
> Same goes for php-imagick, php-dev and a couple of other php7.4 modules. Can't get them installed in debian 10 using sury's repo.

@jult, don't do this. This issue was about `php7.4-memcache`, adding more noise is not helpful.

**Comment by alek13** [comment]
@oerdnj thanx a lot
