### ISSUE TITLE
php-redis and more depend on all available version of php

### ISSUE THREAD

**Issue by jeensg** [oerdnj/deb.sury.org#1495]
**Frequently asked questions**

- [ x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When upgrading php-redis on a server, multiple versions of the package are to be installed: php5.6-redis, php7.0-redis, php7.1-redis, php7.2-redis, php7.3-redis, php7.4-redis, php8.0-redis
This seems to be for the following meta-packages as well: php-igbinary, php-memcache, php-apcu

**To Reproduce**
1. apt install php-redis (example)
Result: "The following additional packages will be installed:
  php5.6-igbinary php5.6-redis php7.0-igbinary php7.0-redis php7.1-igbinary php7.1-redis php7.2-igbinary php7.2-redis php8.0-igbinary php8.0-redis"

**Expected behavior**
Only packages for installed versions are a dependency.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
apt policy php-redis:
php-redis:
  Installed: (none)
  Candidate: 5.3.2+4.3.0-1+0~20201207.27+debian9~1.gbp404a40
  Version table:
     5.3.2+4.3.0-1+0~20201207.27+debian9~1.gbp404a40 900
        900 https://packages.sury.org/php stretch/main amd64 Packages
     4.2.0-1 750
        750 http://ftp.de.debian.org/debian buster/main amd64 Packages

**Comment by oerdnj** [comment]
As described here https://www.patreon.com/posts/october-update-42636315 and beaten to death here: https://github.com/oerdnj/deb.sury.org/issues/1465

**Comment by jeensg** [comment]
So this is embarassing. Thanks for the hint and the well-explained 
pages. Regards.

Am 07.12.20 um 12:40 schrieb Ondřej Surý:
> As described here https://www.patreon.com/posts/october-update-42636315 and beaten to death here: https://github.com/oerdnj/deb.sury.org/issues/1465
>
