### ISSUE TITLE
php-memcached for PHP 8.0

### ISSUE THREAD

**Issue by xPaw** [oerdnj/deb.sury.org#1496]
I think it needs to be built from git, as far as I can tell the repo is actually ready for it:

https://github.com/php-memcached-dev/php-memcached/issues/466

**Comment by oerdnj** [comment]
The issue templates are there for reason, you know, so at least I would know what distro and package version you are talking about.

(The Debian packages are just rebuilding, and it's already in the Ubuntu packages.)

**Comment by xPaw** [comment]
May I suggest making a issue template for missing packages? There's quite a few open issues like that.

It didn't click for me that this would be considered a bug report. And my bad, it was indeed for Debian.

**Comment by xPaw** [comment]
Can confirm the php-memcached supports php8 now. Thanks!
