### ISSUE TITLE
Xdebug major version change with latest update

### ISSUE THREAD

**Issue by Ddcdom** [oerdnj/deb.sury.org#1497]
I'm uncertain if this is a bug or intended behaviour.

1. Updated copy Ubuntu 20.04
2. Have previously installed php-xdebug from ppa:ondrej/php 
3. update packages

**Expected behavior**
Expect PHP xdebug to stay within the same major vestion

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - amd64
 - Ubuntu PPA

**Package(s) (please complete the following information):**
php-xdebug:
  Installed: 3.0.1+2.9.8+2.8.1+2.5.5-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 3.0.1+2.9.8+2.8.1+2.5.5-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 3.0.1+2.9.8+2.8.1+2.5.5-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.2+2.8.1+2.5.5-1build1 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages

**Comment by oerdnj** [comment]
> Expect PHP xdebug to stay within the same major vestion

No, this was never guaranteed.
