### ISSUE TITLE
[feature request] Support multiple PHP versions installed (PHP 5.x co-installability)

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#15]
[This is something like a personal's bounty program. Please only respond if you want to pledge, I will delete all other comments not related to pledge.]

PHP 5.x co-installability is a big task in Debian. All packages would have to be renamed from php5 to php5.x, all conflicting binaries would have to be renamed and an /etc/alternatives/ system would have to be used to select the default PHP version.

But that's the smaller part - the supporting infrastructure (namely dh_php5 and php5-maintscript-helper) would have to be modified to support multiple PHPAPI versions to allow compiling all external (and internal) PHP modules for all supported PHP versions.

Since this is by no means an easy task and it will consume a lot of time, I am asking for a pledges to support. It's up to you whether you [donate](https://deb.sury.org/pages/donate.html) now or after the task is complete , but if you just pledge to support here, I expect you will live up to your word and make the donation.

The minimum amount to implement this feature is 1000 EUR.

**Comment by pbowyer** [comment]
It's sad to see how few people are interested. Have people found an alternative way to run multiple PHP versions side-by-side?

**Comment by bcremer** [comment]
@pbowyer 
For our CI-Machines we run custom PHP-Builds that we build with https://github.com/CHH/php-build and manage with https://github.com/CHH/phpenv.

**Comment by JeGr** [comment]
@oerdnj A problem we currently encounter more and more with new customers is that they are forced to run old PHP versions as they run crypted s*** with old ZendGuard versions, that require e.g. PHP 5.3. So we have 2015, could setup Ubuntu 14.04 or Debian Jessie but both come with PHP versions, that are too new. So we are pushed into installing 12.04 LTS and hope to get them to change/upgrade next year.
Would it be a possibility - if we could donate you - to have a PHP 5.3 version for Ubuntu Trusty (14.04)? Or the even greater luck and possibility of interoperability of different versions (say: like the centos /opt packages that install PHP variants into /opt to have multiple ones on you machine for test reasons)?

I'm sure I could get my company to donate for that purpose (and avoid the mess of having to build a multitude of php versions ourselves).

**Comment by oerdnj** [comment]
@JeGr Do you really need a prepackaged version of PHP in this case? I understand your troubles (I worked for hosting company some years ago), but I would really hate porting old software that's no longer supported and plagued by security issues that won't get fixed to new versions of Ubuntu. It could be done for sure, but it shouldn't be available for general public. Feel free to contact me off-list...

I am foreseeing that the co-installability won't hit anything older than PHP 5.6 or perhaps even PHP 7. There's a GSoC student that has this as a project for this year GSoC, so we'll see in few months how it went.

**Comment by JeGr** [comment]
@oerdnj Thanks for allowing to contact you off list. Have done so yesterday, perhaps you have a few minutes for that. My idea for an "old" build of PHP 5.3 for trusty was to take the last version and use the Debian & Ubuntu Patches from the packages from Precise, that the security team is still bringing until 2017. Wouldn't that be an adequate intermediate solution until Precise EOL to have the old version running "relatively" safe?

**Comment by pbowyer** [comment]
@JeGr A packaged version of PHP 5.3 would really help us too, we have a number of applications that for various client-and-framework-related reasons have not been overhauled to work on PHP 5.5+. Being able to move forward from Ubuntu 12.04 would be great.

**Comment by JeGr** [comment]
@pbowyer I absolutely agree, it's only PHP blocking the path to other applications. Apache2.4/Nginx/MySQL/MariaDB would be great to have in their new incarnations (especially Apache 2.4 is a nice step up in performance), but having to cling on old frameworks or crypted ZendGuard things from developers, that won't update their application to ZendGuard7/PHP5.5 is a huge PITA.

**Comment by oerdnj** [comment]
@pbowyer @JeGr Gentlemen, let's move it to #79, please.

**Comment by foxycode** [comment]
@oerdnj How's the status? Do you still need donations on this? How much?

**Comment by oerdnj** [comment]
@foxycode There's a basic work done for PHP 7.0; I am working on splitting and building modules from a separate package. Right now PHP 7.0 build is broken :), but I am spending some cycles this week to unbreak it. Nobody committed donation specifically towards this goal, so it progresses on its own pace as I have a time. As always if you use this and can afford to donate, please do so.

**Comment by foxycode** [comment]
@oerdnj I am not much interested in PHP 7 right now. I'd like to have PHP 5.4, 5.5 and 5.6 installable this way and I am willing to donate some money to make it happen. Any chances you put yourself into it?

**Comment by oerdnj** [comment]
@foxycode PHP 7.0 packaging is a testbed to prepare new packaging infrastructure, as soon as the dust settles I will convert at least PHP 5.5 and PHP 5.6 to the new infrastructure.

Not sure about PHP 5.4 as its security support will end in one month: http://php.net/supported-versions.php

**Comment by foxycode** [comment]
@oerdnj I can donate some money on my own or I can send higher donation from my company if you can provide deed of gift.

**Comment by oerdnj** [comment]
@foxycode I can issue invoices just fine for higher amounts.

**Comment by foxycode** [comment]
@oerdnj So please send one for 3000 CZK to Sunfox s.r.o. (sunfox at sunfox dot cz)
https://or.justice.cz/ias/ui/rejstrik-$firma?nazev=sunfox

**Comment by oerdnj** [comment]
@foxycode thanks

**Comment by foxycode** [comment]
@oerdnj How it goes? Any milestone in front of you?

**Comment by oerdnj** [comment]
php7.0 and php5.6 builds and can coexist, but I want to rehaul the module building one more time before moving this from Debian experimental to unstable. I am going to move the module building back to src:phpX.Y packages for the core modules.

**Comment by oerdnj** [comment]
The coinstallable versions could be found here: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by oerdnj** [comment]
Fixed including most of the modules.

**Comment by foxycode** [comment]
Great job!

**Comment by oerdnj** [comment]
Just wanted to add that I have added PHP 5.5 into the crowd including full PECL extensions support. More details here: https://www.patreon.com/posts/php-5-5-hit-ppa-5222006
