### ISSUE TITLE
Installing PEAR from php-7.0 on Ubuntu 14.04

### ISSUE THREAD

**Issue by netpalantir** [oerdnj/deb.sury.org#150]
Hello,

thank you for the great job! I was just wondering whether it is just me having problems installing PEAR from the php-7.0 repository on Ubuntu Trusty?

I am trying to install php-pear version 1:1.10.1+submodules+notgz-2+deb.sury.org~trusty+1, what I get is a bunch of broken packages:

```
The following packages have unmet dependencies:
 php-pear : Depends: php5-cli but it is not going to be installed
            Depends: php5-common (>= 5.4.0) but it is not going to be installed
            Depends: php-structures-graph (>= 1.1.0) but it is not installable
            Depends: php-console-getopt (>= 1.4.1) but it is not installable
            Depends: php-xml-util (>= 1.3.0)
E: Unable to correct problems, you have held broken packages.
```

PHP 7 itself works great.

Thanks for any suggestion!

**Comment by blahblah88881** [comment]
same issue on ubuntu 15.10 vanilla installation.

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 php-pear : Depends: php-structures-graph (>= 1.1.0) but it is not installable
            Depends: php-console-getopt (>= 1.4.1) but it is not installable
            Depends: php-xml-util (>= 1.3.0)
E: Unable to correct problems, you have held broken packages.

**Comment by andriiabaimov** [comment]
Same problem, please fix it.

**Comment by andriiabaimov** [comment]
Temporary fix:

**sudo apt-get download php-pear=1:1.10.1+submodules+notgz-3+deb.sury.org~trusty+1**

and then:

**sudo dpkg --ignore-depends=php-structures-graph,php-console-getopt,php-xml-util -i php-pear_1%3a1.10.1+submodules+notgz-3+deb.sury.org~trusty+1_all.deb**

But now **sudo apt-get -f install** suggests to remove php-pear.

**Comment by oerdnj** [comment]
Should be fixed now.
