### ISSUE TITLE
php-imagick has dependency for all php-version packages

### ISSUE THREAD

**Issue by keigel2001** [oerdnj/deb.sury.org#1500]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
After your recent change to add imagick to PHP 8.0 the package `php-imagick` now has dependency for all php-version packages. This is different to the previous behaviour.
I had installed `php7.4-imagick` and was quite surprised when it updated and also wanted to install `php5.6-imagick`, `php7.0-imagick`, `php7.1-imagick`, `php7.2-imagick`, `php7.3-imagick`, `php8.0-imagick`.

Is this change intentional or is it a bug?

**To Reproduce**
```
apt install php7.4-imagick

apt-cache depends php7.4-imagick
php7.4-imagick
  PreDepends: php-common
  Depends: libc6
  Depends: libmagickcore-6.q16-6
  Depends: libmagickwand-6.q16-6
  Breaks: php-imagick
  Recommends: ghostscript
  Recommends: ttf-dejavu-core
  Replaces: php-imagick

apt-cache depends php-imagick
php-imagick
  PreDepends: php-common
  Depends: php8.0-imagick
  Depends: php7.4-imagick
  Depends: php7.3-imagick
  Depends: php7.2-imagick
  Depends: php7.1-imagick
  Depends: php7.0-imagick
  Depends: php5.6-imagick
  Recommends: ghostscript
  Recommends: ttf-dejavu-core
```

**Expected behavior**
Installtion of  `php7.4-imagick` doesn't add `php5.6-imagick`, `php7.0-imagick`, `php7.1-imagick`, `php7.2-imagick`, `php7.3-imagick`, `php8.0-imagick`.

**Distribution (please complete the following information):**
 - OS: Debian Buster
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php-imagick:
  Installed: 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e
  Candidate: 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e
  Version table:
 *** 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.3-4.1 500
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
```
```
php7.4-imagick:
  Installed: 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e
  Candidate: 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e
  Version table:
 *** 3.4.4-10+0~20201209.22+debian10~1.gbp2e170e 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
As described here https://www.patreon.com/posts/october-update-42636315 and beaten to death here: #1465
