### ISSUE TITLE
PHP-fpm 8.0 segfaut on wordpress 5.6

### ISSUE THREAD

**Issue by yodatak** [oerdnj/deb.sury.org#1501]
**Frequently asked questions**

- [ X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When i php-fpm + PHP 8.0  on a wordpress 5.6   i got a segfault and no page when i hit the webpage

I got this error 

Dec 10 01:16:58 . kernel: php-fpm8.0[5517]: segfault at 5583cf033c54 ip 00005583cf033c54 sp 00007fffd86adbe0 error 14
Dec 10 01:16:58  kernel: Code: Bad RIP value.

**To Reproduce**
1. Install php-fpm8.0 on debian 10
2. On a wordpress 
3. Hit the webpage

**Expected behavior**
Don't segfault

**Distribution (please complete the following information):**
 - OS:  Debian 10.7
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
apt-cache policy php8.0-fpm
php8.0-fpm:
  Installed: 8.0.0-1+0~20201206.6+debian10~1.gbp33744b
  Candidate: 8.0.0-1+0~20201206.6+debian10~1.gbp33744b
  Version table:
 *** 8.0.0-1+0~20201206.6+debian10~1.gbp33744b 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
This issue in unlikely related to the packaging. You need to report this to the PHP directly: https://bugs.php.net/bugs-generating-backtrace.php
