### ISSUE TITLE
php7.4-fpm segmentation fault on Debian 9 (stretch)

### ISSUE THREAD

**Issue by vegnuli** [oerdnj/deb.sury.org#1506]
**i dont know if the problem is the php-pecl-http BUT WITH DEBIAN NORMAL PACKAGES IT WORKS (tested in debian jessie, stretch and buster with respective versions.. but with sury versions does not works)**

i got a segfault only when i setup php fpm with apache but not with lighttpd (but with this i got end of file descriptors.. using normal php7.0 from debian working very stable)

```
WARNING: [pool www] child 4319 exited on signal 11 (SIGSEGV) after 1800.
162054 seconds from start

[1026369.614673] php-fpm7.4[34794]: segfault at 679deb21 ip 00005631c46d76bf sp 00007ffd18d90390 error 4 in php-fpm7.4[5631c4529000+3cb000]
```

alfter some debug i found is related to this error: https://github.com/oerdnj/deb.sury.org/issues/1360#issue-583326189 and specially this https://github.com/oerdnj/deb.sury.org/issues/1442

about the second one i setup a php 5.6 and found that with apache got a segfault in 
`[1026950.392088] /usr/sbin/apach[34726]: segfault at 7fbae6f167a0 ip 00007fbae6f167a0 sp 00007ffc24cd7948 error 14 in libexpat.so.1.6.2[7fbae97b0000+27000]`

very different rather than with php 7.4 but in lighttpd does not got that error, but after some hopurs of setup i got out of file descriptors.. with segfault

**Comment by vegnuli** [comment]
so then i unninstall any php-pecl sury package and it works.. the bug is only in sury package.. cos from debian it works flameless, so in my case remove **php5.6-pecl php7.4-pecl** and works.. is a sury package that has the bug not the **php-pecl-http** as it said

**Comment by oerdnj** [comment]
dup of #1442
