### ISSUE TITLE
Php8 - Some problems to send mail over SMTP

### ISSUE THREAD

**Issue by omexlu** [oerdnj/deb.sury.org#1507]
Hello, 

First of all thanks for your great work. 

I have some strange behavior after updating from 7.4.13 to 8.0.0 over your repository. 

I use WoltLab framework as community software, in 7.4.13 the mails send over stmp (build-in mailer) get send correctly but if I switch to 8.0.0 it stops working. After switching to 7.4.13 it works again. 

Maybe there is a conflict in one of your packages on Ubuntu 20.04 (all is up-to-date).

On a VM with the same configuration it works like a charm. 

Maybe there is some conflict in some of the Ubuntu packages that cause here a problem. 

I can't find any errors in all the log files. 

Do you have any idea what it can be? 

PS. There is no probleme in the software because it works on an other machine. 

I would be great if you can help me here, or give me a point to search. 

Thank you.

**Comment by oerdnj** [comment]
I am sorry, I can't provide user support. Also this doesn't seem like a problem in the packaging itself. You will have to debug the problem yourself.
