### ISSUE TITLE
ssl_reject_handshake is not available in current nginx-mainline 1.19.5

### ISSUE THREAD

**Issue by EdisonJwa** [oerdnj/deb.sury.org#1509]
I was upgraded to the latest version of nginx, but the syntax `ssl_reject_handshake` seems not available in the current version

> http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake
> http://nginx.org/en/CHANGES

I was wrote my config file like this 

```
server {
listen 443 ssl http2;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_reject_handshake on;

ssl_session_cache shared:le_nginx_SSL:50m;
ssl_session_timeout 1440m;
}
```

and the server runs well 

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

but this part seems does not work

**Comment by oerdnj** [comment]
Why do you think this is a problem with packaging? Feel free to reopen the issue if you have evidence this was caused by the packaging and not just upstream bug.

Also next time, use issue templates.
