### ISSUE TITLE
trusty php5-apcu > 4.0.6 required for php 5.6

### ISSUE THREAD

**Issue by mkalkbrenner** [oerdnj/deb.sury.org#151]
Hi,

thank you very much for this great PPA.

I have an issue with php5-apcu. The one provided in your PPA for trusty is 4.0.6.
trusty-backports already contains 4.0.7 with important bugfixes. But this one depends on php 5.5 and could therefor not by installed in combination with php 5.6.

Is there a chance to update apcu to 4.0.8 in your PPA?

**Comment by oerdnj** [comment]
There's a bug in php5 5.6.16 PEAR Install command that prevents PECL packages to be built. I think I have a fix, so after it builds I will be able to update APCU to the new version (4.0.10). Thanks for the poke.

**Comment by oerdnj** [comment]
Should be done. Please check whether it works, because I had to drop pkg-php-tools dependency and use old build system. I only checked the resulting package by hand&eye, haven't installed it or tested it.

**Comment by mkalkbrenner** [comment]
Thank you!

At least the package could be installed and apache seems to work. Let's see what happens during the next hours ...

**Comment by oerdnj** [comment]
Is the apcu loaded? :)

**Comment by mkalkbrenner** [comment]
yes, 4.0.10 is loaded and enabled :-)
