### ISSUE TITLE
Better extension dropping policies / information channel - mongodb-5.6 as recent exemple.

### ISSUE THREAD

**Issue by Yivan** [oerdnj/deb.sury.org#1510]
**Frequently asked questions**

- [x ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
I just discover that some old PHP dependencies can be dropped any time from sury.org repo:
We used `php5.6-mongodb`, our builds use `deb https://packages.sury.org/php/ stretch main` as source list. A few month all went ok with `apt-get install php5.6-mongodb`. But now the package has been removed from sury, and it breaks our builds.

**Describe the solution you'd like**
I don't know if dropping is intended or this is an error.
This is more an informational feature request, a way to be able to knowing when package will be dropped.
I imagine maybe php-mongodb has been removed from php5.6 because support has been removed in july 2020 on v1.8.0 ? (https://github.com/mongodb/mongo-php-driver/releases) But in october 2020 the package was always in sury.org.
PHP 5.6 itself is no more supported don't get any fix... (https://www.php.net/supported-versions.php) but is is alwyas on sury.org.

**So if this removal was intended, what is the process decision of removing package, is unclear to me and maybe others.**
(if not intended, this issue should be reclassified as bug please)

Idea for better communication:
- Maybe having this process of removal more defined somewhere would be a good thing.
- If possible having some planning to come making it possible to act before the removal
- Having a sort of "archive" would be great too, so we can just switch the source.list.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
N/A

**Additional context**
N/A

Thanks,
Best regards.

**Comment by oerdnj** [comment]
This is actually a question that you should be asking the upstream as it was the mongodb that has dropped the PHP 5.6 support in 1.8.x. I am now going to add latest 1.7.x to support PHP 5.6 to the package.

**Comment by Yivan** [comment]
Thanks a lot @oerdnj for having added again the latest mongodb for php5.6.
Problem was not the fact that mongodb was abandoned for 5.6, but that the lastest one for php5.6 was no more in sury repository where it was just a few time ago. Now as it is back again, all is fine!

By the way, i just use this issue, to congratulate you for this wonderful repository/project. I am very grateful you provide this to the open-source community.
Have nice Christmas!
Best regards.

**Comment by oerdnj** [comment]
The availability for specific PHP versions is driven by package.xml from the upstream tarball and adding a version that has been dropped requires a) noticing the fact, b) repacking the tarball to include the old version that still has the support.

The b) is no longer required with the package split, but the a) is still required as it doesn't break the build. I am used to check the xdebug, but mongodb was stable for long time...

**Comment by Yivan** [comment]
Thanks for those technical information, now I understand better the process.
