### ISSUE TITLE
Extensions on php 8

### ISSUE THREAD

**Issue by arkadicolson** [oerdnj/deb.sury.org#1514]
Hi

json
xmlrpc

Extensions for propro, json and xmlrpc do not exist in the php8.0 repo:
php8.0-json
php8.0-xmlrpc
php8.0-propro

Perhaps something went wrong during the build process?

 - OS: Debian9
 - Architecture: amd64
 - Repository: packages.sury.org

Thanks

**Comment by oerdnj** [comment]
- json: is part of the core package now
- xmlrpc: please read the PHP 8.0 migration guide first before opening bug reports, https://www.php.net/manual/en/migration80.php says: "The XML-RPC extension has been moved to PECL and is no longer part of the PHP distribution."
- propro: please always check if there's upstream support first: https://github.com/m6w6/ext-propro/commit/921871c048332818704008ce7b67f8f2e32d3cf4
