### ISSUE TITLE
Dist-upgrading from 5.6-40-32 removed php5.6-curl on Debian 10

### ISSUE THREAD

**Issue by generikz** [oerdnj/deb.sury.org#1517]
Hello,

I was using PHP5.6-40.32 and PHP7.3.23-1 and performed a routine **apt-get dist-upgrade**.

Didn't notice CURL would be removed (it's a requirement for my production website):

```
The following packages will be REMOVED:
  php5.6-curl php7.3-curl
The following NEW packages will be installed:
  libncurses5 libtinfo5 php5.6-memcache php7.0-memcache php7.1-memcache php7.2-memcache php7.3-memcache php7.4-memcache php8.0-memcache
  pkg-config
The following packages have been kept back:
  php-imagick
The following packages will be upgraded:
  libapache2-mod-php5.6 libapache2-mod-php7.3 php-memcache php5.6-bz2 php5.6-cli php5.6-common php5.6-dev php5.6-gd php5.6-intl php5.6-json
  php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-pspell php5.6-readline php5.6-soap php5.6-sqlite3 php5.6-sqlite3-dbgsym
  php5.6-xml php5.6-zip php7.3-bz2 php7.3-cli php7.3-common php7.3-dev php7.3-gd php7.3-intl php7.3-json php7.3-mbstring php7.3-mysql
  php7.3-opcache php7.3-pspell php7.3-readline php7.3-sqlite3 php7.3-xml php7.3-zip
```

Upgrade went well to 5.6.40-39 and 7.3.26-1 but now I'm out of php-curl.
Haven't restarted Apache2 so the old version seem to be loaded still.

It seems that libcurl3 is deprecated and was replaced with libcurl4.

The following packages have unmet dependencies:
 php5.6-curl : Depends: libcurl3 (>= 7.18.0) but it is not installable

Is there a way to either:

- "dist-downgrade" to the previous version?
- or have a version phpX.X-curl compatible with libcurl4?

Thank you!

Julien

**Comment by oerdnj** [comment]
Since you intentionally ignored the issue template, I am going to intentionally ignore the incomplete bugreport and close it.
