### ISSUE TITLE
Upgrading from DEB Stretch to Buster didnt update libzip4

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [oerdnj/deb.sury.org#1518]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
I've recently upgraded some machines from debian stretch to debian buster. After upgrading I noticed that lipzip4 remained installed in version `1.5.1-4+0~20190318173229.9+stretch~1.gbp333132` and did not upgrade to `1.5.1-4+0~20190318173200.9+buster~1.gbp333132`.
I think thats because the version string is identical until "stretch" and "buster". And "b" of "buster" is lower than the "s" of "stretch".

**To Reproduce**
1. Have a debian stretch with php-fpm installed from the package.
2. Upgrade to debian buster
3. `dpkg -l | grep libzip4`

**Expected behavior**
Expected upgrade of libzip4 to buster-specific variant during the distribution upgrade, but it stayed on stretch.

**Distribution:**
 - OS: Debian Stretch => Buster
 - Architecture: amd64
 - Repository: https://packages.sury.org/php/

**Package(s):**
Stretch before the update:
```
 # apt-cache policy libzip4
libzip4:
  Installiert:           1.5.1-4+0~20190318173229.9+stretch~1.gbp333132
  Installationskandidat: 1.5.1-4+0~20190318173229.9+stretch~1.gbp333132
  Versionstabelle:
     1.7.3-1 10
         10 http://debian.inf.tu-dresden.de/debian testing/main amd64 Packages
 *** 1.5.1-4+0~20190318173229.9+stretch~1.gbp333132 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.2-1.1+b1 500
        500 http://debian.inf.tu-dresden.de/debian stretch/main amd64 Packages
```

Buster after manual upgrading:
```
# apt-cache policy libzip4
libzip4:
  Installiert:           1.5.1-4+0~20190318173200.9+buster~1.gbp333132
  Installationskandidat: 1.5.1-4+0~20190318173200.9+buster~1.gbp333132
  Versionstabelle:
     1.7.3-1 10
         10 http://debian.inf.tu-dresden.de/debian testing/main amd64 Packages
 *** 1.5.1-4+0~20190318173200.9+buster~1.gbp333132 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     1.5.1-4 500
        500 http://debian.inf.tu-dresden.de/debian buster/main amd64 Packages
```

**Additional context**
I think you solved this problem for other packages already. IMHO you've changed in the version name from "codename" to "debianXY". For example php7.4 has `7.4.14-1+0~20210112.34+debian10~1.gbpaa175a` ("debian10" instead of "buster").

**Comment by oerdnj** [comment]
Thanks for noticing. I update the libzip4 to version 1.7.3, so this should be solved now.

**Comment by MatthiasKuehneEllerhold** [comment]
Version string is now `1.7.3-1+0~20210114.10+debian9~1.gbp4c125d`. 
Thank you!
