### ISSUE TITLE
Dist-upgrading removes permanently phpX.Y-curl packages on Debian 10

### ISSUE THREAD

**Issue by generikz** [oerdnj/deb.sury.org#1519]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
libcurl3 was obsoleted in Debian 10 for libcurl4, making impossible to install php5.6-curl (after 5.6.40-32) or php7.3-curl (after 7.3.23-1).

**To Reproduce**
1. sudo apt-get dist-upgrade

`The following packages will be REMOVED:
  php5.6-curl php7.3-curl
The following NEW packages will be installed:
  libncurses5 libtinfo5 php5.6-memcache php7.0-memcache php7.1-memcache php7.2-memcache php7.3-memcache php7.4-memcache php8.0-memcache
  pkg-config
The following packages have been kept back:
  php-imagick
The following packages will be upgraded:
  libapache2-mod-php5.6 libapache2-mod-php7.3 php-memcache php5.6-bz2 php5.6-cli php5.6-common php5.6-dev php5.6-gd php5.6-intl php5.6-json
  php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-pspell php5.6-readline php5.6-soap php5.6-sqlite3 php5.6-sqlite3-dbgsym
  php5.6-xml php5.6-zip php7.3-bz2 php7.3-cli php7.3-common php7.3-dev php7.3-gd php7.3-intl php7.3-json php7.3-mbstring php7.3-mysql
  php7.3-opcache php7.3-pspell php7.3-readline php7.3-sqlite3 php7.3-xml php7.3-zip`

2. php5.6-curl or php7.3-curl will be removed
3. 
3. They can't be reinstalled with libcurl4:
`The following packages have unmet dependencies:
php5.6-curl : Depends: libcurl3 (>= 7.18.0) but it is not installable`

**Expected behavior**
Upgrading will remove CURL which is expected on many PHP software packages to work properly.

**Distribution (please complete the following information):**
 - OS: Debian 10.7
 - Architecture: amd64
 - Repository: deb https://packages.sury.org/php/ stretch main

**Package(s) (please complete the following information):**
php5.6-curl:
  Installed: (none)
  Candidate: 5.6.40-39+0~20210112.43+debian9~1.gbpe0cf00
  Version table:
     5.6.40-39+0~20210112.43+debian9~1.gbpe0cf00 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
     5.6.40-32+0~20201010.38+debian10~1.gbpdb206f -1
        100 /var/lib/dpkg/status

php7.3-curl:
  Installed: (none)
  Candidate: 7.3.26-1+0~20210112.74+debian9~1.gbpd78724
  Version table:
     7.3.26-1+0~20210112.74+debian9~1.gbpd78724 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
     7.3.23-1+0~20201008.68+debian10~1.gbp30f6c3 -1
        100 /var/lib/dpkg/status
     7.3.19-1~deb10u1 500
        500 http://mirrors.online.net/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
        500 http://deb.debian.org/debian buster/main amd64 Packages

**Additional context**
Sorry, didn't realize the template was a requirement.

**Comment by oerdnj** [comment]
You are installing the stretch PHP packages on buster system.  <-- that's why it's important to use the template, because it makes you answer the important question usually leading to quick answer.
