### ISSUE TITLE
php8.0-fpm lacks AppArmor support

### ISSUE THREAD

**Issue by jlkcz** [oerdnj/deb.sury.org#1522]
**Frequently asked questions**
- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
php8.0-fpm appears to be built without apparmor support

`ERROR: [/etc/php/8.0/fpm/pool.d/adminer.conf:25] unknown entry 'apparmor_hat'`

**To Reproduce**
1. install php-fpm8.0
2. add line `apparmot_hat=whatever` to /etc/php/8.0/fpm/pool.d/www.conf 
3. `/usr/sbin/php-fpm8.0 --test`

**Expected behavior**
Should switch to appropriate apparmor hat

**Distribution (please complete the following information):**
Debian GNU/Linux bullseye using
`deb https://packages.sury.org/php/ buster main`

**Package(s) (please complete the following information):**
```
php8.0-fpm:
  Installed: 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d
  Candidate: 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d
  Version table:
 *** 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     8.0.1-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
```

**Comment by vuorinvi** [comment]
When it comes to PHP 8 the setting name is aa_change_profile instead of apparmor_hat even though Sury's version of PHP8 is not yet compiled with AppArmor support.

**Comment by oerdnj** [comment]
Enabled the AppArmor support in 8.0.2-2, please test and if it works close the issue.

**Comment by jlkcz** [comment]
Now works as expected. Thanks for fixing it. 

@vuorinvi Still uses apparmor_hat though...
