### ISSUE TITLE
Performance degradation with xdebug update (2.9.8 -> 3.0.1) on string operations

### ISSUE THREAD

**Issue by heidemn-faro** [oerdnj/deb.sury.org#1523]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The xdebug upgrade was mentioned in https://github.com/oerdnj/deb.sury.org/issues/1497 .

For particular use cases, xdebug 3.0.1 is way slower than 2.9.8 before.
Noticed with both PHP 7.3 and 7.4, and both Ubuntu 18.04 and 20.04.

While most Apache2 requests have similar performance, we had one particular type of request that was much slower than before.

Basically we had xdebug accidentally installed on our production servers, and suddenly noticed this.
While this is of course not the intended use case, I think you should still investigate the performance drop.

Performance comparison for one particular request handler:
* With vs. without xdebug 3.0.1: **Factor 20** (!)
* xdebug 2.9.8 vs. 3.0.1: (Will add comparison soon)

**To Reproduce**
1. Create a request handler (in our case, Symfony and Apache2 were used, probably doesn't matter).
2. The request handler should do heavy string operations (in our case, a 1-2 MB binary string)
3. Notice the performance difference with/without xdebug 3.0.1
4. Notice the performance degradation from xdebug 2.9.8 to 3.0.1

Didn't check if CLI is also affected, but I guess so.

**Expected behavior**
Similar performance to before.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04 + 20.04
 - Architecture: amd64
 - Repository: `ppa:ondrej/php`

**Package(s) (please complete the following information):**
_Output of `apt-cache policy <package>` works best._

**Additional context**
_Add any other context about the problem here._

**Comment by oerdnj** [comment]
I am sorry, but this is not a packaging issue. You need to bring this up with the upstream.

**Comment by heidemn-faro** [comment]
True, you're right.

**Comment by heidemn** [comment]
This was already reported here: https://bugs.xdebug.org/view.php?id=1911
