### ISSUE TITLE
Please provide current PHP8.0.1 on Debian ARM64

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1524]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Although php8.0.1 is out since January 7 (and is provided on Debian amd64) it is not available on Debian arm64.

**To Reproduce**

```
rfay@d9-web:/var/www/html$ php --version
PHP 8.0.0 (cli) (built: Dec  6 2020 06:56:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies

rfay@d9-web:/var/www/html$ arch
aarch64

rfay@d9-web:/var/www/html$ sudo apt-get -qq update
rfay@d9-web:/var/www/html$ sudo apt-get install php8.0-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
php8.0-cli is already the newest version (8.0.0-1+0~20201206.6+debian10~1.gbp33744b).
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
```

**Expected behavior**

PHP8.0.1 is the current version (and current on Debian amd64). 

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: arm64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

$ apt-cache policy php8.0-cli
php8.0-cli:
  Installed: 8.0.0-1+0~20201206.6+debian10~1.gbp33744b
  Candidate: 8.0.0-1+0~20201206.6+debian10~1.gbp33744b
  Version table:
 *** 8.0.0-1+0~20201206.6+debian10~1.gbp33744b 500
        500 https://packages.sury.org/php buster/main arm64 Packages
        100 /var/lib/dpkg/status

**Additional context**

**Comment by oerdnj** [comment]
8.0.2 is now available for all dist and archs.

**Comment by rfay** [comment]
Thank you!
