### ISSUE TITLE
php7 gettext package depends

### ISSUE THREAD

**Issue by rivimey** [oerdnj/deb.sury.org#1525]
Summary:

A package I wanted to install (bareos-webui 19.2) has an explicit dependency on php gettext. Its dependency line includes:

    Depends: php-gettext, php5-gettext, php7-gettext

I have installed php from deb.sury.org:

    Package: php7.4-common
    Version: 7.4.14-1+ubuntu20.10.1+deb.sury.org+1

This has a Provides line:

    Provides: php-calendar, php-ctype, php-exif, php-ffi, php-fileinfo, php-ftp, php-iconv, php-pdo, php-phar, php-posix, \
        php-shmop, php-sockets, php-sysvmsg, php-sysvsem, php-sysvshm, php-tokenizer, \
        php7.4-calendar, php7.4-ctype, php7.4-exif, php7.4-ffi, php7.4-fileinfo, php7.4-ftp, php7.4-gettext, \
        php7.4-iconv, php7.4-pdo, php7.4-phar, php7.4-posix, php7.4-shmop, php7.4-sockets, \
        php7.4-sysvmsg, php7.4-sysvsem, php7.4-sysvshm, php7.4-tokenizer

I can see that this package includes a Provides of `php7.4-gettext`, but no other variants. I can also see that extensions like  php-exif, php-iconv have a version-independent Provides.

I don't know if the issue is that the `bareos-webui` package should include a different name, or that `php7.4-common` should include a more generic name (`php-gettext`). However, I am submitting this here because I think it makes sense for bareos to be able to say 'I need gettext' and not have to specify a version -- that is, I believe the Provides line in php-common should include version-independent (`php-gettext`) as well as version-specific (`php7.4-gettext`) names.

I am unsure whether a major-version variant (`php7-gettext`) should be included or not.

To be clear, I am _not_ saying I want a package (`php-getttext`) that depends on all php versions... the version-independent name should be virtual.

**Comment by oerdnj** [comment]
Yes, the `php-gettext` is handled specially, because here's the problem: https://packages.debian.org/search?keywords=php-gettext

We might now get rid of `php-gettext` transitional package in `sid` and then perhaps I could reintroduce the `php-gettext` package.

**Comment by oerdnj** [comment]
This should be fixed now.
