### ISSUE TITLE
PCRE is not patched

### ISSUE THREAD

**Issue by halaei** [oerdnj/deb.sury.org#1526]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The following code doesn't work correctly in php7.4.14 from this repository, but it works correctly when I installed it with phpbrew. According to the comments in https://bugs.php.net/bug.php?id=79363&thanks=2 it is because https://bugs.exim.org/show_bug.cgi?id=2621 is not backported. I really don't understand the details, but my guess is I should report it here.

**To Reproduce**
Run the following line of code:
```php
echo(preg_replace('/[^\p{L}\p{Arabic}]/', '0', '<->'));
```
The ubuntu build prints the following wrong output:
 ```
<->
```
**Expected behavior**
This is the correct output of phpbrew build:
```
000
```

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
php7.4-cli:
  Installed: 7.4.14-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.4.14-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.4.14-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by MatthewVernon** [comment]
Hi,
I'm the Debian pcre2 maintainer; the underlying pcre2 bug is fixed in Debian's 10.36-2; the issue seems to be that Ubuntu is only shipping an older version of pcre2 that is buggy.

**Comment by MatthewVernon** [comment]
I think, based on the [Debian bug report apropos this issue](https://bugs.debian.org/981432), that @oerdnj is shipping their own pcre build, so maybe the answer is for them to base theirs off Debian's 10.36-2 rather than the buggy Ubuntu version?

**Comment by halaei** [comment]
Maybe `./configure` without `--with-external-pcre` can help, in case it is used? I can't find source code on how this package configure & make php.

**Comment by oerdnj** [comment]
Thanks @MatthewVernon, I'll sync up with your version in Debian.

**Comment by oerdnj** [comment]
And that has been done.
