### ISSUE TITLE
No need to depend on libmagic1

### ISSUE THREAD

**Issue by halaei** [oerdnj/deb.sury.org#1527]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Starting from php 5.3.0, php uses its own patch of libmagic, so there is no need to depend on libmagic1, and maybe mime-types. 
https://www.php.net/manual/en/fileinfo.requirements.php
https://www.php.net/manual/en/fileinfo.installation.php

**Additional context**
This is only my guess after being confused about a bug in finfo. https://bugs.php.net/bug.php?id=78987
Maybe I am wrong.
Thanks.

**Comment by oerdnj** [comment]
Debian packages generally doesn't use embedded libraries. This needs to be fixed in the `file` package in Debian/Ubuntu.

**Comment by halaei** [comment]
They have already fixed the bug in file package. I think we should wait for their next release at least.
In this issue I am just worried about this quote in php docs. My inference is that php have to use it's own embedded libmagic:
> The libmagic library is bundled with PHP, but includes PHP specific changes. A patch against libmagic named libmagic.patch is maintained and may be found within the PHP fileinfo extensions source.
