### ISSUE TITLE
PHP 8.0.2, 7.4.15 and 7.3.27 for Debian

### ISSUE THREAD

**Issue by BrookeDot** [oerdnj/deb.sury.org#1528]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
[PHP 7.4.15](https://www.php.net/archive/2021.php#2021-02-04-2) was recently released, the [Ubuntu PPAs have been updated](https://launchpad.net/~ondrej/+archive/ubuntu/php) (thanks!), however, the Debian packages have not yet been built and are currently PHP 7.4.14 in Jenkins:
https://jenkins.rfc1925.org/view/PHP/

**Describe the solution you'd like**
Updated PHP Debian packages available from`packages.sury.org`

**Distribution:**
 - OS: **Debian 10.8**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
$ cat /etc/debian_version
10.8
```
 - Architecture: **AMD64**
```
$ uname -a
Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```
 - Repository: `deb https://packages.sury.org/php/ buster main`

**Package(s) (please complete the following information):**
```
$ apt-cache policy php7.4-common
php7.4-common:
  Installed: 7.4.14-1+0~20210112.34+debian10~1.gbpaa175a
  Candidate: 7.4.14-1+0~20210112.34+debian10~1.gbpaa175a
  Version table:
 *** 7.4.14-1+0~20210112.34+debian10~1.gbpaa175a 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by BrookeDot** [comment]
Just noting that the source builds were successful, but the binaries failed for AMD64.
https://jenkins.rfc1925.org/view/PHP/job/php_php8.0-binaries/
https://jenkins.rfc1925.org/view/PHP/job/php_php7.4-binaries/
https://jenkins.rfc1925.org/view/PHP/job/php_php7.3-binaries/

**Comment by oerdnj** [comment]
Oh well, I updated that machine to bullseye and now everything's broken. I'm looking into that.

**Comment by oerdnj** [comment]
It's building. It might still choke on bullseye that I've also added to the supported distros, but at least the stretch-amd64 and buster-amd64 should be build.  The rest will follow as I will squash all the other bugs.

**Comment by oerdnj** [comment]
We are almost there, there are couple of armhf and arm64 build still pending, but most of the packages have been already compiled.
