### ISSUE TITLE
xdebug-2.4 for php7.0

### ISSUE THREAD

**Issue by aTanCS** [oerdnj/deb.sury.org#153]
Hi, xdebug-2.4 supports php7.0. Please add it to the ppa.

**Comment by oerdnj** [comment]
2.4.0~rc2-1+deb.sury.org~<dist>+1 uploaded and built

**Comment by mpalourdio** [comment]
Hello,

I can't install this package. (Mint 17.2)

apt-get install php-xdebug
E: Sub-process /usr/bin/dpkg returned an error code (1)

Thanks.

**Comment by oerdnj** [comment]
Should be fixed in +2 that I have just uploaded. There was a missing parameter in dh_php that generated a wrong maintscripts.
