### ISSUE TITLE
PHP7.4-MySQL removed automatically after system updates

### ISSUE THREAD

**Issue by conandrum** [oerdnj/deb.sury.org#1530]
Yesterday I sent a message on https://launchpad.net/~ondrej but that may not have been noticed, so I am posting here.
This may not be a bug, but I think it is unexpected behaviour. 

This is a fresh system (05 Feb 2021) with 
```
Operating system Ubuntu Linux 20.04.2
Webmin version 1.962 Usermin version 1.812 Virtualmin version 6.14 Kernel and CPU Linux 5.4.0-65-generic on x86_64
```

Webmin installed MySQL & PHP 7.4 - I then enabled multiple PHP versions using
```
add-apt-repository -y ppa:ondrej/php
apt-get update
```

By 22:44 I finished configuring the server. I then installed Wordpress and made sure it was functioning properly.
The system has automatic updates enabled in /etc/apt/apt.conf.d/60unattended-upgrades.

So at 23:00 PHP 8.0 got installed automatically - I got this in /var/log/apt/history.log :
```
Start-Date: 2021-02-05 23:00:50
Commandline: apt-get -y install php php-cgi php-cli php-fpm php-mbstring php-mysql php-xml
Install: php8.0-mbstring:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-readline:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-cgi:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-cli:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-fpm:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-opcache:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-xml:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-common:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), php8.0-mysql:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic), libapache2-mod-php8.0:amd64 (8.0.1-1+ubuntu20.04.1+deb.sury.org+1, automatic)
Upgrade: php-xml:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php-cgi:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php-cli:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php-fpm:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php-mbstring:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1), php-mysql:amd64 (2:7.4+75, 2:8.0+80~exp2+ubuntu20.04.1+deb.sury.org+1)
End-Date: 2021-02-05 23:01:27
```

Wordpress was still functional at this point.

The next day I get this in /var/log/apt/history.log:
```
Start-Date: 2021-02-06 06:50:14
Commandline: /usr/bin/unattended-upgrade
Remove: php7.4-mysql:amd64 (7.4.14-1+ubuntu20.04.1+deb.sury.org+1)
End-Date: 2021-02-06 06:50:16
```

So today I go to check Wordpress and of course it is not working because there is no php7.4-mysql
When I switch PHP to version 8.0 it works fine.

**Am I right to assume that php7.4-mysql is considered an Unused-Dependency? 
Why is it being removed?
How do I avoid this?**

_Thanks in advance for your help._

PS. 
```
/etc/apt/apt.conf.d/60unattended-upgrades
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
	"${distro_id}:${distro_codename}-security";
	"${distro_id}ESM:${distro_codename}";
	"${distro_id}:${distro_codename}-updates";
	"LP-PPA-ondrej-php:bionic";
};
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";

```

**Comment by oerdnj** [comment]
Install it by hand, so it's not pulled as dependency to php-mysql.

The version-less packages depend on latest stable. If you need to keep specific version you'll need to install versioned packages.

**Comment by conandrum** [comment]
Hi Ondřej, (please excuse me posting here - let me know if there is a better place for such issues)

` Install it by hand, so it's not pulled as dependency to php-mysql.`
Are you talking about installing php7.4-mysql by hand? 

`If you need to keep specific version you'll need to install versioned packages.`
So basically what you said earlier ('Install it by hand, so it's not pulled as dependency to php-mysql')???

`The version-less packages depend on latest stable.`
Are you saying that if the latest stable is php8.x.x-mysql, all previous versions will be removed? 
**Why is this not happening with other packages like xml, xsl, xmlwriter etc?** Only with php-mysql?

Modules for PHP 7.4 
`| calendar | cgi-fcgi | Core | ctype | curl | date | dom | exif | FFI | fileinfo | filter | ftp | gd | gettext | hash | iconv | intl | json | libxml | mbstring | mcrypt | openssl | pcntl | pcre | PDO | Phar | posix | readline | Reflection | session | shmop | SimpleXML | soap | sockets | sodium | SPL | standard | sysvmsg | sysvsem | sysvshm | tokenizer | xml | xmlreader | xmlrpc | xmlwriter | xsl | zip | zlib`

Modules for PHP 8.0 
`| calendar | cgi-fcgi | Core | ctype | date | dom | exif | FFI | fileinfo | filter | ftp | gettext | hash | iconv | json | libxml | mbstring | **mysqli** | mysqlnd | openssl | pcntl | pcre | PDO | pdo_mysql | Phar | posix | readline | Reflection | session | shmop | SimpleXML | sockets | sodium | SPL | standard | sysvmsg | sysvsem | sysvshm | tokenizer | xml | xmlreader | xmlwriter | xsl | zlib`

**Comment by conandrum** [comment]
Why is this not happening with other packages like xml, xsl, xmlwriter etc? Why only with php-mysql?
Should I be worried that other packages may be auto removed in the future?

On another server I have Ubuntu 18.04 which came with php7.2 before I installed ppa:ondrej/php - That server did not remove anything after php8.0 got installed.

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#what-to-report-in-the-issue-tracker especially this part:

> Please note that I can't possibly do any user support - I can't teach you the basics of system administration, configure your system or solve unrelated problems. There are more appropriate forums for that like Ask Ubuntu, Server Fault or Debian User Forum.

**Comment by conandrum** [comment]
Of course Ondřej, I am not expecting support. 
Just was curious why this was happening only with  php7.4-mysql and only on 20.04 Ubuntu.
The reason why I cam here is because other experienced users urged me to speak to you.
e.g. https://answers.launchpad.net/ubuntu/+question/695428
