### ISSUE TITLE
PHP-FPM status page shows listen queue 0

### ISSUE THREAD

**Issue by MichaIng** [oerdnj/deb.sury.org#1531]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

I enabled the PHP-FPM status page and configured a handler in Apache2:
```
<Location /status>
        SetHandler "proxy:unix:/run/php/php8.0-fpm.sock|fcgi://localhost/status"
</Location>
```
This is the result:
```
pool:                 www
process manager:      static
start time:           28/Jan/2021:15:53:44 +0100
start since:          1147547
accepted conn:        1054191
listen queue:         0
max listen queue:     0
listen queue len:     0
idle processes:       11
active processes:     1
total processes:      12
max active processes: 12
max children reached: 0
slow requests:        0
```
As can be seen, while all running processes have been used concurrently (this is the case after a few hours already, so not a very rare event), the listen queue stays at zero. Especially the `listen queue len` stays at zero, even that `listen.backlog = 1024` is applied in the pool configuration and as well system-wide a sufficient backlog is permitted:
```
net.core.somaxconn = 2048
net.ipv4.tcp_max_syn_backlog = 1024
```
This is on PHP8.0, but it was the same before on PHP7.4.

**To Reproduce**
1. Install Debian Bullseye
2. Install Apache2 and PHP-FPM
3. Enable the PHP-FPM status page and the related handler in Apache2
4. Cause more concurrent requests than `pm.max_children`
5. Watch PHP-FPM status page to show `listen queue len` and `max listen queue` being zero.

**Expected behavior**
I would expect that `listen queue len` matches `listen.backlog` and that I do see a non-zero value at `max listen queue`, when the process limit is hit regularly. But probably in this setup it is handled differently? At least connections are not dropped from what I can say, no related error messages appear in either PHP or Apache2 logs, so in fact requests are queried somewhere.

**Distribution (please complete the following information):**
 - OS: **Debian Bullseye**
 - Architecture: **x86_64**
 - Repository: **packages.sury.org/php**

**Package(s) (please complete the following information):**
```
php8.0-fpm:
  Installed: 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d
  Candidate: 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d
  Version table:
 *** 8.0.1-1+0~20210112.7+debian10~1.gbp71cd4d 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status

apache2:
  Installed: 2.4.46-4
  Candidate: 2.4.46-4
  Version table:
 *** 2.4.46-4 500
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
I believe you need to report this to the upstream. This doesn't seem like anything I could control by the packaging. Please report the URL of upstream issue back here when you do that.

**Comment by MichaIng** [comment]
Bug report sent upstream: https://bugs.php.net/bug.php?id=80739
