### ISSUE TITLE
E: Failed to get Packages.gz File has unexpected size (270252! = 269886)

### ISSUE THREAD

**Issue by DmitrySkibitsky** [oerdnj/deb.sury.org#1536]
**Describe the bug**
E: Failed to get https://packages.sury.org/php/dists/buster/main/binary-amd64/Packages.gz File has unexpected size (270252! = 269886)
How to fix it?

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Just wait a bit and try again.

**Comment by DmitrySkibitsky** [comment]
> Just wait a bit and try again.

Yes, everything works. Thank)
