### ISSUE TITLE
php8.0-ssh2

### ISSUE THREAD

**Issue by milo** [oerdnj/deb.sury.org#1538]
- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Missing `php8.0-ssh2` extension on Debian Buster.

**Describe the solution you'd like**
Not missing the extension :)

Hello. I'm preparing PHP 8.0 as a parallel option to our hosting server and I found out that extension `php8.0-ssh2` is not in your respository [pool](https://packages.sury.org/php/pool/main/p/php-ssh2/). As I found on [pecl/ssh](https://pecl.php.net/package/ssh2) in release 1.2 notes: "PHP version 8.0.0 or older", it sould be compatible.

Is there any way I can help with it?

**Comment by oerdnj** [comment]
For starters, it's always best to check whether the version you are requesting is even supported by the extension...  (and if not try to check what's needed, e.g. is there an upstream patch that can be used?)

In this case, I already had the patches pulled, but the `package.xml` prevented the PHP 8.0 build, so I fixed that.

**Comment by milo** [comment]
Thank you!
