### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by samtarling** [oerdnj/deb.sury.org#1539]
Hey - just a nudge that the [invite link](https://join.slack.com/t/debsuryorg/shared_invite/enQtNTY2MTg0MDg2NjI4LWEwNDliMWIyY2U0OWJjOTQ1YzFhNzc3OGMzY2U4NWM5MDE4OWJhNGE2OTNhNDkwZDkzNzY2ZWNiMzgyY2Y5ZTI) has expired :-)

![image](https://user-images.githubusercontent.com/375162/107955101-49914700-6f95-11eb-8e57-d57e6ac98943.png)

**Comment by oerdnj** [comment]
Thanks. They've changed the policy on the invite links, so they can no longer don't expire.

Let's move here: https://gitter.im/deb-sury-org/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
