### ISSUE TITLE
mcrypt module for php 7.0

### ISSUE THREAD

**Issue by soffchen** [oerdnj/deb.sury.org#154]
Please compile this module into deb :)

**Comment by oerdnj** [comment]
You know that the library is unmaintained since ~2007, right? (I will do that, but I just wanted to point this out.)

**Comment by soffchen** [comment]
You are right. Maybe it is time to re-write the related code :(

**Comment by oerdnj** [comment]
php7.0_7.0.0-5+deb.sury.org~<dist>+1
