### ISSUE TITLE
Debian Buster arm64 packages can't update (15 Feb 2021)

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1540]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

It's currently impossible to update Debian buster arm64 packages:
```
E: Failed to fetch https://packages.sury.org/php/dists/buster/main/binary-arm64/Packages.gz  File has unexpected size (265681 != 265671). Mirror sync in progress? [IP: 172.67.182.150 443]
   Hashes of expected file:
    - Filesize:265671 [weak]
    - SHA256:9961476177459775c0c269716933ad3ab3fe895cc58cc1a606d3a56ea9a6a459
    - SHA1:454070c81105935c7d823e6952a2c8f4f5a0b151 [weak]
    - MD5Sum:02361554531705efb633c0af61e7c05b [weak]
   Release file created at: Mon, 15 Feb 2021 13:10:23 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**To Reproduce**

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
Could somebody review my purge cache script:
```
#!/bin/sh
set -e
[ -z "$1" ] && exit 1
repo=$1

find_dists() (
    repo=$1
    find -L "/var/www/repository/$repo/dists" -mindepth 1 -maxdepth 1 -type d | sed -e "s@.*/@@"
)

find_files() (
    repo=$1
    dist=$2
    find -L "/var/www/repository/$repo/dists/$dist" -type f | sed -e "s@/var/www/repository/$repo@\"https://packages.sury.org/$repo@" -e "s@\$@\"@" | tr "\n" "," | sed -e "s@,\$@@"
)

for dist in $(find_dists "$repo"); do
    echo "Purging $dist..."
    data="{\"files\":[$(find_files "$repo" "$dist")]}"
    echo "Data being purged:"
    echo "$data" | python -m json.tool
    echo "Sending request to purge data to CloudFlare:"
    curl -sSL \
	 -X POST "https://api.cloudflare.com/client/v4/zones/<zone>/purge_cache" \
	 -H "Authorization: Bearer <auth>" \
	 -H "Content-Type: application/json" \
	 --data "$data" | python -m json.tool
done
```

It seems it break quite a lot when there's a lot of package updates going on.

**Comment by oerdnj** [comment]
Oh, dammit: `12:31:58 /var/lib/jenkins/bin/purge-repository: 21: python: not found`

**Comment by oerdnj** [comment]
I fixed the `python` to `python3` (and also installed `python-is-python3` package).

Could you try it now?

**Comment by hirschrobert** [comment]
works now for `https://packages.sury.org/php buster/main arm64 Packages [267 kB]`
many thanks

**Comment by oerdnj** [comment]
I was wondering why is this happening and I installed some python3 package that removed `python-is-python2` package over the weekend and Jenkins is kinda bad at catching these kind of errors.

**Comment by rfay** [comment]
Thanks for this, working now.

**Comment by mrtimp** [comment]
Hi there.  

I'm not sure if I am running into the same issue but with brand new Buster instances we are getting 403 errors from Cloudflare when attempting to do an apt update, getting errors like:

...
Hit:1 http://deb.debian.org/debian buster InRelease
Ign:2 https://packages.sury.org/php buster InRelease
Err:3 https://packages.sury.org/php buster Release  
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.67.182.150 443]
Reading package lists... Done
W: https://packages.sury.org/php/dists/buster/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.sury.org/php/dists/buster/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://packages.sury.org/php buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

We have fully removed and reinstalled ca-certificates, confirmed that isn't an issue as we can use curl to reach URL's such as:

https://packages.sury.org/php/dists/buster/main/binary-amd64/

how ever get 403 errors attempting to download the Release, Release.gz or any of the .deb files in URL's like https://packages.sury.org/php/pool/main/p/php-defaults/ - the same issue apt has.

Is this related to the above issue with Cloudflare caching/blocking potential sources of bad traffic?
