### ISSUE TITLE
Missing dependency on libenchant-dev when building php 7.3 and earlier on Debian unstable

### ISSUE THREAD

**Issue by anomiex** [oerdnj/deb.sury.org#1542]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
It appears that Debian has removed libenchant-dev from unstable, only libenchant-2-dev is available now. The PHP 5.6 to 7.3 sources depend on libenchant-dev. The PHP 7.4 and 8.0 sources build-depend on libenchant-2-dev | libenchant-dev and so don't have this problem.

I know you don't officially support Debian unstable, but this will eventually wind up in a stable version (probably Bookworm) so it seems worth reporting even if you don't get to it for a while.

**To Reproduce**
1. Use Debian unstable, e.g. `docker run --rm -it debian:sid`.
2. Add `deb-src https://packages.sury.org/php/ bullseye main` to your apt sources.list, as there are no sources specifically for sid. Also install the sury gpg key if necessary.
3. `apt-get update && apt-get build-dep php7.3`

**Expected behavior**
Build dependencies are installed.

**Actual behavior**
```
The following packages have unmet dependencies:
 builddeps:php7.3 : Depends: libenchant-dev but it is not installable
```

**Distribution (please complete the following information):**
 - OS: Debian unstable
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

Not sure what to put for `<package>` there, but
```
root@1e4c07c1783e:/# apt-cache policy 
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://deb.debian.org/debian sid/main amd64 Packages
     release o=Debian,a=unstable,n=sid,l=Debian,c=main,b=amd64
     origin deb.debian.org
Pinned packages:
```

**Additional context**
Possible to work around by downloading an old version of libenchant1c2a and libenchant-dev from https://snapshot.debian.org/, or presumably by recompiling the bullseye libenchant from source.

**Comment by oerdnj** [comment]
> Possible to work around by downloading an old version of libenchant1c2a and libenchant-dev from https://snapshot.debian.org/, or presumably by recompiling the bullseye libenchant from source.

I actually took down this path for bullseye: https://salsa.debian.org/ondrej/enchant

**Comment by oerdnj** [comment]
I also synced up the patches used in PHP 7.4, so the packages might just need the alternative B-D. I didn't have time to try that yet, but I would encourage you to try and report back.

**Comment by oerdnj** [comment]
Ok, I have now verified that PHP 5.6 - PHP 8.0 builds with enchant-2 (the version in git, so will be part of next upload).
