### ISSUE TITLE
php-imagick upgrade breaks on Debian Buster

### ISSUE THREAD

**Issue by elam0nt** [oerdnj/deb.sury.org#1543]
**Frequently asked questions**

- [X ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Upgrading php-imagick on Debian 10 running multiple php versions fails because it tries to remove '/etc/php'.
 
[cmd-output.txt](https://github.com/oerdnj/deb.sury.org/files/5989361/cmd-output.txt)

**To Reproduce**
apt install php-imagick

**Expected behavior**
post-removal script should not try to remove '/etc/php'.

**Distribution (please complete the following information):**
 - OS: Debian 10 Buster
 - Architecture: amd64 
 - Repository: deb https://packages.sury.org/php/ buster main

**Package(s) (please complete the following information):**
php-imagick:
  Installed: (none)
  Candidate: 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866
  Version table:
     3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.3-4.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

**Additional context**

**Comment by oerdnj** [comment]
I am pretty sure that you did something to your system that makes the packaging scripts to break. I can't tell what since you didn't tell me. Both clean installation of `php-imagick` and upgrade from buster version of `php-imagick` works for me.

```
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libargon2-1 libedit2 libncurses6 libsodium23 php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-phpdbg php7.3-readline
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  php5.6-imagick php7.0-imagick php7.1-imagick php7.2-imagick php7.3-imagick php7.4-imagick php8.0-imagick
Recommended packages:
  ghostscript ttf-dejavu-core
The following NEW packages will be installed:
  php5.6-imagick php7.0-imagick php7.1-imagick php7.2-imagick php7.3-imagick php7.4-imagick php8.0-imagick
The following packages will be upgraded:
  php-imagick
1 upgraded, 7 newly installed, 0 to remove and 50 not upgraded.
Need to get 729 kB of archives.
After this operation, 3017 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://packages.sury.org/php buster/main amd64 php-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [12.2 kB]
Get:2 https://packages.sury.org/php buster/main amd64 php8.0-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [102 kB]
Get:3 https://packages.sury.org/php buster/main amd64 php7.4-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [103 kB]
Get:4 https://packages.sury.org/php buster/main amd64 php7.3-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [104 kB]
Get:5 https://packages.sury.org/php buster/main amd64 php7.2-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [103 kB]
Get:6 https://packages.sury.org/php buster/main amd64 php7.1-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [103 kB]
Get:7 https://packages.sury.org/php buster/main amd64 php7.0-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [103 kB]
Get:8 https://packages.sury.org/php buster/main amd64 php5.6-imagick amd64 3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866 [99.7 kB]
Fetched 729 kB in 0s (4949 kB/s)
(Reading database ... 20996 files and directories currently installed.)
Preparing to unpack .../0-php-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) over (3.4.3-4.1) ...
Selecting previously unselected package php8.0-imagick.
Preparing to unpack .../1-php8.0-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php8.0-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php7.4-imagick.
Preparing to unpack .../2-php7.4-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php7.4-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php7.3-imagick.
Preparing to unpack .../3-php7.3-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php7.3-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php7.2-imagick.
Preparing to unpack .../4-php7.2-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php7.2-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php7.1-imagick.
Preparing to unpack .../5-php7.1-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php7.1-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php7.0-imagick.
Preparing to unpack .../6-php7.0-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php7.0-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Selecting previously unselected package php5.6-imagick.
Preparing to unpack .../7-php5.6-imagick_3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866_amd64.deb ...
Unpacking php5.6-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php7.2-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php7.4-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php7.3-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php5.6-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php7.0-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php7.1-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php8.0-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
Setting up php-imagick (3.4.4+php8.0+3.4.4-2+0~20210215.25+debian10~1.gbp784866) ...
```

If you need help, you must not withheld information, your system is not in a standard shape.

**Comment by elam0nt** [comment]
Sorry if my issue report was not detailed enough, here's some additional  information:

This server was built from a fresh install (not dist-upgraded) of Buster when it came out and has been in service ever since.  It's a web server hosting many Apache virtual hosts, each running under it's own UID/GID (using mod-mpm-itk) and each having is own php-fpm configuration.  There is no real "process jailling" involved here. 

I've upgraded this system many times without issue before and the only thing that I think can interfere with the current  update scripts, is that I have an extra folder under /etc/php where all the per vhost  FPM config files are stored (/etc/php/fpm-pools.d) and then  symlinked under /etc/php/X.X/fpm/pool.d/. (see the included output of "tree /etc/php".) But this extra directory has been there since this system is online.

I don't know if this is relevant but, only php5.6 to php7.4 are installed, no php8.0 yet.

Hopping this clarifies things a bit.

[installed-pkgs.txt](https://github.com/oerdnj/deb.sury.org/files/5991665/installed-pkgs.txt)
[tree-etc-php.txt](https://github.com/oerdnj/deb.sury.org/files/5991666/tree-etc-php.txt)

**Comment by oerdnj** [comment]
I think the problem is `rmdir --ignore-fail-on-non-empty /etc/php` fails.

Find why your system is ignoring the option and you'll find the problem.

Did you change the default shell to some non-POSIX shell?

**Comment by elam0nt** [comment]
So, "rmdir --ignore-fail-on-non-empty /etc/php" fails... but not because /etc/php is not empty, but for some other reasons.  Tomorrow, I will double-check that all the files and directories permissions are right, along some other things and get back to you. 

If I use non-POSIX shell, no.  I just use Bash.

Thanks

**Comment by elam0nt** [comment]
I think I found why it fails now.  Sorry if I didn't mention it at first because I forgot this system was setup that way. You see, this system is part of a web server cluster and the /etc/php is in fact mounted from an NFS share. So "rmdir --ignore-fail-on-non-empty /etc/php" gives an uncaught error.  I know this is not a standard setup, and I won't ask you to modify the post-removal script just for me, but maybe I'm not the only one to have a system where /etc/php is mounted from an other fs.  So, i would suggest it could be a good thing if the post-removal script skip the rmdir completely  if /etc/php is a mountpoint.

**Comment by elam0nt** [comment]
I think I found why it fails now.  Sorry if I didn't mention it at first because I forgot this system was setup that way. You see, this system is part of a web server cluster and the /etc/php is in fact mounted from an NFS share. So "rmdir --ignore-fail-on-non-empty /etc/php" gives an uncaught error.  I know this is not a standard setup, and I won't ask you to modify the post-removal script just for me, but maybe I'm not the only one to have a system where /etc/php is mounted from an other fs.  So, i would suggest it could be a good thing if the post-removal script skip the rmdir completely  if /etc/php is a mountpoint.

**Comment by oerdnj** [comment]
> I think I found why it fails now. Sorry if I didn't mention it at first because I forgot this system was setup that way.

No hard feelings here, we got to the point where we discovered the important part in the end.

> You see, this system is part of a web server cluster and the /etc/php is in fact mounted from an NFS share. So "rmdir --ignore-fail-on-non-empty /etc/php" gives an uncaught error. I know this is not a standard setup, and I won't ask you to modify the post-removal script just for me, but maybe I'm not the only one to have a system where /etc/php is mounted from an other fs. So, i would suggest it could be a good thing if the post-removal script skip the rmdir completely if /etc/php is a mountpoint.

In the future, the `rmdir` might not be needed, it was there because the `php-imagick` contained all the extensions and it rolled from one set of versions to another. Now they are split, this code could just go.

I have some more fixes I need to put into `php-defaults` and `dh-php` packages, so I'll probably fix this right away.

**Comment by oerdnj** [comment]
The rmdir is gone now. It should work on your system even when `/etc/php` is a mount point.
