### ISSUE TITLE
php-mysql is not satisfied with php7.4-mysql

### ISSUE THREAD

**Issue by jooola** [oerdnj/deb.sury.org#1547]
**Describe the bug**

The `zabbix-frontend-php` has a dependency on `php-mysql`, since I want to pin the version to php7.4 I manually install php7.4-mysql. But the dependency is not satisfied when I install the `zabbix-frontend-php` package.

I am unsure if this is a problem on the zabbix side, or the sury repository side.

```
jo@monitor-auk: ~ $ sudo apt-cache depends zabbix-frontend-php 
zabbix-frontend-php
  Depends: php-mbstring
    php5.6-mbstring
    php7.0-mbstring
    php7.1-mbstring
    php7.2-mbstring
    php7.3-mbstring
    php7.4-mbstring
    php8.0-mbstring
  Depends: php-bcmath
    php5.6-bcmath
    php7.0-bcmath
    php7.1-bcmath
    php7.2-bcmath
    php7.3-bcmath
    php7.4-bcmath
    php8.0-bcmath
  Depends: php-xml
    php5.6-xml
    php7.0-xml
    php7.1-xml
    php7.2-xml
    php7.3-xml
    php7.4-xml
    php8.0-xml
 |Depends: php-mysql
    php5.6-mysql
  Depends: php-pgsql
    php5.6-pgsql
    php7.0-pgsql
    php7.1-pgsql
    php7.2-pgsql
    php7.3-pgsql
    php7.4-pgsql
    php8.0-pgsql
  Depends: php-gd
    php5.6-gd
    php7.0-gd
    php7.1-gd
    php7.2-gd
    php7.3-gd
    php7.4-gd
    php8.0-gd
  Depends: php-ldap
    php5.6-ldap
    php7.0-ldap
    php7.1-ldap
    php7.2-ldap
    php7.3-ldap
    php7.4-ldap
    php8.0-ldap
 |Depends: fonts-dejavu
 |Depends: ttf-dejavu-core
  Depends: <ttf-japanese-gothic>
  Suggests: zabbix-apache-conf
  Suggests: zabbix-nginx-conf
```

**To Reproduce**
1. Setup Sury PHP repository
2. Setup Zabbix repository
```sh
wget https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1+debian10_all.deb
sudo dpkg -i zabbix-release_5.2-1+debian10_all.deb
sudo apt update 
```
3. Install dependencies for the zabbix-frontend manually
```sh
sudo apt install php7.4 php7.4-fpm php7.4-cli php7.4-common php7.4-bcmath php7.4-gd php7.4-json php7.4-ldap php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-readline php7.4-xml
```
4. Try to install `zabbix-frontend-php` without installing php8.0
```sh
sudo apt install zabbix-frontend-php
```

**Expected behavior**

The zabbix package should install without install php8.0-mysql and its dependencies

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
This is a bit complicated. The package is named mysql for historical reasons, but the Provides line is generated from the names of included extensions - mysqli or mysqlnd. The zabbix package should depend on php-<ext_name> meta-name where <ext_name> is the actual extension used.

On the other hand, I understand this is little bit confusing and Provides: php_mysql might be useful.

**Comment by posledov** [comment]
Same situation with `phpmyadmin` package 😞 

```
# apt show phpmyadmin
Package: phpmyadmin
Version: 4:5.0.4+dfsg2-2
Priority: optional
Section: web
Maintainer: phpMyAdmin Packaging Team <team+phpmyadmin@tracker.debian.org>
…
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
…
```

```
# apt install -s -o Debug::pkgDepCache::AutoInstall=true phpmyadmin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 …
  Installing php-mysql:amd64 as Depends of phpmyadmin:amd64
    Installing php8.1-mysql:amd64 as Depends of php-mysql:amd64
…
```

```
# apt show php7.4-mysql
Package: php7.4-mysql
Version: 7.4.29-1+0~20220422.62+debian11~1.gbp6939ea
…
Provides: php-mysqli, php-mysqlnd, php-pdo-mysql, php7.4-mysqli, php7.4-mysqlnd, php7.4-pdo-mysql
…
APT-Manual-Installed: yes
APT-Sources: https://packages.sury.org/php bullseye/main amd64 Packages
…
```

**Comment by oerdnj** [comment]
> I think the php<X.Y>-mysql packages should provide the php-mysql package…

No, that would be wrong. The mysql extension has been removed and replaced with mysqli.

The external packages need to be updated to reflect this.

**Comment by posledov** [comment]
> The external packages need

Ondřej, first of all thank you for your reply.

As you can see the `phpmyadmin` is from debian repo, so sury's packages are more "external" then first one :)

Whenever… How it's possible to install `phpmyadmin` with already installed `php7.4` and without pinning? 🤓
