### ISSUE TITLE
When installing libapache2-mod-php on Debian 10, the PHP 8.0 version is shipped

### ISSUE THREAD

**Issue by thompol** [oerdnj/deb.sury.org#1548]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When installing libapache2-mod-php on Debian 10, the PHP 8.0 version is shipped. You would expect the default PHP version for Buster (7.3) to be installed. It used to be like that aswell, until PHP8 was added to the repo.

**To Reproduce**
1. Run `apt install libapache2-mod-php`

**Expected behavior**
libapache2-mod-php - version 7.3.X to be installed.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
`root@server1:/home/joe# apt-cache policy libapache2-mod-php` \
`libapache2-mod-php:` \
`  Installed: 2:7.3+69` \
`  Candidate: 2:8.0+80+0~20210220.33+debian10~1.gbp730ac0` \
`  Version table:` \
`     2:8.0+80+0~20210220.33+debian10~1.gbp730ac0 500` \
`        500 https://packages.sury.org/php buster/main amd64 Packages` \
` *** 2:7.3+69 500` \
`        500 http://deb.debian.org/debian buster/main amd64 Packages` \
`        500 http://mirror.hetzner.de/debian/packages buster/main amd64 Packages` \
`        100 /var/lib/dpkg/status`

**Comment by oerdnj** [comment]
No, this is not the purpose of this repository. The meta-package always depends on latest stable PHP version (with some grace period).
