### ISSUE TITLE
Error with Starting apcu-Extension

### ISSUE THREAD

**Issue by kayamaty** [oerdnj/deb.sury.org#1549]
Hello Ondrej,

since the last update from 20th of February I get the following error for the apcu extension:

php-fpm7.4[19421]: [22-Feb-2021 10:39:35] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' (tried: /usr/lib/php/20190902/apc.so (/usr/lib/php/20190902/apc.so: undefined symbol: zif_apcu_store), /usr/lib/php/20190902/apc.so.so (/usr/lib/php/20190902/apc.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Nothing changed on config, just ran a apt upgrade.

I´m not sure what changed but something does.

Kind regards

Steffen

**Comment by oerdnj** [comment]
Please use issue templates for filling bugs. It has all the questions I would have to ask again here.
