### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by Schampango** [oerdnj/deb.sury.org#1550]
Hello,
after the last update of PHP7.3 the apc.so does not load anymore.

The following message appears:
root@bambi:~# php -i
PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' (tried: /usr/lib/php/20180731/apc.so (/usr/lib/php/20180731/apc.so: undefined symbol: apc_iterator_obj_init), /usr/lib/php/20180731/apc.so.so (/usr/lib/php/20180731/apc.so.so: undefined symbol: apc_iterator_obj_init)) in Unknown on line 0
phpinfo()
PHP Version => 7.3.27-7+0~20210220.80+debian9~1.gbpccb1ab
...

Here is an ls from the module:
root@bambi:~# ls -l /usr/lib/php/20180731/apc.so
-rw-r--r-- 1 root root 14944 Dez 10 22:18 /usr/lib/php/20180731/apc.so

Can I provide more info?

Best regards
Daniel

**Comment by oerdnj** [comment]
Use issue templates, it has all the questions I need answered.
