### ISSUE TITLE
Changed Depends: on 5.1.19+4.0.11-7 breaks non-8 versions

### ISSUE THREAD

**Issue by sysadmin1139** [oerdnj/deb.sury.org#1551]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The virtual package `php-acpu` version 5.1.19+4.0.11-7 lists the following for dependencies and suggestions:

```
Package: php-apcu
Status: install ok installed
Priority: optional
Section: php
Installed-Size: 15
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Architecture: amd64
Version: 5.1.19+4.0.11-7+ubuntu16.04.1+deb.sury.org+1
Depends: php8.0-apcu
Pre-Depends: php-common (>= 2:69~)
Recommends: php-apcu-bc
Suggests: php-gd
Conflicts: php-xcache, php-yac
```
The next previous version, 5.1.19+4.0.11-4, shows:
```
 Package: php-apcu
 Version: 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1
 Architecture: amd64
 Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
 Installed-Size: 15
 Pre-Depends: php-common (>= 2:69~)
 Depends: php8.0-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php7.4-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php7.3-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php7.2-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php7.1-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php7.0-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~), php5.6-apcu (>= 5.1.19+4.0.11-4+ubuntu16.04.1+deb.sury.org+1~)
 Recommends: php-apcu-bc
 Suggests: php-gd
 Conflicts: php-xcache, php-yac

```

Changing the depends in this way breaks the previous behavior of installing all existing php(version)-apcu packages.

**To Reproduce**
1. apt-get install php-acpu
2. dpkg --list php*-apcu

The list of installed packages shows:
* php-apcu
* php-apcu-bc
* php7.4-apcu
* php7.4-apcu-bc
* php8.0-apcu

**Expected behavior**
1. apt-get install php-acpu
2. dpkg --list php*-apcu

The list of installed packages shows:
* php-apcu
* php5.6-apcu
* php7.0-apcu
* php7.1-apcu
* php7.2-apcu
* php7.3-apcu
* php7.4-apcu
* php8.0-apcu

**Distribution (please complete the following information):**
Ubuntu 16.04 AMD64, Launchpad PPA

**Package(s) (please complete the following information):**
```
$ apt-cache policy php-apcu
php-apcu:
  Installed: 5.1.19+4.0.11-7+ubuntu16.04.1+deb.sury.org+1
  Candidate: 5.1.19+4.0.11-7+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 5.1.19+4.0.11-7+ubuntu16.04.1+deb.sury.org+1 999
        500 https://[private artifactory]/ppa-ondrej-php7 xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.3+4.0.10-1build1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

**Comment by oerdnj** [comment]
Yes, as described here: https://www.patreon.com/posts/47793617
