### ISSUE TITLE
memcached auto-removed?

### ISSUE THREAD

**Issue by jorismak** [oerdnj/deb.sury.org#1552]
I'm _asking_ here if there might be some change that can be related to this.
Honestly, I think it's something else on my systems so I'm not creating a 'full fledged issue'.

Yesterday some servers running the Ondrej PPA repositories decided to uninstall the memcached and igbinary extensions for all installed PHP versions (7.2, 7.3, 7.4, 8.0).

I could simple 'reinstall' them and all is fine.. and I see from the Ubuntu unattended-upgrades that both memcached and igbinary are removed.. but I'm still scratching my head why.

Did something change ? I see no recent commits in this repo that could cause something like that, but I assume the packages are also fetching changes from upstream somewhere?

If nothing comes to mind, so be it. Like I said, it's probably more a Ubuntu / Debian config issue than a Ondrej-PPA issue.
-------

Ubuntu 18.04 LTS x64_64 http://ppa.launchpad.net/ondrej/php/ubuntu bionic main

**Comment by oerdnj** [comment]
This https://www.patreon.com/posts/47793617

**Comment by jorismak** [comment]
Thanks!.

Let's see if I understand it correctly: From reading that it seems I was doing things wrong for quite some time by installing 'php-memcached' which would install all versions... If I wanted memcached for specific versions I should have installed those instead of relying on the php-memcached 'meta' package.
php-memcached changed from targeting all versions to targeting the latest 'official' or 'default' one, so all older versions got auto-removed.

Am I close? :)

**Comment by oerdnj** [comment]
The split into versioned packages caused a quite bit of turmoil (#1465), so yes, for some time, it was better to install specific versioned packages.
