### ISSUE TITLE
smbclient:: symbol smbc_setOptionProtocols not defined

### ISSUE THREAD

**Issue by theroch** [oerdnj/deb.sury.org#1553]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Updated from php7.4-smbclient(1.0.0-3+ubuntu18.04.1+deb.sury.org+1) to php7.4-smbclient (1.0.5-5+ubuntu18.04.1+deb.sury.org+1)

If I start php I've got following error:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'smbclient.so' (tried: /usr/lib/php/20190902/smbclient.so (/usr/lib/php/20190902/smbclient.so: symbol smbc_setOptionProtocols version SMBCLIENT_0.2.3 not defined in file libsmbclient.so.0 with link time reference), /usr/lib/php/20190902/smbclient.so.so`

I'm using latest libsmbclient/bionic,now 2:4.10.18+karoshi-1~linuxschools1+bionic1 which contains support for 'smbc_setOptionProtocols'.

Because the only update was the one of php7.4-libsmbclient and the libsmbclient was untouched it have something to do with your latest package.

**To Reproduce**
1. Update to php7.4-smbclient (1.0.5-5+ubuntu18.04.1+deb.sury.org+1)
2. Install libsmbclient (libsmbclient/bionic,now 2:4.10.18+karoshi-1~linuxschools1+bionic1)
3. run `php -v`

**Expected behavior**
Version output without error

**Distribution (please complete the following information):**
 - OS: Ubuntu bionic latest updates
 - Architecture: VM
 - Repository: http://ppa.launchpad.net/ondrej/php/ubuntu bionic main

**Additional context**
I've solved the problem while removing php7.4-smbclient and installed latest version with pecl
`pecl -d php_suffix=7.4 install smbclient`

I don't know why but the version from pecl works fine, although the versions (v1.0.5) seem to be the same?

**Comment by oerdnj** [comment]
Latest libsmbclient Ubuntu bionic version is 2:4.7.6+dfsg~ubuntu-0ubuntu2.21, I can't support derivatives.
