### ISSUE TITLE
Phalcon3 for PHP 7.3

### ISSUE THREAD

**Issue by angoras** [oerdnj/deb.sury.org#1556]
Hi!

We use Phalcon 3 with PHP 7.3 on Ubuntu 16.04, but today I get the error message that package php-phalcon3 doesn't exist. So just wondering if this is an error or if it has been discontinued or something? I can't find any info about it.

Thank you for your hard work btw! :)

**Comment by oerdnj** [comment]
The package was not building, so I removed it until the build was fixed (which happened over the weekend).

As a side note, phalcon3 has been discontinued by upstream and it's not getting any updates.

**Comment by angoras** [comment]
Ah, I see. Thank you for clarifying! :)
