### ISSUE TITLE
bump nginx-mainline to 1.19.7

### ISSUE THREAD

**Issue by olewales** [oerdnj/deb.sury.org#1557]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

nginx-mainline seems to be a bit behind official release and there were some segfaults fixed since packaged version:
http://nginx.org/en/CHANGES

**Comment by oerdnj** [comment]
nginx 1.19.7 is now available.
