### ISSUE TITLE
Some PHP 8.0 extension is missing

### ISSUE THREAD

**Issue by joglomedia** [oerdnj/deb.sury.org#1558]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
I try new PHP 8.0 (migrating from 7.4)
Unfortunately some of extensions is missing

**To Reproduce**
sudo apt install -y php8.0 php8.0-bcmath php8.0-bz2 php8.0-calendar php8.0-cli php8.0-common php8.0-curl php8.0-dev php8.0-exif php8.0-fpm php8.0-gd php8.0-gettext php8.0-gmp php8.0-gnupg php8.0-iconv php8.0-imap php8.0-intl php8.0-json php8.0-mbstring php8.0-mysql php8.0-opcache php8.0-pdo php8.0-posix php8.0-pspell php8.0-readline php8.0-ldap php8.0-snmp php8.0-soap php8.0-sqlite3 php8.0-tidy php8.0-tokenizer php8.0-xml php8.0-xmlrpc php8.0-xsl php8.0-zip php-pear php-xml pkg-php-tools

E: Unable to locate package php8.0-gnupg
E: Couldn't find any package by glob 'php8.0-gnupg'
E: Couldn't find any package by regex 'php8.0-gnupg'
E: Package 'php8.0-json' has no installation candidate

**Expected behavior**
Requested package installed

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
masedi@dev ~ $ sudo apt-cache policy php8.0-gnupg
php8.0-json:
  Installed: (none)
  Candidate: (none)
  Version table:
N: Unable to locate package php8.0-gnupg
N: Couldn't find any package by glob 'php8.0-gnupg'
N: Couldn't find any package by regex 'php8.0-gnupg'
masedi@dev ~ $ sudo apt-cache policy php8.0-json

**Additional context**
N/A

**Comment by oerdnj** [comment]
* json is included in the base binaries, but I get I need to make this more prominent
* gnupg doesn't have support PHP 8.0 yet (please always check that in PECL)
