### ISSUE TITLE
404 for some phps

### ISSUE THREAD

**Issue by PVasileff** [oerdnj/deb.sury.org#1559]
Hello,

On some of main servers with Debian 10 (buster) I got errors 404 for some packages:

# apt-get update
```
Hit:1 http://ftp.bg.debian.org/debian buster InRelease
Hit:2 http://ftp.bg.debian.org/debian buster-updates InRelease                                                       
Hit:3 http://ftp.debian.org/debian buster-backports InRelease                                                        
Hit:4 http://security.debian.org buster/updates InRelease                                      
Hit:5 https://packages.sury.org/php buster InRelease                     
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-xml_7.4.15-7+0~20210227.41+debian10~1.gbpb91400_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-readline_7.4.15-7+0~20210227.41+debian10~1.gbpb91400_amd64.deb  404  Not Found [IP: 172.67.182.150 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

In https://packages.sury.org/php/pool/main/p/php7.4/ 

I see that packages but may be with different names?

Can you fix that ?

**Comment by oerdnj** [comment]
I flushed the entire Cloudflare cache again

**Comment by mjoelweb** [comment]
im having same issue today. how do i solve this ?

**Comment by mjoelweb** [comment]
> im having same issue today. how do i solve this ?
solution
https://dietpi.com/phpbb/viewtopic.php?t=8825

**Comment by BonBonSlick** [comment]
```
The following NEW packages will be installed:                                                        
  libapache2-mod-php7.2 php7.2 php7.2-cli php7.2-json php7.2-opcache php7.2-readline                 
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.                                       
Need to get 3,093 kB of archives.                                                                    
After this operation, 10.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://packages.sury.org/php buster/main amd64 php7.2-json amd64 7.2.34-18+0~20210223.60+debi$
n10~1.gbpb21322
  404  Not Found [IP: 172.67.182.150 443]
Err:2 https://packages.sury.org/php buster/main amd64 php7.2-opcache amd64 7.2.34-18+0~20210223.60+d$
bian10~1.gbpb21322
  404  Not Found [IP: 172.67.182.150 443]
Err:3 https://packages.sury.org/php buster/main amd64 php7.2-readline amd64 7.2.34-18+0~20210223.60+$
ebian10~1.gbpb21322
  404  Not Found [IP: 172.67.182.150 443]
Err:4 https://packages.sury.org/php buster/main amd64 php7.2-cli amd64 7.2.34-18+0~20210223.60+debia$
10~1.gbpb21322
  404  Not Found [IP: 172.67.182.150 443]
Err:5 https://packages.sury.org/php buster/main amd64 libapache2-mod-php7.2 amd64 7.2.34-18+0~202102$
3.60+debian10~1.gbpb21322
  404  Not Found [IP: 172.67.182.150 443]
Err:6 https://packages.sury.org/php buster/main amd64 php7.2 all 7.2.34-18+0~20210223.60+debian10~1.$
bpb21322

```

and thousands more

**Comment by BonBonSlick** [comment]
UPD, redownloading gpg key solved my issue.
```

wget https://packages.sury.org/php/apt.gpg

sudo apt-key add apt.gpg
```

**Comment by cfficaurzua** [comment]
Hi, I need to install php7.4-intl, but it fails, I tried downloading gpg key, but it didn't solve it
`Reading package lists... Done

Building dependency tree
Reading state information... Done

The following additional packages will be installed:
  php7.4-intl

The following NEW packages will be installed:
  php-intl php7.4-intl

0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 133 kB of archives.

After this operation, 534 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y

Err:1 https://packages.sury.org/php buster/main amd64 php7.4-intl amd64 7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0
  404  Not Found [IP: 138.199.40.58 443]

Err:2 https://packages.sury.org/php buster/main amd64 php-intl all 2:7.4+75+0~20200423.24+debian10~1.gbp7ccdd5
  404  Not Found [IP: 138.199.40.58 443]

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.4/php7.4-intl_7.4.5-1+0~20200419.16+debian10~1.gbpc40fd0_amd64.deb  404  Not Found [IP: 138.199.40.58 443]

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-defaults/php-intl_7.4+75+0~20200423.24+debian10~1.gbp7ccdd5_all.deb  404  Not Found [IP: 138.199.40.58 443]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by bashgeek** [comment]
PHP 7.4 has reached end of life and is not supported/provided anymore. Please update your system(s).

**Comment by oerdnj** [comment]
> PHP 7.4 has reached end of life years ago and is not supported/provided anymore. Please update your system(s).

While technically true, the very purpose of this repository is to provide access to older PHP versions with security updates.

**Comment by bonnebulle** [comment]
I had the same issue, on RaspberryPI (armhf)
I follow [this](https://community.passbolt.com/t/raspberry-pi-install/9558/4) to install all the extensions :
- php8.3-intl
- php8.3-tidy
(installing wallabag, again)

**Comment by Caprico85** [comment]
Also missing the imagick extensions (e.g. `php8.3-imagick`).
