### ISSUE TITLE
The latest php7.4 build is an unreleased snapshot build

### ISSUE THREAD

**Issue by joec4i** [oerdnj/deb.sury.org#1562]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
It seems the current php7.4 build from the deb.sury.repo is a snapshot build that's marked as `UNRELASED`. I'm not sure if this is a mistake. I only noticed this because we have a few nodes on the snapshot build having a lot more segfaults than other nodes that are on an older version. We are still investigating the segfaults so unsure if the current build has anything to do with them, but I think it's worth reporting the issue here. Thanks!

**To Reproduce**
```bash
root@debian-10:/usr/src/php/php7.4-7.4.15/debian# zcat /usr/share/doc/php7.4-common/changelog.Debian.gz | head
php7.4 (7.4.15-7+0~20210227.41+debian10~1.gbpb91400) unstable; urgency=medium

  ** SNAPSHOT build @b914008d9b0c1c80935d2c151386bb3366893e23 **

  * UNRELEASED

 -- Ondřej Surý <ondrej@sury.org>  Sat, 27 Feb 2021 16:45:26 +0100

php7.4 (7.4.15-7) unstable; urgency=medium

root@debian-10:/usr/src/php/php7.4-7.4.15/debian# apt-cache policy php7.4-fpm
php7.4-fpm:
  Installed: 7.4.15-7+0~20210227.41+debian10~1.gbpb91400
  Candidate: 7.4.15-7+0~20210227.41+debian10~1.gbpb91400
  Version table:
 *** 7.4.15-7+0~20210227.41+debian10~1.gbpb91400 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
**Expected behavior**
The latest build should include meaningful changelogs, and ideally, not an `UNRELEASED` build.

**Distribution (please complete the following information):**
 - OS: Debian Buster
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
root@debian-10:/usr/src/php/php7.4-7.4.15/debian# apt-cache policy php7.4-fpm
php7.4-fpm:
  Installed: 7.4.15-7+0~20210227.41+debian10~1.gbpb91400
  Candidate: 7.4.15-7+0~20210227.41+debian10~1.gbpb91400
  Version table:
 *** 7.4.15-7+0~20210227.41+debian10~1.gbpb91400 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
**Additional context**
N/A

**Comment by oerdnj** [comment]
That's just a relict of the build system used (https://jenkins-debian-glue.org) that creates snapshots from the git and it allows rebuilding the same version without making dummy changelog entry every time a rebuild is needed.

This is the way how the packages are build, you just ignore the first entry in the changelog.
