### ISSUE TITLE
Repository 'https://packages.sury.org/nginx-mainline buster InRelease' changed its 'Origin' value from '' to 'deb.sury.org'

### ISSUE THREAD

**Issue by NielsH** [oerdnj/deb.sury.org#1565]
Hello,

We are seeing the following error today on our servers using the following repo when we run an `apt update`:
```
deb https://packages.sury.org/nginx-mainline/ buster main
```

```
E: Repository 'https://packages.sury.org/nginx-mainline buster InRelease' changed its 'Origin' value from '' to 'deb.sury.org'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

We only see it on Debian 10, not on 9.
It's fixable with `apt update --allow-releaseinfo-change` - however Ansible does not natively support this flag and as such we get an error during deployments.

We can just run the command manually once on all of our servers to fix it, but would just like to report the issue and ask if this was intended (and if so, should we prepare for Debian 9 servers to also receive this change soon?)

Cheers

Niels

**Comment by oerdnj** [comment]
I reverted the change and I think I have found a way how to make a change that would not require a manual intervention.

**Comment by NielsH** [comment]
Thank you! Looking good here so-far!

**Comment by oerdnj** [comment]
FTR It's two step process - first `Signed-By:` field needs to be added to `Release` file and then any changes to the `Release` file signed by the GPG key listed in the `Signed-By:` field are automatically accepted.

**Comment by videochums** [comment]
Hello. I got a similar error when trying `sudo update` today:

```
E: Repository 'https://packages.sury.org/apache2 bullseye InRelease' changed its 'Origin' value from '' to 'deb.sury.org'

N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

**Comment by oerdnj** [comment]
That's result of #1942, but apparently the `Signed-By:` method no longer works, because both `buster` and `bullseye` already had `Signed-By` field.

I guess you'll have to approve the Origin change manually then.

**Comment by KodaCHC** [comment]
>>I guess you'll have to approve the Origin change manually then.
How can I do this?

**Comment by videochums** [comment]
In case anyone arrives here wanting to know how to approve the origin change then all you need to do is this once:
`sudo apt-get update --allow-releaseinfo-change`

**Comment by oerdnj** [comment]
> In case anyone arrives here wanting to know how to approve the origin change then all you need to do is this once:
> `sudo apt-get update --allow-releaseinfo-change`

Thanks for highlighting this, but it's literally in the first message here. That's why I pinned this.
