### ISSUE TITLE
php-imagick for php7

### ISSUE THREAD

**Issue by FabianKoestring** [oerdnj/deb.sury.org#157]
Please add it to the ppa.

Great Work!

**Comment by tschoffelen** [comment]
+1 on this. Thanks for the effort!

**Comment by FabianKoestring** [comment]
I dont want to advertise another ppa but here you can get `php7.0-imagick`.

https://launchpad.net/~jbboehr/+archive/ubuntu/php-7.0?field.series_filter=trusty

**Comment by oerdnj** [comment]
I would advice patience, young padawan :).

I already built apcu, so imagick (and other PECL modules) is just behind the corner...

**Comment by oerdnj** [comment]
fixed in php-imagick_3.4.0~rc2-1+deb.sury.org~<dist>+1

**Comment by FabianKoestring** [comment]
Niiiice! :+1:
