### ISSUE TITLE
php-gnupg is not satisfied with php 7.4

### ISSUE THREAD

**Issue by isukapalli** [oerdnj/deb.sury.org#1571]
**Describe the bug**
The current PHP extension GnuPG support only the php7.3 version but not 7.4.

https://packages.debian.org/buster/php-gnupg has details and dependencies.

The extension shows up under `/etc/php/7.3/mods-available` folder instead `/etc/php/7.4/mods-available`

```
root@dokken:/# php -v
PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

root@dokken:/etc/php/7.3/mods-available# ls gnupg.ini
gnupg.ini

root@dokken:/etc/php/7.4/mods-available# ls -l gnupg.ini
ls: cannot access 'gnupg.ini': No such file or directory
```

**Note:** It's a new package request in deb.sury.org for PHP 7.4

**Comment by oerdnj** [comment]
Please use the issue templates when filling new bugs, it contains all the questions that I will have to ask you, so I am closing this bug.
