### ISSUE TITLE
php-gnupg extension not available for php7.4

### ISSUE THREAD

**Issue by isukapalli** [oerdnj/deb.sury.org#1572]
**Describe the bug**
Php-gnupg extension is available for 7.3 version but not for 7.4

**To Reproduce**
1. apt-get install php-gnupg
2. it gets installed under /etc/php/7.3 and also dependencies of 7.3 but not 7.4
```
root@dokken:/etc/php/7.3/mods-available# ls gnupg.ini
gnupg.ini
```
https://packages.debian.org/buster/php-gnupg

**Expected behavior**
The extension should be available for php 7.4 version

```
root@dokken:/# php -v
PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

root@dokken:/etc/php/7.4/mods-available# ls -l gnupg.ini
ls: cannot access 'gnupg.ini': No such file or directory
``` 

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
root@dokken:/# apt-cache search php-gnupg
php-gnupg - PHP wrapper around the gpgme library
```

**Additional context**

**Comment by oerdnj** [comment]
Much better, the `src:php-gnupg` was missing from the Debian repository. Now, the `php7.4-gnupg` package is available (also added `1.5.0~RC2` to support PHP 8.0 in one go).
