### ISSUE TITLE
New package signature

### ISSUE THREAD

**Issue by NaLiJa** [oerdnj/deb.sury.org#1574]
Sorry to ask (and for the foreign language), but I get an error about an invalid sigature. Was the repo key regenerated?
Thanks!

Fehl:4 https://packages.sury.org/php buster InRelease
  Die folgenden Signaturen waren ungültig: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
Es wurden 65,4 kB in 0 s geholt (240 kB/s).
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: https://packages.sury.org/php buster InRelease: Die folgenden Signaturen waren ungültig: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Fehlschlag beim Holen von https://packages.sury.org/php/dists/buster/InRelease Die folgenden Signaturen waren ungültig: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

**Comment by oerdnj** [comment]
Yes, see: https://www.patreon.com/posts/february-update-47617742
