### ISSUE TITLE
Debian Stretch php-phalcon3 package empty

### ISSUE THREAD

**Issue by AllenRDCo** [oerdnj/deb.sury.org#1578]
**Frequently asked questions**

- [X ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

The Phalcon packages for Debian Buster and Stretch AMD64 on packages.sury.org appear to be empty and when installed/upgraded results in no .so file for phalcon installed. Looking at the Packages files appears to confirm this as the packages are now only shown as being about 4K in size:

```
Package: php-phalcon3
Version: 3.4.5-5+0~20210228.6+debian10~1.gbp8a5fc4
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 17
Pre-Depends: php-common (>= 2:69~)
Depends: ucf
Breaks: php-phalcon (<< 3.4.5-2~)
Replaces: php-phalcon (<< 3.4.5-2~)
Provides: php-phalcon
Homepage: https://phalconphp.com/
Priority: optional
Section: php
Filename: pool/main/p/php-phalcon3/php-phalcon3_3.4.5-5+0~20210228.6+debian10~1.gbp8a5fc4_amd64.deb

Size: 4720 <- 4.7K when it used to be 4.2MB

SHA256: d9cb610a809c201a1e7eaa9a96d6890bdca3e1ad5d3ef43f37ad6e62c4372fe6
SHA1: ecb1086e8d1aea424c83f485a0391a2fa95fdacd
MD5sum: a123c8701b3f28ba9466e90861b2c9d4
```
I also extracted the .deb for php-phalcon3 (php-phalcon3_3.4.5-5+0~20210228.6+debian9~1.gbp8a5fc4_amd64.deb) and verified there is virtually nothing in it.

For now I am re-installing the previous version from /var/cache/apt on our affected servers so it's not breaking our production systems but I imagine this will be an issue for any new users.

Thanks for the help!

**Comment by AllenRDCo** [comment]
While doing updates on another of our servers that has Phalcon installed I realized what is probably going on. On those other servers we have the php version specific packages installed: 
`$ dpkg -l | grep phal
ii  php7.0-phalcon                    3.4.5-1+php7.0                                                           amd64        High performance PHP framework
ii  php7.4-phalcon                    4.1.0-1099+php7.4                                                        amd64        High performance PHP framework
`

We have already being going through the mess that the migration from php-* packages to php<vers>-* packages has caused with ones like php-imagick, php-memcache, etc.

I realized this must be along the same lines. However instead of the php-phalcon3 package pulling in php8.0-phalcon3 for example it is just installing an empty package instead. I noticed when looking at the pool directory on packages.sury.org there are the php version specific packages for phalcon3 that are all clearly the fully packages. 

I'm going to go through our systems and install the PHP version specific phalcon packages to fix this on our side, but that php-phalcon3 and php-phalcon4 packages need to be looked at still I believe. 

Speaking of the whole php-* to php<vers>-* migration, is there any notification email list or something we can get on to be made aware of these changes ahead of time before we run into it on production systems during patches? The majority of our clients are on production only systems, there are very few that have development machines we can catch this on first before production is affected. This is especially a concern since it seems there will be issues with the php-* packages not pulling in version specific packages and instead breaking installations.

Thanks!

**Comment by oerdnj** [comment]
I'll look into this soon.

> Speaking of the whole php-* to php-* migration, is there any notification email list or something we can get on to be made aware of these changes ahead of time before we run into it on production systems during patches?

I post the updates to https://patreon.com/oerdnj and all the news also gets copied to GitHub Sponsors.

**Comment by oerdnj** [comment]
I've finally found the time to update the packaging, so the phalcon3, phalcon4 and phalcon5 packages should be available and working.
