### ISSUE TITLE
Unable to get some php extensions

### ISSUE THREAD

**Issue by MetalArend** [oerdnj/deb.sury.org#1583]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
404 Not Found error when trying to install php7.4-pgsql, php7.4-amqp or php7.4-ssh2

**To Reproduce**
As described in both #1434 and #1559

**Expected behavior**
Things should resolve ;)

**Distribution (please complete the following information):**
 - php 7.4 docker image based on debian

**Comment by oerdnj** [comment]
I need a description how it doesn't work for you, the distribution and exact versions of the packages you are trying to install.

**Comment by MetalArend** [comment]
It seems to be resolved - I do not know what I did meanwhile, but something got fixed somehow :) Sorry for the interrupt, and thanks for the fast reply!
