### ISSUE TITLE
Please add php8.0-uploadprogress on Debian

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1584]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

AFAICT php8.0-uploadprogress is not available in either amd64 or arm64. I have php-uploadprogess installed; php8.0-uploadprogress is not available. `php -i` doesn't show uploadprogress from anywhere else

**To Reproduce**

`sudo apt-get update && sudo apt-get install php8.0-uploadprogress`

**Expected behavior**

It seems that it should be available: https://pecl.php.net/package/uploadprogress

**Distribution (please complete the following information):**
 - OS: [Debian]
 - Architecture: [both amd64 and arm64]
 - Repository: [packages.sury.org]

**Package(s) (please complete the following information):**
```
$ sudo apt-cache policy php8.0-uploadprogress
N: Unable to locate package php8.0-uploadprogress
N: Couldn't find any package by glob 'php8.0-uploadprogress'
N: Couldn't find any package by regex 'php8.0-uploadprogress'
```
**Additional context**

**Comment by oerdnj** [comment]
Removed patch that limited build to PHP < 8, and it works like a charm. Uploaded.
