### ISSUE TITLE
Compression support for php-redis

### ISSUE THREAD

**Issue by iliaal** [oerdnj/deb.sury.org#1585]
**Is your feature request related to a problem? Please describe.**
Enable compression support for php-redis extension, in particular support for lz4 would be very helpful. This would allow minimization of network traffic between redis client/server.

**Describe the solution you'd like**
When compiling php-redis extension please add the following configure flags `--enable-redis-lzf`, `--enable-redis-lz4` and `--enable-redis-zstd`. lz4 in particular may require libz4 library to be installed.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**
```php7.3-redis:
  Installed: 5.3.4+4.3.0-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 5.3.4+4.3.0-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 5.3.4+4.3.0-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status```

**Comment by oerdnj** [comment]
Uploaded, let's see what happens.
