### ISSUE TITLE
[PHP7.0] Please include php-amqp module

### ISSUE THREAD

**Issue by guilhermeblanco** [oerdnj/deb.sury.org#159]
AMQP is an application layer protocol for message exchanging, very useful to decouple mid-large sized systems and handle work distribution.

PECL offers the AMQP 0.9.1 compatibility module (PECL: https://pecl.php.net/package/amqp, Code: https://github.com/pdezwart/php-amqp) that can be used with compatible software, such as RabbitMQ, ZeroMQ, Qpid, OpenAMQP, etc.

Adding this module support would enable a lot more mid-sized projects to migrate to PHP 7.0. It also requires a newer version of `librabbitmq1` (Code: https://github.com/alanxz/rabbitmq-c). 

* In Ubuntu 12.04, the packaged library is named `librabbitmq0` and its version is 0.0.1.hg216 (code refers to original `rabbitmq-c` implementation, very unsupported and not compatible with 0.9.1 protocol (only 0.8). PECL library only works with this package in version 0.2.*).
* In Ubuntu 14.04, the packaged library version is 0.4.1.
* In any other Ubuntu releases after 14.04, package version is 0.5.2.

To support the PHP module, it would be required to also provide a compiled `librabbitmq1` at minimum version 0.5.0 (ideally latest). Latest minor version is 0.7+ (patch level release is 0.7.1 as of Dec 8th, 2016). It supports non-blocking sockets internally, providing an incredible performance boost to consumers.

**Comment by oerdnj** [comment]
This shouldn't be hard, but please let me finish porting existing modules before introducing new ones. Ping me in week or two if nothing happens.

**Comment by guilhermeblanco** [comment]
Sure thing. =) 
In the meantime I compiled myself (and yes, it's not hard), but you'll have to use master (currently 1.7.0alpha1) of `php-amqp` since 1.6.1 refuses to `make`.
And don't forget `pkg-config` to compile `librabbitmq`. It's not checked properly checked.

Quick steps I've done:

**librabbitmq1**

```bash
sudo apt-get purge librabbitmq1 librabbitmq-dev librabbitmq-dbg
sudo apt-get install libtool automake autoconf pkg-config
cd ~
git clone git@github.com:alanxz/rabbitmq-c.git
cd rabbitmq-c
git checkout tags/v0.7.1
git submodule init && git submodule update
autoreconf -i && ./configure && make && sudo make install
```

**PECL amqp**

```bash
sudo apt-get install php7.0-dev
git@github.com:pdezwart/php-amqp.git
cd php-amqp
phpize && ./configure && make && sudo make install
sudo echo 'extension=amqp.so' > /etc/php/mods-available/amqp.ini
sudo ln -s /etc/php/mods-available/amqp.ini /etc/php/7.0/cli/conf.d/20-amqp.ini
sudo ln -s /etc/php/mods-available/amqp.ini /etc/php/7.0/fpm/conf.d/20-amqp.ini
```

**Comment by oerdnj** [comment]
I don't think it's hard, but I have a rule -> everything stable I do goes to Debian first (even though it might sit in NEW queue or get rejected), so it needs some extra work to have that properly packaged, perhaps librabbitmq updated in Debian, etc.

So the work I do has a benefit for more people than just the PPA users...

**Comment by oerdnj** [comment]
Done
