### ISSUE TITLE
PHP 8.0 memcached : undefined symbol: igbinary_serialize 

### ISSUE THREAD

**Issue by stathis** [oerdnj/deb.sury.org#1590]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
After installing php8.0-memcached, php commands produce this warning:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20200930/memcached.so (/usr/lib/php/20200930/memcached.so: undefined symbol: igbinary_serialize), /usr/lib/php/20200930/memcached.so.so (/usr/lib/php/20200930/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**To Reproduce**
1. Install php8.0-memcached
2. `php -v`

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
php8.0-memcached/bionic,now 3.1.5+2.2.0-9+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php8.0-msgpack/bionic,now 2.1.2+0.5.7-6+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php8.0-igbinary/bionic,now 3.2.1+2.0.8-6+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
```
**Other info:**
- I've confirmed that `/usr/lib/php/20200930/memcached.so` exists on the filesystem.
- No warnings with other PHP versions

**Comment by oerdnj** [comment]
1. Is `igbinary` enabled?
2. Do `ls -l /etc/php/8.0/*/conf.d/*igbinary.ini` and post the output here.
3. Do `ls -l /etc/php/8.0/*/conf.d/*memcached.ini` and post the output here.
4. Do `cat /etc/php/8.0/mods-available/memcached.ini` and post the output here.
5. Do `cat /etc/php/8.0/mods-available/igbinary.ini` and post the output here.

**Comment by stathis** [comment]
Good catch! No, the symlink is not there, but the actual INIs are in the available directory.
I tried to `--reinstall` but it doesn't fix it.
Should I just recreate the symlinks?

**Comment by oerdnj** [comment]
Fix you provisioning then.

**Comment by stathis** [comment]
It happened directly after `apt-get install php8.0-memcached` manually nothing special there.
I had to `--purge` memcached, redis, igbinary and reinstall them.

**Comment by oerdnj** [comment]
I am 100% sure this is a local problem. You might not remember it or you don't know about it, but you would have to provide a reproducer in clean environment to prove this is a bug in the package.

Unfortunately, I've seen this too many times, and there's no code in the package that would leave the system in the state you have described.
