### ISSUE TITLE
Support for Ubuntu 21.04 (Hirsute Hippo)

### ISSUE THREAD

**Issue by apblack96** [oerdnj/deb.sury.org#1591]
**Frequently asked questions**

- [ ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Problem is that currently we are unable to use the repository on Ubuntu 21.04

**Describe the solution you'd like**
Would like support for the latest version of Ubuntu released on 04/22/2021.

**Describe alternatives you've considered**
N/A

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **request** accurately (where the template below will help), I might be able to help you.

**Distribution (please complete the following information):**
 - OS: Ubuntu 21.04 (Hirsute Hippo)
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
I'm sure this is already being worked on, but wanted to submit an issue for tracking purposes as well as to get a timeline on when this would be complete. In my case I specifically need php7.3, but I'm sure others will need access to other versions of php as well.

**Comment by jayshields** [comment]
A temporary fix is as follows;

Open Software & Updates, Other Software, select the ondrej/php repo (not the Source Code one). Click Edit. Change distribution from "hirsute" to "groovy". Then back to terminal and run `sudo apt-get update` and then whatever else you want, eg. `sudo apt-get install php7.3`.

**Comment by oerdnj** [comment]
I'll start uploading the packages with the next PHP update.

I kind of consider packaging for the intermittent releases to be waste of resources and time, so as a workaround I would recommend to perhaps not upgrade?

**Comment by abdulmueid** [comment]
@jayshields thanks for the workaround.

@oerdnj For me personally, I like running an up-to-date desktop/workstation, while targeting Ubuntu LTS on the server. This repo has been solid and dependable without worrying about which version of PHP comes bundled with Ubuntu. Ultimately it's your decision.

**Comment by lorenzleutgeb** [comment]
"don't upgrade" might work for people that casually keep their system(s) updated. However, there are users like me that use your PPA to automatically install PHP to images. My builds run on a daily basis, and switch to the newest version of Ubuntu as soon as it becomes available (max. 24h later). And these builds fail since the release off Hirsute Hippo.

**Comment by BurningC4** [comment]
Ubuntu 21.04 arm64 is still not support

**Comment by eilandert** [comment]
Hi,

While migrating my docker from Groovy to Hirsute we seem to be missing some php modules which are present in Groovy

E: Unable to locate package php5.6-igbinary
E: Unable to locate package php5.6-imagick
E: Unable to locate package php5.6-memcache
E: Unable to locate package php5.6-memcached
E: Unable to locate package php5.6-redis

(not including packages which we are not using)

Any idea?

**Comment by loxK** [comment]
@oerdnj do you plan to add "hirsute"' support to apache2 and nginx ppa too ?
