### ISSUE TITLE
extension php8.0-geoip missing

### ISSUE THREAD

**Issue by c33s** [oerdnj/deb.sury.org#1592]
looks like nobody is using geoip any more

**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
please add geoip to php8

**Distribution (please complete the following information):**
 - OS: debian buster
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

```
apt-cache policy php8.0-geoip
N: Unable to locate package php8.0-geoip
N: Couldn't find any package by glob 'php8.0-geoip'
N: Couldn't find any package by regex 'php8.0-geoip'

apt-cache policy php-geoip
php-geoip:
  Installed: (none)
  Candidate: 1.1.1-12+0~20210301.19+debian10~1.gbp85682e
  Version table:
     1.1.1-12+0~20210301.19+debian10~1.gbp85682e 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     1.1.1-3 500
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
```
but php-geoip gets only installed for php7.4

**Comment by sokai** [comment]
Maybe because [„MaxMind will be retiring the GeoIP Legacy databases at the end of May 2022“](https://github.com/maxmind/geoip-api-php#end-of-life).(?)

**Comment by Zenexer** [comment]
Install `php8.0-maxminddb` instead, which uses the newer GeoIP2 format.  The legacy GeoIP format is deprecated.

**Comment by c33s** [comment]
doesn't look like the `geoip` extension is dead yet:

PHP geoip ext for PHP 8 
https://github.com/rlerdorf/geoip

**Comment by oerdnj** [comment]
There's no support for PHP 8.0 in official [geoip](http://pecl.php.net/package/geoip) extensions and I am not very eager to pick patches from external repositories just to keep something that's already dead:

**Comment by oerdnj** [comment]
I mean why would you upgrade to PHP 8.0 and keep using old GeoIP which was announced to be deprecated years ago...
