### ISSUE TITLE
Debian 10 suggesting autoremoving memcache and memcached

### ISSUE THREAD

**Issue by superlinuxero** [oerdnj/deb.sury.org#1593]
Hi there and sorry to post this since I'm not sure it's a bug

I've several php versions installed for a couple of years in my servers and suddenly my systems are suggesting to autoremove the php-7.x-memcahe and php-7.x-memcached packages. Obviously, unless I am missing something, I don't want to uninstall those, but I'm not sure if memcache and mechached installs are integrated in other deb packages now, or they were installed as a dependency (and that's why apt suggests autoremoving them now)

Can anybody suggest the proper way to deal with this?

Thanks so much in advance

Ignacio

**Comment by oerdnj** [comment]
It's pinned at the top: https://github.com/oerdnj/deb.sury.org/issues/1555
