### ISSUE TITLE
pgsql package 7.4.18 breaking database connection

### ISSUE THREAD

**Issue by yalsicor** [oerdnj/deb.sury.org#1598]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
There seems to be slipped a bug in the 7.4.18 release for pgsql that breaks laravel database connections [[1]](https://bugs.php.net/bug.php?id=81002) [[2]](https://github.com/php/php-src/pull/6801#issuecomment-828783810). Can we have a backport to 7.4.16 until the fix hits the next release? [[3]](https://github.com/php/php-src/pull/6801#issuecomment-831087914)

**Distribution:**
 - OS: Debian Buster
 - Architecture: amd64
 - Repository: https://packages.sury.org/php buster/main amd64 Packages

**Package(s)**
php7.4:
  Installed: 7.4.18-1+0~20210501.43+debian10~1.gbp01e078
php7.4-pgsql:
  Installed: 7.4.18-1+0~20210501.43+debian10~1.gbp01e078

**Comment by eusonlito** [comment]
Same for PHP 8.0.5.

**Comment by oerdnj** [comment]
Reverted the PR

**Comment by pokgak** [comment]
PHP 7.4.19 and 8.0.6 reverted the changes that contain the bug. Should the package's version be updated to 7.4.19 and 8.0.6?

**Comment by oerdnj** [comment]
No, not really, the revert has already been made in the package, so we would be just changing a single digit in version number.

**Comment by mikebronner** [comment]
Hi @oerdnj, would you consider updating PHP to 8.0.6 now that it has been released as stable on 6 May 2021? Would help us out a lot to fix the pgsql bug. (Ubuntu is still installing 8.0.5, not sure if you downgraded that as well?)

Thanks! :)
