### ISSUE TITLE
Unable to use sury repo on turnkey vm or LXC container

### ISSUE THREAD

**Issue by ScarUY** [oerdnj/deb.sury.org#1599]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
For the last few months I've been unable to update my nextcloud LXC containers, I've read and followed 'https://packages.sury.org/php/README.txt' it kinda worked, but it didn't cause I started getting HTTP code 403 errors, (I asked about last month here https://github.com/oerdnj/deb.sury.org/issues/1023) so I just deleted /etc/apt/sources.list.d/php.list to make sure automatic updates wouldn't keep me blacklisted.

I figured a month would be enough for cloudflare to remove me from whatever blacklist they put me in, so today I went ahead and recreated /etc/apt/sources.list.d/php.list, run apt-get update and got:

> Err:3 https://packages.sury.org/php stretch/main amd64 Packages
>   Received HTTP code 403 from proxy after CONNECT
> W: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT

So at first looks seems like I'm still somehow banned, I tried with another existing debian stretch container, added the repository as per 'https://packages.sury.org/php/README.txt' and I got the exact same error, so it's not something specific from my container, and my IP changes daily so is not that either, I've tried it on another physical system and a couple existing containers at a remote location with also dynamic IP address and got the exact same result, so I'm wondering if somehow cloudflare blacklisted my entire ISP range which makes no sense so clerly something else is happening.

I've tried to create a new vm with debian stretch and after adding the repo it run apt update without errors, so there must be something either broken, outdated or missing in all my containers, but I don't have the slightest clue what that could be, so I appreciate any ideas or pointers.

**To Reproduce**
1. Install fresh Debian stretch vm (or LXC container) from turnkeylinux.org
2. Update sury repository as per 'https://packages.sury.org/php/README.txt' 
3. Run apt update

**Expected behavior**
apt update returns no errors.

**Distribution (please complete the following information):**
 - Debian Stretch
 - AMD 64
 - packages.sury.org

**Comment by JedMeister** [comment]
I can't reproduce?!

I just tested a v15.0 (Debian 9/Stretch based) TurnKey LXC container, added sury.org repo and installed php (8.0). It appears to be working as intended.

I can only guess that it's some sort of networking issue and/or network filtering on your end (that is mangling the traffic somehow) or perhaps you've been blacklisted by cloudflare?

Also unless you added sury.org to the `security.sources.list`, then no packages from sury.org will auto-update (almost certainly the way that you want it).

**Comment by oerdnj** [comment]
There seems to be some kind of proxy on your end. Also your report doesn't contain the affected IP address, so there's nothing I can do on my end.

**Comment by oerdnj** [comment]
There seems to be some kind of proxy on your end. Also your report doesn't contain the affected IP address, so there's nothing I can do on my end.

**Comment by oerdnj** [comment]
> there's absolutely no proxies

That simply not true:

> Received HTTP code 403 from proxy after CONNECT

**Comment by ScarUY** [comment]
> > there's absolutely no proxies
> 
> That simply not true:
> 
> > Received HTTP code 403 from proxy after CONNECT

Sorry I didn't came back to thank you! I got up to my nose in other work.

Your answer was the most helpful answer I've ever received in a forum, forced me to go and check my containers, and indeed there was a proxy set up there! I've no idea how that got there in the first place, I do know it wasn´t me, at least not knowingly, but removing it solved the issue.

The proxy was the LXC host, which to my knowledge shouldn't even have a proxy installed, honestly I don't have the time to try and reproduce the issue to find how that got there, but I wanted to at least post the solution for others, and to thank you for your help.

**Comment by dankopisti** [comment]
I greet you
my problem is similar, is there a solution?
  wget -O- /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
/etc/apt/trusted.gpg.d/php.gpg: Schema is missing.
--2021-07-12 21: 50: 13-- https://packages.sury.org/php/apt.gpg
Unlocking packages.sury.org (packages.sury.org)… 172.67.182.150
Connect to packages.sury.org (packages.sury.org) [172.67.182.150]: 443… connected.
HTTP request sent, waiting for response… 403 Forbidden
2021-07-12 21:50:13 ERROR 403: Forbidden.
this is a completely freshly installed debian 10.
Thank you in advance for your help
your ip: 78.131.75.228

**Comment by ScarUY** [comment]
I don't know if yours is the same problem I had, it could be that cloudflare blocked your ip address, in which case it should fix itself in about 24 hours.
In my case was the LXC host setting up an apt proxy without me knowing, removing that option solved the problem.

**Comment by dankopisti** [comment]
Thanks for your answer, unfortunately I have been trying for 2 weeks, but I can't get ahead ...
if it were an ip ban as you mentioned, it should have stopped several times and it should have been a successful operation at least once. :(
I'm clueless :(

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/use-rsync-luke-32563640

**Comment by dankopisti** [comment]
Thank you for your answer, oerdnj
Can you confirm that my ip address is not on the blacklist?
If so, could you be a partner in temporarily dissolving it?
would be very engaging.
Thanks in advance for your reply and help.
Regards,
Stephen

**Comment by oerdnj** [comment]
There are no blocklists, just automatic rules to prevent mirroring using wget/curl.

**Comment by oerdnj** [comment]
But your IP is automatically blocked by Cloudflare because of "badscore", you'll have to use **rsync** to mirror the repository.

**Comment by dankopisti** [comment]
Can you solve it for me temporarily?
i only got this static ip address a couple of weeks ago.
I don't want to abuse anything.
Thank you very much for your help.

**Comment by oerdnj** [comment]
Use `rsync`.

**Comment by dankopisti** [comment]
The imscp client application does not currently use rsync, so it would be complicated and time consuming for me to rewrite the installation program everywhere so I can start the basic installation. there is a cost to this, then of course I stand.
Please help with this.
Thanks in advance.
Stephen
