### ISSUE TITLE
[feature request] PHP Debian Personal Archive

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#16]
[This is something like a personal's bounty program. Please only respond if you want to pledge, I will delete all other comments not related to pledge.]

Debian Personal Archive intend to implement similar infrastructure for PHP	packages to Ubuntu PPAs.  I will support oldstable, stable and testing releases (e.g. squeeze, wheezy and jessie at the time of writing this) with all supported PHP versions and modules.

Since this is by no means an easy task and it will consume a lot of time, I am asking for a pledges to support. It's up to you whether you [donate](https://deb.sury.org/pages/donate.html) now or after the task is complete , but if you just pledge to support here, I expect you will live up to your word and make the donation.

The minimum amount to implement this feature is 1000 EUR.

**Comment by xbox360141** [comment]
I'm willing to donate because I have just installed Debian on a computer I bought from Newegg. Before I do, I see that this is from last September and was wondering do you still need donations?

Looking forward to your reply!

**Comment by oerdnj** [comment]
There are now i386 and amd64 repositories:
 * [PHP 5.4 for Debian wheezy](http://packages.sury.org/php5-5.4/)
 * [PHP 5.6 for Debian jessie](http://packages.sury.org/php5-5.6/)

But since I was able to negotiate regular updates of PHP versions via Debian security team, those are just for people who need updates faster than usual security process takes. (And I would appreciate to have a feedback from such people...)

I will add PHP 7 for Debian jessie when PHP 7 is in RC state.

**Comment by nilsmeyer** [comment]
PHP7 is now in RC state, are you going to do a jessie repository for that one?

**Comment by oerdnj** [comment]
Try https://packages.sury.org/php/

**Comment by nilsmeyer** [comment]
Thanks, I made a small donation (BTC & Paypal).

**Comment by oerdnj** [comment]
As https://packages.sury.org/php/ carry the version for Jessie, I think this can be closed. When true Debian Personal Archives starts to exists, I will use those.
