### ISSUE TITLE
404 Errors updating packages

### ISSUE THREAD

**Issue by jvivona** [oerdnj/deb.sury.org#1602]
Getting 404 errors on 2 different debian 10 servers trying to update both 7.3 and 7,.4

Err:1 https://packages.sury.org/php buster/main amd64 php7.4-json amd64 7.4.16-1+0~20210305.42+debian10~1.gbpbbe65e
  404  Not Found [IP: 172.67.182.150 443]

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.3/php7.3-gd_7.3.27-9+0~20210227.82+debian10~1.gbpa4a3d6_amd64.deb  404  Not Found [IP: 172.67.182.150 443]

Err:22 https://packages.sury.org/php buster/main amd64 php7.3-opcache amd64 7.3.27-9+0~20210227.82+debian10~1.gbpa4a3d6
  404  Not Found [IP: 172.67.182.150 443]

**Comment by jvivona** [comment]
whatever it was - it's resolved today.

**Comment by philippemouchel** [comment]
Any chances you have an explanation or a workaround..
I'm experiencing the same since this morning in a BitBucket pipelines, when trying to install PHP extensions (php7.4-bz2, bcmath and zip).
Everything was working just fine last Friday !!!! 🧐
