### ISSUE TITLE
php8.0-apcu installs php7.4 packages

### ISSUE THREAD

**Issue by EinfxchFinn** [oerdnj/deb.sury.org#1603]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When you run "apt install php8.0-apcu" it installs some php7.4 packages.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Architecture: amd64
 - Repository: Ubuntu PPA
![php-bug](https://user-images.githubusercontent.com/58655519/118927264-d0154600-b941-11eb-936b-e16e8ca7dad6.png)

**Comment by oerdnj** [comment]
You need to use `apt-get install --no-recommends php8.0-apcu`, there's no `apcu-bc` for PHP 8.0, but I don't have a way how to express that in the packaging.

**Comment by mklepaczewski** [comment]
> You need to use `apt-get install --no-recommends php8.0-apcu`, there's no `apcu-bc` for PHP 8.0, but I don't have a way how to express that in the packaging.

Just for struggling users - that's `--no-install-recommends`, not `--no-recommends`
