### ISSUE TITLE
libssl-dev 1.1.1j not present

### ISSUE THREAD

**Issue by LorenzoRogai** [oerdnj/deb.sury.org#1605]
Hi,

I'm encountering the following error when trying to install "libssl-dev"

```
The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1f-1ubuntu2.4) but 1.1.1j-1+ubuntu20.04.1+deb.sury.org+3 is to be installed
```

Is it normal that the libssl1.1 is upgraded to 1.1.1j by the Sury repository but the libssl-dev is still tied to F version? Shouldn't it also be present inside Sury repository together with the main binary?

```
apt list -a libssl-dev libssl1.1 openssl
```

shows this

```
libssl-dev/focal-updates 1.1.1f-1ubuntu2.4 amd64
libssl-dev/focal-security 1.1.1f-1ubuntu2.3 amd64
libssl-dev/focal 1.1.1f-1ubuntu2 amd64

libssl1.1/now 1.1.1j-1+ubuntu20.04.1+deb.sury.org+3 amd64 [installed,local]
libssl1.1/focal-updates 1.1.1f-1ubuntu2.4 amd64
libssl1.1/focal-security 1.1.1f-1ubuntu2.3 amd64
libssl1.1/focal 1.1.1f-1ubuntu2 amd64

openssl/now 1.1.1j-1+ubuntu20.04.1+deb.sury.org+3 amd64 [installed,local]
openssl/focal-updates 1.1.1f-1ubuntu2.4 amd64
openssl/focal-security 1.1.1f-1ubuntu2.3 amd64
openssl/focal 1.1.1f-1ubuntu2 amd64
```

This the current sources.list.d file

```
deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main
# deb-src http://ppa.launchpad.net/ondrej/php/ubuntu focal main
```

Thank you

**Comment by oerdnj** [comment]
There's a huge pinned issue at the top: https://github.com/oerdnj/deb.sury.org/issues/1563

I don't know what you did to your machine, but the packages should have been downgraded unless you like not installed `php-common` or other packages that pull the apt preferences.
