### ISSUE TITLE
PHP 7.4: pdo_sqlite.so: undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by LiamFry** [oerdnj/deb.sury.org#1606]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Simply executing PHP at the command line will generate the relevant error.

`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite.so' (tried: /usr/lib/php/20190902/pdo_sqlite.so (/usr/lib/php/20190902/pdo_sqlite.so: undefined symbol: sqlite3_column_table_name), /usr/lib/php/20190902/pdo_sqlite.so.so (/usr/lib/php/20190902/pdo_sqlite.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**To Reproduce**
`$ php`

**Expected behavior**
No error.

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA (sury)

**Package(s) (please complete the following information):**
`php7.4-sqlite3:                                                                  
  Installed: 7.4.18-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.4.18-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 7.4.18-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
`

**Additional context**
When I searched for this error, several sites indicated that it was due to the library being built without `-DSQLITE_ENABLE_COLUMN_METADATA=1`

**Comment by oerdnj** [comment]
What's output of `ldd /usr/lib/php/20190902/pdo_sqlite.so`?

**Comment by LiamFry** [comment]
> What's output of `ldd /usr/lib/php/20190902/pdo_sqlite.so`?

        linux-vdso.so.1 (0x00007ffe49d19000)                                         
        libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x00007f9f85dce000)       
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9f859e7000)            
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9f8565c000)            
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9f85458000)          
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9f85238000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9f862f6000)

**Comment by LiamFry** [comment]
Forget it. I'm a fool. The output of `ldd` got me wondering and I dug and dug and dug. As it turns out, ***I*** built/installed my own instance of the SQLite3 library bc. the one from the Ubuntu repository was too old for a series of extensions I've written. I failed to build my instance with `SQLITE_ENABLE_COLUMN_METADATA`

I rebuilt and reinstalled SQLite with the requisite switch and - BAM! - PDO in PHP7.4 (Sury) is working fine.

My apologies for the ticket.

**Comment by oerdnj** [comment]
I know, that's why I asked that exact question. Kudos to you for following up on you own!

**Comment by francwalter** [comment]
I had the same issue on Ubuntu 18.04 where I compiled (without that flag) sqlite3 v3.41.2 and then I found in that thread: [i have problem with pdo_sqlite](https://laracasts.com/discuss/channels/laravel/i-have-problem-with-pdo-sqlite?reply=638821) the solution, how to compile it with this DSQLITE_ENABLE_COLUMN_METADATA flag.

```
cd /usr/local/src
wget https://www.sqlite.org/2023/sqlite-autoconf-3410200.tar.gz
tar xvzf sqlite-autoconf-3410200.tar.gz
cd sqlite-autoconf-3410200/
CFLAGS="-O2 -DSQLITE_ENABLE_COLUMN_METADATA=1" ./configure
make
make install
```

and then the error was gone :)

**Comment by davisngl** [comment]
@francwalter thank you, bro. That cflag helped, no more warnings.

**Comment by popov654** [comment]
Hi, I have the very similar problem but with pdo_mysql.so.
I really need it working in command line mode, because I want to make a patch for that extension.
