### ISSUE TITLE
Upgrade Apache 2.4.48

### ISSUE THREAD

**Issue by stondino00** [oerdnj/deb.sury.org#1609]
Apache has released 2.4.48 which appears to fix some vulnerabilities.

https://downloads.apache.org/httpd/CHANGES_2.4.48

Thanks

**Comment by lifeforms** [comment]
The package is bumped so this issue can be closed.

```
dpkg -l|grep apache2
ii  apache2                                2.4.48-1+ubuntu18.04.1+deb.sury.org+1
```
