### ISSUE TITLE
Broken PPA for php5.6-says unable to locate packages

### ISSUE THREAD

**Issue by dthakur1620** [oerdnj/deb.sury.org#1610]
I am using php5.6 in my docker - FROM romeoz/docker-phpfpm:5.6
and below installation is failing all of sudden today, it was working fine when I last checked couple of days ago..please help!!

RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php

RUN apt-get update && apt-get install -y --no-install-recommends \
                libapache2-mod-php5.6 \
                php5.6 \
                php5.6-cli \
                php5.6-curl \
                php5.6-dev \
                php5.6-odbc \
                php5.6-mbstring \
                php5.6-mcrypt \
                php5.6-mysql \
                php5.6-xml \
                php5.6-xmlrpc \
                php5.6-soap

Error: E: Unable to locate package libapache2-mod-php5.6
E: Couldn't find any package by glob 'libapache2-mod-php5.6'
E: Couldn't find any package by regex 'libapache2-mod-php5.6'
E: Unable to locate package php5.6-dev
E: Couldn't find any package by glob 'php5.6-dev'
E: Couldn't find any package by regex 'php5.6-dev'
E: Unable to locate package php5.6-odbc
E: Couldn't find any package by glob 'php5.6-odbc'
E: Couldn't find any package by regex 'php5.6-odbc'
E: Unable to locate package php5.6-xmlrpc
E: Couldn't find any package by glob 'php5.6-xmlrpc'
E: Couldn't find any package by regex 'php5.6-xmlrpc'
E: Unable to locate package php5.6-soap

**Comment by sleemanj** [comment]
16.04?

https://github.com/oerdnj/deb.sury.org/issues/1567#issuecomment-855091229

**Comment by dthakur1620** [comment]
Yes its on 16.04

**Comment by amenk** [comment]
Upgrade you system / containers. If for any reasons you still need the packages, you might be able to dig up them up from past xenial builds

https://launchpad.net/~ondrej/+archive/ubuntu/php/+builds?build_text=php5.6&build_state=built

Disclaimer: Please don't try that at home.

**Comment by dthakur1620** [comment]
> Upgrade you system / containers. If for any reasons you still need the packages, you might be able to dig up them up from past xenial builds
> 
> https://launchpad.net/~ondrej/+archive/ubuntu/php/+builds?build_text=php5.6&build_state=built
> 
> Disclaimer: Please don't try that at home.

Thank you, we upgraded to 20.04, took little bit but all good now.
