### ISSUE TITLE
Php5.6-<module> are missing from ppa:ondrej/php repository (Ubuntu 16.04 Xenial)

### ISSUE THREAD

**Issue by sborpo** [oerdnj/deb.sury.org#1611]
Hello,
I have using Ubuntu 16.04 Xenial.
Tried to install the php5.6 modules by using the ppa:ondrej/php repository
and running:
`sudo apt-get install -y  php5.6-pgsql`

produces the following error:
```
E: Unable to locate package php5.6-pgsql
E: Couldn't find any package by glob 'php5.6-pgsql'
E: Couldn't find any package by regex 'php5.6-pgsql'
```

Will be glad if can help

**Comment by stpnkcrk** [comment]
@sborpo #1567
