### ISSUE TITLE
Package Missing Error PHP7.1

### ISSUE THREAD

**Issue by hansenquadros** [oerdnj/deb.sury.org#1616]
Steps executed:
1. sudo apt-get install software-properties-common
2. sudo add-apt-repository ppa:ondrej/php
3. sudo apt get-update
4. sudo apt install php7.1

Expected behavior
Able to install php7.1 successfully.

Actual output
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.1
E: Couldn't find any package by glob 'php7.1'
E: Couldn't find any package by regex 'php7.1'
```

Distribution:
 - OS: Ubuntu 16.04 LTS
 - Architecture: amd64
 - Repository: oerdnj/php

**Comment by stpnkcrk** [comment]
#1567
