### ISSUE TITLE
Build failures for several Extensions (PHP8.0, Hirsute)

### ISSUE THREAD

**Issue by swiffer** [oerdnj/deb.sury.org#1617]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The PPA for Ubuntu 21.04 is missing several PHP extensions (e.g. php8.0-apcu and php8.0-igbinary)

**To Reproduce**
1.) After upgrading to Ubuntu 21.04
2.) and changing the apt url to `deb http://ppa.launchpad.net/ondrej/php/ubuntu hirsute main`
3.) running `ubuntu-security-status --unavailable` shows:

```
root@ubuntu:~$ ubuntu-security-status --unavailable
889 packages installed, of which:
  2 packages are no longer available for download
php8.0-apcu php8.0-igbinary
```

Checking the PPA it looks like several packages could not be built correctly because of a missing build-dependency

https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=&field.status_filter=published&field.series_filter=hirsute

```
Missing build dependencies: php-apcu-all-dev 
```

**Expected behavior**
Extension packages should have been upgraded

**Distribution (please complete the following information):**
 - OS: Ubuntu 21.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
 apt-cache policy php8.0-apcu
php8.0-apcu:
  Installiert:           5.1.19+4.0.11-7+ubuntu20.10.1+deb.sury.org+1
  Installationskandidat: 5.1.19+4.0.11-7+ubuntu20.10.1+deb.sury.org+1
  Versionstabelle:
 *** 5.1.19+4.0.11-7+ubuntu20.10.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by oerdnj** [comment]
Ah, I see. Canonical has already uploaded uncoordinated 5.1.20+4.0.11 orig.tar.xz to the main archive, so it clashed with the upload. It will be fixed in a moment.

**Comment by swiffer** [comment]
Thanks! Fixed for me!
