### ISSUE TITLE
Repo in sync, impossible to install php, should not happen

### ISSUE THREAD

**Issue by Yivan** [oerdnj/deb.sury.org#1618]
Hello,

**Frequently asked questions**

- [ x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

I just hit the sync problem (talked here: https://github.com/oerdnj/deb.sury.org/issues/1318)

Get:4 https://packages.sury.org/php buster InRelease [6837 B]
Get:5 https://packages.sury.org/php buster/main amd64 Packages [316 kB]
Err:5 https://packages.sury.org/php buster/main amd64 Packages
  File has unexpected size (316022 != 315996). Mirror sync in progress? [IP: 104.21.18.148 443]
  Hashes of expected file:
   - Filesize:315996 [weak]
   - SHA256:ee31bd8fa522d28b103ae61675da8936e6abfdac85c265a33d2ff0fa8118d84f
   - SHA1:96a5eaef634fc4ae8fdf93112c81417d80840a1e [weak]
   - MD5Sum:c885d7289c9301e095d41773cc9833ca [weak]
  Release file created at: Mon, 21 Jun 2021 21:21:55 +0000
Fetched 6837 B in 0s (19.9 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/buster/main/binary-amd64/Packages.gz  File has unexpected size (316022 != 315996). Mirror sync in progress? [IP: 104.21.18.148 443]
   Hashes of expected file:
    - Filesize:315996 [weak]
    - SHA256:ee31bd8fa522d28b103ae61675da8936e6abfdac85c265a33d2ff0fa8118d84f
    - SHA1:96a5eaef634fc4ae8fdf93112c81417d80840a1e [weak]
    - MD5Sum:c885d7289c9301e095d41773cc9833ca [weak]
   Release file created at: Mon, 21 Jun 2021 21:21:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**To Reproduce**

In shell:
```
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
sh -c 'echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/php.list'
apt-get update
```

**Expected behavior**

Purpose of this issue if finding a way that it never happens if possible (I don't know the technical detail of sync/GPG).
It would be really great and confident, that during sync a working repository can handle installation.
In our case, right now it occurs now during a production update, making the site unavailable the time the sync finish (i don't know if this is long / when it will be done, the other issue mention every hour).

For now I am stuck... trying repeating apt-get update until it works : ((
I someone has help information to make it work during this meantime, I will be delighted ; ) Thanks.

**Distribution (please complete the following information):**
 - OS: Debian Buster uptodate
 - Architecture: amd64
 - Repository: packages.sury.org

Thanks for reading it.

**Comment by denistrofimov** [comment]
+1

**Comment by oerdnj** [comment]
Well, should not, but it does happen sometimes for some weird reason, and the whole CloudFlare cache must be purge even when the API reports success purging the individual files.

**Comment by Yivan** [comment]
Thanks for your fast answer!

It's sad so this mean there is nothing doable at your level to ensure always availability ? (secondary fallback repository... ?)
I solved by saving/loading our docker image. But without this docker construction of our PHP image was really stuck...

**Comment by oerdnj** [comment]
I reduced the "Expires" header on the control files from 1w to 5m. Let's see what it does to the traffic to the origin server, but in any case, it should cause the caches to recover automatically after 5 minutes now.

**Comment by oerdnj** [comment]
> It's sad so this mean there is nothing doable at your level to ensure always availability?

There's always something you can do. If your business relies on the availability, you can buy a support where there's a guaranteed availability: [DEB.SURY.ORG and Freexian join forces](https://www.patreon.com/posts/deb-sury-org-and-40238414). Or you can always use `rsync` to create your own mirror: [Use rsync, Luke!](https://www.patreon.com/posts/use-rsync-luke-32563640)

**Comment by Yivan** [comment]
So great you can provide support at enterprise level this is good to know thanks!
Yes rsync is a good solution I think (as well as we should store our own docker images instead building them on the fly).
Thanks again for your valuable help, have a nice day!

**Comment by jygastaud** [comment]
For at least 3 hours now, I have the same kind of error on Debian 11.

```
root@XXX:/# lsb_release -sc
bullseye
root@XXX:/# sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
root@XXX:/# apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://packages.sury.org/php bullseye InRelease [6841 B]
Get:5 https://packages.sury.org/php bullseye/main amd64 Packages [322 kB]
Err:5 https://packages.sury.org/php bullseye/main amd64 Packages
  File has unexpected size (321937 != 321927). Mirror sync in progress? [IP: 185.93.2.243 443]
  Hashes of expected file:
   - Filesize:321927 [weak]
   - SHA256:f4a86e1b7f89f226d449f92483789d5b2a06385bfd0ed5fd9613f0d3908c30e0
   - SHA1:85b222f67fe2beccc7df81031771784a33ea754d [weak]
   - MD5Sum:4fae2c59604be456e80e1403c31ed8a2 [weak]
  Release file created at: Thu, 24 Feb 2022 07:40:46 +0000
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (321937 != 321927). Mirror sync in progress? [IP: 185.93.2.243 443]
   Hashes of expected file:
    - Filesize:321927 [weak]
    - SHA256:f4a86e1b7f89f226d449f92483789d5b2a06385bfd0ed5fd9613f0d3908c30e0
    - SHA1:85b222f67fe2beccc7df81031771784a33ea754d [weak]
    - MD5Sum:4fae2c59604be456e80e1403c31ed8a2 [weak]
   Release file created at: Thu, 24 Feb 2022 07:40:46 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by rfay** [comment]
Yeah, the FAQ says wait an hour, so I was going to wait longer, but this has been happening for several hours. But a new issue would be appropriate.

**Comment by oerdnj** [comment]
I purged the cache few times, fixed a bug in the auto-purge
script, regenerated the meta files and synced them again, so open a new issue with more details if this persists.
