### ISSUE TITLE
php7.4-imagick requires php8.0-* packages

### ISSUE THREAD

**Issue by IStranger** [oerdnj/deb.sury.org#1620]
**Frequently asked questions**

- [+] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

`php7.4-imagick` package depends on `php-8.0-*` packages:
```
$ apt-cache showpkg php7.4-imagick


Package: php7.4-imagick
Versions: 
3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 1b0be74175e2a8655593a6b583950eed


Reverse Depends: 
Dependencies: 
3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1 - php-common (2 2:69~) php7.4-common (0 (null)) libc6 (2 2.14) libmagickcore-6.q16-6 (2 8:6.9.10.2) libmagickwand-6.q16-6 (2 8:6.9.10.2) php-imagick (3 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1~) ghostscript (0 (null)) ttf-dejavu-core (0 (null)) php-imagick (3 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1~) 
Provides: 
3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1 - php-imagick (= )
```

When you install php7.4 with this package, `apt` installs php8.0. This may break existing environments. Because php8.0 has a higher priority.

**To Reproduce**
1. Install `apt-get install -y php7.4-fpm php7.4-imagick`
2. Check installed php versions: `update-alternatives --display php` and check default php version: `php -v`
```
php - manual mode
  link best version is /usr/bin/php8.0
  link currently points to /usr/bin/php7.4
  link php is /usr/bin/php
  slave php.1.gz is /usr/share/man/man1/php.1.gz
/usr/bin/php7.4 - priority 74
  slave php.1.gz: /usr/share/man/man1/php7.4.1.gz
/usr/bin/php8.0 - priority 80
  slave php.1.gz: /usr/share/man/man1/php8.0.1.gz
```

**Expected behavior**
`php8.0-*` should not be installed, if only specific  `php7.4-*` packages are requested.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04 (docker image)
 - Architecture: x86_64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

```
$apt-cache policy php7.4-imagick

php7.4-imagick:
  Installed: 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1
  Candidate: 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
It does not:
```

ondrej# apt install php7.4-cli php7.4-imagick --no-install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core imagemagick-6-common
  libedit2 libfftw3-double3 libfontconfig1 libfreetype6
  libjbig0 libjpeg-turbo8 libjpeg8 liblqr-1-0 libltdl7
  libmagickcore-6.q16-6 libmagickwand-6.q16-6 libsodium23
  libtiff5 libwebp6 libwebpmux3 libx11-6 libx11-data
  libxau6 libxcb1 libxdmcp6 libxext6 php-common
  php7.4-common php7.4-json php7.4-opcache php7.4-readline
  psmisc ucf
Suggested packages:
  libfftw3-bin libfftw3-dev libmagickcore-6.q16-6-extra
  php-pear
Recommended packages:
  ghostscript gsfonts ttf-dejavu-core
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core imagemagick-6-common
  libedit2 libfftw3-double3 libfontconfig1 libfreetype6
  libjbig0 libjpeg-turbo8 libjpeg8 liblqr-1-0 libltdl7
  libmagickcore-6.q16-6 libmagickwand-6.q16-6 libsodium23
  libtiff5 libwebp6 libwebpmux3 libx11-6 libx11-data
  libxau6 libxcb1 libxdmcp6 libxext6 php-common php7.4-cli
  php7.4-common php7.4-imagick php7.4-json php7.4-opcache
  php7.4-readline psmisc ucf
0 upgraded, 33 newly installed, 0 to remove and 6 not upgraded.
Need to get 8765 kB of archives.
After this operation, 36.2 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Try using `--no-install-recommends` with `apt install`.

**Comment by metalocator** [comment]
We are experiencing this issue as well:

`
$ sudo apt install php7.4-imagick --no-install-recommends
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-aws-5.4-headers-5.4.0-1069 linux-aws-5.4-headers-5.4.0-1071 linux-aws-5.4-headers-5.4.0-1072 linux-aws-5.4-headers-5.4.0-1075 linux-aws-5.4-headers-5.4.0-1078 linux-aws-5.4-headers-5.4.0-1080
  linux-aws-5.4-headers-5.4.0-1081 linux-aws-5.4-headers-5.4.0-1083 linux-aws-5.4-headers-5.4.0-1084 linux-aws-5.4-headers-5.4.0-1085 linux-aws-5.4-headers-5.4.0-1086 linux-aws-5.4-headers-5.4.0-1088
  ttf-dejavu-core
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libsodium23 php-imagick php8.2-cli php8.2-common php8.2-imagick php8.2-opcache php8.2-phpdbg php8.2-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php7.4-imagick php8.2-cli php8.2-common php8.2-imagick php8.2-opcache php8.2-phpdbg php8.2-readline
The following packages will be upgraded:
  libsodium23 php-imagick
2 upgraded, 7 newly installed, 0 to remove and 63 not upgraded.
Need to get 4,716 kB of archives.
After this operation, 21.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
`

**Comment by todeveni** [comment]
> The following packages will be upgraded:
>  libsodium23 php-imagick

You already have `php-imagick` installed, which pulls 8.2 packages.
With a clean Ubuntu 18.04 image, there are no problems with this repo.
