### ISSUE TITLE
bump ext-grpc to 1.38 to fix "Unauthenticated" errors with Google Cloud Emulators (spanner, pubsub, firebase)

### ISSUE THREAD

**Issue by AymericPlanche** [oerdnj/deb.sury.org#1622]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Using a Google Cloud emulator (spanner, pubsub, firebase) with the `php7.4-grpc` packages which compile the `grpc` extension in its `1.36` version lead to an "Unauthenticated" error.

This bug was fixed in the version `1.37.1` of grpc extension (https://github.com/grpc/grpc/pull/25994)

**To Reproduce**

I've made a little test sandbox with the sury package and with the pecl one:

1. `git clone https://github.com/AymericPlanche/grpc-bug-test`
2. `docker-compose build && docker-compose run pecl` -> Happy path, no error
3. `docker-compose build && docker-compose run sury` -> Error path

The error path will lead to output the following error message:
```
string(19) "GRPC version:1.36.0"
PHP Fatal error:  Uncaught Google\Cloud\Core\Exception\ServiceException: {
    "message": "Established channel does not have a sufficient security level to transfer call credential.",
    "code": 16,
    "status": "UNAUTHENTICATED",
    "details": []
} in /app/vendor/google/cloud-core/src/GrpcRequestWrapper.php:257
```

**Expected behavior**
No PHP Fatal error.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Done since 18. July.
