### ISSUE TITLE
php-mongodb 1.10.* for PHP 8.*

### ISSUE THREAD

**Issue by stefnats** [oerdnj/deb.sury.org#1623]
Please consider adding php-mongodb 1.10.0 to PHP 8.0, since it's not available in the package and some php libraries already depend on that version. Also this is the first version to support the new MongoDB 5.0 release.

Check https://github.com/mongodb/mongo-php-driver/releases for PHP driver releases.

**Comment by thor-juhasz** [comment]
:+1: but for PHP 7.4 as well

**Comment by oerdnj** [comment]
Done
