### ISSUE TITLE
Update php-rrd from 2.0.1 to 2.0.[2|3] to support PHP8

### ISSUE THREAD

**Issue by dutchie027** [oerdnj/deb.sury.org#1625]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
It's not more of a problem more so than a compatibility update request.

**Describe the solution you'd like**
Currently php-rrd includes the 2.0.1 [PECL library](https://pecl.php.net/package/rrd) and I'd like the 2.0.3 (you can use 2.0.2 if you want as the only changes for .0.3 are Windows related, but I digress) included when you use the PPA from your build(s).

**Describe alternatives you've considered**
It's completely possible to use your ppa and install the 2.0.1 PECL RRD library and then update it, but it'd be nice if, since the PPA has PHP 8 that the PECL is the PHP 8 compatible one.

**Distribution (please complete the following information):**
 - OS: U20.04 LTS
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**
php-rrd

**Additional context**
Nothing else at this point other than a big thanks for the ppa as it is already!

**Comment by oerdnj** [comment]
Done.

FTR The package was patches to have PHP 8.0 support.
