### ISSUE TITLE
Bird 2.0.8 build ?

### ISSUE THREAD

**Issue by udf2457** [oerdnj/deb.sury.org#1629]
Hi @oerdnj 

Given the weird state of play with Bird / cz.nic (re: #1325 ) what are your current plans for maintaining BIRD builds ?

2.0.8 was released 21/3/2021 but it doesn't look like you have built it yet ?

**Comment by oerdnj** [comment]
I am not a maintainer for BIRD project and nobody has asked me to update the packages.

**Comment by udf2457** [comment]
So what is https://packages.sury.org/bird/ then ?  That's on a server you control, is it not ?

I'm very confused !

**Comment by oerdnj** [comment]
That was just staging area. I just purged it.
