### ISSUE TITLE
ssh for PHP 7.0

### ISSUE THREAD

**Issue by dlussky** [oerdnj/deb.sury.org#163]
So I almost transferred my development environment to PHP7, but I found out there are no ssh extension available yet (php5 package is inconveniently named libssh2-php, but i think it would make much more sense to name 7.0 package php7.0-ssh)
Thank you for that ppa, btw, great job)

**Comment by oerdnj** [comment]
Unfortunately PECL ssh2 0.12 is not compatible with PHP 7.0. Looks like we might be lucky with git snapshot, but use it with caution. Who know what breaks :-)

**Comment by dlussky** [comment]
Works for me! Thank you very much)
