### ISSUE TITLE
PHP 8 on Ubuntu 20.10 (Groovy)

### ISSUE THREAD

**Issue by meligo** [oerdnj/deb.sury.org#1631]
**Frequently asked questions**
I have followed everything to the letter here - https://www.tecmint.com/install-php-8-on-ubuntu/ , doesn't actually mather which link I use to install php8 I always come to "sudo add-apt-repository ppa:ondrej/php" , and do "sudo apt update" behind the command.. 
 
**Describe the bug**

# sudo apt install php8.0-fpm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php8.0-fpm
E: Couldn't find any package by glob 'php8.0-fpm'

**To Reproduce**
Install php8 on an Ubuntu 20.10 environment

**Expected behavior**
Installing Php8

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: AMD64
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
 apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://asi-fs-n.contabo.net/ubuntu groovy-security/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-security/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-security/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-security/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=amd64
     origin asi-fs-n.contabo.net
 100 http://asi-fs-n.contabo.net/ubuntu groovy-backports/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin asi-fs-n.contabo.net
 100 http://asi-fs-n.contabo.net/ubuntu groovy-backports/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=main,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-updates/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-updates/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-updates/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy-updates/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin asi-fs-n.contabo.net
 500 http://asi-fs-n.contabo.net/ubuntu groovy/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=amd64
     origin asi-fs-n.contabo.net
Pinned packages:

**Additional context**
this did work for me on Ubuntu 20.04 , but went with Ubuntu 20.10 and installed php 7.4 and now I wanted up upgrade to php 8.

**Comment by oerdnj** [comment]
https://fridge.ubuntu.com/2021/07/25/ubuntu-20-10-groovy-gorilla-end-of-life-reached-on-july-22-2021/
