### ISSUE TITLE
cannot upgrade a php-fpm if no pool defined

### ISSUE THREAD

**Issue by aqueos** [oerdnj/deb.sury.org#1632]
Hi,

**When you have no pool defined on a php version you cannot upgrade the version because the apt- upgrade fails.**

[~]: apt-get upgrade 
-i used with no filenames on the command line, reading from STDIN.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.

Do you want to continue? [Y/n] 
Setting up php7.4-fpm (7.4.22-1+0~20210730.49+debian10~1.gbpc4d40d) ...
NOTICE: Not enabling PHP 7.4 FPM by default.
NOTICE: To enable PHP 7.4 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.4-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Job for php7.4-fpm.service failed because the control process exited with error code.
See "systemctl status php7.4-fpm.service" and "journalctl -xe" for details.
invoke-rc.d: initscript php7.4-fpm, action "restart" failed.
● php7.4-fpm.service - The PHP 7.4 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.4-fpm.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/php7.4-fpm.service.d
           └─zzz-lxc-service.conf
   Active: failed (Result: exit-code) since Thu 2021-08-19 09:43:44 CEST; 6ms ago
     Docs: man:php-fpm7.4(8)
  Process: 70351 ExecStart=/usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf (code=exited, status=78)
  Process: 70352 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/7.4/fpm/pool.d/www.conf 74 (code=exited, status=0/SUCCESS)
 Main PID: 70351 (code=exited, status=78)

Aug 19 09:43:44 server01 systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
Aug 19 09:43:44 server01 php-fpm7.4[70351]: [19-Aug-2021 09:43:44] WARNING: Nothing matches the include pattern '/etc/php/7.4/fpm/pool.d/*.conf' from /etc/php/7.4/fpm/php-fpm.conf at line 145.
Aug 19 09:43:44 server01 php-fpm7.4[70351]: [19-Aug-2021 09:43:44] ERROR: No pool defined. at least one pool section must be specified in config file
Aug 19 09:43:44 server01 php-fpm7.4[70351]: [19-Aug-2021 09:43:44] ERROR: failed to post process the configuration
Aug 19 09:43:44 server01 php-fpm7.4[70351]: [19-Aug-2021 09:43:44] ERROR: FPM initialization failed
Aug 19 09:43:44 server01 systemd[1]: php7.4-fpm.service: Main process exited, code=exited, status=78/CONFIG
Aug 19 09:43:44 server01 systemd[1]: php7.4-fpm.service: Failed with result 'exit-code'.
Aug 19 09:43:44 server01 systemd[1]: Failed to start The PHP 7.4 FastCGI Process Manager.
dpkg: error processing package php7.4-fpm (--configure):
 installed php7.4-fpm package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 php7.4-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

### **To Reproduce**
remove any pool as php of this particular version is not used at this particular moment
try to upgrade after a new release comes ( apt-get upgrade)

### **Expected behavior**
Should upgrade the package even with no pool
### 
**Distribution (please complete the following information):**
    codename => "buster",
    description => "Debian GNU/Linux 10 (buster)",
    id => "Debian",
    release => {
      full => "10.10",
      major => "10",
      minor => "10"
    }

### **Package(s) (please complete the following information):**
 apt-cache policy php7.4-fpm
php7.4-fpm:
  Installed: 7.4.22-1+0~20210730.49+debian10~1.gbpc4d40d
  Candidate: 7.4.22-1+0~20210730.49+debian10~1.gbpc4d40d
  Version table:
 *** 7.4.22-1+0~20210730.49+debian10~1.gbpc4d40d 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status

best regards,
Ghislain

**Comment by oerdnj** [comment]
You made the configuration invalid. If you want to disable all the pools, you need to comment out the include in the main configuration file.

**Comment by aqueos** [comment]
thanks for the quick answer.

i commented the include  in /etc/php/7.4/fpm/php-fpm.conf
;include=/etc/php/7.4/fpm/pool.d/*.conf

and it still do not want to upgrade

Setting up php7.4-fpm (7.4.22-1+0~20210730.49+debian10~1.gbpc4d40d) ...
NOTICE: Not enabling PHP 7.4 FPM by default.
NOTICE: To enable PHP 7.4 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.4-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Job for php7.4-fpm.service failed because the control process exited with error code.
See "systemctl status php7.4-fpm.service" and "journalctl -xe" for details.
invoke-rc.d: initscript php7.4-fpm, action "restart" failed.
● php7.4-fpm.service - The PHP 7.4 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.4-fpm.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/php7.4-fpm.service.d
           └─zzz-lxc-service.conf
   Active: failed (Result: exit-code) since Thu 2021-08-19 10:35:32 CEST; 5ms ago
     Docs: man:php-fpm7.4(8)
  Process: 12510 ExecStart=/usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf (code=exited, status=78)
  Process: 12511 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/7.4/fpm/pool.d/www.conf 74 (code=exited, status=0/SUCCESS)
 Main PID: 12510 (code=exited, status=78)

Aug 19 10:35:32 server01.aqserver.com systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
Aug 19 10:35:32 server01.aqserver.com php-fpm7.4[12510]: [19-Aug-2021 10:35:32] ERROR: No pool defined. at least one pool section must be specified in config file
Aug 19 10:35:32 server01.aqserver.com php-fpm7.4[12510]: [19-Aug-2021 10:35:32] ERROR: failed to post process the configuration
Aug 19 10:35:32 server01.aqserver.com php-fpm7.4[12510]: [19-Aug-2021 10:35:32] ERROR: FPM initialization failed
Aug 19 10:35:32 server01.aqserver.com systemd[1]: php7.4-fpm.service: Main process exited, code=exited, status=78/CONFIG
Aug 19 10:35:32 server01.aqserver.com systemd[1]: php7.4-fpm.service: Failed with result 'exit-code'.
Aug 19 10:35:32 server01.aqserver.com systemd[1]: Failed to start The PHP 7.4 FastCGI Process Manager.
dpkg: error processing package php7.4-fpm (--configure):
 installed php7.4-fpm package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 php7.4-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by aqueos** [comment]
-- A start job for unit php7.4-fpm.service has begun execution.
-- 
-- The job identifier is 477.
Aug 19 10:39:42 ffbbstats.aqserver.com php-fpm7.4[17127]: [19-Aug-2021 10:39:42] ERROR: No pool defined. at least one pool section must be specified in config file
Aug 19 10:39:42 ffbbstats.aqserver.com php-fpm7.4[17127]: [19-Aug-2021 10:39:42] ERROR: failed to post process the configuration
Aug 19 10:39:42 ffbbstats.aqserver.com php-fpm7.4[17127]: [19-Aug-2021 10:39:42] ERROR: FPM initialization failed
Aug 19 10:39:42 ffbbstats.aqserver.com systemd[1]: php7.4-fpm.service: Main process exited, code=exited, status=78/CONFIG
-- Subject: Unit process exited
-- Defined-By: systemd


if the start fail, the upgrade fails also it seems.
