### ISSUE TITLE
package refuse to upgrade

### ISSUE THREAD

**Issue by aqueos** [oerdnj/deb.sury.org#1633]
Sorry to reopen the issue but i cannot ugrade at all without having a running pool.

About your previous answer:

i commented the include  in /etc/php/7.4/fpm/php-fpm.conf
;include=/etc/php/7.4/fpm/pool.d/*.conf

and it still do not want to upgrade. 
So even if i stop it, disable all pool. I cannot in any way upgrade the package and apply patch. i dont think not having a pool should block a package upgrade :)

thanks a lot for your work.

best regards,
Ghislain.

**Comment by oerdnj** [comment]
This is not a packaging issue.  It's reasonable requirement to make a valid configuration for the start stop scripts to work.  You can disable the specific FPM with systemctl disable command.
