### ISSUE TITLE
Error phpinfo >>> php5.6 

### ISSUE THREAD

**Issue by ft-12** [oerdnj/deb.sury.org#1635]
Ubuntu Server 20.04 focal Has php 5.6 installed and when you try to call the phpinfo function, the server returns a message:
```
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log."
```
Data from log files:
`"[Fri Aug 27 18:05:26.284743 2021] [cgi:error] [pid 578295] [client 192.168.223.1:56571] End of script output before headers: php5.6.cgi"`
If in the file .php replace the request with `"phpinfo"`
with
```
phpinfo(1);
phpinfo(4);
phpinfo(8);
phpinfo(16);
phpinfo(32);
phpinfo(64);
phpinfo(2);
```

Then the data is only partially output. There is no information about the connected modules.

Tell me how to fix this error. 

Sorry for bad English.

**Comment by oerdnj** [comment]
It's most probably this: https://github.com/oerdnj/deb.sury.org/issues/1442#issuecomment-668569084
