### ISSUE TITLE
nginx 1.21.3

### ISSUE THREAD

**Issue by jadeops** [oerdnj/deb.sury.org#1636]
nginx 1.21.3 was released today - http://nginx.org/en/CHANGES

Please update mainline repository if you have some free time. Thank you!

**Comment by oerdnj** [comment]
Uploaded and building.

**Comment by jadeops** [comment]
Just a friendly bump - nginx 1.21.5 was released on 28 Dec 2021 https://nginx.org/en/CHANGES

There's a low volume RSS feed if you want to track nginx updates - https://nginx.org/index.rss

```
Changes
    *) Change: now nginx is built with the PCRE2 library by default.
    *) Change: now nginx always uses sendfile(SF_NODISKIO) on FreeBSD.
    *) Feature: support for sendfile(SF_NOCACHE) on FreeBSD.
    *) Feature: the $ssl_curve variable.
    *) Bugfix: connections might hang when using HTTP/2 without SSL with the
       "sendfile" and "aio" directives.
```
