### ISSUE TITLE
Upgrade igbinary to latest 3.2.6 release

### ISSUE THREAD

**Issue by stronk7** [oerdnj/deb.sury.org#1637]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

This is a followup of #1626 where it was reported that the igbinary extension >= 3.2.2 and <= 3.2.4 have a bug that, simply, break any operation on arrays unserialize, returning "consumed" (internal pointer out of order) results.

Basically any php72 out there with igbinary installed (standalone or being used by redis/memcached) will fail when handling array structures.

In that issue,  I added a comment about a new 3.2.6 version already available some weeks ago but I imagine that, being closed, it has not got much traction.

We tracked the problem originally in out systems (Moodle) @ [MDL-72312](https://tracker.moodle.org/browse/MDL-72312), by introducing a workaround that allows to the [php-setup GHA action](https://github.com/marketplace/actions/setup-php-action) (that uses this PPA) to work and also created a followup issue to revert the workaround @ [MDL-72399](https://tracker.moodle.org/browse/MDL-72399) once the new extensions are available.

But looking to https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=igbinary&field.status_filter=published&field.series_filter= , it seems that no builds have happened since August 2nd.

So it would be great to get the [extension updated to current 3.2.6](https://pecl.php.net/package/igbinary), towards a greener (GHA-wise) world! :-)

**To Reproduce**
1. Run this snippet with php72 and current igbinary extension 3.2.4
    ```
    <?php
    $data = [1, 2, 3];
    $data = igbinary_unserialize(igbinary_serialize($data));
    echo (key($data) === 0 ? 'Good!' : 'Broken!') . "\n";
    ````
2. It prints "Broken!", array internal pointer is wrong.

**Expected behavior**
It should print "Good!", 1st key of the array returned.

**Distribution (please complete the following information):**
 - OS: Any
 - Architecture: Any
 - Repository: Any

**Package(s) (please complete the following information):**
???

**Additional context**
???

**Comment by oerdnj** [comment]
> In that issue, I added a comment about a new 3.2.6 version already available some weeks ago but I imagine that, being closed, it has not got much traction.

Yes, while I read your comment while back, when there's no separate issue to track this, I tend to forget. Thanks for filling a separate issue for this. The updated package has been uploaded and it's building everywhere (Freexian, DEB.SURY.ORG, PPAs).

**Comment by stronk7** [comment]
Thanks!
