### ISSUE TITLE
Apache 2.4.49

### ISSUE THREAD

**Issue by lifeforms** [oerdnj/deb.sury.org#1640]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The Apache project has released some security vulnerabilities in Apache 2.4.48 and lower: https://httpd.apache.org/security/vulnerabilities_24.html

It's recommended to update to Apache 2.4.49.

**To Reproduce**
1. Install apache2
2. dpkg -l | grep apache2
```
ii  apache2                                2.4.48-1.0+ubuntu18.04.1+deb.sury.org+1                            amd64        Apache HTTP Server
```

**Expected behavior**
Apache 2.4.49 being installed :)

**Distribution (please complete the following information):**
 - OS: Ubuntu 
 - Architecture: all
 - Repository: PPA

**Package(s) (please complete the following information):**
```
 ubuntutest  ~  apt-cache policy apache2
apache2:
  Installed: 2.4.48-1.0+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.4.48-1.0+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2.4.48-1.0+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.29-1ubuntu4.16 500
        500 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     2.4.29-1ubuntu4 500
        500 http://nl.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Additional context**
N/A

**Comment by codeman76** [comment]
Hello,

Yesterday I upgraded this package:

Upgrade: apache2-data:amd64 (2.4.48-1.0+ubuntu20.04.1+deb.sury.org+1, 2.4.49-1+ubuntu20.04.1+deb.sury.org+1), apache2-bin:amd64 (2.4.48-1.0+ubuntu20.04.1+deb.sury.org+1, 2.4.49-1+ubuntu20.04.1+deb.sury.org+1), apache2:amd64 (2.4.48-1.0+ubuntu20.04.1+deb.sury.org+1, 2.4.49-1+ubuntu20.04.1+deb.sury.org+1), apache2-utils:amd64 (2.4.48-1.0+ubuntu20.04.1+deb.sury.org+1, 2.4.49-1+ubuntu20.04.1+deb.sury.org+1)

Now I see a lot of segfaults that I didn't see before, they started right after installing the package:

[Tue Sep 21 12:11:59.672526 2021] [core:notice] [pid 5133] AH00052: child pid 1926479 exit signal Segmentation fault (11)
[Tue Sep 21 12:11:59.672576 2021] [core:notice] [pid 5133] AH00052: child pid 1926493 exit signal Segmentation fault (11)
[Tue Sep 21 12:12:00.688861 2021] [core:notice] [pid 5133] AH00052: child pid 1926459 exit signal Segmentation fault (11)
[Tue Sep 21 12:12:00.689136 2021] [core:notice] [pid 5133] AH00052: child pid 1926494 exit signal Segmentation fault (11)
[Tue Sep 21 12:12:00.689164 2021] [core:notice] [pid 5133] AH00052: child pid 1926495 exit signal Segmentation fault (11)
[Tue Sep 21 12:12:00.689201 2021] [core:notice] [pid 5133] AH00052: child pid 1926496 exit signal Segmentation fault (11)

Apache runs, though.

Is there anything wrong with the package or is there anything changed that I need to look for in my configuration?

Thanks!

**Comment by oerdnj** [comment]
There were no changes to the packaging scripts, so any crash should be reported to upstream.

**Comment by codeman76** [comment]
Thanks a lot, I will look further to file a crash report in upstream.

Is there any chance that I can download a copy of the deb packages of 2.4.48 somewhere again to temporary fix the problem? I see old packages are not in the repository.

**Comment by lifeforms** [comment]
I will close this issue, as I see that Apache is updated to 2.4.49 already, so the situation is resolved. If there are remaining questions, it may be better to open a separate issue.

**Comment by oerdnj** [comment]
You can look at the build logs in the launchpad and sometimes the old package is cached there.

**Comment by oerdnj** [comment]
And if there's a patch from upstream, I would be happy to apply it before the new upstream is out.
