### ISSUE TITLE
Segmentation Fault and Illegal instruction when running php -v

### ISSUE THREAD

**Issue by corrilan** [oerdnj/deb.sury.org#1642]
**Frequently asked questions**

- [ Y ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
I am on a Raspberry Pi Zero.
Have tried php7.4 and php8.1 but they result in "Segmentation Fault" and "Illegal instruction" respectively when running php -v.

**To Reproduce**
1. Install php7.4 or php8.0 from the sury.org repository.
2. Run php -v

**Expected behavior**
Working php showing version.

**Distribution (please complete the following information):**
 - OS: [Raspbian]
 - Architecture: [armhf]
 - Repository: [packages.sury.org]

**Package(s) (please complete the following information):**
php8.1:
  Installed: 8.1.0~rc1-1+0~20210913.2+debian10~1.gbp9cecaa
  Candidate: 8.1.0~rc1-1+0~20210913.2+debian10~1.gbp9cecaa
  Version table:
 *** 8.1.0~rc1-1+0~20210913.2+debian10~1.gbp9cecaa 500
        500 https://packages.sury.org/php buster/main armhf Packages
        100 /var/lib/dpkg/status

**Additional context**
php7.3 installed from Raspbian Buster repo is working fine.  But a newer version is a dependency for some software I need to install.

**Comment by oerdnj** [comment]
Raspbian armhf isn't same armhf as Debian and it is not supported.
