### ISSUE TITLE
Error using pecl to install extenstion from pecl.php.net

### ISSUE THREAD

**Issue by khayman123** [oerdnj/deb.sury.org#1644]
I've problem with pecl, installed from deb.sury.org.

Specification:
OS: debian11
PHP: 7.0-8.1
partitions:
Filesystem                        Type     1K-blocks    Used Available Use% Mounted on
udev                              devtmpfs   1979076       0   1979076   0% /dev
tmpfs                             tmpfs       399372    4836    394536   2% /run
/dev/mapper/SystemVG-SystemLV     xfs       15693824 3451700  12242124  22% /
tmpfs                             tmpfs      1996852      16   1996836   1% /dev/shm
tmpfs                             tmpfs         5120       0      5120   0% /run/lock
/dev/mapper/DockerVG-DockerLV     xfs        1017736   40360    977376   4% /var/lib/docker
/dev/sda1                         ext4        495250   48436    416606  11% /boot
tmpfs                             tmpfs       399368       0    399368   0% /run/user/1000
tmpfs                             tmpfs       399368       0    399368   0% /run/user/0

Problem:
when I run pecl, to install extension, I get error:
pecl install oci8
downloading oci8-3.0.1.tgz ...
Starting to download oci8-3.0.1.tgz (190,882 bytes)
.........................................done: 190,882 bytes
13 source files, building
running: phpize
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
shtool at '/opt/php_tmp/oci8/build/shtool' does not exist or is not executable.
Make sure that the file exists and is executable and then rerun this script.

ERROR: `phpize' failed

I've changed default path from /tmp to my /opt/php_tmp dir, error was the same. It's not wrong permissons on the filesystem, because every command works, and additional, I 've change path from /tmp to /opt/php_tmp and chmod a+x php_tmp

Whe I try manually install tarball with extension, situation is the same.
tar xvf oci8-3.0.1.tgz
cd oci8-3.0.1
phpize (which point to phpize8.1):
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
shtool at '/opt/php_tmp/oci8-3.0.1/build/shtool' does not exist or is not executable.
Make sure that the file exists and is executable and then rerun this script.
ls -l build
-rw-r--r-- 1 root root   2104 Sep 24 11:36 ax_check_compile_flag.m4
-rw-r--r-- 1 root root   8415 Sep 24 11:36 ax_gcc_func_attribute.m4
-rw-r--r-- 1 root root  44283 Sep 24 11:36 config.guess
-rw-r--r-- 1 root root  36136 Sep 24 11:36 config.sub
-rw-r--r-- 1 root root 117274 Sep 24 11:36 gen_stub.php
-rw-r--r-- 1 root root 306681 Sep 24 11:36 libtool.m4
-rw-r--r-- 1 root root 327287 Sep 24 11:36 ltmain.sh
-rw-r--r-- 1 root root   6140 Sep 24 11:36 lt~obsolete.m4
-rw-r--r-- 1 root root  14514 Sep 24 11:36 ltoptions.m4
-rw-r--r-- 1 root root   4384 Sep 24 11:36 ltsugar.m4
-rw-r--r-- 1 root root    699 Sep 24 11:36 ltversion.m4
-rw-r--r-- 1 root root   6856 Sep 24 11:36 Makefile.global
-rw-r--r-- 1 root root  17629 Sep 24 11:36 php_cxx_compile_stdcxx.m4
-rw-r--r-- 1 root root  72904 Sep 24 11:36 php.m4
-rw-r--r-- 1 root root  10247 Sep 24 11:36 pkg.m4
-rw-r--r-- 1 root root 142086 Sep 24 11:36 shtool

shtool doesnt have executable flag, and seems to pecl doesnt give it during install. 
When I manually add executable flag:
chmod a+x build/shtool
phpize8.1
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902

Seems ok.

Error shows on different versions of php, from 7.0. to 8.1. Maybe It is my error, but I dont know what may be . 

Installed:
[php-modules.txt](https://github.com/oerdnj/deb.sury.org/files/7224668/php-modules.txt)
[php-info.txt](https://github.com/oerdnj/deb.sury.org/files/7224680/php-info.txt)

**Comment by oerdnj** [comment]
```
# ls -l /usr/bin/shtool
-rwxr-xr-x 1 root root 142086 Dec 23  2019 /usr/bin/shtool
```

On your system?

**Comment by khayman123** [comment]
ls -l /usr/bin/shtool
-rwxr-xr-x 1 root root 142086 Dec 23  2019 /usr/bin/shtool

**Comment by oerdnj** [comment]
Then it's your local configuration that strips the execute flag on copy. Can't help you here.
