### ISSUE TITLE
Apache2 stops working randomly

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#1646]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
After upgrading to the most up to date version of apache2 (`apache2/focal,now 2.4.49-3+ubuntu20.04.1+deb.sury.org+2 amd64`) it simply stops to work.
There is no error within any log file (/var/log/apache2, journalctl).

I am using PHP7.4-FPM as well from your repository.

Usually the only thing that helps is to restart apache2 and php7.4-fpm systemd-services.

**To Reproduce**
1. Do daily business (mostly Nextcloud & proxy for Matrix Synapse) & wait
2. It crashes.

**Expected behavior**
Apache2 should keep running as it did before the last update.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Architecture: amd64
 - Repository: deb.sury.org

**Package(s) (please complete the following information):**
2.4.49-3+ubuntu20.04.1+deb.sury.org+2

**Additional context**
If you know any point where to start to debug this issue I would be very happy.

**Comment by oerdnj** [comment]
This issue is not directly related to the packaging and it needs to be reported to the Apache upstream using their bugtracker. Put a reference here when you do that. I can then for example pull an upstream patch.

**Comment by derritter88** [comment]
Hello @oerdnj ,

I have already found exactly my issue on httpd bugtracker -> https://bz.apache.org/bugzilla/show_bug.cgi?id=65596

**Comment by oerdnj** [comment]
Pulled the patch into the package and let's see if that helps. The packages should be ready in couple of minutes.

**Comment by derritter88** [comment]
How long will it take until it's available via your repository?

**Comment by oerdnj** [comment]
Looks like it's almost there: https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+packages

**Comment by derritter88** [comment]
ahh okay now I see - needs to be build separately during an online process.
I'll keep an eye on that and upgrade it as soon as it has been build and published.

I will closely keep an eye on that and review the issue ticket in a month.

Djakujem :-)

**Comment by oerdnj** [comment]
Please also report back to the Apache issue.

**Comment by derritter88** [comment]
You will do that

**Comment by derritter88** [comment]
by the way: I just want to say thank you @oerdnj  for mainting the PPA for PHP & apache2-httpd.
I am using it now for a couple of years now without any major issues.

**Comment by ghubz** [comment]
Updated now, fingers crossed. Thanks @oerdnj .

**Comment by ghubz** [comment]
All good after 2.4.49-3+ubuntu18.04.1+deb.sury.org+3, finally! This was driving me crazy.

**Comment by derritter88** [comment]
Closed due to #1652
