### ISSUE TITLE
Segfaults with PHP 7.4 fpm and preg_match

### ISSUE THREAD

**Issue by niclashoyer** [oerdnj/deb.sury.org#1649]
**Frequently asked questions**

- [x ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
We started to get a lot of segfaults recently using PHP 7.4 FPM. Every segfault is related to PCRE2 and it seems that something goes wrong while executing a regular expression. It is not always the same regular expression. The segfault always happens at

```
src/pcre2_match.c:6105
```

I already tried downgrading the libpcre2-8-0 package, but that did not help. Any hints on how to debug this further or resolve the issue?

**To Reproduce**

Using gdb and the `zbacktrace` function provided by the `php7.4-fpm` source package I tried to replicate the regular expressions that led to segfaults, e.g.:

```php
// /tmp/core-php-fpm7.4.2071045
$a = preg_match("/^(.+)\s+AS\s+(.+)$/i", "*", $matches);
var_dump($matches);
```
But unfortunately this works, so it is not just the call to `preg_match`.

**Expected behavior**
A call to `preg_match` should not run into a segfault.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
libpcre2-8-0:
  Installed: 10.36-2+ubuntu20.04.1+deb.sury.org+2
  Candidate: 10.36-2+ubuntu20.04.1+deb.sury.org+2
  Version table:
 *** 10.36-2+ubuntu20.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     10.34-7 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages focal/main amd64 Packages

php7.4-fpm:
  Installed: 7.4.24-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 7.4.24-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 7.4.24-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     7.4.3-4ubuntu2.6 500
        500 http://de.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages focal-updates/universe amd64 Packages
     7.4.3-4ubuntu2.5 500
        500 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages focal-security/universe amd64 Packages
     7.4.3-4ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages focal/universe amd64 Packages
```

**Comment by oerdnj** [comment]
I have updated the `pcre2` library to `v10.37`. If that doesn't help, you'll have to report the issue directly to [upstream tracker](https://bugs.php.net/how-to-report.php).
