### ISSUE TITLE
[PHP7.0] Missing php7.0-apc?

### ISSUE THREAD

**Issue by kcivey** [oerdnj/deb.sury.org#165]
I've been happily using your PHP 5.6 repository for a while, and I'm now trying PHP 7.0. Thank you for providing this service to the community.

How can I get APC compatibility (being able to use `apc_fetch` instead of `apcu_fetch`, so so on)? Installing php-apcu alone doesn't do it, but php-apc can't be installed because it's looking to install the php5 version, not php7.0.

Should there be a php7.0-apc package, or am I misunderstanding something?

**Comment by d--j** [comment]
It is called `apcu_bc` ( https://pecl.php.net/package/apcu_bc ) and it would be cool if there could be a `php7.0-apcu_bc` package for that. (Or if that extension gets bundled into `php7.0-apc`).

For now you could just use pecl to install it:
```bash
apt-get install php-pear
pecl install apcu_bc-beta
echo "extension=apc.so" > /etc/php/mods-available/apcu_bc.ini
phpenmod -v 7.0 -s ALL apcu_bc
```

**Comment by oerdnj** [comment]
APC has been discontinued since PHP 5.5 release with Opcache (e.g. mid 2013). If you have been using APC with PHP 5.6, you have been doing something very wrong. So there will be no APC for PHP 7.0, since there's not any on the upstream side. 

On 9 Dec 2015, "Keith C. Ivey" <notifications@github.com> wrote:
>I've been happily using your PHP 5.6 repository for a while, and I'm
>now trying PHP 7.0. Thank you for providing this service to the
>community.
>
>How can I get APC compatibility (being able to use `apc_fetch` instead
>of `apcu_fetch`, so so on)? Installing php-apcu alone doesn't do it,
>but php-apc can't be installed because it's looking to install the php5
>version, not php7.0.
>
>Should there be a php7.0-apc package, or am I misunderstanding
>something?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/165

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by kcivey** [comment]
My understanding is that I was not actually using APC but using APCu through a compatibility mode that supplied apc_fetch() and other functions as if it was using APC. I thought that's what the "php-apc" package was supplying. There's still lots of code out there, like Doctrine, that uses the apc_* functions for caching data. Are they all supposed to be rewritten to use apcu_fetch() and so on instead?

**Comment by oerdnj** [comment]
Looks like it: https://pecl.php.net/package-changelog.php?package=APCu according to 5.1.0 changelog entry.

**Comment by oerdnj** [comment]
`apt-get install php-apcu-bc` should install an interim compatibility layer. Wait of +2 to be built.

**Comment by kcivey** [comment]
Thanks! That seems to do the trick. Off to find your donation link, which I should've done long ago.
