### ISSUE TITLE
php8 bc in preg_match after apt-get upgrade

### ISSUE THREAD

**Issue by timglabisch** [oerdnj/deb.sury.org#1653]
**Describe the bug**
i want to crosspost this bug here beacause i am not sure if it's a php problem or an issue with ppa:ondrej/php.

https://bugs.php.net/bug.php?id=81505

**To Reproduce**
take a ubuntu server from a few days ago and run these php lines:

```
preg_match('/\/([\d]+)\/XXX_([\d]+)\//', '00/348/348182/XXX_348102/xxx', $matches); var_dump($matches);
```

you would get: 

```
array(3) {
  [0]=>
  string(19) "/348182/XXX_348102/"
  [1]=>
  string(6) "348182"
  [2]=>
  string(6) "348102"
}
```

after upgrading (apt-get upgrade) the server you would get 

```
array(0) {
}
```

the upgraded packages are: libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1

**Expected behavior**
no changes in preg_match

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd65
 - Repository: ppa:ondrej/php

you can reproduce the issue in with docker. The only difference here is the apt-get upgrade. foo.php is the example script.

```

docker run --rm -v "`pwd`/foo.php:/foo.php" -it ubuntu:latest \
   /bin/bash -c 'apt-get update && apt-get install software-properties-common -y && add-apt-repository ppa:ondrej/php && apt-get update && apt-get install -y php8.0-cli && php -v &&  php /foo.php'

# array(3) {
#   [0]=>
#   string(19) "/348182/XXX_348102/"
#   [1]=>
#   string(6) "348182"
#   [2]=>
#   string(6) "348102"
# }

echo "now with upgrade"

# array(0) {
# }

docker run --rm -v "`pwd`/foo.php:/foo.php" -it ubuntu:latest \
   /bin/bash -c 'apt-get update && apt-get install software-properties-common -y && add-apt-repository ppa:ondrej/php && apt-get update && apt-get upgrade && apt-get install -y php8.0-cli && php -v &&  php /foo.php'

```

the complete output: 

https://gist.github.com/timglabisch/75683af0250262a556cd0d694414a742

**Comment by oerdnj** [comment]
pcre2 has been updated to 10.37 few days ago, that's most probable culprit

**Comment by oerdnj** [comment]
10.38 has been released meanwhile, so I am going to upload that into repository.

**Comment by sleemanj** [comment]
Note that 10.38 also has a bad bug in it's JIT

  https://github.com/PhilipHazel/pcre2/issues/21

**Comment by oerdnj** [comment]
Thanks, pulled the PHP patch to fix that.

**Comment by fghamsary** [comment]
It seems like I've misplaced my bug report, as mentioned in on the pcre2 project:
https://github.com/PhilipHazel/pcre2/issues/21#issuecomment-934291263 
It seems like there is a problem really the same as on pcre2, so if it's the integration or the bug on the other side, I don't have an Idea.

**Comment by fghamsary** [comment]
I have the problem on php7.4 and not php8 just a note :)

**Comment by oerdnj** [comment]
It's the same issue, PHP 7.4 is also using pcre2

**Comment by fghamsary** [comment]
I confirm that the problem is resolved, thanks a lot @oerdnj :)

**Comment by timglabisch** [comment]
works now. thanks.
