### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by madpsy** [oerdnj/deb.sury.org#1656]
**Frequently asked questions**

- [x ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Segmentation fault - is not responding to any HTTP requests. Every apache thread dies before doing any useful work.

apache2[9533]: segfault at 7f1a63a4d9e8 ip 00007f1a6381a8c1 sp 00007f1a52c37da0 error 7 in libpthread-2.27.so[7f1a6380d000+1a000]

and

apache2[9640]: segfault at 7f1a642690a0 ip 00007f1a642690a0 sp 00007f1a53c39eb8 error 15

**To Reproduce**

Install Apache 2.4.50

**Expected behavior**
It works.

**Distribution (please complete the following information):**
Ubuntu 18.04 on x86_64
http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic main

**Package(s) (please complete the following information):**
apache2:
  Installed: 2.4.50-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.4.50-1+ubuntu18.04.1+deb.sury.org+1

**Additional context**

**Comment by oerdnj** [comment]
The bug report doesn't contain enough information to be able to go on. You need to install debug symbols and produce at least a backtrace.

**Comment by EPGDigital-MW** [comment]
Could be related to

https://bz.apache.org/bugzilla/show_bug.cgi?id=65627

appears a fix should be available in 2.4.52

I'm seeing a lot of segmentation faults at the moment, but apache is still working and serving
