### ISSUE TITLE
Bug in apachectl script

### ISSUE THREAD

**Issue by HawkinsDan** [oerdnj/deb.sury.org#1659]
**Describe the bug**
Multi-instance Apache installs will not start any site other than the primary after the 2.4.48 package.

There is a script located in /usr/sbin/ called apachectl.  In the 2.4.48 version, line 78 looks like this:
 
HTTPD=${APACHE_HTTPD:-usr/sbin/apache2}
 
In the 2.4.49 and later versions, this line looks like this:
 
HTTPD=${APACHE_HTTPD:-usr/sbin/apache2$SUFFIX}
 
Where $SUFFIX is the name of the other Apache instances.  This variable sets the location for the Apache binary, so appending on the suffix makes it look in a directory that doesn’t exist. 

**To Reproduce**
1.  Update Apache on a multi-instance system via your repository to any version after 2.4.48
2.  Attempt to start any apache2 - works.
3.  Attempt to start any of the other instances (e.g. apache2@suffix1 or apache2@suffix2).  Attempt fails with the following output:
Oct 06 22:11:17 SERVER systemd[1]: Starting The Apache HTTP Server...
Oct 06 22:11:17 SERVER apachectl[848]: /usr/sbin/apachectl: 174: /usr/sbin/apache2-suffix1: not found
Oct 06 22:11:17 SERVER apachectl[816]: Action 'start' failed.

**Expected behavior**
I expected the apache2@suffixX sites to start as they had in 2.4.48 and earlier.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture:  amd64
 - Repository:   ppa:ondrej/apache2

**Package(s) (please complete the following information):**

**Additional context**

**Comment by oerdnj** [comment]
Yadd (Debian co-maintainer) was so kind that he fixed the issue while doing the security update to 2.4.51, so this is fixed in the current version (2.4.51-1...)
