### ISSUE TITLE
Missing php7.0-memcached

### ISSUE THREAD

**Issue by milhouse1337** [oerdnj/deb.sury.org#166]
First thank you for your excellent work on this PPA.

Can you include the `memcached` module ? It's the only module needed in order for my application stack to fully work on PHP 7.

I know they have a php7 branch, but havn't tried to compile it manually yet.
https://github.com/php-memcached-dev/php-memcached/tree/php7

**Comment by oerdnj** [comment]
Thanks for the hint about php7 branch, I have somehow missed it. The packages have been uploaded and they are building right now. Please remember this is a git snapshot, so use with caution.
