### ISSUE TITLE
PHP7.0-curl with libcurl3

### ISSUE THREAD

**Issue by markosole** [oerdnj/deb.sury.org#1664]
Hi all, I am looking for solution to install install PHP7.0-curl with libcurl3 and I am getting error that PHP7.0-curl required libcurl4. 

Here is same problem that I am getting because of MSSQL which installs libcurl3.
https://askubuntu.com/questions/1035646/php7-0-curl-and-mssql-tools-incompatibility

Is there ANY way I can make cURL work on PHP Version 7.0.33-30+ubuntu18.04.1+deb.sury.org+1  while I have ODBC Driver 13 for SQL Server installed?

My setup is: 
Ubuntu 18.04 
PHP7.0

Thanks a lot!

**Comment by oerdnj** [comment]
libcurl4 is the correct library for Bionic.  This is problem in MSSQL that needs to be recompiled to use libcurl4.
