### ISSUE TITLE
Unmet dependencies on debian bullseye: php7.4-sqlite3-dbgsym : Depends: php7.4-sqlite3

### ISSUE THREAD

**Issue by Yannik** [oerdnj/deb.sury.org#1668]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Trying to install php7.4-sqlite3 with your debian bullseye repo results in the following error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 php7.4-sqlite3-dbgsym : Depends: php7.4-sqlite3 (= 7.4.25-1+0~20211023.53+debian11~1.gbp6a5285) but 7.4.25-1+deb11u1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Distribution (please complete the following information):**
 - OS: debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Fresh debian bullseye docker container, no other packages installed

**Comment by eilandert** [comment]
I have the same issue

**Comment by oerdnj** [comment]
Yes, this will be solved with next package update. Why do you need `-dbgsym` package installed anyway?

**Comment by eilandert** [comment]
@oerdnj I don't know, It goes wrong when I install php7.4-sqlite on debian bullseye only as far as I know. Other phpversions are ok, as well as the ubuntu php7.4-sqlite for hirsute in my CI. I don't ever install -dbgsym packages

**Comment by oerdnj** [comment]
No, you obviously don't install `php7.4-sqlite3`, but you are also installing `php7.4-sqlite3-dbgsym`. Why?

**Comment by eilandert** [comment]
Ok, thanks. I see what's going wrong now ;-)  I install php7.4-sqlite and not php7.4-sqlite3!

My bad, sorry for the confusion.

# apt-get install php7.4-sqlite
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php7.4-sqlite3-dbgsym' for regex 'php7.4-sqlite'
Note, selecting 'php7.4-sqlite3' for regex 'php7.4-sqlite'

**Comment by oerdnj** [comment]
I bumped the version to `php7.4_7.4.25-2`, but you should not be installing `-dbgsym` packages if you don't need them.
