### ISSUE TITLE
Some regex no longer working - due to libpcre2-8-0 update

### ISSUE THREAD

**Issue by TuningYourCode** [oerdnj/deb.sury.org#1669]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Some regex do no longer work after upgrade to `libpcre2-8-0` version `10.38-2+0~20211005.11+debian10~1.gbpb6790a`

**To Reproduce**
```
<?php
$matches = [];
preg_match('/(^.*phv-0*([1-9]\d{4,})(\D|$).*$)|((\D|^)([1-9]\d{7})(\D|$))/is', 'Mein Vertrag 12345678', $matches);
var_dump($matches);
```

**Expected behavior**
```
array(8) {
  [0]=>
  string(9) " 12345678"
  [1]=>
  string(0) ""
  [2]=>
  string(0) ""
  [3]=>
  string(0) ""
  [4]=>
  string(9) " 12345678"
  [5]=>
  string(1) " "
  [6]=>
  string(8) "12345678"
  [7]=>
  string(0) ""
}
```

**Additional context**
Downgrading `libpcre2-8-0` to Debian buster package version seems to work.

We also opened ticket https://github.com/PhilipHazel/pcre2/issues/33 which should solve this issue.

**Comment by sleemanj** [comment]
I see that oerdnj has built 10.39, @TuningYourCode does this fix the issue you had with your regexp?

**Comment by TuningYourCode** [comment]
seems to be working now. thanks for the information on the new build :)
