### ISSUE TITLE
Problems receiving package php7.0-imagick

### ISSUE THREAD

**Issue by FabianKoestring** [oerdnj/deb.sury.org#167]
Hey there!

On the one server i tested installation of php7 with php7-imagick. Everything works as expected. Then i wanted to update our production server to php7. I added the ppa and did the following...

```console
apt-cache search php7.0-*
```

Output:
```
php7.0-common - Common files for packages built from the PHP source
libapache2-mod-php7.0 - server-side, HTML-embedded scripting language (Apache 2 module)
php7.0-cgi - server-side, HTML-embedded scripting language (CGI binary)
php7.0-cli - command-line interpreter for the PHP scripting language
php7.0-phpdbg - server-side, HTML-embedded scripting language (PHPDBG binary)
php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
libphp7.0-embed - HTML-embedded scripting language (Embedded SAPI library)
php7.0-dev - Files for PHP7.0 module development
php7.0-dbg - Debug symbols for PHP7.0
php7.0-curl - CURL module for PHP
php7.0-gd - GD module for PHP
php7.0-imap - IMAP module for PHP
php7.0-intl - Internationalisation module for PHP
php7.0-ldap - LDAP module for PHP
php7.0-mcrypt - libmcrypt module for PHP
php7.0-readline - readline module for PHP
php7.0-odbc - ODBC module for PHP
php7.0-pgsql - PostgreSQL module for PHP
php7.0-pspell - pspell module for PHP
php7.0-recode - recode module for PHP
php7.0-snmp - SNMP module for PHP
php7.0-tidy - tidy module for PHP
php7.0 - server-side, HTML-embedded scripting language (metapackage)
php7.0-json - JSON module for PHP
php-all-dev - package depending on all supported PHP development packages
php7.0-sybase - Sybase module for PHP
php7.0-modules-source - PHP 7.0 modules source package
php7.0-sqlite3 - SQLite3 module for PHP
php7.0-mysql - MySQL module for PHP
php7.0-opcache - Zend OpCache module for PHP
```

php7.0-imagick is missing. I tried to delete the cache with `apt-get clean` and `apt-get autoclean`. Did a reboot and a ton of `apt-get update` but the `php7-imagick` package is still missing. As i said before. I did the same steps on our test server and everything works as expected.

What can i do?

**Comment by oerdnj** [comment]
`apt-get install php-imagick`? 

O. 

On 9 Dec 2015, "Fabian Köstring" <notifications@github.com> wrote:
>Hey there!
>
>On the one server i tested installation of php7 with php7-imagick.
>Everything works as expected. Then i wanted to update our production
>server to php7. I added the ppa and did the following...
>
>```console
>apt-cache search php7.0-*
>```
>
>Output:
>```
>php7.0-common - Common files for packages built from the PHP source
>libapache2-mod-php7.0 - server-side, HTML-embedded scripting language
>(Apache 2 module)
>php7.0-cgi - server-side, HTML-embedded scripting language (CGI binary)
>php7.0-cli - command-line interpreter for the PHP scripting language
>php7.0-phpdbg - server-side, HTML-embedded scripting language (PHPDBG
>binary)
>php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI
>binary)
>libphp7.0-embed - HTML-embedded scripting language (Embedded SAPI
>library)
>php7.0-dev - Files for PHP7.0 module development
>php7.0-dbg - Debug symbols for PHP7.0
>php7.0-curl - CURL module for PHP
>php7.0-gd - GD module for PHP
>php7.0-imap - IMAP module for PHP
>php7.0-intl - Internationalisation module for PHP
>php7.0-ldap - LDAP module for PHP
>php7.0-mcrypt - libmcrypt module for PHP
>php7.0-readline - readline module for PHP
>php7.0-odbc - ODBC module for PHP
>php7.0-pgsql - PostgreSQL module for PHP
>php7.0-pspell - pspell module for PHP
>php7.0-recode - recode module for PHP
>php7.0-snmp - SNMP module for PHP
>php7.0-tidy - tidy module for PHP
>php7.0 - server-side, HTML-embedded scripting language (metapackage)
>php7.0-json - JSON module for PHP
>php-all-dev - package depending on all supported PHP development
>packages
>php7.0-sybase - Sybase module for PHP
>php7.0-modules-source - PHP 7.0 modules source package
>php7.0-sqlite3 - SQLite3 module for PHP
>php7.0-mysql - MySQL module for PHP
>php7.0-opcache - Zend OpCache module for PHP
>```
>
>php7.0-imagick is missing. I tried to delete the cache with `apt-get
>clean` and `apt-get autoclean`. Did a reboot and a ton of `apt-get
>update` but the `php7-imagick` package is still missing. As i said
>before. I did the same steps on our test server and everything works as
>expected.
>
>What can i do?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/167

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
