### ISSUE TITLE
php-mongodb extension - snappy & zstd support

### ISSUE THREAD

**Issue by xpender** [oerdnj/deb.sury.org#1670]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

Currently the php mongodb extension only contains zlib compression support built-in (at least for PHP 7.3 and PHP 8.0, but guess it affects all)

It would be nice to have at least snappy support included, as it's server default and recommended as best practice https://www.mongodb.com/blog/post/performance-best-practices-hardware-and-os-configuration ("Network Compression")

If possible, adding also zstd support would give the best freedom of choice for users.

php -i output
```
mongodb

MongoDB support => enabled
MongoDB extension version => 1.10.0
MongoDB extension stability => stable
libbson bundled version => 1.18.0
libmongoc bundled version => 1.18.0
[...]
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
[...]
```

**Describe the solution you'd like**

It should be enough to extend the packages debian/control file with

for snappy:

```
Build-Depend: libsnappy-dev
Depends: libsnappy1v5
```

for zstd:

```
Build-Depend: libzstd-dev
Depends: libzstd1
```

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.0-mongodb:
  Installed: 1.10.0+1.7.5-1+0~20210802.26+debian10~1.gbp5e9dc6
  Candidate: 1.10.0+1.7.5-1+0~20210802.26+debian10~1.gbp5e9dc6
  Version table:
 *** 1.10.0+1.7.5-1+0~20210802.26+debian10~1.gbp5e9dc6 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
```
19:41:31 checking for PHP_MONGODB_SNAPPY... yes
19:41:31 checking for PHP_MONGODB_ZLIB... yes
19:41:31 checking for PHP_MONGODB_ZSTD... yes
```
