### ISSUE TITLE
Adding Ondřej PPA repository fails on Linux Mint

### ISSUE THREAD

**Issue by Roebie** [oerdnj/deb.sury.org#1671]
Dear,
When trying to add the ppa repository it fails with error message **gpg: keyserver receive failed: Server indicated a failure**
How can I solve this?

Screenshot of terminal window added:
![Screenshot_2021-11-01_20-06-48](https://user-images.githubusercontent.com/2420046/139727136-f2ec74d7-1650-49ad-8d9b-687cb450e8c5.png)

Thanks!

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#supported-distributions
