### ISSUE TITLE
php8.1-xdebug please (Debian amd64 and arm64)

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1672]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Although xdebug has been upgraded to 3.1.1 it's not yet packaged for php8.1. Thanks for making php8.1-xdebug available.

I note that current xdebug 3.1.1 works fine with php8.1

**Comment by oerdnj** [comment]
Should be done.

**Comment by rfay** [comment]
Thanks - not seeing it yet (testing Debian Bullseye arm64 here)

```
$ sudo apt-get install php8.1-xdebug
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php8.1-xdebug
E: Couldn't find any package by glob 'php8.1-xdebug'
E: Couldn't find any package by regex 'php8.1-xdebug'
```

**Comment by oerdnj** [comment]
Damn, I forgot to push the git tree and it failed to build on Debian. It's building now.

**Comment by rfay** [comment]
There now, thanks so much!
