### ISSUE TITLE
php8.1-mbstring causes startup warning on Ubuntu 18.04

### ISSUE THREAD

**Issue by spideyfusion** [oerdnj/deb.sury.org#1674]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

After adding the `php8.1-mbstring` to an existing PHP installation, the following warning can be seen when running PHP from CLI:

```sh
user@ubuntu:~$ php -m
PHP Warning:  PHP Startup: ^(text/|application/xhtml\+xml) (offset=0): unrecognised compile-time option bit(s) in Unknown on line 0
```

The extension loads fine though because I can utilize the `mb_` functions as expected.

**Expected behavior**

The warning above is not present on PHP startup.

**Distribution (please complete the following information):**
 
- OS: Ubuntu 18.04
- Architecture: amd64
- Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

```sh
php8.1-mbstring:
  Installed: 8.1.0~rc5-1+ubuntu18.04.1+deb.sury.org+2
  Candidate: 8.1.0~rc5-1+ubuntu18.04.1+deb.sury.org+2
  Version table:
 *** 8.1.0~rc5-1+ubuntu18.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**

I can't reproduce this on Ubuntu 21.10.

**Comment by oerdnj** [comment]
That is not a packaging issue and needs to be reported directly to PHP. Feel free to add the link to the PHP bug here afterwards.

**Comment by spideyfusion** [comment]
Just an update that the issue occurred due to outdated `pcre2` libraries on the system. Once I installed the latest available versions, the problem disappeared:

```sh
sudo apt-get install --only-upgrade libpcre2-16-0 libpcre2-32-0 libpcre2-8-0 libpcre2-dev libpcre2-posix2
```
