### ISSUE TITLE
PHP 8 shell: can't input non-Ascii chars

### ISSUE THREAD

**Issue by drmnk** [oerdnj/deb.sury.org#1675]
After upgrading from PHP 7.4 to PHP 8 from ondrej/php repository I can't input any non-ASCII characters in PHP interactive shell ("php -a"). 
I tried Russian, Serbian, Chinese and some unicode symbols. Can't input from keyboard or paste from clipboard.

In simple words: if I try to input in shell "Привет" - russian letters just not get in shell. If I try to paste "Ondřej Surý" - in shell I only get "Ondej Sur".

In PHP 7.4 there is no such problem, everything works fine.

I have this behavior in Ubuntu 21.10, 20.04 (bare metal) and 20.04 (WSL2). I use Windows Terminal, Ubuntu Terminal, Putty - choice of terminal is no matter. In Mac OS - everything is fine.

I check charset in php CLI ini - default_charset = "UTF-8"

This issue is important for me, because I use php function calls with non-ASCII symbols in it from CLI.

P.S. I'm sorry if this issue not related with your (definitely great) repository. I try to find answers in PHP mailing lists - but unsuccesfully.

**Comment by sleemanj** [comment]
https://bugs.php.net/bug.php?id=81598

**Comment by drmnk** [comment]
Thank you very much @sleemanj
