### ISSUE TITLE
php-memcached amd64 is missing the so library

### ISSUE THREAD

**Issue by 0bff0324** [oerdnj/deb.sury.org#1678]
-rw-r--r--         7940  2021-11-10 12:57  php7.4-memcached_3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf_amd64.deb

**Comment by heratech** [comment]
I am seeing this also - bunch of CI builds starting breaking this afternoon.

**Comment by TasPats** [comment]
so with some other packages
in
/usr/share/doc/php7.3-memcached/changelog.Debian.gz

php-memcached (3.1.5+2.2.0-10+0~20211110.32+debian10~1.gbp3d83cf) unstable; urgency=medium

  ** SNAPSHOT build @3d83cf31acc603f2910220262e34f08e6f2a77f9 **

  * UNRELEASED

 -- Ondřej Surý <ondrej@sury.org>  Wed, 10 Nov 2021 12:55:21 +0100

**Comment by hoppithek** [comment]
compared to yesterday
```
diff <(dpkg-deb -c php7.4-memcached_3.1.5+2.2.0-9+0~20211109.31+debian10~1.gbp2db493_amd64.deb | grep -oE '\..*') <(dpkg-deb -c php7.4-memcached_3.1.5+2.2.0-10+0_20211110.32+debian10_1.gbp3d83cf_amd64.deb | grep -oE '\..*')
8,11d7
< ./usr/lib/
< ./usr/lib/php/
< ./usr/lib/php/20190902/
< ./usr/lib/php/20190902/memcached.so
```

**Comment by sleemanj** [comment]
#1676

**Comment by oerdnj** [comment]
dup of #1676
