### ISSUE TITLE
php5-6 & libapache2-mod-fastcgi

### ISSUE THREAD

**Issue by Poil** [oerdnj/deb.sury.org#168]
Hi,

When I use your PPA "PHP 5.6", apache is upgrading to 2.4.16, but this PPA doesn't have libapache2-mod-fastcgi, and it seems that this module is not working anymore.
You also have a PPA "Apache 2", with apache 2.4.17 and libapache2-mod-fastcgi, is it compatible with your PPA of PHP 5.6  ? Is it possible to include libapache2-mod-fastcgi on your PPA "PHP 5.6" ?

Thanks for your great works.

Best regards,

**Comment by oerdnj** [comment]
Yes, those are compatible, but I strongly advice you to just switch to mod_proxy_fcgid[1] instead of using old unmaintained mod_fastcgi. 

1. https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html
