### ISSUE TITLE
PHP 8.1-rc5 fail with any preg_*() function

### ISSUE THREAD

**Issue by joanhey** [oerdnj/deb.sury.org#1680]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

All preg_*() functions fail with:
`Compilation failed: unrecognised compile-time option bit(s) at offset 0 in file ...`

Almost with `preg_match(), preg_match_all(), preg_split()` and `preg_replace()`.

It's failing with all the php frameworks in https://github.com/TechEmpower/FrameworkBenchmarks

**To Reproduce**

Use this docker file:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/fe90508e82feb91a0bb72e94e75865609517b2b1/frameworks/PHP/php/php.dockerfile

And try to use any preg_*() function.

With php 8.0 is working without problems.

**Distribution (please complete the following information):**
 - OS: Docker with Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Seems like dup of #1674 to me.

**Comment by joanhey** [comment]
Don't look like a php bug.

It's working in https://3v4l.org/rJvkX#v8.1rc3 and with any docker image `php:8.1-rc`.

Only fail when using these packages.

Extra info:  when `php8.1-dev` is installed the `preg_*()` has no errors.

**Comment by oerdnj** [comment]
Have you actually read the other issue? Especially the part about pcre2 libraries?

**Comment by joanhey** [comment]
Yes, but it's only necessary to add `php8.1-dev` and it will work without problems. Without update the pcre2 libs.

But why with `php8.1-dev ` is working and not with only `php-8.1` or `php8.1-common`

**Comment by oerdnj** [comment]
What are the pcre2 library versions on system where it works and what are the versions where it doesn't?

**Comment by oerdnj** [comment]
E.g. is you system fully upgraded when you are testing the issue?

**Comment by sleemanj** [comment]
The dockerfile does not do an upgrade, only an update, that will be your problem @joanhey the focal tarvall that the docker image is constructed from (as I understand it) was generated way back on the 6/7th of October.

I don't use docker, but I just spun up a fresh 20.04 EC2 instance,  an initial update & upgrade brings in 

    The following packages will be upgraded:
       libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1

And 8.1 CLI works...

   $ php8.1 -r "echo preg_replace('/fubar/', 'hello world', '    fubar   ');"
        hello world

**Comment by joanhey** [comment]
Using inside a docker with `ubuntu:20.04`:

Update the docker file to use php8.1:
https://github.com/joanhey/FrameworkBenchmarks/commit/8819d833b19f63b8c8c511de50946e5f13acb102

And appear these errors:
https://github.com/joanhey/FrameworkBenchmarks/runs/4176964544?check_suite_focus=true#step:9:799

Add `php8.1-dev`, without update pcre libs: 
https://github.com/joanhey/FrameworkBenchmarks/commit/a453b6d2a291f0af1f069d640565c584e1d9337b

and it don't have errors:
https://github.com/joanhey/FrameworkBenchmarks/runs/4177163628?check_suite_focus=true#step:9:800

That happens with all frameworks.
Using docker `php:8.1-rc` is working OK, but NOT when using the `ppa:ondrej/php` with `ubuntu:20.04` without the `php8.1-dev`.

**Comment by sleemanj** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/fe90508e82feb91a0bb72e94e75865609517b2b1/frameworks/PHP/php/php.dockerfile#L5

As above, you are missing an upgrade here.

**Comment by joanhey** [comment]
Yes, but `php8.1-dev` update the pcre libs (I think).

But not when using only `php8.1` or `php8.1-common` (Why ?).

**Comment by oerdnj** [comment]
Did you come for help or to argue? I can't tell anymore...

**Comment by joanhey** [comment]
I try to help.

I understand that the correct way will be to upgrade the docker.

But if `php8.1` update the pcre libs, like do `php8.1-dev`. Nobody will ask for this question again.

Thank you for your hard work and sorry for use your time.
