### ISSUE TITLE
The value of error_reporting() gets overridden

### ISSUE THREAD

**Issue by Honzaik** [oerdnj/deb.sury.org#1685]
The value of error_reporting() function (and global error reporting setting) gets overridden when a native PHP function such as random_int() or filemtime() gets called with a suppress "@" operator and assigned to a class variable.

I am running PHP Version 8.0.13 with the latest Apache2. I was able to reproduce this also when ran as FPM. I was not able to reproduce this when called as CLI. I am using a precompiled binaries from https://launchpad.net/~ondrej/+archive/ubuntu/php/. I was not able to reproduce this on PHP7.4 when install via Ubuntu repos. This might be only relevant to the build from that repository (which is used by many people AFAIK).

Sample code:
```php
<?php

error_reporting(E_ALL);

class Foo
{
    public $a;

    public function bar() {
        $this->a = (true) ? @random_int(0, 100) : false;
    }
}

var_dump(error_reporting()); //int(32767) = E_ALL
$c = new Foo();

$c->bar();

var_dump(error_reporting()); //random int
```
Expected result:
```
int(32767)
int(32767) 
```
Actual result:
```
int(32767)
int(5) //random int
```

**Comment by oerdnj** [comment]
This is not a packaging issue. You need to report this upstream.

**Comment by Honzaik** [comment]
Ok thanks. Already submitted https://bugs.php.net/bug.php?id=81652
