### ISSUE TITLE
libcurl4-openssl-dev & libpcre2-8-0 conflict

### ISSUE THREAD

**Issue by doubaokun** [oerdnj/deb.sury.org#1686]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Hello,

We have run into some dependency conflict issues since about 2 days ago on PHP8.1-dev only at the CI system. This may related to a recent libpcre2-8-0 upgrade.

Any suggestions?

```
libpcre2-8-0:
  Installed: 10.39-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 10.39-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 10.39-2+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     10.34-7 500
        500 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 Packages
libpcre2-dev:
  Installed: 10.34-7
  Candidate: 10.34-7
  Version table:
 *** 10.34-7 500
        500 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
sudo apt-get install -y libcurl4-openssl-dev
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpcre2-dev : Depends: libpcre2-8-0 (= 10.34-7) but 10.39-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**To Reproduce**

**Expected behavior**

**Distribution (please complete the following information):**

Linux fv-az72-145 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Package(s) (please complete the following information):**

**Additional context**

**Comment by oerdnj** [comment]
There's no issue here. The local problem is right before your eyes in the lines you pasted. Keep looking and if you don't find it come back tomorrow and I'll help you.

**Comment by doubaokun** [comment]
Even we upgraded the libpcre2-dev, we still get the same conflict errors.

**Comment by oerdnj** [comment]
There's no issue with the repository. I can't help you administer your own system. Especially not if you withhold important information.

**Comment by doubaokun** [comment]
You are right, it was our local env issue. Thanks anyway.
