### ISSUE TITLE
Package request: pecl-openswoole

### ISSUE THREAD

**Issue by doubaokun** [oerdnj/deb.sury.org#1687]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

Could you please include `pecl-openswoole` in your repo?

- https://pecl.php.net/package/openswoole
- https://github.com/openswoole/swoole-src

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Distribution (please complete the following information):**

**Package(s) (please complete the following information):**

**Additional context**

**Comment by oerdnj** [comment]
Please leave me out of this. I don't want to get involved in a hostile fork.
