### ISSUE TITLE
Release updated `php*-pcov` packages

### ISSUE THREAD

**Issue by pgrenaud** [oerdnj/deb.sury.org#1688]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Additional context**

Greetings,

Last week, [a new version of the pcov extension containing bug fixes was released](https://github.com/krakjoe/pcov/issues/78). I was wondering if the packages `php*-pcov` could be updated?

I tried and was unable to find any information regarding a release schedule or if the release process was automated of not, hence this issue. Meaning that I do not know if I'm supposed to make this issue or if oerdnj is already aware and working on it. More guidance on this could help in the future.

Regards,

**Comment by oerdnj** [comment]
Updated to 1.0.11.

**Comment by pgrenaud** [comment]
Thanks a lot!
