### ISSUE TITLE
Ubuntus diverging /var/log ownership prevents using fpm logrotate directly

### ISSUE THREAD

**Issue by mmayer-pt** [oerdnj/deb.sury.org#1689]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
(used 7.3 for the example, but still applies for 7.4+)

It might be used seldomly (when disk is low), but explicitly calling logrotate can help at times.

But as Ubuntu is using root:syslog ownership on `/var/log`, if you explicitly call `logrotate -f` on the php-fpm logrotate config, it will complain
```
error: skipping "/var/log/php7.3-fpm.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```
what is quickly solved by including `su root syslog` in the fpm logrotate config directly.

Rotation in Ubuntu still works via /etc/logrotate.conf, as the distribution has the su config there and includes the logrotate files.

Ubuntus diverging ownership of /var/log from Debian is discussed in https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1278193 but can't see the original reason to do so.

Is the expectation for explicitly calling the logrotate config to work? Then the Ubuntu config has to be altered to have a `su root syslog`.

**To Reproduce**
```
logrotate -f /etc/logrotate.d/php7.3-fpm
```

**Expected behavior**
Logs will rotate.

**Workaround**
rotate everything to rotate php-fpm logs too
```
logrotate -f /etc/logrotate.conf
```

**Proposed fix**
```
/var/log/php7.3-fpm.log {
        rotate 12
        weekly
        missingok
        notifempty
        compress
        delaycompress
+       su root syslog
        postrotate
                /usr/lib/php/php7.3-fpm-reopenlogs
        endscript
}
```

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
  Installed: 7.3.22-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 7.3.33-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
     7.3.33-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
 *** 7.3.22-1+ubuntu18.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
No, this is not something that should be solved at individual package level.

That said, you can put the change on your machines and since logrotate configuration is a config files the change won't be reverted on upgrade.

**Comment by mmayer-pt** [comment]
Ubuntu makes it harder for every package to rotate individually when inside /var/log because of syslog, will look into this - I think it was still possible when php was in its own log directory, before https://github.com/oerdnj/deb.sury.org/issues/221 - thanks for getting back to me
