### ISSUE TITLE
php8.1-gearman uses undefined symbol ZVAL_NEW_ARR

### ISSUE THREAD

**Issue by KirbyDE** [oerdnj/deb.sury.org#1691]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Pacakge php8.1-gearman uses undefined symbol ZVAL_NEW_ARR which does prevent the extension from being loaded.

This was fixed in https://github.com/php/pecl-networking-gearman/commit/7da13e4babc17067b2b45d6b37041c3c8ed91637 but the fix is not included in the package

**To Reproduce**
Install package php8.1-gearman and try to start PHP-FPM 

**Expected behavior**
PHP-FPM does start

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.1-gearman:
  Installiert:           2.1.0+1.1.2-6+0~20211113.29+debian9~1.gbp29c7f0
  Installationskandidat: 2.1.0+1.1.2-6+0~20211113.29+debian9~1.gbp29c7f0
  Versionstabelle:
 *** 2.1.0+1.1.2-6+0~20211113.29+debian9~1.gbp29c7f0 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by stof** [comment]
The commit you linked is not part of any release of the gearman pecl extension. It is only in the master branch. So this is expected. You should ask for a release of the extension first.

**Comment by oerdnj** [comment]
Uploaded package with the patch. It's building now, so closing the issue
