### ISSUE TITLE
php-fpm services fails on system boot

### ISSUE THREAD

**Issue by eachtime** [oerdnj/deb.sury.org#1692]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Systemctl fails to start php-fpm services on startup.

`php-fpm8.1[672]: [11-Dec-2021 13:28:56] ERROR: unable to bind listening socket for address '/run/php/scocket_name.sock': No such file or directory (2)`

I always have to create the /run/php directory and restart php-fpm services manually for them to run properly.

**To Reproduce**

I dont know when this problem started to occur because I don't reboot my servers too often,
I think that it is when I tried to uninstall unused versions of php-fpm via apt which were reinstalled during the next system upgrade anyway.

> I thought I installed each version manually, but they are installed automatically with the repo

**Expected behavior**
Systemctl to start properly php-fpm services on system startup.

**Distribution**
debian version 10.11

**Additional context**
```BASH
# >> cat /etc/apt/sources.list.d/php.list 
deb https://packages.sury.org/php/ buster main
```

**Comment by oerdnj** [comment]
How does `cat /usr/lib/tmpfiles.d/php8.1-fpm.conf` look like?

**Comment by eachtime** [comment]
```BASH
# >> cat /usr/lib/tmpfiles.d/php8.1-fpm.conf
#Type Path                  Mode UID      GID      Age Argument
    d /run/php              0755 www-data www-data -   -
```

**Comment by oerdnj** [comment]
Then I guess you need to discover why systemd-tmpfiles doesn't work properly on your system. There's little I can do from here.

**Comment by eachtime** [comment]
It was indeed a systemd-tmpfiles issue. I understood it all thanks to you. I caused the issue myself. Thank you very much.

**Comment by oerdnj** [comment]
> It was indeed a systemd-tmpfiles issue. I understood it all thanks to you. I caused the issue myself. Thank you very much.

Wow, this is rare. Thank you, I appreciate this.

**Comment by 9967819** [comment]
This issue is not fully resolved for me. Using php 8.2 on rocky linux 9... Interestingly i have added /run/php in the tmpfiles.d config but still need to create the directory (/run/php) manually to start the php-fpm process. 

/usr/lib/tmpfiles.d/php-fpm : 
> d /run/php 755 root root

/etc/systemd/system/php-fpm.service :

> [Service]
> Type=notify
> PIDFile=**/run/php/php8.2-fpm.pid**
> ExecStart=/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/php-fpm.conf
> ExecReload=/bin/kill -USR2 $MAINPID

Here is the error message showing with "**systemctl status php-fpm**" : 

> $ sudo systemctl status php-fpm
> × php-fpm.service - The PHP FastCGI Process Manager
>      Loaded: loaded (/etc/systemd/system/php-fpm.service; enabled; preset: disabled)
>      Active: failed (Result: exit-code) since Thu 2023-08-10 06:15:43 EDT; 19s ago
>     Process: 398994 ExecStart=/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/php-fpm.conf (code=exited, status=78)
>    Main PID: 398994 (code=exited, status=78)
>         CPU: 119ms
> 
> Aug 10 06:15:43 pamela systemd[1]: Starting The PHP FastCGI Process Manager...
> Aug 10 06:15:43 pamela php-fpm[398994]: [10-Aug-2023 06:15:43] ERROR: Unable to create the PID file (/run/php/php8.2-fpm.pid).: No such file or directory (2)
> Aug 10 06:15:43 pamela php-fpm[398994]: [10-Aug-2023 06:15:43] ERROR: FPM initialization failed
> Aug 10 06:15:43 pamela systemd[1]: php-fpm.service: Main process exited, code=exited, status=78/CONFIG
> Aug 10 06:15:43 pamela systemd[1]: php-fpm.service: Failed with result 'exit-code'.
> Aug 10 06:15:43 pamela systemd[1]: Failed to start The PHP FastCGI Process Manager.

**Comment by oerdnj** [comment]
> on rocky linux 9

How is this related to this repository?
