### ISSUE TITLE
deb sury org apache 2 2.4.52-1 package on ubuntu 18.04 issues

### ISSUE THREAD

**Issue by fuco809** [oerdnj/deb.sury.org#1695]
after updating the apache2 packages from 2.4.51 version we had some outages in serving pages from apache... mainly for about 15minutes without any hint in system and apache logs.

mainly looks like the descibed one here at cpanel: 
https://forums.cpanel.net/threads/apache-2-4-52-issues.696537/#post-2892469

has anyone else experienced problems with that build of apache2?
ubuntu 18.04
deb sury org apache2 2.4.52-1
mpm_event in use
php several versions with fcgid

**Comment by oerdnj** [comment]
This doesn't sound like a packaging issue, but upstream issue. You need to report this to the upstream issue tracker.

**Comment by fuco809** [comment]
Thanks, now confirmed...

Apache Foundation is tracking this bug here:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65769
Additional report here:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65771

**Comment by oerdnj** [comment]
Try using 2.4.52-2+ubuntu18.04.1+deb.sury.org+1 (well, when and if it builds...): https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+packages
