### ISSUE TITLE
Do not get php8.0-fpm version 8.0.14 under arm

### ISSUE THREAD

**Issue by Tuffiglig** [oerdnj/deb.sury.org#1697]
Hey.
I use the php repo on two machines.
The first one is a x86_64 machine (Hetzner cloud server),
and the second one a aarch64 machine (ODROID HC4).

On the first one i got the update to PHP 8.0.14 a view days ago.
The second one is still on PHP 8.0.13.

Both machines are running Ubuntu 20.04.3 LTS.

repo on first one:
`deb [arch=amd64] http://ppa.launchpad.net/ondrej/php/ubuntu focal main`

second one:
`deb [arch=arm64] http://ppa.launchpad.net/ondrej/php/ubuntu focal main`

<details>
<summary>Installed software on first: # apt list --installed | grep php</summary>
php-common/focal,now 2:90+ubuntu20.04.1+deb.sury.org+1 all  [Installiert,automatisch]

php8.0-apcu/focal,now 5.1.21+4.0.11-2+ubuntu20.04.1+deb.sury.org+3 amd64  [installiert]
php8.0-bcmath/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-bz2/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-cli/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-common/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-curl/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-fpm/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-gd/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-gmp/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-igbinary/focal,now 3.2.6+2.0.8-2+ubuntu20.04.1+deb.sury.org+3 amd64  [installiert]
php8.0-imagick/focal,now 3.5.1-2+ubuntu20.04.1+deb.sury.org+3 amd64  [installiert]
php8.0-intl/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-ldap/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-mbstring/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-mysql/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-opcache/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-readline/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-redis/focal,now 5.3.4+4.3.0-5+ubuntu20.04.1+deb.sury.org+3 amd64  [installiert]
php8.0-smbclient/focal,now 1.0.6-2+ubuntu20.04.1+deb.sury.org+3 amd64  [installiert]
php8.0-xml/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
php8.0-zip/focal,now 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 amd64  [installiert]
</details>

<details>
<summary>Installed software on second: # apt list --installed | grep php</summary>
php-common/focal,now 2:90+ubuntu20.04.1+deb.sury.org+1 all [installed,automatic]

php8.0-apcu/focal,now 5.1.21+4.0.11-2+ubuntu20.04.1+deb.sury.org+3 arm64 [installed]
php8.0-bcmath/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-bz2/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-cli/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-common/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-curl/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-fpm/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-gd/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-gmp/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-igbinary/focal,now 3.2.6+2.0.8-2+ubuntu20.04.1+deb.sury.org+3 arm64 [installed]
php8.0-imagick/focal,now 3.5.1-2+ubuntu20.04.1+deb.sury.org+3 arm64 [installed]
php8.0-intl/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-ldap/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-mbstring/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-mysql/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-opcache/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-readline/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-redis/focal,now 5.3.4+4.3.0-5+ubuntu20.04.1+deb.sury.org+3 arm64 [installed]
php8.0-smbclient/focal,now 1.0.6-2+ubuntu20.04.1+deb.sury.org+3 arm64 [installed]
php8.0-xml/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
php8.0-zip/focal,now 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 arm64 [installed]
</details>

Output of `apt-cache policy php8.0-fpm`
```
php8.0-fpm:
  Installed: 8.0.13-1+ubuntu20.04.1+deb.sury.org+2
  Candidate: 8.0.13-1+ubuntu20.04.1+deb.sury.org+2
  Version table:
 *** 8.0.13-1+ubuntu20.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 Packages
        100 /var/lib/dpkg/status
```

Thank you,
Tuffi

**Comment by Tuffiglig** [comment]
Now i was able to upgrade on my second machine to 8.0.14.
Did you do something?

**Comment by oerdnj** [comment]
> Now i was able to upgrade on my second machine to 8.0.14.
> 
> Did you do something?

Yup, the arm64 builders were broken at the time of the last upload, so I issued the rebuild.
