### ISSUE TITLE
[php7.0] php-mongodb module

### ISSUE THREAD

**Issue by phofmann-trust** [oerdnj/deb.sury.org#170]
Would be great to have a package for the new mongodb driver: https://github.com/mongodb/mongo-php-driver

**Comment by oerdnj** [comment]
The PHP7 branch is based on alpha2 and not up-to-date. I am reluctant to package this right now.

**Comment by joshuataylor** [comment]
Yes, it may be best to wait until release. Right now it's not complete - if you package it people will use it and complain it doesn't work right.

**Comment by oerdnj** [comment]
1.1.1 can be built on amd64, but fails on i386: https://github.com/mongodb/mongo-php-driver/issues/189

Anyway the amd64 builds are available as I write this comment.

I am going to keep this bug open till the 32-bit builds are sorted-out.

**Comment by oerdnj** [comment]
Thanks to Remi, we have a working patch.

**Comment by cybear-d** [comment]
i'm still cannot use the php-mongodb, when starting the php script it will warn that the mongodb.so is not valid.

```
/usr/lib/php/20151012/mongodb.so doesn't appear to be a valid Zend extension
```

**Comment by oerdnj** [comment]
@cybear-d what about some details? architecture, ubuntu release, packages versions, etc?

Folks, I really don't have a crystal ball or magic abilities to guess what have you done or installed on your system(s).

**Comment by cybear-d** [comment]
sorry for the missing information.
i'm using ubuntu 15.10 willy amd64 with php7.0 and install mongodb driver 1.1.1-2+deb.sury.org~wily+1

thank you.

**Comment by oerdnj** [comment]
Ah, I see; an copy&paste error slipped in, just run:

`sed -i s/zend_extension/extension/ /etc/php/mods-available/mongodb.ini`

I'll fix that in the package.
