### ISSUE TITLE
Apache cannot start after I upgraded it on Jan. 2, 2002.

### ISSUE THREAD

**Issue by taojing2002** [oerdnj/deb.sury.org#1702]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
I upgraded Apache on Jan. 2, 2002 and the Apache server cannot start. The error message looks like:
```
Cannot load /usr/lib/apache2/modules/mod_qos.so into server: /usr/lib/apache2/modules/mod_qos.so: undefined symbol: pcre_free
```
I am not the only one has the issue. I found someone has the same issue:
https://answers.launchpad.net/ubuntu/+source/libapache2-mod-qos/+question/700060

**Distribution (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA 

**Package(s) (please complete the following information):**
```
apt-cache policy libapache2-mod-qos apache2 libpcre3
libapache2-mod-qos:
  Installed: 11.44-1build1
  Candidate: 11.44-1build1
  Version table:
 *** 11.44-1build1 500
        500 http://ubuntu.nceas.ucsb.edu/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
apache2:
  Installed: 2.4.52-2+ubuntu18.04.1+deb.sury.org+1
  Candidate: 2.4.52-2+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 2.4.52-2+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.29-1ubuntu4.20 500
        500 http://ubuntu.nceas.ucsb.edu/ubuntu bionic-updates/main amd64 Packages
     2.4.29-1ubuntu4.18 500
        500 http://ubuntu.nceas.ucsb.edu/ubuntu bionic-security/main amd64 Packages
     2.4.29-1ubuntu4 500
        500 http://ubuntu.nceas.ucsb.edu/ubuntu bionic/main amd64 Packages
libpcre3:
  Installed: 2:8.39-9
  Candidate: 2:8.39-9
  Version table:
 *** 2:8.39-9 500
        500 http://ubuntu.nceas.ucsb.edu/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
The Debian apache2 package recently switched from pcre1 (old, unmaintained, buggy) to pcre2, and the mod-qos project needs to do the same. You can politely ask the mod-qos upstream to do so, from a quick glance this should not be that much work, but until then, you can't use mod-qos with these packages.

The move from pcre1 to pcre2 should have happened years ago, and it's inevitable now.

**Comment by taojing2002** [comment]
Thank you for the prompt reply. I will the mod-qos builder for the switch. Maybe I will bother you later :)
