### ISSUE TITLE
PHP8.1 on Ubuntu 20.04 report error: undefined symbol: crypto_core_ristretto255_scalar_invert

### ISSUE THREAD

**Issue by bpresles** [oerdnj/deb.sury.org#1707]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When installing php8.1-fpm package on Ubuntu 20.04, it fails to start with the error: undefined symbol: crypto_core_ristretto255_scalar_invert

**To Reproduce**
1. Upgrade Ubuntu 20.04 to latest packages
2. Add PPA for ondrej/php: `sudo add-apt-repository ppa:ondrej/php; sudo apt update`
3. Install php8.1-fpm: `sudo apt install php8.1-fpm`

Upon configuring the php8.1-fpm package, it tries to start it and report error: undefined symbol: crypto_core_ristretto255_scalar_invert
Note that this error also occurs using php cli.

**Expected behavior**
PHP FPM starts without error,a nd PHP cli works without error.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php8.1-fpm:
  Installé : 8.1.1-2+ubuntu20.04.1+deb.sury.org+1
  Candidat : 8.1.1-2+ubuntu20.04.1+deb.sury.org+1
 Table de version :
 *** 8.1.1-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
What's the output of `ldd /usr/sbin/php-fpm8.1`?

**Comment by bpresles** [comment]
Ok, thanks for the tip, I think I found the problem, I've a libsodium installed on /usr/local/lib.
        linux-vdso.so.1 (0x00007ffc4b9d3000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fca5f2a5000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fca5f2a0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca5f151000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca5f14b000)
        libapparmor.so.1 => /usr/lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007fca5f136000)
        libacl.so.1 => /usr/lib/x86_64-linux-gnu/libacl.so.1 (0x00007fca5f12b000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fca5f07a000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fca5eec2000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fca5ee2f000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fca5eb59000)
        libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fca5eac6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fca5eaaa000)
        **libsodium.so.23 => /usr/local/lib/libsodium.so.23 (0x00007fca5ea51000)**
        libargon2.so.1 => /usr/lib/x86_64-linux-gnu/libargon2.so.1 (0x00007fca5ea47000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca5e855000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fca5f83d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca5e832000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fca5e827000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fca5e7fe000)
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fca5e7db000)
        libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fca5e6bd000)
        libicuuc.so.66 => /usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007fca5e4d7000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fca5e4b4000)
        libicudata.so.66 => /usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007fca5c9f3000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fca5c80f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fca5c7f4000)

I'll look at what software installed it to avoid to break it.

**Comment by oerdnj** [comment]
Yup!
