### ISSUE TITLE
php8.1-gnupg 1.5.0 throws deprecation warnings, newer version available

### ISSUE THREAD

**Issue by spaze** [oerdnj/deb.sury.org#1708]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

`php8.1-gnupg/focal` throws

> PHP Deprecated:  Return type of gnupg_keylistiterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0

This is due to a change in PHP 8.1 and the gnupg extension has fixed the issue in 1.5.1 release https://github.com/php-gnupg/php-gnupg/issues/41 & https://github.com/php-gnupg/php-gnupg/pull/35

**To Reproduce**
1. Install `php8.1-gnupg`, my full version from `apt list --installed` is `php8.1-gnupg/focal,now 1.5.0-2+ubuntu20.04.1+deb.sury.org+3`
2. Run any PHP script
3. Notice these deprecation errors

```
PHP Deprecated:  Return type of gnupg_keylistiterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
PHP Deprecated:  Return type of gnupg_keylistiterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
PHP Deprecated:  Return type of gnupg_keylistiterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
PHP Deprecated:  Return type of gnupg_keylistiterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
PHP Deprecated:  Return type of gnupg_keylistiterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
```

**Expected behavior**
No deprecation errors :-)

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

Can you please package and release ext-gnupg 1.5.1? Thanks a lot!

**Comment by oerdnj** [comment]
Uploaded and building.
