### ISSUE TITLE
php-common : Breaks: php-apcu

### ISSUE THREAD

**Issue by clusterx** [oerdnj/deb.sury.org#1709]
since today after the sury.org update I see issues with php-common : Breaks: php-apcu

`The following packages have unmet dependencies:
php-common : Breaks: php-apcu (< 5.1.21+4.0.11-7~)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

#Update process:
The following package was automatically installed and is no longer required:
  php8.1-imagick
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  php-apcu php-imagick
The following NEW packages will be installed:
  php8.1-imap
The following packages will be upgraded:
  php-common php-imap
2 upgraded, 1 newly installed, 2 to remove and 0 not upgraded.
Need to get 56.8 kB of archives.
After this operation, 100 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.sury.org/php buster/main amd64 php-common all 2:92+0~20220117.41+debian10~1.gbp7a2f0c [16.9 kB]
Get:2 https://packages.sury.org/php buster/main amd64 php8.1-imap amd64 8.1.1-1+0~20211220.11+debian10~1.gbp519568 [32.6 kB]
Get:3 https://packages.sury.org/php buster/main amd64 php-imap all 2:8.1+92+0~20220117.41+debian10~1.gbp7a2f0c [7,392 B]
Fetched 56.8 kB in 0s (301 kB/s)     
(Reading database ... 136492 files and directories currently installed.)
Removing php-apcu (5.1.21+4.0.11-2+0~20211113.30+debian10~1.gbp4aed2f) ...
Removing php-imagick (3.6.0-1+0~20211231.34+debian10~1.gbp2575b4) ...
(Reading database ... 136486 files and directories currently installed.)
Preparing to unpack .../php-common_2%3a92+0~20220117.41+debian10~1.gbp7a2f0c_all.deb ...
Unpacking php-common (2:92+0~20220117.41+debian10~1.gbp7a2f0c) over (2:91+0~20211231.40+debian10~1.gbpe2a6c5) ...
Selecting previously unselected package php8.1-imap.
Preparing to unpack .../php8.1-imap_8.1.1-1+0~20211220.11+debian10~1.gbp519568_amd64.deb ...
Unpacking php8.1-imap (8.1.1-1+0~20211220.11+debian10~1.gbp519568) ...
Preparing to unpack .../php-imap_2%3a8.1+92+0~20220117.41+debian10~1.gbp7a2f0c_all.deb ...
Unpacking php-imap (2:8.1+92+0~20220117.41+debian10~1.gbp7a2f0c) over (2:8.0+91+0~20211231.40+debian10~1.gbpe2a6c5) ...
Setting up php-common (2:92+0~20220117.41+debian10~1.gbp7a2f0c) ...
Setting up php8.1-imap (8.1.1-1+0~20211220.11+debian10~1.gbp519568) ...`

**Comment by ArthurHoaro** [comment]
We also have an issue with `php-apcu` that appeared today on a legacy Docker image that could be related.

The package `php7.3-apcu` installs PHP 7.4:

> `apt-get install php7.3-apcu`
>
> The following additional packages will be installed:
> bzip2 file libargon2-1 libbsd0 libedit2 libgdbm-compat4 libgdbm6 libicu67
> libmagic-mgc libmagic1 libmd0 libpcre2-8-0 libperl5.32 libsodium23 libxml2
> mailcap media-types mime-support netbase perl perl-modules-5.32 php-apcu-bc
> php-common php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-phpdbg
>  php7.3-readline **php7.4-apcu php7.4-apcu-bc php7.4-cli php7.4-common
>  php7.4-json php7.4-opcache php7.4-phpdbg php7.4-readline** psmisc
>  sensible-utils ucf xz-utils

Here is a simple Dockerfile to reproduce the issue:

```
FROM debian:11-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
      curl \
      zip \
      apt-utils \
      gnupg \
      apt-transport-https \
   && curl -L -k https://packages.sury.org/php/apt.gpg | apt-key add - \
   && sh -c 'echo "deb https://packages.sury.org/php/ bullseye main" > /etc/apt/sources.list.d/php.list' \
   && apt-get update && apt-get install -y \
      php7.3-apcu

RUN php -v
```
