### ISSUE TITLE
php7.0-ldap and php7.0-intl modules

### ISSUE THREAD

**Issue by paulschreiber** [oerdnj/deb.sury.org#171]
It would be handy to have the php7.0-ldap and php7.0-intl modules available.

**Comment by oerdnj** [comment]
And they are not? They should be available  

On 12 Dec 2015, Paul Schreiber <notifications@github.com> wrote:
>It would be handy to have the php7.0-ldap and php7.0-intl modules
>available.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/171

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by paulschreiber** [comment]
Looks like my ppa configuration was overwritten. I re-added it and see them now.

**Comment by paulschreiber** [comment]
Which package should I install to get PEAR? `php-pear` seems to be for php5.
