### ISSUE TITLE
php8.0-dev installs PHP 8.1.1 (cli)

### ISSUE THREAD

**Issue by timglabisch** [oerdnj/deb.sury.org#1711]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
when installing php8.0-dev you end up with php 8.1
even if you also install php 8.1 cli. 

**To Reproduce**
```
docker run --rm ubuntu:20.04 bash -c "apt-get update && apt-get install -y software-properties-common && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php && apt-get update && apt-get install -y php8.0-dev && php -v"
```

ends up as: 

```
PHP 8.1.1 (cli) (built: Dec 31 2021 07:26:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
```

**Expected behavior**
yesterday php 8.0 was installed. (our daily ci build starts failing today)

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: x86
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**
```
php8.0-dev:
  Installed: 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
> I have read Frequently Asked Questions

No, you didn't, it's actually explained in the FAQ

**Comment by timglabisch** [comment]
i guess this is related to https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#why-is-phpdefaultversion-cli-always-installed (would make sense if default.version was updated yesterday).

I am still confused and wondering if all the people who installed `php8.0-cli php8.0-dev` would end up with php 8.1 after running apt update. 

for me, even after reading the faq it's still unexpected that you end up with php 8.1 when running this:

```
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php && apt-get update && apt-get install -y \
    php8.0-xml \
    php8.0-fpm \
    php8.0-cli \
    php8.0-opcach \
    php8.0-readli \
    php8.0-curl \
    php8.0-gd \
    php8.0-intl \
    php8.0-mysql \
    php8.0-mbstri \
    php8.0-soap \
    php8.0-zip \
    php8.0-bcmath \
    php8.0-sqlite3 \
    php8.0-ssh2 \
    php8.0-apcu \
    php8.0-tidy \
    php8.0-redis \
    php8.0-dev
```

looks like i have no choice but to remove php8.0-dev as a fix for me.

anyway, thanks a lot for maintaining these packages.

**Comment by vincentlepot** [comment]
This is due to php8.0-dev recommending pkg-php-tools, needing php-json.

Either avoid installing pkg-php-tools, or just update-alternative to force php8.0 as your cli. (see the php-pear section in the FAQ)

**Comment by swalkinshaw** [comment]
This issue was closed, but *something*  change did the past ~24 hours causing this issue since it's affecting many people. Was 8.1 recently made the default version? Or did some other change affect this?

The FAQ points to a few potential solutions, but not the root cause. Knowing that would better help people understand what the proper fix is hopefully.

**Comment by swalkinshaw** [comment]
If this helps anyone:

```plain
$ apt-cache depends php8.0-dev
php8.0-dev
  Depends: autoconf
  Depends: automake
  Depends: libpcre2-dev
  Depends: libssl-dev
  Depends: pkg-config
    pkgconf
  Depends: php8.0-cli
  Depends: php8.0-common
  Depends: shtool
  Depends: libtool
  Recommends: pkg-php-tools
vagrant@example:~$ apt-cache depends pkg-php-tools
pkg-php-tools
  Depends: php-pear
  Depends: php-cli
    php5.6-cli
    php7.0-cli
    php7.1-cli
    php7.2-cli
    php7.3-cli
    php7.4-cli
    php8.0-cli
    php8.1-cli
  Suggests: dh-make
vagrant@example:~$ apt-cache depends php-cli
php-cli
  Depends: php8.1-cli
```

Summary: `php8.0-dev` recommends `pkg-php-tools`, which depends on `php-cli` (virtual package), which resolves to `php8.1-cli`.

`apt-get` by default (on Ubuntu at least) automatically installs recommended packages (but not suggested). One solution is to disable that: `sudo apt-get install --no-install-recommends php8.0-dev`

**Comment by kbond** [comment]
I don't have `php8.0-dev` installed and I use `--no-install-recommends` but still got `php8.1-cli` on an `apt upgrade`. Still tracking down why.

**Comment by willitscale** [comment]
For those struggling with this Oerdnj's response is correct, it is covered in the FAQ. What he meant by this was https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#php-pear, 

If I'm correct the implicit reference to PHP 8.1 lies in the `pkg-php-tools` package which depends on `php-json` (individual versions supported up to 7.4) and if PHP 8.0 or above that will always depend on the latest version (as shown below).

```
$ apt-cache depends pkg-php-tools
pkg-php-tools
  Depends: debhelper
  Depends: php-pear
  Depends: php-cli
    php5.6-cli
    php7.0-cli
    php7.1-cli
    php7.2-cli
    php7.3-cli
    php7.4-cli
    php8.0-cli
    php8.1-cli
  Depends: php-json
    php5.6-json
    php7.0-json
    php7.1-json
    php7.2-json
    php7.3-json
    php7.4-json
  Depends: php-xml
    php5.6-xml
    php7.0-xml
    php7.1-xml
    php7.2-xml
    php7.3-xml
    php7.4-xml
    php8.0-xml
    php8.1-xml
  Suggests: dh-make
$ apt-cache depends php-json     
php-json
  Depends: php-common
  Depends: <php8.1-json>
    libapache2-mod-php8.1
    libphp8.1-embed
    php8.1-cgi
    php8.1-cli
    php8.1-fpm
    php8.1-phpdbg
```

As Ondrej isn't the maintainer of this we're waiting on Ubuntu to update it

```
$ apt-cache policy pkg-php-tools
pkg-php-tools:
  Installed: (none)
  Candidate: 1.38
  Version table:
     1.38 500
        500 http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu focal/main i386 Packages
$ Package: pkg-php-tools
Version: 1.38
Priority: extra
Section: php
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 164 kB
Depends: debhelper, php-pear, php-cli, php-json, php-xml
Suggests: dh-make
Download-Size: 28.3 kB
APT-Sources: http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu focal/main amd64 Packages
Description: various packaging tools and scripts for PHP packages
 Provide an easy way to package PHP PEAR, PECL and Composer packages: Run
 dh_make, edit debian/rules and debian/control and that's it!
 .
 Detailed instructions can be found in included READMEs.
```

There are two fixes outlined in the FAQ:

1. Install `php8.0-dev` without recommends, although this will not install pkg-php-tools and in turn also NOT install php-pear
```
$ apt-get install -y -q --no-install-recommends \
        php8.0-dev
```

This will stop any PHP 8.1 components from being installed, but also not install pear.

2. Install `php8.0-dev` as normal and then update your alternatives to use PHP-8.0 which will install php-pear and continue to work as expected with PHP 8.0

```
$ update-alternatives --set php /usr/bin/php8.0
$ pear version
PEAR Version: 1.10.12
PHP Version: 8.0.15
Zend Engine Version: 4.0.15
Running on: Linux 2327f35387d6 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64
```

This will install PHP 8.1 cli, common, opcache, phpdbg and readline

Hope that helps
