### ISSUE TITLE
memcached: php_msgpack_serialize in Unknown on line 0 after yesterday update

### ISSUE THREAD

**Issue by qeepcologne** [oerdnj/deb.sury.org#1713]
after updated some packages yesterday (ubuntu 20.04, php5.6) i got the following warnings:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcached.so' - /usr/lib/php/20131226/memcached.so: undefined symbol: php_msgpack_serialize in Unknown on line 0

old version working:
php5.6-memcached:amd64=3.1.5+2.2.0-10+ubuntu20.04.1+deb.sury.org+3
php5.6-igbinary:amd64 3.2.6+2.0.8-2+ubuntu20.04.1+deb.sury.org+3
php5.6-msgpack:amd64=2.2.0~rc1+2.1.2+0.5.7-2+ubuntu20.04.1+deb.sury.org+3
etc.

problem starts after updated to:
php5.6-memcached:amd64 3.1.5+2.2.0-14+ubuntu20.04.1+deb.sury.org+10
php5.6-igbinary:amd64 3.2.6+2.0.8-6+ubuntu20.04.1+deb.sury.org+10
php5.6-msgpack:amd64 2.2.0~rc1+2.1.2+0.5.7-6+ubuntu20.04.1+deb.sury.org+10
etc.

I also tried to rollback, but old version seems not to be available anymore.

i checked all of these modules are loaded, order is also correct (20 for igbinary and msgpack, 25 for memcached). This is a little strange: old packages provide the 25 order link, new memcached package 20 memcached link in php-fpm). I tried to remove the 20, same result, if i keep the 20 and remove the 25, sessions are not working at all.

in general i am confused, we set in memcached.ini
memcached.serializer = "igbinary"
So msgpack should not be used at all, i tried to uninstall, but not possible, because memcached has dependency on it.

**Comment by oerdnj** [comment]
Is the msgpack loaded at all?

**Comment by qeepcologne** [comment]
root@www1 ~ # php -m|grep msgpack
msgpack
root@www1 ~ # php -i|grep msgpack
/etc/php/5.6/cli/conf.d/20-msgpack.ini,
msgpack support => yes
msgpack
msgpack.error_display => On => On
msgpack.illegal_key_insert => Off => Off
msgpack.php_only => On => On
msgpack.use_str8_serialization => On => On
Registered serializer handlers => php_serialize php php_binary igbinary msgpack wddx

**Comment by oerdnj** [comment]
My guess is that you are loading `memcached` out of order somewhere from the config files:

```
(focal-amd64)root@calcifer:/home/ondrej# php -v
PHP 5.6.40-57+ubuntu20.04.1+deb.sury.org+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

and the modules load just fine:

```
(focal-amd64)root@calcifer:/home/ondrej# php -m
[PHP Modules]
calendar
Core
ctype
date
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
json
libxml
memcached
mhash
msgpack
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

**Comment by oerdnj** [comment]
So, you need to look at any custom modifications you did to the PHP installation.

Also the `php-cli` has a different configuration than `php-fpm`, so the output you gave isn't really proving that you are loading `msgpack` in the correct order to the FPM SAPI. (On other hand, my output proves it should work...)

**Comment by qeepcologne** [comment]
thanks a lot, i have the similar output, all modules including memcached are loaded fine (and its working), i am just scared about the warning and why memcached requires msgpack and throwing msgpack warning even if we use a different memcached.serializer. I try to reproduce tomorrow in a clean docker environment.

**Comment by oerdnj** [comment]
Than this might be even stronger support that you might be loading memcached twice - on the first try the msgpack isn't loaded yet and it fails and on the second try it works.

Try greping /etc/php for memcached, maybe something will catch your eye...

**Comment by qeepcologne** [comment]
works exactly as you described. There are 2 links in /etc/php/5.6/fpm/conf.d (and cli/conf.d)
the last update installed conf.d/20-memcached.ini
and from the older package install: 25-memcached.ini
if i remove both of the 20-memcached.ini links warning is gone.

Don't know why this config order changed and i believe you that clean install works, but update results in situation with 2 links and only the old order works.

**Comment by oerdnj** [comment]
What are the exact contents of `memcached.ini`?

**Comment by qeepcologne** [comment]
`
extension=memcached.so
[memcached]
memcached.sess_locking = 0
memcached.sess_prefix = "www.sess.key."
memcached.sess_consistent_hash = On
memcached.sess_remove_failed_servers = 1
memcached.sess_remove_failed = 1
memcached.sess_number_of_replicas = 1 
memcached.sess_binary_protocol = 1 
memcached.sess_binary = 1
memcached.sess_randomize_replica_read = 0
memcached.sess_connect_timeout = 1000
memcached.use_sasl=
memcached.sess_sasl_username = NULL
memcached.sess_sasl_password = NULL
memcached.compression_type = "fastlz"
memcached.compression_factor = "1.3"
memcached.compression_threshold = 2000
memcached.serializer = "igbinary"
memcached.store_retry_count = 2
`

**Comment by oerdnj** [comment]
That explains it. You trashed the priority header and it defaulted to priority 20.
