### ISSUE TITLE
php-ssh2 depend from Depends: php8.1-ssh2

### ISSUE THREAD

**Issue by aqueos** [oerdnj/deb.sury.org#1715]
**Frequently asked questions**

- [ ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

upgrading php-ssh2 install php8.1 and a bunch of other 8.1 packages :)

Package: php-ssh2
Version: 1.3.1+0.13-6+0~20220117.24+debian9~1.gbpe1a643
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 13
Pre-Depends: php-common (>= 2:69~)
Depends: php8.1-ssh2
Breaks: libssh2-php (<< 0.12-2)
Replaces: libssh2-php (<< 0.12-2)
Homepage: http://pecl.php.net/package/ssh2
Priority: extra

**To Reproduce**

use php7.2 having php-ssh2 installed, apt-get upgrade, you endup with php8.1 installed

**Expected behavior**

just upgrade php-ssh2 packages

**Distribution (please complete the following information):**

    codename => "stretch",
    description => "Debian GNU/Linux 9.13 (stretch)",
    id => "Debian",
    release => {
      full => "9.13",
      major => "9",
      minor => "13"
    }

hope it helps !

Ghislain.

**Comment by oerdnj** [comment]
Yes.
