### ISSUE TITLE
php-imagick install php8.1

### ISSUE THREAD

**Issue by aqueos** [oerdnj/deb.sury.org#1716]
**Describe the bug**

After the php-ssh2 with a depend php8.1-common i see that imagick has the same issue. This could be present in a lot more extention:

Package: php-imagick
Depends: php8.1-imagick

Package: php-imagick
Version: 3.6.0-4+0~20220117.35+debian10~1.gbp149f82
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 23
Pre-Depends: php-common (>= 2:69~)
Depends: php8.1-imagick

perhaps its present on other packages, only found in those 2 for now.

best regards,
Ghislain.

**Comment by oerdnj** [comment]
There's no issue.  Stop opening new issues.
