### ISSUE TITLE
Conflict libphp.so for PHP 8.0 and PHP 8.1

### ISSUE THREAD

**Issue by mar0x** [oerdnj/deb.sury.org#1718]
**Frequently asked questions**

- [+] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Both libphp8.0.so and libphp8.1.so have same soname (libphp.so) which is a symlink. This is incorrect because libraries are not binary compatible.

Actual issue can be reproduced with [NGINX Unit application server](https://unit.nginx.org). Unit uses language modules which is linked with libphp8.so. After linkage, reference to library replaced with libphp.so (because of soname). So, if the module was build for PHP 8.0 and then PHP 8.1 installed module will not work (issue https://github.com/nginx/unit/issues/634).

As far as I understand, soname should be more version specific (e.g. libphp8.0.so and libphp8.1.so). As an option, there can be two different libphp.so in version-specific locations.

**To Reproduce**
1. add ppa for Ubuntu 20.04: `sudo add-apt-repository ppa:ondrej/php`
2. install php8.0: `sudo apt install php8.0 php8.0-dev libphp8.0-embed`
3. download Unit sources:
```
$ curl -O https://unit.nginx.org/download/unit-1.26.1.tar.gz
$ tar xzf unit-1.26.1.tar.gz
```
4. configure and build Unit and PHP module:
```
$ cd unit-1.26.1
$ ./configure
$ ./configure php --config=php-config8.0
$ make
```
5. install php8.1: `sudo apt install php8.1 php8.1-dev libphp8.1-embed`
6. check the module linkage:
```
$ ldd build/php.unit.so | grep libphp
        libphp.so => /lib/libphp.so (0x00007f88f8ae8000)
$ ls -l /lib/libphp.so
lrwxrwxrwx 1 root root 12 Jan 21 11:51 /lib/libphp.so -> libphp8.1.so
```
an attempt to use module lead to undefined behaviour.

**Expected behavior**
Unit PHP module should be linked against libphp8.0.so and work perfect.

**Distribution:**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s):**
```
libphp8.0-embed:
  Installed: 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 8.0.14-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tippexs** [comment]
Hi @oerdnj any update on this? Is there anything we can do to help? Your repository and the pre-build PHP Versions are a great resource! Used them as a user a lot and would like to say thank you for that :)
Now - working for / with Unit it is great to work on the implementation side of things.

Let me know if there is anything we can help with to make the different versions of PHP work with Unit

**Comment by oerdnj** [comment]
I understand this is annoying, but it's not a packaging problem:
```
(focal-amd64)root@calcifer:/home/ondrej# objdump -p /usr/lib/libphp8.0.so | grep SONAME
  SONAME               libphp.so
(focal-amd64)root@calcifer:/home/ondrej# objdump -p /usr/lib/libphp8.1.so | grep SONAME
  SONAME               libphp.so
```

And I am not going to mangle the upstream SONAME. This would break far more things than this annoyance, where you need to manually pin the `libphp.so` to version you need, see `man update-alternatives`.

**Comment by tippexs** [comment]
Thanks @oerdnj for you quick reply. I will look into this and find a way in our documentation to workaround this issue by "manually" pinning the libphp.so to the version we need.
