### ISSUE TITLE
aptitude install php7.0-dev suggests php5 dependencies

### ISSUE THREAD

**Issue by paulschreiber** [oerdnj/deb.sury.org#172]
I'm on Ubuntu 15.10 (wily). When I try and install `php7.0-dev`, aptitude suggests installing many php5 dependencies:

```
# aptitude install php7.0-dev
The following NEW packages will be installed:
  php-cli{a} php-pear{a} php5-cli{a} php5-common{a} php5-json{a} php5-readline{a} php7.0-dev pkg-php-tools{a} shtool{a} 
0 packages upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,613 kB of archives. After unpacking 17.9 MB will be used.
The following packages have unmet dependencies:
 php7.0-cli : Breaks: php5-cli but 5.6.11+dfsg-1ubuntu3.1 is to be installed.
 php7.0-common : Conflicts: php5-common but 5.6.11+dfsg-1ubuntu3.1 is to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     php5-cli [Not Installed]                           
2)     php5-common [Not Installed]                        
3)     php5-json [Not Installed]                          
4)     php5-readline [Not Installed]                      
5)     pkg-php-tools [Not Installed]                      

     Leave the following dependencies unresolved:         
6)     php7.0-dev recommends pkg-php-tools                


Accept this solution? [Y/n/q/?] ^C
```

**Comment by oerdnj** [comment]
What does `apt-cache policy php-pear` says on your system? 

On 12 Dec 2015, Paul Schreiber <notifications@github.com> wrote:
>I'm on Ubuntu 15.10 (wily). When I try and install `php7.0-dev`,
>aptitude suggests installing many php5 dependencies:
>
>```
># aptitude install php7.0-dev
>The following NEW packages will be installed:
>php-cli{a} php-pear{a} php5-cli{a} php5-common{a} php5-json{a}
>php5-readline{a} php7.0-dev pkg-php-tools{a} shtool{a} 
>0 packages upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
>Need to get 3,613 kB of archives. After unpacking 17.9 MB will be used.
>The following packages have unmet dependencies:
>php7.0-cli : Breaks: php5-cli but 5.6.11+dfsg-1ubuntu3.1 is to be
>installed.
>php7.0-common : Conflicts: php5-common but 5.6.11+dfsg-1ubuntu3.1 is to
>be installed.
>The following actions will resolve these dependencies:
>
>     Keep the following packages at their current version:
>1)     php5-cli [Not Installed]                           
>2)     php5-common [Not Installed]                        
>3)     php5-json [Not Installed]                          
>4)     php5-readline [Not Installed]                      
>5)     pkg-php-tools [Not Installed]                      
>
>     Leave the following dependencies unresolved:         
>6)     php7.0-dev recommends pkg-php-tools                
>
>
>Accept this solution? [Y/n/q/?] ^C
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/172

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by paulschreiber** [comment]
```
php-pear:
  Installed: 1:1.10.1+submodules+notgz-3+deb.sury.org~wily+2
  Candidate: 1:1.10.1+submodules+notgz-3+deb.sury.org~wily+2
  Version table:
 *** 1:1.10.1+submodules+notgz-3+deb.sury.org~wily+2 0
        500 http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/ wily/main amd64 Packages
        100 /var/lib/dpkg/status
     5.6.11+dfsg-1ubuntu3.1 0
        500 http://ubuntu.mirror.iweb.ca/ wily-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ wily-security/main amd64 Packages
     5.6.11+dfsg-1ubuntu3 0
        500 http://ubuntu.mirror.iweb.ca/ wily/main amd64 Packages
```

**Comment by oerdnj** [comment]
`aptitude` is trying to pull pkg-php-tools from Recommends and this packages hasn't been updated yes. Either use `apt-get` or disable pulling of recommended packages by default.
