### ISSUE TITLE
php5.6-xcache missing in impish/jammy, available in focal

### ISSUE THREAD

**Issue by qeepcologne** [oerdnj/deb.sury.org#1720]
i tried to install php5.6 setup on ubuntu 21.10 (Impish Indri).
but package php5.6-xcache is missing.
on ubuntu 20.04 LTS (Focal Fossa) package exists.
i tried to copy package from ubuntu 20 server (/var/cache/apt/archives/php5.6-xcache_3.2.0-8+ubuntu20.04.1+deb.sury.org+1_amd64.deb) and installed it via dpkg -i and i looks like it is working.

Is there a specific reason to remove it?

i know that we should migrate to opcache and must do this for recent php version, this is at the top of our list, but for now we have some legacy code with custom xcache implementation.

**Comment by qeepcologne** [comment]
same on jammy,
php5.6-xcache/now 3.2.0-8+ubuntu20.04.1+deb.sury.org+1 is the last and still works on jammy, but need to install manually from old repository.

**Comment by qeepcologne** [comment]
thanks for answering.
I think for most people it's not relevant if it's coming from new or old build system or if it is build for ubuntu20 or 22, is it possible to just add the existing ubuntu 20 package to the ubuntu 22 repos?

**Comment by oerdnj** [comment]
I've updated the packaging, so the packages are now building again.
