### ISSUE TITLE
Question: Support for downgrade to Xdebug2?

### ISSUE THREAD

**Issue by janosmiko** [oerdnj/deb.sury.org#1722]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
We would require Xdebug version 2 for some projects (e.g: Magento 2.3 does not support Xdebug 3)

**Describe the solution you'd like**
Is it possible to downgrade to version 2 somehow?

**Describe alternatives you've considered**
I'm not 100% sure about this but on CentOS (Remi repo) there are 2 xdebug packages: xdebug and xdebug3. 
An idea would be to add php7.x-xdebug2 for backward compatibility.

**Distribution:**
 - OS: Debian Bullseye
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php7.4-xdebug:
  Installed: 3.1.2+2.9.8+2.8.1+2.5.5-1+0~20220117.45+debian11~1.gbp75d182
  Candidate: 3.1.2+2.9.8+2.8.1+2.5.5-1+0~20220117.45+debian11~1.gbp75d182
  Version table:
 *** 3.1.2+2.9.8+2.8.1+2.5.5-1+0~20220117.45+debian11~1.gbp75d182 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
You can always compile weird combinations by hand. You don't need packages for that.
