### ISSUE TITLE
openssl 3.0 compatiblity

### ISSUE THREAD

**Issue by shemgp** [oerdnj/deb.sury.org#1724]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
You would need [this](https://bugs.php.net/patch-display.php?bug_id=81278&patch=php-8.1-openssl3.patch&revision=latest) patch when compiling PHP 8.0 in Ubuntu Jammy Jellyfish since it uses openssl 3.0.

**Describe the solution you'd like**
Use the patch, so build will finish.

**Describe alternatives you've considered**
Use PHP 8.1 and not PHP 8.0.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Additional context**
https://bugs.php.net/bug.php?id=81278

**Comment by My1** [comment]
to be entirely honest I would in fact love openssl3 in there too as php8.1 and openssl3 in combination is needed for some things like ECDH in openssl_dh_compute_key

**Comment by oerdnj** [comment]
I am not going to backport OpenSSL 3.0, but for distributions that already have OpenSSL 3.0, there's full compatibility.
