### ISSUE TITLE
PHP 8.1 php-memcached may be missing fixes from upstream

### ISSUE THREAD

**Issue by xPaw** [oerdnj/deb.sury.org#1725]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Storing float values in memcached are always appended with negative sign, which is incorrect.

See https://github.com/php-memcached-dev/php-memcached/issues/500 for more information and repro code.
I created a brief test case in the upstream repo and it passed: https://github.com/php-memcached-dev/php-memcached/pull/501

If I am looking at the right repo: https://salsa.debian.org/php-team/pecl/php-memcached it appears to be missing some of the last commits, which I am not entirely sure how it even compiles for PHP8.1?

Specifically this commit: https://github.com/php-memcached-dev/php-memcached/commit/605a8a63a7461983512ce12601e995dad18f5a9b

**Distribution (please complete the following information):**
 - OS: Debian 11
 - Architecture: amd64
 - Repository: https://packages.sury.org/php/

**Package(s) (please complete the following information):**
```
$ apt-cache policy php8.1-memcached
php8.1-memcached:
  Installed: 3.1.5+2.2.0-14+0~20220117.37+debian11~1.gbpc8d81e
  Candidate: 3.1.5+2.2.0-14+0~20220117.37+debian11~1.gbpc8d81e
  Version table:
 *** 3.1.5+2.2.0-14+0~20220117.37+debian11~1.gbpc8d81e 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by xPaw** [comment]
There's now php-mecached [3.2.0RC1](https://github.com/php-memcached-dev/php-memcached/commit/5bb007e62503cf2730514db742a3d47b2d28f9be) which should properly support PHP8.0 / PHP8.1 and thus fix this issue.

**Comment by tvlooy** [comment]
3.2.0 is released now

**Comment by meniam** [comment]
Please bump the version to 3.2.0 it's very important for Symfony users

**Comment by xPaw** [comment]
Fixed now.
