### ISSUE TITLE
Status of systemd dependency

### ISSUE THREAD

**Issue by retry-the-user** [oerdnj/deb.sury.org#1726]
I don't want to belabor the issue about the systemd dependency. I just want to know why, with the latest php7.4 update, apt reports that systemd is no longer a required dependency.  This doesn't seem to be the case for php8.1 though.  Can we get some clarification on what's happening, please?  Is the systemd dependency going away indefinitely, temporarily, or is this a mistake of some kind?  Will future php8.1 releases follow suit or is this just a php7.x change?  Thank you.

**Comment by oerdnj** [comment]
This applies on to a version in Debian bullseye: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959174#87
