### ISSUE TITLE
Packages files for Hirsute / AMD64 are empty

### ISSUE THREAD

**Issue by klimenttoshkov** [oerdnj/deb.sury.org#1732]
[Packages files](http://ppa.launchpad.net/ondrej/php/ubuntu/dists/hirsute/main/binary-amd64/) are empty.
Nothing is found when PPA added to Ubuntu and PHP 8.1 cannot be installed.

**To Reproduce**
Add repository:
```
add-apt-repository ppa:ondrej/php
apt install php8.1
```

**Expected behavior**
to install the requested version

**Distribution (please complete the following information):**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```

**Package(s) (please complete the following information):**
```
N: Unable to locate package php8.1
N: Couldn't find any package by glob 'php8.1'
N: Couldn't find any package by regex 'php8.1'
```

**Comment by oerdnj** [comment]
Yes

**Comment by klimenttoshkov** [comment]
@oerdnj Please apologize me but how are we going to install them on 21.04 then? It is LTS.

**Comment by bashgeek** [comment]
> @oerdnj Please apologize me but how are we going to install them on 21.04 then? It is LTS.

21.04 is NOT an LTS and is even EOL since January 20th.

**Comment by klimenttoshkov** [comment]
Thank you. I thought it was.

**Comment by mxdpeep** [comment]
18.04, 20.04, 22.04 (future) are LTS

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*
