### ISSUE TITLE
PHP8.0 install appears not to allow for CURL to be installed even after running apt-get install php-curl

### ISSUE THREAD

**Issue by bostonmacosx** [oerdnj/deb.sury.org#1734]
**Frequently asked questions**

- [ X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Installed PHP 8.0
ran:
sudo install apt-get install php-curl

appears to install a bunch of 7.4 php-curl...and not 8.0

We've done a purge of 7.* php on the machine and a remove...

Says that when running the start of php8.0

PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: /usr/lib/php/20200930/curl (/usr/lib/php/20200930/curl: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/curl.so (/usr/lib/php/20200930/curl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/bin/curl' (tried: /usr/bin/curl (/usr/bin/curl: cannot dynamically load position-independent executable), /usr/lib/php/20200930//usr/bin/curl.so (/usr/lib/php/20200930//usr/bin/curl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**To Reproduce**

**Expected behavior**
Expected to be able to add CURL support to the 8.0 installation. curl_init is reporting unavailable in any PHP based page. 

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Ubuntu 21.XX
 - Architecture: [e.g. amd64 or armhf or ...]
 - amd64
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]
sorry I don't have this exact info at this time...on a co-workers server

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
None

**Comment by oerdnj** [comment]
You intentionally ignored all the questions, so I am going to intentionally ignore this question.

**Comment by bostonmacosx** [comment]
@oerdnj Updated with the apt-cache information

**Comment by oerdnj** [comment]
hirsute

^^^ Here's your problem...

**Comment by bostonmacosx** [comment]
> hirsute
> 
> ^^^ Here's your problem...

So you're saying it isn't compatible with this build of ubuntu?

**Comment by bashgeek** [comment]
Hirsute (21.04) is EOL since January, please upgrade your system(s).
