### ISSUE TITLE
php-gnupg depends on php7.4-gnupg instead of php8.1-gnupg

### ISSUE THREAD

**Issue by KimBrodowski** [oerdnj/deb.sury.org#1735]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
The metapackage php-gnupg depends on php7.4-gnupg instead of php8.1-gnupg. Since the majority of php metapackages depends on their 8.1 counterpart, so should php-gnupg.

Having the correct dependency allows for clean upgrades.

**To Reproduce**
1. `aptitude show php-gnupg`
2. Compare to e.g. `aptitude show php-fpm`

**Expected behavior**
php-gnupg depends on some version of php8.1-gnupg.

**Distribution (please complete the following information):**
 - OS: Debian Bullseye
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
~~~
Package: php-gnupg
Version: 1.5.1-1+0~20220117.9+debian11~1.gbp2d981f
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 11
Pre-Depends: php-common (>= 2:69~)
Depends: ucf, php7.4-gnupg
Homepage: https://pecl.php.net/package/gnupg
Priority: optional
Section: php
Filename: pool/main/p/php-gnupg/php-gnupg_1.5.1-1+0~20220117.9+debian11~1.gbp2d981f_amd64.deb
Size: 3508
SHA256: a596a0f56ca8516ac2afc286b0617351384f9386d837ebcb0a3fa7c94490b601
SHA1: 7809c80f5f948fd28c8cf25d57af0497b3ae6066
MD5sum: b433016be57e4ef5f547dd38a9ab51e2
Description: PHP wrapper around the gpgme library
 This PHP extension provides methods to interact with gnupg.
~~~

**Additional context**
N/A

**Comment by oerdnj** [comment]
This was fixed in 1.5.1-2
