### ISSUE TITLE
[php-7.0] request for extension uploadprogress

### ISSUE THREAD

**Issue by basz** [oerdnj/deb.sury.org#174]
https://pecl.php.net/package/uploadprogress

**Comment by oerdnj** [comment]
This looks like it might be possible:
http://git.php.net/?p=pecl/php/uploadprogress.git;a=commitdiff;h=7a4d6b3ac3575caedf9429940f54688411cbf5e9
I'll look into it, but I would rather wait for a full upstream release for non-critical extensions.

**Comment by basz** [comment]
thanks but no rush on my part - we have refactored to use session's build in progress loader

**Comment by oerdnj** [comment]
Uploaded as `php-uploadprogress_1.0.3.1-4-g95d8a0f-1+deb.sury.org~*+1`
