### ISSUE TITLE
Repo now IPv4-only?

### ISSUE THREAD

**Issue by WilliamDEdwards** [oerdnj/deb.sury.org#1742]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

The repo is unreachable from IPv6-only systems, whereas it was working fine before.

```
root@failover:~# host packages.sury.org
packages.sury.org is an alias for debsuryorg.b-cdn.net.
debsuryorg.b-cdn.net has address 84.17.46.53
```

I don't know since when this has been the case.

**To Reproduce**

1. Ensure the host has only IPv6 connectivity
2. Attempt connecting to packages.sury.org
3. `connect: Network is unreachable`

**Expected behavior**

The ability to reach the repo over IPv6. It's 2022, after all.

**Comment by oerdnj** [comment]
I got this answer from the Bunny CDN:

> We only support IPv6 in some locations, so this would only work if you were hitting the region/server where IPv6 is enabled. 
> 
> IPv6 is still something we're working on to deploy fully across the network, so you might be hitting a location where we don't have IPv6 allocated and set up yet. Unfortunately, we don't have an ETA to share at the moment when this will be fully enabled all across the network but it's something we're actively working on.
> 
> Apologies for this, but please do let me know if I can be of any further assistance.

So, the answer is that it depends on the PoP you are connecting to.

If you need IPv6-only mirror, you can always use the rsync to sync the packages locally.

**Comment by ddebin** [comment]
1.5y later, Bunny CDN still does not support IPv6  from everywhere (AWS IE in my case). With AWS pushing for IPv6 only, it's a shame.

**Comment by devstuff** [comment]
And yet another year later, a new Lightsail IPv6-only instance in AWS us-west still can't connect.
