### ISSUE TITLE
php-pear : Depends: php-archive-tar (>= 1.4.9) but it is not installable

### ISSUE THREAD

**Issue by clusterx** [oerdnj/deb.sury.org#1743]
Debian 10
PHP 7.0 (PHP 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0)

I'm no longer able to install php-pear

The following packages have unmet dependencies:
 php-pear : Depends: php-archive-tar (>= 1.4.9) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by s4iya** [comment]
Can confirm, I have the same issue since this morning.

**Comment by nightw0lv** [comment]
curly braces issue in my machine
you have to rename many codes from {0} to [0]

**Comment by alec-pinson** [comment]
I think someone has fixed this now.
