### ISSUE TITLE
installing libpcre2-8-0 10.39.3 tries to remove several packages, including wine32

### ISSUE THREAD

**Issue by thomasphansen** [oerdnj/deb.sury.org#1745]
**Frequently asked questions**
- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Using your repo with Linux Mint 20.3 (based on Ubuntu 20.04).
when trying to install updates, I get a warning that updating libpcre2-8-0 to 10.39.3 will remove the several packages from my system:

The following packages will be REMOVED:
glib-networking:i386 gstreamer1.0-plugins-base:i386 gstreamer1.0-plugins-good:i386 gstreamer1.0-x:i386 libavcodec-extra58:i386 libcairo-gobject2:i386 libfaudio0:i386 libgdk-pixbuf2.0-0:i386 libglib2.0-0:i386 libgstreamer-plugins-base1.0-0:i386 libgstreamer plugins-good1.0-0:i386 libgstreamer1.0-0:i386 libgudev-1.0-0:i386 libharfbuzz0b:i386 libmount1:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386 libpcre2-8-0:i386 librsvg2-2:i386 librsvg2-common:i386 libselinux1:i386 libsoup2.4-1:i386 libwine:i386 wine32:i386

It seems this error has been around before: I found a discussion (here: https://github.com/actions/virtual-environments/issues/4589), which mentions this problem in Dec. 3, and the same discussion ends with users downgrading to Ubuntu 18.04 images in order to avoid the break, or installing version 10.34-7 from Ubuntu repos.

**To Reproduce**
On a regular ubuntu 20.04 (or ubuntu 20.04 based) installation, having wine (32 bits libraries) and ondrej repo installed:
1. sudo apt update
2. sudo apt install libpcre2-8-0

**Expected behavior**
Library upgraded, no other packages removed due to that

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04 (Linux Mint 20.3)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```bash
$ apt-cache policy libpcre2-8-0
libpcre2-8-0:
  Installed: 10.39-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 10.39-3+ubuntu20.04.1+deb.sury.org+2
  Version table:
     10.39-3+ubuntu20.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
 *** 10.39-2+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     10.34-7 500
        500 http://mirror.one.com/ubuntu focal/main amd64 Packages
```

**Comment by mpolk** [comment]
Apparently the reason is that `libpcre2-8-0:amd64` wants to upgrade to the version 10.39-3, but its 32-bit version `libpcre2-8-0:i386` still remains with the version 10.39-2. The similar mismatch (with the similar problem as a consequence) is observed for the `libxml2` package.

**Comment by mstyles** [comment]
hmm, so is the solution just to wait until the 32-bit version gets updated to 10.39-3?

**Comment by oerdnj** [comment]
No, the solution is to **not** try cram everything into a single system.

i386 is practically dead on Ubuntu side and requires exceptions for the main archive and then it just breaks in the PPA.

You can also pin libpcre2 to the official system version.

There's no universal panacea here.

**Comment by thomasphansen** [comment]
Hello, @oerdnj,
First of all, thanks for using your time on this, and for all the time you spent building your repository! :smile:

I'm not an expert in launchpad compilation, but I tried looking at the log for the i386 compilation of pcre2 (at https://launchpadlibrarian.net/593691236/buildlog_ubuntu-focal-i386.pcre2_10.39-3+ubuntu20.04.1+deb.sury.org+2_BUILDING.txt.gz), and it seems that the source for the bug is the package "debhelper":
> The following packages have unmet dependencies:
> sbuild-build-depends-main-dummy : Depends: debhelper (>= 10~) but it is not going to be installed

But isn't debhelper architecture-agnostic? So, I don't see why it fails due to architecture issues...
Also, I can see that the pcre2 package is compiling fine for Ubuntu 21.10, both on amd64 and i386 architectures - so I'm a bit confused here...

Anyway, if there is no better option, I'll follow your recommendation and pin the package. I just hope php will work fine with the pinned version... :smile:

Thanks again! :smile:

**Comment by zaltysz** [comment]
Is this related https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1965800 ?

**Comment by oerdnj** [comment]
> Is this related https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1965800 ?

Could be, but I don't depend on `debhelper-compat (= 13)` anywhere for compatibility reasons.

**Comment by mpolk** [comment]
> You can also pin libpcre2 to the official system version.

I'm afraid I can not. Unless I also remove `php8.1` and all related packages, which all depend on the custom (PPA) version of the `libpcre2`.

**Comment by mpolk** [comment]
> Anyway, if there is no better option, I'll follow your recommendation and pin the package. I just hope php will work fine with the pinned version... smile

It won't even install (at least php8.1).

**Comment by thomasphansen** [comment]
My solution (until something changes) was to pin the currently installed version (10.39-2+ubuntu20.04.1+deb.sury.org+1). This allows me to have php8.1+ installed, as it is an accepted version for the dependency.

But what still triggers me is: why does this package compile fine in Ubuntu 21.10? If this was caused by a missing 32 bits library, then no newer version of Ubuntu would compile this package as well...

**Comment by stathis** [comment]
I think there's more to it than this - something weird is going on.

On Ubuntu 20.04.4, it wants to keep back the following packages, versions align with OP:
```
libpcre2-16-0 libpcre2-32-0 libpcre2-8-0 libpcre2-dev
``` 

Trying to upgrade them by giving `apt upgrade libpcre2-16-0 libpcre2-32-0 libpcre2-8-0 libpcre2-dev` I have the following result:
```
The following packages have unmet dependencies:
 libpcre2-dev : Depends: libpcre2-posix3 (= 10.39-3+ubuntu20.04.1+deb.sury.org+2) but it is not going to be installed
```

So the solution to this for me, is to manually force the install of `libpcre2-posix3`, which removes `libpcre2-posix2` and also upgrades the aforementioned packages.

**Comment by FabianRahm** [comment]
I'm affected by the same hiatus, which is still unresolved from a user point of view.

@stathis Would you mind posting the force install command you used?

**Comment by gatons** [comment]
The same issue....

Just my opinion.... User use LTS distro. LTS means - long time using stable system. And all people, who builds some PPA, need to accept that. Some time ago i upgrade php 7.2 for debian from deb.sury.org. That was a prod system, but after upgrade i lose php7.2-mongodb module, because on repo was file, that not contain this module. Fast solution was upgrade to php7.4. 

I use this repo for many years and thanks for great work, but please - be a little more careful. Please, fix this dependency error or create some manual, how user can solve that step by step, to not spend time in bug tracker.

 Thanks.

**Comment by oerdnj** [comment]
Just do `sudo apt install libpcre2-posix3` or `apt dist-upgrade`

**Comment by gatons** [comment]
> Just do `sudo apt install libpcre2-posix3` or `apt dist-upgrade`

Thanks for answer. Yes, that solves php installation, but breaks i386 lib dependencies, because i use Crossover Office for windows apps :(

**Comment by zaltysz** [comment]
My solution was simply to LOCALLY rebuild libpcre2-8-0 and libxml2 for amd64 and i386. This provided dependencies for php and wine32.

**Comment by gatons** [comment]
> My solution was simply to LOCALLY rebuild libpcre2-8-0 and libxml2 for amd64 and i386. This provided dependencies for php and wine32.

Thanks. It helps.

**Comment by oerdnj** [comment]
>  And all people, who build some PPA, need to accept that.

No, you need to accept the fact that as long as you are using PPA, you are no longer using the LTS base system.

This is a free service and comes with no warranty. If you run a production system, you either need to do the testing yourself, or there's always the option to use paid PHP by Freexian service that's more conservative when it comes to the dependencies.

As an option, you can always build the PHP yourself.

**Comment by FabianRahm** [comment]
As an option, I just donated a few bucks and thank you for your great service. My LTS (dev only) is now in great shape again.

**Comment by dbn000** [comment]
If you have installed and then uninstall ppa package : "ppa:ondrej/php", just reinstall it.
