### ISSUE TITLE
Support for Quiche and HTTP3 for Nginx

### ISSUE THREAD

**Issue by christiantosta** [oerdnj/deb.sury.org#1746]
Provide a package for Nginx built with BoringSSL and Quiche patch, needed to enable HTTP3 protocol support.

[Quiche Github Page](https://github.com/cloudflare/quiche)
[BoringSSL Github Page](https://github.com/google/boringssl)

Recipe here:

[Experiment with HTTP/3 using NGINX and Quiche-Ubuntu](https://www.secureserverlk.com/experiment-with-http-3-using-nginx-and-quiche/)

**Comment by oerdnj** [comment]
Sorry, but not until there's official support.
