### ISSUE TITLE
error processing archive /var/cache/apt/archives/libpcre2-posix3_10.39-3+u, trying to overwrite '/usr/lib/x86_64-linux-gnu/libpcre2-posix.so.3.0.1', which is also in package libpcre2-posix2:amd64 10.39-2+ubuntu20.04.1+deb.sury.org+1

### ISSUE THREAD

**Issue by kamilrafik** [oerdnj/deb.sury.org#1747]
Upgrade of Ubuntu 20 via standard UI tool has failed. Here are the problems displayed in terminal after attempt to fix installation.  

I use several PHP versions since 7.2 till 8.1, and Russian IP address (not sure whether it is issue, but just letting you know).

Another person reported the same problem here yesterday: https://askubuntu.com/questions/1400033/libpcre2-dev-depends-libpcre2-posix3-10-39-3ubuntu20-04-1deb-sury-org1
Also, I found similar 4-month old bug report here: https://askubuntu.com/questions/1377997/the-package-system-is-broken-in-ubuntu-21-04-with-php-ppa

Further you may see output from my terminal:

owner@device:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following package was automatically installed and is no longer required:
  libpcre2-posix2
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libpcre2-posix3
The following NEW packages will be installed:
  libpcre2-posix3
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
1 not fully installed or removed.
Need to get 8 068 B of archives.
After this operation, 34,8 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libpcre2-posix3 amd64 10.39-3+ubuntu20.04.1+deb.sury.org+1 [8 068 B]
Fetched 8 068 B in 0s (20,5 kB/s)
(Reading database ... 377119 files and directories currently installed.)
Preparing to unpack .../libpcre2-posix3_10.39-3+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libpcre2-posix3:amd64 (10.39-3+ubuntu20.04.1+deb.sury.org+1) ...
dpkg: error processing archive /var/cache/apt/archives/libpcre2-posix3_10.39-3+u
buntu20.04.1+deb.sury.org+1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libpcre2-posix.so.3.0.1', which
is also in package libpcre2-posix2:amd64 10.39-2+ubuntu20.04.1+deb.sury.org+1
Errors were encountered while processing:
 /var/cache/apt/archives/libpcre2-posix3_10.39-3+ubuntu20.04.1+deb.sury.org+1_am
d64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kamilrafik** [comment]
I did not try to resolve issue by giving to apt permissions to overwrite packages (as offered by one of the links posted in issue), just because I'm not proficient in such things and I'm afraid to break the whole tree of dependencies in the system. The problem is confirmed in one more source; so, I suppose it should be resolved on the side of repository.

**Comment by kamilrafik** [comment]
Initially, I posted bug report at https://bugs.launchpad.net/ubuntu/+source/pcre2/+bug/1966855 But I suppose, this issue tracker is better location for such bug.

**Comment by oerdnj** [comment]
This 10.39-3+ubuntu20.04.1+deb.sury.org+1 is outdated version.
