### ISSUE TITLE
php7.3-xml cannot be installed - Ubuntu 18.04 or 20.04

### ISSUE THREAD

**Issue by josephcrawfordSRH** [oerdnj/deb.sury.org#1749]
**Frequently asked questions**

- [ X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
I am unable to get php7.3-xml to install using Ubuntu 18.04 and arm64 (Apple M1), the command goes through fine without error from what I see, however when i try to install xdebug it says the XML Extension Cannot Be Found.

I am running this in a dockerfile running Ubuntu 18.04, I have also tried 20.04

```
FROM --platform=linux/arm64 ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install software-properties-common -yq
RUN add-apt-repository ppa:ondrej/php

RUN apt-get update && apt-get install -yq --no-install-recommends \
    wget \
    build-essential \
    apt-utils \
    vim \
    curl \
    # Install git
    git \
    # Install apache
    apache2 \
    # Install php 7.3
    libapache2-mod-php7.3 \
    php7.3-cli \
    php7.3-json \
    php7.3-curl \
    php7.3-fpm \
    php7.3-gd \
    php7.3-ldap \
    php7.3-mbstring \
    php7.3-mysql \
    php7.3-soap \
    php7.3-sqlite3 \
    php7.3-zip \
    php7.3-intl \
    php7.3-dev \
    php7.3-xml \
    php-pear \
    php-imagick \
    # Install tools
    openssl \
    nano \
    graphicsmagick \
    imagemagick \
    ghostscript \
    mysql-client \
    iputils-ping \
    locales \
    sqlite3 \
    ca-certificates \
    make \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug
COPY /misc/laravel-local2/xdebug.ini /etc/php/7.3/mods-available
RUN phpenmod xdebug
```

The error received is
```
#11 0.302 XML Extension not found
```

I have found that if I install php-xml it will install just fine, however, it also installs PHP 8.1.4 which is not what I am trying to accomplish.

**Comment by oerdnj** [comment]
You need to do your homework first and properly debug the issue instead of pasting `Dockerfile` here. I am not going to debug your docker image.

Also you stripped all the additional questions from the bug template. Don't do that if you want help.

**Comment by josephcrawfordSRH** [comment]
I am not trying to make you do any homework for me at all, I only showed the docker file so you would see what I was trying to install when it came to the php extensions.  I have been doing my homework, everything I read states to install it like I am but after the install the extension cannot be found.

**Comment by mxdpeep** [comment]
PHP 7.3 is dead = end of life reached

Filip Oščádal 🍀📱
