### ISSUE TITLE
Imagick update to 3.7.0

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1751]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Imagick bump from 3.6.0 to 3.7.0.

**Comment by oerdnj** [comment]
Darn, looks like I've updated it only in Ubuntu 22.04, it has been uploaded to the other releases now.
