### ISSUE TITLE
Dependency PHP version from the repo and Ubuntu 18.04 !

### ISSUE THREAD

**Issue by CpServiceSpb** [oerdnj/deb.sury.org#1756]
I have Ubuntu 18.04 LTS.
There is 7.2.60 PHP version at the time om the default Ubuntu repository.
I needed version 7.4 and for that I had to add this repository because there are and 7.2 and 7.4 and 8.0 and 8.1 PHP versions.
I istalled necessary PHP modules using specified version assignment, for example: apt install php77.4 php7.4-zip and so on and installed the only version, no one others.
One day I needed to install phpMyAdmin 5.x which requested php-mysql, exact php-mysql.
But PHP of 8.1.92 version was offered to me.
I investigated the situation and found out that PHP 8.1.92 version is dependency version for Debian Sid.
But I have Ubuntu 18.04 (version before Sid) .
I tried to reassign PHP version (locally of course) by update-alternatives, but there wasn' t any result.

So, can somebody tell how is to make a default PHP version of version I need (in the case is 7.4) ?
Or may be it is repository side situation, is it ?

**Comment by oerdnj** [comment]
This is not a user support forum, sorry.

**Comment by CpServiceSpb** [comment]
The sense of my post is - can you make default PHP version regarding of default PHP version installed on asking OS ?
