### ISSUE TITLE
php8.1-mysql on ubuntu 20.04 seems buggy

### ISSUE THREAD

**Issue by samysadi** [oerdnj/deb.sury.org#1758]
The php8.1-mysql on ubuntu 20.04 is not loaded (on a fresh install).

I am getting this when starting php:
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql.so' (tried: /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: pdo_parse_params), /usr/lib/php/20210902/pdo_mysql.so.so (/usr/lib/php/20210902/pdo_mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Something is wrong with the packaged pdo_mysql.so

**Comment by oerdnj** [comment]
There's a issue template for a reason.

**Comment by samysadi** [comment]
Rude though.
Nevermind, have a great day.

**Comment by oerdnj** [comment]
No, you are the rude one here expecting me to debug your issue while not lifting a single finger to provide information I clearly ask for to help with the debugging in the first place.

**Comment by samysadi** [comment]
Alright, I am the rude one for expecting an answer like: "Can you please resubmit following the template I provided?".

Anyways, I will fill up the template when I get time.

Cheers.
