### ISSUE TITLE
Unable to install php 8.0 Debian 11

### ISSUE THREAD

**Issue by lhale78723** [oerdnj/deb.sury.org#1759]
I've been trying to install php 8.xx on but get the following error when trying to update:

Err:13 https://packages.sury.org/php elsie Release                  
  404  Not Found [IP: 156.146.53.225 443]
E: The repository 'https://packages.sury.org/php elsie Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by oerdnj** [comment]
"elsie"?

**Comment by lhale78723** [comment]
Debian 11

**Comment by lhale78723** [comment]
I'm sorry, that should be Bullseye

**Comment by lhale78723** [comment]
Please disregard. The instructions I was following are wrong.
