### ISSUE TITLE
php8.0 is not available on ubuntu jammy ondrej repository

### ISSUE THREAD

**Issue by gkia999** [oerdnj/deb.sury.org#1763]
**Frequently asked questions**

- [ ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

I'm using php8.0 and upgraded from ubuntu 20.0.4 to 22.04 and noticed
  that I removed php mbstring extension from computer and tried to
  install it using sudo apt-get install php8.0-mbstring command but I
  failed to do so because it is not available on ubuntu jammy ondrej
  repository.

**Comment by oerdnj** [comment]
Don't open duplicate issues.

**Comment by gkia999** [comment]
I tried again today, now the command works but it doesn't create apache2 files in mods-available folder I tried following commands: 
apt install php8.0 

apt install php8.0 libapache2-mod-php8.0
