### ISSUE TITLE
I can't upgrade the apache2 version to latest version by using ppa:ondrej repository.

### ISSUE THREAD

**Issue by mickymartin** [oerdnj/deb.sury.org#1764]
**I need to upgrade my apache2.4.41 to the latest version on ubuntu16.04 and 19.04 VPS**
I upgraded the apache2 version to 2.4.41 by ppa:ondrej 2 years ago.
Recently i need to upgrade it to the latest version 2.4.53.
I tried to add the ppa:ondrej/apache2 again.

sudo add-apt-repository ppa:ondrej/apache2
sudo apt update

But i can't get the latest version.
When I check the available version, it returns the always apache2.4.41.

apt-cache showpkg apache2

"
Dependencies:
2.4.41-1+ubuntu16.04.1+deb.sury.org+5 - apache2-bin (5 2.4.41-1+ubuntu16.04.1+deb.sury.org+5) apache2-data (5 2.4.41-1+ubuntu16.04.1+deb.sury.org+5) apache2-utils (5 2.4.41-1+ubuntu16.04.1+deb.sury.org+5) lsb-base (0 (null)) mime-support (0 (null)) perl (0 (null)) procps (0 (null)) init-system-helpers (2 1.18~) apache2.2-bin (0 (null)) apache2.2-common (0 (null)) libapache2-mod-proxy-uwsgi (3 2.4.33) ssl-cert (0 (null)) apache2-doc (0 (null)) apache2-suexec-pristine (16 (null)) apache2-suexec-custom (0 (null)) www-browser (0 (null)) apache2.2-bin (0 (null)) apache2.2-common (0 (null)) libapache2-mod-proxy-uwsgi (3 2.4.33)
2.4.18-2ubuntu3.17+esm5 - dpkg (2 1.17.14) lsb-base (0 (null)) procps (0 (null)) perl (0 (null)) mime-support (0 (null)) apache2-bin (5 2.4.18-2ubuntu3.17+esm5) apache2-utils (2 2.4) apache2-data (5 2.4.18-2ubuntu3.17+esm5) apache2.2-bin (0 (null)) apache2.2-common (0 (null)) ssl-cert (0 (null)) www-browser (0 (null)) apache2-doc (0 (null)) apache2-suexec-pristine (16 (null)) apache2-suexec-custom (0 (null)) ufw (0 (null)) apache2.2-bin (0 (null)) apache2.2-common (0 (null))
2.4.18-2ubuntu3.17 - dpkg (2 1.17.14) lsb-base (0 (null)) procps (0 (null)) perl (0 (null)) mime-support (0 (null)) apache2-bin (5 2.4.18-2ubuntu3.17) apache2-utils (2 2.4) apache2-data (5 2.4.18-2ubuntu3.17) apache2.2-bin (0 (null)) apache2.2-common (0 (null)) ssl-cert (0 (null)) www-browser (0 (null)) apache2-doc (0 (null)) apache2-suexec-pristine (16 (null)) apache2-suexec-custom (0 (null)) ufw (0 (null)) apache2.2-bin (0 (null)) apache2.2-common (0 (null))
2.4.18-2ubuntu3 - dpkg (2 1.17.14) lsb-base (0 (null)) procps (0 (null)) perl (0 (null)) mime-support (0 (null)) apache2-bin (5 2.4.18-2ubuntu3) apache2-utils (2 2.4) apache2-data (5 2.4.18-2ubuntu3) apache2.2-bin (0 (null)) apache2.2-common (0 (null)) ssl-cert (0 (null)) www-browser (0 (null)) apache2-doc (0 (null)) apache2-suexec-pristine (16 (null)) apache2-suexec-custom (0 (null)) ufw (0 (null)) apache2.2-bin (0 (null)) apache2.2-common (0 (null))
"

I hope someone can help me.
Thanks

**Comment by oerdnj** [comment]
> I hope someone can help me.

You are using distributions way past their respective end-of-life dates, nobody can help you here.

**Comment by mickymartin** [comment]
Thanks for your reply.
Do you mean I have to upgrade my ubuntu version to use the latest apache2 version?

**Comment by mxdpeep** [comment]
the only solution is to containerize your code into Docker and use it
inside that obsolete container, or upgrade your Ubuntu to 18.04 LTS/20.04
LTS/22.04 LTS - clean install is always a win-win situation

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*
