### ISSUE TITLE
[Ubuntu 22.04] Apache2 / Nginx packages 

### ISSUE THREAD

**Issue by jaapmarcus** [oerdnj/deb.sury.org#1765]
**Frequently asked questions**

- [ X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Are there any plans to add support for Apache2 / Nginx for Ubuntu Jammy?

https://launchpad.net/~ondrej/+archive/ubuntu/apache2/

and 

https://launchpad.net/~ondrej/+archive/ubuntu/nginx/

**To Reproduce**
N/A

**Expected behavior**

**Distribution (please complete the following information):**
 - Ubuntu Jammy 22.04
 - Both 
 
**Package(s) (please complete the following information):**
apache2 and nginx

**Additional context**

**Comment by oerdnj** [comment]
Don't open duplicate issues
