### ISSUE TITLE
Problem with libapache2-mod-php7.4 distribution on ubuntu 22.04

### ISSUE THREAD

**Issue by arcanisgk** [oerdnj/deb.sury.org#1767]
**To Reproduce**

I have a clean installation of ubuntu 22.04.

i have runing this consecutive command:

```
sudo apt install apache2

sudo ufw allow Apache

sudo reboot

sudo add-apt-repository ppa:ondrej/php

sudo apt install php7.2 libapache2-mod-php7.2 php7.2-common php7.2-sqlite3 php7.2-curl php7.2-fpm php7.2-dev php7.2-curl php7.2-xmlrpc php7.2-gd php7.2-mysql php7.2-mbstring php7.2-xml php7.2-soap php7.2-cli php7.2-zip php7.2-bz2 php7.2-dba php7.2-imap php7.2-intl php7.2-ldap php7.2-json php7.2-cli php7.2-cgi php7.2-fpm

sudo apt install php7.4 libapache2-mod-php7.4 php7.4-common php7.4-sqlite3 php7.4-curl php7.4-fpm php7.4-dev php7.4-curl php7.4-xmlrpc php7.4-gd php7.4-mysql php7.4-mbstring php7.4-xml php7.4-soap php7.4-cli php7.4-zip php7.4-bz2 php7.4-dba php7.4-imap php7.4-intl php7.4-ldap php7.4-json php7.4-cli php7.4-cgi php7.4-fpm
```

the intention was to have both versions of PHP running; version 7.2 and 7.4 since I require them on my server... but for some strange reason I get the following warning:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapache2-mod-php7.4 : Depends: php8.1-common (= 8.1.2-1ubuntu2) but 8.1.5-1+ubuntu22.04.1+deb.sury.org+1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Is there something damaged, or that has not been published?

If I manage to install php7.4 without libapache2-mod-php7.4 when trying to switch between version 7.2 and 7.4 with the command:

```
sudo a2dismod php7.2
sudo a2enmod php7.4 
```

this line gives me an error that the module does not exist... so I cannot tell apache to use one or another version of php by default.

I don't want to have to implement fpm or nginx because something is missing...

**Comment by oerdnj** [comment]
Use the issue template, answer the questions there and try again.

**Comment by arcanisgk** [comment]
@oerdnj  Let's see, I don't see the need to create or fill the entire template... it's not a programming error, it's a distribution error... there's just something missing and I don't know how to solve it; but if you've already closed my post to continue with this ... I assume you're not interested in the slightest of what I exposed ... thanks anyway and good luck.

**Comment by oerdnj** [comment]
Let's see. The template has a questions I would have to ask here again and again and again. That's why there's the template because it asks the questions I need answered before I can process further.

By not filling the template you are wasting my time and your time. And you clearly think my time comes for free since "it's open source", right?

**Comment by arcanisgk** [comment]
@oerdnj  no, not at all... you are immaturely assuming what I think... and assuming or believing something without validating it is a mistake... I am not interested in the least if this is open source or paid or not; if you need help, you can receive my limited collaboration or not, that should not determine sentimental thoughts about how they see your work ... I appreciate the time you invest in any of the ways you do it since your contribution is substantially beneficial for the entire network of PHP developers.

And so you can see that in this scenario your template doesn't add anything to the context of my question, it can even make it more difficult to understand. I'll place it right here:

<hr>


**Describe the bug**

Is there something damaged, or that has not been published?

```
The following packages have unmet dependencies:
 libapache2-mod-php7.4 : Depends: php8.1-common (= 8.1.2-1ubuntu2) but 8.1.5-1+ubuntu22.04.1+deb.sury.org+1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
**To Reproduce**


Steps to reproduce the behavior:
1. create a clean instalation of Ubuntu 22.04
2. try to install some php packeage following thes steps:

```
sudo apt install apache2

sudo ufw allow Apache

sudo reboot

sudo add-apt-repository ppa:ondrej/php

sudo apt install php7.2 libapache2-mod-php7.2 php7.2-common php7.2-sqlite3 php7.2-curl php7.2-fpm php7.2-dev php7.2-curl php7.2-xmlrpc php7.2-gd php7.2-mysql php7.2-mbstring php7.2-xml php7.2-soap php7.2-cli php7.2-zip php7.2-bz2 php7.2-dba php7.2-imap php7.2-intl php7.2-ldap php7.2-json php7.2-cli php7.2-cgi php7.2-fpm

sudo apt install php7.4 libapache2-mod-php7.4 php7.4-common php7.4-sqlite3 php7.4-curl php7.4-fpm php7.4-dev php7.4-curl php7.4-xmlrpc php7.4-gd php7.4-mysql php7.4-mbstring php7.4-xml php7.4-soap php7.4-cli php7.4-zip php7.4-bz2 php7.4-dba php7.4-imap php7.4-intl php7.4-ldap php7.4-json php7.4-cli php7.4-cgi php7.4-fpm
```

**Expected behavior**
install the packages without problem

**Distribution (please complete the following information):**
 - OS: UBUNTU 22.04
 - Architecture: x64
 - Repository: your php repository

**Package(s) (please complete the following information):**
libapache2-mod-php7.4

**Comment by oerdnj** [comment]
The template says:

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

And this is exactly the information that you stripped and would have immediately show the culprit.

That's why the template exist, because it has all the question I have been asking over and over again.

At this point you are just wasting my time that I don't really have.

**Comment by arcanisgk** [comment]
@oerdnj hoo sorry; I no longer have that data, I rolled back to the update from v22.04 to v20.04.4; as no one answered; you can't stop my developments because of something that doesn't work.

**Comment by arcanisgk** [comment]
test:

```
badas@test:~$ sudo apt-cache policy libapache2-mod-php7.4
libapache2-mod-php7.4:
  Installed: (none)
  Candidate: 8.1.2-1ubuntu2
  Version table:
     8.1.2-1ubuntu2 500
        500 http://pa.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Comment by mxdpeep** [comment]
I am simply wondering why you are still using a PHP 7.2 deprecated in 2019,
it's just an obscure question as an obscure use case.
You can always containerize your legacy 7.2 code into a Docker container
using php7.2-apache or fpm images. It works!


sincerely, yours Fred Brooker

**Comment by arcanisgk** [comment]
@mxdpeep QTI ...
