### ISSUE TITLE
Installing PHP 7.4 on Ubuntu 18.04 makes it want to install PHP 8.1 and update PHP 7.2 afterwards

### ISSUE THREAD

**Issue by anrikun** [oerdnj/deb.sury.org#1770]
**Frequently asked questions**
- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
After installing PHP 7.4, repository wants to update PHP 7.2 (that comes with Ubuntu) and install PHP 8.x

**To Reproduce**
```
add-apt-repository ppa:ondrej/php
apt update
apt install php7.4
```

**Expected behavior**
PHP 7.4 should be installed. But no other PHP versions should be installed/updated afterwards.

**Distribution**
 - OS: Ubuntu 18.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by anrikun** [comment]
My solution to prevent this behavior as (in case it helps someone):

1. Add repository as usual:
add-apt-repository ppa:ondrej/php

2. Add the following preferences
vi /etc/apc/preferences.d/PPA-ondrej-php

```
Package: *
Pin: release o=LP-PPA-ondrej-php
Pin-Priority: 90

Package: php-common libpcre2-8-0 libzip4
Pin: release o=LP-PPA-ondrej-php
Pin-Priority: 500
```

3. Update the package list:
apt update

4. Install php 7.4:
apt install php7.4

5. Install other needed php 7.4 packages:
apt install php7.4-bcmath php7.4-fpm php7.4-gd
etc.

**Comment by oerdnj** [comment]
> I have read Frequently Asked Questions

Did you? Because this is exactly described in the FAQ.

**Comment by anrikun** [comment]
I'm sorry but even after reading the FAQ several times, I don't see this behavior explicitly described.
Anyway, I only wanted to help people that might face the same issue.
