### ISSUE TITLE
Add php7.1-mongodb on Ubuntu 22.04

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1775]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Package `php7.1-mongodb` is missing on Ubuntu 22.04, for other PHP versions builds are there.

**Describe the solution you'd like**
Please add php7.1-mongodb on Ubuntu 22.04

**Describe alternatives you've considered**
Compiling the extension

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
$ apt-cache policy php7.1-mongodb
N: Unable to locate package php7.1-mongodb
N: Couldn't find any package by glob 'php7.1-mongodb'
N: Couldn't find any package by regex 'php7.1-mongodb'
```

**Comment by oerdnj** [comment]
Found it, mongodb 1.12.0 dropped support for PHP 7.1, I've re-added 1.11.1 into the bunch.
