### ISSUE TITLE
Add phalcon3 packages for PHP 5.6 to 7.3, and php7.4-phalcon4 on Ubuntu 22.04

### ISSUE THREAD

**Issue by shivammathur** [oerdnj/deb.sury.org#1776]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
`phalcon3` packages are not there on ubuntu 22.04 for PHP 5.6 to 7.3, and `php7.4-phalcon4` is missing as well. So this PR is a request to add these packages.

**Describe the solution you'd like**
Add the `phalcon3` packages for PHP 5.6 to 7.3 and `phalcon4` package for PHP 7.4 on Ubuntu 22.04.

**Describe alternatives you've considered**
Compiling the extensions

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
$ apt-cache policy php*-phalcon*
php7.3-phalcon4:
  Installed: (none)
  Candidate: 4.1.2-3+ubuntu22.04.1+deb.sury.org+1
  Version table:
     4.1.2-3+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
php-phalcon4-all-dev:
  Installed: (none)
  Candidate: 4.1.2-3+ubuntu22.04.1+deb.sury.org+1
  Version table:
     4.1.2-3+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
php-phalcon4:
  Installed: (none)
  Candidate: 4.1.2-3+ubuntu22.04.1+deb.sury.org+1
  Version table:
     4.1.2-3+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
php7.2-phalcon4:
  Installed: (none)
  Candidate: 4.1.2-3+ubuntu22.04.1+deb.sury.org+1
  Version table:
     4.1.2-3+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
php-phalcon:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Comment by mohanvishal** [comment]
Yes This is required..

**Comment by oerdnj** [comment]
I've updated the packaging and this should be done now.
