### ISSUE TITLE
Can't install php8.1 on Debian 10

### ISSUE THREAD

**Issue by mp-alexchadwick** [oerdnj/deb.sury.org#1777]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When trying to install `php8.1` apt responds saying that:

```
Package php8.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**To Reproduce**
1. Prepare a Debian 10 instance (I'm using an Azure App Service and have SSH'ed into it)
2. Log in as a superuser (i'm using root)
3. run `curl -sSL https://packages.sury.org/php/README.txt | bash -x`
4. then run `apt update`
5. then run `apt upgrade`
6. finally try `apt install php8.1`

**Expected behavior**
PHP 8.1 would install

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: `x86_64`
 - Repository: `packages.sury.org`

**Package(s) (please complete the following information):**
Output of `apt-cache policy php8.1`
```
php8.1:
  Installed: (none)
  Candidate: (none)
  Version table:
     8.1.6-1+0~20220517.17+debian10~1.gbp6b3bd1 -1
        500 https://packages.sury.org/php buster/main amd64 Packages
```

**Additional context**
-

**Comment by oerdnj** [comment]
See the `-1` in the `apt-cache policy` output. That comes from `apt` preferences file on your side.
