### ISSUE TITLE
SIGSEGV in protobuf extension when using php-fpm 8.1

### ISSUE THREAD

**Issue by radykal-com** [oerdnj/deb.sury.org#1778]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
There is a bug in php-protobuf extension for PHP8.1 when running in php-fpm. It's been solved by upstream and a new release is available:
https://github.com/protocolbuffers/protobuf/pull/9995
https://github.com/protocolbuffers/protobuf/releases/tag/v21.0

It would be nice to have a new release packaged as the last one in the repository is v19 and the latest one is v21.

Thanks you,

**Comment by oerdnj** [comment]
Updated the package to 3.21.1 and it's building now.

**Comment by radykal-com** [comment]
Thanks you!
