### ISSUE TITLE
Update from Ubuntu 14.0.4  from PHP7.0 to PHP8.1

### ISSUE THREAD

**Issue by robouden** [oerdnj/deb.sury.org#1779]
I am trying for a long time to upgrade the PHP on an Ubuntu 14.0.4 server running php7.0 with Japanese and English support, to update to php8.1. But I keep getting the following errors. Even after add the repo from oerdnj.

_root@ngeigie:~# sudo apt-get install php8.1
  Reading package lists... Done
  Building dependency tree       
  Reading state information... Done
  E: Unable to locate package php8.1
  E: Couldn't find any package by regex 'php8.1'_

If anyone has a solution please leave a reply.

Regards,
Rob Oudendijk

**Comment by sleemanj** [comment]
You would have to compile yourself, orbetter, **update your distro**!

Ubuntu 14.04 Trusty, Ubuntu 16.04 Xenial and Debian 8 Jessie are not supported in this repository.

**Comment by robouden** [comment]
@sleemanj Thanks for the reply. Any good guide for doing the compiling ?

**Comment by rfay** [comment]
[ddev](https://github.com/drud/ddev) is a docker-based local development tool that runs many versions of php, and is great for resurrecting old sites. It's easy to set up a project. Worth trying, it's great for things like you're doing. I'm the maintainer of ddev, and it uses these repositories.

**Comment by oerdnj** [comment]
There's an issue template and there's a FAQ and all of those would lead you to the right answer.

**Comment by robouden** [comment]
@oerdnj Thanks for the reply. Going through the hops and struggles to get my distro update from 14.0 to 22.04.. Takes a long time.

Regards,
Rob Oudendijk

**Comment by oerdnj** [comment]
Yes, that's best course of action.
