### ISSUE TITLE
Upgrade mailparse packages to 3.1.3

### ISSUE THREAD

**Issue by iamfoz** [oerdnj/deb.sury.org#1783]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
The latest php-mailparse version currently provided is version 3.1.2, as seen on: https://packages.sury.org/php/pool/main/p/php-mailparse/

**Describe the solution you'd like**
Add mailparse 3.1.3 packages to php-mailparse in the repo.

**Describe alternatives you've considered**
Building the package myself, which is difficult as it requires PHP with a specific set of compilation instructions and integrated modules. This also risks using the packages in production environments.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Updated, thanks.
