### ISSUE TITLE
NGINX 1.22.x

### ISSUE THREAD

**Issue by androidacy-user** [oerdnj/deb.sury.org#1786]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
NGINX in the mainline repo is still on 1.21

**Describe the solution you'd like**
NGINX 1.22 has been out since it looks like May 24. This is just a reminder more than anything else, I'm sure you have a busy life! 😄 

**Describe alternatives you've considered**
n/a

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: PPA
 
**Package(s) (please complete the following information):**
I manually checked the website

**Additional context**
n/a

**Comment by jadeops** [comment]
Please update `nginx-mainline` too (1.23.0 released 21 Jun 2022) 
OS: Debian 11 amd64 and Ubuntu 22.04 amd64

https://nginx.org/en/CHANGES

**Comment by oerdnj** [comment]
nginx 1.23.0 was a bit harded because it changed a couple of internal APIs and some modules were broken, but I think I've patched them all, so both 1.22.0 and 1.23.0 should be available shortly.
