### ISSUE TITLE
php8.1-apcu installs PHP 7.4 packages by default

### ISSUE THREAD

**Issue by stof** [oerdnj/deb.sury.org#1789]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

Installing `php8.1-apcu` brings in php 7.4 packages when `--no-install-recommends` is not used

**To Reproduce**
1. Install `php8.1-cli`
2. Then run `sudo apt-get install php8.1-apcu`
3. Look at the list of packages that would be installed, which includes PHP 7.4 packages.

Adding the `--no-install-recommends` option (which is not the default) removes that.

**Expected behavior**
As `php-apcu-bc` does not exist anymore for PHP 8+, the `php-8.0-apcu` and `php8.1-apcu` packages should not recommend it anymore.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: x86_64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
php8.1-apcu:
  Installed: 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10
  Candidate: 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10
  Version table:
 *** 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by oerdnj** [comment]
Can you please paste output of `apt-cache show php8.1-apcu`? (I'm just on a phone right now...)

**Comment by stof** [comment]
@oerdnj here it is:

```
Package: php8.1-apcu
Source: php-apcu
Priority: optional
Section: php
Installed-Size: 177
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Architecture: amd64
Version: 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10
Recommends: php-apcu-bc
Replaces: php-apcu (<< 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10~)
Suggests: php-gd
Provides: php-apcu
Depends: php8.1-common, phpapi-20210902, libc6 (>= 2.14)
Conflicts: php-xcache, php-yac
Pre-Depends: php-common (>= 2:69~)
Breaks: php-apcu (<< 5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10~)
Filename: pool/main/p/php-apcu/php8.1-apcu_5.1.21+4.0.11-7+ubuntu20.04.1+deb.sury.org+10_amd64.deb
Size: 45076
MD5sum: 4df90bb460291bc3fb23c1fd9cde115e
SHA1: b77889b220958bbed7b55b57942421fcf35f8905
SHA256: d8cb71eac74d158c285cae8752171ede344fb66554c2373af8fe9eddb656c116
Description-en: APC User Cache for PHP
 The APCu is userland caching: APC (Alternative PHP Cache) stripped of
 opcode caching after the deployment of Zend OpCache in PHP 5.5 as the
 primary solution to opcode caching in future versions of PHP.
 .
 The APCu is a fast solution for userland caching (and dumping) of PHP
 variables locally, it is not distributed like MemcacheD, but they can
 be used together for optimal caching.
Description-md5: 0d7462c8f566c71b65f0d4bcf7806445
```

**Comment by oerdnj** [comment]
Thanks, I think I do have a mechanism to use versioned recommends now. I'll look into that.0

**Comment by oerdnj** [comment]
I've dropped the `php-apcu-bc` from Recommends in the end.
