### ISSUE TITLE
Missing updates on https://packages.sury.org/php/

### ISSUE THREAD

**Issue by pesselbach** [oerdnj/deb.sury.org#1790]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Some of the updated PHP packages (5.6.40-58, 7.0.33-58, 7.1.33-45, 7.2.34-30, 7.3.33-2, 7.4.30-1) are currently not available on https://packages.sury.org/php/

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
For example: 
apt-cache policy php5.6 is still showing PHP 5.6.40-57:

php5.6:
  Installed: (none)
  Candidate: 5.6.40-57+0~20211119.60+debian10~1.gbp8a9bd1
  Version table:
     5.6.40-57+0~20211119.60+debian10~1.gbp8a9bd1 500
        500 https://packages.sury.org/php buster/main amd64 Packages

**Additional context**
Perhaps a caching issue with Cloudflare? For example, the directory listing of https://packages.sury.org/php/pool/main/p/php8.1/ is missing the PHP 8.1.7 packages but they are there.

**Comment by oerdnj** [comment]
Try now? I've purged the full pull zone (it's no longer hosted on Cloudflare, but on CDN provided by Bunny CDN)

**Comment by pesselbach** [comment]
This fixed the directory listings for the PHP 8.0/8.1 packages but the other PHP packages are still the old versions.

**Comment by pesselbach** [comment]
Thanks. The packages are now available.

**Comment by oerdnj** [comment]
FTR the build machine ran out of disk space, so the packages were not built at all. I cleaned up the Jenkins workspaces and old jobs and set more aggressive pruning.
