### ISSUE TITLE
[nginx-stable/mainline] kTLS support

### ISSUE THREAD

**Issue by SeparateReality** [oerdnj/deb.sury.org#1793]
Does any of the available packages already come with kTLS support (`--with-openssl-opt=enable-ktls`)
I could not find any information about it.

**Comment by oerdnj** [comment]
No and it's unlikely to happen. This needs a specialized hardware and if you have a specialized hardware you should probably fine tune your software for it.

**Comment by SeparateReality** [comment]
Thanks for the quick reply! I'll close the topic then.

**Comment by oerdnj** [comment]
I can probably consider this when OpenSSL in Ubuntu is compiled with kTLS, but not until then.

**Comment by JoeHorn** [comment]
Hi,

According to [this document](https://www.nginx.com/blog/improving-nginx-performance-with-kernel-tls/) , OpenSSSL & kernel requirements seem to full-filled on some versions of Ubuntu.

FYI.
