### ISSUE TITLE
phpredis 5.3.7 failed to build in Ubuntu PPA Focal

### ISSUE THREAD

**Issue by magnetik** [oerdnj/deb.sury.org#1795]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
It seems that the PECL extension phpredis 5.3.7 was supposed to be releases in the repo, but the build failed: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/23512790

**To Reproduce**
See the packages available

**Expected behavior**
See php-redis 5.3.7 available

**Distribution (please complete the following information):**

**Package(s) (please complete the following information):**
php-redis

**Additional context**

**Comment by oerdnj** [comment]
This should have been solved by a rebuild.

**Comment by magnetik** [comment]
Awesome, thanks !
