### ISSUE TITLE
Apache 2.4.18 - issues with mod_http2

### ISSUE THREAD

**Issue by vansieleghemstijn** [oerdnj/deb.sury.org#180]
After upgrading to Apache 2.4.18 on Ubuntu 14.04, I get a failing configtest with the following error: 

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/http2.load: Cannot load /usr/lib/apache2/modules/mod_http2.so into server: /usr/lib/apache2/modules/mod_http2.so: undefined symbol: nghttp2_session_change_stream_priority

After disabling mod_http2, everything starts working fine again.

**Comment by oerdnj** [comment]
What's your version of libnghttp2-14 package?

**Comment by oerdnj** [comment]
I can't reproduce this bug on trusty amd64:
```
root@lettie:/# dpkg -l libnghttp2-14 apache2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-================================================================================================================
ii  apache2                                               2.4.18-1+deb.sury.org~trusty+1  amd64                           Apache HTTP Server
ii  libnghttp2-14:amd64                                   1.5.0-1+deb.sury.org~trusty+1   amd64                           library implementing HTTP/2 protocol (shared library)
root@lettie:/# a2enmod http2
Enabling module http2.
To activate the new configuration, you need to run:
  service apache2 restart
root@lettie:/# apache2ctl configtest
Syntax OK
```

**Comment by vansieleghemstijn** [comment]
root@vansieleghem:~# dpkg -l libnghttp2-14 apache2
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                                                           Version                              Architecture                         Description
    +++-==============================================================-====================================-====================================-=================================================================================================================================
    ii  apache2                                                        2.4.18-1+deb.sury.org~trusty+1       amd64                                Apache HTTP Server
    ii  libnghttp2-14:amd64                                            1.5.0-1+deb.sury.org~trusty+1        amd64                                library implementing HTTP/2 protocol (shared library)
    root@vansieleghem:~# a2enmod http2
    Enabling module http2.
    To activate the new configuration, you need to run:
      service apache2 restart
    root@vansieleghem:~# apache2ctl configtest
    apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/http2.load: Cannot load /usr/lib/apache2/modules/mod_http2.so into server: /usr/lib/apache2/modules/mod_http2.so: undefined symbol: nghttp2_session_change_stream_priority
    Action 'configtest' failed.
    The Apache error log may have more information.
    root@vansieleghem:~# uname -a
    Linux vansieleghem.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oerdnj** [comment]
Delete your local libnghttp2 library from `/usr/local`, you are linking the module to the old library you self installed, the linking should look like this:
```
ldd /usr/lib/apache2/modules/mod_http2.so
	linux-vdso.so.1 =>  (0x00007ffdc58d7000)
	/usr/lib/cowdancer/libcowdancer.so (0x00007f6350574000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f635034e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f635012f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f634fd6a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f634fb66000)
	/lib64/ld-linux-x86-64.so.2 (0x00005565d1509000)
```

**Comment by vansieleghemstijn** [comment]
Thanks, working perfectly now. I've sent a tip for the trouble.
