### ISSUE TITLE
[Debian] Apt no longer recognises PGP key since its moved to /usr/share/keyrings/deb.sury.org-php.gpg

### ISSUE THREAD

**Issue by AdamReece-WebBox** [oerdnj/deb.sury.org#1802]
Morning,

Since the PGP key for the Debian repository (packages.sury.org) has moved to "/usr/share/keyrings/deb.sury.org-php.gpg" it no longer seems to be recognised. This is for Debian Buster on amd64.

I've re-run the installer script and removed the old key from "/etc/apt/trusted.gpg.d/php.gpg" but get the usual rejection from Apt:
```
W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

The PGP key is definitely at the new location:
```
# sha256sum /usr/share/keyrings/deb.sury.org-php.gpg
b3ea944563435e54bb64f181ee8bc26200985d09164cdc4c1702fc3ef051f19d  /usr/share/keyrings/deb.sury.org-php.gpg

# gpg -v /usr/share/keyrings/deb.sury.org-php.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa3072 2019-03-18 [SC] [expires: 2024-02-16]
      15058500A0235D97F5D10063B188E2B695BD4743
uid           DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sig        B188E2B695BD4743 2021-02-16   [selfsig]
sub   rsa3072 2019-03-18 [E] [expires: 2024-02-16]
sig        B188E2B695BD4743 2021-02-16   [keybind]
```

The Apt sources file also definitely refers to it:
```
# cat /etc/apt/sources.list.d/php.list
deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ bullseye main
```

**Comment by AdamReece-WebBox** [comment]
Found the problem moments later. It looks like when the installer script obtains the PGP key via Curl the permissions become `0660`:

```
# ls -al /usr/share/keyrings/deb.sury.org-php.gpg
-rw-rw---- 1 root root 1769 Jul  1 08:29 /usr/share/keyrings/deb.sury.org-php.gpg
```

Changing that to `0644` resolved the problem. Unsure why though, I'm 100% running apt commands elevated as expected. The installer script probably just needs an addition before doing an apt update:

```
chmod 0644 /usr/share/keyrings/deb.sury.org-php.gpg
```

**Comment by oerdnj** [comment]
What's your `umask` settings?

**Comment by oerdnj** [comment]
And more specifically, did you change the default `umask`?

**Comment by AdamReece-WebBox** [comment]
`0027`
(Not something I've set intentionally.)

**Comment by oerdnj** [comment]
That's weird, because I think the default `umask` is `0022`: https://wiki.debian.org/Permissions#The_defaults_for_new_files_and_directories

**Comment by AdamReece-WebBox** [comment]
Interesting. I'll check PAM further. Making a test file came up with `0640`:
```
# touch testfile ; stat testfile ; rm testfile
  File: testfile
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fe01h/65025d    Inode: 3146017     Links: 1
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-07-01 08:48:39.903343837 +0100
Modify: 2022-07-01 08:48:39.903343837 +0100
Change: 2022-07-01 08:48:39.903343837 +0100
 Birth: -
```

**Comment by oerdnj** [comment]
All root accounts on all my Debian systems have `umask 0022`, so this is something you must have configured yourself when you installed or configured the server.

Still, it's good to know that the permissions on the keyfile could be a problem.
