### ISSUE TITLE
Adding bookworm

### ISSUE THREAD

**Issue by Justman10000** [oerdnj/deb.sury.org#1804]
You know it, bookworm has been released! But if you try the following:

deb [signed-by=/usr/share/keyrings/php-archive-keyring.gpg] https://packages.sury.org/php/ bookworm main

comes only this:

Fehl:9 https://packages.sury.org/php bookworm Release
  404  Not Found [IP: 138.199.37.226 443]

It's because bookworm doesn't exist for PHP yet:

![grafik](https://user-images.githubusercontent.com/49990629/178115406-305d6760-9280-4ea8-be49-2101862ea89c.png)

@oerdnj

Could you add it?

**Comment by oerdnj** [comment]
> You know it, bookworm has been released!

No, it hasn't been.

**Comment by Justman10000** [comment]
> > You know it, bookworm has been released!
> 
> No, it hasn't been.

Like mine?

**Comment by sleemanj** [comment]
> > > You know it, bookworm has been released!
> > 
> > 
> > No, it hasn't been.
> 
> Like mine?

Bookworm is still in testing, it has not been released.

https://wiki.debian.org/DebianReleases

Testing releases are outside the scope of Ondřej's packaging (see FAQ).
