### ISSUE TITLE
libgd 2.3.3 no longer defines `GD_FLIP_*` constants

### ISSUE THREAD

**Issue by anomiex** [oerdnj/deb.sury.org#1805]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
In v2.3.3, libgd [has removed](https://github.com/libgd/libgd/commit/bdc281eadb1d58d5c0c7bbc1125ee4674256df08) the constants `GD_FLIP_HORIZONTAL`, `GD_FLIP_VERTICAL`, and `GD_FLIP_BOTH`. [A patch](https://github.com/php/php-src/commit/b3646440b1808abf0874b6f89027ce53ec5da03f) was merged into PHP 8.1 to account for this, but does not appear to have been backported to 8.0 or earlier.

Thus, builds fail with errors like `.../php8.0-8.0.20/ext/gd/gd.c:353:55: error: ‘GD_FLIP_HORIZONTAL’ undeclared (first use in this function)`.

**To Reproduce**
1. Install libgd v2.3.3
2. Attempt to compile PHP 8.0 or earlier from sources.

**Expected behavior**
Compilation succeeds.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
n/a

**Additional context**
Backporting [that php8.1 patch](https://github.com/php/php-src/commit/b3646440b1808abf0874b6f89027ce53ec5da03f) allows it to compile.

**Comment by oerdnj** [comment]
Thanks for the patch. I will look into that with the next update.

**Comment by oerdnj** [comment]
I did put back the constants into libgd headers. It's much easier that way than to patch 7 PHP major releases.
