### ISSUE TITLE
Cannot install libxml2:i386

### ISSUE THREAD

**Issue by Maxwell175** [oerdnj/deb.sury.org#1806]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When trying to install the i386 version of libxml2, it conflicts with the x64 version.

**To Reproduce**

`sudo apt install libxml2:i386`

https://gist.github.com/Maxwell175/c87d26fc94d45a129649252b081434ae

**Expected behavior**
The install should complete as expected

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
```
maxwell@Maxwell-Ubu-Main:~/StockSharp-main$ apt-cache policy libxml2
libxml2:
  Installed: 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1
  Candidate: 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.10+dfsg-5ubuntu0.20.04.3 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.9.10+dfsg-5 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
maxwell@Maxwell-Ubu-Main:~/StockSharp-main$ apt-cache policy libxml2:i386
libxml2:i386:
  Installed: (none)
  Candidate: 2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1
  Version table:
     2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main i386 Packages
     2.9.10+dfsg-5ubuntu0.20.04.3 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages
     2.9.10+dfsg-5 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main i386 Packages
```

**Additional context**

Perhaps similar to #1394

**Comment by oerdnj** [comment]
It’s same as https://github.com/oerdnj/deb.sury.org/issues/1745

Until Ubuntu fixes this, you basically have to either build libxml2:i386 yourself or pin the version to the version in the base distribution. There’s nothing I can do on my side.
