### ISSUE TITLE
package hardlink stops working with libpcre2-posix package from your repo on debian 11

### ISSUE THREAD

**Issue by Elkropac** [oerdnj/deb.sury.org#1808]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

When i upgrade `libpcre2-posix` package to the one from your repository, utility `hardlink` stops to work, because your package contains file `/usr/lib/x86_64-linux-gnu/libpcre2-posix.so.3` and not `/usr/lib/x86_64-linux-gnu/libpcre2-posix.so.2`.

Shouldn't it be named differently so it can be co-installed with original `libpcre2-posix` package?

**To Reproduce**
1. upgrade `libpcre2-posix2` to version from your repository
2. install package `hardlink` and start it
3. See error `hardlink: error while loading shared libraries: libpcre2-posix.so.2: cannot open shared object file: No such file or directory`

**Expected behavior**
No error

**Distribution (please complete the following information):**
 - OS: Debian 11.4
 - Architecture: amd64
 - Repository: debian repositories and packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best. - is that needed?

**Additional context**

**Comment by oerdnj** [comment]
> Output of apt-cache policy <package> works best. - is that needed?

Yes, it allows to see what version is installed and what versions are available and from where.

**Comment by Elkropac** [comment]
```
# apt-cache policy hardlink
hardlink:
  Installed: 0.3.2+b1
  Candidate: 0.3.2+b1
  Version table:
 *** 0.3.2+b1 500
        500 http://ftp.cz.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
# apt-cache policy libpcre2-posix2
libpcre2-posix2:
  Installed: 10.39-2+0~20211122.14+debian11~1.gbp0d570b
  Candidate: 10.39-2+0~20211122.14+debian11~1.gbp0d570b
  Version table:
 *** 10.39-2+0~20211122.14+debian11~1.gbp0d570b 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     10.36-2 500
        500 http://ftp.cz.debian.org/debian bullseye/main amd64 Packages
```

I have just checked reverse dependencies of `libpcre2-posix2` and there are just two packages depending on it, so i don't know if it's worth solving this. I will try to rebuild `hardlink` with your `libpcre2-dev` to see if it works

**Comment by oerdnj** [comment]
Thanks, it does seem to need the package name change to accommodate for the soname bump.

**Comment by oerdnj** [comment]
Looks like I already have fixed this, but forgot to rebuild the package. Should be all good now.

**Comment by Elkropac** [comment]
Great, thanks. Will you eventually remove libpcre2-posix2 from repository, so it won't get pulled in by upgrade again?

**Comment by oerdnj** [comment]
> Will you eventually remove libpcre2-posix2 from repository, so it won't get pulled in by upgrade again?

Hmm, I don't know why `reprepro` kept these. I manually removed them, so they should be gone in few moments.
