### ISSUE TITLE
[php-7.0] request for xmlrpc

### ISSUE THREAD

**Issue by thsteinmetz** [oerdnj/deb.sury.org#181]
Request to have xmlprc added to the ppa.

http://php.net/manual/en/xmlrpc.installation.php

**Comment by thsteinmetz** [comment]
It seems it works out of the box when compiled, as seen here: https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog

**Comment by oerdnj** [comment]
I remember now - building with external XMLRPC-EPI library fails. I'll look into that when I have time.

**Comment by oerdnj** [comment]
Fixed in 7.0.1-1+deb.sury.org~*+1, needed Build-Conflict with different xmlrpc library and patch to link with -lxmlrpc-epi
