### ISSUE TITLE
Site Debian DPA not available

### ISSUE THREAD

**Issue by aandaradev** [oerdnj/deb.sury.org#1810]
**Describe the bug**
The site https://packages.sury.org is not available so it is impossible to get updates.

**Distribution (please complete the following information):**
 - OS:Debian
 - Architecture: amd64
 - Repository:  packages.sury.org

**Comment by oerdnj** [comment]
> The site https://packages.sury.org is not available so it is impossible to get updates.

It is available. If you want help you need to be specific.

**Comment by aandaradev** [comment]
When trying to access the site it shows the following problem:

![Screenshot_20220718_093912](https://user-images.githubusercontent.com/14893370/179524307-3ee5628c-df8a-47ce-81d4-d3dbe2f688be.png)

**Comment by oerdnj** [comment]
That's a local problem. You need to talk to your ISP.

**Comment by aandaradev** [comment]
Ah ok thanks
