### ISSUE TITLE
Update to nginx 1.23.1 

### ISSUE THREAD

**Issue by asrob** [oerdnj/deb.sury.org#1814]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
NGINX in the mainline repo is on 1.23.0.

**Describe the solution you'd like**
Update to the 1.23.1

**Describe alternatives you've considered**
n/a

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA (https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline)

**Package(s) (please complete the following information):**
- nginx

I've checked on the website manually. (https://nginx.org/en/CHANGES)

**Additional context**
n/a

**Comment by oerdnj** [comment]
Done, building now...
