### ISSUE TITLE
PHP5.6 / PHP7.4 SSL EOF error on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Dankitymao** [oerdnj/deb.sury.org#1817]
**Frequently asked questions**

- [X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
As per https://github.com/oerdnj/deb.sury.org/issues/1761 I see that a patch was implemented to allow PHP earlier than 8 to build on OpenSSL 3.0.0+ as currently ships with Ubuntu 22.04 LTS.  I am, however, encountering a potentially related issue when attempting to use PHP functions which read from an HTTPS stream (file_get_contents with an HTTPS URL for example); attempting this in either PHP 7.4 or 5.6 results in:

_PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading in /home/me/ssltest.php on line 3_

Test file used to generate this error on demand:
```
<?php
  $recaptcha_url = 'https://www.google.com/recaptcha/api/siteverify';
  file_get_contents($recaptcha_url);
?>

```
Package versions installed:
libssl3 3.0.2-0ubuntu1.6
PHP 7.4 packages 7.4.30-3+ubuntu22.04.1+deb.sury.org+1
PHP 5.6 packages 5.6.40-60+ubuntu22.04.1+deb.sury.org+1
On Ubuntu 22.04 LTS
No changes made to php.ini for any version for these tests

This test completes successfully on PHP 8.1 (packages version 8.1.8-1+ubuntu22.04.1+deb.sury.org+1)

I did find some information at https://github.com/owncloud/docs-server/issues/252 regarding an attempt to re-install libssl 1.1.1, but this did not appear to resolve my issue so I backed this change out and forcibly reinstalled libssl3 just to make sure.  

PHP8's fixed issue for what this appears to be: https://bugs.php.net/bug.php?id=79589 (the patch looks to add an option to ignore unexpected EOFs essentially: https://bugs.php.net/patch-display.php?bug_id=79589&patch=openssl-ignore-eof.patch&revision=latest ).

Or perhaps I've just missed something in configuration and I'm an idiot, hah!

**To Reproduce**
1. Install libssl3 and PHP 7 or 5 (apt install libssl3 php7.4 php5.6)
2. Create test file ssltest.php with contents:
```
  <?php
    $recaptcha_url = 'https://www.google.com/recaptcha/api/siteverify';
    file_get_contents($recaptcha_url);
  ?>
```
3. Execute test file with "php7.4 ./ssltest.php" or "php5.6 ./ssltest.php"
4. Get error response: _PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading in /home/me/ssltest.php on line 3_
  
**Expected behavior**
No output at all should be generated since nothing is done with the result of file_get_contents; PHP should exit cleanly and does so with PHP8.1.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04LTS
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
libssl3:
  Installed: 3.0.2-0ubuntu1.6
  Candidate: 3.0.2-0ubuntu1.6
  Version table:
 *** 3.0.2-0ubuntu1.6 500
        500 http://mirrors.linode.com/ubuntu jammy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.2-0ubuntu1 500
        500 http://mirrors.linode.com/ubuntu jammy/main amd64 Packages

php7.4:
  Installed: 1:7.4.30-3+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1:7.4.30-3+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1:7.4.30-3+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

php5.6:
  Installed: 5.6.40-60+ubuntu22.04.1+deb.sury.org+1
  Candidate: 5.6.40-60+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 5.6.40-60+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

php8.1:
  Installed: 8.1.8-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 8.1.8-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 8.1.8-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     8.1.2-1ubuntu2.2 500
        500 http://mirrors.linode.com/ubuntu jammy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
     8.1.2-1ubuntu2 500
        500 http://mirrors.linode.com/ubuntu jammy/main amd64 Packages

**Comment by oerdnj** [comment]
I'll look into backporting that upstream patch. It looks simple enough. Thanks for the pointer.

**Comment by Dankitymao** [comment]
Thank you!  Let me know if I can be of any assistance in testing or providing further information.

**Comment by pieterza** [comment]
Thanks @oerdnj , hope you do!

**Comment by pieterza** [comment]
FYI, Ubuntu has deprecated their non-lts repo's

```
[2022-07-31T08:40:03.656Z] E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
[2022-07-31T08:40:03.656Z] E: The repository 'http://archive.ubuntu.com/ubuntu impish Release' does not have a Release file.
[2022-07-31T08:40:03.656Z] E: The repository 'http://archive.ubuntu.com/ubuntu impish-updates Release' does not have a Release file.
[2022-07-31T08:40:03.656Z] E: The repository 'http://archive.ubuntu.com/ubuntu impish-backports Release' does not have a Release file.
```

As such we need to either move to Jammy, which is blocked by this bug, or regress back to 20.04.

We'd really appreciate you having a look!

**Comment by Dankitymao** [comment]
@pieterza He hasn't had a chance to update this issue yet in the tracker, but it does look like there are new PHP packages in the repos for Jammy which implement this fix.  Some quick testing shows it works as well :)

**Comment by oerdnj** [comment]
Yeah, I just need to double check if I successfully uploaded all versions, but the issue has been patched.

**Comment by pieterza** [comment]
Ah awesome, thank you very much!  I'll test shortly.

**Comment by pieterza** [comment]
Fix confirmed, thanks again! 🥇

**Comment by oerdnj** [comment]
This has been done to all versions where I backported OpenSSL 3.0.0 support.

**Comment by rastapopougros** [comment]
Mmh that's strange, cause I have the PPA https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ "jammy" … and my version for PHP 7.4 is "1:7.4.33-1+ubuntu22.04.1+deb.sury.org+1" from there… and I still have this error `SSL operation failed with code 1. OpenSSL Error messages` etc (on Ubuntu 22.04 so)

**Comment by rastapopougros** [comment]
Even more strange, even with the PHP8.1 mod activated, I still have the same error message `SSL operation failed with code 1. OpenSSL Error messages: error:0A000152:SSL routines::unsafe legacy renegotiation disabled` and `Warning: fsockopen(): Failed to enable crypto` (always with same Ubuntu 22 en openssl 3)

**Comment by oerdnj** [comment]
No, you don’t. That’s completely different problem. The cause is even stated in the message you posted.
