### ISSUE TITLE
Backport openssl3 compatibility to 8.0

### ISSUE THREAD

**Issue by pieterza** [oerdnj/deb.sury.org#1818]
**Describe the bug**

PHP 8.0 is not meant to compile against OpenSSL 3.0, yet the Ubuntu Jammy 8.0 PHP PPA works with OpenSSL 3 shipped with the system.

"Works", until you try the following:

```
php -r "echo file_get_contents('https://chromedriver.storage.googleapis.com/LATEST_RELEASE', false, stream_context_create());"
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading in Command line code on line 1
PHP Warning:  file_get_contents(): SSL: Success in Command line code on line 1
```

This exact thing was hacked and patched to 8.1, but PHP developers refused to port to 8.0.

Could you please port this fix to your 8.0 branch:

https://github.com/php/php-src/pull/8558/files

Looks like it's literally just this:

```
#ifdef SSL_OP_IGNORE_UNEXPECTED_EOF
	/* Only for OpenSSL 3+ to keep OpenSSL 1.1.1 behavior */
	ssl_ctx_options |= SSL_OP_IGNORE_UNEXPECTED_EOF;
#endif
```

(I tried finding your PHP 8.0 repo, to PR it myself, and will keep looking but maybe this gets to you first.)

To reproduce, run that PHP command above, to confirm fix...output should be like:

```
pieters@STN:~$ php -r "echo file_get_contents('https://chromedriver.storage.googleapis.com/LATEST_RELEASE', false, stream_context_create());"
103.0.5060.134p
```

**Comment by oerdnj** [comment]
Next time, could you just take a look at the existing issues to not open duplicates?
