### ISSUE TITLE
PHP7.4 Reload not working 

### ISSUE THREAD

**Issue by sidenkoaleksandr** [oerdnj/deb.sury.org#1819]
**Frequently asked questions**

- [yes ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Reload not working on version PHP 7.4.30 (cli) (built: Jun 27 2022 08:14:10) ( NTS ) 

**To Reproduce**
I see problem on version PHP 7.4.30 (cli) (built: Jun 27 2022 08:14:10) ( NTS )
I`m doing on version PHP 7.4.30 (cli) (built: Jun 27 2022 08:14:10) ( NTS )
/etc/init.d/php7.4-fpm reload
Nginx return 404 error for my clients. 

I checked on another server, server have a version of php is PHP 7.4.30 (cli) (built: Jul  7 2022 15:51:43) ( NTS ) I don't see any problems with reload.

**Expected behavior**
When I doing  /etc/init.d/php7.4-fpm reload, php will start new process before closed older.

**Distribution (please complete the following information):**
 - Debian
 - Architecture: Linux app1 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php7.4-fpm:
  Installed: 1:7.4.30-3+0~20220627.69+debian11~1.gbpf2b381
  Candidate: 1:7.4.30-3+0~20220627.69+debian11~1.gbpf2b381
  Version table:
 *** 1:7.4.30-3+0~20220627.69+debian11~1.gbpf2b381 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     7.4.30-1+deb11u1 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
     7.4.28-1+deb11u1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages

**Additional context**

**Comment by oerdnj** [comment]
The report doesn't have enough information to actually do anything.
