### ISSUE TITLE
Update PHP 8.2 package with release candidate

### ISSUE THREAD

**Issue by gvollant** [oerdnj/deb.sury.org#1828]
Last year, I wrote at https://github.com/oerdnj/deb.sury.org/issues/1439#issuecomment-917411055

> PHP 8.1 release candidate is here.
> 
> the PHP_API_VERSION constant (in php.h) changed from 20201009 (in beta) to 20210902 (in release candidate). Based on previous PHP version, I suppose the PHP_API_VERSION value from RC is the final value.
> 
> php extension binary build againt current PHP 8.1 package (beta) will be incompatible with PHP 8.1 RC and final.
> 
> So, if this is possible for you, oerdnj , I think it'll be useful if you can update your package to RC. So we will start produce binary without compatibility problem.
> 
> regards, and thank you for the work!

So  @oerdnj , I suggest upgrading package to PHP 8.2 release candidate without waiting the PHP 8.1.11 date.
Like last year !

**Comment by gvollant** [comment]
It was done today. Thank you!

**Comment by gvollant** [comment]
PHP 8.3 RC is planned August 31, 2023 @oerdnj

**Comment by rfay** [comment]
Better and more recent:
* https://github.com/oerdnj/deb.sury.org/issues/2002
