### ISSUE TITLE
Build failures for php-lz4 for php 8.1 + Ubuntu 22.04

### ISSUE THREAD

**Issue by Xon** [oerdnj/deb.sury.org#1830]
The php-lz4 package for php 8.1 + Ubuntu 22.04 is missing, due to what appear to be build failures:

https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=lz4&field.status_filter=published&field.series_filter=

https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/23563949/+files/buildlog_ubuntu-jammy-amd64.php-lz4_0.4.3-4+ubuntu22.04.1+deb.sury.org+1_BUILDING.txt.gz

**Comment by oerdnj** [comment]
This has been fixed now.
