### ISSUE TITLE
Adding PPA repository to Ubuntu LTS 22.04 seems to break https method of apt

### ISSUE THREAD

**Issue by Anckermann** [oerdnj/deb.sury.org#1833]
- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

I don't know if this is already a known issue, but I couldn't find anything about it.
I'm trying to install php 5.6 on a fresh (and updated) instance of Ubuntu LTS 22.04 server with apache2. When I'm adding the ppa repository with `LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php` I get the following output:
```Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ondrej-ubuntu-php.gpg with fingerprint 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
```
After this all operations on apt seem to be broken:

```
# apt update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
```

To return to normal operating conditions I have to to execute `add-apt-repository  -r  ppa:ondrej/php`

Note that I tried `ppa:ondrej/apache2`  too, but with the same results. All commands are executed with root privileges.

Am I missing something here? I've tried the same exact installation but on Ubuntu LTS 20.04 and it works just fine.

**Comment by oerdnj** [comment]
This is unrelated to this repository. Your system is broken, and you stripped all the other questions from the template, so I can’t help you.

**Comment by Anckermann** [comment]
The system is not broken. I however asked on askubuntu on [this thread](https://askubuntu.com/questions/1429453/adding-ppa-repository-to-ubuntu-lts-22-04-seems-to-break-https-method-of-apt).
If anyone happens to have a similar problem and you're running your Ubuntu LTS 22.04 on ESXi, consider appending to `.bashrc` the line `export GNUTLS_CPUID_OVERRIDE=0x1` and reboot the system. Afterwards run a `sudo apt update && sudo apt full-upgrade` and then you can install PPAs without issues.

**Comment by soroka777** [comment]
The following security updates require Ubuntu Pro with 'esm-infra' enabled:
  screen libpython3.6-minimal libnghttp2-14 libisccfg160 vim-common libcurl4
  libldap-2.4-2 openssl python2.7-minimal libpam-cap libpython3.6-stdlib
  libelf1 libirs160 bind9-host open-iscsi dnsutils python2.7 libpython3.6
  python3.6 linux-headers-aws open-vm-tools openssh-sftp-server libyajl2 gawk
  libisc169 linux-aws libx11-6 python3-requests libapparmor1 python3.6-minimal
  libtiff5 libisc-export169 busybox-static libcap2 libcap2-bin libldap-common
  liblwres160 vim-runtime linux-image-aws vim xxd openssh-server libx11-data
  openssh-client libdns-export1100 libpython2.7-minimal vim-tiny apparmor
  libisccc160 libssl1.1 libbind9-160 libdns1100 libpython2.7-stdlib curl
  libcurl3-gnutls busybox-initramfs
Learn more about Ubuntu Pro for 18.04 at https://ubuntu.com/18-04
