### ISSUE TITLE
php8.1-memcached should have version 3.2.0 not 3.1.5 on arm64 (Debian)

### ISSUE THREAD

**Issue by etremblay** [oerdnj/deb.sury.org#1834]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**

PHP 8.1 require the version 3.2.0 of the memcached extension.

The package php8.1-memcached on amd64 have the good version but the arm64 package have 3.1.5

This may be related to https://github.com/oerdnj/deb.sury.org/issues/1683

**Expected behavior**

php8.1-memcached should be at 3.2.0 on arm64 also.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: arm64

**Package(s) (please complete the following information):**

*amd64*
```
php8.1-memcached:
  Installed: 3.2.0+2.2.0-1+0~20220421.38+debian10~1.gbp96ecac
  Candidate: 3.2.0+2.2.0-1+0~20220421.38+debian10~1.gbp96ecac
  Version table:
 *** 3.2.0+2.2.0-1+0~20220421.38+debian10~1.gbp96ecac 100
        100 /var/lib/dpkg/status
```

*arm64*
```
php8.1-memcached:
  Installed: 3.1.5+2.2.0-10+0~20211120.36+debian10~1.gbp3d83cf
  Candidate: 3.1.5+2.2.0-10+0~20211120.36+debian10~1.gbp3d83cf
  Version table:
 *** 3.1.5+2.2.0-10+0~20211120.36+debian10~1.gbp3d83cf 100
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
This should be ok after the last update.
