### ISSUE TITLE
Please add provide:php-mysql to php7.4-mysql package (and likely other versions)

### ISSUE THREAD

**Issue by bigwillystyle42** [oerdnj/deb.sury.org#1836]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
php-mysql dependency leads to php8.1 packages being installed on a Debian php7.4 setup.

[Cacti](https://packages.debian.org/buster/cacti) in Buster depends on php-mysql (in Stretch it was php-mysql | php-mysqlnd, which worked fine)

**Describe the solution you'd like**
php7.4-mysql should provide php-mysql

**Describe alternatives you've considered**
Repackage cacti for our use, or use equivs to create a package providing the php-mysql package.

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
apt-cache policy php-mysql
php-mysql:
  Installed: (none)
  Candidate: 2:8.1+92+0~20220117.43+debian10~1.gbpe0d14e
  Version table:
     2:8.1+92+0~20220117.43+debian10~1.gbpe0d14e 500
        500 https://packages.sury.org/php buster/main amd64 Packages
     2:7.3+69 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
```

**Additional context**
Liberally copied from request #1791

**Comment by oerdnj** [comment]
No, that’s wrong. mysql extension was removed from PHP 7.4.

**Comment by bigwillystyle42** [comment]
Okay. Then is this a bug in the Cacti packaging? It should depend on php-mysqlnd instead of php-mysql?

**Comment by oerdnj** [comment]
Yes, it should depend on the extension that it actually uses, not a catchall package name, it could be php-mysqli, php-mysqlnd, or php-pdo-mysql, I don’t know which one does cacti use.
