### ISSUE TITLE
[Feature Request] Add Naxsi Module For Nginx PPA

### ISSUE THREAD

**Issue by nausixkiz** [oerdnj/deb.sury.org#1837]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like have  ```ppa:ondrej/nginx-mainline``` compile with [wargio/naxsi](https://github.com/wargio/naxsi). Because of the original project of Naxsi [nbs-system/naxsi](https://github.com/nbs-system/naxsi) is (unofficially) abandoned.

**Describe alternatives you've considered**
I have found the repo of Naxsi is still being maintained. I tried compiling and loading this module into the Nginx official packages. It worked great. So, I hope it will be integrated into our PPA instead of having to build it manually.
Dullicate with [#1604](https://github.com/oerdnj/deb.sury.org/issues/1604)

**Distribution (please complete the following information):**
 - OS: ```Ubuntu Jammy```
 - Architecture: ```x86_64```
 - Repository: ```ppa:ondrej/nginx-mainline```

**Comment by oerdnj** [comment]
So, why did you open a duplicate issue instead of just adding a comment?
