### ISSUE TITLE
PHP8.2 Support

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1840]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

Thank you so much for the early php8.2.0-RC1, it's doing great for me/ddev on Debian 11 on both amd64 and arm64.

I'd just like to put the request in for these extensions as they become possible:
- [ ] apcu 
- [ ] imagick 
- [ ] memcached 
- [ ] redis 
- [ ] uploadprogress 
- [ ] xdebug 
- [ ] xhprof 
- [ ] xmlrpc

I'm a little surprised by xdebug being missing, for example, as I thought that was in good enough shape already.

As always, thanks so much for this amazing resource.

**Comment by ankurk91** [comment]
php8.2-redis is missing

**Comment by simPod** [comment]
\+php8.2-pcov

**Comment by michelv** [comment]
Seconded for pcov and ds! I'd like to ask for `php8.2-uuid` too, please!

**Comment by rfay** [comment]
@oerdnj I see php 8.2.0 [arriving already](https://jenkins.rfc1925.org/view/PHP/job/php_php8.2-binaries/9/) thanks!. 

I was delaying a DDEV release for php 8.2.0, but was hoping to get at least some of these extensions in, but will go ahead if they're not likely to arrive in the near term. 

As always, thanks for maintaining this essential and amazing project.

**Comment by oerdnj** [comment]
I’ll start building the extensions in coming days.

**Comment by rfay** [comment]
Thanks so much.

**Comment by neoteknic** [comment]
You can install it with pecl, no problem for igbinary + redis

**Comment by jmsche** [comment]
Hi oerdnj,

Thanks for all the great work :) 

Could you also please add igbinary & msgpack extensions?

Thanks!

**Comment by oerdnj** [comment]
I'll add all available extensions if they compiled; no need to list them individually.

**Comment by oerdnj** [comment]
Ok, now I am waiting for the dust to settle.

**Comment by caiofior** [comment]
Is mongodb extension avalilable?

**Comment by onlime** [comment]
Thanks @oerdnj for your tremendous support, for all your work, for publishing all those packages so fast! 🚀🙏❤️

**Comment by oerdnj** [comment]
I think I'm done here. I've also managed to fix couple of unrelated bugs in some extensions along the way. There might be some Debian extensions not yet built, but please don't fill new issue until mid next week, so I have time to polish the rough edges.

I've also uploaded PHP 8.2 and extensions to Debian experimental to prepare for PHP 8.2 transition in unstable.  Thus the next Debian stable will have PHP 8.2.

**Comment by rfay** [comment]
Thanks so much!

**Comment by dshoreman** [comment]
Hi @oerdnj, thanks for your continued dedication to the cause over the years.

> I've also uploaded PHP 8.2 and extensions to Debian experimental

I see [php8.2-pcov][1] made it to Debian experimental as `1.0.11-5`, but [the PPA][2] is still on `1.0.11-4`. Is pcov one of the rough edges that needed a bit more time by any chance?

[1]: https://packages.debian.org/experimental/php8.2-pcov
[2]: https://launchpad.net/~ondrej/+archive/ubuntu/php/+sourcepub/13208930/+listing-archive-extra

**Comment by oerdnj** [comment]
> I see [php8.2-pcov](https://packages.debian.org/experimental/php8.2-pcov) made it to Debian experimental as 1.0.11-5, but [the PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php/+sourcepub/13208930/+listing-archive-extra) is still on 1.0.11-4. Is pcov one of the rough edges that needed a bit more time by any chance?

Nope, that's just some stuff needed for upload to Debian experimental.

**Comment by madman-81** [comment]
Could it be that PHP8.2 was 'automatically' installed on my server with regular updates? I found out today that my server has php 8.2 installed and it couldn't have been installed manually by anyone, since there was no one logged in at that time. Any ideas?

**Comment by killerbees19** [comment]
@madman-81 Sure, there are various meta packages. :-)

```
libapache2-mod-php - server-side, HTML-embedded scripting language (Apache 2 module) (default)
libphp-embed       - HTML-embedded scripting language (Embedded SAPI library) (default)
php                - server-side, HTML-embedded scripting language (default)
php-cgi            - server-side, HTML-embedded scripting language (CGI binary) (default)
php-cli            - command-line interpreter for the PHP scripting language (default)
php-dev            - Files for PHP module development (default)
php-fpm            - server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
php-phpdbg         - server-side, HTML-embedded scripting language (PHPDBG binary) (default)
```

Quote from the package description:

> This package is a dependency package, which depends on latest stable PHP version (currently 8.2).

If you've installed on of these packages, the latest PHP version will be pulled with the next package upgrade.

**Comment by madman-81** [comment]
@killerbees19 Thanks! php-cli was installed, so that must have triggered it them.
