### ISSUE TITLE
APCu on PHP 8.2

### ISSUE THREAD

**Issue by luispabon** [oerdnj/deb.sury.org#1842]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
The APCu package is currently missing on php 8.2

**Describe the solution you'd like**
The opposite from the above.

**Describe alternatives you've considered**
APCu 5.1.22 was released a few days back with PHP 8.2 support, please see https://github.com/krakjoe/apcu/releases/tag/v5.1.22

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: all
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
`php8.2-apcu`

**Additional context**
As mentioned above, apcu wasn't compatible with php 8.2 until very recently, but the version which does is already out.

**Comment by oerdnj** [comment]
Dup of #1840
