### ISSUE TITLE
PHP 7.4.32 and 8.1.11 (and 8.0.24)

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1845]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
PHP [7.4.32](https://www.php.net/archive/2022.php#2022-09-29-1) and [8.1.11](https://www.php.net/archive/2022.php#2022-09-29-2) were released and classified as security releases. Official 8.0.24 release announcement still upcoming, but the [tarballs have been released](https://github.com/php/web-php-distributions/commit/dfaf79d064e26dc3d95d3a8bdc2e250256febacf).

**Comment by oerdnj** [comment]
Thanks for the ping. The security issues doesn't seem critical.

The launchpad seems to be having its moments and the uploads are timing out. I'll try to serialize the uploads and we'll see what's the status in the morning. Otherwise everything else should be building now.
