### ISSUE TITLE
Add phalcon5 support for php 8.1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by Bidek996** [oerdnj/deb.sury.org#1846]
**Frequently asked questions**

- [✓] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
The phalcon5 was just released but there is no package for ubuntu 20.04 to PHP 8.1. This Feature request is to add these packages.

**Describe the solution you'd like**
Add the phalcon5 packages for PHP 8.1 on Ubuntu 20.04.

**Describe alternatives you've considered**
Compiling the extensions

**Distribution (please complete the following information):**
OS: Ubuntu 20.04
Architecture: amd64
Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
No package available at this moment

**Comment by oerdnj** [comment]
I've started looking into that and it's not as straightforward as just bumping phalcon4 to phalcon5, so I'll need to give it little bit more time.

**Comment by waja** [comment]
I've started some some rudimentary packaging a few days ago for php-7.4 and bullseye at https://github.com/waja/php-phalcon5.

**Comment by oerdnj** [comment]
The thing is that I need this to work for multiple PHP versions and I already forgotten what is the Makefile voodoo I’m doing in phalcon3 and phalcon4 packages ;)

**Comment by waja** [comment]
Surprise, surprise ... I also tried to understand your packaging about this and I wasn't successfully either. ;)

**Comment by oerdnj** [comment]
I figured it out, so phalcon5 packages are now available.

**Comment by waja** [comment]
Are those packages expected to hit https://packages.sury.org/? It seems https://salsa.debian.org/php-team/pecl/php-phalcon5/-/tree/debian/main/debian got some love too.

**Comment by oerdnj** [comment]
Should be all there: https://jenkins.rfc1925.org/job/php_php-phalcon5-binaries/
