### ISSUE TITLE
php8.1-gd ubuntu 22.04

### ISSUE THREAD

**Issue by it-can** [oerdnj/deb.sury.org#1849]
I upgraded my Ubuntu machines 20 to 22.04 via ```do-release-upgrade```. Now I am getting this error with PHP 8.1.11. Does anybody know whats going on? Tried reinstalling etc but still the same result... The rest of PHP is working fine btw

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20210902/gd.so (libx265.so.179: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/gd.so.so (/usr/lib/php/20210902/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by oerdnj** [comment]
You have deliberately skipped the issue template, so I am closing the issue.
