### ISSUE TITLE
libgd 2.3.3 unwillingly dropped support for GD_BICUBIC* scaling algorithms (fixed upstream, but not released yet)

### ISSUE THREAD

**Issue by fulax** [oerdnj/deb.sury.org#1852]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
My main issue is that libgd3 2.3.3 is broken regarding php-gd's `imagescale` with `GD_BICUBIC`* algorithms. I already reported the bug [there](https://github.com/libgd/libgd/issues/847).

But php8.1-gd in buster depends on libgd3 (>= 2.3.3) which prevent us from apt-pinning libgd3 to some earlier version, while we could to it with the old stretch repository (which depended on >= 2.1.1).

**Your understanding of what is happening**
libgd3 2.3.3 introduced a bug that affect one of my client when using php5.6-gd on debian 10, and as my client is also eager to move its app to php8.1 I have a dependency preventing me from downgrading libgd3 until upstream fixes it and it lands into this repository.

**What steps did you take to resolve issue yourself before reporting it here**
(I actually do not care about libgd-dev, that was just needed to test some C examples).
```
LC_ALL=C aptitude -s install libgd3=2.2.5-5.2                                                                                                                   
The following packages will be DOWNGRADED:
  libgd3 
0 packages upgraded, 0 newly installed, 1 downgraded, 0 to remove and 28 not upgraded.
Need to get 136 kB of archives. After unpacking 2048 B will be freed.
The following packages have unmet dependencies:
 php8.1-gd : Depends: libgd3 (>= 2.3.3) but 2.2.5-5.2 is to be installed
 libgd-dev : Depends: libgd3 (= 2.3.3-5+0~20220711.9+debian10~1.gbp72b297) but 2.2.5-5.2 is to be installed
The following actions will resolve these dependencies:

     Remove the following packages:                                         
1)     libgd-dev [2.3.3-5+0~20220711.9+debian10~1.gbp72b297 (now)]          
2)     php8.1-gd [8.1.11-1+0~20220929.27+debian10~1.gbpe414ce (buster, now)]

Accept this solution? [Y/n/q/?] q
Abandoning all efforts to resolve these dependencies.
Abort.
```

**Expected behavior**
I should be able to downgrade libgd3, or expect a more stable libgd3 version (I understand that is not easy due to numerous CVE in image libraries).

**Distribution (please complete the following information):**
 - OS: Debian 10
 - Architecture: amd64
 - Repository: packages.sury.org, through [our local mirror](http://debian.octopuce.fr/sury-php/)

**Package(s) (please complete the following information):**
```
 apt-cache policy libgd3 php8.1-gd                                                                                                        
libgd3:
  Installé : 2.3.3-7+0~20221024.11+debian10~1.gbpb26540
  Candidat : 2.3.3-7+0~20221024.11+debian10~1.gbpb26540
 Table de version :
 *** 2.3.3-7+0~20221024.11+debian10~1.gbpb26540 500
        500 http://debian.octopuce.fr/sury-php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.5-5.2 500
        500 http://debian.octopuce.fr/debian buster/main amd64 Packages
php8.1-gd:
  Installé : 8.1.11-1+0~20220929.27+debian10~1.gbpe414ce
  Candidat : 8.1.11-1+0~20220929.27+debian10~1.gbpe414ce
 Table de version :
 *** 8.1.11-1+0~20220929.27+debian10~1.gbpe414ce 500
        500 http://debian.octopuce.fr/sury-php buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
Can we consider patching libgd3 in your repository to restore the BICUBIC algorithm? I think I can write the 3 lines patch, or wait for upstream to fix their code.

I don't think downgrading libgd3 in deb.sury.org seems reasonable (as downgrades rarely are).

Thank you.

**Comment by oerdnj** [comment]
> Can we consider patching libgd3 in your repository to restore the BICUBIC algorithm? I think I can write the 3 lines patch, or wait for upstream to fix their code.

Yes, that’s the only way how to fix this. Submit it to libgd and put a link here, I’ll pull it from there.

PHP uses some of the newer symbols, so the dependency tracker did put hard dependency there.

**Comment by fulax** [comment]
> Yes, that’s the only way how to fix this. Submit it to libgd and put a link here, I’ll pull it from there.

Submitted as [a comment](https://github.com/libgd/libgd/issues/847#issuecomment-1290142856) on my bug report, but the code as changed a lot regarding the BICUBIC method, and I'm not sure I'm doing the right thing, I'll wait for their feedback.

> PHP uses some of the newer symbols, so the dependency tracker did put hard dependency there.

Fair enough, thanks for the explanation.

**Comment by fulax** [comment]
Hi @oerdnj, my patch as finally landed and has been cherry-picked to the GD-2.3 branch. See https://github.com/libgd/libgd/commit/a5f5698a6832fc1f8179a9257f0b91c9a8ef496b

Thank you

**Comment by rfay** [comment]
@fulax probably off-topic, but is there any possibility that this can be related to the issues in 
* https://github.com/oerdnj/deb.sury.org/issues/1641
* https://github.com/drud/ddev/issues/4292

We still aren't successful with avif and php8.1-gd.

**Comment by fulax** [comment]
> probably off-topic, but is there any possibility that this can be related to the issues in

No, this is unreleated. My issue was specific to one interpolation method, and I don't see any connection between avif support in php-gd and libgd after looking at the code.

I can tell that the error message "AVIF image support has been disabled" comes from libgd itself https://github.com/libgd/libgd/blob/master/src/gd_avif.c#L666

You should check that your copy of libgd3 is up to date (2.3.3-7) on a supported distibution, as mentionned in https://github.com/oerdnj/deb.sury.org/issues/1641#issuecomment-1288812600 avif support for libgd was enabled for Debian Bullseye and Ubuntu Jammy. I do not know what ddev use as a base system.

**Comment by fulax** [comment]
I updated the issue title, to reflect accurately the issue : It  has nothing to do with php-gd itself, nor regarding how the packages are built in this repo, it's a bug in libgd.

**Comment by oerdnj** [comment]
Added the patch to the package and uploaded.
