### ISSUE TITLE
php-libvirt-php update to 5.5.6 and build for php 8.1

### ISSUE THREAD

**Issue by bs42** [oerdnj/deb.sury.org#1853]
Please update the php-libvirt-php module to 5.5.6 and build for php 8.1.
The current 5.5.5 has an so for 8.0 but is on an old API version and does not work with the current 8.0 release leaving only versions <= 7.4 working currently.

[https://libvirt.org/sources/php/libvirt-php-0.5.6.tar.xz](url)

**Comment by oerdnj** [comment]
Done, thanks, they've changed the compression, so I would have missed that as `d/watch` had only check for `.tar.gz`, not `.tar.xz`.

**Comment by bs42** [comment]
Hello, I see that the ubuntu build pushed, but the builds for debian seem stuck.  Could you give that a look?  Thanks!
