### ISSUE TITLE
kinetic Release' does not have a Release file

### ISSUE THREAD

**Issue by parmonov98** [oerdnj/deb.sury.org#1854]
**Frequently asked questions**

- [ ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
![image](https://user-images.githubusercontent.com/24564577/198882798-56a71754-e63c-4276-922e-460a5a717bbc.png)
as you can see, the same error in https://askubuntu.com/questions/1438143/can-install-php7-4-on-ubuntu-22-10

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **problem** accurately (where the template below will help), I might be able to help you.

What is not **a clear and concise description**:
1. "Look here"
2. "Look at this docker image"
3. "Raw copy of the terminal"
4. "Screenshot"

**To Reproduce**

**Your understanding of what is happening**
Try to describe how do you understand what is happending and why is it happening.

**What steps did you take to resolve issue yourself before reporting it here**
Describe how did you try to resolve the issue yourself.  This is closely connected to the previous question.

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.10 upgraded from 22.04
 - Architecture: amd64]
 - Repository: php

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
#1662
