### ISSUE TITLE
[FR] Add pdo-snowflake package for PHP8+

### ISSUE THREAD

**Issue by kissifrot** [oerdnj/deb.sury.org#1856]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
A [PDO Driver for Snowflake](https://github.com/snowflakedb/pdo_snowflake) is available but only as source code. Package looks rather correctly well-maintained.

**Describe the solution you'd like**
A packaged version of pdo-snowflake is available for Ubuntu 20.04+ and PHP 8+

**Describe alternatives you've considered**
Adding a build step to our deployment scripts, which adds too many build-time-only packages which are a mess to clean after 

**Distribution (please complete the following information):**
 - OS: [Ubuntu]
 - Architecture: [amd/arm64]
 - Repository: [Ubuntu PPA]

**Package(s) (please complete the following information):**
(No package available at this moment :sob:  )

**Additional context**
No package available at this moment

**Comment by oerdnj** [comment]
I am sorry, but I've read the build instructions and I am not going to package that. Then I looked at the build script and it's the kind thing that will haunt me...

Especially this:
```
        libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a \
        libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a \
        libsnowflakeclient/deps-build/linux/cmocka/lib/libcmocka.a
```

Does it really build and link OpenSSL and CMocka as static archives into the extension?

**Comment by kissifrot** [comment]
I'm afraid you are right, sorry for your waste of time, I'll pass on your feedback, and I hope they will improve their extension's quality 🤞

**Comment by oerdnj** [comment]
FTR No waste of time on well articulated feature request. It had everything I needed in one place, so thanks for caring!
