### ISSUE TITLE
[php7.0] php-memcache module

### ISSUE THREAD

**Issue by LAV45** [oerdnj/deb.sury.org#186]
Would be great to have a package for the new memcache connector: 
https://github.com/websupport-sk/pecl-memcache

**Comment by oerdnj** [comment]
I am definitely not going to package an unofficial repositories with the same name as official extensions. That would create only a confusion. I'll update memcache when it's updated in the official PECL page or at least official git.

**Comment by oerdnj** [comment]
Reopen to track official https://pecl.php.net/package/memcache package.

**Comment by oerdnj** [comment]
BTW Is there any reason why not to switch to (maintained) memcached PECL module? I haven't found any (apart from the need to touch already existing code, but the conversion should be straightforward).

**Comment by robfrawley** [comment]
@oerdnj There is not. The memcached extension provides everything in the unmaintained memcache extension, while offering a better interface and an array of excellent additional features (take deferred requests, for one).

I cannot count the number of times I've had to explain to people new to PHP why there are two extensions with such similar names, and for those new to *nix systems the subtle difference of the "d" in the name isn't readily apparent and causes some to become unsure if they even provide the same ability to interface with a memcached server.

Do everyone a favor and don't fill our prompt autocompletes with this when installing packages. ;-)

**Comment by oerdnj** [comment]
@robfrawley Would it be possible to write a thin layer similar to apcu_bc and just alias memcache_* functions to memcached_*?

**Comment by robfrawley** [comment]
In PHP or C? The former would be trivial. There is nothing the old API implements that isn't also provided by the new extension. I'd have to reference the documentation further, but assuming there isn't a situation where the new extension introduces an additional parameter requirement (and I can't think of this being the case, though it's been a while since I've used the old extension), it is absolutely trivial.

**Comment by oerdnj** [comment]
I was thinking about C.

**Comment by robfrawley** [comment]
How did I know that's where you were going with this. ;-)

It doesn't look particularly complex. The old extension only exposes 6 constants and 1 class with 18 methods, 90% of which are directly mappable to Memcached. I may glance at the extension src in the coming weeks, so give me a heads up if you're on it so we don't duplicate effort.

**Comment by oerdnj** [comment]
@robfrawley I can probably help with that in some spare time; this doesn't seem too complex too me, but the free time is always problem with me. Let's start with some git repository - should I open one here under me?

**Comment by oerdnj** [comment]
@robfrawley So I looked into this at it might not be as simple as it looks, as there's no way how to simple alias the Memcache class to Memcached, as PHP_MALIAS (alias for ZEND_MALIAS) can alias functions inside the class, so you can have Memcache->foo alias to Memcache->bar, but not to Memcached->foo.

E.g. writing memcache_bc module would then mean just ripping the structure and writing (or generating) a wrapper function for each method of Memcache class. Not sure if it's worth the trouble, and we might as well let the memcache to die in peace and let the world to move on to memcached as it should have happened long time ago.

If anybody has a code using memcache they can't touch, I would bet it won't run on PHP 7.0 anyway...  But feel free to hack on that if you are bored, or you really see a value in that.

**Comment by robfrawley** [comment]
@oerdnj *I* don't see value in it, though I know there are tons of people using legacy software who may. That said, those people could easily write a quick PHP class to handle the situation, so I don't disagree with your stance at all.

**Comment by oerdnj** [comment]
@robfrawley As far as I understand you only need to change the constructor from Memcache to Memcached (and maybe some minor tweaks). And you can always run a legacy software on a legacy PHP version. Just don't mix the new&shiny with old&rusty.

**Comment by oerdnj** [comment]
I had a chat with Debian maintainer of php-memcache and he had a good point that we need to deprecate php-memcache gracefully. That means have it in Debian stretch with prominent notice about deprecating php-memcache in favour of php-memcached, and remove it in stretch+.

Thus `php-memcache_3.0.8-46-gfdbd46b-1+deb.sury.org~*+1` with code taken from websupport-sk repository has landed in `ppa:ondrej/php` as we speak.
