### ISSUE TITLE
debian repo is behind for php-libvirt-php

### ISSUE THREAD

**Issue by bs42** [oerdnj/deb.sury.org#1862]
This is related to #1853 

I added a comment to that one but it was closed so I thought I should create a new issue.

The build appeared for ubuntu but not for debian.  

I see that PHP 7.4.33 updated so perhaps something is clogging up the build process for Debian just for php-libvirt-php.

Thanks for checking!

**Comment by oerdnj** [comment]
The `src:libvirt-php` was broken for some time, now it should be updated again for both Debian and Ubuntu.
