### ISSUE TITLE
php8.2-smbclient missing

### ISSUE THREAD

**Issue by ralfbecker** [oerdnj/deb.sury.org#1863]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
php8.2-smbclient package is missing, php-smbclient does NOT create /etc/php/8.2/mods-available/smbclient.ini.

**Describe the solution you'd like**
Enhance php-smbclient with PHP 8.2 support. Remi uses 1.0.6 for PHP 8.2 ...

**Describe alternatives you've considered**
Just copying smbclient.ini alone wont help, as the extension needs to be build for 8.2 API.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
php-smbclient:
  Installed: 1.0.6-6+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.0.6-6+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1.0.6-6+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.6-6 500
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

**Additional context**
n/a

**Comment by oerdnj** [comment]
Dup of #1840
