### ISSUE TITLE
The user named '~ondrej' has no PPA named 'ubuntu/php'

### ISSUE THREAD

**Issue by Csardelacal** [oerdnj/deb.sury.org#1865]
**Frequently asked questions**

- [x ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
When trying to add the PPA the error `The user named '~ondrej' has no PPA named 'ubuntu/php'` will show up. The PPA won't be added and (in my case) the pipeline won't continue.

Full output:
```
$ LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
Cannot add PPA: 'ppa:~ondrej/ubuntu/php'.
The user named '~ondrej' has no PPA named 'ubuntu/php'
Please choose from the following available PPAs:
 * 'apache2':  PPA for Apache 2.x
 * 'apache2-qa':  PPA for Apache2 (QA builds; experimental)
 * 'nginx':  PPA for NGINX Stable with HTTP/2
 * 'nginx-mainline':  PPA for NGINX Mainline with HTTP/2
 * 'nginx-qa':  PPA for NGINX Mainline (QA builds; experimental)
 * 'php':  ***** The main PPA for supported PHP versions with many PECL extensions *****
 * 'php-qa':  PPA for PHP (QA builds; experimental)
 * 'pkg-gearman':  PPA for Gearman
```

**To Reproduce**
`LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php`

**Your understanding of what is happening**
When going to the website there's a `+archive` tag in the URL. `https://launchpad.net/~ondrej/+archive/ubuntu/php`
Was this discontinued or is it an error?

**What steps did you take to resolve issue yourself before reporting it here**
Describe how did you try to resolve the issue yourself.  This is closely connected to the previous question.

**Distribution (please complete the following information):**

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
Systemd Version
systemd 245 (245.4-4ubuntu3.17)
```

**Additional context**

This is my pipeline. It worked fine just yesterday.
https://app.travis-ci.com/github/Csardelacal/SpitfireEngine/builds/258242776#L7

**Comment by oerdnj** [comment]
That's just your local problem:
```
# add-apt-repository -y ppa:ondrej/php
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease [23.9 kB]
[...]
```

It works fine here, perhaps Travis CI is playing tricks with you.
