### ISSUE TITLE
php-libvirt-php: Actual module missing from Ubuntu package

### ISSUE THREAD

**Issue by AiYoriAoshi** [oerdnj/deb.sury.org#1868]
php-libvirt-php Packages for Ubuntu are missing the libvirt-php.so module in version 5.6-1

From the buildlogs I think the module is actually built but not packaged so when upgrading from 5.5 the module get's removed and no new module is installed, breaking all applications relying on that module.

**Comment by oerdnj** [comment]
The issue templates are there for a reason. Use them.
