### ISSUE TITLE
SAPI-specific config dirs not symlinked

### ISSUE THREAD

**Issue by ef4** [oerdnj/deb.sury.org#187]
On 5.6.16+dfsg-2+deb.sury.org~trusty+1 `/usr/share/doc/php5/README.Debian.gz` says:

    each SAPI is configured with the compile-time option 

        --with-config-file-scan-dir=/etc/php5/$SAPI/conf.d

    which for all SAPIs is actually a symlink pointing to a central directory /etc/php5/conf.d

But those directories are not actually symlinked together. This results in surprising behavior when you try to run php5dbg and it lacks access to all the modules that are available to apache2 and cli.

I don't know if this is an upstream issue or something specific to the PPA, happy to refile elsewhere if somebody can point the way. Thanks for the PPA!

**Comment by oerdnj** [comment]
The documentation is wrong. The module configuration is separate for each SAPI. But on the other hand if you install any module from package it should auto-enable itself for each installed SAPI. Could you purge phpdbg package and the reinstall it again and send me a console log and output of `ls -lR /etc/php5` and `ls -lR /usr/share/php5 /usr/lib/php5`?

**Comment by ef4** [comment]
[console.txt](https://github.com/oerdnj/deb.sury.org/files/76518/console.txt)

**Comment by oerdnj** [comment]
This looks like specific to phpdbg, I'll look into it.

**Comment by oerdnj** [comment]
Found it, as an intermediate fix use:
`touch /usr/share/php5/sapi/phpdbg`
after installing php5-phpdbg.

**Comment by oerdnj** [comment]
Fixed in `php5_5.6.17+dfsg-2+deb.sury.org~*+1` upload.
