### ISSUE TITLE
Version issue with libgd3 2.3.3-*+ubuntu22.04.1+deb.sury.org+1

### ISSUE THREAD

**Issue by OdinVex** [oerdnj/deb.sury.org#1873]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
A package version dependency issue exists for Ubuntu Jammy:

`libgd3 : Breaks: libgd3:i386 (!= 2.3.3-7+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-6+ubuntu22.04.1+deb.sury.org+1 is to be installed`
`libgd3:i386 : Breaks: libgd3 (!= 2.3.3-6+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-7+ubuntu22.04.1+deb.sury.org+1 is to be installed`

There doesn't appear to actually be a `2.3.3-7+ubuntu22.04.1+deb.sury.org+1` version of `libgd3:i386`.

**What steps did you take to resolve the issue yourself before reporting it here**
I checked the PPA manually, finding the Packages specify an actual version conflict.

**Distribution (please complete the following information):**
 - OS: Mint (Ubuntu-Like)
 - Architecture: amd64
 - Repository: `Ubuntu PPA`
 - Source Content: `deb http://ppa.launchpad.net/ondrej/php/ubuntu jammy main`

**Comment by OdinVex** [comment]
I don't expect any Support or anything, I'm just certain that there is an issue with the version dependency that would genuinely affect Ubuntu Jammy installations right now.

**Comment by oerdnj** [comment]
The i386 is almost dead architecture in the PPA for Jammy. It only builds packages on Canonical exception list and libavif needed by libgd3 isn’t on the list. There’s little I can do here.

**Comment by OdinVex** [comment]
> The i386 is almost dead architecture in the PPA for Jammy. It only builds packages on Canonical exception list and libavif needed by libgd3 isn’t on the list. There’s little I can do here.

The i386 does need to die off, but in my case, many Windows-based software used with Wine need these i386 libraries too. Attempting to remove libgd3:i386 would result in losing:

`libgphoto2-6:i386 libsane1:i386 wine-binfmt wine-staging wine-staging-i386:i386 winehq-staging winetricks` I've found Wine to be rather critical to bridging the transitioning from Windows to Linux.

**Comment by OdinVex** [comment]
> Then just don’t mix the environments.

Mix? I'd have to run a Windows PC or VM, a bit extreme, but I've been thinking about going full-on Arch or Manjaro, so it won't be a problem for much longer.

> No, what I am saying is that it can’t be updated because it won’t build in the PPA for reasons I can’t influence.

Is it libavif15? Makes sense, I've only seen libavif13 on Ubuntu. Does this mean the end of i386 sury stuff or?

**Comment by oerdnj** [comment]
No, just don’t mix the extra PHP repo and wine32. There are other ways how to put things into separate container rather than mashing everything into a single system.

Alternatively, you can build the libgd3:i386 packages locally from a source.

As I said, this is something out of my control, not my choice.

**Comment by OdinVex** [comment]
> No, just don’t mix the extra PHP repo and wine32. There are other ways how to put things into separate container rather than mashing everything into a single system.

Single system is the only way to go, the concept of containers also needs to go away, it's just a re-invention of DLL-Hell. Linux in general has issues with ABI, something Windows got right from the start, I hate to admit. From 16 to 32 to 64, now-days it seems much more breaks in Linux due to any kind of version issue, even minor/patch. Graphics has come a long way, though. Can't wait to see how badly the Pulse->Pipewire migration goes.

> Alternatively, you can build the libgd3:i386 packages locally from a source.
It does seem to be needed, a good idea.

> As I said, this is something out of my control, not my choice.
That's perfectly alright and quite understandable. :)

**Comment by leancode** [comment]
Hey @OdinVex, Could you give some instructions on how to do that here? I have exactly the same problem. php8.2-gd just won't install because:  php8.2-gd : Depends: libgd3 (>= 2.3.3) but 2.3.0-2ubuntu2 is to be installed. It refuses to install libgd3 from deb.sury.org because, me too, I have wine installed (like many people on desktop systems I presume) which requires libgd3:i386 which refuses to install because the x64 and i86 are not the same version number.

I have compiled applications before but don't usually. I don't know where to start exactly to compile a library.

**Comment by leancode** [comment]
Great, thanks for the pointer. Might give Manjaro a go at some point too.

**Comment by chancezeus** [comment]
For those on ubuntu (and probably debian as well) that can't or do not want to switch and need a `libgd3:i386` build, I've created a bash script that should (at least at the moment) take care of building the relevant deb packages from source.

```bash
#!/usr/bin/env bash
set -e

export DEBIAN_FRONTEND=noninteractive

TEMP_DIR="$(readlink -f "$(mktemp -d -p .)")"

trap "rm -rf ${TEMP_DIR}" EXIT

echo "Entering ${TEMP_DIR}"
pushd "${TEMP_DIR}" >/dev/null

echo "Fetch source files"
apt-get source cjson libgav1 libavif libgd2 >/dev/null

CJSON_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name cjson_\*.debian.* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBGAV1_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libgav1_\*.debian.* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBAVIF_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libavif_\*.debian.* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBGD2_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libgd2_\*.debian.* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')

echo "Building:"
echo "- cjson: ${CJSON_VERSION}"
echo "- libgav1: ${LIBGAV1_VERSION}"
echo "- libavif: ${LIBAVIF_VERSION}"
echo "- libgd2: ${LIBGD2_VERSION}"

CJSON_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name cjson-\*)
LIBGAV1_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libgav1-\*)
LIBAVIF_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libavif-\*)
LIBGD2_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libgd2-\*)

CJSON_BUILD_DEB="./cjson-cross-build-deps_${CJSON_VERSION}_i386.deb"
LIBGAV1_BUILD_DEB="./libgav1-cross-build-deps_${LIBGAV1_VERSION}_i386.deb"
LIBAVIF_BUILD_DEB="./libavif-cross-build-deps_${LIBAVIF_VERSION}_i386.deb"
LIBGD2_BUILD_DEB="./libgd2-cross-build-deps_${LIBGD2_VERSION}_i386.deb"

LIBCJSON_DEB="./libcjson1_${CJSON_VERSION}_i386.deb"
LIBCJSON_DEV_DEB="./libcjson-dev_${CJSON_VERSION}_i386.deb"
LIBGAV1_DEB="./libgav1-0_${LIBGAV1_VERSION}_i386.deb"
LIBGAV1_DEV_DEB="./libgav1-dev_${LIBGAV1_VERSION}_i386.deb"
LIBAVIF_DEB="./libavif13_${LIBAVIF_VERSION}_i386.deb"
LIBAVIF_DEV_DEB="./libavif-dev_${LIBAVIF_VERSION}_i386.deb"
LIBGD3_DEB="./libgd3_${LIBGD2_VERSION}_i386.deb"

echo "Creating and installing build dependencies ${CJSON_BUILD_DEB}"
mk-build-deps -a i386 --host-arch i386 cjson >/dev/null
sudo apt-get install -y "${CJSON_BUILD_DEB}" "${LIBGAV1_BUILD_DEB}" >/dev/null
sudo apt-mark auto cjson-cross-build-deps:i386 libgav1-cross-build-deps:i386 >/dev/null

echo "Entering ${CJSON_PATH}"
pushd "${CJSON_PATH}" >/dev/null

echo "Building cjson-${CJSON_VERSION}"
debuild -ai386 -i -us -uc -b >/dev/null

echo "Leaving ${CJSON_PATH}"
popd >/dev/null

echo "Installing ${LIBCJSON_DEB} and ${LIBCJSON_DEV_DEB}"
sudo apt-get install -y "${LIBCJSON_DEB}" "${LIBCJSON_DEV_DEB}" >/dev/null
sudo apt-mark auto libcjson1:i386 libcjson-dev:i386 >/dev/null

echo "Creating and installing build dependencies ${LIBGAV1_BUILD_DEB}"
mk-build-deps -a i386 --host-arch i386 libgav1 >/dev/null
sudo apt-get install -y "${LIBGAV1_BUILD_DEB}" >/dev/null
sudo apt-mark auto libgav1-cross-build-deps:i386 >/dev/null

echo "Entering ${LIBGAV1_PATH}"
pushd "${LIBGAV1_PATH}" >/dev/null

echo "Building libgav1-${LIBGAV1_VERSION}"
debuild -ai386 -i -us -uc -b >/dev/null

echo "Leaving ${LIBGAV1_PATH}"
popd >/dev/null

echo "Installing ${LIBGAV1_DEB} and ${LIBGAV1_DEV_DEB}"
sudo apt-get install -y "${LIBGAV1_DEB}" "${LIBGAV1_DEV_DEB}" >/dev/null
sudo apt-mark auto libgav1-0:i386 libgav1-dev:i386 >/dev/null

echo "Creating and installing build dependencies ${LIBAVIF_BUILD_DEB}"
mk-build-deps -a i386 --host-arch i386 libavif >/dev/null
sudo apt-get install -y "${LIBAVIF_BUILD_DEB}" >/dev/null
sudo apt-mark auto libavif-cross-build-deps:i386 >/dev/null

echo "Entering ${LIBAVIF_PATH}"
pushd "${LIBAVIF_PATH}" >/dev/null

echo "Building libavif-${LIBAVIF_VERSION}"
debuild -ai386 -i -us -uc -b >/dev/null

echo "Leaving ${LIBAVIF_PATH}"
popd >/dev/null

echo "Installing ${LIBAVIF_DEB} and ${LIBAVIF_DEV_DEB}"
sudo apt-get install -y "${LIBAVIF_DEB}" "${LIBAVIF_DEV_DEB}" >/dev/null
sudo apt-mark auto libavif13:i386 libavif-dev:i386 >/dev/null

echo "Creating and installing build dependencies ${LIBGD2_BUILD_DEB}"
mk-build-deps -a i386 --host-arch i386 libgd2 >/dev/null
sudo apt-get install -y "${LIBGD2_BUILD_DEB}" >/dev/null
sudo apt-mark auto libgd2-cross-build-deps:i386 >/dev/null

echo "Entering ${LIBGD2_PATH}"
pushd "${LIBGD2_PATH}" >/dev/null

echo "Building libgd2-${LIBGD2_VERSION}"
debuild -ai386 -i -us -uc -b >/dev/null

echo "Leaving ${LIBGD2_PATH}"
popd >/dev/null

echo "Installing ${LIBGD3_DEB}"
sudo apt-get install -y "${LIBGD3_DEB}" >/dev/null

echo "Leaving ${TEMP_DIR}"
popd >/dev/null

echo "Removing ${TEMP_DIR}"
rm -r "${TEMP_DIR}" >/dev/null

while true; do
  read -p "Run 'apt-get autoremove --purge' to purge unused packages (WARNING: this includes packages NOT installed by this script)? (y/N) " yn

  if [ -z ${yn} ]; then
    yn=N
  fi

  case $yn in
    [yY][eE][sS]|[yY] ) break;;
    [nN][oO]|[nN]     ) exit;;
    *                 ) echo "Invalid response";;
  esac
done

sudo apt-get autoremove --purge -y >/dev/null
```

The script has one dependency that is not automatically installed and that is `devscripts` (install using `apt-get install devscripts`)

The script itself does nothing more than using the tools available in order to:
1. Create a temporary folder
2. Fetch the sources (`apt-get source`)
3. Build and install the dependencies in order
   1. From `cjson` (needed to build `libavif` and unavailable in Ubuntu repos):
      1. Create the build dependencies `.deb` (from `devscripts`: `mk-build-deps -a i386 --host-arch i386`)
      2. Install the build dependencies (`apt-get install`)
      3. Build the `.deb` files (from `devscripts`: `debuild -ai386 -i -us -uc -b`)
      4. Install the needed `.deb` files for `libcjson1:i386` and `libcjson-dev:i386` (`apt-get install`)
      5. Mark them as auto installed (`apt-mark auto`)
   2. From `libgav1` (needed to build `libavif` and unavailable in Ubuntu repos):
      1. Create the build dependencies `.deb` (from `devscripts`: `mk-build-deps -a i386 --host-arch i386`)
      2. Install the build dependencies (`apt-get install`)
      3. Build the `.deb` files (from `devscripts`: `debuild -ai386 -i -us -uc -b`)
      4. Install the needed `.deb` files for `libgav1-0:i386` and `libgav1-dev:i386` (`apt-get install`)
      5. Mark them as auto installed (`apt-mark auto`)
   3. From `libavif` (needed by `libgd2` and unavailable in Ubuntu repos):
      1. Create the build dependencies `.deb` (from `devscripts`: `mk-build-deps -a i386 --host-arch i386`)
      2. Install the build dependencies (`apt-get install`)
      3. Build the `.deb` files (from `devscripts`: `debuild -ai386 -i -us -uc -b`)
      4. Install the needed `.deb` files for `libavif13:i386` and `libavif-dev:i386` (`apt-get install`)
      5. Mark them as auto installed (`apt-mark auto`)
   4. From `libgd2`:
      1. Create the build dependencies `.deb` (from `devscripts`: `mk-build-deps -a i386 --host-arch i386`)
      2. Install the build dependencies (`apt-get install`)
      3. Build the `.deb` files (from `devscripts`: `debuild -ai386 -i -us -uc -b`)
      4. Install the `.deb` file for `libgd3:i386` (`apt-get install`)
4. Cleanup the temporary folder (`rm -r`)
5. Optionally (based on prompt answer) runs `apt-get autoremove --purge` to remove any package that is marked as auto installed and no longer needed (this includes packages not installed by the script, **_USE WITH CAUTION!!!_**)

**Comment by chancezeus** [comment]
Improved version using a docker container to build the deb files for both i386 and amd64 (somehow libavif is giving issues when using official libavif13:amd64 i.c.w. the custom build libavif13:i386, building both from source solves this):

File: `docker-build-libgd3.sh`
```bash
#!/usr/bin/env bash
set -e

export DEBIAN_FRONTEND=noninteractive

if [ \! -z "${1}" ]; then
  OWNER_ID="${1}"
elif [ \! -z "${OWNER_ID}" ]; then
  OWNER_ID="${OWNER_ID}"
else
  OWNER_ID="1000"
fi

if [ \! -z "${2}" ]; then
  GROUP_ID="${1}"
elif [ \! -z "${GROUP_ID}" ]; then
  GROUP_ID="${GROUP_ID}"
else
  GROUP_ID="1000"
fi

if [ \! -z "${3}" ]; then
  TARGET_DIR="${3}"
elif [ \! -z "${TARGET_DIR}" ]; then
  TARGET_DIR="${TARGET_DIR}"
else
  TARGET_DIR=/build
fi

echo -e "Result owner: ${OWNER_ID}"
echo -e "Result group: ${GROUP_ID}"
echo -e "Result location: ${TARGET_DIR}"

echo -e "\nInstalling base dependencies"
sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list >/dev/null
dpkg --add-architecture i386 >/dev/null
apt-get update >/dev/null
apt-get install -y software-properties-common devscripts equivs gpg wget libc6-dev:i386 >/dev/null

echo -e "Adding ppa:ondrej/php"
add-apt-repository -y -s ppa:ondrej/php >/dev/null

echo -e "Upgrading packages"
apt-get upgrade --purge -y >/dev/null

TEMP_DIR="$(mktemp -d)"

echo -e "\nEntering ${TEMP_DIR}"
pushd "${TEMP_DIR}" >/dev/null

echo -e "\nFetch source files"
apt-get source cjson libgav1 libavif libgd2 >/dev/null

CJSON_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name cjson_\*.debian.\* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBGAV1_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libgav1_\*.debian.\* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBAVIF_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libavif_\*.debian.\* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')
LIBGD2_VERSION=$(find -mindepth 1 -maxdepth 1 -type f -name libgd2_\*.debian.\* | awk -F_ '{print $2;}' | sed 's/\.debian\..*$//')

echo -e "\nBuilding:"
echo -e "- cjson: ${CJSON_VERSION}"
echo -e "- libgav1: ${LIBGAV1_VERSION}"
echo -e "- libavif: ${LIBAVIF_VERSION}"
echo -e "- libgd2: ${LIBGD2_VERSION}"

CJSON_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name cjson-\*)
LIBGAV1_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libgav1-\*)
LIBAVIF_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libavif-\*)
LIBGD2_PATH=$(find -mindepth 1 -maxdepth 1 -type d -name libgd2-\*)

CJSON_BUILD_DEB="./cjson-build-deps_${CJSON_VERSION}_amd64.deb"
LIBGAV1_BUILD_DEB="./libgav1-build-deps_${LIBGAV1_VERSION}_amd64.deb"
LIBAVIF_BUILD_DEB="./libavif-build-deps_${LIBAVIF_VERSION}_amd64.deb"
LIBGD2_BUILD_DEB="./libgd2-build-deps_${LIBGD2_VERSION}_amd64.deb"
CJSON_CROSS_BUILD_DEB="./cjson-cross-build-deps_${CJSON_VERSION}_i386.deb"
LIBGAV1_CROSS_BUILD_DEB="./libgav1-cross-build-deps_${LIBGAV1_VERSION}_i386.deb"
LIBAVIF_CROSS_BUILD_DEB="./libavif-cross-build-deps_${LIBAVIF_VERSION}_i386.deb"
LIBGD2_CROSS_BUILD_DEB="./libgd2-cross-build-deps_${LIBGD2_VERSION}_i386.deb"

LIBCJSON_AMD64_DEB="./libcjson1_${CJSON_VERSION}_amd64.deb"
LIBCJSON_DEV_AMD64_DEB="./libcjson-dev_${CJSON_VERSION}_amd64.deb"
LIBGAV1_AMD64_DEB="./libgav1-0_${LIBGAV1_VERSION}_amd64.deb"
LIBGAV1_DEV_AMD64_DEB="./libgav1-dev_${LIBGAV1_VERSION}_amd64.deb"
LIBAVIF_AMD64_DEB="./libavif13_${LIBAVIF_VERSION}_amd64.deb"
LIBAVIF_DEV_AMD64_DEB="./libavif-dev_${LIBAVIF_VERSION}_amd64.deb"
LIBGD3_AMD64_DEB="./libgd3_${LIBGD2_VERSION}_amd64.deb"
LIBCJSON_I386_DEB="./libcjson1_${CJSON_VERSION}_i386.deb"
LIBCJSON_DEV_I386_DEB="./libcjson-dev_${CJSON_VERSION}_i386.deb"
LIBGAV1_I386_DEB="./libgav1-0_${LIBGAV1_VERSION}_i386.deb"
LIBGAV1_DEV_I386_DEB="./libgav1-dev_${LIBGAV1_VERSION}_i386.deb"
LIBAVIF_I386_DEB="./libavif13_${LIBAVIF_VERSION}_i386.deb"
LIBAVIF_DEV_I386_DEB="./libavif-dev_${LIBAVIF_VERSION}_i386.deb"
LIBGD3_I386_DEB="./libgd3_${LIBGD2_VERSION}_i386.deb"

echo -e "\nWorking on cjson"
echo -e "Creating and installing build dependencies"
mk-build-deps -a amd64 --host-arch amd64 cjson >/dev/null
mk-build-deps -a i386 --host-arch i386 cjson >/dev/null
apt-get install -y "${CJSON_BUILD_DEB}" "${CJSON_CROSS_BUILD_DEB}" >/dev/null

echo -e "Entering ${CJSON_PATH}"
pushd "${CJSON_PATH}" >/dev/null

echo -e "Building cjson-${CJSON_VERSION}"
debuild -aamd64 -i -us -uc -b >/dev/null
debuild -ai386 -i -us -uc -b >/dev/null

echo -e "Leaving ${CJSON_PATH}"
popd >/dev/null

echo -e "Installing ${LIBCJSON_AMD64_DEB}, ${LIBCJSON_DEV_AMD64_DEB}, ${LIBCJSON_I386_DEB} and ${LIBCJSON_DEV_I386_DEB}"
apt-get install -y --allow-downgrades "${LIBCJSON_AMD64_DEB}" "${LIBCJSON_DEV_AMD64_DEB}" "${LIBCJSON_I386_DEB}" "${LIBCJSON_DEV_I386_DEB}" >/dev/null

echo -e "\nWorking on libgav1"
echo -e "Creating and installing build dependencies"
mk-build-deps -a amd64 --host-arch amd64 libgav1 >/dev/null
mk-build-deps -a i386 --host-arch i386 libgav1 >/dev/null
apt-get install -y "${LIBGAV1_BUILD_DEB}" "${LIBGAV1_CROSS_BUILD_DEB}" >/dev/null

echo -e "Entering ${LIBGAV1_PATH}"
pushd "${LIBGAV1_PATH}" >/dev/null

echo -e "Building libgav1-${LIBGAV1_VERSION}"
debuild -aamd64 -i -us -uc -b >/dev/null
debuild -ai386 -i -us -uc -b >/dev/null

echo -e "Leaving ${LIBGAV1_PATH}"
popd >/dev/null

echo -e "Installing ${LIBGAV1_AMD64_DEB}, ${LIBGAV1_DEV_AMD64_DEB}, ${LIBGAV1_I386_DEB} and ${LIBGAV1_DEV_I386_DEB}"
apt-get install -y --allow-downgrades "${LIBGAV1_AMD64_DEB}" "${LIBGAV1_DEV_AMD64_DEB}" "${LIBGAV1_I386_DEB}" "${LIBGAV1_DEV_I386_DEB}" >/dev/null

echo -e "\nWorking on libavif"
echo -e "Creating and installing build dependencies"
mk-build-deps -a amd64 --host-arch amd64 libavif >/dev/null
mk-build-deps -a i386 --host-arch i386 libavif >/dev/null
apt-get install -y "${LIBAVIF_BUILD_DEB}" "${LIBAVIF_CROSS_BUILD_DEB}" >/dev/null

echo -e "Entering ${LIBAVIF_PATH}"
pushd "${LIBAVIF_PATH}" >/dev/null

echo -e "Building libavif-${LIBAVIF_VERSION}"
debuild -aamd64 -i -us -uc -b >/dev/null
debuild -ai386 -i -us -uc -b >/dev/null

echo -e "Leaving ${LIBAVIF_PATH}"
popd >/dev/null

echo -e "Installing ${LIBAVIF_AMD64_DEB}, ${LIBAVIF_DEV_AMD64_DEB}, ${LIBAVIF_I386_DEB} and ${LIBAVIF_DEV_I386_DEB}"
apt-get install -y --allow-downgrades "${LIBAVIF_AMD64_DEB}" "${LIBAVIF_DEV_AMD64_DEB}" "${LIBAVIF_I386_DEB}" "${LIBAVIF_DEV_I386_DEB}" >/dev/null

echo -e "\nWorking on libgd2"
echo -e "Creating and installing build dependencies"
mk-build-deps -a amd64 --host-arch amd64 libgd2 >/dev/null
mk-build-deps -a i386 --host-arch i386 libgd2 >/dev/null
apt-get install -y "${LIBGD2_BUILD_DEB}" "${LIBGD2_CROSS_BUILD_DEB}" >/dev/null

echo -e "Entering ${LIBGD2_PATH}"
pushd "${LIBGD2_PATH}" >/dev/null

echo -e "Building libgd2-${LIBGD2_VERSION}"
debuild -aamd64 -i -us -uc -b >/dev/null
debuild -ai386 -i -us -uc -b >/dev/null

echo -e "Leaving ${LIBGD2_PATH}"
popd >/dev/null

echo -e "Installing ${LIBGD3_AMD64_DEB} and ${LIBGD3_I386_DEB}"
apt-get install -y --allow-downgrades "${LIBGD3_AMD64_DEB}" "${LIBGD3_I386_DEB}" >/dev/null

echo -e "Copying resulting .deb files"
install -m 775 -o "${OWNER_ID}" -g "${GROUP_ID}" -d "${TARGET_DIR}"
install -C -m 664 -o "${OWNER_ID}" -g "${GROUP_ID}" "${LIBGAV1_AMD64_DEB}" "${LIBGAV1_I386_DEB}" "${LIBAVIF_AMD64_DEB}" "${LIBAVIF_I386_DEB}" "${LIBGD3_AMD64_DEB}" "${LIBGD3_I386_DEB}" "${TARGET_DIR}"

echo -e "libgd3:i386 and dependencies build successfully"
```

File: `build-libgd3.sh`
```bash
#!/usr/bin/env bash
set -e

export DEBIAN_FRONTEND=noninteractive

mkdir -p libgd3-out
docker run --rm -it -v '.:/build' ubuntu:jammy /build/docker-build-libgd3.sh $(id -u) $(id -g) /build/libgd3-out
sudo apt-get install -y --allow-downgrades ./libgd3-out/*.deb
```

**Comment by bastien70** [comment]
Hello @chancezeus when using your docker sample, at the end, I've the following error : 

N: Le téléchargement est effectué en dehors du bac à sable en tant que « root » car le fichier « /home/bastien/Documents/toto/libgd3-out/libavif13_0.9.3-3_amd64.deb » n'est pas accessible par l'utilisateur « _apt ». - pkgAcquire::Run (13: Permission non accordée)

Do you know what I do ?

**Comment by chancezeus** [comment]
Hi @bastien70,

My French isn't perfect and using MTL will not give the exact error in English, but as far as I can gather from from Google it means that apt can't read or write to one or more of it's internal folder. I recommend retrying it with the locale set to English and then Google the error.

For reference, this is what I found: https://askubuntu.com/a/954929

> This is a known bug:
> 
> https://bugs.launchpad.net/ubuntu/+source/aptitude/+bug/1543280
> 
> They suggest running the following command:
> 
> sudo chown _apt /var/lib/update-notifier/package-data-downloads/partial/
> Give it a try and see if it fixes the issue.

**Comment by bastien70** [comment]
Hey @chancezeus thank for your answer. I also came across this fix, and I tried it, but unfortunately it didn't change anything. As the comment just below claimed:

> This can not work on 22.04.1 LTS (Jammy Jellyfish)

This is my ubuntu version too. I searched the internet for solutions, but I couldn't find anything conclusive (I even went so far as to check with ChatGPT, but it doesn't give a conclusive solution either)

**Comment by sagitariozod** [comment]
> libavif13_0.9.3

Hello, I need compile for Ubuntu 24.04, but not work. This work fine in Ubuntu 22.04.

I have the error: 

`Entering /home/Descargas/libgd3-deb.sury.org-Librerias/tmp.EZH0M0ooyb
Fetch source files
E: No se pudo encontrar el paquete de fuentes para cjson`

Please help me.

Tanks.

**Comment by chancezeus** [comment]
@sagitariozod Ubuntu 24.04 uses a new way to define it's repositories/dependencies so the bash script will have to be changed, specifically the `sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list >/dev/null` command needs to be adapted to work modify `/etc/apt/sources.list.d/ubuntu.sources` by appending `deb-src` to the line `Types: deb`

I currently don't need i386 builds on my system anymore so I do not have a updated version for you...

**Comment by sagitariozod** [comment]
> @sagitariozod Ubuntu 24.04 uses a new way to define it's repositories/dependencies so the bash script will have to be changed, specifically the `sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list >/dev/null` command needs to be adapted to work and instead needs to modify `/etc/apt/sources.list.d/ubuntu.sources` by appending `deb-src` to the line `Types: deb`
> 
> I currently don't need i386 builds on my system anymore so I do not have a updated version for you...

Thanks for your reply, yes, I've already discovered this and now the process is progressing a bit more, but now I get a dependency error, I'll see if I can fix it.
I just need it to install wine:i386 and for the apt upgrade not to give me the message about retained packages

Thank you very much.
