### ISSUE TITLE
New grpc package breaks applications due to upstream bug

### ISSUE THREAD

**Issue by BHSPitMonkey** [oerdnj/deb.sury.org#1884]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**

Context in previous issue: #1877

The php-grpc packages [were recently rebuilt](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=grpc&field.status_filter=&field.series_filter=) (on 2022-12-09 and 2022-12-10) to bump the upstream version from 1.46.3 to 1.51.1.

Due to an upstream bug (see https://github.com/grpc/grpc/issues/31772), this appears to break PHP in many applications which use this extension. This seems related to some thread pooling changes which first appeared in 1.50.0, and there doesn't seem to be an upstream fix at this time. It may be worthwhile to pull the new packages for now (and either revert back to `1.46.3`, or perhaps add new packages for `1.49.0`). 

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**

```
Package: php8.0-grpc
Version: 1.51.1-2+ubuntu18.04.1+deb.sury.org+1
```

**Additional context**

- Upstream bug: https://github.com/grpc/grpc/issues/31772
- Previous (somewhat related) issue: #1877

**Comment by kenji21** [comment]
you were right, it appeared in 1.50.0 as a contributor stated [here](https://github.com/grpc/grpc/issues/31772#issuecomment-1353947274)

**Comment by oerdnj** [comment]
1.51.1+really.1.49.0-1 should be available for some time now.
