### ISSUE TITLE
php7.0-ds, php7.1-ds, and php7.2-ds packages for jammy are missing

### ISSUE THREAD

**Issue by datadestroyd** [oerdnj/deb.sury.org#1885]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
The php7.0-ds, php7.1-ds, and php7.2-ds packages for jammy are missing (7.3+ exist).

**To Reproduce**
```
$ apt install --recon php7.2-ds
E: Unable to locate package php7.2-ds
E: Couldn't find any package by glob 'php7.2-ds'
````

**Your understanding of what is happening**
The packages have not been built for jammy (they are available on bionic and focal). I have manually checked https://ppa.launchpadcontent.net/ondrej/php/ubuntu/pool/main/p/php-ds/ to verify.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04 ("jammy")
 - Architecture: amd64
 - Repository: Ubuntu PPA or packages.sury.org

**Comment by oerdnj** [comment]
Yep, that's the upstream thing:
```
 <dependencies>
  <required>
   <php>
    <min>7.3.0</min>
   </php>
   <pearinstaller>
    <min>1.4.0b1</min>
   </pearinstaller>
  </required>
 </dependencies>
```

I'll make a note to prepare a legacy package from `php-ds 1.3.0`

**Comment by oerdnj** [comment]
It's building now.
