### ISSUE TITLE
Locking to PHP 8.1

### ISSUE THREAD

**Issue by aquavark** [oerdnj/deb.sury.org#1886]
Hi,

Firstly, thanks for this great service that you provide.

Is there a good or easy way to temporarily lock to PHP 8.1 only now you've updated the base to 8.2? I have 8.1 installed from here on a few servers, but I've not finished testing against 8.2 as of yet (and that includes things like the libraries for mssql from Microsoft needing to be built against the new PHP I assume). It's causing some difficulty in running updates on the servers and suddenly apps breaking.

I've tried with some pinning, but it seems I'm not catching everything and it wants to upgrade "bits", and those bits vary across the servers.

Thanks

**Comment by oerdnj** [comment]
Why bother using issue template or reading FAQ when you can ask, right?
