### ISSUE TITLE
Extension request: php-eximer

### ISSUE THREAD

**Issue by Krinkle** [oerdnj/deb.sury.org#1889]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Not a problem, but a request for the <https://pecl.php.net/package/excimer> package to be included. We've already upstreamed it to Debian, where it's been in stable for a few years at <https://packages.debian.org/stable/php-excimer>.

**Describe the solution you'd like**
Creating `php-excimer` and `php8.1-excimer`.

**Describe alternatives you've considered**
Installing pecl, and instructing users to find the right PHP version etc directory and adding INI files to apache, cli, fpm subdirecotires. Depending on where Wikimedia is in its development and PHP upgrade cycle, we sometimes use Debian directly in CI and for local development, but most of the time we use Sury there, where instructions like `apt-get install php-excimer` currently don't work during those months, making setup a bit more involved.

**Distribution (please complete the following information):**
 - OS: Debian 10 Buster
 - Architecture: x86_64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
So, the minimum supported PHP version is PHP 7.1, am I reading that right?

**Comment by oerdnj** [comment]
Unfortunately, the `php-excimer` is just stitched together instead of using `dh-php`, so I'll have to prepare the packaging from the scratch for my repositories. I'll submit it back to Kunal when it's ready.

**Comment by oerdnj** [comment]
Done, thanks to the upstream for standard and well maintained extension.
