### ISSUE TITLE
Requesting bump of php8.1-xhprof and php8.2-xhprof to 2.3.9

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1890]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**

The 2.3.8 php8.1-xhprof and php8.2-xhprof had a SEGV, which seems to be fixed in 2.3.9

**To Reproduce**

* https://github.com/longxinH/xhprof/issues/76
* Reproduction repo in https://github.com/rfay/xhprof-bug-demo

**Your understanding of what is happening**

Users reported a double-free bug.

**What steps did you take to resolve issue yourself before reporting it here**

* Created an issue for https://github.com/longxinH/xhprof
* Created reproduction technique
* Tested manually the new 2.3.9 release

**Expected behavior**

No SEGV

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: both arm64 and amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**

```
$ apt-cache policy php8.2-xhprof
php8.2-xhprof:
  Installed: 2.3.8+0.9.4-1+0~20221209.18+debian11~1.gbp8f76ce
  Candidate: 2.3.8+0.9.4-1+0~20221209.18+debian11~1.gbp8f76ce
  Version table:
 *** 2.3.8+0.9.4-1+0~20221209.18+debian11~1.gbp8f76ce 500
        500 https://packages.sury.org/php bullseye/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by oerdnj** [comment]
Done

**Comment by rfay** [comment]
Wow!

**Comment by oerdnj** [comment]
Send your thanks to mulled wine ;)
