### ISSUE TITLE
Ubuntu php8.2-pcov not available yet

### ISSUE THREAD

**Issue by spaze** [oerdnj/deb.sury.org#1891]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

Hi, can you please check and prepare/build php8.2-pcov Ubuntu extension? I have seen it mentioned several times in #1840 (and have waited a few days before filing this 😅) but can't find it here so maybe it got overlooked or possibly there's a hidden issue somewhere https://ppa.launchpadcontent.net/ondrej/php/ubuntu/pool/main/p/php-pcov/

Thank you!

**Comment by oerdnj** [comment]
Yeah, the upload to PPA has failed for some reason. Uploaded, it should be available in couple minutes.
