### ISSUE TITLE
php8.2-solr missing

### ISSUE THREAD

**Issue by sunkan** [oerdnj/deb.sury.org#1892]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**
The php8.2-solr package is missing. 

**To Reproduce**
```
> apt install php8.2-solr

E: Package 'php8.2-solr' has no installation candidate
```

**Your understanding of what is happening**
The package don't seems to have been built for php8.2
https://ppa.launchpadcontent.net/ondrej/php/ubuntu/pool/main/p/php-solr/

**Distribution (please complete the following information):**
 - OS: Debian Bullseye and Ubuntu 18.04 and 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA both packages.sury.org

**Comment by bix0r** [comment]
@oerdnj Can you take a look at this? Seems like the package should be built.

If you need anything from the upstream, just ping me (I am a maintainer of the solr extension).

**Comment by oerdnj** [comment]
I already fixed that in git, but didn't issue a rebuild - this has been fixed now. It should be available in couple minutes.

**Comment by oerdnj** [comment]
The `package.xml` version parser handles only minor.version, so it doesn't cope with `<max>8.2.99</min>` very well and needs manual intervention. I'll fix that some day...
