### ISSUE TITLE
php7.4 PPA PECL missing 22.04.x packages

### ISSUE THREAD

**Issue by zlaw-webmaster** [oerdnj/deb.sury.org#1893]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**

Certain packages that were built before ubuntu 22.04 was released (2022-04-21) are missing 22.04 counterparts to their packages.

**To Reproduce**
1. Try installing `php-pear` on ubuntu 22.04.1 (jammy)

**Your understanding of what is happening**
The last updates for certain packages all fall before the 22.04 LTS date (2022-04-21) and have not received any further updates, which would indicate that whatever system for builds ran before 22.04 was official and therefore were not built for/against them

Packages that were updated after this date are working as expected, with builds targeting 22.04.x building for the new repo. From what I can tell they are built from the same source and share a list of dependency versions and locks, so just seem to be missing the builds against 22.04.x

working packages:
- php-pecl-http-3 (2022-07-06)
- php-imagick (2022-12-09)

short list of affected packages:
- php-pear (2022-03)
- argon2 (2020-10)
- icu (2020-02)
- libidn2 (2020-04)
- libzip (2020-10)
- libzstd (2021-03)

etc...

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64, all
 - Repository: Ubuntu PPA `ppa:ondrej/php`

**Package(s) (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by oerdnj** [comment]
Yes, only missing packages or packages with significant differences are updated. What exactly is the problem here?

**Comment by zlaw-webmaster** [comment]
`php-pear` is dependent on `php8-cli` and `php8.2-xml` since it is being pulled from upstream and was causing conflict issues with a package I wanted to install, but that problem seems to be upstream. Sorry for the bother.

**Comment by oerdnj** [comment]
Then you haven’t read the FAQ, there’s whole section on it.
