### ISSUE TITLE
php7.4.33 ubuntu 22.04 amd64 reproducible segfault in stripslashes

### ISSUE THREAD

**Issue by martymcguire** [oerdnj/deb.sury.org#1894]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**

On Ubuntu 22.04 on ARM systems using php7.4 installed via `ppa:ondrej/php`, `stripslashes` hangs and segfaults on 16-character strings that end in a `\` character.

**To Reproduce**

Call `stripslashes` on any 16-character string ending in `\`. For example `stripslashes("1234567890abcde\\");`

Expected behavior: returns the string `1234567890abcde`.

Actual behavior: Segmentation Fault.

For example: 

```
$ php --version
PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:53) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

$ php -a
Interactive mode enabled

php > stripslashes("1234567890abcde\\");
Segmentation fault (core dumped)
```

This occurs on Ubuntu 22.04 on arm64 systems using php7.4 installed via `ppa:ondrej/php`.

The same does _not_ occur on amd64 based systems, same versions of Ubuntu and PHP:

```
$ php --version
PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

$ php -a
Interactive mode enabled

php > stripslashes("1234567890abcde\\");
php >
```

**Your understanding of what is happening**

I'm not sure. Some kind of bad memory access in string handling?

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: arm64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

```
$ apt-cache policy php7.4-cli
php7.4-cli:
  Installed: 1:7.4.33-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1:7.4.33-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1:7.4.33-1+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Your report is very confusing. Could you clarify the architecture where is this happening? It seems like it’s **arm64**, but you are also talking about **amd64**.

Also can you get a backtrace with debug symbols installed (see the wiki here on how to enable and add debug symbols.)

**Comment by martymcguire** [comment]
Thanks for the response. I definitely goofed the original and have now updated. The segfault happens on arm64 and _not_ amd64.

will try the debug symbols next week!

**Comment by todeveni** [comment]
Reported upstream, since it happens with all deb.sury.org versions and pristine php-src build.

https://github.com/php/php-src/issues/10187

**Comment by martymcguire** [comment]
Thanks so much for reproducing and reporting upstream. Looks like a patch is happening!

**Comment by todeveni** [comment]
[Fix pushed to php-src](https://github.com/php/php-src/commit/4c9375e504a6ba15de56fcf6b630d8c95155057d).
If needed, @oerdnj could cherry pick the patch to 7.4 and 8.0 builds, since they're EOL and/or out of active support upstream.

**Comment by martymcguire** [comment]
That makes sense to me and would be very much appreciated! Of course I yield to the judgment of the maintainer. :pray:

**Comment by oerdnj** [comment]
I think I pulled the patch to all releases where the patch applies.  Rather try double-checking it, but I am closing this now.

**Comment by martymcguire** [comment]
Confirmed this no longer segfaults on the previously affected arm64 systems.

Thanks so much!!

```
$ php --version
PHP 7.4.33 (cli) (built: Jan 13 2023 10:42:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
ubuntu@ip-172-31-63-200:~$ php -a
Interactive mode enabled

php > echo stripslashes("1234567890abcde\\");
1234567890abcde
```
