### ISSUE TITLE
php8.0-fpm and php8.1-fpm  - installation fails - missing configuration file

### ISSUE THREAD

**Issue by pbousek** [oerdnj/deb.sury.org#1897]
Hello ,
i just tried to install php8.0-fpm and php8.1-fpm packages - both installations ends with same result: 

ERROR: failed to open configuration file '/etc/php/8.0/fpm/php-fpm.conf': No such file or directory (2)

I try to remove all php packages and do clean install (completely removed all php* packages, rm -rf /etc/php/8.*) with same result.

OS Debian 11.6

Complete installation procedure error message:
Jan 04 21:23:29 parsery systemd[1]: Starting The PHP 8.0 FastCGI Process Manager...
Jan 04 21:23:29 parsery php-fpm8.0[2575880]: [04-Jan-2023 21:23:29] ERROR: failed to open configuration file '/etc/php/8.0/fpm/php-fpm.conf': No such file or directory (2)
Jan 04 21:23:29 parsery php-fpm8.0[2575880]: [04-Jan-2023 21:23:29] ERROR: failed to load configuration file '/etc/php/8.0/fpm/php-fpm.conf'
Jan 04 21:23:29 parsery php-fpm8.0[2575880]: [04-Jan-2023 21:23:29] ERROR: FPM initialization failed
Jan 04 21:23:29 parsery systemd[1]: php8.0-fpm.service: Main process exited, code=exited, status=78/CONFIG
Jan 04 21:23:29 parsery systemd[1]: php8.0-fpm.service: Failed with result 'exit-code'.
Jan 04 21:23:29 parsery systemd[1]: Failed to start The PHP 8.0 FastCGI Process Manager.
dpkg: error processing package php8.0-fpm (--configure):
 installed php8.0-fpm package post-installation script subprocess returned error exit status 1
Setting up php8.1-fpm (8.1.13-1+0~20221126.29+debian11~1.gbpfee7cc) ...
Job for php8.1-fpm.service failed because the control process exited with error code.
See "systemctl status php8.1-fpm.service" and "journalctl -xe" for details.
invoke-rc.d: initscript php8.1-fpm, action "start" failed.
● php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-01-04 21:23:30 CET; 6ms ago
       Docs: man:php-fpm8.1(8)
    Process: 2576643 ExecStart=/usr/sbin/php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf (code=exited, status=78)
    Process: 2576644 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
   Main PID: 2576643 (code=exited, status=78)
        CPU: 16ms

Jan 04 21:23:30 parsery systemd[1]: Starting The PHP 8.1 FastCGI Process Manager...
Jan 04 21:23:30 parsery php-fpm8.1[2576643]: [04-Jan-2023 21:23:30] ERROR: failed to open configuration file '/etc/php/8.1/fpm/php-fpm.conf': No such file or directory (2)
Jan 04 21:23:30 parsery php-fpm8.1[2576643]: [04-Jan-2023 21:23:30] ERROR: failed to load configuration file '/etc/php/8.1/fpm/php-fpm.conf'
Jan 04 21:23:30 parsery php-fpm8.1[2576643]: [04-Jan-2023 21:23:30] ERROR: FPM initialization failed
Jan 04 21:23:30 parsery systemd[1]: php8.1-fpm.service: Main process exited, code=exited, status=78/CONFIG
Jan 04 21:23:30 parsery systemd[1]: php8.1-fpm.service: Failed with result 'exit-code'.
Jan 04 21:23:30 parsery systemd[1]: Failed to start The PHP 8.1 FastCGI Process Manager.
dpkg: error processing package php8.1-fpm (--configure):
 installed php8.1-fpm package post-installation script subprocess returned error exit status 1

FPM directory  contains only those files:
ls -la /etc/php/8.0/fpm
total 96
drwxr-xr-x 4 root root  4096 Jan  4 21:23 .
drwxr-xr-x 5 root root  4096 Jan  4 21:23 ..
drwxr-xr-x 2 root root  4096 Jan  4 21:23 conf.d
-rw-r--r-- 1 root root  5458 Dec  5 22:59 php-fpm.conf.dpkg-divert
-rw-r--r-- 1 root root 72948 Dec  5 22:59 php.ini
drwxr-xr-x 2 root root  4096 Jan  4 21:23 pool.d

Problem is with packages:
php8.0-fpm_1%3a8.0.26-1+0~20221205.45+debian11~1.gbpfbda3f_amd64.deb
php8.1-fpm_8.1.13-1+0~20221126.29+debian11~1.gbpfee7cc_amd64.deb

Both deb packages cointain php-fpm.conf.

Interesting is that php8.2-fpm works fine. (php8.2-fpm_8.2.0-1+0~20221208.9+debian11~1.gbp03fa1d_amd64.deb).

**Comment by oerdnj** [comment]
Only you know what you did to your system. The `.dpkg-divert` file hints that. There's no issue with the packaged - you might try asking for help in the discussions.
