### ISSUE TITLE
JSON silently dies in Trusty

### ISSUE THREAD

**Issue by lastguru1** [oerdnj/deb.sury.org#190]
Given the end of support for Precise, I just upgraded to Trusty and discovered an unpleasant surprise: json_decode function silently dies (php stops executing script, i.e. next line is not executed - no errors displayed, no nothing) when is being run from php-fpm. It works if run from command line.

The version I was running is 5.6.16, however, downgrading to 5.5.30 from your repository did not help. Everything started working fine, when I downgraded all to the default php version of Trusty - 5.5.9. Upgrading from that to 5.6.16 broke json_decode once again. Downgrading back to Trusty php fixed the issue once again.

**Comment by lastguru1** [comment]
Additional info:

1. This is a 32bit OpenVZ VPS

2. Still using Trusty php 5.5.9, I have upgraded libjson-c2 and libjson0 to the ones in your repository. Everything is still working. So the problem is probably in php5-json package.

**Comment by oerdnj** [comment]
Could you try upgrading just php5-json package and see what happens?

**Comment by lastguru1** [comment]
It is not possible, unfortunately, as Trusty php 5.5.9 provides phpapi-20121212+lfs, php5-json from php5 repository depends on phpapi-20121212 and php5-json from php5-5.6 repository depends on phpapi-20131226

**Comment by oerdnj** [comment]
You can use updated php5-json from ppa:ondrej/php5

--
Ondřej Surý

**Comment by lastguru1** [comment]
Sorry, no new packages there yet

**Comment by oerdnj** [comment]
https://launchpad.net/~ondrej/+archive/ubuntu/php5 (aka ppa:ondrej/php5) most certainly contains 1.3.9-1+deb.sury.org~trusty+3, but you have to remove the ppa:ondrej/php5-5.6 first (both ppa's cannot coexist).

**Comment by lastguru1** [comment]
Yes, it does contain that package. It was built on 2015-12-10 and has the dependency issue I described earlier.

# apt-cache show php5-json
Package: php5-json
Source: php-json
Priority: optional
Section: php
Installed-Size: 146
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: i386
Version: 1.3.9-1+deb.sury.org~trusty+3
Replaces: php5-dev (<< 5.5.0~rc1+dfsg-1~)
Depends: libc6 (>= 2.8), phpapi-20121212, ucf
Filename: pool/main/p/php-json/php5-json_1.3.9-1+deb.sury.org~trusty+3_i386.deb

Trusty php5-json has these dependencies:
Depends: libc6 (>= 2.8), phpapi-20121212+lfs, ucf, libjson-c2 (>= 0.11-3~)

So, as I told previously, your package cannot be installed without installing full php package set from you.

**Comment by oerdnj** [comment]
Then you'll have to recompile the php5-json localy with something like:
1. Remove the PHP PPAs
2. Get the current sources: `dget https://launchpad.net/~ondrej/+archive/ubuntu/php5/+files/php-json_1.3.9-1%2Bdeb.sury.org%7Etrusty%2B3.dsc`
3. Install build dependencies: `sudo apt-get build-dep php-json` + `sudo apt-get install devscripts`
4. Build the package locally: `cd php-json-*/` && `debuild`

**Comment by lastguru1** [comment]
ok, I have recompiled the package locally. the result is the same: json_decode dies. :(

**Comment by oerdnj** [comment]
Then you should report that preferably with a test case and backtrace to @remicollet here: https://github.com/remicollet/pecl-json-c

**Comment by oerdnj** [comment]
PHP 5.6 packages are now provided from `ppa:ondrej/php` with native json extension (as we don't care that much about JSON-IS-EVIL license in PPAs). That should fix any issues you might have with pecl-json-c.
