### ISSUE TITLE
Imagick extension for PHP version 8.2.0

### ISSUE THREAD

**Issue by whiteCosmic** [oerdnj/deb.sury.org#1907]
I'm using XAMPP and PHP version 8.2.0(Windows).

I'm looking for an Imagick version that is compatible with PHP 8.2.0
on [peck.php.net](http://peck.php.net/) I could only find Imagick 3.7.0 which is compatible with PHP 7.4, 8.0, and 8.1.

After installing and enabling the 8.1 DLL I got the error message on my apache err log:
"PHP Warning:  PHP Startup: Imagick: Unable to initialize module\nModule compiled with module API=20210902\nPHP    compiled with module API=20220829\nThese options need to match\n in"

**Comment by whiteCosmic** [comment]
@oerdnj Why did you close my discussion without an answer to the issue?

**Comment by rfay** [comment]
@whiteCosmic this project has nothing to do with Windows extensions. It's Debian and Ubuntu only. So completely unrelated to your needs. If you're working on Windows, maybe you'll want to try the project I maintain, [DDEV](https://ddev.readthedocs.io), which runs on Windows, has all these packages, and is a full local development environment.

**Comment by oerdnj** [comment]
And why do you think I have to answer your completely random and irrelevant question about running PHP on Windows?

**Comment by whiteCosmic** [comment]
@oerdnj I appologize.
I'm new to this forum and wasn't aware that I'm asking the wrong question at the wrong place.
Just got a little frustrated for not finding this dll compatible to my PHP version.
sorry.
