### ISSUE TITLE
PHP 8.1 bcmath missing

### ISSUE THREAD

**Issue by zofe** [oerdnj/deb.sury.org#1909]
apt install php8.1-bcmath

https://packages.sury.org/php/pool/main/p/php8.1/php8.1-bcmath_8.1.13-1+0~20221126.29+debian10~1.gbpfee7cc_amd64.deb  404  Not Found [IP: 84.17.59.115 443]

**Comment by oerdnj** [comment]
Yes, that's correct.

**Comment by zofe** [comment]
there is an alternative source to install php8.1-bcmath on my debian 10?
sorry for the question 
thanks
