### ISSUE TITLE
request for 'php7-fpm'

### ISSUE THREAD

**Issue by creativeprogramming** [oerdnj/deb.sury.org#191]
Does this PPA has also a php7-fpm or is just for apache mod_php?

https://www.howtoforge.com/tutorial/how-to-install-php-7-on-debian/

If not please consider to build also a package for php7-fpm as many users (nginx users, apache fastcgi users) will be happy to have it.

Thanks, great work anyway

**Comment by oerdnj** [comment]
Which PPA? And you know there's a list of my PPAs, right? Just check them...
