### ISSUE TITLE
Apache2 unmet dependencies on Ubuntu 20.04

### ISSUE THREAD

**Issue by LittleGreyDuck** [oerdnj/deb.sury.org#1912]
Ran the package upgrades this morning, and now there's no apache2 at all. 'apt install apache2' returns:

The following packages have unmet dependencies:
 apache2 : Depends: media-types but it is not installable
           Recommends: ssl-cert but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I don't get the 'ssl-cert' line on my other 20.04 server, but the 'media-types' line shows up on both.

**Comment by oerdnj** [comment]
This is not a bug report, this is rant. Don't skip the issue template.

**Comment by oerdnj** [comment]
This is how the bug report that helps quickly diagnose the issue look like: https://github.com/oerdnj/deb.sury.org/issues/1913

**Comment by LittleGreyDuck** [comment]
My apologies, I was opting for brevity and a concise report rather than an
overly lengthy post. I was in the wrong.
