### ISSUE TITLE
`apache2` 2.4.55-1+ubuntu20.04.1+deb.sury.org+1 depends on `media-types` which is not installable

### ISSUE THREAD

**Issue by m-ueberall** [oerdnj/deb.sury.org#1913]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I ~~have tried to resolve the issue myself and~~ will describe what I did in clear and concise manner

**Describe the bug**
The current `apache2` package cannot be installed on Ubuntu Focal (20.04) as the dependency `media-types` is not available.

**To Reproduce**

```
[2023-01-19T20:37:44+0100] root@desktop01:/tmp# LANG=C apt install apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: media-types but it is not installable
E: Unable to correct problems, you have held broken packages.
[2023-01-19T20:38:05+0100] root@desktop01:/tmp# LANG=C apt policy apache2
apache2:
  Installed: 2.4.54-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 2.4.55-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
     2.4.55-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 Packages
 *** 2.4.54-1+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     2.4.41-4ubuntu3.12 500
        500 http://de.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.4.41-4ubuntu3 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
[2023-01-19T20:38:12+0100] root@desktop01:/tmp# LANG=C apt policy media-types
media-types:
  Installed: (none)
  Candidate: (none)
  Version table:
[2023-01-19T20:41:07+0100] root@desktop01:/tmp#
```

**Your understanding of what is happening**
The package depends on another which is only available starting with Ubuntu Jammy (22.04).

**Expected behavior**
The package can be installed.

**Distribution (please complete the following information):**
 - OS: Ubuntu Focal (20.04)
 - Architecture: amd64
 - Repository: Apache2 PPA (`ppa.launchpad.net/ondrej/apache2/ubuntu`)

**Comment by oerdnj** [comment]
Thanks, I pulled the Debian packaging and it seems to have already moved to the new package.  I'll fix that shortly.

**Comment by PresGas** [comment]
@oerdnj - sounds like you know what is up. We had an update that removed apache2. Appending relevant info just in case.

```
  Building dependency tree...
  Reading state information...
  Calculating upgrade...
  The following packages were automatically installed and are no longer required:
    apache2-data apache2-utils
    Use 'apt autoremove' to remove them.
    The following packages will be REMOVED:
      apache2
      The following packages will be upgraded:
        apache2-bin apache2-data apache2-suexec-custom apache2-utils
        4 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
        Need to get 1708 kB of archives.
        After this operation, 515 kB disk space will be freed.
        Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 apache2-bin amd64 2.4.55-1+ubuntu20.04.1+deb.sury.org+1 [1311 kB]
        Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 apache2-data all 2.4.55-1+ubuntu20.04.1+deb.sury.org+1 [160 kB]
        Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 apache2-suexec-custom amd64 2.4.55-1+ubuntu20.04.1+deb.sury.org+1 [84.6 kB]
        Get:4 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 apache2-utils amd64 2.4.55-1+ubuntu20.04.1+deb.sury.org+1 [151 kB]
        Fetched 1708 kB in 2s (839 kB/s)
        (Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 521277 files and directories currently installed.)\r
        Removing apache2 (2.4.54-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        (Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 521231 files and directories currently installed.)\r
        Preparing to unpack .../apache2-bin_2.4.55-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...\r
        Unpacking apache2-bin (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) over (2.4.54-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Preparing to unpack .../apache2-data_2.4.55-1+ubuntu20.04.1+deb.sury.org+1_all.deb ...\r
        Unpacking apache2-data (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) over (2.4.54-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Preparing to unpack .../apache2-suexec-custom_2.4.55-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...\r
        Unpacking apache2-suexec-custom (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) over (2.4.54-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Preparing to unpack .../apache2-utils_2.4.55-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...\r
        Unpacking apache2-utils (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) over (2.4.54-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Setting up apache2-bin (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Setting up apache2-suexec-custom (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Setting up apache2-data (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Setting up apache2-utils (2.4.55-1+ubuntu20.04.1+deb.sury.org+1) ...\r
        Processing triggers for man-db (2.9.1-1) ...\r
        ",

/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: media-types but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Do you plan on posting here when the fix is in?

**Comment by oerdnj** [comment]
It has been already uploaded and it's building.  FTR you should never do `apt-get dist-upgrade` unsupervised by human. The apt dependency resolver just **wants** to resolve dependencies, so you might end up with ... this.

**Comment by oerdnj** [comment]
Anyway, sorry for the breakage.  The Debian is before freeze, so these little cleanup things slip in.  I did want to upload this to apache2-qa first but then I have my home full of sick children for the last two weeks...

**Comment by PresGas** [comment]
We get sick kids over here. Thanks for the quick response for sure!! :tada:

**Comment by hknet** [comment]
this seems to be an issue still here

**Comment by kristous** [comment]
At the moment the repo is inconsistent for buster. Packages file lists 2.4.55 in pool there is only 2.4.54.

This gives us a hard time rolling back on broken systems. It would be really nice if the last two versions are in the repo. So I can easily rollback to the previous version if the update breaks something.

**Comment by oerdnj** [comment]
What exactly do you see? It looks all peachy on the builders, so I **always** need details.

**Comment by hknet** [comment]
on deb10:
apt list --all-versions apache2
Listing... Done
apache2/buster 2.4.55-1+0~20230120.29+debian10~1.gbpebbdae amd64 [upgradable from: 2.4.54-1+0~20220608.27+debian10~1.gbpa86151]
apache2/now 2.4.54-1+0~20220608.27+debian10~1.gbpa86151 amd64 [installed,upgradable to: 2.4.55-1+0~20230120.29+debian10~1.gbpebbdae]
apache2/oldstable 2.4.38-3+deb10u8 amd64
apache2/oldstable 2.4.38-3+deb10u7 amd64

but it seems the latest apache2 package is now fixed

**Comment by kristous** [comment]
https://packages.sury.org/apache2/dists/buster/main/binary-amd64/Packages lists Version 2.4.55

In https://packages.sury.org/apache2/pool/main/a/apache2/ there is only 2.4.54

So apt is not able to install neither

**Comment by oerdnj** [comment]
The directory listing is useless. Don't use that for diagnostics.  Only a direct hit can tell you if the package is or isn't there.

**Comment by oerdnj** [comment]
> but it seems the latest apache2 package is now fixed

I've issued a new rebuild as quick remedy.

**Comment by kristous** [comment]
> The directory listing is useless. Don't use that for diagnostics. Only a direct hit can tell you if the package is or isn't there.

okay, was just trying to figure out what was the problem after I fixed the broken servers.

What about my "feature request" in having the last two versions in the repo so that a rollback can easily done by issuing
apt-get install apache2=2.4.54.......

**Comment by oerdnj** [comment]
The tool I am using can't do that, see reprepro FAQ: https://github.com/Noctem/reprepro/blob/master/docs/FAQ 3.1

**Comment by kristous** [comment]
> The tool I am using can't do that, see reprepro FAQ: https://github.com/Noctem/reprepro/blob/master/docs/FAQ 3.1

strange, the must have removed it. I have done such a thing in the past with reprepo.
The call we used was
reprepro --ask-passphrase includedeb bionic /tmp/myapp_1.3.0p1-1_all.deb

This added the new deb file and preserved the old one

**Comment by m-ueberall** [comment]
> > The tool I am using can't do that, see reprepro FAQ: [Noctem/reprepro@`master`/docs/FAQ](https://github.com/Noctem/reprepro/blob/master/docs/FAQ?rgh-link-date=2023-01-20T08%3A31%3A03Z) 3.1
> strange, the must have removed it. I have done such a thing in the past with reprepo. The call we used was reprepro --ask-passphrase includedeb bionic /tmp/myapp_1.3.0p1-1_all.deb

It's a bit OT, but have a look at [Debian Bug report logs – #570623 reprepro: please add multiple version management](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570623) (cf. https://packages.debian.org/experimental/reprepro).
