### ISSUE TITLE
https://deb.sury.org is unresponsive

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1919]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
I'm sure you already know this, but `deb.sury.org` is not responding.

```
$ curl -v https://deb.sury.org
*   Trying 89.187.130.10:443...
* connect to 89.187.130.10 port 443 failed: Operation timed out
* Failed to connect to deb.sury.org port 443 after 75575 ms: Couldn't connect to server
* Closing connection 0
curl: (28) Failed to connect to deb.sury.org port 443 after 75575 ms: Couldn't connect to server
```

And it never gets any farther. 

I have also tried from direct internet-connected host:
```
$ curl -v https://deb.sury.org
$ curl -v https://deb.sury.org
*   Trying 2a01:5f0:c001:113:a::10:443...
* TCP_NODELAY set
*   Trying 89.187.130.10:443...
* TCP_NODELAY set
* connect to 2a01:5f0:c001:113:a::10 port 443 failed: No route to host
```

**To Reproduce**

Above.

**Your understanding of what is happening**

Broken webserver

**What steps did you take to resolve issue yourself before reporting it here**

Explained above

**Expected behavior**

Working website.

**Comment by oerdnj** [comment]
Yeah, when the machine reboots for whatever reason, the encryption key needs to be entered manually. I have no clue why it rebooted, but it's up again.

**Comment by rfay** [comment]
Thanks, it was down a couple of days; DDEV docs have link checker and there's a reference to deb.sury.org. I finally went and actually checked what was wrong :)

**Comment by oerdnj** [comment]
I should probably migrate the remnants of that server somewhere "to the cloud" and decommission the physical machine.

**Comment by oerdnj** [comment]
deb.sury.org is now fully hosted on GitHub - previously, the frontend was separate server because GH didn't do certificates and IPv6, but that is all now fixed, so there's no reason to keep the deb.sury.org hosted elsewhere.
