### ISSUE TITLE
apt-get install cannot install packages - Internal Server Error, probably CDN problem

### ISSUE THREAD

**Issue by cerven** [oerdnj/deb.sury.org#1920]
Hello,

I have a problem with installing php7.4 packages:

![image](https://user-images.githubusercontent.com/4920767/215503814-e6cfac79-aaa0-4456-83aa-b019ab8e1dce.png)

It happens only on our CI/CD solution. Locally from another location it works, so I think it is a CDN or some configuration problem.

**Comment by cerven** [comment]
I'm getting another errors, but it is also on Bitbucket, so could be related.

**Comment by accrisoftteam** [comment]
> It might be related. We just faced the following issue within our pipelines on Bitbucket:
> 
> ```
> #11 0.355 + apt-get update
> #11 0.394 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
> #11 0.405 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
> #11 0.405 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
> #11 0.445 Get:4 https://packages.sury.org/php bullseye InRelease
> #11 0.445 Err:4 https://packages.sury.org/php bullseye InRelease
> #11 0.445   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> #11 0.500 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
> #11 0.597 Get:6 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [218 kB]
> #11 0.688 Get:7 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
> #11 1.628 Reading package lists...
> #11 2.147 E: Failed to fetch https://packages.sury.org/php/dists/bullseye/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> #11 2.147 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
> #11 2.147 Error executing command, exiting
> ```
> 
> It works locally and sometimes goes through with a successful build on Bitbucket.

+1 `Clearsigned file isn't valid, got 'NOSPLIT'` on AWS CodeBuild

**Comment by lyrixx** [comment]
And we have the same issue(`Clearsigned file isn't valid, got 'NOSPLIT'`) on GithubAction and Circle CI.

Bit I cannot reproduce it locally.

Our Dockerfile to reproduce:

```Dockerfile
FROM debian:buster as builder

RUN apt update \
    && apt install -y ca-certificates apt-transport-https wget gnupg curl lsb-release \
    && curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list \
    && apt update \
```

**Comment by kafeolic-nuglif** [comment]
We have the same problem, sometimes it works, other times it fails with the error that other users reported. So its not reliable at the moment.

**Comment by rfay** [comment]
Tests failing here too, for about 12-18 hours now:

```
        	            	 > [drud/ddev-webserver:20230128_xdebug_build_time-TestPkgDrupal9-built 3/5] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.0-tidy:
        	            	Failed to fetch https://packages.sury.org/php/dists/bullseye/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
        	            	#11 3.802 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
        	            	------
        	            	', stderr='failed to solve: executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.0-tidy]: exit code: 100'
```

**Comment by oerdnj** [comment]
https://status.bunny.net says only that their API and Dashboard has problem, but I am guessing this might be more widespread than that.

**Comment by oerdnj** [comment]
cc @BunnyWay

**Comment by oerdnj** [comment]
Reported as Ticket #186706 to @bunnyway

**Comment by oerdnj** [comment]
I’ve purged the cache, can you retest?

**Comment by lyrixx** [comment]
It seems good! Thanks (I ran only one build ATM)

**Comment by accrisoftteam** [comment]
+1 no more error on single build test

**Comment by kafeolic-nuglif** [comment]
+1 seems good now. Thanks!

**Comment by artttj** [comment]
+1 it worked for us, thanks

**Comment by cerven** [comment]
Works also here. Thanks. Closing.

**Comment by B0GDAN** [comment]
Hi all,

I seem to have the issue described here for more than a week already

root@raspbx:~# sudo apt update && sudo apt upgrade -y
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease     
Hit:4 http://repo.raspbx.org/apt/debian buster InRelease            
Get:3 https://packages.sury.org/php buster InRelease                
Err:3 https://packages.sury.org/php buster InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/buster/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.sury.org/php buster InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Cheers!
Bogdan

**Comment by mazdel** [comment]
> Hi all,
> 
> I seem to have the issue described here for more than a week already
> 
> ```
> root@raspbx:~# sudo apt update && sudo apt upgrade -y
> Hit:1 http://archive.raspberrypi.org/debian buster InRelease
> Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease     
> Hit:4 http://repo.raspbx.org/apt/debian buster InRelease            
> Get:3 https://packages.sury.org/php buster InRelease                
> Err:3 https://packages.sury.org/php buster InRelease
>   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> Reading package lists... Done
> E: Failed to fetch https://packages.sury.org/php/dists/buster/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> E: The repository 'https://packages.sury.org/php buster InRelease' is no longer signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> Cheers! Bogdan

I got that error too, on my Arm64 home server. even though last month was fine when I upgraded my PHP to 8.3

**Comment by rfay** [comment]
@B0GDAN @mazdel your problem is completely unrelated. Debian buster support has been completely removed. 

See
* https://github.com/oerdnj/deb.sury.org/issues/2098

**Comment by davidcsi** [comment]
```
Err:4 https://packages.sury.org/php buster InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

I'm also getting that now

**Comment by rfay** [comment]
See 
* https://github.com/oerdnj/deb.sury.org/issues/2046
