### ISSUE TITLE
Connection refused, Failed to fetch https://packages.sury.org/php/dists/bullseye/InRelease

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#1923]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

I'm intermittently seeing quite a number of these on different machines in different networks:

`#0 6.209 W: Failed to fetch https://packages.sury.org/php/dists/bullseye/InRelease  Could not connect to packages.sury.org:443 (104.218.233.175). - connect (111: Connection refused)`
 
**To Reproduce**

Sadly, it's intermittent, but has happened enough times now that I thought I should say something.

**Your understanding of what is happening**

packages.sury.org is refusing connections.

**What steps did you take to resolve issue yourself before reporting it here**

I watched it for (a couple of days?)

**Expected behavior**

Should be able to get packages.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: both
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Is the IP address always the same?

**Comment by rfay** [comment]
I will monitor it.

**Comment by rfay** [comment]
Next time I see it I'll check the IP and also push a PR to add the curl.

**Comment by oerdnj** [comment]
@rfay Has it been stable since?

**Comment by rfay** [comment]
Haven't seen it, thanks for checking.
