### ISSUE TITLE
Nginx with HTTP/3 + QUIC

### ISSUE THREAD

**Issue by stevenzhu25** [oerdnj/deb.sury.org#1927]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
It would be nice to consider adding HTTP/3 + QUIC to Nginx builds when the new version is fully released. 

**Describe the solution you'd like**
Provide Nginx lite, regular and extras package with QUIC + HTTP/3 support in the future. 

**Describe alternatives you've considered**
Currently Nginx released a binary preview for HTTP/3, and according to their announcement several users already successfully built it themselves. 

I do not think it would be a easy upgrade from current Nginx to Nginx with HTTP/3, due to OpenSSL not supporting QUIC until maybe version 3.4. That means implementing HTTP/3 in Nginx would probably require other softwares. 

It would be nice if we can know whether there's currently any plan to bring HTTP/3 to Nginx in this repo, and what we can do to help!

If you understand the purpose of this issue tracker and describe your **request** accurately (where the template below will help), I might be able to help you.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Architecture: amd64 
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
Nginx announcement: https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

Nginx QUIC: https://quic.nginx.org/

**Comment by oerdnj** [comment]
FTR That's very unlikely to happen. I really don't want to go into business of packaging patched OpenSSL.

**Comment by stevenzhu25** [comment]
> FTR That's very unlikely to happen. I really don't want to go into business of packaging patched OpenSSL.

Understand! That's also what I thought would happen as well. Probably better to wait until OpenSSL 3.4 (and hope they don't take another version to fix all the bugs 😂)
Thanks!

**Comment by patschi** [comment]
FYI - Experimental HTTP/3 support was added in latest nginx 1.25 mainline. I thought I create update-request issue at #1958 for better tracking.

> What about **Brotli** though?

Brotli was implemented in March 2021: see https://github.com/oerdnj/deb.sury.org/issues/625#issuecomment-791909524.

**Comment by patschi** [comment]
This has been completed - 1.25.0 has been pushed to the repo.

**Comment by stevenzhu25** [comment]
Confirmed working!
Thanks for the update (@oerdnj  & @patschi)


To enable HTTP/3, you'll need to follow the configuration guide on Nginx.com, and add the headers like they did in Nginx.
https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/#configuration

Nginx HTTP3 Module config: https://nginx.org/en/docs/http/ngx_http_v3_module.html

P.S. 
You only need to specify `listen 443 quic reuseport;` in one of your server block, the rest should only use `listen 443 quic;`

e.g. 
default server block
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    # for better compatibility we recommend
    # using the same port number for QUIC and TCP
    listen 443 quic reuseport default_server; # QUIC
    listen 443 ssl http2 default_server;             # TCP
    listen [::]:443 quic reuseport default_server; # QUIC
    listen [::]:443 ssl http2 default_server;             # TCP

    ssl_certificate /path/to/signed_cert_plus_intermediates;
    ssl_certificate_key /path/to/private_key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    ssl_dhparam /path/to/dhparam;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # Enable QUIC and HTTP/3
    ssl_quic on;
    ssl_early_data on;
    add_header Alt-Svc 'h3=":$server_port"; ma=86400';
    add_header X-protocol $server_protocol always;      

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

    # replace with the IP address of your resolver
    resolver 127.0.0.1;
}

```

additional server block
```
server {
    # for better compatibility we recommend
    # using the same port number for QUIC and TCP
    listen 443 quic; # QUIC
    listen 443 ssl http2;             # TCP
    listen [::]:443 quic; # QUIC
    listen [::]:443 ssl http2;             # TCP
    ssl_certificate /path/to/signed_cert_plus_intermediates;
    ssl_certificate_key /path/to/private_key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    ssl_dhparam /path/to/dhparam;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # Enable QUIC and HTTP/3
    ssl_quic on;
    ssl_early_data on;
    add_header Alt-Svc 'h3=":$server_port"; ma=86400';
    add_header X-protocol $server_protocol always;        

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

    # replace with the IP address of your resolver
    resolver 127.0.0.1;
}
```

Credit:
```
# generated 2023-05-28, Mozilla Guideline v5.7, nginx 1.25.0, OpenSSL 3.1.0, intermediate configuration
# https://ssl-config.mozilla.org/#server=nginx&version=1.25.0&config=intermediate&openssl=3.1.0&guideline=5.7
```

**Comment by NielsH** [comment]
Hi @oerdnj 

Thanks for adding this for Ubuntu! 
Will nginx 1.25 also be made available for Debian or will it not be possible to update it there due to the older OpenSSL version?

**Comment by lamka02sk** [comment]
Hi, I am wondering why are we not seeing nginx 1.25 available for Ubuntu while others here mentioned, it is available?
Is it because we are using aarch64?
Thank you

**Comment by szhu25** [comment]
> Hi, I am wondering why are we not seeing nginx 1.25 available for Ubuntu while others here mentioned that it is available?
> Is it because we are using aarch64?
> Thank you

If you are not on any of the currently supported Ubuntu LTS, you probably won't see further Nginx update. Do you know what's your OS version? (I don't know about the architecture part)

**Comment by lamka02sk** [comment]
> If you are not on any of the currently supported Ubuntu LTS, you probably won't see further Nginx update. Do you know what's your OS version? (I don't know about the architecture part)

It is Ubuntu 22.04 LTS. The latest LTS version.

**Comment by lamka02sk** [comment]
> Are you sure you are running `nginx-mainline` ppa ?

I didn't know that there are 2 ppas. We were running `nginx` ppa. Thank you
