### ISSUE TITLE
pq extension support

### ISSUE THREAD

**Issue by siilike** [oerdnj/deb.sury.org#1929]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
It would be great to also have the [pq](https://pecl.php.net/package/pq) extension packaged. It works great, is significantly faster than PDO, and provides some features not available neither in PDO nor in the pgsql extension.

It depends on raphf (already packaged) and libpq (already needed for pgsql/PDO).

**Describe alternatives you've considered**
Currently we package it manually.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
Uploaded, just give it a little time to build.
