### ISSUE TITLE
Dependencies needed to install PhpMyAdmin (php-seclib - php-gettext)

### ISSUE THREAD

**Issue by Paviluf** [oerdnj/deb.sury.org#193]
Some dependencies are needed in order to install PhpMyAdmin (from this PPA ppa:nijel/phpmyadmin that is compatible with PHP 7). 

- php-seclib
- php-gettext

Here is some infos about the packages on Ubuntu 15.10 :

[apt-cache show phpmyadmin](http://pastebin.com/pFdDmsgq)
[apt-cache show php-seclib](http://pastebin.com/6pbWYhLz)
[apt-cache show php-gettext](http://pastebin.com/0z09hCkf)

Thanks

**Comment by oerdnj** [comment]
Checked it, and it cannot be done right now, as pkg-php-tools needs to be converted to PHP 7.0 (DONE), and whole underlying PEAR stack needs to be converted (that needs to be done in Debian first and requires substantial amount of work).

**Comment by oerdnj** [comment]
As soon as 7.0.1-3+deb.sury.org~<dist>+1 has finished building, try temporarily adding ppa:ondrej/sandbox that provides transitional packages from php5* to php* counterparts.

**Comment by oerdnj** [comment]
You don't have to add the sandbox PPA, I have already uploaded the transitional packages to main PHP PPAs, and those packages might be installable again:
```
sudo apt-get install php-seclib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  php5-common
Suggested packages:
  php5-mcrypt php5-gmp php-compat
The following NEW packages will be installed:
  php-seclib php5-common
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 172 kB of archives.
After this operation, 1.247 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by Paviluf** [comment]
Thanks a lot for this, it was fast.
I will try as soon as I can.

**Comment by Paviluf** [comment]
I can now install phpmyadmin (thanks !) but (and I didn't tried before) the php code (a phpinfo() file in /var/www/html and phpmydamin) is not executed and is displayed like a html file. This is what I did to install LAMP :

$ sudo apt-get install python-software-properties && sudo add-apt-repository -y ppa:ondrej/php-7.0 && sudo add-apt-repository -y ppa:nijel/phpmyadmin && sudo apt-get update && sudo apt-get install apache2 mysql-server php5 php5-mysql php7.0 php7.0-fpm php7.0-mysql php7.0-gd phpmyadmin

Is it something to do ?

**Comment by oerdnj** [comment]
You need to configure the binding between PHP FPM and Apache2. It's not automatic.

**Comment by Paviluf** [comment]
On the few tutorials I found it's not explained at all.

- http://askubuntu.com/questions/705880/how-to-install-php-7
- https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04

I searched "binding between PHP Apache2" but I found nothing interesting. I hope I don't ask too much but could you please say me how to do that ? Thanks !

**Comment by oerdnj** [comment]
https://wiki.apache.org/httpd/PHP-FPM

and definitely use mod_proxy_fcgi (not mod_fastcgi) with Apache 2.4:

https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html

**Comment by Paviluf** [comment]
Thank you !

**Comment by Paviluf** [comment]
Thanks to this comment it's a lot easier to "activate" PHP 7 ;)

http://askubuntu.com/questions/705880/how-to-install-php-7#comment1042823_705893

```
$ sudo apt-get install libapache2-mod-php7.0
$ sudo a2enmod php7.0
```
