### ISSUE TITLE
A statusfile/timestamp for rsync.sury.org to make mirroring even more efficient

### ISSUE THREAD

**Issue by Robert-Riedl** [oerdnj/deb.sury.org#1936]
**Frequently asked questions**

- [ X ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

I'm mirroring your repository and would like to limit the amount of req we have to run and traffic we generate.

**Describe the solution you'd like**
A status file to check against, maybe at top level were the README.txt lives.
This way we could check a single file to see if there have been changes and a "full" rsync is warranted and use things like

`rsync --no-motd --dry-run --out-format="%n" "${src}/${statusfile}" "${dst}/${statusfile}"`

is done here https://github.com/rocky-linux/rocky-tools/blob/main/mirror/mirrorsync.sh

Debian and Ubuntu do that with "ls-lR.gz"

i.e: https://security.debian.org/debian-security/ls-lR.gz

but a simple file with a timestamp, that is updated when you push to your mirror, would suffice.

**Describe alternatives you've considered**

Alternatively we just run the rsync as it is

**Distribution (please complete the following information):**

this is not relevant

**Package(s) (please complete the following information):**

also not relevant

**Additional context**

none

**Comment by Robert-Riedl** [comment]
hey @oerdnj  - did you have time to review this request ?

**Comment by todeveni** [comment]
If you're just mirroring PHP-repo, you could use `/php/dists/$(lsb_release -sc)/Release` file, eg. `rsync://rsync.sury.org/repositories/php/dists/bookworm/Release`

If you're doing a full mirror, then a `ls-lR.txt` or something similar would be needed.

**Comment by Robert-Riedl** [comment]
I'm doing a full mirror, yes - so a per-release-solution isn't very feasible I'm afraid

**Comment by oerdnj** [comment]
This?
```
$ rsync rsync://rsync.sury.org/repositories/php/ls-lR.xz
-rw-r--r--            236 2023/05/12 10:19:30 ls-lR.xz
```

**Comment by Robert-Riedl** [comment]
thank you very much @oerdnj
