### ISSUE TITLE
PPA version of libgd3 amd64 and i386 can't be installed concurrently, breaks wine packages

### ISSUE THREAD

**Issue by kfazz** [oerdnj/deb.sury.org#1937]
On ubuntu jammy, using the ppa,
available libgd3 packages are:
i386: 2.3.3-6+ubuntu22.04.1+deb.sury.org+1
amd64:  2.3.3-9+ubuntu22.04.1+deb.sury.org+1
 ideally, these should be rebuild with the same version number as they can't be installed concurrently, which breaks with:
 > sudo apt install libgd3 libgd3:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd3 : Breaks: libgd3:i386 (!= 2.3.3-9+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-6+ubuntu22.04.1+deb.sury.org+1 is to be installed
 libgd3:i386 : Breaks: libgd3 (!= 2.3.3-6+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-9+ubuntu22.04.1+deb.sury.org+1 is to be installed

This breaks wine packages on my system from winehq that depend on having both versions installed concurrently

**Comment by oerdnj** [comment]
This is duplicate as simple search in the closed issues would show.
