### ISSUE TITLE
phpdismod unregisters module, but phpenmod doesn't reregister it

### ISSUE THREAD

**Issue by cmenning** [oerdnj/deb.sury.org#194]
When running ```phpdismod -v 7.0 -s ALL xdebug```, the xdebug module is unregistered. Running ```phpenmod -v 7.0 -s apache2 xdebug``` does not re-register the module, which is counter-intuitive.

This leads to confusing behavior where ```phpquery -v 7.0 -s apache2 -M``` does not list xdebug as an enabled module even though it is actually enabled (as verified by the contents of /etc/php/7.0/apache2/conf.d).

I can see two ways to make the behavior more intuitive:
1. Document the -r and -p arguments, and do not act on them unless they are explicitly set (as opposed to tying them in with "-s ALL").
2. Make registering the package default behavior.

**Comment by oerdnj** [comment]
Seems like you found a bug. The second command should definitely re-register the module.

**Comment by oerdnj** [comment]
Try attached patch:
```
diff --git a/phpenmod b/phpenmod
index 0297566..3366855 100755
--- a/phpenmod
+++ b/phpenmod
@@ -258,9 +258,10 @@ for mod in $@; do
     mods="${mods}${mods:+ }${mod%%/*}"
 done
 if [ "$register" = "no" ]; then
+    versions='${versions:-ALL}'
     sapis="${sapis:-ALL}"
 
-    if [ "$sapis" = "ALL" ]; then
+    if [ "$versions" = "ALL" -a "$sapis" = "ALL" ]; then
        register=yes
     fi
 fi
```

I am bit afraid of changing semantics of -r and -p, but I might have to refresh the memory why there's the automatic deregistration in case of '-s ALL'.

**Comment by oerdnj** [comment]
I think the automatic registry manipulation was added as a backwards compatibility layer for old extensions that didn't call php{en,dis}mod properly from the maintainer script. I might be able to drop it now as most (if not all) modules are using the phpenmodule properly.

**Comment by oerdnj** [comment]
Fixed in `php-defaults_21+coinst+deb.sury.org~<dist>+1`, you'll need to re-register your already unregistered modules manually though.
