### ISSUE TITLE
apache packages for debian/buster missing Origin attribute.

### ISSUE THREAD

**Issue by hknet** [oerdnj/deb.sury.org#1942]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

The debian packages for the apache releases seem to have lost their "Origin" attribute.

grep -i origin /var/lib/apt/lists/packages.sury.org_apache2_dists_buster_InRelease -> nothing

grep -i origin /var/lib/apt/lists/packages.sury.org_php_dists_buster_InRelease
Origin: deb.sury.org

-> php packages have their Origin set.

---

on Ubuntu both have their Origin set:

grep -i origin /var/lib/apt/lists/ppa.launchpad.net_ondrej_apache2_ubuntu_dists_focal_InRelease
Origin: LP-PPA-ondrej-apache2

grep -i origin /var/lib/apt/lists/ppa.launchpad.net_ondrej_php_ubuntu_dists_focal_InRelease
Origin: LP-PPA-ondrej-php

---

while this does not hinder manual upgrading those packages it is the unattended-upgrades package that usually requires some sort of origin being set, otherwise those updates are not considered.

thx.

**Comment by oerdnj** [comment]
Done:
```
# grep -i origin /var/lib/apt/lists/packages.sury.org_apache2_dists_*_InRelease
Origin: deb.sury.org
```
