### ISSUE TITLE
Update request: nginx stable 1.24.0

### ISSUE THREAD

**Issue by patrikjuvonen** [oerdnj/deb.sury.org#1945]
Hi there!

nginx released a new stable version 1.24.0 (https://nginx.org/) (https://nginx.org/en/CHANGES-1.24)

**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Comment by smknstd** [comment]
+1

**Comment by smknstd** [comment]
@patrikjuvonen I guess this issue could be close :) It has been fixed 4 days ago

https://launchpad.net/~ondrej/+archive/ubuntu/nginx
![Screenshot 2023-05-30 at 09-07-49 PPA for NGINX Stable with HTTP_2 Ondřej Surý](https://github.com/oerdnj/deb.sury.org/assets/2412608/9e44c10d-a8bc-40a9-a3e5-a1daaf9960c5)

https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline
![Screenshot 2023-05-30 at 09-08-28 PPA for NGINX Mainline with HTTP_2 Ondřej Surý](https://github.com/oerdnj/deb.sury.org/assets/2412608/316efa23-155f-4a97-abef-5649bcccff92)

**Comment by todeveni** [comment]
> @patrikjuvonen I guess this issue could be close :) It has been fixed 4 days ago

Technically OP didn't specify distro. Ubuntu packages have been built and Debian packages are still waiting 🙂

**Comment by oerdnj** [comment]
Well, that's why I have the issue templates ready, so people fill in the details. Nevertheless, I've now triggered the Debian package builds.
