### ISSUE TITLE
php8.2.5 debian bullseye arm64 build failed?

### ISSUE THREAD

**Issue by jadeops** [oerdnj/deb.sury.org#1946]
Any idea if it failed? How to check?

Here (bullseye) https://packages.sury.org/php/dists/bullseye/main/binary-arm64/Packages

Only 2 packages are at `8.2.5` Everything else is at `8.2.4`
* php8.2
* php8.2-xsl

For `buster` https://packages.sury.org/php/dists/buster/main/binary-arm64/Packages everything is `8.2.5` (build success?)

**Comment by oerdnj** [comment]
Nothing failed. You are just impatient.
