### ISSUE TITLE
[php7.0] Missing memcached.so for PHP 5.6

### ISSUE THREAD

**Issue by AntonStoeckl** [oerdnj/deb.sury.org#195]
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcached.so' - /usr/lib/php/20131226/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.16-9+deb.sury.org~wily+1 (cli) 

I assume it should be included, because the mod is symlinked:

ls -la /etc/php/5.6/cli/conf.d/
.....
lrwxrwxrwx 1 root root   37 Dez 23 11:39 20-memcached.ini -> /etc/php/mods-available/memcached.ini

**Comment by oerdnj** [comment]
Fixed in php-memcached_2.2.0-51-ge573a6e+2.2.0-1+deb.sury.org~<dist>+1

**Comment by AntonStoeckl** [comment]
Fantastic, thx alot! :-)
