### ISSUE TITLE
Update request: swoole:5.0.2

### ISSUE THREAD

**Issue by mihaileu** [oerdnj/deb.sury.org#1950]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
There's a new version of swoole library 5.0.2 https://pecl.php.net/package/swoole/5.0.2

**Describe the solution you'd like**
support the new package 

**Distribution (please complete the following information):**
 - OS: Ubuntu]
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=jammy

**Comment by oerdnj** [comment]
swoole is at 5.1.1 now
