### ISSUE TITLE
wrong day in date php 8.2.5

### ISSUE THREAD

**Issue by wintstar** [oerdnj/deb.sury.org#1951]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

PHP Version
PHP 8.2.5

Operating System
Debian 5.10.162-1

I use the PPA from packages.sury.org

Since it is not clear what is the trigger of this bug, I would like to refer to this one.

https://github.com/php/php-src/issues/11136

**Comment by oerdnj** [comment]
https://github.com/php/php-src/issues/11136 has been closed, so I am closing this as well.
