### ISSUE TITLE
php-fpm > 7.4 relax package dependency on systemd

### ISSUE THREAD

**Issue by no2spam** [oerdnj/deb.sury.org#1953]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Packages fails to upgrade php8.2 when using deb.sury.org repository on Antix-22 Linux (Debian bullseye without systemd) and even advises to install apache2 related mods when nginx is in use. This is due Antix OS apt policy to block systemd packages so others Debian systems should not be affected at all.

**Describe the solution you'd like**
First preference: Drop or change systemd | systemd-tmpfiles depency to recommendation (incl libsystemd0). 
Second preference:  least keep dependencies as it was on php7.4-fpm package. 

In my limited understanding vanilla debian systems won't get affected at all as systemd is fully installed by default and all the required files are in place. 
Debian derivatives without systemd might require additional fiddling (to provide altertive to systemd-tmpfiles), but at least packages would upgrade in full without being held back due to unsolved dependencies.
PHP 8.2 packages in Devuan unstable repo seems to be exactly the same as in Debian so it seems they haven't started work on these packages yet.

**Describe alternatives you've considered**
One of the option is to manually rebuild future php-fpm packages without systemd package dependency. So far everything just worked out of the box due to minimal packaging dependency on systemd.

**Distribution (please complete the following information):**
 - OS: Antix-22 Debian 11 based
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
`apt-cache policy php-fpm php7.4-fpm php8.2-fpm
php-fpm:
  Installed: 2:7.4+76
  Candidate: 2:8.2+93+0~20230409.46+debian11~1.gbpdb4dcc
  Version table:
     2:8.2+93+0~20230409.46+debian11~1.gbpdb4dcc 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        500 https://packages.sury.org/php bullseye/main i386 Packages
 *** 2:7.4+76 500
        500 http://ftp.de.debian.org/debian bullseye/main amd64 Packages
        500 http://ftp.de.debian.org/debian bullseye/main i386 Packages
        100 /var/lib/dpkg/status
php7.4-fpm:
  Installed: 7.4.33-1+deb11u3
  Candidate: 1:7.4.33-5+0~20230409.78+debian11~1.gbpa1ea7f
  Version table:
     1:7.4.33-5+0~20230409.78+debian11~1.gbpa1ea7f 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
 *** 7.4.33-1+deb11u3 500
        500 http://security.debian.org bullseye-security/main amd64 Packages
        500 http://ftp.de.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
php8.2-fpm:
  Installed: (none)
  Candidate: 8.2.5-1+0~20230414.19+debian11~1.gbpbe24a6
  Version table:
     8.2.5-1+0~20230414.19+debian11~1.gbpbe24a6 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
`
PHP 7.4 FPM package dependencies
`apt-cache depends php7.4-fpm
php7.4-fpm
  Depends: libmagic1
  Depends: mime-support
  Depends: php7.4-cli
  Depends: php7.4-common
  Depends: php7.4-json
  Depends: php7.4-opcache
  Depends: procps
    procps:i386
  Depends: tzdata
  Depends: ucf
  Depends: libacl1
  Depends: libapparmor1
  Depends: libargon2-1
  Depends: libc6
  Depends: libpcre2-8-0
  Depends: libsodium23
  Depends: libssl1.1
  Depends: libsystemd0
    libelogind0
  Depends: libxml2
  Depends: zlib1g
  Suggests: php-pear
`
PHP 8.2 FPM package dependencies
`apt-cache depends php8.2-fpm
php8.2-fpm
  Depends: libmagic1
 |Depends: media-types
  Depends: mime-support
  Depends: php8.2-cli
  Depends: php8.2-common
  Depends: php8.2-opcache
  Depends: procps
    procps:i386
 |Depends: systemd
    systemd:i386
  Depends: <systemd-tmpfiles>
    systemd-standalone-tmpfiles
    systemd:i386
    systemd
  Depends: tzdata
  Depends: ucf
  Depends: libacl1
  Depends: libapparmor1
  Depends: libargon2-1
  Depends: libc6
  Depends: libpcre2-8-0
  Depends: libsodium23
  Depends: libssl1.1
  Depends: libsystemd0
    libelogind0
  Depends: libxml2
  Depends: zlib1g
  Suggests: php-pear
`

**Additional context**
This request is about amending packaging dependency not build time dependencies.

**Comment by oerdnj** [comment]
Yeah, confirming that you’ve read the FAQ without reading the FAQ just won’t do.

**Comment by michaelk83** [comment]
In case anyone else is interested, I was able to get around this on Debain 11 by installing `systemd-standalone-tmpfiles` from `bullseye-backports/main`. No `equivs` needed, since it provides `systemd-tmpfiles` out of the box. It's available in the stable sources starting from Debian 12 bookworm, and in Ubuntu starting from 22.04 jammy.

(My use case is running PHP-FPM in Podman based on `debian:11-slim`. Since SystemD won't be running in the container, installing the full SystemD is just a waste of space.)
