### ISSUE TITLE
Php8.1-memcached in Bookworm

### ISSUE THREAD

**Issue by OttoLuck** [oerdnj/deb.sury.org#1957]
Hello,

I need to install php8.1-memcached on Bookworm but I can't find it in "https://packages.sury.org/php/ bookworm main".

The only way I found was to add a repo "https://packages.sury.org/php/ bullseye" on Bookworm but I think it's not safe.
Is there a reason why php8.1-memcached can't be added to this repo branch along with other php8.1 packages?

Thanks!

**Comment by oerdnj** [comment]
Bookworm hasn't been released yet.  All the packages will be available when bookworm is released, it's just best effort as of now.
