### ISSUE TITLE
[php-7.0] Make PDO as an optional module

### ISSUE THREAD

**Issue by Sumanai** [oerdnj/deb.sury.org#196]
Many sites use mysqli to connect to the database, and PDO is a unnecessary for them.
I would like to be able to disable the PDO to save RAM and performance.
Thanks!

**Comment by oerdnj** [comment]
Do you have any measurements how much memory would be saved?

And I don't think it would save any performance at all.

**Comment by Sumanai** [comment]
Last measurements I conducted  at 5.5, exact numbers can not remember, but since then disconnect.
I can hold measurement in their compiling PHP 7, but I'm not sure at the expense of the authenticity of the results due to the different flags compilation.

**Comment by oerdnj** [comment]
Feel free to reopen the bug when you have any number supporting your claims.
