### ISSUE TITLE
Missing `php5.6-redis` and `php5.6-memcached` for Debian Bookworm

### ISSUE THREAD

**Issue by OzzyCzech** [oerdnj/deb.sury.org#1962]
Maybe it's to fresh, [two days](https://www.debian.org/releases/bookworm/) after official release but there are missing `php5.6-redis` and `php5.6-memcached` packages - is there any plan to add them?

**Distribution:**
 - OS: Debian Bookworm
 - Architecture: `amd64`
 - Repository: packages.sury.org

**Comment by Padoup-Padoup** [comment]
I noticed that php8.1-redis is also missing (in Debian Bookworm), not creating a new issue.

**Comment by oerdnj** [comment]
> Maybe it's too fresh, [two days](https://www.debian.org/releases/bookworm/) after official release

Yes

**Comment by oerdnj** [comment]
It will be ready once the things [here](https://jenkins.rfc1925.org/view/PECL/) stop spinning (and I restart the stragglers - there are some layered dependencies around redis, memcached, igbinary and msgpack).

**Comment by OzzyCzech** [comment]
Cool. Thanks a lot @oerdnj
