### ISSUE TITLE
nginx-stable repo for Debian bookworm

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1965]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
`nginx-stable` repo for Debian bookworm. Apparently [the packages have been built](https://jenkins.rfc1925.org/view/NGINX-STABLE/job/nginx_nginx-binaries/architecture=amd64,distribution=bookworm,node=amd64/), but the actual repo is missing.

**Comment by oerdnj** [comment]
And there was a same mistake (cut&paste bullseye instead of bookworm) in different place which really messed up the repository. Now everything has been rebuilt and all packages should be available.
