### ISSUE TITLE
Switch nginx cache-purge module to a feature rich fork

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#1966]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Currently it's impossible to purge cache all at once or purge multiple keys at once.

**Describe the solution you'd like**
Switch to [Tordens fork](https://github.com/torden/ngx_cache_purge) of [FRiCKLE/ngx_cache_purge](https://github.com/FRiCKLE/ngx_cache_purge). Fork contains the following three great features for purging caches:

- [Partial keys](https://github.com/torden/ngx_cache_purge#partial-keys)
- [Purging multiple cache entries with the same cache key](https://github.com/torden/ngx_cache_purge#purging-multiple-cache-entries-with-the-same-cache-key)
- [Purge all cached files](https://github.com/torden/ngx_cache_purge#sample-configuration-same-location-syntax---purge-all-cached-files)

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org/nginx

**Package(s) (please complete the following information):**
```
libnginx-mod-http-cache-purge:
  Installed: 1.24.0-1+0~20230530.24+debian11~1.gbpd7c5fc
  Candidate: 1.24.0-1+0~20230530.24+debian11~1.gbpd7c5fc
  Version table:
 *** 1.24.0-1+0~20230530.24+debian11~1.gbpd7c5fc 500
        500 https://packages.sury.org/nginx bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     1.18.0-6.1+deb11u3 500
        500 https://debian.inf.tu-dresden.de/debian bullseye/main amd64 Packages
        500 https://security.debian.org/debian-security bullseye-security/main amd64 Packages
```

**Additional context**
I could try to create a merge request in Salsa against [main-1.24](https://salsa.debian.org/ondrej/nginx/-/tree/main-1.24/debian/modules/http-cache-purge?ref_type=heads), if this is something you'd consider.

**Comment by oerdnj** [comment]
This this has been done as part of #2073 (the module is at 2.3 version)
