### ISSUE TITLE
packages.sury.org/*/apt.gpg and packages.sury.org/*/README.txt gives 404 not found

### ISSUE THREAD

**Issue by TomCan** [oerdnj/deb.sury.org#1969]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Packages.sury.org is giving a 404. Both on the main page as on pages/documents that were working before (eg. the apt key)

**To Reproduce**
Browse to https://packages.sury.org

```
# curl -I https://packages.sury.org/php/apt.gpg
HTTP/2 404 
date: Thu, 15 Jun 2023 07:21:05 GMT
content-type: text/html
vary: Accept-Encoding
server: BunnyCDN-AMS1-883
cdn-pullzone: 717719
cdn-uid: a7a277f7-2828-404b-9c94-f3b9b03c0434
cdn-requestcountrycode: BE
cache-control: public, max-age=5
cdn-storageserver: DE-165
cdn-proxyver: 1.03
cdn-requestpullsuccess: True
cdn-requestpullcode: 404
cdn-cachedat: 06/15/2023 07:21:05
cdn-edgestorageid: 1056
cdn-status: 404
cdn-requestid: 02d70ce5cd8c7e41b21648fb836fe6a9
cdn-cache: EXPIRED
```

**Your understanding of what is happening**
Content not there, of server misconfiguration.

**What steps did you take to resolve issue yourself before reporting it here**
Test from different machines

**Expected behavior**
To get the requested content.

**Distribution (please complete the following information):**
n/a

**Package(s) (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by 4wk-** [comment]
Same here, can confirm. Needed to have https://packages.sury.org/php/apt.gpg :/

**Comment by zdenek-crha** [comment]
Repository gives 404 when trying to get directory listing, `apt.gpg` or readme file from the server. But downloading packages via apt seems to work without issue.

**Comment by oerdnj** [comment]
> Repository gives 404 when trying to get directory listing, `apt.gpg` or readme file from the server. But downloading packages via apt seems to work without issue.

Yep, the `apt.gpg` and `README.txt` files were missing.

**Comment by oerdnj** [comment]
The files have been reuploaded.

**Comment by pandvan** [comment]
Should directory listing work? At the moment it still gives 404

**Comment by oerdnj** [comment]
> > Should directory listing work? At the moment it still gives 404
> 
> Maybe related to #1972 The directory listing was previously provided by nginx. I don't think bunnycdn provides that

Yep, I also see no reason why directory listing should be provided - the two extra files work (`apt.gpg` and `README.txt`) and `apt` works too.

**Comment by fuegas** [comment]
@oerdnj : we see the following when we run apt-get update:
```
N: Repository 'https://packages.sury.org/php buster InRelease' changed its 'Suite' value from 'buster/snapshots/1686817153' to 'bookworm/snapshots/1686830748'
E: Repository 'https://packages.sury.org/php buster InRelease' changed its 'Codename' value from 'buster' to 'bookworm'
```
Is this intended?

**Comment by pandvan** [comment]
> I also see no reason why directory listing should be provided

Just a easy way to list all packages inside the repository without using `apt`
As you said, it's not really necessary

**Comment by oerdnj** [comment]
> > I also see no reason why directory listing should be provided
> 
> Just a easy way to list all packages inside the repository without using `apt` As you said, it's not really necessary

`man grep-dctrl`, e.g. `grep-dctrl -s Package '' /var/lib/apt/lists/packages.sury.org_php*Packages`
