### ISSUE TITLE
courier-mta wily upgrade problem "unable to make backup link"

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#197]
The error is probably obvious.
```
dpkg: error processing archive /var/cache/apt/archives/courier-mta_0.75.0-2+deb.sury.org~wily+2_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/cancelmsg' before installing new version: Operation not permitted
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

**Comment by markc** [comment]
I'm also seeing an obscure error here but it might be due to the courier vs daemon uid:gid conflict when upgrading to the new wily packages. Note that -access=.dat whereas it should be -access=/etc/courier/smtpaccess.dat but I'll be damned if I can figure out why my `esmtpd:ACCESSFILE=/etc/courier/smtpaccess` setting is not being passed on correctly.
```
root     19325  0.0  0.0   4368  1268 ?        S    14:05   0:00 /usr/sbin/courierlogger -pid=/var/run/courier/imapd.pid -start -name=imapd /usr/sbin/couriertcpd -address=0.0.0.0 -maxprocs=400 -maxperip=200 -access=.dat -nodnslookup -noidentlookup 143 /usr/lib/courier/courier/imaplogin /usr/bin/imapd Maildir
```

**Comment by oerdnj** [comment]
The dpkg error looks really strange. What does `ls -ld /usr/bin/cancel*` says?

I'll figure out the permissions. I am not aware of changing anything about permissions. But the package was in really old packaging format, so something might have been dropped.

**Comment by markc** [comment]
```
~ ls -ld /usr/bin/cancel*
-rwsr-xr-x 1 courier courier 26512 Dec 31 23:18 /usr/bin/cancelmsg*
```
I completely removed all packages and reinstalled from scratch yet again and this time the reported ./usr/bin/cancelmsg problem seems to have cleared up.
