### ISSUE TITLE
Repository gives 404

### ISSUE THREAD

**Issue by NielsH** [oerdnj/deb.sury.org#1970]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
The apt repository gives a 404

**To Reproduce**
1. Go to https://packages.sury.org/
2. Get a 404 response

**Your understanding of what is happening**
So currently a lot of URLs under https://packages.sury.org/ give a 404. I.e. 
- https://packages.sury.org/php/
- https://packages.sury.org/nginx-mainline/
- https://packages.sury.org/php/README.txt
- https://packages.sury.org/nginx-mainline/apt.gpg

It may be related to a CDN cache, but I'm just guessing. When I do an apt-get update it still works, but curl/browser does not.

**What steps did you take to resolve issue yourself before reporting it here**
I tried to access the pages through curl and chrome

**Expected behavior**
The pages give a success status code. i.e. HTTP 200

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: Multiple, see above

**Package(s) (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by 4wk-** [comment]
dup #1969

**Comment by NielsH** [comment]
I see https://github.com/oerdnj/deb.sury.org/issues/1969 was opened 1 minute earlier. I will close my issue to track it through the other one.

**Comment by 4wk-** [comment]
@NielsH It's fixed (in case you didnt get notification from other task)

**Comment by fuegas** [comment]
Hi @4wk- thanks for the heads up, we followed the other issue as well so we're notified :)
