### ISSUE TITLE
packages.sury.org backend (CDN Origin) has been changed

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#1972]
Hey,

I've changed the packages.sury.org, so the packages are directly uploaded to the CDN Storage. Unfortunately, the CDN provider doesn't have `rsync`, but only **FTP** access (implemented as shim on top of their API), so the process wasn't that straightforward. I had to patch the `lftp` to strip `./` from the filename when deleting obsolete files, but other than that `lftp` mirror mode is easy to use, just much much slower than `rsync`.

There are three other changes:

1. When package is built, it only indicates the repository needs to be synced and the hourly cron job will take care of the synchronization.
2. Directory listing is disabled - there are couple of staticly generated index.html and 404.html with instructions on how to add APT repository and how to create a local APT mirror.
3. The synchronization is now using `reprepro` snapshot function, so packages don't disappear during synchronization, thus you might see messages like this:
```
N: Repository 'https://packages.sury.org/php bookworm InRelease' changed its 'Suite' value from 'bookworm/snapshots/1686755836' to 'bookworm/snapshots/1686817153'
```

Those messages are harmless and the number is a UNIX timestamp indicating when the synchronization has started. The script creates snapshots, sync the pool (without deleting files), sync the dists directories, delete obsolete files from pool and deletes the snapshots. This should result in more stable results when there are many packages building at the same time.

The message can be prevented by adding `--allow-releaseinfo-change` to `apt` or `apt-get`, e.g.: `apt update --allow-releaseinfo-change` or `apt-get update --allow-releaseinfo-change`

**Comment by CommanderRoot** [comment]
A change I noticed is that when I click on the "Debian DPA" link on [https://deb.sury.org/](https://deb.sury.org/) I get a 404 error message instead of the README text showing me how to install it.

**Comment by oerdnj** [comment]
> A change I noticed is that when I click on the "Debian DPA" link on https://deb.sury.org/ I get a 404 error message instead of the README text showing me how to install it.

I've added couple of statically created index.html and 404.html here and there.

**Comment by rfeiner** [comment]
We're running into the same issue as mentioned above:
```
Conflicting distribution: https://packages.sury.org/php bullseye InRelease (expected bullseye but got bookworm)
```

**Comment by omarfarooqiom** [comment]
#12 [drud/ddev-webserver:v1.21.5-iom-built 3/5] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.4-gmp
#12 4.754 W: Conflicting distribution: https://packages.sury.org/php bullseye InRelease (expected bullseye but got bookworm)
#12 5.181 E: Unable to correct problems, you have held broken packages.
#12 ERROR: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests php7.4-gmp" did not complete successfully: exit code: 100

DDev instances also not working and having above error.

**Comment by oerdnj** [comment]
Darn, cut&paste error in the last modification of the sync script. Just a sec, it will be fixed in couple of minutes.

**Comment by rfeiner** [comment]
Thanks for the quick turn around, @oerdnj 🙌

**Comment by oerdnj** [comment]
I've now hidden the resolved issues (I've deleted one comment before realising I could just hide them).

**Comment by oerdnj** [comment]
> Thanks for the quick turn around, @oerdnj 🙌

Well, sorry for the hiccup. I've tested this, and then I've realized I need to make the snapshots before synchronizing the pool, so I've split the code that creates the snapshots and syncs them. Unfortunately, I forgot to copy the part that uses the current codename to the second loop, so the last one was always used. It ended up as with every hastily made last minute changes...

**Comment by djalai** [comment]
Many thks @oerdnj for all the work and the quick response on this ;)

**Comment by Erwan-loot** [comment]
Thanks !

**Comment by oerdnj** [comment]
Ok, another update. After some fiddling with `reprepro`, I rewrote the mirroring to a three-tiered design:

1. The main repository is used by [jenkins-debian-glue](https://jenkins-debian-glue.org) to put packages into immediately (via `reprepro processincoming`) and mark the repository as "dirty" (in need for sync)
2. The synchronization script is run once an hour under a lock, looks for dirty repositories, and first uses `reprepro update` to update the second tier repository (and if there's any mismatch in the first tier, it stops) and then it mirror-upload the second tier repository to third tier.
3. The third tier is just static storage for the files mirrored from the second tier repository - the CDN and the rsync place.

I just with the CDN provider would extend the upload service to allow `rsync` along with the `FTP` (which is just shim on top of a REST API).

**Comment by CoolGoose** [comment]
hey @oerdnj . is it safe to assume 
```E: The repository 'https://packages.sury.org/php bullseye Release' does not have a Release file.``` is because this is syncing now ?  Thank you for the update 🥂

**Comment by oerdnj** [comment]
Yes, give it a couple minutes please.

**Comment by oerdnj** [comment]
> hey @oerdnj . is it safe to assume `E: The repository 'https://packages.sury.org/php bullseye Release' does not have a Release file.` is because this is syncing now ? Thank you for the update 🥂

Should be properly synchronized now.

**Comment by ghouscht** [comment]
> > hey @oerdnj . is it safe to assume `E: The repository 'https://packages.sury.org/php bullseye Release' does not have a Release file.` is because this is syncing now ? Thank you for the update 🥂
> 
> Should be properly synchronized now.
> 
> Actually, only the control files have been synchronized, so some package files (.deb) might be missing yet.

Yes looks better now but as you wrote some packages are still missing. I guess you're still syncing those, right?

**Comment by sskender** [comment]
I have still redis missing

**Comment by rsanzante** [comment]
@sskender Redis packages were missing for me as well but now they are available, try again now.

**Comment by oerdnj** [comment]
I'll write it here when the sync is done. Some packages might be already available, but the full sync hasn't completed yet.

**Comment by oerdnj** [comment]
The apt repository should be completely synced, the rsync source is synchronizing right now.

**Comment by oerdnj** [comment]
Looks like this didn't really work, so we are back at the HTTPS based origin, I kept the changes to the way how the APT repository is generated though, so that should improve the synchronization issues anyway.

**Comment by thompol** [comment]
@oerdnj wouldn't it be better to do such changes and tests on a separate repo, instead of your live repo?

**Comment by oerdnj** [comment]
> @oerdnj wouldn't it be better to do such changes and tests on a separate repo, instead of your live repo?

No, not really. I said it many times, this is best effort only, not a commercial service with any guarantees.

Also, it's hard to test anything if nobody would be using that separate repository. Some problems popped up, because the repository was accessed from non-EU regions.
