### ISSUE TITLE
Nginx packages list for bullseye looks like bookworm's

### ISSUE THREAD

**Issue by mikevmk** [oerdnj/deb.sury.org#1974]
It seems that after last update nginx repository for bullseye started to give away packages list for bookworm instead of bullseye

E.g. nginx-core is listed depended on libc6 (>= 2.34), while current bullseye version is 2.31-13+deb11u6

Bookworms libc6 on the other hand is 2.36-9

Could you please check?

Thanks in advance!

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1972#issuecomment-1593085302

**Comment by mikevmk** [comment]
Ops, sorry for duplicate in #1975 

The issue unfortunately is still there

curl -s https://packages.sury.org/nginx/dists/bullseye//main/binary-amd64/Packages | grep 'libc6 (>= 2.34)'
