### ISSUE TITLE
Nginx repo - bookworm list instead of bullseye

### ISSUE THREAD

**Issue by mikevmk** [oerdnj/deb.sury.org#1975]
Ondrej, I'm deeply sorry for reopenning the issue, but the issue is still here

curl -s https://packages.sury.org/nginx/dists/bullseye//main/binary-amd64/Packages | grep 'libc6 (>= 2.34)'

**Comment by oerdnj** [comment]
Ah, that's something different and only tangentially related.

**Comment by oerdnj** [comment]
I'll have to remove the packages from the repository and rebuild them again.

**Comment by oerdnj** [comment]
Related to https://github.com/oerdnj/deb.sury.org/issues/1965

**Comment by oerdnj** [comment]
Thanks for being persistent.  There were two issues that had same symptoms.

**Comment by oerdnj** [comment]
The progress can be checked here: https://jenkins.rfc1925.org/view/NGINX-STABLE/job/nginx_nginx-binaries/27/

**Comment by oerdnj** [comment]
amd64 should be fine, the i386, armhf and arm64 will come later.
