### ISSUE TITLE
Packages are not available (php8.1-apcu, php8.1-uploadprogress i php8.1-xdebug)

### ISSUE THREAD

**Issue by bronisMateusz** [oerdnj/deb.sury.org#1976]
Hi, since yesterday I have a problem downloading 3 packages: `php8.1-apcu`, `php8.1-uploadprogress` and `php8.1-xdebug`, and on Tuesday I could not download `php8.1-memcached`.

`Package php8.1-apcu is not available, but is referred to by another package.
#0 41.95 This may mean that the package is missing, has been obsoleted, or
#0 41.95 is only available from another source
#0 41.95 
#0 41.95 Package php8.1-uploadprogress is not available, but is referred to by another package.
#0 41.95 This may mean that the package is missing, has been obsoleted, or
#0 41.95 is only available from another source
#0 41.95 
#0 41.95 Package php8.1-xdebug is not available, but is referred to by another package.
#0 41.95 This may mean that the package is missing, has been obsoleted, or
#0 41.95 is only available from another source
#0 41.95 
#0 41.96 E: Package 'php8.1-apcu' has no installation candidate
#0 41.96 E: Package 'php8.1-uploadprogress' has no installation candidate
#0 41.96 E: Package 'php8.1-xdebug' has no installation candidate
#0 41.97 apt failed, retrying`

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1922

**Comment by wotnak** [comment]
It looks like currently some arm64 php8.1 packages that were available for earlier releases are missing for bookworm.

**Comment by oerdnj** [comment]
> It looks like currently some arm64 php8.1 packages that were available for earlier releases are missing for bookworm.

How could I know? The “bug report” carry no information and willfully avoided filling in the template that asks the right questions.

**Comment by wotnak** [comment]
Filed issue with more details at https://github.com/oerdnj/deb.sury.org/issues/1977.
