### ISSUE TITLE
Some arm64 php8.1 packages are missing for bookworm

### ISSUE THREAD

**Issue by wotnak** [oerdnj/deb.sury.org#1977]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

After updating base docker image to debian bookworm, installation of some php8.1 packages stopped working. It looks like it affects arm64 devices, but on amd64 everything works fine. 
From what I was able to determine, the repo is missing some arm64 php8.1 packages for bookworm that were available for bullseye.
Downgrading back to bullseye fixes the problem.

**To Reproduce**
1. Use arm64 device with Debian Bookworm
2. Add repo  `curl -sSL https://packages.sury.org/php/README.txt | bash -x `
2.  Try to install php8.1-xdebug package `apt install php8.1-xdebug`
4. See error:
```
Package php8.1-xdebug is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php8.1-xdebug' has no installation candidate
```

**Your understanding of what is happening**
It looks like for bookworm some arm64 php8.1 packages that were available for earlier releases are missing.
After comparing build logs for arm64 php8.1 on [bullseye](https://jenkins.rfc1925.org/view/PHP/job/php_php8.1-binaries/architecture=arm64,distribution=bullseye,node=arm64/41/) and [bookworm](https://jenkins.rfc1925.org/view/PHP/job/php_php8.1-binaries/architecture=arm64,distribution=bookworm,node=arm64/41/) it looks like the following packages are currently missing for bookworm:
```
php8.1-amqp
php8.1-apcu
php8.1-ast
php8.1-decimal
php8.1-ds
php8.1-excimer
php8.1-gearman
php8.1-gmagick
php8.1-gnupg
php8.1-grpc
php8.1-http
php8.1-igbinary
php8.1-imagick
php8.1-inotify
php8.1-libvirt-php
php8.1-lz4
php8.1-mailparse
php8.1-maxminddb
php8.1-mcrypt
php8.1-memcache
php8.1-memcached
php8.1-mongodb
php8.1-msgpack
php8.1-oauth
php8.1-pcov
php8.1-phalcon5
php8.1-pinba
php8.1-protobuf
php8.1-ps
php8.1-psr
php8.1-raphf
php8.1-rdkafka
php8.1-redis
php8.1-rrd
php8.1-smbclient
php8.1-solr
php8.1-ssh2
php8.1-stomp
php8.1-swoole
php8.1-tideways
php8.1-uopz
php8.1-uploadprogress
php8.1-uuid
php8.1-vips
php8.1-xdebug
php8.1-xhprof
php8.1-xmlrpc
php8.1-yac
php8.1-yaml
php8.1-zmq
php8.1-zstd
```

**What steps did you take to resolve issue yourself before reporting it here**
Tried to update apt cache, install problematic packages on different device, compared installation logs between arm64 and amd64 devices, checked that https://packages.sury.org/php/dists/bookworm/main/binary-arm64/Packages doesn't contain for example php8.1-xdebug package that was available on https://packages.sury.org/php/dists/bullseye/main/binary-arm64/Packages, confirmed that issue only exists on bookworm, on bullseye it works without problems.

**Expected behavior**
Installation of arm64 php8.1 packages after debian bookworm update should work the same as on debian bullseye.

**Distribution (please complete the following information):**
 - OS: Debian Bookworm
 - Architecture: arm64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Don't have an arm64 device to provide relevant apt-cache policy output (was made aware of the problem by people at work that use mac m2 devices). Provided the list of packages that seem to be affected based on build logs above.

**Comment by oerdnj** [comment]
Bookworm has been released few days ago. Have some patience please.

**Comment by oerdnj** [comment]
`php-memcached` and some of its build dependencies are still resisting on bookworm arm64 and armhf, but I am almost there.

**Comment by oerdnj** [comment]
I think this is resolved now.

**Comment by mathieuruellanmyscript** [comment]
@oerdnj I've relaunch a PR on my personal github project and package php8.1-imagick seems not to be here.

**Comment by bronisMateusz** [comment]
I also rechecked the build on my project and it is missing:
`php8.1-uploadprogress`
`php8.1-xdebug`

**Comment by domainfun** [comment]
@bronisMateusz Looking at https://packages.debian.org/search?keywords=uploadprogress&searchon=names&suite=all&section=all it appears that `php8.1-uploadprogress` is **not** part of Bookworm, perhaps for PHP 8.1 you need to look for `php-uploadprogress`?  See https://packages.debian.org/bookworm/php-uploadprogress

The same for `php8.1-xdebug`, see https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=xdebug ... look for https://packages.debian.org/bookworm/php-xdebug

**Comment by oerdnj** [comment]
> I also rechecked the build on my project and it is missing: `php8.1-uploadprogress` `php8.1-xdebug`

Looks like there was some glitch in the build and I’ll have to rebuild most of the PECL packages.

**Comment by kallookoo** [comment]
Hi @oerdnj 

I have tried to install several versions of PHP and I find that the following packages have no candidate.

```
E: Package 'php8.1-memcache' has no installation candidate
E: Package 'php8.1-xdebug' has no installation candidate
E: Package 'php8.0-memcache' has no installation candidate
E: Package 'php8.0-xdebug' has no installation candidate
```

I guess it is related to your last comment, but could you please confirm it. 

Thanks

**Comment by langemeijer** [comment]
Hi @oerdnj,

Not only the PECL packages are missing, PHP 8.1 seems stuck on 8.1.21 for arm64. amd64 has 8.1.22. 
This affects bookworm, bullseye and buster.

**Comment by rfay** [comment]
AFAICT there are many many Bookworm packages missing for php8.1 (and php8.0 and maybe everything except on php8.2) on arm64. But I see many now missing on amd64 now as well. 

For example, xmlrpc and xhprof.  But really, most packages are missing except on PHP8.2, where they all seem to show up.

```
# apt install -y php8.0-xmlrpc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php8.0-xmlrpc
E: Couldn't find any package by glob 'php8.0-xmlrpc'
```

I see all these packages listed in https://packages.sury.org/php/dists/bookworm/Contents-amd64.gz and https://packages.sury.org/php/dists/bookworm/Contents-arm64.gz, but I definitely don't find them when I try to get them.

**Comment by nanaya** [comment]
I don't know if it's the same issue but php8.2-swoole is [missing](https://packages.sury.org/php/pool/main/p/php-swoole/) for all debian 12 platforms.

**Comment by fuegas** [comment]
I've compared the package lists of amd64 with arm64 and it looks like arm64 is missing a lot of packages:
```
⋗ wc -l deb12-*
    1722 deb12-amd64.txt
    1246 deb12-arm64.txt
```

Number of missing packages per PHP version:
```
⋗ diff deb12-amd64.txt deb12-arm64.txt | grep '^<' | cut -d' ' -f3 | cut -d'-' -f1 | uniq -c
   2 php
  10 php5.6
  52 php7.0
  56 php7.1
  64 php7.2
  70 php7.3
  68 php7.4
  76 php8.0
  76 php8.1
   2 php8.2
```

**Comment by ondrousn** [comment]
Hello @oerdnj , please any update on this?

Bookworm arm64 builds fail for me:

```
> [2/3] RUN apt-get update     && apt-get dist-upgrade -y     && apt-get install -y --no-install-recommends 		php8.1-pcov         php8.1-xdebug     && apt-get autoclean --yes     && apt-get autoremove --yes     && apt-get clean     && rm -rf /var/lib/apt/lists/*:
43.28 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
55.72 Reading state information...
55.76 Package php8.1-pcov is not available, but is referred to by another package.
55.76 This may mean that the package is missing, has been obsoleted, or
55.76 is only available from another source
55.76 
55.77 E: Package 'php8.1-pcov' has no installation candidate
------
WARNING: buildx: git was not found in the system. Current commit information was not captured by the build
```

**Comment by mrevjd** [comment]
Looks like swoole is missing from php8.1 too on amd64

```
apt install php8.1-swoole                                                                                                                                                                                                               Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php8.1-swoole
E: Couldn't find any package by glob 'php8.1-swoole
```

**Comment by seebeen** [comment]
Don't mean to be a pain in the ass, but php8.0-mailparse is also missing for arm64 on bookworm

**Comment by aguzmans** [comment]
I am having some similar issue with memcached in bookworm:

```
apt search memcached
(...)
php-memcached/stable 3.2.0+2.2.0-4 arm64
  (none)

php-memcached-all-dev/stable 3.2.0+2.2.0-4 all
  (none)

php8.2-memcached/stable 3.2.0+2.2.0-4 arm64
  (none)
(...)
```

using pecl also does not work with docker on debian 12 containers. 
Dockerfile:
```
FROM wordpress:6.3.2-php8.2-apache
(...)
RUN set -ex; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
(...)
		libmemcached-dev \
		libmemcached-tools \
		libmemcached11 \
		zlib1g-dev \
		libssl-dev \
	; \
	\
	(...)
# https://pecl.php.net/package/memcached
	pecl install memcached; \
    docker-php-ext-enable memcached; \
	rm -r /tmp/pear; \
	\
```
I have tried different combination of the libraries above ^
The execution does this:
```
+ php --version
PHP 8.2.12 (cli) (built: Oct 28 2023 02:10:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
+ err=[31-Oct-2023 09:10:21 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached.so (libmemcached.so.11: cannot open shared object file: No such file or directory)) in Unknown on line 0
+ [ -z [31-Oct-2023 09:10:21 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/memcached.so (libmemcached.so.11: cannot open shared object file: No such file or directory)) in Unknown on line 0 ]
```

I will try to install from source directly and report.

**Comment by mihai-stancu** [comment]
Just for reference the following packages still seem to be missing on `arm64`:

- php8.1-mcrypt 
- php8.1-pcov
- php8.1-protobuf
- php8.1-ssh2
- php8.1-stomp
- php8.1-zmq
- php8.1-yaml

**Comment by rfay** [comment]
I think this is largely working now, thanks!

**Comment by MaryanShvets** [comment]
the same error

php -v

Warning: PHP Startup: Unable to load dynamic library 'imagick' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.27 (cli) (built: Dec 28 2023 00:27:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies




apt install imagick

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package imagick



apt install php8.1-imagick

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php8.1-imagick is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php8.1-imagick' has no installation candidate

**Comment by person1534** [comment]
Package php8.1-pgsql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php8.1-pgsql' has no installation candidate


root@mediawiki:/# apt list | grep php8.1-pgsql

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

php8.1-pgsql-dbgsym/bookworm 8.1.27-1+0~20231221.58+debian12~1.gbp3895b2 amd64
php8.1-pgsql/bookworm 8.1.27-1+0~20231221.58+debian12~1.gbp3895b2 amd64

**Comment by oerdnj** [comment]
@person1534 you are pasting output of amd64 into arm64 bug...  what's your point exactly?

**Comment by oerdnj** [comment]
@MaryanShvets Umm, those are not packages from this repository:
```
Warning: PHP Startup: Unable to load dynamic library 'imagick' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so: cannot open shared object file: No such file or directory))
```

this looks like something that you compiled locally...
