### ISSUE TITLE
Ubuntu PPA bionic package index is 0 bytes

### ISSUE THREAD

**Issue by karlkatzke** [oerdnj/deb.sury.org#1978]
**Frequently asked questions**

- [ X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ X ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ X ] I have tried to resolve the issue myself and will describe what I did in clear and consise (sic) manner

**Describe the bug**
Package index for bionic on launchpad, when unzipped, is zero bytes in length. 

We discovered this because starting yesterday at 11:41 UTC we can no longer install PHP versions from the Ondrej PPA repo on Bionic. 

**To Reproduce**

1. Go to http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/main/binary-amd64/Packages.gz
2. See that it's only 20 bytes in length
3. Unzip it and see that Packages is zero bytes in length. 

**Your understanding of what is happening**
Something's busted in the packaging process that has caused Packages to be a zero byte file

**What steps did you take to resolve issue yourself before reporting it here**
I checked to see if there was data in the file that I was trying to pull. 

**Expected behavior**
We expect Packages to contain a list of all packages, as in http://ppa.launchpad.net/ondrej/php/ubuntu/dists/jammy/main/binary-amd64/

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: AMD64
 - Repository: Ubuntu PPA Launchpad

**Package(s) (please complete the following information):**
Can't output it because there's no package list. 

**Additional context**
You know, I appreciate process, but this template is kind of verbose for what I'm sure is a simple problem, and there isn't another way to let you know.

**Comment by oerdnj** [comment]
> I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

No, you did not.
