### ISSUE TITLE
Error 404 "Failed to fetch" for Buster Debian

### ISSUE THREAD

**Issue by Julienh** [oerdnj/deb.sury.org#1980]
Hello,

Since this morning I have this error : 
```
Err:1 https://packages.sury.org/php buster/main amd64 php-igbinary amd64 3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca
  404  Not Found [IP: 143.244.56.51 443]
Err:2 https://packages.sury.org/php buster/main amd64 php8.1-igbinary amd64 3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca
  404  Not Found [IP: 143.244.56.51 443]
Err:3 https://packages.sury.org/php buster/main amd64 php8.2-igbinary amd64 3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca
  404  Not Found [IP: 143.244.56.51 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-igbinary/php-igbinary_3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca_amd64.deb  404  Not Found [IP: 143.244.56.51 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-igbinary/php8.1-igbinary_3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca_amd64.deb  404  Not Found [IP: 143.244.56.51 443]
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-igbinary/php8.2-igbinary_3.2.14-1+0~20230617.41+debian10~1.gbpcc1dca_amd64.deb  404  Not Found [IP: 143.244.56.51 443]
```

I checked the `/etc/apt/sources.list.d/php.list` file: 
`deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ buster main`

I did tests with other servers and I have the error only with Debian 10 servers. It was working yesterday.

Thank you.

**Comment by xponcn** [comment]
`
E: Failed to fetch https://packages.sury.org/php/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (375100 != 375050). Mirror sync in progress? [IP: 169.150.221.147 443]
   Hashes of expected file:
    - Filesize:375050 [weak]
    - SHA256:fd5702db87cd818f4b6c0c1a42e5715eabda1f2f5378d4f6c70e9d71b9092ca9
    - SHA1:fd90939a23768f24004bcf323de1af5fecf8d53a [weak]
    - MD5Sum:919948dd45ecb92e16751231a8ec3047 [weak]
   Release file created at: Sun, 18 Jun 2023 00:00:13 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`
Debian 11, yesterday was OK, but today..

**Comment by zertrin** [comment]
I also experienced it for bullseye, have been trying every 10 mins since about 2 hours, and it seems it just got fixed now 😸

**Comment by Julienh** [comment]
Fixed for me too, thank you!

**Comment by oerdnj** [comment]
You are faster than I was able to write it here :). Have a nice Sunday.
