### ISSUE TITLE
INSECURE REPOSITORIES: Signing key is insecure at 1024R, please update the signing key to at least 4096.

### ISSUE THREAD

**Issue by Danrancan** [oerdnj/deb.sury.org#1985]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
On https://launchpad.net/~ondrej/+archive/ubuntu/php/, the signing key for this repository is insecure, and NOBODY in their right minds should be using this repo until the signing key is update to 4096. Please update ALL of the signing keys so we can use your repository safely.

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: Ubuntu Server 20.04 (Raspberry Pi)
 - Architecture: aarch64
 - Repository: Ubuntu PPA and all other Sury Repo's

**Comment by sleemanj** [comment]
@Danrancan this is a short coming of launchpad, keys can not be replaced without creating an entirely new account (and thus the ppa url will change), longstanding bug reports here: 

https://bugs.launchpad.net/launchpad/+bug/1700167
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1461834

**Comment by oerdnj** [comment]
Coming here, using strong language, they must surely know that, right?

Also here: https://bugs.launchpad.net/launchpad/+bug/1331914

**Comment by Danrancan** [comment]
> https://bugs.launchpad.net/launchpad/+bug/1331914

I didn't know this. But looking at the bug reports, it seems nobody has been active on the issue since mid 2022. It's now Mid 2023. So it looks like there is no fix for this in sight. That being said, we have to weigh the costs and benefits of using the old key with the same ppa url, and creating an entirely new account with a new key (signed by the old key of course) and a new ppa url. This key is literally antiquated, and its the equivalent of browsing the internet securely with Windows Vista. I understand that you don't want to go through the mess of creating a new account, url, etc, as thats a lot of work and a big mess. However, what if your ppa was compromised and users couldn't verify downloads with a strong enough and uncrackable encryption key? Then essentially, all of the work that you do here day in and day out, is utterly useless, and might as well be going into the toilet. With the key's you have currently, and the NSA, CHINESE, and RUSSIANS in their heavily financed nation state positions, it is not out of the question to consider all downloads compromised by default. In a nation state mass data modification scenario, all of the work you are doing here could be completely modified by outside sources, essentially rendering your work utterly useless, while casting a mirage that it is useful. There is no doubt in my mind that the NSA has the tools to easily put backdoors in mass downloads with those using a 1024 bit key. So I would consider all of your software and work that you do, compromised by default after download, and thus, useless. Under these considerations, you might as well just stop developing the PPA, and call it quits, because nobody in their right minds is going to download something with backdoors in it. It's just not sane. Your PPA would be such a grand service to people if they weren't next to risking an http download. Instead, it's grandeur is completely overshadowed by the fact that you can't download this securely, which puts at risk tons and tons of systems and servers around the globe. Why build software if you can't prevent someone form maliciously modifying it upon distribution? I think a new account creation strategy should really take place here very soon, so that you can return control of your software distribution to users as opposed to nation states and hacking groups. Wouldn't you consider the painstaking process of creating a brand new account with your updated keys to mitigate this massive vulnerability? Until you do, nobody with the slightest sense of security and capabilities of nation state adversaries, should ever use your PPA. It's just not feasible with 1024. 

With all that being redundantly clear, what do I need to do to help you create a new account with new 4096 keys? Would you please consider this, as it affects a lot of linux users worldwide. Thanks a ton for listening to my semi-redundant rant and stubborn points. Let me know if there is anything I can do to help make this happen, because it will totally be worth it in the long run, and will preserve the longevity and authenticity of downloads from your PPA.

Let me know, and thanks for all of your work.

**Comment by oerdnj** [comment]
While the crypto hygiene in the PPA repositories is unfortunate, you are making claims that are simply not true and you are just fear mongering. Factorization of 1024 bit RSA still hasn't been done[1] and even if possible as of today (and we have no proofs of that), it would be available to only few actors (state-based).

It's important to make a distinction between protecting sensitive data (encryption) and signing. The PPA uses RSA keys to sign the package, and if the 1024 RSA keys gets close to insecure, I am pretty sure Canonical will move more quickly and rotate the old keys thus making any spoofing attack on the repository impractical. This is different than encrypting a sensitive data and expecting the data to be secure 20 years from now.

Also one must consider that RSA factorization is a resource intensive task. And unless quantum computing becomes prevalent and breaks the current crypto, there are easier ways how to compromise the end computer - court order targeted at Canonical, hacking the launchpad, hacking the user's computer, etc...

So unless you have a cryptographically strong proof that the RSA 1024 key used in the PPA has been actually compromised, this is only hypothetical discussion, and I am going to close the issue.

1. https://en.wikipedia.org/wiki/RSA_Factoring_Challenge

**Comment by Danrancan** [comment]
I guess I come from the standpoint that values good Opsec. Any good engineer knows that if it can be compromised, you must assume it will be or is compromised. The way to mitigate it is to make compromising it as difficult as possible for any entity, before an attack happens. All of my "Hypothetical" discussions, was just a pattern of thinking that excersizes good opsec. Assume the worst outcome is true and do your best to mitigate it before it happens. Thats all I was trying to demonstrate with my "Hypothetical" critique. 

But why are you closing this? What would it actually take to just fire up a fresh account and change URL's and Keys with that new account? Why security not a priority enough to take these steps? You never answered my question of what I can do to help you do these things. Do you just not want to? Let me know if this is possible.

**Comment by oerdnj** [comment]
> I guess I come from the standpoint that values good Opsec.

Yeah, sure, continue this pattern of putting yourself into a (false) moral ground and then wave hands as much as you can.

The fact is that 1024b RSA is safe as of this moment, and a “good Opsec” should also be able to evaluate the actual risk and not just the formal risk.

So take it or leave it. I am not forcing anyone to use the aforementioned PPAs.
