### ISSUE TITLE
php-swoole files aren't accessible

### ISSUE THREAD

**Issue by nanaya** [oerdnj/deb.sury.org#1986]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
php-swoole directory (https://packages.sury.org/php/pool/main/p/php-swoole/) and file (https://packages.sury.org/php/pool/main/p/php-swoole/php8.1-swoole_5.0.1-1%2b0%7e20221209.11%2bdebian11%7e1.gbp37278c_amd64.deb) are currently returning 403 and thus can't be installed.

**To Reproduce**
1. Go to https://packages.sury.org/php/pool/main/p/php-swoole/

**Your understanding of what is happening**
Some weird permission error?

**What steps did you take to resolve issue yourself before reporting it here**
NA

**Expected behavior**
File listing

**Distribution (please complete the following information):**
 - OS: NA
 - Architecture: NA
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
NA

**Additional context**
NA

**Comment by oerdnj** [comment]
Fixed, looks like I was missing `--perms` along to `--chmod` option to the rsync.
