### ISSUE TITLE
No packages found for ubuntu bionic release http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/main/binary-amd64/ 

### ISSUE THREAD

**Issue by ysc2015** [oerdnj/deb.sury.org#1987]
**Frequently asked questions**

- [ ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ ] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Can't install packages for bionic version of ubuntu, the package file http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/main/binary-amd64/
is empty

deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main 
deb-src http://ppa.launchpad.net/ondrej/php/ubuntu bionic main

**Comment by domainfun** [comment]
@ysc2015 Did you not see https://github.com/oerdnj/deb.sury.org/issues/1922 ... ?
