### ISSUE TITLE
php7.1-fpm bookworm + roundcube-1.4.13 + opcache -> 100% CPU

### ISSUE THREAD

**Issue by rkd77** [oerdnj/deb.sury.org#1990]
I tried to upgrade from Debian 11 to Debian 12.
php-7.1 I compiled from sources with your patches, but also installed from deb.sury.org.
Results similar:

Arch amd64. Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
php7.1-fpm with opcache enabled and roundcube-1.4.13 (original sources unpackaged) hangs on login page with 100% CPU.
If opcache is disabled, it works.
If compiled by gcc-10, it works even with opcache. (I checked only compilation, did not rebuild package).

php7.1-fpm:
  Installed: 7.1.33-53+0~20230609.81+debian12~1.gbp201d4d
  Candidate: 7.1.33-53+0~20230609.81+debian12~1.gbp201d4d
  Version table:
 *** 7.1.33-53+0~20230609.81+debian12~1.gbp201d4d 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
Not really a packaging issue. Either disable the opcache or use upstream-supported PHP version, so you can report this to upstream.
