### ISSUE TITLE
Unable to locate package php7.4

### ISSUE THREAD

**Issue by krixnaas** [oerdnj/deb.sury.org#1994]
I am trying to install PHP 7.4 on Ubuntu 18.04 LTS (Bionic Beaver) using the command sudo apt install php7.4, but I am encountering an error.

To Reproduce

Run sudo apt update to update the package list.
Attempt to install PHP 7.4 by running sudo apt install php7.4
![image_2023-07-20_143724010](https://github.com/oerdnj/deb.sury.org/assets/14975723/97b1b378-63c9-4f54-9bf8-6bccd002386c)

It was working till I update my last docker version which was 4.18

**Comment by sleemanj** [comment]
[8.04 is not supported. ](https://github.com/oerdnj/deb.sury.org/issues/1922)
