### ISSUE TITLE
Lua for PHP8.x

### ISSUE THREAD

**Issue by JB1985** [oerdnj/deb.sury.org#1997]
Hello, 

I see that the lua extension is only for PHP7.4 available.

Is there a chance that the extension will also come for PHP8.x?

php7.4-lua/bullseye 2.0.7++-1+0~20230617.24+debian11~1.gbp89b198 amd64
  PHP Embedded lua interpreter

**Comment by oerdnj** [comment]
No, not really. There’s no upstream support.
