### ISSUE TITLE
Update request: php-mongodb

### ISSUE THREAD

**Issue by cognitus** [oerdnj/deb.sury.org#1998]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

Extension mongodb 1.16.x (https://pecl.php.net/package/mongodb) has been released,

 It seems to be required for the newer releases of the Driver installed via `composer require mongodb/mongodb` 

```
    - mongodb/mongodb is locked to version 1.16.0 and an update of this package was not requested.
    - mongodb/mongodb 1.16.0 requires ext-mongodb ^1.16.0 -> it has the wrong version installed (1.15.3).
```

**Describe the solution you'd like**
Update the package.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

php-mongodb:
  Installed: 1.15.3-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.15.3-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1.15.3-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.12.0+1.9.2+1.7.5-4 500
        500 http://sa-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

**Comment by qeepcologne** [comment]
cannot upgrade to mongodb7 because of the outdated php driver:
https://www.mongodb.com/docs/drivers/php/
https://github.com/mongodb/mongo-php-driver/releases
https://pecl.php.net/package/mongodb

**Comment by oerdnj** [comment]
It's now at 1.16.2.

**Comment by keeshoekzema** [comment]
Unfortunalty, https://packages.sury.org/php/pool/main/p/php-mongodb/ doesn't have 1.16.2 yet, all i see is 1.15.3
