### ISSUE TITLE
PHP 8.2.8 CLI slow startup

### ISSUE THREAD

**Issue by michaelk83** [oerdnj/deb.sury.org#1999]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
On a recent install of PHP 8.2.8 based on `debian:bullseye-20230612-slim` image under Podman:
PHP 8.2.8 CLI has ~8 sec delay when running any commands, such as `php8.2 --version`.  
`php8.2 -n --version` has the same delay, so I don't think that it's the `php.ini` or extensions' fault.

By comparison, `php8.0 --version` on the same image, with the same extensions, and with the same `php.ini`, runs immediately (no delay).

If this isn't a packaging bug, I'd appreciate some pointers what else I can check to debug this.

**To Reproduce**
1. `podman pull docker.io/library/debian:bullseye-20230612-slim` (or same with Docker).
2. `podman run -it debian:bullseye-20230612-slim bash`
3. In bash on the image:
```bash
# Set up the Ondrej Sury DPA, backports for `systemd-standalone-tmpfiles`
apt-get update && apt-get install -y --no-install-recommends ca-certificates curl
mkdir -p /etc/apt/keyrings && chmod 755 /etc/apt/keyrings \
    && curl -sSL 'https://packages.sury.org/php/apt.gpg' > /etc/apt/keyrings/deb.sury.org-php.gpg \
    && echo 'deb [signed-by=/etc/apt/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ bullseye main' > /etc/apt/sources.list.d/php.list \
    && echo 'deb https://deb.debian.org/debian bullseye-backports main' > /etc/apt/sources.list.d/backports.list

# Install PHP
apt-get update && apt-get install -y --no-install-recommends systemd-standalone-tmpfiles
apt-get install -y --no-install-recommends \
        php8.2-fpm \
        php8.2-bcmath php8.2-curl php8.2-gd php8.2-intl php8.2-mbstring php8.2-memcached php8.2-mysql \
        php8.2-opcache php8.2-pcov php8.2-readline php8.2-redis php8.2-sqlite3 php8.2-xml php8.2-zip
apt-get install -y --no-install-recommends \
        php8.0-fpm \
        php8.0-bcmath php8.0-curl php8.0-gd php8.0-intl php8.0-mbstring php8.0-memcached php8.0-mysql \
        php8.0-opcache php8.0-pcov php8.0-readline php8.0-redis php8.0-sqlite3 php8.0-xml php8.0-zip

# Test
php8.0 --version            # No delay
php8.2 --version            # 8 sec delay
php8.2 -n --version         # 8 sec delay
```

**Your understanding of what is happening**
Same delay with `-n` suggests it's not an extensions or `php.ini` problem. Good performance of a different PHP version on the same image with the same extensions and `php.ini` further eliminates the parent environment (Podman, mounts, other libraries, system configuration) as possible culprits. Most likely explanation seems to be either a bug in PHP-CLI 8.2.8 itself, or in the packaging.

**What steps did you take to resolve issue yourself before reporting it here**
- Tested with `-n` flag (delay still present).
- Tested a different PHP version (no delay).
- Double-checked with the default `php.ini` (delay still present).

**Expected behavior**
No startup delay.

**Distribution (please complete the following information):**
 - OS: Debian 11
 - Architecture: amd64
 - Repository: packages.sury.org

**Additional context**
```
$ php8.2 --version
PHP 8.2.8 (cli) (built: Jul 16 2023 11:01:56) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies

$ php8.2 -m | tr '\n' ' '
[PHP Modules] bcmath calendar Core ctype curl date dom exif FFI fileinfo filter ftp gd gettext hash iconv igbinary
intl json libxml mbstring memcached msgpack mysqli mysqlnd openssl pcntl pcov pcre PDO pdo_mysql pdo_sqlite Phar
posix random readline redis Reflection session shmop SimpleXML sockets sodium SPL sqlite3 standard sysvmsg sysvsem
sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib  [Zend Modules] Zend OPcache

$ php8.0 --version
PHP 8.0.29 (cli) (built: Jun  9 2023 07:37:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.29, Copyright (c), by Zend Technologies

$ php8.0 -m | tr '\n' ' '
[PHP Modules] bcmath calendar Core ctype curl date dom exif FFI fileinfo filter ftp gd gettext hash iconv igbinary
intl json libxml mbstring memcached msgpack mysqli mysqlnd openssl pcntl pcov pcre PDO pdo_mysql pdo_sqlite Phar
posix readline redis Reflection session shmop SimpleXML sockets sodium SPL sqlite3 standard sysvmsg sysvsem
sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib  [Zend Modules] Zend OPcache
```

**Comment by oerdnj** [comment]
Is there enough entropy in the container?

I would suggest to run it under strace to see what it is doing.

**Comment by michaelk83** [comment]
`cat /proc/sys/kernel/random/entropy_avail` says 256, same as on the host. Don't know if that's enough or not, but strace pointed me to a messed up `/etc/localtime`. A bunch of lines of the form:
```
stat("/usr/share/zoneinfo/localtime/localtime/localtime/localtime/localtime/Asia/Hong_Kong", {st_mode=S_IFREG|0644, st_size=1217, ...}) = 0
```
I must've forgotten to `export TZ=...` before setting it up, so it was an empty link. After fixing that, startup is less than 1 sec. Thanks!

**Comment by oerdnj** [comment]
You provided an exceptional bug report, so it was joy to help you! Good to hear it was resolved so fast.
