### ISSUE TITLE
Trixie release files missing

### ISSUE THREAD

**Issue by Bulmer** [oerdnj/deb.sury.org#2011]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **problem** accurately (where the template below will help), I might be able to help you.

What is not **a clear and concise description**:
1. "Look here"
2. "Look at this docker image"
3. "Raw copy of the terminal"
4. "Screenshot"

**To Reproduce**

**Your understanding of what is happening**
Try to describe how do you understand what is happending and why is it happening.

**What steps did you take to resolve issue yourself before reporting it here**
Describe how did you try to resolve the issue yourself.  This is closely connected to the previous question.

**Expected behavior**

**Distribution (please complete the following information):**
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [e.g. Ubuntu PPA or packages.sury.org]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by Bulmer** [comment]
OS: Debian (Trixie)
Architecture: amd64
Repository: packages.sury.org
I am running Debian Testing (currently Trixie) and have found not release files for it in your repository. Please advise if they are going to be available soon, as I need to run php8.0.

**Comment by sleemanj** [comment]
You see in the template how the first line is 

"I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)"

Perhaps try reading them eh...
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#debian-1
