### ISSUE TITLE
OPCache and call_user_func with PHP 7.2 and Debian Bookworm

### ISSUE THREAD

**Issue by jbgomond** [oerdnj/deb.sury.org#2012]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
If you execute the code below with PHP 7.2, on Debian Bookworm and with OPCache enabled (cli or fpm), the for loop does not stop (but it sometimes does).

```
<?php

function test() {
    $items = ['', ''];
    $nb = count($items);

    for ($i = 0; $i < $nb; $i += 2) {
        echo $i . " ";
    }
}

\call_user_func('test');
```
![bug_sury_php72_debian_bookworm](https://github.com/oerdnj/deb.sury.org/assets/8344487/fce4ed4d-4139-4467-804f-070910b8a6b1)

Bug not present with PHP 7.2 on Debian Bullseye.
Bug not present with PHP 8.0 on Debian Bookworm.

**To Reproduce**
1. Install PHP 7.2 on Debian Bookworm
2. Enable OPCache on CLI or FPM
3. Execute code multiple times

**Expected behavior**
It should print 0 only.

**Distribution (please complete the following information):**
 - OS: Debian Bookwiorm
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
7.2.34-40+0~20230815.87+debian11~1.gbpe8e12b

**Comment by oerdnj** [comment]
Also here: https://github.com/oerdnj/deb.sury.org/discussions/2008

**Comment by oerdnj** [comment]
This looks like this upstream bug fixed in PHP 7.3:

- OPcache:
  . Fixed bug #79412 (Opcache chokes and uses 100% CPU on specific script).
    (Dmitry)

**Comment by oerdnj** [comment]
PHP 7.2 and 7.3 are affected by this.  And the fix for PHP#79412 has already been included in PHP 7.3, so it must be something else that's broken here.

**Comment by oerdnj** [comment]
This one could work work around with `opcache.optimization_level=0x7FFEBF7F` and it should work fine.

**Comment by oerdnj** [comment]
There's another broken case in the discussion mentioned above, so I had to change the default to `opcache.optimization_level=0x7FFEBF5F` and it looks like those two case are covered + I pulled #79412 to PHP 7.1 and PHP 7.2 packages, so couple of OPcache bugs have been either fixed or worked around.

The builds are running right now:
* [php7.1](https://jenkins.rfc1925.org/view/PHP%20Engine/job/php_php7.1-binaries/77/)
* [php7.2](https://jenkins.rfc1925.org/view/PHP%20Engine/job/php_php7.2-binaries/84/)
* [php7.3](https://jenkins.rfc1925.org/view/PHP%20Engine/job/php_php7.3-binaries/109/)
