### ISSUE TITLE
php8.2-gd package for ubuntu 20.04

### ISSUE THREAD

**Issue by mallt** [oerdnj/deb.sury.org#2015]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

Would it be possible to add the php8.2-gd package for ubuntu 20.04? Thank you!

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Why do you think it's not there?

**Comment by mallt** [comment]
Hi @oerdnj, when I try to install it it cannot be found:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php8.2-gd
E: Couldn't find any package by glob 'php8.2-gd'

The only available 8.2 packages seem to be the following:
php8.2-bcmath    php8.2-imap      php8.2-phpdbg    php8.2-xml
php8.2-cli       php8.2-mbstring  php8.2-readline  php8.2-zip
php8.2-common    php8.2-mysql     php8.2-ssh2      
php8.2-curl      php8.2-opcache   php8.2-xdebug 

Is there maybe something missing in my config?

Thanks a lot!

**Comment by oerdnj** [comment]
Well, the issue template that you wilfully ignored could give us some hints, but alas... we don't have that information.

**Comment by mallt** [comment]
Hi @oerdnj; 

I'm sorry, I thought I had to use the feature request template for this request.
I noticed now that after removing and re-adding the ppa the php8.2-gd package became available, so the issue is solved.

Thanks a lot!
