### ISSUE TITLE
PHP 8.2.9 for Debian

### ISSUE THREAD

**Issue by bcremer** [oerdnj/deb.sury.org#2016]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
PHP 8.2.9 is not available for Debian. 

It's available for Ubuntu: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8.2&field.status_filter=published&field.series_filter=

Apparently the 8.2.9 build is executing for 11 days already, see: https://jenkins.rfc1925.org/job/php_php8.2-binaries/25/

**Distribution (please complete the following information):**
    OS: Debian
    Architecture: amd64
    Repository: [packages.sury.org**](https://packages.sury.org/php/)

**Comment by oerdnj** [comment]
Should be good now.  Thanks for the ping...
