### ISSUE TITLE
memcached.so fails to load with missing symbol php_msgpack_serialize after upgrade to 8.1.22-2 packages

### ISSUE THREAD

**Issue by tabacco** [oerdnj/deb.sury.org#2018]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
We're seeing the following error starting with an upgrade to the latest release of the php 8.1 packages
> PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20210902/memcached.so (/usr/lib/php/20210902/memcached.so: undefined symbol: php_msgpack_serialize), /usr/lib/php/20210902/memcached.so.so (/usr/lib/php/20210902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

The upgrade was between the following package versions:
Before (working): ```8.1.22-1+ubuntu20.04.1+deb.sury.org+1```
After (not working): ```8.1.22-2+ubuntu20.04.1+deb.sury.org+1```

This issue *only* occurs if you upgrade from one package to the other. If you start clean with the newest packages, it works fine.

**To Reproduce**
1. Starting with a docker image with an installation of php8.1 (see below for package versions)
    * ```
      root@a8a9637798ed:/# apt list --installed | grep php
      php-common/now 2:93+ubuntu20.04.1+deb.sury.org+2 all [installed,local]
      php8.1-apcu/now 5.1.22+4.0.11-2+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-cli/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-common/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-curl/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-dba/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-gd/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-igbinary/now 3.2.14-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-intl/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-mbstring/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-memcached/now 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-msgpack/now 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-mysql/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-opcache/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-readline/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-redis/now 5.3.7++-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-soap/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-sqlite3/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-xdebug/now 3.2.1++-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-xml/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-xmlrpc/now 3:1.0.0~rc3-5+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      php8.1-zip/now 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,local]
      ```
  1. ```apt-get update```
  2. ```apt-get upgrade```
  3. ```php -v```

**Your understanding of what is happening**
It appears upgrading php packages to this new release causes this error. An important note is that neither php8.1-msgpack nor php8.1-memcached are being upgraded (see below for the transcript). This issue only occurs when starting from the previous release of the php 8.1.22 packages, so I'm assuming something is being overwritten improperly in the upgrade. If I build a new image with the latest packages, everything works fine.

**What steps did you take to resolve issue yourself before reporting it here**
* Confirmed that it works as expected even on new builds of the image with the previous package versions.
* Confirmed that no other config has changed
* Starting with a working docker image (With the old release) I upgraded the php packages and confirmed that with no other config changes I now experienced the error (see end for a transcript of this attempt)
* Verified that installing clean from the latest packages works as expected

**Describe how did you try to resolve the issue yourself.  This is closely connected to the previous question.**
 * I'm not sure how to answer this question differently, I'm sorry. 

**Expected behavior**
I expect php -v to return normally, with no errors, following an upgrade.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
 * See below, I'm happy to provide before/after for any other packages as I have a working image I can repeatedly reproduce the issue in. Just let me know.

**Additional context**

```
root@da5c2e6a1656:/# apt-cache policy php8.1-memcached
php8.1-memcached:
  Installed: 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status

root@da5c2e6a1656:/# apt-cache policy php8.1-msgpack
php8.1-msgpack:
  Installed: 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status

root@da5c2e6a1656:/# apt-cache policy php8.1-common
php8.1-common:
  Installed: 8.1.22-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 8.1.22-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 8.1.22-1+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status

root@da5c2e6a1656:/# php -v
PHP 8.1.22 (cli) (built: Aug 14 2023 05:32:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies

root@da5c2e6a1656:/# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  php8.1-cli php8.1-common php8.1-curl php8.1-dba php8.1-gd php8.1-intl php8.1-mbstring php8.1-mysql php8.1-opcache php8.1-readline php8.1-soap php8.1-sqlite3 php8.1-xml php8.1-zip
14 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3704 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-zip amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [24.3 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-xml amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [109 kB]
Get:3 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-sqlite3 amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [29.3 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-soap amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [121 kB]
Get:5 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-readline amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [12.8 kB]
Get:6 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-opcache amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [337 kB]
Get:7 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-mysql amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [116 kB]
Get:8 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-mbstring amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [395 kB]
Get:9 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-intl amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [127 kB]
Get:10 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-gd amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [28.7 kB]
Get:11 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-dba amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [24.0 kB]
Get:12 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-curl amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [33.7 kB]
Get:13 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-cli amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [1673 kB]
Get:14 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 php8.1-common amd64 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 [674 kB]
Fetched 3704 kB in 11s (328 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 8883 files and directories currently installed.)
Preparing to unpack .../00-php8.1-zip_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-zip (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../01-php8.1-xml_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-xml (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../02-php8.1-sqlite3_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-sqlite3 (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../03-php8.1-soap_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-soap (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../04-php8.1-readline_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-readline (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../05-php8.1-opcache_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-opcache (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../06-php8.1-mysql_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-mysql (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../07-php8.1-mbstring_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-mbstring (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../08-php8.1-intl_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-intl (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../09-php8.1-gd_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-gd (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../10-php8.1-dba_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-dba (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../11-php8.1-curl_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-curl (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../12-php8.1-cli_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-cli (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Preparing to unpack .../13-php8.1-common_8.1.22-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php8.1-common (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) over (8.1.22-1+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-common (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-gd (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-curl (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-sqlite3 (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-xml (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-soap (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-mysql (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-zip (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-readline (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-opcache (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-intl (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-dba (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-mbstring (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php8.1-cli (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...
php_invoke xdebug: no action - module was disabled by maintainer for PHP 8.1 cli sapi
Processing triggers for php8.1-cli (8.1.22-2+ubuntu20.04.1+deb.sury.org+1) ...

root@da5c2e6a1656:/# php -v
[31-Aug-2023 04:05:34 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20210902/memcached.so (/usr/lib/php/20210902/memcached.so: undefined symbol: php_msgpack_serialize), /usr/lib/php/20210902/memcached.so.so (/usr/lib/php/20210902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.22 (cli) (built: Aug 29 2023 10:29:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies

root@da5c2e6a1656:/# apt-cache policy php8.1-memcached
php8.1-memcached:
  Installed: 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 3.2.0++-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

root@da5c2e6a1656:/# apt-cache policy php8.1-msgpack
php8.1-msgpack:
  Installed: 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 1:2.2.0~rc2-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

root@da5c2e6a1656:/# apt-cache policy php8.1-common
php8.1-common:
  Installed: 8.1.22-2+ubuntu20.04.1+deb.sury.org+1
  Candidate: 8.1.22-2+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 8.1.22-2+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
What are the contents of:

- /etc/php/8.2/<sapi>/ directory, for the <sapi> you are experiencing this problem?

- the contents of memcached.ini

- the contents of msgpack.ini

**Comment by tabacco** [comment]
Before the upgrade (working):
```
root@cf18a7a36ed7:/etc/php/8.1# find .
.
./mods-available
./mods-available/sqlite3.ini
./mods-available/igbinary.ini
./mods-available/ffi.ini
./mods-available/simplexml.ini
./mods-available/mysqli.ini
./mods-available/tokenizer.ini
./mods-available/calendar.ini
./mods-available/intl.ini
./mods-available/xmlrpc.ini
./mods-available/xmlwriter.ini
./mods-available/redis.ini
./mods-available/soap.ini
./mods-available/apcu.ini
./mods-available/memcached.ini
./mods-available/ftp.ini
./mods-available/dom.ini
./mods-available/msgpack.ini
./mods-available/iconv.ini
./mods-available/mbstring.ini
./mods-available/xmlreader.ini
./mods-available/exif.ini
./mods-available/fileinfo.ini
./mods-available/pdo.ini
./mods-available/dba.ini
./mods-available/shmop.ini
./mods-available/xml.ini
./mods-available/mysqlnd.ini
./mods-available/gd.ini
./mods-available/sysvmsg.ini
./mods-available/pdo_mysql.ini
./mods-available/xsl.ini
./mods-available/sysvshm.ini
./mods-available/xdebug.ini
./mods-available/sysvsem.ini
./mods-available/posix.ini
./mods-available/opcache.ini
./mods-available/pdo_sqlite.ini
./mods-available/ctype.ini
./mods-available/curl.ini
./mods-available/zip.ini
./mods-available/sockets.ini
./mods-available/readline.ini
./mods-available/phar.ini
./mods-available/gettext.ini
./mods-available/libsodium.ini
./cli
./cli/php.ini
./cli/conf.d
./cli/conf.d/20-xmlwriter.ini
./cli/conf.d/20-mysqli.ini
./cli/conf.d/20-gd.ini
./cli/conf.d/20-xsl.ini
./cli/conf.d/20-igbinary.ini
./cli/conf.d/20-zip.ini
./cli/conf.d/10-pdo.ini
./cli/conf.d/20-dom.ini
./cli/conf.d/20-sysvshm.ini
./cli/conf.d/20-ftp.ini
./cli/conf.d/20-gettext.ini
./cli/conf.d/20-simplexml.ini
./cli/conf.d/20-redis.ini
./cli/conf.d/20-ffi.ini
./cli/conf.d/20-intl.ini
./cli/conf.d/20-exif.ini
./cli/conf.d/20-tokenizer.ini
./cli/conf.d/20-apcu.ini
./cli/conf.d/20-xmlrpc.ini
./cli/conf.d/15-xml.ini
./cli/conf.d/20-pdo_sqlite.ini
./cli/conf.d/10-mysqlnd.ini
./cli/conf.d/20-pdo_mysql.ini
./cli/conf.d/20-xmlreader.ini
./cli/conf.d/20-dba.ini
./cli/conf.d/20-posix.ini
./cli/conf.d/20-shmop.ini
./cli/conf.d/20-sysvmsg.ini
./cli/conf.d/20-mbstring.ini
./cli/conf.d/20-sysvsem.ini
./cli/conf.d/20-iconv.ini
./cli/conf.d/20-curl.ini
./cli/conf.d/20-readline.ini
./cli/conf.d/10-opcache.ini
./cli/conf.d/20-sqlite3.ini
./cli/conf.d/20-calendar.ini
./cli/conf.d/20-sockets.ini
./cli/conf.d/20-phar.ini
./cli/conf.d/20-soap.ini
./cli/conf.d/20-msgpack.ini
./cli/conf.d/20-ctype.ini
./cli/conf.d/20-fileinfo.ini
./cli/conf.d/25-memcached.ini
./apache2
./apache2/php.ini

root@cf18a7a36ed7:/etc/php/8.1# cat ./cli/conf.d/20-msgpack.ini
; configuration for php msgpack module
; priority=20
extension=msgpack.so

root@cf18a7a36ed7:/etc/php/8.1# cat ./cli/conf.d/25-memcached.ini
extension=memcached.so
; You need to install php-igbinary package to use igbinary serializer
; and php-msgpack to use msgpack serializer
memcached.serializer=php
memcached.store_retry_count=2
```

After the upgrade (not working):
```
root@cf18a7a36ed7:/etc/php/8.1# find .
.
./mods-available
./mods-available/sqlite3.ini
./mods-available/igbinary.ini
./mods-available/ffi.ini
./mods-available/simplexml.ini
./mods-available/mysqli.ini
./mods-available/tokenizer.ini
./mods-available/calendar.ini
./mods-available/intl.ini
./mods-available/xmlrpc.ini
./mods-available/xmlwriter.ini
./mods-available/redis.ini
./mods-available/soap.ini
./mods-available/apcu.ini
./mods-available/memcached.ini
./mods-available/ftp.ini
./mods-available/dom.ini
./mods-available/msgpack.ini
./mods-available/iconv.ini
./mods-available/mbstring.ini
./mods-available/xmlreader.ini
./mods-available/exif.ini
./mods-available/fileinfo.ini
./mods-available/pdo.ini
./mods-available/dba.ini
./mods-available/shmop.ini
./mods-available/xml.ini
./mods-available/mysqlnd.ini
./mods-available/gd.ini
./mods-available/sysvmsg.ini
./mods-available/pdo_mysql.ini
./mods-available/xsl.ini
./mods-available/sysvshm.ini
./mods-available/xdebug.ini
./mods-available/sysvsem.ini
./mods-available/posix.ini
./mods-available/opcache.ini
./mods-available/pdo_sqlite.ini
./mods-available/ctype.ini
./mods-available/curl.ini
./mods-available/zip.ini
./mods-available/sockets.ini
./mods-available/readline.ini
./mods-available/phar.ini
./mods-available/gettext.ini
./mods-available/libsodium.ini
./cli
./cli/php.ini
./cli/conf.d
./cli/conf.d/20-xmlwriter.ini
./cli/conf.d/20-mysqli.ini
./cli/conf.d/20-gd.ini
./cli/conf.d/20-xsl.ini
./cli/conf.d/20-igbinary.ini
./cli/conf.d/20-zip.ini
./cli/conf.d/10-pdo.ini
./cli/conf.d/20-dom.ini
./cli/conf.d/20-sysvshm.ini
./cli/conf.d/20-ftp.ini
./cli/conf.d/20-gettext.ini
./cli/conf.d/20-simplexml.ini
./cli/conf.d/20-redis.ini
./cli/conf.d/20-ffi.ini
./cli/conf.d/20-intl.ini
./cli/conf.d/20-exif.ini
./cli/conf.d/20-tokenizer.ini
./cli/conf.d/20-apcu.ini
./cli/conf.d/20-xmlrpc.ini
./cli/conf.d/15-xml.ini
./cli/conf.d/20-pdo_sqlite.ini
./cli/conf.d/10-mysqlnd.ini
./cli/conf.d/20-pdo_mysql.ini
./cli/conf.d/20-xmlreader.ini
./cli/conf.d/20-dba.ini
./cli/conf.d/20-posix.ini
./cli/conf.d/20-shmop.ini
./cli/conf.d/20-sysvmsg.ini
./cli/conf.d/20-mbstring.ini
./cli/conf.d/20-sysvsem.ini
./cli/conf.d/20-iconv.ini
./cli/conf.d/20-curl.ini
./cli/conf.d/20-readline.ini
./cli/conf.d/10-opcache.ini
./cli/conf.d/20-sqlite3.ini
./cli/conf.d/20-calendar.ini
./cli/conf.d/20-sockets.ini
./cli/conf.d/20-phar.ini
./cli/conf.d/20-soap.ini
./cli/conf.d/20-msgpack.ini
./cli/conf.d/20-ctype.ini
./cli/conf.d/20-fileinfo.ini
./cli/conf.d/25-memcached.ini
./cli/conf.d/20-memcached.ini
./apache2
./apache2/php.ini
root@cf18a7a36ed7:/etc/php/8.1# cat ./cli/conf.d/20-msgpack.ini
; configuration for php msgpack module
; priority=20
extension=msgpack.so
root@cf18a7a36ed7:/etc/php/8.1# cat ./cli/conf.d/25-memcached.ini
extension=memcached.so
; You need to install php-igbinary package to use igbinary serializer
; and php-msgpack to use msgpack serializer
memcached.serializer=php
memcached.store_retry_count=2
```

**Comment by bashgeek** [comment]
You load memcached twice:
```
./cli/conf.d/25-memcached.ini
./cli/conf.d/20-memcached.ini
```

and the 20 one before loading msgpack.

**Comment by tabacco** [comment]
Interesting... that file's not there before the update (see the before list), so one of the update packages appears to be adding it?

**Comment by oerdnj** [comment]
Yep, that's on you. You stripped the priority from the memcached.ini.

**Comment by tabacco** [comment]
I'm not convinced it is, but oh well, I tried.

**Comment by oerdnj** [comment]
The priority system isn't bulletproof, but it works well enough.  Making it more robust would require substantial effort which isn't really worth it.  Just make sure you keep the priorities intact, or at least disable the extension first, change the priority, and then re-enable it again.

Messing with priorities on enabled extensions just creates this mess.  Messing with priorities without knowing you are messing with priorities also creates mess for extensions that have dependencies. They need to load in proper order.
