### ISSUE TITLE
getallheaders function is missing in php5.6-fpm 5.6.40-67+0~20230815.79+debian11~1.gbpcb4298

### ISSUE THREAD

**Issue by lota** [oerdnj/deb.sury.org#2019]
After last update seems a old bug (due missing patch)  reappear again, seems the same of two solved bug:

https://github.com/oerdnj/deb.sury.org/issues/440
https://github.com/oerdnj/deb.sury.org/issues/928

I get

` Fatal error: Call to undefined function getallheaders() in ........../test.php on line 7`

with

> Package: php5.6-fpm
> Source: php5.6
> Version: 5.6.40-67+0~20230815.79+debian11~1.gbpcb4298
> Architecture: amd64
> Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
> Installed-Size: 4473

installed from

https://packages.sury.org/php bullseye/main amd64 php5.6-fpm amd64 5.6.40-67+0~20230815.79+debian11~1.gbpcb4298 [1.293 kB]
 
TIA & HTH

Alessandro

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/440#issuecomment-788784928

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/928#issuecomment-414104873
