### ISSUE TITLE
Align Apache2 PHP module identifier to php<Maj>_module instead of php_module

### ISSUE THREAD

**Issue by sndrsmnk** [oerdnj/deb.sury.org#2020]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

The Apache2 php module provided has a 'module identifier' of `php_module`:
```
# apache2ctl -t -D DUMP_MODULES
[ .. ]
 php_module (shared)
[ .. ]
```

Ansible's `community.general.apache2_module` module expects this to be `php<MajVer>_module` on Debian-derivative systems. Because of this it tries to enable the module that is already enabled, which fails the Ansible task etc:
```
failed: [test-host.dmz.bit.nl] (item=php8.2) [..]
Module php8.2 already enabled [..]
Maybe the module identifier (php8_module) was guessed incorrectly. Consider setting the "identifier" option.
```

It would be real nice if your `libapache2-mod-phpM.m`-packages could use the same `php<MajVer>_module` module identifier in the Apache module as the 'stock' distribution packages do.

Setting the `identifier` option in Ansible sure does fix it, but will break on non-Ondřej Surý packages and will likely break when f.e. php9 comes out ,etc.

 - OS: Ubuntu 22.04 Jammy Jellyfish
 - Architecture: amd64
 - Repository: Ubuntu PPA

```
# apt-cache policy libapache2-mod-php8.2
libapache2-mod-php8.2:
  Installed: 8.2.9-2+ubuntu22.04.1+deb.sury.org+1
  Candidate: 8.2.9-2+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 8.2.9-2+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by chriscroome** [comment]
@sndrsmnk is the Ansible role you are using for installing and configuring PHP on Ubuntu a public one?

**Comment by sndrsmnk** [comment]
It's the `community.general.apache2_module` module that comes with Ansible that 'fails' with Ondřej's mod_php.  I seem to have left that out of the original post.

**Comment by oerdnj** [comment]
The module identifier is provided by PHP upstream. I am not going to mangle it.

```
5.6: extern module AP_MODULE_DECLARE_DATA php5_module;
7.0: extern module AP_MODULE_DECLARE_DATA php7_module;
7.1: extern module AP_MODULE_DECLARE_DATA php7_module;
7.2: extern module AP_MODULE_DECLARE_DATA php7_module;
7.3: extern module AP_MODULE_DECLARE_DATA php7_module;
7.4: extern module AP_MODULE_DECLARE_DATA php7_module;
8.0: extern module AP_MODULE_DECLARE_DATA php_module;
8.1: extern module AP_MODULE_DECLARE_DATA php_module;
8.2: extern module AP_MODULE_DECLARE_DATA php_module;
8.3: extern module AP_MODULE_DECLARE_DATA php_module;
```

**Comment by oerdnj** [comment]
The Ansible module needs to be fixed.

**Comment by chriscroome** [comment]
The `ansible.community.general` [issues are here](https://github.com/ansible-collections/community.general/issues)
