### ISSUE TITLE
Add `--enable-cares` to allow async DNS requests with swoole

### ISSUE THREAD

**Issue by binaryfire** [oerdnj/deb.sury.org#2023]
Since v4.7, Swoole supports making async DNS requests with `C-ares`: https://openswoole.com/article/v4-7-0-released. This is from the OpenSwoole website but the same applies to `swoole-src`

It'd be great to have this enabled so we can take advantage of the [libc-ares-dev](https://packages.ubuntu.com/jammy/libc-ares-dev) package with Swoole.

**Comment by oerdnj** [comment]
Should be enabled now.
