### ISSUE TITLE
Latest version 2.1.0 for php-amqp

### ISSUE THREAD

**Issue by sylfabre** [oerdnj/deb.sury.org#2027]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**
The package `php-amqp` provides version 1.11.0 which was released on December 1st, 2021.

Versions 2.0 and 2.1 were released in August 2023 and earlier in September: https://pecl.php.net/package/amqp

Would you please consider publishing new releases of the php-amqp package with these latest versions?

And thanks a lot for this PPA 🤩 

**Distribution:**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
`php-amqp` was updated to 2.1.0 and `php-amqp-1` was split off to support PHP < 7.4

**Comment by sylfabre** [comment]
Thanks a lot @oerdnj

**Comment by tvlooy** [comment]
We use the Symfony 8.0 messenger component with php 8.0, which is not compatible with ext/amqp 2.x. We can't upgrade the component right now. Is it an option to publish the packages as php8.0-amqp / php8.0-amqp-1 and drop support in the next release? I manually compiled it now to fix the issue but I'd rather use a packaged version.
