### ISSUE TITLE
php 8.2 - pdo_odbc - Segmentation fault

### ISSUE THREAD

**Issue by caiofior** [oerdnj/deb.sury.org#2028]
Running a php script that uses pdo_odbc generates a segmentation fault.

The data source is and  mdb database, mdbtool is installed and work ad expected

mdb-tables /home/caiofior/public_html/cap_data/capstreetfile.mdb 
AbbreviazioniDug ArcoStradale Comune ComuneAlias Frazione FrazioneAlias Provincia Regione Strada StradaAlias VariazioniAbbreviazioniDUG VariazioniArcoStradale VariazioniComune VariazioniComuneAlias VariazioniFrazione VariazioniFrazioneAlias VariazioniProvincia VariazioniRegione VariazioniStrada VariazioniStradaAlias Versione

PHP version is 8.2, Operating system is Debian 12 amd64

cat /etc/apt/sources.list.d/php.list 
deb https://packages.sury.org/php/ bookworm main

In var/log/syslog I found

2023-09-26T11:03:31.292131+02:00 debian kernel: [ 8432.008357] php[43202]: segfault at 7fc86f41a000 ip 00007fc871771b10 sp 00007ffdb9642538 error 4 in libc.so.6[7fc871645000+155000] likely on CPU 0 (core 0, socket 0)
2023-09-26T11:03:31.292141+02:00 debian kernel: [ 8432.008366] Code: 00 00 c5 fe 6f be 60 10 00 00 c5 7e 6f 86 00 20 00 00 c5 7e 6f 8e 20 20 00 00 c5 7e 6f 96 40 20 00 00 c5 7e 6f 9e 60 20 00 00 <c5> 7e 6f a6 00 30 00 00 c5 7e 6f ae 20 30 00 00 c5 7e 6f b6 40 30

Thank you for your patience.

**Comment by gnif** [comment]
This gives no useful information.

1. Enable core dumps (`apt-get install systemd-coredump`)
2. Restart PHP
3. Wait for another error
4. Check `coredump list` for a dump when the process crashes.
5. Use `coredump gdb PID` where `PID` is the `PID` listed in the coredump output.
6. type `bt` and press return to obtain a full back-trace that tells the developers where the crash was and what lead up to it.

**Comment by oerdnj** [comment]
Also this is not really a packaging issue.

**Comment by caiofior** [comment]
[coredump.zip](https://github.com/oerdnj/deb.sury.org/files/12794169/coredump.zip)
I enclosed also the coredump

**Comment by gnif** [comment]
1) You should not share a core-dump like this, it contains a snapshot of the application memory at the time of the crash which may include details such as credentials.

2) disable xdebug and see if the problem is resolved, if so you know it's the cause
2) To get more details in that trace instead of all the `n/a` entries, please install the php `-dbg` package


Please install the `dbg`
