### ISSUE TITLE
php8.0-redis in PPA currently has a bug that's been fixed upstream

### ISSUE THREAD

**Issue by aaron-hall-7** [oerdnj/deb.sury.org#2029]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
The current version of php8.0-redis contains a bug that was fixed upstream here: https://github.com/phpredis/phpredis/pull/2388

When installing php8.0-redis v6.0.0 from the PPA on Ubuntu 22.04 and connecting to a redis server on v6.0.5, we receive the error as described in the linked pull request. This was not an issue on v5.3.7.

To work around it, I downloaded v5.3.7 and installed that in our build process instead of adding the version from the PPA. Once the PPA gets updated, I can remove this workaround.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64 and arm64 depending on environment being built on
 - Repository: PHP PPA, specifically the php8.0-redis

**Package(s) (please complete the following information):**
php8.0-redis:
  Installed: 5.3.7+4.3.0-1+ubuntu21.10.1+deb.sury.org+1
  Candidate: 6.0.0-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
     6.0.0-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
 *** 5.3.7+4.3.0-1+ubuntu21.10.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status

**Additional context**
No further context that I can think of

**Comment by fliespl** [comment]
Alternativly - bug was fixed in pecl version 6.0.1. Can this be rebuilt, please? :)

**Comment by aaron-hall-7** [comment]
> 6.0.1 should be available soon...

Thank you for getting this updated. I've confirmed this has fixed my issue and we are operable again.

**Comment by fliespl** [comment]
@oerdnj Thank you - appreciate that as well!
