### ISSUE TITLE
php8.2-fpm systemd dependency

### ISSUE THREAD

**Issue by d0m84** [oerdnj/deb.sury.org#2031]
I upgraded to Debian bookworm today. The php8.2-fpm package inside the Debian main repository as well as the one on deb.sury.org depend on two systemd packages.

I'm using Debian without systemd and as the package also ships a init script I don't understand why those dependencies are there. Currently systemd is installed but not in use, but php8.2-fpm just runs fine with sysvinit without any sort of modification.

**Comment by d0m84** [comment]
@oerdnj Hi. It would be great if you could explain why the PHP packages need to have the systemd dependencies. Is there a reason?

**Comment by todeveni** [comment]
> why the PHP packages need to have the systemd dependencies. Is there a reason?

Did you try to look at the [FAQ](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#is-systemd-required)?

**Comment by d0m84** [comment]
@todeveni Sorry I didn't. Thanks for pointing to it.
