### ISSUE TITLE
Keep (at least) last version available

### ISSUE THREAD

**Issue by TheEvilCoder42** [oerdnj/deb.sury.org#2033]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
There was an update for `php8.1-redis` from 5.7.3 to 6.0.1 which, sadly, brought a major, breaking change for our applications.
I wasn't able to easily roll back to the last version with apt, since it wasn't available anymore.

**Describe the solution you'd like**
Please keep (at least) the last version of packages available, or don't just provide major version changes of extensions.

**Describe alternatives you've considered**
Had to purge the package and install it manually via pecl on all our servers.

**Distribution (please complete the following information):**
 - OS: Debian 11 Bullseye
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.1-redis:
  Installed: (none)
  Candidate: 6.0.1-1+0~20231006.53+debian11~1.gbpe91da2
  Version table:
     6.0.1-1+0~20231006.53+debian11~1.gbpe91da2 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```
Installed version before: `5.3.7++-1+0~20230619.51+debian11~1.gbp4ff337`

**Additional context**
Thanks for the hard work, we use this repo for almost all of our servers to run different php versions on the same server.

**Comment by oerdnj** [comment]
> Please keep (at least) the last version of packages available, or don't just provide major version changes of extensions.

The purpose of this repository is to provide latest available version of PHP and the extensions. The only exception is when there’s unfixed bug in the upstream and even then it’s preferred to patch the bug and not pick arbitrary older version.

I am not going to do this.
