### ISSUE TITLE
PHP 8.3 missing extension: xdebug

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#2034]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

As always, thanks for maintaining this.

On Debian 11 Bullseye, PHP 8.3 arm64 is still missing these extensions

apcu, imagick, memcached, redis, uploadprogress, xdebug, xhprof, xmlrpc

(from https://github.com/oerdnj/deb.sury.org/issues/2002#issuecomment-1699524952)

I believe they're all missing on amd64 as well, but didn't test.

**To Reproduce**

`sudo apt update && sudo apt install -y php8.3-xdebug`

**Your understanding of what is happening**

These haven't been built yet.

**What steps did you take to resolve issue yourself before reporting it here**

Waited a couple of months after original request (which was closed early). Tested again after latest push.

**Expected behavior**

I think most of these are ready. I have certainly heard that php8.3-xdebug is ready.

**Distribution (please complete the following information):**
 - OS: Debian Bullseye 11
 - Architecture: arm64 (and I think amd64)
 - Repository: Debian packages.sury.org

**Package(s) (please complete the following information):**
```
# apt-get update >/dev/null && for item in apcu imagick memcached redis uploadprogress xdebug xhprof xmlrpc; do apt-cache policy php8.3-$item; done
N: Unable to locate package php8.3-apcu
N: Couldn't find any package by glob 'php8.3-apcu'
N: Couldn't find any package by regex 'php8.3-apcu'
N: Unable to locate package php8.3-imagick
N: Couldn't find any package by glob 'php8.3-imagick'
N: Couldn't find any package by regex 'php8.3-imagick'
N: Unable to locate package php8.3-memcached
N: Couldn't find any package by glob 'php8.3-memcached'
N: Couldn't find any package by regex 'php8.3-memcached'
N: Unable to locate package php8.3-redis
N: Couldn't find any package by glob 'php8.3-redis'
N: Couldn't find any package by regex 'php8.3-redis'
N: Unable to locate package php8.3-uploadprogress
N: Couldn't find any package by glob 'php8.3-uploadprogress'
N: Couldn't find any package by regex 'php8.3-uploadprogress'
N: Unable to locate package php8.3-xdebug
N: Couldn't find any package by glob 'php8.3-xdebug'
N: Couldn't find any package by regex 'php8.3-xdebug'
N: Unable to locate package php8.3-xhprof
N: Couldn't find any package by glob 'php8.3-xhprof'
N: Couldn't find any package by regex 'php8.3-xhprof'
N: Unable to locate package php8.3-xmlrpc
N: Couldn't find any package by glob 'php8.3-xmlrpc'
N: Couldn't find any package by regex 'php8.3-xmlrpc'
```

**Additional context**

Followup from (closed) 
* https://github.com/oerdnj/deb.sury.org/issues/2002

**Comment by ernolf** [comment]
If you absolutely needs the missing modules immediately, be it for your development environment or to test new software, then you should take a look [--> here <--](https://help.nextcloud.com/t/nextcloud-28-with-php8-3-on-debian-ubuntu-missing-modules-solution/174766)

Much luck,
ernolf

**Comment by rfay** [comment]
There's also @crazywhalecc's  https://github.com/crazywhalecc/static-php-cli, which probably has more miles on it and is extensively maintained. But of course... nothing replaces this fantastic project!

**Comment by elcheco** [comment]
I have the same issue with these extensions: apcu, igbinary, memcache, redis, xdebug

**Comment by 3kbest** [comment]
I have same issues with redis, imagick and openswoole

**Comment by onlime** [comment]
As always, this is not a real issue, it's just called patience. @oerdnj was always very fast in the past, for the last decades, providing us with perfectly built packages. On a major PHP release, this takes some more effort, we all know! Be assured Ondřej is on it and it will rather get released sooner than later.

Thanks @oerdnj for your tremendous support. Take a break and release the missing extensions whenever you find time. We appreciate any single second you work on this project!

Cheers, Philip

**Comment by oerdnj** [comment]
Thanks @onlime, I think I should be able to have most of them during the weekend.

**Comment by elcheco** [comment]
@onlime - it's just about communication; when there's some reply or at least a rough estimation, the people have patience, but when there's an open issue without any maintainer note/reply, people start to be desperate 😄 

Thank you for the note, @oerdnj. You're doing a tremendous job for the PHP community on Linux.

**Comment by f1mishutka** [comment]
Amazing timing! apcu, igbinary, memcache, redis are already there!

@oerdnj , many many thanks for everything! All your efforts are very appreciated!

**Comment by oerdnj** [comment]
Not everything is peachy yet though (libvirt, lz4 and maybe more).  I'll chew through the failed builds in the following days.

**Comment by rfay** [comment]
My most-anticipated PHP8.3 extension is xdebug, but I don't see that in the builds at https://jenkins.rfc1925.org/job/php_xdebug-binaries/ - Do I just not know where to look?

**Comment by oerdnj** [comment]
> My most-anticipated PHP8.3 extension is xdebug, but I don't see that in the builds at https://jenkins.rfc1925.org/job/php_xdebug-binaries/ - Do I just not know where to look?

There is no xdebug for PHP 8.3 yet.

**Comment by rfay** [comment]
Thanks, and of course thanks for all your work on all of this. @derickr did claim preliminary support in 3.3.0-alpha1, and is now at 3.3.0-alpha3, https://xdebug.org/updates. I had heard that it was working OK.

**Comment by ernolf** [comment]
> There is no xdebug for PHP 8.3 yet.

m4_patch='s/80300/80400/'

It works great for me

**Comment by rfay** [comment]
Yay, I see the only missing extensions from the original list are memcached, redis, xdebug. memcached and redis failed to build, xdebug hasn't been queued yet.

**Comment by oerdnj** [comment]
Waiting for igbinary to finish building: https://jenkins.rfc1925.org/view/PHP/job/php_php-igbinary-binaries/45/

**Comment by adpeyre** [comment]
Xdebug 3.3 is tagged https://github.com/xdebug/xdebug/tags
Soon :)

**Comment by derickr** [comment]
Writing the release announcement right now...

**Comment by joshcangit** [comment]
All of the dependency packages, including `php` depend on the previous version, **8.3**.
They need to be updated so that all the packages can also move up as well.

**Comment by oerdnj** [comment]
> All of the dependency packages, including `php` depend on the previous version, **8.2**. They need to be updated to so that all the packages can also move up as well.

This issue has subject: "PHP 8.3 missing extensions memcached, redis, xdebug"

How is your comment related to the topic?

**Comment by joshcangit** [comment]
> 
> This issue has subject: "PHP 8.3 missing extensions memcached, redis, xdebug"
> 
> How is your comment related to the topic?

Sorry, I think what I've said should've been another issue.

**Comment by bobvandevijver** [comment]
Would love to see xdebug 3.3 for PHP 8.3, seems to be the only package missing to be able to upgrade our development environment.

**Comment by rfay** [comment]
Updated title, only xdebug remains, thanks!

php8.3-redis and php8.3-memcached are now available.

**Comment by oerdnj** [comment]
Nope, I just forgot to push the build button for Debian.

**Comment by onlime** [comment]
It's there! Thanks a bunch, @oerdnj
Close this issue & let's 💃🕺🎉 !!

**Comment by rfay** [comment]
Yay thanks!

**Comment by stasadev** [comment]
`php8.3-memcached` is only available for amd64, other builds failed.
https://jenkins.rfc1925.org/view/PHP/job/php_php-memcached-binaries/

**Comment by oerdnj** [comment]
> `php8.3-memcached` is only available for amd64, other builds failed. https://jenkins.rfc1925.org/view/PHP/job/php_php-memcached-binaries/

Issued a rebuild now - igbinary is now available on all archs, so the builds should not fail now.

**Comment by rahulgupta-acquia** [comment]
Hi,
Still when i used php 8.3.1 ( xdebug.so extension is missing)
Could you please share the link where i can check the available extension of PHP8.3 + xdebug?
Thanks

**Comment by rfay** [comment]
`sudo apt update && sudo apt install -y php8.3-xdebug` will get this for you if you have the deb.sury.org repositories installed.  (deb.sury.org repos currently provide 8.3.2 of php and xdebug 3.3.1)

**Comment by bobo333** [comment]
> Not everything is peachy yet though (libvirt, lz4 and maybe more). I'll chew through the failed builds in the following days.

Hi, I see `php8.3-libvirt` is available, but it seems `php8.3-lz4` is not. Is it possible to get that added? Thank you for all the work you do!
