### ISSUE TITLE
Lack of php-swoole module for php8.1/8.2 at Debian12

### ISSUE THREAD

**Issue by repcio** [oerdnj/deb.sury.org#2035]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
There are no modules php8.x-swoole for Debian12 (Bookworm).
I have checked list of all packages here:
https://packages.sury.org/php/pool/main/p/php-swoole/
and 
https://packages.sury.org/php/pool/main/p/php8.2/

**To Reproduce**
On Debian12 / Bookworm
#apt install php8.2-swoole php8.1-swoole 
root@web-build:~# LC_ALL=C apt-cache policy php8.1-swoole
N: Unable to locate package php8.1-swoole
N: Couldn't find any package by glob 'php8.1-swoole'
N: Couldn't find any package by regex 'php8.1-swoole'
root@web-build:~# LC_ALL=C apt-cache policy php8.2-swoole
N: Unable to locate package php8.2-swoole
N: Couldn't find any package by glob 'php8.2-swoole'
N: Couldn't find any package by regex 'php8.2-swoole'
root@web-build:~# lsb_release -ar
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Your understanding of what is happening**
Module swoole is not building on Debian12

**What steps did you take to resolve issue yourself before reporting it here**
I have checked opened issues 

**Expected behavior**
Swoole module for php8.1/8.2 will be possible to install

**Distribution (please complete the following information):**
 - OS: Debian 12
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
root@web-build:~# LC_ALL=C apt-cache policy php8.1-swoole
N: Unable to locate package php8.1-swoole
N: Couldn't find any package by glob 'php8.1-swoole'
N: Couldn't find any package by regex 'php8.1-swoole'
root@web-build:~# LC_ALL=C apt-cache policy php8.2-swoole
N: Unable to locate package php8.2-swoole
N: Couldn't find any package by glob 'php8.2-swoole'
N: Couldn't find any package by regex 'php8.2-swoole'
root@web-build:~# lsb_release -ar
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Additional context**

**Comment by oerdnj** [comment]
Should be available now:

```
$ apt-cache policy php8.1-swoole
php8.1-swoole:
  Installed: (none)
  Candidate: 5.1.3-2+0~20240623.23+debian12~1.gbp40aead
  Version table:
     5.1.3-2+0~20240623.23+debian12~1.gbp40aead 1001
       1001 https://packages.sury.org/php bookworm/main amd64 Packages
```
