### ISSUE TITLE
[courier] some extra tweaks for esmtp/imap 0.75

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#204]
Finally I am sending and receiving mails. The main problem, and probably all along aside from some permissions adjustment, was that the `courier` daemon was not being started! The original /etc/init.d/courier-mta startup script starts /usr/sbin/courier, /usr/sbin/courierfilter, /usr/sbin/esmtpd and then /usr/sbin/esmtpd-msa where the last 2 are conditional depending on $ESMTPDSTART in the /etc/courier config files.

It seems that starting multiple daemons from a single systemd service file may not be possible so there will have to be separate files and maybe some adjustment of Requires= and After= may work. I have no idea how to emulate the $ESMTPDSTART env var trick to decide whether to start esmtpd and esmtpd-msa.

It's also possible that the suid programs need to be 4755 root:courier rather than courier:courier but I haven't had time to revert my manual changes or do a fresh install to confirm this.

One extra thing that is needed is to create a /etc/courier/imapaccess directory and to run makeimapaccess whereever makehosteddomains and makeacceptmailfor are run in the install script otherwise imapd/imapd-ssl won't start up.

And /var/run/courier needs to be -g+rwx :courier for the courierfilter.pid file.
```
~ cat /lib/systemd/system/courier.service
[Unit]
Description=Courier Daemon
Requires=courier-authdaemon.service
After=courier-authdaemon.service

[Service]
Type=forking
ExecStart=/usr/sbin/courier start
ExecStop=/usr/sbin/courier stop

[Install]
WantedBy=multi-user.target
```
```
~ cat /lib/systemd/system/courier-filter.service
[Unit]
Description=Courier Filter Daemon
Requires=courier-authdaemon.service
After=courier-authdaemon.service

[Service]
Type=forking
ExecStart=/usr/sbin/courierfilter start
ExecStop=/usr/sbin/courierfilter stop
PIDFile=/var/run/courier/courierfilter.pid

[Install]
WantedBy=multi-user.target
```

**Comment by markc** [comment]
I just `systemctl enable` all the courier service files and rebooted my container and I can send/receive mail :)

**Comment by oerdnj** [comment]
> It's also possible that the suid programs need to be 4755 root:courier rather than courier:courier but I haven't had time to revert my manual changes or do a fresh install to confirm this.

Definitely not - that would mean they would run under root user.

**Comment by oerdnj** [comment]
re imapaccess, like this?

```
$ cat courier-mta.imapaccess.service
[Unit]
Description=Courier MTA imapaccess

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=mkdir -m 0750 /etc/courier/imapaccess
ExecStart=/usr/lib/courier/makeimapaccess
ExecStart=chown -R root:courier /etc/courier/imapaccess/
```

**Comment by oerdnj** [comment]
Which daemons need the `/etc/courier/imapaccess`? All or just imapd?

**Comment by markc** [comment]
Just imapd. Wherever you created the /etc/courier/hosteddomains and /etc/courier/esmtpacceptmailfor.dir needs to be /etc/courier/imapaccess and wherever you run makehosteddomains and makeacceptmailfor needs to be a makeimapaccess. It's the imap equivalent of smtpaccess but it doesn't matter if it's an empty folder and imapaccess.dat file, it just needs to be there or imapd won't start.

**Comment by markc** [comment]
_Definitely not - that would mean they would run under root user._

Yes exactly. They are root suid on every other courier install I have and at some point one of these suid programs has to create files in non-courier owned user Maildirs with varying user assigned uid:gids.

**Comment by markc** [comment]
_re imapaccess, like this?_

Not really, although that is a neat solution. It only needs to be done once when the packages are installed. There is this in courier-mta.postinst

        for dir in esmtpacceptmailfor.dir hosteddomains; do

then further down there is...

       # run makesmtpaccess
       makesmtpaccess

so the same sections need to go into courier-imap.postinst but with just imapaccess and makeimapaccess.

OIC, makehosteddomains and makeacceptmailfor are NOT run during installation to create what would otherwise be empty *.dat files. Courier will still work without them but only deliver local mail for the local host.

**Comment by oerdnj** [comment]
> Yes exactly. They are root suid on every other courier install I have and at some point one of these suid programs has to create files in non-courier owned user Maildirs with varying user assigned uid:gids.

I see, I was missing setuid on sendmail and rmail. maildrop should already have correct permissions.

Both should be fixed in courier_0.75.0-8+deb.sury.org~<dist>+2 upload.
