### ISSUE TITLE
Upgrade Apache to 2.4.58

### ISSUE THREAD

**Issue by stondino00** [oerdnj/deb.sury.org#2040]
https://downloads.apache.org/httpd/CHANGES_2.4.58

**Comment by Badb0yBadb0y** [comment]
@oerdnj 
May I know a very rough estimation when this is going to be in the repo? If takes weeks I'll turn off http2 for now and turn back once released but if it is days, I'll keep it as is.

**Comment by oerdnj** [comment]
Uploaded and building. Sorry for the delay, I was too busy with other stuff.

**Comment by stondino00** [comment]
No worries.  Thanks so much for your hard work on this.

**Comment by Badb0yBadb0y** [comment]
Exactly, not hurry, take your time. However thank you the fast built, I’ve
applied already do to this ddos issue.
