### ISSUE TITLE
Could not handshake: A TLS fatal alert has been received. [IP: 37.19.207.34 443]

### ISSUE THREAD

**Issue by retry-the-user** [oerdnj/deb.sury.org#2041]
**Frequently asked questions**

- [X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ X] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Ran apt update per usual:
Ign:1 https://packages.sury.org/php bookworm InRelease
Ign:1 https://packages.sury.org/php bookworm InRelease
Err:1 https://packages.sury.org/php bookworm InRelease
  Could not handshake: A TLS fatal alert has been received. [IP: 37.19.207.34 443]

**Your understanding of what is happening**
Another server at another location reaches the domain correctly (On a different IP). When I add that IP using /etc/hosts, the problem is resolved.  However, it would be better to fix the problem on the server in question since this is an issue with the load balancing.

**What steps did you take to resolve issue yourself before reporting it here**
I also attempted to reach the server IP in question from home with similar failure:

$ grep packages.sury.org /etc/hosts
37.19.207.34 packages.sury.org

$ curl https://packages.sury.org
curl: (35) OpenSSL/1.1.1w: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

**Expected behavior**
Working debian package node...

**Distribution (please complete the following information):**
  - OS: Debian 11 and 12
  - Architecture: amd64 and an AWS cloud instance
  - Repository: packages.sury.org

**Package(s) (please complete the following information):**
N/A

**Comment by todeveni** [comment]
FWIW, that IP works for me on Debian bookworm.

```
⇒  curl -vvv --resolve packages.sury.org:443:37.19.207.34 https://packages.sury.org
* Added packages.sury.org:443:37.19.207.34 to DNS cache
* Hostname packages.sury.org was found in DNS cache
*   Trying 37.19.207.34:443...
* Connected to packages.sury.org (37.19.207.34) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=packages.sury.org
*  start date: Sep 12 22:10:59 2023 GMT
*  expire date: Dec 11 22:10:58 2023 GMT
*  subjectAltName: host "packages.sury.org" matched cert's "packages.sury.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
```

**Comment by retry-the-user** [comment]
Seems to have been a temporary issue with that server. Thanks for verifying.
