### ISSUE TITLE
ppa ondrej:php ubuntu response  connection failed

### ISSUE THREAD

**Issue by tszl004** [oerdnj/deb.sury.org#2045]
When I run `sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php`, response:
```
Err:6 https://ppa.launchpadcontent.net/ondrej/php/ubuntu focal InRelease
  Connection failed [IP: 185.125.190.52 443]
Reading package lists... Done
W: Failed to fetch https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/focal/InRelease  Connection failed [IP: 185.125.190.52 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

These words means some files is missing. I check InRelease files list, `Packages` is missing. I try to visit link `https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/focal/main/binary-amd64/Packages`, page is 404.
What can I do for it? 

System: Windows
Sub System: Ubuntu-20.04

**Comment by oerdnj** [comment]
This is outside my control. I don't run launchpad.net.

> What can I do for it?

I would say wait a little bit until your ISP fixes the connection issues.
