### ISSUE TITLE
upgrade phalcon

### ISSUE THREAD

**Issue by tibz7** [oerdnj/deb.sury.org#2049]
Please could you add the latest version for php -phalcon for debian bookworm?
The latest is one year old: 
`php8.1-phalcon5/bookworm,now 5.1.2-1+0~20230618.4+debian12~1.gbpb44906 amd64 [installed]`

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: X64
 - Repository:  packages.sury.org

**Package(s) (please complete the following information):**
`php8.0-phalcon5/bookworm`

**Comment by ISnotes** [comment]
Phalcon 5 support php 8.2 is being pulled up, there is still an old version for php 8.1 in the repository. Please update, there are not enough current packages for the correct operation of the service, which requires PHP 8.2 and dependencies

**Comment by wbertier** [comment]
Hi, I am also interested for this update.
On debian 12 (bookworm) with the default version of php (php8.2), it is not possible to install phalcon, only php8.1-phalcon5 is present.
php8.1-phalcon5 is in version 5.1 of phalcon which is not compatible with php8.2.
​Today phalcon (5.6) is compatible with PHP 8.2 and PHP 8.3.

**Comment by ISnotes** [comment]
UP

**Comment by rayanlevert** [comment]
I am interested as well, Phalcon just released version 5.6.1 which is fully compatible with php8.2 and php8.3 :)
Thanks in advance.
