### ISSUE TITLE
Upgrade php-mailparse to 3.1.6

### ISSUE THREAD

**Issue by henrikalves** [oerdnj/deb.sury.org#2051]
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
The latest php-mailparse version currently provided is version 3.1.4, as seen on: https://packages.sury.org/php/pool/main/p/php-mailparse/

**Describe the solution you'd like**
Add mailparse 3.1.6 packages to php-mailparse in the repo.

**Distribution (please complete the following information):**
OS: Debian
Architecture: amd64
Repository: packages.sury.org

**Additional context**
https://pecl.php.net/package/mailparse
3.1.5 and 3.1.6 fixes some Segmentation faults

**Comment by oerdnj** [comment]
This has been already done.
