### ISSUE TITLE
Remove old unsupported and empty distributions from Ubuntu PPA

### ISSUE THREAD

**Issue by wolfgangkarall** [oerdnj/deb.sury.org#2052]
**Frequently asked questions**

- [ X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X ] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
@oerdnj Hi Ondřej,

any chance to make the old unsupported PPA URLs not return successfully when `apt update` is run?

http://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/ still has plenty of unsupported distributions, which are all empty but still provide all files (InRelease, Packages.*) that make APT happily use the repository without errors, but alas, also without any packages available from them.

So, on such an installation, APT will never complain that something is amiss. Installed packages will just be left installed on their last version (visible with e.g. `aptitude search ?obsolete`, or also `apt list ?obsolete` on newer versions) and never get any updates.

This of course is worse than getting an actual error from APT to draw attention to the problem, hence I consider this a bug.

Tested with the distribution bionic, i.e.

```
deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main
```

The Debian repository OTOH is fine, only the 3 supported distributions in https://packages.sury.org/php/dists/
 
Cheers
Wolfgang

**Comment by oerdnj** [comment]
That's a good question and good idea, but TBH I have no idea.  This whole thing is controlled by Canonical/Launchpad, so it might be better targeted at them.

**Comment by wolfgangkarall** [comment]
Oh, I thought it was something you as PPA owner could fix, e.g. by actively deleting such obsolete distributions or some such.

But looking at https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/dists/ and others, I see most of them have ancient releases (some have edgy which was EOL'ed 15+ years ago) with valid but empty repositories, so this seems a more general problem indeed.

**Comment by oerdnj** [comment]
It would be great if you have time to report this to the Launchpad team (and link back here for reference). I don't have that time now, so any help is appreciated.

**Comment by wolfgangkarall** [comment]
Not sure when I will get around to it, either, I'm not having a launchpad account available atm and that seems necessary to report a bug at https://bugs.launchpad.net/launchpad

**Comment by wolfgangkarall** [comment]
@oerdnj Was this closed as 'completed' on purpose or by accident? I hope the latter, as open issues still help other people see problems even if they're not resolved yet.
