### ISSUE TITLE
Nchan upgrade to the latest version

### ISSUE THREAD

**Issue by naquad** [oerdnj/deb.sury.org#2056]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

The current Nchan version (1.24.0-1+ubuntu22.04.1+deb.sury.org+1) is out of date and is missing several [critical fixes](https://github.com/slact/nchan/blob/master/changelog.txt#L1-L39), especially for the deployments utilizing Redis.

**Describe the solution you'd like**
Please update Nchan to version 1.3.6.

**Distribution (please complete the following information):**
 - OS: Ubuntu / any
 - Architecture: amd64
 - Repository: ppa:ondrej/nginx

**Package(s) (please complete the following information):**
```
libnginx-mod-nchan:
  Installed: 1.24.0-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.24.0-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1.24.0-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.18.0-6ubuntu14.4 500
```

**Comment by oerdnj** [comment]
This will be fixed as part of https://github.com/oerdnj/deb.sury.org/issues/2073
