### ISSUE TITLE
php8.x-xdebug causes segfault

### ISSUE THREAD

**Issue by kwisatz** [oerdnj/deb.sury.org#2059]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

We've been seeing segfaults with PHP8.2 and PHP8.3 since the release and subsequent installation of `php8.2-xdebug-3.3.0-1+0~20231205.55+debian11~1.gbp02cd78` yesterday, December 5th:

```bash
Dec 06 11:34:48 kobol kernel: php-fpm8.3[1449540]: segfault at 23e0000037f ip 000055d467a2d2fc sp 00007ffe5735dff0 error 4 in php-fpm8.3[55d467777000+318000]
Dec 06 11:34:48 kobol kernel: Code: 00 00 00 00 00 4d 8b b4 24 e8 01 00 00 4d 85 ff 0f 84 96 00 00 00 4c 8d 2d 95 a9 1f 00 90 4d 89 bc 24 e8 01 00 00 49 8b 57 18 <48> 8b 42 38 a8 01 74 12 48 8d 0d b5 53 1f 00 48 8b 89 e0 01 00 00
Dec 06 11:34:49 kobol kernel: php-fpm8.3[1449541]: segfault at 23e0000037f ip 000055d467a2d2fc sp 00007ffe5735dff0 error 4 in php-fpm8.3[55d467777000+318000]
Dec 06 11:34:49 kobol kernel: Code: 00 00 00 00 00 4d 8b b4 24 e8 01 00 00 4d 85 ff 0f 84 96 00 00 00 4c 8d 2d 95 a9 1f 00 90 4d 89 bc 24 e8 01 00 00 49 8b 57 18 <48> 8b 42 38 a8 01 74 12 48 8d 0d b5 53 1f 00 48 8b 89 e0 01 00 00
Dec 06 11:34:49 kobol kernel: php-fpm8.3[1449639]: segfault at 23e0000037f ip 000055d467a2d2fc sp 00007ffe5735dff0 error 4 in php-fpm8.3[55d467777000+318000]
Dec 06 11:34:49 kobol kernel: Code: 00 00 00 00 00 4d 8b b4 24 e8 01 00 00 4d 85 ff 0f 84 96 00 00 00 4c 8d 2d 95 a9 1f 00 90 4d 89 bc 24 e8 01 00 00 49 8b 57 18 <48> 8b 42 38 a8 01 74 12 48 8d 0d b5 53 1f 00 48 8b 89 e0 01 00 00
```

**To Reproduce**

1. Install php8.2-xdebug 
2. Invoke an unknown condition in a PHP application (unknown at this point).

**Your understanding of what is happening**
Something that came with the latest version of the xdebug extension is causing segfaults.

To confirm this was the cause, I have consulted my `apt` `history.log`:

```bash
Start-Date: 2023-12-05  17:05:28
Commandline: apt upgrade
Upgrade: php8.2-xdebug:amd64 (3.2.1++-1+0~20230831.54+debian11~1.gbpa4efb6, 3.3.0-1+0~20231205.55+debian11~1.gbp02cd78)
End-Date: 2023-12-05  17:05:29
```

Then cross-referenced it with the first occurrence of the segfault:

```bash
root@kobol:~# grep 'segfault' /var/log/syslog | head
Dec  5 17:05:57 kobol kernel: [4126064.210884] php-fpm8.2[819920]: segfault at 23e00000387 ip 00005595e5af7ffc sp 00007fff6c984e30 error 4 in php-fpm8.2[5595e5855000+306000]
Dec  5 17:06:21 kobol kernel: [4126088.252854] php-fpm8.2[819922]: segfault at 23e00000387 ip 00005595e5af7ffc sp 00007fff6c984e30 error 4 in php-fpm8.2[5595e5855000+306000]
[…]
```

Finally, uninstalled the `xdebug` extension and confirmed the segfaults were no longer happening.

**What steps did you take to resolve issue yourself before reporting it here**

Uninstalled the `xdebug` extension for both PHP8.2 and PHP8.3

**Distribution (please complete the following information):**
 - OS: Debian 11.8
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```bash
root@kobol:/run/php# apt-cache policy php8.2-xdebug
php8.2-xdebug:
  Installed: (none)
  Candidate: 3.3.0-1+0~20231205.55+debian11~1.gbp02cd78
  Version table:
     3.3.0-1+0~20231205.55+debian11~1.gbp02cd78 990
        990 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
Seen a [similar issue reported here](https://github.com/oerdnj/deb.sury.org/issues/2058) for PHP 8.1 xdebug on `armhf`, but `swoole` is not installed in this case.
I feel like this would probably best go upstream, but I do not know how to get more useful information from this than what I have found. I do not seem to have a coredump or wouldn't know where to find it if there is one.

**Comment by TuningYourCode** [comment]
We also experience segfaults. Currently we check if it's related to having xdebug and blackfire. Any chance that you also run other debugging extensions?

**Comment by oerdnj** [comment]
@derickr does this ring a bell or do you need reports directly to xdebug?

**Comment by kwisatz** [comment]
```
root@kobol:~# php8.2 -m
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
memcache
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
pspell
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by blankse** [comment]
@oerdnj There is a new version of xdebug 3.3.1 which should have a fix for this issue. Can you update the ppa?

**Comment by webmozart** [comment]
We would appreciate this too 🙏 Thank you for the great work!

**Comment by jeanmodesto** [comment]
@oerdnj There is a new version of xdebug 3.3.1 which should have a fix for this issue. Can you update the ppa?

**Comment by blankse** [comment]
xdebug 3.3.1 is available since 2024-01-21. See https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=xdebug&field.status_filter=published&field.series_filter=

**Comment by derickr** [comment]
And 3.3.2 will be today, with more fixes.

**Comment by oerdnj** [comment]
> And 3.3.2 will be today, with more fixes.

This hasn't happened yet :), but 3.3.1 has been packaged.

**Comment by derickr** [comment]
There is another crash bug that I haven't managed to fix.

**Comment by oerdnj** [comment]
> There is another crash bug that I haven't managed to fix.

I know the feeling. Hang in there!
