### ISSUE TITLE
[5.6]imagick

### ISSUE THREAD

**Issue by kovich** [oerdnj/deb.sury.org#206]
Cannot enable php imagick module

**Comment by oerdnj** [comment]
Cannot use the crystal ball, reopen the bug when you provide (any useful) details

**Comment by kovich** [comment]
apt-add-repository ppa:ondrej/php
apt-cache search imagick | grep php 

Package php5.6-imagick/php7.0-imagick is not found.

**Comment by oerdnj** [comment]
You should really learn how to write a bug reports.

I assume that you are using ppa:ondrej/php with php-imagick - 3.4.0~rc4-1+deb.sury.org~trusty+1. The package needed a rebuild to support php5.6, so php-imagick_3.4.0~rc4-1+deb.sury.org~trusty+2 should fix your issue.

**Comment by kovich** [comment]
// After apt-get update; apt-get install php-imagick

php5.6 -m 
//shows following
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/imagick.so' - /usr/lib/php/20131226/imagick.so: cannot open shared object file: No such file or directory in Unknown on line

// There is a imagick.so in /usr/lib/php/20151012
// By cp /usr/lib/php/20151012/imagick.so /usr/lib/php/20131226
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/imagick.so' - /usr/lib/php/20131226/imagick.so: undefined symbol: zend_fetch_resource2_ex in Unknown on line 0

**Comment by kovich** [comment]
?? Still not work with messages shown above.

**Comment by oerdnj** [comment]
Since you are unwilling to provide a proper information in the bug report and just pasting random snippets, so am I. The bug is fixed.

**Comment by kovich** [comment]
Anyway, thanks for your help.

Everything works after apt-get update/dist-upgrade.

// As a complement, attach the description of imagick module
imagick module version	3.4.0RC4
imagick classes	Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version	ImageMagick 6.8.9-9 Q16 x86_64 2015-08-06 http://www.imagemagick.org
Imagick using ImageMagick library version	ImageMagick 6.8.9-9 Q16 i686 2015-08-06 http://www.imagemagick.org
