### ISSUE TITLE
Please add phpx.x-xdebug zlib compression support

### ISSUE THREAD

**Issue by nickchomey** [oerdnj/deb.sury.org#2061]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
I would like to be able to gzip the cachegrind files that are generated by the Xdebug profiler. However, I get an error message saying that zlib hasn't been compiled into the xdebug build

![image](https://github.com/oerdnj/deb.sury.org/assets/88559987/e51e93ab-7565-42f7-b859-0284e48b4775)

**Describe the solution you'd like**
Please add zlib support, with the instructions here: https://xdebug.org/docs/errors#CFG-W-NOZLIB

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: I'm not sure

**Package(s) (please complete the following information):**
```
root@Ubuntu-2204-jammy-amd64-base /home/rplscom/webapps # apt policy php8.1-xdebug
php8.1-xdebug:
  Installed: 3.3.0-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 3.3.0-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 3.3.0-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.2+2.9.8+2.8.1+2.5.5-4 500
        500 http://mirror.hetzner.com/ubuntu/packages jammy/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Additional context**
I only checked php8.1, but I assume this problem exists for the rest of the versions.

**Comment by oerdnj** [comment]
Done
