### ISSUE TITLE
php-ds for PHP8.3 does not load (undefined symbol: fast_add_function)

### ISSUE THREAD

**Issue by aboks** [oerdnj/deb.sury.org#2063]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
When installing the `php8.3-ds` package on a PHP 8.3 system, the install works fine. However, when calling the `php` CLI binary, you get the error
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'ds.so' (tried: /usr/lib/php/20230831/ds.so (/usr/lib/php/20230831/ds.so: undefined symbol: fast_add_function), /usr/lib/php/20230831/ds.so.so (/usr/lib/php/20230831/ds.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**To Reproduce**
```
apt install php8.3 php8.3-ds
php -i
```

**Your understanding of what is happening**
It seems like the `fast_add_function` was removed from the PHP source (https://github.com/php/php-src/commit/3b06618813fe0979850eaa1f4bed426edb5b3123). The `php-ds` extension probably needs the patch from https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-ds.git/diff/0001-fast_add_function-removed-in-PHP-8.3-use-add_functio.patch?id=d1cbd173944bbba55b92de019b01760746a67f78 in order to be compatible with PHP 8.3.

**What steps did you take to resolve issue yourself before reporting it here**
Looking up why/when the `fast_add_function` was removed, and the patch as a possible fix. Unfortunately, it seems impossible to fix this without recompiling the extension with the patch.

**Expected behavior**
PHP runs without startup errors and displays `ds support => enabled`

**Distribution (please complete the following information):**
 - OS: Debian 11
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.3-ds:
  Installed: 1.4.0-5+0~20231125.28+debian11~1.gbp690767
  Candidate: 1.4.0-5+0~20231125.28+debian11~1.gbp690767
  Version table:
 *** 1.4.0-5+0~20231125.28+debian11~1.gbp690767 500
        500 http://HTTPS///packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
-

**Comment by samuelshenrique** [comment]
I had same problem. Did you manage to solve it?

**Comment by AlexanderGH** [comment]
This is now fixed in 1.5.0: https://github.com/php-ds/ext-ds/issues/199

Any chance we could get a new build up on deb.sury.org?

**Comment by oerdnj** [comment]
Updated to 1.5.0

**Comment by bruno-buiret** [comment]
Thank you!
