### ISSUE TITLE
Request to Upgrade Curl to >= 7.87.0 in Ubuntu 22.04 LTS due to Keep-Alive Connection Issue

### ISSUE THREAD

**Issue by lukasojd** [oerdnj/deb.sury.org#2068]
**Environment:**

    Ubuntu Version: 22.04 LTS
    PHP Version: 8.2.15
    Curl Version: 7.81.0

**Description:**
There's an issue with the current version of curl (7.81.0) included in the ppa:ondrej/php for Ubuntu 22.04 LTS, which significantly impacts the behavior of keep-alive connections in PHP applications.

**Issue Detail:**
When using curl to make HTTP requests, the keep-alive connections are not maintained if only the status code of the HTTP response is retrieved without accessing the content. This behavior forces applications to re-establish connections and perform new handshakes for subsequent requests, leading to a noticeable delay (approximately 30-80 ms per request). This issue is significantly impacting the performance, especially in scenarios involving high-frequency requests.

Notably, this issue has been addressed in curl version 7.87.0 and later. In these versions, keep-alive connections are appropriately maintained regardless of whether the response body is accessed or not.

**Request:**
I kindly request an upgrade of the curl library to version 7.87.0 or higher in the ppa:ondrej/php repository for Ubuntu 22.04 LTS. This upgrade will resolve the keep-alive connection issue and improve the performance of PHP applications that rely on curl for HTTP requests, especially those communicating frequently with services like AWS.

**Impact:**
This upgrade is crucial for PHP applications requiring fast and efficient network communication. The current version hinders performance and affects the overall efficiency of applications that depend on persistent HTTP connections.

Thank you for considering this upgrade to enhance the capabilities and performance of PHP on Ubuntu 22.04 LTS.

**Comment by lukasojd** [comment]
[[#https://github.com/async-aws/aws/pull/1655](https://github.com/async-aws/aws/pull/1655) ](https://github.com/async-aws/aws/pull/1655)

**Comment by oerdnj** [comment]
The PPA doesn't include curl, and it's not going to as this is outside of the scope for this PPA.

**Comment by lukasojd** [comment]
@oerdnj PPA include PHP 

> The PPA doesn't include curl, and it's not going to as this is outside of the scope for this PPA.

Thank you for your prompt response. I understand the constraints of the PPA's scope, but allow me to further clarify the specific issue regarding the curl integration within PHP, as it might be a point of misunderstanding.

When PHP is compiled and built, it can be configured to include the curl extension. This process involves linking the PHP-curl extension to a specific version of the libcurl library available at the time of compilation. The critical point here is that once PHP is compiled with a particular version of libcurl, this version becomes an intrinsic part of the PHP binary. In the case of the PHP package provided in your PPA, it currently includes libcurl version 7.81.0.

The challenge arises from the fact that this embedded version of libcurl within PHP cannot be upgraded or altered externally once PHP is compiled. This means, as long as the PHP package in your PPA uses an older version of libcurl (7.81.0), users of this package have no means to upgrade or change this specific component of PHP to address the keep-alive connection issue. The only way to upgrade libcurl within the PHP environment is through recompiling PHP with a newer version of the libcurl library.

Hence, my request to consider upgrading the version of libcurl used in the PHP compilation process for your PPA. Upgrading to a version higher than 7.87.0 would resolve the current keep-alive connection issue inherent in the older version. This change would significantly enhance the functionality and performance of PHP applications relying on the curl extension, especially for those requiring efficient network communication.

I hope this further explanation clarifies the technical aspect of my request. I appreciate the work and maintenance that goes into managing this PPA, and I believe this upgrade would be beneficial for a wide range of PHP users.

Thank you for reconsidering this aspect of the PHP package in your PPA.

**Comment by oerdnj** [comment]
> The critical point here is that once PHP is compiled with a particular version of libcurl, this version becomes an intrinsic part of the PHP binary. In the case of the PHP package provided in your PPA, it currently includes libcurl version 7.81.0.

Please first understand how shared libraries work before stating nonsense like a facts with words like "critical point". There is no embedded libcurl.

Also, let me reiterate once more:

> this is outside of the scope for this PPA
