### ISSUE TITLE
[PHP-5.6] Add php5-dbg

### ISSUE THREAD

**Issue by rufinus** [oerdnj/deb.sury.org#207]
Please add the php5-dbg package. (xdebug is so damn slow with code-coverage)

( 42 minutes 44 seconds php5.6 with xdebug and coverage vs. 3 minutes 13 seconds php7 with php-phpdbg and coverage)

**Comment by oerdnj** [comment]
Do you mean phpX.Y-phpdbg?

**Comment by rufinus** [comment]
yes. sorry for misleading.

afaik its included in core source since php5.6

**Comment by rufinus** [comment]
sorry its already included... got mislead by using the wrong name.
