### ISSUE TITLE
PHP 5.6 compile error

### ISSUE THREAD

**Issue by azurit** [oerdnj/deb.sury.org#2072]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

While trying to compile PHP version 5.6 from sources downloaded from packages.sury.org repository for Debian Bullseye, this error shows up and compilation stops:

```
/home/_nobackup/install/php-fpm/src/php5.6-5.6.40/ext/standard/info.c:912:2: error: too few arguments to function 'php_print_packaging_credits'
  912 |  php_print_packaging_credits(flag, 1);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/_nobackup/install/php-fpm/src/php5.6-5.6.40/ext/standard/info.c:29:
/home/_nobackup/install/php-fpm/src/php5.6-5.6.40/ext/standard/credits.h:42:13: note: declared here
   42 | PHPAPI void php_print_packaging_credits(int flag, int top TSRMLS_DC);

```

I am able to compile all other versions without any problems.

**To Reproduce**

I'm compiling it using these commands:
```
apt-get source php5.6
DEB_BUILD_OPTIONS=nocheck debuild -b -us -uc

```

**Your understanding of what is happening**
I'm not C coder but, after comparing it with other PHP versions (which are compiling fine), it looks like some kind of arguments type mismatch.

**What steps did you take to resolve issue yourself before reporting it here**
I was trying to modify type of a `flag` argument but without success.

**Expected behavior**
It should compile.

**Distribution (please complete the following information):**
 - OS: Debian Bullseye
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
# apt-cache policy php5.6
php5.6:
  Installed: 5.6.40-68+0~20230902.80+debian11~1.gbpa2012b
  Candidate: 5.6.40-68+0~20230902.80+debian11~1.gbpa2012b
  Version table:
 *** 5.6.40-68+0~20230902.80+debian11~1.gbpa2012b 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
        100 /var/lib/dpkg/status

```
**Additional context**
None.

**Comment by oerdnj** [comment]
> `apt-get source php5.6`
> `DEB_BUILD_OPTIONS=nocheck debuild -b -us -uc`

So, what are the things you are **not** telling me?  Why do you even ask for help if you wilfully withhold important information?

> It should compile.

It does compile.
