### ISSUE TITLE
`php-maxminddb` not available on `arm64` platform

### ISSUE THREAD

**Issue by BusterNeece** [oerdnj/deb.sury.org#2077]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

If I update my build process to use PHP 8.3, the build completes without issue on AMD64 platforms, but fails on ARM64 because `php-maxminddb` is missing, but only specifically for that platform, not for AMD64. I'm not sure if this is a misconfiguration of the build process or if they're no longer making that library available for ARM64.

**Comment by oerdnj** [comment]
There's a whole lot of information missing that was stripped from the template. I don't have a crystal ball, so I am just going to close this.

**Comment by BusterNeece** [comment]
@oerdnj Wait...I sincerely felt it was okay to be concise with my bug report here.

The issue is honestly very simple: I'm not seeing a `php-maxminddb` package for PHP 8.3 on the ARM64 platform.

Any additional information I could provide would just be padding to that fact. That's the core problem and I described it above.

**Comment by oerdnj** [comment]
Well from you bug report, I can as easily guess that you are using Windows, and thus it is not relevant here...

**Comment by oerdnj** [comment]
Those questions are there for a good reason...

**Comment by BusterNeece** [comment]
@oerdnj My apologies for missing those details. I was trying to respect your time by being as concise as possible, given several of the questions on the template weren't relevant to this issue.

In particular, I'm referring to Ubuntu 22.04 LTS using the Ubuntu PPA.

**Comment by oerdnj** [comment]
> I was trying to respect your time

And yet, this look much longer. Don't guess, as I said those questions are there for a reason.

The logs no longer say why it failed to build, so I've restarted it: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/27022216

Let's see what happens.

**Comment by BusterNeece** [comment]
> And yet, this look much longer. Don't guess, as I said those questions are there for a reason.

With all due respect, my understanding was that this repository was solely for issues with the PPA, so the presumption that I was using Windows is one I didn't expect you to have.

Yes, I missed a few details, but of what benefit would "expected result" and "steps you took to reproduce" have been in this case? I would've just been writing an essay with padding that would've wasted both of our time.

I suspect it would've been just as easy to ask me the specific missing piece of information (which version of Ubuntu I was using) and you wouldn't have, in the process, made me incredibly unlikely to ever report another issue here again.

**Comment by oerdnj** [comment]
So, let me get this straight - you wanted me to spend time looking up the missing information or asking you for the missing information because you wanted to save yourself a little bit of work and time.

> made me incredibly unlikely to ever report another issue here again.

Thank you, this is appreciated.
