### ISSUE TITLE
php-ds 1.5.0 for php8.3/arm64 is missing

### ISSUE THREAD

**Issue by nanaya** [oerdnj/deb.sury.org#2081]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
php-ds 1.4.0 is broken on php 8.3 so 1.5.0 is required for it to work at all but the package is missing for the specified platform.

**To Reproduce**
1. Go to https://packages.sury.org/php/pool/main/p/php-ds/
2. Try to locate `php8.3-ds_1.5.0-*_arm64.deb`
4. It doesn't exist

**Your understanding of what is happening**
Build failure?

**What steps did you take to resolve issue yourself before reporting it here**
Wait a few days after the package was [claimed to be built](https://github.com/oerdnj/deb.sury.org/issues/2063#issuecomment-1942024801)

**Expected behavior**
Package exist

**Distribution (please complete the following information):**
 - OS: debian 11, debian 12
 - Architecture: arm64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
N/A

**Additional context**
Note that all other variations for arm64 also stuck at 1.4.0 but it's less of a problem on php other than 8.3.

**Comment by oerdnj** [comment]
Should be fine now.
