### ISSUE TITLE
Segmentation fault executing curl_init() with php8.3-swoole on Debian packages

### ISSUE THREAD

**Issue by MrMeshok** [oerdnj/deb.sury.org#2082]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
I got error "Segmentation fault (core dumped)" when running composer commands on Debian 12 VM. After disabling swoole extension error disappeared. After that i tried to reproduce it in docker on Debian 12 and Ubuntu 22.04. Error happens only on packages from packages.sury.org, Ubuntu PPA not affected. I even try to use packages.sury.org on Ubuntu(pretending to be bookworm)

I did some digging through composer source code and found out error happens when using curl_init. And it's happening only on php8.3, php8.2 work as expected

**To Reproduce**
Run this commands on clean Debian 12:
1. apt-get update
2. apt-get install -y curl
3. curl -sSL https://packages.sury.org/php/README.txt | bash -x
4. apt install -y php8.3-swoole
5. php -r 'curl_init();'

OR through docker
```console
docker run --rm -it debian:12 /bin/sh -c "apt-get update && apt-get install -y curl && curl -sSL https://packages.sury.org/php/README.txt | bash -x && apt install -y php8.3-swoole && php -r 'curl_init();'"
```

**What steps did you take to resolve issue yourself before reporting it here**
Tried different distributions and packages

**Expected behavior**
php -r 'curl_init();' executes without error

**Distribution:**
 - OS: Debian 12 and Ubuntu 22.04
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
It's missing the upload to the PECL.

**Comment by MrMeshok** [comment]
Ubuntu PPA has the same 5.1.1-1 version, but no issue there

**Comment by oerdnj** [comment]
Still nothing, see the upstream issue: https://github.com/swoole/swoole-src/issues/5242

**Comment by nanaya** [comment]
as an alternative maybe disable curl option for now?

**Comment by webard** [comment]
Hello, Swoole 5.1.2 was released in PECL today: https://pecl.php.net/package-changelog.php?amp=&package=swoole&release=4.5.5 @oerdnj can you trigger build extension in your repository?

**Comment by MrMeshok** [comment]
Everything works now. Thanks everyone!
