### ISSUE TITLE
Ubuntu nginx-extras - new dependency

### ISSUE THREAD

**Issue by ohdearaugustin** [oerdnj/deb.sury.org#2085]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
The new update from the nginx-extras package has a breaking change of the dependencies for the libnginx-mod-http-lua. The new package nginx-extras=1.24.0-2+ubuntu22.04.1+deb.sury.org+3 will break the installation via update or a new install. As with the newer package lua-resty-core is needed for the plugin to work. 

**To Reproduce**
1. Add the nginx repo to fresh Ubuntu 22.04 server according to [ppa](https://launchpad.net/~ondrej/+archive/ubuntu/nginx)
2. Run `apt update`
3. Run `apt install nginx-extras`
4. Get error
    ```
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    libnginx-mod-http-lua : Depends: lua-resty-core (< 0.1.28.1~) but it is not installable
                         Depends: lua-resty-core (>= 0.1.28) but it is not installable
    E: Unable to correct problems, you have held broken packages
    ```

**Your understanding of what is happening**
A new dependency was introduced which cannot be fulfilled by the ppa or standard packages included in Ubuntu 22.04. Therefore an update or new install of the nginx-extras, more specifically the libnginx-mod-http-lua is not working anymore. (Dependency chain)

**What steps did you take to resolve issue yourself before reporting it here**
I looked up if there is a easy possibility to get the lua-resty-core package on Ubuntu 22.04. Unfortunately it is not packaged anywhere. I fear we need to migrate to openresty to get the lua functionality again in nginx.

**Expected behavior**
I did expect that the nginx-extras package is still working the same way as it did with the version 1.24.0-1+ubuntu22.04.1+deb.sury.org+2

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.
```
nginx-extras:
  Installed: 1.24.0-1+ubuntu22.04.1+deb.sury.org+2
  Candidate: 1.24.0-2+ubuntu22.04.1+deb.sury.org+3
  Version table:
     1.24.0-2+ubuntu22.04.1+deb.sury.org+3 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
 *** 1.24.0-1+ubuntu22.04.1+deb.sury.org+2 100
        100 /var/lib/dpkg/status
     1.18.0-6ubuntu14.4 500
        500 https://mirror.hetzner.com/ubuntu/packages jammy-updates/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
     1.18.0-6ubuntu14.3 500
        500 https://mirror.hetzner.com/ubuntu/security jammy-security/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
     1.18.0-6ubuntu14 500
        500 https://mirror.hetzner.com/ubuntu/packages jammy/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
 ```

**Additional context**
This problem was introduced today, the install was working as expected until the release of the new package. I didn't test it on other OS destributions. Maybe could also be a problem for other Ubuntu versions.

Edit: Probably related to #2073

**Comment by CxDevLead** [comment]
Also occurring on Ubuntu 20.04

**Comment by JimmyBanks** [comment]
I am having the same issue on 20.04

**Comment by oerdnj** [comment]
See #2073 for details what had to be done for the packages to continue working.

**Comment by kilburn** [comment]
@oerdnj the issue is that these packages are now uninstallable in jammy. If this had to be done to support newer debian/ubuntu releases maybe the changes should only be done for those but not for `jammy`?

**Comment by oerdnj** [comment]
> If this had to be done to support newer debian/ubuntu releases maybe the changes should only be done for those but not for jammy?

That's unsustainable. Everything needs to be unified.

> Otherwise, what would you suggest that we do to be able to use these packages under jammy?

Just wait a little bit - `lua-resty-core` is building right now and should be available.

Alternatively, for people that don't need `libnginx-mod-http-lua`, they can just install the modules they need instead of `nginx-extra`.

**Comment by kilburn** [comment]
Everything is now working again (including our tests passing with the new versions). Thanks @oerdnj !

**Comment by ohdearaugustin** [comment]
Thank you everything is working again.

@oerdnj You are awesome, thank you for all your great work and the really fast fix.

**Comment by massej** [comment]
I try to install nginx-extra on Ubuntu 24.04 (nobel) but i can't install nginx-extra

13.99 Reading state information...
14.53 Some packages could not be installed. This may mean that you have
14.53 requested an impossible situation or if you are using the unstable
14.53 distribution that some required packages have not yet been created
14.53 or been moved out of Incoming.
14.53 The following information may help to resolve the situation:
14.53
14.53 The following packages have unmet dependencies:
15.01  libnginx-mod-http-lua : Depends: libluajit-5.1-2 (>= 2.1-20220411) but it is not installable or
15.01                                   libluajit-5.1-2 (>= 2.1.0~beta3) but it is not installable
15.02 E: Unable to correct problems, you have held broken packages.

It there a way to install 2.1-20220411 or 2.1.0~beta3 on 24.04?

In the Ubuntu 24.04 it's using libluajit-5.1-2 (2.1.0+git20231223.c525bcb+dfsg-1)

**Comment by oerdnj** [comment]
> It's again not working in Ubuntu 24.04
> 
> `ubuntu@ip-10-7-0-23:~$ sudo apt-get install nginx-extras -y` `Reading package lists... Done` `Building dependency tree... Done` `Reading state information... Done` `Some packages could not be installed. This may mean that you have` `requested an impossible situation or if you are using the unstable` `distribution that some required packages have not yet been created` `or been moved out of Incoming.` `The following information may help to resolve the situation:`
> 
> `The following packages have unmet dependencies:` ` libnginx-mod-http-lua : Depends: libluajit-5.1-2 (>= 2.1.0) but it is not installable or` ` libluajit-5.1-2 (>= 2.1.0+openresty) but it is not installable` `E: Unable to correct problems, you have held broken packages.`

Don't canibalize old closed issues. Open a new issue, especially when the problem is different.

**Comment by massej** [comment]
I just openned @https://github.com/oerdnj/deb.sury.org/issues/2175
