### ISSUE TITLE
nginx-mainline jammy broken upgrade

### ISSUE THREAD

**Issue by walmartshopper** [oerdnj/deb.sury.org#2086]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Trying to upgrade to today's build (1.25.4-2+ubuntu22.04.1+deb.sury.org+1) resulted in a broken nginx install.  Before the upgrade, I had nginx-light, nginx-common, and libnginx-mod-brotli 1.25.4-1 installed.  Doing "apt dist-upgrade" removed libnginx-mod-brotli and installed nginx, and nginx failed to restart because mod-brotli was missing.

**To Reproduce**
1. Install nginx-common, nginx-light, and libnginx-mod-brotli 1.25.4-1
2. Run "apt dist-upgrade" 

**Your understanding of what is happening**
current build seems to be missing libnginx-mod-brotli, and it wants to replace nginx-light with nginx

**What steps did you take to resolve issue yourself before reporting it here**
Downgraded to previous build

**Expected behavior**
Clean upgrade and nginx restart

**Distribution (please complete the following information):**
 - OS: Ubuntu jammy
 - Architecture: arm64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

nginx-light:
  Installed: 1.25.4-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1
  Version table:
     1.25.4-2+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu jammy/main arm64 Packages
 *** 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     1.18.0-6ubuntu14.4 500
        500 http://us-west-2.ec2.ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages
     1.18.0-6ubuntu14.3 500
        500 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages
     1.18.0-6ubuntu14 500
        500 http://us-west-2.ec2.ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages

nginx-common:
  Installed: 1.25.4-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1
  Version table:
     1.25.4-2+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu jammy/main arm64 Packages
 *** 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu jammy/main arm64 Packages
        100 /var/lib/dpkg/status
     1.18.0-6ubuntu14.4 500
        500 http://us-west-2.ec2.ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages
     1.18.0-6ubuntu14.3 500
        500 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages
     1.18.0-6ubuntu14 500
        500 http://us-west-2.ec2.ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages

libnginx-mod-brotli:
  Installed: 1.25.4-1+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1.25.4-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu jammy/main arm64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
The replacement is correct, see #2073 for details what had to be done.

The missing brotli module will be added as soon as I chew through the rest.

**Comment by oerdnj** [comment]
The `libnginx-mod-brotli` has been replaced with:

```
Package: libnginx-mod-http-brotli-filter
Architecture: any
Multi-Arch: foreign
Depends: ${misc:Depends},
         ${shlibs:Depends},
Description: Brotli lossless compression support for Nginx - filter
 Brotli is a generic-purpose lossless compression algorithm that compresses
 data using a combination of a modern variant of the LZ77 algorithm, Huffman
 coding and 2nd order context modeling, with a compression ratio comparable
 to the best currently available general-purpose compression methods. It is
 similar in speed with deflate but offers more dense compression.
 .
 ngx_brotli filter module - used to compress responses on-the-fly

Package: libnginx-mod-http-brotli-static
Architecture: any
Multi-Arch: foreign
Depends: ${misc:Depends},
         ${shlibs:Depends},
Description: Brotli lossless compression support for Nginx - static
 Brotli is a generic-purpose lossless compression algorithm that compresses
 data using a combination of a modern variant of the LZ77 algorithm, Huffman
 coding and 2nd order context modeling, with a compression ratio comparable
 to the best currently available general-purpose compression methods. It is
 similar in speed with deflate but offers more dense compression.
 .
 ngx_brotli static module - used to serve pre-compressed files
```

This matches the newer packaging by Debian nginx-team.

**Comment by phildawson-gravity** [comment]
Just experienced the issue brotli today affecting both Jammy and Focal Fossa whilst running the usual 

`apt-get update && apt-get dist-upgrade -y
`
results in nginx panic with the missing enabled brotli module and followed by lots of dpkg error processing the other packages.

`[emerg] 730571#730571: open() "/etc/nginx/modules-enabled/50-mod-brotli.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf`

A quick

`mv /etc/nginx/modules-enabled/50-mod-brotli.conf /etc/nginx/modules-enabled/50-mod-brotli.conf.removed
`
and re-run then sorts it
