### ISSUE TITLE
packages.sury.org/*/nginx-extras_1.24.0.deb gives 404 not found 

### ISSUE THREAD

**Issue by juanr-yes** [oerdnj/deb.sury.org#2088]
**Frequently asked questions**

- [✅] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [✅] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [✅] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Packages.sury.org is returning a 404 error on some of the directories

To Reproduce
Browse to https://packages.sury.org/nginx/pool/main/n/nginx/nginx-extras_1.24.0-1%2b0~20230615.28%2bdebian11~1.gbpd7c5fc_amd64.deb

Your understanding of what is happening
Content is not there or server misconfiguration.

What steps did you take to resolve issue yourself before reporting it here
Test from different machines

Expected behavior
To get the requested content.

Distribution (please complete the following information):
n/a

Package(s) (please complete the following information):
n/a

Additional context
n/a

**Comment by oerdnj** [comment]
Yes, that's correct. The package is no longer there and was replaced with newer version.
