### ISSUE TITLE
PHP 8.3 shows full package version in phpversion()

### ISSUE THREAD

**Issue by marlonanjos** [oerdnj/deb.sury.org#2090]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
phpversion() and php -v are returning the complete package version instead of only the php version:

```
# /usr/bin/php8.3 -v
PHP 8.3.3-1+ubuntu22.04.1+deb.sury.org+1
root@marlon-dev:~# /usr/bin/php8.3 -r 'echo(phpversion()."\n");'
8.3.3-1+ubuntu22.04.1+deb.sury.org+1
```

It worked fine until version 8.2:
```
root@marlon-dev:~# /usr/bin/php8.2 -r 'echo(phpversion()."\n");'
8.2.15
```
Instead of returning only the current version (8.3.3)

**To Reproduce**
1. Run:
`/usr/bin/php8.3 -v`
2. Compare the version with 8.2
`/usr/bin/php8.2 -v`

**Your understanding of what is happening**
I understand that it could be used, but keeping only the PHP version number is more concise.

**Expected behavior**
phpversion() ideally should return only the PHP version

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
php8.3:
  Installed: (none)
  Candidate: 8.3.3-1+ubuntu22.04.1+deb.sury.org+1
  Version table:
     8.3.3-1+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main amd64 Packages
```

TYIA

**Comment by oerdnj** [comment]
Yes, that’s intentional.

**Comment by oerdnj** [comment]
It was requested in Debian.  But as I think about this, I don't really see a value in that, so I am probably drop that patch.

**Comment by oerdnj** [comment]
The packages now don't include the full version.

**Comment by marlonanjos** [comment]
Thank you @oerdnj :+1:
