### ISSUE TITLE
E: Unable to locate package nginx-brotli

### ISSUE THREAD

**Issue by CxDevLead** [oerdnj/deb.sury.org#2094]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
When installing `nginx-brotli` on Ubuntu 22.04, I receive the error `E: Unable to locate package nginx-brotli`

This issue only started occurring in the previous two weeks.

**To Reproduce**
1. Add the repository: `sudo add-apt-repository ppa:ondrej/nginx-mainline -y`
2. Install nginx, extras, and brotli:
```
sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
sudo apt-get -y install nginx-brotli
```
4. Error is output: `E: Unable to locate package nginx-brotli`

**Your understanding of what is happening**
`install nginx-brotli` previously was found in the repository, it is no longer found

**What steps did you take to resolve issue yourself before reporting it here**
Attempted to adjust the installation order, and ensured that the repository was being set

**Expected behavior**
The brotli extension is installed

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: ondrej/nginx-mainline

**Package(s) (please complete the following information):**

**Additional context**

**Comment by oerdnj** [comment]
I don't think there was ever `nginx-brotli` brotli package, the package was always called `libnginx-mod-brotli` which should be ok in couple minutes.

**Comment by feroda** [comment]
Today you have to install

`libnginx-mod-http-brotli-filter` - Brotli lossless compression support for Nginx - filter
`libnginx-mod-http-brotli-static` - Brotli lossless compression support for Nginx - static

**Comment by TTWShell** [comment]
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

```shell
sudo add-apt-repository ppa:ondrej/nginx-mainline -y
sudo apt-get update
sudo apt install libnginx-mod-brotli
```
then run `ls -al /etc/nginx/modules-enabled/*`

```text
lrwxrwxrwx 1 root root 62 Dec 23 06:51 /etc/nginx/modules-enabled/50-mod-http-brotli-filter.conf -> /usr/share/nginx/modules-available/mod-http-brotli-filter.conf
lrwxrwxrwx 1 root root 62 Dec 23 06:51 /etc/nginx/modules-enabled/50-mod-http-brotli-static.conf -> /usr/share/nginx/modules-available/mod-http-brotli-static.conf
```
restart the nginx:

```shell
sudo nginx -t
sudo systemctl restart nginx
```

**Comment by Jire** [comment]
> Today you have to install
> 
> `libnginx-mod-http-brotli-filter` - Brotli lossless compression support for Nginx - filter `libnginx-mod-http-brotli-static` - Brotli lossless compression support for Nginx - static

Works great, thanks!
