### ISSUE TITLE
Nginx Lua error with 1.24.0-2+ubuntu22.04.1+deb.sury.org+3

### ISSUE THREAD

**Issue by tubby1981** [oerdnj/deb.sury.org#2096]
**Describe the bug**
2024/03/15 11:32:31 [error] 1082347#1082347: *235191 lua entry thread aborted: runtime error: /usr/share/lua/5.1/resty/core/request.lua:131: no request found
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/share/lua/5.1/resty/core/request.lua:131: in function 'get_headers'
        /etc/nginx/conf.d/prd_request_logger.lua:55: in function 'process_chunked_body'
        /etc/nginx/conf.d/prd_request_logger.lua:111: in function </etc/nginx/conf.d/prd_request_logger.lua:1>

**Your understanding of what is happening**
I have the issue above since the last update to 1.24.0-2+ubuntu22.04.1+deb.sury.org+3
I'm using the libnginx-mod-http-lua (1:0.10.26+1.24.0-2+ubuntu22.04.1+deb.sury.org+4)

**What steps did you take to resolve issue yourself before reporting it here**
it seems that ngx.req.get_headers and other variables are no longer understood

**Expected behavior**
How can we fix this?

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: deb http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy main

**Package(s) (please complete the following information):**
apt-cache policy nginx
nginx:
  Installed: 1.24.0-2+ubuntu22.04.1+deb.sury.org+3
  Candidate: 1.24.0-2+ubuntu22.04.1+deb.sury.org+3
  Version table:
 *** 1.24.0-2+ubuntu22.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.24.0-1+ubuntu22.04.1+deb.sury.org+2 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
     1.18.0-6ubuntu14.4 500
        500 http://nl.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
     1.18.0-6ubuntu14.3 500
        500 http://nl.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages
     1.18.0-6ubuntu14 500
        500 http://nl.archive.ubuntu.com/ubuntu jammy/main amd64 Packages

**Additional context**

**Comment by tubby1981** [comment]
Everything works again after doing a rollback to the older version by installing the necessary deb packages found in /var/cache/apt/archives

It was a hell of a job getting the older version installed

**Comment by oerdnj** [comment]
The +5 version now depends only on the openresty version of the luajit, this should resolve the issue.
