### ISSUE TITLE
Add OpenTelemetry extension

### ISSUE THREAD

**Issue by CSalih** [oerdnj/deb.sury.org#2100]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
For some businesses observability is a crucial business requirement (reliability, performance, security, ...). OpenTelemetry provides a standardized framework and tools for creating, managing, and exporting telemetry data like traces, metrics, and logs. It allows users to easily instrument their applications regardless of language, infrastructure, or runtime environment, enabling them to understand the internal state of a system and making it easier to optimize performance and troubleshoot issues.

OpenTelemetry's [Automatic Instrumentation](https://opentelemetry.io/docs/languages/php/automatic/) requires the [OpenTelemetry extension](https://github.com/open-telemetry/opentelemetry-php-instrumentation). Adding the extension to ondrej/php would make the installation process much easier. 

**Describe the solution you'd like**
Add OpenTelemetry extension to this PPA.

**Describe alternatives you've considered**
The alternative installation method is to build the extension from source, pecl or pickle.

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by danilobuerger** [comment]
@oerdnj Any chance to get this in?

**Comment by cevin** [comment]
Debian /  Ubuntu PPA also need.

**Comment by xvilo** [comment]
I'm not sure if we can, but @oerdnj, is there anyway we can help with adding this? Or is everything managed on your side, without the capability of us adding a PR somewhere?

**Comment by oerdnj** [comment]
But looking locally, I’ve already done most of that, so I just need to check why I haven’t uploaded it yet. Perhaps disturbance in the force interrupted me before ai finished the work.

**Comment by oerdnj** [comment]
Ok, I just got confused. The packages are actually available from the repositories.  The was a build failure on Debian bookworm though, I will investigate that, but I am closing the issue now.

**Comment by xvilo** [comment]
Wonderful, thanks for the quick response @oerdnj

```
$ sudo apt search php8.3-opentelemetry
Sorting... Done
Full Text Search... Done
php8.3-opentelemetry/noble 1.0.3-1+ubuntu24.04.1+deb.sury.org+1 amd64
  OpenTelemetry auto-instrumentation support extension for PHP
```

<3
