### ISSUE TITLE
Excessive UNRELEASED Snapshot builds showing up every day since the 8.2.17 release

### ISSUE THREAD

**Issue by retry-the-user** [oerdnj/deb.sury.org#2101]
- [X ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X ] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Everyday since the php8.2.17 update on March 16th, I'm getting prompted to install what the Debian php changelog calls "Unrleased Snapshots". 

(8.2.17-1+0~20240317.42+debian12~1.gbpc3bdbd)  bookworm [amd64]
(8.2.17-1+0~20240318.45+debian12~1.gbpc3bdbd) bookworm [amd64]

And now it wants to install a March 20 build:
(8.2.17-1+0~20240320.48+debian12~1.gbpc3bdbd bookworm [amd64])

/usr/share/doc/php8.2-common/changelog. Debian.gz shows the Mar 18th build but not the 17th, and now I'm being prompted to install the Mar 20th build.  That's 4 new builds in 5 days. 

  ** SNAPSHOT build @c3bdbd35be595a7f1df060ed9ca3554f910cc1da **
  * UNRELEASED
 -- Ondřej Surý <ondrej@sury.org>  Mon, 18 Mar 2024 13:01:14 +0100

This is Debian GNU/Linux 12 (bookworm) amd64 
 - Repository: packages.sury.org

Policy shows the March 20th candidate
# apt-cache policy php8.2
php8.2:
  Installed: (none)
  Candidate: 8.2.17-1+0~20240320.48+debian12~1.gbpc3bdbd
  Version table:
     8.2.17-1+0~20240320.48+debian12~1.gbpc3bdbd 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
     8.2.7-1~deb12u1 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages
        500 https://deb.debian.org/debian-security bookworm-security/main amd64 Packages

**Additional context**
I've gotten occasional "Snapshot" builds before, but never 3 days in a row.  

I installed the latest on one of my servers and the Debian changelog for php now shows:

php8.2 (8.2.17-1+0~20240320.48+debian12~1.gbpc3bdbd) unstable; urgency=medium

  ** SNAPSHOT build @c3bdbd35be595a7f1df060ed9ca3554f910cc1da **
  * UNRELEASED
 -- Ondřej Surý <ondrej@sury.org>  Wed, 20 Mar 2024 13:05:21 +0100

So the other "unreleased" snapshot builds are not in the changelog, only the newest one. 

If these UNRELEASED builds are not actually version upgrades or bug fixes, is there a way they can not show up in the main channel for the repository?

**Comment by oerdnj** [comment]
> If these UNRELEASED builds are not actually version upgrades or bug fixes, is there a way they can not show up in the main channel for the repository?

No, not until the build system is switched to something little bit smarter (probably debusine) than jenkins-debian-glue.

There was a chroot failure and with jenkins-debian-glue, and it's impossible to trigger just the broken builds, so I have to reissue the whole set of the packages.

On top of that there was also something wrong with the guest - if it became too overloaded, it just disabled itself 🤷, and jenkins is also lovely - if you restart it, it will just forget all the scheduled and interrupted jobs.

It's the current limitation of the system used, and I intend to improve on that.

There should be one last build today and it should be stable again. I found the underlying issue today.

**Comment by retry-the-user** [comment]
> There should be one last build today and it should be stable again. I found the underlying issue today.

Just got another one today :
Inst php8.2-cli [8.2.17-1+0~20240320.48+debian12~1.gbpc3bdbd] (8.2.17-1+0~20240322.50+debian12~1.gbpc3bdbd bookworm [amd64]) []

**Comment by oerdnj** [comment]
So, what do you expect? A written notice every time I need to rebuild the package?

The packages will be rebuild as I need them to be rebuilt.

**Comment by retry-the-user** [comment]
> So, what do you expect? A written notice every time I need to rebuild the package?

No the opposite, because that's what IS happening now.   I just want to know if what you wrote before about having found the issue and resolved all this is true or not.
