### ISSUE TITLE
Can't access PPA repositories

### ISSUE THREAD

**Issue by GabrielMilanez1** [oerdnj/deb.sury.org#2102]
Hello, how's going?

https://ppa.launchpadcontent.net/ondrej/php/ubuntu/

503 Service Unavailable when I try to open it

**Comment by oerdnj** [comment]
Yes

**Comment by etepeu** [comment]
I'm trying to download packages, but I get error 503. Will there be another repository to download the php 7.4 installers?

**Comment by oerdnj** [comment]
I am not the only one that can lookup the launchpad status, right?

https://ubuntu.social/@launchpadstatus/112128869030316721

**Comment by oerdnj** [comment]
Don't close it yet, at least I hope that people will not fill duplicate issues.

**Comment by GabrielMilanez1** [comment]
That's ok, thanks for help mate, appreciate it

**Comment by oerdnj** [comment]
https://ubuntu.social/@launchpadstatus/112129652880776690
