### ISSUE TITLE
arm64 php release lags amd64 release

### ISSUE THREAD

**Issue by satphil** [oerdnj/deb.sury.org#2104]
**Frequently asked questions**

- [Y] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [Y ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [Y ] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
It seems the repo has a version mismatch between amd64 (8.3.4) and arm64 (8.3.3)

**Your understanding of what is happening**
amd64:
```
# apt-cache policy php8.3-common
php8.3-common:
  Installed: 8.3.4-1+0~20240320.25+debian12~1.gbpa5171b
  Candidate: 8.3.4-1+0~20240320.25+debian12~1.gbpa5171b
  Version table:
 *** 8.3.4-1+0~20240320.25+debian12~1.gbpa5171b 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

# cat /etc/apt/sources.list.d/php.list
deb https://packages.sury.org/php/ bookworm main
```

arm64:
```
# apt-cache policy php8.3-common
php8.3-common:
  Installed: 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b
  Candidate: 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b
  Version table:
 *** 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status

# cat /etc/apt/sources.list.d/php.list
deb https://packages.sury.org/php/ bookworm main
```
**What steps did you take to resolve issue yourself before reporting it here**
on the repo, it seems both repos were updated 3 or 4 days ago

[](https://packages.sury.org/php/dists/bookworm/main/)
```
Index of /php/dists/bookworm/main/
../
binary-amd64/                                      22-Mar-2024 12:01                   -
binary-arm64/                                      23-Mar-2024 07:01   
``` 

**Expected behavior**
I was expecting them to be the same release by now.  It helps if our test systems can run  the same release as production.

**Distribution (please complete the following information):**
 - OS: debian 12
 - Architecture: amd64 **and** arm64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
see above

**Additional context**
I just seems to have happened with the 8.3.4 release, prior to that the releases seem to have been in step.
(By the way, I'm a big fan of your work, thanks very much for all you and your team have done for the php community. It is much appreciated. My apologies if I'm barking up the wrong tree in reporting this).

**Comment by Zenexer** [comment]
I think Jenkins is down at the moment, so that could be why: https://jenkins.rfc1925.org/

**Comment by codewithmartin** [comment]
Thank you. Waiting for php8.3-mcrypt

**Comment by oerdnj** [comment]
> Thank you. Waiting for php8.3-mcrypt

`php8.3-mcrypt` does not build from `src:php8.3`, so whatever you are missing it's not this issue.
