### ISSUE TITLE
Downgrade xdebug to version 3.2.2

### ISSUE THREAD

**Issue by catalindevops** [oerdnj/deb.sury.org#2106]
**Frequently asked questions**

- [x ] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
I installed the latest version for php8.0, php8.1, php8.2 and I have random crash for fpm manager. After investigation I discovered that the problem is related to xdebug version 3.3.0 and 3.3.1.
There are tickets opened for the problem: https://bugs.xdebug.org/view.php?id=2242

**Describe the solution you'd like**
Build a php version with xdebug 3.2.2 till the problem is solved.

**Describe alternatives you've considered**
For custom builds in docker with xdebug 3.2.2 , the issue is mitigated.

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php8.1-debug version 3.3.1-2+0~20240213.59+debian11~1.gbp6c3556
php8.2-debug version 3.3.1-2+0~20240213.59+debian11~1.gbp6c3556

**Comment by oerdnj** [comment]
No, report the crash to xdebug and I’ll upgrade the package when there’s new upstream version. You can always use PECL if you need random versions from the past.

**Comment by danilobuerger** [comment]
@oerdnj There is a new upstream version, see also https://github.com/oerdnj/deb.sury.org/issues/2116 . Is there anything I can do to get this upgraded?
