### ISSUE TITLE
Upgrade to Apache 2.4.59

### ISSUE THREAD

**Issue by derritter88** [oerdnj/deb.sury.org#2109]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Partially. Changelog mentions some security fixes.

**Describe the solution you'd like**
Please upgrade your repos to the newest Apache release

**Describe alternatives you've considered**
Backport them the current release

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **request** accurately (where the template below will help), I might be able to help you.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04 & 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
apache2:
  Installiert:           2.4.58-1+ubuntu22.04.1+deb.sury.org+1
  Installationskandidat: 2.4.58-1+ubuntu22.04.1+deb.sury.org+1
  Versionstabelle:
 *** 2.4.58-1+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/apache2/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.52-1ubuntu4.8 500
        500 http://at.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
     2.4.52-1ubuntu4.7 500
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
     2.4.52-1ubuntu4 500
        500 http://at.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

**Comment by oerdnj** [comment]
Packages are building and should be available shortly.

**Comment by derritter88** [comment]
Thanks!

**Comment by fretb** [comment]
Hi, it seems there is no Debian 11 package for this version. Debian 10 + 12 are available.

Is this intended?

Thanks!
