### ISSUE TITLE
[Request] Update Xdebug to 3.3.2

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#2116]
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

Xdebug 3.3 has had a series of problem crashes, some were resolved in 3.3.1, but there are still more in today's 3.3.2

https://github.com/xdebug/xdebug/releases/tag/3.3.2

**Describe the solution you'd like**

Please update Xdebug to 3.3.2

**Describe alternatives you've considered**

Thank you!

**Distribution (please complete the following information):**
 - OS: Debian (but all)
 - Architecture: all
 - Repository: All

**Package(s) (please complete the following information):**

```
$ apt-cache policy php8.2-xdebug
php8.2-xdebug:
  Installed: 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556
  Candidate: 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556
  Version table:
 *** 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556 100
        100 /var/lib/dpkg/status
```

**Additional context**

**Comment by danilobuerger** [comment]
@oerdnj any chance to get this updated? The old version is causing crashes which is fixed with this release:
> This is a bug fix release that addresses a crash bug when Xdebug and Blackfire are active, as well as a crash bug/100% CPU bug in threaded PHP environments (Apache, FrankenPHP).

**Comment by oerdnj** [comment]
It has been updated yesterday.

**Comment by rfay** [comment]
Thanks!

```
root@6dc5938ce3cf:/# apt-cache policy php8.3-xdebug
php8.3-xdebug:
  Installed: 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556
  Candidate: 3.3.2-1+0~20240420.60+debian12~1.gbp3869a8
  Version table:
     3.3.2-1+0~20240420.60+debian12~1.gbp3869a8 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
 *** 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556 100
        100 /var/lib/dpkg/status

root@6dc5938ce3cf:/# apt-cache policy php8.2-xdebug
php8.2-xdebug:
  Installed: 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556
  Candidate: 3.3.2-1+0~20240420.60+debian12~1.gbp3869a8
  Version table:
     3.3.2-1+0~20240420.60+debian12~1.gbp3869a8 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
 *** 3.3.1-2+0~20240213.59+debian12~1.gbp6c3556 100
        100 /var/lib/dpkg/status
     3.2.0+3.1.6+2.9.8+2.8.1+2.5.5-3 500
        500 http://deb.debian.org/debian bookworm/main arm64 Packages
```
