### ISSUE TITLE
ZTS enabled build

### ISSUE THREAD

**Issue by mikk150** [oerdnj/deb.sury.org#212]
Is it possible to add --enable-maintainer-zts to compiler so if we want we can install pthreads from pecl

**Comment by oerdnj** [comment]
Folks, if you want to shoot yourself in foot, the new packaging infrastructure I built for PHP 7.0 allows to build variants quite easily, so here's experimental, totally unsupported PPA with PHP 7.0 ZTS: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts

No external modules, no batteries, no support (patches accepted and welcomed).
