### ISSUE TITLE
unable to connect to packages.sury.org

### ISSUE THREAD

**Issue by insp1re1** [oerdnj/deb.sury.org#2125]
Cannot initiate the connection to packages.sury.org:443 (2400:52e0:1e03::886:1). - connect (101: Network is unreachable) Could not connect to packages.sury.org:443 (143.244.38.136), connection timed out

**Comment by oerdnj** [comment]
This is not really anything actionable. And not really a bug report. You’ve chosen to provide no details, so I am just closing this.

**Comment by insp1re1** [comment]
it simply wont connect.
