### ISSUE TITLE
Couldn't find any package by glob 'php7.4-imagick'

### ISSUE THREAD

**Issue by MichelFrade** [oerdnj/deb.sury.org#2126]
I'm trying to install php7.4-imagick on Ubuntu 24.04 and it's returning the following error message.

Couldn't find any package by glob 'php7.4-imagick'

**Comment by lifeforceinst** [comment]
I am still seeing this issue with 24.04 with php7.4-imagick

I have today performed
```
# apt-get clean
# apt-get update
# apt-get install php7.4-imagick
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php7.4-imagick
E: Couldn't find any package by glob 'php7.4-imagick'
E: Couldn't find any package by regex 'php7.4-imagick'
```

Is there something I am missing

**Comment by bashgeek** [comment]
Yes, PHP 7.4 is EOL for 1.5 years now.

**Comment by lifeforceinst** [comment]
While PHP 7.4 is EoL many systems such as WordPress still indicated that PHP 7.4 is the latest fully supported release (8.x is all marked as verious levels of partially supported or Beta).

Much of the rest of the PHP 7.4 library are present in your repository, just the imagick items are missing.

**Comment by oerdnj** [comment]
> While PHP 7.4 is EoL many systems such as WordPress still indicated that PHP 7.4 is the latest fully supported release (8.x is all marked as verious levels of partially supported or Beta).
> 
> Much of the rest of the PHP 7.4 library are present in your repository, just the imagick items are missing.

I’ve removed the “helpful” comment. You didn’t have to respond.

**Comment by oerdnj** [comment]
And yes, PHP 7.4 has in fact reached end-of-life, but the whole purpose of this repository is to provide patched PHP versions past their respective EOL dates.
