### ISSUE TITLE
Ubuntu 24.04 Status

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#2127]
Not officially supported yet. Things might be missing here and there. Don’t open issues for Ubuntu 24.04, I’ll just close them until I write here that the support is official.

**Comment by tlueder** [comment]
Hi @oerdnj, just so I can plan ahead and not to pressure you. Do you have a timeline for the 24.04 support?

And I only need to know if it is days, weeks or months away.

Thanks

**Comment by oerdnj** [comment]
Some extensions fail to build from the source: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=&field.status_filter=published&field.series_filter=noble

I need to take a closer look what's going on which means installing noble chroot and having some time to debug this.  I expect this to happen in a small number of weeks (like 1 or 2).  Shorter time if the weather starts to be bad again :D.

**Comment by tlueder** [comment]
In that case I'm rooting for rain, storm and clouds that block out the sun?!? :D

Best of luck.

**Comment by YelehaUwU** [comment]
![obrázok](https://github.com/oerdnj/deb.sury.org/assets/162886331/93e375c7-296e-45a1-8a4b-9fb47757c63d)
Trying to install php8.3-sqlite fails with an unmet dependency, probably related to Ubuntu 24, correct me if I'm wrong.

**Comment by tuyennn** [comment]
+ 1 Placeholder for the status of this

**Comment by oerdnj** [comment]
There are couple of extensions that don't build from the source: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?batch=300, but generally Ubuntu 24.04 should be supported now.
