### ISSUE TITLE
[Request] Update nginx to 1.26.0 on stable ppa:ondrej/nginx

### ISSUE THREAD

**Issue by SagePtr** [oerdnj/deb.sury.org#2129]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Request for update

**Describe the solution you'd like**
Update Nginx to 1.26.0

**Describe alternatives you've considered**
Alternative is `ppa:ondrej/nginx-mainline`, but the main branch has 1.26.0 as stable now.

**Comment by smknstd** [comment]
+1 thanx in advance
