### ISSUE TITLE
Add PHP's DIO Extension

### ISSUE THREAD

**Issue by ralphschindler** [oerdnj/deb.sury.org#2130]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**

A problem exists in PHP docker environments, primarily where applications would like to write to process id 1's stdout (for normal docker logging). This is not directly possible through PHP's filesystem function due to protections that are in place. In this scenario, current advice is to use the DIO extension. https://github.com/php/php-src/issues/9551

**Describe the solution you'd like**

Please include PHP's DIO extension in the repository:
https://pecl.php.net/package/dio

**Describe alternatives you've considered**

n/a

**Distribution (please complete the following information):**
 - OS: debian/ubuntu
 - Architecture: all
 - Repository: n/a

**Package(s) (please complete the following information):**

n/a

**Additional context**

n/a

Thank you for the consideration!
-ralph

**Comment by oerdnj** [comment]
Done (it's in the build queue, so give it a tad bit time to finish)
