### ISSUE TITLE
Apache 2.4.59 missing for Debian 11 (bullseye, oldstable)

### ISSUE THREAD

**Issue by fretb** [oerdnj/deb.sury.org#2134]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
Apache 2.4.59 contains a patch that mitigates the http/2 continuation flood vulnerabilities. The package is built and available for both Debian 10 and 12 (https://packages.sury.org/apache2/pool/main/a/apache2/), but not for Debian 11.

Is this intended?

Thank you for your efforts!

**Comment by oerdnj** [comment]
Hmm, I don't know what went wrong because the packages were built without any problems, but then they didn't get installed into the repository. I've issued the rebuild just now.

**Comment by fretb** [comment]
Thank you for your hard work!

**Comment by fretb** [comment]
@oerdnj any ETA on the release on the repository? Not meaning to put pressure, but on the repository it's still the same situation unfortunately, so their might still be an issue?

**Comment by oerdnj** [comment]
It should not take so long.  I'll check what's going on.

**Comment by oerdnj** [comment]
Found it - it was copy&paste error in the repository configuration files - I’ve wrote a script to generate the configurations instead, and the new packages are building now.

**Comment by fretb** [comment]
Hi @oerdnj,

The package is indeed present now, thank you for that.

There is, however, another slight problem now I think. The package has a dependency that's not present for debian 11 as well:

```# apt-cache show apache2-bin
Package: apache2-bin
Priority: optional
Section: httpd
Installed-Size: 5157
Maintainer: Debian Apache Maintainers <debian-apache@lists.debian.org>
Architecture: amd64
Source: apache2
Version: 2.4.59-2+0~20240625.3+debian11~1.gbp9f0e8b
Provides: apache2-api-20120211, apache2-api-20120211-openssl1.1
Depends: debsuryorg-archive-keyring
```

But the debsuryorg-archive-keyring is only present for deb10 and deb12: https://packages.sury.org/apache2/pool/main/d/debsuryorg-archive-keyring/.

**Comment by fretb** [comment]
Just letting you know, I saw the package is available now, thanks a lot!
