### ISSUE TITLE
Unable to connect to packages.sury.org from my Debian VPS while connection from home isp works fine

### ISSUE THREAD

**Issue by juozaspo** [oerdnj/deb.sury.org#2137]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
I'm unable to connect to Debian packages repository server from my Debian VPS (IP: 80.209.228.178), while connecting from my home ISP (IP: 78.63.212.187) works fine. Other sites such as main site works, only Debian package repository is broken. Happens since this morning.

**To Reproduce**
1. Try to connect from any affected network, not sure if any exists, Fail to do so
2. Try to connect from any other unaffected isp, se it succeed

**Your understanding of what is happening**
There's an issue with connection from my Debian VPS, not sure why, like ip/range/etc being blocked or similar where it shouldn't be.

**What steps did you take to resolve issue yourself before reporting it here**
Try later, try to connect using home isp.

**Expected behavior**
No connection issues while trying to update Debian packages on my Debian VPS

**Distribution (please complete the following information):**
 - OS: Debian 11
 - Architecture: x86_64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Any Debian php package from packages.sury.org

**Additional context**
W: Failed to fetch https://packages.sury.org/php/dists/bullseye/InRelease  Could not connect to packages.sury.org:443 (195.238.127.98), connection timed out

**Comment by seraphyn** [comment]
Work as intended from my different networks and VPS
Have tried to dig it, have you ping the site etc?
<img width="860" alt="Bildschirmfoto 2024-05-21 um 07 38 47" src="https://github.com/oerdnj/deb.sury.org/assets/140527/76de159b-555d-42fd-83e1-21ef9dd6cdd3">

**Comment by oerdnj** [comment]
You need to start with debugging your network connection from the place where you can't connect. So far, this is in the "it doesn't work" bugreport category, and I can't really work with that.

I would suggest to contact your Debian VPS provider first.

**Comment by juozaspo** [comment]
Unfortunately I'm even unable to ping deb.sury.org while still able to ping sury.org from the vps and I administer the vps server myself. Unless there's an underlying issue caused by my VPS provider I'm not sure if I could do anything, I'll ask my vps provider first and update if there's any news. Checked traceroute, failure is after MELBICOM.balt-ix.net, maybe some firewall is misconfigured or blocking ranges, as changin ip didn't help.

**Comment by oerdnj** [comment]
> Checked traceroute, failure is after MELBICOM.balt-ix.net, maybe some firewall is misconfigured or blocking ranges, as changin ip didn't help.

That looks like broken peering. You need to work with the VPS provider on that.

**Comment by juozaspo** [comment]
It appears the address was blocked on provider site becouse of supposed attacks against the servers they host. After unblocking it should take some time for issue to solve itself. Rough translation from Lithuanian to English by google translator is quoted below, the firewall provider would think deb.sury.org would attack it while it usally shouldn't be the case or there were a large scale connection from/to there at a time so provider thought it was attack.

> Hello,
> 
> we can see that the IP address 195.238.127.98 (deb.sury.org) has been globally blocked by our firewall. We have done the unblocking of this IP address in the node, the result will be visible today at ~9 pm.
> 
> The reason for the IP blocking is an attack against one of our servers. However, at the moment, the server administrators do not see anything wrong, so they did the unblocking, but the result will have to wait a little while.
> 
> Have a nice day.

**Comment by insp1re1** [comment]
which isp? i cant seem to connect to it either for weeks.

**Comment by juozaspo** [comment]
The isp of the vps is `UAB Interneto vizija`, a server hosting service based in Lithuania, updating from my vps server works fine. Your should check your isp if it is not blocking connections to the target server on your side, it was the case fo me.

**Comment by insp1re1** [comment]
i managed to connect by using tor and torsocks to update apt, not ideal but works fine this way.

**Comment by w3box** [comment]
I am dealing with a similar problem. I can't connect to packages.sury.org due to timeout.

`Could not connect to packages.sury.org:443 (146.59.69.202), connection timed out`

The VPS provider assures me that they do not block the connection on their side.
I have no problem with another VPS from the same provider. 

Could I ask for verification that on the packages.sury.org side, my server's IP (185.25.150.118) has not been blocked for some reason?

**Comment by insp1re1** [comment]
You must be fella

**Comment by oerdnj** [comment]
@insp1re1 Thank you for letting me know what I am doing. You must surely know it better.

**Comment by insp1re1** [comment]
I know a lot are having issues. But you don't care, basta.

**Comment by MuldersMakes** [comment]
Basta
