### ISSUE TITLE
Ubuntu 24.04 : Signature by key uses weak algorithm

### ISSUE THREAD

**Issue by admike82** [oerdnj/deb.sury.org#2139]
Hi,
when i do "sudo apt update", i have this message :

w: https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/noble/InRelease: Signature by key 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C uses weak algorithm (rsa1024)

Have a good day

**Comment by oerdnj** [comment]
#1429

**Comment by workmailrahul** [comment]
Got the same issue

**Comment by pausasilva** [comment]
Does anyone solvd this problem?

**Comment by kodmanyagha** [comment]
`sudo nano /etc/apt/apt.conf.d/99weakkey-warning`

Paste this to here:
```
APT::Key::Assert-Pubkey-Algo ">=rsa1024";
```

Source: https://github.com/sabnzbd/sabnzbd/issues/2845

**Comment by pausasilva** [comment]
Thank you so much @kodmanyagha , its helpeds me a lot.

**Comment by bfontaine** [comment]
@pausasilva it does not solve the issue; it just makes the warning disappear.

**Comment by blakethepatton** [comment]
Fixed the warning on my system by removing and re-adding the ppa. 

```
sudo add-apt-repository --remove ppa:ondrej/php
sudo add-apt-repository ppa:ondrej/php
```

Your ppa name may vary as you might have the nginx or apache or gearman version.

This is based on what [Guruprasad (lgp171188)](https://answers.launchpad.net/launchpad/+question/809194#comment-12) said over on launchpads support forum. 

> All the affected Launchpad PPAs have been signed with a more secure key and Launchpad now serve that key. So for fixing this issue for PPAs already added to a system, just remove and re-add them.

**Comment by abs2310** [comment]
Thanks @blakethepatton your solution helped to remove and re-add the repo.
