### ISSUE TITLE
libnginx-mod-http-lua have unmet dependencies

### ISSUE THREAD

**Issue by tubby1981** [oerdnj/deb.sury.org#2141]
```
 apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 lua-resty-core : Depends: libnginx-mod-http-lua (>= 1:0.10.26) but 1.24.0-1+ubuntu22.04.1+deb.sury.org+2 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Distribution (please complete the following information):**
Ubuntu 22.04.4 LTS amd64
 - OS: [e.g. Debian or Ubuntu]
 - Architecture: [e.g. amd64 or armhf or ...]
 - Repository: [deb http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy main]

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
```
apt-cache policy libnginx-mod-http-lua
libnginx-mod-http-lua:
  Installed: 1.24.0-1+ubuntu22.04.1+deb.sury.org+2
  Candidate: 1:0.10.26+1.24.0-2+ubuntu22.04.1+deb.sury.org+5
  Version table:
     1:0.10.26+1.24.0-2+ubuntu22.04.1+deb.sury.org+5 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
 *** 1.24.0-1+ubuntu22.04.1+deb.sury.org+2 100
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
The updated version is available, try installing it and see what happens?
```
     1:0.10.26+1.24.0-2+ubuntu22.04.1+deb.sury.org+5 500
        500 http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
```

**Comment by tubby1981** [comment]
Still the same error when I try to upgrade. I can test it to remove it and install it again

`
apt show libnginx-mod-http-lua
Package: libnginx-mod-http-lua
Version: 1:0.10.26+1.24.0-2+ubuntu22.04.1+deb.sury.org+5
Priority: optional
Section: httpd
Source: libnginx-mod-http-lua (1:0.10.26-2+ubuntu22.04.1+deb.sury.org+5)
Maintainer: Debian Nginx Maintainers <pkg-nginx-maintainers@alioth-lists.debian.net>
Installed-Size: 479 kB
Depends: lua-resty-core (<< 0.1.28.1~), lua-resty-core (>= 0.1.28), libnginx-mod-http-ndk, nginx-abi-1.24.0-1, libc6 (>= 2.33), libluajit-5.1-2 (>= 2.1-20220411) | libluajit-5.1-2 (>= 2.1.0~beta3)
Recommends: nginx
Download-Size: 174 kB
APT-Sources: http://ppa.launchpad.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
Description: Lua module for Nginx
 Embed Lua runtime into nginx.
 .
 This module embeds Lua, via LuaJIT 2-5.1, into Nginx and by leveraging Nginx's
 subrequests, allows the integration of the powerful Lua threads
 (Lua coroutines) into the Nginx event model.

N: There is 1 additional record. Please use the '-a' switch to see it
`

`
dpkg -l | grep lua
ii  liblua5.3-0:amd64                      5.3.6-1build1                                          amd64        Shared library for the Lua interpreter version 5.3
ii  libluajit-5.1-2:amd64                  2.1.0+openresty20231117-1+ubuntu22.04.1+deb.sury.org+1 amd64        OpenResty-maintained branch of LuaJIT (shared objects)
ii  libluajit-5.1-common                   2.1.0+openresty20231117-1+ubuntu22.04.1+deb.sury.org+1 all          OpenResty-maintained branch of LuaJIT (common files)
hi  libnginx-mod-http-lua                  1.24.0-1+ubuntu22.04.1+deb.sury.org+2                  amd64        Lua module for Nginx
ii  lua-lpeg:amd64                         1.0.2-1                                                amd64        LPeg library for the Lua language
hi  lua-resty-core                         0.1.28-2+ubuntu22.04.1+deb.sury.org+2                  all          New FFI-based Lua API for NGINX Lua module
ii  lua-resty-lrucache                     0.13-10+ubuntu22.04.1+deb.sury.org+1                   all          Simple LRU cache for the ngx_lua module
`

**Comment by oerdnj** [comment]
You are not even trying to provide any useful information, so I can help you.

Did you do `apt --fix-broken install` and if yes with what result?

Did you do `apt install libnginx-mod-http-lua` like I told you and if yes with what result?

Anyway, the packages have been updated to 1.26.1, so there's a little point to debug the 1.24.0 installation now.
