### ISSUE TITLE
can't update package 

### ISSUE THREAD

**Issue by aminbahgat** [oerdnj/deb.sury.org#2144]
When do update get the error :  EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key
sudo apt update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://packages.sury.org/apache2 bullseye InRelease [7,479 B]
Get:5 https://packages.sury.org/php bullseye InRelease [7,551 B]
Hit:6 http://mirror.hetzner.com/debian/packages bullseye InRelease
Hit:7 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:8 http://mirror.hetzner.com/debian/packages bullseye-updates InRelease
Hit:9 http://mirror.hetzner.com/debian/security bullseye-security InRelease
Hit:10 https://apt.hestiacp.com bullseye InRelease
Hit:11 https://nginx.org/packages/mainline/debian bullseye InRelease
Err:4 https://packages.sury.org/apache2 bullseye InRelease
  The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
Err:5 https://packages.sury.org/php bullseye InRelease
  The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
Hit:12 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/debian bullseye InRelease
Hit:13 https://packagecloud.io/ookla/speedtest-cli/debian bullseye InRelease
Reading package lists... Done
W: GPG error: https://packages.sury.org/apache2 bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
E: The repository 'https://packages.sury.org/apache2 bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by rfay** [comment]
You almost certainly have the expired key. Please see
* https://github.com/oerdnj/deb.sury.org/issues/2074
