### ISSUE TITLE
For each PHP release, use latest Sqlite3 release

### ISSUE THREAD

**Issue by dmausner** [oerdnj/deb.sury.org#2145]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
A _request_ to build each PHP release with the latest available Sqlite3 release.

**Describe the solution you'd like**
When using latest PHP upgrade, to experience the Sqlite3 extension upgraded to the latest Sqlite3 release.

**Describe alternatives you've considered**
It is not possible to separately compile php_sqlite3.dll (for Windows) or php_sqlite3 (Linux) module, for end user who lacks the required tool chain experience.

Please understand that this issue tracker is specifically meant to report issues with the packages and with the repositories. I won't teach you the basics of system administration, I won't help you with bugs in the software itself. For both, there are better sites where are people with more free time that allows them to be more friendly to newcomers.

Please make sure you read [Dear anonymous internet user asking for help...](https://berthub.eu/articles/posts/anonymous-help/) by Bert Hubert and [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

If you understand the purpose of this issue tracker and describe your **request** accurately (where the template below will help), I might be able to help you.

**Distribution (please complete the following information):**
 - OS: Any supported Linux, Any supported Windows.
 - Architecture: Any supported.
 - Repository: Any supported.

**Package(s) (please complete the following information):**
php8.3-sqlite3:
  Installed: 8.3.8-2+0~20240608.35+debian12~1.gbp4d7dbc
  Candidate: 8.3.8-2+0~20240608.35+debian12~1.gbp4d7dbc
  Version table:
 *** 8.3.8-2+0~20240608.35+debian12~1.gbp4d7dbc 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
d

**Additional context**
![image](https://github.com/oerdnj/deb.sury.org/assets/8300916/83f1c8aa-1786-4a67-af68-ce17b403abfe)

Note: latest Sqlite release is 3.46.

**Comment by oerdnj** [comment]
The SQLite3 library is dynamically linked and PHP is using whatever version is provided by the Ubuntu/Debian release.

I maintain the extra libraries only in special cases and generally avoid doing that, so no, sorry, this is not going to happen.

P.S.: You didn’t even described why it is so important to have the latest SQLite3 available.
