### ISSUE TITLE
Restart=on-failure

### ISSUE THREAD

**Issue by SharkMachine** [oerdnj/deb.sury.org#2147]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
PHP-FPM crashed because of segfault and it didn't restart.

**Describe the solution you'd like**
`Restart=on-failure` on the service file.

**Describe alternatives you've considered**
Is there any alternative? I'd like to know.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Weird, I though it's already set to `on-failure`, but apparently it isn't. It will be part of the next upload (when it happens).
