### ISSUE TITLE
Module `mongodb` is missing for PHP 7.1 (Noble)

### ISSUE THREAD

**Issue by SpraxDev** [oerdnj/deb.sury.org#2153]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
We are installing multiple PHP versions on our internal (development) servers and are planning to switch from self-compiled PHP binaries to *deb.sury.org*.
We would like to install the same set of modules for each PHP version we install.

**Describe the solution you'd like**
It would be great if the `mongodb` module could be provided for PHP 7.1 too, as it is already provided for all the other PHP versions.

**Describe alternatives you've considered**
The alternative would probably be to not provide the mongodb module for that specific PHP version as it is luckily available for all the other PHP versions.

**Distribution (please complete the following information):**
 - OS: Ubuntu 24.04 LTS (Noble Numbat)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
N: Unable to locate package php7.1-mongodb
N: Couldn't find any package by glob 'php7.1-mongodb'
N: Couldn't find any package by regex 'php7.1-mongodb'
```

**Additional context**
–

**Comment by oerdnj** [comment]
Truly, the src:php-mongodb-1-11 build was missing for noble. It should be all fixed now.
