### ISSUE TITLE
Module `mailparse` is missing for PHP 7.0, 7.1, 7.2 (Noble)

### ISSUE THREAD

**Issue by SpraxDev** [oerdnj/deb.sury.org#2154]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
We are installing multiple PHP versions on our internal (development) servers and are planning to switch from self-compiled PHP binaries to *deb.sury.org*.
We would like to install the same set of modules for each PHP version we install.

**Describe the solution you'd like**
It would be great if the `mailparse` module could be provided for PHP 7.0, 7.1 and 7.2 like it is already available for the other PHP versions.

**Describe alternatives you've considered**
No real alternative considered yet.

**Distribution (please complete the following information):**
 - OS: Ubuntu 24.04 LTS (Noble Numbat)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
N: Unable to locate package php7.0-mailparse
N: Couldn't find any package by glob 'php7.0-mailparse'
N: Couldn't find any package by regex 'php7.0-mailparse'
N: Unable to locate package php7.1-mailparse
N: Couldn't find any package by glob 'php7.1-mailparse'
N: Couldn't find any package by regex 'php7.1-mailparse'
N: Unable to locate package php7.2-mailparse
N: Couldn't find any package by glob 'php7.2-mailparse'
N: Couldn't find any package by regex 'php7.2-mailparse'
```

**Additional context**
–

**Comment by oerdnj** [comment]
That affected all supported distributions - I've now packaged this as `src:php-mailparse-3` to keep support for PHP 7.0-7.2
