### ISSUE TITLE
403 error on packages.sury.org/php/dists/buster

### ISSUE THREAD

**Issue by marcodestefani** [oerdnj/deb.sury.org#2156]
I am using some Debian packages from https://packages.sury.org/php/dists/ but the /bullseye folder works as expected, the /buster folder is returning a 403. This has been happening from today, AFAIK, yesterday it was working fine.

1. Go to ['packages.sury.org/php/dists/buster'](https://packages.sury.org/php/dists/buster)
2. See the 403
3. Go to ['packages.sury.org/php/dists/bullseye'](https://packages.sury.org/php/dists/bullseye)
4. The folder is correctly shown

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/2098
