### ISSUE TITLE
Update Request Apache 2.4.60

### ISSUE THREAD

**Issue by stondino00** [oerdnj/deb.sury.org#2158]
Apache Update PPA to 2.4.60

https://[downloads.apache.org/httpd/CHANGES_2.4.60](https://downloads.apache.org/httpd/CHANGES_2.4.60)

**Comment by oerdnj** [comment]
Should be already built or building...

**Comment by onezero1010101** [comment]
Looks like the builds have failures :(

**Comment by oerdnj** [comment]
Checking...

**Comment by oerdnj** [comment]
Fixed - the upstream Debian package switched to `liblua5.4-dev` which is not present in the older Ubuntu releases. I have provided alternative B-D (`liblua5.3-dev`) and all packages have been built now.

**Comment by onezero1010101** [comment]
Awesome!   Thanks for your continued efforts!

**Comment by oerdnj** [comment]
> New upstream version 2.4.61

Oh no!

**Comment by onezero1010101** [comment]
Woe is the life.  That didn't take long!
