### ISSUE TITLE
[php-7.0] php-xdebug missing in xenial PPA's

### ISSUE THREAD

**Issue by glitsj16** [oerdnj/deb.sury.org#216]
Hi, thanks for all your efforts on these php PPA's, much appreciated. I've noticed that php-xdebug isn't in the xenial PPA's you offer (contrary to wily, vivid & trusty). Is there any specific reasoning behind this? Not a big issue, the wily PPA works just fine on xenial too. Just wanted a heads-up on this.

**Comment by oerdnj** [comment]
xdebug was uploaded before I enabled Xenial builds. It will get fixed with next upload (RC4 I guess).

**Comment by glitsj16** [comment]
Thanks for the clarification. Closing this issue.

**Comment by oerdnj** [comment]
FYI uploaded rc3 to xenial now for the convenience.
