### ISSUE TITLE
[courier] Missing courier-mta.service

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#217]
I just installed the 0.75.0-10 packages and courier-mta.service is missing to start up esmtpd (not esmtpd-ssl) on port 25 otherwise incoming mail cannot be accepted. It may be possible to configure esmtpd-ssl to also start on port 25 but I'm not aware of anyway to turn off mandatory SSL handling of port 25 if esmptd-ssl is used, which would defeat the purpose of handling generic incoming mail on port 25. It may be possible to get the esmtpd-ssl daemon to only handle SSL only if requested by the sending mta but in my experience there are enough brain dead mail servers out there to require the non-SSL esmptd deamon to handle port 25 traffic and let esmtpd-ssl handle authenticated port 465/SSL traffic.

Along the same lines I think a courier-imap.service is also needed so that port 143 with TLS can be started. I only use IMAP on port 993/SSL these days but IMAP on port 143/TLS is also a common requirement and I don't think imapd-ssl starts up on port 143. Again, perhaps the /etc/courier/imapd-ssl config file could be tweaked to start both IMAP ports 993/SSL and 143/TLS but I've never tried that.

I see that the courier-mta-ssl and courier-imap-ssl packages are empty and can be removed. Good one.

I copied courier-mta-ssl.service to courier-mta.service and made a few edits and I now have incoming mail with my particular configuration.
```
~ cat /lib/systemd/system/courier-mta.service
[Unit]
Description=Courier ESMTP Daemon
Requires=courier-authdaemon.service,courier.service,courierfilter.service
After=courier-authdaemon.service,courier.service,courierfilter.service
#PartOf=courier-mta.service

[Service]
Type=forking
ExecStart=/usr/sbin/esmtpd start
ExecStop=/usr/sbin/esmtpd stop
PIDFile=/var/run/courier/esmtpd.pid

[Install]
WantedBy=multi-user.target
```

**Comment by markc** [comment]
I just did another fresh wily reinstall by completely removing the previous packages and starting from scratch. The issue of a missing `courier-mta.service` file is definitely a problem otherwise there is nothing on port 25 to accept external mail and the perms of `/etc/courier` must be `chmod 755` otherwise users `.courier` and `.mailfilter` files cannot access `/etc/courier/maildroprc`. FWIW I use this script to finish my setup after installing the packages...

https://raw.githubusercontent.com/markc/sh/master/newcourier

**Comment by oerdnj** [comment]
Should be fixed in `courier_0.75.0-11+deb.sury.org~*+1`
