### ISSUE TITLE
PHP 8.2.21 breaks php8.2-imagick on Debian 12

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#2171]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
PHP 8.2.21 upgrade from today breaks `php8.2-imagick`.

```
php8.2-common : Breaks: php8.2-imagick (< 3.7.0-5~) but 3.7.0-4+0~20231125.43+debian12~1.gbpbf7e27 is to be installed

$ apt-cache show php8.2-imagick
Package: php8.2-imagick
Source: php-imagick
Version: 3.7.0-4+0~20231125.43+debian12~1.gbpbf7e27

$ apt-cache show php8.2-common
Package: php8.2-common
Source: php8.2
Version: 8.2.21-1+0~20240704.58+debian12~1.gbpaee42f
...
Breaks: php8.2-apcu (<< 5.1.23-1~), php8.2-imagick (<< 3.7.0-5~), php8.2-oauth (<< 2.0.7++-1~)
```

**Your understanding of what is happening**
Debian 12 doesn't have latest `php-imagick` build available, which was bumped apparently ~a week ago to `3.7.0-5`.

**What steps did you take to resolve issue yourself before reporting it here**
Checked salsa.debian.org changelogs vs. available packages on repo.

**Expected behavior**
PHP 8.2.21 upgrade doesn't break/remove `php8.2-imagick`

**Distribution (please complete the following information):**
 - OS: Debian 12
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**

**Comment by oerdnj** [comment]
Thanks, 3.7.0-5 packages are building right now.

**Comment by todeveni** [comment]
Thanks!
New package available and upgrades working 👍

**Comment by AleksCee** [comment]
@oerdnj same error on Ubuntu 22.04:
The following packages have unmet dependencies:
 php8.2-common : Breaks: php8.2-imagick (< 3.7.0-5~) but 3.7.0-4+ubuntu22.04.1+deb.sury.org+2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by oerdnj** [comment]
> @oerdnj same error on Ubuntu 22.04: The following packages have unmet dependencies: php8.2-common : Breaks: php8.2-imagick (< 3.7.0-5~) but 3.7.0-4+ubuntu22.04.1+deb.sury.org+2 is to be installed E: Unable to correct problems, you have held broken packages.

I see all of them to be correctly built now. Maybe try `apt-get update` again?

**Comment by oerdnj** [comment]
https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=imagick&field.status_filter=published&field.series_filter=

**Comment by AleksCee** [comment]
> I see all of them to be correctly built now. Maybe try `apt-get update` again?
After this post I see that a new version is coming with Update and can be installed. Sorry for bothering..
