### ISSUE TITLE
[courier] suid root submitmkdir and chmod 755 /etc/courier

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#218]
A couple of extra tweaks before mail could be delivered...
```
~ chown root /usr/lib/courier/courier/submitmkdir
~ chmod 4755 /usr/lib/courier/courier/submitmkdir
```
And the `/etc/courier` folder has to be `chmod 755` so that any uid:gid user deliveries via courier dotfiles and mailfilters can open `/etc/courier/maildroprc` (which itself needs to be 644).

Also some of the created *.dat files needed to be chown :courier but I haven't tested exactly which ones.

**Comment by oerdnj** [comment]
Should be fixed in `courier_0.75.0-11+deb.sury.org~*+1`

Please open extra bug when you confirm what *.dat files needs to be fixed. Perhaps a helper script is needed for that.
