### ISSUE TITLE
403 Error when trying to update or install from sury repository

### ISSUE THREAD

**Issue by yesoos** [oerdnj/deb.sury.org#2182]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
When trying to refresh (apt-get update) or install from sury repository I get an 403 error. Tested on multiple servers (located in France). Also tested from local PC - 403 as well.

**To Reproduce**
Run apt-get update or try installing something from sury repository.

**Your understanding of what is happening**
N/A

**What steps did you take to resolve issue yourself before reporting it here**
Tried accessing the repo from multiple locations.

**Expected behavior**
Update or installation working

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by oerdnj** [comment]
> I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

you obviously haven’t
