### ISSUE TITLE
AVIF support missing in PHP 8.2/8.3 for Ubuntu 24.04 (noble numbat)

### ISSUE THREAD

**Issue by eposjk** [oerdnj/deb.sury.org#2183]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

**Describe the bug**

When upgrading from Ubuntu 22.04 to Ubuntu 24.04, I noticed that AVIF support is missing.
As my application uses AVIF, I did some systematic tests:

function imagecreatefromavif seems to be available for
| | Ubuntu 22.04 | Ubuntu 24.04 |
| --- | --- | --- |
| PHP 8.1 | available | available |
| PHP 8.2 | available | missing |
| PHP 8.3 | available | missing |

**Your understanding of what is happening**

It seems that AVIF support has been deactivated for these build (but didn't find your packaging code repository to confirm that theory).
As I see some other issues reported here concerning AVIF support, I'm not sure if this was done intentionally.

Are there any plans to support AVIF for Ubuntu 24.04 (except in PHP 8.1)?

**Expected behavior**
- functions imagecreatefromavif and imageavif are available
- phpinfo() reports "AVIF Support" in section "gd"

**Distribution (please complete the following information):**
 - OS: Ubuntu 24.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**

php8.1-gd:
  Installiert:           8.1.29-1+ubuntu22.04.1+deb.sury.org+1
  Installationskandidat: 8.1.29-1+ubuntu22.04.1+deb.sury.org+1
  Versionstabelle:
 *** 8.1.29-1+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     8.1.2-1ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
php8.2-gd:
  Installiert:           8.2.21-1+ubuntu22.04.1+deb.sury.org+1
  Installationskandidat: 8.2.21-1+ubuntu22.04.1+deb.sury.org+1
  Versionstabelle:
 *** 8.2.21-1+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
php8.3-gd:
  Installiert:           8.3.9-1+ubuntu22.04.1+deb.sury.org+1
  Installationskandidat: 8.3.9-1+ubuntu22.04.1+deb.sury.org+1
  Versionstabelle:
 *** 8.3.9-1+ubuntu22.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by oerdnj** [comment]
I think this might solve itself with the next upload as I uploaded updated libgd2 this week.

**Comment by rfay** [comment]
Related:
* https://github.com/oerdnj/deb.sury.org/issues/2024

**Comment by andypost** [comment]
Is it solved? a week ago was a new upload

**Comment by eposjk** [comment]
Yes - looks good! Thanks!

**Comment by ariaieboy** [comment]
Should we install specific dependencies to activate the avif support in 24.04?
Still, Avif support is missing here is my PHP versions:
```
php-common/now 2:94+ubuntu24.04.1+deb.sury.org+1 all [installed,local]
php8.3-bcmath/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-cli/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-common/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-curl/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-gd/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-igbinary/now 3.2.16-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-imagick/now 3.7.0-5+ubuntu24.04.1+deb.sury.org+2 amd64 [installed,local]
php8.3-imap/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-intl/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-ldap/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-mbstring/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-memcached/now 3.2.0++-1+ubuntu24.04.1+deb.sury.org+2 amd64 [installed,local]
php8.3-msgpack/now 1:2.2.0-4+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-mysql/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-opcache/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-pgsql/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-readline/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-redis/now 6.0.2-1+ubuntu24.04.1+deb.sury.org+2 amd64 [installed,local]
php8.3-soap/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-sqlite3/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-swoole/now 6.0.0+really+5.1.4-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-xml/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]
php8.3-zip/now 8.3.11-1+ubuntu24.04.1+deb.sury.org+1 amd64 [installed,local]

libgd3/now 2.3.3-9ubuntu5 amd64 [installed,local]
libgdbm-compat4t64/now 1.23-5.1build1 amd64 [installed,local]
libgdbm6t64/now 1.23-5.1build1 amd64 [installed,local]
libgdk-pixbuf-2.0-0/now 2.42.10+dfsg-3ubuntu3.1 amd64 [installed,local]
libgdk-pixbuf2.0-bin/now 2.42.10+dfsg-3ubuntu3.1 amd64 [installed,local]
libgdk-pixbuf2.0-common/now 2.42.10+dfsg-3ubuntu3.1 all [installed,local]
```

**Comment by oerdnj** [comment]
> libgd3/now 2.3.3-9ubuntu5

What's the output of `apt-cache policy libgd3`

**Comment by ariaieboy** [comment]
> > libgd3/now 2.3.3-9ubuntu5
> 
> What's the output of `apt-cache policy libgd3`

```
# apt-cache policy libgd3
libgd3:
  Installed: 2.3.3-9ubuntu5
  Candidate: 2.3.3-9ubuntu5
  Version table:
 *** 2.3.3-9ubuntu5 100
        100 /var/lib/dpkg/status
```
I installed php packages on docker image ubuntu:24.04 if that matters.

**Comment by ariaieboy** [comment]
I've managed to fix the problem using this command:
```bash
apt-get --with-new-pkgs upgrade libgd3
```

**Comment by tmotyl** [comment]
thanks @ariaieboy ! 
for me just `apt-get install libgd3` (ubuntu 24.04) worked on php 8.3
it updated from libgd3 2.3.3-9ubuntu5 to 2.3.3-12+ubuntu24.04.1+deb.sury.org+1

**Comment by BackuPs** [comment]
> ibgd2

It is still misisng. I just did a fresh ubuntu server 24.04 install

Above solutions do not work.

**Comment by BackuPs** [comment]
Ok the solution for a clean ubuntu 24.04 server is this

```
sudo apt install php
apt install php-mysql php-imap php-ldap php-xml php-curl php-mbstring php-zip php-gd

apt-get install ca-certificates apt-transport-https software-properties-common
add-apt-repository ppa:ondrej/php
apt-get install libgd3

```

**Comment by oerdnj** [comment]
> Ok the solution for a clean ubuntu 24.04 server is this
> 
> ```
> sudo apt install php
> apt install php-mysql php-imap php-ldap php-xml php-curl php-mbstring php-zip php-gd
> 
> apt-get install ca-certificates apt-transport-https software-properties-common
> add-apt-repository ppa:ondrej/php
> apt-get install libgd3
> apt-get --with-new-pkgs upgrade libgd3
> ```
> 
> After which Avif support comes back and works

That’s a solution for mixing packages from random repositories together. If you are using deb.sury.org packages you need to use all of them otherwise stuff will break.
