### ISSUE TITLE
php grpc module is outputting experiment log messages

### ISSUE THREAD

**Issue by DavidGoodwin** [oerdnj/deb.sury.org#2186]
Hi, Can you revert / yank the update to PHP8.2-grpc please until upstream release an update? See linked ticket(s).

See also : 

https://github.com/grpc/grpc/issues/37222

https://github.com/grpc/grpc/issues/37178

**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**

grpc extension is causing PHP to output unnecessary text to stdout etc

`php -m` writes this to stdout : 

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721116027.736562 3383435 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
```

**Your understanding of what is happening**

the grpc extension presumably has some unnecessary functionality configured/turned on that's a breaking change.

**What steps did you take to resolve issue yourself before reporting it here**

**Distribution (please complete the following information):**

 - OS: Debian Bookworm
 - Architecture: amd64
 - Repository:  packages.sury.org

**Package(s) (please complete the following information):**

```
$ apt-cache policy php8.2-grpc
php8.2-grpc:
  Installed: 1.65.0-1+0~20240714.26+debian12~1.gbp93ccf5
  Candidate: 1.65.0-1+0~20240714.26+debian12~1.gbp93ccf5
  Version table:
 *** 1.65.0-1+0~20240714.26+debian12~1.gbp93ccf5 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by stanley-cheung** [comment]
`grpc` yanked the `v1.65.0` release just now

**Comment by oerdnj** [comment]
I’ll take a look at this once the power is back after the thunderstorms.

**Comment by oerdnj** [comment]
Can't tell if 1.65.1 fixed the issue, so please report back.

**Comment by DavidGoodwin** [comment]
```
php8.2-grpc:
  Installed: 1.65.1-1+0~20240717.27+debian12~1.gbp4672cc
  Candidate: 1.65.1-1+0~20240717.27+debian12~1.gbp4672cc
  Version table:
 *** 1.65.1-1+0~20240717.27+debian12~1.gbp4672cc 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

still does : 

```
$ php -m
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721201220.618502 2809173 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
[PHP Modules]
....
```

**Comment by oerdnj** [comment]
Why would they yank 1.65.0 only to release 1.65.1 with the same problem?

Can some confirm that 1.64.2 is ok?  I've seen it mentioned that it also suffers from the logging problem too...

**Comment by DavidGoodwin** [comment]
the php8.2-grpc 1.64.1-1+0~20240623.23+debian12~1.gbpe8a241 package was fine ... I don't see a package with 1.64.2 in it's version string (yet?).

**Comment by garyburgmann** [comment]
@oerdnj can confirm the previous release 1.64.1 was perfectly fine.

I agree, crazy they would try to hastily push out 1.65.1 so fast knowing the problems with 1.65.0 🤷‍♂️

**Comment by garyburgmann** [comment]
@oerdnj this fixed my problems for now. Thanks!

![image](https://github.com/user-attachments/assets/5df59f50-a06a-4592-818d-af8579a58b00)

**Comment by DavidGoodwin** [comment]
Hi - fix confirmed. 

`1.65.1.really.1.64.1-1+0~20240717.28+debian12~1.gbp1cb6f3` fixes it for me too. Thank you!

**Comment by oerdnj** [comment]
@DavidGoodwin @stanley-cheung @garyburgmann Hey, grpc 1.65.2 has been released, but as far as I can tell, the issue hasn't been fixed yet, right?

**Comment by garyburgmann** [comment]
No idea. The GitHub Action we use relies on the version you package up. So as long as your version is good, we are good.On 6 Aug 2024, at 16:41, Ondřej Surý ***@***.***> wrote:﻿
@DavidGoodwin @stanley-cheung @garyburgmann Hey, grpc 1.65.2 has been released, but as far as I can tell, the issue hasn't been fixed yet, right?

**Comment by pulzarraider** [comment]
To get rid of the message, the grpc.grpc_verbosity have to be set to `error`.
