### ISSUE TITLE
[courier] @certsdir@/esmtpd.pem

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#219]
Looks like this `@certsdir@` config variable was not converted to `/etc/courier` in `/etc/courier/esmptd`.
```
# #TLS_CERTFILE=@certsdir@/esmtpd.pem
TLS_CERTFILE=/etc/courier/esmtpd.pem
```
BTW I just discovered that I made a significant mistake of using some older config files that I lazily copied into a fresh install so the previous 2 issue may not be real issues. I will have to do yet another fresh install to be sure.

**Comment by oerdnj** [comment]
Should be fixed in `courier_0.75.0-11+deb.sury.org~*+1`
