### ISSUE TITLE
please publish the script you are using to compile the packages

### ISSUE THREAD

**Issue by ecxod** [oerdnj/deb.sury.org#2193]
Could you please publish next to the code of conduct the script you are using to compile the packages.
I suspect you are somehow turning off security things, because for me it does not compile, and a whole lot of tests fail.

**Comment by rfay** [comment]
Related:
* https://github.com/oerdnj/deb.sury.org/issues/1436

**Comment by oerdnj** [comment]
It is all published, see the links in #1436; the `gbp buildpackage` should work with `debuild`, `pbuilder` and `sbuild`.

I only upload source packages to Debian and buildd processes are building the packages just fine from the source package too.

I recommend having a clean build environment, that helps a lot, especially at the beginning.
