### ISSUE TITLE
php8.3-lz4 not available

### ISSUE THREAD

**Issue by bobo333** [oerdnj/deb.sury.org#2196]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
`php8.3-lz4` package is not available for debian bullseye

**To Reproduce**
```
# apt-get install php8.3-lz4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php8.3-lz4
E: Couldn't find any package by glob 'php8.3-lz4'
E: Couldn't find any package by regex 'php8.3-lz4'
```

**Your understanding of what is happening**
The `lz4` extension has either not been built, or not been published, for PHP `8.3`. It is available for `8.2` and earlier versions.

```
# apt search php8.3-lz4
Sorting... Done
Full Text Search... Done

# apt search php8.2-lz4
Sorting... Done
Full Text Search... Done
php8.2-lz4/bullseye,bullseye 0.4.3-5+0~20230612.9+debian11~1.gbpe9959a amd64
  LZ4 Extension for PHP
```

**What steps did you take to resolve issue yourself before reporting it here**
I searched for packages with a similar name, as well as the same package from a previous version of PHP, confirming that the package is not available for PHP `8.3`. I also ensured I could install other PHP `8.3` packages, confirming it was not a configuration problem on my machine (ex: `php8.3-cli`)

**Expected behavior**
The package `php8.3-lz4` to be available for install

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

The package doesn't exist for PHP `8.3` so this is the output:

```
# apt-cache policy php8.3-lz4
N: Unable to locate package php8.3-lz4
N: Couldn't find any package by glob 'php8.3-lz4'
N: Couldn't find any package by regex 'php8.3-lz4'
```

For the `8.2` version that does exist, here is the output:

```
# apt-cache policy php8.2-lz4
php8.2-lz4:
  Installed: (none)
  Candidate: 0.4.3-5+0~20230612.9+debian11~1.gbpe9959a
  Version table:
     0.4.3-5+0~20230612.9+debian11~1.gbpe9959a 500
        500 https://artifactory.intern.weebly.net/sq/artifactory/ecom-debian-weebly bullseye/main amd64 Packages
        500 https://artifactory.intern.weebly.net/sq/artifactory/debian-sury bullseye/main amd64 Packages
```

**Additional context**
I saw mention of this package [here](https://github.com/oerdnj/deb.sury.org/issues/2034#issuecomment-1826838074) and while one of the referenced packages (`php8.3-libvirt`) is now available, `php8.3-lz4` is not.

**Comment by moewhale** [comment]
https://github.com/kjdev/php-ext-lz4 now supports php-8.3

**Comment by jogoossens** [comment]
Same here, it's missing for us :)

**Comment by bobo333** [comment]
works great, thank you!
