### ISSUE TITLE
[php] ssh2 module only available for php7.0

### ISSUE THREAD

**Issue by funbaker** [oerdnj/deb.sury.org#220]
When i apt-get install php-ssh2, the .so gets only installed in /usr/lib/php/20151012, not in /usr/lib/php/20131226, which makes it unusable when using both php versions 7.0 and 5.6.

**Comment by oerdnj** [comment]
Ack, this was oné od the first packaged external modules, and I'll update it soon(ish) enough.

**Comment by oerdnj** [comment]
Fixed in `php-ssh2_0.12-39-g3dfe336+0.12-1+deb.sury.org~*+1` upload.
