### ISSUE TITLE
debian 10 install php 5.6

### ISSUE THREAD

**Issue by brookzb** [oerdnj/deb.sury.org#2202]
apt-get update

error message
Hit:1 http://mirrors.163.com/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease  
Get:3 https://packages.sury.org/php buster InRelease                      
Err:3 https://packages.sury.org/php buster InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://packages.sury.org/php/dists/buster/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.sury.org/php buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by oerdnj** [comment]
Really? Ignoring bug template, and not looking at the existing **pinned** issues? What kind of reaction do you expect?

**Comment by brookzb** [comment]
What causes this? How should I fix it

**Comment by bbroekhu** [comment]
> What causes this? How should I fix it

Read this **pinned** post: https://github.com/oerdnj/deb.sury.org/issues/2098
It explains it all.
