### ISSUE TITLE
arm64 php release lags amd64 release (again)

### ISSUE THREAD

**Issue by satphil** [oerdnj/deb.sury.org#2203]
**Frequently asked questions**

- [x ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x ] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
Seems to be a repeat of earlier report "arm64 php release lags amd64 release #2104"
This time php8.3.11 on amd64, but php8.3.10 on arm64

**To Reproduce**
See previous report

**Your understanding of what is happening**
latest release not yet visible for arm64 but visible for amd64

**What steps did you take to resolve issue yourself before reporting it here**
re-ran "apt update"

**Expected behavior**
expect arm64 and amd64 releases to be in step

**Distribution (please complete the following information):**
 - OS: debian
 - Architecture: arm64 and amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
amd64:
# sudo apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]                                                                                        
Get:3 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]                                                                         
Get:4 https://packages.sury.org/php bookworm InRelease [7,548 B]                                                                                                                                             
Hit:5 https://download.docker.com/linux/debian bookworm InRelease                                                                                       
Hit:6 https://deb.nodesource.com/node_22.x nodistro InRelease
Get:7 https://packages.sury.org/php bookworm/main amd64 Packages [242 kB]
Fetched 352 kB in 2s (193 kB/s)   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.

# apt-cache policy php8.3
php8.3:
  Installed: (none)
  Candidate: 8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8
  Version table:
     8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages

# apt-cache policy php8.3-cli  # note 8.3.11 available for amd64
php8.3-cli:
  Installed: 8.3.10-1+0~20240802.37+debian12~1.gbp06babf
  Candidate: 8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8
  Version table:
     8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
 *** 8.3.10-1+0~20240802.37+debian12~1.gbp06babf 100
        100 /var/lib/dpkg/status

arm64:
# sudo apt update
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [38 B]
Get:2 file:/etc/apt/mirrors/debian-security.list Mirrorlist [47 B]                                                                      
Hit:7 https://packages.sury.org/php bookworm InRelease                                                       
Hit:3 https://cdn-aws.deb.debian.org/debian bookworm InRelease                     
Hit:4 https://cdn-aws.deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian bookworm-backports InRelease
Hit:6 https://cdn-aws.deb.debian.org/debian-security bookworm-security InRelease
Hit:8 https://deb.nodesource.com/node_22.x nodistro InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.

# apt-cache policy php8.3  # note php8.3 is architecture independent
php8.3:
  Installed: 8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8
  Candidate: 8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8
  Version table:
 *** 8.3.11-1+0~20240902.42+debian12~1.gbp1a56f8 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status

# apt-cache policy php8.3-cli  # note only 8.3.10 available for arm64
php8.3-cli:
  Installed: 8.3.10-1+0~20240802.37+debian12~1.gbp06babf
  Candidate: 8.3.10-1+0~20240802.37+debian12~1.gbp06babf
  Version table:
 *** 8.3.10-1+0~20240802.37+debian12~1.gbp06babf 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status

**Additional context**
# date
Tue 03 Sep 2024 16:56:49 AEST

**Comment by oerdnj** [comment]
The architecture builds for each package are built serially, so unless there’s a broken build, you just need to be little patient.

**Comment by satphil** [comment]
Sorry for the waste of a good panic. As you were, it's all OK now. Thanks as always for your assistance and contribution.

**Comment by oerdnj** [comment]
The build failures happen, but give it about a day - the arm builders run in QEMU and are a bit slower.
