### ISSUE TITLE
 libgd3 Breaks: libgd3:i386 (and vice versa)

### ISSUE THREAD

**Issue by Zorono** [oerdnj/deb.sury.org#2207]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
when i try to upgrade libgd3 or libgd3:i386 it throws the following errors
```
 libgd3 : Breaks: libgd3:i386 (!= 2.3.3-12+ubuntu22.04.1+deb.sury.org+1) but 2.3.0-2ubuntu2 is to be installed
 libgd3:i386 : Breaks: libgd3 (!= 2.3.0-2ubuntu2) but 2.3.3-12+ubuntu22.04.1+deb.sury.org+1 is to be installed
 ```

**Distribution:**
 - OS: Ubuntu 22.04.5
 - Architecture: amd64
 - Repository: ppa:ondrej/php

**Package(s):**
```
libgd3:
  Installed: 2.3.0-2ubuntu2
  Candidate: 2.3.3-12+ubuntu22.04.1+deb.sury.org+1
  Version table:
     2.3.3-12+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
 *** 2.3.0-2ubuntu2 500
        500 http://eg.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /sdb1/.system-base/var/lib/dpkg/status
```
and 
```
libgd3:i386:
  Installed: 2.3.0-2ubuntu2
  Candidate: 2.3.3-6+ubuntu22.04.1+deb.sury.org+1
  Version table:
     2.3.3-6+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main i386 Packages
 *** 2.3.0-2ubuntu2 500
        500 http://eg.archive.ubuntu.com/ubuntu jammy/main i386 Packages
        100 /sdb1/.system-base/var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
PPAs no longer build i386 packages.  Just don't try to cram everything onto the same system.

> I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported

Did you really though? https://github.com/oerdnj/deb.sury.org/issues/1873#issuecomment-1343164132
