### ISSUE TITLE
[php7.0-fpm] wrong log path in logrotate config

### ISSUE THREAD

**Issue by ConteZero** [oerdnj/deb.sury.org#221]
In /etc/php/7.0/fpm/php-fpm.conf the log path is:
```
; Error log file
; If it's set to "syslog", log is sent to syslogd instead of being written
; in a local file.
; Note: the default prefix is /var
; Default Value: log/php-fpm.log
error_log = /var/log/php7.0-fpm.log
```

But in /etc/logrotate.d/php7.0-fpm the log path is different:
```
/var/log/php/php7.0-fpm.log {
	rotate 12
	weekly
	missingok
	notifempty
	compress
	delaycompress
	postrotate
		/usr/lib/php/php7.0-fpm-reopenlogs
	endscript
}
```

**Comment by oerdnj** [comment]
Good catch. I have replaced `/var/log/php/` with just `/var/log/` in logrotate script in git. It will be part of some next upload. (This doesn't warrant torturing the build machines with just a change in the script.)

**Comment by oerdnj** [comment]
Fixed in `php7.0_7.0.2-2+deb.sury.org~*+1` and `php5.6_5.6.17+dfsg-2+deb.sury.org~*+1` uploads.
