### ISSUE TITLE
Remove requirement on PSR extension from Phlacon 5

### ISSUE THREAD

**Issue by Sn0wCrack** [oerdnj/deb.sury.org#2210]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Somewhat, currently I build the extension myself to specifically avoid needing to install the PSR extension as it causes issues with other local projects. It would be nice to just install via this repository.

**Describe the solution you'd like**
Phlacon removed the dependency on the PSR extension in Phalcon 5.0.0RC1, and while their site still states their dependency on it, I have successfully been compiling and running Phalcon 5 without the PSR extension installed since Phalcon 5.0.0RC1.

**Describe alternatives you've considered**
Right now I manually compile and install Phalcon 5 as part of a local environment setup and this works fine, just a little slow when setting things up again fresh.

**Distribution (please complete the following information):**
 - OS: Ubuntu 22.04 and 24.04
 - Architecture: arm64 and amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
- php8.2-phalcon5
- php8.3-phalcon5

I'm sure this affects other versions as well, but these are the ones I attempted to install.

**Additional context**
See changelog on 5.0.0RC1 release: https://github.com/phalcon/cphalcon/releases/tag/v5.0.0RC1

Specifically the following:

- Changed Phalcon\Logger\Logger to no longer depend on PSR interfaces https://github.com/phalcon/cphalcon/issues/15925
- Changed Phalcon\Cache\Cache to no longer depend on PSR interfaces https://github.com/phalcon/cphalcon/issues/15927
- Changed Phalcon\Html\Link to no longer depend on PSR interfaces https://github.com/phalcon/cphalcon/issues/15930

The build workflows in their GitHub have also removed installing PSR as part of their own build process.

**Comment by oerdnj** [comment]
This should be now gone.

**Comment by Sn0wCrack** [comment]
Thanks for that!
