### ISSUE TITLE
[Upgrade Request] phalcon5 to v5.8.0

### ISSUE THREAD

**Issue by rayanlevert** [oerdnj/deb.sury.org#2213]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Currently, the version 5.6.1 is the latest available for php8.0, 8.1, 8.2 and 8.3.

**Describe the solution you'd like**
Make available the latest version, v5.8.0 to their 4 compatible versions of PHP, from 8.0 to 8.3.

**Distribution (please complete the following information):**
 - OS: Debian 11 and 13
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
- php8.0-phalcon5
- php8.1-phalcon5
- php8.2-phalcon5
- php8.3-phalcon5

Thanks in advance and have a great day :)

**Comment by lucascesconetto** [comment]
Hello, I noticed that after the update the builds are no longer terminated by dependencies.

![image](https://github.com/user-attachments/assets/f7eed89a-a0e4-48c5-97dd-6534de88c1a5)

Could it be related to this update @oerdnj ?

**Comment by oerdnj** [comment]
Yes, but php8.3-phalcon package should be also available. I would need more than a screenshot to help with debugging this.

**Comment by hostaway-greg** [comment]
I am using php 8.2 and I cannot install phalcon:
```
apt-get install -y php8.2-phalcon5
```
I am getting this error:
```
0.293 Reading package lists...
1.597 Building dependency tree...
1.859 Reading state information...
2.047 Some packages could not be installed. This may mean that you have
2.047 requested an impossible situation or if you are using the unstable
2.047 distribution that some required packages have not yet been created
2.047 or been moved out of Incoming.
2.047 The following information may help to resolve the situation:
2.047
2.047 The following packages have unmet dependencies:
2.384  php8.2-phalcon : Breaks: php8.2-phalcon5 (< 5.8.0-4~) but 5.8.0-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
2.445 E: Unable to correct problems, you have held broken packages.
```

In aptitude I see that dependencies are not meet:

![image](https://github.com/user-attachments/assets/73da7d2b-41cf-4ccf-8005-4fc37f265ed8)

**Comment by oerdnj** [comment]
Unless something went wrong, it should be already fixed.

**Comment by oerdnj** [comment]
This looks fine to me:
```
# apt install php8.3-phalcon5
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  debsuryorg-archive-keyring libedit2 libpcre2-8-0 libsodium23 php-common php-phalcon php8.4-cli php8.4-common php8.4-opcache php8.4-phalcon php8.4-phpdbg php8.4-readline psmisc ucf
Suggested packages:
  php-pear
The following NEW packages will be installed:
  debsuryorg-archive-keyring libedit2 libsodium23 php-common php-phalcon php8.3-phalcon5 php8.4-cli php8.4-common php8.4-opcache php8.4-phalcon php8.4-phpdbg php8.4-readline psmisc ucf
The following packages will be upgraded:
  libpcre2-8-0
1 upgraded, 14 newly installed, 0 to remove and 5 not upgraded.
Need to get 7111 kB of archives.
After this operation, 32.5 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by oerdnj** [comment]
I can't really test the upgrade path as I don't have the old packages installed anywhere, but I think I got the combination of "Replaces/Breaks/Depends" right. If not, please report back.

**Comment by rayanlevert** [comment]
It works great on Ubuntu thanks, have you fixed it for the Debian repo ? It's still the v5.6.1.

**Comment by hostaway-greg** [comment]
@oerdnj One question: I see that there is 5.6.1 for 8.3 but for 8.2 there is only 5.8 :/ Is there a chance to fix this also ?

**Comment by oerdnj** [comment]
I need more information like `apt-cache policy` output for both.

**Comment by hostaway-greg** [comment]
Not sure if this is it:
```
root@84592814d2ea:/# apt-cache policy php8.3-phalcon
php8.3-phalcon:
  Installed: (none)
  Candidate: 5.8.0-6+ubuntu20.04.1+deb.sury.org+1
  Version table:
     5.8.0-6+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
root@84592814d2ea:/# apt-cache policy php8.3-phalcon5
php8.3-phalcon5:
  Installed: (none)
  Candidate: 5.8.0-4+ubuntu20.04.1+deb.sury.org+1
  Version table:
     5.8.0-4+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
root@84592814d2ea:/# apt-cache policy php8.2-phalcon
php8.2-phalcon:
  Installed: 5.8.0-6+ubuntu20.04.1+deb.sury.org+1
  Candidate: 5.8.0-6+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 5.8.0-6+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
root@84592814d2ea:/# apt-cache policy php8.2-phalcon5
php8.2-phalcon5:
  Installed: (none)
  Candidate: 5.8.0-4+ubuntu20.04.1+deb.sury.org+1
  Version table:
     5.8.0-4+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
```

I don't see it when I run it from within container vs on my system. 
I think the issue is with my apt remembering previous version of ppa manifest :/ 
So it looks like "currently" there is no 5.6.x at all on any version, correct?

**Comment by oerdnj** [comment]
There’s shouldn’t be a previous version.

**Comment by yannux** [comment]
Hello,  here is an output of apt depends on my docker container, if it can help

```
root@af0a415f1626:/app# apt install php8.3-phalcon5
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  php-phalcon php8.4-cli php8.4-common php8.4-opcache php8.4-phalcon php8.4-phpdbg php8.4-readline
```

```
root@af0a415f1626:/app# apt depends php8.3-phalcon5
php8.3-phalcon5
  Dépend: php-phalcon (>= 5.8.0-4~)
```
```
root@af0a415f1626:/app# apt depends php-phalcon
php-phalcon
  Pré-Dépend: php-common (>= 2:69~)
  Dépend: ucf
  Dépend: php8.4-phalcon
  Casse: php-phalcon5 (<< 5.8.0-4~)
  Remplace: php-phalcon5 (<< 5.8.0-4~)
```

**Comment by oerdnj** [comment]
`apt depends` output is not of any help. `apt-cache policy <package>` gives the most critical information.

**Comment by yannux** [comment]
Ok, I didn't know.

Here is : 

```
root@af0a415f1626:/app# apt-cache policy php8.3-phalcon5
php8.3-phalcon5:
  Installé : (aucun)
  Candidat : 5.8.0-4+0~20241008.2+debian11~1.gbpc8497d
 Table de version :
     5.8.0-4+0~20241008.2+debian11~1.gbpc8497d 500
        500 https://packages.sury.org/php bullseye/main amd64 Packages
```

**Comment by oerdnj** [comment]
Actually, @yannux, I found out it the `depends` was useful in this case :). I uploaded the fixed version a moment ago.

**Comment by yannux** [comment]
@oerdnj  great to read, I can confirm it's working well now :)

**Comment by rayanlevert** [comment]
I can confirm it as well, thanks for your time !

**Comment by hostaway-greg** [comment]
Hi @oerdnj
Sorry for digging back this issue, but I want to confirm one thing:
There is no 5.6.x at all on any version? Do you plan to restore it ?

Thank you and have a good day :)
