### ISSUE TITLE
Possible Trojan:Linux/Wacatac.A!ml found in php8.2-sqlite3-dbgsym ( 8.2.24-1+0~20240927.61+debian12~1.gbpbf08e8 )

### ISSUE THREAD

**Issue by DavidGoodwin** [oerdnj/deb.sury.org#2214]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**

Debian Bookworm server runs PHP8.2. 

It had the php8.2-sqlite3-dbgsym package installed which installs the file `/usr/lib/debug/.build-id/a9/f5e66b558a3a09eca789adc4b6fe4341aec9d2.debug`

Server is scanned by Microsoft Defender for Cloud which claims the file is infected with malware.

> 'Wacatac' malware was detected (Agentless)
> 
> Malware and unwanted software are undesirable applications that perform annoying, disruptive, or harmful actions on affected machines. Some of these undesirable applications can replicate and spread from one machine to another. Others are able to receive commands from remote attackers and perform activities associated with cyber attacks. This detection might indicate that the malware was stopped from delivering its payload. However, it is prudent to check the machine for signs of infection.
> 
> October 6, 2024 15:56 UTC

**To Reproduce**

1. install the php8.2-sqlite3-dbgsym package on bookworm.
2. md5 of /usr/lib/debug/.build-id/a9/f5e66b558a3a09eca789adc4b6fe4341aec9d2.debug is `36639bc0836166e7873c6abb6bf3b113` which triggers the malware detection 

**Your understanding of what is happening**

I can't tell if the file is actually infected with the malware, just that it triggered MS Defender for Cloud.

It maybe some sort of false positive. It may be there's a problem.

**What steps did you take to resolve issue yourself before reporting it here**

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.2-sqlite3-dbgsym:
  Installed: (none)
  Candidate: 8.2.24-1+0~20240927.61+debian12~1.gbpbf08e8
  Version table:
     8.2.24-1+0~20240927.61+debian12~1.gbpbf08e8 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
```

**Comment by DavidGoodwin** [comment]
![image](https://github.com/user-attachments/assets/2d01b3ed-ed4c-4ef9-8d4b-73341d4b7dd3)

which is the alert within azure, with file hashes : 

 * 1ae1d3a8216de332d0182b74daf34fd587d4a6a541a317fe4ed18f3cc43579c2
 * 36639bc0836166e7873c6abb6bf3b113
 * 39984de0c9fc0942510a7b2c61ec9be0f9ef91eb

**Comment by oerdnj** [comment]
No, this is nonsense. Thank you for reporting this though. It’s better to be safe than sorry.

**Comment by DavidGoodwin** [comment]
Thank you for the fast turn around / reply!
