### ISSUE TITLE
nginx-extras - > nginx/1.27.2 - > ubuntu 24.04 - > problem with installation

### ISSUE THREAD

**Issue by AbcITAndrzej** [oerdnj/deb.sury.org#2218]
Is there any chance that in the new version of nginx/1.27.2 on ubuntu 24.04 it will be possible to install nginx-extras ? Currently I can't install it because the version installed on the server is too new.

Installation log:
root@hostname:/etc/nginx# apt install nginx-extras
Reading package lists... Done
Building dependency tree... Done
Reading status information... Done
Some packages could not be installed. This may mean that
an impossible situation was requested or that an unstable distribution was used,
in which some packages have not yet been created or moved
from the Incoming directory.
The following information may help to resolve the situation:

The following packages have unmet dependencies:

nginx-extras : Depends: nginx (= 1.24.0-2ubuntu7.1) but 1.27.2-1~jammy is to be installed
Depends: libnginx-mod-http-geoip (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-http-image-filter (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-http-perl (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-http-xslt-filter (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-mail (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-stream (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-stream-geoip (= 1.24.0-2ubuntu7.1) but it will not be installed
Depends: libnginx-mod-http-auth-pam (>= 1:1.5.3-4~) but it will not be installed
Depends: libnginx-mod-http-cache-purge (>= 1:2.3-5~) but it will not be installed
Depends: libnginx-mod-http-dav-ext (>= 1:3.0.0-4~) but it will not be installed
Depends: libnginx-mod-http-echo (>= 1:0.63-5~) but it will not be installed
Depends: libnginx-mod-http-fancyindex (>= 1:0.5.2-4~) but it will not be installed
Depends: libnginx-mod-http-geoip2 (>= 1:3.4-4~) but it will not be installed
Depends: libnginx-mod-http-headers-more-filter (>= 1:0.34-4~) but it will not be installed
Depends: libnginx-mod-http-subs-filter (>= 1:0.6.4-5~) but it will not be installed
Depends: libnginx-mod-http-uploadprogress (>= 1:0.9.2-4~) but it will not be installed
Depends: libnginx-mod-http-upstream-fair (>= 1:0.0~git20120408.a18b409-4~) but it will not be installed
Depends: libnginx-mod-nchan (>= 1:1.3.6+dfsg-3~) but it will not be installed
Depends: libnginx-mod-stream-geoip2 (>= 1:3.4-4~) but it will not be installed

**Comment by oerdnj** [comment]
There's nothing indicating that you are actually using my packages. Closing.
