### ISSUE TITLE
[Ubuntu][focal] Opentelemetry conflicts with apcu

### ISSUE THREAD

**Issue by hostaway-greg** [oerdnj/deb.sury.org#2222]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [X] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
Using Ubuntu 20.04 I am trying to install opentelemetry in an existing project, but it is having information that it conflicts with apcu. I could not find any information on the internet, why is that. 
I looked at:
1. source code of the opentelemetry
2. opentelemetry docs
3. opentelemetry repo - they actually mention APCU for usage for sharing some telemetry between processes
4. google/duckduckgo and bing chat

**To Reproduce**
1. Existing project in docker
2. apt-get install php8.2-apcu works fine
3. apt-get install php8.2-opentelemetry returns error below

```
apt-get install php8.2-opentelemetry
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  php-apcu php8.2-apcu php8.4-apcu
The following NEW packages will be installed:
  php8.2-opentelemetry
0 upgraded, 1 newly installed, 3 to remove and 18 not upgraded.
Need to get 13.9 kB of archives.
After this operation, 327 kB disk space will be freed.
Do you want to continue? [Y/n] n
```

**Your understanding of what is happening**
As far as I understand, this is invalid. I used PECL and installed opentelemetry and everything works fine. 

**What steps did you take to resolve issue yourself before reporting it here**
Using pecl works.

**Expected behavior**
I am able to install opentelemetry using apt without issues.

**Distribution (please complete the following information):**
 - OS: Ubuntu 20.04 in Docker
 - Architecture: amd64
 - Repository: deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main

**Package(s) (please complete the following information):**
```
apt-cache policy php8.2-opentelemetry
php8.2-opentelemetry:
  Installed: (none)
  Candidate: 1.0.3-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
     1.0.3-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
apt-cache policy php8.2-apcu
php8.2-apcu:
  Installed: 5.1.24-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 5.1.24-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
 *** 5.1.24-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
apt info php8.2-opentelemetry
Package: php8.2-opentelemetry
Version: 1.0.3-1+ubuntu20.04.1+deb.sury.org+1
Priority: optional
Section: php
Source: php-opentelemetry
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 57.3 kB
Provides: php-opentelemetry
Pre-Depends: php-common (>= 2:69~)
Depends: php8.2-common, phpapi-20220829, libc6 (>= 2.25)
Conflicts: php-apcu, php-xcache
Breaks: php-opentelemetry (<< 1.0.3-1+ubuntu20.04.1+deb.sury.org+1~)
Replaces: php-opentelemetry (<< 1.0.3-1+ubuntu20.04.1+deb.sury.org+1~)
Download-Size: 13.9 kB
APT-Sources: http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
Description: OpenTelemetry auto-instrumentation support extension for PHP
```

**Comment by hostaway-greg** [comment]
@oerdnj Are you able to fix this?

**Comment by oerdnj** [comment]
I thought I already did, but I've been traveling a lot lately.  I'll recheck this again.

**Comment by oerdnj** [comment]
I think all should be peachy now. Could you recheck whether the issue is fixed for you now?
