### ISSUE TITLE
php-mongodb package is absent in version 8.4.1 for Debian

### ISSUE THREAD

**Issue by needz** [oerdnj/deb.sury.org#2226]
When installing the new 8.4.1 version for Debian Bookworm 12.2.0-14, I get "unable to locate package" error. Also, maybe it's possible to update the package to verison 1.20.0 for MongoDB 8.0 support?

apt install php8.4-mongodb
E: Unable to locate package php8.4-mongodb
E: Couldn't find any package by glob 'php8.4-mongodb'

`apt-cache show php8.4-fpm
Package: php8.4-fpm
Source: php8.4
Version: 8.4.1-2+0~20241121.18+debian12~1.gbpeda51a
Architecture: amd64
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 5920
Depends: media-types | mime-support, php8.4-cli, php8.4-common (= 8.4.1-2+0~20241121.18+debian12~1.gbpeda51a), php8.4-opcache, procps, systemd | systemd-tmpfiles, tzdata, ucf, libacl1 (>= 2.2.23), libapparmor1 (>= 2.7.0~beta1+bzr1772), libargon2-1 (>= 0~20171227), libc6 (>= 2.35), libpcre2-8-0 (>= 10.32), libsodium23 (>= 1.0.18), libssl3 (>= 3.0.0), libsystemd0, libxml2 (>= 2.9.4), zlib1g (>= 1:1.1.4)
Suggests: php-pear
Provides: php-fpm, php-json, php8.4-json, phpapi-20240924
Homepage: http://www.php.net/
Priority: optional
Section: php
Filename: pool/main/p/php8.4/php8.4-fpm_8.4.1-2+0~20241121.18+debian12~1.gbpeda51a_amd64.deb
Size: 1844492
SHA256: 9338a36266f0fa634aeee6fc6c9cbde2a3fa1e4c69807246dc340e21a4d4b4c1
SHA1: f7ce891c74b951c21790b9bae40695e84c5ca5a0
MD5sum: bf8aaf6a449111c9eb69df47fd955186`

**Comment by luispabon** [comment]
```
php8.4-mongodb/noble 1.20.0-1+ubuntu24.04.1+deb.sury.org+1 amd64
  MongoDB driver for PHP
```

It's definitely there, at least for Ubuntu 24.04

**Comment by needz** [comment]
@luispabon ,is there a way I can check the availability in command line? I run Debian 12.2.0-14. It's definitely there for both 8.2 and 8.3, but not 8.4.
