### ISSUE TITLE
List of missing extensions on php 8.4

### ISSUE THREAD

**Issue by luispabon** [oerdnj/deb.sury.org#2227]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**

There are a number of extensions missing that were available on 8.3:

 * php8.4-decimal
 * php8.4-grpc
 * php8.4-inotify
 * php8.4-lz4
 * php8.4-protobuf
 * php8.4-smbclient
 * php8.4-solr
 * php8.4-swoole
 * php8.4-vips
 * php8.4-xhprof
 * php8.4-zstd

**To Reproduce**
1. Install PPA on ubuntu 24.04
2. Update package lists

**Your understanding of what is happening**
Some of those extensions are quite popular, like inotify, swoole or protobuf - is it possible they aren't yet compatible with 8.4?

**Expected behavior**
Extensions are present.

**Distribution (please complete the following information):**
 - OS: Ubutu 24.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
apt policy php8.4-decimal php8.4-grpc php8.4-inotify php8.4-lz4 php8.4-protobuf php8.4-smbclient php8.4-solr php8.4-swoole php8.4-vips php8.4-xhprof php8.4-zstd
N: Unable to locate package php8.4-decimal
N: Couldn't find any package by glob 'php8.4-decimal'
N: Unable to locate package php8.4-grpc
N: Couldn't find any package by glob 'php8.4-grpc'
N: Unable to locate package php8.4-inotify
N: Couldn't find any package by glob 'php8.4-inotify'
N: Unable to locate package php8.4-lz4
N: Couldn't find any package by glob 'php8.4-lz4'
N: Unable to locate package php8.4-protobuf
N: Couldn't find any package by glob 'php8.4-protobuf'
N: Unable to locate package php8.4-smbclient
N: Couldn't find any package by glob 'php8.4-smbclient'
N: Unable to locate package php8.4-solr
N: Couldn't find any package by glob 'php8.4-solr'
N: Unable to locate package php8.4-swoole
N: Couldn't find any package by glob 'php8.4-swoole'
N: Unable to locate package php8.4-vips
N: Couldn't find any package by glob 'php8.4-vips'
N: Unable to locate package php8.4-xhprof
N: Couldn't find any package by glob 'php8.4-xhprof'
N: Unable to locate package php8.4-zstd
N: Couldn't find any package by glob 'php8.4-zstd'
```

**Comment by melroy89** [comment]
Hi sorry to interrupt you again.

But it seems you closed the ticket as completed (without comment?), however I can't still find `php8.4-inotify` under Noble?

```
sudo apt install php8.4-inotify
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php8.4-inotify
E: Couldn't find any package by glob 'php8.4-inotify'
```

I also tried looking in the [package searching feature](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=inotify&field.status_filter=published&field.series_filter=noble), no `php8.4-inotify`
