### ISSUE TITLE
Wrong description for pq extension

### ISSUE THREAD

**Issue by luispabon** [oerdnj/deb.sury.org#2228]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**

The php-pq package is incorrectly described the same as the uuid package:

```
php8.4-pq/noble 2.2.3-2+ubuntu24.04.1+deb.sury.org+1 amd64
  PHP UUID extension

php8.4-uuid/noble 1.2.0-15+ubuntu24.04.1+deb.sury.org+1 amd64
  PHP UUID extension
```

Affected:
 * 8.2
 * 8.3
 * 8.4

**To Reproduce**
n/a

**Your understanding of what is happening**
Copy-paste casualty?

**What steps did you take to resolve issue yourself before reporting it here**
n/a

**Expected behavior**
Perhaps use the summary on the [PECL page for it](https://pecl.php.net/package/pq)?

```
php8.4-pq/noble 2.2.3-2+ubuntu24.04.1+deb.sury.org+1 amd64
  PostgreSQL client library (libpq) binding
```

**Distribution (please complete the following information):**
 - OS: Ubuntu 24.04
 - Architecture: amd64
 - Repository: PPA

**Package(s) (please complete the following information):**
```
root@405f3097c5f8:/workdir# apt policy php8.4-pq
php8.4-pq:
  Installed: (none)
  Candidate: 2.2.3-2+ubuntu24.04.1+deb.sury.org+1
  Version table:
     2.2.3-2+ubuntu24.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu noble/main amd64 Packages
```

**Additional context**
n/a

**Comment by oerdnj** [comment]
Fixed, thanks.
