### ISSUE TITLE
pdo_odbc and varchar(max)

### ISSUE THREAD

**Issue by luesak** [oerdnj/deb.sury.org#223]
Hi,

Thanks for maintaining the packages for debian.

One long standing problem... That we recently encountered is this pdo_odbc problem with Microsoft SQL server.
https://bugs.php.net/bug.php?id=54169

Apparently the problem has a patch but it doesn't get wrapped into the main codebase. https://bugs.php.net/patch-display.php?bug_id=54169&patch=pdo_odbc-varchar&revision=latest

Would it be possible to make a package for PHP 5.6 and PHP 7 with this patch included? You would really help a lot of us who have to connect to MS SQL.

Thanks

Kim

**Comment by oerdnj** [comment]
Hi @luesak - since you obviously use MSSQL, could you please take a look at #226 ?
I don't have MSSQL anywhere, co it's hard for me to test anything like that.

**Comment by luesak** [comment]
I've responded... I showed how to connect to mssql but at the end he will
run into the same pdo_odbc bug as me. Please help make package as soon as
you can. Thanks

Kim

**Comment by oerdnj** [comment]
It's on the top of the queue. If it bothers you too much, you can always do:

```
cp -a ext/sybase/ /tmp/
cd /tmp/sybase/
...apply the patch...
phpize
./configure --with-pdo-dblib=/usr
make
make install
```

as a temporary remedy.

**Comment by luesak** [comment]
Haha... If I could do it I would have chipped in... I'm not sure what your
instructions mean... What is phpize? I assume you mean the file where the
code needs to be changed is in Sybase?

**Comment by oerdnj** [comment]
Fixed in `php7.0_7.0.2-2+deb.sury.org~*+1` and `php5.6_5.6.17+dfsg-2+deb.sury.org~*+1` uploads.

**Comment by luesak** [comment]
Thanks!

Kim

**Comment by luesak** [comment]
Stupid question... How do I install....

sudo apt-get install php7.0_7.0.2-2

Like that?

Which part should I change from this instructions
https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04

The repo or the install

Kim

**Comment by oerdnj** [comment]
Just wait for build to finish ("View package details" on PPA page) and then do standard `apt-get update && apt-get upgrade`

**Comment by luesak** [comment]
You mean follow everything in the digital ocean link .... And then update
like you said?

Kim

**Comment by oerdnj** [comment]
Nah, if you are doing fresh install you will get new packages automatically.

**Comment by luesak** [comment]
Thanks... I think I get it... would the co-installable and separate work
the same? Patch applied to both version?
Thanks!

Kim


__________________________________

*Luesak Luesukprasert*
Tel: +66 81 942-2737
E-mail: kim@myfamilylink.net
LineID: luesak-kim, Skype: luesak
WeChat: luesak1111, QQ: 1276375037

**Comment by oerdnj** [comment]
Yup

**Comment by luesak** [comment]
Thanks again.

Kim


__________________________________

*Luesak Luesukprasert*
Tel: +66 81 942-2737
E-mail: kim@myfamilylink.net
LineID: luesak-kim, Skype: luesak
WeChat: luesak1111, QQ: 1276375037
