### ISSUE TITLE
php7.3-redis postinst disables redis module in other installed php versions

### ISSUE THREAD

**Issue by fretb** [oerdnj/deb.sury.org#2233]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
It seems the postinstall script of php7.3-redis has a loop that disables the redis module for _each_ PHP version active on the system.

```
test-001:~# cat /var/lib/dpkg/info/php7.3-redis.postinst
#!/bin/sh
set -e

if [ "$1" = "configure" ] && [ -n "$2" ]; then
    for ver in $(phpquery -V); do
        for sapi in $(phpquery -v "$ver" -S); do
            ini="/etc/php/$ver/$sapi/conf.d/20-redis.ini"
            if [ -h $ini ]; then
                rm "$ini"
            fi
        done
    done
fi


# Automatically added by dh_php/UNDECLARED
# Hey emacs, this is -*- shell-script -*-

if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 7.3 ; do
        for name in redis ; do
            php_invoke enmod "$version" ALL "$name" || exit 1
        done
    done
else
    for name in redis ; do
        phpenmod "$name"
    done
fi
# End automatically added section

exit 0
```

Other `phpX.X-redis` packages don't have the `phpquery -V` loop at the top of the file. Is it possible this is something unwanted? 
This disabled the redis module for some other versions on some of our servers today.

I tested this on both Debian 11 and Debian 12, both distros have this issue.

```
deb11:~# apt-cache show php7.3-redis
Package: php7.3-redis
Priority: optional
Section: php
Installed-Size: 819
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Architecture: amd64
Source: php-redis-6
Version: 1:6.0.2-1+0~20241126.1+debian11~1.gbpadc546
Replaces: php-redis (<< 1:6.0.2-1+0~20241126.1+debian11~1.gbpadc546~)
Provides: php-redis
Depends: php7.3-common, php7.3-igbinary, phpapi-20180731, libc6 (>= 2.14), liblz4-1 (>= 0.0~r130), libzstd1 (>= 1.4.0)
Pre-Depends: php-common (>= 2:69~)
Suggests: redis-server
Breaks: php-redis (<< 1:6.0.2-1+0~20241126.1+debian11~1.gbpadc546~)
Filename: pool/main/p/php-redis-6/php7.3-redis_6.0.2-1+0~20241126.1+debian11~1.gbpadc546_amd64.deb
Size: 181856
MD5sum: b2447343b0253fa21cc7fa0191a48a15
SHA1: 2c849821e9a9319da7e96c8988fbd26229c5fa25

﻿deb12:~# apt-cache show php7.3-redis
Package: php7.3-redis
Priority: optional
Section: php
Installed-Size: 813
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Architecture: amd64
Source: php-redis-6
Version: 1:6.0.2-1+0~20241126.1+debian12~1.gbpadc546
Replaces: php-redis (<< 1:6.0.2-1+0~20241126.1+debian12~1.gbpadc546~)
Provides: php-redis
Depends: php7.3-common, php7.3-igbinary, phpapi-20180731, libc6 (>= 2.14), liblz4-1 (>= 0.0~r130), libzstd1 (>= 1.5.2)
Pre-Depends: php-common (>= 2:69~)
Suggests: redis-server
Breaks: php-redis (<< 1:6.0.2-1+0~20241126.1+debian12~1.gbpadc546~)
Filename: pool/main/p/php-redis-6/php7.3-redis_6.0.2-1+0~20241126.1+debian12~1.gbpadc546_amd64.deb
Size: 185112
MD5sum: 5632d0c60b32e88871417eb4ff262a9b
SHA1: 1fcf481a2840a7c48ff6840fac5404f12072c0cb
[...]
```
**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
You are right, these packages should only update the priorities for themselves. I've just uploaded `src:php-redis-4`, `src:php-redis-5`, `src:php-redis-6` and `src:php-redis` with the fix. Thanks for the report!

**Comment by oerdnj** [comment]
As a side note (for myself mostly) - next time I need to check whether there are multiple source packages as this would have been fine if everything was built from the same package.

And even better, the priority update should be made part of the `src:php-defaults` and `src:dh-php` packages, so we can update the priorities freely without needing to prepare extra `postinst` script.

**Comment by fretb** [comment]
Can't thank you enough for all your work, and swift responses!

**Comment by oerdnj** [comment]
@fretb Can you check whether all the other *-redis upgrades do what they should?

**Comment by fretb** [comment]
@oerdnj will do it tomorrow. But I have nodes that go from 5.6 to 8.4 and I only saw the faulty postint script on 7.3 pkg I think.

Will confirm tomorrow!

**Comment by oerdnj** [comment]
All `redis` packages need the new `postinst` script. The problem was that not all packages have been updated to do so. I have now done this.

**Comment by fretb** [comment]
Morning @oerdnj,

All the other *-redis packages are ok, I tested them all (5.6, 7.0, 7.1, 7.2, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4), they don't contain the `phpquery -V` loop.

Just to confirm, php7.3-redis is at this time not available anymore on your repository, right?

**Comment by oerdnj** [comment]
Argh, I just pushed the packages to the repository and forgot to push the buttons to build them for Debian. I just did that.

**Comment by fretb** [comment]
Hi @oerdnj,

I just tested upgrades on all versions, and the problem exists no more.
Thank you very much for the lightning-fast support.

As far as I'm concerned, this issue can be closed.
