### ISSUE TITLE
php8.2-redis BC break

### ISSUE THREAD

**Issue by TomCan** [oerdnj/deb.sury.org#2234]
**Describe the bug**

php8.2-redis installs `6.1.0-1+0~20241126.61+debian12~1.gbp719437` coming from `6.0.2-1+0~20231128.56+debian12~1.gbp9f3071`

This breaks applications, as the definition of Redis:hSet has changed. This results is internal server errors

`AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Symfony\\Component\\Cache\\Traits\\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false
`

It appears that this change was related to this upstream commit on the php-redis package:
https://github.com/phpredis/phpredis/commit/6ea5b3e08bdbf8cbe93e0dc56b18e8316d65097c

**Your understanding of what is happening**
The phpredis version 6.1.0 version does not appear to be BC compatible with previous 6.0.2.

**What steps did you take to resolve issue yourself before reporting it here**
Reverted to `6.0.2-1+0~20231128.56+debian12~1.gbp9f3071` using a package found in the apt cache folder of another (not yet upgraded) server.

**Expected behavior**
Packages within 8.2 branch to be BC compatible within the branch.

**Distribution (please complete the following information):**
 - OS: Debian 12
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php8.2-redis:
  Installed: 6.0.2-1+0~20231128.56+debian12~1.gbp9f3071
  Candidate: 6.1.0-1+0~20241126.61+debian12~1.gbp719437
  Version table:
     6.1.0-1+0~20241126.61+debian12~1.gbp719437 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
 *** 6.0.2-1+0~20231128.56+debian12~1.gbp9f3071 100
        100 /var/lib/dpkg/status
```

**Comment by s0xDk** [comment]
There's no problem with the package.

`hSet` signature in php-redis 6.1.0 is changed

from:
`public function hSet(string $key, string $member, mixed $value): Redis|int|false;`

to:
`public function hSet(string $key, mixed ...$fields_and_vals): Redis|int|false;`

@TomCan  So you should ask Symfony to update its `Redis6Proxy` to work with 6.1.0

**Comment by stasadev** [comment]
Duplicate of:

- #2232

And it's already solved in Symfony:

- https://github.com/symfony/symfony/issues/57884

Use `composer update`

**Comment by TomCan** [comment]
Ah missed that ticket as it was already closed.
