### ISSUE TITLE
php 8.3.14-3 fails to build on launchpad but only for Jammy amd64

### ISSUE THREAD

**Issue by elfranne** [oerdnj/deb.sury.org#2235]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
php 8.3.14-3 fails to build on launchpad but only for Jammy amd64:
https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8.3&field.status_filter=published&field.series_filter=jammy

I tried to find the logs to see the error, but the build does not produce any logs: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/29299781
On IRC #launchpad (libera.chat) it was asked to rerun the build by the support contact (pelpsi)

**Distribution:**
 - OS: Ubuntu Jammy
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Comment by oerdnj** [comment]
Weird, I've restarted the job. Thanks for noticing.
