### ISSUE TITLE
Support for Ubuntu 24.10

### ISSUE THREAD

**Issue by 1ma** [oerdnj/deb.sury.org#2242]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the solution you'd like**

I'm hitting this error on Aptitude when installing the PPA on Oracular Oriole. Are there plans to support this version? It is indeed in [Standard Support](https://wiki.ubuntu.com/Releases).

```
Err:10 https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular Release
  404  Not Found [IP: 185.125.190.80 443]
Error: The repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu oracular Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Distribution (please complete the following information):**
 - OS: Xubuntu 24.10
 - Architecture: amd64
 - Repository: ppa:ondrej/php

**Comment by oerdnj** [comment]
Yep...  https://github.com/oerdnj/deb.sury.org/issues/1662
