### ISSUE TITLE
Swoole 6.0.0 released and now supports PHP 8.4

### ISSUE THREAD

**Issue by droplinxuser** [oerdnj/deb.sury.org#2244]
**Frequently asked questions**

- [ Yes] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
Currently, I cannot use Swoole on PHP 8.4.1.

**Describe the solution you'd like**
Updating to version swoole 6.0.0 will solve the PHP 8.4 compatibility issue.

**Describe alternatives you've considered**
Dowgrading to PHP 8.3 is the quick solution.

**Distribution:**
 - OS: Ubuntu 24.04
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Additional context**
6.0.0 changelogs:
https://github.com/swoole/swoole-src/releases/tag/v6.0.0

**Comment by oerdnj** [comment]
“released 1 hour ago”, impatient are you? 🤣

I’ll update the package later today…

**Comment by droplinxuser** [comment]
Apologize for posting it that early :)

**Comment by oerdnj** [comment]
Uploaded. Just a warning, upstream dropped support for PHP 8.0
