### ISSUE TITLE
Remove debsuryorg-archive-keyring from dependencies of php-common and sury.org key from trusted.gpg.d

### ISSUE THREAD

**Issue by malamut-ubuntu** [oerdnj/deb.sury.org#2245]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
In https://packages.sury.org/php/README.txt, you correctly describe how to add non-official repositories using the signed-by option. However, your repository still installs its key to the system-wide /etc/apt/trusted.gpg.d directory when installing any PHP package (as php-common depends on debsuryorg-archive-keyring).

**Describe the solution you'd like**
1. First, remove the dependency on debsuryorg-archive-keyring from php-common. If someone wants to install keyrings via a deb package, they should be able to do so explicitly.
2. Second, remove the key from /etc/apt/trusted.gpg.d and keep it exclusively in /usr/share/keyrings/. Alternatively, if using a deb package for keyrings, it might be better to remove the signed-by option from the repository configuration. In any case, you should either use system-wide keys without the signed-by option or use custom keys with it. Currently, there is misconfiguration in README.txt.

**Describe alternatives you've considered**
The main goal is to enable explicit repository configuration, for example, using the new preferred DEB822 format. In any case, users should be able to configure the repository without adding keys globally to the system. The most secure and straightforward way is to provide either a single .sources file containing the key or two files: a .list file for /etc/apt/sources.list.d/ and a .gpg key file for /etc/apt/keyrings/ (not /etc/apt/trusted.gpg.d, as it is slightly less secure).

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: any
 - Repository: packages.sury.org

**Comment by oerdnj** [comment]
No, the dependency was was introduced, so I can change the keys as needed. I’ll eventually remove the /etc/apt keys, but there’s too much legacy systems that it will require some planning.

**Comment by malamut-ubuntu** [comment]
1. According to the README, you already ask users to install debsuryorg-archive-keyring, so there is no need to add an extra dependency. With this package, you can update your keys at any time. Currently, you simply deny managing keys without your package, and nothing more.
2. As I see it, you support only stable and old-stable distributions. You don’t need to worry about legacy systems.

**Comment by oerdnj** [comment]
You can use `equivs` package to provide an alternative package for the archive keyring if you don’t want to have the official one.

I consider the added value of per repository keys to be close to zero as any repository can install any package, so it’s all just security theatre.

**Comment by malamut-ubuntu** [comment]
Well, as you can see, I didn't mark it as a bug. Still, there are some slight security issues, especially with the key in trusted.gpg.d. There are reasons why you should use signed-by for third party repositories, even if you trust them. The main, I think, is http transport for base system repositories.

In your case anything with the keyring package and a way you configure the repository is not a huge security issue, but just a misconfiguration. It works, but you should be as accurate with keys as you can. Of course, I can do anything I want with your current system of keys, but it's confusing. I can't imagine any advantages of strict dependency on already installed keyring package (may be they exist, nevertheless), but there are a lot of small disadvantages. E.g. you can't remove it and put other packages on hold. You can put the keyring package on hold and remove its files, and you can solve other issues, sure, but it's a dirty hack.

Also, there are issues with system-wide keys in trusted.gpg.d, but more importantly, you're using signed-by and a global key simultaneously, which is also a confusing misconfiguration.

My main goal is just to point that security configuration should be as clear as possible, but currently it has some understandable, but unnecessary and strange things.
