### ISSUE TITLE
PHP5.6 mssql

### ISSUE THREAD

**Issue by cybear-d** [oerdnj/deb.sury.org#226]
When installing php5.6-sybase package, the mssql module is not loaded, so i cannot using mssql function from php.
i'm using ubuntu 15.10 amd64 and trying install php5.6 with mssql support

**Comment by luesak** [comment]
Did you make the debian package with the patch? I can add the PPA and then test the package.

Thanks

Kim

**Comment by luesak** [comment]
I'm sorry I was mistaken... The problem is you need to use pdo odbc with either FreeTDS or MSSql ODBC driver version 13 with Unix ODBC 2.3.1.... Having said that you will run into problem #223 if you connect to mssql via ODBC because of the bug in the pdo_odbc module.

**Comment by oerdnj** [comment]
Ah, right, the non-PDO version of the module has been removed.

**Comment by cybear-d** [comment]
i'm already using FreeTDS, but as you said i'm using mssql module, not the pdo one and i don't know the non-PDO version has been removed.

thanks for your response.

**Comment by luesak** [comment]
That is correct.

Kim

**Comment by oerdnj** [comment]
@cybear-d I am trying to keep the PHP 5.6 and PHP 7.0 as close as possible. Please keep using php5-sybase if you need old interfaces. php5-* and php7.0-* packages should be co-installable right now.
