### ISSUE TITLE
Issue installing PHP7 on Trusty

### ISSUE THREAD

**Issue by danpurpura** [oerdnj/deb.sury.org#227]
This had been working with `7.0.2-1*`, but `7.0.2.-2*` seems to have missed updating `php7.0-common`: 

` php7.0-cli : Depends: php7.0-common (>= 7.0.2-2+deb.sury.org~trusty+1) but 7.0.2-1+deb.sury.org~trusty+1 is to be installed`

**Comment by oerdnj** [comment]
Patience
