### ISSUE TITLE
php5dbg canot be installed in the latest upgrade

### ISSUE THREAD

**Issue by stof** [oerdnj/deb.sury.org#228]
I'm on Ubuntu 14.04 (using the PPA). This is the error I'm getting from ``apt-get upgrade`` today:

```
Paramétrage de php5-phpdbg (5.6.17+dfsg-2+deb.sury.org~trusty+1) ...
dpkg: error processing package php5-phpdbg (--configure):
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 php5-phpdbg
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I don't know whether there is a way to get more info about the error (I have no experience debugging apt-get errors)

**Comment by oerdnj** [comment]
For immediate fix edit /usr/share/php5/php5-maintscript-helper and add `|phpdbg` just after `...|embed` in the `case` condition. Otherwise just wait for current fixed build to finish.
