### ISSUE TITLE
[php7.0 + Xdebug v2.4.0RC3] segfault when running PHPUnit with code coverage

### ISSUE THREAD

**Issue by AntonStoeckl** [oerdnj/deb.sury.org#229]
``` bash
PHP 5.6.17-2+deb.sury.org~wily+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
```

This causes as segfault when PHPUnit is run with code coverage.
When switching to 5.6 with update-alternatives, with same version of Xdebug, it works fine.

**Comment by oerdnj** [comment]
Could you retry with manually compiled xdebug 2.4.0RC4-dev from git? I think I've heard something similar already. In any case this is not a packaging bug per se and needs to be reported to xdebug upstream.

**Comment by oerdnj** [comment]
`xdebug_2.4.0~rc4-1+deb.sury.org~*+1` has been uploaded to PPA, I suspect this will solve your issue. If not, please open an issue with upstream (https://bugs.xdebug.org/my_view_page.php).

**Comment by AntonStoeckl** [comment]
Hi Ondřej,

sorry for forgetting to compile it myself. :-(
Thx for the new version with xdebug RC4, sadly it does not solve the problem.

I'll open an upstream issue then!

**Comment by oerdnj** [comment]
Also see here: https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1522422/comments/41

**Comment by oerdnj** [comment]
@AntonStoeckl Did you open the bug with upstream? Could you paste the link here for reference?

**Comment by AntonStoeckl** [comment]
https://bugs.xdebug.org/view.php?id=1263

**Comment by oerdnj** [comment]
@AntonStoeckl Did the crash got fixed with 2.4.0 release of xdebug? (The upstream bug is silent.)

**Comment by AntonStoeckl** [comment]
No, still segfault.

**Comment by oerdnj** [comment]
@AntonStoeckl Just checking whether PHP 7.0.5 and xdebug 2.4.0 is fine?

**Comment by AntonStoeckl** [comment]
Hi Ondrej,

on my Ubuntu 15.10 after last apt-get upgrade, with installed php-xdebug there is no xdebug.so file on my system. Already purged and re-installed with no difference, xdebug.so is missing.

If a look at "installed files" in synaptic it indeed shows not xdebug.so for 2.4.0-2+deb.sury.org~wily+2

Trying to find out if it's some weird hickup on my system, but does not seem so.

**Comment by oerdnj** [comment]
Nope, that's the effect of unification of the build system, but src package named xdebug instead of php-xdebug. Hopefully fixed in +3 that I just uploaded.

**Comment by oerdnj** [comment]
I updated build rules for 29 packages today, so this slipped my attention. Thanks for the report.

**Comment by oerdnj** [comment]
@AntonStoeckl Try updating now. Looks like the +3 is already built, but not yet published, but you can download the .deb from here: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/9661357

**Comment by AntonStoeckl** [comment]
This build of xdebug is fine, but still no success with coverage, still segfaulting when opcache is enabled, without opcache it works.

**Comment by pavarnos** [comment]
Hi. xdebug 2.41 is released with a fix for the opcache issue. https://xdebug.org/updates.php. Would it be possible to have a new build of xdebug to the latest version in the ubuntu ppa?
Thanks so much for all you do.
