### ISSUE TITLE
MongoDb configuration file incorrect

### ISSUE THREAD

**Issue by carnage** [oerdnj/deb.sury.org#230]
/etc/php/7.0/fpm/conf.d/20-mongodb.ini has:

zend_extension=mongodb.so 

it should read:

extension=mongodb.so

**Comment by oerdnj** [comment]
Thanks. I already fixed this, but I switched to system libbson and libmongoc, and libbson failed to build for some reason.

**Comment by oerdnj** [comment]
@carnage Could you please try the new mongodb extension (`php-mongodb_1.1.2-2+deb.sury.org~*+2`) from ppa:ondrej/php? It's not compiled with external libmongoc library with some extra private symbols, so it might be broken (although the extension loads fine).

The `zend_extension` typo is fixed as well.
