### ISSUE TITLE
php 56 unable to load dynamic library amqp.so

### ISSUE THREAD

**Issue by slimus** [oerdnj/deb.sury.org#233]
Hi!

I was install php 56 over your ppa and got this error:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/amqp.so' - /usr/lib/php5/20131226/amqp.so: cannot open shared object file: No such file or directory in Unknown on line 0

I need php5-aqmp module for my project.

**Comment by oerdnj** [comment]
What version of php-amqp do you have installed?

**Comment by oerdnj** [comment]
Pasting output of `apt-cache policy <packagename>` would be the best.

**Comment by slimus** [comment]
Sorry, it's my mistake.
There was old package from "main" repo. I re-compile aqmp from pecl and will be problem fixed. 
Thanks.
