### ISSUE TITLE
Warning: apc_clear_cache() expects exactly 1 parameter, 0 given

### ISSUE THREAD

**Issue by partounian** [oerdnj/deb.sury.org#234]
In the documentation, apc_clear_cache should be fine accepting no parameters, and I've this fixed on newer versions of apcu, could you run a new build for php-apcu?

**Comment by oerdnj** [comment]
`php-apcu_5.1.3+4.0.10-1+deb.sury.org~*+1` has been uploaded to PPAs.

**Comment by partounian** [comment]
Sorry, my mistake, but I realized this issue is related to apcu-bc not apcu. Whenever you're running a new build could you also run apcu-bc? Thank you for all of your contributions to the community,

**Comment by oerdnj** [comment]
php-apcu-bc_1.0.1 also uploaded.
