### ISSUE TITLE
[PHP 5.6] Unable to load dynamic library libsmbclient.so

### ISSUE THREAD

**Issue by enoch85** [oerdnj/deb.sury.org#235]
Just want to start with saying - thanks a lot for your efforts!

I recently installed PHP 5.6 on Ubuntu 14.04 Server, and when installing `php5-libsmbclient` I get this error when I ask for PHP version with `php -v`:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/libsmbclient.so' - /usr/lib/php5/20131226/libsmbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

Don't know if this is a know issue, but I thought I would report it. Is there any fix available? 

**Additional info**
```
root@owncloud:~# apt-cache policy php5-libsmbclient
php5-libsmbclient:
  Installed: 0.5.0-1.1
  Candidate: 0.5.0-1.1
  Version table:
 *** 0.5.0-1.1 0
        500 http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  Packages
        100 /var/lib/dpkg/status

root@owncloud:~# ll /usr/lib/php5/20131226/
curl.so        imap.so        json.so        mcrypt.so      mysql.so       pdo_mysql.so   pdo.so         pgsql.so       sqlite3.so     
gd.so          intl.so        ldap.so        mysqli.so      opcache.so     pdo_pgsql.so   pdo_sqlite.so  readline.so    

root@owncloud:~# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/libsmbclient.so' - /usr/lib/php5/20131226/libsmbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.17-3+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

```

**Comment by enoch85** [comment]
@jnwieger as there is a 500 error on ownClouds server.

**Comment by oerdnj** [comment]
@enoch85 Could you attach output of `dpkg -L php5-libsmbclient` and `apt-cache show php5-libsmbclient`? I suspect the php5-libsmbclient is compiled against different PHP version and doesn't properly declare dependency on PHPAPI version.

**Comment by enoch85** [comment]
@oerdnj 

```
ocadmin@owncloud:~$ dpkg -L php5-libsmbclient
/.
/usr
/usr/lib
/usr/lib/php5
/usr/lib/php5/20121212
/usr/lib/php5/20121212/libsmbclient.so
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/php5-libsmbclient
/usr/share/doc
/usr/share/doc/php5-libsmbclient
/usr/share/doc/php5-libsmbclient/copyright
/usr/share/doc/php5-libsmbclient/changelog.Debian.gz
/usr/share/php5
/usr/share/php5/libsmbclient
/usr/share/php5/libsmbclient/libsmbclient.ini

ocadmin@owncloud:~$ apt-cache show php5-libsmbclient
Package: php5-libsmbclient
Version: 0.5.0-1.1
Architecture: amd64
Maintainer: Jürgen Weigert <jw@owncloud.com>
Installed-Size: 93
Depends: libc6 (>= 2.14), libsmbclient (>= 2:4.0.3+dfsg1), php5 (>= 5.3.3)
Filename: ./amd64/php5-libsmbclient_0.5.0-1.1_amd64.deb
Size: 13270
MD5sum: 4d7bd4f946d625bda9c4eb52b1184ea9
SHA1: a33a030c69e7d248177b61b03aa4ea43cf053f27
SHA256: 4316056cc4aa97ea6dd2cdb2683552b6ac1f7e77b3aff88f7ad6f805c2997ee2
Section: devel
Priority: optional
Description: libsmbclient-php is a PHP extension that uses Samba's libsmbclient
 library to provide Samba related functions to PHP programs.
 See also: https://github.com/eduardok/libsmbclient-php/blob/master/README.md
Description-md5: 64047e55b33ca49507d836a83010c48d
```

**Comment by oerdnj** [comment]
Thanks as I suspected the package is broken as it *has* to declare dependency on `phpapi-20121212` and it doesn't (instead of the `php5 (>= 5.3.3)` that just can't work). Fill a bug with upstream to properly package that.

JFTR I really dislike people packaging random stuff without even trying to get the proper package to Debian. That doesn't apply only for PHP packages. If you take, and use others work, you should contribute back.

I'll investigate if 0.8.0RC1 supports PHP 7.0 and properly package it if it does.

Meanwhile I would recommend install `php5-dev` package and doing `pecl install smbclient` instead of using that broken package.

**Comment by enoch85** [comment]
Thanks @oerdnj! As always you save the community. Donated some time ago actually :)

I will report it upstream. Feel free to close this issue.

**Comment by oerdnj** [comment]
php-smbclient_0.8.0~rc1 has been uploaded to ppa:ondrej/php; I won't be packaging new stuff for the old repositories, so it will help you only if you can switch to php5.6-fpm or php7.0-fpm as your primary PHP engine.

**Comment by enoch85** [comment]
Just to be clear, the ppa:ondrej/php is containing PHP7 right? Not PHP7-FPM?

The FPM stuff isn't optimal for me.

**Comment by jnweiger** [comment]
@oerdnj It is easy for me to contribute back by submitting packages to the openSUSE Build Service, or to prepare pull requests at github. I am a newbie to debian packaging, and have not yet investigated how upstream packages are built for debian/ubuntu.

I checked the rules file, and found, that for most other php packages, I have
``echo "php:Depends=phpapi-$$(php-config5 --phpapi)" >> $(CURDIR)/debian/substvars``
but this was missing in php5-libsmbclient. Hope adding this makes it less 'broken'.

**Comment by oerdnj** [comment]
@enoch85 sure, contains full set of packages.

**Comment by oerdnj** [comment]
@jnweiger please ask next time you need to package something, ok? And yes, the phpapi-<ver> was missing and adding it would help.
