### ISSUE TITLE
phpenmod doesn't work without -v and -s flags?

### ISSUE THREAD

**Issue by nicwortel** [oerdnj/deb.sury.org#236]
Hello,

First of all, thank you for maintaining this PPA.

I believe I have found a bug in the `phpenmod` en `phpdismod` executables. It appears that they only work when I provide both the `-v` and the `-s` flag, even though the 'usage' hint shows them as optional.

So for example, running `phpenmod -v ALL -s ALL intl` works fine (creates a symlink to the intl config file), but the shorter version `phpenmod intl` does nothing.

I am not very familiar with bash scripting, but I think this could be solved by replacing lines 228 and 229:

```
versions=
sapis=
```
with:
```
versions=ALL
sapis=ALL
```

I would send you a pull request, but it seems like this file is not on GitHub.

**Comment by oerdnj** [comment]
Good catch. Your proposed patch would make the script fail every time :) (see L236), but this patch should do:
```
diff --git a/phpenmod b/phpenmod
index 13224b0..a72c366 100755
--- a/phpenmod
+++ b/phpenmod
@@ -258,6 +258,10 @@ for mod in $@; do
     mods="${mods}${mods:+ }${mod%%/*}"
 done
 
+# If -v or -s was not specified run on every version and every SAPI
+[ -z "$versions" ] && versions=ALL
+[ -z "$sapis"    ] && sapis=ALL
+
 [ -z "$mods" ] && usage
 
 case "${SCRIPT_NAME}" in
```

Could you please do me a favor and test it whether it works as expected for you, before I do the upload?

**Comment by nicwortel** [comment]
:+1: it works perfectly!

`phpenmod intl`, `phpenmod -v ALL intl`, `phpenmod -v 7.0 intl`, `phpenmod -s ALL intl`, `phpenmod -s cli intl`, `phpenmod -v ALL -s ALL intl`... and the same with `phpdismod`... everything I can think of seems to work :smile:

**Comment by oerdnj** [comment]
Fixed in `php-defaults_24+deb.sury.org~*+1` and `php-defaults_24+coinst+deb.sury.org~*+1`
