### ISSUE TITLE
Use upstream openssl

### ISSUE THREAD

**Issue by smereczynski** [oerdnj/deb.sury.org#237]
Hi,
Your build of openssl in php5-56 repository for 14.04 is different than the upstream one from 16.04  (also 1.0.2e). It causes a compatibility issues for other software - like OMS Agent for Linux (https://github.com/Microsoft/OMS-Agent-for-Linux). It works OK with upstream "OpenSSL 1.0.1f" and upstream OpenSSL 1.0.2e (on 16.04) but fails with Your build. Probably because of -no-ssl3.

**Comment by oerdnj** [comment]
Care to provide any details at all? You don't have to use neither the library nor the development package if you don't want it. Just use apt pinning.

**Comment by smereczynski** [comment]
If You want some details we had and issue about that here: https://github.com/Microsoft/OMS-Agent-for-Linux/issues/14. I know that I can pin version of the package but I just wanted to give You a signal about this case. If user will do dist-upgrade with Your repo then openssl will be upgraded. Many users do that so maybe it's good idea to use openssl compiled as the mainline (16.04) version is.

**Comment by oerdnj** [comment]
That's OMS-Agent-for-Linux that needs to be fixed. Or just don't mix production and developement/build environments.
