### ISSUE TITLE
Bayesian Spam Filters

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#238]
I have been using Dspam with great success for years but the last few Ubuntu versions have dropped it because the upstream project seems unmaintained and no longer compiles. For the last year I've tried to replace Dspam with Bogofilter and it does a reasonable (to be kind) job and just recently, out of desperation to find something better, I tried out SpamProbe. On my main test server, which gets plenty of spam, it is struggling to identify spam at all but it may be due to my lack of understanding and pre-training causing the problem.

Two points; I notice you provide the SpamProbe package and one of it's recomends is maildrop but because I am using courier-maildrop, when I went to install spamprobe it wanted to install postfix so perhaps you could add courier-maildrop to the next package update.

As I mentioned I have had no luck with testing spamprobe so I can't judge it properly yet but there is no doubt in my mind that Dspam is by far and away a better bayesian filter than bogofilter. Bogofilter can get to be 95% effective with decent training but Dspam will work well almost immediately with no pre-training and get to ~95% within a few 100 messages and then 99% effective with ~3000 messages and can get to 99.9% after that with diligent training.

I really miss Dspam. Is there any chance you could look at reviving it please? Name your price.

**Comment by oerdnj** [comment]
I just fixed FTBFS with recent Berkeley DB in SpamProbe.

As for DSPAM: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754810

> As annoying as it is for all its users (and I'm one of them) it's best
> to make it clear that dspam is no longer supported. For the past 2 years
> I've been stacking patches to fix security issues and serious bugs and I
> can't imagine another release cycle like this, with no hope of any patch
> being merged.

It doesn't seem like a good idea to run DSPAM at all. And this:

https://sourceforge.net/p/dspam/mailman/message/32585111/

also doesn't fill me with hope.

Sorry.
