### ISSUE TITLE
Zend OPcache

### ISSUE THREAD

**Issue by majksner** [oerdnj/deb.sury.org#24]
Hi, there is a issue with Zend OPcache. When it's freshly installed it works fine, it loads module and caching works, but when upgrade is available for sury packages it stops working after packages are upgraded and installation is finished.

This can be possible cause https://github.com/zendtech/ZendOptimizerPlus/issues/188

`php -i`

Throws this error
```
*** Error in `php': free(): invalid pointer: 0x00007f53567d2b30 ***
Segmentation fault (core dumped)
```

And under ZendOPcache is this

```
Zend OPcache

Opcode Caching => Disabled
Optimization => Disabled
```

Only building virtual machine from scratch can help. Reboot does not.

PHP Version installed is 5.5.17

Thanks,

**Comment by oerdnj** [comment]
This is an upstream bug and not a packaging bug, thus I am closing the issue.
