### ISSUE TITLE
[php-7.0] Cannot load Zend OPcache - it was already loaded

### ISSUE THREAD

**Issue by dnmvisser** [oerdnj/deb.sury.org#245]
Just saw this message appeared after upgrading to 7.0.3 when running from CLI.

visser@cajones:~$ php -v
Cannot load Zend OPcache - it was already loaded
PHP 7.0.3-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

This also causes sessionclean cron jobs to suddenly create output, so I get two of these every hour:

Subject: Cron <root@cajones>   [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean

Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded

**Comment by oerdnj** [comment]
`grep -r opcache /etc/php` looks normal? Could you attach the output of that?

**Comment by ConteZero** [comment]
I have the same problem after upgrade.
This is the content of /etc/php/7.0/fpm/conf.d
lrwxrwxrwx 1 root root 35 Feb  6 09:57 10-opcache.ini -> /etc/php/mods-available/opcache.ini
lrwxrwxrwx 1 root root 32 Dec 22 17:05 20-curl.ini -> /etc/php/mods-available/curl.ini
lrwxrwxrwx 1 root root 30 Dec 22 17:05 20-gd.ini -> /etc/php/mods-available/gd.ini
lrwxrwxrwx 1 root root 32 Dec 22 17:05 20-json.ini -> /etc/php/mods-available/json.ini
lrwxrwxrwx 1 root root 34 Dec 22 17:05 20-mysqli.ini -> /etc/php/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 35 Dec 22 17:05 20-opcache.ini -> /etc/php/mods-available/opcache.ini
lrwxrwxrwx 1 root root 37 Dec 22 17:05 20-pdo_mysql.ini -> /etc/php/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 36 Dec 22 17:05 20-readline.ini -> /etc/php/mods-available/readline.ini

The update added 10-opcache.ini but 20-opcache.ini was already here so it try to load the plugin twice.

**Comment by ConteZero** [comment]
The same thing happens in /etc/php/7.0/cli/conf.d
lrwxrwxrwx 1 root root 35 Feb  6 09:57 10-opcache.ini -> /etc/php/mods-available/opcache.ini
lrwxrwxrwx 1 root root 32 Dec 22 17:05 20-curl.ini -> /etc/php/mods-available/curl.ini
lrwxrwxrwx 1 root root 30 Dec 22 17:05 20-gd.ini -> /etc/php/mods-available/gd.ini
lrwxrwxrwx 1 root root 32 Dec 22 17:05 20-json.ini -> /etc/php/mods-available/json.ini
lrwxrwxrwx 1 root root 34 Dec 22 17:05 20-mysqli.ini -> /etc/php/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 35 Dec 22 17:05 20-opcache.ini -> /etc/php/mods-available/opcache.ini
lrwxrwxrwx 1 root root 37 Dec 22 17:05 20-pdo_mysql.ini -> /etc/php/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 36 Dec 22 17:05 20-readline.ini -> /etc/php/mods-available/readline.ini

**Comment by oerdnj** [comment]
Ah, yes. The fix for extension priorities broke this. It's fairly easy to fix, I'll fix that on Monday (or during the weekend if I find some free time).

**Comment by oerdnj** [comment]
Just delete the 20-opcache.ini meanwhile: `find /etc/php -name 20-opcache.ini -delete`

**Comment by dnmvisser** [comment]
I'll do that, thanks for quick response.



On Saturday, 6 February 2016, Ondřej Surý <notifications@github.com> wrote:

> Just delete the 20-opcache.ini meanwhile: find /etc/php -name
> 20-opcache.ini -delete
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oerdnj/deb.sury.org/issues/245#issuecomment-180734041>
> .
>


-- 
Sent from Gmail Mobile

**Comment by oerdnj** [comment]
I have just uploaded 7.0.3-2, that should have a fix (but I haven't been able to test it, so crossed-fingers here).

**Comment by oerdnj** [comment]
@ConteZero @dnmvisser It would be great if either of one could test upgrade path from `7.0.3-1` to `7.0.3-2` without removing `20-opcache.ini` by hand, just to confirm the postinst code works as expected.

**Comment by ConteZero** [comment]
Unfortunately I already removed 20-opcache.ini

**Comment by dnmvisser** [comment]
I was in a hurry this morning so I just commented out the line in
/etc/cron.d/php to get rid of the mails.
So I didn't remove 20-opcache.ini.
I just upgraded the two boxes that run php7 and they were nicely removed.

Thanks again for swift action, much appreciated.

Dick

**Comment by ConteZero** [comment]
I've re-added the symlink to 20-opcache.ini , upgraded to 7.0.3-2 and 20-opcache.ini was removed, so the upgrade fixed the problem.
Thanks for your work.
