### ISSUE TITLE
Apache 2.4 not properly installed on Ubuntu 12.04

### ISSUE THREAD

**Issue by sm8ps** [oerdnj/deb.sury.org#248]
I added ppa:ondrej/php5 and did ''apt-get dist-upgrade''. The upgrade process choked on the installation of '/usr/share/man/man8/apache2.8.gz' (messages translated to english):

`Unpacking apache2-bin (from .../apache2-bin_2.4.16-4+deb.sury.org~precise+4_amd64.deb) ...
dpkg: error while handling /var/cache/apt/archives/apache2-bin_2.4.16-4+deb.sury.org~precise+4_amd64.deb (--unpack):
 Trying to over-write »/usr/share/man/man8/apache2.8.gz« which also is contained in package apache2.2-common 2.2.22-1ubuntu1.10 ist
                                                                                   dpkg-deb (sub-process): sup-process data was killed by signal (Broken pipe)
dpkg-deb: Error: sub-process <Dekompression> returned error code 2`

The remainder of the upgrade process seems to go well; it includes the following:

`The following packages are REMOVED:
  apache2-mpm-prefork apache2.2-bin apache2.2-common
The following NEW packages are installed:
  apache2-bin apache2-data bsdmainutils build-essential debhelper dh-apparmor dh-php5 dpkg-dev
  fakeroot g++ g++-4.6 gettext gettext-base groff-base html2text intltool-debian
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libdpkg-perl libgd3
  libgettextpo0 libicu52 libjson-c2 liblua5.1-0 libmail-sendmail-perl libonig2 libpipeline1
  libqdbm14 libssl1.0.2 libstdc++6-4.6-dev libsys-hostname-long-perl libunistring0 libvpx1 lsof
  man-db owncloud-config-apache owncloud-server patch php5-apcu php5-json php5-ldap php5-readline
  pkg-php-tools po-debconf
The following packages are updated (Upgrade):
  apache2 apache2-utils libapache2-mod-php5 libapache2-mod-xsendfile libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libbsd0 libedit2 libjson0 libssl-dev libssl-doc
  openssl owncloud php-apc php-pear php5 php5-cli php5-common php5-curl php5-dev php5-gd
  php5-imagick php5-intl php5-mcrypt php5-mysql php5-pgsql php5-sqlite`

Sorry for the messy lay-out! Cannot seem to format terminal output as code snippets correctly.

**Comment by sm8ps** [comment]
This is what I get from a renewed ''apt-get dist-upgrade'':

`The following packages have unresolved dependencies:
 libapache2-mod-php5 : depends on: apache2-api-20120211
                       depends on: apache2 (>= 2.4)
                       depends on: php5-common (= 5.5.32+dfsg-1+deb.sury.org~precise+1) but 5.3.10-1ubuntu3.21 is installed
 libapache2-mod-xsendfile : depends on: apache2-api-20120211
E: unresolved dependencies. Try using -f.`

Also PHP still is on 5.3.

`$ php -v
PHP 5.3.10-1ubuntu3.21 with Suhosin-Patch (cli) (built: Oct 28 2015 01:43:56) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies`

**Comment by oerdnj** [comment]
Remove apache2 first before installing, or preferably upgrade to something that isn't 4 years old, f.e. Ubuntu 14.04.

I am removing support for Ubuntu Precise in PHP 5.5 and PHP 5.6 in few weeks anyway.

**Comment by sm8ps** [comment]
You certainly are right but I want to be holding out until 16.04 is out if possible but I still need to make PHP 5.4+ available now. Thanks for your efforts anyways!

**Comment by oerdnj** [comment]
`apt-get -f install` has the ability to return your system to a saner state, then `apt-get --purge remove apache2.2-common` and only after that try install updated PHP version. Hope you are doing this in a test environment first.

Yeah, I'll be closing the support for Ubuntu 12.04 after Xenial is out, and I just can't wait. It's hard to support such an old version when the world has turned several times now.
