### ISSUE TITLE
[PHP 5.6] Request: upgrade php-imagick package to latest stable release

### ISSUE THREAD

**Issue by Mav** [oerdnj/deb.sury.org#249]
I've been using the PPA for PHP 5.6 and it would be great if php-imagick could be upgraded to the latest stable release 3.3.0 released last December. Current version is from 2013. - https://pecl.php.net/package/imagick

I noticed the PHP 7 PPA does have the 3.4.0 betas of php-imagick but I can't switch to PHP 7 just yet.

I've already tried to just upgrade it via PECL but it gives a configuration error that way and I haven't been able to solve it.

**Comment by oerdnj** [comment]
Fixed in `php-imagick_3.3.0-1+deb.sury.org~*+1`

**Comment by Mav** [comment]
I see it's updated on the launchpad list, but the PPA sources doesn't seem to have been updated? I figured it was cached and takes a day or so to update, but it's been a few days now.

If you go directly to the source at http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/ - it shows it was last updated on Feb 16th (before this upgrade) and php-imagick is still 3.1.2-1.1 in those packages files. So when using apt-get it can't find the new version.

**Comment by oerdnj** [comment]
@Mav What Ubuntu release are you using, and what does: `apt-cache policy php5-imagick` say?

**Comment by oerdnj** [comment]
Never mind, the packages silently failed to build because of:
> Missing build dependencies: libmagickwand-6.q16-dev

**Comment by oerdnj** [comment]
@Mav It should be ok now.

**Comment by Mav** [comment]
Yes, it's working now. Thanks a lot!
