### ISSUE TITLE
PHP 7 ZMQ

### ISSUE THREAD

**Issue by scragg0x** [oerdnj/deb.sury.org#250]
Any plans adding this package to the PPA?  Zmq has a working PHP7 branch via github.  That is the only why I know how to build the extension.

**Comment by oerdnj** [comment]
I don't have any "plans" on PECL extensions, then come on request basis, so if this is really a packaging request then it will happen if there's official git repository with working code.

**Comment by scragg0x** [comment]
This is a packaging request.  Here is the git repo with working code:
https://github.com/mkoppanen/php-zmq/tree/php7

Pecl:
http://pecl.php.net/package/zmq/1.1.3

Your PHP5.5 ppa has this extension but main PHP ppa does not.

**Comment by oerdnj** [comment]
Uploaded as `php-zmq_1.1.3-1+deb.sury.org~*+1`
