### ISSUE TITLE
use dsoname instead of module when building extension ini files

### ISSUE THREAD

**Issue by mvrhov** [oerdnj/deb.sury.org#253]
If the dsoname is used in script that means if there are multiple extensions in a single package an one needs to be loaded before the other you can set the priority and extension based on a specific extension.
```patch
@@ -426,9 +416,9 @@
 	  modules=$$(eval echo \$${$${module}_EXTENSIONS}); \
 	  description=$$(eval echo \$${$${module}_DESCRIPTION}); \
 	  for dsoname in $${modules}; do \
-	    priority=$$(eval echo \$${$${module}_PRIORITY}); \
+	    priority=$$(eval echo \$${$${dsoname}_PRIORITY}); \
 	    if [ -z "$${priority}" ]; then priority=20; fi; \
-	    extension=$$(eval echo \$${$${module}_EXTENSION}); \
+	    extension=$$(eval echo \$${$${dsoname}_EXTENSION}); \
 	    if [ -z "$${extension}" ]; then extension=extension; fi; \
 	    mkdir -p debian/tmp/usr/share/$${package}/$${module}/; \
 	    $(SED) -e "s,@extname@,$${module}," \
```

**Comment by oerdnj** [comment]
Do you have a real use case?

**Comment by mvrhov** [comment]
I our case we package the 
* optimizer in commons package 
* mysqlnd as a shared in mysql package
* we use a static build of sqlite, so sqlite needs to be loaded before pdo_sqlite
Also as said in another issue, it would be nice if mysqlnd would be a part of mysql package.

This would also mean that I have to track less changes with upstream package

**Comment by oerdnj** [comment]
Make sense; commited to git
