### ISSUE TITLE
pacakge some of the extensions into the common package

### ISSUE THREAD

**Issue by mvrhov** [oerdnj/deb.sury.org#254]
Some packages like: soap, mbstring, phar, could be packaged inside a commons package this would result in a smaller executables for cgi,fpm,cli,apache and emmbeded.
I also don't see a reason with DBA having been compiled in, I don't know anyone using that so it could a separate package.
On the other hand I'm wondering why the json is a separate package as everybody uses it so it could be compiled in.

I have patches for the 1rst two if interested.

**Comment by oerdnj** [comment]
How much are you going to save in the memory? Or is this just a premature optimalization?

**Comment by mvrhov** [comment]
We prefer smaller executables and smaller downloads. It also alows someone to disable some of the packages.

Also there is no need to have mysqlnd compiled in as not everyone uses mysql, it would be a better if it would have been compiled as a shared an packaged with php-mysql libs.

**Comment by mvrhov** [comment]
Oh another thing it seems that the common build section is missing --with-zlib.. this means that there is no support for zlib compiled in. I'm wondering how nobody else figured this out :P

**Comment by oerdnj** [comment]
So, premature optimalization. Hard numbers are going to convince me, not what do you or do you not prefer.

Good catch with zlib though.

**Comment by oerdnj** [comment]
Moving mysqlnd to mysql has been done in git, it was an leftover from previous work. Moving dba to separate package make sense as well, since it pulls unnecessary runtime dependency (libqdbm).
For rest I would have to see hard numbers - how much non-shared memory do you save by moving each extension out of the core SAPIs. Fill a bug per extensions to be moved out with the numbers.

**Comment by oerdnj** [comment]
If you have said that FPM would go down from 9844104 to 3775816 bytes, I would be convinced in the first place. `php7.0_7.0.3-6` and `php5.6_5.6.18+dfsg-5` contains the changes. Only hash, libxml, openssl, pcre and session remains built-in extensions.

**Comment by mvrhov** [comment]
Sorry I thought that smaller executables caught you. Without me presenting the file size numbers.
Nice to hear that.

**Comment by oerdnj** [comment]
Smaller binaries on their own are useless (unless you run in really constrained environment). Smaller memory footprint is what matters.
