### ISSUE TITLE
compiling pecl extensions.

### ISSUE THREAD

**Issue by mvrhov** [oerdnj/deb.sury.org#255]
I have some experiences in building and repackaging original packages so they suit our needs and to build newer versions. but it seems that I'm unable to rebuild any new pecl package.

This is the tree structure.
\compile\php\<extracted tar.orig>
then I copy the debian directory into the <extracted tar.orig>
and run `debuild -S -uc -us` in the same directory. this worked and also works for all packages but when building the new pecl extensions it errors out with
```
 dpkg-buildpackage -rfakeroot -d -us -uc -S
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package php-xdebug
dpkg-buildpackage: source version 2.4.0-1.pi
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by Miha Vrhovnik <>
 dpkg-source --before-build xdebug-2.4.0RC4
 fakeroot debian/rules clean
ls: cannot access xdebug-*: No such file or directory
/bin/sh: 1: /usr/sbin/phpquery: not found
dh clean --with php --sourcedirectory=
   dh_testdir -O--sourcedirectory=
   debian/rules override_dh_auto_clean
ls: cannot access xdebug-*: No such file or directory
/bin/sh: 1: /usr/sbin/phpquery: not found
make[1]: Entering directory `/compile/php/xdebug-2.4.0RC4'
for v in ; do \
          dh_auto_clean --builddirectory=/compile/php/xdebug-2.4.0RC4/build-$v --sourcedirectory=; \
          rm -rf /compile/php/xdebug-2.4.0RC4/build-$v; \
        done
cd  && phpize --clean
Cannot find config.m4.
Make sure that you run '/usr/bin/phpize --clean' in the top level source directory of the module

make[1]: *** [override_dh_auto_clean] Error 1
make[1]: Leaving directory `/compile/php/xdebug-2.4.0RC4'
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -d -us -uc -S failed
```
P.S. Then I build the package with `DIST=trusty ARCH=amd64 pbuilder build <pkg>.dsc`

**Comment by oerdnj** [comment]
You are missing build-deps installed - you need to have php-all-dev and dh-php installed at least. Please don't open bugs for user help issues, we have askubuntu.com and other forums for that.

**Comment by mvrhov** [comment]
I think its a specific php packaing problem that's why I asked here as like I said I never had problems before.
It's not a problem in php-all-dev and dh-php. 
The problem is in this line `ls: cannot access xdebug-*: No such file or directory`. I don't understand this. there is xdebug-* directory I level above the debian directory.

**Comment by oerdnj** [comment]
So if you know better, then why are you asking here? I already gave you the correct answer, your build machine has broken build deps.

**Comment by mvrhov** [comment]
What I meant was that the main problem lies with `SOURCE_DIR   := $(shell ls -1d $(PECL_NAME)-*)
` inside a rules file which results in SOURCE_DIR being blank the error message being `ls: cannot access xdebug-*: No such file or directory`. And thus all further run commands fail.
I run `debuild -S -uc -us` from  `/compile/php/xdebug-2.4.0RC4/` like for other packages.

**Comment by oerdnj** [comment]
Then it's not your build deps, but your build environment that is obviously broken as it can be seen from the build log in the first post. But as I said this is not "how to debug my packaging" support forum. There's nothing wrong with the package.

Hint: it's the next line in the build log that's important. Fix that and the package will build just fine.
