### ISSUE TITLE
MySQL module broken? 7.0.3-6+deb.sury.org~wily+2

### ISSUE THREAD

**Issue by anthonysomerset** [oerdnj/deb.sury.org#257]
just updated to 7.0.3-6+deb.sury.org~wily+2 on Wily

getting following PHP errors now

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Warning:  Cannot load module 'mysqli' because required module 'mysqlnd' is not loaded in Unknown on line 0`

no changes to config made that i noticed

**Comment by simon-lifelike** [comment]
Same issue here. Also getting a similar error for bz2:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/bz2.so' - /usr/lib/php/20151012/bz2.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by fab120** [comment]
Same issue here
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0`

**Comment by oerdnj** [comment]
`php7.0_7.0.3-7+deb.sury.org~*+2` and `php5.6_5.6.18+dfsg-6+deb.sury.org~*+2` contains fixes for both issue. The change was quite big and I have missed this when I was testing the NEW split packages.

**Comment by Ardakilic** [comment]
+1 Same issue here. I'm already up-to-date but I guess the packages that hold the fixes are currently building, right ?

**Comment by oerdnj** [comment]
They should be available any moment. All packages have been built and they are in 'Pending publication' -> this usually resolves in couple of minutes.

**Comment by Ardakilic** [comment]
I can confirm the issue is fixed on my end after the latest build. Thanks!
