### ISSUE TITLE
DOM extension missing? (7.0.3-6+deb.sury.org~wily+2)

### ISSUE THREAD

**Issue by nicwortel** [oerdnj/deb.sury.org#258]
My system upgraded to PHP 7.0.3-6+deb.sury.org~wily+2, and suddenly the DOM extension is not working anymore. This prevents me from using phpunit, for example.

**Comment by nicwortel** [comment]
I see there is also a report about the [MySQL extension being broken](https://github.com/oerdnj/deb.sury.org/issues/257), perhaps the two are related to each other?

**Comment by nicwortel** [comment]
For other people coming here because they have the same issue: I fixed this by installing the php7.0-xml package.

**Comment by oerdnj** [comment]
Nope, unrelated. The move of DOM is stated in NEWS file:
```
php7.0 (7.0.3-6) unstable; urgency=medium

  * Several extensions have been split into separate extension packages:
   - php-dba - Database (dbm-style) Abstraction Layer
   - php-mbstring - Multibyte String
   - php-soap - SOAP
   - php-xml - DOM, SimpleXML, WDDX, XML, XMLReader and XMLWriter
   - php-zip - Zip
  * The new packages are not installed automatically, so you will need to
    install them by hand, if you use the functions in those modules.
  * Most modules that have been builtin before are now included in
    php7.0-common package and they are enabled by default for your
    convenience.  You can disable unneede modules via phpdismod tool.

 -- Ondřej Surý <ondrej@debian.org>  Mon, 22 Feb 2016 12:37:09 +0100
```
The NEWS file should show to you when upgrading by default if you have apt-listchanges installed.
