### ISSUE TITLE
msgpack should be loaded before memcached

### ISSUE THREAD

**Issue by calvera** [oerdnj/deb.sury.org#259]
I would recommend to set:

```INI
; configuration for php msgpack module
; priority=10
extension=msgpack.so

**Comment by oerdnj** [comment]
Right, I'll rather bump memcached to 25. igbinary + memcached and igbinary + redis probably has the same problem, but it doesn't manifest because 'i' goes first in the alphabet.

**Comment by calvera** [comment]
yes, good point

**Comment by oerdnj** [comment]
Could you retry with `php-memcached_2.2.0-51-ge573a6e+2.2.0-4+deb.sury.org~*+3`? I am not having the most successful day of my life, so `+1`-'+4` revisions contained little typos on just 4 lines :(.

Ahaha, I haven't had a coffee today yet :).

**Comment by calvera** [comment]
it works, shit happens ;)
