### ISSUE TITLE
problem with wddx?

### ISSUE THREAD

**Issue by calvera** [oerdnj/deb.sury.org#260]
in php5.6-xml version 5.6.18+dfsg-6+deb.sury.org~wily+2

I get
```ShellSession
13:32 # php5.6 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/wddx.so' - /usr/lib/php/20131226/wddx.so: undefined symbol: php_XML_SetUserData in Unknown on line 0

**Comment by oerdnj** [comment]
Does it help if you load xml.so first? (e.g. change it's priority to n < 20)

**Comment by calvera** [comment]
yes, so similar problem to msgpack and memcached... thanks!

**Comment by oerdnj** [comment]
Will be fixed in `+3` upload I just made.

**Comment by oerdnj** [comment]
So, it should be fixed in `php5.6 - 5.6.18+dfsg-6+deb.sury.org~*+5 ` and `php7.0 - 7.0.3-7+deb.sury.org~*+5`. Unfortunately PHP takes 20-30 minutes to rebuild, so I really hope `+5` doesn't have any little typo in the php-xml `postinst` script :)
