### ISSUE TITLE
[PHP-7] PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - 

### ISSUE THREAD

**Issue by qauseradm** [oerdnj/deb.sury.org#261]
https://launchpad.net/~ondrej/+archive/ubuntu/php
7.0.3-7+deb.sury.org~trusty+2

server:/var/www$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Warning:  Cannot load module 'mysqli' because required module 'mysqlnd' is not loaded in Unknown on line 0
PHP 7.0.3-7+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by oerdnj** [comment]
See the `7.0.3-7+deb.sury.org~trusty+1` in your listing. Update to `+2` at least.

**Comment by qauseradm** [comment]
Yep, it's fixed. Thank you/

**Comment by fab120** [comment]
Fixed also for me. Thanks you so much @oerdnj

**Comment by oerdnj** [comment]
Sorry for the breakage, it somehow slipped my attention.
