### ISSUE TITLE
[PHP7.0] zlib isn't enabled in newest build

### ISSUE THREAD

**Issue by cerlestes** [oerdnj/deb.sury.org#262]
I'm getting the following output after upgrading to `7.0.3-7+deb.sury.org~trusty+5` from `7.0.3-5+deb.sury.org~trusty+1`:

```
# php -i | grep "zlib"
gzip compression => disabled (install ext/zlib)
```

Is this intended? zlib has always been enabled for Debian/Ubuntu builds to my knowledge. And as there's no php7.0-zlib package available, I guess this is a mistake?

**Comment by opi99** [comment]
A little bit slower, but same issue for me.

**Comment by oerdnj** [comment]
Fixed in `php5.6_5.6.18+dfsg-7+deb.sury.org~*+1` and `php7.0_7.0.3-8+deb.sury.org~*+1` uploads.

**Comment by oerdnj** [comment]
JFTR please wait for `php5.6_5.6.18+dfsg-7+deb.sury.org~*+2` and `php7.0_7.0.3-8+deb.sury.org~*+2`, I moved zlib to -common package as zlib1g is in essential package set anyway.

**Comment by cerlestes** [comment]
It's working again. Awesome! Thanks for your efforts, Ondřej.

**Comment by opi99** [comment]
\o/ Thanks
