### ISSUE TITLE
Unable to decompress gzipped phar archive

### ISSUE THREAD

**Issue by harshadyeola** [oerdnj/deb.sury.org#263]
While using PHP packages with repo ```ppa:ondrej/php``` following WP-CLI  command worked fine.

But suddenly commands are non functional with following error

```
root@vagrant-ubuntu-trusty-64:~# wp --allow-root core download

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcached.so' - /usr/lib/php/20131226/memcached.so: undefined symbol: php_msgpack_serialize in Unknown on line 0
Downloading WordPress 4.4.2 (en_US)...
Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive "/tmp/wp_56cca8d55f801.tar.gz" to temporary file, enable zlib extension in php.ini
 ```

**Comment by oerdnj** [comment]
This should be fixed in latest upload of php-memcached?

What version of php-memcached do you have installed? Also do you have php-msgpack installed or not?

**Comment by oerdnj** [comment]
Ah, also zlib has been addressed in #262

**Comment by oerdnj** [comment]
JFTR please wait for `php5.6_5.6.18+dfsg-7+deb.sury.org~*+2` and `php7.0_7.0.3-8+deb.sury.org~*+2`, I moved zlib to -common package as zlib1g is in essential package set anyway.

**Comment by harshadyeola** [comment]
@oerdnj 
Thanks! Issue is solved now
