### ISSUE TITLE
[PHP 7.0] - pecl errors

### ISSUE THREAD

**Issue by AntonStoeckl** [oerdnj/deb.sury.org#264]
Hi Ondrej,

probably that's also upstream, but pecl goes wild:

[pecl.txt](https://github.com/oerdnj/deb.sury.org/files/144113/pecl.txt)

anton@nimbus~> php -v
PHP 7.0.3-8+deb.sury.org~wily+2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

php-pear/wily,now 1:1.10.1+submodules+notgz-3+deb.sury.org~wily+3 all  [installed]

pear seems to work fine

Best regards, Anton

**Comment by oerdnj** [comment]
I don't touch pecl at all, so that's probably an upstream bug. There were quite big changes in PEAR 1.10.0, that broke some stuff in pecl, so maybe this is also the victim. I don't use pecl for packaging external modules, just plain `phpize && ./configure && make && make install` for that reason.

**Comment by AntonStoeckl** [comment]
Ok Ondrej, thx for the input! I'll try to solve it / get it solved.

**Comment by AntonStoeckl** [comment]
Ondrej, just another question:
Is there a chance you will add oci8 to the PPA, so us "users" get rid of pecl for this module?

**Comment by oerdnj** [comment]
Does it still need non-free libraries from the Spawn of the Evil?

**Comment by AntonStoeckl** [comment]
Yeah. If you need to talk to the Database of the Evil, you need it's client libs. At least I don't know a different way. :-(

**Comment by oerdnj** [comment]
This --> http://www.oracle.com/technetwork/licenses/instant-client-lic-152016.html <-- is the problem. I would need the libraries uploaded to PPA and Oracle would hunt me down :). Shame nobody wrote PHP extension based on ocilib.

**Comment by AntonStoeckl** [comment]
Understood! Probably compiling and packaging with debhelper will do the job for us.

**Comment by oerdnj** [comment]
Shouldn't be hard to package yourself though. Take f.e. php-gmagick as an example package.

```
apt-get install php-all-dev git-buildpackage
# install libraries of evil somewhere linker can find them
mkdir /tmp/php-oci8
cd /tmp/php-oci8
mkdir php5.6 php7.0
wget -q -O - https://pecl.php.net/get/oci8-2.0.10.tgz | tar -xz -C php5.6
wget -q -O - https://pecl.php.net/get/oci8-2.1.0.tgz | tar -xz -C php7.0
tar -cJf ../php-oci8-2.1.0+2.0.10.tar.xz
rm -rf php5.6 php7.0
git init
gbp import ../php-oci8-2.1.0+2.0.10.tar.xz # hit ENTER on every question
cp <php-gmagick-source-dir>/debian/ .
cd debian
rename s/gmagick/oci8/ *gmagick*
find . -type f | xargs -i sed -i 's/gmagick/oci8/' {}
editor changelog # make something sensible here, like strip all the previous lines
cd ..
git add debian
git commit -m "Initial import"
```

And debug into functionality...  (wrote that just from top of my head)

**Comment by pkruithof** [comment]
I think this _is_ caused by recent changes in this repo. I'm currently in the process of updating to the new `ondrej/php` ppa (without the version), since the previous sources now give 404's (by the way, kind of harsh in my opinion to 404 them this soon).

The problem is that pecl runs php without an ini file: `php -n`, which excluded the xml extension in the new situation. More detailed description here: http://serverfault.com/a/612038/43144

Output from a server that was provisioned just a week ago (with ppa `ondrej/php-7.0`):

```
$ php -n -m 
[PHP Modules]
[..some modules..]
xml
xmlreader
xmlwriter
zip
zlib
```

Now with PHP 7 installed via ppa `ondrej/php`:

```
$ sudo apt-get install php7.0-cli 
[..install output..]
$ php -n -m
[PHP Modules]
Core
date
filter
hash
libxml
openssl
pcntl
pcre
Reflection
session
SPL
standard
```

**Comment by oerdnj** [comment]
> since the previous sources now give 404's (by the way, kind of harsh in my opinion to 404 them this soon).

This was announced several times.

> The problem is that pecl runs php without an ini file: php -n

Don't hijack old bugs, but open a new open. This should be simple to fix by editing pecl and removing the '-n' option.

**Comment by pkruithof** [comment]
I know the fix is simple by editing the pecl file, but I don't think it's the right fix. It's third-party software that should not be edited IMO. Anyway, should I open a new issue, will you fix it?

> This was announced several times.

Another discussion, another time perhaps :)

**Comment by oerdnj** [comment]
pecl is part of php-pear package, so it needs to be fixed there. It would be best to open the bug in the Debian bug tracker, but here will do as well. I'll make sure it's fixed in php-pear package in Debian and in here.

**Comment by pkruithof** [comment]
I've created #284. Are you sure you want to fix this in pecl, rather than the configure options? If so, may I know the reasons for changing the compile configuration?

Also, just a quick thanks for all the work with these repo's. Been using them a long time now, and it's greatly appreciated.

**Comment by oerdnj** [comment]
The reason why most of the extensions were moved out of main SAPIs are outlined here: #254
