### ISSUE TITLE
[php7.0+php5.6] php5.6 failed to start

### ISSUE THREAD

**Issue by ed29** [oerdnj/deb.sury.org#265]
When upgrade co-installed php5.6+7.0,php5.6 failed to start,hrer is the log:

Processing triggers for php7.0-fpm (7.0.1-4+deb.sury.org~trusty+1) ...
 * Restarting PHP 7.0 FastCGI Process Manager php-fpm7.0                                                                           [ OK ]
Processing triggers for php5.6-fpm (5.6.16+dfsg-9+deb.sury.org~trusty+1) ...
 * Restarting PHP 5.6 FastCGI Process Manager php-fpm5.6                                                                                  *** Error in `/usr/sbin/php-fpm5.6': free(): invalid pointer: 0x00007f8b985933b8 ***

**Comment by oerdnj** [comment]
Versions? `7.0.1-4+deb.sury.org~trusty+1` <-- this is definitely not up-to-date.

**Comment by oerdnj** [comment]
Extensions installed, etc? The more information about your system the better. I am not a clairvoyant.

**Comment by oerdnj** [comment]
`5.6.16+dfsg-9+deb.sury.org~trusty+1` is also not latest available version.

**Comment by ed29** [comment]
Got it,maybe something went wrong on my side,i will check by myself first,thank you for your point out.
