### ISSUE TITLE
PHP 7.0.3 mbstring

### ISSUE THREAD

**Issue by karlbuckland** [oerdnj/deb.sury.org#267]
Firstly, thank you for producing these packages. They're really useful.

I've recently upgraded from 7.0.1 to 7.0.3 and this has caused a problem with the mbstring functions. Have they been removed or has the configuration to use them been changed?

For example, if I call:
`mb_internal_encoding("UTF-8");`
I get the error
`PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding()`

I also can't see the mbstring section in phpinfo.

I'm running PHP 7.0.3-9+deb.sury.org~trusty+3. This was working fine on 7.0.1. If you can't reproduce the problem then I'll roll a new virtual system and install fresh and see if the issue happens again.

Also: from what I can see there doesn't appear to be a way to downgrade from 7.0.3 to 7.0.1?

**Comment by karlbuckland** [comment]
In addition - and this may or may not be related. It also looks like zlib support has disappeared. The zlib section in our phpinfo is gone and calls to gzcompress (for example) are not working.

**Comment by oerdnj** [comment]
Does nobody read NEWS.Debian these days? Please `apt-get install apt-listchanges`, so you read the NEWS file when upgrading:
```
$ zcat /usr/share/doc/php7.0-common/NEWS.Debian.gz 
php7.0 (7.0.3-6) unstable; urgency=medium

  * Several extensions have been split into separate extension packages:
   - php-dba - Database (dbm-style) Abstraction Layer
   - php-mbstring - Multibyte String
   - php-soap - SOAP
   - php-xml - DOM, SimpleXML, WDDX, XML, XMLReader and XMLWriter
   - php-zip - Zip
  * The new packages are not installed automatically, so you will need to
    install them by hand, if you use the functions in those modules.
  * Most modules that have been builtin before are now included in
    php7.0-common package and they are enabled by default for your
    convenience.  You can disable unneede modules via phpdismod tool.

 -- Ondřej Surý <ondrej@debian.org>  Mon, 22 Feb 2016 12:37:09 +0100
```

**Comment by karlbuckland** [comment]
Thank you. I ran the upgrades via Ansible, so I didn't see the upgrade notes. I've set up apt-listchanges to email me the changes from the servers, so that should do it!
