### ISSUE TITLE
[php7.0+php5.6] support for php-ssh2

### ISSUE THREAD

**Issue by aberbenni** [oerdnj/deb.sury.org#269]
Please add php-ssh2 package to ppa:ondrej/php.

**Comment by oerdnj** [comment]
Have you even checked the repository? It's already there.

**Comment by aberbenni** [comment]
Here is what i obtain typing

apt-get install php7.0

php7.0            php7.0-cli        php7.0-dev        php7.0-gmp        php7.0-json       php7.0-mysql      php7.0-phpdbg     php7.0-snmp       php7.0-tidy       php7.0-zip
php7.0-bcmath     php7.0-common     php7.0-enchant    php7.0-imap       php7.0-ldap       php7.0-odbc       php7.0-pspell     php7.0-soap       php7.0-xml
php7.0-bz2        php7.0-curl       php7.0-fpm        php7.0-interbase  php7.0-mbstring   php7.0-opcache    php7.0-readline   php7.0-sqlite3    php7.0-xmlrpc
php7.0-cgi        php7.0-dbg        php7.0-gd         php7.0-intl       php7.0-mcrypt     php7.0-pgsql      php7.0-recode     php7.0-sybase     php7.0-xsl

**Comment by aberbenni** [comment]
Using apt-get install php-ssh2 the default 0.12-39-g3dfe336+0.12-1+deb is installed but I expect 0.12-39-g3dfe336+0.12-1+deb.sury.org~trusty.

**Comment by oerdnj** [comment]
What does `apt-cache policy php-ssh2` say?

**Comment by aberbenni** [comment]
I solved pinning the package (https://help.ubuntu.com/community/PinningHowto). But, at the end php-ssh2 for php7 is bugged (https://bugs.php.net/bug.php?id=71376) and completely useless for now ;-(
