### ISSUE TITLE
php-config --extension-dir

### ISSUE THREAD

**Issue by colinodell** [oerdnj/deb.sury.org#270]
Running `php-config --extension-dir` results in the following output: `${prefix}/lib/php/20151012`.  I would expect this to contain a full and proper path.

I'm able to replicate this issue on 7.0.3-9+deb.sury.org~trusty+3.

**Comment by oerdnj** [comment]
You are right, something went awol. Did that happened before, or did the bug just appeared?

**Comment by colinodell** [comment]
I suspect that this bug was introduced in the latest build.

An automated script I was using (from puphpet/puphpet) to compile xdebug worked fine 2 days ago and stopped working today.  This script basically installs the latest PHP 7 and eventually runs this bash command:

```bash
cp /.puphpet-stuff/xdebug/modules/xdebug.so `php-config --extension-dir`/xdebug.so
```

This process worked fine two day ago.  Today it is throwing this error:  `cannot create regular file ‘${prefix}/lib/php/20131226/xdebug.so’`

This automated process always uses the latest PPA build.  I haven't changed anything else over the past two days.  This is why I think the last build might be the culprit.

This might also affect 5.5 and 5.6: https://github.com/puphpet/puphpet/issues/2191

**Comment by oerdnj** [comment]
BTW Why you just don't `apt-get install php-xdebug`?

**Comment by oerdnj** [comment]
You are right, it was introduced in `7.0.3-9`, dunno why.

**Comment by oerdnj** [comment]
I think this should be fixed in `php7.0_7.0.3-10+deb.sury.org~*+1`, but I'll have to see when the build finishes. (Just replacing single with double quotes should fix the issue.)

**Comment by colinodell** [comment]
I can confirm it is fixed in the latest build.  Thank you!

**Comment by jtreminio** [comment]
@oerdnj 

> BTW Why you just don't apt-get install php-xdebug?

puphpet's offered PHP7 support since it was in early beta, via the Zend repos. Back then, xdebug had to be compiled to work (when it finally had a version that worked on PHP 7).

Now that PHP 7's stable and xdebug is packaged in several repos, I may go back to using the packages.
