### ISSUE TITLE
DOM extention disabled

### ISSUE THREAD

**Issue by BartoszBartniczak** [oerdnj/deb.sury.org#271]
I cannot download phpunit by composer because of lack of DOM Extension:
`Problem 1
    - phpunit/phpunit 5.2.9 requires ext-dom * -> the requested PHP extension dom is missing from your system.
`
Is this an known issue for you or it is just mine machine? I think it came up with last build.

**Comment by oerdnj** [comment]
`apt-get install php-xml` to install XML related extensions and `apt-get install apt-listchanges`, so you actually read NEWS.Debian.

**Comment by BartoszBartniczak** [comment]
Thank you very much.
