### ISSUE TITLE
Missing mysqli extension

### ISSUE THREAD

**Issue by mbrodala** [oerdnj/deb.sury.org#272]
I am trying to set up a VM with PHP 7 and this repository for TYPO3 but get this error:

> #1271492607: Database Error: PHP mysqli extension not loaded. This is a must have for TYPO3 CMS! 

Running `php -m | grep mysqli` indeed yields nothing whereas the extension shows up just fine for the PHP5 packages installed from `ppa:ondrej/php5-5.6`.

Thus I'd assume that the `mysqli` extension was simply not compiled, could you change this?

**Comment by oerdnj** [comment]
`apt-get install php-mysql`

**Comment by mbrodala** [comment]
Thanks, works like a charm. I was under the impression that this package only provides the old `mysql` extension. ;-)

**Comment by Talkless** [comment]
I just experienced same issue. ISPConfig on Ubuntu 12.04 with php5.6 produces errors in it's cron job:
```
PHP Fatal error:  Class 'mysqli' not found in /usr/local/ispconfig/server/lib/classes/db_mysql.inc.php on line 30
```

`php-mysql` package does not seems to help. This packages is rather..empty in Precise:
```
# apt-cache policy php-mysql
php-mysql:
  Installed: 1:7.0+45+deb.sury.org~precise+1
  Candidate: 1:7.0+45+deb.sury.org~precise+1
  Version table:
 *** 1:7.0+45+deb.sury.org~precise+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status

# dpkg -L php-mysql
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php-mysql
/usr/share/doc/php-mysql/changelog.gz
/usr/share/doc/php-mysql/copyright
```

**Comment by oerdnj** [comment]
`php-mysql` is a dummy package:
```
Description-en: MySQL module for PHP [default]
 This package provides a MySQL module for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on Debian's default
 PHP version (currently 7.0).
```

You need to install `php5.6-mysql`.

**Comment by Talkless** [comment]
My problem was that somehow I've installed php7. 

`php --version` returned 7.1, and I hae not installed any php7-replated mysql packages etc. etc.

I removed all php7* packages and now that cron job (php cli v5.6)  is working.

Sorry for bothering.
