### ISSUE TITLE
Bump php-memcached version

### ISSUE THREAD

**Issue by Jud** [oerdnj/deb.sury.org#274]
First, thanks for the awesome work you've done getting with the PHP7 builds.

I was having an issue with memcached segfaulting:

```
php7.0[5074]: segfault at 7fff27200000 ip 00002ac8f506cd4a sp 00007fff273f51d0 error 4 in php7.0[2ac8f4e40000+387000]
```

It looks to be fixed in the php-memcached php7 branch, and after manually installing the extension from the php7 branch (https://github.com/php-memcached-dev/php-memcached/commit/6ace07da69a5ebc021e56a9d2f52cdc8897b4f23), there are no more segfaults.

Would you consider updating the package to the latest git snapshot?

**Comment by oerdnj** [comment]
Fixed in `php-memcached_2.2.0-95-g6ace07d+2.2.0-1+deb.sury.org~*+1`

**Comment by Jud** [comment]
:+1:  Thanks!
