### ISSUE TITLE
requesting another 2.4.18 release with newer mod_h2 ( 1.1.0+ )

### ISSUE THREAD

**Issue by RossRogers** [oerdnj/deb.sury.org#275]
mod_h2 has some [new fixes](https://github.com/icing/mod_h2/issues/62) which have an effect on the basic stability of using `protocol h2`.  I'd love to see a new apache 2.4.18 release with a mod_h2 version number greater than 1.1.0, if possible.

Thanks for your work Ondřej.

 - Ross

**Comment by oerdnj** [comment]
@RossRogers apache2_2.4.20 was release into PPAs today with MOD_HTTP2_VERSION "1.4.6"

**Comment by RossRogers** [comment]
Thank you @oerdnj !
