### ISSUE TITLE
README as front page of this repository

### ISSUE THREAD

**Issue by joelhandwell** [oerdnj/deb.sury.org#276]
It would be beneficial for the visitors of this GitHub project to have a README file describing purpose of this repo and/or instruction on how to use the issue tracker.

**Comment by oerdnj** [comment]
Definitely, could you write one? :)

**Comment by joelhandwell** [comment]
Sure, please review following: 

README.md 

```
* ppa:ondrej/php issue tracker
This GitHub project is the issue tracker of [PPA for PHP (5.6, 7.0)](https://launchpad.net/~ondrej/+archive/ubuntu/php).

Please submit bug reports and feature request about the PPA as [issues here](https://github.com/oerdnj/deb.sury.org/issues).
```

**Comment by oerdnj** [comment]
Thanks, I will update it with more info in due time, but this will do for now.
