### ISSUE TITLE
Request for tideways extension

### ISSUE THREAD

**Issue by lornajane** [oerdnj/deb.sury.org#278]
Traditionally, profiling in PHP is done via XDebug or XHProf.  XHProf was excellent but is no longer maintained and doesn't work on PHP 7.  The same functionality can be achieved using the Tideways extension, which is available now for PHP 7 https://github.com/tideways/php-profiler-extension - this will integrate with existing profiling tools such as https://github.com/perftools/xhgui

**Comment by oerdnj** [comment]
@lornajane should I go for 4.0.3 release or rather pull latest git master for the moment?

**Comment by oerdnj** [comment]
Hmm, looks like 4.0.3 should be ok:
```
$ git log v4.0.3..HEAD
commit 1f075d9b6e58a4cea9abf9454b9db65f38d0a7f9
Author: Benjamin Eberlei <kontakt@beberlei.de>
Date:   Fri Feb 12 23:39:27 2016 +0100

    [PROF-458] Add log level ini setting.

commit b7639191c8a4a6d7f8b7830deb719f1d0d23ec4c
Author: Benjamin Eberlei <kontakt@beberlei.de>
Date:   Wed Feb 3 10:15:56 2016 +0100

    Fix compile error on Mac platform.
```

**Comment by lornajane** [comment]
I would go with the tagged release

**Comment by oerdnj** [comment]
I am adding `tideways.auto_prepend_library=0` into default configuration. Is that right?

**Comment by oerdnj** [comment]
@lornajane I have just uploaded tideways extension to `ppa:ondrej/php-qa`, as I am changing how the extensions are handled because of #273. Don't use the `php-qa` in production, but I would appreciate if you could test the php-tideways from this repository before I push all the changes into `ppa:ondrej/php` itself.

**Comment by oerdnj** [comment]
Should be available as `php-tideways` in couple of minutes.

**Comment by lornajane** [comment]
Thanks!  Didn't get a chance to test yet, really appreciate this :)
