### ISSUE TITLE
Request for AST extension

### ISSUE THREAD

**Issue by lornajane** [oerdnj/deb.sury.org#279]
PHP 7 has Abstract Syntax Trees and the AST extension exposes these so that tools can use this information.  The extension is here https://github.com/nikic/php-ast but doesn't seem to have a pecl release yet (it is likely to become a core extension in PHP 7.1).  Making this extension available enables use of tools such as https://github.com/etsy/phan which are key to PHP 7 upgrades and adoption IMO.

**Comment by oerdnj** [comment]
`php-ast_0.1.1-1` should be already available.
