### ISSUE TITLE
completely broken

### ISSUE THREAD

**Issue by ChrisWiegman** [oerdnj/deb.sury.org#280]
php7 installs are completely broken and refuse to install. 

sudo apt-get install php7.0-fpm php7.0-curl php7.0-mysql php7.0-cli php-imagick 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-cli : Depends: php7.0-common (= 7.0.3-10+deb.sury.org~wily+1) but it is not going to be installed
              Depends: php7.0-json but it is not going to be installed
              Depends: php7.0-opcache but it is not going to be installed
              Depends: php7.0-readline but it is not going to be installed
 php7.0-curl : Depends: php-common but it is not going to be installed
               Depends: php7.0-common (= 7.0.3-10+deb.sury.org~wily+1) but it is not going to be installed
 php7.0-fpm : Depends: php7.0-common (= 7.0.3-10+deb.sury.org~wily+1) but it is not going to be installed
              Depends: php7.0-json but it is not going to be installed
              Depends: php7.0-opcache but it is not going to be installed
 php7.0-mysql : Depends: php-common but it is not going to be installed
                Depends: php7.0-common (= 7.0.3-10+deb.sury.org~wily+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by oerdnj** [comment]
This is just an temporary state and it will be fixed as the packages are uploaded and built. There's just incompatible change that forces to upgrade all packages at the same time. Patience please.

**Comment by hypergeometric** [comment]
Getting a similar situation with the php-memcached package complaining about unmet dependencies on php-igbinary, php-json, php-msgpack, php-memcached and php-phpapi-20151012/phpapi-20131226.

**Comment by oerdnj** [comment]
Here's a way how to check whether the packages has finished building: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?batch=200

**Comment by hypergeometric** [comment]
The php-memcached builds seems to have broken with the following:
```
sbuild-build-depends-php-memcached-dummy : 
  Depends: php-igbinary but it is not going to be installed
  Depends: php-msgpack but it is not going to be installed
```
Thought I'd mention this as I'm not sure what the retry setup is on these.

**Comment by Demoboy** [comment]
I too cannot install php-memcached. According to: https://launchpad.net/~ondrej/+archive/ubuntu/php/+builds all the packages have been built. 

```
The following packages have unmet dependencies:
 php-memcached : Depends: php-igbinary but it is not going to be installed
                 Depends: php-json
                 Depends: php-msgpack but it is not going to be installed
                 Depends: php-common (>= 1:7.0+33~) but it is not going to be installed
                 Depends: phpapi-20151012 or
                          phpapi-20131226
E: Unable to correct problems, you have held broken packages.
```

**Comment by oerdnj** [comment]
Found it, will be fixed in moment. I defined couple of Breaks in php-common and php-memcached and php-radius had a lower version.

**Comment by bungle** [comment]
Yes, same problem with me.

**Comment by oerdnj** [comment]
All should be fixed as of this moment.

**Comment by oerdnj** [comment]
This is the last major change of the PHP packaging that needed to be done (crossed fingers)...

**Comment by VusP** [comment]
I am on Debian 7 machine. I have installed PHP 7.1 via source and then I wanted to install libmemcached. But since that is available for PHP 5, I decided to go with php-memcached in the  ppa:ondrej/php repository. I am pulling the packages for Precise in the repository. I get the following
```
 php-memcached : Depends: php-igbinary but it is not going to be installed
 Depends: php-msgpack but it is not going to be installed
                 Depends: phpapi-20151012 or
                          phpapi-20131226 or
                          phpapi-20121212
                 Depends: libc6 (>= 2.14) but 2.13-38+deb7u10 is to be installed
                 Depends: libmemcached11 but it is not going to be installed
```
Can I get this to install on Debian somehow or should I ditch Debian and go for Ubuntu ( this will require me to make OS changes and check all code & processes for all my production servers which is quite a task )

**Comment by oerdnj** [comment]
@VusP https://deb.sury.org/#php-packages
