### ISSUE TITLE
Broken redis

### ISSUE THREAD

**Issue by piotrantosik** [oerdnj/deb.sury.org#281]
Upgrade to latest redis require igbinary.
But igbinary won't work properly on php 7
```
WARNING: [pool www] child 8396 said into stderr: "NOTICE: PHP message: PHP Warning:  igbinary_unserialize_header: unsupported version: 1329214260, should be 1 or 2
```

see https://github.com/oerdnj/deb.sury.org/issues/92#issuecomment-185733355

**Comment by robfrawley** [comment]
@piotrantosik Igbinary is working fine, it simply doesn't understand the data you are trying to deserialize (and assumes its an Igbinary mis-match). You will receive that error if there is serialization data from any other serializer already present. I've run across it often; just clear the necessary caches, PHP sessions, etc.

**Comment by oerdnj** [comment]
The default redis serializer is SERIALIZER_NONE:

# php test.php 
Redis::SERIALIZER_NONE

test.php:
```
<?php

$redis = new Redis();
$redis->connect('127.0.0.1', 6379);

$s = $redis->getOption(Redis::OPT_SERIALIZER);

if ($s === Redis::SERIALIZER_NONE) {
   print "Redis::SERIALIZER_NONE\n";
} else if ($s === Redis::SERIALIZER_PHP) {
  print "Redis::SERIALIZER_PHP\n";
} else if ($s === Redis::SERIALIZER_IGBINARY) {
  print	"Redis::SERIALIZER_IGBINARY\n";
}

?>
```

You need to make sure your serialize and unserialize uses (and used) same Redis SERIALIZER option.
