### ISSUE TITLE
General (basic) documentation

### ISSUE THREAD

**Issue by robfrawley** [oerdnj/deb.sury.org#282]
Does GitHub have the ability to grant access to only the Wiki? If so, and assuming you are interested, I'd like lead an effort creating some central documentation around these packages within the Wiki. For example:

- Which extensions have been compiled against others but do not have hard dependencies (for example, Memcached and Igbinary/Msgpack).
- Basic info on managing a system with two PHP versions, and specifically, knowing that `update-alternatives` is available (and understanding what it is).
- Information on `phpenmod`, `php-config`, etc
- Specification for the packages to facilitate anyone who may want to package an extension you haven't (or one you will not), as well as provide a roadmap for anyone who may need to package the core PHP package themselves due to specific compile-time requirements.
- I'm sure there's more

I'm more than happy to write up some stuff (and I plan to regardless), but I figured it would make a ton of sense to use the Wiki here to keep all public-facing interaction with the PPA you manage in a singular location. 

@oerdnj How do you feel about this? Do I get a thumbs up or down? ;-)

**Comment by JeGr** [comment]
I'd throw in a :+1: and would add usage for pecl/pear with those two PHP versions etc.
So some basic intel/documentation would be very nice to have and participate in.

**Comment by oerdnj** [comment]
> GitHub Wikis is a simple way to let others contribute content. *Any GitHub user* can create and edit pages to use for documentation, examples, support, or anything you wish. 

It should just work...

**Comment by oerdnj** [comment]
And it is an excellent idea!

**Comment by robfrawley** [comment]
Ha! _It does just work!_ ([test page](https://github.com/oerdnj/deb.sury.org/wiki)) I use Github solely as a mirror for Packagist, otherwise I'm using Gitlab --- it looks like I need to brush up on the Github feature-set. ;-)

**Comment by oerdnj** [comment]
So, I guess I can close this...

**Comment by mablae** [comment]
@robfrawley Did you already write it up? I am running into some issues and some docs would be nice :-)
