### ISSUE TITLE
[php-7.0] not configured with XML, breaks pecl

### ISSUE THREAD

**Issue by pkruithof** [oerdnj/deb.sury.org#284]
(continuing from https://github.com/oerdnj/deb.sury.org/issues/264#issuecomment-191275691)

Switching from `ondrej/php-7.0` to the new `ondrej/php` ppa, php is no longer built with xml support. `php-config7.0` shows that (among others) the following options are no longer there:

```
--enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter
```

This in turn breaks pecl support, as this runs without any additional extensions (by excluding the php.ini file), and it requires the xml extension.

I'm not familiar with the reasons for this change, so I don't know if the configure options needs to be changed, or the pecl script, to fix this problem. But I'd say that if you `apt-get install php7.0-cli php7.0-dev` that both should be installed and working without errors.

**Comment by oerdnj** [comment]
This should be fixed in `php-pear_1:1.10.1+submodules+notgz-4+deb.sury.org~*+1`.
