### ISSUE TITLE
[PHP 7] Missing installation of Apache mod

### ISSUE THREAD

**Issue by enoch85** [oerdnj/deb.sury.org#285]
Just tried the latest version and when showing php files I only got text. Running `apt-get install libapache2-mod-php` fixed the error, and php sites showed normally. Shouldn't this be inlcuded in the PPA?

**Comment by oerdnj** [comment]
What exactly you did, what packages got installed, and what exactly you did after that to get it working and what packages did get installed?

**Comment by enoch85** [comment]
I just updated as normal and didn't find out until a few days ago that there was an issue, it's hard to pin down the exact reason. I can just confirm this bug.

The version is the latest as of yesterday from your PPA.

**Comment by oerdnj** [comment]
This isn't very helpful...  Anything relevant in your APT logs  (`/var/log/apt`)?

**Comment by oerdnj** [comment]
Perhaps "updated as normal" means you do `apt-get dist-upgrade` without reading the packages to be removed and just saying 'yes' to everything?

**Comment by enoch85** [comment]
### Steps to reprodce
1. Do a fresh install of PHP 7 from the PPA
2. Notice the error
3. apt-get install libapache2-mod-php7.0 to get it working

I installed this on a VM. This are the scripts I used: https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh

**Comment by oerdnj** [comment]
Your script is wrong or rather the assumptions are wrong - `php7.0` is just a convenience package that other packages might depend to be guaranteed some web interface, but it might install either libapache2-mod-php7.0 or php7.0-cgi or php7.0-fpm. You need to pick one manually if you know what server are you going to install.

**Comment by enoch85** [comment]
It worked before without adding it manually, so I thought something had changed - which it apperantly had?

You say the script is wrong, what would be the correct way to go then?

Thanks!

**Comment by oerdnj** [comment]
Don't install php7.0 and just libapache2-mod-php7.0 because that's what you want 

Which package gets installed as a dependency to php7.0 package is decided by apt dependency resolver and it's influenced by other factors.

**Comment by enoch85** [comment]
:+1:
