### ISSUE TITLE
SWF not supported

### ISSUE THREAD

**Issue by Wizermil** [oerdnj/deb.sury.org#286]
Hello,

We upgraded from php 7.0.3 to php 7.0.4 unfortunately we are using SWF extensively and one of our script stopped working.
I had a quick look at the [src code](https://github.com/php/php-src/blob/PHP-7.0.4/ext/standard/image.c#L88) and it seems ZLIB is mandatory do you think you could add it back to your build script?

You can use [this test](https://github.com/php/php-src/blob/PHP-7.0.4/ext/standard/tests/image/getimagesize_swc.phpt) to check that everything is working

Congrats for the hard work on PHP7.0 for ubuntu ;)
```
# php -version
PHP 7.0.4-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

# uname -a
Linux delphox 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

**Comment by oerdnj** [comment]
I prepared a very quick rebuild with --with-zlib-dir=/usr given close to the ext/gd configure parameters. Could you please retry with `ppa:ondrej/php-qa` and I'll dig deeper tomorrow if that still doesn't work (some paths might be broken due MultiArch support).

**Comment by oerdnj** [comment]
Hah, it looks like SWF is not related to gd directly:
```
./ext/standard/image.c:	REGISTER_LONG_CONSTANT("IMAGETYPE_SWC",     IMAGE_FILETYPE_SWC,     CONST_CS | CONST_PERSISTENT);
```

**Comment by Wizermil** [comment]
My bad I created the ticket with the wrong information I changed 10min after when I discovered that gd wasn't implicated in the issue but you probably received the notif email before that

I tested the qa build and it's not working :(

I don't know if it can help you but on my server here are the paths I found for zlib and libzip
```
# ls -fl /usr/lib/x86_64-linux-gnu/ | grep libz
lrwxrwxrwx   1 root root       35 May 13  2013 libz.so -> /lib/x86_64-linux-gnu/libz.so.1.2.8
lrwxrwxrwx   1 root root       15 Mar  3 13:09 libzip.so.4 -> libzip.so.4.0.0
-rw-r--r--   1 root root   142346 May 13  2013 libz.a
-rw-r--r--   1 root root    80152 Mar  3 13:09 libzip.so.4.0.0
# ls -fl /lib/x86_64-linux-gnu/ | grep libz
lrwxrwxrwx  1 root root      13 May 13  2013 libz.so.1 -> libz.so.1.2.8
-rw-r--r--  1 root root  100728 May 13  2013 libz.so.1.2.8
```

**Comment by oerdnj** [comment]
Found a solution, and uploaded it to the php-qa, just wait for the builds to finish: https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages?batch=200

I'll make it part of main package in next round.

(Reopen if not fixed in `7.0.4-2+deb.sury.org~*+1`

**Comment by Wizermil** [comment]
The compilation failed https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+build/9295411

**Comment by oerdnj** [comment]
Yeah, extra '=' got deleted. Reuploaded as +2 and it should be fine.

**Comment by Wizermil** [comment]
Sorry it's not working
```
# php -r "var_dump(defined(\"IMAGETYPE_SWC\"));"
# php --version
PHP 7.0.4-2+deb.sury.org~trusty+2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by oerdnj** [comment]
It needs zlib extension to be compiled in and not as shared module, so I'll have to change some bits in the packaging and I'll release fix next week, ok?

**Comment by Wizermil** [comment]
let me know if I can help testing

**Comment by oerdnj** [comment]
`ppa:ondrej/php-qa` has the correct version. Just issue `phpdismod zlib` after installation (working to fix that now).

**Comment by oerdnj** [comment]
@Wizermil It would be nice if you could test it yourself. It works for me.

**Comment by oerdnj** [comment]
Released to `ppa:ondrej/php` as `php5.6_5.6.19+dfsg-3+deb.sury.org~*+4` and `php7.0_7.0.4-3+deb.sury.org~*+4` and it's building right now.

**Comment by Wizermil** [comment]
Thanks @oerdnj it works like a charm
