### ISSUE TITLE
phpMyAdmin can not be installed when using PPA for PHP (5.6, 7.0)

### ISSUE THREAD

**Issue by thirdeyenick** [oerdnj/deb.sury.org#287]
Heya,
we noticed that when using the PPA for PHP (5.6, 7.0) in Ubuntu Trusty in combination with either 'libapache2-mod-php5.6' or 'libapache2-mod-php7.0' we can not install phpMyAdmin anymore.
This happens because the official Ubuntu Trusty phpMyAdmin package lacks the new '5.6' and '7.0' package names:

`Depends: libapache2-mod-php5 | libapache2-mod-php5filter | php5-cgi | php5-fpm | php5, php5-mysql | php5-mysqli | php5-mysqlnd, php5-mcrypt, php5-json, perl, debconf (>= 0.5) | debconf-2.0, dbconfig-common, fonts-dejavu-core | ttf-dejavu-core, php-gettext, libjs-jquery, libjs-jquery-ui, libjs-jquery-cookie, libjs-jquery-mousewheel, libjs-jquery-event-drag, libjs-jquery-tablesorter, libjs-codemirror, libjs-underscore, ucf (>= 0.28)`

Does anyone see a way around this without repackaging phpMyAdmin and change the dependencies? I can see that this is fixed in the official Ubuntu Xenial package of phpMyAdmin.

**Comment by oerdnj** [comment]
Use phpmyadmin ppa: https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin It's fully compatible with PHP 7.0 packaging.

**Comment by amenk** [comment]
:+1:

**Comment by amenk** [comment]
Actually it is not working for me. I am on Ubuntu wily.

	me@me-laptop:/etc/apt/sources.list.d◈ 100 $ sudo apt-get install phpmyadmin
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 phpmyadmin : Depends: php-gettext but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.
	me@me-laptop:/etc/apt/sources.list.d◈ 100 $ sudo apt-get install php-gettext
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 php-gettext : Depends: php5 but it is not going to be installed or
		                      php5-cli but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.
