### ISSUE TITLE
[php 7.0] add php-judy

### ISSUE THREAD

**Issue by LAV45** [oerdnj/deb.sury.org#291]
can add to your collection of extensions [php7.0-judy](https://github.com/tony2001/php-judy/tree/php7)
This extension uses and supports company https://badoo.com

**Comment by oerdnj** [comment]
I could package this if you still want. But I would rather wait for full release on https://pecl.php.net/package/Judy for less common extensions.

**Comment by LAV45** [comment]
After installing this extension, tests have shown that it works 2 times slower than normal array. So I closed the task, because the application is no longer relevant for php7.
