### ISSUE TITLE
[PHP7.0] php7.0-dbg

### ISSUE THREAD

**Issue by OPM87** [oerdnj/deb.sury.org#292]
Hello,
I'm getting for PHP7: Segmentation fault (11) zend_mm_heap corrupted 
so I wanted to debug the dumpfile.
But since upgrade to 7.0.4 I'm getting an error for installing php7.0-dbg:

xyz@xyz:~# apt-get install php7.0-dbg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-dbg : Depends: libapache2-mod-php7.0 (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed or
                       php7.0-cgi (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed or
                       php7.0-cli (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed or
                       php7.0-fpm (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed or
                       libphp7.0-embed (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed or
                       php7.0-phpdbg (= 7.0.3-5+deb.sury.org~trusty+1) but 7.0.4-3+deb.sury.org~trusty+1 is to be installed
E: Unable to correct problems, you have held broken packages.

I updated the package lists, cleanup the cache but no success.
Also I saw on the launchpad.net site for the package 
"php7.0 - 7.0.4-3+deb.sury.org~trusty+4" the module:
"php7.0-fpm-dbgsym debug symbols for package php7.0-fpm" but i can't install it.

**Comment by oerdnj** [comment]
There has been change in the way the debug symbols are generated in recent Debian unstable (hence the automatic dbgsym package). Unfortunately it's virtually impossible to support both ways, so only dbgsym packages are now supported (looks like there's support for that in Ubuntu Trusty). So you'll only need to install dbgsym packages matching the real packages.

**Comment by oerdnj** [comment]
And I removed the old cruft, so php7.0-dbg should not be available anymore.
