### ISSUE TITLE
php-memcache fails with php 7

### ISSUE THREAD

**Issue by friizer** [oerdnj/deb.sury.org#294]
- ubuntu trusty installed with both 5.6 and 7.0 versions
- symfony 2.8 app with MemcacheSessionHandler

on php5.6 works
on php7.0 login works, but after it immadeitely the session could not be serialized into memcache

session_write_close calls memcache->set which returns false

from tcpdump i see
memcache-set internally  called memcache->delete->memcache->get->memcache->set on php5.6
on php7.0 only memcache->delete called, and after it the memcache->set returns false

Where does the php-memcache 3.0.9~20151130.fdbd46b-2+deb.sury.org~trusty+6 version comes from:?

**Comment by oerdnj** [comment]
> Where does the php-memcache 3.0.9~20151130.fdbd46b-2+deb.sury.org~trusty+6 version comes from:?

Here: https://github.com/websupport-sk/pecl-memcache

**Comment by oerdnj** [comment]
But to tell the truth I think you might have better chance with switching to memcached.

**Comment by oerdnj** [comment]
No reply in month and half. Closing.
