### ISSUE TITLE
missing php7.0-gettext from repo

### ISSUE THREAD

**Issue by shakaran** [oerdnj/deb.sury.org#295]
I am trying to install phpmyadmin from ubuntu package, but it is linked to php-gettext instead php7.0-gettext

Also, there are missing php7.0-gettext in the repository, so I cannot install using PHP 7.0 with your repo

**Comment by oerdnj** [comment]
php-gettext is not an PECL extension, it's PEAR package, so it should be named php-gettext. I uploaded version compatible with php-pear and PHP 7.0 package to the repository right now. It should be available in a moment.

**Comment by shakaran** [comment]
@oerdnj thanks for the quick update. But it seems that the phpmyadmin package provided by ubuntu (even in Xenial), it is requesting by php5 packages:

	sudo apt-get install phpmyadmin 
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	The following additional packages will be installed:
	  dbconfig-mysql libjs-sphinxdoc php-phpseclib php-tcpdf php5-common php5-gd php5-mcrypt
	Suggested packages:
	  php5-libsodium php5-gmp php5-imagick php5-user-cache
	The following NEW packages will be installed:
	  dbconfig-mysql libjs-sphinxdoc php-phpseclib php-tcpdf php5-common php5-gd php5-mcrypt phpmyadmin
	0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
	Need to get 12.6 MB of archives.
	After this operation, 47.9 MB of additional disk space will be used.
	Do you want to continue? [Y/n] 


Not sure if you provide phpmyadmin package too with php7.0 support in your repo

**Comment by oerdnj** [comment]
@shakaran Get it from the phpmyadmin author's PPA: https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin

**Comment by shakaran** [comment]
@oerdnj thanks! I didn't know it about that PPA. Sadly it has the same problem. I will try to reach the developer of the PPA. Thanks again for your support!

**Comment by shakaran** [comment]
Just in case that someone reads this in future or coming from google. Go to this bug:

https://bugs.launchpad.net/ubuntu/+source/phpmyadmin/+bug/1555012?comments=all
