### ISSUE TITLE
Latest release with PHP 7.0.4 is missing bcmath and Zip

### ISSUE THREAD

**Issue by peterrehm** [oerdnj/deb.sury.org#296]
After I upgraded from PHP 7.0.3 to 7.0.4 the extensions bcmath and Zip are not any more available.
I used the same build script (https://github.com/peterrehm/vagrant-boxes) with the packages "php7.0-cli","php7.0-curl","php7.0-common","php7.0-mysql","php7.0-gd","php7.0-intl","php7.0-opcache", "php7.0-dev", "php7.0-fpm".

**Comment by peterrehm** [comment]
Nevermind, saw there are new packages php7.0-zip and php7.0-bcmath.

**Comment by oerdnj** [comment]
@peterrehm Please `apt-get install apt-listchanges`, so you get informed about changes in the packages, it has been properly documented in NEWS.Debian, but it seems nobody read that :(

**Comment by peterrehm** [comment]
Thanks for the info, indeed I was not noticing it as the build is automated. Will follow your changes more closely. My bad was that when looking at the PPA repository I was not looking at the detailed package information and was not seeing bcmath and zip package but found it later through apt-cache.
