### ISSUE TITLE
mbstring enabled

### ISSUE THREAD

**Issue by convertr-deployer** [oerdnj/deb.sury.org#297]
Hi,

Could you compile php7.0 with the --enable-mbstring option?
Would be great!

Thanks

**Comment by oerdnj** [comment]
`apt-get install php-mbstring`

**Comment by convertr-deployer** [comment]
Thanks for your answer

Unfortunatly, It doesn't solve my problem.
When I try to install mailparse using pecl or manually. I get: ```#error The mailparse extension requires the mbstring extension!```

The mbstring extension is enabled and I can find it inside my ```php -m```. 
But it doesn't show up in the ```php-config```

The only way I could find is to have a php version with ```--enable-mbstring```

Any idea how I could fix it without compiling php myself?

**Comment by oerdnj** [comment]
`./configure CFLAGS=-DHAVE_MBSTRING` should work or `apt-get install php-mailparse` in couple of minutes after the new package have finished building.

The check in the mailparse.c is just plain wrong.

**Comment by convertr-deployer** [comment]
Just tried the configure option and it works!
I'll wait the package to built thought to update my scripts.

Thanks for your help! I appreciate :)
