### ISSUE TITLE
Reason for no upstart scripts?

### ISSUE THREAD

**Issue by Schnitzel** [oerdnj/deb.sury.org#298]
The official php5 package: http://packages.ubuntu.com/trusty/php5-fpm and the php5-5.6 package both ship with an `/etc/init/php5-fpm.conf` file.

The newest php package does not ship with such a file, but with old `/etc/init.d/` files
Is there a reason for that? I run into an issue where the service command falls back to `init.d` and tries to do find some processes via process-names, which cases that it finds too many processes and kills them.

If I create an easy  `/etc/init/php7.0-fpm.conf` file, like:

```
# php7.0-fpm - The PHP FastCGI Process Manager

description "The PHP FastCGI Process Manager"
author "Ondřej Surý <ondrej@debian.org>"

start on runlevel [2345]
stop on runlevel [016]

# you can uncomment this with recent upstart
# reload signal USR2

pre-start exec /usr/lib/php/php7.0-fpm-checkconf

respawn
exec /usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf
```

service correctly realizes that it should only stop the "exec" command and no other commands.

thanks

**Comment by oerdnj** [comment]
That's easy. Upstart has been abandoned since Wily/Xenial and it seems like a waste of time to add support for Upstart in new package just for backwards compatibility with Trusty.

**Comment by slauber** [comment]
The current Trusty `php5-fpm_5.6.19+dfsg-1+deb.sury.org~precise+1_amd64.deb` contains a symlink to an upstart job, that does not exist. I think, the `/etc/init.d `script is missing for two releases now.

`/​etc​/​init​.​d​/​php5​-​fpm -> /​lib​/​init​/​upstart​-​job`

Could you please reinsert the old startup script?

**Comment by tobru** [comment]
Seems to be done: https://launchpadlibrarian.net/249678082/php7.0_7.0.4-6+deb.sury.org~trusty+5_7.0.4-7+deb.sury.org~trusty+2.diff.gz

> * Add upstart init script for backport reasons

**Comment by Schnitzel** [comment]
thank you @oerdnj  :heart:

**Comment by AnrDaemon** [comment]
Just because the project doesn't need constant patching is not a reason to call it abandoned.
I was disappointed to see no upstart jobs for MySQL in new updates.
I do not (rather - can not) use systemd as it doesn't let me run certain configurations. (To put it bluntly: systemd is broken by design.)

**Comment by oerdnj** [comment]
@AnrDaemon please keep the discussion free of comments that don't bring any value to the issue as your rant here.
