### ISSUE TITLE
Problem with php-mongodb package

### ISSUE THREAD

**Issue by Oloremo** [oerdnj/deb.sury.org#303]
Current versions of php-mongodb from this PPA is not working with php7 due to this error:
WARNING: pid 16668, fpm_stdio_child_said(), line 191: [pool prod] child 17295 said into stderr: "php-fpm: pool prod: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all"

Its seems to an error with wrong deps of libmongoc, looks like more recent version is needed as pointed here: https://github.com/mongodb/mongo-php-driver/issues/219#issuecomment-181666483

**Comment by oerdnj** [comment]
What's the output of `ldd /usr/lib/php/20151012/mongodb.so` on your system? Can you reproduce this in the clean system?

**Comment by oerdnj** [comment]
@Oloremo And output of `apt-cache policy libbson-1.0-0 libmongoc-1.0-0`.

**Comment by Oloremo** [comment]
Everything was installed yesterday from your repo, Ill send this info tomorrow, cant access this host right now

**Comment by oerdnj** [comment]
@Oloremo Does it happen with PHP 7.0, PHP 5.6 or both? I can reproduce it locally with PHP 5.6 only on Debian Jessie (dunno why, yet).

**Comment by oerdnj** [comment]
@Oloremo Found some missing symbol in the -priv library, adding it now. It might take a while to hunt down all the -priv library symbols, but we'll get there eventually :)

**Comment by Oloremo** [comment]
@oerdnj I tested it only with 7.0

**Comment by oerdnj** [comment]
@Oloremo I've decided to use bundled libmongoc library for now. Not optimal, but other solutions take just too much time. Let's just hope upstream will solve that for 1.4.0.

I'll upload fixed package in couple of minutes.

**Comment by oerdnj** [comment]
Should be fixed when `php-mongodb - 1.1.4-1+deb.sury.org~*+4` finishes building.
