### ISSUE TITLE
php-pear incorrect installation path

### ISSUE THREAD

**Issue by randompixel** [oerdnj/deb.sury.org#304]
On 5.6, PEAR is installed in `/usr/share/php`. On 7.0, it is installed in `/usr/lib/php/pear`.

The latter is not added to the include_path (or in it by default like `/usr/share/php` is). I think this is a regression from the previous version.

**Comment by oerdnj** [comment]
JFTR it still belongs to `/usr/share/php`, but php-pear is built from different source package, so it lost the original settings from php source build. I'll look into it directly in Debian where it's broken right now as well.

**Comment by oerdnj** [comment]
Sigh, I will need to build PEAR from inside `src:php7.0` and `src:php5.6`, but don't install it to have `PEAR_INSTALL_DIR` defined. I just love magic variables :-/. Will be fixed today.

**Comment by oerdnj** [comment]
Fixed most of the changed values back to the original state. Just sysconfdir is still just `/etc` instead of original `/etc/pear`. Tracked here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818271

**Comment by randompixel** [comment]
```
PEAR directory                 php_dir          /usr/share/php
```

Great thanks :)

**Comment by oerdnj** [comment]
@randompixel Thanks to you, the issue didn't went unnoticed and was fixed for all Debian/Ubuntu PHP users, so you are the hero here :)
