### ISSUE TITLE
PHP 5.6 is missing dom extension

### ISSUE THREAD

**Issue by rowanparker** [oerdnj/deb.sury.org#305]
Refer to this ticket for more information:
https://github.com/puphpet/puphpet/issues/2221

Using a freshly created version box with PHP 5.6 gives me:

```
$ php -m
[PHP Modules]
calendar
Core
ctype
date
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
mbstring
mhash
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache
```
Running a composer install gives me

`phpunit/phpunit 4.8.18 requires ext-dom * -> the requested PHP extension dom is missing from your system.`

Which previously worked as late as two weeks on a box I built then.

**Comment by oerdnj** [comment]
It's not. XML related extensions are in phpX.Y-xml

**Comment by tersmitten** [comment]
As far as I know `ext-dom` was build-in in the (old) 5.6 ppa. @oerdnj Can you confirm?

**Comment by oerdnj** [comment]
Have no idea what `ext-dom` is, but as I said, the DOM extension is now in `phpX.Y-xml` package (f.e. `php7.0-xml`)
