### ISSUE TITLE
[PHP 7.0] Add PHP 7.0 support to src:twig

### ISSUE THREAD

**Issue by andrewtch** [oerdnj/deb.sury.org#307]
Hi,

IT would be nice to have two extensions - thrift (for apache thrift) and twig (for twig template acceleration). Thrift has support for php7, twig in the works.

If you can point be out hot to help you porting them, I'd help gladly.

**Comment by oerdnj** [comment]
@andrewtch Where are the code repositories? Both for PHP 5.6 and PHP 7.0?

**Comment by andrewtch** [comment]
@oerdnj , thrift is here: https://github.com/apache/thrift/tree/master/lib/php/src/ext/thrift_protocol
and twig is here: https://github.com/twigphp/Twig/tree/master/ext/twig

**Comment by andrewtch** [comment]
Hi, any progress on that / any help needed?

**Comment by oerdnj** [comment]
Just lack of time. Not much you can do about it. But I keep it in mind for next bigger chunk of free time.

**Comment by oerdnj** [comment]
@andrewtch twig hasn't been updated to PHP 7.0 yet, so cannot do anything here really.

**Comment by andrewtch** [comment]
@oerdnj , twig phpizes and compiles for me for 7.0.4 (PHP Api Version:         20151012, Zend Module Api No:      20151012, Zend Extension Api No:   320151012). Did you check it out?

**Comment by oerdnj** [comment]
It doesn't compile:
```
$ make
/bin/bash /tmp/Twig/ext/twig/libtool --mode=compile cc  -I. -I/tmp/Twig/ext/twig -DPHP_ATOM_INC -I/tmp/Twig/ext/twig/include -I/tmp/Twig/ext/twig/main -I/tmp/Twig/ext/twig -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/Twig/ext/twig/twig.c -o twig.lo 
libtool: compile:  cc -I. -I/tmp/Twig/ext/twig -DPHP_ATOM_INC -I/tmp/Twig/ext/twig/include -I/tmp/Twig/ext/twig/main -I/tmp/Twig/ext/twig -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/Twig/ext/twig/twig.c  -fPIC -DPIC -o .libs/twig.o
/tmp/Twig/ext/twig/twig.c:23:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include "ext/standard/php_smart_str.h"
                                        ^
compilation terminated.
Makefile:193: recipe for target 'twig.lo' failed
make: *** [twig.lo] Error 1
```

Both `master` and `1.x` branch is using PHP 5.x style includes.

**Comment by andrewtch** [comment]
Can you explain for a noob what is fixable? I can make a PR for twig.

**Comment by oerdnj** [comment]
Most of the specifics are written in UPGRADING.INTERNALS file in PHP distribution tarballs. I am sure you might also be able to find some online blogpost about rewriting the extensions for PHP 7.0. Last but not least you might look at some other extensions (pecl.php.net/uuid comes to mind) how to convert the extensions to PHP 7.0.

Or try using this: https://github.com/flaupretre/pecl-compat

**Comment by stof** [comment]
the C extension for Twig has not been rewritten for PHP 7 for now, and there is no immediate plan for that. This C extension provides a single function implementing an algorithm in C to replace the implementation provided in ``Twig_Template::getAttribute``. The userland implementation running in PHP 7 is already faster than the C implementation running in PHP 5.6, which is why this rewrite has not been planned.

**Comment by oerdnj** [comment]
I suspected so, closing the bug.
