### ISSUE TITLE
/var/run/php not created

### ISSUE THREAD

**Issue by magnetik** [oerdnj/deb.sury.org#309]
Hi,

On a 14.04 ubuntu, after the installation of php7.0-fpm, the folder `/var/run/php` was not created. As a consequence, the sock file can't be created, and php-fpm doesn't start.

**Comment by oerdnj** [comment]
I am guessing, is that already the version with upstart, right?

**Comment by magnetik** [comment]
It's `7.0.4-6+deb.sury.org~trusty+4`

**Comment by oerdnj** [comment]
Darn, I knew supporting one more init system was a bad idea. I'll fix that in next upload.

**Comment by magnetik** [comment]
Great, thanks for the fast answer :+1:

**Comment by oerdnj** [comment]
@magnetik `+5` versions that are building right now should have the fix in the `/usr/lib/php/php7.0-fpm-checkconf`. Feel free to reopen, if it's not the case.
