### ISSUE TITLE
Consider including php-tcpdf in your great PPA

### ISSUE THREAD

**Issue by normadize** [oerdnj/deb.sury.org#311]
First, thanks for all your work on the php PPAs! 

The following is somewhat related to https://github.com/oerdnj/deb.sury.org/issues/295

In installing phpmyadmin from either Xenial or the nijel's PPA, I've hit a similar issue in that one of the dependencies, namely `php-tcpdf`, wanted to install php5 (specifically `php5-common`, `php5-gd`, `php5-mcrypt`, `libphp5.6-embed`) when in fact I already had the php7.0 alternatives installed from your great PPA.

I tracked it down to a bug in the package definition for `php-tcpdf` and filed a bug and also a fix on Launchpad already, see: https://bugs.launchpad.net/ubuntu/+source/tcpdf/+bug/1562046

I think it would be worthwhile to include the `php-tcpdf` package in your php7.0 PPA (would also be easy as it doesn't need compiling) so those of us using your php7.0 PPA can install packages like `phpmyadmin` without having to upgrade to Xenial and wait for the devs to fix the `php-tcpdf` bug.

All of the following directly depend on php-tcpdf and would therefore benefit directly:

     phpmyadmin
     civicrm-common
     php-phpdocx
     php-dompdf
     dolibarr
     collabtive

**Comment by oerdnj** [comment]
JFTR I think it might be easier to just install tcpdf with:
`pear install tcpdf`
and generate dummy package with `equivs`:
```
$ apt-cache show equivs
Package: equivs
Version: 2.0.9+nmu1
Installed-Size: 54
Maintainer: Peter Samuelson <peter@p12n.org>
Architecture: all
Depends: perl, debhelper, dpkg-dev, make, fakeroot
Description-en: Circumvent Debian package dependencies
 This package provides a tool to create trivial Debian packages.
 Typically these packages contain only dependency information, but they
 can also include normal installed files like other packages do.
 .
 One use for this is to create a metapackage: a package whose sole
 purpose is to declare dependencies and conflicts on other packages so
 that these will be automatically installed, upgraded, or removed.
 .
 Another use is to circumvent dependency checking: by letting dpkg
 think a particular package name and version is installed when it
 isn't, you can work around bugs in other packages' dependencies.
 (Please do still file such bugs, though.)
Description-md5: eecadd6e89bb6f575d54f8f256a154aa
Tag: admin::package-management, devel::packaging, implemented-in::perl,
 interface::commandline, role::program, scope::utility, suite::debian,
 works-with::software:package
Section: admin
Priority: extra
Filename: pool/main/e/equivs/equivs_2.0.9+nmu1_all.deb
Size: 19838
MD5sum: a878bb49bb7e04b9f3072906fee387b6
SHA1: cb563d564709d240024aec9a4efa367be3fbcac0
SHA256: 36fae0b679c96e656ed985c83e463c39d6375012736152e976de63734989dbd0
```

Or just install php5-cli that would satisfy the dependency chain for php-tcpdf.

**Comment by normadize** [comment]
To the users of your PPA, that's definitely more complicated than having php-tcpdf included properly in your PPA by default.

I've already fixed in my case by fixing the dependency defs (I don't want any php5 packages if I'm using php7 exclusively).

**Comment by oerdnj** [comment]
Adding `ppa:ondrej/php5-compat` will solve all those dependency issues on old packages.
