### ISSUE TITLE
the apache2 package does not provide ufw profiles

### ISSUE THREAD

**Issue by qnxor** [oerdnj/deb.sury.org#312]
Title should be enough. I've been using your apache2 package in Trusty and noticed it doesn't include the ufw profile files like the official packages do, see http://packages.ubuntu.com/search?suite=trusty&arch=any&mode=filename&searchon=contents&keywords=apache2-utils.ufw.profile

Keep up the great work!

**Comment by oerdnj** [comment]
Is it really that helpful as opposed to `ufw allow 443/tcp` ?

**Comment by qnxor** [comment]
It would just make your package more complete. The official Ubuntu Apache2 packages do offer ufw profiles for both unsecure and secure ports, 80 and 443, which get (de)activated automatically when you (un)install apache2.

**Comment by oerdnj** [comment]
I don't think this is actually helpful. I don't consider the automatic holes in the firewall as a something that should be done on package installation. Sorry.

**Comment by qnxor** [comment]
You're providing packages for an OS that has this tradition. Your views are at odds with it. But as long as Ubuntu allows it ...
