### ISSUE TITLE
Technical reason for OpenSSL in Apache2 Repository

### ISSUE THREAD

**Issue by drubb** [oerdnj/deb.sury.org#314]
Just a question: is there a technical reason for including openssl in the apache2 repo? I've got some issues trying to build php 5.3 after installing apache2 on ubuntu 14.04, resulting from openssl upgraded unintentionally to 1.0.2g, and had to downgrade it to default version 1.0.1f.
I see no security issues, as openssl should be maintained by ubuntu.

**Comment by oerdnj** [comment]
HTTP/2, see #125
