### ISSUE TITLE
apt-get install php5-curl fails with a strange error

### ISSUE THREAD

**Issue by i-fail** [oerdnj/deb.sury.org#316]
I'm on Ubuntu 15.04 and using **ppa:ondrej/php5-5.6** (I think)

So I get this weird error:

```
apt-get install php5-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-curl : Depends: php5-common (= 5.6.4+dfsg-4ubuntu6.4) but 5.6.18+dfsg-1+deb.sury.org~vivid+1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

I've been searching for hours, tried a few different things, and still failed.

Things I tried:

apt-get update
apt-get upgrade
apt-get autoclean $$ apt-get clear cache
apt-get update --fix-missing
aptitude install php5-curl  (which offered to uninstall all kinds of things, including most of PHP).

Here's the output of  **apt-cache policy php5**:
```
php5:
  Installed: (none)
  Candidate: 5.6.4+dfsg-4ubuntu6.4
  Version table:
     5.6.4+dfsg-4ubuntu6.4 0
        500 http://archive.ubuntu.com/ubuntu/ vivid-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ vivid-security/main amd64 Packages
     5.6.4+dfsg-4ubuntu6 0
        500 http://archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
```

**Comment by oerdnj** [comment]
Looks like you are _not_ using the PPA, but you are using some older packages that come from the PPA. Look into `/etc/apt/sources.list.d/` it should have a file related to ppa with .list extension.

**Comment by oerdnj** [comment]
Just an idea? Are you using Ubuntu vivid? Upgrade to wily, as vivid has be discontinued.

**Comment by i-fail** [comment]
Could you please explain how I'm not using the PPA? I have this in my command history, that's how I installed PHP:

LANG=en_GB.UTF-8 add-apt-repository ppa:ondrej/php5-5.6

I definitely did not manually download some packages, I did everything through apt-get.

**Comment by oerdnj** [comment]
@i-fail As I said in next comment - are you using vivid? Looks like it according to version numbers. Ubuntu vivid is not supported neither by Canonical nor by this PPAs.
