### ISSUE TITLE
PHP 5.6/7.0 in Ubuntu Xenial

### ISSUE THREAD

**Issue by thirdeyenick** [oerdnj/deb.sury.org#318]
Hi,
as there was a final decision about removing PHP 5.x support from Ubuntu Xenial we are thinking about how to get PHP 5.6 support back into Xenial. As PHP 5.4 for Ubuntu Precise in your PPA is almost EOL we need to upgrade to a new distribution. We would like to upgrade directly to Xenial as otherwise we would need to upgrade twice (first Trusty, then Xenial).
Yesterday I tested your PHP 5.6/7.0 PPA on Ubuntu 16.04 and it worked quite well. As we would depend very strong on you when using your PPA in Ubuntu Xenial we ask ourselves a few questions now:
- How fast do security updates get in?
- How long are you going to support Xenial in the 5.6/7.0 PPA?
- There is also the possibility to mirror the PPA on our side and filter out any PHP 7.0 packages. This way we could use PHP 7.0 from Ubuntu directly and PHP 5.6 from your PPA. This is a very ugly solution and we are afraid that there might be version dependencies one day which hinder us on upgrading one or the other. What is your opinion about it?

Beside those questions, we really want to thank your for your PPAs and the effort and time you spend on them.

**Comment by oerdnj** [comment]
> How fast do security updates get in?
Usually next day or couple of days. But I am also a human and I also travel from time to time, take vacation, etc.
> How long are you going to support Xenial in the 5.6/7.0 PPA?
My policy is to support at least two LTS at the time (that would be 2020), but you have to mix&match that with security support from PHP: http://php.net/supported-versions.php and neither PHP 5.6 nor PHP 7.0 won't make it past 2019.
> There is also the possibility to mirror the PPA on our side and filter out any PHP 7.0 packages.
I think it might be ok. But if you take precautions (like testing the upgrade before deploying it), you should be fine with PHP 7.0 updates as well. The upstream PHP release has some hiccups from time to time, but the overall quality of the patch releases has gone up several levels.

Also the dust has settled now and the only bigger change I have on my TODO list is dropping ucf for ext.ini handling. I also have a php-qa repository that I use to land bigger changes first.

**Comment by thirdeyenick** [comment]
Thank you very much for the information. We might look into the 'mirror & filter' idea and see if it works. Thanks again for the great PPA!

**Comment by oerdnj** [comment]
@thirdeyenick Thanks!
