### ISSUE TITLE
enable-zip

### ISSUE THREAD

**Issue by dbajet** [oerdnj/deb.sury.org#320]
Thank you very much for providing this nice debian package.

When using it I have noticed that the ZipArchive class is not accessible.

My understanding is that the flag `--enable-zip` should be added when compiling the PHP code.

If that is confirmed, would you consider to add it?

Thanks
Denis

**Comment by oerdnj** [comment]
Would you consider searching for a package before filling a bug next time, please?
`apt-cache search php zip`
