### ISSUE TITLE
Lastest apache2 broken

### ISSUE THREAD

**Issue by auroraeosrose** [oerdnj/deb.sury.org#326]
ppa:ondrej/php5-5.6
ubuntu 14.04
apache2  	2.4.20-1+deb.sury.org~trusty+2

on ubuntu the following issue occurs when trying to install/upgrade apache2

https://gist.github.com/auroraeosrose/17620f08376a6d54ad09541c8418160f

This worked perfectly before the new package  release

**Comment by JakeWorrell** [comment]
I can confirm that I also get this issue. I'm not sure how I can get around it either as I don't seem to be able to force Ubuntu to install an earlier version.

**Comment by ChrisWiegman** [comment]
Looks like a2enmod has broken, as some of the apache packages are also listed as broken on the repo page perhaps this is related?

**Comment by JakeWorrell** [comment]
a2ensite and a2dissite also return the exact same errors, right down to the line numbers:
`a2dissite
syntax error at /usr/sbin/a2dissite line 564, near ") {"
syntax error at /usr/sbin/a2dissite line 572, near "}"
syntax error at /usr/sbin/a2dissite line 589, near "}"
Execution of /usr/sbin/a2dissite aborted due to compilation errors.`

**Comment by oerdnj** [comment]
As a fast remedy before the next apache2 package builds use this patch:
```
$ git diff
diff --git a/debian/a2enmod b/debian/a2enmod
index f65877e..be84145 100755
--- a/debian/a2enmod
+++ b/debian/a2enmod
@@ -11,6 +11,7 @@ use File::Spec;
 use File::Basename;
 use File::Path;
 use Getopt::Long;
+use feature qw(switch);
 no if $] >= 5.017011, warnings => 'experimental::smartmatch';
 
 my $quiet;
```

**Comment by JakeWorrell** [comment]
Thanks @oerdnj, How long should we expect to have to wait until the next package will be built? If it's in the next hour or so it's probably easier for me to wait

**Comment by oerdnj** [comment]
Or slightly better one:
```
$ git diff
diff --git a/debian/a2enmod b/debian/a2enmod
index f65877e..be84145 100755
--- a/debian/a2enmod
+++ b/debian/a2enmod
@@ -11,6 +11,7 @@ use File::Spec;
 use File::Basename;
 use File::Path;
 use Getopt::Long;
+use 5.014;
 no if $] >= 5.017011, warnings => 'experimental::smartmatch';

 my $quiet;
```

Anyway fixed packages has been just uploaded - Look for `2.4.20-1+deb.sury.org~*+3` and you can check the build status: 
https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6/+builds?build_text=apache2&build_state=all
https://launchpad.net/~ondrej/+archive/ubuntu/php5/+builds?build_text=apache2&build_state=all

**Comment by JakeWorrell** [comment]
Great, thank you @oerdnj

**Comment by oerdnj** [comment]
@JakeWorrell Almost done - fortunately apache2 builds takes just ~5 minutes.

**Comment by auroraeosrose** [comment]
thanks :)
