### ISSUE TITLE
Broken dependencies installing php5-gd

### ISSUE THREAD

**Issue by gristc** [oerdnj/deb.sury.org#328]
Hi,

I'm trying to install PHP5 onto Ubuntu 16.04LTS to support some Drupal web sites. I have enabled your excellent repository, but have come across a dependency issue trying to install php5-gd. Apt-get install says it depends on libgd3, which in turn depends on libvpx1 which is apparently missing.

Should I be able to install php5-gd from your repository, or is there somewhere else to go for older versions of modules like this?

Regards,
grist.

**Comment by oerdnj** [comment]
@gristc There's no `php5-gd` available for Ubuntu 16.04. Could you do `apt-cache policy php5-gd` and paste output here?

**Comment by oerdnj** [comment]
The supported packages for Ubuntu 16.04 LTS are in `ppa:ondrej/php` and GD extension would be installed with `apt-get install php5.6-gd`.

**Comment by gristc** [comment]
Thanks for the quick reply. I have added the ppa:/ondrej/php repository, but attempting to install php5.6-gd is giving the same dependancy problem as I was getting with php5-gd...

 php5.6-gd : Depends: libgd3 (>= 2.1.1)
 libgd3 : Depends: libvpx1 (>= 1.0.0) but it is not installable

apt-cache search libvpx1 gives no results.

We're probably going to stick with 14.04 for now, so don't put too much time into this if I'm the only one affected.

Cheers,
grist.

**Comment by oerdnj** [comment]
I did a new upload yesterday, so can't check the previous version, but right now, the `php5.6-gd` can be installed just fine:
```
# apt-get install php5.6-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  php5.6-gd
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/28.5 kB of archives.
After this operation, 142 kB of additional disk space will be used.
Selecting previously unselected package php5.6-gd.
(Reading database ... 23217 files and directories currently installed.)
Preparing to unpack .../php5.6-gd_5.6.21~rc1+really.5.6.20+json-1+donate.sury.org~xenial+2_amd64.deb ...
Unpacking php5.6-gd (5.6.21~rc1+really.5.6.20+json-1+donate.sury.org~xenial+2) ...
Setting up php5.6-gd (5.6.21~rc1+really.5.6.20+json-1+donate.sury.org~xenial+2) ...

Creating config file /etc/php/5.6/mods-available/gd.ini with new version
```
