### ISSUE TITLE
New v0.76.0 courier-mta released

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#329]
Download: http://www.courier-mta.org/download.html

Changes:

- courier, courier-imap: add support for TLS SNI when Courier is built with OpenSSL.
- courier: "mx" SPF keyword ignores hosts without an MX, instead of returning an error.
- maildrop: fix parsing a message without a body, and without a blank line that separates the message's headers from its body. This did not affect Courier which always inserts a blank line after headers, even if a received message didn't have one.
- maildrop: fix maildrop not searching the last line of a text message.
- maildrop: FLAGS variable sets message flags when delivering a message to a maildir.
- Add Received-SPF: headers for the message envelope sender before the first Received: header. The Received-SPF: header for the HELO domain, if enabled, wasn't being added to the message due to a bug.
- courier-imap: explicitly flush unread input when executing STARTTLS.
- all: Added BuildRequires: perl-generators to the Fedora rpm spec file.
- courier, courier-imap: fix compilation warnings.

**Comment by markc** [comment]
It looks like you have already built courier-mta 0.76.0 so this may be related. This package depends on libmysqlclient18 but xenial only has libmysqlclient20...

    Package: courier-authlib-mysql
    Version: 0.66.4-7+deb.sury.org~xenial+1
    Depends: courier-authlib (>= 0.66.4-7+deb.sury.org~xenial+1), libc6 (>= 2.4), libmysqlclient18

**Comment by oerdnj** [comment]
Unrelated. I built the new 0.76 after you filled this bug. Please fill a separate issue for the libmysqlclient on Ubuntu 16.04 and I'll look into that when children are in the bed :)
