### ISSUE TITLE
[courier] courier-authlib-mysql xenial depends on old libmysqlclient18

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#330]
The courier-authlib-mysql package depends on libmysqlclient18 but xenial only has libmysqlclient20. This xenial package needs to be built against libmysqlclient20.

    Package: courier-authlib-mysql
    Version: 0.66.4-7+deb.sury.org~xenial+1
    Depends: courier-authlib (>= 0.66.4-7+deb.sury.org~xenial+1), libc6 (>= 2.4), libmysqlclient18

**Comment by oerdnj** [comment]
I don't see anything obvious that would cause that, so I am trying to just rebuild the packages, if that helps. Perhaps it was compiled before Xenial has finalized MySQL version.

**Comment by markc** [comment]
That's odd. `apt show courier-authlib-mysql` definitely shows a dependency on libmysqlclient18 so it "must" be specified in the rules makefile... or I would think it would be. Hopefully a simple rebuild under an updated xenial system will fix it.

**Comment by oerdnj** [comment]
Looks good to me now:
```
# apt-cache show courier-authlib-mysql
Package: courier-authlib-mysql
Source: courier-authlib
Priority: optional
Section: mail
Installed-Size: 63
Maintainer: Stefan Hornburg (Racke) <racke@linuxia.de>
Architecture: amd64
Version: 0.66.4-7+deb.sury.org~xenial+2
Depends: courier-authlib (>= 0.66.4-7+deb.sury.org~xenial+2), libc6 (>= 2.4), libmysqlclient20 (>= 5.7.11)
Filename: pool/main/c/courier-authlib/courier-authlib-mysql_0.66.4-7+deb.sury.org~xenial+2_amd64.deb
Size: 19032
MD5sum: 14b18c63438f9dbae302a78c39a3a9f0
SHA1: 5a1eb12bf6cfe6db9e7f305c8dc0fff5b26f4aef
SHA256: 97bdfa8a92f4cf4015206391be78d5b7ad48fd3a602ba2c5d82e1f63d86296fc
Description-en: MySQL support for the Courier authentication library
 This package contains the MySQL support for the Courier
 authentication library.
Description-md5: f305ead8efa36cfda2d75a0673c57eec
```

**Comment by markc** [comment]
Yep, all good...

    The following packages will be REMOVED:
        libmysqlclient18

BTW I will be running these 0.76.0 packages on a server with a few 1000 active mail users within the next week or two so that will be a good test. Or not :-)
