### ISSUE TITLE
[php-7.0] request for extension gearman

### ISSUE THREAD

**Issue by laurenzgamper** [oerdnj/deb.sury.org#331]
Hi,

It would be great to have the php-gearman extension in this ppa https://launchpad.net/~ondrej/+archive/ubuntu/php . There seemst to be a php-gearman version supporting php7: https://github.com/hjr3/pecl-gearman/issues/12 .

Thanks for the great work!

**Comment by oerdnj** [comment]
Done, I already had it prepared, but nobody has asked for it.

**Comment by dmitriivoitovich** [comment]
Hello! There is one problem with GearmanClient, installed from **ppa:ondrej/php**. The addOptions method should have only one argument http://php.net/manual/ru/gearmanclient.addoptions.php, but it actually have two.

```
string(125) "Method [ <internal:gearman> public method addOptions ] {

  - Parameters [1] {
    Parameter #0 [ <required> $option ]
  }
}
```

**Comment by oerdnj** [comment]
@dmitriivoitovich You need to report it here: https://github.com/wcgallego/pecl-gearman/ (See https://github.com/hjr3/pecl-gearman/issues/12)

**Comment by winks** [comment]
@oerdnj Tangentially related, is there a reason why this is not available for ubuntu precise (12.04)? If not, would it be possible to get that as well, if it's not too complicated? Testing some upgrade path with manually built pecl-gearman atm, but every other ext I need is there and works.

**Comment by oerdnj** [comment]
@winks Uploaded for precise, I'll check later if it has built correctly...

**Comment by winks** [comment]
Thanks for the quick response.

Apparently the `libgearman` version in precise is too old.

From [buildlog](https://launchpadlibrarian.net/271016604/buildlog_ubuntu-precise-amd64.php-gearman_1.1.2-96-ge77f981+1.1.2+-2+deb.sury.org~precise+1_BUILDING.txt.gz)

```
configure: error: libgearman version 1.1.0 or later required
```

On my machine:
```
ii  libgearman-dev                   1.0.6-2+debphp.org~precise+2                            Development files for the Gearman Library
ii  libgearman6                      0.27-5ubuntu3                                           Library providing Gearman client and worker functions
ii  libgearman7                      1.0.6-2+debphp.org~precise+2                            Library providing Gearman client and worker functions
```

**Comment by oerdnj** [comment]
Yup, I noticed, but you'll have to be patient. I taking time off this week... Ping me mid next week if nothing happens by then.

**Comment by winks** [comment]
Ping. 
Not trying to be annoying, sorry :)

**Comment by oerdnj** [comment]
@winks Took me a while to tackle gearmand to build on Ubuntu 12.04. Also gearman has been unmaintained for a while, so I had to take the current git master from https://github.com/gearman/gearmand

**Comment by winks** [comment]
@oerdnj Awesome, thanks a lot!
