### ISSUE TITLE
igbinary support missing from latest memcached?

### ISSUE THREAD

**Issue by Jud** [oerdnj/deb.sury.org#333]
Just installed `memcached-3.0.0a1-13-g6ee96ca+2.2.0-2+donate.sury.org~trusty+1` and it looks like it was built without igbinary support which differs from previous versions. Is this intended?

Output from `php -i`
```
memcached

memcached support => enabled
Version => 3.0.0b1
libmemcached version => 1.0.18
SASL support => yes
Session support => yes
igbinary support => no
json support => no
msgpack support => no

igbinary

igbinary support => enabled
igbinary version => 1.2.2-dev
igbinary APC serializer ABI => no
igbinary session support => no
```

**Comment by uduncanu** [comment]
I'm seeing the same issue. Upgraded from 3.0.0a1-10-gffd1c64+2.2.0-1+deb.sury.org~xenial+1 to the latest and it stopped working. Downgrading back has got it working again.

**Comment by oerdnj** [comment]
Side-effect of unifying the build scripts, `3.0.0a1-13-g6ee96ca+2.2.0-3` will have the fix as soon as it is built.

**Comment by oerdnj** [comment]
@Jud @uduncanu The update packages has been finally published. If you update now, you'll get igbinary serialization in memcached back.

**Comment by Jud** [comment]
Thanks for the quick work Ondřej!

**Comment by oerdnj** [comment]
@Jud And sorry for the breakage. I was updating 30+ packages at one go and simply forgot about extra parameters for this.
