### ISSUE TITLE
Add mod_wsgi compiled for Python 3

### ISSUE THREAD

**Issue by maedox** [oerdnj/deb.sury.org#336]
Please consider supporting a libapache2-mod-wsgi-py3 for Ubuntu 14.04.

**Comment by oerdnj** [comment]
Fortunately Python folks are not as crazy as Ruby people, so the backport was piece of cake. Should be published any moment now.

**Comment by maedox** [comment]
Good to hear. I will test it later today. :smiley:

**Comment by maedox** [comment]
As far as I can tell it works like a charm. Thank you so much!

How likely is it that'll you'll be able to get the package updated to use mod_wsgi 4.5.2? There's not much I need since 4.3.0, but it would be nice to have any bug fixes included.

**Comment by oerdnj** [comment]
Could you please try mod_wsgi 4.5.2 from `ppa:ondrej/apache2-qa` first and confirm that everything works as expected?

**Comment by maedox** [comment]
Great! 
Yes, I have tested five different applications and they run perfectly.

**Comment by oerdnj** [comment]
Ok, copied 4.5.2 to `ppa:ondrej/apache2` now.

**Comment by maedox** [comment]
Perfect. Thank you. :bow:
