### ISSUE TITLE
php5.6-xcache missing

### ISSUE THREAD

**Issue by hafkenscheid** [oerdnj/deb.sury.org#337]
php5.6-xcache is missing in http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php5.6/
See also https://github.com/puphpet/puphpet/issues/2157

Thanks!

**Comment by oerdnj** [comment]
Please try `php-xcache` from `ppa:ondrej/php-qa`, I'll upload it to the main repo, when everything works out.

**Comment by oerdnj** [comment]
The package looks correct, so it has been uploaded to the main repository.

**Comment by ashutoshtyagi** [comment]
I am using your repo to install and run my website using php 5.6 on ubuntu 16.10. But I am getting an error "PHP Fatal error:  Uncaught exception 'Exception' with message 'PHP Xcache extension is not available.'". I added repo ppa:ondrej/php-qa and then did apt-get install php5.6-xcache but it is not available. Where can I install xcache from?
