### ISSUE TITLE
Php7.0 Sybase not loading date format from Freetds

### ISSUE THREAD

**Issue by andremoniz** [oerdnj/deb.sury.org#338]
The bug is that php7.0-sybase is not loading locales.conf date format from freetds.

If I go back to php5 it works.
The locales.conf has 
[default]
        date format = %Y-%m-%d %H:%M:%S.%z

But when results come from database it returns in this format:
%Y-%m-%d %H:%M:%S

freetds version 8.0.

PHP 7.0.6-1+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by oerdnj** [comment]
@andremoniz Could you try with `php5.6-sybase`? If it works, then it's an upstream bug and needs to be reported to https://bugs.php.net/how-to-report.php

**Comment by andremoniz** [comment]
When I try with php5 env it works. 
How would you suggest to try that package with php7? is this possible?

**Comment by oerdnj** [comment]
No, it's not possible. Report this to the upstream bugtracker as mentioned before. And report the URL back here.

**Comment by oerdnj** [comment]
@andremoniz did you report the bug upstream? can you recheck whether 7.0.7 exhibits the same (faulty) behaviour?

**Comment by oerdnj** [comment]
No response since May 2016, closing.
