### ISSUE TITLE
Package php "redis" extension

### ISSUE THREAD

**Issue by marek-obuchowicz** [oerdnj/deb.sury.org#34]
Is there any chance that you could add PHP 5.4/5.5
extenstion "redis" (available via pecl, exists for example at
http://packages.dotdeb.org wheezy all) for Precise to your great
repository?

**Comment by oerdnj** [comment]
@marek-obuchowicz The extension already exists for PHP 5.5. I am sorry, but no more modules for PHP 5.4 as the module build system has changed meanwhile and it's simply too much work to package the module for both build systems.
