### ISSUE TITLE
MySQL defaults

### ISSUE THREAD

**Issue by zuiguniang** [oerdnj/deb.sury.org#340]
Hi,

MySQL is not related to PHP directly, but is usually used in conjunction. Every time there is an update to MySQL (5.6), the defaults are changed, and MySQL is not started automatically on boot. I have to manually issue sudo update-rc.d mysql defaults to make it work as intended.

**Comment by stof** [comment]
mysql is not provided by this package repository, so this is not reported to the right people

**Comment by zuiguniang** [comment]
same package author

**Comment by oerdnj** [comment]
There's simply not enough information to make anything out of it. Add the Ubuntu version, MySQL packages version, the PPAs used and how do you perform the upgrade, the log of what's happening at the upgrade time and with all the relevant information re-open the bug.
