### ISSUE TITLE
php7.0.6 not starting

### ISSUE THREAD

**Issue by geoff-gedde** [oerdnj/deb.sury.org#341]
We just launched a new PHP server and php7.0-fpm is not starting.
After further review the only thing that changed was that the php version is now at 7.0.6

`sudo service php7.0-fpm restart`
> stop: Unknown instance: 
> php7.0-fpm start/running, process 31224

If I run it again I keep getting the same results
Start does show it starting, but if I run status it shows it as not running.

`sudo service php7.0-fpm status`
> php7.0-fpm stop/waiting

Has anything changed in the update that requires anything different in the fpm settings?

**Comment by geoff-gedde** [comment]
Also is there a way that we can specifically install a certain version.  I really don't like the idea that when a new version is updated that it could break an install.  We use Chef to install new servers and so our configurations files are setup with certain settings.  I would prefer that we always install 7.0.5

**Comment by mwalcott** [comment]
I have the same issue right now.

**Comment by Kiaatix** [comment]
Same here

Syslog:

> kernel: [  502.183933] init: php7.0-fpm main process (1652) terminated with status 78

**Comment by andrew-boyd** [comment]
I'm experiencing this same issue when attempting to use Trellis by Roots.io to provision a new box. Relevant support topic that lead me here: [https://discourse.roots.io/t/502-bad-gateway-php-wont-start/6677/21](https://discourse.roots.io/t/502-bad-gateway-php-wont-start/6677/21)

**Comment by mwalcott** [comment]
I am using trellis. Ben said this happened about a month ago and people were experiencing the same thing.

**Comment by oerdnj** [comment]
What does `php-fpm7.0 -t` say? And what's the return code? And what does `/usr/lib/php/php7.0-fpm-checkconf` report?

**Comment by geoff-gedde** [comment]
`sudo php-fpm7.0 -t`
> [09-May-2016 23:36:35] NOTICE: configuration file /etc/php/7.0/fpm/php-fpm.conf test is successful

`sudo /usr/lib/php/php7.0-fpm-checkconf`
Reports nothing

**Comment by geoff-gedde** [comment]
Here is the contents of /usr/lib/php/php7.0-fpm-checkconf
`#!/bin/sh
/usr/sbin/php-fpm7.0 -t >/dev/null 2>/dev/null
ret=$?
if [ "$ret" -ne 0 ]; then
    echo "PHP FPM configuration is broken:"
    /usr/sbin/php-fpm7.0 -t
    exit 1
fi
exit 0`

Running /usr/sbin/php-fpm7.0 -t is the same as above
`sudo /usr/sbin/php-fpm7.0 -t`
> [09-May-2016 23:38:47] NOTICE: configuration file /etc/php/7.0/fpm/php-fpm.conf test is successful

**Comment by oerdnj** [comment]
@geoff-gedde And:
```
php-fpm7.0 -t
echo $?
```
I wonder if php-fpm7.0 might return non-zero exit code even if the configuration file is correct.

**Comment by iam404** [comment]
Same here
In my case it looks like **/run/php** directory was not created which was needed for .pid file . Though manually creating the folder and restarting service solved the issue but still i get following while I do service php7.0-fpm status : 
```
sudo service php7.0-fpm status
    php7.0-fpm stop/waiting
```

**Comment by oerdnj** [comment]
@iam404 Could you try this patch:
```
diff --git a/debian/php-fpm.upstart b/debian/php-fpm.upstart
index 6b2ebef..c164d61 100644
--- a/debian/php-fpm.upstart
+++ b/debian/php-fpm.upstart
@@ -9,7 +9,12 @@ stop on runlevel [016]
 # you can uncomment this with recent upstart
 # reload signal USR2
 
-pre-start exec /usr/lib/php/php7.0-fpm-checkconf
+pre-start script
+mkdir -p /run/php
+chmod 0755 /run/php
+chown www-data:www-data /run/php
+exec /usr/lib/php/php7.0-fpm-checkconf
+end script
 
 respawn
 exec /usr/sbin/php-fpm@PHP_VERSION@ --nodaemonize --fpm-config /etc/php/@PHP_VERSION@/fpm/php-fpm.conf
\ No newline at end of file
```

That should help with the missing /run/php

**Comment by geoff-gedde** [comment]
Sorry I am not following the above.  I can't find the upstart.
However, I can confirm that the folder /run/php was missing.
I just did
```
sudo mkdir /run/php
sudo service php7.0-fpm restart
```
Now it's Working!

So How do I patch this correctly?
Where is the b/debian/php-fpm.upstart

**Comment by geoff-gedde** [comment]
Also Is there a way to specify a certain version to install?
That way when my load servers spawn up they don't fetch a newer version and instead just use the version I specify.

**Comment by oerdnj** [comment]
@geoff-gedde `/etc/init/php7.0-fpm` or just wait until the packages finished building, it should be fixed in `7.0.6-3+donate.sury.org~*+2` and `5.6.21-3+donate.sury.org~*+2`.

**Comment by oerdnj** [comment]
@geoff-gedde No, you can't specify a version to install when using PPAs.

**Comment by geoff-gedde** [comment]
Ok, Thanks
Would it be possible to create a separate PPA for Stable.
Or any advise to how I should account for this in the future.
I am thinking of creating a IMAGE or something so updates don't happen.

Thanks again

**Comment by oerdnj** [comment]
I would simply suggest at least briefly test each new update in non-production environment. I also have a ppa:ondrej/php-qa where I usually stage things before I push them into main repository, but it hasn't gained a big traction and without people testing new features, it's hard to not publish a buggy version from time to time.

This time it was a fix for a bug that caused php7.0-fpm-checkconf never to report failure which introduced this bug. I try to minimize the amount of breakages, but I am just a person, not a god, so fuckups from my side might happen. At least you know that the bugs are fixed quite quickly, and I don't push big changes before my vacation or weekend (at least those with nice weather forecasts :sweat_smile:).

**Comment by oerdnj** [comment]
@Kiaatix If you see:

> php7.0-fpm main process (1652) terminated with status 78

then your `php-fpm.conf` have some errors and `php-fpm7.0 -t` should reveal those. I am not sure if upstart can report the bugs from `pre-start script` to the end users.

I will be a very happy man when I can drop upstart support and have just two init systems in the packages again.

**Comment by geoff-gedde** [comment]
Thanks, I fully understand.  
Unfortunately, we don't have time to test the updates on a regular basis, but I will give it a shot.
I am looking around and can't seem to find the information.  Is there a newsletter or a speciic Repo that I should watch so I can get notification when your about to update something.  For both the Main and the php-qa PPA's.

**Comment by oerdnj** [comment]
@geoff-gedde I have [Twitter](https://twitter.com/debsuryorg), where I announce changes (not all), and the longer stuff is published on [Patreon](https://www.patreon.com/oerdnj).

**Comment by oerdnj** [comment]
And the packages has been published, so closing this bug:
```
root@lettie:~# apt-cache policy php5.6
php5.6:
  Installed: (none)
  Candidate: 5.6.21-3+donate.sury.org~trusty+2
  Version table:
     5.6.21-3+donate.sury.org~trusty+2 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
root@lettie:~# apt-cache policy php7.0
php7.0:
  Installed: (none)
  Candidate: 7.0.6-3+donate.sury.org~trusty+2
  Version table:
     7.0.6-3+donate.sury.org~trusty+2 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
```

**Comment by jdebuchy** [comment]
Thanks, @oerdnj 
I can check things are working now with Trellis and your PPA.

**Comment by geoff-gedde** [comment]
@oerdnj   Thanks
