### ISSUE TITLE
PHP 7.0 can't install 

### ISSUE THREAD

**Issue by johnluxor** [oerdnj/deb.sury.org#342]
From old issue

I tried to install and got this error

Setting up php7.0-fpm (7.0.6-3+donate.sury.org~trusty+2) ...
start: Job failed to start
invoke-rc.d: initscript php7.0-fpm, action "start" failed.
dpkg: error processing package php7.0-fpm (--configure):
subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of php7.0:
php7.0 depends on php7.0-fpm | libapache2-mod-php7.0 | php7.0-cgi; however:
Package php7.0-fpm is not configured yet.
Package libapache2-mod-php7.0 is not installed.
Package php7.0-cgi is not installed.

dpkg: error processing package php7.0 (--configure):
dependency problems - leaving unconfigured
Errors were encountered while processing:
php7.0-fpm
php7.0
E: Sub-process /usr/bin/dpkg returned an error code (1)

Your command 

php-7.0-fpm -t 

returned me

-bash: php7.0-fpm: command not found

**Comment by oerdnj** [comment]
It should be `sudo php-fpm7.0 -t`. What extensions do you have installed? xdebug? Try disabling opcache with `sudo phpdismod opcache`

**Comment by johnluxor** [comment]
I purge php and tried to install again. -v 7.0.6-4+donate.sury.org~trusty+2

It installed without errors, but php don't see any exctensions - json, phar etc

**Comment by oerdnj** [comment]
If you start doing random things in panic, then you'll end up with broken system. No surprise here. 

I removed the configuration check from the init scripts, so the zend_mm_heap bug won't influence restarts.
