### ISSUE TITLE
Pear doesn't work with Php7 on Ubuntu 12.04

### ISSUE THREAD

**Issue by sascha-hendel** [oerdnj/deb.sury.org#343]
Installation of Php7.0 packages and remove of old Php5 packages worked well. Php7 runs with Apache2. Only problem is Pear/Pecl.
Installing Package php-pear requires php5-cli php5-common php5-dev. If install it with these dependencies following error occurs on starting pear or pecl:
Parse error: syntax error, unexpected 'new' (T_NEW) in ...

**Comment by oerdnj** [comment]
`apt-cache policy php-pear` says?

**Comment by oerdnj** [comment]
@sascha-hendel It's precise, right?

**Comment by sascha-hendel** [comment]
Yes, it's precise. But better say: it was...
Updated now the whole server to 14.04 (with do-release-upgrade) and now php-pear doesn't require the php5 packages anymore.

**Comment by rfletcher** [comment]
I just noticed the same issue. It looks like there just isn't a php-pear package in the repository right now:

https://launchpad.net/%7Eondrej/+archive/ubuntu/php/+index?field.series_filter=precise

````
# cat /etc/apt/sources.list.d/ondrej-php-precise.list 
deb http://ppa.launchpad.net/ondrej/php/ubuntu precise main
deb-src http://ppa.launchpad.net/ondrej/php/ubuntu precise main

# apt-get update >/dev/null && apt-cache policy php-pear
php-pear:
  Installed: (none)
  Candidate: 5.3.10-1ubuntu3.22
  Version table:
     5.3.10-1ubuntu3.22 0
        500 http://archive.ubuntu.com/ubuntu/ precise-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ precise-security/main amd64 Packages
     5.3.10-1ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
````

**Comment by oerdnj** [comment]
Just uploaded `php-pear` for Ubuntu 12.04 LTS. Just wait a sec for packages to be built.

**Comment by rfletcher** [comment]
Great, thanks!

**Comment by rfletcher** [comment]
Looks like [the build failed](https://launchpadlibrarian.net/259024746/buildlog_ubuntu-precise-i386.php-pear_1%3A1.10.1+submodules+notgz-8+donate.sury.org~precise+1_BUILDING.txt.gz) with:

````
...
make[1]: Leaving directory `/«BUILDDIR»/php-pear-1.10.1+submodules+notgz'
   dh_compress
   dh_fixperms
   dh_installdeb
dh_installdeb: unknown dpkg-maintscript-helper command: symlink_to_dir
make: *** [binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 
````

**Comment by oerdnj** [comment]
@rfletcher Yep, just uploaded version without symlink_to_dir. Ubuntu 12.04 LTS is really old :(.

**Comment by rfletcher** [comment]
> Ubuntu 12.04 LTS is really old :(.

Hah. It sure is. Ubuntu really meant it when they came up with **Long** Term Support.

Thanks again.

**Comment by sascha-hendel** [comment]
Sorry I can't check it now, because my system now runs on trusty...

**Comment by koenpunt** [comment]
Works for me. Although when `php-xml` isn't installed, `php-pear` suggests it, but `php-xml` installs the php7 package. So had to manually install `php5.5-xml` before installing `php-pear`
