### ISSUE TITLE
alternative for phpdbg for an easier usage

### ISSUE THREAD

**Issue by stof** [oerdnj/deb.sury.org#345]
It would be great to register an alternative for ``phpdbg``, so that we can use it without having to look for ``phpdbg-5.6`` or ``phpdbg-7.0`` explicitly (having to remember the current alternative selected for php)

**Comment by stof** [comment]
Closing as it is already available in the new ppa (was not the case in the old ppa AFAICT)

**Comment by oerdnj** [comment]
Yep, but the old one was something like phpdbg5, wasn't it?

**Comment by stof** [comment]
It was ``php5dbg`` (somewhat consistent with the name of ``php5`` but weird to have the 5 in the middle)
