### ISSUE TITLE
Dependencies on compat php5-common broken

### ISSUE THREAD

**Issue by derSascha** [oerdnj/deb.sury.org#346]
Hi,

i am current installing packages from php-ppa and php-compat-ppa on ubuntu trusty. Everthings works well except `php5-common`:

    php5-common : Depends: php5.6-dba but it is not installable

**Comment by oerdnj** [comment]
Good catch, you are actually the first one to notice that phpX.Y-dba hasn't been built because of s/.m4/.mk/ extension in `debian/rules.d/` :)

If the builds here, successfully finishes, I'll upload them to main PPA: https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages

**Comment by oerdnj** [comment]
It's building right now in `ppa:ondrej/php`.

**Comment by oerdnj** [comment]
@derSascha Just confirmed that it works like a charm :)

**Comment by derSascha** [comment]
Thanks for the fast response, great work :)

Looks like the compat meta package are missing php5-json (phpmyadmin depends on this...)
