### ISSUE TITLE
ZMQ extension missing

### ISSUE THREAD

**Issue by rinu** [oerdnj/deb.sury.org#347]
I ran into an issue where I needed an updated version of PHP and the ZMQ extension.
It would be nice if didn't have to compile it myself. I'm pretty sure the official packages have this extension available but for some reason not this PPA.

**Comment by oerdnj** [comment]
Which Ubuntu version?

**Comment by rinu** [comment]
All of them. In my specific case I needed it for 12.04 but it seems to be missing for all supported Ubuntu versions. I use a variety of versions on different computers.

**Comment by oerdnj** [comment]
Nope, it's just Ubuntu 12.04 build missing, I'll upload it later today.

**Comment by oerdnj** [comment]
Packages built and waiting for upload. One more thing, I'll upload more recent zeromq library and issue second rebuild, but the extensions should be installable meanwhile.
