### ISSUE TITLE
What is the correct symbol to use in the LoadModule php7.load file ?

### ISSUE THREAD

**Issue by erikstainsby** [oerdnj/deb.sury.org#348]
I keep running into this error: 
/usr/lib/libphp7.so: undefined symbol: php7_module
when trying to test the apache config. Clearly my lphp7.load file has the wrong symbol named.

LoadModule php7_module /usr/lib/libphp7.so

I've tried php_module and php7.0_module but I'm just guessing wildly. Can I get a clue please?

**Comment by oerdnj** [comment]
You are doing it wrong. Apache2 module doesn't reside in `/usr/lib`. You should just install `libapache2-mod-php7.0` and if it doesn't enable automatically, fix the reasons why and run `a2enmod php7.0`.
