### ISSUE TITLE
PHP libapache2-mod-php7.0 (7.0.6) fails to install

### ISSUE THREAD

**Issue by erikstainsby** [oerdnj/deb.sury.org#349]
On Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-36-generic x86_64)

```
root@cloud ~ 
> # apt-get upgrade

```
...
Setting up libapache2-mod-php7.0 (7.0.6-8+donate.sury.org~trusty+1) ...
dpkg: error processing package libapache2-mod-php7.0 (--configure):
 subprocess installed post-installation script returned error exit status 1
...
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Errors were encountered while processing:
 libapache2-mod-php7.0
E: Sub-process /usr/bin/dpkg returned an error code (1)

---
Sad face.
Erik

**Comment by oerdnj** [comment]
I am guessing that you left your apache2 configuration in broken state after your experiments. Check with `apache2ctl checkconf` (or something like that), fix the errors and run `sudo dpkg --configure -a`.

**Comment by oerdnj** [comment]
I've just installed `libapache2-mod-php7.0` normally, so that's your local configuration problem.
