### ISSUE TITLE
(minor) cross-version PHP packages still mention PHP5 in the description

### ISSUE THREAD

**Issue by mike503** [oerdnj/deb.sury.org#350]
A bit misleading nowadays, since you're starting to make it so universal. I appreciate the work. It was getting to be a bit of a headache to figure out which repo to use, you seem to have be putting this all together well!

The two I have installed that I noticed:

php-memcache 3.0.9~20160311.4991c2f-1+donate.sury.org~wily+2
memcache extension module for PHP5

php-memcached 3.0.0a1-13-g6ee96ca+2.2.0-3+donate.sury.org~wily+1
memcached extension module for PHP5, uses libmemcached

**Comment by oerdnj** [comment]
Good catch
