### ISSUE TITLE
php5.xenmod, php5.xdismod

### ISSUE THREAD

**Issue by wellebee** [oerdnj/deb.sury.org#352]
I just upgraded from ppa:ondrej/php5 to ppa:ondrej/php. 

In the new repository I see that a version prefix has been appended to some items, e.g., from /var/run/php5-fpm.sock to /var/run/php/php5.6-fpm.sock, but I haven't found a replacement for php5enmod, php5dismod. I am looking for a suggestion on how to enable/disable PHP modules with the new repository. Thank you.

**Comment by oerdnj** [comment]
It's just `phpenmod` and it now accepts `-v` for a version or it works on all installed modules if omitted.

**Comment by wellebee** [comment]
Wonderful. Thank you.
