### ISSUE TITLE
[libpcre3] PHP7.0 dies with segfault: munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by cerlestes** [oerdnj/deb.sury.org#353]
Hi Ondřej.

We're experiencing a bug with one of our framework's regular expressions. We've traced the problem down to the following code: https://3v4l.org/ELKEb

As you can see, this works fine on 3v4l.org. But on our servers, running your PHP7.0/libpcre3 build, we get the following error before the process dies to a SIGABRT: 
```
*** Error in `php': munmap_chunk(): invalid pointer: 0x00007fdce5550060 ***
```

strace yields the following last lines:
```
...
stat("/xyz/Packages/Framework/TYPO3.Fluid/Classes/TYPO3/Fluid/Core/ViewHelper/Facets/CompilableInterface.php", {st_mode=S_IFREG|0640, st_size=4663, ...}) = 0
open("/dev/tty", O_RDWR|O_NOCTTY|O_NONBLOCK) = -1 ENXIO (No such device or address)
writev(2, [{"*** Error in `", 14}, {"php-fpm: pool xyz", 22}, {"': ", 3}, {"munmap_chunk(): invalid pointer", 31}, {": 0x", 4}, {"00007f3fcd356fd0", 16}, {" ***\n", 5}], 7) = 95
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3fcbd5d000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(5138, 5138, SIGABRT)             = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=5138, si_uid=33} ---
+++ killed by SIGABRT (core dumped) +++
```

The code works on the following versions:
```
libpcre3    =  1:8.31-2ubuntu2.2
php7.0-fpm  =  7.0.5-2+deb.sury.org~trusty+1

# uname -a
Linux xyz 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

But not on this combination:
```
libpcre3    =  2:8.35-3.3+deb8u4+deb.sury.org~trusty+1
php7.0-fpm  =  7.0.6-11+donate.sury.org~trusty+2

# uname -a
Linux xyz 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Please tell me if you need further help with reproduction, as I have no idea what other information you might need. As always, thanks for your help and dedication!

**Comment by cerlestes** [comment]
More information: I've debugged it down to the following piece of code within the regular expression: `|\s+` If I remove this from the regex, it works fine. If I add it again it fails. Also permutations like `|[ ]+` or placing it somewhere else in the regex-group will fail.

**Comment by oerdnj** [comment]
I had to update `pcre3` version due JIT support, but I am looking into updating it to 8.38 right now. Just a moment, there has been change between with introduction of GCC 5.x, so backporting needs some tweaks.

**Comment by oerdnj** [comment]
@cerlestes Could you retry with `pcre3_3.83*` from `ppa:ondrej/php-qa` (beware, there's 7.0.7~rc1 as well, so take care to upgrade just `pcre3` libraries). Here's direct link for trusty-amd64 build: https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+build/9758854

**Comment by cerlestes** [comment]
@oerdnj `libpcre3 = 2:8.38-3.1+deb.sury.org~trusty+3` seems to fix the problem. I'm getting no more segmentation faults. Thanks for the quick response! I'll make sure that we send you a nice donation soon :smile:

**Comment by oerdnj** [comment]
@cerlestes Thanks for the confirmation. I have uploaded those fixed `pcre3` packages into main repo.
