### ISSUE TITLE
/usr/lib/php/php7.0-fpm-checkconf is missing in php7.0 on Xenial

### ISSUE THREAD

**Issue by jeroenvermeulen** [oerdnj/deb.sury.org#354]
It looks like `/usr/lib/php/php7.0-fpm-checkconf` is recently removed from your PHP 7.0 for Xenial.
Our current version is now `7.0.6-11+donate.sury.org~xenial+2` and the file suddenly disappeared.
It is used in the default PHP-FPM systemd startup scripts, which we based our own startup scripts on.

I am willing to donate if you fix it.

**Comment by oerdnj** [comment]
Why exactly you need the script for systemd service file? What's the scenario that will save the day? 

It was a safeguard for sysvrc configuration reload that is not applicable for service files anymore, because ExecStartPre is applied only on service start. 

I have no problem putting the file back, but I consider it useless how it was used there.

**Comment by jeroenvermeulen** [comment]
This is an example config of how we are using it. This is completely inspired on the file `/lib/systemd/system/php7.0-fpm.service` in the Xenial repo.
```
[Unit]
Description=The PHP 7.0 FastCGI Process Manager - ##VHOSTUSER##
After=network.target

[Service] 
Environment="PHPRC=/etc/php/7.0/fpm-##VHOSTUSER##"
Environment="PHP_INI_SCAN_DIR=/etc/php/7.0/fpm-##VHOSTUSER##/conf.d"
Type=notify
PIDFile=/run/php/php7.0-fpm-##VHOSTUSER##.pid
ExecStartPre=/usr/lib/php/php7.0-fpm-checkconf /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/usr/lib/php/php7.0-fpm-checkconf /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by oerdnj** [comment]
Ah, that makes (sort of) sense, does:

```
ExecStartPre=/usr/sbin/php-fpm7.0 -t /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/usr/sbin/php-fpm7.0 -t /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID
```

work for you or does it fail with `zend_mm_heap corrupted`?

Do you have any specific reasons why you just don't add new pools per customer? (AFAIK configuration reloads should not affect other customers.)

**Comment by oerdnj** [comment]
The only reason for dedicated script was frequent segfaults on FPM shutdown.

**Comment by jeroenvermeulen** [comment]
Thank you @oerdnj, that works (except you forgot one `-y`). Donation is coming your way.
I am now using:
```
ExecStartPre=/usr/sbin/php-fpm7.0 -t -y /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/usr/sbin/php-fpm7.0 -t -y /etc/php/7.0/fpm-##VHOSTUSER##/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID
```

We run a limited number of very heavy vhosts on one server. We host Magento on shared (and dedicated) servers. Magento contains 9286 separate PHP files.
The reason we run one PHP-FPM daemon per vhostuser instead of using pools are:

* It previously happened one vhost caused the whole PHP-FPM to crash. We don't want this to affect the other webshops.
* We think it is more efficient with the use of OpCache, not 100% sure

**Comment by oerdnj** [comment]
Ok, great, it solved the issue for you. Let me know if you encounter the `zend_mm_heap corrupted` on restarts and I'll restore the script - I don't have an exact pattern when it happens (I think it might be xdebug related), so I am not turning this on by default for all users.
