### ISSUE TITLE
Update php5.5-fpm on Ubuntu 12.04 missing sysv-rc dependencies

### ISSUE THREAD

**Issue by Prometee** [oerdnj/deb.sury.org#356]
Hi,

We are facing some difficulties with the ppa:ondrej/php on Ubuntu 12.04 since the update of php5.5 tomorrow.
After the update php5.5-fpm was not restartable. We try to reinstall it but dependencies are not satisfied because of sysv-rc. The installed version is 2.88dsf-13.10ubuntu11.1 but php5.5-fpm need a version >= 2.88dsf-24.

Complete apt error message below [fr_FR]:
`# apt-get install php5.5-fpm
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation :

Les paquets suivants contiennent des dépendances non satisfaites :
 php5.5-fpm : Dépend: sysv-rc (>= 2.88dsf-24) mais 2.88dsf-13.10ubuntu11.1 devra être installé ou
                       file-rc (>= 0.8.16) mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».`

**Comment by oerdnj** [comment]
It should hopefully get better when `php5.5_5.5.35-6**+3` is built which I just uploaded. If not, please reopen.

**Comment by oerdnj** [comment]
Hmm, it didn't helped, so it must be something else.

**Comment by oerdnj** [comment]
Found it, yet another rebuild and all should be fine.

**Comment by Prometee** [comment]
I try updating 3 minutes ago, the same message appears.

**Comment by Prometee** [comment]
Version show by apt-cache after apt-get update is  5.5.35-6+donate.sury.org~precise+2

**Comment by Prometee** [comment]
It works now, thank you for your extreme rapidity :)

**Comment by oerdnj** [comment]
It was caused by backported `debhelper` needed to backport `cmake` needed to backport `librabbitmq-dev`. Precise needs to die :)

**Comment by Prometee** [comment]
Agree !!!
