### ISSUE TITLE
No mysql 5.5/5.6 packages for Xenial

### ISSUE THREAD

**Issue by jwadsager** [oerdnj/deb.sury.org#357]
There are no Xenial packages in your MySQL ppa's yet:

https://launchpad.net/~ondrej/+archive/ubuntu/mysql-5.5
https://launchpad.net/~ondrej/+archive/ubuntu/mysql-5.6

Thank you for work.

**Comment by oerdnj** [comment]
I'll give the mysql packages some priority during next week.

**Comment by oerdnj** [comment]
It's building right now. Closing this bug (but I'll take care if something fails to build).

**Comment by Dimasdanz** [comment]
After adding your ppa and proceed with `apt-get install mysql-server-5.5`  

The following occured:
```
The following packages have unmet dependencies:
 mysql-server-5.5 : PreDepends: mysql-common (>= 5.5) but it is not going to be installed
                    Depends: mysql-client-5.5 (>= 5.5.49-1+deb.sury.org~xenial+5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by oerdnj** [comment]
Yeah, the build scripts are broken and I spend several days on fixing them, but it needs some more time. I'll look at it during July.

**Comment by rsommer** [comment]
The problem still exists:

`dpkg: regarding mysql-server-5.5_5.5.51-1+deb.sury.org~xenial+1_amd64.deb containing mysql-server-5.5:
 mysql-common conflicts with mysql-server-5.5
  mysql-server-5.5 (version 5.5.51-1+deb.sury.org~xenial+1) is to be installed.
`

Any news on this?

**Comment by pantaoran** [comment]
I also tried to install this and it failed with the above mentioned issues :-(

**Comment by oerdnj** [comment]
As I don't really have time to properly maintain neither MySQL nor MariaDB, I have deprecated the repositories.

**Comment by pantaoran** [comment]
Pity, but I guess it's the best solution.
