### ISSUE TITLE
php-memcached forces php7.0 packages install on trusty with just 5.6

### ISSUE THREAD

**Issue by rubroboletus** [oerdnj/deb.sury.org#359]
Doing fresh install of php5.6 using ppa:sury/php with php-memcached package forces install of few php7.0 packages.

**Comment by oerdnj** [comment]
Could you please be more descriptive? Like listing the packages that got installed? Or copy&pasting the terminal output to see what has happened?

There are several alternatives in the dependencies, so you might be not specific enough in what are you trying to install and `apt-get` picks the first options to satisfy the dependency.

**Comment by rubroboletus** [comment]
"apt-get install php5.6 php5.6-cli php5.6-fpm php5.6-curl php5.6-gd php5.6-mcrypt php5.6-mysql php5.6-xsl php5.6-intl php-redis php-memcache php-ssh2"
installs just php5.6 packages but just extend it with "php-memcached" and it will also install "php7.0-common" and "php7.0-json"

**Comment by oerdnj** [comment]
I see. It depends on `php-json` that pulls `php7.0-json` in turn. I'll drop `php-json` from the dependencies as it is installed everywhere sane anyway. It will get fixed when `php-memcached_3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~*+3` finishes building.

**Comment by rubroboletus** [comment]
Thank you Ondrej, have a nice day.

**Comment by tkd-hgoertz** [comment]
is this fixed now? I install the following packages:
```
apt-get install php5.6 php5.6-cli php5.6-fpm php5.6-gd php5.6-mcrypt php5.6-curl \
php5.6-xml php5.6-bcmath php5.6-mysql php5.6-readline php5.6-common php5.6-json \
php5.6-opcache php5.6-dev php5.6-xmlrpc php5.6-mbstring php5.6-sqlite3 php-apcu \
php-geoip php-imagick php-redis php-xdebug php-mongo php-mongodb php-memcache \
php-memcached
```
and get some php7.0 packages, where they coming from ?
```
The following NEW packages will be installed:
autoconf automake autotools-dev debhelper dh-apparmor dh-php gettext
intltool-debian libasprintf-dev libgd3 libgettextpo-dev libgettextpo0
liblist-moreutils-perl libltdl-dev libmail-sendmail-perl libmcrypt4
libmemcached11 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0
libphp7.0-embed libssl-dev libssl-doc libssl1.0.2 libsys-hostname-long-perl
libtool libunistring0 libvpx1 libxmlrpc-epi0 libxpm4 libxslt1.1 m4 php-apcu
php-apcu-bc php-common php-geoip php-igbinary php-imagick php-memcache
php-memcached php-mongo php-mongodb php-msgpack php-pear php-redis
php-xdebug php5.6 php5.6-bcmath php5.6-cli php5.6-common php5.6-curl
php5.6-dev php5.6-fpm php5.6-gd php5.6-json php5.6-mbstring php5.6-mcrypt
php5.6-mysql php5.6-opcache php5.6-readline php5.6-sqlite3 php5.6-xml
php5.6-xmlrpc php7.0-cli php7.0-common php7.0-json php7.0-opcache
php7.0-readline pkg-php-tools po-debconf shtool ttf-dejavu-core xml2
zlib1g-dev
```

**Comment by oerdnj** [comment]
@tkd-hgoertz Yes, it is:
```
root@lettie:/# apt-get install php-memcached php5.6-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libedit2 libmagic1 libmemcached11 libssl1.0.2 libxml2 php-common
  php-igbinary php-msgpack php5.6-common php5.6-opcache php5.6-readline psmisc
Suggested packages:
  file php-pear
Recommended packages:
  xml-core
The following NEW packages will be installed:
  libedit2 libmagic1 libmemcached11 libssl1.0.2 libxml2 php-common
  php-igbinary php-memcached php-msgpack php5.6-cli php5.6-common
  php5.6-opcache php5.6-readline psmisc
0 upgraded, 14 newly installed, 0 to remove and 33 not upgraded.
Need to get 2205 kB/4456 kB of archives.
After this operation, 19.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

It's `pkg-php-tools` - why do you need it anyway?

**Comment by tkd-hgoertz** [comment]
hm I didn't explizit install pkg-php-tools, it must be an dependency from some php packages nor ?

**Comment by oerdnj** [comment]
@tkd-hgoertz APT install Recommended packages by default and that pulls `php-pear`; Use `apt-get --no-install-recommends`

**Comment by tkd-hgoertz** [comment]
thx for that hint, got it
