### ISSUE TITLE
5.6 - PDO - Undefined class constant 'MYSQL_ATTR_SSL_CA' in CLI

### ISSUE THREAD

**Issue by brentoboy** [oerdnj/deb.sury.org#360]
I recently switched from an old PPA to the new PPA (based on a recommendation during an apt-get update).

I'm running php 5.6

when I run a script from the CLI, I get an error that looks like this...
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_SSL_CA' in myfile.php on line 38

strangely, it all seems to work fine through mod_php / apache.  its just the CLI version with the issue.

php -m gives this output:

[PHP Modules]
...
openssl
pcntl
pcre
PDO
Phar
posix
...

any thoughts on what I need to do to fix it?

**Comment by oerdnj** [comment]
Could you check whether `/etc/php/5.6/cli/conf.d/` contains symlink to `/etc/php/5.6/mods-available/pdo_mysql.ini` or any other mysql symlinks?

And if now whether `phpenmod mysqlnd pdo_mysql` helps the situation?

And if yes, I would be interested in having your /var/log/apt/* logs to see what has happened.

**Comment by brentoboy** [comment]
10-pdo.ini -> /etc/php/5.6/mods-available/pdo.ini

but nothing links to pdo_mysql.ini

in fact, pdo_mysql.ini isnt in mods-avialable.  I wonder how the apache mod works.

I did this ... which fixed me
sudo apt-get install php5.6-mysql

thanks for the unbelievably quick response.

**Comment by oerdnj** [comment]
Ah, I didn't realized that you might not have `php5.6-mysql` installed at all :).

**Comment by podarok** [comment]
Same issue for PHP7
For fixing it you need to run
```sudp apt-get install php-mysql```

**Comment by xdeus** [comment]
You may try the solution mentioned here : 

https://stackoverflow.com/questions/42511383/fatal-error-undefined-class-constant-mysql-attr-ssl-ca-in-var-www-laravel-co/54931113#54931113
