### ISSUE TITLE
Cannot find php5-compat packages

### ISSUE THREAD

**Issue by xZise** [oerdnj/deb.sury.org#361]
According to https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php's section **Compatibility php5-* packages**, I added `sudo add-apt-repository ppa:ondrej/php5-compat` (although it uses `ppa:ondrey/php5` which seemed to me like an error) and now get the following errors when I do `sudo apt-get update`:

```
W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-compat/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-compat/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-compat/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
```

Should've used the `ppa:ondrey/php5` repository? And should `apt-cache showpkg php5` the PPA to verify it worked? I want to use `phpmyadmin` and `phppgadmin` which both use the `php5` packages.

**Comment by oerdnj** [comment]
Uploaded a precise build right now and it should be available in couple of minutes.

**Comment by xZise** [comment]
Yep it works now, thanks!
