### ISSUE TITLE
Debug symbols for php7 & exts

### ISSUE THREAD

**Issue by Seldaek** [oerdnj/deb.sury.org#362]
Would it be possible to get a php-dbg package that includes debug symbols? I encountered an APCu segfault using php-apcu `5.1.3+4.0.11+unpack-1+donate.sury.org~trusty+2` and php7.0-fpm `7.0.6-13+donate.sury.org~trusty+1`. If I could get debug symbols for them I'd be able to give @krakjoe what he needs to look into this :)

**Comment by krakjoe** [comment]
I know these may be big files, and that's probably the reason they are not uploaded ... but ... pretty please, I need them :)

**Comment by oerdnj** [comment]
@Seldaek @krakjoe As in: https://github.com/oerdnj/deb.sury.org/wiki/Debugging-symbols ?

**Comment by Seldaek** [comment]
Yes exactly like that ;) Thanks a lot, it might be good to link to this from the PPA description.

**Comment by oerdnj** [comment]
The documentation is still in the infancy and very sparce (in fact anybody can edit the wiki, so you are all welcome to contribute), but I might publish a link at the deb.sury.org.

**Comment by Seldaek** [comment]
Eh it allowed me to get a stack trace out of the crash log so that's great docs already!

**Comment by oerdnj** [comment]
Ok, I have added the link to the wikis to https://deb.sury.org/ pages.
