### ISSUE TITLE
php 5.6 - PDO - MySQL - OpenSSL error in CLI

### ISSUE THREAD

**Issue by brentoboy** [oerdnj/deb.sury.org#366]
Since switching my ppa to the new repository, I'm having issues with php scripts that are run from the CLI (as cron jobs).   I dont have the issues when I run php scripts hosted by Apache.

I use Ubuntu 14.04, MySQL 5.6, php 5.6, PDO

My PDO initialization looks like this:

```
    $options = [
        PDO::MYSQL_ATTR_SSL_CA => '/path/to/ca.pem'
    ];
    // this next statement fails in CLI php, but not in Apache hosted PHP
    $pdo_connection = new PDO(
        'my-connection-string',
        'php_user',
        'secret',
        $options
    );
```

the error I get looks like this:
`PHP Fatal error:  Uncaught exception 'ErrorException' with message 'PDO::__construct(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed' in /path/to/myfile.php:41`

my apache2 and cli conf.d folders have the same mods enabled....
`$ ls /etc/php/5.6/apache2/conf.d
10-mysqlnd.ini  10-pdo.ini       20-ctype.ini  20-fileinfo.ini  20-gettext.ini  20-json.ini    20-mysql.ini      20-phar.ini   20-readline.ini  20-sockets.ini  20-sysvsem.ini  20-tokenizer.ini
10-opcache.ini  20-calendar.ini  20-exif.ini   20-ftp.ini       20-iconv.ini    20-mysqli.ini  20-pdo_mysql.ini  20-posix.ini  20-shmop.ini     20-sysvmsg.ini  20-sysvshm.ini`

`$ ls /etc/php/5.6/cli/conf.d
10-mysqlnd.ini  10-pdo.ini       20-ctype.ini  20-fileinfo.ini  20-gettext.ini  20-json.ini    20-mysql.ini      20-phar.ini   20-readline.ini  20-sockets.ini  20-sysvsem.ini  20-tokenizer.ini
10-opcache.ini  20-calendar.ini  20-exif.ini   20-ftp.ini       20-iconv.ini    20-mysqli.ini  20-pdo_mysql.ini  20-posix.ini  20-shmop.ini     20-sysvmsg.ini  20-sysvshm.ini`

I'm not sure what else could be different between the two environments, or how they could be different from what was installed in the older PPA.    I'm starting to suspect that the apache version has some ssl modules compiled in, and the cli doesn't, and I need to install them manually, but I dont know where to start.

**Comment by oerdnj** [comment]
How exactly do you launch the cron jobs?

**Comment by brentoboy** [comment]
I actually haven't started running them as crons again, I'm still just trying to make it work directly from the command line.

so, I log in as a non-root power user in a bash shell.
and I run a script like so...
`php run_migrations.php`

and get that error.

so, my comment about the crons is more to bring out the idea that this script is the sort of thing I'll run every few minutes in the background.

**Comment by oerdnj** [comment]
And `php -v` output is?

**Comment by brentoboy** [comment]
> And `php -v` output is?

PHP 5.6.22-3+donate.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by oerdnj** [comment]
That looks good. There isn't any difference in the compiled-in modules (or there shouldn't be one).

Do you have correct permissions to `/path/to/ca.pem`? Can you read the file as the user you are trying to run the PHP script?

**Comment by brentoboy** [comment]
cat ./ssl_certs/prod-db/ca.pem
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIJANFLX6sIKJEWMA0GCSqGSIb3DQEBCwUAMG4xCzAJBgNV
BAYTAlVTMREwDwYDVQQIDAhNaXNzb3VyaTERMA8GA1UEBwwIU3QgTG91aXMxEzAR
BgNVBAoMClNtYXJ0IENhcmUxJDAiBgNVBAMMG3Byb2QtZGIuc21hcnRjYXJlc3lz

...
...

**Comment by brentoboy** [comment]
I ran my script using sudo and have the same error, so I'm thinking its not a permission thing.

**Comment by oerdnj** [comment]
Unfortunately it's not possible to debug MySQL using OpenSSL, but I actually suspect that the used CA file doesn't match the certificate used on MySQL server.

**Comment by brentoboy** [comment]
k, I'll dig around on that a bit and see what I can find out.
Thanks for your help.

And super thanks for building and maintaining this PPA.

**Comment by oerdnj** [comment]
Check whether your CAfile matches, you have correct DH params and the CN in the cert matches the server:
See this: http://stackoverflow.com/questions/32592368/how-do-i-connect-with-an-ssl-between-mysql-and-php or this: http://stackoverflow.com/questions/31424518/php-5-6-mysql-ssl-and-self-signed-certificates or http://stackoverflow.com/questions/34622899/pdo-with-self-signed-certificates

**Comment by oerdnj** [comment]
Or this: http://stackoverflow.com/questions/31357560/mysql-connection-over-ssl-with-php-mysqli

**Comment by oerdnj** [comment]
Also please check if you are really running php5.6 in apache2. Uninstall libapache2-mod-php5 just to be sure (or `a2dismod php5 && a2enmod php5.6`).

**Comment by oerdnj** [comment]
No response since May 2016, closing.
