### ISSUE TITLE
How to get php5-xsl, php5-curl and so on when using this PPA's php5.6 in 16.04?

### ISSUE THREAD

**Issue by axfelix** [oerdnj/deb.sury.org#367]
Hi,

Forgive me if this is a silly question, but is there a supported way to get php5-xsl and other modules through the package manager when using php5.x provided from this PPA, since it's no longer in 16.04 sources? I'm assuming the php7.0 libraries in apt sources aren't backwards compatible; do the libraries have to be installed manually for older php versions in this case?

**Comment by oerdnj** [comment]
Install `php5.6-xml` or `php5.5-xml` from `ppa:ondrej/php`
