### ISSUE TITLE
php5.6 ext igbinary gmagick

### ISSUE THREAD

**Issue by tigefa4u** [oerdnj/deb.sury.org#368]
wordpress latest/trunk image upload result

![wordpress upload](https://res.cloudinary.com/hxidhfgwg/image/upload/v1464783055/Cuplikan_layar_dari_2016-06-01_19-09-20_zry390.png)

then i roll back `sudo phpdismod igbinary gmagick`

**Comment by oerdnj** [comment]
You need to be more verbose, your bugreport is cryptic and doesn't describe the result. Here's an excellent essay on good bug reports: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by oerdnj** [comment]
But most probably you'll have to report the bugs to the upstream authors.

**Comment by tigefa4u** [comment]
what is ext http

```
sudo phpenmod http
php -v

# Got this
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/http.so' - /usr/lib/php/20131226/http.so: undefined symbol: php_resource_factory_handle_ctor in Unknown on line 0
PHP 5.6.22-4+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

i think this ext. :hammer:

**Comment by oerdnj** [comment]
How is this related to the original bugreport? Please don't re-use existing bugreports to report new bugs. You haven't added the more information requested to gmagick, so I am closing this bug.
