### ISSUE TITLE
Package conflict when trying to upgrade 

### ISSUE THREAD

**Issue by sareiodata** [oerdnj/deb.sury.org#369]
I get the following error when trying to upgrade and I'm not sure how to move forward. 

https://launchpad.net/~ondrej/+archive/ubuntu/nginx

`Preparing to unpack .../nginx_1.10.1-1~trusty_amd64.deb ...
Unpacking nginx (1.10.1-1~trusty) over (1.10.0-1+deb.sury.org~trusty+4) ...
dpkg: error processing archive /var/cache/apt/archives/nginx_1.10.1-1~trusty_amd64.deb (--unpack):
 trying to overwrite '/etc/default/nginx', which is also in package nginx-common 1.10.1-0+deb.sury.org~trusty+1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nginx_1.10.1-1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

Any suggestions would are more then welcomed.

**Comment by oerdnj** [comment]
Don't mix different repositories. `nginx_1.10.1-1~trusty` doesn't come from my repo. 

What does `apt-cache policy nginx` shows?

**Comment by sareiodata** [comment]
Hi! 

Thanks for getting back to me. 

`
  Installed: 1.10.0-1+deb.sury.org~trusty+4
  Candidate: 1.10.1-1~trusty
  Version table:
     1.10.1-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
 *** 1.10.0-1+deb.sury.org~trusty+4 0
        100 /var/lib/dpkg/status
     1.10.0-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.8.1-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.8.0-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.4.6-1ubuntu3.4 0
        500 http://mirrors.digitalocean.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.4.6-1ubuntu3 0
        500 http://mirrors.digitalocean.com/ubuntu/ trusty/main amd64 Packages
`

I can see this probably has nothing to do with your repo. I'll see if I can make heads and tails of how to get updates just from your repo.

**Comment by sareiodata** [comment]
Figured it out. I had the original nginx package added a while back added in /etc/apt/sources.list.d/nginx.list

Commented that out and I could upgrade. 

Sorry to give you extra work! apt-cache policy nginx did put me on the right path. 

Have a great one!
