### ISSUE TITLE
PHP 5.6 version of php-memcache, php-memcached and php-mongo not available for Precise

### ISSUE THREAD

**Issue by andrewmcgilvray** [oerdnj/deb.sury.org#37]
I would like to use the php-memcache and php-memcached packages but they seem to be built for precise but then they are not available because of a "Build for superseded Source" issue : https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6/+packages?field.name_filter=memcache&field.status_filter=&field.series_filter=

Also the php-mongo package does not seem to be available for precise but I cannot see any reason why.

Thanks.

**Comment by lastguru1** [comment]
php-geoip is not available as well :(

**Comment by oerdnj** [comment]
@andrewmcgilvray @lastguru1 I'll take care of it next week (or over weekend). Ping me if you don't hear from me till Wednesday.

**Comment by oerdnj** [comment]
@andrewmcgilvray @lastguru1 Uploaded both updated php-geoip and php-mongo to ppa:ondrej/php5-5.6 and ppa:ondrej/php5.

Let's see if they build correctly and I will close the issue then.
