### ISSUE TITLE
Php 5.6-fpm vs. php 5, mismatch between socket locations and possibly between the sockets.

### ISSUE THREAD

**Issue by tchalvak** [oerdnj/deb.sury.org#370]
I've installed php5.6-fpm and php5.6-cli on Ubuntu (14.04, not that I expect that matters).  Unfortunately, the php5.6-fpm.sock, which was previously located in the new subfolder: /var/run/php/ does not exist!

I was a little confused by this, since none of my php sites were running as a result, yet the nginx configuration was pointing at where I expected the socket to be from the previous upgrade.  This was the resulting error:

`*16419 connect() to unix:/var/run/php/php5.6-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: xxxx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php5.6-fpm.sock:", host: "xxxx"`

Instead, there is a socket for php5-fpm.sock located in /var/run/php5-fpm.sock (note the lack of /php/ subdirectory).

```
$ ls /var/run/ | grep php
php/
php5-fpm.sock=

$ ls /var/run/php/
php5.6-fpm.pid  

```

I worked around this issue for now by using the hack:
```
    cd /var/run/php/
    ln -s ../php5-fpm.sock ./php5.6-fpm.sock
```

Clearly this is not the best solution, and something ungainly is going on with versioning.

Here is my installed packages information:

```
$ apt-cache policy php5-fpm
php5-fpm:
  Installed: (none)
  Candidate: 5.6.22+dfsg-1+donate.sury.org~trusty+1
  Version table:
     5.6.22+dfsg-1+donate.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main amd64 Packages
     5.6.21+dfsg-1+donate.sury.org~trusty+4 0
        100 /var/lib/dpkg/status
     5.5.9+dfsg-1ubuntu4.17 0
        500 http://mirrors.mit.edu/ubuntu/ trusty-updates/universe amd64 Packages
        500 http://mirrors.mit.edu/ubuntu/ trusty-security/universe amd64 Packages
     5.5.9+dfsg-1ubuntu4 0
        500 http://mirrors.mit.edu/ubuntu/ trusty/universe amd64 Packages
$ apt-cache policy php5.6-fpm
php5.6-fpm:
  Installed: 5.6.22-3+donate.sury.org~trusty+1
  Candidate: 5.6.22-3+donate.sury.org~trusty+1
  Version table:
 *** 5.6.22-3+donate.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy php5.6-cli
php5.6-cli:
  Installed: 5.6.22-3+donate.sury.org~trusty+1
  Candidate: 5.6.22-3+donate.sury.org~trusty+1
  Version table:
 *** 5.6.22-3+donate.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy php5-cli
php5-cli:
  Installed: 5.6.21+dfsg-1+donate.sury.org~trusty+4
  Candidate: 5.6.22+dfsg-1+donate.sury.org~trusty+1
  Version table:
     5.6.22+dfsg-1+donate.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main amd64 Packages
 *** 5.6.21+dfsg-1+donate.sury.org~trusty+4 0
        100 /var/lib/dpkg/status
     5.5.9+dfsg-1ubuntu4.17 0
        500 http://mirrors.mit.edu/ubuntu/ trusty-updates/main amd64 Packages
        500 http://mirrors.mit.edu/ubuntu/ trusty-security/main amd64 Packages
     5.5.9+dfsg-1ubuntu4 0
        500 http://mirrors.mit.edu/ubuntu/ trusty/main amd64 Packages
```

**Comment by tchalvak** [comment]
I just did an apt-get update && apt-get upgrade, with the resulting message that:

```
NOTICE: Not enabling PHP 5.6 FPM by default.
NOTICE: To enable PHP 5.6 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi
NOTICE: a2enconf php5.6-fpm
php5.6-fpm stop/waiting
php5.6-fpm start/running, process 32466

```

I don't know whether this is indicating that there's a step that I'm missing because I don't run apache any more, or whether those not running apache can simply ignore that notice.

**Comment by oerdnj** [comment]
The old socket path is not used as it would conflict with old packages. That's intended and documented in the migration guide: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php

But I'll add more text there. 

You can ignore the apache2 text if you are running nginx.

**Comment by tchalvak** [comment]
Yes, what you described is what I would expect.  But in fact the old socket is the only one that I found, there is no new socket file present.

**Comment by oerdnj** [comment]
@tchalvak What PHP FPM packages have you installed? (output of `dpkg -l 'php*-fpm'`)?

**Comment by tchalvak** [comment]
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
un  php-fpm                <none>           <none>           (no description available)
rc  php5-fpm               5.6.21+dfsg-1+do amd64            server-side, HTML-embedded scripting language (FPM
ii  php5.6-fpm             5.6.22-3+donate. amd64            server-side, HTML-embedded scripting language (FPM


I'm not totally familiar with this syntax of dpkg, but maybe this is because I didn't do a `apt-get remove --purge php5-fpm` when I uninstalled it, only an `apt-get remove php5-fpm`

Still I'd have expected there to be two .sock files, but shall I try a full reinstall and full purge of php5?

**Comment by oerdnj** [comment]
You did remove the old `php5-fpm` package, so you have only the sockets defined in the `php5.6-fpm` package. Look into `/etc/php/5.6/fpm/pool.d/*.conf` -> each resource have it's own socket, and the default location is:
```
ondrej@lettie:/etc/php/5.6/fpm/pool.d$ grep ^listen www.conf 
listen = /run/php/php5.6-fpm.sock
listen.owner = www-data
listen.group = www-data
```

Still not sure what the problem here is, though.

**Comment by tchalvak** [comment]
kzqai@hal3k:~$ ls /etc/php/5.6/fpm/pool.d/*.conf
/etc/php/5.6/fpm/pool.d/www-5.6.conf  /etc/php/5.6/fpm/pool.d/www.conf
kzqai@hal3k:~$ ls /etc/php5/fpm/pool.d/
www.conf  www.conf.dpkg-dist
kzqai@hal3k:~$ cd /etc/php/5.6/fpm/pool.d
kzqai@hal3k:/etc/php/5.6/fpm/pool.d$ grep ^listen www.conf 
listen = /var/run/php5-fpm.sock
listen.owner = www-data
listen.group = www-data

kzqai@hal3k:/etc/php/5.6/fpm/pool.d$ ls
www-5.6.conf  www.conf  www.conf.dpkg-dist
kzqai@hal3k:/etc/php/5.6/fpm/pool.d$ grep ^listen www-5.6.conf 
listen = /run/php/php5.6-fpm.sock
listen.owner = www-data
listen.group = www-data


So I have two confs in my php/5.6/fpm/pool.d 
Let me try an uninstall --purge of php5 and a reinstall of php5.6 and see what is left.

**Comment by oerdnj** [comment]
You kept the old `www.conf` from php5 by following the migration guide without really checking what you are doing. By keeping the old configuration you also kept the old socket path. I see no issue here.

**Comment by tchalvak** [comment]
Hmmm, yeah, I guess I wasn't sure whether I'd still need the old `www.conf` later, so I thought a `cp` instead of just a `mv` and forgot to move the old config to a backup location, and thus got the wrong active config.  In the end on my side I just did a total purge of php5 and a complete purge and then reinstall of php5.6 to get to a clean state.

**Comment by cigzigwon** [comment]
But, when working with docker you don't have an old sock file to migrate or really anything to migrate. The issue is that by running apt-get install -y php5.6-fpm we don't get a new sock file nor could it be copied. Am I missing something? Am I supposed to go back to a previous container image that is vulnerable and copy over a sock file? Where is it!?

**Comment by oerdnj** [comment]
Yeah, you are missing a lot by using "docker" without understanding the technologies you are using inside. The default location of the socket file is clearly stated in the default fpm configuration.

**Comment by cigzigwon** [comment]
I wasn't noticing the new subdir you added and by doing so changed the root struct of this install so after noticing that I just added mkdir /run/php. Also after thinking a bit more... I don't see why it is necessary to have the subdir because your www.conf file could have just pointed at /run/php5.6-fpm.sock, leaving /run/php5-fpm.sock intact anyways  and that would have saved me quite a headache today.

**Comment by cigzigwon** [comment]
It's not that I understand the tech here, my approach is coming from dev-ops stance. If dev-ops teams are relying on repos that get hard deprecated then parts of build pipelines do fail. If you are consuming this new repository you are running it against base images that in no case have /run/php. Since the default roll of nginx with php-fpm on debian, cent and ubuntu will install to TCP. I found the migration guide handy but it was misleading. You should use your original www.conf if you want to avoid re-configuration issues. Since this is a backport one could assume that we wouldn't need a new www.conf because the 5.6 builds should be stable with your original confs. I still find your build package superior but you might want to consider how hard deprecating a PPA can be taxing in organizations w/CI build lines. I'm assuming it went to the trash because of vulnerability reasons?

**Comment by Tomdarkness** [comment]
Where is /run/php suppose to come from if you have a fresh install of ubuntu, add the PPA and run `apt-get install -y php5.6-fpm`? I can manually create the directory but I would of thought this would be created when the package is installed.

**Comment by cigzigwon** [comment]
Just use your previous www.conf and keep the listener sock file name the same... change it to 5.6 is you want to use both versions old and new. The issue is that by following the migration guide here you are pointing at a new subdir which no OS has.

**Comment by abstractk** [comment]
Thanks @cigzigwon for your input here. I'm building a docker container from scratch. I can see `www.conf` in `/etc/php/5.6/fpm/pool.d`. This is the result of `grep ^listen www.conf`

```
listen = /run/php/php5.6-fpm.sock
listen.owner = www-data
listen.group = www-data
```

I've also created `/run/php` explicitly in dockerfile but can't seem to locate `php5.6-fpm.sock` . Is there another location where I need to copy it from?

**Comment by cigzigwon** [comment]
You need to look at you nginx logs as something else seems to be the issue.
It should run in the dir you have indicated.

**Comment by tomdtn** [comment]
For anyone looking to find the updated location, the file is not placed in `/run/php`, not `/var/run/php`.

**Comment by OwlGreenApple** [comment]
@tomdtn there are no php5.6-fpm.sock file just php5.6-fpm.pid in that folder

**Comment by cigzigwon** [comment]
Make the directory in the docker file where the sock file will spawn as Ondrej has indicated. The file won't exist until you run the container.
