### ISSUE TITLE
TWO fpms running after switch to ppa:ondrej/php, new one nonfunctional

### ISSUE THREAD

**Issue by rfay** [oerdnj/deb.sury.org#373]
I got the popup yesterday during an update: https://www.evernote.com/l/AA8IatnceehJeq7Mz0qEMnTBzZm_TpsKaHI

So I followed the instructions in it. I installed with 

apt-get install php5.6-fpm

since I have an nginx config and didn't want the apache dependencies.

The result of this is that now two different fpms are running,  And two sets of configuration are out there in /etc/php5 and /etc/php/5.6

Copying the fpm config initially has not sorted out the problem for me. 

At this point, I have stopped the php5.6-fpm and started the php5-fpm:

sudo service php5.6-fpm stop
sudo service php5-fpm start

and have the websites served in service.

Could you please give complete instructions about work that has to be done when transitioning to the new package?

I very much appreciate your work on this, and have donated in the past because it's a great service to the community- thanks!

-Randy

**Comment by oerdnj** [comment]
Each setup is a different and without knowing what was broken with your setup in the first place, it's quite hard to update the documentation. You are still running the old FPM and you need to switch to the php5.6-fpm if you want to use packages from the new repository.

So, could you describe more the "problem" you are talking about?

**Comment by rfay** [comment]
1. The old php did not get uninstalled or moved (/etc/php5/*), and the startup script for the old is still in /etc/init.d
2. The new php conf in /etc/php/5.6 did not inherit the long-time standard debian-type configuration in /etc/php5/*
3. The update/install of the new php5.6 did not stop the old php5-fpm

I would expect that there would need to be some kind of graceful migration of PHP configuration, and removal of the old stuff from your (now deprecated) package. At the very least a set of instructions, and hints about what's changing in the filesystem and what it means.

I haven't completely worked it through, but I had to back out the new php with 

`update-alternatives --config php`

and kill off the php5.6 version that was running. My system is still quite unstable.

The new php failed when trying to run anything drupal-related, including the command-line tool drush. My working assumption is this is because the config was all out-of-the-box config on the new php/5.6, but I haven't had time to fully chase it down.

**Comment by rfay** [comment]
I was able to sort this out on my server, but the upgrade was way painful. The issues were simple, but unexpected. When we change a source PPA as suggested here we don't expect everything to break.

* The full list of needed PHP packages must be reviewed (from the old PPA) and then reinstalled.  In my case, for Drupal, I was missing php5.6-mysql, php5.6-curl, php5.6-gd, php5.6-xml, php5.6-mbstring. So basically, if you're not going to install the packages that were there in php5- then please provide instructions saying "Review the php5-xxx packages you currently require and install them with apt-get install php5.6-xxx"
* The old php5-* packages need to be uninstalled. People need instructions on how to do this. I haven't done this yet, but apt-get remove php5-common will probably get them all for me.
* If removing the old package doesn't do it, and php5-fpm was configured, then it needs to be disabled with `update-rc.d php5-fpm disable`
* The basic suggested install process leaves us with more than one php-fpm running. I was running php5-fpm with php5.6, but installed the new version of fpm. The result was two fpms running.
* Remind people to remove the old /etc/apt/sources.list.d/ondrej-php5-5_6.list after everything else is cleaned up.
* Since php5-opcache is being installed by default, people may need to be warned if they were previously depending on php5-apcu.

**Comment by rfay** [comment]
A further issue: 3rd-party packages may be unusable with this configuration. Example: [New Relic's PHP agent](https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian)

**Comment by AnrDaemon** [comment]
The new PPA is designed in such a way they it can work in parallel to any old installations. So, "switching" isn't really a word that properly describes the process.

**Comment by rfay** [comment]
I'm a little baffled since your (excellent) php56 PPA is clearly deprecated, so I was told by the big bold letters, in no uncertain terms, that I needed to "switch".  So I did :)
