### ISSUE TITLE
Why php5.6-dev requires php7.0-common

### ISSUE THREAD

**Issue by karlos007** [oerdnj/deb.sury.org#375]
karlos@virtual-trusty:~$ sudo apt-get install php5.6-dev
Additional extra packages will be installed:
  autoconf automake autotools-dev build-essential cpp-4.8 debhelper
  dh-apparmor dh-php dpkg-dev fakeroot g++ g++-4.8 gcc-4.8 gcc-4.8-base
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan0 libatomic1 libdpkg-perl libfakeroot libgcc-4.8-dev libgomp1 libitm1
  libltdl-dev libmail-sendmail-perl libpcre16-3 libpcre3 libpcre3-dev
  libpcre32-3 libpcrecpp0 libquadmath0 libsigsegv2 libssl-dev libssl-doc
  libstdc++-4.8-dev libstdc++6 libsys-hostname-long-perl libtool libtsan0 m4
  php-pear php-xml **php7.0-common php7.0-xml** pkg-php-tools po-debconf shtool

Previously installed: php5.6 php5.6-common php5.6-cli (and dependencies).

karlos@virtual-trusty:~$ php -v
PHP 5.6.22-4+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by karlos007** [comment]
sudo apt-get install php5.6-dev
sudo apt-get purge php7.0*

Not the best practice but it looks like working well...

**Comment by oerdnj** [comment]
Disable installing of recommended packages in apt.
