### ISSUE TITLE
Unable to load dynamic library (readline.so)

### ISSUE THREAD

**Issue by trinajstica** [oerdnj/deb.sury.org#377]
I have strange error I can't solve it, maybe you can suggest me what to do. If I run php -v, I have this in output:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/readline.so' - /usr/lib/php/20131226/readline.so: undefined symbol: rl_on_new_line in Unknown on line 0
PHP 5.6.22-4+deb.sury.org~precise+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

I have Ubuntu 12.04.5 LTS server.

**Comment by oerdnj** [comment]
`ldd /usr/lib/php/20131226/readline.so`? 

Guess is that you either have old libedit library or something in `/usr/local/lib`

**Comment by trinajstica** [comment]
ldd /usr/lib/php/20131226/readline.so:

	linux-vdso.so.1 =>  (0x00007ffecbf7d000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f758e12b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f758dd6d000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f758db5d000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f758d936000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f758e55a000)

in /usr/local/lib is only this:

python2.7  
site_ruby

locate libedit:

/var/lib/dpkg/info/libedit2:amd64.list
/var/lib/dpkg/info/libedit2:amd64.md5sums
/var/lib/dpkg/info/libedit2:amd64.postinst
/var/lib/dpkg/info/libedit2:amd64.postrm
/var/lib/dpkg/info/libedit2:amd64.shlibs
/var/lib/dpkg/info/libedit2:amd64.symbols
/usr/lib/x86_64-linux-gnu/libedit.so.2
/usr/lib/x86_64-linux-gnu/libedit.so.2.0.51
/usr/lib/x86_64-linux-gnu/libedit.so.2.11
/usr/share/doc/libedit2
/usr/share/doc/libedit2/TODO.Debian
/usr/share/doc/libedit2/changelog.Debian.gz
/usr/share/doc/libedit2/copyright
/usr/share/lintian/overrides/libedit2

**Comment by oerdnj** [comment]
`apt-cache policy libedit2`

**Comment by trinajstica** [comment]
apt-cache policy libedit2:

libedit2:
  Installed: 3.1-20140620-2+deb.sury.org~precise+4
  Candidate: 3.1-20140620-2+deb.sury.org~precise+4
  Version table:
 *** 3.1-20140620-2+deb.sury.org~precise+4 0
        500 http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/ 
precise/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1-20140620-2+deb.sury.org~precise+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ precise/main 
amd64 Packages
     2.11-20080614-3ubuntu2 0
        500 http://si.archive.ubuntu.com/ubuntu/ precise/main amd64 
Packages

Podjetje: aServis d.o.o., Jenkova 20, 6230 Postojna
Ostali podatki: Tel: 05 726 22 72, ID za DDV: SI 12885304, IBAN: SI56 
1010 0003 5190 625
Hitra izdelava spletnih vizitk, prodajnih strani: 
http://vizitka.xn--strenik-gxb.net
Ugodno gostovanje spletnih strani: https://xn--strenik-gxb.net


pon, 6. jun, 2016 ob 9:49 , je Ondřej Surý <notifications@github.com> 
napisal:

**Comment by oerdnj** [comment]
Could you try: `apt-get install libedit2=3.1-20140620-2+deb.sury.org~precise+1` if it helps? (The versions should be same, but let's try it)

**Comment by trinajstica** [comment]
I did, same thing. Thank you for trying helping me.

PHP Warning:  PHP Startup: Unable to load dynamic library 
'/usr/lib/php/20131226/readline.so' - 
/usr/lib/php/20131226/readline.so: undefined symbol: rl_on_new_line in 
Unknown on line 0
PHP 5.6.22-4+deb.sury.org~precise+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend 
Technologies

pon, 6. jun, 2016 ob 9:54 , je Ondřej Surý <notifications@github.com> 
napisal:
> apt-get install libedit2=3.1-20140620-2+deb.sury.org~precise+1




Podjetje: aServis d.o.o., Jenkova 20, 6230 Postojna
Ostali podatki: Tel: 05 726 22 72, ID za DDV: SI 12885304, IBAN: SI56 
1010 0003 5190 625
Hitra izdelava spletnih vizitk, prodajnih strani: 
http://vizitka.xn--strenik-gxb.net
Ugodno gostovanje spletnih strani: https://xn--strenik-gxb.net

**Comment by oerdnj** [comment]
I just retested it in my precise chroot, and I can't reproduce it. Let me think if I come up with something. I suppose the system is fully upgraded, right?

**Comment by trinajstica** [comment]
Yes, system is fully upgraded and is running ok. Thank you!

Podjetje: aServis d.o.o., Jenkova 20, 6230 Postojna
Ostali podatki: Tel: 05 726 22 72, ID za DDV: SI 12885304, IBAN: SI56 
1010 0003 5190 625
Hitra izdelava spletnih vizitk, prodajnih strani: 
http://vizitka.xn--strenik-gxb.net
Ugodno gostovanje spletnih strani: https://xn--strenik-gxb.net


pon, 6. jun, 2016 ob 10:24 , je Ondřej Surý 
<notifications@github.com> napisal:

**Comment by oerdnj** [comment]
I just noticed that you have two libedit.so.2 providers, that's it.

Where does: `/usr/lib/x86_64-linux-gnu/libedit.so.2` symlink point to?

```
/usr/lib/x86_64-linux-gnu/libedit.so.2.0.51
/usr/lib/x86_64-linux-gnu/libedit.so.2.11
```

It should look like this:
```
# ls -ld /usr/lib/x86_64-linux-gnu/libedit.so.2
lrwxrwxrwx 1 root root 17 May 10 13:12 /usr/lib/x86_64-linux-gnu/libedit.so.2 -> libedit.so.2.0.51
```

**Comment by trinajstica** [comment]
Hi!

That is it!  Now there is no more error. Thank you again! :)


Podjetje: aServis d.o.o., Jenkova 20, 6230 Postojna
Ostali podatki: Tel: 05 726 22 72, ID za DDV: SI 12885304, IBAN: SI56 
1010 0003 5190 625
Hitra izdelava spletnih vizitk, prodajnih strani: 
http://vizitka.xn--strenik-gxb.net
Ugodno gostovanje spletnih strani: https://xn--strenik-gxb.net


pon, 6. jun, 2016 ob 10:49 , je Ondřej Surý 
<notifications@github.com> napisal:

**Comment by ittaskeu** [comment]
Almost the same problem here.
`PHP Startup: Unable to load dynamic library 'readline.so' (tried: /usr/lib/php/20190902/readline.so (/usr/lib/php/20190902/readline.so: undefined symbol: history_list), /usr/lib/php/20190902/readline.so.so (/usr/lib/php/20190902/readline.so.so: cannot open shared object file: No such file or directory)) in Unknown:0`

ldd /usr/lib/php/20190902/readline.so
	linux-vdso.so.1 =>  (0x00007ffdd63f3000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f10245b1000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f1024388000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f1024150000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f1023f3b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1023b71000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f102396d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f10249db000)

/usr/local/lib/
drwxrwsr-x 4 root staff 4096 Mar  4  2021 python2.7
drwxrwsr-x 3 root staff 4096 Jan 28  2021 python3.5

locate libedit
/usr/lib/x86_64-linux-gnu/libedit.so.2
/usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
/usr/share/doc/libedit2
/usr/share/doc/libedit2/TODO.Debian
/usr/share/doc/libedit2/changelog.Debian.gz
/usr/share/doc/libedit2/copyright
/usr/share/lintian/overrides/libedit2
/var/lib/dpkg/info/libedit2:amd64.list
/var/lib/dpkg/info/libedit2:amd64.md5sums
/var/lib/dpkg/info/libedit2:amd64.shlibs
/var/lib/dpkg/info/libedit2:amd64.symbols
/var/lib/dpkg/info/libedit2:amd64.triggers


ls -ld /usr/lib/x86_64-linux-gnu/libedit.so.2
lrwxrwxrwx 1 root root 17 Feb  7  2016 /usr/lib/x86_64-linux-gnu/libedit.so.2 -> libedit.so.2.0.53

Any sugestion how to resolve the problem ?

**Comment by oerdnj** [comment]
My guess is that you are using package that doesn't match your distribution version.

**Comment by oerdnj** [comment]
I can't help you with random other packages. Do a clean reinstall and make sure you know what you are doing at every step.
