### ISSUE TITLE
Error installing libss-dev and libssl-doc on Ubuntu 16.04

### ISSUE THREAD

**Issue by KundK** [oerdnj/deb.sury.org#378]
When trying to install those packages, I get the following errors:

`apt install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-dev-bin libc6-dev libssl-doc linux-libc-dev manpages-dev zlib1g-dev
Suggested packages:
  glibc-doc
The following NEW packages will be installed:
  libc-dev-bin libc6-dev libssl-dev libssl-doc linux-libc-dev manpages-dev zlib1g-dev
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,812 kB/8,016 kB of archives.
After this operation, 32.7 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-dev amd64 1.0.2h-1+deb.sury.org~xenial+1 [1,543 kB]
Err:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-dev amd64 1.0.2h-1+deb.sury.org~xenial+1
  Writing more data than expected (1543126 > 1542904)
Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-doc all 1.0.2h-1+deb.sury.org~xenial+1 [1,269 kB]
Err:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-doc all 1.0.2h-1+deb.sury.org~xenial+1
  Writing more data than expected (1269616 > 1269116)
E: Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/pool/main/o/openssl/libssl-dev_1.0.2h-1+deb.sury.org~xenial+1_amd64.deb  Writing more data than expected (1543126 > 1542904)

E: Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/pool/main/o/openssl/libssl-doc_1.0.2h-1+deb.sury.org~xenial+1_all.deb  Writing more data than expected (1269616 > 1269116)

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by oerdnj** [comment]
I can't reproduce it:
```
root@lettie:/# apt-get update
Hit:1 http://cz.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://cz.archive.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial InRelease [23.8 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease [23.9 kB]
Get:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages [8464 B]
Get:6 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main i386 Packages [8500 B]
Get:7 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main Translation-en [5784 B]
Get:8 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages [38.2 kB]     
Get:9 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main i386 Packages [38.3 kB]
Get:10 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main Translation-en [21.9 kB]
Fetched 263 kB in 0s (450 kB/s)                                   
Reading package lists... Done
root@lettie:/# apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libssl1.0.2 zlib1g-dev
Recommended packages:
  libssl-doc
The following NEW packages will be installed:
  libssl-dev libssl1.0.2 zlib1g-dev
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 2820 kB/2988 kB of archives.
After this operation, 11.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl1.0.2 amd64 1.0.2h-1+deb.sury.org~xenial+1 [1277 kB]
Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-dev amd64 1.0.2h-1+deb.sury.org~xenial+1 [1543 kB]
Fetched 2820 kB in 0s (4352 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libssl1.0.2:amd64.
(Reading database ... 22652 files and directories currently installed.)
Preparing to unpack .../libssl1.0.2_1.0.2h-1+deb.sury.org~xenial+1_amd64.deb ...
Unpacking libssl1.0.2:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4) ...
Selecting previously unselected package libssl-dev:amd64.
Preparing to unpack .../libssl-dev_1.0.2h-1+deb.sury.org~xenial+1_amd64.deb ...
Unpacking libssl-dev:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Setting up libssl1.0.2:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4) ...
Setting up libssl-dev:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
root@lettie:/# apt-get install libssl-doc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libssl-doc
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 1269 kB of archives.
After this operation, 2901 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-doc all 1.0.2h-1+deb.sury.org~xenial+1 [1269 kB]
Fetched 1269 kB in 0s (2546 kB/s)   

Selecting previously unselected package libssl-doc.
(Reading database ... 22787 files and directories currently installed.)
Preparing to unpack .../libssl-doc_1.0.2h-1+deb.sury.org~xenial+1_all.deb ...
Unpacking libssl-doc (1.0.2h-1+deb.sury.org~xenial+1) ...
Setting up libssl-doc (1.0.2h-1+deb.sury.org~xenial+1) ...
```

Have you tried running `apt-get update` again as suggested? It seems like a mismatch in the Release file, but that's generated in the launchpad.

**Comment by KundK** [comment]
Hi Ondrej, 

It seemed to be a problem with our apt-cache server. That held an
outdated version of the package. 

After I deleted it, apt-cache downloaded the latest file and it works
fine. 

Maybe you haven't changed the file name at your last release. 

best regards 

Zsolt 

On 2016-06-07 07:04, Ondřej Surý wrote: 

> I can't reproduce it: 
> 
> root@lettie:/# apt-get update
> Hit:1 http://cz.archive.ubuntu.com/ubuntu xenial InRelease
> Get:2 http://cz.archive.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
> Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial InRelease [23.8 kB]
> Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease [23.9 kB]
> Get:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 Packages [8464 B]
> Get:6 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main i386 Packages [8500 B]
> Get:7 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main Translation-en [5784 B]
> Get:8 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages [38.2 kB] 
> Get:9 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main i386 Packages [38.3 kB]
> Get:10 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main Translation-en [21.9 kB]
> Fetched 263 kB in 0s (450 kB/s) 
> Reading package lists... Done
> root@lettie:/# apt-get install libssl-dev
> Reading package lists... Done
> Building dependency tree 
> Reading state information... Done
> The following additional packages will be installed:
> libssl1.0.2 zlib1g-dev
> Recommended packages:
> libssl-doc
> The following NEW packages will be installed:
> libssl-dev libssl1.0.2 zlib1g-dev
> 0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
> Need to get 2820 kB/2988 kB of archives.
> After this operation, 11.4 MB of additional disk space will be used.
> Do you want to continue? [Y/n] 
> Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl1.0.2 amd64 1.0.2h-1+deb.sury.org~xenial+1 [1277 kB]
> Get:2 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-dev amd64 1.0.2h-1+deb.sury.org~xenial+1 [1543 kB]
> Fetched 2820 kB in 0s (4352 kB/s)
> Preconfiguring packages ...
> Selecting previously unselected package libssl1.0.2:amd64.
> (Reading database ... 22652 files and directories currently installed.)
> Preparing to unpack .../libssl1.0.2_1.0.2h-1+deb.sury.org~xenial+1_amd64.deb ...
> Unpacking libssl1.0.2:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
> Selecting previously unselected package zlib1g-dev:amd64.
> Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4_amd64.deb ...
> Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4) ...
> Selecting previously unselected package libssl-dev:amd64.
> Preparing to unpack .../libssl-dev_1.0.2h-1+deb.sury.org~xenial+1_amd64.deb ...
> Unpacking libssl-dev:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
> Processing triggers for libc-bin (2.23-0ubuntu3) ...
> Setting up libssl1.0.2:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
> Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4) ...
> Setting up libssl-dev:amd64 (1.0.2h-1+deb.sury.org~xenial+1) ...
> Processing triggers for libc-bin (2.23-0ubuntu3) ...
> root@lettie:/# apt-get install libssl-doc
> Reading package lists... Done
> Building dependency tree 
> Reading state information... Done
> The following NEW packages will be installed:
> libssl-doc
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 1269 kB of archives.
> After this operation, 2901 kB of additional disk space will be used.
> Get:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial/main amd64 libssl-doc all 1.0.2h-1+deb.sury.org~xenial+1 [1269 kB]
> Fetched 1269 kB in 0s (2546 kB/s) 
> 
> Selecting previously unselected package libssl-doc.
> (Reading database ... 22787 files and directories currently installed.)
> Preparing to unpack .../libssl-doc_1.0.2h-1+deb.sury.org~xenial+1_all.deb ...
> Unpacking libssl-doc (1.0.2h-1+deb.sury.org~xenial+1) ...
> Setting up libssl-doc (1.0.2h-1+deb.sury.org~xenial+1) ...
> 
> Have you tried running apt-get update again as suggested? It seems like a mismatch in the Release file, but that's generated in the launchpad. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/oerdnj/deb.sury.org/issues/378#issuecomment-224187493
[2]
https://github.com/notifications/unsubscribe/AEvpvppEKKrXYV0jjpO45Q1X13uXDAT3ks5qJQnlgaJpZM4Iuytl

**Comment by oerdnj** [comment]
I think the package name should have changed, unless you are just caching all package on one heap - there might have been same package names between different PPAs.
