### ISSUE TITLE
Installing PHP5.6 non-interactively on Xenial 

### ISSUE THREAD

**Issue by mablae** [oerdnj/deb.sury.org#379]
I want to update my vagrant setup files to
Xenial Xerus and your most up2date 5.6 ppa
but not use php7 at all.
 
How would I configure your PPA and constraint the
versions to avoid installing anything of the php7 packages with apt-get?
 
Is there a non-interactive way to do this while provisioning the vagrant VM?
  
Thanks in advance.

**Comment by oerdnj** [comment]
Disable installing recommended packages in apt-get, either by dropping conf snippet in /etc/apt/apt.conf.d/ or by adding `--no-install-recommends` (check the man page, writing that from top of my head). 

If that doesn't help, you'll have to be more specific.

**Comment by mablae** [comment]
Thanks for the pointer. I will RTFM :smile:

**Comment by oerdnj** [comment]
Ok, then. I am closing this, but feel free to reopen if you encounter any issues.
