### ISSUE TITLE
Cockpit - A remote manager for GNU/Linux servers

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#38]
FWIW, it depends on systemd but this project may be off interest to package...

https://github.com/cockpit-project/cockpit

From Stef Walter at Redhat..

_We're looking for someone to get a PPA started for Ubuntu, or at least get one started, and then I could perhaps contribute to it. I agree that it should be pretty straightforward._

**Comment by stefwalter** [comment]
I'm not very familiar with how to do rules, and break down a build into sub packages, etc. But I can help with sending updates for the package if that's helpful.

**Comment by oerdnj** [comment]
@stefwalter Could you please describe a bit more what needs to be packaged? Maybe a reference RPM structure?

Also I usually don't do only PPAs, so you will get a full Debian package first and then PPA spinoff.

**Comment by jpsutton** [comment]
I just created a Debian package configuration (control and rules files).  I tested them on my local Debian server and they seem to produce a usable package as I could easily start the service through systemctl after installation.

Can someone let me know how I can contribute them?

**Comment by jpsutton** [comment]
Nix that last question.  I created a PPA and published my build here (for the most recent Ubuntu LTS release):

https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit

**Comment by markc** [comment]
Well done. I tried to run it on utopic (and eventually vivid on my laptop) as I no longer have any trusty setups and I don't think systemd will work in a container. FWIW I got these install errors on a utopic box which I will look into.

    The following packages have unmet dependencies:
     cockpit : Depends: libsystemd-daemon0 (>= 31) but it is not installable
               Depends: libsystemd-journal0 (>= 38) but it is not installable

**Comment by stefwalter** [comment]
> I just created a Debian package configuration (control and rules files). I tested them on my local Debian server and they seem to produce a usable package as I could easily start the service through systemctl after installation.

> Can someone let me know how I can contribute them?

I think long term the concrete reason to have spec files or distribution packaging stuff upstream is to use in our CI. As a corollary, any distribution packaging upstream will bit rot unless we base CI builds on it. If we do Debian CI builds, then it would make sense to have the control and rules files upstream, otherwise not.

> Nix that last question. I created a PPA and published my build here (for the most recent Ubuntu LTS release)

Nice :)

**Comment by jpsutton** [comment]
@markc I just uploaded for Utopic, so change your sources.list entry to point to it and try installing again.

@stefwalter In the time between my first and second comments yesterday, I ended up having to hack a little more on the packing config to get it to build on Launchpad.  The worst of it was patching autobuild.sh to not run "npm install" (as Launchpad's build farm apparently won't let you download stuff from the internet during the build process) and then taring up a set of the files it was downloading and added them to the build configuration.  I'd rather not push that sort of a hack upstream if at all possible.  I'm certainly open to suggestions on what to do with it though.

**Comment by stefwalter** [comment]
> The worst of it was patching autobuild.sh to not run "npm install" (as Launchpad's build farm apparently won't let you download stuff from the internet during the build process) 

Can you build from a cockpit released tarball? Because we include all the files necessary so you don't need to touch npm or nodejs code at all. For us npm and nodejs are treated like autoconf and automake. They are dependencies necessary to *develop* cockpit, but not to *build* from the tarball. Does that make sense?

**Comment by jpsutton** [comment]
Makes total sense.  I don't see why I shouldn't be able to build from the tarball.  I'll give it a shot when I'm off of the day job (which sadly doesn't bankroll my efforts in FLOSS land :\ ).

**Comment by oerdnj** [comment]
Folks, could you take this discussion elsewhere? Upstream seems to be a good place. I would be happy to sponsor the package in Debian if there's interest, but this discussion is now off-topic here as it's not related to deb.sury.org packages...

**Comment by stefwalter** [comment]
Sounds good to me. @jpsutton cockpit-devel mailing list https://lists.fedorahosted.org/mailman/listinfo/cockpit-devel is also a decent place if that works for you.
