### ISSUE TITLE
[?] apache_request_headers missing in FCGI SAPI

### ISSUE THREAD

**Issue by AnrDaemon** [oerdnj/deb.sury.org#380]
From the http://php.net/apache_request_headers :

> 5.4.0 This function became available under FastCGI.

While at the same time:

 PHP Version 5.6.22-4+deb.sury.org~trusty+1
 Server API FPM/FastCGI

 PHP Fatal error: Call to undefined function apache_request_headers() in …

**Comment by oerdnj** [comment]
FPM != FastCGI see https://bugs.php.net/bug.php?id=62596

**Comment by AnrDaemon** [comment]
Thanks. Sorry for noise.
