### ISSUE TITLE
[PHP 7.0] libxml issue

### ISSUE THREAD

**Issue by IandroidFan** [oerdnj/deb.sury.org#381]
Hello. PHP 7.0.4 builded with libxml 2.9.3 which have an serious bug. An CMS when importing languagepack (an XML-file) throwing error due to A bug in libxml.
Record from libxml 2.9.4 changelog:
Bug 760183: REGRESSION (v2.9.3): XML push parser fails with bogus UTF-8 encoding error when multi-byte character in large CDATA section is split across buffer .
So can you build PHP 7.0 with new version of libxml, please? It will help bug amount of users.
Thank you.

**Comment by oerdnj** [comment]
Can you try adding extra `ppa:ondrej/php-qa`, there's libxml2 2.9.4 build, but I need confirmation it actually helps and doesn't break anything.

**Comment by IandroidFan** [comment]
I was added your repository to the system and runned `apt update && apt upgrade` but phpinfo() in "dom" section says `libxml Version	2.9.3`, not 2.9.4.

**Comment by oerdnj** [comment]
And what does: `apt-cache policy libxml2` says?

**Comment by IandroidFan** [comment]
`libxml2:
  Installed: 2.9.4-1+deb.sury.org~xenial+2
  Candidate:   2.9.4-1+deb.sury.org~xenial+2
  Versions table:
 *** 2.9.4-1+deb.sury.org~xenial+2 500
        500 http://ppa.launchpad.net/ondrej/php-qa/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.3+dfsg1-1ubuntu0.1 500
        500 http://mirrors.digitalocean.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.9.3+dfsg1-1 500
        500 http://mirrors.digitalocean.com/ubuntu xenial/main amd64 Packages
`
I have translated strings to english because I have langpack installed on my system.

**Comment by oerdnj** [comment]
If the binaries are linked with system libxml2

1. for FPM:
```
$ ldd /usr/sbin/php-fpm7.0 | grep libxml2
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f66406f7000)
```

2. for apache2:
```
$ ldd /usr/lib/apache2/modules/libphp7.0.so | grep libxml2
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f6fc4d03000)
```

3. for cli
```
$ ldd /usr/bin/php7.0 | grep libxml2
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fd777068000)
```

then it's just the PHP output which is wrong and it should use libxml2 2.9.4 from your system.

**Comment by IandroidFan** [comment]
Ok., tried installing languagepack to CMS what I use and all works fine. Thank you!

**Comment by oerdnj** [comment]
I am going to upload the update to the main repo now.
