### ISSUE TITLE
php5-apcu requires php5.5

### ISSUE THREAD

**Issue by crankycyclops** [oerdnj/deb.sury.org#383]
If I install php5.6, then try to install php5-apcu, it attempts to install php5.5. php-apcu, by contrast, requires me to install php 7. There doesn't seem to be a way to install apcu for 5.6. This forces me for the time being to stick with the deprecated 5.6 ppa. Is there something I've missed?

**Comment by oerdnj** [comment]
`php-apcu` doesn't require to install php7.0, it's just default apt-get setup that pulls Recommends. Use `--no-recommends` with apt-get, or change the system-wide configuration to not pull Recommends.
