### ISSUE TITLE
PHP 5.6 Redis module will not work

### ISSUE THREAD

**Issue by clubdeuce** [oerdnj/deb.sury.org#384]
I have installed the following packages on Ubuntu 14-04:

+ php-fpm
+ php-curl
+ php-gd
+ php-mysql
+ php-redis
+ php-xdebug
+ redis-server
+ php5.6-fpm
+ php5.6-curl
+ php5.6-gd
+ php5.6-mysql

I am able to have both PHP-FPM 5.6 and 7.0 running concurrently. However, the `redis` module will not work with PHP-FPM 5.6, despite the `ini` file being included in the PHP-FPM 5.6 configuration. The `redis` module works as expected with PHP-FPM 7.0, however.

Any thoughts as to why this is happening?

**Comment by clubdeuce** [comment]
![screen shot 2016-06-13 at 1 36 34 pm](https://cloud.githubusercontent.com/assets/2600497/16017015/f5ab2b40-316b-11e6-89b1-de6c6a8df724.png)

**Comment by clubdeuce** [comment]
vagrant@host:~$ cat /etc/php/5.6/mods-available/redis.ini 
extension=redis.so

**Comment by clubdeuce** [comment]
It seems the `php-memcached` module has the same issue. The behavior is identical.

**Comment by clubdeuce** [comment]
![screen shot 2016-06-13 at 2 06 54 pm](https://cloud.githubusercontent.com/assets/2600497/16017919/234170c4-3170-11e6-8f82-8981a51462a8.png)

**Comment by oerdnj** [comment]
What does "doesn't work" and "same behavior" mean?

**Comment by clubdeuce** [comment]
As you can see from the screenshots I posted, the `redis` module configuration file is being parsed. However, further down the `phpinfo()` results page there is no information regarding the `redis` module:
![screen shot 2016-06-13 at 2 32 48 pm](https://cloud.githubusercontent.com/assets/2600497/16018726/bed967fa-3173-11e6-8577-36e40272297a.png )

 The `memcached` module does the same thing:

![screen shot 2016-06-13 at 2 33 47 pm](https://cloud.githubusercontent.com/assets/2600497/16018764/ec683ce6-3173-11e6-84ca-a9523bfcbe56.png)

**Comment by oerdnj** [comment]
What does `php5.6 -m` output?

**Comment by clubdeuce** [comment]
I was unaware of the `-m` option. It seems the cause of this issue is:

vagrant@wplib:/var/www$ php5.6 -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/redis.so' - /usr/lib/php/20131226/redis.so: undefined symbol: igbinary_serialize in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/memcached.so' - /usr/lib/php/20131226/memcached.so: undefined symbol: igbinary_serialize in Unknown on line 0

**Comment by oerdnj** [comment]
Could you post output of:
`apt-cache show php-redis php-memcached`
and
`apt-cache policy php-redis php-memcached`
It seems to me, you are using outdated packages.

**Comment by clubdeuce** [comment]
`apt-cache show php-redis php-memcached` yields:

```
Package: php-redis
Priority: optional
Section: php
Installed-Size: 1038
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: amd64
Version: 2.2.7-394-g892f928+2.2.7-4+deb.sury.org~trusty+1
Suggests: redis-server
Provides: php5.5-redis, php5.6-redis, php7.0-redis
Depends: php-igbinary, php-common (>= 1:7.0+33~), phpapi-20151012 | phpapi-20131226 | phpapi-20121212, libc6 (>= 2.14)
Filename: pool/main/p/php-redis/php-redis_2.2.7-394-g892f928+2.2.7-4+deb.sury.org~trusty+1_amd64.deb
Size: 202122
MD5sum: e4b67e11bc1d343637e049c295c60b7b
SHA1: 5d8fcee058082e1f8475235749b5db115921e843
SHA256: 0c3dbcd24d204984223d1e63bdeb68e08b128043fdd2ba12945fad5765224658
Description-en: PHP extension for interfacing with Redis
 This extension allows php applications to communicate with the Redis
 persistent key-value store.  The php-redis module provides an easy
 object oriented interface.
Description-md5: b8a3de89cf7f4311899f1f5751dbc60a

Package: php-memcached
Priority: optional
Section: php
Installed-Size: 387
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: amd64
Version: 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3
Provides: php5.5-memcached, php5.6-memcached, php7.0-memcached
Depends: php-igbinary, php-msgpack, ucf, php-common (>= 1:7.0+33~), phpapi-20151012 | phpapi-20131226 | phpapi-20121212, libc6 (>= 2.14), libmemcached11, libsasl2-2 (>= 2.1.24), zlib1g (>= 1:1.1.4)
Filename: pool/main/p/php-memcached/php-memcached_3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3_amd64.deb
Size: 64246
MD5sum: a3933000abbee7dfa7480af510377983
SHA1: 80fcc97aa8902139a8d7b47d0cd33cedb835d20a
SHA256: 7aca84300c9a51b2dfa6db4dc237372a73f4efa0bc602c7e0481644b0e19b8cf
Description-en: memcached extension module for PHP, uses libmemcached
 Memcached is a caching daemon designed especially for dynamic web
 applications to decrease database load by storing objects in memory.
 .
 This extension uses libmemcached library to provide API for
 communicating with memcached servers.
Description-md5: 8dd75c15765c7e1abc72767ad4d0eaba
```

**Comment by clubdeuce** [comment]
`apt-cache policy php-redis php-memcached` yields:

```
php-redis:
  Installed: 2.2.7-394-g892f928+2.2.7-4+deb.sury.org~trusty+1
  Candidate: 2.2.7-394-g892f928+2.2.7-4+deb.sury.org~trusty+1
  Version table:
 *** 2.2.7-394-g892f928+2.2.7-4+deb.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
php-memcached:
  Installed: 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3
  Candidate: 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3
  Version table:
 *** 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by oerdnj** [comment]
Is `php-igbinary` installed: `apt-cache policy php-igbinary`?
Or did you disable it by hand?
Could you just re-enable it with `phpenmod igbinary`.

**Comment by clubdeuce** [comment]
`phpenmod igbinary` solved the problem.

Is there a reason this module was not activated when `php5.6-fpm` was installed? Given the list of modules I posted in the original comment for this issue, should they be added in a certain order.

Thank you for your assistance on this. I am very appreciative.

**Comment by oerdnj** [comment]
Could you check the logs in `/var/log/apt`? They might give a hint why it was not enabled. (There might be some race condition somewhere.)

**Comment by voku** [comment]
only for info: I also needed to execute ```phpenmod msgpack```

**Comment by austinPatel** [comment]
same issue i have faced could you suggest me more  below is log
 
Start-Date: 2017-03-20  18:11:46
Commandline: apt-get install redis-server
Requested-By: software
Install: redis-tools:amd64 (2:3.0.6-1, automatic), libjemalloc1:amd64 (3.6.0-9ubuntu1, automatic), redis-server:amd64 (2:3.0.6-1)
End-Date: 2017-03-20  18:11:55

Start-Date: 2017-03-20  18:12:14
Commandline: apt-get install php5.6-redis
Requested-By: software
Upgrade: php-redis:amd64 (2.2.7-389-g2887ad1+2.2.7-1, 3.1.1-1+deb.sury.org~xenial+1)
End-Date: 2017-03-20  18:12:16

**Comment by austinPatel** [comment]
i also find the log in redis-server.log 
the server is now ready to accept connections on port [6379]
so kindly please help me to get redis on server(phpinfo)

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/384#issuecomment-225672956 ?

**Comment by austinPatel** [comment]
its done
