### ISSUE TITLE
Is it possible to use this repo just for openssl and stick with Ubuntu's PHP5.5?

### ISSUE THREAD

**Issue by partounian** [oerdnj/deb.sury.org#386]
Sorry if this is in the wrong place, but I was wondering if it's possible to use your great repo simply for openssl, and not php5.5. The reason for this is to use ALPN on Nginx. 
I will use it alongside this.
https://launchpad.net/~fxr/+archive/ubuntu/nginx-mainline-alpn

**Comment by oerdnj** [comment]
The simplest would be to use ppa:ondrej/nginx, it's just openssl and nginx 
there. Please bear in mind that you need to recompile anything not already 
linked with 1.0.2.

**Comment by partounian** [comment]
Thank you for the input, I installed it on our dev server, the two other apps I have installed are PHP and Percona 5.6 which I am thinking about. But, I don't believe those need to be recompiled correct? 

I love your work for the community, you don't plan to have support Nginx mainline on that repo do you?

**Comment by partounian** [comment]
I apologize for asking, but I realized in most cases those two do not need SSL.

**Comment by oerdnj** [comment]
Yes, I plan to support nginx mainline in ppa:ondrej/nginx. Check my Patreon blog on the topic: https://www.patreon.com/oerdnj

TLS Police says nobody needs SSL nowadays, but I believe that OpenSSL 1.0.2 is needed only for ALPN support in HTTP/2, so I think you are fine.
