### ISSUE TITLE
PHP 5.5 End of Life

### ISSUE THREAD

**Issue by jcshort** [oerdnj/deb.sury.org#387]
As I'm sure you're aware, 5.5 EOL even for security updates is scheduled for 10 July 2016, less than a month away per http://php.net/supported-versions.php

Do you intend to continue to provide support for 5.5 in your [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) past that date?  Will you be backporting security patches from 5.6?  At what point can we expect 5.5 to be removed from the PPA?

**Comment by oerdnj** [comment]
Yep, I am aware of that.

I will provide some support past the date, but it will best-effort. The removal will be based on the amount of security vulnerabilities found in PHP 5.5 past the EOL. Basically I will schedule the removal when unbearable. Please make sure you either follow twitter.com/debsuryorg or patreon.com/oerdnj for the updates.

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/7174814

**Comment by ihipop** [comment]
I think it should be move the old package  to an `old stable  repo` to archive them, not just delete them

**Comment by oerdnj** [comment]
You can also store old radioactive material in your backyard. I am not going to do neither as I am not going to help people run outdated vulnerable software.

**Comment by jaymecd** [comment]
Ubuntu `14.04 LTS` end of life is `Apr-2019`, it would be fair enough to provide at least archive of 5.5 (i.e., educational/history purpose) and not burn the bridge by eliminating it.

@oerdnj If you don't want to host it by urself, are there any live mirrors? or is it possible to make mirror and host by myself?

**Comment by oerdnj** [comment]
There's a git-buildpackage git repository of the "educational/history" purpose. I am neither going to provide nor help other people provide packages with vulnerable software.
