### ISSUE TITLE
Problems of phpenmod/phpdismod with opcache

### ISSUE THREAD

**Issue by rommsen** [oerdnj/deb.sury.org#388]
Hi,

first, thanks for all your work.

We have some problems with the phpenmod/phpdismod scripts. In development we usually turn opcache off, so we use `sudo [phpenmod|phpdismod] -v 5.6 -s cli opcache` regularly. The problem is, that the scripts create the symlink: `05-opcache.ini` but when installing php via apt-get the file is called `10-opcache.ini`. So after installing and calling phpenmod we have  `05-opcache.ini` and `10-opcache.ini` files in `/etc/php/5.6/cli/conf.d/` which leads to ``Cannot load Zend OPcache - extension already loaded` errors.

**Comment by oerdnj** [comment]
Is it possible that you create `/etc/php/5.6/mods-available/opcache.ini` from some management scripts? What is the contents of `/etc/php/5.6/mods-available/opcache.ini`?

`10-opcache.ini` is the correct value.

**Comment by rommsen** [comment]
you are right. I created the ini via ansible. I did not change the opcache ini file while upgrading the repo from the old `php5-5.6` to `php`
It says in there `; priority=05`.  Never knew that this is whats used for the naming of those files.

Thanks for getting back to this

**Comment by oerdnj** [comment]
The phpenmod/phpdismod probably should be slightly smarter and don't create duplicities, but it's in the "accepting patches" priority pile :)
