### ISSUE TITLE
Can't install on ubuntu 15.10

### ISSUE THREAD

**Issue by PieerotGG** [oerdnj/deb.sury.org#390]
Hello,
I have a problem on my computer: I do this :
`sudo add-apt-repository ppa:ondrej/php`
`sudo apt-get update`
`sudo apt-get install php7.0`

But he return : 

> E: Unable to locate package php5.6
E: Couldn't find any package by regex 'php5.6'
E: Unable to locate package php7.0
E: Couldn't find any package by regex 'php7.0'

**Comment by oerdnj** [comment]
What is the contents of `/etc/apt/sources.list.d/*php*.list`?

**Comment by PieerotGG** [comment]
No content

**Comment by PieerotGG** [comment]
I haven't the *php*.list

**Comment by PieerotGG** [comment]
the command didn't create me all files

**Comment by PieerotGG** [comment]
I only have this :
`cinelerra-ppa-ubuntu-ppa-vivid.list       obsproject-ubuntu-obs-studio-vivid.list.save  spotify.list                               webupd8team-ubuntu-sublime-text-2-vivid.list       webupd8team-ubuntu-sublime-text-3-vivid.list.save
cinelerra-ppa-ubuntu-ppa-vivid.list.save  ondrej-ubuntu-php-vivid.list                  spotify.list.save                          webupd8team-ubuntu-sublime-text-2-vivid.list.save
obsproject-ubuntu-obs-studio-vivid.list   ondrej-ubuntu-php-vivid.list.save             upubuntu-com-ubuntu-devel-vivid.list.save  webupd8team-ubuntu-sublime-text-3-vivid.list
`

**Comment by oerdnj** [comment]
Ubuntu Vivid is no longer supported release. Upgrade to Wily or Xenial first.
