### ISSUE TITLE
nginx 1.11.1 (security release) and CoudFlare SPDY + HTTP2 patch

### ISSUE THREAD

**Issue by gslin** [oerdnj/deb.sury.org#394]
Would you like to upgrade nginx to 1.11.1 (security release) and merge https://github.com/cloudflare/sslconfig/pull/36 this patch?

SPDY is still important for Android devices due to Android 3.0 to 4.4 (which support SPDY but not HTTP/2), and Google Chrome does not support SPDY anymore.

**Comment by oerdnj** [comment]
nginx 1.11.1 is not going to happen, the PPA already has 1.10.1 (production release), but I have just merged the SPDY patch and uploaded 1.10.1 with SPDY re-enabled.

**Comment by gslin** [comment]
Thanks, it works pretty well.

**Comment by chillophil** [comment]
Don't seem working for me =/

I added your nginx repo and installed the latest version

> 1.10.1-1+0~20160602102431.1+jessie~1.gbp52025f

on my Debian 8.4 jessie server

It's okay to define `listen 443 ssl spdy http2;` but spdy is not served - even not with `listen 443 ssl spdy;` only.

So what am I doing wrong?

**Comment by oerdnj** [comment]
@chillophil Maybe because I updated only the Ubuntu PPAs?

**Comment by chillophil** [comment]
@oerdnj sure, figured it out myself - already edited my comment =)

**Comment by yaung** [comment]
@gslin Do you have the patch for nginx1.10.1 or nginx1.11.1 ? Thanks for your sharing !
