### ISSUE TITLE
On every install/upgrade, mpm_worker is disabled and mpm_prefork is enabled 

### ISSUE THREAD

**Issue by koehn** [oerdnj/deb.sury.org#395]
Every time I upgrade php5.6 and php7.0, the installer disables mpm_worker and re-enables mpm_prefork, forcing me to switch my configuration back after the installation completes. Can you make it not do this?

**Comment by oerdnj** [comment]
Can you explain a scenario where you need `libapache2-mod-phpX.Y` installed, but you don't actually use it?

**Comment by koehn** [comment]
How about this one? 

    # apt remove libapache2-mod-php7.0 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following extra packages will be installed:
      libapache2-mod-php5 libonig2 owncloud-deps-php5 php5 php5-cli php5-common
      php5-curl php5-gd php5-intl php5-json php5-mcrypt php5-mysqlnd php5-pgsql
      php5-readline php5-sqlite
    Suggested packages:
      php5-apcu php-apc php5-imagick php5-ldap php-smbclient libsmbclient
      php5-user-cache
    The following packages will be REMOVED:
      libapache2-mod-php7.0 owncloud-deps-php7.0
    The following NEW packages will be installed:
      libapache2-mod-php5 libonig2 owncloud-deps-php5 php5 php5-cli php5-common
      php5-curl php5-gd php5-intl php5-json php5-mcrypt php5-mysqlnd php5-pgsql
      php5-readline php5-sqlite
    0 upgraded, 15 newly installed, 2 to remove and 0 not upgraded.
    Need to get 5,482 kB of archives.
    After this operation, 17.8 MB of additional disk space will be used.

**Comment by koehn** [comment]
If you could detect the worker mode instead of assuming that the presence of an installed packed implied a worker mode, that would be better.

**Comment by koehn** [comment]
Try `apache2ctl -V`

**Comment by oerdnj** [comment]
God, that's ... not very wise from owncloud. They should be depending on `php7.0`, so you can freely choose your PHP SAPI.

Filled https://github.com/owncloud/core/issues/25283 and I'll think on how to fix this in `php7.0`, as `apache2_invoke` tracks who disabled the module, it might be just a matter of checking that out and don't switch mpm if the package was disabled by system administrator.

**Comment by oerdnj** [comment]
@koehn Looks like ownCloud people will fix the package. Meanwhile I uploaded php7.0 version `7.0.8-2+deb.sury.org~xenial+2~mpmfix` to [ppa:ondrej/php-qa](https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages?batch=300). Could you please test it if it's not too horribly broken? I haven't spotted any errors, but I haven't had time to test the postinst script myself and I won't be able till tomorrow.

**Comment by koehn** [comment]
I'll take a peek, not sure I'll be able to before tomorrow.

**Comment by oerdnj** [comment]
I did some basic tests and it seems to be fixed in the package I uploaded to `ppa:ondrej/php-qa`. I will do upload to the main PPA shortly after the new packages are built (there are some more changes stacked up).

**Comment by oerdnj** [comment]
JFTR the upload has landed main PPA and the packages are building right now. Also owncloud folks has a working solution, so you might be able to uninstall `libapache2-mod-php7.0` in some future upgrade.

**Comment by koehn** [comment]
Thanks a ton! I really appreciate it. [finds donation page]
