### ISSUE TITLE
libapache2-mod-php7.0 should depend on apache2

### ISSUE THREAD

**Issue by baurmatt** [oerdnj/deb.sury.org#396]
### What did you do?
```
apt-get install libapache2-mod-php7.0
...
apt-get install apache2
```

### What did you expect to happen?
A functional Apache/PHP webserver setup

### What did actually happen?
Apache2 configured with mpm_event which isn't suitable for PHP.

It might work to add a depenedecy to apache2 for the libapache2-mod-php7.0. This needs probably also be fixed for all libapache-mod-php* packages.

**Comment by oerdnj** [comment]
https://wiki.debian.org/Apache/PackagingFor24#Modules
> Take special care not to depend' on apache2 or apache2-bin. Your module binary package must depend on the virtual API version package we provide instead.

`a2dismod mpm_event && a2enmod mpm_prefork`

or even installing the packages in reverse order will just work.

Not sure if I can really do anything here.

**Comment by baurmatt** [comment]
I know that this is kind of a lame excuse, but Debian themself depend on the apache2 package:

```
root@mbaur-debian:/home/debian# apt-cache show libapache2-mod-php5
Package: libapache2-mod-php5
Source: php5
Version: 5.6.22+dfsg-0+deb8u1
Installed-Size: 9649
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: amd64
Depends: libbz2-1.0, libc6 (>= 2.15), libcomerr2 (>= 1.01), libdb5.3, libgssapi-krb5-2 (>= 1.6.dfsg.2), libk5crypto3 (>= 1.6.dfsg.2), libkrb5-3 (>= 1.6.dfsg.2), libonig2 (>= 5.9.5), libpcre3 (>= 1:8.35), libqdbm14 (>= 1.8.74), libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 4.1.1), libxml2 (>= 2.9.0), zlib1g (>= 1:1.1.4), apache2-api-20120211, apache2 (>= 2.4), mime-support, php5-common (= 5.6.22+dfsg-0+deb8u1), php5-cli, php5-json, libmagic1, ucf, tzdata
Suggests: php-pear
Conflicts: libapache2-mod-php4, libapache2-mod-php5filter
...
```
Perhaps it might be also an option to just depend on "apache2-mpm-prefork (>> 2.0.52) | apache2-mpm-itk" this was done with Debian 7.

**Comment by oerdnj** [comment]
Yep, `libapache2-mod-php5` in Debian stable hasn't been fixed (and won't be). (BTW You do understand that I am also the primary packager of PHP in Debian and therefore author of `libapache2-mod-php5` package?)

Neither `apache2-mpm-prefork` nor `apache2-mpm-itk` exist in Apache 2.4 packaging. They are just dummy packages. I still don't understand what are you trying to accomplish? Installing `apache2` first and then installing `libapache2-mod-php5` will just work, or adjusting the MPMs with the command I gave in previous command.

**Comment by baurmatt** [comment]
Oh, no i wasn't aware that you're also the core maintainer of the PHP packages in Debian. Sorry! :)

We work with an environment where we sometimes can't really control which packages is going to be installed first and i want to minimize debugging work and/or workarounds. Also, i feel that I shouldn't have to think about the installation order of packages just to get a working setup. Isn't there any way to accomplish this? Just for my understanding: Why isn't the dependency of the apache2 package removed within Debian?

**Comment by oerdnj** [comment]
I added `Recommends: apache2` to `libapache2-mod-phpX.Y`. That might solve most issues as it will pull apache2 automatically in the default installation (that has APT::Install-Recommended = on;). The new packages are building in `ppa:ondrej/php-qa` and I will upload them to `ppa:ondrej/php` shortly after the finish to build (it's not the only change there).

**Comment by oerdnj** [comment]
And to answer your question about Debian packages:
* (jessie) I either ignored the lintian warning before jessie was released, or the lintian warning was added later; and this is not a change we want to do in stable release
* (stretch) php5 is going to be removed from testing soon and replaced with `php7.0` (like tomorrow or day after that)

**Comment by baurmatt** [comment]
Works great, thanks a lot! :)
