### ISSUE TITLE
PHP no longer works after upgrading to 5.6

### ISSUE THREAD

**Issue by zodthepossum** [oerdnj/deb.sury.org#397]
Hi
I've been following along with your instructions on how to upgrade PHP on Ubuntu 14.04 (VirtualBox) server with Apache 2.4.7, since the upgrade the only sites that I browse to are sites with no PHP.

The PHP sites are just showing as text in the browser, it is like PHP is not working
I checked the tail on Apache log after i try to browse to one of the sites and have the following;

Cannot adopt OID in UCD-SNMP-MIB: laErrMessage ::= { laEntry 101 }
Cannot adopt OID in UCD-SNMP-MIB: laErrorFlag ::= { laEntry 100 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadFloat ::= { laEntry 6 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadInt ::= {laEntry 5 }
Cannot adopt OID in UCD-SNMP-MIB: laConfig ::= { laEntry 4 }
Cannot adopt OID in UCD-SNMP-MIB: laLoad ::= { laEntry 3 }
Cannot adopt OID in UCD-SNMP-MIB: laNames ::= { laEntry 2 }
Cannot adopt OID in UCD-SNMP-MIB: laIndex ::= { laEntry 1 }
[Thu June 30 14:31:53.460276 2016] [mpm_prefork:notice] [pid 1484] AH00163: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Thu June 30 14:31:53.460338 2016] [core:notice] [pid 1484] AH00094: Command Line: '/usr/sbin/apache2'

When I check info.php everthing seems normal except it says Virtual Directory Support disabled

Would appreciate any help
Zod

**Comment by zodthepossum** [comment]
update
Found this link;
https://www.digitalocean.com/community/questions/installed-php-7-0-now-returns-errors
and installed snmp as suggested and now my PHP seems to be working - phew!
zod

**Comment by oerdnj** [comment]
I'll add `Recommends: snmp` to `php7.0-snmp` package.

**Comment by oerdnj** [comment]
Ended with `Depends`, will be included in next update.
