### ISSUE TITLE
Is it possible to open source the build process?

### ISSUE THREAD

**Issue by PeterDaveHello** [oerdnj/deb.sury.org#399]
Thanks for all the awesome work, no offense, just a small question, since I'm wondering if people can learning something from this, or contribute something. Thank you!

**Comment by oerdnj** [comment]
It is open-source. And source packages and git repository is available.

**Comment by PeterDaveHello** [comment]
hmmm ... sorry, so I may missed something, is there a repo for the scripts or configs about the package build process? Or they are all on the PPA? I see a repo here: https://github.com/oerdnj/pkg-php, but it's old, and didn't see a repo for nginx.

**Comment by oerdnj** [comment]
`apt-get source <foo>` is your friend. If you want to learn deb packaging there's a lot of material on the Web..

**Comment by PeterDaveHello** [comment]
Okay, thanks.
