### ISSUE TITLE
php5-memcached tryies to configure into/etc/php/7.0/mods-available/memcached.ini

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#400]
php5-memcached tryies to configure into /etc/php/7.0/mods-available/memcached.ini - most probably just an copy and paste issue?

I am running a dual-stack php7 / php5.5 installation

reproduction:

```
apt-get install -y php7.0
apt-get install -y php7.0-memcached
apt-get install -y php5.5
apt-get install -y php5.5-memcached
```

**Comment by oerdnj** [comment]
There's no `php5-memcached` nor `php7.0-memcached` nor `php5.5-memcached`, only `php-memcached` that includes extensions for all supported releases. Care to elaborate what the problem is?

**Comment by EugenMayer** [comment]
@oerdnj that is interesting - i have no idea were all those packages actually come from. I will elaborate and come back, if needed providing a docker image for reproduction.

Its obvious you are right, https://packages.sury.org/php/pool/main/p/php5.5/ none of those packages are present. Let me have a closer, detailed look.

Sorry for the dups - i though those things are not related in general, so i created separate issues. Guess i have to get used to your structure, give me some time :)

**Comment by oerdnj** [comment]
Ok, so far it's in the expectations vs reality area ;). Feel free to reopen.

Since the external extensions need to be built every time a new PHP major.minor version it's introduced, they need more general name so packages don't pop up and disappear on rebuild as it requires debian/control modification.

**Comment by EugenMayer** [comment]
Ok so here is the case and i am not sure thats how it is designed. Thats how it is installed, i created a docker image
 
https://github.com/EugenMayer/deb-surg-org-tests/blob/master/memcached/build/Dockerfile

```
git clone EugenMayer/deb-surg-org-tests
cd deb-surg-org-tests/memcached
docker-compose build
docker run --rm -i -t eugenmayer/deb-surg-org-tests:memcached bash
```
then you end up having

```
ls -la /etc/php/
drwxr-xr-x  7 root root 4096 Jul  3 11:46 .
drwxr-xr-x 56 root root 4096 Jul  3 11:51 ..
drwxr-xr-x  4 root root 4096 Jul  3 11:46 5.5
drwxr-xr-x  3 root root 4096 Jul  3 11:46 5.6
drwxr-xr-x  6 root root 4096 Jul  3 11:46 7.0
```

Is that by design? So creating also php5.6 entries, even though its not installed?

Those php5.5-memached and php7.0-memcached packages seem to be virtual and reference php-memached. Both cannot be part of jessies repos, so it must be part of yours?

**Comment by oerdnj** [comment]
Yes, it is intentional. It installs `/etc/php/X.Y/mods-available` for every supported PHP X.Y release, but doesn't enable the module unless the specific PHP version and SAPI is also installed.

**Comment by EugenMayer** [comment]
Thank you. What about php5.5-memached and php7.0-memcached  - you mentioned above, you do not offer such packages and they are not listed, but seem to be virtual? Would you dare to clarify?

**Comment by oerdnj** [comment]
Many people tried to install the extension with version listed in the package name hence the Provides, as they will get the right version. And vice versa, look at the php7.0-common Provides line...
