### ISSUE TITLE
php5.5-igbinary creates /etc/php/5.6/mods-available/igbinary.ini

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#401]
php5.5-igbinary creates /etc/php/5.6/mods-available/igbinary.ini

again dualstack php7.0 / php5.5 installation but this should not matter, just install php5.5-igbinary and it should create /etc/php/5.6/mods-available/igbinary.ini

**Comment by oerdnj** [comment]
Don't create duplicate issues. Dup of #400
