### ISSUE TITLE
Docs: Explain people how to build pecl packages when using a dualstack setup

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#403]
When having e.g. php7.0 / php5.5 and someone wants to install pecl packages for either of this, it must be prepared.

Eg. for php5.5:

```
update-alternatives --set php /usr/bin/php5.5
update-alternatives --set php-config /usr/bin/php-config5.5
update-alternatives --set phpize /usr/bin/phpize5.5
```

so its more then switching php - it works but will lead to arbitrary compile issues ( beside it uses the wrong libs .. ) which are not obvious that its just the wrong phpize / config.

This just needs some docs so people know, how to do that - leaving this ticket for google until we have it someone else.

**Comment by oerdnj** [comment]
Plain `pecl install` wont' work unless you change defaults using `update-alternatives`, that's correct. But you can only download the extension, run `phpize5.5` and run `./configure --with-php-config=php-config5.5`, that's how the packages build the modules. 

There's a wiki: https://github.com/oerdnj/deb.sury.org/wiki you are free to document various options.

**Comment by EugenMayer** [comment]
@oerdnj https://github.com/oerdnj/deb.sury.org/wiki/PECL-considerations be bold, cut it, squeeze it :)
