### ISSUE TITLE
Extension request: yaml

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#406]
I am yet quiet not sure why this extension is rarely or ever have been offered as a Debian package, but its not only very useful, its commonly used.

I see that, e.g. symfony has its own yaml library written in PHP, others require the C extension.

Proposal: 
offer a phpX.Y-yaml extension based on https://pecl.php.net/package/yaml

I am using this extension in production for over 3 years now, never head any issues. Also the current yaml-beta build is pretty stable.

Any comments on this?

**Comment by oerdnj** [comment]
I am on vacation next week spending time with my family, so I am not sure I'll find a time to package it. But copying debian/ from some other simple extension (f.e. `apt-get source php-apcu`) and adjusting, renaming files:

```
rename s/apcu/yaml/ *apcu*
sed -i s/apcu/yaml/g
```

And adjusting `d/changelog`

and running `dpkg-buildpackage` might just work. Needs some Debian packaging skills though.

**Comment by EugenMayer** [comment]
I am not sure i find time, i think i packaged it in the past, not using your template, but customly.

Still, i am not sure how this extension should be handled due to its version-specific builds ( see the other yaml ticket )

**Comment by oerdnj** [comment]
apcu is an example, it's driven by package-ver.xml. Every version looks at most specific to least specific `package.xml`, so you would rename `package.xml` to `package-5.xml` for `yaml` and to `package-7.0.xml` for `yaml-beta`. (Or just the last step and leave PHP 5.x to fallback to `package.xml`.)

**Comment by oerdnj** [comment]
Just uploaded as `php-yaml_2.0.0~rc8+1.3.0~b1-1+deb.sury.org~*+1`

**Comment by EugenMayer** [comment]
thank you very much, seriously!

**Comment by EugenMayer** [comment]
does not really work for me:

```
(root:php7)➜  20151012  apt-cache search yaml | grep php
php-symfony-yaml - convert YAML to PHP arrays and the other way around
(root:php7)➜  20151012  cat /etc/apt/sources.list.d/packages.sury.org.list
deb https://packages.sury.org/php/ jessie main
```

Any reasons i miss it?

**Comment by EugenMayer** [comment]
At least for me, i had to reference yaml-2.0.0 explicitly for php7 builds, otherwise the build failed when using yaml-beta. This might be due to the release of 1.3.0 which is marked to be compatible with 5.3+ but will not compile under 7.0 `php_smart_str.h`

This might also have broken your builds?

**Comment by oerdnj** [comment]
This was not being built for Debian Jessie.
You can watch the builds here: https://howl.labs.nic.cz/jenkins/view/PHP-source/job/php_php-yaml-binaries/

**Comment by EugenMayer** [comment]
@oerdnj oh - so only for stretch. Are you building it for jessie right now?

**Comment by oerdnj** [comment]
Both. It was built on for Ubuntus and now it's built for Debian jessie and stretch now.

**Comment by EugenMayer** [comment]
great, thank you!
