### ISSUE TITLE
How to handle installing different extension version for each PHP version

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#407]
Due to yaml-beta only being available for php7 and yaml being available for < php7 i have to install 2 different pecl extensions.

I am aware of switching php-config / phpize and php the way discribed here https://github.com/oerdnj/deb.sury.org/wiki/PECL-considerations 

Issue:
when installing yaml-beta for php7, it ends up only being in the extension folder of php7, which is perfectly fine.
```
pecl install yaml-beta
....
Build process completed successfully
Installing '/usr/lib/php/20151012/yaml.so'
```

When i then, switch alternatives to php5.5 and try to install yaml

```
php -version
PHP 5.5.37-1+0~20160628130434.3+jessie~1.gbpde89a7 (cli)

phpize --version
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212

php-config --version
5.5.37-1+0~20160628130434.3+jessie~1.gbpde89a7

pecl install yaml
pecl/yaml is already installed and is the same as the released version 2.0.0RC8
install failed
```

the installation fails, since pecl still thinks that yaml-beta ( 2.x ) is installed for the current php version.

Is there something i miss / forgot about?

**Comment by EugenMayer** [comment]
my work arround for now is, using https://github.com/oerdnj/deb.sury.org/wiki/PECL-considerations#alternatives so installing the php5.5 yaml 1.2.0 pecl extension using the manual way.

Is this, generally what your propose, maybe https://github.com/oerdnj/deb.sury.org/wiki/PECL-considerations needs adjustments there. Telling that and flipping the order, makein pecl install X a second-choice alternative?

**Comment by oerdnj** [comment]
Don't use PECL to install the extension, but just download the tarball, unpack, chdir into unpacked dir and run: `phpize5.5 && ./configure --with-php-config=php-config5.5 && make && sudo make install`

I will check the wiki later...

**Comment by oerdnj** [comment]
The PECL wiki looks fine. Thanks, I have added the link to it on the main wiki page.

**Comment by seyfer** [comment]
Seems like this issue is an answer to this SO question...
[How to install php extension using pecl for specific php version, when several php versions installed in system?](https://stackoverflow.com/questions/40419718/how-to-install-php-extension-using-pecl-for-specific-php-version-when-several-p)
