### ISSUE TITLE
Packaging request: libsodium extension

### ISSUE THREAD

**Issue by frederikbosch** [oerdnj/deb.sury.org#409]
Tried multiple things, but how do I install libsodium for PHP 7.0? I see the package contains libsodium by default but I dont see a php-libsodium package to install it. Only the lib itself. How can I activate it?

**Comment by oerdnj** [comment]
The libsodium php extension is not packaged (yet).

**Comment by frederikbosch** [comment]
@oerdnj How would I install libsodium then? I tried to copy the .so.1.8 to the extension dir and added a libsodium.ini file but without success. I think I cannot see how are extensions have been packaged. Otherwise I could help by packaging libsodium.

**Comment by oerdnj** [comment]
@frederikbosch Just to make sure, we are talking about the same thing. You want this: https://pecl.php.net/package/libsodium to be packaged?

**Comment by oerdnj** [comment]
https://twitter.com/debsuryorg/status/752517236791869440
And it's building now...
