### ISSUE TITLE
Could you please release a ZTS-enabled php5-5.6 package?

### ISSUE THREAD

**Issue by sexyzane** [oerdnj/deb.sury.org#41]
I installed your great php5-5.6 package on Ubuntu. It works well, thanks!, but it is a non-thread safe build, and this makes it incompatible with http://pthreads.org/

![NTS](http://i.imgur.com/xycUTaV.png)

Any plan to alse release a thread safe package?

Thansk again for your hard work!

**Comment by oerdnj** [comment]
Unfortunately not. If you want to use threaded version of PHP, you are on your own. While it might work just fine in a specific environment, it's not thread-safe in all possible scenarios (including loading external modules) and thus it's not wise to provide "thread-safe" packages for general use.

**Comment by sexyzane** [comment]
I see. Thanks anyway for your explanation :-)

**Comment by oerdnj** [comment]
And mark as dup of #7

**Comment by oerdnj** [comment]
Folks, if you want to shoot yourself in foot, the new packaging infrastructure I built for PHP 7.0 allows to build variants quite easily, so here's experimental, totally unsupported PPA with PHP 7.0 ZTS: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts

No external modules, no batteries, no support (patches accepted and welcomed).

**Comment by ZaneCEO** [comment]
Great, thanks!
