### ISSUE TITLE
sessioncleaner cron seems to be missing

### ISSUE THREAD

**Issue by bertvandepoel** [oerdnj/deb.sury.org#412]
We fully switched from your old repo to your new one. Currently temporarily keeping one server on 5.5, but will soon migrate to 5.6. 

We were getting persistant cron errors from the session cleaner after the upgrade:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/mysql.so' - /usr/lib/php/20121212/mysql.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/mysqli.so' - /usr/lib/php/20121212/mysqli.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/pdo_mysql.so' - /usr/lib/php/20121212/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/xsl.so' - /usr/lib/php/20121212/xsl.so: undefined symbol: dom_node_class_entry in Unknown on line 0

After looking into the configuration and disabling/reenabling + priority checking all mysql modules, we noticed that the cron file was supplied by php5-common, which was uninstalled. So I removed the cron-file and reinstalled php-common and php5.5-common (as well as some other packages just to be sure). None of these seem to generate the cron file itself (but php-common does install the sessioncleaner script correctly).

Which package is supposed to supply the cron file for php5.5? Or is it perhaps missing?

**Comment by oerdnj** [comment]
`sessionclean` script and the cron job is (should be) provided by `php-common` package.

**Comment by bertvandepoel** [comment]
I see, it is indeed part of the php-common package. However a reinstall does not seem to put it in place. Is this expected behaviour? I'm very confused why this doesn't just unpack the cron file.

bert@bc3:~$ dpkg -L php-common
/.
/etc
/etc/cron.d
/etc/cron.d/php
/var
/var/lib
/var/lib/php
/var/lib/php/modules
/var/lib/php/sessions
/usr
/usr/sbin
/usr/sbin/phpquery
/usr/sbin/phpenmod
/usr/lib
/usr/lib/php
/usr/lib/php/sessionclean
/usr/lib/php/php-maintscript-helper
/usr/lib/php/php-helper
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/php-common
/usr/share/doc
/usr/share/doc/php-common
/usr/share/doc/php-common/changelog.gz
/usr/share/doc/php-common/copyright
/usr/sbin/phpdismod
bert@bc3:~$ aptitude reinstall php-common
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
bert@bc3:~$ sudo aptitude reinstall php-common
[sudo] password for bert: 
The following packages will be REINSTALLED:
  php-common 
0 packages upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/12.9 kB of archives. After unpacking 0 B will be used.
perl: warning: Setting locale failed.    
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:en",
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 259431 files and directories currently installed.)
Preparing to unpack .../php-common_1%3a42+deb.sury.org~trusty+2_all.deb ...
Unpacking php-common (1:42+deb.sury.org~trusty+2) over (1:42+deb.sury.org~trusty+2) ...
Setting up php-common (1:42+deb.sury.org~trusty+2) ...
                                         
bert@bc3:~$ cd /etc/cron.d
bert@bc3:/etc/cron.d$ ls
mdadm  munin-node  ttrss

**Comment by oerdnj** [comment]
conffiles are not replaced (when changed or deleted) by default. There's some dpkg option to reinstall the conffiles. (`--force-confmiss`)

**Comment by bertvandepoel** [comment]
Ah, that was it indeed. Weird how I never came across that.

However, sessioncleaner is again at it throwing:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/mysql.so' - /usr/lib/php/20121212/mysql.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/mysqli.so' - /usr/lib/php/20121212/mysqli.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/pdo_mysql.so' - /usr/lib/php/20121212/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20121212/xsl.so' - /usr/lib/php/20121212/xsl.so: undefined symbol: dom_node_class_entry in Unknown on line 0

The weird thing is that we can't replicate it. Both php5.5-fpm and php cli don't throw any warnings on startup and extensions/libraries are loaded and working. We have not moved away from the default config either. So I'm very confused what is causing these warnings.

**Comment by oerdnj** [comment]
How does output of `find /etc/php` look? Especially any `conf.d` for any less used SAPI.

**Comment by bertvandepoel** [comment]
root@bc3:/etc/php# find
.
./5.5.bak
./5.5.bak/fpm
./5.5.bak/fpm/conf.d
./5.5.bak/fpm/conf.d/20-tokenizer.ini
./5.5.bak/fpm/conf.d/20-sysvshm.ini
./5.5.bak/fpm/conf.d/20-phar.ini
./5.5.bak/fpm/conf.d/20-iconv.ini
./5.5.bak/fpm/conf.d/10-opcache.ini
./5.5.bak/fpm/conf.d/20-exif.ini
./5.5.bak/fpm/conf.d/20-json.ini
./5.5.bak/fpm/conf.d/20-readline.ini
./5.5.bak/fpm/conf.d/20-ftp.ini
./5.5.bak/fpm/conf.d/20-shmop.ini
./5.5.bak/fpm/conf.d/20-calendar.ini
./5.5.bak/fpm/conf.d/10-pdo.ini
./5.5.bak/fpm/conf.d/20-sysvmsg.ini
./5.5.bak/fpm/conf.d/20-sockets.ini
./5.5.bak/fpm/conf.d/20-fileinfo.ini
./5.5.bak/fpm/conf.d/20-sysvsem.ini
./5.5.bak/fpm/conf.d/20-ctype.ini
./5.5.bak/fpm/conf.d/20-gettext.ini
./5.5.bak/fpm/conf.d/20-posix.ini
./5.5.bak/fpm/php-fpm.conf
./5.5.bak/fpm/pool.d
./5.5.bak/fpm/pool.d/www.conf
./5.5.bak/fpm/php.ini
./5.5.bak/cli
./5.5.bak/cli/conf.d
./5.5.bak/cli/conf.d/20-tokenizer.ini
./5.5.bak/cli/conf.d/20-sysvshm.ini
./5.5.bak/cli/conf.d/20-phar.ini
./5.5.bak/cli/conf.d/20-iconv.ini
./5.5.bak/cli/conf.d/10-opcache.ini
./5.5.bak/cli/conf.d/20-exif.ini
./5.5.bak/cli/conf.d/20-json.ini
./5.5.bak/cli/conf.d/20-readline.ini
./5.5.bak/cli/conf.d/20-ftp.ini
./5.5.bak/cli/conf.d/20-shmop.ini
./5.5.bak/cli/conf.d/20-calendar.ini
./5.5.bak/cli/conf.d/10-pdo.ini
./5.5.bak/cli/conf.d/20-sysvmsg.ini
./5.5.bak/cli/conf.d/20-sockets.ini
./5.5.bak/cli/conf.d/20-fileinfo.ini
./5.5.bak/cli/conf.d/20-sysvsem.ini
./5.5.bak/cli/conf.d/20-ctype.ini
./5.5.bak/cli/conf.d/20-gettext.ini
./5.5.bak/cli/conf.d/20-posix.ini
./5.5.bak/cli/php.ini
./5.5.bak/mods-available
./5.5.bak/mods-available/tokenizer.ini
./5.5.bak/mods-available/sysvmsg.ini
./5.5.bak/mods-available/iconv.ini
./5.5.bak/mods-available/json.ini
./5.5.bak/mods-available/pdo.ini
./5.5.bak/mods-available/ctype.ini
./5.5.bak/mods-available/phar.ini
./5.5.bak/mods-available/opcache.ini
./5.5.bak/mods-available/gettext.ini
./5.5.bak/mods-available/sysvshm.ini
./5.5.bak/mods-available/sysvsem.ini
./5.5.bak/mods-available/calendar.ini
./5.5.bak/mods-available/exif.ini
./5.5.bak/mods-available/readline.ini
./5.5.bak/mods-available/fileinfo.ini
./5.5.bak/mods-available/posix.ini
./5.5.bak/mods-available/sockets.ini
./5.5.bak/mods-available/ftp.ini
./5.5.bak/mods-available/shmop.ini
./5.5
./5.5/fpm
./5.5/fpm/conf.d
./5.5/fpm/conf.d/20-xmlreader.ini
./5.5/fpm/conf.d/20-tokenizer.ini
./5.5/fpm/conf.d/20-sysvshm.ini
./5.5/fpm/conf.d/20-memcache.ini
./5.5/fpm/conf.d/20-pdo_mysql.ini
./5.5/fpm/conf.d/20-htscanner.ini
./5.5/fpm/conf.d/20-intl.ini
./5.5/fpm/conf.d/20-dom.ini
./5.5/fpm/conf.d/20-pspell.ini
./5.5/fpm/conf.d/20-mcrypt.ini
./5.5/fpm/conf.d/20-xsl.ini
./5.5/fpm/conf.d/20-curl.ini
./5.5/fpm/conf.d/20-simplexml.ini
./5.5/fpm/conf.d/20-phar.ini
./5.5/fpm/conf.d/20-iconv.ini
./5.5/fpm/conf.d/20-ldap.ini
./5.5/fpm/conf.d/20-pgsql.ini
./5.5/fpm/conf.d/20-xmlrpc.ini
./5.5/fpm/conf.d/20-svn.ini
./5.5/fpm/conf.d/20-apcu.ini
./5.5/fpm/conf.d/05-opcache.ini
./5.5/fpm/conf.d/20-exif.ini
./5.5/fpm/conf.d/20-imap.ini
./5.5/fpm/conf.d/20-gd.ini
./5.5/fpm/conf.d/15-xml.ini
./5.5/fpm/conf.d/20-bz2.ini
./5.5/fpm/conf.d/20-tidy.ini
./5.5/fpm/conf.d/20-geoip.ini
./5.5/fpm/conf.d/20-json.ini
./5.5/fpm/conf.d/20-mysql.ini
./5.5/fpm/conf.d/20-mbstring.ini
./5.5/fpm/conf.d/20-readline.ini
./5.5/fpm/conf.d/20-soap.ini
./5.5/fpm/conf.d/20-ftp.ini
./5.5/fpm/conf.d/20-shmop.ini
./5.5/fpm/conf.d/20-calendar.ini
./5.5/fpm/conf.d/20-pdo_sqlite.ini
./5.5/fpm/conf.d/20-ssh2.ini
./5.5/fpm/conf.d/10-pdo.ini
./5.5/fpm/conf.d/20-sysvmsg.ini
./5.5/fpm/conf.d/20-wddx.ini
./5.5/fpm/conf.d/20-pdo_pgsql.ini
./5.5/fpm/conf.d/20-imagick.ini
./5.5/fpm/conf.d/20-uuid.ini
./5.5/fpm/conf.d/20-sockets.ini
./5.5/fpm/conf.d/20-mysqli.ini
./5.5/fpm/conf.d/10-mysqlnd.ini
./5.5/fpm/conf.d/20-xmlwriter.ini
./5.5/fpm/conf.d/20-fileinfo.ini
./5.5/fpm/conf.d/20-sqlite3.ini
./5.5/fpm/conf.d/25-mailparse.ini
./5.5/fpm/conf.d/20-sysvsem.ini
./5.5/fpm/conf.d/20-ctype.ini
./5.5/fpm/conf.d/20-gettext.ini
./5.5/fpm/conf.d/20-posix.ini
./5.5/fpm/conf.d/20-zip.ini
./5.5/fpm/php.ini.ucf-dist
./5.5/fpm/php-fpm.conf
./5.5/fpm/php.ini.save
./5.5/fpm/pool.d
./5.5/fpm/pool.d/xmpp.conf
./5.5/fpm/pool.d/ulyssis.conf
./5.5/fpm/pool.d/campuspay.conf
./5.5/fpm/pool.d/www.conf
./5.5/fpm/pool.d/ucc.conf
./5.5/fpm/pool.d/pay.conf
./5.5/fpm/pool.d/phpmyadmin.conf
./5.5/fpm/pool.d/intern.conf
./5.5/fpm/pool.d/stumar.conf
./5.5/fpm/pool.d/www.conf.test
./5.5/fpm/pool.d/24u.conf
./5.5/fpm/pool.d/ttrss.conf
./5.5/fpm/pool.d/loko.conf
./5.5/fpm/pool.d/webmail.conf
./5.5/fpm/php.ini
./5.5/cli
./5.5/cli/conf.d
./5.5/cli/conf.d/20-xmlreader.ini
./5.5/cli/conf.d/20-tokenizer.ini
./5.5/cli/conf.d/20-sysvshm.ini
./5.5/cli/conf.d/20-memcache.ini
./5.5/cli/conf.d/20-pdo_mysql.ini
./5.5/cli/conf.d/20-htscanner.ini
./5.5/cli/conf.d/20-intl.ini
./5.5/cli/conf.d/20-dom.ini
./5.5/cli/conf.d/20-pspell.ini
./5.5/cli/conf.d/20-mcrypt.ini
./5.5/cli/conf.d/20-xsl.ini
./5.5/cli/conf.d/20-curl.ini
./5.5/cli/conf.d/20-simplexml.ini
./5.5/cli/conf.d/20-phar.ini
./5.5/cli/conf.d/20-iconv.ini
./5.5/cli/conf.d/20-ldap.ini
./5.5/cli/conf.d/20-pgsql.ini
./5.5/cli/conf.d/20-xmlrpc.ini
./5.5/cli/conf.d/20-svn.ini
./5.5/cli/conf.d/20-apcu.ini
./5.5/cli/conf.d/05-opcache.ini
./5.5/cli/conf.d/20-exif.ini
./5.5/cli/conf.d/20-imap.ini
./5.5/cli/conf.d/20-gd.ini
./5.5/cli/conf.d/15-xml.ini
./5.5/cli/conf.d/20-bz2.ini
./5.5/cli/conf.d/20-tidy.ini
./5.5/cli/conf.d/20-geoip.ini
./5.5/cli/conf.d/20-json.ini
./5.5/cli/conf.d/20-mysql.ini
./5.5/cli/conf.d/20-mbstring.ini
./5.5/cli/conf.d/20-readline.ini
./5.5/cli/conf.d/20-soap.ini
./5.5/cli/conf.d/20-ftp.ini
./5.5/cli/conf.d/20-shmop.ini
./5.5/cli/conf.d/20-calendar.ini
./5.5/cli/conf.d/20-pdo_sqlite.ini
./5.5/cli/conf.d/20-ssh2.ini
./5.5/cli/conf.d/10-pdo.ini
./5.5/cli/conf.d/20-sysvmsg.ini
./5.5/cli/conf.d/20-wddx.ini
./5.5/cli/conf.d/20-pdo_pgsql.ini
./5.5/cli/conf.d/20-imagick.ini
./5.5/cli/conf.d/20-uuid.ini
./5.5/cli/conf.d/20-sockets.ini
./5.5/cli/conf.d/20-mysqli.ini
./5.5/cli/conf.d/10-mysqlnd.ini
./5.5/cli/conf.d/20-xmlwriter.ini
./5.5/cli/conf.d/20-fileinfo.ini
./5.5/cli/conf.d/20-sqlite3.ini
./5.5/cli/conf.d/25-mailparse.ini
./5.5/cli/conf.d/20-sysvsem.ini
./5.5/cli/conf.d/20-ctype.ini
./5.5/cli/conf.d/20-gettext.ini
./5.5/cli/conf.d/20-posix.ini
./5.5/cli/conf.d/20-zip.ini
./5.5/cli/php.ini.ucf-old
./5.5/cli/php.ini
./5.5/mods-available
./5.5/mods-available/intl.ini.ucf-old
./5.5/mods-available/tokenizer.ini
./5.5/mods-available/imap.ini
./5.5/mods-available/sysvmsg.ini
./5.5/mods-available/pdo_mysql.ini
./5.5/mods-available/iconv.ini
./5.5/mods-available/uuid.ini
./5.5/mods-available/json.ini
./5.5/mods-available/pdo.ini
./5.5/mods-available/htscanner.ini
./5.5/mods-available/ctype.ini
./5.5/mods-available/xmlwriter.ini
./5.5/mods-available/phar.ini
./5.5/mods-available/mysqlnd.ini
./5.5/mods-available/curl.ini.ucf-old
./5.5/mods-available/dom.ini
./5.5/mods-available/pdo_pgsql.ini.ucf-old
./5.5/mods-available/ssh2.ini
./5.5/mods-available/svn.ini
./5.5/mods-available/xml.ini
./5.5/mods-available/simplexml.ini
./5.5/mods-available/pspell.ini
./5.5/mods-available/soap.ini
./5.5/mods-available/gd.ini.ucf-old
./5.5/mods-available/opcache.ini
./5.5/mods-available/pgsql.ini.ucf-old
./5.5/mods-available/zip.ini
./5.5/mods-available/mysqli.ini.ucf-old
./5.5/mods-available/xsl.ini.ucf-old
./5.5/mods-available/mysql.ini
./5.5/mods-available/geoip.ini
./5.5/mods-available/curl.ini
./5.5/mods-available/ldap.ini
./5.5/mods-available/intl.ini
./5.5/mods-available/bz2.ini
./5.5/mods-available/pdo_pgsql.ini
./5.5/mods-available/ldap.ini.ucf-old
./5.5/mods-available/mailparse.ini
./5.5/mods-available/imap.ini.ucf-old
./5.5/mods-available/gettext.ini
./5.5/mods-available/imagick.ini
./5.5/mods-available/sysvshm.ini
./5.5/mods-available/sqlite3.ini
./5.5/mods-available/wddx.ini
./5.5/mods-available/sysvsem.ini
./5.5/mods-available/mysql.ini.ucf-old
./5.5/mods-available/tidy.ini
./5.5/mods-available/calendar.ini
./5.5/mods-available/apcu.ini
./5.5/mods-available/mcrypt.ini
./5.5/mods-available/memcache.ini
./5.5/mods-available/mysqli.ini
./5.5/mods-available/memcache.ini.dpkg-old
./5.5/mods-available/xmlrpc.ini
./5.5/mods-available/xsl.ini
./5.5/mods-available/xmlrpc.ini.ucf-old
./5.5/mods-available/exif.ini
./5.5/mods-available/readline.ini
./5.5/mods-available/pgsql.ini
./5.5/mods-available/pdo_mysql.ini.ucf-old
./5.5/mods-available/pdo_sqlite.ini
./5.5/mods-available/gd.ini
./5.5/mods-available/fileinfo.ini
./5.5/mods-available/pdo_sqlite.ini.ucf-old
./5.5/mods-available/posix.ini
./5.5/mods-available/redland.ini
./5.5/mods-available/mcrypt.ini.ucf-old
./5.5/mods-available/sqlite3.ini.ucf-old
./5.5/mods-available/mbstring.ini
./5.5/mods-available/sockets.ini
./5.5/mods-available/ftp.ini
./5.5/mods-available/shmop.ini
./5.5/mods-available/xmlreader.ini
./5.5/cgi
./5.5/cgi/conf.d
./5.5/cgi/conf.d/20-memcache.ini
./5.5/cgi/conf.d/20-pdo_mysql.ini
./5.5/cgi/conf.d/20-htscanner.ini
./5.5/cgi/conf.d/20-intl.ini
./5.5/cgi/conf.d/20-pspell.ini
./5.5/cgi/conf.d/20-mcrypt.ini
./5.5/cgi/conf.d/20-xsl.ini
./5.5/cgi/conf.d/20-curl.ini
./5.5/cgi/conf.d/20-ldap.ini
./5.5/cgi/conf.d/20-pgsql.ini
./5.5/cgi/conf.d/20-xmlrpc.ini
./5.5/cgi/conf.d/20-svn.ini
./5.5/cgi/conf.d/20-apcu.ini
./5.5/cgi/conf.d/05-opcache.ini
./5.5/cgi/conf.d/20-imap.ini
./5.5/cgi/conf.d/20-gd.ini
./5.5/cgi/conf.d/20-tidy.ini
./5.5/cgi/conf.d/20-geoip.ini
./5.5/cgi/conf.d/20-json.ini
./5.5/cgi/conf.d/20-mysql.ini
./5.5/cgi/conf.d/20-readline.ini
./5.5/cgi/conf.d/20-pdo_sqlite.ini
./5.5/cgi/conf.d/10-pdo.ini
./5.5/cgi/conf.d/20-pdo_pgsql.ini
./5.5/cgi/conf.d/20-imagick.ini
./5.5/cgi/conf.d/20-mysqli.ini
./5.5/cgi/conf.d/20-sqlite3.ini
./5.5/cgi/php.ini
./5.6
./5.6/mods-available
./5.6/mods-available/uuid.ini
./5.6/mods-available/ssh2.ini
./5.6/mods-available/geoip.ini
./5.6/mods-available/mailparse.ini
./5.6/mods-available/imagick.ini
./5.6/mods-available/apcu.ini
./5.6/mods-available/memcache.ini
./7.0
./7.0/cli
./7.0/cli/conf.d
./7.0/cli/conf.d/20-memcache.ini
./7.0/cli/conf.d/20-apcu.ini
./7.0/cli/conf.d/20-geoip.ini
./7.0/cli/conf.d/20-ssh2.ini
./7.0/cli/conf.d/20-imagick.ini
./7.0/cli/conf.d/20-uuid.ini
./7.0/cli/conf.d/25-mailparse.ini
./7.0/mods-available
./7.0/mods-available/uuid.ini
./7.0/mods-available/ssh2.ini
./7.0/mods-available/geoip.ini
./7.0/mods-available/mailparse.ini
./7.0/mods-available/imagick.ini
./7.0/mods-available/apcu.ini
./7.0/mods-available/memcache.ini
./7.0/embed
./7.0/embed/conf.d
./7.0/embed/conf.d/20-memcache.ini
./7.0/embed/conf.d/20-apcu.ini
./7.0/embed/conf.d/20-geoip.ini
./7.0/embed/conf.d/20-ssh2.ini
./7.0/embed/conf.d/20-imagick.ini
./7.0/embed/conf.d/20-uuid.ini
./7.0/embed/conf.d/25-mailparse.ini

I've read here that the 5.6 and 7.0 configs get installed by generic extensions that are the same package for all version. We currently have only an active version of 5.5 installed. As soon as we're sure the config is fully done we'll attempt a move to 5.6. The 5.5.bak is because we wanted to do some diffs between our old /etc/php5 and the new /etc/php/5.5, they turned out to basically be the same.

**Comment by oerdnj** [comment]
`php5.5-cgi` extension setup is broken. Either disable and enable all extensions for CGI SAPI or just sync the dir with other SAPI (CLI).

**Comment by bertvandepoel** [comment]
My bad, I had migrated the CGI config files while CGI isn't even installed. Thank you very much for your help and keep up the good work with the repo!
