### ISSUE TITLE
[PPA Request] Mainline NGINX PPA

### ISSUE THREAD

**Issue by welnanick** [oerdnj/deb.sury.org#413]
I'd like to switch my Ubuntu 14.04 LTS Server to use the mainline build of Nginx (I know this is generally cautioned against, since the point of LTS is it's stable), while also being compiled against the latest OpenSSL so I can have ALPN support. I see you have an up to date build of the stable version of nginx here: ppa:ondrej/nginx, which I will be using in the meantime since it also has the lastest OpenSSL in the same ppa, but it would be nice to have the option. You could possibly rename this ppa to something like ppa:ondrej/nginx-stable and create another that is exactly the same but with the mainline version called ppa:ondrej/nginx-mainline, or something like that. Anyway, thank you for creating these ppas!

**Comment by oerdnj** [comment]
Use `ppa:ondrej/nginx-mainline` (after it builds the packages).

**Comment by welnanick** [comment]
Thank You!
