### ISSUE TITLE
igbinary segfaults

### ISSUE THREAD

**Issue by uduncanu** [oerdnj/deb.sury.org#414]
I'm seeing an issue where php7.0-fpm occasionally segfaults when unserializing igbinary data from memcached.  From what I can tell, pull request 8 on the igbinary7 project (https://github.com/igbinary/igbinary7/pull/8) fixes the issue, but movement on getting it merged in to the main project appears to have stalled.  Can that be pulled into the built packages?

**Comment by oerdnj** [comment]
`php-igbinary_1.2.1-10-ge0e66b9+1.2.1+-3+deb.sury.org~*+1` has the referenced patch, thanks for pointing it out.

This might also solve #405 .
