### ISSUE TITLE
No bundled SoapClent?

### ISSUE THREAD

**Issue by TiGR** [oerdnj/deb.sury.org#415]
When I try to use `\SoapClient` php says that 

    Attempted to load class "SoapClient" from the global namespace.
    Did you forget a "use" statement?

So, according to documentation, in order to get SoapClient you have to compile php with `--enable-soap`. Could you, please, enable this option, as it is on by default in php bundled with ubuntu (at least it is so in 14.04).

**Comment by oerdnj** [comment]
Did you even tried?

```
$ apt-cache search php7.0 soap 
php7.0-soap - SOAP module for PHP
php7.0-soap-dbgsym - Debug symbols for php7.0-soap
```
