### ISSUE TITLE
Any way to downgrade?

### ISSUE THREAD

**Issue by koehn** [oerdnj/deb.sury.org#419]
I think the current php7 broke something in my system, but I'm unable to debug it (at least I can't figure out how to get php7.0-fpm to actually log anything). Can I downgrade to the previous version somehow? I can't figure that out either. Help!

**Comment by koehn** [comment]
Details of my woes are [here])https://help.nextcloud.com/t/apache-rewrite-to-remove-index-php/658/14)

**Comment by oerdnj** [comment]
You might have a luck by finding a build that hasn't been purged yet here: https://launchpad.net/~ondrej/+archive/ubuntu/php/+builds?build_text=php7.0&build_state=built
Or you can downgrade to Ubuntu Xenial stock packages using `ppa-purge` (`apt-get install ppa-purge && ppa-purge ppa:ondrej/php`)

**Comment by koehn** [comment]
Thanks. It appears after many hours of debugging that `RewriteRule`s are not being called prior to calling `ProxyPassMatch`. I don't understand how/why that would change.

**Comment by koehn** [comment]
Turns out this solved my problem: https://serverfault.com/questions/450628/apache-2-4-php-fpm-proxypassmatch
