### ISSUE TITLE
Problem with imagettfbbox()

### ISSUE THREAD

**Issue by fredcm** [oerdnj/deb.sury.org#42]
Problem with imagettfbbox()

The function imagettbbox() always returns -1 for X coordinate left corner.

$bbox = imagettfbbox(20, 0, './arial.ttf', 'TestImagettfbbox');

echo $bbox[0]; // always -1 - lower left corner, X position
echo $bbox[6]; // always -1 - upper left corner, X position

![anexo_925293](https://cloud.githubusercontent.com/assets/10728917/5923436/aaceffb0-a63a-11e4-91f6-a819ebe4ba2a.png)

**Comment by oerdnj** [comment]
If you think there's a problem in upstream function, you need to take it to the upstream bug system, e.g. bugs.php.net. It's not a bug related to packaging.
