### ISSUE TITLE
mongodb driver with ppa:ondrej/php php5.6

### ISSUE THREAD

**Issue by shabadoo75** [oerdnj/deb.sury.org#422]
I was not able to find the mongodb driver when using the ondrej/php PPA with php5.6

php5-mongo is compiled against php5.5 and the module wont work with php5.6.

I've tried to install mongo and mongodb from pecl but this requires the php5.6-dev package which does not exist. ( using php5-dev did not work )

Is there a way to install the mongo driver with php5.6?

**Comment by oerdnj** [comment]
`apt-cache search php mongo`

**Comment by shabadoo75** [comment]
thanks man!
