### ISSUE TITLE
opcache.optimization_level 0x7FFFBFFF

### ISSUE THREAD

**Issue by sshilko** [oerdnj/deb.sury.org#426]
**7.0.5-3+donate.sury.org~trusty+1 
opcache.optimization_level: 0x7FFFBFFF**

any reason why it is not default 0xFFFFFFFF ? @oerdnj

**Comment by oerdnj** [comment]
Perhaps the documentation is wrong? I'm not doing anything to the defaults. Any reason why you are using a version with known security vulnerabilities?

**Comment by sshilko** [comment]
@oerdnj  ok maybe documentation is wrong  then :(
http://php.net/manual/en/opcache.configuration.php#ini.opcache.optimization-level

I'm just about to upgrade
