### ISSUE TITLE
PHP 7.0.9 now requires install of libapache2-mod-php7.0

### ISSUE THREAD

**Issue by EspadaV8** [oerdnj/deb.sury.org#427]
Not sure if this was intended or not but installing PHP 7.0.9 will now pull in `libapache2-mod-php7.0` and `apache2` itself. Previously this wasn't the case.

We have a provisioning script that would install and configure most of our PHP setup and then install `php7.0-fpm` and `nginx` and configure those, since the bump to 7.0.9 our server failed to start correctly because apache2 was installed and bound to port 80 before nginx could get it.

The fix for us was fairly easy (just install `php7.0-fpm` at the same time as the rest of the PHP packages). If this was intentional then hopefully this will help others that have the same issue.

**Comment by oerdnj** [comment]
It does not. Read the PPA migration guide in the wiki here, the last section. The cause is the same.

**Comment by EspadaV8** [comment]
@oerdnj did the `depends` change with 7.0.9 then? Because this didn't happen with PHP <= 7.0.8.

**Comment by oerdnj** [comment]
No, it did not.
```
php7.0 (7.0.6-9) unstable; urgency=medium

  [ Ondřej Surý ]
  * Offer libapache2-mod-phpX.Y as a first alternative in phpX.Y
    dependency (Closes: #822774)
```

But I was mistaken in my first comment. The cause is not the same, `libapache2-mod-php7.0` is just a first package that can satisfy dependency. If you want to install FPM, then install `php7.0-fpm` and not the dummy dependency-only `php7.0` package.

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php70-cli-always-installed

**Comment by EspadaV8** [comment]
Great, thanks 😄 that's exactly what we ended up doing to our install script to fix the issue.
