### ISSUE TITLE
nginx log rotation doesn't work (ppa:ondrej/nginx, ubuntu 14.04)

### ISSUE THREAD

**Issue by kepstin** [oerdnj/deb.sury.org#428]
I found that when running nginx from this ppa, log rotation (via logrotate) is no longer functional. The log gets rotated once, but nginx continues writing to the old log file.

After some debugging, the issue appears to be that nginx-common installs three files:
```
/etc/logrotate.d/nginx
/etc/init.d/nginx
/etc/init/nginx.conf
```

The `logrotate.d/nginx` file attempts to send signal USR1 to nginx by running `invoke-rc.d nginx rotate`. If only the `/etc/init.d/nginx` script was present this would work, since the invoke-rc.d script would end up running `/etc/init.d/nginx rotate`, which sends the signal.

However, because an upstart job file is available, the invoke-rc.d script attempts to run `initctl rotate nginx`, which fails. Nginx never receives the USR1 signal.

Not sure what the best solution is; the logrotate config file might need to be made more general.

**Comment by oerdnj** [comment]
Hi, I have updated the logrotate script to send USR1 signal directly to the nginx, so it would work in general:
```
diff --git a/debian/nginx-common.nginx.logrotate b/debian/nginx-common.nginx.logrotate
index 423c6ad..b97a260 100644
--- a/debian/nginx-common.nginx.logrotate
+++ b/debian/nginx-common.nginx.logrotate
@@ -13,6 +13,7 @@
                fi \
        endscript
        postrotate
-               invoke-rc.d nginx rotate >/dev/null 2>&1
+               PID=$(awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") { print $2; exit; } }' /etc/nginx/nginx.conf)
+               start-stop-daemon --stop --signal USR1 --quiet --pidfile ${PID:-/run/nginx.pid} --name nginx
        endscript
 }
```
