### ISSUE TITLE
php7.0-zip - unmet dependency on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by paulywebster** [oerdnj/deb.sury.org#429]
Hello,

First, thanks @oerdnj  for your work !

Then, I can't install php7.0-zip, i get this message and I don't find any solution : 

`sudo apt-get install php7.0-zip `

`The following packages have unmet dependencies:
 php7.0-zip : Depends: php7.0-common (= 7.0.8-0ubuntu0.16.04.2) but 7.0.8-3+deb.sury.org~wily+1 is to be installed
E: Unable to correct problems, you have held broken packages.`

Thanks in advance

**Comment by oerdnj** [comment]
You have upgraded your base system to Xenial, but the PPA is still kept at wily.
