### ISSUE TITLE
Issue with php-apcu on PHP 5.6.24

### ISSUE THREAD

**Issue by gizemcan** [oerdnj/deb.sury.org#430]
Hello & thanks for maintaining this repo.
I am sorry if I sound like an amateur (well, I am an amateur) but I have a problem:

I am running PHP 5.6.24 and I would like to install php-apcu module.

There are 3 apcu related packages available in your repo:

- php5-apcu **is for PHP 5.5. NOT for 5.6**
- php-apcu **is for PHP 7.XX**
- php-apcu-bc - **is for older stuff**

How can I get php apcu module for php 5.6?

**Comment by oerdnj** [comment]
No, `php-apcu` is for all supported PHP versions:
```
$ apt-cache show php-apcu | grep Provides
Provides: php-user-cache, php5.5-apcu, php5.6-apcu, php7.0-apcu
```

**Comment by gizemcan** [comment]
Hello @oerdnj  Thanks for your answer but if I install php-apcu by typing:
`apt-get install php-apcu`

it installs php7 and all kinds of php7 related things.

how am I going to have php-apcu along with php 5.6 then?

**Comment by oerdnj** [comment]
Use `apt-get install --no-install-recommends php-apcu`

**Comment by gizemcan** [comment]
omg, you're so awesome!!!!!
Thank you very much
