### ISSUE TITLE
precise: php-geoip package

### ISSUE THREAD

**Issue by oskarpearson** [oerdnj/deb.sury.org#431]
Hi

Thanks for all the work you do here!

I was wondering: would you be able to make the php-geoip package available for precise?

Backgound:

I'm switching across from your php5 ppa to your new repo.

On https://launchpad.net/%7Eondrej/+archive/ubuntu/php5 you have the 'php-geoip' package listed (1.1.0-2+deb.sury.org~precise+1), but it seems to be missing on https://launchpad.net/%7Eondrej/+archive/ubuntu/php/+index?batch=75&memo=75&start=75 (it's available only for trusty/wily/xenial)

**Comment by oerdnj** [comment]
Should be there.

**Comment by oerdnj** [comment]
I mean I uploaded the build in the morning and no failed build report came back... ;)
