### ISSUE TITLE
[courier] New version 0.76.2

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#435]
Download: http://www.courier-mta.org/download.html

Changes:
- courier: allow consecutive % and ! characters in return addresses. Still disallow consecutive periods, as that's still expressly prohibited in RFC 2822.
- couriermlm NOBOZOS=1 option checks only the first word of the first line, not the first word of each line in the message.
- reformime: do not abort due to invalid encoding of the "name" attribute.
- imapd: the server should reject commands from buggy IMAP clients to delete the entire mailbox. This didn't work in some cases, letting IMAP clients nuke the entire mailbox.
- maildrop: implement the FLAGS variable.
- maildrop: fix a bug where the last line in a message wasn't getting searched, fix parsing of a message without a body.

**Comment by tchalvak** [comment]
This doesn't seem to be at all applicable to this repository.

**Comment by oerdnj** [comment]
It is applicable. @markc I'll look into that during this week.

**Comment by oerdnj** [comment]
I am done with the courier. I have properly orphaned it in Debian, as I really can't debug a package I don't ever use.
