### ISSUE TITLE
Broken links on https://launchpad.net/~ondrej/+archive/ubuntu/apache2

### ISSUE THREAD

**Issue by lurch** [oerdnj/deb.sury.org#436]
https://launchpad.net/~ondrej/+archive/ubuntu/apache2 has a couple of links which 404
 * https://deb.sury.org/pages/bugreporting.html
 * https://deb.sury.org/pages/donate.html

Also, just out of curiosity, how come that PPA has updated `automake` and `dh-python` packages? I wouldn't expect either of them to be run-time requirements for Apache2?

**Comment by oerdnj** [comment]
Good catch, thanks. Fixed.
