### ISSUE TITLE
main/debug missing for jessie

### ISSUE THREAD

**Issue by arnaud-lb** [oerdnj/deb.sury.org#437]
I found some reproducible seg fault, so I tried to trace it back. However, I can't find a way to install debug symbols on debian jessie.

It seems that the main/debug component is missing on packages.sury.org/php.

**Comment by oerdnj** [comment]
Unfortunately there's no simple way how to accomplish this using standard tools. PHP packaging has switched to automatic dbgsym packages and the jessie buildchain doesn't support that.

If you can reliably reproduce the bug I would suggest to install Debian testing in some chroot and install the debugging packages there.

**Comment by arnaud-lb** [comment]
I see. Thank you for the php 7 packages :)
