### ISSUE TITLE
Hard to install apcu

### ISSUE THREAD

**Issue by NinoFloris** [oerdnj/deb.sury.org#438]
When trying to install `php-apcu` you get php7.0 with it, also with `php5.6-apcu`
However installing it (including php7.0) and then deinstalling php7.0 shows it is now installed for 5.6 (php -i).

It seems it depends on a bit too much.

**Comment by oerdnj** [comment]
No it does not. Dup of #430

**Comment by NinoFloris** [comment]
Ah, using by using --no-install-recommends it indeed works, how untransparent for mere mortal apt users.
