### ISSUE TITLE
getallheaders function is missing in php5.6-fpm

### ISSUE THREAD

**Issue by nugzarg** [oerdnj/deb.sury.org#440]
If virtualhost is runnig with apache and php5.6-fpm, getallheaders function is not avaialable. Apache error_log says something like this:

 AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined function getallheaders() in /var/www/<SOMESCRIPT.php>

Error not appears in apaches mod_php.
It seems that it is known bug  ([https://github.com/oerdnj/pkg-php/blob/master-5.6/debian/patches/0046-getallheaders-for-php-fpm-62596.patch](url)) and path already exists ([https://github.com/oerdnj/pkg-php/blob/master-5.6/debian/patches/0046-getallheaders-for-php-fpm-62596.patch](url)).

Here some extra info (my apache/php configuration):

PHP packages versions:

dh-php 0.21+deb.sury.org~trusty+1
libapache2-mod-php5.6 5.6.25-1+deb.sury.org~trusty+1
php-common 1:44+deb.sury.org~trusty+1
php-igbinary 1.2.1-10-ge0e66b9+1.2.1+-4+deb.sury.org~trusty+1
php-memcached 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3
php-msgpack 2.0.1+0.5.7+-2+donate.sury.org~trusty+1
php-pear 1:1.10.1+submodules+notgz-8+donate.sury.org~trusty+2
php5.6 5.6.25-1+deb.sury.org~trusty+1
php5.6-bcmath 5.6.25-1+deb.sury.org~trusty+1
php5.6-bz2 5.6.25-1+deb.sury.org~trusty+1
php5.6-cgi 5.6.25-1+deb.sury.org~trusty+1
php5.6-cli 5.6.25-1+deb.sury.org~trusty+1
php5.6-common 5.6.25-1+deb.sury.org~trusty+1
php5.6-curl 5.6.25-1+deb.sury.org~trusty+1
php5.6-dba 5.6.25-1+deb.sury.org~trusty+1
php5.6-dev 5.6.25-1+deb.sury.org~trusty+1
php5.6-fpm 5.6.25-1+deb.sury.org~trusty+1
php5.6-gd 5.6.25-1+deb.sury.org~trusty+1
php5.6-intl 5.6.25-1+deb.sury.org~trusty+1
php5.6-json 5.6.25-1+deb.sury.org~trusty+1
php5.6-ldap 5.6.25-1+deb.sury.org~trusty+1
php5.6-mbstring 5.6.25-1+deb.sury.org~trusty+1
php5.6-mcrypt 5.6.25-1+deb.sury.org~trusty+1
php5.6-opcache 5.6.25-1+deb.sury.org~trusty+1
php5.6-pgsql 5.6.25-1+deb.sury.org~trusty+1
php5.6-readline 5.6.25-1+deb.sury.org~trusty+1
php5.6-soap 5.6.25-1+deb.sury.org~trusty+1
php5.6-xml 5.6.25-1+deb.sury.org~trusty+1
php5.6-xmlrpc 5.6.25-1+deb.sury.org~trusty+1
php5.6-xsl 5.6.25-1+deb.sury.org~trusty+1
php5.6-zip 5.6.25-1+deb.sury.org~trusty+1
pkg-php-tools 1.33+deb.sury.org~trusty+1

apache-vhost.conf (domain name modified for privacy reasons):

`<VirtualHost *:80>

```
ServerName vhost.example.com
DocumentRoot /var/www/public_html

ErrorLog  "/var/log/apache2/error.log"
CustomLog "/var/log/apache2/access.log" combined

ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/var/run/php-fpm.sock|fcgi://localhost/var/www/public_html/
```

</VirtualHost>`

Loaded php-modules:

bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
ldap
libxml
mbstring
mcrypt
memcached
mhash
msgpack
oci8
openssl
pcntl
pcre
PDO
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

Apache Version:

`Server version: Apache/2.4.23 (Ubuntu)
Server built:   2016-07-11T10:51:19
Server's Module Magic Number: 20120211:61
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"`

Apache loaded modules:

 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 rpaf_module (shared)
 setenvif_module (shared)
 status_module (shared)
 xml2enc_module (shared)

**Comment by nrobinaubertin** [comment]
I know it's an old bug but it bit me today. Here are my findings.
This is likely not going to be fixed since it's the same upstream and php5.6 has reached end of life.
This was already reported on php upstream in 2012 (https://bugs.php.net/bug.php?id=62596) and was finally fixed in 2017 for php7.3 only (https://php.net/ChangeLog-7.php#7.3.0).  
This can be an issue because maintainers of debian jessie manually patched it: https://sources.debian.org/patches/php5/5.6.33+dfsg-0+deb8u1/0045-getallheaders-for-php-fpm-62596.patch/
So if you come from php5.6-fpm from jessie and go to sury (which you shouldn't do ideally because php5.6 has reached end of life), be aware that `getallheaders()` is not here anymore.  
A polyfill for it can be found here: https://github.com/ralouphie/getallheaders

**Comment by oerdnj** [comment]
Nothing less than PHP 7.3 is officially supported and I am not going to patch this, so I am just closing the issue here.
