### ISSUE TITLE
Include all PHP versions when using the metapackages

### ISSUE THREAD

**Issue by deviantintegral** [oerdnj/deb.sury.org#441]
When I apt-get install a package like php-oauth, it looks like some packages install only the PHP 7 versions, while others also include 5.6 (and 5.5? packages). When I install the metapackage, I'm not expecting just the latest PHP, but all of the various versions. If I only want a specific extension (like the 7.0 extensions), I'd expect to install php7.0-oauth.

At the least, making this consistent would be a nice win.

**Comment by oerdnj** [comment]
```
Package: php-oauth
Priority: extra
Section: php
Installed-Size: 340
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: amd64
Version: 2.0.1+1.2.3+-2+donate.sury.org~trusty+1
Provides: php5.5-oauth, php5.6-oauth, php7.0-oauth
Depends: php-common (>= 1:7.0+33~), phpapi-20121212 | phpapi-20151012 | phpapi-20131226, libc6 (>= 2.14)
Filename: pool/main/p/php-oauth/php-oauth_2.0.1+1.2.3+-2+donate.sury.org~trusty+1_amd64.deb
Size: 61628
MD5sum: 69d055ea0beec5566b6ba78e241eb8f3
SHA1: e211b5de6b1c3a4db4b32fb549a821279a1680ba
SHA256: f1b4d450d802237f283341b2f5e991657aa94a8c3cd0e7458f46cf2423fe1f9c
Description-en: OAuth 1.0 consumer and provider extension
 OAuth is an authorization protocol built on top of HTTP which allows
 applications to securely access data without having to store
 usernames and passwords.
 .
 This package provides an API for fetching and serving OAuth
 protected resources.
Description-md5: fb3d073fa1941bfdc8fb470a0bc6a56c
```

**Provides: php5.5-oauth, php5.6-oauth, php7.0-oauth**

**Comment by deviantintegral** [comment]
Actually, oauth was a bad example, but I'm seeing this with the mysql extension.

```
➜  ~ apt-cache show php-mysql
Package: php-mysql
Status: install ok installed
Priority: optional
Section: php
Installed-Size: 28
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: all
Source: php-defaults (44+deb.sury.org~trusty+1)
Version: 1:7.0+44+deb.sury.org~trusty+1
Depends: php-common, php7.0-mysql
Description: MySQL module for PHP [default]
 This package provides a MySQL module for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on Debian's default
 PHP version (currently 7.0).
Description-md5: 265a7711f424b33d41963a4e513338ea
```

**Comment by oerdnj** [comment]
> This package is a dependency package, which depends on Debian's default PHP version (currently 7.0).

**Comment by deviantintegral** [comment]
Right, but why does php-oauth behave differently than php-mysql? Doesn't it make sense for all PHP extension metapackages to either only install PHP 7 / latest packages, or install all available versions?

**Comment by oerdnj** [comment]
There's a difference between core extensions (included with PHP) and external PECL packages. The external PECL packages are versionless, but provide versioned package names. The core extensions have to be versioned and thus they have meta packages. One way or another when installing versionless packages (php-oauth or php-mysql), you always get extension compiled with default PHP version.

**Comment by oerdnj** [comment]
The PECL packages are versionless so they don't require manual action every time there's a new PHP version (or old PHP version is made obsolete).l

**Comment by deviantintegral** [comment]
Ah, that makes sense. Thanks for the help.
