### ISSUE TITLE
Can't seem to install xdebug for php 7.1

### ISSUE THREAD

**Issue by asgrim** [oerdnj/deb.sury.org#444]
Not sure if it's me or it's really just missing, but I can't get xdebug installed for php7.1.

I've just installed php7.1 (I had php7.0 already)

I've tried `sudo apt-get purge php-xdebug && sudo apt-get install php-xdebug`. Copied my `xdebug.ini` from `/etc/php/7.0/` to `/etc/php/7.1/`.

```
$ php -v
Failed loading /usr/lib/php/20160303/xdebug.so:  /usr/lib/php/20160303/xdebug.so: cannot open shared object file: No such file or directory
PHP 7.1.0beta3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0beta3, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by oerdnj** [comment]
xdebug doesn't support PHP 7.1 yet.

**Comment by asgrim** [comment]
I installed `xdebug.so` by compiling manually from `master` (at `9ad6791` currently) and initial indications are that it works just fine.

Steps to reproduce:

```
$ cd xdebug
$ phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
$ ./configure --enable-xdebug
 -- snip --
$ make
 -- snip --
$ sudo cp modules/xdebug.so /usr/lib/php/20160303/.
$ php -v
PHP 7.1.0beta3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0beta3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
$
```

Not sure if earlier versions work, but release notes seem to suggest that even 2.4.0 of xdebug should work with PHP 7.1:

> [2016-01-25] - Xdebug 2.4.0RC4 is out!
> This is the fourth and hopefully last release candidate of the 2.4 series. The 2.4 series adds support for PHP 7 and is in large parts a rewrite of the earlier code base to support PHP 5.4 through PHP 7.0. This release candidate fixes among others, a bunch of crashes, and adds support for PHP 7.1.

I haven't had a response from @derickr directly though, but indications are that it should work.

**Comment by oerdnj** [comment]
From https://launchpadlibrarian.net/281530030/buildlog_ubuntu-xenial-amd64.xdebug_2.4.1-1+deb.sury.org~xenial+1.1_BUILDING.txt.gz
> configure: error: not supported. Need a PHP version >= 5.4.0 and < 7.1.0 (found 7.1.0beta3)

**Comment by asgrim** [comment]
Perhaps needs to be `master` then, no worries :) I'll continue building from source for now.

**Comment by derickr** [comment]
Only master works with PHP 7.1, 2.4.x is PHP 5.4 to PHP 7.0 only.

**Comment by asgrim** [comment]
Thanks for confirming Derick! :)

**Comment by kbond** [comment]
It looks like xdebug 2.5.0RC1 supports 7.1 (https://github.com/xdebug/xdebug/releases/tag/XDEBUG_2_5_0RC1)

**Comment by derickr** [comment]
Indeed, and the upcoming 2.5.0RC2 ... or maybe I should just call it 2.5.0.

**Comment by pavarnos** [comment]
Woo hoo! 2.5.0 is now released https://xdebug.org/updates.php#x_2_5_0
