### ISSUE TITLE
Phpmyadmin and php5.6

### ISSUE THREAD

**Issue by Arjoni** [oerdnj/deb.sury.org#449]
Hello, 
Can you please add a phpmyadmin version for php5.6 so when a user wants to install phpmyadmin, he doesn't have to install the old version of php5. Thank you.

**Comment by oerdnj** [comment]
Use phpmyadmin ppa: https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin

**Comment by Arjoni** [comment]
I did, it still asked me to install php5 from ubuntu repos.

**Comment by oerdnj** [comment]
Just double checked phpmyadmin from nijel's repository and it's correct. Does:
`apt-cache policy phpmyadmin`
really shows the version from `ppa:nijel/phpmyadmin`?
