### ISSUE TITLE
Ubuntu 12.04 can't update apache 2 packages

### ISSUE THREAD

**Issue by cvetan** [oerdnj/deb.sury.org#45]
When today updates came the software could not be updated. It helds back these packages: 
apache2 apache2-bin apache2-data apache2-mpm-prefork,
and the dist-upgrade doesn't help. When i try 
sudo apt-get install apache2 apache2-bin apache2-data apache2-mpm-prefork, it shows The following packages have unmet dependencies:
 apache2 : PreDepends: dpkg (>= 1.17.14).

I haven't had any issues with this ppa at all, until now. Always upgraded my php on ubuntu 12.04. Any advice?

**Comment by tomgidden** [comment]
I can confirm this is happening with a brand new Ubuntu (trusty) install in a VM.

**Comment by oerdnj** [comment]
Tracking in #47
