### ISSUE TITLE
zend_mm_heap corrupted

### ISSUE THREAD

**Issue by pavarnos** [oerdnj/deb.sury.org#452]
Hi

Updated from 7.0.9-1 to 7.0.10-2 and now seeing lots of zend_mm_heap corrupted messages in the apache error logs (ubuntu 14.10 and 16.10). Seems like an intermittent fault: i think i just got it isolated to one spot in the php code, so i make a small change and it shifts somewhere else.

How do I diagnose this and provide a meaningful bug report?

**Comment by pavarnos** [comment]
https://bugs.php.net/bug.php?id=69251 did not help.
neither did https://bugs.php.net/bug.php?id=40479 (there is a stress app at 2011-08-31 07:49 UTC. Setting the count to 10,000,000 did not trigger the error)

**Comment by pavarnos** [comment]
Possibly related to APC?
http://stackoverflow.com/questions/2247977/what-does-zend-mm-heap-corrupted-mean has a number of different approaches, all old.
I was using apc very intensively (apc_* functions) to cache hundreds of small pieces of data. I switched out to filesystem storage and stopped getting the error.
Its been difficult to replicate: the place where it dies (in my php code) seems to shift around or fail inconsistently as i comment out bits to try and isolate it.

**Comment by machinez** [comment]
After trying a variety of settings posted on the stackoverflow link above, this change worked for me
edit: /etc/php.d/opcache.ini
set: opcache.fast_shutdown=0
reload apache. This solution worked on Centos 7.2/PHP 5.5

**Comment by oerdnj** [comment]
Neither PHP 7.0 nor 7.2 is official supported by upstream, closing.
