### ISSUE TITLE
dpkg error processing package libapache2-mod-php7.0 (--configure)

### ISSUE THREAD

**Issue by Sid6555** [oerdnj/deb.sury.org#457]
I am running a virtual machine with vagrant and have set up Ubuntu as the OS. I want to setup apache2 with php7.0 but it keeps telling the libapache2-mod-php7.0 cannot be configured, I do not know why. Apt-get upgrade also returns the same error. I read somewhere to install the package software-properties-gtk to update sources.list. But that too did not work.

Package: libapache2-mod-php7.0 (7.0.10-2+deb.sury.org~trusty+1)
Version: 7.0.10

Error: dpkg: error processing package libapache2-mod-php7.0 (--configure)
Ubuntu version: 14.04.5 LTS

Through admin login:
1. Ran apt-get update and apt-get upgrade
2. Disabled xdebug in /etc/php/7.0/apache2/php.ini as
        xdebug.remote_autostart=0
        xdebug.remote_enable=0
        xdebug.profile_enable=0

On running apt-get install libapache2-mod-php7.0 it throws the following  error.

dpkg: error processing package libapache2-mod-php7.0 (--configure)
subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of php7.0

**Comment by oerdnj** [comment]
What is the full output of the upgrade process and is there more information in the apt log files (`/var/log/apt/*.log`)?

**Comment by oerdnj** [comment]
No input for OP, closing.
