### ISSUE TITLE
memcached.ini not installed for php71

### ISSUE THREAD

**Issue by basz** [oerdnj/deb.sury.org#459]
Hi,

when installing `php-memcached` it will not install

'/etc/php/7.1/mods-available/memcached.ini'

**Comment by basz** [comment]
It seems `/usr/lib/php/20160303` doesn't contain `memcached.so`. 

Probably the php-memcached package isn't ready for php71 at this time.

**Comment by oerdnj** [comment]
Exactly. `php-msgpack` is missing PHP 7.1 support, and memcached depends on that.

**Comment by oerdnj** [comment]
The easy way how to check what PHP versions are supported is `Provides` field of the package:
```
$ apt-cache show php-memcached | grep ^Provides
Provides: php5.5-memcached, php5.6-memcached, php7.0-memcached
```

**Comment by basz** [comment]
is this true for php-redis as well?

that's becoming a problem then. memcached and reds not working on php7.1

**Comment by oerdnj** [comment]
PHP 7.1 hasn't been released yet, so please just be patient. memcached haven't seen a release for PHP 7.0 yet, so let's not make a fuzz about PHP 7.1 until there's a final release.

**Comment by basz** [comment]
forgot for a moment php71 has not been released yet... sorry, didn't mean to apply pressure.

**Comment by oerdnj** [comment]
Try now, msgpack with patch successfully compiled with PHP 7.1, so did memcached.

**Comment by basz** [comment]
thanks oerdnj! work for me

**Comment by RafaelPlantard** [comment]
how can I install it at Mac?

**Comment by RafaelPlantard** [comment]
`
brew info php71-memcached
Error: No available formula with the name "php71-memcached"
`

**Comment by basz** [comment]
hm, not merged PR

https://github.com/Homebrew/homebrew-php/pull/3798

I would wait a few more days...

**Comment by RafaelPlantard** [comment]
Thanks, I will wait for it.
