### ISSUE TITLE
Problem whit apache 

### ISSUE THREAD

**Issue by tokar86a** [oerdnj/deb.sury.org#46]
Hi

After a recently updated to the new apache version i have end up whit this problem. 

Failed to start apache :

 * Starting web server apache2
 * 
 * The apache2 configtest failed.
Output of config test was:
env: apache2ctl: No such file or directory

Is this some sort of bug?

**Comment by oerdnj** [comment]
Looks like it, could you please do:

    dpkg -L apache2

and post the contents here?

**Comment by tokar86a** [comment]
This is what i get:

tokar86a@server:~$ dpkg -L apache2
/etc
/etc/bash_completion.d
/etc/bash_completion.d/apache2
/etc/default
/etc/default/apache2
/etc/cron.daily
/etc/cron.daily/apache2
/etc/logrotate.d
/etc/logrotate.d/apache2
/etc/apache2
/etc/apache2/conf-available
/etc/apache2/conf-available/serve-cgi-bin.conf
/etc/apache2/conf-available/charset.conf
/etc/apache2/conf-available/security.conf
/etc/apache2/conf-available/localized-error-pages.conf
/etc/apache2/conf-available/other-vhosts-access-log.conf
/etc/apache2/apache2.conf
/etc/apache2/conf-enabled
/etc/apache2/envvars
/etc/apache2/magic
/etc/apache2/sites-enabled
/etc/apache2/sites-available
/etc/apache2/sites-available/default-ssl.conf
/etc/apache2/sites-available/000-default.conf
/etc/apache2/mods-available
/etc/apache2/mods-available/log_forensic.load
/etc/apache2/mods-available/expires.load
/etc/apache2/mods-available/request.load
/etc/apache2/mods-available/dav_lock.load
/etc/apache2/mods-available/negotiation.load
/etc/apache2/mods-available/session_dbd.load
/etc/apache2/mods-available/ldap.load
/etc/apache2/mods-available/cache_socache.load
/etc/apache2/mods-available/access_compat.load
/etc/apache2/mods-available/buffer.load
/etc/apache2/mods-available/authz_dbm.load
/etc/apache2/mods-available/proxy_connect.load
/etc/apache2/mods-available/authz_owner.load
/etc/apache2/mods-available/auth_form.load
/etc/apache2/mods-available/file_cache.load
/etc/apache2/mods-available/negotiation.conf
/etc/apache2/mods-available/usertrack.load
/etc/apache2/mods-available/mime_magic.load
/etc/apache2/mods-available/lbmethod_byrequests.load
/etc/apache2/mods-available/sed.load
/etc/apache2/mods-available/heartbeat.load
/etc/apache2/mods-available/userdir.load
/etc/apache2/mods-available/authn_dbd.load
/etc/apache2/mods-available/status.load
/etc/apache2/mods-available/authn_anon.load
/etc/apache2/mods-available/deflate.conf
/etc/apache2/mods-available/dav_fs.load
/etc/apache2/mods-available/alias.conf
/etc/apache2/mods-available/proxy.conf
/etc/apache2/mods-available/lbmethod_heartbeat.load
/etc/apache2/mods-available/cache.load
/etc/apache2/mods-available/heartmonitor.load
/etc/apache2/mods-available/authz_host.load
/etc/apache2/mods-available/autoindex.conf
/etc/apache2/mods-available/log_debug.load
/etc/apache2/mods-available/cache_disk.conf
/etc/apache2/mods-available/proxy_ftp.conf
/etc/apache2/mods-available/proxy_ajp.load
/etc/apache2/mods-available/lua.load
/etc/apache2/mods-available/actions.conf
/etc/apache2/mods-available/mime_magic.conf
/etc/apache2/mods-available/authn_socache.load
/etc/apache2/mods-available/proxy.load
/etc/apache2/mods-available/dbd.load
/etc/apache2/mods-available/mpm_event.conf
/etc/apache2/mods-available/cgi.load
/etc/apache2/mods-available/info.conf
/etc/apache2/mods-available/status.conf
/etc/apache2/mods-available/rewrite.load
/etc/apache2/mods-available/proxy_balancer.conf
/etc/apache2/mods-available/remoteip.load
/etc/apache2/mods-available/slotmem_plain.load
/etc/apache2/mods-available/dir.load
/etc/apache2/mods-available/userdir.conf
/etc/apache2/mods-available/authn_file.load
/etc/apache2/mods-available/cgid.load
/etc/apache2/mods-available/proxy_express.load
/etc/apache2/mods-available/allowmethods.load
/etc/apache2/mods-available/include.load
/etc/apache2/mods-available/authz_dbd.load
/etc/apache2/mods-available/suexec.load
/etc/apache2/mods-available/info.load
/etc/apache2/mods-available/authz_core.load
/etc/apache2/mods-available/setenvif.conf
/etc/apache2/mods-available/authnz_ldap.load
/etc/apache2/mods-available/session_crypto.load
/etc/apache2/mods-available/lbmethod_bybusyness.load
/etc/apache2/mods-available/actions.load
/etc/apache2/mods-available/session.load
/etc/apache2/mods-available/mpm_prefork.conf
/etc/apache2/mods-available/unique_id.load
/etc/apache2/mods-available/filter.load
/etc/apache2/mods-available/reqtimeout.conf
/etc/apache2/mods-available/asis.load
/etc/apache2/mods-available/proxy_wstunnel.load
/etc/apache2/mods-available/ssl.conf
/etc/apache2/mods-available/socache_shmcb.load
/etc/apache2/mods-available/lbmethod_bytraffic.load
/etc/apache2/mods-available/data.load
/etc/apache2/mods-available/macro.load
/etc/apache2/mods-available/cache_disk.load
/etc/apache2/mods-available/reflector.load
/etc/apache2/mods-available/proxy_balancer.load
/etc/apache2/mods-available/alias.load
/etc/apache2/mods-available/mpm_worker.load
/etc/apache2/mods-available/authz_groupfile.load
/etc/apache2/mods-available/ssl.load
/etc/apache2/mods-available/env.load
/etc/apache2/mods-available/echo.load
/etc/apache2/mods-available/substitute.load
/etc/apache2/mods-available/autoindex.load
/etc/apache2/mods-available/cgid.conf
/etc/apache2/mods-available/authn_dbm.load
/etc/apache2/mods-available/charset_lite.load
/etc/apache2/mods-available/proxy_scgi.load
/etc/apache2/mods-available/authn_core.load
/etc/apache2/mods-available/dialup.load
/etc/apache2/mods-available/proxy_http.load
/etc/apache2/mods-available/socache_dbm.load
/etc/apache2/mods-available/auth_digest.load
/etc/apache2/mods-available/slotmem_shm.load
/etc/apache2/mods-available/ratelimit.load
/etc/apache2/mods-available/dav_fs.conf
/etc/apache2/mods-available/auth_basic.load
/etc/apache2/mods-available/mime.conf
/etc/apache2/mods-available/ldap.conf
/etc/apache2/mods-available/speling.load
/etc/apache2/mods-available/mpm_event.load
/etc/apache2/mods-available/socache_memcache.load
/etc/apache2/mods-available/vhost_alias.load
/etc/apache2/mods-available/deflate.load
/etc/apache2/mods-available/proxy_html.load
/etc/apache2/mods-available/session_cookie.load
/etc/apache2/mods-available/setenvif.load
/etc/apache2/mods-available/proxy_fcgi.load
/etc/apache2/mods-available/proxy_ftp.load
/etc/apache2/mods-available/dump_io.load
/etc/apache2/mods-available/mime.load
/etc/apache2/mods-available/authz_user.load
/etc/apache2/mods-available/reqtimeout.load
/etc/apache2/mods-available/mpm_worker.conf
/etc/apache2/mods-available/ext_filter.load
/etc/apache2/mods-available/dav.load
/etc/apache2/mods-available/headers.load
/etc/apache2/mods-available/xml2enc.load
/etc/apache2/mods-available/proxy_fdpass.load
/etc/apache2/mods-available/mpm_prefork.load
/etc/apache2/mods-available/dir.conf
/etc/apache2/ports.conf
/etc/apache2/mods-enabled
/etc/init.d
/etc/init.d/apache2
/var
/var/log
/var/log/apache2
/var/www
/var/www/html
/etc/ufw/applications.d/apache2-utils.ufw.profile

So whats happen now?

**Comment by oerdnj** [comment]
What Ubuntu release are you on?

**Comment by oerdnj** [comment]
Also I need the PPA and architecture.

**Comment by tokar86a** [comment]
I use 14.04 

And what exactly do you mean whit this?

PPA and architecture.

**Comment by tokar86a** [comment]
Do you mean this? 

# deb cdrom:[Ubuntu-Server 14.04 LTS _Trusty Tahr_ - Release amd64 (20140416.2)]/ trusty main restricted

# deb cdrom:[Ubuntu-Server 14.04 LTS _Trusty Tahr_ - Release amd64 (20140416.2)]/ trusty main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://mirrors.digitalocean.com/ubuntu/ trusty main restricted
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://mirrors.digitalocean.com/ubuntu/ trusty-updates main restricted
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://mirrors.digitalocean.com/ubuntu/ trusty universe
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty universe
deb http://mirrors.digitalocean.com/ubuntu/ trusty-updates universe
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://mirrors.digitalocean.com/ubuntu/ trusty multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty multiverse
deb http://mirrors.digitalocean.com/ubuntu/ trusty-updates multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://mirrors.digitalocean.com/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://mirrors.digitalocean.com/ubuntu/ trusty multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty multiverse
deb http://mirrors.digitalocean.com/ubuntu/ trusty-updates multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://mirrors.digitalocean.com/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb-src http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb-src http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse
deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu trusty partner
# deb-src http://archive.canonical.com/ubuntu trusty partner

## Uncomment the following two lines to add software from Ubuntu's
## 'extras' repository.
## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
# deb http://extras.ubuntu.com/ubuntu trusty main
# deb-src http://extras.ubuntu.com/ubuntu trusty main
deb http://download.webmin.com/download/repository sarge contrib

deb http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main
deb-src http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main
deb http://dl.hhvm.com/ubuntu trusty main
# deb-src http://dl.hhvm.com/ubuntu trusty main
# deb-src http://dl.hhvm.com/ubuntu trusty main

**Comment by oerdnj** [comment]
ppa:ondrej/php5 it is.

Are you on i386 or amd64?

I will track the bug under #47 from now on.
