### ISSUE TITLE
Two small fixes for sessionclean script

### ISSUE THREAD

**Issue by tinuzz** [oerdnj/deb.sury.org#460]
Looking at the code of /usr/lib/php/sessionclean, I noticed some things that are likely incorrect, breaking the functionality of touching the currently open session files.

First the script looks for processes with a specific name. In the case of the FPM SAPI, that is 'php@VERSION@-fpm'. That used to be correct in the days of 'php5', but it is incorrect now. It should be 'php-fpm@VERSION@'.

`$ pidof php5.6-fpm`
`$ pidof php-fpm5.6`
`5132 5131 5130 5129 5128 5127 5126 5125 5124`
`$ sudo ls -ln /proc/5129/exe`
`lrwxrwxrwx 1 1011 1012 0 Sep 22 16:09 /proc/5129/exe -> /usr/sbin/php-fpm5.6`

So, for the FPM SAPI, the script won't find any processes and therefore no session files to touch.

Secondly, the script uses this command to find the files:

`find "/proc/$pid/fd" -ignore_readdir_race -lname "$save_path/sess_\*" -exec touch -c {} \;`

The problem is with -lname `"$save_path/sess_\*"`. By putting the name inside quotes AND escaping the asterisk, it will look for a literal '*' and no files will ever match. I think it should be this:

`find "/proc/$pid/fd" -ignore_readdir_race -lname "$save_path/sess_*" -exec touch -c {} \;`

I hope this helps.

Best regards,
Martijn.

**Comment by oerdnj** [comment]
Good catch. Fixed in `php-defaults >= 45`
