### ISSUE TITLE
Ubuntu 14.04 Update to php5.6 failed (libapache2-mod-php5.6)

### ISSUE THREAD

**Issue by maeh86** [oerdnj/deb.sury.org#462]
Hello,

today, I wanted to upgrade my Ubuntu 14.04 LTS with included php5.5 to php5.6 with the help of the repository of Ondrej (ppa:ondrej/php).
 The Installation of php5.6 itself works fine, but the Installation of libapache2-mod-php5.6 aborts with errors:

-------------------
 apt-get install libapache2-mod-php5.6
 Paketlisten werden gelesen... Fertig
 Abhängigkeitsbaum wird aufgebaut.
 Statusinformationen werden eingelesen.... Fertig
 Die folgenden NEUEN Pakete werden installiert:
   libapache2-mod-php5.6
 0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
 Es müssen 1.207 kB an Archiven heruntergeladen werden.
 Nach dieser Operation werden 4.428 kB Plattenplatz zusätzlich benutzt.
 Holen: 1 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libapache2-mod-php5.6 amd64 5.6.26-1+deb.sury.org~trusty+1 [1.207 kB]
 Es wurden 1.207 kB in 0 s geholt (1.552 kB/s).
 Vormals nicht ausgewähltes Paket libapache2-mod-php5.6 wird gewählt.
 (Lese Datenbank ... 127409 Dateien und Verzeichnisse sind derzeit installiert.)
 Vorbereitung zum Entpacken von .../libapache2-mod-php5.6_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
 Entpacken von libapache2-mod-php5.6 (5.6.26-1+deb.sury.org~trusty+1) ...
 libapache2-mod-php5.6 (5.6.26-1+deb.sury.org~trusty+1) wird eingerichtet ...
 usage: fail($reason, $retval) at /usr/sbin/a2query line 168.
 usage: fail($reason, $retval) at /usr/sbin/a2query line 168.
 usage: fail($reason, $retval) at /usr/sbin/a2query line 168.
 usage: fail($reason, $retval) at /usr/sbin/a2query line 168.
 /var/lib/dpkg/info/libapache2-mod-php5.6.postinst: 284: [: !=: unexpected operator
 apache2_switch_mpm prefork: No action required
 dpkg: Fehler beim Bearbeiten des Paketes libapache2-mod-php5.6 (--configure):
  Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
 Fehler traten auf beim Bearbeiten von:
  libapache2-mod-php5.6
 E: Sub-process /usr/bin/dpkg returned an error code (1)
 -------------------

Can someone help me?

thanks and best regards
 Markus

edit: same Problem, but with packet libapache2-mod-php5 was fixed by Ondrej here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755057

**Comment by oerdnj** [comment]
Could you attach contents of `/var/lib/dpkg/info/libapache2-mod-php5.6.postinst` on your system and output of:
1. `a2query -m "php5.6"`
2. `a2query -m | sed -n 's/^\(php[\.0-9]*\) (enabled.*)/\1/p'`
3. `a2query -M`

I think something is broken with your apache2 installation making the `a2query` invocations to fail.

**Comment by maeh86** [comment]
Thanks for your Response :)

Attached, you will find the Content of  /var/lib/dpkg/info/libapache2-mod-php5.6.postinst.
The a2query commands do all fail with the following error:
----
usage: fail($reason, $retval) at /usr/sbin/a2query line 168.
----

I've tested the a2query-command on some other webservers (all Ubuntu 14.04.5 LTS with mpm-itk (some are upgraded to php5.6 and some are still on php5.5) and everywhere, the same error occurs.
I've attached the file /usr/sbin/a2query too, if this could be interesting for you.


[a2query.txt](https://github.com/oerdnj/deb.sury.org/files/502512/a2query.txt)
[libapache2-mod-php5.6.postinst.txt](https://github.com/oerdnj/deb.sury.org/files/502513/libapache2-mod-php5.6.postinst.txt)

best regards,
Markus

**Comment by oerdnj** [comment]
Could you try a2query with plain apache2 installation without mpm_itk and then enable itk and retry a2query again? If the failure is caused by mpm_itk, you'll need to fill the bug against mpm_itk package. Your apache2 installation is broken and I can't do anything about that from within PHP packaging.

**Comment by maeh86** [comment]
You are right and your tip was very good.
I first disabled mpm_itk (a2dismod mpm_itk) and a2query ran without any problem. After that, I installed libapache2-mod-php5.6 without errors and activated mpm_itk again. Now, Apache runs with php5.6 and mpm_itk, but a2query doesn't work - I will look, where I can report this bug to mpm_itk.
Many thanks for your help and best regards.

Markus
