### ISSUE TITLE
php5.6-dev installs php7.0 package

### ISSUE THREAD

**Issue by jtreminio** [oerdnj/deb.sury.org#464]
Ubuntu 14.04 x64:

    [06:46 AM]-[root@machine1]-[/home/vagrant]
    # php -v
    bash: /usr/bin/php: No such file or directory

    [06:46 AM]-[root@machine1]-[/home/vagrant]
    # apt-get install php5.6-fpm
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libicu52 liblist-moreutils-perl libpcre16-3 libpcre3-dev libpcre32-3
      libpcrecpp0 libxslt1.1 shtool xml2
    Use 'apt-get autoremove' to remove them.
    The following extra packages will be installed:
      php-common php5.6-cli php5.6-common php5.6-json php5.6-opcache
      php5.6-readline
    Suggested packages:
      php-pear
    The following NEW packages will be installed:
      php-common php5.6-cli php5.6-common php5.6-fpm php5.6-json php5.6-opcache
      php5.6-readline
    0 upgraded, 7 newly installed, 0 to remove and 116 not upgraded.
    Need to get 0 B/5,362 kB of archives.
    After this operation, 16.1 MB of additional disk space will be used.
    Do you want to continue? [Y/n]
    Selecting previously unselected package php-common.
    (Reading database ... 70857 files and directories currently installed.)
    Preparing to unpack .../php-common_1%3a45+deb.sury.org~trusty+1_all.deb ...
    Unpacking php-common (1:45+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-common.
    Preparing to unpack .../php5.6-common_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-common (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-json.
    Preparing to unpack .../php5.6-json_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-json (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-opcache.
    Preparing to unpack .../php5.6-opcache_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-opcache (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-readline.
    Preparing to unpack .../php5.6-readline_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-readline (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-cli.
    Preparing to unpack .../php5.6-cli_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-cli (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php5.6-fpm.
    Preparing to unpack .../php5.6-fpm_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-fpm (5.6.26-1+deb.sury.org~trusty+1) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Processing triggers for ureadahead (0.100.0-16) ...
    Setting up php-common (1:45+deb.sury.org~trusty+1) ...
    Setting up php5.6-common (5.6.26-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/5.6/mods-available/calendar.ini with new version

    Creating config file /etc/php/5.6/mods-available/ctype.ini with new version

    Creating config file /etc/php/5.6/mods-available/exif.ini with new version

    Creating config file /etc/php/5.6/mods-available/fileinfo.ini with new version

    Creating config file /etc/php/5.6/mods-available/ftp.ini with new version

    Creating config file /etc/php/5.6/mods-available/gettext.ini with new version

    Creating config file /etc/php/5.6/mods-available/iconv.ini with new version

    Creating config file /etc/php/5.6/mods-available/pdo.ini with new version

    Creating config file /etc/php/5.6/mods-available/phar.ini with new version

    Creating config file /etc/php/5.6/mods-available/posix.ini with new version

    Creating config file /etc/php/5.6/mods-available/shmop.ini with new version

    Creating config file /etc/php/5.6/mods-available/sockets.ini with new version

    Creating config file /etc/php/5.6/mods-available/sysvmsg.ini with new version

    Creating config file /etc/php/5.6/mods-available/sysvsem.ini with new version

    Creating config file /etc/php/5.6/mods-available/sysvshm.ini with new version

    Creating config file /etc/php/5.6/mods-available/tokenizer.ini with new version
    Setting up php5.6-json (5.6.26-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/5.6/mods-available/json.ini with new version
    Setting up php5.6-opcache (5.6.26-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/5.6/mods-available/opcache.ini with new version
    Setting up php5.6-readline (5.6.26-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/5.6/mods-available/readline.ini with new version
    Setting up php5.6-cli (5.6.26-1+deb.sury.org~trusty+1) ...
    update-alternatives: using /usr/bin/php5.6 to provide /usr/bin/php (php) in auto mode
    update-alternatives: using /usr/bin/phar5.6 to provide /usr/bin/phar (phar) in auto mode
    update-alternatives: using /usr/bin/phar.phar5.6 to provide /usr/bin/phar.phar (phar.phar) in auto mode

    Creating config file /etc/php/5.6/cli/php.ini with new version
    Setting up php5.6-fpm (5.6.26-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/5.6/fpm/php.ini with new version
    php5.6-fpm start/running, process 4679
    Processing triggers for ureadahead (0.100.0-16) ...

    [06:46 AM]-[root@machine1]-[/home/vagrant]
    # php -v
    PHP 5.6.26-1+deb.sury.org~trusty+1 (cli)
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

    [06:46 AM]-[root@machine1]-[/home/vagrant]
    # apt-get install php5.6-dev
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following package was automatically installed and is no longer required:
      libicu52
    Use 'apt-get autoremove' to remove it.
    The following extra packages will be installed:
      dh-php php-pear php-xml php7.0-common php7.0-xml pkg-php-tools
    Suggested packages:
      dh-make
    The following NEW packages will be installed:
      dh-php php-pear php-xml php5.6-dev php7.0-common php7.0-xml pkg-php-tools
    0 upgraded, 7 newly installed, 0 to remove and 116 not upgraded.
    Need to get 0 B/1,802 kB of archives.
    After this operation, 12.2 MB of additional disk space will be used.
    Do you want to continue? [Y/n]
    Selecting previously unselected package php7.0-common.
    (Reading database ... 71001 files and directories currently installed.)
    Preparing to unpack .../php7.0-common_7.0.11-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php7.0-common (7.0.11-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php7.0-xml.
    Preparing to unpack .../php7.0-xml_7.0.11-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php7.0-xml (7.0.11-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php-xml.
    Preparing to unpack .../php-xml_1%3a7.0+45+deb.sury.org~trusty+1_all.deb ...
    Unpacking php-xml (1:7.0+45+deb.sury.org~trusty+1) ...
    Selecting previously unselected package php-pear.
    Preparing to unpack .../php-pear_1%3a1.10.1+submodules+notgz-8+donate.sury.org~trusty+2_all.deb ...
    Unpacking php-pear (1:1.10.1+submodules+notgz-8+donate.sury.org~trusty+2) ...
    Selecting previously unselected package php5.6-dev.
    Preparing to unpack .../php5.6-dev_5.6.26-1+deb.sury.org~trusty+1_amd64.deb ...
    Unpacking php5.6-dev (5.6.26-1+deb.sury.org~trusty+1) ...
    Selecting previously unselected package dh-php.
    Preparing to unpack .../dh-php_0.21+deb.sury.org~trusty+1_all.deb ...
    Unpacking dh-php (0.21+deb.sury.org~trusty+1) ...
    Selecting previously unselected package pkg-php-tools.
    Preparing to unpack .../pkg-php-tools_1.33+deb.sury.org~trusty+1_all.deb ...
    Unpacking pkg-php-tools (1.33+deb.sury.org~trusty+1) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Setting up php7.0-common (7.0.11-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/7.0/mods-available/calendar.ini with new version

    Creating config file /etc/php/7.0/mods-available/ctype.ini with new version

    Creating config file /etc/php/7.0/mods-available/exif.ini with new version

    Creating config file /etc/php/7.0/mods-available/fileinfo.ini with new version

    Creating config file /etc/php/7.0/mods-available/ftp.ini with new version

    Creating config file /etc/php/7.0/mods-available/gettext.ini with new version

    Creating config file /etc/php/7.0/mods-available/iconv.ini with new version

    Creating config file /etc/php/7.0/mods-available/pdo.ini with new version

    Creating config file /etc/php/7.0/mods-available/phar.ini with new version

    Creating config file /etc/php/7.0/mods-available/posix.ini with new version

    Creating config file /etc/php/7.0/mods-available/shmop.ini with new version

    Creating config file /etc/php/7.0/mods-available/sockets.ini with new version

    Creating config file /etc/php/7.0/mods-available/sysvmsg.ini with new version

    Creating config file /etc/php/7.0/mods-available/sysvsem.ini with new version

    Creating config file /etc/php/7.0/mods-available/sysvshm.ini with new version

    Creating config file /etc/php/7.0/mods-available/tokenizer.ini with new version
    Setting up php7.0-xml (7.0.11-1+deb.sury.org~trusty+1) ...

    Creating config file /etc/php/7.0/mods-available/dom.ini with new version

    Creating config file /etc/php/7.0/mods-available/simplexml.ini with new version

    Creating config file /etc/php/7.0/mods-available/wddx.ini with new version

    Creating config file /etc/php/7.0/mods-available/xml.ini with new version

    Creating config file /etc/php/7.0/mods-available/xmlreader.ini with new version

    Creating config file /etc/php/7.0/mods-available/xmlwriter.ini with new version

    Creating config file /etc/php/7.0/mods-available/xsl.ini with new version
    Setting up php-xml (1:7.0+45+deb.sury.org~trusty+1) ...
    Setting up php-pear (1:1.10.1+submodules+notgz-8+donate.sury.org~trusty+2) ...
    Setting up php5.6-dev (5.6.26-1+deb.sury.org~trusty+1) ...
    update-alternatives: using /usr/bin/php-config5.6 to provide /usr/bin/php-config (php-config) in auto mode
    update-alternatives: using /usr/bin/phpize5.6 to provide /usr/bin/phpize (phpize) in auto mode
    Setting up dh-php (0.21+deb.sury.org~trusty+1) ...
    Setting up pkg-php-tools (1.33+deb.sury.org~trusty+1) ...

When Puppet does this installation is seems PHP 7.0 takes over as the default.

The expected behavior is only version requested by installed, if version provided. For example, only php5.6-dev should have been installed, not php7.0-dev which brings in php7.0

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php70-cli-always-installed
