### ISSUE TITLE
php5.6-zip

### ISSUE THREAD

**Issue by 58bits** [oerdnj/deb.sury.org#467]
`apt-get install php5.6-zip` on Ubuntu 16.04 reports, E: Unable to locate package php5.6-zip.

Should this package be present in php5.6 via the ppa?

**Comment by oerdnj** [comment]
What's output of? 

apt-cache policy php7.0-zip

**Comment by oerdnj** [comment]
@58bits I suspect you don't have PPA enabled at all.

**Comment by oerdnj** [comment]
The PPA publishes:
```
php5.6-zip_5.6.26-1+deb.sury.org~xenial+1_amd64.deb (19.2 KiB)
php5.6-zip_5.6.26-1+deb.sury.org~xenial+1_arm64.deb (16.3 KiB)
php5.6-zip_5.6.26-1+deb.sury.org~xenial+1_armhf.deb (17.1 KiB)
php5.6-zip_5.6.26-1+deb.sury.org~xenial+1_i386.deb (20.9 KiB)
```

So I think there's a mistake on your side.

**Comment by 58bits** [comment]
My apologies - reinstalling the ppa solved it. Thanks very much for the prompt replies.
