### ISSUE TITLE
ppa:ondrej/pkg-gearman update?

### ISSUE THREAD

**Issue by m-ueberall** [oerdnj/deb.sury.org#468]
Hi, is it planned/possible to update the aforementioned repository now that Ubuntu Xenial 16.04 LTS and gearmand v1.1.13 (https://github.com/gearman/gearmand) are available?
Kind regards and many thanks in advance for a heads up!

**Comment by oerdnj** [comment]
Just uploaded to `ppa:ondrej/php`. Give it ~hour to build and install into repository.

**Comment by dol** [comment]
I'm not a fan of this change. The bundling and updating gearman to a newer version broke our production system.
I think it's a nice of @oerdnj to providing a newer gearman version. But not in the context of the `ppa:ondrej/php` repository.
We use pecl to compile the php-gearman extension. This update change the shared libraries and our compiled extension is not compatible with the new shared library interface.
