### ISSUE TITLE
Debian jessie: libapache2-mod-php7.0  cannot be installed

### ISSUE THREAD

**Issue by chechenblaikner** [oerdnj/deb.sury.org#469]
Hi,

Setup as follow:
lsb_release -sc
jessie

 
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

apt-get update && apt-get install -y apache2 libapache2-mod-php7.0 \
                php7.0-gd php7.0-mcrypt php7.0-curl php7.0-memcached \
                php7.0-imagick php7.0-mysql php7.0-apc php7.0-xml \
                php7.0-json php7.0-xsl \
                php7.0-readline php7.0-gd php7.0-cli php7.0-soap \
                php7.0-mbstring php7.0-zip

error as follow:
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapache2-mod-php7.0 : Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1t-1+deb8u5 is to be installed
 php7.0-cli : Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1t-1+deb8u5 is to be installed        
E: Unable to correct problems, you have held broken packages.                                     
...

Thank you,
 Christian

**Comment by oerdnj** [comment]
You need jessie-backports enabled and install:
`apt-get install -t jessie-backports libssl1.0.0`

I have updated README.txt accordingly.

**Comment by chechenblaikner** [comment]
Thank you for the fast response,
