### ISSUE TITLE
Apache 2.4.12 will not install on Trusty

### ISSUE THREAD

**Issue by hbokh** [oerdnj/deb.sury.org#47]
Hi Ondřej,   
Thank you for building the new Apache2.4 packages.
However, there are some issues on Ubuntu Trusty 14.04.1 when installing **and / or** upgrading.
Firts I tried with `aptitude update` and `aptitude install`:

```
user@hostname:~# aptitude install apache2 apache2-bin apache2-data apache2-mpm-worker
The following NEW packages will be installed:
  apache2-utils{a} 
The following packages will be upgraded:
  apache2{b} apache2-bin apache2-data apache2-mpm-worker 
4 packages upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 1,395 kB of archives. After unpacking 415 kB will be used.
The following packages have unmet dependencies:
 apache2 : PreDepends: dpkg (>= 1.17.14) but 1.17.5ubuntu5.3 is installed.
The following actions will resolve these dependencies:

     Remove the following packages:
1)     apache2                     
2)     apache2-mpm-worker          

Accept this solution? [Y/n/q/?] q
Abandoning all efforts to resolve these dependencies.
Abort.
```

dpkg on Ubuntu Trusty is version `1.17.5ubuntu5.3`, also on a fresh installed and updated system.
Version `1.17.14` seems to unique to Debian. I found this: http://git.net/debian-apache/msg02096.html

But OK, let's give it a try with `apt-get install` instead:

```
user@hostname:~# apt-get install apache2 apache2-bin apache2-data apache2-mpm-worker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: apache2-bin (= 2.4.10-1+deb.sury.org~trusty+1) but 2.4.12-1+deb.sury.org~trusty+1 is to be installed
           Depends: apache2-data (= 2.4.10-1+deb.sury.org~trusty+1) but 2.4.12-1+deb.sury.org~trusty+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
LSB information:
```
user@hostname:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```
Installed apache2-packages:
```
user@hostname:~# dpkg -l | grep apache2
ii  apache2                             2.4.10-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server
ii  apache2-bin                         2.4.10-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server (binary files and modules)
ii  apache2-data                        2.4.10-1+deb.sury.org~trusty+1       all          Apache HTTP Server (common files)
ii  apache2-mpm-worker                  2.4.10-1+deb.sury.org~trusty+1       amd64        transitional worker MPM package for apache2
ii  libapache2-mod-fastcgi              2.4.7~0910052141-1.1                 amd64        Apache 2 FastCGI module for long-running CGI scripts
```

Any clues?

**Comment by oerdnj** [comment]
Should be fixed in +5. Just wait till it's built.

**Comment by tokar86a** [comment]
I am pretty sure that i use: i386

**Comment by tokar86a** [comment]
It is: amd64

 dpkg -l | grep apache2
rc  apache2                              2.4.10-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server
ii  apache2-bin                          2.4.12-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                         2.4.12-1+deb.sury.org~trusty+1       all          Apache HTTP Server (common files)
ii  apache2-dev                          2.4.12-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server (development headers)
ii  apache2-suexec-pristine              2.4.12-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server standard suexec program for mod_suexec
ii  apache2-utils                        2.4.12-1+deb.sury.org~trusty+1       amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-bw                    0.92-10                              amd64        bandwidth limiting module for apache2
ii  libapache2-mod-fastcgi               2.4.7~0910052141-1.1                 amd64        Apache 2 FastCGI module for long-running CGI scripts
ii  libapache2-mod-fcgid                 1:2.3.9-1                            amd64        FastCGI interface module for Apache 2
rc  libapache2-mod-php5                  5.5.21+dfsg1-1+deb.sury.org~trusty+2 amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-python                3.3.1-11ubuntu2                      amd64        Python-embedding module for Apache 2
ii  libapache2-mod-suphp                 0.7.2-0ubuntu1                       amd64        Apache2 module to run PHP scripts with the owner permissions

**Comment by oerdnj** [comment]
@tokar86a You should pay attention to what your packaging system tells you:

    rc apache2 2.4.10-1+deb.sury.org~trusty+1

means that you have uninstalled apache2 package.

Anyway looks like the +5 version is fixed, it's already rebuilt and it should be in the archive in few minutes:
https://launchpad.net/~ondrej/+archive/ubuntu/php5/+packages
https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6/+packages

Sorry all for the troubles.

**Comment by hbokh** [comment]
I have just succesfully upgraded on Ubuntu 14.04.01 amd64:

```
# dpkg -l | grep apache
ii  apache2                             2.4.12-1+deb.sury.org~trusty+5       amd64        Apache HTTP Server
ii  apache2-bin                         2.4.12-1+deb.sury.org~trusty+5       amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                        2.4.12-1+deb.sury.org~trusty+5       all          Apache HTTP Server (common files)
ii  apache2-mpm-worker                  2.4.12-1+deb.sury.org~trusty+5       amd64        transitional worker MPM package for apache2
ii  apache2-utils                       2.4.12-1+deb.sury.org~trusty+5       amd64        Apache HTTP Server (utility programs for web servers)
```
