### ISSUE TITLE
PHP 7.0 on Debian 8 - libssl1.0.0

### ISSUE THREAD

**Issue by thmmueller** [oerdnj/deb.sury.org#471]
It seems that the dependencies have changed after update from PHP 7.0.10 to 7.0.11. When I now try to install, e.g., php7.0-cli the following error occurs:

> apt-get install php7.0-cli
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  php7.0-cli : Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1t-1+deb8u5 is to be installed
> E: Unable to correct problems, you have held broken packages.

But this package is not available in Debian 8 repositories. From your repository I have the following libssl installed, but it's not working:

> ii  libssl1.0.2:amd64                     1.0.2j-0+0~20160926185101.3+jessie~1.gbpfd7fbc                    amd64        Secure Sockets Layer toolkit - shared libraries

Do you have any solution for it? I also tried to install PHP 7.0.10, but it seems you don't list older versions in your repository. 

Greets
 Toms

**Comment by oerdnj** [comment]
apt-get install -t jessie-backports libssl1.0.0 

Should fix that. I'll update the repo to fix that.

**Comment by thmmueller** [comment]
Thanks, that helped! And also thanks for fixing it in repo.

Another question. Is it possible, that you keep (at least the last one) old versions in your repository?

Greets
 Toms

**Comment by oerdnj** [comment]
Nope, it's not possible. The packages are handled by launchpad.
