### ISSUE TITLE
apt-get install php-apcu-bc automatically installs php7.0-cli but we only want php5.6-cli

### ISSUE THREAD

**Issue by thomasbley** [oerdnj/deb.sury.org#474]
apt-get install php-apcu-bc automatically installs php7.0-cli (and others) even though we only installed php5.6-cli and don't want php7.

add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php5.6-common php5.6-cli php5.6-opcache php5.6-json php-apcu-bc

**Comment by oerdnj** [comment]
Makes sense as apcu_bc is PHP 7.0+ only.

**Comment by thomasbley** [comment]
ok, what about installing php-apcu with php5.6 only?

add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php5.6-common php5.6-cli php5.6-opcache php5.6-json php-apcu
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libphp7.0-embed libssl1.0.2 php-apcu-bc php-common php5.6-readline
  php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline
Suggested packages:
  php-gd
The following NEW packages will be installed:
  libphp7.0-embed libssl1.0.2 php-apcu php-apcu-bc php-common php5.6-cli
  php5.6-common php5.6-json php5.6-opcache php5.6-readline php7.0-cli
  php7.0-common php7.0-json php7.0-opcache php7.0-readline

**Comment by thomasbley** [comment]
we used this with the php5-5.6 repo:
apt-get install php5-cli php5-apcu

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php70-cli-always-installed

**Comment by thomasbley** [comment]
thanks! we are now using:
apt-get install --no-install-recommends php-apcu
