### ISSUE TITLE
Php7.0 fails to install on ubuntu15.10

### ISSUE THREAD

**Issue by adi2909** [oerdnj/deb.sury.org#475]
Followed the following steps to install php7.0 on an AWS Ubuntu 15.10 image: 

1.sudo add-apt-repository ppa:ondrej/php
2. sudo apt-get update
3. sudo apt-get install php7.0

Got the error on step 3 when its unable to locate php7.0? 

We were able to run these commands last week... just wondering what happened ?

**Comment by oerdnj** [comment]
Ubuntu 15.10 reached EOL in July 2016.
