### ISSUE TITLE
Compile from source error

### ISSUE THREAD

**Issue by JesusTheHun** [oerdnj/deb.sury.org#477]
Hello,

Trying to compile php 7.0.12 from pkg source, `./debian/rules binary` returns :

```
configure: exit 1
	cd /home/jmassuch/packages/php7.0-7.0.12
Died at /usr/share/perl5/Debian/Debhelper/Buildsystem/autoconf.pm line 77.
debian/rules:320: recipe for target 'override_dh_auto_configure-arch' failed
make[1]: *** [override_dh_auto_configure-arch] Error 255
make[1]: Leaving directory '/home/jmassuch/packages/php7.0-7.0.12'
debian/rules:268: recipe for target 'binary' failed
make: *** [binary] Error 2
```

From Ubuntu Xenial.

Do you need any extra information ?

**Comment by oerdnj** [comment]
You didn't provide much information at all.

You should use `debuild` or `dpkg-buildpackage` instead of manual invocation of `debian/rules`. I suspect you are missing build-depends installed. If this is not the case provide a *full* build log and reopen.

**Comment by JesusTheHun** [comment]
I'm not familiar with building package thus I don't know what information is necessary, sorry about that.

Using `debuild` fixes it, yet it detects my changes and refuse to compile as it.
Adding a patch in `debian/patches` and append its name to `debian/patches/series` doesn't do the trick, the patch failed to be applied whereas applying it manually with patch -p1 at the root of the package just works.

```
patching file ext/mysqlnd/mysqlnd_wireprotocol.c
Hunk #1 FAILED at 1516.
1 out of 1 hunk FAILED
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch '0048-mysqlnd-empty-row-packet-body.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/0048-mysqlnd-empty-row-packet-body.patch/ --reject-file=- < php7.0-7.0.12.orig.I5rUfP/debian/patches/0048-mysqlnd-empty-row-packet-body.patch gave error exit status 1
```

Here is my patch file : 

```
From 3de45b0efca2031b9166a78ab4463da602c324ac Mon Sep 17 00:00:00 2001
From: jfilipiak <Jan.Filipiak@trivago.com>
Date: Fri, 16 Sep 2016 20:33:29 +0200
Subject: [PATCH] looks like an easy shot, maybe we can get things moving here

---
 ext/mysqlnd/mysqlnd_wireprotocol.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/ext/mysqlnd/mysqlnd_wireprotocol.c b/ext/mysqlnd/mysqlnd_wireprotocol.c
index bd0ee2a..34fe653 100644
--- a/ext/mysqlnd/mysqlnd_wireprotocol.c
+++ b/ext/mysqlnd/mysqlnd_wireprotocol.c
@@ -1516,6 +1516,7 @@ php_mysqlnd_read_row_ex(MYSQLND_PFC * pfc,
                if (PASS != (ret = pfc->data->m.receive(pfc, vio, p, header.size, stats, error_info))) {
                        DBG_ERR("Empty row packet body");
                        php_error(E_WARNING, "Empty row packet body");
+                       ret = FAIL;
                        break;
                }
```

Relative path of the patch looks the same than other patches.
Do you mind helping me on this ?

**Comment by oerdnj** [comment]
You don't expect me to teach you packaging basics by filling an issue? There are tons of resources on the web for this. Sorry, but I really don't have time for this.

**Comment by JesusTheHun** [comment]
No I expected you to point me the right direction. There are tons of **utterly outdated** resources on the web. Thanks for your time.
