### ISSUE TITLE
php apcu depends on php 7.1

### ISSUE THREAD

**Issue by luispabon** [oerdnj/deb.sury.org#480]
This is breaking php 7.0 installations at the moment:

```
[development@localhost ~] sudo apt install php-apcu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  php-apcu-bc php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-phpdbg php7.1-readline
Suggested packages:
  php-pear
The following NEW packages will be installed
  php-apcu php-apcu-bc php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-phpdbg php7.1-readline
0 to upgrade, 8 to newly install, 0 to remove and 0 not to upgrade.
Need to get 3,800 kB of archives.
After this operation, 15.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by oldskool** [comment]
Can confirm, this error just upgraded some of our servers from 7.0 to 7.1 RC5. From apt logs:

> Start-Date: 2016-11-07  12:14:30
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef install php-apcu
Install: php7.1-readline:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic), php7.1-phpdbg:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic), php7.1-opcache:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic), php7.1-json:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic), php7.1-cli:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic), php7.1-common:amd64 (7.1.0~rc5-1+deb.sury.org~xenial+1, automatic)
Upgrade: php-apcu:amd64 (5.1.5-8-gdbb1d14+tysonandre+4.0.11-1+deb.sury.org~xenial+1, 5.1.7+4.0.11-1+deb.sury.org~xenial+1)
End-Date: 2016-11-07  12:14:42

**Comment by oerdnj** [comment]
Fixed in `php-apcu_5.1.7+4.0.11-2+deb.sury.org~<dist>+1` (well, in fact, it was fixed in `dh-php_0.23`, but rebuild was needed.

**Comment by luispabon** [comment]
Thank you :+1:
