### ISSUE TITLE
*** Error in `/usr/sbin/apache2': malloc(): memory corruption: 0x000055b0dafaab80 ***

### ISSUE THREAD

**Issue by krichter722** [oerdnj/deb.sury.org#482]
[error.log.zip](https://github.com/oerdnj/deb.sury.org/files/577580/error.log.zip)

Page load in ownCloud fails and `/var/log/apache2/error.log` reveals

    > sudo tail -f /var/log/apache2/error.log
    7fcdb52ab000-7fcdb52fa000 rw-p 00000000 00:00 0 
    7fcdb52fa000-7fcdb52fb000 r--p 00024000 00:15 1456016807                 /lib/x86_64-linux-gnu/ld-2.24.so
    7fcdb52fb000-7fcdb52fc000 rw-p 00025000 00:15 1456016807                 /lib/x86_64-linux-gnu/ld-2.24.so
    7fcdb52fc000-7fcdb52fd000 rw-p 00000000 00:00 0 
    7ffc16839000-7ffc1685a000 rw-p 00000000 00:00 0                          [stack]
    7ffc1689f000-7ffc168a1000 r--p 00000000 00:00 0                          [vvar]
    7ffc168a1000-7ffc168a3000 r-xp 00000000 00:00 0                          [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
    [Tue Nov 08 08:36:41.317365 2016] [core:notice] [pid 21161] AH00051: child pid 23130 exit signal Segmentation fault (11), possible coredump in /etc/apache2
    [Tue Nov 08 08:36:41.317412 2016] [core:notice] [pid 21161] AH00051: child pid 23133 exit signal Aborted (6), possible coredump in /etc/apache2
    *** Error in `/usr/sbin/apache2': malloc(): memory corruption: 0x000055b0dafaab80 ***
    ======= Backtrace: =========
    /lib/x86_64-linux-gnu/libc.so.6(+0x790cb)[0x7fcdb449e0cb]
    /lib/x86_64-linux-gnu/libc.so.6(+0x8421e)[0x7fcdb44a921e]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fcdb44aade4]
    /usr/lib/libGraphicsMagick-Q16.so.3(SetMagickInfo+0x17)[0x7fcd9b2dc1b7]
    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/gif.so(RegisterGIFImage+0x81)[0x7fcd70547681]
    /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(+0x12a351)[0x7fcd9978e351]
    /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(OpenModules+0x69)[0x7fcd9978efd9]
    /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(GetMagickInfo+0x1b0)[0x7fcd99789930]
    /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(GetMagickList+0x68)[0x7fcd9978a0e8]
    /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2(MagickQueryFormats+0x20)[0x7fcd99bc1430]
    /usr/lib/php/20131226/imagick.so(zim_imagick_queryformats+0x66)[0x7fcd99e65386]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_internal+0x174)[0x7fcda1cf7d94]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305a07)[0x7fcdaa9c6a07]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(zend_call_function+0xa4b)[0x7fcdaa90813b]
    /usr/lib/apache2/modules/libphp5.6.so(zif_call_user_func_array+0x73)[0x7fcdaa84e483]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_internal+0x174)[0x7fcda1cf7d94]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305a07)[0x7fcdaa9c6a07]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305ee0)[0x7fcdaa9c6ee0]
    /usr/lib/apache2/modules/libphp5.6.so(execute_ex+0x40)[0x7fcdaa955630]
    /usr/lib/apache2/modules/libphp5.6.so(dtrace_execute_ex+0x158)[0x7fcdaa906448]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_ex+0x58a)[0x7fcda1cf752a]
    /usr/lib/apache2/modules/libphp5.6.so(zend_call_function+0xa4b)[0x7fcdaa90813b]
    /usr/lib/apache2/modules/libphp5.6.so(zif_call_user_func+0x6a)[0x7fcdaa84e33a]
    /usr/lib/php/20131226/xdebug.so(xdebug_execute_internal+0x174)[0x7fcda1cf7d94]
    /usr/lib/apache2/modules/libphp5.6.so(+0x305a07)[0x7fcdaa9c6a07]

Memory map attached

experienced with libapache2-mod-php5.6 5.6.27-1+deb.sury.org~yakkety+1

**Comment by oerdnj** [comment]
Could you disable xdebug and try if that happens again? Also installing debugging symbols and getting full gdb backtrace would be helpful (https://github.com/oerdnj/deb.sury.org/wiki/Debugging-symbols)

**Comment by oerdnj** [comment]
No additional info has been received, closing.
