### ISSUE TITLE
php-mysqlnd-ms with PHP 5.6?

### ISSUE THREAD

**Issue by swarrenzimconet** [oerdnj/deb.sury.org#486]
We're switching from ppa:ondrej/php5-5.6 to ppa:ondrej/php on our Trusty hosts and we can't get php-mysqlnd-ms to install with PHP 5.6.  

Apt-cache lists three packages:

```apt-cache search php | grep mysqlnd
php5-mysqlnd - MySQL module for php5 (Native Driver)
php5-mysqlnd-ms - MySQL replication and load balancing module for PHP
php-mysqlnd-ms - MySQL replication and load balancing module for PHP 
```

The first two (based on `apt-cache showpkg`) are from the Trusty repository and the third one is from your repository.  

When I attempt to install the php-mysqlnd-ms package it appears to be matched up with PHP 5.5:

```sudo apt-get install php-mysqlnd-ms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  php5.5-mysql
The following NEW packages will be installed:
  php-mysqlnd-ms php5.5-mysql
0 upgraded, 2 newly installed, 0 to remove and 49 not upgraded.
Need to get 228 kB of archives.
After this operation, 978 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

I did try installing it and it only setup files for 5.5:

```Setting up php5.5-mysql (5.5.38-4+deb.sury.org~trusty+1) ...

Creating config file /etc/php/5.5/mods-available/mysql.ini with new version

Creating config file /etc/php/5.5/mods-available/mysqlnd.ini with new version

Creating config file /etc/php/5.5/mods-available/mysqli.ini with new version

Creating config file /etc/php/5.5/mods-available/pdo_mysql.ini with new version
Setting up php-mysqlnd-ms (1.6.0-2+donate.sury.org~trusty+2) ...
```

Is there something I can do to get this working?

Thanks for all your work!

**Comment by oerdnj** [comment]
As far as I remember mysqlnd_ms doesn't support PHP 5.6

**Comment by swarrenzimconet** [comment]
@oerdnj We have it installed on a couple servers right now which we initially setup using ppa:ondrej/php5-5.6.

    apt-cache showpkg php5-mysqlnd-ms
    Package: php5-mysqlnd-ms
    Versions: 
    1.6.0-1+deb.sury.org~trusty+4 (/var/lib/apt/lists/ppa.launchpad.net_ondrej_php5-5.6_ubuntu_dists_trusty_main_binary-amd64_Packages) (/var/lib/dpkg/status)
     Description Language: 
                     File: /var/lib/apt/lists/mirror.rackspace.com_ubuntu_dists_trusty_universe_binary-amd64_Packages
                      MD5: f753221ffb5c9d5b0fbb7a86b21e1f5e
     Description Language: en
                     File: /var/lib/apt/lists/mirror.rackspace.com_ubuntu_dists_trusty_universe_i18n_Translation-en
                      MD5: f753221ffb5c9d5b0fbb7a86b21e1f5e

    1.5.2-3build1 (/var/lib/apt/lists/mirror.rackspace.com_ubuntu_dists_trusty_universe_binary-amd64_Packages)
     Description Language: 
                     File: /var/lib/apt/lists/mirror.rackspace.com_ubuntu_dists_trusty_universe_binary-amd64_Packages
                      MD5: f753221ffb5c9d5b0fbb7a86b21e1f5e
     Description Language: en
                     File: /var/lib/apt/lists/mirror.rackspace.com_ubuntu_dists_trusty_universe_i18n_Translation-en
                      MD5: f753221ffb5c9d5b0fbb7a86b21e1f5e


    Reverse Depends: 
      php5-mysqlnd-ms:i386,php5-mysqlnd-ms
      php5-mysqlnd-ms:i386,php5-mysqlnd-ms
    Dependencies: 
    1.6.0-1+deb.sury.org~trusty+4 - libc6 (2 2.14) phpapi-20131226 (0 (null)) php5-mysqlnd (0 (null)) php5-mysqlnd-ms:i386 (0 (null)) 
    1.5.2-3build1 - libc6 (2 2.14) phpapi-20121212 (0 (null)) php5-mysqlnd (0 (null)) php5-mysqlnd-ms:i386 (0 (null)) 
    Provides: 
    1.6.0-1+deb.sury.org~trusty+4 - 
    1.5.2-3build1 - 
    Reverse Provides: 

The PHP guide also says "PHP 5.3.6 or newer. Some advanced functionality requires PHP 5.4.0 or newer."  (<http://php.net/manual/en/mysqlnd-ms.requirements.php>)

**Comment by oerdnj** [comment]
I have checked my old php-mysqlnd-ms package and there was a patch pulled from SVN to get a PHP 5.6 support, this has now been applied to the ppa:ondrej/php as well in `php-mysqlnd-ms - 1.6.0+svn333622-1+deb.sury.org~<dist>+1`

**Comment by swarrenzimconet** [comment]
Thanks!
