### ISSUE TITLE
Unable to load dynamic library '/usr/lib/php/20151012/mysql.so'

### ISSUE THREAD

**Issue by ChrisWiegman** [oerdnj/deb.sury.org#488]
When installing PHP7.0-mysql on Ubuntu 16.04 I receive the following error on all subsequent PHP commands.

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysql.so' - /usr/lib/php/20151012/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0`

**Comment by oerdnj** [comment]
There's no mysql module for PHP 7.0

**Comment by ChrisWiegman** [comment]
I realize this but installing the package php7.0-mysql from your repository is the only way to get get the  available mysql libraries yet doing so throws this error as it is trying to install the standard mysql library as well.

**Comment by oerdnj** [comment]
In that case, something fishy is going on in the helper. It should ignore the non-existent extensions. I'll look into it. Any prior packages you had installed before install `php7.0-mysql`.

**Comment by ChrisWiegman** [comment]
No, nothing prior. In fact I did a fresh install of Ubuntu 16.04 and attempted to install php7 with php7.0-mysql.

**Comment by oerdnj** [comment]
`phpdismod mysql` should get rid of that message meanwhile.

**Comment by ChrisWiegman** [comment]
Yes, I've got it working doing that for now. I use this package in https://github.com/ChrisWiegman/Primary-Vagrant so getting all to do it there is a trickier challenge. Thanks for looking into it.

**Comment by oerdnj** [comment]
Ok, I did look into this and I am quite sure it's the provisioning you are using that's causing the problems. The package doesn't enable mysql.so module by default.
