### ISSUE TITLE
PHP 5.6 404

### ISSUE THREAD

**Issue by wilkinsocks** [oerdnj/deb.sury.org#49]
When I try to update my packages list, I get the following output:

W: Failed to fetch http://ppa.launchpad.net/ondrej/ppa/ubuntu/dists/precise/main                                                                                        /source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ondrej/ppa/ubuntu/dists/precise/main                                                                                        /binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ondrej/ppa/ubuntu/dists/precise/main                                                                                        /binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used                                                                                         instead.

Also there is no precise directory when going to http://ppa.launchpad.net/ondrej/ppa/ubuntu/dists/ 

I am using Ubuntu 12.04 LTS

**Comment by oerdnj** [comment]
How did you add the ppa?

And what is in /etc/apt/sources.list.d/?

O.

**Comment by wilkinsocks** [comment]
I used the following commands:

sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get update

In  /etc/apt/sources.list.d/ there is: 
ondrej-ppa-precise.list
ondrej-ppa-precise.list.save
.swp

**Comment by oerdnj** [comment]
And the contents of ondrej-ppa-precise.list is? Because it doesn't look like ppa:ondrej/php5-5.6, but just the contents should include php5-5.6, e.g. something based on http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/

I think it's error on your side, perhaps you did add-apt-repository ppa:ondrej ?

**Comment by wilkinsocks** [comment]
Yes, sorry, just removed and tried again and it seems to be correct now!
Cheers.
