### ISSUE TITLE
5.6 cli overritten with 7 after every update

### ISSUE THREAD

**Issue by RonCollins** [oerdnj/deb.sury.org#490]
Every time I update php packages, my php cli reverts to version 7 and I have to run this to switch it back:

`sudo ln -sfn /usr/bin/php5.6 /etc/alternatives/php`

The apache version of php is unaffected (5.6).

I'm running it on Ubuntu 14.04.

Please let me know if I can provide any further details.

**Comment by oerdnj** [comment]
Then do it properly with update-alternatives instead of manual symlink

**Comment by RonCollins** [comment]
whoa. thanks. the instructions I followed to install didn't include this and I never new how the alternatives system worked. now I do. thanks. and thanks for the amazing repo.

**Comment by oerdnj** [comment]
There a paragraph on this in the migration guide: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#explaining-php-pear-dependency

**Comment by RonCollins** [comment]
I must have missed that the first time I read through it. I also just wanted to thank you for updating this http://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04
which is where I had been working from. I tried to comment but I don't have enough reputation yet :)
