### ISSUE TITLE
ZTS Builds?

### ISSUE THREAD

**Issue by karbowiak** [oerdnj/deb.sury.org#491]
Hi there!

Any chance of getting the ZTS builds back for php7 ? :)

If not, any chance of some hints in regards to how to build the .deb packages ourselves (with the php7.0-zts-* tag so as to not overwrite regular php7.0)

Thanks :)

**Comment by oerdnj** [comment]
Unfortunately if you combine my lack of time and little motivation, it's not likely to happen unless somebody contributes either functional patches or funds the development.

Rebase `master-7.0-zts` branch on top of `master-7.0` branch and fix the bug in `debian/rules` that prevents the package from building.

As a next step to have this really viable the whole thing needs to be integrated so the master-7.0 branch builds non-zts and zts packages in one build step. Which is achievable, but it would require a substantial amount of my time to do it properly.

**Comment by Stricted** [comment]
i rebuilded the dotdeb php7.0 with zts myself, the same should work here
```
apt-get build-dep php7.1
mkdir ~/php7-armhf; cd ~/php7-armhf
apt-get source php7.1
cd php7.1-7.1.1
sed sed -i -e 's/php7.1/php7.1-zts/g' debian/changelog
sed sed -i -e 's/php7.1/php7.1-zts/g' debian/control
export DEB_BUILD_OPTIONS=parallel=2
dpkg-buildpackage -b -uc -us
```

i let this run right now on my banana pi (need the zts version for pthreads)

**Comment by oerdnj** [comment]
dup of #327
