### ISSUE TITLE
php-ssh2 broken in PHP 7.0.13

### ISSUE THREAD

**Issue by marius-wieschollek** [oerdnj/deb.sury.org#492]
It seems like the update to PHP 7.0.13 breaks the php-ssh2 module. After installing the update, using the ssh2:// wrapper does not work anymore and methods like "ssh2_scp_recv" will report that the ssh2 session is not valid.

After a little bit of research i found this conversation https://forum.remirepo.net/viewtopic.php?id=3509.
It seems like a security patch broke the module and there is a patch available.

could you take a look at this?

**Comment by oerdnj** [comment]
Fixed in `php-ssh2_1.0+0.13-2+deb.sury.org~<dist>+1` that I have just uploaded.

**Comment by marius-wieschollek** [comment]
It works again. Thank you!
