### ISSUE TITLE
[feature request]Module php5-radius missing

### ISSUE THREAD

**Issue by PatrickM73** [oerdnj/deb.sury.org#50]
First i would like to thank you for the great work, the availability of backported packages helps a lot.
Sadly i'm missing the php5-radius module which is essential to update our moodle Servers which run on Ubuntu 12.04 LTS and authenticate against Radius. 

It would be great if you could add this module.

Sincerely Patrick

**Comment by oerdnj** [comment]
Hi, I took over php5-radius maintainership in Debian (that's why it took a tad bit longer) and those new packages have been uploaded to php5 and php5-5.6 PPAs.
