### ISSUE TITLE
augeas lense not working with new config structure

### ISSUE THREAD

**Issue by dol** [oerdnj/deb.sury.org#500]
Augeas is a configuration editing tool. It's also used in combination of Puppet. The new PHP configuration structure is not compatible with the current augeas lense for PHP.
E.g:
https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/augeas/wily/view/head:/lenses/php.aug#L49

The new folder structure adds one level to the tree. The PHP augeas lense won't detect the PHP config files out of the box.

A possible solution would be providing an slightly altered php.aug file saved under /usr/share/augeas/lenses under a new name. Even if augeas not installed.
libvirt-bin e.g. is providing a lense file => https://packages.debian.org/wheezy/sparc/libvirt-bin/filelist => libvirtd.aug

**Comment by gjuric** [comment]
Maybe you should file this issue with the Augeas project. The file in question is here https://github.com/hercules-team/augeas/blob/master/lenses/php.aug and the fastest way would probably be to provide them with a pull request.

**Comment by oerdnj** [comment]
That's a bug in Augeas, not here.
