### ISSUE TITLE
mysql 5.5 on xenial still has dependency issues

### ISSUE THREAD

**Issue by vain** [oerdnj/deb.sury.org#501]
Upon installing mysql-server-5.5 on Ubuntu 16.04, we still get this dependency error:

	root@ubuntu1604lts:~# apt install mysql-server-5.5
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 mysql-server-5.5 : PreDepends: mysql-common (>= 5.5) but it is not going to be installed
						Depends: mysql-client-5.5 (>= 5.5.51-1+deb.sury.org~xenial+1) but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.

This was already reported in #357.

Any advice? :)

**Comment by oerdnj** [comment]
I am probably going to drop MySQL 5.5 at all, as backporting/forwardporting is really hell.

**Comment by oerdnj** [comment]
As I don't really have time to properly maintain neither MySQL nor MariaDB, I have deprecated the repositories.
