### ISSUE TITLE
php-imagick missing HAVE_MAGICKSETIMAGEINTERPOLATEMETHOD

### ISSUE THREAD

**Issue by Zorlin** [oerdnj/deb.sury.org#503]
Hi there,

We recently upgraded to php-imagick 3.4.3RC, and immediately began seeing errors in imagick on our Magento sites.

Quote from our internal discussion:
"I've checked source code of new Imagick in order to see what are changes because there are no recent mention of setImageInterpolateMethod modification. I've discovered that they have placed IF directive HAVE_MAGICKSETIMAGEINTERPOLATEMETHOD which is used to determine should setImageInterpolateMethod() be included in library after compilation.
It seems like provided precompiled library doesn't have HAVE_MAGICKSETIMAGEINTERPOLATEMETHOD set to TRUE, which I have checked in Imagick 3.4.3RC1 on dev server.
There is no quick fix, what we have to do is to download https://github.com/mkoppanen/imagick/tree/3.4.3RC1 and manually recompile whole package by providing HAVE_MAGICKSETIMAGEINTERPOLATEMETHOD parameter"

Please advise on next steps - for now we had to disable features and downgrade to an earlier php-imagick package.

**Comment by oerdnj** [comment]
I have looked into this and I haven't find any documentation on the HAVE_MAGICKSETIMAGEINTERPOLATEMETHOD. Could you provide any pointers?

Also when you are talking about "library", do you mean PHP extension or imagemagick library that is also provided from the repository?

**Comment by Zorlin** [comment]
Hi @oerdnj,

Here is some more details, hopefully this helps.

First off, when we're talking about the library I mean php-imagick not imagemagick itself.

We started getting these errors in Magento - here's the start of a stack trace (I can provide the full one if needed):

```
Stack trace
E_ERROR: Call to undefined method Imagick::setimageinterpolatemethod()
in Varien_Image_Adapter_Imagemagic::resize called at /home/redacted/www/app/code/local/Varien/Image/Adapter/Imagemagic.php (139)
```

This occurred only on servers with version 3.4.3RC of the php-imagick library - those with 3.4.2 were unaffected. 

One of our devs attached this screenshot, of a few places in the code this #ifdef appears:

http://i.imgur.com/FdzcvYv.png

It should hopefully just be a matter of adding that as a parameter while compiling the module.

**Comment by oerdnj** [comment]
I see now. Adding the define would be wrong way to fix it.

The `HAVE_` should be defined by `PHP_CHECK_FUNC(MagickSetImageInterpolateMethod)` call from config.m4. I'll have to check what that fails.

**Comment by oerdnj** [comment]
So, after debugging this for a while - this is a bug in php-imagemagick: https://github.com/mkoppanen/imagick/pull/191

I have fixed this in the package and I will upload it shortly.

**Comment by Zorlin** [comment]
@oerdnj Excellent! Thank you so much! 👍
