### ISSUE TITLE
segfault with php 5.6

### ISSUE THREAD

**Issue by ang3lx** [oerdnj/deb.sury.org#504]
hello,
I've this problem only with 5.6 version (nginx webserver) that cause error in log
is this a bug of this release of php5.6? (i've 7.0 too and it works well)

Dec  9 16:12:01 s02 kernel: [  155.212182] php-fpm5.6[24318]: segfault at 7efd2a11eab0 ip 00007efd469d1410 sp 00007ffc343c1048 error 4 in libc-2.23.so[7efd46884000+1bf000]

**Comment by oerdnj** [comment]
You need to install `php5.6-fpm-dbgsym` and dbgsym packages for all the modules you are using: https://github.com/oerdnj/deb.sury.org/wiki/Debugging-symbols, then produce a coredump and provide a full backtrace - run `bt full` from `gdb /usr/bin/php-fpm5.6 <coredump>`.

The PHP code is definitely far from perfect and crashes happen from time to time.

Also providing a versions of packages would be very helpful...

After you have all this information - fill a bug in bugs.php.net as this is a crash related to upstream PHP and not to packaging.

**Comment by ang3lx** [comment]
I think that i've resolved
i've removed php-xcache, restarted php5.6-fpm and now seems to work fine!
no kernel error

ps: my system is ubuntu 16.04 
Software server nginx/1.10.0
PHP version 5.6.29-1+deb.sury.org~xenial+1
