### ISSUE TITLE
No sybase_connect() function

### ISSUE THREAD

**Issue by fwolf** [oerdnj/deb.sury.org#508]
Function sybase_connect() was removed in PHP7, but in this php5.6, there already has no this method ?

I'm using legacy [ADODb](https://github.com/ADOdb/ADOdb) （With Sybase db）, there is code like:

```php
    if (!function_exists('sybase_connect')) return null;
```

So it need this function to work probably.

**Comment by oerdnj** [comment]
Should be available (`mssql.so` extension) as of now.

**Comment by fwolf** [comment]
Thanks !
