### ISSUE TITLE
Build of Apache2 on ppa:ondrej/apache2 does not support CHACHA20 or other modern ciphers

### ISSUE THREAD

**Issue by ghost** [oerdnj/deb.sury.org#511]
Figured this was worth opening an issue about - the build of Apache2 on this PPA was likely compiled against an older OpenSSL version because it doesn't support CHACHA20 ciphers, x25519 curves, and a few other misc modern ciphers. They can be added to the CipherSuite, but won't be passed or used by OpenSSL regardless, even if the version of OpenSSL used supports them; I've tested with OpenSSL 1.1.0c and 1.1.1-dev on my Ubuntu 14.04 server to no avail.

It would be very nice if we could get an "update" with an Apache2 2.4.23 compiled against OpenSSL 1.1.0c or newer so we could support these ciphers; compiling against OpenSSL 1.1.0c shouldn't break OpenSSL 1.0.2 support or anything.

**Comment by oerdnj** [comment]
As far as I know apache 2.4.23 doesn't support OpenSSL 1.1 without external patches, and the work is still ongoing to get the support into Apache2.

I will be happy to provide Apache2 version with modern ciphers once the support will be released in upstream version.

**Comment by oerdnj** [comment]
JFTR While I support the adoption of modern curves and latin dances by djb, there has been no breakthrough in cryptography that would call for an immediate action.

That applies to #493 as well.

**Comment by Vilican** [comment]
> As far as I know apache 2.4.23 doesn't support OpenSSL 1.1 without external patches, and the work is still ongoing to get the support into Apache2.

It supports now:

> Changes with Apache 2.4.26
>   *) mod_ssl: Add support for OpenSSL 1.1.0. [Rainer Jung]

Could you please compile Apache 2.4.26 against the new OpenSSL 1.1.0f?

Thank you

**Comment by oerdnj** [comment]
It has been done now.
