### ISSUE TITLE
Debug symbols are missing for php7.1-fpm ( and others )

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#512]
#Sources:
```
(root:php7)➜  www  cat /etc/apt/sources.list.d/packages.sury.org.list | grep debug
deb http://packages.sury.org/php/ jessie main/debug
``` 

php7.1-fpm-dbgsym not found
```
(root:php7)➜  (root:php7)➜  www  apt-cache search php7.1-fpm-dbgsym
```

While php7.0-fpm-dbgsym is there

```
apt-cache search php7.0-fpm-dbgsym
php7.0-fpm-dbgsym - Debug symbols for php7.0-fpm
```

**Comment by oerdnj** [comment]
I have updated dpkg recently between PHP 7.1 (before) and PHP 7.0 (after) builds. So that might explain it. Could you wait for next PHP 7.1 release?

**Comment by EugenMayer** [comment]
If any possible, i would love to have those. The problem is, i update to php7.1 and now, the session handling is broken, session_destroy_sid is never called. I cannot debug it using a PHP ide, i have to see where it goes from  https://github.com/php/php-src/blob/master/ext/session/session.c#L153 here - i cannot also try to reproduce it in php7.0, since it works there.

I blocked,  seriously. Sorry  ;/

**Comment by oerdnj** [comment]
Ok, I fired rebuild of php 7.1 (and 5.6) to get the debug symbols installed.

**Comment by EugenMayer** [comment]
You are my superman! Thank you sir!

**Comment by EugenMayer** [comment]
Thank you sir!

**Comment by oerdnj** [comment]
Does it work now (too lazy to check myself when you already have verified setup :))?

**Comment by EugenMayer** [comment]
You really need a docker/packer or chef/test-kitchen ci to test your stuff :)

I would be fairly easy to run with chef/test-kitchen and inspec. Are you particularly interested in such - might try to contribute this. (i will open a different issue for discussion if you are in on this).

For the issue:
```
(root:php7)➜  www  apt-cache search php7.1-fpm
php7.1-cgi - server-side, HTML-embedded scripting language (CGI binary)
php7.1-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.1-fpm-dbgsym - Debug symbols for php7.1-fpm
```
Yes, all there! Thank you a lot

**Comment by oerdnj** [comment]
Thanks for the confirmation.

**Comment by Gamesh** [comment]
Can we reopen this as there are no debug symbols for PHP 7.1.4 or PHP 7.1.5?

**Comment by oerdnj** [comment]
I think I have actually solved this in the last build that's still running:
https://howl.labs.nic.cz/jenkins/view/PHP-binaries/job/php_php5.6-binaries/41/
https://howl.labs.nic.cz/jenkins/view/PHP-binaries/job/php_php7.0-binaries/37/
https://howl.labs.nic.cz/jenkins/view/PHP-binaries/job/php_php7.1-binaries/23/

**Comment by oerdnj** [comment]
Ok, couple of builds later:
```
php7.0-fpm-dbgsym:
  Installed: (none)
  Candidate: 7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9
  Version table:
     7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9 0
        500 http://packages.sury.org/php/ jessie/main amd64 Packages
php7.0-fpm:
  Installed: (none)
  Candidate: 7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9
  Version table:
     7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9 0
        500 http://packages.sury.org/php/ jessie/main amd64 Packages
```

**Comment by oerdnj** [comment]
The PHP 7.1 is still building.

**Comment by Gamesh** [comment]
got everything installed as needed. @oerdnj thank you very much for support and quick response

**Comment by twobombs** [comment]
reopened: current 7.1-fpm release also looks like it doesn't have dbg symbols:
<img width="863" alt="Screenshot 2019-06-25 at 16 18 58" src="https://user-images.githubusercontent.com/12692227/60106231-5f188400-9754-11e9-849c-fb288682c462.png">

**Comment by oerdnj** [comment]
Well, @twobombs, how can you tell that from `php -v` output?  You actually need to install the debug symbols from a separate package.
