### ISSUE TITLE
PHP 5.6 packages removed or relocated?

### ISSUE THREAD

**Issue by nplowman** [oerdnj/deb.sury.org#513]
Hi, we are using the PHP 5.6 packages as part of our build process. We have just recently started getting 404 errors.

```
W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
```

Have these packages been relocated or removed?

**Comment by oerdnj** [comment]
If "recently" is end of October, then yes. https://www.patreon.com/posts/now-is-time-to-7009050
