### ISSUE TITLE
[PHP-IGBINARY] Missing version 2.0.0

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [oerdnj/deb.sury.org#515]
Analyzing #507 I've noticed that the version of the igbinary extension is "1.2.2-dev" instead of the 7.0+ compatible 2.0.

This package is a dependency of (at least) php7.1-redis (and possibly the memcache(d) extension too).

Could you please add version 2.0 for igbinary to the repository? Thanks in advance!
Changelog is here: https://pecl.php.net/package-changelog.php?package=igbinary

**Comment by oerdnj** [comment]
The repository has: `php-igbinary - 2.0.1-1+deb.sury.org~<repo>+1` ?

**Comment by oerdnj** [comment]
Or what repository are you talking about?

**Comment by MatthiasKuehneEllerhold** [comment]
I'm using a debian jessie docker container with this install script:
```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y curl
echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/ondrej-sury.list
curl -sS https://packages.sury.org/php/apt.gpg | apt-key add -
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install php7.1-cli php7.1-curl php7.1-intl php7.1-redis php7.1-mysql php7.1-sqlite php7.1-xml php7.1-dom php7.1-mbstring php7.1-gd sudo
```

After that I get this:
```
$ php -i | grep igbinary
/etc/php/7.1/cli/conf.d/20-igbinary.ini,
igbinary
igbinary support => enabled
igbinary version => 1.2.2-dev
```

Is there any way to enforce installing the 2.0 version instead of the old 1.2.2?

**Comment by MatthiasKuehneEllerhold** [comment]
Well... I've just rebuild the container and now I get version 2.0.1. Sorry for this!

**Comment by oerdnj** [comment]
No, that was fault at my side. I realized you might be talking about jessie, and I fired up the rebuild right after I asked you the question :).

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks :)
