### ISSUE TITLE
please update php-redis to 3.1.1

### ISSUE THREAD

**Issue by BlackIkeEagle** [oerdnj/deb.sury.org#516]
the current php-redis package breaks sessions, 3.1.1 fixes that

thanks

**Comment by oerdnj** [comment]
There's no 3.1.1 release yet, only 3.1.1RC1.

**Comment by oerdnj** [comment]
Is this the commit about the sessions? https://github.com/phpredis/phpredis/commit/18c7ab007649f068075880984e59938b849b5ab5

**Comment by BlackIkeEagle** [comment]
I did not really check, just thought they released it because of this tweet: https://twitter.com/grumi78/status/811734440573485056

And I see its 3.1.1-RC1

Anyway If you are using redis for your sessions 3.1.0 is completely broken

**Comment by BlackIkeEagle** [comment]
we have the exact same issue as described here: http://www.dragonbe.com/2016/12/sessions-in-php-71-and-redis.html?update-20161222

**Comment by BlackIkeEagle** [comment]
The commit and issue you are talking about are correct

https://github.com/phpredis/phpredis/issues/1062

**Comment by oerdnj** [comment]
`php-redis_3.1.0-2*` should contain the selected fix.

**Comment by BlackIkeEagle** [comment]
Thank you very much, really appreciate the effort
