### ISSUE TITLE
Stability of php-redis > 3.0.0

### ISSUE THREAD

**Issue by baurmatt** [oerdnj/deb.sury.org#517]
After upgrading php-redis to anything greater than 3.0.0 we realized that it totally unstable. See https://github.com/phpredis/phpredis/issues/1076

Is there an option to get 3.0.0 back into the repository to at least have the option to downgrade and pin the extension?

**Comment by ajbonner** [comment]
They've got a working fix for the issues reported there https://github.com/phpredis/phpredis/issues/1076 which should land shortly, so the stability issues ought to 'go away' with RC2.

**Comment by oerdnj** [comment]
`php-redis_3.1.1~rc1-2...` has a patch that should fix the issue. I have just uploaded this version.
