### ISSUE TITLE
Add amqp and riak extensions

### ISSUE THREAD

**Issue by robocoder** [oerdnj/deb.sury.org#518]
* https://pecl.php.net/package/amqp
* https://pecl.php.net/package/riak

**Comment by oerdnj** [comment]
amqp is already available

**Comment by oerdnj** [comment]
And I am not very keen on packaging PECL extension that was last updated two years ago and not available for PHP 7.x. You can always either `pecl install riak` or install it from upstream github: https://github.com/php-riak/php_riak
