### ISSUE TITLE
Wiki page PPA-migration-to-ppa:ondrej-php needs updating to assume people want to use latest version

### ISSUE THREAD

**Issue by mvl22** [oerdnj/deb.sury.org#519]
The very useful wiki page at:

https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php

comes up top in a lot of search engine hits for migrating from the old setup to the new multi-installation PHP which enables PHP 7.1 to be installed.

However, the examples and documentation given talk about old versions (5.6, 7.0, and so on) which new installations should obviously avoid.

It would be useful (and reduce confusion) to have this updated so that it directly provides the most relevant use-case, i.e. 7.1 at present.

**Comment by oerdnj** [comment]
Hint: you (and anybody with github account) can edit the wiki ;)

**Comment by mvl22** [comment]
> Hint: you (and anybody with github account) can edit the wiki ;)

I should have added that I would not feel confident in making the changes correctly.

**Comment by oerdnj** [comment]
Feel free to just propose changes and I'll review them. This way it would be much faster...

**Comment by oerdnj** [comment]
A patch to MD source would be fine.

**Comment by mvl22** [comment]
OK - will try to do so once I've tried out some installs on some fresh VMs, as I can't experiment on live servers to make sure I'm doing the right thing.

PS May I take this opportunity to thank you for these releases - it is excellent work.

**Comment by oerdnj** [comment]
Replaced all 7.0 to 7.1
