### ISSUE TITLE
Adding suhosin extension to the repo?

### ISSUE THREAD

**Issue by tabacco** [oerdnj/deb.sury.org#52]
Any chance you could add the suhosin extension to the repo? It has some handy security stuff (like allowing the disabling of /e in preg_replace): https://suhosin.org/stories/index.html

They also provide a very friendly build script which may or may not save time.

**Comment by oerdnj** [comment]
Sorry, not a chance. 

O. 

On March 16, 2015 11:03:52 PM GMT+01:00, Doug Tabacco <notifications@github.com> wrote:
>Any chance you could add the suhosin extension to the repo? It has some
>handy security stuff (like allowing the disabling of /e in
>preg_replace): https://suhosin.org/stories/index.html
>
>They also provide a very friendly build script which may or may not
>save time.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
