### ISSUE TITLE
Prevent auto upgrading to php7.1

### ISSUE THREAD

**Issue by ram108** [oerdnj/deb.sury.org#520]
I have php-fpm (7.0) installed on Ubuntu 16.04 system and today I was forced to upgrade to php7.1. Last version of php is not fully support by mostly CMS and will get at least errors and warnings.

How to prevent auto upgrading to php7.1? And if upgraded already how to return to php7.0?

**Comment by syphernl** [comment]
Same applies on 14.04. For some reason PHP 7.1 gets installed alongside the already installed version. 

Since this particular machine is running PHP 5.6 due to upgrade/version limitations it definitely shouldn't upgrade to 7.1 all of a sudden. Luckily `php -v` still shows 5.6 and PHP-FPM is still running for that particular version. 

This seems to be caused by the upgrade of `php-xml` which went from 7.0 to 7.1 on another server.

**Comment by oerdnj** [comment]
The `php-fpm` package description says:

> This package is a dependency package, which depends on default PHP version (currently 7.1). 

Just install `phpX.Y-fpm` if you don't want to follow latest stable PHP version.

**Comment by oerdnj** [comment]
For `php7.1-cli`, see https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php70-cli-always-installed

**Comment by syphernl** [comment]
@oerdnj I am installing `php-fpm` the "right" way, however my 5.6 (and 7.0) instances suddenly received the 7.1 version of php-xml (which was installed as a dependency, not manually).

**Comment by oerdnj** [comment]
For `php-xml` apply same logic, e.g. install `phpX.Y-xml`.

**Comment by oerdnj** [comment]
@syphernl This is too theoretical. What's your exact `apt-get install` line?

**Comment by oerdnj** [comment]
And how does initial output from `apt-get` looks like (the one where it lists the packages to be installed).

**Comment by syphernl** [comment]
I have no access to the actual install line since that is being done by our configuration management software. 

I have however verified that we are explicitly referring to `php5.6-xml` and/or `php7.0-xml` and not to the pseudo package `php-xml`. For other packages (redis, xdebug, pear) it seems like we can however still refer to the `phpX.Y` equivalent 

```
root@server:~# apt-cache showpkg php7.1-xdebug
Package: php7.1-xdebug
Versions: 

Reverse Depends: 
Dependencies: 
Provides: 
Reverse Provides: 
php-xdebug 2.5.0-1+deb.sury.org~trusty+1
```

**Comment by oerdnj** [comment]
So, do you at least have a log or something? Most probably this is getting pulled by something like `php-json`, and you just need to add `phpX.Y-json` to the list of the packages to hint the dependency resolver.

**Comment by oerdnj** [comment]
Oh, and if you install `php-pear` this will always pull `php-cli` (and thus `php7.1-cli`): https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#explaining-php-pear-dependency

**Comment by ram108** [comment]
I have the same situation, all my packages controlled by Server software (ISPmanager) and I have no choice to install php7.0-fpm as ISPmanager install default Ubuntu php-fpm package and dont know anything about php7.0-fpm.

But now php-fpm is an alias of php7.1-fpm.

If I remove php-fpm to install php7.0-fpm manual all my sites and settings in will be removed in ISPmanager too. And I will not be able to restore it in ISPmanager as no php-fpm package installed on system.

**Comment by oerdnj** [comment]
@ram108 You should ask your ISPmanager provider to fix that.

**Comment by oerdnj** [comment]
JFTR the change was announced before here: https://www.patreon.com/posts/php-7-1-to-be-2-7473428 and also notified on twitter: https://twitter.com/debsuryorg

**Comment by daniejstriata** [comment]
I tried to do the following to stay on version 7.0 which did not work. When I run "apt upgrade" afterwards it would change to 7.1.

What is the correct way to stay on 7.0? Should I uninstall 7.0 and reinstall with 7.0 as I've done below? 

#apt install libapache2-mod-php7.0 php7.0 php7.0-curl php7.0-fpm php7.0-xml
libapache2-mod-php7.0 is already the newest version (7.0.14-2+deb.sury.org~xenial+1).
php7.0-fpm is already the newest version (7.0.14-2+deb.sury.org~xenial+1).
php7.0-fpm set to manually installed.
php7.0-curl is already the newest version (7.0.14-2+deb.sury.org~xenial+1).
php7.0-curl set to manually installed.
php7.0 is already the newest version (7.0.14-2+deb.sury.org~xenial+1).
php7.0 set to manually installed.
php7.0-xml is already the newest version (7.0.14-2+deb.sury.org~xenial+1).
php7.0-xml set to manually installed.
