### ISSUE TITLE
php7.0-dev package installs php7.1 libraries

### ISSUE THREAD

**Issue by Motoma** [oerdnj/deb.sury.org#521]
Hi there,

The `php7.0-dev` package depends on `php-xml`, which will happily resolve to `php7.1-xml` if it hasn't been satisfied. I believe the package should depend on `php7.0-xml` instead.

Cheers,
Chris

**Comment by oerdnj** [comment]
`php7.0-dev` does not depend on `php-xml`, you are most likely bumping into: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php70-cli-always-installed

**Comment by Motoma** [comment]
My mistake, thanks for the quick reply.
