### ISSUE TITLE
No PHP 5.6.29 packages for Debian Stretch?

### ISSUE THREAD

**Issue by pesselbach** [oerdnj/deb.sury.org#523]
Are there no longer PHP 5.6.x packages for Debian Stretch? I just noticed that the last released version is PHP 5.6.27.

**Comment by oerdnj** [comment]
Well, unfortunately yes. PHP 5.6 can't be compiled with OpenSSL 1.1 and I haven't found solution for that yet as that's the default for Debian stretch now. I might have to disable OpenSSL module or something like that.

**Comment by pesselbach** [comment]
Thanks for the info. I guess in the worse case there is still Debian 8 or Ubuntu 16.04 LTS for PHP 5.6 support.

**Comment by zsalab** [comment]
Patches to compile php 5.6.30 on Debian 9 (with OpenSSQL 1.1):
https://zettasystem.com/0053-z-curl-easy-check.patch
https://zettasystem.com/0053-z-libssl-1.1-compatibility.patch

**Comment by oerdnj** [comment]
Cool! Thanks, I'll take a look.

**Comment by zsalab** [comment]
Please let me know if you find any problem whit this patches, I've just created my first version today, I used the jessie version of PHP5.6 from deb.sury.org and patched, looks compile and works fine (but it is a huge patch, so maybe it has some issues).... I will try to send a pull request to the official PHP repo too....
I haven't tested compile the patched PHP with OpenSSL 1.0.x but it should work.

**Comment by oerdnj** [comment]
@zsalab So far, the Jessie builds are OK, so it does compile with OpenSSL 1.0.x. And the Debian Stretch test build went through as well, so the packages should be available as soon as this build: https://howl.labs.nic.cz/jenkins/view/PHP-binaries/job/php_php5.6-binaries/28/ finishes.

**Comment by oerdnj** [comment]
Everything looks fine. Thanks!
