### ISSUE TITLE
libapache2-mod-php7.1 breaks server on reload

### ISSUE THREAD

**Issue by sjackson44** [oerdnj/deb.sury.org#524]
After installing libapache2-mod-php7.1 on our Debian 8.6 64bit version, to work with Apache 2.4.10 something strange happens. Upon entering "systemctl reload apache2" the server stops running, there is no error output, it is just is shown as "inactive (dead)". This is only with the reload command, everything else works. Is there a work around for this?

**Comment by oerdnj** [comment]
You are the only one having this problem so far. I guess there's some combination of either apache2 module or php7.1 modules that's causing the problem.

Remove the extra modules you have installed one-by-one and check what might be causing the problem.

Or use `php7.1-fpm` it's better anyway for privilege separation.

I am closing the bug until more evidence is provided.
