### ISSUE TITLE
php 7.1 problem

### ISSUE THREAD

**Issue by ang3lx** [oerdnj/deb.sury.org#525]
after an update, php 7.1 was automatically installed on server that break all.
I've only 5.6 and 7.0

root@mx-01:~# /usr/bin/php-cgi -v
PHP 7.1.0-5+deb.sury.org~xenial+1 (cgi-fcgi)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

if I try to remove php 7.1 it remove standard php-fpm too
How can solve this problem?

**Comment by oerdnj** [comment]
Duplicate of #520
