### ISSUE TITLE
trap divide error in Zend OpCache

### ISSUE THREAD

**Issue by tdm4** [oerdnj/deb.sury.org#526]
Hi,

  I'm getting a kernel trap divide error in opcache.so:
```
kernel: [ 3308.047213] traps: php-fpm7.1[16876] trap divide error ip:7fb0511cfa53 sp:7ffdf453f210 error:0 in opcache.so[7fb051196000+59000]
```

Running on Ubuntu 14.04, and php7.1 (7.1.0-5+deb.sury.org~trusty+1).
Got php7.1-fpm and opcache installed.

If I disable opcache, problem goes away, but enabled, opcache won't load any pages.

**Comment by oerdnj** [comment]
Hi, you should really report this to upstream bugs.php.net and add URL of upstream bug here for reference.
