### ISSUE TITLE
Latest courier-mta for vivid?

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#53]
Would there be any possibility that courier-0.74.1 could be compiled for vivid?

There is about 5 weeks to go and courier needs testing with systemd and lxc/lxd containers.

**Comment by oerdnj** [comment]
Uploaded and looks it builds (it needed addition of libtool-bin to Build- 
Depends though). 


O. 



On Thu, Mar 19, 2015, at 07:06, Mark Constable wrote: 

> Would there be any possibility that courier-0.74.1 could be compiled for  
> vivid?


> There is about 5 weeks to go and courier needs testing with systemd and  
> lxc/lxd containers.


> —
> Reply to this email directly or view it on GitHub[1].

>

-- 

Ondřej Surý <ondrej@sury.org> 

Knot DNS (https://www.knot-dns.cz/) – a high-performance DNS server 





Links: 


  1. https://github.com/oerdnj/deb.sury.org/issues/53
