### ISSUE TITLE
apache2 module should report same name as used for a2enmod (i.e. php7.1_module)

### ISSUE THREAD

**Issue by robinro** [oerdnj/deb.sury.org#531]
The apache2_module in ansible fails to load the php modules for 7.0 and 7.1 correctly. It uses the output from `apache2ctl -M`, which usually lists the enabled modules as `NAME_module`, when it was enabled using `a2enmod NAME`. For the php7.1 (and 7.0) modules they are listed as `php7_module` in `apache2ctl -M` while a2enmod uses `php7.1`.
Would it be possible to change the name displayed by `apache2ctl -M` to follow the convention of other modules?

There are multiple bug reports about this at ansible, see https://github.com/ansible/ansible/issues/20288 and links there. Using a2query is no option, since it is not available in SUSE, which is supported otherwise.

**Comment by oerdnj** [comment]
It's not possible as they both provide php7 (with only major version as part of module name).
