### ISSUE TITLE
PHP 7.0 upgrade to PHP 7.1

### ISSUE THREAD

**Issue by daniejstriata** [oerdnj/deb.sury.org#532]
Hi,

Currently running PHP 7.0 from the ondrej/php/ubuntu repo.
PHP 7.0.14-2+deb.sury.org~xenial+1 (cli) ( NTS )

We've noticed that if we 'apt update' the system it will upgrade the current PHP 7.0 to 7.1. Is there a way to stay on PHP 7.0 or do you not build new versions of 7.0 anymore and have no issue with replacing 7.0 with 7.1?

**Comment by oerdnj** [comment]
dup of #520
