### ISSUE TITLE
libapache2-mod-php7.1 still breaks on reload.

### ISSUE THREAD

**Issue by sjackson44** [oerdnj/deb.sury.org#535]
After installing libapache2-mod-php7.1 on our Debian 8.6 64bit version, to work with Apache 2.4.10 something strange happens. Upon entering "systemctl reload apache2" the server stops running, there is no error output, it is just is shown as "inactive (dead)". This is only with the reload command, everything else works. Is there a work around for this?

**Comment by oerdnj** [comment]
Dup of #524
