### ISSUE TITLE
Request to package Rspamd

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#536]
Rspamd is a modern highly performant and efficient much needed replacement for spamassassin.

Upstream https://rspamd.com/apt/ has stable 1.4.1 or 1.5.0-0~git191~55f6b60~xenial debs but there are no official Debian packages so it would be fairly simple to build and package as all the work is done. They just need a Debian developer to get the packages into the Debian repos so they could filter down to Ubuntu. Any help appreciated.

**Comment by oerdnj** [comment]
@markc, I am sorry, but I am not taking yet another software I am not using myself.
