### ISSUE TITLE
php7.1-redis package

### ISSUE THREAD

**Issue by f1mishutka** [oerdnj/deb.sury.org#537]
Hi,

I'm migrating from php 7.0 at dotdeb to php 7.1 at packages.sury.org (there is a [suggestion](https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/) from Guillaume Plessis).

And I'm using php7.0-redis in my projects. But there is no php7.1-redis package here :(

Any chances to have it at packages.sury.org?

Thank you.

**Comment by oerdnj** [comment]
I wish you folks could at least try typing `apt-get install php7.1-redis`...

```
$ dpkg --info /home/ondrej/Downloads/php-redis_3.1.1~rc2-1+0~20170118110419.8+jessie~1.gbp11e7ce_amd64.deb  | grep Provides
 Provides: php5.6-redis, php7.0-redis, php7.1-redis
```

**Comment by f1mishutka** [comment]
I'm am really sorry that I missed the fact, that php7.1-redis is in php-redis package.

Thank you for your time!
