### ISSUE TITLE
php 5.6.30 for debian stable

### ISSUE THREAD

**Issue by debianuser69** [oerdnj/deb.sury.org#538]
Why isn't the latest php available to debian jessie users? We shouldn't have to install a 3rd party repo to get the latest security releases in a timely manner from the official php maintainer.

It's been almost 2 weeks.

**Comment by oerdnj** [comment]
I don't respond to anonymous rants

**Comment by debianuser69** [comment]
You are solely responsible for an essential development platform for one of the major branches of linux in the world.  FreeBSD, and most of the other major, professional linux branches, released new binaries within days.  Your own 3rd party repo has 5.6.30 in it.  

Your response to my perfectly REASONABLE query is just to stfu and go away?  Is this what Debian has come to? Do I need to find a new distro for my company's infrastructure?

You didn't even release 5.6.28.  So Debian sat with vulnerable 5.6.27 for months until you released 5.6.29 . Is that a rant? Looks like the truth to me.  If you don't have time to prioritize the project, you should tell the Debian project to find a new maintainer.

I find it awfully suspicious that you already released 5.6.30 for your personal repository (linked to several ways to accept personal donations), and yet the official debian security channel is still behind.

**Comment by oerdnj** [comment]
How much are you willing to pay for my time and security team to rigorously test the PHP packages before they are released to all Debian stable devices? I already know the answer, so just stop throwing accusations if you know nothing about Debian and fuck off.
