### ISSUE TITLE
php-7.x ssh2 package

### ISSUE THREAD

**Issue by drsect0r** [oerdnj/deb.sury.org#539]
We are thinking about migrating from dotdeb.org to sury.org.

We are using https://github.com/gplessis/dotdeb-php/issues/133 in production. Would it be possible to make the same package available?

Thank you.

**Comment by drsect0r** [comment]
Missed a dash

**Comment by drsect0r** [comment]
Maybe this is what I am searching for... https://packages.sury.org/php/pool/main/p/php-ssh2/...

**Comment by oerdnj** [comment]
Yes, this is the package you are looking for.
