### ISSUE TITLE
Update xdebug package

### ISSUE THREAD

**Issue by gries** [oerdnj/deb.sury.org#54]
Hi thanks for maintaining this ppa :)
I'm currently getting the xdebug version: Xdebug v2.2.5 via. this ppa.
Would it be possible to update xdebug to atleast version 2.2.7? I'm currently getting segmentation-faults because of a bug that is fixed in 2.2.7 (http://bugs.xdebug.org/view.php?id=1087)

**Comment by oerdnj** [comment]
Uploaded
