### ISSUE TITLE
7.1 apcu

### ISSUE THREAD

**Issue by splitice** [oerdnj/deb.sury.org#540]
Package Version: Debian Jessie

7.1 apcu is built against 7.0, the error shown is an error with apcu.ini being included in both packages (7.0 php path).

**Comment by oerdnj** [comment]
You haven't posted any error. Would you care to post more information about the problem without your diagnosis?

**Comment by splitice** [comment]
I've already worked around the issue by using PECL to source the package. It's the standard file contained within 2 packages issue. php-acpu tries to put its ini in 7.0 where it already exists in another deb.

**Comment by oerdnj** [comment]
So I presume that you have dotdeb packages installed? I am not responsible for whatever incompatible stuff there is.
