### ISSUE TITLE
Automatically restart php-fpm with systemd if it goes down

### ISSUE THREAD

**Issue by khromov** [oerdnj/deb.sury.org#542]
I had an out-of-memory error on one of my servers today. Most services came back up again thanks to `systemd` but not `php5.6-fpm` and `php7.0-fpm`, which cause sites to be unavailable. with a 502 gateway error message from Nginx. Can we add the `Restart=always` directive under `[Service]` to the files:

`/etc/systemd/system/multi-user.target.wants/php5.6-fpm.service`
`/etc/systemd/system/multi-user.target.wants/php7.0-fpm.service`

That will automatically restart them if they go down, regardless of reason.

**Comment by oerdnj** [comment]
No, this is wrong. The `on-failure` setting is correct even in the enomem case (see

**Comment by oerdnj** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by khromov** [comment]
If I understand correctly, you are saying the services should have been restarted, but there was an issue preventing that?

**Comment by oerdnj** [comment]
Yes, but you have the logs... I don't...
