### ISSUE TITLE
bundle latest php-memcached with 7.0&7.1

### ISSUE THREAD

**Issue by lhwparis** [oerdnj/deb.sury.org#543]
Only the latest release 3.0.0+ is compatible with php7.0&7.1 can you please bundle this latest php-memcached version with php 7.0 and 7.1?
https://github.com/php-memcached-dev/php-memcached/releases

**Comment by oerdnj** [comment]
`php-memcached` is already compatible with PHP 7.0 and 7.1 and the changes between the git snapshot and 3.0.1 are minimal.

I have updated the package, but not because of the PHP 7.x compatibility - that's already there.
