### ISSUE TITLE
apt update packages.sury.org gnutls_handshake() failed

### ISSUE THREAD

**Issue by OsirisWsjr** [oerdnj/deb.sury.org#545]
Err:7 https://packages.sury.org/php stretch Release
  gnutls_handshake() failed: Public key signature verification has failed.
W: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages  gnutls_handshake() failed: Public key signature verification has failed.
E: Some index files failed to download. They have been ignored, or old ones used instead.

Using Deb Stretch openssl 1.1.0d

**Comment by oerdnj** [comment]
Did you install the required packages? https://packages.sury.org/php/README.txt
```
To add this repository please do:

# apt-get install apt-transport-https lsb-release ca-certificates
# wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
# echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
# apt-get update
```

It seems not, as I can't reproduce the error.

**Comment by OsirisWsjr** [comment]
apt-transport-https is already the newest version (1.4~rc1).
ca-certificates is already the newest version (20161130).
lsb-release is already the newest version (9.20161125).


OpenSSL 1.1.0d  26 Jan 2017 (Library: OpenSSL 1.1.1-dev  xx XXX xxxx)

**Comment by OsirisWsjr** [comment]
Fixed by purging libgnutls-deb0-28 "libgnutls-deb0-28 which was
being kept around by an old librtmp1 package version, left over from
Jessie debian-multimedia"

**Comment by Esysteme** [comment]
got same problem but from new install

**Comment by Esysteme** [comment]
maybe behind a proxy ?
