### ISSUE TITLE
Is is possible to include curl in PHP 5.6.30?

### ISSUE THREAD

**Issue by ronsavage** [oerdnj/deb.sury.org#547]
I'm running your PHP 5.6.30 under Ubuntu 14.04, but my ecommerce package needs curl.

**Comment by pradzikowski** [comment]
Install php5.6-curl
`sudo apt-get install php5.6-curl`

**Comment by ronsavage** [comment]
Thanx. From my history:
 1544  sudo apt-get install php-curl
 1547  sudo apt-get install php5-curl
But I missed your correct (and tested) solution.
