### ISSUE TITLE
Update to libssl has broken NTP on Ubuntu 12

### ISSUE THREAD

**Issue by RobHooper** [oerdnj/deb.sury.org#548]
I have just installed the latest version of libssl from your PHP repository on my Ubuntu 12.04.5 server and it has broken NTP. 
`$ sudo service ntp start`
`* Starting NTP server ntpd `
`/usr/sbin/ntpd: relocation error: /usr/sbin/ntpd: symbol CRYPTO_memcmp, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference [fail]`

Package versions `dpkg -l`
`ii ntp 1:4.2.6.p3+dfsg-1ubuntu3.11 Network Time Protocol daemon and utility programs`
`ii  openssl 1.0.2k-1+deb.sury.org~precise+5 Secure Sockets Layer toolkit - cryptographic utility`
`ii  libssl1.0.0 1.0.2k-1+deb.sury.org~precise+1 Secure Sockets Layer toolkit - shared libraries`

Let me know if there is any more debug information I can provide.
Thanks in advance.

**Comment by oerdnj** [comment]
`libssl1.0.0` should not be available from the repository as it was superseded by `1.0.2k-1+deb.sury.org~precise+5`.

Could you do:
`apt-get update`

and post output of `apt-cache policy libssl1.0.0` here?

**Comment by RobHooper** [comment]
```
$ apt-cache policy libssl1.0.0
libssl1.0.0:
  Installed: 1.0.2k-1+deb.sury.org~precise+1
  Candidate: 1.0.2k-1+deb.sury.org~precise+1
  Version table:
 *** 1.0.2k-1+deb.sury.org~precise+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1-4ubuntu5.39 0
        500 http://gb.archive.ubuntu.com/ubuntu/ precise-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ precise-security/main amd64 Packages
     1.0.1-4ubuntu3 0
        500 http://gb.archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
```
Having a bit more of a dig into this, this happened after running a `apt-get dist-upgrade` this morning and it seems it has just started prioritising your package over the default ubuntu one.
`2017-02-16 11:27:48 upgrade libssl1.0.0 1.0.1-4ubuntu5.39 1.0.2k-1+deb.sury.org~precise+1`

**Comment by oerdnj** [comment]
Looks like some bug in the launchpad, as it should remove the `libssl1.0.0` automatically, but it hasn't. I have purged all occurences of `1.0.2k-1+deb.sury.org~<dist>+1`.

Could you retry to `apt-get update` && `apt-get policy libssl1.0.0` again?

**Comment by oerdnj** [comment]
Oh, and for manual downgrade, you can use:

`apt-get install libssl1.0.0/precise-security` or `apt-get install libssl1.0.0=1.0.1-4ubuntu5.39`, this should get your system back in shape.

My precise chroot now reports:
```
# apt-cache policy libssl1.0.0 
libssl1.0.0:
  Installed: 1.0.1-4ubuntu5.39
  Candidate: 1.0.1-4ubuntu5.39
  Version table:
 *** 1.0.1-4ubuntu5.39 0
        500 http://eu.archive.ubuntu.com/ubuntu/ precise-updates/main amd64 Packages
        500 http://eu.archive.ubuntu.com/ubuntu/ precise-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ precise-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1-4ubuntu3 0
        500 http://eu.archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
```

**Comment by RobHooper** [comment]
Awesome I can confirm that has fixed it.
