### ISSUE TITLE
Feature request: Please add mod_geoip2 and apache2-dev packages in the Apache2 repository

### ISSUE THREAD

**Issue by RobinMathewRajan** [oerdnj/deb.sury.org#549]
Hi,

The Canonical maintained mod_geoip2 and apache2-dev packages for Apache2 are often outdated. It would be really nice if you could include these packages in your repository. I'm using your PPA. If I install these packages from Ubuntu repositories, which are for earlier versions of Apache2, would it break my current install of Apache?

Thanks,
Robin Mathew Rajan

**Comment by oerdnj** [comment]
Are you talking about this package? `libapache2-mod-geoip`

Why not use directly new https://github.com/maxmind/mod_maxminddb ?

**Comment by oerdnj** [comment]
@RobinMathewRajan ping? ^^^

**Comment by oerdnj** [comment]
No response, closing.
