### ISSUE TITLE
libssh2-php

### ISSUE THREAD

**Issue by mkaatman** [oerdnj/deb.sury.org#55]
Hey Ondřej,

Could you please add ssh2 support for the 5.6 backport? I noticed it exists in 5.5 but seems to be missing from 5.6.

Thank you!
Matt

**Comment by fgreinus** [comment]
:+1:

**Comment by oerdnj** [comment]
Hi, thank you for reminder, I will work in the first half of this week. Thank you for patience.

**Comment by mkaatman** [comment]
Is there a good getting started guide for packaging backports? I wouldn't mind learning and helping out.

**Comment by oerdnj** [comment]
@mkaatman Start with Debian packaging guide and become Debian maintainer/developer. That would be helpful :). Anyway - you should look at Debian NM manual as a start and understand the tools used (debuild, dpkg-buildpackage, debhelper, pbuilder, git-buildpackage). Most backporting is just running debuild -S -sa, but when you encounter a problem, you should understand various stuff to be able to fix it (f.e. DEBHELPER compatilibity levels).

Anyway php-ssh2 has been uploaded to php5-5.6, so I am closing the bug.

**Comment by fgreinus** [comment]
Thank you :+1:
