### ISSUE TITLE
"PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data" in the newest php7.1 packages.

### ISSUE THREAD

**Issue by HerMajestyDrMona** [oerdnj/deb.sury.org#552]
Hello. There is a problem with the newest version of php7.1 packages. It gives error:
`2017/02/17 20:28:34 [error] 3434#3434: *259 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/phpBB3/includes/functions.php:99
Stack trace:
#0 /var/www/phpBB3/includes/functions.php(99): random_bytes(8)
#1 /var/www/phpBB3/phpbb/session.php(806): unique_id()
#2 /var/www/phpBB3/phpbb/session.php(493): phpbb\session->session_create()
#3 /var/www/phpBB3/viewtopic.php(26): phpbb\session->session_begin()
#4 {main}
  thrown in /var/www/phpBB3/includes/functions.php on line 99"`

It's caused by: https://github.com/php/php-src/pull/2385
(packages compiled with the newer kernel versions are incompatible due to getrandom() changes).
Could you please apply the fix for this problem and release an update?

**Comment by oerdnj** [comment]
Applied and uploaded as `7.1.2-2*`
