### ISSUE TITLE
no PHP source packages in the repo

### ISSUE THREAD

**Issue by zsalab** [oerdnj/deb.sury.org#556]
Source packages missing from the repo (7.0 exists but no 5.6 and 7.1)
https://packages.sury.org/php/pool/main/p/php5.6/
https://packages.sury.org/php/pool/main/p/php7.1/

**Comment by oerdnj** [comment]
Honestly, I have absolutely no idea, why that might be happening, since the packages are almost the same and the build recipe is absolutely the same.

**Comment by oerdnj** [comment]
Looks like updating dpkg and debhelper to sid versions has helped with this too and sources are now available.

**Comment by zsalab** [comment]
thanks!
