### ISSUE TITLE
Can't install gd on php 5.6 ubuntu 16.04 docker

### ISSUE THREAD

**Issue by sebastianvirlan** [oerdnj/deb.sury.org#557]
I am trying to install GD library on php:apache-5.6 container. Here is my Dockerfile:

```
FROM php:5.6-apache
RUN apt-get update
RUN touch /etc/apt/sources.list.d/ondrej-php.list
RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php.list
RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
RUN apt-get update
RUN apt-get install php5.6-gd
```
The error I receive is:

> 
> The following packages have unmet dependencies:
>  php5.6-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

If I try to install that dependency I need another tree of dependencies.

**Comment by oerdnj** [comment]
> you have held broken packages.

The container  you are using has broken apt settings
