### ISSUE TITLE
no armhf architecture for php7 and php7.1

### ISSUE THREAD

**Issue by yekorzh** [oerdnj/deb.sury.org#558]
Hi,

I've noticed that there are no armhf packages for php7. 
I'm wondering if it possible to add this architecture? 

Thanks.

**Comment by oerdnj** [comment]
Possible yes, but whether it will be successful depends whether the QEMU builds in Debian are stable enough. I've had cases when xz crashed when compressing dbgsym packages.

**Comment by oerdnj** [comment]
Dup of #579
