### ISSUE TITLE
preg_match returning false and preg_last_error returning 0

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [oerdnj/deb.sury.org#559]
PHP version:

    PHP 5.6.30-1+deb.sury.org~trusty+1 (cli)
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

PHP error:

    PHP message: PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 123 in TestRegex.php on line 4"

I've checked the PHP issue tracker, and they resolved it on PHP 5.3.3 (https://bugs.php.net/bug.php?id=52732&edit=2).

About the code:

    <?php
    $sTest = "Hello world";
    $sRegex = "/([A-Z]|[a-z]|[0-9]| |Ñ|ñ|!|&quot;|%|&amp;|'|´|-|:|;|>|=|&lt;|@|_|,|\{|\}|`|~|á|é|í|ó|ú|Á|É|Í|Ó|Ú|ü|Ü){1,300}/";
    var_dump(preg_match($sRegex, $sTest));
    var_dump(preg_last_error());

**Comment by oerdnj** [comment]
No, this hasn't been resolved, as seen here: https://3v4l.org/ffaFI

This is not a packaging issue, so please fill an upstream bug and report it here for reference.

**Comment by oerdnj** [comment]
BTW a simple change to make the regex less complex:
```
<?php
$sTest = "Hello world";
$sRegex = "/([-A-Za-z0-9 Ññ!%'´:;>=@_,\{\}`~áéíóúÁÉÍÓÚüÜ]|&amp;|&quot;|&lt;){1,300}/";
var_dump(preg_match($sRegex, $sTest));
var_dump(preg_last_error());
```
just works...  https://3v4l.org/kjTtU

So I would recommend just fixing your regex.

**Comment by MikeVelazcoMtz** [comment]
I've reported this here: https://bugs.php.net/bug.php?id=74183

I documented it wrong and editing it is not so pretty, the edition appeared as a comment.

Thanks!
