### ISSUE TITLE
Unable to add PPA Key

### ISSUE THREAD

**Issue by aranw** [oerdnj/deb.sury.org#56]
Hey, 

Trying to add the PPA key but it seems to always fail due to the your name in the PPA Key.

```
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by SmallRoomLabs** [comment]
Running on Ubuntu I do like this to get his PPA's working:

```
apt-get update &&
apt-get install -y language-pack-en-base &&
export LC_ALL=en_US.UTF-8 &&
export LANG=en_US.UTF-8 &&
apt-get install -y software-properties-common &&
add-apt-repository -y ppa:ondrej/php5-5.6 &&
add-apt-repository -y ppa:ondrej/mariadb-10.0 && 
apt-get update && 
apt-get -y upgrade
```

**Comment by aranw** [comment]
I found the fix was for me to set the language to UTF-8.

```
locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by SmallRoomLabs** [comment]
The AMI that I use on AWS doesn't have the language pack installed by default so I had to install language-pack-en-base.  Just doing the locale-gen didn't cut it for me.

But even after 22 years of screwing around with Linux (0.99pl3 was the kernel on my first dist) I'm still more than just a bit confused when it comes to character- & language encodings. ;-)

**Comment by oerdnj** [comment]
Unfortunately that's something broken by Ubuntu and has to be fixed by Ubuntu. I will leave this open for others to find. Thanks for the workaround...

**Comment by oerdnj** [comment]
JFTR this is shortened version that should work (run as root):
```
# apt-get install -y language-pack-en-base
# LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/<repository>
```

**Comment by Seldaek** [comment]
@oerdnj has this been reported to ubuntu? And alternatively while I fully understand that it's not your fault, would it be an option for you to use a transliterated version of your name instead of the full unicode one? That would be a good workaround I guess.

**Comment by oerdnj** [comment]
Should I also change my official name so your copy & paste buffer doesn't get cluttered with few more characters?

No, I am definitely not going to use transliterated name because it's 2015 and I like my name as it is.

**Comment by Seldaek** [comment]
Eh I meant no offense. I just meant it would be a pragmatic way to reduce
the load of duplicate support issues about this problem. I agree with you
though that in this day and age Unicode usage shouldn't cause such breakage.

**Comment by oerdnj** [comment]
I have added instructions to every major PPA description how to circumvent this issue. Hope this fixes most problems.

**Comment by oerdnj** [comment]
JFTR: `LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php` also works.

**Comment by rvadym** [comment]
Dockerfile part for official Ubuntu 14 docker image which worked for me

```
# required by PHP 5.6
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get update && \
	apt-get install -y language-pack-en-base &&\
	export LC_ALL=en_US.UTF-8 && \
    export LANG=en_US.UTF-8


RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y software-properties-common
RUN DEBIAN_FRONTEND=noninteractive LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php


RUN DEBIAN_FRONTEND=noninteractive LC_ALL=en_US.UTF-8 \
	apt-get update && apt-get install -y \
	php5.6 php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml
```

**Comment by ktamas77** [comment]
@rvadym your solution is excellent, there is only a small issue, you missed a `-y` to avoid interactions this line; the noninteractive flag is not enough (docker / ubuntu xenial). With the `-y` parameter it works:
`RUN DEBIAN_FRONTEND=noninteractive LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php`

**Comment by rvadym** [comment]
@ktamas77 I think you're right. It is just part of much bigger config, so I might miss some small details accidentally. Thanks for pointing this out.

**Comment by hypotheses** [comment]
With the current locale setting
```
ubuntu1604# locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```


I still got the warning below. Is this something I can ignore?
```
add-apt-repository ppa:ondrej/php
 Co-installable PHP versions: PHP 5.5, 5.6, PHP 7.0 and batteries included.

You can get more information about the packages at https://deb.sury.org

For PHP 5.4 on Ubuntu 12.04 use: ppa:ondrej/php5-oldstable

BUGS&FEATURES: This PPA now has a issue tracker: https://deb.sury.org/#bug-reporting

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
Press [ENTER] to continue or ctrl-c to cancel adding it
```

**Comment by adgooroo** [comment]
`sudo LC_ALL=ru_RU.UTF-8 add-apt-repository ppa:ondrej/php`
Does not Russian-language support work?

**Comment by mstnorris** [comment]
I have done what is suggested above and added the following two lines to the top of my install.sh script.

```
sudo apt-get install -y language-pack-en-base
sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
```

Yet I still get the following message:

```
WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround
```

Am I missing something?

**Comment by shadowhand** [comment]
No matter what I do, this is still an issue for me on 16.04. I have tried the [this fix](https://github.com/oerdnj/deb.sury.org/issues/56#issuecomment-191748654) multiple times in different ways (using Ansible) and none of them work. The end result is always:

```
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu xenial Release' is no longer signed.                                                         
N: Updating from such a repository can't be done securely, and is therefore disabled by default.                                                           
N: See apt-secure(8) manpage for repository creation and user configuration details. 
```

**Comment by todeveni** [comment]
@shadowhand 

```
- name: Add PHP repository
  apt_repository:
    repo: deb https://ppa.launchpad.net/ondrej/php/ubuntu xenial main
    state: present

- name: Add PHP repository signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
```

**Comment by shadowhand** [comment]
@todeveni did not work, same error.

**Comment by todeveni** [comment]
@shadowhand Works for me 🙂

[Here's](https://gist.github.com/todeveni/2bbe5aa2424202742052fc476813ed2f) the full vagrant setup I tested it on.

**Comment by shadowhand** [comment]
Well, I was having some other SSL issues with composer so I decided to reinstall my OS completely and now everything appears to be working. 🤷🏼‍♂️

**Comment by shadowhand** [comment]
I spoke too soon. Every time there is an ansible package install it will fail ~50% of the time. I can even SSH into the vagrant machine and manually run `sudo apt-get update` and sometimes it will error and sometimes not. At a loss as to what to do.

**Comment by emilklindt** [comment]
After adding via:
```
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
```
I get the following error when running ```apt-get update```:
```
W: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
```
The files seem to be unavailable. Is anyone else having this issue?

**Comment by todeveni** [comment]
@emilklindt You're trying to add Ubuntu repo to Debian. Doesn't work that way.

**Comment by emilklindt** [comment]
@todeveni makes sense. Didn't notice that it was a Ubuntu repo, thanks.

**Comment by o-ayoub** [comment]
Hello, 
sudo add-apt-repository  ppa:ondrej/php

![add_ed](https://user-images.githubusercontent.com/27408905/55087531-2b20ba80-50a2-11e9-9368-2a575f572337.png)


But when I try to install php5.6, it gives this: 

Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php5.6-json amd64 5.6.40-5+ubuntu16.04.1+deb.sury.org+1
  403  Forbidden
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php5.6/php5.6-json_5.6.40-5+ubuntu16.04.1+deb.sury.org+1_amd64.deb  403  Forbidden


Please how can I fix this ?
Thank you

**Comment by oerdnj** [comment]
@o-ayoub Don't hijack old issues with new unrelated issues.  There's no blocking on the launchpad, the blocking is on your side.  I am going to delete your comment in a moment.

**Comment by o-ayoub** [comment]
No, it s ubnutu  16.04 Xenial. 
![ubuntu](https://user-images.githubusercontent.com/27408905/55088309-6f608a80-50a3-11e9-8393-f1e8221f8dd4.png)

**Comment by caiowilson** [comment]
I'd like to add that you can just 
`apt-get install -y language-pack-en-base &&
export LC_ALL=en_US.UTF-8 &&
export LANG=en_US.UTF-8 &&
apt-get install -y software-properties-common`

then proceed as normal (ie: sudo apt-get install -y php7.2) etc.
works with ubuntu based and ubuntu versions with problems with locale.

**Comment by deepakbaltech** [comment]
Hello.. I'm getting error in ubuntu14.04. Can not install php7.1 by "sudo add-apt-repository -y ppa:ondrej/php" and "sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php"

**Comment by todeveni** [comment]
> Hello.. I'm getting error in ubuntu14.04. Can not install php7.1

Ubuntu 14.04 is deprecated and not supported.

**Comment by deepakbaltech** [comment]
Thank you @todeveni , but still could I ask is there any way around!!

**Comment by ftejada1** [comment]
Hi is possible to install php5.6 on ubuntu 14.04.6??? I have some problems....

**Comment by o-ayoub** [comment]
@ftejada1 Yes,

**Comment by ftejada1** [comment]
I can't install php5.6 in my ubuntu 14.04.6 using ondrej repository
If i make apt-cache search php5.6, I don't have any result....

**Comment by todeveni** [comment]
> I can't install php5.6 in my ubuntu 14.04.6 using ondrej repository

Ubuntu 14.04 is deprecated and not supported.

**Comment by o-ayoub** [comment]
your skype or email contact ?!

**Comment by ftejada1** [comment]
> your skype or email contact ?!

francesc.tejada@gmail.com

**Comment by o-ayoub** [comment]
sent.

**Comment by oerdnj** [comment]
Stop hijacking old issues for unrelated chitchat.

**Comment by oerdnj** [comment]
Also asking for other user contact details here, will get you blocked.
