### ISSUE TITLE
Socket IO Emits causing trailing bytes errors

### ISSUE THREAD

**Issue by KarlJakober** [oerdnj/deb.sury.org#562]
Hello. After using your ppa and installing the following packages

> php7.0-mbstring php7.0-mysql php7.0-gd php7.0-xml php7.0-fpm php7.0-cli php7.0-mcrypt php7.0-curl php7.0-zip php-memcached php7.0-intl php7.0-xsl

any emit done through the following package https://github.com/rase-/socket.io-php-emitter results in our socket io nodejs servers crashing and emitting a 

> Error: -435547348 trailing bytes

after a LOT of troubleshooting, including updating both node, composer packages, trying php7.1 we removed your ppa and installed the aforementioned packages directly from apt-get and it resolved our issues immediately

Unfortunately I am not knowledgeable enough to deduce which php package may be causing the issue.

I hope this can get resolved or this issue can help someone else who might encounter this issue in the future.

**Comment by oerdnj** [comment]
What are the package versions you tried? And have you used the `php-redis` package?

**Comment by KarlJakober** [comment]
happens with the newest version 0.7.0, i have assumed this is happening only with a ppa package as when it was removed and apt-get packages were installed, there were no issues. I am also assuming it has more to do with the msgpack file specifically. https://github.com/rase-/socket.io-php-emitter/blob/master/src/msgpack_pack.php if I get time in the future I may be able to build a small package to reproduce.

**Comment by KarlJakober** [comment]
Ok Ive done quite a bit of debugging on this issue..
If i remove php-webpack package, everything worse nicely (as socket.io-php-emitter includes a fallback version)

Keep in mind relating to your php-redis question earlier, I am passing an instance of predis (through laravel) into that socket io emitter package.

Here are my results of debugging, I thought I would get different results from the two packages, but I was wrong in the end.



DOES work with php-msgpack

```
$args = [
    "follows",
    [
        "name" => "ActionBa5tard",
        "variation" => -1
        "isTest" => true
    ]
]
```

Packed without php-msgpack

`���type�data��follows���name�ActionBa5tard�variation��isTestãnsp�/��rooms��6557A74B19C2EBCA0B2A�flags�`

packed with php-msgpack

`���type�data��follows���name�ActionBa5tard�variation��isTestãnsp�/��rooms��6557A74B19C2EBCA0B2A�flags�`


DOESNT work with php-msgpack


```
$args = [
    "donations",
    [
        "name" => "ActionBa5tard",
        "formattedAmount" =>"$1.00",
        "amount" => 1,
        "message" => "This is a test donation for $1.00.",
        "currency" => "USD",
        "variation" => -1
        "isTest" => true
    ]
]
```

packed without php-msgpack

`���type�data��donations���name�ActionBa5tard�formattedAmount�$80.00�amountP�message�#This is a test donation for $80.00.�currency�USD�variation��isTestãnsp�/��rooms��6557A74B19C2EBCA0B2A�flags�
`
packed with php-msgpack

`���type�data��donations���name�ActionBa5tard�formattedAmount�$66.00�amountB�message�#This is a test donation for $66.00.�currency�USD�variation��isTestãnsp�/��rooms��6557A74B19C2EBCA0B2A�flags�
`
but socket io throws error with php-msgpack

Error in socketio (included debug offset and buffer length)

```
0|worker   | decoder offset 592734411
0|worker   | buffer length 195
0|worker   | Error: -592734216 trailing bytes
0|worker   |     at Object.decode (/home/vagrant/io/node_modules/msgpack-js/msgpack.js:228:47)
0|worker   |     at Redis.onmessage (/home/vagrant/io/node_modules/socket.io-redis/index.js:94:24)
0|worker   |     at emitThree (events.js:116:13)
0|worker   |     at RedisClient.emit (events.js:194:7)
0|worker   |     at RedisClient.return_reply (/home/vagrant/io/node_modules/redis/index.js:672:22)
0|worker   |     at ReplyParser.<anonymous> (/home/vagrant/io/node_modules/redis/index.js:309:14)
0|worker   |     at emitOne (events.js:96:13)
0|worker   |     at ReplyParser.emit (events.js:188:7)
```


In the long run my debug is inconclusive, but you might have a better idea as to where that absurdly long offset is coming from

**Comment by KarlJakober** [comment]
IGNORE! Incompatible msgpack specs! php-msgpack is v5 not compatible with old versions! (didnt have this issue without ppa because package includes fallback msgpack package

**Comment by oerdnj** [comment]
Thanks for letting me know. I like the bugs that solve themselves in time the most :).

**Comment by KarlJakober** [comment]
hopefully this issue will help someone in the future.

cheers
