### ISSUE TITLE
Received HTTP code 403 from proxy after CONNECT

### ISSUE THREAD

**Issue by buddy** [oerdnj/deb.sury.org#565]
Hi, Ondřej!
i'm trying to install php7.1 from your repository, but apt update return this mistake:

`
Err https://packages.sury.org jessie/main amd64 Packages                                                                                                        
  Received HTTP code 403 from proxy after CONNECT

W: Failed to fetch https://packages.sury.org/php/dists/jessie/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by oerdnj** [comment]
Do you have any proxy server between your end-machine and the server? There's no proxy on my side.

**Comment by saifuullah** [comment]
fatal: unable to access 'https://github.com/saifuullah/PPSD-Project.git/': Received HTTP code 403 from proxy after CONNECT
i am facing this error please help
