### ISSUE TITLE
PHP 5.6 - LibSSL 1.1 compatibility

### ISSUE THREAD

**Issue by zsalab** [oerdnj/deb.sury.org#566]
Modified patch linked below, this new patch does not try to backport the 7.1 openssl module it is the improved version of the 5.6 original openssl module.
Related issues: #523 #555

`
Test result on Jessie:
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   34
---------------------------------------------------------------------

Number of tests :  100                97
Tests skipped   :    3 (  3.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   97 ( 97.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :   37 seconds
=====================================================================

Addition test based on issue #555
--------------------------------------
php /tmp/ssltest.php 0123456789ABCDEF
string(16) "0123456789ABCDEF"
string(44) "bENRlpIGWuwr8Dcr6JGsAMX+HN03lM3dtrkICOIPYlA="
string(16) "0123456789ABCDEF"
--------------------------------------
php /tmp/ssltest.php 0123456789ABCDEFGHIJKLMNOPQRS
string(29) "0123456789ABCDEFGHIJKLMNOPQRS"
string(44) "bENRlpIGWuwr8Dcr6JGsAKDz9TdPKcTfweZ8oQtKDqk="
string(29) "0123456789ABCDEFGHIJKLMNOPQRS"
`

Stretch notes: SNI maybe not supported yet (under investigation, I will provide new patch soon as possible), all other functionality restored even the problem discovered in #555 issue.
Failed tests on Stretch: sni_server, stream_verify_peer_name
The sni_server test fails on my build system even with the newest 7.1 untouched PHP

Patch available:
https://zettasystem.com/php-5.6-libssl-1.1-compatibility-20170309.patch

All contributions welcome!

**Comment by oerdnj** [comment]
Applied, thanks.

**Comment by HansVanEijsden** [comment]
@zsalab thanks for the patch. I just upgraded to Debian 9 Stretch, but for 1 site and FreePBX I still need PHP 5.6. Unfortunately the patch doesn't apply (1 failed hunk) on PHP 5.6.31, but it works on PHP 5.6.30. Am I missing something? Is there a more recent patch for PHP 5.6.31?

**Comment by oerdnj** [comment]
@hansvaneijsden https://gitlab.sury.org/pkg-php/php/blob/master-5.6/debian/patches/0055-Use-OpenSSL-1.1-compatibility-patch-when-built-with-.patch

**Comment by oerdnj** [comment]
This is the location of up-to-date patch for latest PHP 5.6 release.

**Comment by HansVanEijsden** [comment]
@oerdnj thank you very much. Up & running! 👍🏻

**Comment by zsalab** [comment]
I improved my patch a bit, to support the different Debian versions
1.1.0f (Debian Stretch)
1.0.1t (Debian Wheezy & Jessie)
0.9.8o (Debian Squeeze LTS)

http://zettasystem.com/PHP-5.6.31-OpenSSL-1.1.0-compatibility-20170801.patch

Probably the PHP developers wont accept the pull request but I created one
https://github.com/php/php-src/pull/2667
It would be nice if they accept because probably wont cause any more issues on newer versions.

So vote for it if you want to use PHP 5.6 with OpenSSL 1.0

**Comment by HansVanEijsden** [comment]
A smooth and working build on:

- Debian Stretch with OpenSSL 1.1.0f-3 package (x86_64)
- Debian Jessie with OpenSSL 1.0.2l-1~bpo8+1 package from jessie-backports (x86_64)

Thanks again!

**Comment by joseErico** [comment]
Sorry for my ignorance but how do I apply this patch?

**Comment by joseErico** [comment]
Sorry for my ignorance, but how do I apply this patch?

**Comment by zsalab** [comment]
@joseErico 
1., you can use the pre build packages here: https://deb.sury.org
2., or build by yourself
- download PHP source
- cd source folder and patch -p1 < ../patchname
- and the normal build process

**Comment by joseErico** [comment]
@zsalab  Worked perfectly. 
Thank you!!
