### ISSUE TITLE
phpmyadmin support for php7.0/php7.1

### ISSUE THREAD

**Issue by justnx** [oerdnj/deb.sury.org#569]
Hi,

since phpmyadmin is linking to php5 dependencies on Debian Jessie+ can you provide a fixed version of phpmyadmin which cooperate with your package versions?

**Comment by nijel** [comment]
There is [phpMyAdmin PPA](https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin) which you can use.

**Comment by aboe76** [comment]
I would love to see phpmyadmin in deb.sury.org so if it is possible to add it that would be nice..

**Comment by oerdnj** [comment]
There's nijel's PPA for that.

**Comment by justnx** [comment]
PPA on Debian? Sounds no good idea.

**Comment by oerdnj** [comment]
It's OK for pure PHP packages, otherwise I wouldn't recommend it.
