### ISSUE TITLE
uwsgi (libapache2-mod-uwsgi) support

### ISSUE THREAD

**Issue by moser4035** [oerdnj/deb.sury.org#57]
Hi Ondrej,
Could you add support for uwsgi module (<a href="http://packages.ubuntu.com/precise/libapache2-mod-uwsgi">libapache2-mod-uwsgi</a>) to your build?

Greetings,
David

**Comment by oerdnj** [comment]
Could you be a little bit more specific about repository and ubuntu version? The uwsgi is not that easy to backport.

**Comment by oerdnj** [comment]
The uwsgi backport is too fragile to be maintained across several Ubuntu versions with just one source. I tried, but it breaks too much.
