### ISSUE TITLE
php5.6-fpm doesn't parse PHP scripts

### ISSUE THREAD

**Issue by jmail** [oerdnj/deb.sury.org#571]
Hi there I have an issue on Ubuntu 14.04 . PHP is not parsing scripts - I get plain text on the screen.

I run installation

`apt-get purge php.*`
`apt-get install php5.6-fpm`

> Creating config file /etc/php/5.6/fpm/php.ini with new version
> NOTICE: Not enabling PHP 5.6 FPM by default.
> NOTICE: To enable PHP 5.6 FPM in Apache2 do:
> NOTICE: a2enmod proxy_fcgi setenvif
> NOTICE: a2enconf php5.6-fpm
> NOTICE: You are seeing this message because you have apache2 package installed.
> php5.6-fpm start/running, process 3914
> Processing triggers for ureadahead (0.100.0-16) ...

`a2enmod proxy_fcgi setenvif`

> Considering dependency proxy for proxy_fcgi:
> Module proxy already enabled
> Module proxy_fcgi already enabled
> Module setenvif already enabled

`a2enconf php5.6-fpm`

> Enabling conf php5.6-fpm.
> To activate the new configuration, you need to run:
>   service apache2 reload

`service apache2 restart`

> * Restarting web server apache2                                                                                                      [ OK ]

`service php5.6-fpm restart`

> php5.6-fpm stop/waiting
> php5.6-fpm start/running, process 4051

And the output is content of the script

**Comment by oerdnj** [comment]
You need newer apache2: https://wiki.apache.org/httpd/PHP-FPM

You can get it from `ppa:ondrej/apache2` or use different configuration.
