### ISSUE TITLE
Older versions of 7.1

### ISSUE THREAD

**Issue by martinssipenko** [oerdnj/deb.sury.org#572]
Hi,

Is it possible to install older versions of PHP? Currently the latest is `7.1.2`, but I'm experiencing high CPU load with this version, so I'm wondering if it's possible to downgrade to `7.1.1` or `7.1.0`. Running on `7.1.0` has no CPU load issues.

Thanks.

**Comment by oerdnj** [comment]
Neither `reprepro` used for Debian nor launchpad for PPAs have this option, and I said this many times - I think it would be irresponsible of me to provide software with know security issues for general public use.

You can always rebuild the packages easily from git using `git-buildpackage` and checking out the wanted versions, but it's your choice and your foot being shot...

**Comment by martinssipenko** [comment]
Fair points and thanks! Upcoming 7.1.3 seems to have issue sulved.

Martins

**Comment by oerdnj** [comment]
If you know a patch (or set of patches), I would be happy to apply it on top of current stable release. Just send a commit(s).
