### ISSUE TITLE
/etc/php/7.0/cli/conf.d/20-xdebug.ini recreated at every update

### ISSUE THREAD

**Issue by netpalantir** [oerdnj/deb.sury.org#576]
Hello,
I'd love to disable Xdebug for the CLI only. My first thougt wat to just delete the symlink /etc/php/7.0/cli/conf.d/20-xdebug.ini, which IIRC should be a good way to disable that module for the CLI only, leaving it intact for FPM.

Unfortunately, after every update, the symlink gets recreated. This looks to me lilke a bug, but if this is the intended behavior sorry for my misunderstanding.

Thank you very much for your work, this repo is invaluable.

**Comment by oerdnj** [comment]
Use `phpdismod`

**Comment by netpalantir** [comment]
Thank you.
