### ISSUE TITLE
php-ds

### ISSUE THREAD

**Issue by basz** [oerdnj/deb.sury.org#577]
Hello,

i havely make use of the [php-ds](https://github.com/php-ds/extension) extension. Would it be a lot of work to add that pecl extension?

Thanks

**Comment by oerdnj** [comment]
Done

**Comment by basz** [comment]
A new [version](https://github.com/php-ds/extension/issues/77) was [released](https://github.com/php-ds/extension/releases/tag/v1.1.8) which fixed a serialisation bug, could that be updated, or should I wait until a new version of PHP arrives...

 (not my week apparently as I found two php bugs in one week)
