### ISSUE TITLE
reverting

### ISSUE THREAD

**Issue by basz** [oerdnj/deb.sury.org#578]
Hi,

php 7.1.3 has a datetime bug, which stopped my app from working. :-/ 

is it possible to revert to 7.1.2 somehow?

thank you

**Comment by oerdnj** [comment]
Check whether there's upstream patch and I'll fix that. Or I can revert the commit that broke it, again a link to commit would be appreciated

**Comment by basz** [comment]
pressure is of. I simply copied an older 7.1.2 fpm and cli binaries from a different machine over the 7.1.3

otherwise here is the bug patched https://github.com/php/php-src/commit/2b7c3831cdc9a0e708040af37d8cf8967755bce3

**Comment by oerdnj** [comment]
Both patches applied.
