### ISSUE TITLE
[feature request]: PHP on arm* Debian architectures (armel, armhf, arm64)

### ISSUE THREAD

**Issue by KuenzelIT** [oerdnj/deb.sury.org#579]
Hey,

when installing PHP 7.1, I'm getting this message:
```
The following packages have unmet dependencies:
 php7.1 : Depends: libapache2-mod-php7.1 but it is not installable or
                   php7.1-fpm but it is not installable or
                   php7.1-cgi but it is not installable
          Depends: php7.1-common but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Do you have any idea what goes wrong here?

Thank you!

**Comment by oerdnj** [comment]
The arm* QEMU builds are very unstable, so it's not available atm

**Comment by jahudka** [comment]
@oerdnj I have a couple of Raspberry PIs (a 2B and a 3) that are online 24/7, but not necessarily busy. I'm not really a package maintainer, so I have no idea how to do this or if it's even possible, but I could run the armhf builds for you if you help me set it up. I'm quite sure that both the PIs are idle at the very least between 4am and 9am and I can set you up with a VPN to give you access to them. I'm located in Prague, so our timezones should match, guessing from your name ;-) If you're interested, my e-mail is `me` at `subsonic` dot `cz` :-) thanks for all your great packages in any case!

**Comment by oerdnj** [comment]
@jahudka That might work if we can get jenkins slaves running there.

**Comment by jahudka** [comment]
Something like this?
http://software-novotny.de/raspberry-pi-remote-compilation-with-jenkins

**Comment by mati75** [comment]
Try to use my packages: http://repozytorium.mati75.eu/raspbian/pool/main/p/php7.1/
Instruction: http://repozytorium.mati75.eu/

**Comment by oerdnj** [comment]
Just an update - a RPi 3 Model B just arrived via snail mail, and I hope to have the autobuilder there during summer...

**Comment by ndandanov** [comment]
Hi,

Thank you for your great work!

I tried to install php7.1 on a Debian Jessie, running on Banana Pi (armv7l).

I first did

```bash
aptitude update
aptitude dist-upgrade
apt-get install apt-transport-https lsb-release ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
cat /etc/apt/trusted.gpg.d/php.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
apt-get update
```

And then I found that not all packages are available in your repo:
```bash
root@me ~ # apt-get install php7.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1 : Depends: libapache2-mod-php7.1 but it is not installable or
                   php7.1-fpm but it is not installable or
                   php7.1-cgi but it is not installable
          Depends: php7.1-common but it is not installable
E: Unable to correct problems, you have held broken packages.
100 root@me ~ # aptitude search libapache2-mod-php7.1                                                                                                                              :(
aptitude search libapache2-mod-php7.1  6.11s user 0.53s system 99% cpu 6.669 total
```

The system is:
```bash
root@me ~ # more /etc/debian_version
8.9
root@me ~ # uname -a 
Linux me 3.4.113-bananian #9 SMP PREEMPT Sat May 6 12:20:11 UTC 2017 armv7l GNU/Linux
```

Thank you in advance for your support!

If needed, perhaps I could also provide some remote Jenkins build support.

**Comment by yaccin** [comment]
I would be willing to cover the fees of an arm64 Debian stretch server if it would mean that future php packages would be available for arm64. ( i would provide root access to the server, so you could set up any software you want/need)

**Comment by stevenwdv** [comment]
Same problem here with raspberry pi 3B (aarch64 with Debian stretch) trying to install php 7.2 :/
This took me too long to figure out... It would be really awesome if you could manage to make it compatible :)
By the way: why is php 7.2/7.1 not available from the default sources?

**Comment by jlayt** [comment]
Would also like to see Rpi3 packages available, and would also be happy to donate hardware or sponsor costs.

**Comment by oerdnj** [comment]
There's more to it. I haven't really investigated how does the jenkins-debian-glue play along with remote slaves - and remote slaves on different architecture. So even with a build server available it won't be easy to make it happen.

**Comment by yaccin** [comment]
Still, if you ever want to give it a try just let me know and I'd be happy to launch a new ARMv8 server for you, even if it turns out that it won't work, no strings attached

**Comment by no-one** [comment]
I really hope it will be possible to use PHP7.1/7.2 on a Pi.

**Comment by diabollo1** [comment]
Can you estimate the time after which the problem solution will be available?

**Comment by CWallenberg** [comment]
This repo (https://repozytorium.mati75.eu) has php7.2 for RPi 3B on Debian Stretch.

**Comment by mati75** [comment]
@CWallenberg for all Raspberry'ies models, not only 3B. I compiled it on arm6 cpu.

**Comment by lukavia** [comment]
Hey, is there anything we can help with in order to get php7.1 packages on Pi 3?

**Comment by mati75** [comment]
@lukavia https://repozytorium.mati75.eu/raspbian/pool/main/p/php7.1/

**Comment by lukavia** [comment]
Since the other 300+ servers use sury's packages I would prefer to use it's repository.

**Comment by TCB13** [comment]
@lukavia completely agree with you. I trust very much the Sury repo.

Same issue with php 7.2 here:
```
root@nightwalk:~# apt install php7.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:

 php7.2 : Depends: libapache2-mod-php7.2 but it is not installable or
                   php7.2-fpm but it is not installable or
                   php7.2-cgi but it is not installable
          Depends: php7.2-common but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Running a FriendlyARM NanoPi Neo 2 here:
```
root@nightwalk:~# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Model:                 4
CPU max MHz:           816.0000
CPU min MHz:           408.0000
BogoMIPS:              48.00
NUMA node0 CPU(s):     0-3
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

Thank you.

**Comment by moso** [comment]
I have two Rock64's which are arm64. One is running Ubuntu 16.04 Xenial, and the other have just had Debian 9 Stretch installed.

The Ubuntu one is running PHP 7.2 just fine with the ppa, but I can't install 7.2 on the Debian one, unless I install it from the buster repos.

I'm running into the same errors as everyone else: none of the dependencies are there:

```
moso@rock64:~# sudo apt install php7.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:

 php7.2 : Depends: libapache2-mod-php7.2 but it is not installable or
                   php7.2-fpm but it is not installable or
                   php7.2-cgi but it is not installable
          Depends: php7.2-common but it is not installable
E: Unable to correct problems, you have held broken packages.
```
lscpu:
```
moso@rock64:~# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Model:                 4
CPU max MHz:           1296,0000
CPU min MHz:           408,0000
BogoMIPS:              48.00
L1d cache:             unknown size
L1i cache:             unknown size
L2 cache:              unknown size
NUMA node0 CPU(s):     0-3
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

**Comment by nachoparker** [comment]
Hi, I also realized that php7.2-redis is available for x86, but not for armhf.
The rest of the php7.2 armhf packages are available in Raspbian Buster, but not this one.

+1 here

**Comment by oerdnj** [comment]
Quick update on this. The qemu arm emulation now works, after moving my build scripts from LXC based machine to a full virtualization, and I built all base dependencies for PHP, so I am now trying to build PHP 5.6 for arm64. I will continue with more after this build will succeed.

**Comment by TCB13** [comment]
@oerdnj many thanks for the update, and for the effort!

**Comment by oerdnj** [comment]
You may try now and report success or failures.

**Comment by ntomka** [comment]
Works for me. Thank you!

**Comment by oerdnj** [comment]
I am going to build all the extensions gradually - you can watch the progress here: https://jenkins.rfc1925.org/
Closing the issue.

**Comment by nachoparker** [comment]
Hi,

Still no php7.2-redis on armhf, whereas it exists on x86. It is the only package missing. I can see it on your Jenkins but it doesn't show up when I try to install it through apt.

Any news about this?

Dup of https://github.com/oerdnj/deb.sury.org/issues/890

**Comment by nachoparker** [comment]
Awesome! Thank you again for your work
