### ISSUE TITLE
php5-oldstable doesn't have any package for Ubuntu Trusty 

### ISSUE THREAD

**Issue by jujugrrr** [oerdnj/deb.sury.org#58]
Hello,
I was trying to use ondrej/php5-oldstable to use PHP5.4 on Ubuntu Trusty, unfortunately it seems the list of package is empty => http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/dists/trusty/main/binary-amd64/Packages.
Is it an issue or is it just not supported?

Thank you!

**Comment by oerdnj** [comment]
It's not supported.

**Comment by jujugrrr** [comment]
:+1:

**Comment by oerdnj** [comment]
More info (from computer with real keyboard): Ubuntu 14.04 has apache 2.4 and PHP 5.4 packaging hasn't been ported to apache2.4 packaging and it's not worth the effort given that PHP 5.4 EOL is just in couple of months.

**Comment by jujugrrr** [comment]
It makes sense, thank you for the update!
