### ISSUE TITLE
php7.0-geoip

### ISSUE THREAD

**Issue by luckyraul** [oerdnj/deb.sury.org#580]
Php 7.0-geoip installs php 7.1 packages

```
Start-Date: 2017-03-21  10:06:44
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php7.0-geoip
Install: geoip-database:amd64 (20150317-1, automatic), libedit2:amd64 (3.1-20140620-2, automatic), php7.1-opcache:amd64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd, automatic),
 php7.1-cli:amd64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd, automatic), php7.1-readline:amd64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd, automatic), php7.1-phpdbg:amd
64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd, automatic), libmagic1:amd64 (5.22+15-2+deb8u3, automatic), php7.1-common:amd64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd,
 automatic), libxml2:amd64 (2.9.1+dfsg1-5+deb8u4, automatic), php-geoip:amd64 (1.1.1-1+0~20161205134332.5+jessie~1.gbp2bf964), sgml-base:amd64 (1.26+nmu4, automatic), libbsd0:amd64
(0.7.0-2, automatic), xml-core:amd64 (0.13+nmu2, automatic), libgeoip1:amd64 (1.6.2-4, automatic), php7.1-json:amd64 (7.1.3+-2+0~20170315222009.20+jessie~1.gbpc7e7dd, automatic)
End-Date: 2017-03-21  10:06:49
```

**Comment by oerdnj** [comment]
It does not. https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php71-cli-always-installed

**Comment by luckyraul** [comment]
Ondřej, can you tell me why you did not split versions in different releases? 

This dependencies make this repository unusable for 7.0, even I am strictly select version to install  ?

**Comment by oerdnj** [comment]
No, you are wrong. Only php-pear enforce default php-maint package. Nothing else does, read the link I sent you again.

**Comment by luckyraul** [comment]
check my log

```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Php::Packages/Package[php7.0-mysql]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-mcrypt]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-intl]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-curl]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-gd]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-geoip]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-xsl]/ensure: created
Notice: /Stage[main]/Php::Packages/Package[php7.0-cli]/ensure: created


```

and result

```
php -v
PHP 7.1.3-2+0~20170315222009.20+jessie~1.gbpc7e7dd
```

**Comment by oerdnj** [comment]
For the last time, php-geoip *doesn't* depend on PHP 7.1:

`Depends: php-common (>= 1:7.0+33~), phpapi-20160303 | phpapi-20151012 | phpapi-20131226 | phpapi-20121212, libc6 (>= 2.14), libgeoip1`

I am not going to neither debug your scripts nor teach you how to administer your system properly. This isn't the appropriate place for that. Use Ubuntu Forums or any other end-user support forum for that.

**Comment by luckyraul** [comment]
Sorry for bothering you, I've looked at repository https://packages.sury.org/php/dists/jessie/main/binary-amd64/Packages and there is direct dependency.

**Comment by luckyraul** [comment]
But 

```
docker run --rm -it debian:jessie /bin/bash
apt-get update
apt-get install apt-transport-https lsb-release ca-certificates wget

**Comment by oerdnj** [comment]
No, there isn't a direct dependency. Installing virtually _any_ PHP 7.0 SAPI along with `php-geoip` would just work.

**Comment by luckyraul** [comment]
it should be less complicated

```
apt-get install php7.0-geoip php7.0-mysqli php7.0-mcrypt --no-install-recommends


The following extra packages will be installed:
  init-system-helpers libbsd0 libedit2 libgeoip1 libltdl7 libmcrypt4 libssl1.0.2 libxml2 php-common php7.0-common php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-phpdbg
  php7.1-readline psmisc ucf


```

Only if I install php7.0-cli  first, then others it will works normally.

**Comment by oerdnj** [comment]
> it should be less complicated
well, go ahead and reduce the complexity while maintaining the flexibility. Patches are welcomed.

**Comment by luckyraul** [comment]
Anyway, thanks for answering. 
Where can I look into? I have one one option in mind - to split repo....
