### ISSUE TITLE
Redis Extension 3.1.2 released

### ISSUE THREAD

**Issue by mrmark** [oerdnj/deb.sury.org#581]
The release tag: https://github.com/phpredis/phpredis/releases/tag/3.1.2

A new release of the extension is available and it fixes several segfaults that people are experiencing.

Sorry if this is not the correct way to request extension upgrade and it would have just happened auto-magically without an issue.  Thanks for your time!

**Comment by oerdnj** [comment]
Done

**Comment by mrmark** [comment]
Thank you very much!
