### ISSUE TITLE
Update request: php-gearman to version 2.0.3

### ISSUE THREAD

**Issue by cbywater** [oerdnj/deb.sury.org#582]
Would it be possible to update php-gearman to version 2.0.3?

There's a bug in 2.0.2 (fixed in [this commit](https://github.com/wcgallego/pecl-gearman/commit/0d98f96575f0dd6b1d77f69b69f7cf3575180dee)) which is causing us problems when we try to mock the runTasks method for testing purposes.

Thanks for your work!

**Comment by oerdnj** [comment]
Done.
