### ISSUE TITLE
Is it possible to install APCu (php-apcu) when using PHP 5.6?

### ISSUE THREAD

**Issue by djvdorp** [oerdnj/deb.sury.org#583]
Hi! First of all, please let me start with thanking you for this amazing repository; it is really appreciated that you do this for the community to make the world a better and more secure place, great work!

One one of my servers (Ubuntu 14.04 Trusty) I made the switch from the "embedded" PHP 5.5.9 to "your" PHP 5.6.x, and everything worked flawless so far. However, when I did a double-check of the modules I used to have enabled in PHP 5.5.9 and I have running now, I noticed that I am missing the PHP 5.6-equivalent of `php5-apcu` it seems. However, when I tried installing your `php-apcu`, it wanted to install a bit more than I was asking for, specifically PHP 7.x. 

See the output here:

```
root@server / # apt install php-apcu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libvpx1
Use 'apt-get autoremove' to remove it.
The following extra packages will be installed:
  libphp7.1-embed php-apcu-bc php7.1-cli php7.1-common php7.1-json
  php7.1-opcache php7.1-readline
The following NEW packages will be installed:
  libphp7.1-embed php-apcu php-apcu-bc php7.1-cli php7.1-common php7.1-json
  php7.1-opcache php7.1-readline
0 upgraded, 8 newly installed, 0 to remove and 5 not upgraded.
Need to get 3,674 kB of archives.
After this operation, 15.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

Is this by design or is there any other way to install APCu in any other way again on PHP 5.6.x ?

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php#why-is-php71-cli-always-installed
