### ISSUE TITLE
dependency on php-mysql forces installation of php7.1-mysql (and php7.1-common) despite php7.0-mysql being installed

### ISSUE THREAD

**Issue by qnxor** [oerdnj/deb.sury.org#586]
As the title says. I have php7.0 installed with php7.0-mysql and I really don't want to pollute it with any php7.1 modules. However, any package that depends on `php-mysql` forces installation of php7.1-mysql and php7.1-common ... this shouldn't be the case as I have php7.0-mysql installed.

I'm not an expert on debian packaging, but I take it you tied the meta package php-mysql to php7.1-mysql ... can it be changed so that it won't force installation of php7.1-mysql when php7.0-mysql is installed?

**Comment by oerdnj** [comment]
The meta-packages depend on latest stable PHP release, so that's expected and correct behavior.
