### ISSUE TITLE
Ubuntu 17.04 (Zesty Zapus) support

### ISSUE THREAD

**Issue by maxbloch** [oerdnj/deb.sury.org#588]
Any plans on supporting Ubuntu 17.04 (Zesty Zapus)?

**Comment by oerdnj** [comment]
It hasn't been released yet.

I have added it to the list of distributions to build for and it will be there in next uploads of packages.

**Comment by oerdnj** [comment]
Uploaded `php5.6`, `php7.0` and `php7.1`.

If you have any specific PECL extensions you need please list them here.

**Comment by emodric** [comment]
@oerdnj How about `php-imagick` for zesty?

Thanks!

**Comment by oerdnj** [comment]
Most extensions have been built and the rest will sort itself out.

**Comment by Zombaya** [comment]
@oerdnj, I noticed there's still no build for apache2 on zesty and the version I get from the official repositories is newer (but misses some modules you include). (2.4.25.0 vs 2.4.25.3)

Any idea when there is going to be a new build of apache2 for zesty?
