### ISSUE TITLE
IntlDateFormatter doesn't instantiate with some timezone on PHP 5.6

### ISSUE THREAD

**Issue by thaiphv** [oerdnj/deb.sury.org#589]
I'm not really sure if this is a problem of the PHP packages provided by the PPA but here is what is happening to me:
I'm using PHP 5.6 on Ubuntu Trusty:

$ php -v
PHP 5.6.30-7+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans_

This code snippet failed for me:
`<?php
$f = new IntlDateFormatter('en_US', IntlDateFormatter::NONE, IntlDateFormatter::LONG, 'Antarctica/Troll');
var_dump($f);`

It's output is always NULL even though this is not documented on PHP.net
Besides this timezone, it also happens to a few other timezones such as America/Creston, Asia/Chita, Asia/Khandyga, or Asia/Srednekolymsk.

I'm also using phpbrew to compile and install PHP 5.6 on my local machine:
$ php -v
PHP 5.6.30 (cli) (built: Apr  6 2017 22:36:10) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

And this code snippet above works for me. i.e:
$ php test.php 
object(IntlDateFormatter)#1 (0) {
}

I'm not sure if this is an issue of the "intl" package provided by the PPA or not. Please advise.
Thanks,
Thai

**Comment by thaiphv** [comment]
I think the ICU database bundled with the intl extension provided by the PPA is pretty old:

$ php -r "var_dump(IntlTimeZone::getTZDataVersion());"
Command line code:1:
string(5) "2013g"

Running the above command on my local machine, which is using the PHP compiled by phpbrew gave a new version:

$ php -r "var_dump(IntlTimeZone::getTZDataVersion());"
string(5) "2015b"

**Comment by oerdnj** [comment]
Debian/Ubuntu PHP uses system provided timezone. Updating [tzdata](http://packages.ubuntu.com/search?keywords=tzdata) should fix (at least some of) that.

**Comment by joshuaspence** [comment]
I'm not sure about that. I have version `2016j-0ubuntu0.12.04` of the `tzdata` package installed, but `IntlTimeZone::getTZDataVersion()` returns `2001k`.

**Comment by thaiphv** [comment]
Since "IntlTimeZone::getTZDataVersion()" is not documented at the moment and it's also a new method introduced in PHP 5.5 so I can't tell what it returns.

**Comment by oerdnj** [comment]
@joshuaspence Then it's even not any Debian patch. It's the `libicuSONAME` version:

```
# grep -r 2011k .
./source/data/misc/zoneinfo64.txt:// Olson version: 2011k
./source/data/misc/zoneinfo64.txt: TZVersion { "2011k" }
```

I could (in theory) update the `icu` version, but that would mean yet another package I need to take care of (security updates and such...).

I would simply recommend updating to Ubuntu 16.04 for a newer libicu version.
