### ISSUE TITLE
Packages for armel

### ISSUE THREAD

**Issue by mpmc** [oerdnj/deb.sury.org#590]
Hello!

Firstly, thanks ever so much for providing a repo for newer PHP versions. However, I noticed that there are no armel packages available, would it be possible to add it? 

Cheers.

**Comment by oerdnj** [comment]
Dup of #579

**Comment by mpmc** [comment]
Ah, apologies! Seems my eyesight is getting worse. I wonder why that didn't show up in an issue search for "armel" though, nevermind!

**Comment by oerdnj** [comment]
The original request was for `armhf` and not `armel`. That's why (I guess). But if you have used searched then your eyesight is excused, that's more than usual ;)

**Comment by callegar** [comment]
Any chance to have builds for armel? I see that #579 is now closed, but I see only armhf in the repo. Having packages for armel - for which debian is the only possibility would be an enabler to move to buster.

**Comment by oerdnj** [comment]
No, the costs for building everything on armel would be higher than costs for buying RPi3 for everybody still using non-armhf CPUs and needing PHP. E.g. it’s not worth it. The arm packages are built using qemu and it already takes ages to built the main PHP package.

**Comment by sergiocallegari** [comment]
I understand.  Unfortunately, my target is not RPI. Do you know if the open build service can target armel, so I can try to to re-build your packages for armel there?

**Comment by AdamWeglarz** [comment]
Its a pitty, as there are tons of armel devices (Zyxel and manufactures NAS'es, which really works different than RPI) which can run on Debian and due to limitations they require to run older releases of for example opemmedivault and require which require PHP 7.0 which is not available on Debian Bullseye and here we are :-)

@sergiocallegari did you manage to build project for armel?

Adam

**Comment by callegar** [comment]
@AdamWeglarz not yet, for the time being I am trying to look at solutions to move away from ARMEL
