### ISSUE TITLE
Persist changes in systemd config

### ISSUE THREAD

**Issue by mmaedler** [oerdnj/deb.sury.org#591]
Hi there,

first of all thanks a lot for maintaining the package sources for php!
Since switching to the recent Ubuntu 16.04 and with it systemd, we are facing a little issue with starting php7 after reboot.
We also run multiple php versions in parallel, but use a slightly different directory structure in the /run folder compared to the original one (we have an extra subfolder e.g. /run/php/7.0/). Therefore we needed to modify the systemd startup script in /lib/systemd/system/php7.0-fpm to add a ExecStartPre command that creates the folder structure for us. 

So here comes the issue: Everytime we update php through apt this extra configuration line disappears which ultimately causes php7 not to start after reboot.
So, is there a way to prevent that from happening?

I am not sure if that is even the right place to address this issue, but I thought I might ask. If not feel free to close it.

Thanks a lot,
M

**Comment by oerdnj** [comment]
You are doing it wrong :).

`systemctl edit php7.0-fpm`

will create an override file in `/etc/systemd/system`.

For specifics, use your favourite search engine.
