### ISSUE TITLE
ssh2 extension for PHP 7.1

### ISSUE THREAD

**Issue by belaustegui** [oerdnj/deb.sury.org#592]
I am setting up a project that requires PHP 7.1 with the extension _ssh2_ to work. I can only find the package `php-ssh2` that installs the said extension for PHP 7.0, but not for PHP 7.1.

I tried to install a `php7.1-ssh2` but the package does not exist. Does the package have a different name? Could it be added to the ppa?

**Comment by oerdnj** [comment]
DIstribution? Versions?

**Comment by belaustegui** [comment]
Hi! I am running Ubuntu 17.04.
I was able to compile the extension myself. But it would be great to have it prepackaged for PHP 7.1 in the same way as for PHP 7.0.

**Comment by oerdnj** [comment]
Great, and answering the question I haven't asked and not answering the questions I have asked is going to help to achieve that.

**Comment by belaustegui** [comment]
Well, I stated that I am using Ubuntu 17.04, and the package would be for PHP 7.1.
Not sure which other questions did you asked and was left unanswered.

Its fine though, extension is now working. Thank you anyway.

**Comment by rgpublic** [comment]
php7.1-ssh2 still missing. Using Ubuntu 17.04 (Zesty) and this line in APT:

deb http://ppa.launchpad.net/ondrej/php/ubuntu zesty main

On Ubuntu 17.10 (Artful) the same situation with this line in APT:

deb http://ppa.launchpad.net/ondrej/php/ubuntu artful main

apt-cache search ssh2 | grep php only shows php-ssh2 but no php7.1-ssh2, php7.2-ssh2. This is different from all the other PHP extensions.
