### ISSUE TITLE
[PPA Update request] Nginx 1.12.0 now available, 1.13.x coming soon

### ISSUE THREAD

**Issue by WilliamFeely** [oerdnj/deb.sury.org#597]
As of 2017-04-12 the latest version of nginx is 1.12.0, this being the latest Stable branch.  Mainline 1.13.0 is also due to be released on 2017-04-25.
The mainline repository has not been update since version 1.11.10 as of today.

**Comment by willfull** [comment]
Mainline 1.13.0 was _just_ released, however it looks like this repository was only updated to 1.11.13 a few hours ago.

**Comment by oerdnj** [comment]
I guess (hope) the heavy-lifting update was done in 1.11.13, so the 1.12.0 and 1.13.0 update shouldn't be that difficult.

**Comment by willfull** [comment]
Any news on 1.13.0 mainline?  Did it turn out to be a difficult update?

**Comment by oerdnj** [comment]
I don't think so, but it's too sunny outside (+public holiday today) and I was finishing MariaDB 10.3 packaging. I'll have a look this week.

**Comment by willfull** [comment]
Děkuji, Ondřej.  Enjoy the weather, sounds nice!  :-)

**Comment by oerdnj** [comment]
You're lucky, I had to relax in the evening, so it has been now done. Some architectures are still building, but should finish shortly.

The only caveat is that I had to drop SPDY patch for 1.13.0 mainline as it doesn't compile. I kept it for 1.12.0 though.

**Comment by WilliamFeely** [comment]
Are you saying you had the SPDY+HTTP2 patch working all the way up to 1.12.0?  I had no idea it was even present in your 1.11.x builds.

**Comment by oerdnj** [comment]
Yup ;). It's still present in 1.12.0.

**Comment by willfull** [comment]
But it should be noted that Ondřej's mainline release still supports HTTP/2:

`$ nginx -V
nginx version: nginx/1.13.0
built with OpenSSL 1.1.0e  16 Feb 2017
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-jlENeP/nginx-1.13.0/debian/modules/nginx-auth-pam --add-dynamic-module=/build/nginx-jlENeP/nginx-1.13.0/debian/modules/nginx-dav-ext-module --add-dynamic-module=/build/nginx-jlENeP/nginx-1.13.0/debian/modules/nginx-echo --add-dynamic-module=/build/nginx-jlENeP/nginx-1.13.0/debian/modules/nginx-upstream-fair --add-dynamic-module=/build/nginx-jlENeP/nginx-1.13.0/debian/modules/ngx_http_substitutions_filter_module`

**Comment by oerdnj** [comment]
Yes, definitely.

**Comment by WilliamFeely** [comment]
Is there still any plans to attempt to merge in the SPDY hack to 1.13.x or should we consider it dead and buried?

**Comment by oerdnj** [comment]
Is there a compelling reason to do so? https://caniuse.com/#search=http2

**Comment by PeterDaveHello** [comment]
I think the point is for legacy especially mobile devices, looks like Cloudflare updated its patch for nginx v1.13.x already: https://github.com/cloudflare/sslconfig/blob/master/patches/nginx__1.13.0_http2_spdy.patch, maybe it'll be great to use it?

**Comment by WilliamFeely** [comment]
Doesn't IE11 in Windows 7 and 8.1 support SPDY but not HTTP/2?
