### ISSUE TITLE
Failed to issue method call: Unit phpsessionclean.timer not loaded

### ISSUE THREAD

**Issue by ruuter** [oerdnj/deb.sury.org#598]
Unable to upgrade or reinstall `php-common` on `4.4.0-72-generic #93~14.04.1-Ubuntu`

`$ sudo apt-get -y upgrade php-common`
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be upgraded:
>   php-common
> 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/14,3 kB of archives.
> After this operation, 0 B of additional disk space will be used.
> (Reading database ... 447884 files and directories currently installed.)
> Preparing to unpack .../php-common_1%3a52+deb.sury.org~trusty+1_all.deb ...
> Failed to issue method call: Unit phpsessionclean.timer not loaded.
> dpkg: warning: subprocess old pre-removal script returned error exit status 5
> dpkg: trying script from the new package instead ...
> Failed to issue method call: Unit phpsessionclean.timer not loaded.
> dpkg: error processing archive /var/cache/apt/archives/php-common_1%3a52+deb.sury.org~trusty+1_all.deb (--unpack):
>  subprocess new pre-removal script returned error exit status 5
> Failed to issue method call: Unit phpsessionclean.timer failed to load: No such file or directory. See system logs and 'systemctl status phpsessionclean.timer' for details.
> Errors were encountered while processing:
>  /var/cache/apt/archives/php-common_1%3a52+deb.sury.org~trusty+1_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

`$ sudo systemctl status phpsessionclean.timer`

> phpsessionclean.timer
>    Loaded: error (Reason: No such file or directory)
>    Active: inactive (dead)

`$ locate phpsessionclean.timer`

> /etc/systemd/system/timers.target.wants/phpsessionclean.timer
> /lib/systemd/system/phpsessionclean.timer
> /var/lib/systemd/deb-systemd-helper-enabled/phpsessionclean.timer.dsh-also
> /var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/phpsessionclean.timer

**Comment by oerdnj** [comment]
I am afraid that I can't do anything about that without prior logs - e.g. what has happened to the systemd unit before the upgrade. I guess this is a result of some incomplete installation (or did somebody remove the `phpsessionclean.timer` by hand?).

**Comment by ruuter** [comment]
Unfortunately I have no idea. Did not remove anything by hand though.
However, it is not a problem for me at the moment and planning to upgrade Ubuntu soon anyway, so no problem. Just thought it might be useful to report.
Thanks for feedback!
