### ISSUE TITLE
Uninstalling PHP PPA

### ISSUE THREAD

**Issue by davidlanier** [oerdnj/deb.sury.org#60]
I have not found any good information on removing your PPA. Originally I installed it on Ubuntu 12.02 LTS server, but upgraded my servers to Ubuntu 14.04 LTS and now I would like to revert to the default PHP packages provided by Ubuntu. Can you provide some instructions on how to completely remove your PPA and all related packages?

Thanks

**Comment by oerdnj** [comment]
apt-get install ppa-purge ?

**Comment by oerdnj** [comment]
JFTR please use askubuntu or similar forum for general questions like this ... or Google "remove ppa", since both would lead you to: http://askubuntu.com/questions/307/how-can-ppas-be-removed
