### ISSUE TITLE
5.6 is missing many default modules

### ISSUE THREAD

**Issue by techdaddies-kevin** [oerdnj/deb.sury.org#601]
I have co-installed both PHP 5.6 and 7.1 on an Ubuntu 16.04 box. 7.1 is our default version, but we have many sites requiring 5.6 still. Our 5.6 installation is missing several default modules for some reason.

php -m (7.1) output
```
[PHP Modules]
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

php5.6 -m output
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/pdo_mysql.so' - /usr/lib/php/20131226/pdo_mysql.so: undefined symbol: pdo_parse_params in Unknown on line 0
[PHP Modules]
Core
curl
date
ereg
filter
gd
hash
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
Reflection
session
SPL
standard
zlib

[Zend Modules]
```

We noticed this issue specifically because one of our sites has a fatal error due to the missing ctype extension in 5.6.

**Comment by oerdnj** [comment]
The modules are available in `php5.6-common` package and enabled by default. I guess something went wrong during the installation of the package.

**Comment by techdaddies-kevin** [comment]
We have this same issue across 3 separate servers. I have removed php5.6 and all associated packages and reinstalled several times now, and I still don't have the default modules available.

**Comment by oerdnj** [comment]
You need to provide more information than just "it doesn't work"... 

Installation logs (`/var/log/apt`), state of /etc/php/ (`ls -lR /etc/php`), state of /var/lib/php/.
