### ISSUE TITLE
Failed to connect to packages.sury.org port 443: Connection refused

### ISSUE THREAD

**Issue by martinsuly** [oerdnj/deb.sury.org#602]
Hi, recently I have a problem to update/install anything from this repository. It always ends with this error message. I am connecting fom Thailand and I guess it's related because through VPN it works.

```
Err https://packages.sury.org/php/ jessie/main php-common all 1:52+0~20170504085122.17+jessie~1.gbpd2ab76
  Failed to connect to packages.sury.org port 443: Connection refused
Err https://packages.sury.org/php/ jessie/main php7.1-common amd64 7.1.4-1+0~20170411221130.22+jessie~1.gbp4ea64a
  Failed to connect to packages.sury.org port 443: Connection refused
Err https://packages.sury.org/php/ jessie/main php7.1-json amd64 7.1.4-1+0~20170411221130.22+jessie~1.gbp4ea64a
```

**Comment by oerdnj** [comment]
So, should I call the Thailand government and object? 

Use VPN if that works.

**Comment by martinsuly** [comment]
Your website works from Thailand. Why should it be issue of thai government? It's just not possible to download packages. More likely I would tell that there is blocked traffic or so to Asia.

**Comment by martinsuly** [comment]
Please check i can normally load subdomain with packages. But from package manager it doesnt work.

![img_0457](https://cloud.githubusercontent.com/assets/1812855/25771006/d51cd2fc-326e-11e7-8897-d0ce1252fd95.PNG)

**Comment by dldamilola** [comment]
The strange thing is from mac os it is ok to connect to packages.sury.org:

**Comment by martinsuly** [comment]
I have exactly this problem when I run debian from Parallels too but I don't know why it is happening. Otherwise it's ok.
