### ISSUE TITLE
/etc/init.d/php7.1-fpm problem

### ISSUE THREAD

**Issue by IceNV** [oerdnj/deb.sury.org#605]
Package version : latest to day (`7.1.5-1+0~20170513113859.24+jessie~1.gbpe4bc94`)

__Symptom__ : 
On system boot, PHP-FPM does not start.

__Platform__ :
Debian Jessie x64 (on a VPS)

__Cause__ :
First I ran `systemctl is-enabled php7.1-fpm` and it returned `disabled`.

Then I tried to enable it using `systemctl enable php7.1-fpm.service` : 

    Synchronizing state for php7.1-fpm.service with sysvinit using update-rc.d...\
    Executing /usr/sbin/update-rc.d php7.1-fpm defaults\
    insserv: warning: current start runlevel(s) (empty) of script 'php7.1-fpm' overrides LSB defaults (2 3 4 5).\
    insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script 'php7.1-fpm' overrides LSB defaults (0 1 6).
    Executing /usr/sbin/update-rc.d php7.1-fpm enable

Hm, so it seems to come from runlevels...? So I went on to see the contents of `/etc/init.d/php7.1-fpm`.

It seems that, on line 7 of `/etc/init.d/php7.1-fpm`, there is a tab after the Default-Stop runlevels, causing a malfunction.
(GitHub doesn't let me attach it, even as a .txt)

__Solution__ :

Removing the tab seems to solve the problem, after that I ran `systemctl enable php7.1-fpm.service` again and it worked properly :

    Synchronizing state for php7.1-fpm.service with sysvinit using update-rc.d...
    Executing /usr/sbin/update-rc.d php7.1-fpm defaults
    Executing /usr/sbin/update-rc.d php7.1-fpm enable

Then I rebooted the system and PHP started correctly.

Maybe the package needs to be fixed to remove that trailing space ? If not fixed already. Also I don't know why php7.1-fpm appeared disabled, maybe it was directly related, maybe not. It may be worth looking into, too.

Thanks in advance for any comment on this, and also thank you for maintaining this repo :) !

**Comment by oerdnj** [comment]
Good catch! Fixed, uploaded and the packages are building right now.

**Comment by eblanshey** [comment]
I got this same error today @oerdnj, except all output stopped after that:

```
Synchronizing state of php7.1-fpm.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable php7.1-fpm
insserv: warning: current start runlevel(s) (empty) of script `php7.1-fpm' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `php7.1-fpm' overrides LSB defaults (0 1 6).
```

When I ran `systemctl enable php7.1-fpm` a second time, it worked fine:

```
Synchronizing state of php7.1-fpm.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable php7.1-fpm
```

My `/etc/init.d/php7.1-fpm` file did not have any tabs/spaces on the line IceNV mentioned (line 4.)

After rebooting, fpm started just fine though. I still wanted you to be aware of this though.
