### ISSUE TITLE
[Feature Request] PECL: LUA

### ISSUE THREAD

**Issue by JohnKiller** [oerdnj/deb.sury.org#606]
Hi,
Could the [LUA PECL](https://pecl.php.net/package/lua) be included on this repo? I always had problems installing this particular extension in Debian/Ubuntu, then I've discovered [this script](https://github.com/chtombleson/php-lua-install-script) and it works on older versions of php.

Thanks for your amazing work.

PS.: if you can't add this due to dependency issues, can you please tell me where I can find the correct way to install this?

**Comment by oerdnj** [comment]
Done, compiled with Lua5.2 because Lua5.3 is not available in Ubuntu 14.04 LTS.

**Comment by JohnKiller** [comment]
Thanks, tested and working 100%
