### ISSUE TITLE
Upgrade libpcre3 to 8.40 11-January-2017

### ISSUE THREAD

**Issue by ruudk** [oerdnj/deb.sury.org#608]
I'd like to use the latest version of pcre. Currently, it's `2:8.39-1+deb.sury.org~xenial+1`.

Would it be possible to pull in the latest version?

**Comment by oerdnj** [comment]
Done. I just hope it doesn't break anything.

**Comment by ruudk** [comment]
Thank you!! I just put a donation in. Thanks for all your work :)
