### ISSUE TITLE
PHP 5.6 packages for Precise have disappeared?

### ISSUE THREAD

**Issue by thaiphv** [oerdnj/deb.sury.org#609]
Hi @oerdnj, what happened to those packages? I was able to install them on my Precise servers yesterday but now they have all varnished.

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/ubuntu-12-04-lts-9815483

**Comment by thaiphv** [comment]
Thanks for the information. I actually wasn't aware of that announcement.
