### ISSUE TITLE
Update MySQL Distro to 5.6.24

### ISSUE THREAD

**Issue by vstokesjr** [oerdnj/deb.sury.org#61]
Would you please update your MySQL Distro to 5.6.24?

**Comment by oerdnj** [comment]
Hi, thank you for reminder, I will work in the first half of this week. Thank you for patience.

**Comment by vstokesjr** [comment]
<whistling>
    <bump />
    </whistling>

**Comment by oerdnj** [comment]
I am hearing you :). Let's throw MySQL into the build mayhem my build machine is currently experiencing :).

     13:53:46 up 27 days,  2:11,  6 users,  load average: 13,80, 12,04, 8,46

**Comment by vstokesjr** [comment]
WOW! I understand now. We shall wait ever more patiently. ;)

**Comment by oerdnj** [comment]
It's building on PPA machines now: https://launchpad.net/~ondrej/+archive/ubuntu/mysql-5.6/+packages

Fortunately the PPA builds are just source builds, so it doesn't take much time and the machine is usually not that overloaded, but I am playing with rebuilding GNOME 3.16 for Debian jessie, making two nightly builds (for Knot DNS and BIRD) and compiling PHP 5.6.8 for my extra repository I am preparing for Debian jessie (PHP 5.4.x for wheezy will come later).

**Comment by oerdnj** [comment]
It failed to build, so I am reopening the bug to look on it later.

**Comment by oerdnj** [comment]
JFTR (for my reference) it failed with: fatal error: lex_token.h: No such file or directory

**Comment by oerdnj** [comment]
Took me a while to figure it out, but the PIC part of the build now needs more than just two directories. Falling back to full PIC build (but cherry-picking only the parts we need for the package) seems a huge waste of resources, but it's a reasonable workaround for the moment.

MySQL 5.6 is now available from the repository.
