### ISSUE TITLE
Precise packages gone in the ppa

### ISSUE THREAD

**Issue by JanKanis** [oerdnj/deb.sury.org#611]
The PHP packages for Precise are gone from the ppa repository. They were there a few days ago. If you look at http://ppa.launchpad.net/ondrej/php/ubuntu/dists/precise/main/binary-amd64/Packages.gz, it only contains two packages: libzmq3 and libzmq3-dbg. 

Is this an oversight or is Precise no longer supported?

**Comment by oerdnj** [comment]
#609
