### ISSUE TITLE
Update php-ast module (for phan) to v0.1.4

### ISSUE THREAD

**Issue by tersmitten** [oerdnj/deb.sury.org#613]
I would be nice if the `php-ast` extension can be updated from `v0.1.2` to `v0.1.4`, as this is required to use the latest version of [etsy/phan](https://packagist.org/packages/etsy/phan).

**Comment by oerdnj** [comment]
Done (also it's a first module compiled against PHP 7.2.0~alpha2).

**Comment by legoktm** [comment]
According to https://packages.sury.org/php/pool/main/p/php-ast/ only 0.1.2 is available? We also would like to use 0.1.4 for phan :)
