### ISSUE TITLE
Pinba

### ISSUE THREAD

**Issue by mikeSimonson** [oerdnj/deb.sury.org#615]
Is it possible to include the pinba php extension (https://github.com/tony2001/pinba_extension) and the pinba mysql engine (https://github.com/tony2001/pinba_engine) in your repo ?

It's a nice production performance monitoring/exploration tool.

What can I do to help ?

**Comment by neanton** [comment]
Hi, @oerdnj

**Comment by oerdnj** [comment]
This has been packaged for a while
