### ISSUE TITLE
Suggestion: alpha and RC of PHP 7.2

### ISSUE THREAD

**Issue by Llbe** [oerdnj/deb.sury.org#618]
I suggest adding alpha and RC versions of PHP, to make them more accessible and hopefully increase testing of new versions.

To counter the risk of someone running an RC in production / failing to recognize the *RC*, I suggest adding "unstable" in the package name.

The first alpha of 7.2 is available.

**Comment by oerdnj** [comment]
I will package RC, I won't bother with alpha

**Comment by obrienmd** [comment]
Beta3 is out - RC1 should hit tomorrow. looking forward to it!

**Comment by oerdnj** [comment]
It's already packaged (beta 3)
