### ISSUE TITLE
php 7.1.6 regression in HOST and PATH ini sections

### ISSUE THREAD

**Issue by adapterik** [oerdnj/deb.sury.org#619]
Updated my l local Ubuntu 14.04 dev vm, which picked up php 7.1.6, and lo and behold my php7.1-fpm virtual hosts stopped working -- they all appeared to all be picking up the configs of the alphabetically last host ini (as defined in /etc/php/7.1/fpm/conf.d). Since each one sets an appropriate open_basedir and include_path, this badly breaks them all (other than the last lucky one).

After some digging, found this was a regression in 7.1.6, and has been reported and fixed https://github.com/php/php-src/pull/2570
in this commit https://github.com/php/php-src/pull/2570/commits/ee0e6963f39cc8f30bbd5675a0c4880a18b63b00.

Would you be able to pick this up?

The impact of this bug is that it breaks any multi-virtual-host installation. I'm just very glad that this only occurred in a local dev environment!

**Comment by oerdnj** [comment]
Uploaded both to ppa:ondrej/php and packages.sury.org/php/

Thanks for bringing this to my attention.
