### ISSUE TITLE
Updating PHP to 5.5.24

### ISSUE THREAD

**Issue by HAZARDU5** [oerdnj/deb.sury.org#62]
It'd be great to see this updated to PHP 5.5.24.

Currently PHP 5.5.23 has a [critical bug](https://bugs.php.net/bug.php?id=69293) that prevents SOAP requests from being made with multiple headers due to seg faults. SOAP requests like these are these are usually required to connect with Windows Azure web services.

**Comment by oerdnj** [comment]
Hi, thank you for reminder, I will work in the first half of this week. Thank you for patience.

**Comment by HAZARDU5** [comment]
Awesome - thank you!

**Comment by oerdnj** [comment]
Done, it took me longer than expected, sorry for that.

**Comment by HAZARDU5** [comment]
No problem - thanks for looking into this! :-)
