### ISSUE TITLE
Packages for PHP 7.1 install igbinary.ini and redis.ini in PHP 7.0 folder

### ISSUE THREAD

**Issue by staelche** [oerdnj/deb.sury.org#620]
For easy switching PHP versions I am installing PHP 7.0 and PHP 7.1 in parallel. This is great for webhosters providing different PHP versions in parallel but as well for development and production systems during a migration phase from one to another version.

When I install those two versions in parallel (first 7.0 then 7.1) on an up to date and fresh Debian Jessie I get an APT error when installing the latter like:
```
trying to overwrite '/etc/php/7.0/mods-available/igbinary.ini', which is
also in package php-igbinary
```
A can see that if I install PHP 7.0 it creates INI files for redis, igbinary and xdebug in all version folders of PHP you provide (5.6, 7.0, 7.1). Seems like APT does not like to overwrite them. 

Maybe you can have a look into it if this is (easily) solvable.

**Comment by oerdnj** [comment]
I need full apt log.

**Comment by staelche** [comment]
PHP7.0 is already installed and the virtual package php7.0-igbinary was already installed via the actual package php-igbinary because e.g. php7.0-redis was required. Then the following minimum action produces the error (of course, generally you would install e.g. php7.1-fpm and php7.1-redis and some other packages with it):
```
~# aptitude install php7.1-igbinary
Note: selecting "php-igbinary" instead of the
      virtual package "php7.1-igbinary"
The following NEW packages will be installed:
  php-igbinary
0 packages upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 41.5 kB of archives. After unpacking 243 kB will be used.
Get: 1 https://packages.sury.org/php/ jessie/main php-igbinary amd64 2.0.1-1+0~20170315141929.10+jessie~1.gbp48b058 [41.5 kB]
Fetched 41.5 kB in 0s (154 kB/s)
Selecting previously unselected package php-igbinary.
(Reading database ... 53026 files and directories currently installed.)
Preparing to unpack .../php-igbinary_2.0.1-1+0~20170315141929.10+jessie~1.gbp48b058_amd64.deb ...
Unpacking php-igbinary (2.0.1-1+0~20170315141929.10+jessie~1.gbp48b058) ...
dpkg: error processing archive /var/cache/apt/archives/php-igbinary_2.0.1-1+0~20170315141929.10+jessie~1.gbp48b058_amd64.deb (--unpack):
 trying to overwrite '/etc/php/7.0/mods-available/igbinary.ini', which is also in package php7.0-igbinary 2.0.1-1~dotdeb+8.1
Errors were encountered while processing:
 /var/cache/apt/archives/php-igbinary_2.0.1-1+0~20170315141929.10+jessie~1.gbp48b058_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:

~#
```

**Comment by oerdnj** [comment]
php7.0-igbinary 2.0.1-1~dotdeb+8.1...

**Comment by oerdnj** [comment]
You can't mix packages from different repositories.

**Comment by staelche** [comment]
Damned. I was 100% sure that I tested it without including the old dotdeb repo in advance. 

Sorry for bothering you.

**Comment by oerdnj** [comment]
No worries. Just send a full log right away next time :).

**Comment by muelli75** [comment]
I was running in the same trouble, now, after a while, i cant fix this. :-(

Mainly its "my" apt-get problem:
How do I remove php-igbinary from the install-list? 

Thanks for any hints.
