### ISSUE TITLE
Code Coverage Issue in Xdebug 2.5.4

### ISSUE THREAD

**Issue by ChristianSchaefer** [oerdnj/deb.sury.org#621]
Can you please update xdebug to version 2.5.5. This version fixes an issue with code coverage in php unit.

The related issue is

https://bugs.xdebug.org/view.php?id=1444

**Comment by oerdnj** [comment]
There's no 2.5.5 release yet.

**Comment by VasekPurchart** [comment]
2.5.5 is out now and includes the code coverage fixes: https://twitter.com/xdebug/status/877552382955139073

**Comment by oerdnj** [comment]
Done, uploaded and built.

**Comment by VasekPurchart** [comment]
Great, thanks! :)
