### ISSUE TITLE
php-imagick installation fail on debian stretch

### ISSUE THREAD

**Issue by nicolasbadia** [oerdnj/deb.sury.org#623]
I've just upgraded to debian 9 stretch and `apt install php-imagick` is now failing:

```
The following packages have unmet dependencies:
 php-imagick : Depends: libmagickcore-6.q16-2 (>= 8:6.8.8.2) but it is not installable
               Depends: libmagickwand-6.q16-2 (>= 8:6.8.8.9) but it is not installable
               Recommends: ttf-dejavu-core but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Any idea of what is going wrong?

**Comment by oerdnj** [comment]
What's output of `apt-cache policy php-imagick`?

**Comment by nicolasbadia** [comment]
```
php-imagick:
  Installed: (none)
  Candidate: 3.4.3~rc2-2+0~20170315141820.8+jessie~1.gbpd65842
  Version table:
     3.4.3~rc2-2+0~20170315141820.8+jessie~1.gbpd65842 500
        500 https://packages.sury.org/php jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.3~rc2-2 500
        500 http://debian.mirrors.ovh.net/debian stretch/main amd64 Packages
```

Also note that it fail from a clean install of debian stretch (tested on vagrant box "debian/stretch64").

**Comment by oerdnj** [comment]
Sure, you must see the issue yourself now...

**Comment by nicolasbadia** [comment]
Indeed... thanks for pointing it out and thanks a lot for your work.

**Comment by TCB13** [comment]
I'm also experiencing this issue.

**Comment by gabrielbull** [comment]
So, whats the solution?

**Comment by adrianbj** [comment]
@gabrielbull - I don't know why no-one has given explicit instructions here, but the issue is this line: `https://packages.sury.org/php jessie/main amd64 Packages`

You need to modify your sources so that it points to `stretch` rather than `jessie`:
`https://packages.sury.org/php stretch/main amd64 Packages`

For me that was in: `/etc/apt/sources.list.d/php.list` and not the main: `/etc/apt/sources.list`

Hope that helps you and others who stumble across this.

**Comment by janzajec** [comment]
@adrianbj thanks a lot for pointing out the solution, saved my day!

**Comment by wtorsi** [comment]
Same problem but on jessie
````
The following packages have unmet dependencies:
 php-imagick : Depends: libmagickcore-6.q16-2 (>= 8:6.8.8.2) but it is not installable
               Depends: libmagickwand-6.q16-2 (>= 8:6.8.8.9) but it is not installable

#source 
deb https://packages.sury.org/php/ jessie main
````

**Comment by RoosDev** [comment]
Hello 

I had the same problem with upgrade from stretch to buster .... ;) so thank you !!

**Comment by gauravmaini** [comment]
I have the same problem. I am on Ubuntu 16.04 using PHP 7.2
The fix above doesn't work for me. Any pointers?

**Comment by sleemanj** [comment]
@gauravmaini

https://github.com/oerdnj/deb.sury.org/issues/1567#issuecomment-855091229
