### ISSUE TITLE
5.6.30-12 is consuming more CPU than 5.6.30-10

### ISSUE THREAD

**Issue by thaiphv** [oerdnj/deb.sury.org#624]
I noticed that the new PHP revision (5.6.30-12) released recently is consuming about 10% higher CPU power than the previous one (5.6.30-10). All of our servers are AWS EC2 instances and they are all on Ubuntu 16.04. Does anyone have a similar problem or know of a way to troubleshoot it?

**Comment by oerdnj** [comment]
That has to be problem with your measurements, as there were no code changes between 5.6.30-10 and 5.6.30-12 (or something in underlaying libraries - f.e. pcre3 has been updated)
