### ISSUE TITLE
mod_brotli or brotli support in apache2 and nginx

### ISSUE THREAD

**Issue by iatpatelishan** [oerdnj/deb.sury.org#625]
Brotli compression has been implemented by Firefox and chrome. It has performance advantages over gzip.

**Comment by oerdnj** [comment]
Those two?

Apache2: https://httpd.apache.org/docs/trunk/mod/mod_brotli.html
Nginx: https://github.com/google/ngx_brotli

Please don't be terse, but be descriptive as much as possible, when writing issues/bugreport/feature requests.

**Comment by iatpatelishan** [comment]
Yes, this two. And they maybe need brotli deb package.
PS: Next time it would be descriptive :)

**Comment by oerdnj** [comment]
Yes, it needs https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865523 to be resolved first

**Comment by axtho** [comment]
would love to see this also as part of the nginx ppa

**Comment by ConteZero** [comment]
I'm also interested in brotli support for apache

**Comment by frk7z** [comment]
Any news about it @oerdnj ?  I think Tomasz Buchert is waiting for an answer.

**Comment by foxycode** [comment]
@oerdnj Any news in this? I believe issue with libbrotli is now fixed.

**Comment by foxycode** [comment]
@oerdnj Will some donation wpeed this up?

**Comment by moderndeveloperllc** [comment]
@ConteZero This is now available and being built in the Apache 2 builds. @foxycode Are you looking for nginx to be built with brotli support? I too am looking for that. 

@oerdnj It would appear that [this is active fork of the `ngx_brotli`](https://github.com/eustas/ngx_brotli) being actively maintained. It is being used in the macOS [`homebrew`](https://github.com/denji/homebrew-nginx/blob/master/Formula/brotli-nginx-module.rb) repo for nginx-full. FWIW, I have had good luck with the module. Current open issues are primarily questions/concerns; not actual bugs.

**Comment by foxycode** [comment]
@moderndeveloperllc Yes, I definitelly am.

**Comment by moderndeveloperllc** [comment]
@oerdnj Blocking bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865523 has been resolved. @eustas (one of the [current brotli maintainers](https://github.com/google/brotli/commits/master)) has an [nginx module](https://github.com/eustas/ngx_brotli) already if you don't want to start from scratch.

**Comment by gdob** [comment]
Brotli support would be nice.
I just moved my nginx installation from the official Debian repository to deb.sury.org only because of OpenSSL 1.1.1 and the possibility of using TLS v1.3. With Brotli would be a complete package. :)

**Comment by ndum** [comment]
Yes, pleae add it ;)

**Comment by foxycode** [comment]
@oerdnj Can I help somehow to push this thru?

**Comment by patschi** [comment]
Brotli support would be quite nice, indeed. Also https://github.com/google/ngx_brotli/commits/master seems to be actively maintained again, so IMO it would be worth integrating it. Might play quite nice together with TLSv1.3 and HTTP/2. :)

**Comment by NotTsunami** [comment]
@oerdnj Is there anything blocking at this point? The official repo is being maintained again.

**Comment by joglomedia** [comment]
+1 for Nginx mod Brotli since the ngx_brotli

**Comment by morph027** [comment]
Added something here to nginx: https://gitlab.com/packaging/ondrej-nginx-brotli

**Comment by bytesplit** [comment]
@morph027 would you be willing/able to extend your setup with Debian Buster(Stretch) builds?
@oerdnj anything we can help with to unblock this?

On Apache things are really well. I'd love to see this also with NGiNX.

**Comment by Metrax** [comment]
+1
would be a nice feature

**Comment by morph027** [comment]
@bytesplit I'be added stretch and buster to the repo (untested, please use with caution ;) )

**Comment by DronKram** [comment]
Hello Ondřej,
Any updates about this?

**Comment by joglomedia** [comment]
Hi @oerdnj The google/ngx_brotli now seems to be stable - https://github.com/google/ngx_brotli/issues/115#issuecomment-772548865_

**Comment by oerdnj** [comment]
done

**Comment by foxycode** [comment]
I wanted to try, but can't see `libnginx-mod-brotli` or similar when I do `apt-cache search`. Am I doing something wrong?

- `Ubuntu 18.04.5 LTS`
- `deb http://ppa.launchpad.net/nginx/stable/ubuntu bionic main` in apt sources
- Of course I did `apt update`
- `nginx-light 1.18.0-3ubuntu1+bionic1` installed

**Comment by oerdnj** [comment]
> http://ppa.launchpad.net/nginx/stable/ubuntu

this is not the repository you are looking for...

**Comment by foxycode** [comment]
My mistake :) Thanks :)
