### ISSUE TITLE
New version of Apache (2.4.26)

### ISSUE THREAD

**Issue by xephersteel** [oerdnj/deb.sury.org#626]

**Comment by PaddyMann** [comment]
Very keen to see the new version of Apache to address various security issues.

**Comment by ConteZero** [comment]
Debian backported the security fixes to 2.4.25 but up to now has not released 2.4.26.
I think it's related to this bug in 2.4.26:
https://bz.apache.org/bugzilla/show_bug.cgi?id=61202
But that's just my guess, I'm also waiting for 2.4.26, if you use http/2 there are many important fixes and enhancements.

**Comment by oerdnj** [comment]
This has been done, although it looks like there's at least one regression #630 and one possible segfault #629

**Comment by oerdnj** [comment]
As I had to revert the update because of segfaults in http2 module #629

**Comment by darthsteven** [comment]
This seems to have caused serious issues because of this line:

```
<IfModule proxy_fcgi_module>
	ProxyFCGIBackendType GENERIC
</IfModule>
```

which is valid in 2.4.26, but not 2.4.25, so downgrading the packages stops Apache from starting if you have the proxy_fcgi_module module enabled.

**Comment by ConteZero** [comment]
ProxyFCGIBackendType GENERIC
should be used only on 2.4.26 as a workaround until a real patch is released

**Comment by oerdnj** [comment]
Fixed in `+3`, building right now.

**Comment by oerdnj** [comment]
This was the most broken upstream release yet, but I think I tackled all the errors now.
