### ISSUE TITLE
Update request: php-amqp to version 1.9.1

### ISSUE THREAD

**Issue by Articus** [oerdnj/deb.sury.org#627]
Would it be possible to update [php-amqp extension](https://pecl.php.net/package/amqp) to latest stable (1.9.1)? 

1.9.* is around for several months now and it contains several important additions to extension API that are really nice to have for PHP development.

Thanks for awesome repository!

**Comment by oerdnj** [comment]
Ubuntu or Debian? I've just updated both, but the builds have yet to succeed.

**Comment by Articus** [comment]
Currently use Debian Jessie , thanks for fast response! :)

**Comment by oerdnj** [comment]
Looks like all builds have succeeded.
