### ISSUE TITLE
Request upgrade to 1.13.2 for NGINX Mainline PPA

### ISSUE THREAD

**Issue by willfull** [oerdnj/deb.sury.org#633]
Version 1.13.1 of NGINX "mainline" was released back on 30 May, and the newest 1.13.2 update was just released a few days ago.  Would love to see the branch brought up to date, esp. considering my server environment has been affected by a bug that was noted as fixed in the latest version.

As always, _děkuji_ for all of your work, Ondřej.

**Comment by oerdnj** [comment]
Uploaded. Closing the bug in hope it will just build :).
