### ISSUE TITLE
phpquery tool not returning correct error level

### ISSUE THREAD

**Issue by StoneISStephan** [oerdnj/deb.sury.org#634]
$ dpkg -l | grep php-common
ii  php-common                           1:42-1~dotdeb+8.1                all          Common files for PHP packages

$ phpquery -v 7.0 -s fpm -m memcached ; echo $?
memcached (Enabled for fpm by local administrator)
0

$ phpquery -v 7.0 -s fpm -m memcachedd ; echo $?
No module matches memcachedd
0

Desired result:

$ phpquery -v 7.0 -s fpm -m memcachedd ; echo $?
No module matches memcachedd
1

$ cat $(which phpquery)

And I guess the fix is simple:

Just replace

exit $?

With

exit $ret

**Comment by oerdnj** [comment]
The dotdeb version is seriously outdated. This has been already fixed in `44`.
