### ISSUE TITLE
Provide full-length key ID

### ISSUE THREAD

**Issue by mdular** [oerdnj/deb.sury.org#635]
Hey,

when adding the repository via puppetlabs-apt the following warning is thrown:

Warning: /Apt_key[Add key: AC0E47584A7A714D from Apt::Source packages.sury.org]: The id should be a full fingerprint (40 characters), see README.

I was unable to locate a full-length key id. Is it possible to provide one? Thanks :)

**Comment by oerdnj** [comment]
You need to take this to puppetlabs, my README instructions work with full keys, not keyids.
