### ISSUE TITLE
Performance regression of PHP 7.1 in Debian Stretch?

### ISSUE THREAD

**Issue by acasademont** [oerdnj/deb.sury.org#637]
Hi @oerdnj ! We recently upgraded our 2 front-end servers to Stretch and we started seeing our Symfony app times go up by quite a lot (from 35ms to around 45ms). We reverted one of the front-end servers to Jessie and we can clearly see the pretty big difference but we are unable to pinpoint the culprit. We were using PHP 7.1.6 from your repos both in Jessie and Stretch. Any clues on what might be happening here? Maybe some differente compilation flag? We tried Blackfire to profile both versions but even though we can see the performance hit, their service seems to be unable to display low-level functions.

We also tried profiling a simple symfony console command with Valgrind and even though I don't know how to compare both versions I see that there seems to be an important difference in the memory management calls, in Jessie I see php using "memcpy-ss2-unaligned" whereas in Stretch I basically see "memmove-bec-unaligned-erms" instructions. Happy to share those Valgrind profiles if they can be helpful

To be honest I don't have a clue where to look further, any guidance would be really appreciated. Thanks a lot!

**Comment by acasademont** [comment]
![screenshot from 2017-07-05 12-37-10](https://user-images.githubusercontent.com/825021/27860929-032dacae-617f-11e7-99e5-c6d3217dbfbe.png)

Attaching our Newrelic profiling. On July 3rd we switched to Strech and you can see the big hit from 35ms to 45ms. Yesterday afternoon I switched back one of the backends to Jessie and that's why the average it's now around 40ms.

**Comment by oerdnj** [comment]
Hi @acasademont, there are some differences between the two:
* default gcc version
* default hardening build flags

If you have time to play with this, you can check https://wiki.debian.org/Hardening and play with different settings of `export DEB_BUILD_MAINT_OPTIONS = hardening=+all` in `debian/rules` and test each recompilation cycle.

**Comment by divinity76** [comment]
my guess is that there's something related to the brand new 7.1 `DFA optimization framework`, which aims to optimize function calls where the input & return types are known at compile time - just a guess though

**Comment by divinity76** [comment]
Symfony still tries to be php5.6 compatible, and thus makes 0 of use input/return type declarations, right?

**Comment by oerdnj** [comment]
@divinity76 That wouldn't explain difference between Jessie and Stretch - in both cases PHP 7.1 is used, but there are different libraries and different compiler (and different compiler options) used.

**Comment by acasademont** [comment]
Exactly, I was already using 7.1 in Jessie. I'm going to try compiling PHP by hand and let y'all know.

**Comment by acasademont** [comment]
Also, Symfony doesn't use scalar/return type hints but we do in our code.

**Comment by acasademont** [comment]
I must give up on this, the number of extensions I need to compile or manually install from pecl is too much just to be able to have a working set up :(

Do you know if anybody else has seen these performance drops? If it's only us I might just close the issue and just live with it.

**Comment by oerdnj** [comment]
I think you need to recompile just the main package. The extensions should work as they are...
so something like:
```
apt-get source php7.1
apt-get build-dep php7.1
apt-get install devscripts
cd php7.1-<version>
#mangle debian/rules
dch -i # to bump the version number to something recognizable
debuild -uc -us
# install resulting packages
```

should work for you.

**Comment by acasademont** [comment]
I feel so stupid right now! Thanks @oerdnj I'm totally new to Debian packaging, that was easy indeed. I tried a simple build against GCC6 and see how it goes. Gonna compile against 4.9 afterwards.

**Comment by oerdnj** [comment]
You are willing to learn, that's never stupid!

**Comment by oerdnj** [comment]
You are also willin

**Comment by acasademont** [comment]
I'm adding this line

`export CC=/usr/bin/gcc-4.9` to debian/rules

configure seems to be working fine but then it fails

```
configure: exit 1
Died at /usr/share/perl5/Debian/Debhelper/Buildsystem/autoconf.pm line 77.
	cd /home/ulabox/php7.1-7.1.7
debian/rules:322: recipe for target 'override_dh_auto_configure-arch' failed
make[1]: *** [override_dh_auto_configure-arch] Error 2
make[1]: Leaving directory '/home/ulabox/php7.1-7.1.7'
debian/rules:270: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc failed
```

any ideas?

**Comment by acasademont** [comment]
Changing the hardening options to +all,-pie also makes that step fail :( no idea what's going on there

**Comment by oerdnj** [comment]
a) set and export `DH_VERBOSE=1`
b) look for `config.log`

**Comment by oerdnj** [comment]
Also PIE might be required by PHP

**Comment by acasademont** [comment]
@oerdnj DH_VERBOSE=1 is already set on the first line of debian/rules, no config.log though :( Regarding PIE, yeah, I was just trying other stuff, I want my first test to be compiling with GCC 4.9 with hardening=+all, the default right now

**Comment by oerdnj** [comment]
@acasademont Can you upload a full `*.build` log somewhere?

**Comment by acasademont** [comment]
@oerdnj by *.build log you mean the output of the `debuild` command that fails?

**Comment by acasademont** [comment]
The only change I'm trying right now is `debuild --set-envvar CC=/usr/bin/gcc-4.9 -uc -us` changing the CC flag to force GCC 4.9 instead of 6

**Comment by waja** [comment]
@acasademont try ```ls ../*.build``` from your directory you are running ```debuild --set-envvar CC=/usr/bin/gcc-4.9 -uc -us``` after it fails.

**Comment by acasademont** [comment]
sorry again for my lack of Debian packagin skills :(

https://gist.github.com/acasademont/e2ee60908f6e51bc2308009546dd91bc

Steps to build

```
apt-get source php7.1
apt-get build-dep php7.1
apt-get install devscripts
cd php7.1-7.1.7
dch -i 
debuild --set-envvar CC=/usr/bin/gcc-4.9 -uc -us
```

**Comment by waja** [comment]
Seems like there are dependencies missing. For example I spotted some, but there are several more in the log:
```
/usr/bin/ld: cannot find -lintl
```
```
/usr/bin/ld: cannot find -lstdc++
```

**Comment by oerdnj** [comment]
Did you do: `apt-get build-dep php7.0`?

**Comment by acasademont** [comment]
Well, seems like the gcc4.9 package was already there from the Jessie => Stretch upgrade, probably related to that...

**Comment by oerdnj** [comment]
Hi @acasademont, did you come to any conclusions about the performance drop on Debian stretch?

**Comment by acasademont** [comment]
hey @oerdnj sorry i didn't see that :( unfortunately no, i don't have any more clues so yeah, it might be better to just close the issue. thx for your patience!!!
