### ISSUE TITLE
php7.1 source on sury.org

### ISSUE THREAD

**Issue by free6k** [oerdnj/deb.sury.org#638]
Hi all
```
apt-get install php7.1
```
installed is fine
```
apt-get source php7.1
```
cant found package...

Why so? I use source for recompiling 'intl' extension

thanks fo answer

**Comment by oerdnj** [comment]
Distribution? Your sources list for repository? I don't have  crystal ball...

**Comment by free6k** [comment]
Usually i do command apt-get source , when i used dotdeb php7.0
Now i use sury.org repo for php7.1
I have next problem. Debian 8 (Jessie)
php7.1 install for system is very good
But i want download sources for php7.1 from sury.org for recompiling few modules with configure with my options
But! from sury.org apt-get tell about sources not found
command apt-get source php7.1 don't work. it worked with dotdeb repo apt-get source php7.0...

Why so? :) sorry for my english

**Comment by oerdnj** [comment]
Since you didn't answer the second question, here I am asking it again:
How does your `/etc/apt/sources.list` and files in `/etc/apt/sources.list.d/*list` look like?

**Comment by free6k** [comment]
```
cat /etc/apt/sources.list.d/packages_sury_org_php.list
deb http://packages.sury.org/php/ jessie main
```

**Comment by oerdnj** [comment]
As I though, you are kissing source repository. An excellent opportunity for you to learn more about your system.

**Comment by free6k** [comment]
For users with same problem. I forgot add deb-src to source.list
```
deb-src http://packages.sury.org/php/ jessie main
```
