### ISSUE TITLE
Update to 5.4.40

### ISSUE THREAD

**Issue by mivale** [oerdnj/deb.sury.org#64]
Hi,

Will you be releasing the 5.4.40 release on the ppa? I've noticed that this version is out for some time already: http://php.net/archive/2015.php#id2015-04-16-3

We're running into this bug: https://bugs.php.net/bug.php?id=69293 which has been fixed in 5.5.40 :-)

**Comment by oerdnj** [comment]
Yes, I expect that I will be able to work on PPAs tomorrow 

On April 30, 2015 4:25:46 PM GMT+02:00, Michiel van Leening <notifications@github.com> wrote:
>Hi,
>
>Will you be releasing the 5.4.40 release on the ppa? I've noticed that
>this version is out for some time already:
>http://php.net/archive/2015.php#id2015-04-16-3
>
>We're running into this bug: https://bugs.php.net/bug.php?id=69293
>which has been fixed in 5.5.40 :-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/64

-- 
Ondřej Surý

**Comment by oerdnj** [comment]
Done
