### ISSUE TITLE
wrong version for php-7.0 package version? requested PHP extension sqlite3 has the wrong version (7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738)

### ISSUE THREAD

**Issue by hashar** [oerdnj/deb.sury.org#642]
We are using sury php7.0 packages.  One of our build started failing on July 6th after the sury php7.0 package got installed. Composer complains with:
```
    - Installation request for etsy/phan 0.7 -> satisfiable by etsy/phan[0.7].
    - etsy/phan 0.7 requires ext-sqlite3 0.7-dev -> the requested PHP extension sqlite3 has the wrong version (7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738) installed.
```

The `composer.json` depends on `etsy/phan==0.7` which in turns requires `ext-sqlite3 0.7-dev`.
```
$ apt-cache policy php7.0-sqlite
php7.0-sqlite3:
  Installed: 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738
  Candidate: 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738
  Version table:
 *** 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738 0
        500 https://packages.sury.org/php/ jessie/main amd64 Packages
```

Looking at the package changelog, it seems a `7.0.21-1` got published immediately followed by a snapshot version `7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738`.  I suspect that the later is the version detected by composer and it fails to match it as `0.7-dev`.

```
$ zcat changelog.Debian.gz
php7.0 (7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738) unstable; urgency=medium

  ** SNAPSHOT build @57c738a72fd43c9428cf8f952b410cfbb5ba2c96 **

  * UNRELEASED

 -- Ondřej Surý <ondrej@sury.org>  Thu, 06 Jul 2017 11:22:55 +0200

php7.0 (7.0.21-1) unstable; urgency=medium

  * New upstream version 7.0.21
  * Rebase patches on top of PHP 7.0.21

 -- Ondřej Surý <ondrej@debian.org>  Thu, 06 Jul 2017 11:01:45 +0200

php7.0 (7.0.20-2) unstable; urgency=medium

  * Add Ferenc Kovacs signing key to upstream GPG keyring
  * Add upstream patch to fix broken support for HOST/PATH ini sections

 -- Ondřej Surý <ondrej@debian.org>  Wed, 14 Jun 2017 07:30:04 +0200
```

Expected:
```
$ composer show -p|grep sqlite3
ext-sqlite3         0.7-dev  The sqlite3 PHP extension
```

(actual missing, gotta reproduce sorry).
(our downstream bug https://phabricator.wikimedia.org/T169904)

**Comment by oerdnj** [comment]
I don't think the PHP packages are at fault. Seems like composer or just the etsy/phan dependency definition to me. Perhaps `composer` has some internal mappings that needs to be updated? 

Nothing has changed in the packages apart from the upstream version number, do either this is composer or upstream bug. I strongly suspect composer, try taking it there.

**Comment by hashar** [comment]
I have dig a little more using the current latest package.  It seems the sqlite3 module version changed from `0.7-dev` to `7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738`:

**Good**
```
$ php --version
PHP 7.0.20-2+0~20170614060657.1+jessie~1.gbp37279a (cli) (built: Jun 14 2017 06:28:15) ( NTS )

$ composer show -p|grep sqlite3
ext-sqlite3         0.7-dev  The sqlite3 PHP extension

$ php7.0 --ri sqlite3|grep version
SQLite3 module version => 0.7-dev
```

**Bad**
```
$ php --version
PHP 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738 (cli) (built: Jul  6 2017 09:45:30) ( NTS )

$ composer show -p|grep sqlite3
ext-sqlite3         7.0.21   The sqlite3 PHP extension (actual version: 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738)

$ php7.0 --ri sqlite3|grep version
SQLite3 module version => 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738
```

You seem to use git buildpackage / jenkins-debian-glue and from the changelog entries, the currently available version seems to be a snapshot instead of a normal release, so most probably that change the way the version is filled for extensions.

Changelog:
```
php7.0 (7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738) unstable; urgency=medium
  ** SNAPSHOT build @57c738a72fd43c9428cf8f952b410cfbb5ba2c96 **
  * UNRELEASED
 -- Ondřej Surý <ondrej@sury.org>  Thu, 06 Jul 2017 11:22:55 +0200

php7.0 (7.0.21-1) unstable; urgency=medium
  * New upstream version 7.0.21
  * Rebase patches on top of PHP 7.0.21
 -- Ondřej Surý <ondrej@debian.org>  Thu, 06 Jul 2017 11:01:45 +0200
```

There are a bunch of other PHP extensions that have the same issue:

pdo_pgsql: 1.0.2 -> 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738

```
sysvsem
sysvshm
```
Versus:
```
sysvsem
Version => 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738
sysvshm
Version => 7.0.21-1+0~20170706092253.2+jessie~1.gbp57c738
```

Etc

**Comment by oerdnj** [comment]
...or upstream feature:

That's https://github.com/php/php-src/commit/c3b910370c5c92007c3e3579024490345cb7f9a7

**Comment by hashar** [comment]
That is a change in php-src between 7.0.20 and 7.0.21:
```
$ git grep -e 'PHP_SQLITE3_VERSION\s' php-7.0.20
php-7.0.20:ext/sqlite3/php_sqlite3.h:#define PHP_SQLITE3_VERSION         "0.7-dev"
```
```
$ git grep -e 'PHP_SQLITE3_VERSION\s' php-7.0.21
php-7.0.21:ext/sqlite3/php_sqlite3.h:#define PHP_SQLITE3_VERSION        PHP_VERSION
```

https://github.com/php/php-src/commit/c3b910370c5c92007c3e3579024490345cb7f9a7

**Comment by hashar** [comment]
> ...or upstream feature:

@oerdnj indeed. Thank you and sorry for the trouble :]

**Comment by oerdnj** [comment]
I just knew I didn't change anything in the packaging itself, it just took a full blown device with git and keyboard  to find the culprit.
