### ISSUE TITLE
PHP 7.1 package does not use bundled GD

### ISSUE THREAD

**Issue by langemeijer** [oerdnj/deb.sury.org#644]
I assume this because imageantialias() is not available. Are there still valid technical reasons to use the separately packaged lib instead of the bundled one? Debian Jessie is providing me with LibGD 2.1.0 which I hope has the CVE's patched, but I'm not sure of that.

**Comment by oerdnj** [comment]
Yes, it is patched, and the technical reason is to not use bundled libraries because of security implications (you have to patch all over places in case of security vulnerability).
