### ISSUE TITLE
Upgrade Apache to 2.4.27

### ISSUE THREAD

**Issue by swiffer** [oerdnj/deb.sury.org#646]
seems Apache 2.4.27 provides fixes introduced with 2.4.26
http://www.apache.org/dist/httpd/CHANGES_2.4.27

**Comment by oerdnj** [comment]
Done, I also tested upgrades from the previous version with workaround and it seems nothing breaks on upgrade.

**Comment by swiffer** [comment]
can confirm that it's working fine (php-fpm 7.1.7, mpm_event, mod_http2)

**Comment by andrii-trush** [comment]
It still not working for me

**Comment by oerdnj** [comment]
@andrii-trush What does "It still not working for me" mean?

**Comment by andrii-trush** [comment]
@oerdnj  ERR_CONNECTION_REFUSED with https
and Error 503 Backend fetch failed with http, i'm using varnish for port 80

**Comment by oerdnj** [comment]
@andrii-trush You need to take it to upstream. There were no packaging changes.
