### ISSUE TITLE
HTTP/2 broken in Zesty after upgrade to 2.4.27

### ISSUE THREAD

**Issue by Vilican** [oerdnj/deb.sury.org#648]
I am running Apache2 on Ubuntu 17.04 server. After last upgrade from Apache 2.4.26 to 2.4.27, HTTP/2 stopped working on my site. I have http2 module enabled and in `apache2.conf` I have this:

```
Protocols h2 h2c http/1.1
H2Upgrade on
```

Neither my browser (Chrome) or other tests like cURL with HTTP/2 can connect to my site via this protocol.

Can you please recheck whether the http2 module is working properly?

Thank you

**Comment by oerdnj** [comment]
It's not broken. It's disabled for mpm_prefork due incompatibility. Read apache2 changelog.
