### ISSUE TITLE
Compile PHP with --enable-debug Ubuntu 16.04

### ISSUE THREAD

**Issue by js94x** [oerdnj/deb.sury.org#651]
Hello,

I wanted to build a debian Package from PHP7.0.21 with the compile flag --enable-debug on my Ubuntu 16.04 system.

My approach was the following:

**Download the source code and build files**
1. add-apt-repository ppa:ondrej/php
2. comment out the deb-src in /etc/apt/
3. apt-get update
4. apt-get source php7.0
5. apt-get build-dep php7.0

Then I changed Line 182 of the file debian/rules from --disalbe-debug to --enable-debug.

Also I ran 

`DEB_BUILD_OPTIONS=nocheck debuild`

and got many errors like the following from dh_install

```
...
dh_install: usr/lib/php/20151012-debug/mbstring.a exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/php/20151012-debug/iconv.a exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/php/20151012-debug/gd.a exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/php/20151012-debug/pdo.a exists in debian/tmp but is not installed to anywhere
dh_install: missing files, aborting
debian/rules:488: recipe for target 'override_dh_install-arch' failed
make[1]: *** [override_dh_install-arch] Error 2
make[1]: Leaving directory '/tmp/php7.0-7.0.21'
debian/rules:274: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

It seems that this problem comes from **dh_install --fail-missing**. Furthermore I tried to get some more information but I wasn't able to track the problem down any further.

I would really appreciate any help.

**Comment by oerdnj** [comment]
You need to update `d/rules` so `PHP_ZEND_VERSION` actually matches `20151012-debug`, appending `-debug` to
```
PHP_ZEND_VERSION     := $(shell $(SED) -ne 's/\#define ZEND_MODULE_API_NO //p' Zend/zend_modules.h)$(ZTS)
```
might just work. If case it doesn't this is a general direction that needs to be fixed.
