### ISSUE TITLE
[Feature Request] php-dav

### ISSUE THREAD

**Issue by stephenreay** [oerdnj/deb.sury.org#652]
There is a nice little webdav client at https://github.com/jedisct1/PHP-WebDAV-extension

It doesn't seem to be packaged for Debian anywhere - any chance you could add this?

Cheers!

Stephen

**Comment by oerdnj** [comment]
This doesn't have an official PECL release nor even upstream release and the last update was in 2017. Sorry, but this is not going to happen.
