### ISSUE TITLE
again bug 7.0 to 7.1

### ISSUE THREAD

**Issue by ang3lx** [oerdnj/deb.sury.org#655]
Hello,
i've installed on ubuntu 16.04 only 5.6 and 7.0
after last apt update/upgrade some 7.1 packages are installed, and default php version now is 7.1

Also system would remove php7.0-curl php7.0-gd php7.0-imap php7.0-intl php7.0-mcrypt php7.0-pspell php7.0-recode php7.0-tidy php7.0-xmlrpc zlib1g-dev because are not requested

if I try to remove 
`apt-get remove php7.1-cli php7.1-common php7.1-fpm`
I get
<pre>Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti sono stati installati automaticamente e non sono più richiesti:
  aspell aspell-en dictionaries-common emacsen-common libaspell15 libssl1.0.2 libtidy-0.99-0 libtidy5 libvpx3 libxmlrpc-epi0 linux-headers-4.4.0-45 linux-headers-4.4.0-45-generic linux-headers-4.4.0-47 linux-headers-4.4.0-47-generic linux-headers-4.4.0-51
  linux-headers-4.4.0-51-generic linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-headers-4.4.0-57 linux-headers-4.4.0-57-generic linux-headers-4.4.0-59 linux-headers-4.4.0-59-generic linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic
  linux-headers-4.4.0-63 linux-headers-4.4.0-63-generic linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-67 linux-headers-4.4.0-67-generic linux-headers-4.4.0-70 linux-headers-4.4.0-70-generic linux-headers-4.4.0-71
  linux-headers-4.4.0-71-generic linux-headers-4.4.0-72 linux-headers-4.4.0-72-generic linux-headers-4.4.0-75 linux-headers-4.4.0-75-generic linux-headers-4.4.0-78 linux-headers-4.4.0-78-generic linux-headers-4.4.0-79 linux-headers-4.4.0-79-generic
  linux-headers-4.4.0-81 linux-headers-4.4.0-81-generic linux-image-4.4.0-45-generic linux-image-4.4.0-47-generic linux-image-4.4.0-51-generic linux-image-4.4.0-53-generic linux-image-4.4.0-57-generic linux-image-4.4.0-59-generic linux-image-4.4.0-62-generic
  linux-image-4.4.0-63-generic linux-image-4.4.0-66-generic linux-image-4.4.0-67-generic linux-image-4.4.0-70-generic linux-image-4.4.0-71-generic linux-image-4.4.0-72-generic linux-image-4.4.0-75-generic linux-image-4.4.0-78-generic linux-image-4.4.0-79-generic
  linux-image-4.4.0-81-generic linux-image-extra-4.4.0-45-generic linux-image-extra-4.4.0-47-generic linux-image-extra-4.4.0-51-generic linux-image-extra-4.4.0-53-generic linux-image-extra-4.4.0-57-generic linux-image-extra-4.4.0-59-generic
  linux-image-extra-4.4.0-62-generic linux-image-extra-4.4.0-63-generic linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-67-generic linux-image-extra-4.4.0-70-generic linux-image-extra-4.4.0-71-generic linux-image-extra-4.4.0-72-generic
  linux-image-extra-4.4.0-75-generic linux-image-extra-4.4.0-78-generic linux-image-extra-4.4.0-79-generic linux-image-extra-4.4.0-81-generic php7.0-curl php7.0-imap php7.0-intl php7.0-pspell php7.0-recode php7.0-tidy php7.0-xmlrpc zlib1g-dev
Usare "apt autoremove" per rimuoverli.
I seguenti pacchetti saranno RIMOSSI:
  php-curl php-fpm php-gd php-imap php-intl php-mbstring php-mcrypt php-mysql php-pspell php-recode php-tidy php-xmlrpc php7.1-cli php7.1-common php7.1-curl php7.1-fpm php7.1-gd php7.1-imap php7.1-intl php7.1-json php7.1-mbstring php7.1-mcrypt php7.1-mysql
  php7.1-opcache php7.1-pspell php7.1-readline php7.1-recode php7.1-tidy php7.1-xmlrpc
0 aggiornati, 0 installati, 29 da rimuovere e 0 non aggiornati.
Dopo quest'operazione, verranno liberati 17,9 MB di spazio su disco.</pre>

there is a package that require 7.1, how can remove safely 7.1?

**Comment by oerdnj** [comment]
```
Package: php-fpm
Source: php-defaults (52+0~20170614061845.1+stretch~1.gbpd2ab76)
Version: 1:7.1+52+0~20170614061845.1+stretch~1.gbpd2ab76
Architecture: all
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Installed-Size: 12
Depends: php7.1-fpm
Priority: optional
Section: php
Filename: pool/main/p/php-defaults/php-fpm_7.1+52+0~20170614061845.1+stretch~1.gbpd2ab76_all.deb
Size: 5416
SHA256: 4a33b3c76eae22acad08f93a7eaf083c96907021ea65592c2378a794537da80a
SHA1: 68d7227307bf687551ac1b7460e5a4e97985dfad
MD5sum: 9a710b9b08b6d221244a1db939c41921
Description: server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
 This package provides the Fast Process Manager interpreter that runs
 as a daemon and receives Fast/CGI requests.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on latest stable
 PHP version (currently 7.1).
```

Note the: *This package is a dependency package, which depends on latest stable PHP version (currently 7.1).*

So you can safely remove all the: `php-curl php-fpm php-gd php-imap php-intl php-mbstring php-mcrypt php-mysql php-pspell php-recode php-tidy php-xmlrpc` packages.
