### ISSUE TITLE
Missing Extensions

### ISSUE THREAD

**Issue by c33s** [oerdnj/deb.sury.org#656]
being spoiled from dotdeb.org i miss the following extensions on your apt server: 

- php7.1-geoip 
- php7.1-imagick 
- php7.1-memcached 
- php7.1-mongodb 
- php7.1-redis 
- php7.1-ssh2 
- php7.1-xdebug 
- php7.1-apcu 
- php7.1-apcu-bc 

any change to get them into your repo?

**Comment by oerdnj** [comment]
No, they are not missing.

**Comment by c33s** [comment]
@oerdnj sorry my fault, i generated a list of all packages of your repo with some kind of `grep ^Package: /var/lib/apt/lists/ppa.launchpad.net_*_Packages` https://serverfault.com/a/282804

it looks like this method can't find aliases.
