### ISSUE TITLE
php5.6-mbstring missing from deb

### ISSUE THREAD

**Issue by alfonsius** [oerdnj/deb.sury.org#657]
Err:1 https://packages.sury.org/php stretch/main amd64 php5.6-mbstring amd64 5.6.31-1+0~20170711121556.3+stretch~1.gbp94bb71
  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php5.6/php5.6-mbstring_5.6.31-1+0~20170711121556.3+stretch~1.gbp94bb71_amd64.deb  404  Not Found

**Comment by oerdnj** [comment]
Run `apt-get update` again in couple of minutes.
