### ISSUE TITLE
Dumb question: where is the php7.1 cli located?

### ISSUE THREAD

**Issue by MPLLC** [oerdnj/deb.sury.org#658]
I need to setup a cron job, but I can't find where the cli is actually located.  Debian 8, PHP 7.1 from the PPA.   Please help.

**Comment by oerdnj** [comment]
Like the `apt-cache search php7.1-cli` or `dpkg -L php7.1-cli` or `which php7.1`.

Also please don't abuse issues meant for packaging to learn system basics there are other more suite fora for that.
