### ISSUE TITLE
php-libsodium - 2.x Available (BC Break)

### ISSUE THREAD

**Issue by moderndeveloperllc** [oerdnj/deb.sury.org#659]
The php-libsodium extension is now on it's 2.x version on PECL, but it causes an interesting issue for package maintainers such as yourself. The new version compiles a `sodium.so` extension instead of `libsodium.so` and is no longer PHP 5.x compatible. It's also a pretty complete userland code BC break as the namespace goes from `\Sodium` to the core namespace (what will be in PHP 7.2), so all function calls have to be changed.

The author has indicated that [he will not be creating a separate PECL project for 2.x](https://github.com/jedisct1/libsodium-php/issues/145), so I'm curious how you will handle packaging this.

**Comment by oerdnj** [comment]
I can amalgate sources for version 5 and 7, but best course of action might be to create new package called php-sodium just for PHP 7.0 and 7.1, and let the old PHP-libsodium deprecate on it's own.

**Comment by moderndeveloperllc** [comment]
I figured splitting would be the best course of action to keep the package name the same as the extension. Similar to the mongo and mongodb extensions. I was just wanting to bring this change to your attention. You can close this ticket or leave it open until the new package is done - whichever you wish. And thanks for maintaining such an awesome PPA!

**Comment by oerdnj** [comment]
@moderndeveloperllc Could you please try `php-sodium` package from `ppa:ondrej/php-qa`?

**Comment by oerdnj** [comment]
Oh, wait for `+2` version. The `+1` didn't have ini files.

**Comment by moderndeveloperllc** [comment]
@oerdnj I was able to load it up on PHP 7.1.7. I did notice a few things:

1. The script did not trigger an Apache restart. I forget if that's the same behavior for other php extensions or not.
2. If the `php-libsodium` package is loaded concurrently (possible due to differing namespaces and extension name) I get `PHP Fatal error:  sodium_init() in Unknown on line 0` on CLI runs (even `php -i`), but the script *does* work. The scripts also work with the libapache-mod-php interpreter. I had always thought a "PHP Fatal error" would stop script execution, but I guess not in this case. I believe this error is because one of the two modules has already [initialized the core libsodium library](https://github.com/jedisct1/libsodium-php/search?utf8=✓&q=sodium_init&type=) and the second module is trying to re-init it, causing the error. This may mean you would wish to have a note added to `php-sodium` indicating this error can occur when using the extension with `php-libsodium`, or just declare the two extensions as being conflicts that would cause an uninstall of the other.

**Comment by jedisct1** [comment]
[this](https://github.com/jedisct1/libsodium-php/commit/ecbf0f15206d6898b26fc4c12a5c03a2e1609995) should have fixed it.

I can release a new version with that change and publish it to PECL if you like.

**Comment by oerdnj** [comment]
`php7.2_7.2.0~beta3-2*` has the native sodium extension enabled. PHP 7.0 and PHP 7.1 are supported via `php-sodium` package. PHP 5.6 users should just update to PHP 7.x as I've just deleted `php-libsodium` as I don't have any intention of having unsupported *crypto* extension in the repository; that would be a call for trouble.

**Comment by lferro9000** [comment]
In my case, it was receiving this error with a MacOS installation with homebrew. 

It was failing because as indicated by the last comment, the library has been included in the global namespace. 

As i have been testing the PHP 7.2 since alpha on this machine, the extension was also being loaded. 

Removing the extension sorted the issue.
