### ISSUE TITLE
 apache2-mpm-prefork : Depends: apache2 (= 2.4.7-1ubuntu4.17) but 2.4.27-3.0+ubuntu14.04.1+deb.sury.org+3 is to be installed

### ISSUE THREAD

**Issue by necrophcodr** [oerdnj/deb.sury.org#662]
I'm not sure where to go from here, this is not a fun issue.

apt-get install apache2-mpm-prefork
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2-mpm-prefork : Depends: apache2 (= 2.4.7-1ubuntu4.17) but 2.4.27-3.0+ubuntu14.04.1+deb.sury.org+3 is to be installed
E: Unable to correct problems, you have held broken packages.

OS: Ubuntu 14.04.5

**Comment by oerdnj** [comment]
Just don't install `apache2-mpm-prefork`:

> This is a transitional package to apache2 for users of apache2-mpm-prefork and can be safely removed after the installation is complete.
