### ISSUE TITLE
php-amqp/librabbitmq package broken with latest update (trusty)

### ISSUE THREAD

**Issue by deains** [oerdnj/deb.sury.org#666]
Since Friday's issues, this package has become uninstallable on Ubuntu Trusty due to a malformed libssl dependency.

Specifically, the package php-amqp depends on librabbitmq4 (>= 0.6.0). librabbitmq4 then depends on libssl1.0.2 (>= 1.0.2d), however this package no longer exists, it seems to have been replaced with libssl1.1.

Assuming librabbitmq4 is compatible with libssl1.1, this should be a minor fix. If not, well, best of luck working this out.

**Comment by oerdnj** [comment]
Should be ok now. I have also updated `librabbitmq` to `0.8.0` in the same go.
