### ISSUE TITLE
Where is php5.6?

### ISSUE THREAD

**Issue by smohring** [oerdnj/deb.sury.org#667]
Hi,

I was wondering, why i dont get any php5.6 packages? 
Are they gone?

sudo apt install php5.6-cli php7.0-cli php7.1-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5.6-cli
E: Couldn't find any package by glob 'php5.6-cli'
E: Couldn't find any package by regex 'php5.6-cli'

**Comment by oerdnj** [comment]
You are running end-of-life rrlease

**Comment by smohring** [comment]
So there is no way to install php 5.6 anymore? I would need it for old projects...thanks for your help!

**Comment by oerdnj** [comment]
Run a supported release.
