### ISSUE TITLE
php-pear broken on php 7.2

### ISSUE THREAD

**Issue by macintoshplus** [oerdnj/deb.sury.org#668]
The package php-pear is broken if use only PHP 7.2.

Command: `pear install xdebug`
Result: `PHP Fatal error:  Cannot use result of built-in function in write context in /usr/share/php/Archive/Tar.php on line 639`

Edit:
The version 1.4.3 work fine but I have copy the `Tar.php` file manually. 
https://github.com/pear/Archive_Tar/releases/tag/1.4.3

**Comment by oerdnj** [comment]
Fixed in `1:1.10.5+submodules+notgz-1+ubuntu<ver>+deb.sury.org+1`

**Comment by chw131** [comment]
Yes, copy the 1.4.3 "Tar.php" file manually into
%php%\pear\Archive\  folder solves the problem.
Cannot use upgrade or install since Tar.php is needed for both actions.
