### ISSUE TITLE
PHP 5.4.40-1+deb.sury.org~precise+2 does not work because of gd.so

### ISSUE THREAD

**Issue by dsteinkopf** [oerdnj/deb.sury.org#67]
Today after apt-get upgr/date my apache/php does work any more because of this error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/gd.so' - /usr/lib/php5/20100525/gd.so: undefined symbol: gdGetC in Unknown on line 0
```

As this is a production system and everything worked fine until this update, I assume this is an error in the latest update.

If I can help to solve this problem by providing more info please tell me.

Thank you.

**Comment by dsteinkopf** [comment]
Maybe it helps to know that other distributions had a (in my eyes) similiar problem. e.g.

https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1188070
http://askubuntu.com/questions/329210/php5-4-unable-to-load-dynamic-library-gd-so-undefined-symbol-gdgetc

**Comment by oerdnj** [comment]
Hi, 

could you send me output of

dpkg -l libgd*

Did you upgrade libgd as well or just php? 

Ondřej 

On May 3, 2015 10:52:23 AM GMT+02:00, dsteinkopf <notifications@github.com> wrote:
>Today after apt-get upggr/date my apache/php does work any more because
>of this error:
>
>```
>PHP Warning:  PHP Startup: Unable to load dynamic library
>'/usr/lib/php5/20100525/gd.so' - /usr/lib/php5/20100525/gd.so:
>undefined symbol: gdGetC in Unknown on line 0
>```
>
>As this is a production system and everything worked fine until this
>update, I assume this is an error in the latest update.
>
>If I can help to solve this problem by providing more info please tell
>me.
>
>Thank you.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/67

-- 
Ondřej Surý

**Comment by Maartenlameris** [comment]
Same problem overhere,

output from my host:

root@apache:~# dpkg -l libgd*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version                          Description
+++-================================-================================-================================================================================
un  libgd-gd1-noxpm-perl             <none>                           (no description available)
un  libgd-gd1-perl                   <none>                           (no description available)
ii  libgd-gd2-noxpm-perl             1:2.46-2build1                   Perl module wrapper for libgd - gd2 variant without XPM support
un  libgd-gd2-perl                   <none>                           (no description available)
un  libgd-gd2-xpm-perl               <none>                           (no description available)
un  libgd-noxpm-perl                 <none>                           (no description available)
un  libgd-perl                       <none>                           (no description available)
un  libgd-tools                      <none>                           (no description available)
un  libgd2                           <none>                           (no description available)
un  libgd2-noxpm                     <none>                           (no description available)
ii  libgd2-xpm                       2.0.36~rc1~dfsg-6ubuntu2         GD Graphics Library version 2
ii  libgd3                           2.1.0-5+deb.sury.org~precise+1   GD Graphics Library
ii  libgdbm3                         1.8.3-10                         GNU dbm database routines (runtime version)
rc  libgdk-pixbuf2.0-0               2.26.1-1ubuntu1.1                GDK Pixbuf library
un  libgdk-pixbuf2.0-common          <none>                           (no description available)

**Comment by tudo75** [comment]
same issue also for me

dpkg -l libgd*

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Nome                     Versione                 Descrizione
+++-========================-========================-================================================================
un  libgd-tools              <nessuna>                (nessuna descrizione disponibile)
un  libgd2                   <nessuna>                (nessuna descrizione disponibile)
un  libgd2-noxpm             <nessuna>                (nessuna descrizione disponibile)
ii  libgd2-xpm               2.0.36~rc1~dfsg-6ubuntu2 GD Graphics Library version 2
ii  libgd3                   2.1.0-5+deb.sury.org~pre GD Graphics Library
ii  libgdbm-dev              1.8.3-10                 GNU dbm database routines (development files)
un  libgdbm1-dev             <nessuna>                (nessuna descrizione disponibile)
ii  libgdbm3                 1.8.3-10                 GNU dbm database routines (runtime version)
un  libgdbmg1-dev            <nessuna>                (nessuna descrizione disponibile)
ii  libgdk-pixbuf2.0-0       2.26.1-1ubuntu1.1        GDK Pixbuf library
ii  libgdk-pixbuf2.0-common  2.26.1-1ubuntu1.1        GDK Pixbuf library - data files

**Comment by vkimball** [comment]
I'm having the same problem:

 dpkg -l libgd*

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version                     Description
+++-===========================-===========================-======================================================================
un  libgd-tools                 <none>                      (no description available)
un  libgd2                      <none>                      (no description available)
un  libgd2-noxpm                <none>                      (no description available)
ii  libgd2-xpm                  2.0.36~rc1~dfsg-6ubuntu2    GD Graphics Library version 2
ii  libgd3                      2.1.0-5+deb.sury.org~precis GD Graphics Library
ii  libgdbm3                    1.8.3-10                    GNU dbm database routines (runtime version)

**Comment by wweich** [comment]
I have the same problem on my Ubuntu 12.04.5 server.
dpkg -l libgd*
```
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                           Version                        Beschreibung
+++-==============================-==============================-=============================================
un  libgd-dev                      <keine>                        (keine Beschreibung vorhanden)
ii  libgd-tools                    2.1.0-5+deb.sury.org~precise+1 GD command line tools and example code
un  libgd2                         <keine>                        (keine Beschreibung vorhanden)
un  libgd2-noxpm                   <keine>                        (keine Beschreibung vorhanden)
ii  libgd2-xpm                     2.0.36~rc1~dfsg-6ubuntu2       GD Graphics Library version 2
ii  libgd3                         2.1.0-5+deb.sury.org~precise+1 GD Graphics Library
un  libgdbm-ruby1.8                <keine>                        (keine Beschreibung vorhanden)
ii  libgdbm3                       1.8.3-10                       GNU dbm database routines (runtime version)
ii  libgdk-pixbuf2.0-0             2.26.1-1ubuntu1.1              GDK Pixbuf library
ii  libgdk-pixbuf2.0-common        2.26.1-1ubuntu1.1              GDK Pixbuf library - data files
un  libgdu-gtk0                    <keine>                        (keine Beschreibung vorhanden)
un  libgdu0                        <keine>                        (keine Beschreibung vorhanden)
```

The packages I upgraded from your PPA:
```
libapache2-mod-php5 5.4.40-1+deb.sury.org~precise+2
libgd3 2.1.0-5+deb.sury.org~precise+1
libgd-tools 2.1.0-5+deb.sury.org~precise+1
php5 5.4.40-1+deb.sury.org~precise+2
php5-cli 5.4.40-1+deb.sury.org~precise+2
php5-common 5.4.40-1+deb.sury.org~precise+2
php5-curl 5.4.40-1+deb.sury.org~precise+2
php5-dev 5.4.40-1+deb.sury.org~precise+2
php5-gd 5.4.40-1+deb.sury.org~precise+2
php5-imap 5.4.40-1+deb.sury.org~precise+2
php5-intl 5.4.40-1+deb.sury.org~precise+2
php5-ldap 5.4.40-1+deb.sury.org~precise+2
php5-mcrypt 5.4.40-1+deb.sury.org~precise+2
php5-mysql 5.4.40-1+deb.sury.org~precise+2
php5-pgsql 5.4.40-1+deb.sury.org~precise+2
php5-readline 5.4.40-1+deb.sury.org~precise+2
php5-sqlite 5.4.40-1+deb.sury.org~precise+2
php5-tidy 5.4.40-1+deb.sury.org~precise+2
php5-xsl 5.4.40-1+deb.sury.org~precise+2
php-pear 5.4.40-1+deb.sury.org~precise+2
```

**Comment by m4lvin** [comment]
Same problem here, see below ...
Any other information which could be useful?

    ... :~# php -a
    PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/gd.so' - /usr/lib/php5/20100525/gd.so: undefined symbol: gdGetC in Unknown on line 0
    Interactive mode enabled

    php > quit
    ... :~# file /usr/lib/php5/20100525/gd.so
    /usr/lib/php5/20100525/gd.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x3b4f08ef94cbd97257d2adb83e7d340d8607b09e, stripped

    ... :~# dpkg -l php*|grep ii
    ii  php-pear                         5.4.40+real-1+deb.sury.org~precise+2  PEAR - PHP Extension and Application Repository
    ii  php-xml-parser                   1.3.2-4                               PHP PEAR module for parsing XML
    ii  php5                             5.4.40+real-1+deb.sury.org~precise+2  server-side, HTML-embedded scripting language (metapackage)
    ii  php5-cgi                         5.4.40+real-1+deb.sury.org~precise+2  server-side, HTML-embedded scripting language (CGI binary)
    ii  php5-cli                         5.4.40+real-1+deb.sury.org~precise+2  command-line interpreter for the php5 scripting language
    ii  php5-common                      5.4.40+real-1+deb.sury.org~precise+2  Common files for packages built from the php5 source
    ii  php5-curl                        5.4.40+real-1+deb.sury.org~precise+2  CURL module for php5
    ii  php5-gd                          5.4.40+real-1+deb.sury.org~precise+2  GD module for php5
    ii  php5-geoip                       1.0.8+repack.1-1~precise+1            GeoIP module for php5
    ii  php5-imagick                     3.1.0~rc2-1~precise+1                 ImageMagick module for php5
    ii  php5-imap                        5.4.40+real-1+deb.sury.org~precise+2  IMAP module for php5
    ii  php5-intl                        5.4.40+real-1+deb.sury.org~precise+2  internationalisation module for php5
    ii  php5-mcrypt                      5.4.40+real-1+deb.sury.org~precise+2  MCrypt module for php5
    ii  php5-mysql                       5.4.40+real-1+deb.sury.org~precise+2  MySQL module for php5
    ii  php5-pgsql                       5.4.40+real-1+deb.sury.org~precise+2  PostgreSQL module for php5
    ii  php5-readline                    5.4.40+real-1+deb.sury.org~precise+2  Readline module for php5
    ii  php5-sqlite                      5.4.40+real-1+deb.sury.org~precise+2  SQLite module for php5
    ii  php5-tidy                        5.4.40+real-1+deb.sury.org~precise+2  tidy module for php5
    ... :~# dpkg -l libgd*|grep ii
    ii  libgd2-noxpm                     2.0.36~rc1~dfsg-6ubuntu2              GD Graphics Library version 2 (without XPM support)
    ii  libgd3                           2.1.0-5+deb.sury.org~precise+1        GD Graphics Library
    ii  libgdbm3                         1.8.3-10                              GNU dbm database routines (runtime version)
    ii  libgdk-pixbuf2.0-0               2.26.1-1ubuntu1.1                     GDK Pixbuf library
    ii  libgdk-pixbuf2.0-common          2.26.1-1ubuntu1.1                     GDK Pixbuf library - data files
    ii  libgdome2-0                      0.8.1+debian-4.1build1                DOM level2 library for accessing XML files
    ii  libgdome2-cpp-smart0c2a          0.2.6-6build2                         C++ bindings for GDome2 DOM implementation
    ... :~# lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 12.04.5 LTS
    Release:        12.04
    Codename:       precise

**Comment by spoxaka** [comment]
I'm sure my workaround is super-ugly, but for those who are desperately trying to bring back production sites you can `wget` http://security.debian.org/debian-security/pool/updates/main/p/php5/php5-gd_5.4.39-0+deb7u2_amd64.deb, unpack it and replace `/usr/lib/php5/20100525/gd.so` with the unpacked file. Make sure to save the original just in case.

**Comment by vkimball** [comment]
Thanks for the workaround, sphoxaka.  It worked for me.  (Yes, I saved the original go.so)

**Comment by oerdnj** [comment]
@spoxaka It's not that ugly at all. The PHPAPI is still same, so thank you very much for providing workaround.

To all - sorry for the breakup. I messed hard this time, and fix is hopefully on it's way. I reverted the PPA to previous state (deleting wrong libgd) and rebuilding package against old libgd - that should fix it.

**Comment by oerdnj** [comment]
@dsteinkopf @Maartenlameris @vkimball @spoxaka @m4lvin @tudo75 @wweich Could you retry with 5.4.40+real-1+deb.sury.org~precise+4

I made sure that the package is linked with libgd 2.0.x, so I believe this issue has been fixed, and my precise chroot also looks fine (from phpinfo()):

    GD Support => enabled
    GD Version => 2.0.36

Again I am very sorry for all the troubles.

**Comment by Recon** [comment]
@oerdnj I had the same problem, I can confirm it's fixed (Ubuntu 12.04.5 LTS)

**Comment by wweich** [comment]
The `precise+4` version fixes the issue for me, too.

**Comment by tudo75** [comment]
works also for me
thanks

**Comment by dsteinkopf** [comment]
Everything fine here, too. Thank you for your quick fix !
