### ISSUE TITLE
VCS Locations for php, dh-php, and php-defaults Repositories

### ISSUE THREAD

**Issue by jeffwecan** [oerdnj/deb.sury.org#673]
It appears that php, dh-php, and php-defaults source code repositories were transitioned from anonscm.debian.org to gitlab.sury.org this past April. Are there plans to synchronize these gitlab and aloith/debian repositories (as anonscm.debian.org is meant to serve as the "official" location for debian packaging)?

**Comment by oerdnj** [comment]
Nope, the official repository is defined by Vcs-* fields in the debian/control file. There's no such thing as "official" location for Debian packaging. 

Oh, and even more recently I moved those under https://gitlab.com/deb.sury.org/ namespace. And I also intend to move all PECL packages there, alioth (fusion forge) is simply to outdated to be used effectively.
