### ISSUE TITLE
php-7.2beta3 Argon2 constants missing

### ISSUE THREAD

**Issue by DeadP4xel** [oerdnj/deb.sury.org#675]
If I try to hash a password with Argon2 (password_hash()) I'm always getting this error:

 "PHP Warning:  Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I'

It seems like the "--with-password-argon2" configuration parameter is missing in the default installation?

**Comment by oerdnj** [comment]
Just uploaded a versions (`7.2.0~beta3-2*`) with Argon2 support.

**Comment by DeadP4xel** [comment]
Can't find it on my package list on my server. Only (7.2.0~beta3-1) is available.

**Comment by oerdnj** [comment]
Did you do apt-get update? It's there: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?batch=300

**Comment by DeadP4xel** [comment]
On my Debian 9 server I have this version available after updating:

7.2.0~beta3-1+0~20170818130329.5+stretch~1.gbp310bdb

I've also checked the mirror for the beta-2* package here: https://packages.sury.org/php/pool/main/p/php7.2/

**Comment by oerdnj** [comment]
Please specify the distribution next time you fill an issue.

The Debian repositories has been updated as well.
