### ISSUE TITLE
Debian Stretch: php7.1-fpm missing?

### ISSUE THREAD

**Issue by mauricemeyer** [oerdnj/deb.sury.org#678]
Hello everyone,

I just installed a fresh Raspbian Stretch and tried to use php7.1-fpm as I always do (most of my other machines are Ubuntu though).

So I added the https://packages.sury.org/php/ as source, following https://packages.sury.org/php/README.txt and updated my apt-cache.

Now, **all** _php7.1-*_-Packages are missing for stretch?

I can't find them anywhere in https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages

Is this intended, do I miss something or is this indeed an error?

Thanks to anyone taking the time!

**Comment by oerdnj** [comment]
Raspbian is arm(hf) and this is already tracked as #579
