### ISSUE TITLE
[Feature Request] PHP 5.5 and PHP 5.4 for Stretch (Debian 9)

### ISSUE THREAD

**Issue by PVasileff** [oerdnj/deb.sury.org#680]
It possible to provide us PHP 5.5 and PHP 5.4 in your repo? 
I see that you successfully compile and packaged PHP 5.6.. 
I try to compile PHP 5.5.38 from source.. but when configure --with-openssl,
configure done with success, but when run make I got error..

**Comment by oerdnj** [comment]
No. https://secure.php.net/supported-versions.php
