### ISSUE TITLE
Support for TCP Fast Open in Nginx

### ISSUE THREAD

**Issue by frk7z** [oerdnj/deb.sury.org#682]
I like to know if you can add support for TCP Fast Open in Nginx, would be possible? Thanks

More info, if needed, here: https://www.keycdn.com/support/tcp-fast-open/ It only need add the compiler flag "-DTCP_FASTOPEN=23" in "--with-cc" argument.

**Comment by oerdnj** [comment]
I believe that the TCP_FASTOPEN is already compiled in as the build logs says:
```
checking for TCP_FASTOPEN ... found
```

**Comment by frk7z** [comment]
mmmm I tested both nginx and nginx-mainline and I think the packages doesn't support it.

nginx stable from ppa
```
[~] $ nginx -V
nginx version: nginx/1.12.2
built with OpenSSL 1.0.2l  25 May 2017
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat 
-Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' ...
```

and nginx-mainline from ppa
```
[~] $ nginx -V
nginx version: nginx/1.13.6
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat 
-Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 '...
```

If need more tests, glad to help you.
