### ISSUE TITLE
php7.2: undefined symbol: pcre_jit_exec

### ISSUE THREAD

**Issue by vmartins** [oerdnj/deb.sury.org#683]
PHP 7.2 error:

```
root@web:~# php7.2 --version
php7.2: symbol lookup error: php7.2: undefined symbol: pcre_jit_exec
```

Ubuntu 14.04.5 LTS (Linux 3.13.0-43-generic x86_64)
Packages: php7.2 (7.2.0~beta3-2+ubuntu14.04.1+deb.sury.org+1), php7.2-cli, php7.2-common, php7.2-curl, php7.2-fpm, php7.2-json, php7.2-mbstring, php7.2-mysql, php7.2-opcache, php7.2-readline
No apache, only nginx.
I have also installed PHP 5.6 and PHP 7.1, both without error.

**Comment by oerdnj** [comment]
Update libpcre3 to 2:8.41-1.1 and try again. There was a bug in `pcre3` in trusty and jessie that disabled JIT on i386 platforms.

**Comment by vmartins** [comment]
Works after upgrade. Thanks!

**Comment by dikiaap** [comment]
@oerdnj I still have this problem. This happens on Ubuntu 16.04 LTS 32 bit
```shell
$ apt show libpcre3
Package: libpcre3
Version: 2:8.41-1.1+ubuntu16.04.1+deb.sury.org+2
```

**Comment by taccoboss1973** [comment]
Working after i installed libpcre3  on Ubuntu 14.04.5.Thank you.

**Comment by star1015** [comment]
How to Update libpcre3 to 2:8.41-1.1?
