### ISSUE TITLE
Cleaning old PHP session files doesn't work

### ISSUE THREAD

**Issue by azurit** [oerdnj/deb.sury.org#690]
Cleaning old PHP session files using systemd service/timer phpsessionclean doesn't work:

Sep  4 21:32:01 cloud0001 systemd[1]: Starting Clean php session files...
Sep  4 21:32:01 cloud0001 systemd[31959]: Failed at step NETWORK spawning /usr/lib/php/sessionclean: Invalid argument
Sep  4 21:32:01 cloud0001 systemd[1]: phpsessionclean.service: main process exited, code=exited, status=225/NETWORK
Sep  4 21:32:01 cloud0001 systemd[1]: Failed to start Clean php session files.
Sep  4 21:32:01 cloud0001 systemd[1]: Unit phpsessionclean.service entered failed state.

Everything starts to work fine after removing this line from systemd unit file:
PrivateNetwork=true

Debian Jessie, 64bit, using original Debian kernel and systemd.

Thank you!

**Comment by oerdnj** [comment]
Should be fixed since `php-defaults/55`.

**Comment by sandrotosi** [comment]
hey @oerdnj ! I cant find php-defaults/55 in any debian suites, and this error occurs also on stretch - any plan to upload the fix to stable-updates?

**Comment by CyrilBrulebois** [comment]
I've seen this issue as well, and cherry-picking the patch indeed makes it go away. +1 for stretch-proposed-updates.

**Comment by CyrilBrulebois** [comment]
Oh, my bad. I'm seeing the similar but different CGROUP issue:

```
mars 20 15:39:01 ldap CRON[22095]: pam_unix(cron:session): session opened for user root by (uid=0)
mars 20 15:39:01 ldap systemd[1]: Starting Clean php session files...
mars 20 15:39:01 ldap systemd[22097]: phpsessionclean.service: Failed at step CGROUP spawning /usr/lib/php/sessionclean: No such file or directory
mars 20 15:39:01 ldap CRON[22096]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
mars 20 15:39:01 ldap systemd[1]: phpsessionclean.service: Main process exited, code=exited, status=219/CGROUP
mars 20 15:39:01 ldap systemd[1]: Failed to start Clean php session files.
mars 20 15:39:01 ldap CRON[22095]: pam_unix(cron:session): session closed for user root
mars 20 15:39:01 ldap systemd[1]: phpsessionclean.service: Unit entered failed state.
mars 20 15:39:01 ldap systemd[1]: phpsessionclean.service: Failed with result 'exit-code'.
```
