### ISSUE TITLE
php7.1-xdebug overwrites php 7.0 config-files

### ISSUE THREAD

**Issue by rikvdh** [oerdnj/deb.sury.org#691]
When having php7.0 and 7.1 side-by-side fails when installing php7.1-xdebug with php7.0-xdebug installed.

```
$ sudo apt-get install php7.1-xdebug
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php-xdebug' instead of 'php7.1-xdebug'
The following NEW packages will be installed:
  php-xdebug
0 upgraded, 1 newly installed, 0 to remove and 153 not upgraded.
Need to get 0 B/642 kB of archives.
After this operation, 3,352 kB of additional disk space will be used.
(Reading database ... 77245 files and directories currently installed.)
Preparing to unpack .../php-xdebug_2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48_amd64.deb ...
Unpacking php-xdebug (2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48) ...
dpkg: error processing archive /var/cache/apt/archives/php-xdebug_2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48_amd64.deb (--unpack):
 trying to overwrite '/etc/php/7.0/mods-available/xdebug.ini', which is also in package php7.0-xdebug 1:2.5.1-1~dotdeb+8.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/php-xdebug_2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rikvdh** [comment]
Sorry, I see that I have dotdeb php packages installed somewhere

**Comment by neskhodovskiy** [comment]
@rikvdh how did you solve this please? I have exactly the same issue and not sure where to look. Thanks!

**Comment by neskhodovskiy** [comment]
What I did so far to get past this, is `apt-get remove php7.0-xdebug` then `apt-get install php7.1-xdebug`. While it worked, I'm still interested in the correct way to have xdebug installed for both php versions.

**Comment by rikvdh** [comment]
@neskhodovskiy the problem was that `php7.1-xdebug` doesnt exist, it automatically selects `php-xdebug`, this installs configuration for 7.1 but also 7.0.  The commands you describe above are the only resolutions. I didn't need support for both. Perhaps installing php7.0 from sury as well instead of dotdeb resolves this.

**Comment by oerdnj** [comment]
Remove anything dotdeb first before installing anything from deb.sury.org
