### ISSUE TITLE
[PHP7] Please package/provide php7.[12]-mcrypt as well

### ISSUE THREAD

**Issue by m-ueberall** [oerdnj/deb.sury.org#693]
ATM, only php7.0-mcrypt is available. (Debian sid has php7.1-mcrypt and will likely have php7.2-mcrypt later on, but it would be nice to have everything pre-built in one repository.) Thanks in advance!

**Comment by oerdnj** [comment]
What repository are you talking about?

**Comment by m-ueberall** [comment]
I'm using `ppa:ondrej/php` (which actually _does_ have `php7.1-mcrypt`, but not `php7.2-mcrypt`. I could have sworn the former wasn't found when I tried to install it the first time a couple of minutes ago, but it worked now, so I must have been mistaken).

**Comment by oerdnj** [comment]
http://php.net/manual/en/migration71.deprecated.php

**Comment by m-ueberall** [comment]
Ouch. But thanks a lot for the pointer!
