### ISSUE TITLE
php5.6-gd depends on libgd3 >= 2.1.1, cannot install on trusty

### ISSUE THREAD

**Issue by josegonzalez** [oerdnj/deb.sury.org#694]
When trying to install php5.6-gd, I get the following error:

```
# apt-get install php5.6-gd=5.6.31-4+ubuntu14.04.1+deb.sury.org+4
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5.6-gd : Depends: libgd3 (>= 2.1.1) but 2.1.0-3ubuntu0.8 is to be installed
E: Unable to correct problems, you have held broken packages.
```

The latest version - even in [trust-updates](https://packages.ubuntu.com/trusty-updates/libgd3) - is `2.1.0-3ubuntu-0.8`. Any chance we can downgrade the dependency?

**Comment by oerdnj** [comment]
The up to date version of libgd3 is available from the ppa

**Comment by josegonzalez** [comment]
That doesn't seem correct. `libgd2` is available from the PPA, but the package depends on `libgd3`. Is [this](https://launchpad.net/~ondrej/+archive/ubuntu/php) the incorrect PPA (linked to from the README.md)?

**Comment by josegonzalez** [comment]
Upgrading from Trusty to Xenial is a workaround for those out there that do not have a hard OS dependency.

**Comment by oerdnj** [comment]
No, you are wrong. The *binary* package is available from the PPA for Trusty.

**Comment by josegonzalez** [comment]
Thanks for pointing that out.

Any chance you have an idea why the above apt-get call failed? It was run from within chef, but I ran that in the resulting vm with the above resulting. My simple reproduce... doesn't reproduce it, but now I am slightly curious as to why it would report a different available version for the package.

**Comment by oerdnj** [comment]
Do you have any apt preferences setup?

`apt-cache policy libgd3` might give you some hints.

**Comment by josegonzalez** [comment]
That was it. I had the following apt-cache preference set:

```
$ cat /etc/apt/preferences.d/ubuntu.pref
Package: *
Pin: origin archive.ubuntu.com
Pin-Priority: 600
```

Thanks for the helpful pointer!

**Comment by fkobon** [comment]
I have the same problem. I read the answers above but I do not know how to correct the error

```
root@vps42215:/var/www/clients/client2/web20/web/test# apt-get install php7.2-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.2-gd : Depends: libgd3 (>= 2.1.1) but 2.1.0-5+deb8u11 is to be installed
E: Unable to correct problems, you have held broken packages.
```

My OS : 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
```
Codename:	jessie
