### ISSUE TITLE
PHP packaging source unavailable because gitlab.sury.org is offline

### ISSUE THREAD

**Issue by vdloo** [oerdnj/deb.sury.org#696]
The PHP packaging source on https://gitlab.sury.org/pkg-php/php has been unavailable for a couple of days. In the past there was also this [github mirror](https://github.com/pkg-php/php) that could be used to build the ondrej/php packaging, but that mirror hasn't been updated in 5 months. Has the source code perhaps been moved to somewhere else?

**Comment by oerdnj** [comment]
https://gitlab.com/deb.sury.org/

**Comment by vdloo** [comment]
thanks

**Comment by oerdnj** [comment]
Oh, and btw `apt-cache showsrc php7.1 | grep Vcs-` will should you up-to-date information from current package available on your system.

**Comment by vdloo** [comment]
Yeah we don't use the PPA but build directly from git and put the debs in our own repo. One of the reasons for that is so we can run some elaborate integration tests for our stack using dpkg-scanpackages in VMs before actually repreproing the new version into the repo. I couldn't find any changelog mentioning the source move, but next time I'll know where to look. Thanks
