### ISSUE TITLE
Installing nginx-extras on Ubuntu Artful 17.10

### ISSUE THREAD

**Issue by salaros** [oerdnj/deb.sury.org#699]
For some reason nginx-extras from ppa:ondrej/nginx depends on perl-base v5.24 via libnginx-mod-http-perl package.
v5.24 is shipped with Zesty, while Artful ships v5.26 and there is not easy way to downgrade it to 5.24

**Comment by oerdnj** [comment]
Is this nginx stable or nginx-mainline? I guess it has been built before the perl transition in Artful. nginx-mainline should already be ok (due 1.13.5 update), and I have just issued nginx (stable) rebuild.
