### ISSUE TITLE
Request: ZTS variant of the `php5` package

### ISSUE THREAD

**Issue by crishoj** [oerdnj/deb.sury.org#7]
Enabling ZTS would allow the usage of the `pthreads` PECL package, among other things. However, ZTS seems to have been deliberately disabled in the Ubuntu package all the way back in 2004 (http://changelogs.ubuntu.com/changelogs/pool/main/p/php5/php5_5.3.10-1ubuntu3.11/changelog). 

I have no idea if the concerns voiced "upstream" still apply, but a cautious approach that would sidestep potential issues could perhaps be to provide an alternative package, e.g. `php5-zts`, with a `Provides: php5` field.

**Comment by oerdnj** [comment]
Folks, if you want to shoot yourself in foot, the new packaging infrastructure I built for PHP 7.0 allows to build variants quite easily, so here's experimental, totally unsupported PPA with PHP 7.0 ZTS: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts

No external modules, no batteries, no support (patches accepted and welcomed).
