### ISSUE TITLE
php5-oldstable packages dropped for lucid?

### ISSUE THREAD

**Issue by tucksaun** [oerdnj/deb.sury.org#70]
Hi,

In the releasing of PHP 5.4.40 (#64), lucid packages were not included as we can see [here](https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable/+builds?build_text=&build_state=built).
More problematic, there's no packages available anymore for php5-oldstable for lucid.

Just want to check if it's intentional or not.

Thanks

**Comment by oerdnj** [comment]
Ubuntu Lucid server support ended on April 30, 2015. So, yes, it is intentional.
