### ISSUE TITLE
PHP-7.1 : Json problem

### ISSUE THREAD

**Issue by rgoerner** [oerdnj/deb.sury.org#705]
With Build  php7.1 -v
PHP 7.1.9-1+0~20170902060745.8+stretch~1.gbpebe5d6 (cli) (built: Sep  2 2017 06:07:49) ( NTS )
There seems to be a problem with the json-module. Although it is installed, it is not enabled or can be found as an extension.
:(

**Comment by rgoerner** [comment]
In /etc/php/7.1/mods-available I created a file:
json,ini

with the following content:
; configuration for php mbstring module
; priority=20
extension=json.so

then, it it is working

**Comment by oerdnj** [comment]
I am quite sure that you did something wonky with your setup.

Could you reproduce the issue installing manually on a clean stretch machine?

**Comment by oerdnj** [comment]
no response, closing
