### ISSUE TITLE
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client xxx.xxx.xxx.xxx]

### ISSUE THREAD

**Issue by rohanvakharia** [oerdnj/deb.sury.org#706]
I found this error in my log
`Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client xxx.xxx.xxx.xxx]`

As per the [issues/1468](https://github.com/SpiderLabs/ModSecurity/issues/1468) of ModSecurity it is fixed in version 2.9.1-3 patch for debian and Ubuntu Xeniel.

Can you please release update the modsecurity package for Xeniel?

**Comment by oerdnj** [comment]
I have update to the latest upstream version (`2.9.2`) that should already have the fix.

**Comment by rohanvakharia** [comment]
Thank you.
