### ISSUE TITLE
Unable to upgrade to PHP 5.6 on ubuntu 14.04

### ISSUE THREAD

**Issue by ravindrabhat6** [oerdnj/deb.sury.org#708]
Hi ,

I am trying to upgrade my php from 5.3 to 5.6 and having a difficulty. please help. 
here is the error.

Although I am able to Add PPA , but stuck with the below error.

ubuntu@ip-10-252-131-243:~$ sudo apt-get -y install php5.6 php5.6-mcrypt php5.6-mbstring php5.6-curl php5.6-cli php5.6-mysql php5.6-gd php5.6-intl php5.6-xsl php5.6-zip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5.6
E: Couldn't find any package by regex 'php5.6'
E: Unable to locate package php5.6-mcrypt
E: Couldn't find any package by regex 'php5.6-mcrypt'
E: Unable to locate package php5.6-mbstring
E: Couldn't find any package by regex 'php5.6-mbstring'
E: Unable to locate package php5.6-curl
E: Couldn't find any package by regex 'php5.6-curl'
E: Unable to locate package php5.6-cli
E: Couldn't find any package by regex 'php5.6-cli'
E: Unable to locate package php5.6-mysql
E: Couldn't find any package by regex 'php5.6-mysql'
E: Unable to locate package php5.6-gd
E: Couldn't find any package by regex 'php5.6-gd'
E: Unable to locate package php5.6-intl
E: Couldn't find any package by regex 'php5.6-intl'
E: Unable to locate package php5.6-xsl
E: Couldn't find any package by regex 'php5.6-xsl'
E: Unable to locate package php5.6-zip
E: Couldn't find any package by regex 'php5.6-zip'

**Comment by oerdnj** [comment]
You are either using unsupported release or you forgot to update the sources.list.d/*php*.list to trusty.
