### ISSUE TITLE
apache 2.4.12-1+deb.sury.org~trusty+5  doesn't support SSLOpenSSLConfCmd DHParameters

### ISSUE THREAD

**Issue by akhepcat** [oerdnj/deb.sury.org#71]
When trying to mitigate some SSL issues by supplying custom DH parameters, the syntax as specified by apache and others:  (http://serverfault.com/questions/693241/how-to-fix-logjam-vulnerability-in-apache-httpd)

SSLOpenSSLConfCmd DHParameters "/etc/apache2/dhparams.pem"

returns an error during apache startup:

 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 78 of /etc/apache2/mods-enabled/ssl.conf:
Invalid command 'SSLOpenSSLConfCmd', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.

\# apachectl -v
Server version: Apache/2.4.12 (Ubuntu)
Server built:   Feb  4 2015 14:20:59

Per http://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd
This is a valid command, since 2.4.8, so I'm confused about why it's generating an error.

\# openssl version
OpenSSL 1.0.2a 19 Mar 2015

**Comment by oerdnj** [comment]
Perhaps OpenSSL was upgraded later and Apache was compiled with OpenSSL version 1.0.1 or 1.0.0. I'll check when at computer... 

Ondřej 

On May 21, 2015 1:56:40 AM GMT+02:00, Leif <notifications@github.com> wrote:
>When trying to mitigate some SSL issues by supplying custom DH
>parameters, the syntax as specified by apache and others: 
>(http://serverfault.com/questions/693241/how-to-fix-logjam-vulnerability-in-apache-httpd)
>
>SSLOpenSSLConfCmd DHParameters "/etc/apache2/dhparams.pem"
>
>returns an error during apache startup:
>
> * The apache2 configtest failed.
>Output of config test was:
>AH00526: Syntax error on line 78 of /etc/apache2/mods-enabled/ssl.conf:
>Invalid command 'SSLOpenSSLConfCmd', perhaps misspelled or defined by a
>module not included in the server configuration
>Action 'configtest' failed.
>The Apache error log may have more information.
>
>\# apachectl -v
>Server version: Apache/2.4.12 (Ubuntu)
>Server built:   Feb  4 2015 14:20:59
>
>Per
>http://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd
>This is a valid command, since 2.4.8, so I'm confused about why it's
>generating an error.
>
>\# openssl version
>OpenSSL 1.0.2a 19 Mar 2015
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/71

-- 
Ondřej Surý

**Comment by oerdnj** [comment]
Hi, as I suspected, trusty (and even vivid) still has openssl 1.0.1f and I don't really feel like I should be backporting openssl in php5 repositories when there's a different workaround.

Perhaps you just could switch to ECDHE?

From https://weakdh.org/sysadmin.html:

Deploy (Ephemeral) Elliptic-Curve Diffie-Hellman (ECDHE). Elliptic-Curve Diffie-Hellman (ECDH) key exchange avoids all known feasible cryptanalytic attacks, and modern web browsers now prefer ECDHE over the original, finite field, Diffie-Hellman. **The discrete log algorithms we used to attack standard Diffie-Hellman groups do not gain as strong of an advantage from precomputation, and individual servers do not need to generate unique elliptic curves.**

We have switched to strong ciphers some time ago, and our servers are safe against logjam, f.e. https://www.ssllabs.com/ssltest/analyze.html?d=www.knot-dns.cz&latest

Cheers,
Ondrej

**Comment by oerdnj** [comment]
I have upgraded openssl in ppa:ondrej/apache2 due HTTP/2 support (for trusty and higher):
https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+packages
@akhepcat could you try upgrading if the DHParams works for you with those packages. I will do the same with php5 and php5-5.6 PPAs if everything is ok.

**Comment by oerdnj** [comment]
No feedback, but it should be fine now as Apache 2.4 has been recompiled with newer openssl in all PPAs.

**Comment by akhepcat** [comment]
Ah, sorry, missed this.  I don't remember which box I had this installed in, or if it's still there.
