### ISSUE TITLE
libgearman8 dependency for php-gearman has no installable candidate

### ISSUE THREAD

**Issue by mathiasaerts** [oerdnj/deb.sury.org#711]
When using the main PHP PPA and trying to install the `php-gearman` package, the following error occurs:
` php-gearman : Depends: libgearman8 (>= 1.1.13) but it is not installable`

There is no libgearman8 package available in the PPA:
```
# apt-cache policy libgearman8 
libgearman8:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Comment by oerdnj** [comment]
Yeah, please add:

ppa:ondrej/pkg-gearman

I need to yet make an announce and update the description. It was too confusing to maintain the same package at two places.

**Comment by oerdnj** [comment]
I wrote a short blog post about it: https://www.patreon.com/posts/gearman-now-in-14627464

I'll keep this open for a short while, so people can find it.

**Comment by mathiasaerts** [comment]
Thanks! Adding `ppa:ondrej/pkg-gearman` as well fixes the issue. I understand your decision to split the packages in separate repos. 

I did take a look at `ppa:ondrej/pkg-gearman` before but the package list at the bottom of the [launchpad page](https://launchpad.net/~ondrej/+archive/ubuntu/pkg-gearman) made me think the `libgearman8` package was not included.

**Comment by sjkeerthi** [comment]
Thank you so much for add this packages which really helps me a lot.

**Comment by ivanzor** [comment]
@mathiasaerts thx, really work.
