### ISSUE TITLE
Can't install PHP7.1 on Ubuntu 16.10 (Yakkety Yak)

### ISSUE THREAD

**Issue by josipjelic** [oerdnj/deb.sury.org#713]
`$ sudo add-apt-repository ppa:ondrej/php`
`$ sudo apt install php7.1`
```Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.1
E: Couldn't find any package by glob 'php7.1'
E: Couldn't find any package by regex 'php7.1'
```
I can see that Yakkety packages are missing. Any reason for that?

**Comment by oerdnj** [comment]
Any reason why you are using release after it's EOL?

**Comment by toncic92** [comment]
Is there any other way to install php7.1 on Ubuntu 16.10? I tried to do the same as @josipjelic but get the same error?

**Comment by oerdnj** [comment]
https://wiki.ubuntu.com/Releases

STOP USING RELEASES AFTER THEIR RESPECTIVE END-OF-LIFE.
