### ISSUE TITLE
php-memcache wrong work with memcache

### ISSUE THREAD

**Issue by rnz** [oerdnj/deb.sury.org#717]
Bug in php-memcache: https://github.com/websupport-sk/pecl-memcache/issues/23
Wrong behavior: https://paste.ubuntu.com/25685803/
Right behavior: https://paste.ubuntu.com/25685809/

Fixed by the next patch: https://github.com/websupport-sk/pecl-memcache/issues/23#issuecomment-327702906

Please update php-memcache in repos applying patch (for php7, for php5 need save backward compatibility)

**Comment by oerdnj** [comment]
I quite don't understand why you don't finally start using php-memcached and insist on using ages old not-really supported php-memcache.

**Comment by oerdnj** [comment]
I pulled the patch into the latest version in the ppa.
