### ISSUE TITLE
Trusty PHP 7.0 packages not built against openssl 1.1

### ISSUE THREAD

**Issue by Silarn** [oerdnj/deb.sury.org#718]
After upgrading to recent builds of PHP 7.0, the openssl 1.1 package was also pulled in.

However, both the php7.0-curl and php-ssh2 packages are not compatible with this:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/curl.so' - libssl.so.1.0.2: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ssh2.so' - libcrypto.so.1.0.2: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 7.0.24-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep 28 2017 16:33:02) ( NTS )

**Comment by oerdnj** [comment]
What's output of `apt-cache policy php7.0-curl php-ssh2`?

**Comment by Silarn** [comment]
```
php7.0-curl:
  Installed: 7.0.24-1+ubuntu14.04.1+deb.sury.org+1
  Candidate: 7.0.24-1+ubuntu14.04.1+deb.sury.org+1
  Version table:
 *** 7.0.24-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
php-ssh2:
  Installed: 1.1.2+0.13-1+ubuntu14.04.1+deb.sury.org+1
  Candidate: 1.1.2+0.13-1+ubuntu14.04.1+deb.sury.org+1
  Version table:
 *** 1.1.2+0.13-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by Silarn** [comment]
Sorry, I mistakently wrote Xenial - should have been Trusty.

**Comment by oerdnj** [comment]
Could you provide output of:
1. `apt-cache policy libssl1.0.0`
2. `dpkg -l 'libssl*'`
3. `ldd /usr/lib/php/20151012/curl.so`
4. `ldd /usr/lib/php/20151012/ssh2.so`

Both packages have been recompiled after openssl 1.1 got into the PPA, so it must be something on your system. Can you reproduce it in clean environment?

**Comment by Silarn** [comment]
Unfortunately I don't have direct control over this server, so I'm working partially via their support. It looks like the openssl package may be installed from another source, however. That may be the issue...

libssl1.0.0:
  Installed: 1.0.1f-1ubuntu2.22
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
 *** 1.0.1f-1ubuntu2.22 0
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-===============================================================
ii  libssl-dev:amd64              1.1.0f-2~ubuntu14.0 amd64               Secure Sockets Layer toolkit - development files
ii  libssl-doc                    1.1.0f-2~ubuntu14.0 all                 Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64             1.0.1f-1ubuntu2.22  amd64               Secure Sockets Layer toolkit - shared libraries
rc  libssl1.0.2:amd64             1.0.2j-1+deb.sury.o amd64               Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64               1.1.0f-2~ubuntu14.0 amd64               Secure Sockets Layer toolkit - shared libraries

It looks like your PPA still contains openssl-1.0.2 but now I think they may have manually installed 1.1... dpkg-query can't find a matching package for libssl.so.1.1.

**Comment by Silarn** [comment]
So from the dpkg -l I can see that libssl1.0.2 was likely removed but still has config files left. Could this cause the linking to try loading the wrong lib for some reason? Would purging this package fix it, or do we need to try reinstalling the libssl1.0.2 package?

**Comment by oerdnj** [comment]
I still need the output of these commands:

```
ldd /usr/lib/php/20151012/curl.so
ldd /usr/lib/php/20151012/ssh2.so
```
