### ISSUE TITLE
Missing libapache2-mod-xsendfile in php5.6 repo

### ISSUE THREAD

**Issue by jkroepke** [oerdnj/deb.sury.org#72]
Hello,

I miss the libapache2-mod-xsendfile package on the php 5.6 repo. I see, the package exists on the php 5.5 repo.

It is possible to add the libapache2-mod-xsendfile package to the php5.6 repo?

Regards,
Jan

**Comment by oerdnj** [comment]
Hi, I will work on adding new packages to the repositories this week.

**Comment by oerdnj** [comment]
Ubuntu 12.04 LTS support in my PPAs is reaching EOL, so no new packages for Ubuntu 12.04 LTS (Precise) will be added, see https://deb.sury.org/ubuntu-precise-and-PHP-5.4-eol.html

The libapache2-mod-xsendfile for Trusty and higher should be installable without any problems.
