### ISSUE TITLE
PHP 7.2 RC4

### ISSUE THREAD

**Issue by thomaskonrad** [oerdnj/deb.sury.org#722]
Hi,

is there a chance to get the [RC4 of PHP 7.2](https://secure.php.net/archive/2017.php#id2017-10-12-1)? It came out on 12th of October. It [adds a couple of Sodium bindings](https://mailinglist-archive.mojah.be/php-commits/2017-10/msg00015.php) that would be useful for me.

Thank you
Thomas

**Comment by oerdnj** [comment]
Done.

**Comment by todeveni** [comment]
Debian packages are still RC3.

**Comment by oerdnj** [comment]
Launched a Debian build.
