### ISSUE TITLE
Missing php5.6-imagick package for Ubuntu 17.10 (artful)

### ISSUE THREAD

**Issue by m-burst** [oerdnj/deb.sury.org#723]
The package `php5.6-imagick` for Ubuntu 17.10 is missing. Only `php-imagick` is present which depends on PHP 7.
Could you please have a look at this?
Thanks in advance!

**Comment by oerdnj** [comment]
I bumped the version to `-3` to override the `-2ubuntu3` that 17.10. It should be available in couple of minutes.
