### ISSUE TITLE
[nginx-mainline]: new install does not automatically start on reboot with 17.10 'artful'

### ISSUE THREAD

**Issue by willfull** [oerdnj/deb.sury.org#725]
Just did an install of nginx-mainline (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) on a fresh new Ubuntu Server 17.10 'artful aardvark' build.  Restarted the system, did a status of the nginx service and it came up inactive.  Executed a manual 'service nginx start', checked the status again and it came up fine.

Inspection of /etc/systemd/system/multi-user.target.wants directory shows no link to /lib/systemd/system/nginx.service, which I assume is the culprit here.  I manually added the symbolic link, restarted the server, and the service activates automatically as expected.  Unsure as to why the link wasn't added at the time of installation, but wanted to mention this in case others are affected.

_Děkuji mnohokrát_,
Will

Note: I performed a clean install of this same NGINX version to a brand new 16.04 'xenial' server the other day, and everything (e.g., automatic start) performed as normal.

**Comment by oerdnj** [comment]
Could you look into `/var/log/apt/` files for clues why it hasn't been enabled?

**Comment by willfull** [comment]
Here's what I could find:

**Excerpt from /var/log/apt/history.log**
`Start-Date: 2017-10-24  10:42:14`
`Commandline: apt install nginx`
`Requested-By: willfull (1000)`
`Install: libnginx-mod-http-geoip:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libnginx-mod-http-upstream-fair:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libwebp6:amd64 (0.6.0-3, automatic), libnginx-mod-http-auth-pam:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libnginx-mod-http-dav-ext:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libgd3:amd64 (2.2.5-3, automatic), fontconfig-config:amd64 (2.11.94-0ubuntu2, automatic), nginx-common:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libnginx-mod-http-subs-filter:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), nginx-full:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libtiff5:amd64 (4.0.8-5, automatic), libnginx-mod-http-image-filter:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), fonts-dejavu-core:amd64 (2.37-1, automatic), libnginx-mod-http-echo:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libjpeg8:amd64 (8c-2ubuntu8, automatic), libnginx-mod-mail:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libfontconfig1:amd64 (2.11.94-0ubuntu2, automatic), libjpeg-turbo8:amd64 (1.5.2-0ubuntu5, automatic), libjbig0:amd64 (2.1-3.1, automatic), libnginx-mod-stream:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), libxpm4:amd64 (1:3.5.12-1, automatic), libnginx-mod-http-xslt-filter:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1, automatic), nginx:amd64 (1.13.5-1+ubuntu17.10.1+deb.sury.org+1)`
`End-Date: 2017-10-24  10:43:32`

**Excerpt from /var/log/apt/term.log**
`Log started: 2017-10-24  10:42:14`
`Selecting previously unselected package libjpeg-turbo8:amd64.`
`(Reading database ... 70880 files and directories currently installed.)`
`Preparing to unpack .../00-libjpeg-turbo8_1.5.2-0ubuntu5_amd64.deb ...`
`Unpacking libjpeg-turbo8:amd64 (1.5.2-0ubuntu5) ...`
`Selecting previously unselected package libjbig0:amd64.`
`Preparing to unpack .../01-libjbig0_2.1-3.1_amd64.deb ...`
`Unpacking libjbig0:amd64 (2.1-3.1) ...`
`Selecting previously unselected package fonts-dejavu-core.`
`Preparing to unpack .../02-fonts-dejavu-core_2.37-1_all.deb ...`
`Unpacking fonts-dejavu-core (2.37-1) ...`
`Selecting previously unselected package fontconfig-config.`
`Preparing to unpack .../03-fontconfig-config_2.11.94-0ubuntu2_all.deb ...`
`Unpacking fontconfig-config (2.11.94-0ubuntu2) ...`
`Selecting previously unselected package libfontconfig1:amd64.`
`Preparing to unpack .../04-libfontconfig1_2.11.94-0ubuntu2_amd64.deb ...`
`Unpacking libfontconfig1:amd64 (2.11.94-0ubuntu2) ...`
`Selecting previously unselected package libjpeg8:amd64.`
`Preparing to unpack .../05-libjpeg8_8c-2ubuntu8_amd64.deb ...`
`Unpacking libjpeg8:amd64 (8c-2ubuntu8) ...`
`Selecting previously unselected package libtiff5:amd64.`
`Preparing to unpack .../06-libtiff5_4.0.8-5_amd64.deb ...`
`Unpacking libtiff5:amd64 (4.0.8-5) ...`
`Selecting previously unselected package libwebp6:amd64.`
`Preparing to unpack .../07-libwebp6_0.6.0-3_amd64.deb ...`
`Unpacking libwebp6:amd64 (0.6.0-3) ...`
`Selecting previously unselected package libxpm4:amd64.`
`Preparing to unpack .../08-libxpm4_1%3a3.5.12-1_amd64.deb ...`
`Unpacking libxpm4:amd64 (1:3.5.12-1) ...`
`Selecting previously unselected package libgd3:amd64.`
`Preparing to unpack .../09-libgd3_2.2.5-3_amd64.deb ...`
`Unpacking libgd3:amd64 (2.2.5-3) ...`
`Selecting previously unselected package nginx-common.`
`Preparing to unpack .../10-nginx-common_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_all.deb ...`
`Unpacking nginx-common (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-auth-pam.`
`Preparing to unpack .../11-libnginx-mod-http-auth-pam_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-auth-pam (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-dav-ext.`
`Preparing to unpack .../12-libnginx-mod-http-dav-ext_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-dav-ext (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-echo.`
`Preparing to unpack .../13-libnginx-mod-http-echo_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-echo (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-geoip.`
`Preparing to unpack .../14-libnginx-mod-http-geoip_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-geoip (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-image-filter.`
`Preparing to unpack .../15-libnginx-mod-http-image-filter_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-image-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-subs-filter.`
`Preparing to unpack .../16-libnginx-mod-http-subs-filter_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-subs-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-upstream-fair.`
`Preparing to unpack .../17-libnginx-mod-http-upstream-fair_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-upstream-fair (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-http-xslt-filter.`
`Preparing to unpack .../18-libnginx-mod-http-xslt-filter_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-http-xslt-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-mail.`
`Preparing to unpack .../19-libnginx-mod-mail_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-mail (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package libnginx-mod-stream.`
`Preparing to unpack .../20-libnginx-mod-stream_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking libnginx-mod-stream (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package nginx-full.`
`Preparing to unpack .../21-nginx-full_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_amd64.deb ...`
`Unpacking nginx-full (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Selecting previously unselected package nginx.`
`Preparing to unpack .../22-nginx_1.13.5-1+ubuntu17.10.1+deb.sury.org+1_all.deb ...`
`Unpacking nginx (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Processing triggers for ufw (0.35-5) ...`
`Processing triggers for ureadahead (0.100.0-20) ...`
`Setting up libjbig0:amd64 (2.1-3.1) ...`
`Setting up fonts-dejavu-core (2.37-1) ...`
`Setting up nginx-common (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-http-subs-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libjpeg-turbo8:amd64 (1.5.2-0ubuntu5) ...`
`Processing triggers for libc-bin (2.26-0ubuntu2) ...`
`Processing triggers for systemd (234-2ubuntu12) ...`
`Setting up libnginx-mod-http-auth-pam (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-http-dav-ext (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-mail (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libxpm4:amd64 (1:3.5.12-1) ...`
`Processing triggers for man-db (2.7.6.1-2) ...`
`Setting up libnginx-mod-http-xslt-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-http-upstream-fair (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-http-geoip (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libwebp6:amd64 (0.6.0-3) ...`
`Setting up libjpeg8:amd64 (8c-2ubuntu8) ...`
`Setting up fontconfig-config (2.11.94-0ubuntu2) ...`
`Setting up libnginx-mod-stream (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libnginx-mod-http-echo (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up libtiff5:amd64 (4.0.8-5) ...`
`Setting up libfontconfig1:amd64 (2.11.94-0ubuntu2) ...`
`Setting up libgd3:amd64 (2.2.5-3) ...`
`Setting up libnginx-mod-http-image-filter (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up nginx-full (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Setting up nginx (1.13.5-1+ubuntu17.10.1+deb.sury.org+1) ...`
`Processing triggers for ureadahead (0.100.0-20) ...`
`Processing triggers for ufw (0.35-5) ...`
`Processing triggers for libc-bin (2.26-0ubuntu2) ...`
`Log ended: 2017-10-24  10:43:32`

**Comment by willfull** [comment]
Noticing this was still open, I just wanted to mention that upon creation of a new 16.04.3 LTS "xenial" server just fifteen minutes ago, the same problem occurred (like in post #1) where there was no link to nginx.service in the `/etc/systemd/system/multi-user.target.wants` directory.

**Comment by oerdnj** [comment]
How do you create the servers? Any elaborate provisioning?

**Comment by willfull** [comment]
No, none at all.  Nothing automated, nothing scripted.  Just a brand-new (virtual) server, an install straight from Ubuntu's ISO, and then I configure its network and start apt installing.  Basic, simple.

**Comment by mvrhov** [comment]
@oerdnj: If you backported from upstream, maybe the `dh-systemd` is needed in _Build-Depends_ section `debhelper` > 10= in newver version does not need this.

**Comment by willfull** [comment]
Also want to add that the same issue appeared on a brand-new install of ubuntu-17.10-server-i386.  I had to issue the command:

`ln -s /lib/systemd/system/nginx.service /etc/systemd/system/multi-user.target.wants/nginx.service`

... manually.

**Comment by MatthiasKuehneEllerhold** [comment]
`systemctl enable nginx` should have worked too, wouldnt it?

**Comment by willfull** [comment]
Actually, that would be the preferred method - I don't know why I didn't think of doing that.  (Thank you for the reminder.)

**Comment by oerdnj** [comment]
I think I finally found it. The Debian maintainers has split the debhelper 10 switch to three different commits and I missed the other two. Now all three has been reverted, so the 1.13.8 package should have the fix.

Unfortunately, the launchpad build farm is still non-operational, so we'll just have to wait.

**Comment by oerdnj** [comment]
This should be fixed on x86 architectures now.
