### ISSUE TITLE
Nginx 1.12.2 released

### ISSUE THREAD

**Issue by emord** [oerdnj/deb.sury.org#726]
Hi,

nginx 1.12.2 was released last week. Is there a ETA on getting that to https://launchpad.net/~ondrej/+archive/ubuntu/nginx? 

Changes: http://nginx.org/en/CHANGES-1.12

The following bugfix seems particularly useful for this  

> Bugfix: when using HTTP/2 client request body might be corrupted.

Thanks for maintaining this project!

**Comment by oerdnj** [comment]
Uploaded.

**Comment by emord** [comment]
@oerdnj thanks so much. I noticed that it looks like 16.10 is still on 1.12.1 in your repo. This isn't blocking me as we're using 14.04. Just an FYI
