### ISSUE TITLE
FPM processes crashing with 7.2.0RC4

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#727]
After upgrading from 7.2.0RC3 to RC4 some of our PHP FPM processes/sites are dying with SIGILL or SIGKILL signals. Disabling opcache from FPM seems to solve the problem.

Debian Jessie with `7.2.0~rc4-2+0~20171024190016.11+jessie~1.gbp26be74`

Not sure how to get backtrace from FPM, any advice?

**Comment by scara** [comment]
Hi @todeveni,
it looks like pretty similar to #724.

HTH,
Matteo

**Comment by todeveni** [comment]
@scara Yes, similar, but I guess I'd be running already "fixed" build of RC4.

I tried installing `php7.2-xmlrpc` and running `php -r "echo xmlrpc_encode_request('func', 'text', []);"` works (with opcache).

**Comment by todeveni** [comment]
I managed to [generate backtrace](https://easyengine.io/tutorials/php/core-dump-php5-fpm/).

```
Core was generated by `php-fpm: pool hss                                                            '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  i_free_compiled_variables (execute_data=<optimized out>) at ./Zend/zend_execute.c:2100
2100    ./Zend/zend_execute.c: No such file or directory.
(gdb) bt
#0  i_free_compiled_variables (execute_data=<optimized out>) at ./Zend/zend_execute.c:2100
#1  zend_leave_helper_SPEC () at ./Zend/zend_vm_execute.h:437
#2  0x000000000068a900 in ZEND_RETURN_SPEC_CV_HANDLER () at ./Zend/zend_vm_execute.h:33343
#3  execute_ex (ex=0x4) at ./Zend/zend_vm_execute.h:61948
#4  0x000000000068ea36 in zend_execute (op_array=0x7fb3efa79000, op_array@entry=0x7fb3d5d6e6e8, return_value=0x0,
    return_value@entry=0x7fb3efa1ce10) at ./Zend/zend_vm_execute.h:63763
#5  0x00000000005dbc83 in zend_execute_scripts (type=type@entry=8, retval=0x7fb3efa1ce10, retval@entry=0x0,
    file_count=file_count@entry=3) at ./Zend/zend.c:1496
#6  0x0000000000577168 in php_execute_script (primary_file=0x7ffdb36cc730) at ./main/main.c:2590
#7  0x000000000042da98 in main (argc=20428055, argv=0x137b668) at ./sapi/fpm/fpm/fpm_main.c:1966
```

**Comment by oerdnj** [comment]
It would be best to report such bugs to the upstream bugtracker, but they always need a code that triggers the behaviour.

**Comment by todeveni** [comment]
I'm guessing [#75357](https://bugs.php.net/bug.php?id=75357) _could_ be the upstream bug. Fixed in RC5, which is [tagged in git](http://git.php.net/?p=php-src.git;a=commit;h=fcbf63d8087db46f2ecd9248687ef2a463013a14) but not yet packaged for release or announced.

**Comment by todeveni** [comment]
7.2.0 RC5 (#729) fixed this. opcache enabled and FPM processes running smoothly again.

**Comment by oerdnj** [comment]
Thanks for the confirmation.
