### ISSUE TITLE
PHP LIBSQLITE Version behind?

### ISSUE THREAD

**Issue by dylanetaft** [oerdnj/deb.sury.org#73]
https://bugs.php.net/bug.php?id=69287
That sample code shows version 3.8.2 for the version of SQL in your repo
Missing features.
PHP Warning:  SQLite3::prepare(): Unable to prepare statement: 1, unknown tokenizer: unicode61 

PHP 5.6.9-1+deb.sury.org~trusty+2 (cli) (built: May 24 2015 15:46:23)

**Comment by dylanetaft** [comment]
This isn't really your bug - it's part of the package php5-sqlite\phpapi.  You don't have that packaged.  Ended up uninstalling all PHP packages and just building from source and installing in /usr/local

Feel free to close this or add php5-sqlite if you want!

**Comment by oerdnj** [comment]
php5-sqlite is packaged and "apt-get install php5-sqlite" should install it just fine.
