### ISSUE TITLE
[PHP 5.6] php: symbol lookup error: php: undefined symbol: pcre_jit_exec

### ISSUE THREAD

**Issue by lukaszsiminski** [oerdnj/deb.sury.org#730]
After install php5.6-apcu on my server I have this error after command php -v and another php command. Example:
`$ php -v`
`$ php: symbol lookup error: php: undefined symbol: pcre_jit_exec`

**Comment by oerdnj** [comment]
Upgrade the libpcre3 to latest version.

**Comment by lukaszsiminski** [comment]
Should I follow this instruction: https://www.mediawiki.org/wiki/Updating_to_PCRE_8.33_or_Higher ?

**Comment by oerdnj** [comment]
The other option might be a locally installed libpcre in `/usr/local/lib`.
