### ISSUE TITLE
PEAR for PHP 5.6 missing on Debian 9

### ISSUE THREAD

**Issue by hostingnuggets** [oerdnj/deb.sury.org#731]
I am using the deb.sury.org PHP 5.6 packages on Debian 9 and need to install the MDB2 PEAR package (http://pear.php.net/package/MDB2/redirected) but I am missing the `pear` command. I found it in the `php-pear` package but this one is for PHP 7.1 (dependencies on the packages php-xml php7.1-common php7.1-xml).

Would you also be able to provide a `php-pear` package for PHP 5.6 on Debian 9?

Thanks

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/wiki/PPA-Migration#why-is-php71-cli-always-installed
