### ISSUE TITLE
gd reports unrecoverable error

### ISSUE THREAD

**Issue by githabas** [oerdnj/deb.sury.org#732]
Sometimes png image data can be passed to imagecreatefromjpeg. In that case it should trigger catchable warning but reports unrecoverable error:
`php -r "imagecreatefromjpeg('test.png');"`
`PHP Fatal error: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x89 0x50 in Command line code on line 1`

As far as I know this issue has fixed in GD library version 2.2.5 but in Ubuntu 16.04 there is still version 2.1.1:
`PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 27 2017 13:49:56)
GD headers Version => 2.2.5 
GD library Version => 2.1.1`

**Comment by oerdnj** [comment]
What's `apt-cache policy libgd3`?

**Comment by oerdnj** [comment]
There 2.2.5 available from the repository. Do you have it installed?
