### ISSUE TITLE
Feature Request - ModSecurity CRS

### ISSUE THREAD

**Issue by ossie-git** [oerdnj/deb.sury.org#733]
Hi,

I just ran into your PPA and really like it.  I use it mainly for ModSecurity.  Would it be possible to package the ModSecurity Core Rule Set as well (https://github.com/SpiderLabs/owasp-modsecurity-crs/releases) as the one that currently comes with Debian and Ubuntu is very old.

Thanks a lot.

**Comment by oerdnj** [comment]
Uploaded.
