### ISSUE TITLE
Problem upgrading apache2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by richwales** [oerdnj/deb.sury.org#736]
I'm trying to upgrade apache2 on an Ubuntu 14.04 ("Trusty") system.  I added the PPA (sudo add-apt-repository ppa:ondrej/apache2; sudo apt-get update) — but the new version of apache2 is being ignored — after doing apt-get upgrade, I've still got Apache version 2.4.7, instead of 2.4.29 as I had expected.  The PPA works just fine on several Ubuntu 16.04 ("Xenial") systems.

**Comment by oerdnj** [comment]
What is output of `apt-cache policy apache2`?

**Comment by richwales** [comment]
$ apt-cache policy apache2
apache2:
  Installed: 2.4.7-1ubuntu4.18
  Candidate: 2.4.29-0.1+ubuntu14.04.1+deb.sury.org+2
  Version table:
     2.4.29-0.1+ubuntu14.04.1+deb.sury.org+2 0
        500 http://ppa.launchpad.net/ondrej/apache2/ubuntu/ trusty/main i386 Packages
     2.4.10-1ubuntu1.1~ubuntu14.04.2 0
        100 http://us.archive.ubuntu.com/ubuntu/ trusty-backports/main i386 Packages
 *** 2.4.7-1ubuntu4.18 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main i386 Packages
        100 /var/lib/dpkg/status
     2.4.7-1ubuntu4 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main i386 Packages
$

**Comment by oerdnj** [comment]
So, what happens if you directly do `apt-get install apache2`?

**Comment by richwales** [comment]
It worked. :-)

When I did "apt-get upgrade", it said this:

The following packages have been kept back:
  apache2 apache2-bin apache2-data

But when I did "apt-get install apache2", the new apache2 (2.4.29) from your PPA was installed.  And after I did "service apache restart", I inspected /var/log/apache2/error.log and confirmed that version 2.4.29 was in fact running.

I'm happy that I've got the new version running -- but I'm still confused as to why the new version was "kept back" when I tried a general upgrade.

**Comment by todeveni** [comment]
> I'm happy that I've got the new version running -- but I'm still confused as to why the new version was "kept back" when I tried a general upgrade.

If an upgrade would add or remove packages in addition to those being upgraded, it will be held back.

**Comment by richwales** [comment]
OK, then, I guess that issue is outside the scope of your PPA, which (as I said) I was eventually able to get installed.  Thanks for your help on this.
