### ISSUE TITLE
phpinfo() segfaulting on amd64 php5.6 with pecl-http installed

### ISSUE THREAD

**Issue by KrisShannon** [oerdnj/deb.sury.org#741]
This is with php-http_3.1.0+2.6.0-4+0~20170825_amd64

I've tracked this down to lines 222-228 of php_http.c which shows the libevent version:

```c
        php_info_print_table_row(3, "libevent",
#       ifdef LIBEVENT_VERSION
                        LIBEVENT_VERSION,
#       else
                        PHP_HTTP_EVENT_VERSION,
#       endif
                        event_get_version());
```

which gets compiled to:

```
xor    %eax,%eax
callq  event_get_version
lea    0x3fede(%rip),%rdx        
lea    0x3fee5(%rip),%rsi        
mov    %eax,%ecx
mov    $0x3,%edi
xor    %eax,%eax
callq  php_info_print_table_row
```

The call to event_get_version() successfully returns a proper pointer to a version string but the `mov %eax,%ecx` is a 32 bit move so the top bits get truncated.

The second parameter to php_info_print_table_row is "2.0.21-stable" so I'm assuming this was compiled against libevent-dev >= 2.0.21-stable-1 which definitely includes a proper prototype for event_get_version so I'm pretty confused why this is happening.

**Comment by oerdnj** [comment]
You should report this to the upstream bug tracker, as this is not a packaging error. Please report the upstream issue back here.

**Comment by oerdnj** [comment]
No response for almost two months, closing now.
