### ISSUE TITLE
php-mongodb: BC break in current version

### ISSUE THREAD

**Issue by Sander-Toonen** [oerdnj/deb.sury.org#745]
The version of the php-mongodb package that is currently available (1.3.0) has a backwards compatibility issue. See: https://github.com/mongodb/mongo-php-driver/issues/663

The change that resulted in this BC-break has been reverted in version 1.3.2. Can the available package be upgraded to this version please?

**Comment by vkhramtsov** [comment]
As quick workaround you can install driver from PECL. I'm also waiting for new package

**Comment by oerdnj** [comment]
For some strange reason, gitlab stopped sending me emails, so I never received notification for this. Upgrading to 1.3.3 now.
