### ISSUE TITLE
az_AZ locale and multibyte strings

### ISSUE THREAD

**Issue by icetique** [oerdnj/deb.sury.org#748]
First of all, I am not sure if this is a bug or intended feature, but I don't know where to ask.
When using az_AZ locale the PHP treats strings containing "I" (uppercase i) character as multibyte string. This may cause a lot of problems with libraries and packages written to use only non-multibyte functions.

The mbstring.func_overload set to 2 in php.ini is a workaround, although it is depreceated since PHP 7.2 and will be removed in the future.

The test code to see what I mean:
```
<?php
$string = "it_IT";
$string = explode("_", $string);
$string = $string[1];
var_dump(strtolower($string));
var_dump(mb_strtolower($string));
echo '<br>';

putenv('LC_ALL=az_AZ.utf8');
setlocale(LC_ALL, "az_AZ.utf8");
$string = "it_IT";
$string = explode("_", $string);
$string = $string[1];
var_dump(strtolower($string));
var_dump(mb_strtolower($string));
echo '<br>';

putenv('LC_ALL=en_US.utf8');
setlocale(LC_ALL, "en_US.utf8");
$string = "it_IT";
$string = explode("_", $string);
$string = $string[1];
var_dump(strtolower($string));
var_dump(mb_strtolower($string));
echo '<br>';
?>
```

Results:
```
string(2) "it" string(2) "it" 
string(2) "It" string(2) "it" 
string(2) "it" string(2) "it"
```

Tested on:
Ubuntu 16.04 LTS fully updated
PHP Version 7.0.22-0ubuntu0.16.04.1 (latest from stable repository)
with installed az_AZ UTF-8 locale
with php-intl and php-mbstring
apache2 from stable repository

Also tested on:
Ubuntu 17.10
PHP Version 7.1.11-1+ubuntu17.10.1+deb.sury.org+1
with installed az_AZ UTF-8 locale
with php-intl and php-mbstring
apache2 from your repository

Do you know is it intended behavior or do you know where can I look for a possible explanation of this?

**Comment by todeveni** [comment]
Here's the upstream bug report [#18556](https://bugs.php.net/bug.php?id=18556).

It's related to Azerbaijani using Turkish language rules and two different types of letter i.

**Comment by oerdnj** [comment]
This is not a packaging bug. Closing.

**Comment by icetique** [comment]
May be it, although tr_TR is working very well with "I" letter, so I am unsure how is it related. Thanks for the information though.
