### ISSUE TITLE
PHP 7.1.12

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [oerdnj/deb.sury.org#749]
PHP 7.1.12 was released on the 23th / 24th of November but it seems like its still missing from your debian stretch repo.

See https://packages.sury.org/php/pool/main/p/php7.1/
PHP Release: http://www.php.net/ChangeLog-7.php#7.1.12

`apt-cache show php7.1` also shows only `7.1.11-1+0~20171027135525.10+stretch~1.gbp2e638d`.

Debian Jessie seems the same (reported version: `7.1.11-1+0~20171027135825.10+jessie~1.gbp2e638d`)

**Comment by waja** [comment]
Yes, and it's 4 days later (actually). I don't know why there is a hurry here.

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry if I came across as aggressive or demanding.

All other releases were available the next day and I just wanted to notify the maintainer that the package is still missing.

**Comment by waja** [comment]
It's still a community project driven by @oerdnj. In other words: a one man show.

**Comment by MatthiasKuehneEllerhold** [comment]
`7.1.12-1+0~20171129100550.11+stretch~1.gbp8ded15` is now available. Thank you very much.
