### ISSUE TITLE
Tests fail with "unable to load dynamic library mysql.so" while building from source

### ISSUE THREAD

**Issue by El-76** [oerdnj/deb.sury.org#750]
Greetings,

Im trying to rebuild PHP5.6 package from php5.6_5.6.32-1+0\~20171027135529.7+stretch\~1.gbpd60169.dsc with standard dpkg-builpackage.

Build dependencies are installed ok with "apt-get build-dep".

Looks like it builds ok, but tests fail with:

Warning: PHP Startup: Unable to load dynamic library '/home/login/deb-playground/packages/3rdparty/php5.6/php5.6-5.6.32/ext-build/modules/mysql.so' - /home/login/deb-playground/packages/3rdparty/php5.6/php5.6-5.6.32/ext-build/modules/mysql.so: undefined symbol: mysqlnd_connect in Unknown on line 0

If I add -d "extension=mysqlnd.so" to the test script, the problem disappears.

Please advise what might be the root of the problem and how to fix it correctly.

**Comment by oerdnj** [comment]
Use `git-buildpackage` or `sbuild` to build packages in clean build environment. I have no capacity in debugging your system. There's no problem in the packaging, so there must be something different in your build environment.
