### ISSUE TITLE
libzip 1.2.0 needed for ZipArchive encryption features

### ISSUE THREAD

**Issue by ftrotter** [oerdnj/deb.sury.org#752]
Hello,
         According to the [7.2 new features page](http://php.net/manual/en/migration72.new-features.php), libzip 1.2.0 is required to make the zip encryption functions in php 7.2 function. 

As it stands, the code from the documentation page for the zip encryption feature http://php.net/manual/en/ziparchive.setencryptionname.php

```
<?php
$zip = new ZipArchive();
if ($zip->open('test.zip', ZipArchive::CREATE) === TRUE) {
    $zip->setPassword('secret');
    $zip->addFile('text.txt');
    $zip->setEncryptionName('text.txt', ZipArchive::EM_AES_256);
    $zip->close();
    echo "Ok\n";
} else {
    echo "KO\n";
}
?>
```

Will return 

`PHP Fatal error:  Uncaught Error: Call to undefined method ZipArchive::setEncryptionName()
`

I am assuming that upgrading libzip to 1.2.0 should fix this problem.

Thank you for all the work you do making php on ubuntu et al smooth.

Regards,
-FT

**Comment by oerdnj** [comment]
Uploaded and building.
