### ISSUE TITLE
Segfaults in PHP 7.1.12 and 7.0.26

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#753]
Please consider applying fix for [PHP bug #75573](https://bugs.php.net/bug.php?id=75573) into 7.1.12 and 7.0.26 builds.

7.1.12 patch:
http://git.php.net/?p=php-src.git;a=commit;h=3b9ba7b6bd9e24bdbeca8e8e3f24cee2fccc51d8

7.0.26 patch:
https://bugs.php.net/bug.php?id=75573#1512050558

**Comment by oerdnj** [comment]
Do you know if PHP 7.2 is affected as well?

**Comment by todeveni** [comment]
I ran the reproducing script with `PHP 7.2.0-1+0~20171201111145.14+jessie~1.gbp47ee8a` and got segfault.

**Comment by Bullace** [comment]
Any news on this? I can't revert to a previous version because it's not on the repo and I cleaned the apt cache and it seems like it's going to take around 3 more weeks for 7.1.13. So now I'm stuck with 2 half functional websites and I'm not sure what to do at this point (on 14.04 with 7.1.12).

**Comment by Llbe** [comment]
7.1.13 is scheduled for release 7th Dec: https://github.com/php/php-src/blob/php-7.1.13RC1/NEWS

**Comment by Bullace** [comment]
Ah cool, guess I'll wait it out.

**Comment by oerdnj** [comment]
It doesn't look like it yet. So, if there's no release by the evening, I'll patch.

**Comment by todeveni** [comment]
7.1.13 is scheduled for 4th Jan 2018 (according to [PHP-7.1 branch NEWS](https://github.com/php/php-src/blob/PHP-7.1/NEWS)).
[7.1.13RC1](https://github.com/php/php-src/releases/tag/php-7.1.13RC1) and [7.0.27RC1](https://github.com/php/php-src/releases/tag/php-7.0.27RC1) were released 7th Dec and there's no 7.2.1 RC release yet.

**Comment by Llbe** [comment]
Sorry for misleading here.

**Comment by oerdnj** [comment]
Uploaded patched versions and they are building right now.
