### ISSUE TITLE
php 7.2 provides

### ISSUE THREAD

**Issue by rlex** [oerdnj/deb.sury.org#754]
Hello, from php7.2 i can't install zabbix from mainline:
```
 zabbix-frontend-php : Depends: php5-mysql but it is not installable or
                                php5-mysqlnd but it is not installable or
                                php-mysql or
                                php5-pgsql but it is not installable or
                                php-pgsql
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

Looks like php7.2-mysql doesn't provide php-mysql (btw, force-installed with dependency skip it works correctly). Pgsql package works correctly (since it provides php-pgsql) and can be used as a temporary fix as well.

**Comment by oerdnj** [comment]
That's because there's no mysql module provided, so zabbix-frontend-php is missing  Depends: php-mysqlnd (or rather php-mysqli, because there's only mysqli.so now)

**Comment by todeveni** [comment]
I've just created [upstream issue](https://support.zabbix.com/browse/ZBX-13123) for this. I wouldn't hold my breath on getting this done anytime soon.
