### ISSUE TITLE
php-memcached 3.0.4 not available

### ISSUE THREAD

**Issue by anavarre** [oerdnj/deb.sury.org#757]
[php-memcached 3.0.4 is available](https://github.com/php-memcached-dev/php-memcached/releases). However, I'm not seeing it's available in deb.sury.org

```
$ sudo apt-cache show php-memcached | grep Version
Version: 3.0.3+2.2.0-1+0~20170806090136.1+stretch~1.gbp1eacf2
Version: 3.0.1+2.2.0-1
```

Might you be able to make it available?

**Comment by oerdnj** [comment]
It should be available now.
