### ISSUE TITLE
Update request: php-amqp to version 1.9.3

### ISSUE THREAD

**Issue by Koc** [oerdnj/deb.sury.org#758]
Please update `php-amqp` from 1.9.1 to 1.9.3 on ubuntu  https://pecl.php.net/package/amqp/1.9.3 
And ensure that it present for PHP 7.2

**Comment by oerdnj** [comment]
Done

**Comment by Koc** [comment]
@oerdnj Thanks!

**Comment by makasim** [comment]
@oerdnj Great job!
