### ISSUE TITLE
OpenSSL Policy with 1.0.2 default (Ubuntu 16.04) / Remove PPA OpenSSL policy

### ISSUE THREAD

**Issue by jordanramstad** [oerdnj/deb.sury.org#760]
This issue came up for me when using https://github.com/lastpass/lastpass-cli with the PPA (though the ppa ended up being the "cause")

That being said, I don't consider this a bug with the PPA, more like OpenSSL itself if even that (It just is too confusing). I would call it more of a feature request.

I am using Ubuntu, but I assume Debian can recreate this under the right conditions.

If the distro ships with a certain version of openssl, and packages are installed that use it before it is upgraded to 1.1, it can lead to those new packages having both versions of openssl added to their shared objects. This leads to segmentation faults.

After looking at the update policy for openssl it was set to 1.1 by the PPA, but Ubuntu had it set to 1.0.2.

```
openssl:
  Installed: 1.0.2g-1ubuntu4.9
  Candidate: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Version table:
     1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
 *** 1.0.2g-1ubuntu4.9 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

The above is on a rebuilt box where I used `apt-mark hold openssl` to prevent it updated since other packages required me to use `apt-get upgrade`. This in the end resolved the issue at least on my end.

In earlier attempts trying to downgrade openssl, I found it left the shared objects leading to it being much easier to just completely rebuild the box rather then fight to "fix" it.

I just wanted to bring this up, if there was anyway for the PPA to let the system decide what version to use for openssl I think that would be for the best, I am only writing this seeing that I don't understand why the policy for the PPA needs to update it above the LTS version of openssl.

I am not totally familiar with the ins and outs of a PPA, so forgive me if what I bring up here is not actually related to the PPA itself.

**Comment by oerdnj** [comment]
OpenSSL 1.1.x contains modern ciphers, that's the reason for update. It might be theoretically possible to update just the libraries and leave the `openssl` package out of it, but that would require some extra time on every OpenSSL upgrade (and that's the time I don't have).

**Comment by oerdnj** [comment]
Anyway it's still a bug in lastpass-cli package. If it requires openssl <= 1.0 than it needs to explicitly set the dependency in the source package.

There's not much to do from here except to recommend to not mix multiple external programs in the same system, hence I am closing the issue.
