### ISSUE TITLE
(deprecated) libsodium packages not even available for download

### ISSUE THREAD

**Issue by frederikbosch** [oerdnj/deb.sury.org#761]
@oerdnj I totally get your earlier made point not having to support a deprecated extension (libsodium) because it is now sodium. However, PHP 7.2 has just been released. It has been days, not months, not years. The majority of the libsodium users - including myself - will start the transformation now. When trying to install the package `libsodium`, also *.deb files were deleted. I find that a little too much. Give people sometime to make the switch.

You would really help me out by just providing the *.deb files in your repository. Hopefully you are willing to put them somewhere available for download.

**Comment by oerdnj** [comment]
If you are talking about the 1.x API, then I am simply not going to provide upstream unsupported security extension. This simply won't happen. If you want to shoot yourself into the foot, that would be your decision, but I won't be taking any part of it.

BTW the upstream (@jedisct1) is referencing this compatibility layer https://github.com/mollie/polyfill-libsodium?

**Comment by frederikbosch** [comment]
Ah, that library is nice for the meanwhile. Thanks, that helps moving towards a complete `sodium` solution.
