### ISSUE TITLE
How can I install php7.2 on ubuntu 16.10 desktop?

### ISSUE THREAD

**Issue by yceruto** [oerdnj/deb.sury.org#762]
Hi, I'm having trouble installing php7.2 on ubuntu 16.10 desktop.

This is my last installed version:
```bash
PHP 7.1.5-1+deb.sury.org~yakkety+1 (cli) (built: May 11 2017 14:08:22) ( NTS )
```
After `apt-get update` I've tried this without success :(
```bash
$ sudo apt-get install -y php7.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.2
E: Couldn't find any package by glob 'php7.2'
E: Couldn't find any package by regex 'php7.2'
```
I guess it does not exist yet? https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php7.2&field.status_filter=published&field.series_filter=

If so, is there some opportunity to make a release for this dist? Thanks!

**Comment by oerdnj** [comment]
No. https://wiki.ubuntu.com/Releases
