### ISSUE TITLE
php7.1-gd and php7.1-intl on stretch

### ISSUE THREAD

**Issue by brianwilkinson** [oerdnj/deb.sury.org#764]
Hi. I just tried to install php7.1 on stretch (from https://hub.docker.com/_/debian/). All the packages I tried to install were OK except php7.1-gd and php7.1-intl which failed with...

_Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-gd : Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
             Depends: libwebp5 but it is not installable
 php7.1-intl : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages._

I appear to have libpng16-16 and libicu57

**Comment by todeveni** [comment]
Unable to reproduce with said stretch docker image

```
$ docker run -it debian:stretch /bin/bash
root@d8fd44b90995:/# apt-get update && apt-get install -y apt-transport-https gnupg2 software-properties-common
root@d8fd44b90995:/# apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 AC0E47584A7A714D
root@d8fd44b90995:/# add-apt-repository -y "deb https://packages.sury.org/php/ stretch main"
root@d8fd44b90995:/# apt-get update
root@d8fd44b90995:/# DEBIAN_FRONTEND=noninteractive apt-get install -y php7.1-cli php7.1-gd php7.1-intl
root@d8fd44b90995:/# php -v
PHP 7.1.12-2+0~20171207160618.12+stretch~1.gbp5c91f3 (cli) (built: Dec  7 2017 16:06:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-2+0~20171207160618.12+stretch~1.gbp5c91f3, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by brianwilkinson** [comment]
OK, a colleague couldn't reproduce either so my problem. Thanks anyway

**Comment by oerdnj** [comment]
I think the OP might not be using the DPA (packages.sury.org) packages at all.

Please provide output of:

`apt-cache policy php7.1-gd`

and

`apt-cache policy php7.1-intl`

**Comment by ngagestudios** [comment]
> 

> I think the OP might not be using the DPA (packages.sury.org) packages at all.
> 
> Please provide output of:
> 
> `apt-cache policy php7.1-gd`
> 
> and
> 
> `apt-cache policy php7.1-intl`

  Version table:
     7.1.26-2+0~20190216175340.13+stretch~1.gbpc20626 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
     7.1.26-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
