### ISSUE TITLE
How to accept title changes?

### ISSUE THREAD

**Issue by binarykitchen** [oerdnj/deb.sury.org#765]
Now with `apt-get update` I get that warning below every time:

```
E: Repository 'http://ppa.launchpad.net/ondrej/php/ubuntu artful InRelease' changed its 'Label' value from '***** The main PPA for PHP (5.6, 7.0, 7.1) with many PECL extensions *****' to '***** The main PPA for supported PHP versions with many PECL extensions *****'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

How can I accept that title change best? And was this really needed? Because everyone will see this and google for a fix that has no hits ...

**Comment by oerdnj** [comment]
I have no idea, try removing and re-adding the repository.

That must some new feature, as I have changed the repository name in the past (when PHP 7.1 was release for example).

**Comment by brunodbo** [comment]
On Ubuntu 17.10, removing the repository (`sudo rm /etc/apt/sources/ondrej-ubuntu-php-artful.list`) and re-adding it (`sudo add-apt-repository ppa:ondrej/php`, then `sudo apt-get update`) fixed this for me, thanks!

**Comment by todeveni** [comment]
Using `apt update` instead of `apt-get update` it will ask interactively.

**Comment by oerdnj** [comment]
I think `add-apt-repository` also has an option to remove the repository instead of adding it, but running `apt update` seems like best option now.

**Comment by Llbe** [comment]
This also works: `apt-get update --allow-releaseinfo-change`
