### ISSUE TITLE
Warning: "Narrowing occurred during type inference"

### ISSUE THREAD

**Issue by PHPGangsta** [oerdnj/deb.sury.org#767]
There is a bug in PHP 7.1.12 which floods the error_log with messages like:

apache2: PHP Warning: Narrowing occurred during type inference. Please file a bug report on bugs.php.net in /xxx/xxxx.php on line 864

https://bugs.php.net/bug.php?id=74980
https://www.google.com/search?q=Narrowing+occurred+during+type+inference

Details and Link to patch:
https://github.com/nextcloud/server/issues/7380#issuecomment-350351633

The workaround to disable opcache is not an option :-) Or to disable error_log.

Would be nice if you could apply that fix, so we don't have to wait until 4th of January. Currently 7.1.12 is unusable in production because of this.

Thanks for your work!

**Comment by oerdnj** [comment]
Done. It should be building right now. If the fixed packages are not available in couple of hours, please reopen the issue.
