### ISSUE TITLE
php-ds package is outdated

### ISSUE THREAD

**Issue by enumag** [oerdnj/deb.sury.org#768]
Today I experienced a bug with the [ds extension](https://pecl.php.net/package/ds) on PHP 7.2.0. It seems to be fixed in the 1.2.4 version of the extension though. I installed the extension using

```
sudo apt-get install php7.2-ds
```

which seems to install version 1.2.0 of the extension instead of 1.2.4. Could you release an update?

```
dpkg -s php-ds | grep Version
# Version: 1.2.0-1+ubuntu16.04.1+deb.sury.org+1
```

Ref:
https://github.com/Roave/BetterReflection/issues/388
https://github.com/php-ds/extension/issues/104

Test code:
```php
$reflection = new ReflectionMethod(\Ds\Map::class, 'copy');
echo $reflection->getReturnType();
// writes "PHP_DS_NS(Collection)", should write "Ds\Collection"
```

**Comment by oerdnj** [comment]
Updated and it's building now.

**Comment by enumag** [comment]
Thank you!
