### ISSUE TITLE
nginx-1.13.8 released

### ISSUE THREAD

**Issue by Showfom** [oerdnj/deb.sury.org#771]
Please update it 💃

**Comment by todeveni** [comment]
Current stable is still 1.12.2.
1.13.8 is the mainline version.

If you wish to use the it, they've got an [official PPA for mainline](https://launchpad.net/~nginx/+archive/ubuntu/development).

**Comment by oerdnj** [comment]
I will as soon as the launchpad build farm is up.

**Comment by oerdnj** [comment]
I have uploaded the build, but it will be just silently sitting there until the build farm is unfrozen again.

**Comment by oerdnj** [comment]
The Ubuntu Trusty build is missing updated hiredis library, that should be fixed now. Also the non-x86 architecture is still disabled, but that's being tracked as #779
