### ISSUE TITLE
Unable to pin packages from repository if mirrored together with other repositories on same host

### ISSUE THREAD

**Issue by Programie** [oerdnj/deb.sury.org#775]
We have an internal aptly host mirroring various Debian repositories including packages.sury.org/php.

The repository currently only defines `n=jessie,c=main` which is pretty generic and therefore unusable for pinning packages in the repository to a higher priority. The only other way would be use `origin`, but that would affect all repositories on the host.

Therefore please specify a unique label so we can use it to pin packages. For example deb.nodesource.com is using `l=Node Source`. What about using `l=packages.sury.org/php`?

**Comment by oerdnj** [comment]
Would this work for you?
```
$ head ./dists/jessie/Release
Origin: deb.sury.org
Label: php
Codename: jessie
Date: Fri, 05 Jan 2018 17:11:51 UTC
Architectures: amd64 armhf arm64 i386
Components: main
```

**Comment by Programie** [comment]
In this case, only the label "php" would work for me as origin would be the host hosting the repository. But it should work, I could use `l=php` to pin packages to the repository.

**Comment by oerdnj** [comment]
I think you are mixing the origin and Origin: (see `apt_preferences` man page).

**Comment by oerdnj** [comment]
```
           A note of caution: the keyword used here is "origin" which can be used to match a hostname. The following record will assign a high priority to all versions available from the server identified by the hostname
           "ftp.de.debian.org"

               Package: *
               Pin: origin "ftp.de.debian.org"
               Pin-Priority: 999

           This should not be confused with the Origin of a distribution as specified in a Release file. What follows the "Origin:" tag in a Release file is not an Internet address but an author or vendor name, such as "Debian" or
           "Ximian".
```

**Comment by oerdnj** [comment]
So in this case this would be `o=deb.sury.org`. But hey this was good idea!

**Comment by Programie** [comment]
Oh, you are right, just saw it. Then it would be perfect and I could use "Origin" to pin the packages to your repository.

**Comment by oerdnj** [comment]
JFTR I dropped the `Label:` and kept only the `Origin:`.

**Comment by oerdnj** [comment]
BTW This unfortunatelly caused #778. But still, it was a good move.
