### ISSUE TITLE
WARNING: The following packages cannot be authenticated!

### ISSUE THREAD

**Issue by krypton-code** [oerdnj/deb.sury.org#777]
Hello. Always used this repository without problems. Now I get a warning, I run command on fresh Ubuntu 16.04.3 (DigitalOcean). Error is received immediately after first the import of the repository. Thanks for the help.
https://pastenow.ru/2GUHS

**Comment by oerdnj** [comment]
That's your local configuration problem. Try removing and adding the PPA again.

**Comment by krypton-code** [comment]
@oerdnj, thank you for help!
