### ISSUE TITLE
The Launchpad build farm is disabled pending maintenance; we do not yet have an ETA.

### ISSUE THREAD

**Issue by swiffer** [oerdnj/deb.sury.org#779]
Hey,

multiple package updates are stuck in "Waiting to build" in PPA.

Is this intentional or is something broken?

Thanks!

**Comment by todeveni** [comment]
I guess it has something to do with [this](https://twitter.com/launchpadstatus/status/948688233029881856)
> The Launchpad build farm is disabled pending maintenance; we do not yet have an ETA.

**Comment by oerdnj** [comment]
Yep, pretty much nothing builds in the PPA.

**Comment by marcorivm** [comment]
I'm getting some Temporary failure errors when trying to do an install on a new docker image. 
`Err:47 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libjbig0 amd64 2.1-3.1+deb.sury.org~xenial+1
  Temporary failure resolving 'ppa.launchpad.net'`

Do you think they might be related??

**Comment by swiffer** [comment]
Packages are published now

**Comment by swiffer** [comment]
Packages are published now

**Comment by swiffer** [comment]
Packages are published now

**Comment by swiffer** [comment]
Packages are published now

**Comment by oerdnj** [comment]
So, the arm builders are back as well now: https://twitter.com/launchpadstatus/status/954609952601116672

powerpc, ppc64el and s390x should follow shortly...

**Comment by oerdnj** [comment]
So, finally the build farm is operational again: https://twitter.com/launchpadstatus/status/956033098860453894

**Comment by ohnotnow** [comment]
Just wondering if I'm missing something - but there doesn't seem to be any sign of the arm builds showing up in the [main 7.1/2 repo list](https://packages.sury.org/php/pool/main/p/php7.2/). Maybe I'm pointing at the wrong place though (rpi/jessie)?
