### ISSUE TITLE
The following packages have unmet dependencies:

### ISSUE THREAD

**Issue by bartkoek** [oerdnj/deb.sury.org#78]
When I try to update to php5.5 on my udoo using the ppa:ondrej/php5 repository I get the following error:

The following packages have unmet dependencies:
 php5 : Depends: libapache2-mod-php5 (>= 5.5.25+dfsg-1+deb.sury.org~precise+2~) but 5.3.10-1ubuntu3 is to be installed or
                 libapache2-mod-php5filter (>= 5.5.25+dfsg-1+deb.sury.org~precise+2~) but it is not going to be installed or
                 php5-cgi (>= 5.5.25+dfsg-1+deb.sury.org~precise+2~) but it is not going to be installed or
                 php5-fpm (>= 5.5.25+dfsg-1+deb.sury.org~precise+2~) but 5.3.10-1ubuntu3 is to be installed
        Depends: php5-common (>= 5.5.25+dfsg-1+deb.sury.org~precise+2~) but 5.3.10-1ubuntu3 is to be installed
E: Unable to correct problems, you have held broken packages.

What can I do to solve this?

**Comment by oerdnj** [comment]
Looks like a disabled PPA or some other local configuration problem to me, do:

```
apt-cache policy php5
```

and it will probably not show up PPA packages.

Cheers,
Ondrej

**Comment by bartkoek** [comment]
Dead Ondrej,

Thank you for your response! When I do apt-cache policy php5 it shows the following:

php5:
  Installed: 5.3.10-1ubuntu3
  Candidate: 5.5.25+dfsg-1+deb.sury.org~precise+2
  Version table:
     5.5.25+dfsg-1+deb.sury.org~precise+2 0
        500 http://ppa.launchpad.net/ondrej/php5/ubuntu/ precise/main armhf Packages
 *** 5.3.10-1ubuntu3 0
        500 http://ports.ubuntu.com/ precise/main armhf Packages
        100 /var/lib/dpkg/status


Looks like the ppa is enabled. Do you have any hints?

**Comment by oerdnj** [comment]
Hope I am not dead yet... ;) 

I see you forgot to mention armhf architecture, launchpad doesn't build armhf (at least) for precise. 

Ah, just found this https://dev.launchpad.net/CommunityARMBuilds

I'll check how long does the build take and if it qualifies... 

Cheers, 
Ondřej 

On June 11, 2015 4:46:13 PM GMT+02:00, bartkoek <notifications@github.com> wrote:
>Dead Ondrej,
>
>Thank you for your response! When I do apt-cache policy php5 it shows
>the following:
>
>php5:
>  Installed: 5.3.10-1ubuntu3
>  Candidate: 5.5.25+dfsg-1+deb.sury.org~precise+2
>  Version table:
>     5.5.25+dfsg-1+deb.sury.org~precise+2 0
>500 http://ppa.launchpad.net/ondrej/php5/ubuntu/ precise/main armhf
>Packages
> *** 5.3.10-1ubuntu3 0
>        500 http://ports.ubuntu.com/ precise/main armhf Packages
>        100 /var/lib/dpkg/status
>
>
>Looks like the ppa is enabled. Do you have any hints?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/78#issuecomment-111158758

-- 
Ondřej Surý

**Comment by bartkoek** [comment]
Haha, sorry! Of course I wanted to type dear! 

I'm eager to know what launchpad will say about the php build. Thank you in advance!

**Comment by bartkoek** [comment]
Hi Ondřej,

Did you manage to build the ARM version?

Thanks!

**Comment by oerdnj** [comment]
Here: https://answers.launchpad.net/launchpad/+question/279597

**Comment by oerdnj** [comment]
The armhf builds should be available from most repositories. So builds are failing though, so you might want to check a specific repository whether the build was successful or not.
