### ISSUE TITLE
Cannot install PHP 7.2.1 or 7.1.13

### ISSUE THREAD

**Issue by emodric** [oerdnj/deb.sury.org#780]
As far as I can see, PHP 7.2.1 build is provided in the PPA, however, my system does not recognize it for some reason, there are no packages to be upgraded. The same happens with PHP 7.1.13.

Is this a known issue? I don't know where to begin to look for a problem.

Using Ubuntu 17.10.

Thanks!

**Comment by PHPGangsta** [comment]
I have the same problem. I have installed:
PHP 7.1.12-3+ubuntu16.04.1+deb.sury.org+1

I can see on launchpad that there is
7.1.13-1+ubuntu16.04.1+deb.sury.org+1

But it's not upgraded (`apt-get update` + `apt-get dist-upgrade`).

Maybe some dependency is blocking the upgrade?

**Comment by todeveni** [comment]
The packages are updated, but not built yet.
See #779

**Comment by oerdnj** [comment]
dup of #779
