### ISSUE TITLE
php-rrd:on php 7.2 bad directory

### ISSUE THREAD

**Issue by Novgor** [oerdnj/deb.sury.org#781]
PHP Warning:  PHP Startup: Unable to load dynamic library 'rrd.so' (tried: /usr/lib/php/20170718/rrd.so (/usr/lib/php/20170718/rrd.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/rrd.so.so (/usr/lib/php/20170718/rrd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

# dpkg -L php-rrd
/.
/etc
/etc/php
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/rrd.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/rrd.ini
/etc/php/5.6
/etc/php/5.6/mods-available
/etc/php/5.6/mods-available/rrd.ini
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/rrd.ini
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php-rrd
/usr/share/doc/php-rrd/changelog.Debian.gz
/usr/share/doc/php-rrd/copyright
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/rrd.so
/usr/lib/php/20151012
/usr/lib/php/20151012/rrd.so
/usr/lib/php/20160303
/usr/lib/php/20160303/rrd.so
/usr/lib/php/20160731
/usr/lib/php/20160731/rrd.so

but 
# dpkg -L php7.2-common | grep lib
/usr/lib
/usr/lib/php
/usr/lib/php/7.2
/usr/lib/php/7.2/php.ini-development
/usr/lib/php/7.2/php.ini-production.cli
/usr/lib/php/7.2/php.ini-production
/usr/lib/php/20170718

so seems in php-rrd correct path to rrd.so for php-7.2 should be /usr/lib/php/20170718/rrd.so instead  /usr/lib/php/20160731/rrd.so

**Comment by oerdnj** [comment]
Issues a rebuild.
