### ISSUE TITLE
php-mcrypt depends on non-existing php7.2-mcrypt

### ISSUE THREAD

**Issue by Ralpht12** [oerdnj/deb.sury.org#782]
$ apt-cache show php-mcrypt
    Package: php-mcrypt
    Source: php-defaults (57+ubuntu16.04.1+deb.sury.org+1)
    Priority: optional
    Section: php
    Installed-Size: 12
    Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
    Architecture: all
    Version: 1:7.2+57+ubuntu16.04.1+deb.sury.org+1
    Depends: php-common, php7.2-mcrypt

The faulty dependency causes apt-get to hold back a php-mcrypt update:

    $ apt-get install php-mcrypt
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     php-mcrypt : Depends: php7.2-mcrypt but it is not installable
    E: Unable to correct problems, you have held broken packages.

I have PHP versions 5.6, 7.0, 7.1, 7.2 running on my server and version 5.6 is set as the default PHP version (a web app still requires 5.6).

Since php-mcrypt is deprecated PHP 7.2 isn't supporting it, so a php7.2-mcrypt package will (probably) never come into existence.

Should I either wait for the dependency issue to be fixed? As I can't find this dependency in `/var/lib/dpkg/status` and manually edit it. Or should I simply remove the entire php-mcrypt package? Though I'm not 100% sure whether something requires php-mcrypt... so I prefer not to remove php-mcrypt for now.

**Comment by oerdnj** [comment]
Removed `php-mcrypt` package from `php-defaults` source. It's also safe to remove from your system, it is a empty dependency package.

Also why you have PHP 5.6, 7.0, 7.1 and 7.2 installed on your system when you need just PHP 5.6?

**Comment by Ralpht12** [comment]
Great, thanks for the quick fix and the mcrypt removal info! Re `php-defaults`: I assume I have to wait for the next update to be released, right? Or should I implement the fix manually?

To answer your question: I have another VPS that only supports official/default Ubuntu PPAs and when its PHP gets a major update, previous versions are usually auto-removed (if I remember correctly). I simply assumed that the same would be the case with Ondrej PPA PHP updates and on top of that I figured the point updates would all fall under one single PHP7 flag... so until yesterday, when trying to fix the mcrypt issue, I assumed the VPS was only running 5.6 and 7.2. Since I now know that that is not the case, I'll remove 7.0 and 7.1 from the system.

The reason I'm running both PHP5.6 and 7+ is because the PHP5.6 web app should soon run on PHP7, since 5.6 is nearing its end of life date. And once it does, having both PHP versions ready to run, makes switching to PHP7 a breeze I hope. And in general I like to be prepared for the unexpected (it's unclear when exactly the web app devs will move to PHP7).
