### ISSUE TITLE
PHP 7.1.13 not available for amd64 in Jessie

### ISSUE THREAD

**Issue by valouille** [oerdnj/deb.sury.org#783]
Hello,

I was looking to install the 7.1.13 version on PHP on a Jessie server, but this version is available only for :
* Stretch i386
* Stretch amd64
* Jessie i386

Unfortunately, no amd64 Jessie available. Are you having trouble building them, or maybe is there an issue with a building script ?

Regards

**Comment by arkadicolson** [comment]
+1

**Comment by oerdnj** [comment]
That's intermittent issue, I have launched a rebuild that should fix it.

**Comment by oerdnj** [comment]
Should be fixed now.
