### ISSUE TITLE
Failed to fetch ... php packages due to Hash Sum mismatch

### ISSUE THREAD

**Issue by numberOneUser** [oerdnj/deb.sury.org#786]
Hello, we have encountered this error a few times today while building vagrant using an updated Ubuntu 14.04  base box image....

sudo apt-get install php5.6

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-defaults/php-common_58+ubuntu14.04.1+deb.sury.org+1_all.deb  Hash Sum mismatch

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php5.6/php5.6-readline_5.6.33-1+ubuntu14.04.1+deb.sury.org+1_amd64.deb  Hash Sum mismatch

sudo apt-get update

W: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/trusty/main/i18n/Translation-en  Hash Sum mismatch

One or both of these errors have been showing up on.... multiple vagrant rebuilds... multiple machines... multiple internet connections.  Also, we had some success earlier today until the last few hours of update failures.  Are there any known issues with the php PPA right now?

Update: I was running through some php packages and php5.6-mcrypt needed --fix-missing, is there a better place to message in regards to that package specifically?

**Comment by oerdnj** [comment]
Usually these go away by themselves. I suspect there's an internal CDN in place. Anyway that's the question you need to ask the launchpad people not me.
