### ISSUE TITLE
After "apt upgrade" on 14/01/2018 , PHP7.0 with Server API "FPM/FastCGI" and Apache mod_worker, turned into PHP7.2 with Server API "Apache 2.0 Handler" and Apache mod_prefork

### ISSUE THREAD

**Issue by FabioDa10** [oerdnj/deb.sury.org#787]
Hi,
first of all: Ondřej Surý, thank you for all your work ;-)
Then forgive my english, it's not my "default language"...

Last weekend I made "apt update; apt upgrade" on a dev server (a VirtualBox VM on my PC), an Ubuntu 16.04.3 64bit with added repo "ppa:ondrej/php".

BEFORE this update, I had phpinfo() showing (in different sites):
PHP Version 5.6.32-1+ubuntu16.04.1+deb.sury.org+2
Server API: **FPM/FastCGI**
Loaded Configuration File: **/etc/php/5.6/fpm/php.ini**

PHP Version 7.0.26-2+ubuntu16.04.1+deb.sury.org+2
Server API: **FPM/FastCGI**
Loaded Configuration File: **/etc/php/7.0/fpm/php.ini**

AND the running Apache2 was "worker".
I used the following during setup:
```
> a2dismod php5.6 php7.0 php7.1 php7.2 mpm_prefork mpm_event
> a2enmod actions fastcgi alias mpm_worker rewrite
```

-----

NOW, the sites running on PHP5.6 are OK, they show:
PHP Version 5.6.33-1+ubuntu16.04.1+deb.sury.org+1
Server API: **FPM/FastCGI**
Loaded Configuration File: **/etc/php/5.6/fpm/php.ini**

BUT the sites that used to be running on PHP7.0 give "500 INTERNAL SERVER ERROR", and now they show:
PHP Version 7.2.1-1+ubuntu16.04.1+deb.sury.org+1
Server API: Apache 2.0 Handler
Loaded Configuration File: /etc/php/7.2/apache2/php.ini

I know that "500 INTERNAL SERVER ERROR" is due to the PHP configuration not set as I need it to be... but think about an update on a production server: ALL PHP7 sites down :-(

I checked all /etc/ dir before and after update with diff.
The CHANGED files are:
/etc/alternatives/phar
/etc/alternatives/phar.phar
/etc/alternatives/php
/etc/php/7.0/apache2/conf.d/*
/etc/php/7.1/apache2/conf.d/*

The other differences are NEW files:
/etc/apache2/mods-available/php7.2.conf
/etc/apache2/mods-available/php7.2.load
/etc/php/7.2/cli/*
/etc/php/7.2/mods-available/*

IMHO the real bad part is that, with no changes to Apache2 configuration files, mod_worker has been DISABLED, and mod_prefork has been ENABLED during "Setting up libapache2-mod-php7.2":
```
Creating config file /etc/php/7.2/apache2/php.ini with new version
Module mpm_worker disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
apache2_invoke: Enable module php7.2
```

Can you please investigate and tell me if I am wrong and, in case I did nothing bad, please consider avoiding changes that could alter the running Apache modules and PHP binaries.

Any answers is welcome, I thank in advance for the kind and helpful ones ;-)

Greetings,
Fabio.

P.S.: I solved running again:
```
> a2dismod php5.6 php7.0 php7.1 php7.2 mpm_prefork mpm_event
> a2enmod actions fastcgi alias mpm_worker rewrite
> service apache2 restart

```

**Comment by oerdnj** [comment]
If you don't want to have the PHP update to the latest upstream stable release, then uninstall the generic (non-versioned) dependency packages:

```
Package: php
[...]
Description-en: server-side, HTML-embedded scripting language (default)
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on Debian's default
 PHP version (currently X.Y).
```

Also, you are required to review any `apt-get update; apt-get dist-upgrade` you do. The apt was listing all the new packages it's going to install.

**Comment by FabioDa10** [comment]
OK, "with great power comes a great responsibility"... but I think I didn't make clear which is the point of my "issue".

BTW, I didn't do a "dist-upgrade", I don't have "php" package installed, nor any php*.* ones
```
> apt remove php php5.6 php7.0 php7.1 php7.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'php' is not installed, so not removed
Package 'php7.0' is not installed, so not removed
Package 'php5.6' is not installed, so not removed
Package 'php7.1' is not installed, so not removed
Package 'php7.2' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

I installed EXACTLY with the following, three times on different VM, only "cli" and "fpm" versions of PHP5.6 and PHP7.0:
```
> apt install apache2
> add-apt-repository ppa:ondrej/php
> apt update
> apt upgrade
> apt install php7.0-cli php7.0-fpm php7.0-mysqli php7.0-mbstring php7.0-gd php7.0-bcmath php7.0-bz2 php7.0-curl php7.0-soap php7.0-zip php7.0-xml
> apt install php5.6-cli php5.6-fpm php5.6-mysqli php5.6-mbstring php5.6-gd php5.6-bcmath php5.6-bz2 php5.6-curl php5.6-soap php5.6-zip php5.6-xml
> a2dismod php5.6 php7.0 php7.1 php7.2 mpm_prefork mpm_event
> a2enmod actions fastcgi alias mpm_worker rewrite
> service apache2 restart
> apt install mysql-server mysql-client
```

Last weekend I did
> apt update
> apt upgrade

What I didn't like is NOT the upgrading of all PHP packages (e.g. php->php7.2), what did break my running sites (in LAN intranet) was that **Apache mod_worker has been DISABLED, and mod_prefork ENABLED** with no possibility (to my knowledge) to avoid it: apache2 has been restarted during set up of "libapache2-mod-php7.2" (required by "php7.2-cli"), so on a production server this means all PHP7 down in a matter of seconds, and a lot more time to understand and to react.

I kindly ask you to show me how I can predict that a setup script is going to enable/disable modules with no question, reading the packages list and their description.

**Comment by FabioDa10** [comment]
I updated right now, and I think the issue I noticed has finally been addressed:
```
Setting up libapache2-mod-php7.2 (7.2.2-1+ubuntu16.04.1+deb.sury.org+1) ...
libapache2-mod-php7.2: not switching MPM - disabled by maintainer

```
BTW, I noticed that at the moment "libapache2-mod-php7.2" is no more required by "php7.2-cli", while I am quite sure it was at the time I initially opened the issue.

Anyway, thank you Mr.Ondřej for the maintenance job.

Greetings,
Fabio.

**Comment by oerdnj** [comment]
php7.2-cli never required libapache2-mod-php7.2

**Comment by FabioDa10** [comment]
**Of course you're right**: I made this wrong assumption while trying to understand what caused the issue I had, while it is the opposite (**libapache2-mod-php7.2 requires php7.2-cli**).

It looks like you didn't have time to read my previous message: it is not a problem to me, I only think that someone else could get wrong informations, this is the main reason I reply again.

To prevent someone else from having my same problem: if you ever made a "LAMP" install in Ubuntu first install, and you don't want to ever use PHP as Apace module, consider the following, possibly overabundant, command:
`apt remove php php5.6 php7.0 php7.1 php7.2 libapache2-mod-php libapache2-mod-php5.6 libapache2-mod-php7.0 libapache2-mod-php7.1 libapache2-mod-php7.2`
