### ISSUE TITLE
Strange behaviour of callbacks array_map, call_user_func_array

### ISSUE THREAD

**Issue by rimuln** [oerdnj/deb.sury.org#788]
Not sure if this is right place.

At one hosting is installed this version of PHP:

 PHP Version 5.6.33-1+ubuntu16.04.1+deb.sury.org+1
When I tried deploy Nette Application to this server I got errors. After analyzing it looks for me that it is probably bug in the PHP. On windows 5.6.33 x64-vc11-ts it works as expected. on another hosting with 5.5.38 it works too.
I'm trying to solve it with hosting, but there is horrible technical support:( They said that have the newest version of PHP and nobody reports error till now.

Test contains 4 examples.
1. use array_map to call class_exists -> this failed I expect same/similar output as in 2nd example
2. direct use of class_exists -> this works 
3. direct usage of preg_replace_callback - this works
4 use call_user_func_array to call preg_replace_callback - again failed I expect same/similar results as in 3rd example

failed runs on mentioned hosting
![lezeni-test-banan-updated2](https://user-images.githubusercontent.com/14931517/35100198-2eafb2e2-fc5b-11e7-95d7-9d5948b2db22.png)

reference run on different platform
![lezeni-test-localhost-updated2](https://user-images.githubusercontent.com/14931517/35100202-366de382-fc5b-11e7-8e86-2b82ec4b5e43.png)
![lezeni-test-pipni-updated2](https://user-images.githubusercontent.com/14931517/35100208-3a41b81c-fc5b-11e7-84d8-5124c2a3557f.png)

source code of test
[test.php.txt](https://github.com/oerdnj/deb.sury.org/files/1642954/test.php.txt)

zip contains phpinfo from hosting and localhost and original exceptions from Tracy\Debbuger
[bug-php5.6.zip](https://github.com/oerdnj/deb.sury.org/files/1642969/bug-php5.6.zip)

I would know if it is some configuration problem of hosting or PHP orbug in libraries or something other

**Comment by oerdnj** [comment]
This doesn't seem like anything closely related to the bug in packaging. You'll need to report this to upstream bug tracker: https://bugs.php.net/how-to-report.php
