### ISSUE TITLE
Error in update after add repository

### ISSUE THREAD

**Issue by bergpb** [oerdnj/deb.sury.org#789]
Hello, i get this error in sudo apt update, after add repository:

Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu bionic Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

System: Debian 9, Google Cloud Platform
Anyone can fix this?

**Comment by todeveni** [comment]
Debian doesn't use PPA, it's for Ubuntu.

For Debian use packages from [packages.sury.org](https://packages.sury.org/php/README.txt)

**Comment by oerdnj** [comment]
Also bionic is the development release and those are supported only when reasonable (and the definition of reasonable in this context is at my sole discretion).
