### ISSUE TITLE
php7.1-memcached is missing

### ISSUE THREAD

**Issue by LeonMelis** [oerdnj/deb.sury.org#794]
There seems to be no memcached plugin for php7.1 in the repo. When trying to install `php7.1-memcached` it defaults to `php-memcached`, which requires `php-7.2` as a dependency.

See:
```bash
root@1633f97cd212:/# apt-get install php7.1 php7.1-memcached
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php-memcached' instead of 'php7.1-memcached'
The following extra packages will be installed:
  init-system-helpers libapache2-mod-php7.1 libargon2-0 libbsd0 libedit2 libmemcached11 libmemcachedutil2 libsodium23 libssl1.0.2
  php-common php-igbinary php-msgpack php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-readline php7.2-cli php7.2-common
  php7.2-json php7.2-opcache php7.2-phpdbg php7.2-readline psmisc ucf
Suggested packages:
  php-pear
Recommended packages:
  php-readline
The following NEW packages will be installed:
  init-system-helpers libapache2-mod-php7.1 libargon2-0 libbsd0 libedit2 libmemcached11 libmemcachedutil2 libsodium23 libssl1.0.2
  php-common php-igbinary php-memcached php-msgpack php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-readline php7.2-cli
  php7.2-common php7.2-json php7.2-opcache php7.2-phpdbg php7.2-readline psmisc ucf
0 upgraded, 27 newly installed, 0 to remove and 37 not upgraded.
Need to get 8857 kB of archives.
After this operation, 36.2 MB of additional disk space will be used.
```

Note that:
```
Note, selecting 'php-memcached' instead of 'php7.1-memcached'
```
And:
```
The following extra packages will be installed:
[snip]
php7.2-cli php7.2-common  php7.2-json php7.2-opcache php7.2-phpdbg php7.2-readline 
```

Is there  a reason for this? I've read [here](https://github.com/Homebrew/homebrew-php/issues/3841) that memcached had problems with 7.1, but can't find anything about that.

**Comment by oerdnj** [comment]
It's not missing.

But you are missing matching `phpX.Y-cli` package in your example, thus a generic `php-cli` is pulled, which in turns pulls default PHP version (e.g. 7.2).

**Comment by LeonMelis** [comment]
Thanks for the explanation. I guess I'll have to redesign my Dockerfiles, as this behavior of `apt` won't allow for reproducible builds...

**Comment by beliys** [comment]
Is it possible to create `phpX.Y-EXT_NAME` for all php extensions, because using `php-EXT_NAME` and depends style as `phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226` make many troubles with puppet install? Now we need to configure requires for some package from virtual package `phpapi` as `phpX.Y-EXT_NAME` for every `php-EXT_NAME` extensions and it don't flexible for installations. Another we have installed php7.2-* packages with less php versions.

**Comment by oerdnj** [comment]
No, that has different sets of problems. Also every package has correct Provides that provides phpX.Y-ext aliases.
