### ISSUE TITLE
[Apache 2] modification of mpm after each update

### ISSUE THREAD

**Issue by Fluoo** [oerdnj/deb.sury.org#796]
Hello,

I use your repository and I want to thank you to the job you done.
I'm post here beacuse I have a problem : I use apache with MPM_event and each time I update apache with your repository it disable MPM_event to enable MPM_prefork. It seems that the module php7.2 require the MPM_prefork perhaps it's the reason why the MPM_prefork is enable each time I update ?

Do you have an idea to keep my MPM_event enabled each time I update ?

Regards,
And Thanks again for your great job.

**Comment by oerdnj** [comment]
Yeah, uninstall `libapache2-mod-php7.2` package and use `php7.2-fpm` instead.

**Comment by FabioDa10** [comment]
I updated right now, and I think the same issue I noticed has finally been addressed:
```
Setting up libapache2-mod-php7.2 (7.2.2-1+ubuntu16.04.1+deb.sury.org+1) ...
libapache2-mod-php7.2: not switching MPM - disabled by maintainer

```
