### ISSUE TITLE
Debian9 apt-get update problem with https://packages.sury.org/

### ISSUE THREAD

**Issue by georgezip** [oerdnj/deb.sury.org#797]
After I did this:
${SUDO} apt-get -y install apt-transport-https lsb-release ca-certificates
${SUDO} wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg --no-check-cert
${SUDO} sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
${SUDO} apt-get update

there is an error:

Błąd:11 https://packages.sury.org/php  Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
W: The repository 'http://packages.sury.org/php  Release' does not have a Release file.
E: Nie udało się pobrać https://packages.sury.org/php/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

if I run:
gnutls-cli -p 443 packages.sury.org
Processed 137 CA certificate(s).
Resolving 'packages.sury.org:443'...
Connecting to '217.31.192.150:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=packages.sury.org', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x03bd03a306d502982366c7bbdcb8849fd868, RSA key 4096 bits, signed using RSA-SHA256, activated `2017-12-07 22:13:18 UTC', expires `2018-03-07 22:13:18 UTC', key-ID `sha256:588b93322c0bdf142070a43187160c95fe7204875216e5bf02a4525b57c54a70'
        Public Key ID:
                sha1:0407a66ef6dd6832efdce8e169520aaee8974ee7
                sha256:588b93322c0bdf142070a43187160c95fe7204875216e5bf02a4525b57c54a70
        Public key's random art:
                +--[ RSA 4096]----+
                |      +..        |
                |     o o         |
                |    .   .        |
                |   .   .         |
                |    +   S        |
                |   o.. ..o       |
                |   o.o+o= .      |
                | ..o+ oB.=       |
                |o.+o E =O .      |
                +-----------------+

- Certificate[1] info:
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', key-ID `sha256:60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18'
- Status: The certificate is NOT trusted. The certificate issuer is unknown.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** handshake has failed: Error in the certificate.

please help

**Comment by oerdnj** [comment]
Try removing `ca-certificates` package and install it again. It looks like something went wrong when installing the CA certificates files.

**Comment by oerdnj** [comment]
Most probably you have disabled some certificates when installing the `ca-certificates` package, because on my systems the `gnutls-cli` gives:

```
$ gnutls-cli -p 443 packages.sury.org
Processed 166 CA certificate(s).
```

**Comment by georgezip** [comment]
oh yes, that was a problem. After reinstalling ca-certificates everything is ok :)
thank you

**Comment by mbourqui** [comment]
Hi,

I encounter the same issue, but jus re-installing the ca-certificates did not work. I tried the following:

*
      sudo apt-get -f install
      sudo dpkg --purge --force-depends ca-certificates
      sudo apt-get -f install

* Removed the `php.gpg` key and the `php.list`, re-applied the commands from the https://packages.sury.org/php/README.txt (but had to use the `-k` option of curl).
* `wget -q https://packages.sury.org/php/apt.gpg -O - | sudo apt-key add -`
* https://www.brightbox.com/blog/2014/03/04/add-cacert-ubuntu-debian/
* `update-ca-certificates -f`

But the problem is still the same. curl and wget say that the certificate is expired, event though Firefox says it is still valid until March.

Am I missing something?
