### ISSUE TITLE
Request for Tideways XHProf Extension

### ISSUE THREAD

**Issue by kbond** [oerdnj/deb.sury.org#798]
Tideways has split their extension (see https://tideways.io/profiler/blog/releasing-new-tideways-xhprof-extension)

> With the 5.0 version of the Tideways PHP extension, we are separating the open-source extension to generate XHProf compatible profiling data from our own timeline/tracing Profiler, so we can work on improving them independently.

> This is why the now released Tideways XHProf open-source extension has a new name tideways_xhprof, while the existing extension name tideways will continue to be used for our software as a service / product.

**Comment by beliys** [comment]
> We have just pushed the  **beta** of a new version 5.0 of our XHProf fork to Github.

Now it in beta...

**Comment by oerdnj** [comment]
The new modules always have lower priority when it comes to chipping off my free time. So, yes, I will package it, but it will take some time.

**Comment by flip111** [comment]
I would also like xhprof in php7, this seems to be the only free implementation of it at the moment.

**Comment by NicoHaase** [comment]
Is there any good reason not to use their own repositories like documented on https://support.tideways.com/article/85-install-on-debian-ubuntu?

**Comment by oerdnj** [comment]
Already done for some time
