### ISSUE TITLE
Request for mod_rpaf

### ISSUE THREAD

**Issue by tersmitten** [oerdnj/deb.sury.org#80]
We really like your work on the PHP 5.6 PPA. We would also love to see `mod_rpaf` (https://github.com/gnif/mod_rpaf) being added. Are you interested in building that?

Regards, Mischa

**Comment by oerdnj** [comment]
Hi, I will work on adding new packages to the repositories this week.

**Comment by tersmitten** [comment]
That's great to hear @oerdnj. If you need any help building the package (compiling the .so) please let me know.

**Comment by AnrDaemon** [comment]
You do not need mod_rpaf for Apache 2.4 http://httpd.apache.org/docs/trunk/mod/mod_remoteip.html

**Comment by tersmitten** [comment]
You do if you want to keep `$_SERVER['HTTPS']` and `$_SERVER['SERVER_PORT']`

**Comment by AnrDaemon** [comment]
Change your setup so that these variables bear no significance.
That'll be a much cleaner solution.

**Comment by tersmitten** [comment]
@AnrDaemon sorry but I don't want that

**Comment by robfrawley** [comment]
> You do if you want to keep $_SERVER['HTTPS'] and $_SERVER['SERVER_PORT']

Direct reliance on globals in such a way that it is *less effort* to add a compiled dependency than edit the application source, huh?

**Comment by AnrDaemon** [comment]
He just don't know how to edit PHP files…

**Comment by oerdnj** [comment]
@AnrDaemon @tersmitten Guys, I won't tollerate ad hominem attacks here!

**Comment by oerdnj** [comment]
'$_SERVER['HTTPS'] can be set using SetEnvIf in Apache 2.4: https://github.com/dmikusa-pivotal/cf-php-apache-buildpack/issues/6#issuecomment-31485783

You can set SERVER_PORT (why is that important at all?) using mod_rewrite.

The rest can be solved using mod_remoteip. So I don't feel any urge to package mod_rpaf at all.

**Comment by tersmitten** [comment]
Ok @oerdnj, I'll try to get that working
