### ISSUE TITLE
Unable to load dynamic library '/usr/lib/php/20151012/wddx.so'

### ISSUE THREAD

**Issue by beliys** [oerdnj/deb.sury.org#800]
I have next error with using php-xml extention with all version php on debian 9:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/wddx.so' - /usr/lib/php/20151012/wddx.so: undefined symbol: php_XML_SetUserData in Unknown on line 0`

For fixing need rename `20-wddx.ini` to `25-wddx.ini` and restart php. Please fix it in package...

**Comment by oerdnj** [comment]
That’s not right. xml should be loaded with priority 15. Could you confirm this is the case?

**Comment by beliys** [comment]
wddx.so should be loaded after xml.so and priority 15 for xml is correct. Also please add removing duplicates  for symlinks  when we update packages after changing the extensions priority. Thanks.

**Comment by oerdnj** [comment]
So you are saying that xml extension has symlink 15-xml.ini, but 20-wddx.ini is loaded first?

**Comment by beliys** [comment]
No, priority 15 for xml is correct.

**Comment by oerdnj** [comment]
> For fixing need rename 20-wddx.ini to 25-wddx.ini and restart php. Please fix it in package...

So far, you haven't demonstrated this is needed.

Or perhaps you have been running this even before this commit?

> commit 34f4282969e05fe8164fe226ffcb15755483c49d
> Author: Ondřej Surý <ondrej@sury.org>
> Date:   Tue Feb 23 14:11:02 2016 +0100
> 
>     XML extension has to be loaded before WDDX or XMLRPC-EPI extensions

Feel free to reopen the bug if can provide a way to reproduce it.

**Comment by beliys** [comment]
Well, I'm confused because now i can't reproduce it more on test server.
