### ISSUE TITLE
Fix installing php7.2-* packages with less php versions

### ISSUE THREAD

**Issue by beliys** [oerdnj/deb.sury.org#801]
Is it possible to create `phpX.Y-EXT_NAME` for all php extensions, because using `php-EXT_NAME` and depends style as `phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226` make many troubles with puppet install? Now we need to configure requires for some package from virtual package `phpapi` as `phpX.Y-EXT_NAME` for every `php-EXT_NAME` extensions and it don't flexible for installations. Another we have installed php7.2-* packages with less php versions.

**Comment by oerdnj** [comment]
Copied the answer from the first occurrence of your question:

No, that has different sets of problems. Also every package has correct Provides that provides phpX.Y-ext aliases.

**Comment by beliys** [comment]
Do you have any idea how it happened and how need fixing it?

**Comment by beliys** [comment]
My first issue was correct. For reproduce it we can try installing manually as puppet server without set requires for most extensions:
1) Install correct:
```
# apt-get install -y php7.0-fpm && apt-get install -y php7.0-memcache
# dpkg -l | grep php
ii  php-common                    1:59+0~20180122053946.6+stretch~1.gbp70c3ba                     all          Common files for PHP packages
ii  php-memcache                  3.0.9~20160311.4991c2f-6+0~20170825111229.1+stretch~1.gbpb69873 amd64        memcache extension module for PHP
ii  php7.0-cli                    7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                 7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        documentation, examples and common module for PHP
ii  php7.0-fpm                    7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-json                   7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        JSON module for PHP
ii  php7.0-opcache                7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        Zend OpCache module for PHP
ii  php7.0-readline               7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        readline module for PHP
```
2) Install php7.2 extensions with less php version (as can install from puppet):
```
# apt-get install -y php7.0-memcache && apt-get install -y php7.0-fpm
# dpkg -l | grep php
ii  php-common                    1:59+0~20180122053946.6+stretch~1.gbp70c3ba                     all          Common files for PHP packages
ii  php-memcache                  3.0.9~20160311.4991c2f-6+0~20170825111229.1+stretch~1.gbpb69873 amd64        memcache extension module for PHP
ii  php7.0-cli                    7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                 7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        documentation, examples and common module for PHP
ii  php7.0-fpm                    7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-json                   7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        JSON module for PHP
ii  php7.0-opcache                7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        Zend OpCache module for PHP
ii  php7.0-readline               7.0.27-1+0~20180114070557.15+stretch~1.gbp3bc0e2                amd64        readline module for PHP
ii  php7.2-cli                    7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                 7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        documentation, examples and common module for PHP
ii  php7.2-json                   7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        JSON module for PHP
ii  php7.2-opcache                7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        Zend OpCache module for PHP
ii  php7.2-phpdbg                 7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.2-readline               7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a                 amd64        readline module for PHP
```

**Comment by beliys** [comment]
Please respond or reopen issue if will be fix a little later.

**Comment by beliys** [comment]
Up

**Comment by oerdnj** [comment]
Have you read https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions

**Comment by beliys** [comment]
> If you require specific PHP version you need to use versioned package names, e.g. apt-get install php5.6 php5.6-fpm

In our case we using `apt-get install -y php7.0-memcache && apt-get install -y php7.0-fpm` but we need set requires (php7.0-fpm) for all non specific version extensions. Is it possible to create only specific version package without next depends style as `phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226`?
I can help with changes for ci or build scripts if need some help with it.

**Comment by MatthiasKuehneEllerhold** [comment]
Quoting the FAQ:

> **Why is php7.2-cli always installed?**
> 2. The real packages has always precedence over virtual. Thus although php5.6-json Provides php-json, the real php-json package is pulled by default. This might happen when installing php-memcached package that Depends (has to depend) on php-json. The workaround is to explicitly list the package providing virtual php-json, e.g. for PHP 5.6 you need to type: apt-get install php5.6-json php-memcached.

**Comment by beliys** [comment]
Yeap, I'm understand it, but I want to know about 
> Is it possible to create only specific version package?
> I can help with changes for ci or build scripts if need some help with it.
