### ISSUE TITLE
php7.1 Unable to load dynamic library pdo_mysql 

### ISSUE THREAD

**Issue by TamiasSibiricus** [oerdnj/deb.sury.org#804]
Hi got problem with loading pdo_mysql with php7.1 on Debian 8.10 Jessie

There is also installed php7.0 latest update from sury repo and there is no any problems with pdo mysql module.
Removing and installing module again do not help me. So i guess it is dynamic module compilation problem.

Here is apt-cache and php info:

```
# apt-cache policy php7.1-mysql
php7.1-mysql:
  Installed: 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa
  Candidate: 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa
  Version table:
 *** 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa 0
       1001 https://packages.sury.org/php/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
# php7.1 -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/pdo_mysql.so' - /usr/lib/php/20160303/pdo_mysql.so: undefined symbol: pdo_parse_params in Unknown on line 0
[PHP Modules]
Core
curl
...
[Zend Modules]
Zend OPcache
```

**Comment by oerdnj** [comment]
You actually haven’t provided any information about the error. “Problem with loading” can mean a lot of things. Also if you are doing any customizations then you’ll need to reproduce the error on a vanilla system.

**Comment by oerdnj** [comment]
But as a first thing please make sure that pdo module is loaded with lower priority. 

What’s the output of:
ls -l /etc/php/7.1/cli/conf.d/
?

**Comment by TamiasSibiricus** [comment]
```
# ls -l /etc/php/7.1/cli/conf.d/
lrwxrwxrwx 1 root root 39 лют  1 17:30 10-mysqlnd.ini -> /etc/php/7.1/mods-available/mysqlnd.ini
lrwxrwxrwx 1 root root 39 лют  1 17:18 10-opcache.ini -> /etc/php/7.1/mods-available/opcache.ini
lrwxrwxrwx 1 root root 35 лют  1 17:19 15-xml.ini -> /etc/php/7.1/mods-available/xml.ini
lrwxrwxrwx 1 root root 36 лют  1 17:18 20-curl.ini -> /etc/php/7.1/mods-available/curl.ini
lrwxrwxrwx 1 root root 35 лют  1 17:19 20-dom.ini -> /etc/php/7.1/mods-available/dom.ini
lrwxrwxrwx 1 root root 34 лют  1 17:18 20-gd.ini -> /etc/php/7.1/mods-available/gd.ini
lrwxrwxrwx 1 root root 36 лют  1 17:18 20-imap.ini -> /etc/php/7.1/mods-available/imap.ini
lrwxrwxrwx 1 root root 36 лют  1 17:18 20-intl.ini -> /etc/php/7.1/mods-available/intl.ini
lrwxrwxrwx 1 root root 36 лют  1 17:18 20-json.ini -> /etc/php/7.1/mods-available/json.ini
lrwxrwxrwx 1 root root 40 лют  1 17:18 20-mbstring.ini -> /etc/php/7.1/mods-available/mbstring.ini
lrwxrwxrwx 1 root root 38 лют  1 17:18 20-mcrypt.ini -> /etc/php/7.1/mods-available/mcrypt.ini
lrwxrwxrwx 1 root root 38 лют  1 17:30 20-mysqli.ini -> /etc/php/7.1/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 41 лют  1 17:30 20-pdo_mysql.ini -> /etc/php/7.1/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 38 лют  1 17:19 20-pspell.ini -> /etc/php/7.1/mods-available/pspell.ini
lrwxrwxrwx 1 root root 40 лют  1 17:18 20-readline.ini -> /etc/php/7.1/mods-available/readline.ini
lrwxrwxrwx 1 root root 41 лют  1 17:19 20-simplexml.ini -> /etc/php/7.1/mods-available/simplexml.ini
lrwxrwxrwx 1 root root 36 лют  1 17:19 20-wddx.ini -> /etc/php/7.1/mods-available/wddx.ini
lrwxrwxrwx 1 root root 41 лют  1 17:19 20-xmlreader.ini -> /etc/php/7.1/mods-available/xmlreader.ini
lrwxrwxrwx 1 root root 41 лют  1 17:19 20-xmlwriter.ini -> /etc/php/7.1/mods-available/xmlwriter.ini
lrwxrwxrwx 1 root root 35 лют  1 17:19 20-xsl.ini -> /etc/php/7.1/mods-available/xsl.ini
lrwxrwxrwx 1 root root 35 лют  1 17:19 20-zip.ini -> /etc/php/7.1/mods-available/zip.ini
```

lrwxrwxrwx - seems this rights shown cause there symlinks in folder. Also pdo_mysql loading with 20 priority and it is same priority as 7.0. But 7.0 works well with it.

**Comment by TamiasSibiricus** [comment]
I have changed manually priority to 10 and 30 and there no changes. Loading error still exists. I'll try today to setup from sury repo on debian jessie 64bit at my virtal pc and write here what is happened.

**Comment by oerdnj** [comment]
It seems to me that something has disabled pdo module. Could you try enabling it?

**Comment by TamiasSibiricus** [comment]
My colleague try to reproduce setup on vanilla system but without installing 7.0 at first. PDO module loads well and seems working(we do not have enough time to run php script with pdo usage). So i think it is conflict between 7.0 and 7.1 somewhere. We try to reproduce it at next monday with 7.0 installed at first and then try to install 7.1. Please do not close issue.

**Comment by oerdnj** [comment]
Any luck reproducing the issue?

**Comment by TamiasSibiricus** [comment]
Ok. After second test we can't reproduce error on vanilla system. 
Also we remove packages with purge option and it solve issue.
Seems you can close issue. Thanks for help.
