### ISSUE TITLE
PHP 5.4.42 (Security-)Update for Ubuntu 12.04

### ISSUE THREAD

**Issue by cpupower** [oerdnj/deb.sury.org#81]
PHP 5.4.42 fixes six security-related issues.

Fix was released on 11 Jun 2015.

http://php.net/archive/2015.php#id2015-06-11-4
http://www.php.net/ChangeLog-5.php#5.4.42

Also other versions are affected:
5.6.10
http://php.net/ChangeLog-5.php#5.6.10

5.5.26
http://php.net/ChangeLog-5.php#5.5.26

**Comment by oerdnj** [comment]
Uploaded
