### ISSUE TITLE
How to check for differences in config files (e.g. logrotate.d)

### ISSUE THREAD

**Issue by hrvoj3e** [oerdnj/deb.sury.org#811]
How to check for changes in config files and should I check this manually when updating `nginx` trough your PPA via `apt` ?
I expected that the apt upgrade procedure will ask to diff the files or something like when the are changes in `php.ini`.

older postrotate

    postrotate
        invoke-rc.d nginx rotate >/dev/null 2>&1
    endscript
vs newer postrotate

    postrotate
        PID=$(awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") { print $2; exit; } }' /etc/nginx/nginx.c$
        start-stop-daemon --stop --signal USR1 --quiet --pidfile ${PID:-/run/nginx.pid} --name nginx
    endscript

For example logrotate.d :
https://github.com/oerdnj/nginx/blob/0e58e5688aff37de21a055b1baaee79505f59c62/debian/nginx-common.nginx.logrotate

**Comment by oerdnj** [comment]
No, it will only ask if you have changed the conffile yourself. Otherwise it won't ask for changes. So sorry, no, there's no standard way to check this.
