### ISSUE TITLE
Half modules 7.2 half modules 7.1?

### ISSUE THREAD

**Issue by ipkpjersi** [oerdnj/deb.sury.org#813]
The other day, I was attempting to upgrade to PHP 7.1 or PHP 7.2 using this PPA on Ubuntu 16.04. However, when I do this, I have problems. Basically, the issue is, half of the modules seem to be only for 7.1 and the other half seem to be for 7.2 so it creates a weird hybrid install it seems. I need a bunch of modules to get Laravel 5.6 working I think, and I am pretty sure they all need to be the same PHP version. I can't remember which modules are for which version of PHP right now but I guess I could check later if necessary. If you'd like an idea of which modules I try to install on for PHP 7.2, here is basically what I try to install: https://pastebin.com/gBeax0qx in order to get Laravel 5.6 working. Please let me know if any of you have any ideas or suggestions for this.

**Comment by oerdnj** [comment]
That's simply not true. Debug it a little bit more and then come back with evidence.

**Comment by ipkpjersi** [comment]
It was true a few days ago but it seems that it has been resolved now as I tried again just now and I was unable to replicate it. Thanks.
