### ISSUE TITLE
libzmq needs transition for new libsodium

### ISSUE THREAD

**Issue by kevinwinahradsky** [oerdnj/deb.sury.org#814]
I am trying to install php5.6 with zmq on a trusty image but I am getting some errors. It looks like libzmq5 depends on libsodium18 but it appears that this package is no longer available in this ppa.

```
$ sudo apt-get install php5.6-cli php-zmq libzmq5
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libzmq5 : Depends: libsodium18 (>= 0.6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
```
$ apt-cache policy php5.6-cli php-zmq libzmq5 libsodium18
php5.6-cli:
  Installed: (none)
  Candidate: 5.6.33-3+ubuntu14.04.1+deb.sury.org+1
  Version table:
     5.6.33-3+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
php-zmq:
  Installed: (none)
  Candidate: 1.1.3-6+ubuntu14.04.1+deb.sury.org+2
  Version table:
     1.1.3-6+ubuntu14.04.1+deb.sury.org+2 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
libzmq5:
  Installed: (none)
  Candidate: 4.2.2-1+ubuntu14.04.1+deb.sury.org+1
  Version table:
     4.2.2-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
libsodium18:
  Installed: (none)
  Candidate: (none)
  Version table:
```

Thanks.

**Comment by oerdnj** [comment]
Uploaded and it's almost finished, so closing.

**Comment by franbenz** [comment]
Hi @oerdnj, how was this solved? I'm having a similar issue while installing libzmq5 on a Debian GNU/Linux 10 docker image.
I'm finding a libsodium23 package available, but libzmq5 depends on libsodium18 just as your message above.
Thanks!

**Comment by KronosTheLate** [comment]
I am also experiencing this issue, after having mucked about trying to install [zmqpp](https://github.com/zeromq/zmqpp), which reccomends installing libsodium, for which I followed [these](https://doc.libsodium.org/installation) instructions. However, after installing libsodium and zmqpp this way, I was getting a warning about `libzmq5` having unmet dependencies whenever I did `apt`-operations. To resolve it, I removed `libzmq5` (because I had decided my application did not require ZeroMQ after all). Turns out, a lot of packaages including my file explorer dolhpin depend on libzmq5, and were removed:
<details><summary>List of removed packages:</summary>

```
dolphin dragonplayer ffmpegthumbs gimp goldendict gstreamer1.0-libav gwenview juk kde-baseapps
kde-plasma-desktop kde-standard kdeaccessibility kdepim-addons khelpcenter kinfocenter kio-extras
kmail kmousetool konq-plugins konqueror libavdevice59 libavfilter8 libavformat59 libgegl-0.4-0
libgimp2.0 libkf5baloowidgets-bin libkf5baloowidgets5 libkf5filemetadata-bin libkf5khtml-bin
libkf5khtml5 libkf5mailcommon5abi2 libkpimimportwizard5 libkpipewirerecord5 libobs0 libokular5core10
libzmq5 mbox-importer obs-plugins obs-studio okular phonon4qt5 phonon4qt5-backend-vlc pim-data-exporter
plasma-desktop plasma-widgets-addons plasma-workspace plasma-workspace-wayland
qml-module-org-kde-pipewire sddm-theme-breeze sddm-theme-debian-breeze task-kde-desktop vlc vlc-plugin-base
```
</details>

Unfortunately I pressed okay before thinking, and so I am left with all this uninstalled. When I try to install dolphin now, I get the following:
<details><summary>Trying to install dolphin, then the problematic dependency:</summary>

```
(base) dennis@dennismakinPC:~$ sudo apt install dolphin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libkf5filemetadata-bin : Depends: libavformat59 (>= 7:5.0)
E: Unable to correct problems, you have held broken packages.
(base) dennis@dennismakinPC:~$ sudo apt install libavformat59
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libzmq5 : Depends: libsodium18 (>= 1.0.3) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
</details>

So libzmq5 and libsodium are still a pain in my a**. I am at my wits end regarding how to resolve this. I am not sure if this is an appropritate place to post about this issue, but it is the closes thing I could find.

**Comment by KronosTheLate** [comment]
I was able to fix the issue. When I do `apt show libzmq5`, I can find the dependencies in the line starting with `Depends:`. `libsodium18` is listed there, as expected. However, I get told by apt that `N: There is 1 additional record. Please use the '-a' switch to see it`. When I do `apt show libzmq5 -a`, I get two versions of `libzmq5` from different sources. 

The first one is the problematic one. It is version `4.3.5-0`, and lists `zeromq` as the "Source". This is the version with `libsodium18` as a dependency, and can therefore not be installed.

Below, I can see another version: `4.3.4-6`, with `zeromq3` as the "Source". This version has `libsodium23` as a dependency, which is readily available via `apt`. So for me, the fix ended up being to run `sudo apt install libzmq5=4.3.4-6`, as I knew that this version had a dependency I could also install.

I added this explanation in case someone else founds this post from googling the issue, like me. Sorry for the noise on a year-old solved issue ^_^
