### ISSUE TITLE
PPA for PHP 5.6 doesn't allow to install Steam on Ubuntu 15.04 x64

### ISSUE THREAD

**Issue by Cysioland** [oerdnj/deb.sury.org#82]
Steam requires following packages:
* libgl1-mesa-dri:i386
* libgl1-mesa-glx:i386

But when I try to install them, following happens:

```
The following packages have unmet dependencies:
 libedit2 : Breaks: libedit2:i386 (!= 3.1-20140620-2+deb.sury.org~trusty+4) but 3.1-20140620-2 is to be installed.
 libedit2:i386 : Breaks: libedit2 (!= 3.1-20140620-2) but 3.1-20140620-2+deb.sury.org~trusty+4 is installed.
```

**Comment by oerdnj** [comment]
Well, don't mix work & play and you should be fine. The libedit2 update is needed for readline extension to work. Sorry.
