### ISSUE TITLE
install memcahced on ubuntu 12

### ISSUE THREAD

**Issue by hsahrij** [oerdnj/deb.sury.org#822]
Hey I've tried the following:
`sudo apt-get install php5-memcached`
I'm getting the following errors
`Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ precise/main libmemcached11 amd64 1.0.18-3+deb.sury.org~precise+2
  403  Forbidden
Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ precise/main php5-memcached amd64 2.2.0-2+deb.sury.org~precise+1
  403  Forbidden
Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/libm/libmemcached/libmemcached11_1.0.18-3+deb.sury.org~precise+2_amd64.deb  403  Forbidden
Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/php-memcached/php5-memcached_2.2.0-2+deb.sury.org~precise+1_amd64.deb  403  Forbidden
`

I've made some research I'm getting that ondrej/php5-5.6 package has been deleted is it right or there is sth I couldn't understand

**Comment by oerdnj** [comment]
Precise is EOL.
