### ISSUE TITLE
libargon2.so.0: no such file or directory (PHP 7.2)

### ISSUE THREAD

**Issue by rask** [oerdnj/deb.sury.org#824]
I've installed PHP 7.2 via this PPA. Today after running `apt-get update` I received some update to libargon2. Now when I run

    php7.2 --version

or any other command for that matter I only receive the following error:

    php7.2: error while loading shared libraries: libargon2.so.0: cannot open shared object: No such file or directory

This happened on two separate Ubuntu 14.04 systems today, but use the same PPA. Yesterday PHP7.2 worked fine on both systems. Is this related to 14.04 or the packaged PPA version?

`ldd /usr/bin/php7.2` output:

	linux-vdso.so.1 =>  (0x00007fffc29d1000)
	libargon2.so.0 => not found
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f3ec5d20000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3ec5b07000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f3ec5898000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3ec5592000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3ec538e000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f3ec5028000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f3ec4dbe000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f3ec4948000)
	libsodium.so.23 => /usr/lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f3ec46f7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3ec432e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3ec4110000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3ec65e3000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f3ec3eee000)

**Comment by rask** [comment]
Hmm, I wonder if this issue comes from incompatibilities between this PPA and KeepassXC PPA:

(`sudo apt-cache policy libargin2-0`):

```
libargon2-0:
  Installed: 20171227-0ppa1~trusty6
  Candidate: 20171227-0ppa1~trusty6
  Version table:
 *** 20171227-0ppa1~trusty6 0
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0~20161029-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
```

**Comment by rask** [comment]
Yes. After reinstalling the version from this PPA `php7.2 --version` works as expected. I wonder if this breaks how KeepassXC works.

**Comment by rask** [comment]
KeepassXC PPA fellow said they reinstanted the missing library file, will have to see how this works now. https://github.com/keepassxreboot/keepassxc-packaging/issues/8#issuecomment-369059588

**Comment by rask** [comment]
Yes, now I have the KeepassXC version of the library and PHP7.2 works normally now.

**Comment by Psalms23** [comment]
having same error. how did you fixed it? Sorry newbie

**Comment by rask** [comment]
@Psalms23 my issue was related to KeepassXC upstream PPA having an invalid package. Do you have KeepassXC installed?
