### ISSUE TITLE
[Update] php-mongodb to 1.4.1

### ISSUE THREAD

**Issue by moderndeveloperllc** [oerdnj/deb.sury.org#825]
@oerdnj [PECL extension](http://pecl.php.net/package/mongodb) has been updated to 1.4.1. This new release add support for client sessions, array filters for `update` commands, and it can now compile different SSL libraries (OpenSSL, LibreSSL), wire compression, etc. Drops support for MongoDB 2.4 and earlier.

**Comment by oerdnj** [comment]
I uploaded 1.4.2 just today.

**Comment by drsect0r** [comment]
Is the package available? I can't find the package.

**Comment by oerdnj** [comment]
https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=mongodb&field.status_filter=published&field.series_filter=

**Comment by drsect0r** [comment]
Will it be released on packages.sury.org or should I create a separate issue for that?

**Comment by oerdnj** [comment]
Oh, sure. I'll fired a build there. You just need to be explicit where you can't find the packages next time...

**Comment by drsect0r** [comment]
Thank you! I was unaware that this repository was also used for an Ubuntu PPA. Can you verify if the build on Debian was successfully executed? I've got an update off the MongoDB extension but it's still version 1.3.3.

**Comment by oerdnj** [comment]
Right, I forgot to push the repo before triggering the build.

I confirmed it had picked 1.4.2 now: https://howl.labs.nic.cz/jenkins/view/PHP-source/job/php_php-mongodb-binaries/6/
