### ISSUE TITLE
PHP 7.2.3 for Debian

### ISSUE THREAD

**Issue by BandonRandon** [oerdnj/deb.sury.org#827]
Thanks for all your work on making modern versions of PHP easy to install on Debian! I've always been impressed with how fast the latest versions are available. Sometimes even before php.net updates the release notes. 

PHP 7.2.3 was [officially released](https://secure.php.net/ChangeLog-7.php#7.2.3) March 1st with some security fixes. I'm wondering if you have an ETA for these packages to be added to the sury repo. 

Thanks again for all your work!

**Comment by oerdnj** [comment]
Done.
