### ISSUE TITLE
[Feature] php-vips

### ISSUE THREAD

**Issue by andrews05** [oerdnj/deb.sury.org#830]
Hi, thanks heaps for maintaining all this stuff, really appreciate it. Just wondering if you could add [php-vips](https://pecl.php.net/package/vips)? [Libvips](https://jcupitt.github.io/libvips/) is an alternative image processing library which I'm trying use to replace imagemagick.

**Comment by andrews05** [comment]
@pbowyer The php-vips extension works with libvips as far back as v8.2, as available in Ubuntu 16.04. So maintaining another ppa for libvips isn't strictly necessary.
(That said, having libvips prebuilt with mozjpeg would be nice. Mozjpeg deb packages can be found [here](https://mozjpeg.codelove.de/binaries.html).)

**Comment by pbowyer** [comment]
@andrews05 While it does, libvips develops fast and Ubuntu's builds are missing a lot of the useful, newer features such as face detection for smart cropping. Being able to use those without building from scratch (which I find surprisingly painful compared with other software) would be _awesome_ 😄

**Comment by oerdnj** [comment]
Done, but I am not going to update `libvips` as it's a maze of dependencies and updating one forces to backport more packages.

**Comment by pbowyer** [comment]
Thank you @oerdnj. I understand about `libvips`, I tried it myself and failed.

**Comment by andrews05** [comment]
Thank you!
Don't suppose this is using mozjpeg?
Btw, if it's the pdf support that is causing dependency hell, I'd be quite happy if that was omitted.
