### ISSUE TITLE
ext-mongo vs. ext-mongodb in php5.6 - bionic

### ISSUE THREAD

**Issue by duschata** [oerdnj/deb.sury.org#834]
Hello All,
I've problems to run the mongodb driver with php5.6 in Ubuntu Bionic. Composer asks for ext-mongo support during the installation and the needed dependencies are not solved. I 've read, that ext-mongodb has legacy support but how can I force to use  ext-mongodb instead of ext-mongo?
Thanks in advance,

Tom

**Comment by oerdnj** [comment]
I uploaded php-mongo to bionic. Although I strongly thing that requiring obsolete version of the extension is a bug in the software you are using.
