### ISSUE TITLE
Apache 2.4.33

### ISSUE THREAD

**Issue by Ayesh** [oerdnj/deb.sury.org#835]
Hello,
There are few Apache2 releases, but the repo only contains 2.4.29. I'd be quite grateful if we could get the recent versions. 

Thank you.

**Comment by oerdnj** [comment]
Uploaded.

**Comment by Ayesh** [comment]
Thank you so much! Apache 2.4.33 has a new module, [`mod_md`](https://github.com/apache/httpd/tree/2.4.33/modules/md). Do you think it will be possible to have this module in releases well? It's marked experimental but they backported it from 2.5 branch (which I believe is a signal this module is somewhat stable at this point).
