### ISSUE TITLE
Install error of php7.1-curl in Ubuntu 18.04 (Bionic Beaver)

### ISSUE THREAD

**Issue by ahrasis** [oerdnj/deb.sury.org#836]
> The following packages have unmet dependencies:
 php7.1-curl : Depends: libcurl3 (>= 7.44.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by oerdnj** [comment]
Version of `php7.1-curl` you are trying to install?

**Comment by ahrasis** [comment]
As stated, Ubuntu 18.04 (Bionic Beaver) version.

**Comment by oerdnj** [comment]
Let me ask you once again:

What is the exact version of php7.1-curl you are trying to install?

**Comment by ahrasis** [comment]
May be 7.1.15-1+ubuntu18.04.1+deb.sury.org+2 but I don't know for sure since all I know that I am installing multiple php using your ppa in Ubuntu 18.04 (Bionic Bever) via this command:

>  apt -y install php-apcu php-apcu-bc php-common php-gettext php-imagick php-memcache php-pear php-php-gettext php-xml php5.6 php5.6-cgi php5.6-cli php5.6-common php5.6-curl php5.6-fpm php5.6-gd php5.6-imap php5.6-intl php5.6-json php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-pspell php5.6-readline php5.6-recode php5.6-sqlite3 php5.6-tidy php5.6-xml php5.6-xmlrpc php5.6-xsl php5.6-zip php7.0 php7.0-cgi php7.0-cli php7.0-common php7.0-curl php7.0-fpm php7.0-gd php7.0-imap php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-pspell php7.0-readline php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xml php7.0-xmlrpc php7.0-xsl php7.0-zip php7.1 php7.1-cgi php7.1-cli php7.1-common php7.1-curl php7.1-fpm php7.1-gd php7.1-imap php7.1-intl php7.1-json php7.1-mbstring php7.1-mcrypt php7.1-mysql php7.1-opcache php7.1-pspell php7.1-readline php7.1-recode php7.1-sqlite3 php7.1-tidy php7.1-xml php7.1-xmlrpc php7.1-xsl php7.1-zip php7.2 php7.2-cgi php7.2-cli php7.2-common php7.2-curl php7.2-fpm php7.2-gd php7.2-imap php7.2-intl php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-pspell php7.2-readline php7.2-recode php7.2-sqlite3 php7.2-tidy php7.2-xml php7.2-xmlrpc php7.2-xsl php7.2-zip

I can install the above fine without php7.1-curl so I thought I report this issue to help.

I know that Ubuntu 18.04 (Bionic Beaver) is still beta so it is ok.

**Comment by oerdnj** [comment]
Ok, I see. Wait a until `7.1.15-1+ubuntu18.04.1+deb.sury.org+2+libcurl4` is built and then try again (usually it takes about an hour).
