### ISSUE TITLE
Segfault with openssl_sign

### ISSUE THREAD

**Issue by Vinorcola** [oerdnj/deb.sury.org#838]
Hello,

I encounter some segmentation fault when using OpenSSL, especially the `openssl_sign` method. The issue occures rather than I use php 7.1 or 7.2 from your package.

Apache2 log me with this line:

```
[core:notice] [pid 19477] AH00051: child pid 20028 exit signal Segmentation fault (11), possible coredump in /tmp/apachecoredump
```

I've created a simple code to reproduce:

```php
<?php

// Key generated with command:
// $ openssl genrsa -out key.pem 2048 && openssl rsa -in key.pem -outform PEM -pubout -out public.pem
$publicKey = openssl_pkey_get_public('file://../security/public.pem');
$privateKey = openssl_pkey_get_private('file://../security/key.pem');

// Encrypt
openssl_public_encrypt('message', $encryptedData, $publicKey);
$encryptedData = base64_encode($encryptedData);

// Sign
openssl_sign($encryptedData, $signature, $privateKey);
$signature = base64_encode($signature);

?>
<html>
        <body>
                <h3>Encrypted message</h3>
                <code><?= $encryptedData ?></code>

                <h3>Signature</h3>
                <code><?= $signature ?></code>
        </body>
</html>
```

The error comes from the `openssl_sign` call, because if I comment that line, no more errors occure.

Note the error is not occuring every time. When the error appears, the page may be completely loaded at that time (the signature is displayed correctly), so I guess the error occures when the script is cleaning something. However, in a more complex script, the process crash before retruning any response...

I'm running the script on an Ubuntu Xenial (16.04.4) machine.

Thanks for your help.

**Comment by oerdnj** [comment]
This is not exactly packaging related. You'll need to report this to upstream PHP bug tracker located at:  https://bugs.php.net and generate a backtrace: https://bugs.php.net/bugs-generating-backtrace.php
