### ISSUE TITLE
php5-json is missing updates from PHP 5.6.10 (1.3.6-1+deb.sury.org~trusty+2)

### ISSUE THREAD

**Issue by bskart** [oerdnj/deb.sury.org#84]
In php 5.6.6 (2015-02-19) a new constant and behaviour for json_encode was introduced (JSON_PRESERVE_ZERO_FRACTION) it is missing in the current version of the php5-json-package and there seems to be no newer version of the package.

To reproduce run:

```php
<?php

var_dump(json_encode(['baa' => 1,'foo' => 1.0],JSON_PRESERVE_ZERO_FRACTION));
var_dump(JSON_PRESERVE_ZERO_FRACTION);
```
Expected output:

```
string(19) "{"baa":1,"foo":1.0}"
int(1024)
```

Actual output:

```
PHP Notice:  Use of undefined constant JSON_PRESERVE_ZERO_FRACTION - assumed 'JSON_PRESERVE_ZERO_FRACTION' in /.../test.php on line 3
PHP Warning:  json_encode() expects parameter 2 to be long, string given in /.../test.php on line 3
NULL
PHP Notice:  Use of undefined constant JSON_PRESERVE_ZERO_FRACTION - assumed 'JSON_PRESERVE_ZERO_FRACTION' in /.../test.php on line 4
string(27) "JSON_PRESERVE_ZERO_FRACTION"
```
It seems php5-json needs to be rebuild in a newer version.

One thing which was very confusing for me, that according to phpinfo, the version of the php-json-extension is the same as your package-version (1.3.6) while the actual version of the json-extension in PHP is only 1.2.1. I would have expected in phpinfo to get the version of the extension or something like: 1.2.1-1.3.6-1+deb.sury.org~trusty+2, if you want to include the package versioning number, but not the "package-version" if it differs from the actual extensions version.

**Comment by oerdnj** [comment]
php5-json was updated to 1.3.7 that includes JSON_PRESERVE_ZERO_FRACTION fix. Thanks for the poke.
As for the version - that's probably some bug in phpinfo() - could you perhaps open a separate wishlist bug? I will look at it eventually when I have nothing else to do.

**Comment by bskart** [comment]
Wow from bugreport to new release in < 30min :) That's fast.

Thanks a lot.

**Comment by oerdnj** [comment]
Sometimes it's > 30 days :). Depends on what my current workload is and how hard the problem is to solve...  You're welcome.

**Comment by Modelizer** [comment]
I'm facing this issue on EC2 instance. PHP version is 5.6 and json is 1.3.6 but when I run `sudo yum install php-json` to update json I get `Package php56-jsonc-1.3.6-1.19.amzn1.x86_64 already installed and latest version` Also, Right now we are not in favor to upgrade PHP version.

Please help.. Thanks.

**Comment by oerdnj** [comment]
@Modelizer You are at the wrong place, this is issue tracker for ppa:ondrej/php for Ubuntu and Debian. Don't fill random comments just because the link popped at the first place in the Google search.

**Comment by Modelizer** [comment]
My bad... After commenting I notice you only support for Ubuntu and Debian but the issue is similar what I'm facing on redhat version. Anyways thanks.
