### ISSUE TITLE
Trusty - php7.0-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable

### ISSUE THREAD

**Issue by lobsterdore** [oerdnj/deb.sury.org#840]
Hello,

Within the last hour or so this error has started occurring on the ondrej/php ppa when installing PHP 7.0 on Trusty 64 (and possibly other platforms), this seems to be due to a requirement on libssl1.1, only version 0.9.8 is available however.

Error output is:

```
apt-get install php7.0-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Thanks

**Comment by ralphschindler** [comment]
```The following packages have unmet dependencies:
 php7.2-cli : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.2-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.2-fpm : Depends: libssl1.1 (>= 1.1.0) but it is not installable```

**Comment by allanxp4** [comment]
Also with php7.2 on Ubuntu/WSL.

**Comment by matthbull** [comment]
same on Ubuntu 16.04 with php 7.2

**Comment by acejam** [comment]
I'm also seeing similar errors with other PHP packages using this PPA:

> The following packages have unmet dependencies:
 php7.1-bcmath : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-fpm : Depends: php7.1-cli but it is not going to be installed
              Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
              Depends: php7.1-json but it is not going to be installed
              Depends: php7.1-opcache but it is not going to be installed
              Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.1-gd : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-ldap : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-mbstring : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-mysql : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-xml : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
 php7.1-zip : Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed

**Comment by dark2y** [comment]
Confirm this is happening on Ubuntu 16.04 with php-7.1

>  php7.1-fpm : Depends: php7.1-cli but it is not going to be installed
              Depends: php7.1-common (= 7.1.15-1+ubuntu16.04.1+deb.sury.org+2) but it is not going to be installed
              Depends: php7.1-json but it is not going to be installed
              Depends: php7.1-opcache but it is not going to be installed
              Depends: libssl1.1 (>= 1.1.0) but it is not installable

**Comment by oerdnj** [comment]
There was an upstream bug in `c_rehash` and I had to remove the libraries to fix it for a moment. Updated versions are building right now.

**Comment by kwn** [comment]
Thanks @oerdnj !

**Comment by lobsterdore** [comment]
@oerdnj looking good now, thanks very much for the quick response.
