### ISSUE TITLE
Broken apache2 mod_proxy_uwsgi with latest apache2-bin

### ISSUE THREAD

**Issue by Shadowghost** [oerdnj/deb.sury.org#841]
I used your apache2.x PPA on Ubuntu 16.04 and with the last update of the apache2-bin package  it seems like __mod_proxy_uwsgi__ is broken.
I was not aware that this module is shipped with your builds, since up until now I needed to install __libapache2-mod-proxy-uwsgi__ to get it.
With the last update I got a conflict: The updated apache2-bin wanted to replace __/usr/lib/apache2/modules/mod_proxy_uwsgi.so__, so I purged the proxy-package and reinstalled apache2-bin. No conflicts were found, but the proxy_uwsgi module couldn't be loaded since the module definition __/etc/apache2/mods-available/proxy_uwsgi.load__ was missing.

Besides that, when installing __libapache2-mod-proxy-uwsgi__ with apt, it additionally installs the packages __libjansson4, libmatheval1, uwsgi-core__ which aren't installed with your package.

Not sure if it's just a mistake in building the package (the build log suggest that: the module is built, but the definition is not included in the distributed files) or if I did something wrong, would be nice if someone can elaborate.

**Comment by oerdnj** [comment]
Thanks for the report, it looks like something that needs to be fixed.

**Comment by oerdnj** [comment]
This is now tracked as: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894785

And similar issue with mod_md: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894760 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894761

**Comment by Shadowghost** [comment]
@oerdnj  I'd like to close this issue, since upstream fixed it, but it doesn't seem to be fixed on your latest packages for 16.04.
When running `dpkg-query -L apache2-bin | grep uwsgi` I still get `/usr/lib/apache2/modules/mod_proxy_uwsgi.so` as installed by this package, which prevents `libapache2-mod-proxy-uwsgi`to be installed.

**Comment by steffann** [comment]
There is still a conflict. `apache2-bin` provides `/usr/lib/apache2/modules/mod_proxy_uwsgi.so` but no `/etc/apache2/mods-available/proxy_uwsgi.load`. I think either both or none should be provided.

**Comment by Shadowghost** [comment]
As previously said it's wrong to provide the mod with the package, it shouldn't be included. They fixed it upstream (take a look at the bugreport linked earlier).

**Comment by Shadowghost** [comment]
`/usr/lib/apache2/modules/mod_proxy_uwsgi.so` is still present in `apache2-bin` but with the new packages from yesterday (?) it's possible to install and load `libapahce2-mod-uwsgi` without any problems, so I'm closing this issue.
