### ISSUE TITLE
some mods not enabled for supported php versions in 18.04

### ISSUE THREAD

**Issue by heldchen** [oerdnj/deb.sury.org#842]
I found some mods that would not install/activate for php 7.0, 7.1 and/or 7.2 in 18.04. in 17.10, all those packages installed ok for all supported php versions.

**php-imagick:**
- `3.4.3~rc2-2ubuntu4`
- only enabled for 7.2

**php-igbinary**
- `2.0.5-1+ubuntu18.04.1+deb.sury.org+1`
- only enabled for 7.**1**

**php-memcached:**
- `3.0.1+2.2.0-1build2`
- only enabled for 7.2
- fails to load in 7.2 due to missing php-igbinary

**php-redis:**
- `3.1.6-1build1`
- only enabled for 7.2
- fails to load in 7.2 due to missing php-igbinary

**php-msgpack:** 
- `2.0.2+0.5.7-2build1`
- only enabled for 7.2

**Comment by oerdnj** [comment]
Yes, you are listing Ubuntu versions (most of them) as:
* 30th November: Feature Definition Freeze
* 4th January: Alpha 1 release
* 1st February: Alpha 2 release
* 1st March: Feature Freeze
* 8th March: First beta release
* 5th April: Final beta release
* 19th April: Final Freeze
* ***26th April: Stable Ubuntu 18.04 LTS release***

**Comment by oerdnj** [comment]
JFTR As final beta has been released, I have also batch updated all the supported extensions.
