### ISSUE TITLE
installation error of mcrypt for php7.2

### ISSUE THREAD

**Issue by hasan** [oerdnj/deb.sury.org#843]
Hello,

I try to install mcrypt for php7.2 on ubuntu 16.04 LTS, but i couldn't find pacckage on repository. I get error which is below

```
root@ubuntu:/# apt install php7.2-mcrypt
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.2-mcrypt
E: Couldn't find any package by glob 'php7.2-mcrypt'
E: Couldn't find any package by regex 'php7.2-mcrypt'
```

How can i install mcrypt for php7.2?

**Comment by oerdnj** [comment]
You can’t. Read the PHP documentation.

**Comment by hasan** [comment]
Thanks, for the information. I hadn't read version changelog. It's had been moved from core to pecl.
