### ISSUE TITLE
Debian 9.4: php7.2-curl installation error

### ISSUE THREAD

**Issue by ademchenko** [oerdnj/deb.sury.org#844]
Getting the following error while installing php7.2-curl on Debian 9.4:
```
The following packages have unmet dependencies:
 php7.2-curl : Depends: libcurl4 (>= 7.44.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

Could you help with that issue?

**Comment by ademchenko** [comment]
It's strange but if I run 'php -v' command it return the following text: 

> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.3-1+ubuntu18.04.1+deb.sury.org+1+libcurl4, Copyright (c) 1999-2018, by Zend Technologies

So, it's written that php installation include libcurl4.

**Comment by todeveni** [comment]
You've installed Ubuntu packages to Debian?

> with Zend OPcache v7.2.3-1+**ubuntu18.04.1**+deb.sury.org+1+libcurl4

**Comment by oerdnj** [comment]
^^^

**Comment by ademchenko** [comment]
Thank you, todeveni and oerdnj, probably that's the case.
