### ISSUE TITLE
PHP5.6-imagick on Debian Stretch?

### ISSUE THREAD

**Issue by Af0x** [oerdnj/deb.sury.org#848]
hello,
how to get php5.6-imagick on Debian Stretch?
Thanks in advance,
Af0x

**Comment by oerdnj** [comment]
I don’t know, what did you try and what didn’t work?

**Comment by Af0x** [comment]
i coinstalled your repo with a lower Priority (100) so that the "original" PHP-packages stay in place. After I tried to install php-imagick it only installed in the folder of PHP7.0 (original).

**Comment by Af0x** [comment]
I now want to try it with a higher priority (1000) limiting it to php* and libphp* packages as the openssl version of your repo is lower than the original. Is there a reason you provide separate openssl-packages?
Best regards and thank you for this repo - it saves many lives i guess :D

**Comment by oerdnj** [comment]
So, there’s no actual bug..
