### ISSUE TITLE
Show the right version of json extension in phpinfo()

### ISSUE THREAD

**Issue by bskart** [oerdnj/deb.sury.org#85]
The phpinfo shows the version of the .deb-package instead of the json-extension.

Not critical.

https://github.com/oerdnj/deb.sury.org/issues/84#event-350814723
> As for the version - that's probably some bug in phpinfo() - could you perhaps open a separate wishlist > bug? I will look at it eventually when I have nothing else to do.

**Comment by oerdnj** [comment]
PHP 7.0 has the json extension from main sources again. Not worth fixing for anything older.
