### ISSUE TITLE
Ubuntu package v7.2.4-1+ubuntu16.04.1+deb.sury.org+1

### ISSUE THREAD

**Issue by h4kuna** [oerdnj/deb.sury.org#851]
Yeatarday, i update php  from 7.2.3 to 7.2.4 where is incompatible redis extension. In php7.2.3 is redis version 3.6.1 and php7.2.4 is redis version 4.0.0. 

In package for debian php7.2.4 is redis 3.6.1 for debian whose is on production server.

If is possible i downgrade to php to 7.2.3. Could you upload older packages?

**Comment by oerdnj** [comment]
redis 4.0.0 is the latest stable upstream version: http://pecl.php.net/package/redis

So, no, I am not going to upload older versions. This repository specifically tracks latest upstream versions.

**Comment by rostenkowski** [comment]
hi oerdnj :) 

can u please estimate the time in which the 4.0 version reaches the Debian channel at https://packages.sury.org/php/ ?
