### ISSUE TITLE
php curl ssl version?

### ISSUE THREAD

**Issue by friizer** [oerdnj/deb.sury.org#853]
Why is there a difference of libssl version used by main binary and curl extension?

ldd /usr/bin/php7.0 | grep ssl
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2c22fd6000)

ldd /usr/lib/php/20151012/curl.so | grep ssl
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f554603b000)

**Comment by oerdnj** [comment]
Because that’s what the distribution you have is using for curl. The switch to OpenSSL 1.1 for curl has been done only very recently.
