### ISSUE TITLE
warning message in php 5.6 for missing php_openssl.dll and php_soap.dll

### ISSUE THREAD

**Issue by ravindrabhat6** [oerdnj/deb.sury.org#854]
Hi There,
Not sure why i am getting the below warning. any help would be highly appreciated.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/php_openssl.dll' - /usr/lib/php/20131226/php_openssl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/php_soap.dll' - /usr/lib/php/20131226/php_soap.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.32-1+ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by ravindrabhat6** [comment]
i am getting this warning message for ubuntu 16.04.2 server .

**Comment by oerdnj** [comment]
Then don’t cut & paste random configuration snippets from the Internet into your server configuration.
