### ISSUE TITLE
I cannot install the PPA

### ISSUE THREAD

**Issue by jsuarezik** [oerdnj/deb.sury.org#855]
Hello guys, how are you doing today? I'm a little bit newbie to Ubuntu. I was trying to upgrade my php version, to 7.1 or 7.2, i followed the multiple tutorials, everyone says the same

add the ppa with this:
`add-apt-repository ppa:ondrej/php` apparently it worked
Then i update, but when i run
`apt-get install php7.2` I don't get any packages

What can i do?

**Comment by oerdnj** [comment]
The best course of action would be to ask at [Ubuntu Forums](https://ubuntuforums.org) or search [Ask Ubuntu](https://askubuntu.com).

I am sorry, but this is not a user support forum.
