### ISSUE TITLE
openssl 1.1.0h-2+ubuntu18.04.1+deb.sury.org+2 breaks ca-certificates install if duplicate certs found

### ISSUE THREAD

**Issue by stevebeattie** [oerdnj/deb.sury.org#859]
The openssl package in the php ppa needs to have the fix for [LP: #1764848](https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1764848) applied to it ([upstream commit](https://github.com/openssl/openssl/commit/e6a833cb97ed762408b57ea3efa83bd10c1d2a78) ). This is affecting users upgrading to 18.04 LTS with the php ppa installed; e.g. [LP: #1767864](https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1767864).

See also discussion in [debian-devel](https://lists.debian.org/debian-devel/2018/04/msg00620.html).

Thanks.

**Comment by oerdnj** [comment]
I pulled the upstream patch and uploaded fixed version.
