### ISSUE TITLE
Support for Wily

### ISSUE THREAD

**Issue by robfrawley** [oerdnj/deb.sury.org#86]
They alphas for 15.10 are out! I'd love for you to add Wily support. BTW: You're the best.

**Comment by markc** [comment]
Same here. I've been using wily for a few months now so would also appreciate pre-wily support to shake out any bugs before October

**Comment by robfrawley** [comment]
@oerdnj If there is anything I can do to contribute; please let me know, as well!

**Comment by robfrawley** [comment]
@oerdnj Quick note: the following packages from the vivid repo install and run perfectly on Wily:
```
php-pear
php5-cli
php5-common
php5-dev
php5-fpm
php5-gd
php5-json
php5-mcrypt
php5-mysqlnd
php5-tidy
```
As I continue with my development I'll be installing more and keep you updated. Thanks for your hard work. I sincerely rely on your up-to-date packages daily and appreciate the amount of work it must take to keep them as fresh as you do. Thanks!

**Comment by oerdnj** [comment]
I have modified all my scripts to add wily to the list of the supported releases. (And dropped utopic at the same time...)
