### ISSUE TITLE
 php7.1-curl : Depends: libcurl4 (>= 7.44.0) but it is not going to be installed

### ISSUE THREAD

**Issue by tarun-axelerant** [oerdnj/deb.sury.org#862]
Hi,

Getting below issue while instalingl php curl on Ubuntu 18.04 LTS. Please help. When I installed libcurl4 it uninstalled my virtualbox 5.2. 

 php7.1-curl : Depends: libcurl4 (>= 7.44.0) but it is not going to be installed
 virtualbox-5.2 : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed

Thanks,
Tarun

**Comment by oerdnj** [comment]
That’s a bug in virtualbox-5.2, it needs to be recompiled with curl from bionic.

**Comment by mrPsycho** [comment]
@oerdnj hello! 
same problem came again. 

new stuff, like unifi controller, needs new libcurl4

is there any way to rebuild php7.2-curl to use new libcurl4?
