### ISSUE TITLE
Problem with file uploads

### ISSUE THREAD

**Issue by flack** [oerdnj/deb.sury.org#863]
I'm using `PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1` on an Ubuntu 16.04 machine and I'm having a problem with form data getting lost. The form submits data roughly in this structure:

```php
[
    'video' => [
        'translations' => [
            'de' => [
                'title' => 'string',
                'subtitles' => 'upload field'
            ]
        ],
        'posterFrame' => 'upload field'
        'duration' => 'string'
    ]
]
```

When I leave the upload fields empty, the entire form data is available correctly in `$_POST`. However, when I try to upload a file in the `posterFrame` field, it shows up as expected in `$_FILES`, but `$_POST` then only contains the keys that were listed _before_ the upload field (i.e. in the example, `translations` is available in `$_POST`, but `duration` is missing).

All the relevant `php.ini` settings (max_post_size, allow_file_uploads etc.) look fine, and the application code itself also seems ok (it works fine on different machines with 18.04 and 17.10), so I wonder if this could be specific to this particular PHP build?

**Comment by flack** [comment]
P.S.: Not sure if this is relevant, but this happens with `php-fpm` under `nginx`

**Comment by oerdnj** [comment]
> (it works fine on different machines with 18.04 and 17.10)

What does that mean?  Are those running the same PHP version?

**Comment by flack** [comment]
the machines with 18.04/17.10 run the default PHP from Ubuntu (i.e. not from this PPA)

**Comment by oerdnj** [comment]
Then you need to report this to the upstream bug tracker as it is most probably related to the PHP 7.1.17 and not the _build_.

**Comment by flack** [comment]
For the record, I just tried upgrading to `7.2.5-1+ubuntu16.04.1+deb.sury.org+1` (on Ubuntu 16.04), which exhibits the same behavior. OTOH, `7.2.5-0ubuntu0.18.04.1` (on Ubuntu 18.04) works fine
