### ISSUE TITLE
Oracle OCI8 extension cannot be loaded in PHP-FPM on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cbj4074** [oerdnj/deb.sury.org#865]
PHP Version `7.2.5-1+ubuntu18.04.1+deb.sury.org+1`

I'm experiencing a frustrating issue that I describe in detail on StackOverflow:

https://stackoverflow.com/questions/50396992/how-does-one-enable-the-oci8-php-extension-using-the-oracle-instant-client-in

In short, I have no trouble configuring, compiling, installing, and enabling the oci8 extension on Ubuntu 16.04 LTS, but the same procedure does not work on Ubuntu 18.04 LTS.

I managed to get oci8 working on the CLI by specifying `LD_LIBRARY_PATH` in the invoking user's environment, but can't seem to find the equivalent solution for PHP running under PHP-FPM.

The same `oci8.so` works fine under Apache on the same system, although, Apache, too, requires the `LD_LIBRARY_PATH` to be specified, e.g., via its `envvars` configuration file.

Given that both PHP CLI and the module under Apache require `LD_LIBRARY_PATH` to be defined in ways that are not necessary in Ubuntu 16.04 LTS, I have to assume that this problem is somehow related.

Perhaps most oddly, I can't find any trace of an oci8-related error message when starting PHP-FPM or requesting a script through it. This is particularly strange given that both PHP CLI and Apache complained about not being able to find `libmql1.so` before I added the Oracle Instant Client path to `LD_LIBRARY_PATH`. I would expect PHP-FPM to complain similarly, yet the extension simply does not load and fails silently.

Does this seem like an issue with the packaging? Operator error? A problem with the OS? Any help would be greatly appreciated.

**Comment by oerdnj** [comment]
You need to configure your dynamic linker to search for the shared library in the non standard path. Either by configuring it globally or by using rpath when compiling the extension.

**Comment by cbj4074** [comment]
Thanks for taking a look, @oerdnj ; I really appreciate your time.

I made several attempts at doing as you suggest before opening this issue, but I wasn't explicit about what I had tried. My apologies.

Have you actually tried this on Ubuntu 18.04 LTS? Did it work for you? If so, what are you doing differently than I?

Based on cmake's order of precedence for resolving links, as described at https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling , I made the following attempts:

1.

Add to current user's environment before calling `./configure` and `make install`:

    export PHP_RPATHS=/opt/oracle/instantclient_12_2
    export LD_RUN_PATH=/opt/oracle/instantclient_12_2

2.

Add to `/etc/php/7.2/fpm/pool.d/www.conf` and restart `php7.2-fpm`:

    env[LD_LIBRARY_PATH] = /opt/oracle/instantclient_12_2

3.

Add library directory to linker configuration prior to configure/build:

    # echo /opt/oracle/instantclient_12_2 > /etc/ld.so.conf.d/oracle-instantclient

None of these measures allow the extension to be loaded.

The `configure` output says:

> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the '-LLIBDIR'
> flag during linking and do at least one of the following:
>   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
>     during execution
>    - add LIBDIR to the 'LD_RUN_PATH' environment variable
>      during linking
>    - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
>    - have your system administrator add LIBDIR to '/etc/ld.so.conf'

Okay, so we look at the `libtool` output during `configure` (full `configure` and `make` output at https://gist.github.com/cbj4074/f1426eb35a86f16385f4296ce1b2b1cd ):

```
/bin/bash /usr/local/src/oci8-2.1.8/libtool --mode=link cc -DPHP_ATOM_INC -I/usr/local/src/oci8-2.1.8/include -I/usr/local/src/oci8-2.1.8/main -I/usr/local/src/oci8-2.1.8 -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib -I/opt/oracle/instantclient_12_2/sdk/include  -DHAVE_CONFIG_H  -g -O2   -o oci8.la -export-dynamic -avoid-version -prefer-pic -module -rpath /usr/local/src/oci8-2.1.8/modules  oci8.lo oci8_lob.lo oci8_statement.lo oci8_collection.lo oci8_interface.lo oci8_failover.lo -Wl,-rpath,/opt/oracle/instantclient_12_2 -L/opt/oracle/instantclient_12_2 -lclntsh
libtool: link: cc -shared  -fPIC -DPIC  .libs/oci8.o .libs/oci8_lob.o .libs/oci8_statement.o .libs/oci8_collection.o .libs/oci8_interface.o .libs/oci8_failover.o   -L/opt/oracle/instantclient_12_2 -lclntsh  -g -O2 -Wl,-rpath -Wl,/opt/oracle/instantclient_12_2   -Wl,-soname -Wl,oci8.so -o .libs/oci8.so
```

The output reflects `-L/opt/oracle/instantclient_12_2`, which unless I am misunderstanding, seems to satisfy the first requirement.

Regarding the secondary requirements, not only have I done "at least one" of those things, I've done *all* of them:

   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution

I did this, as noted above.

   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking

I did this, as noted above.

   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag

Shouldn't this happen automatically by way of this switch?

    ./configure --with-oci8=instantclient,/opt/oracle/instantclient_12_2`

The `libtool` output I pasted above does contain the following:

    (line 1) ... -Wl,-rpath,/opt/oracle/instantclient_12_2 -L/opt/oracle/instantclient_12_2 ...
    (line 2 )... -Wl,-rpath -Wl,/opt/oracle/instantclient_12_2 ...

   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

I did this, as noted above.

I must be missing something here...

I notice an interesting discrepency between Ubuntu 16.04 LTS, where this works as expected, and Ubuntu 18.04 LTS, where it does not.

The `objdump` output for the compiled extension reveals that `rpath` is used on Ubuntu 16.04, but `runpath` is used on Ubuntu 18.04.

On 16.04:

```
root@homestead:/home/vagrant# objdump -x /usr/lib/php/20170718/oci8.so | grep -i "rpath"
  RPATH                /opt/oracle/instantclient_12_2
root@homestead:/home/vagrant# objdump -x /usr/lib/php/20170718/oci8.so | grep -i "runpath"
```

On 18.04:

```
root@homestead:/usr/local/src/oci8-2.1.8# objdump -x /usr/lib/php/20170718/oci8.so | grep -i "rpath"
root@homestead:/usr/local/src/oci8-2.1.8# objdump -x /usr/lib/php/20170718/oci8.so | grep -i "runpath"
  RUNPATH              /opt/oracle/instantclient_12_2
```

Could this be a contributing factor to the observed behavior?

As yet unanswered questions:

1. Why does the extension work fine on the CLI and under Apache2, but not php-fpm, despite the same `LD_LIBRARY_PATH` value being set in all three scenarios?
2. Why doesn't php-fpm emit a startup error similar to the error that the CLI and Apache2 emit when `LD_LIBRARY_PATH` is not defined in the runtime environment? Silently failing to load the extension isn't the expected behavior.

Thanks again for your help!

**Comment by cbj4074** [comment]
I believe I have found the source of this problem:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859732

**Comment by vinc17fr** [comment]
Debian bug 859732 is a completely different issue. See [my answer on Stackoverflow](https://stackoverflow.com/a/50642297/3782797). In short, your `LD_LIBRARY_PATH` seems incorrect.

Note also that your usage of the run path is incorrect: it must be provided when compiling PHP, not the library. So, just ignore this solution.

**Comment by cbj4074** [comment]
Alas, foregoing `LD_LIBRARY_PATH` in favor of updating the linker configuration prior to building solves the problem:

    # sh -c "echo /opt/oracle/instantclient_12_2 > /etc/ld.so.conf.d/oracle-instantclient.conf"
    # ldconfig

I had tried this before, but shame on me: I appear to have forgotten to execute `ldconfig` after adding the path, based on the snippet I pasted in the OP.

I still don't know why `LD_LIBRARY_PATH` isn't honored in the PHP-FPM context, but at least the linker method works as it should.

Thanks again @oerdnj and @vinc17fr for your patience and expertise.

**Comment by vinc17fr** [comment]
Be careful that adding `/opt/oracle/instantclient_12_2` to the default search directories with `ldconfig`, thus globally, might conflict with other software. A run path (either with `DT_RPATH` or with `DT_RUNPATH`) , since this is what `oci8.so` uses,or `LD_LIBRARY_PATH` specific to Apache would have been a better solution here.

If `LD_LIBRARY_PATH` doesn't work, perhaps there's a bug in Apache or PHP. But look at https://www.google.com/search?q=php+ld_library_path first.

**Comment by cbj4074** [comment]
@vinc17fr Excellent point regarding introducing potential conflicts by using `ldconfig`; for that reason, I'd still like to determine why `LD_LIBRARY_PATH` is ignored in PHP-FPM.

I've determined (in the StackOverflow post cited in the OP) that on Ubuntu 16.04 LTS, `ldd /usr/lib/php/20170718/oci8.so`  finds the Oracle libraries in `/opt/oracle/instantclient_12_2`, *even when* `LD_LIBRARY_PATH` is unset.

For whatever reason, the same is not true on Ubuntu 18.04 LTS, with all other factors being equal. I am literally using the *exact* same "recipe" in a Vagrant VM to test this, and the *only* thing I'm changing is the Vagrant box version, from 16.04 to 18.04, between tests. The oci8 extension loads-up in PHP-FPM just fine on 16.04, but not on 18.04.

Here's a diff of all the relevant library and object linkage information on both OSes:

https://www.diffchecker.com/kpJtFoBm

The relevant facts seem to be as follows:

1. The extension is loaded perfectly well in the CLI, provided that `LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2`:

```
vagrant@homestead:~$ echo $LD_LIBRARY_PATH
/opt/oracle/instantclient_12_2
vagrant@homestead:~$ php -i | grep "oci8"
/etc/php/7.1/cli/conf.d/20-oci8.ini,
oci8
oci8.connection_class => no value => no value
oci8.default_prefetch => 100 => 100
oci8.events => Off => Off
oci8.max_persistent => -1 => -1
oci8.old_oci_close_semantics => Off => Off
oci8.persistent_timeout => -1 => -1
oci8.ping_interval => 60 => 60
oci8.privileged_connect => Off => Off
oci8.statement_cache_size => 20 => 20
```

2. The extension is loaded perfectly well in Apache, provided that `LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2`.

3. *But*, the extension is *not* loaded in PHP-FPM (running via NGINX), even when `LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2`, set by adding `env['LD_LIBRARY_PATH'] = '/opt/oracle/instantclient_12_2'` to the effective PHP-FPM pool configuration, e.g., `/etc/php/7.2/fpm/pool.d/www.conf` and restarating the PHP-FPM daemon.

As can be seen from the `phpinfo();` output, the `LD_LIBRARY_PATH` value I've set is clearly registered with the environment:

![php-fpm-ubuntu-18 04-env](https://user-images.githubusercontent.com/1236883/40982183-a1cdffca-68aa-11e8-8ca3-a9d8e5071a14.PNG)

Isn't the only plausible explanation here that PHP-FPM is ignoring `LD_LIBRARY_PATH`?

In fact, it's quite possibly (and perhaps even likely) that the same problem exists in Ubuntu 16.04, but it doesn't manifest in the same way because, as I noted above, `ldd /usr/lib/php/20170718/oci8.so`  finds the Oracle libraries in `/opt/oracle/instantclient_12_2`, *even when* `LD_LIBRARY_PATH` is unset.

I'm not sure how to troubleshoot this any further, but until somebody else tries it and confirms that it works for them, I remain convinced that this is a bug of some variety.

**Comment by vinc17fr** [comment]
`/usr/lib/php/20170718/oci8.so` finds the libraries in `/opt/oracle/instantclient_12_2` because it uses a `RUNPATH` set to `/opt/oracle/instantclient_12_2` (thus `LD_LIBRARY_PATH` is useless here).

Setting `env['LD_LIBRARY_PATH'] = '/opt/oracle/instantclient_12_2'` may not be a solution because it may be taken into account too late. Make sure that `nginx` is started in an environment where `LD_LIBRARY_PATH` is already set (the `nginx` startup file may need to be modified).

**Comment by cbj4074** [comment]
With @vinc17fr 's help, I was finally able to resolve this.

It turns-out that shell environment variables are not propagated to processes started via `systemd` Unit files. Rather, it is necessary to specify the any environment variables, particularly those that affect library linkages, in the Unit configuration file(s).

For example, on a system running co-installable versions of your PHP 7.0, 7.1, and 7.2 packages:

Create the unit extension directories (to avoid modifying package-maintained files):

```
# mkdir /etc/systemd/system/php7.0-fpm.service.d
# mkdir /etc/systemd/system/php7.1-fpm.service.d
# mkdir /etc/systemd/system/php7.2-fpm.service.d
```

Create one extender configuration file, to which we can symlink for the other PHP versions:

```
# touch /etc/systemd/system/php7.0-fpm.service.d/environment.conf
```

To this file we add the following:

```
[Service]
Environment=LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2
```


Then we create the symlinks for other PHP versions:

```
# ln -s /etc/systemd/system/php7.0-fpm.service.d/environment.conf /etc/systemd/system/php7.1-fpm.service.d/environment.conf
# ln -s /etc/systemd/system/php7.0-fpm.service.d/environment.conf /etc/systemd/system/php7.2-fpm.service.d/environment.conf
```

And to make the change effective:

```
# systemctl daemon-reload
# systemctl restart php7.*-fpm
```

:+1:

**Comment by delzep** [comment]
I had the same problem with a Laravel aplication using Ubuntu 23.1, nginx and php 8.2.10 @cbj4074 your solution worked perfectly, Thank you so much!
