### ISSUE TITLE
Php7.0 -> 7.2, conflicting ssh2.ini

### ISSUE THREAD

**Issue by goldencut** [oerdnj/deb.sury.org#866]
Hi,
While trying to install php7.2 alongside 7.0 I get:

> Unpacking php-ssh2 (1.1.2+0.13-1+0~20170825111614.1+jessie~1.gbp4442f0) ...
dpkg: error processing archive /var/cache/apt/archives/php-ssh2_1.1.2+0.13-1+0~20170825111614.1+jessie~1.gbp4442f0_amd64.deb (--unpack):
 trying to overwrite '/etc/php/7.0/mods-available/ssh2.ini', which is also in package php7.0-ssh2 1.0-1~dotdeb+8.4
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 /var/cache/apt/archives/php-ssh2_1.1.2+0.13-1+0~20170825111614.1+jessie~1.gbp4442f0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Should 7.2 ini files be in "7.0" directory - '/etc/php/**7.0**/mods-available/ssh2.ini'?

BR,
G.

**Comment by oerdnj** [comment]
You can’t mix dotdeb packages with mine.

**Comment by goldencut** [comment]
Reason being...?
Anyhow - are php7.2 config files kept in directory named "7.0"?

G.

**Comment by oerdnj** [comment]
Because they are not compatible.

php-ssh provides extensions for all available supported PHP versions.

**Comment by goldencut** [comment]
So to move to using your php7.2 I should remove my current php7.0 first?

G.

**Comment by oerdnj** [comment]
You need to remove and purge dotdeb packages first, or deal with errors one-by-one.

**Comment by goldencut** [comment]
Thnx, I guess so it has to be..
