### ISSUE TITLE
PPA for Apache 2.x - Debian 7, 8, and 9 Support Possible?

### ISSUE THREAD

**Issue by own3mall** [oerdnj/deb.sury.org#867]
The Apache 2.x PPA works perfectly on Ubuntu 14.04 - 18.04.  Would it be possible to add support for a minimum version of Apache 2.4.26 or greater through this PPA for Debian 7, 8, and 9?

https://launchpad.net/~ondrej/+archive/ubuntu/apache2

I'd really like to be able to use these directives on Debian:

https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html#ProxyFCGISetEnvIf

Thanks for doing this for Ubuntu.  Hopefully, we can get this working on Debian next.  :+1:

**Comment by own3mall** [comment]
I think supporting Debian 8 and 9 is enough.  7 is too old.

Also, it looks like I can get it to work on both Debian 8 and 9 by changing the /etc/apt/sources.list.d/ondrej-ubuntu-apache2-cosmic.list contents to use xenial rather than cosmic for Debian 9, and change /etc/apt/sources.list.d/ondrej-ubuntu-apache2-cosmic.list to use trusty rather than cosmic for Debian 8.

I'm guessing it's just a question of identifying which one to use for Debian.  Here's a list if it helps:

https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on#answer-445496

**Comment by drewwalton19216801** [comment]
I second this.

**Comment by stephenreay** [comment]
I'd also like to see this as an option, to make use of the PROXY protocol support merged into `mod_remoteip`: https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html#remoteipproxyprotocol

**Comment by oerdnj** [comment]
This exists for quite some time now: https://packages.sury.org/apache2/
