### ISSUE TITLE
Need previous version of php-redis package

### ISSUE THREAD

**Issue by h4xmd** [oerdnj/deb.sury.org#869]
It seems that with the upgrade of php-redis to v4.0, this introduces a breaking change with, for example, the Symfony snc/redis-bundle.

https://github.com/snc/SncRedisBundle/issues/399

The only way around this is to downgrade to the previous version of php-redis but you don't appear to have them in the repository anymore?

This is a showstopping change and without a fix from the snc/redis-bundle, we are in a very difficult situation.

How can I go back to the previous 3.1.x version?

**Comment by curry684** [comment]
This can actually be closed since we "fixed" it in the bundle. It's not an issue for upstream anyway.

**Comment by oerdnj** [comment]
This is not going to happen.  The goal of the repository is to provide latest upstream releases.
