### ISSUE TITLE
PPA for PHP 7.0 (experimental) fails on php7.0-cli installation

### ISSUE THREAD

**Issue by geerlingguy** [oerdnj/deb.sury.org#87]
I'm getting the following error when I try installing PHP 7.0 via the just-released beta1 version on your PPA (thanks for your work on these packages!):

```
Creating config file /etc/php/7.0/mods-available/pdo.ini with new version
cp: cannot create regular file ‘/etc/php/7.0/mods-available/pdo.ini’: No such file or directory
dpkg: error processing package php7.0-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of php7.0-cli:
 php7.0-cli depends on php7.0-common (= 7.0.0~beta1-1+deb.sury.org~trusty+useatyourownrisk5); however:
  Package php7.0-common is not configured yet.
```

It seems the `mods-available` directory and `pdo.ini` file is never created, so maybe that's the issue here? Or the order of installation/dependencies?

**Comment by oerdnj** [comment]
It seems there's something broken with dh_installdirs. I am running a debug build on slightly modified version, so we'll see. Thanks for the report.

**Comment by oerdnj** [comment]
The main problem is that it takes ages to build the PHP package (even without running the tests), so every glitch like this also takes ages to fix, since it's hard to debug during the build process.

**Comment by oerdnj** [comment]
I think it should be fixed in the 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8

I am entirely not sure whether phpenmod and phpdismod works as expected since it's a 3d matrix now (version, sapi, module), but at least it doesn't stop on random shell script errors.

**Comment by geerlingguy** [comment]
@oerdnj - Thanks! I can install the main packages now, but I wasn't able to get `php7.0-json` installed; it gave the error:

```
The following packages have unmet dependencies:
 php7.0-json : Depends: php7.0-common (= 7.0.0~alpha2-1+deb.sury.org~trusty+donotuse1) but 7.0.0~beta1-1+deb.sury.org~trusty+useatyourownrisk8 is to be installed
```

The json package is required to get Composer working with PHP 7.

**Comment by oerdnj** [comment]
json extension is not again bundled in the SAPIs, so you don't need to install it. But I will re-add the Provides: php7.0-json to php7.0-common, so it doesn't confuse people.
