### ISSUE TITLE
Debian 9 + PHP7.2-fpm not available

### ISSUE THREAD

**Issue by JB1985** [oerdnj/deb.sury.org#873]
> # cat /etc/apt/sources.list.d/php.list 
> deb https://packages.sury.org/php/ stretch main

`# apt-get install php7.2-fpm
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paket php7.2-fpm ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.

E: Für Paket »php7.2-fpm« existiert kein Installationskandidat.
`

Anyone a idea?

**Comment by oerdnj** [comment]
ARM?

**Comment by JB1985** [comment]
No, 64bit.

**Comment by oerdnj** [comment]
Did you run apt-get update, right? And it finished without error?

**Comment by JB1985** [comment]
Yes, sure.

# apt update
Ign:1 http://hwraid.le-vert.net/debian stretch InRelease
OK:2 http://hwraid.le-vert.net/debian stretch Release                                                                                                                
OK:3 http://security.debian.org stretch/updates InRelease                                                                                                                                  
Ign:4 http://dl.google.com/linux/mod-pagespeed/deb stable InRelease                                                                                                         
Ign:5 http://ftp.de.debian.org/debian stretch InRelease                                                                                             
Ign:6 http://debian.mirrors.ovh.net/debian stretch InRelease                 
OK:7 http://dl.google.com/linux/mod-pagespeed/deb stable Release             
Holen:8 http://debian.mirrors.ovh.net/debian stretch Release [118 kB]        
OK:9 http://ftp.de.debian.org/debian stretch-updates InRelease                      
OK:10 http://ftp.de.debian.org/debian stretch Release                               
OK:12 https://packages.sury.org/php stretch InRelease       
OK:13 https://apt.dockerproject.org/repo debian-stretch InRelease
Es wurden 118 kB in 0 s geholt (150 kB/s).
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.

**Comment by oerdnj** [comment]
Then what does apt-cache policy php7.2-fpm says?

**Comment by JB1985** [comment]
Sorry, my fault. I had forgotten to add

Package: *php7.2*
Pin: origin packages.sury.org
Pin-Priority: 1000

in the preferences.

But I get this error now:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 php7.2-fpm : Hängt ab von: php7.2-cli soll aber nicht installiert werden
              Hängt ab von: libsodium23 (>= 1.0.14) ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by JB1985** [comment]
OK, after installing libsodium23 [1.0.16-2+0~20180103211631.7+stretch~1.gbpb56693 (<NULL>)] works now.

Sorry!

**Comment by oerdnj** [comment]
Happy to be your [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging).
