### ISSUE TITLE
php5.6-mysql install errors

### ISSUE THREAD

**Issue by chrisdrysdale** [oerdnj/deb.sury.org#876]
Hi there,

I'll start by admitting my near-noob-like abilities when it comes to php and docker, but I'm having issues when it comes to updating my dockerfile for unsupported php extensions.  In this case the php-mysql package.  My dockerfile:

`FROM php:5.6-fpm
RUN apt-get update

RUN apt-get install -y wget
RUN apt-get -y install apt-transport-https lsb-release ca-certificates
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update

RUN apt-get install -y aptitude
RUN aptitude purge dpkg -l | grep php| awk '{print $2}' |tr "\n" " "

RUN apt-get update
RUN apt-get install -y php5.6-mysql
RUN docker-php-ext-install mysqli

RUN usermod -u 1000 www-data`

The error:

`Step 11/13 : RUN apt-get install -y php5.6-mysql
 ---> Running in 557f71ff2a4d
Reading package lists...
Building dependency tree...
Reading state information...
Package php5.6-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5.6-mysql' has no installation candidate
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get install -y php5.6-mysql' returned a non-zero code: 100`

I was just wondering if there's anything basic I'm missing here?  Any advice is much appreciated!

**Comment by oerdnj** [comment]
I am sorry, I do not a capacity to solve the problems not directly related to the packages. You will need to use appropriate forum like Server Fault.
