### ISSUE TITLE
Support Debian buster

### ISSUE THREAD

**Issue by DeepDiver1975** [oerdnj/deb.sury.org#879]
Since yesterday libcurl was updated in the debian buster repos to 7.60.0 which removed php*-curl and can no longer be installed

![screenshot from 2018-06-05 08-45-51](https://user-images.githubusercontent.com/1005065/40959438-fa02b90a-689c-11e8-83c2-4c1e0dd074e7.png)

Let me know if there is anything to help out ... THX a lot!

**Comment by DeepDiver1975** [comment]
looks like libcurl3 conflicts with libcurl4 and libcurl4 is a major dependency to curl, apache, gnome, cmake .....

but libcurl3-gnutls is installed - will that be enough?

**Comment by oerdnj** [comment]
Debian buster isn't really supported neither from Ubuntu PPAs nor Debian DPAs.

**Comment by DeepDiver1975** [comment]
Can we still keep this open? I mean: one day buster will become stable - right?
I happily contribute to make it work - just let me know

**Comment by bonswouar** [comment]
Same problem here with `php7.1-curl`, using PPA for Bionic works thanks @DeepDiver1975 .

**Comment by kmbt** [comment]
Hi

Could we reopen the issue since buster is stable now? I am facing similar problems with `php7.3-curl`.
