### ISSUE TITLE
How to trace segfaults on php5.6

### ISSUE THREAD

**Issue by stAn47** [oerdnj/deb.sury.org#881]
Hello, we are getting lot's of segfaults with php5.6-fpm and i'd like to ask a little help on how to enable traces with dbg packages installed, this is the segfault: 

```
[Wed Jun  6 10:25:08 2018] php-fpm5.6[23993]: segfault at 7ffdd2379f10 ip 0000560b9af8d5f5 sp 00007ffdd2379f00 error 6 in php-fpm5.6[560b9ad9d000+3b4000]
```

PHP version: PHP Version 5.6.36-1+ubuntu14.04.1+deb.sury.org+1
Linux: Ubuntu 14.04 with Xenial kernel 4.4.127 (we recently upgraded kernel in hope that this bug would get fixed, but it happened also on standard 3.13.X kernel )

loaded extensions are: 
```

array (
--
  | 0 => 'Core',
  | 1 => 'date',
  | 2 => 'ereg',
  | 3 => 'libxml',
  | 4 => 'openssl',
  | 5 => 'pcre',
  | 6 => 'zlib',
  | 7 => 'filter',
  | 8 => 'hash',
  | 9 => 'Reflection',
  | 10 => 'SPL',
  | 11 => 'session',
  | 12 => 'standard',
  | 13 => 'cgi-fcgi',
  | 14 => 'mysqlnd',
  | 15 => 'PDO',
  | 16 => 'xml',
  | 17 => 'bcmath',
  | 18 => 'bz2',
  | 19 => 'calendar',
  | 20 => 'ctype',
  | 21 => 'curl',
  | 22 => 'dom',
  | 23 => 'mbstring',
  | 24 => 'fileinfo',
  | 25 => 'ftp',
  | 26 => 'gd',
  | 27 => 'gettext',
  | 28 => 'iconv',
  | 29 => 'imagick',
  | 30 => 'imap',
  | 31 => 'intl',
  | 32 => 'json',
  | 33 => 'exif',
  | 34 => 'mcrypt',
  | 35 => 'mysql',
  | 36 => 'mysqli',
  | 37 => 'pdo_mysql',
  | 38 => 'Phar',
  | 39 => 'posix',
  | 40 => 'readline',
  | 41 => 'shmop',
  | 42 => 'SimpleXML',
  | 43 => 'soap',
  | 44 => 'sockets',
  | 45 => 'tokenizer',
  | 46 => 'wddx',
  | 47 => 'xmlreader',
  | 48 => 'xmlrpc',
  | 49 => 'xmlwriter',
  | 50 => 'xsl',
  | 51 => 'zip',
  | 52 => 'mhash',
  | )

```
any help on how to enable traces so we know which php extension causes the trouble would be appreciated. we are using php-fpm's chroot option and it's possible that some extension is missing files within individual chroot enviroment. 

thank you, best regards, stan

**Comment by oerdnj** [comment]
The debugging symbols:
https://github.com/oerdnj/deb.sury.org/wiki/Debugging-Symbols
How to get a backtrace:
https://bugs.php.net/bugs-generating-backtrace.php
