### ISSUE TITLE
Update to nginx 1.14.0 (Mainline) ?

### ISSUE THREAD

**Issue by Ruok2bu** [oerdnj/deb.sury.org#888]
Current version on the PPA is out of date.  Can you update it?

**Comment by Ruok2bu** [comment]
Mainline got another update; the version is now 1.15.0  What's the ETA on the upgrade?  If its more than a month away, what command can i use to force installation of your version over the newer version?

**Comment by oerdnj** [comment]
nginx 1.15.2 has been uploaded to the repository.
