### ISSUE TITLE
Request for a version of libapache2-mod-perl2 (mod_perl.so) that works with the PHP5 PPA

### ISSUE THREAD

**Issue by dleigh** [oerdnj/deb.sury.org#89]
Hi,  (sent this via email to you but since then I found your tracking page and placed it here)
I’m running one of your PPA packages (I believe so that I could run OwnCloud on my Ubuntu 12.04 system): 

root@i-server:~# apt-cache policy apache2.2-common
apache2.2-common:
  Installed: 2.4.12-1+deb.sury.org~precise+5
  Candidate: 2.4.12-1+deb.sury.org~precise+5
  Version table:
*** 2.4.12-1+deb.sury.org~precise+5 0
        500 http://ppa.launchpad.net/ondrej/php5/ubuntu/ precise/main i386 Packages
        100 /var/lib/dpkg/status
     2.2.22-1ubuntu1.9 0
        500 http://fr.archive.ubuntu.com/ubuntu/ precise-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu/ precise-security/main i386 Packages
     2.2.22-1ubuntu1 0
        500 http://fr.archive.ubuntu.com/ubuntu/ precise/main i386 Packages

Unfortunately, it apparently breaks mod-perl:
The following packages have unmet dependencies:
libapache2-mod-perl2 : Depends: apache2.2-common but it is not going to be installed

Can you suggest a source for mod_perl.so that will function with your PPA package?  I suppose the other alternative is to upgrade to 14.04?
Thanks!

**Comment by oerdnj** [comment]
Hi, I will work on adding new packages to the repositories this week.

**Comment by dleigh** [comment]
Thanks!

 

 <mailto:david@leighweb.com> DavidEmailSig

**Comment by oerdnj** [comment]
Ubuntu 12.04 LTS support in my PPAs is reaching EOL, so no new packages for Ubuntu 12.04 LTS (Precise) will be added, see https://deb.sury.org/ubuntu-precise-and-PHP-5.4-eol.html
