### ISSUE TITLE
[Feature Request] make PHP7.2-redis available in armhf

### ISSUE THREAD

**Issue by nachoparker** [oerdnj/deb.sury.org#890]
Hello,

I noticed that I can install `php7.2-redis` from sury packages in x86, but it is not available in armhf.

Thanks for your work.

**Comment by oerdnj** [comment]
dup of #579

**Comment by nachoparker** [comment]
apologies, I saw that but I thought it was a different issue

thanks

**Comment by nachoparker** [comment]
Hi,

Still no php7.2-redis on armhf, whereas it exists on x86. It is the only package missing. I can see it on your Jenkins but it doesn't show up when I try to install it through apt.

Any news about this? Are there plans to provide this package in the future? I would just like to know if this is ever going to happen.

Many thanks for your packages
