### ISSUE TITLE
Apache 2.4.33-3 breaks systems running Ubuntu 14.04

### ISSUE THREAD

**Issue by hawk-tld** [oerdnj/deb.sury.org#892]
Release 2.4.33-3 of apache2 breaks Ubuntu 14.04 installation by requiring dpkg newer than available. After dist-upgrade apache2 package is in  'rc' state and thus apache2 no longer works. Here is sample apt-get output:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : PreDepends: dpkg (>= 1.17.14)
E: Unable to correct problems, you have held broken packages.

Trusty has dpkg 1.17.5.

**Comment by drkskwlkr** [comment]
I confirm identical issue.

**Comment by aidvu** [comment]
Same.

**Comment by kristous** [comment]
+1

**Comment by stecklars** [comment]
Can confirm this as well

**Comment by kzakhark** [comment]
Confirm: 

The following packages have unmet dependencies:
apache2 : PreDepends: dpkg (>= 1.17.14)
E: Unable to correct problems, you have held broken packages.

**Comment by kzakhark** [comment]
Any updates on this, please?

**Comment by magnetik** [comment]
I've contacted Ondřej and he does not have the time to fix it at the moment.

As a workaround (for the specific bug I mentioned regarding mod md) is to copy the mod manually.

**Comment by oerdnj** [comment]
I scheduled some time for next week to work on this. There's a problem that mod_md requires a version of curl not available on trusty. And backporting curl requires caution.

**Comment by oerdnj** [comment]
Seems ok to me now:
```
ondrej@lettie:/tmp$ dpkg --info apache2_2.4.34-1+ubuntu14.04.1+deb.sury.org+4_amd64.deb | grep Pre-Depends
ondrej@lettie:/tmp$ dpkg --info apache2-bin_2.4.34-1+ubuntu14.04.1+deb.sury.org+4_amd64.deb | grep Pre-Depends
```

If not, I will need more diagnostic information.

**Comment by drkskwlkr** [comment]
Thank you @oerdnj. Update went OK for me.
