### ISSUE TITLE
libapache2-mod-md 2.4.33-3.0+ubuntu16.04.1+deb.sury.org+1 is empty

### ISSUE THREAD

**Issue by magnetik** [oerdnj/deb.sury.org#894]
The latest version from the repo `2.4.33-3.0+ubuntu16.04.1+deb.sury.org+1` only contains:

```
 This is a transitional package to apache2 for users of libapache2-mod-md.
 It can be safely removed after the installation is complete.
```

Has the package name changed? There should be a dependency or something?

Where can we find the file `/usr/lib/apache2/modules/mod_md.so`?

**Comment by magnetik** [comment]
Might be a duplicated of #841

**Comment by michlaustn** [comment]
I too am having the same issues with the md module.  Removing the transitional packages and installing apache fresh I still get the error regarding the missing module file.

`apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/md.load: Cannot load /usr/lib/apache2/modules/mod_md.so into server: /usr/lib/apache2/modules/mod_md.so: cannot open shared object file: No such file or directory`

**Comment by marcelofrota2** [comment]
I also see the problem on my machines

**Comment by oerdnj** [comment]
Nah, the hard curl >= 7.50 is still in the 2.4.34, I am trying to remove that hard requirement in the next build, so we'll see whether all hell break loose or it will just work.

**Comment by oerdnj** [comment]
apache2-bin for Ubuntu 14.04 now contains mod_md; can somebody that uses it please test the packages and report success (or failure)?

**Comment by magnetik** [comment]
Confirming it for Ubuntu 16.04

**Comment by magnetik** [comment]
Ton of thanks of course :)

**Comment by oerdnj** [comment]
Well, sorry that it took so long to fix it.  I am busy and when some breakage like this occurs I need a continuous block of time to debug and properly fix the it.  I know this isn't ideal.

**Comment by oerdnj** [comment]
I am closing the issue for now as it seems that it has been fixed. I still have no idea why curl 7.50 is enforced by upstream while it compiles just fine with the version in Ubuntu 14.04.
