### ISSUE TITLE
GD extension (especially libgd) should to be updated on Jessie

### ISSUE THREAD

**Issue by vdechenaux** [oerdnj/deb.sury.org#897]
Hi,

I'm using `https://packages.sury.org/php/` with Jessie and I have a problem with GD extension.
I'm facing this bug https://bugs.php.net/bug.php?id=73479 and the fix is available in libgd.

The current version of the lib in your packages is `2.1.1-dev`, it would be great if you can update it to `2.2.5`.

Thanks!

**Comment by MrMitch** [comment]
Hi @oerdnj, i'm facing a similar issue. I'm using your PPAs (one on Ubuntu 16.04 and another on Debian 8 jessie) to install PHP and its modules. 
On the Ubuntu 16.04 machine, the GD library installed from your ppa is `2.2.5` (which seems to be the latest available).
On the Debian 8 jessie machine, the GD library installed seems to be `2.1.1-dev` which is faily old (around May 2016 according to https://github.com/libgd/libgd/releases/tag/gd-2.2.1).

This is causing a different behavior between our image processing apps on each machine, with the one on Debian behaving wrongly.

Could you update the GD library in the ppa used on Debian, please ? If not, can I do anything to help or do you have any alternative in mind to get the latest GD on Debian 8 jessie ?

Thank you for your work, much appreciated.

**Comment by oerdnj** [comment]
Let's see if all combinations build successfully: https://jenkins.rfc1925.org/view/PHP/job/php_libgd2-binaries/

**Comment by MrMitch** [comment]
Hi @oerdnj, thank you for closing this so quickly. I see that all the builds passed and `dpkg -l libgd3` indicates that the version of the library is indeed `2.2.5`
```
mitch@54b5192a13cf:~$ dpkg -l libgd3
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  libgd3:amd64                              2.2.5-5+0~20181028223034. amd64                     GD Graphics Library
```

However, php stills seems to use `2.1.1-dev` : 
mesavolt@54b5192a13cf:~$ php --ri gd

gd

GD Support => enabled
GD headers Version => 2.1.1-dev
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.5.2
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.2.50
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

Do we need to take complementary actions in our container to make sure PHP 7.1 uses the correct version of GD ?
