### ISSUE TITLE
php-apcu missing 7.2 module

### ISSUE THREAD

**Issue by zsalab** [oerdnj/deb.sury.org#898]
the 7.2 module is missing from the php-apcu package, I tried to build the source package and it added the module to 7.2 for me, I guess the package just have to be rebuild

**Comment by zsalab** [comment]
my bad, sorry

**Comment by oerdnj** [comment]
Do, how do you know it’s missing? What’s output of:
dpkg -L php-apcu 
apt-cache policy php-apcu 
On a system that’s broken?
