### ISSUE TITLE
Odd unmet dependencies 

### ISSUE THREAD

**Issue by tommiv** [oerdnj/deb.sury.org#90]
So I'm trying to install php 5.6 from PPA on pretty clean Ubuntu 14.04 (I've only added PPAs for nginx and postgresql for now, installed it and created user for http pool).

1. I'm add PPA `sudo add-apt-repository ppa:ondrej/php5-5.6`, result
```
gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
```

2. `sudo apt-get update`
```
Fetched 3,301 kB in 19s (172 kB/s)
Reading package lists... Done
```

3. Check if it's ok `apt-cache policy php5`
```php5:
  Installed: (none)
  Candidate: 5.6.11+dfsg-1+deb.sury.org~trusty+1
  Version table:
     5.6.11+dfsg-1+deb.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main amd64 Packages
     5.5.9+dfsg-1ubuntu4.11 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     5.5.9+dfsg-1ubuntu4 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

4. Fine, let's install it `sudo apt-get install php5`

```
Reading state information... Done
The following extra packages will be installed:
  libapache2-mod-php5 php5-cli php5-common php5-json php5-readline
Suggested packages:
  php-pear php5-user-cache
The following NEW packages will be installed:
  libapache2-mod-php5 php5 php5-cli php5-common php5-json php5-readline
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5,039 kB of archives.
After this operation, 20.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
```

and then:

```
Setting up php5-common (5.6.11+dfsg-1+deb.sury.org~trusty+1) ...
dpkg: dependency problems prevent configuration of php5-json:
 php5-json depends on phpapi-20121212; however:
  Package phpapi-20121212 is not installed.

dpkg: error processing package php5-json (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          dpkg: dependency problems prevent configuration of php5-cli:
 php5-cli depends on php5-json; however:
  Package php5-json is not configured yet.

dpkg: error processing package php5-cli (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libapache2-mod-php5:
 libapache2-mod-php5 depends on php5-cli; however:
  Package php5-cli is not configured yet.
 libapache2-mod-php5 depends on php5-json; however:
  Package php5-json is not configured yet.

dpkg: error processing package libapache2-mod-php5 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                   dpkg: dependency problems prevent configuration of php5:
 php5 depends on libapache2-mod-php5 (>= 5.6.11+dfsg-1+deb.sury.org~trusty+1~) | libapache2-mod-php5filter (>= 5.6.11+dfsg-1+deb.sury.org~trusty+1~) | php5-cgi (>= 5.6.11+dfsg-1+deb.sury.org~trusty+1~) | php5-fpm (>= 5.6.11+dfsg-1+deb.sury.org~trusty+1~); however:
  Package libapache2-mod-php5 is not configured yet.
  Package libapache2-mod-php5filter is not installed.
  Package php5-cgi is not installed.
  Package php5-fpm is not installed.

dpkg: error processing package php5 (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent configuration of php5-readline:
 php5-readline depends on php5-cli (= 5.6.11+dfsg-1+deb.sury.org~trusty+1); however:
  Package php5-cli is not configured yet.

dpkg: error processing package php5-readline (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              Errors were encountered while processing:
 php5-json
 php5-cli
 libapache2-mod-php5
 php5
 php5-readline
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This error appears every time I try to install it. `apt-get -f install` doesn't work until I remove ondrej PPA. Then I need to uninstall php5-common explicitly. So, why it depends on php5-json which depends on api of 2012 year? Is this a common bug or something wrong with my Ubuntu installation? And, of course, how to get rid with this error?

**Comment by oerdnj** [comment]
What does

apt-cache policy php5-json

says? 

On July 23, 2015 11:28:30 AM GMT+02:00, Konstantin Ilchenko <notifications@github.com> wrote:
>So I'm trying to install php 5.6 from PPA on pretty clean Ubuntu 14.04
>(I've only added PPAs for nginx and postgresql for now, installed it
>and created user for http pool).
>
>1. I'm add PPA `sudo add-apt-repository ppa:ondrej/php5-5.6`, result
>```
>gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
>gpg: Total number processed: 1
>gpg:               imported: 1  (RSA: 1)
>OK
>```
>
>2. `sudo apt-get update`
>```
>Fetched 3,301 kB in 19s (172 kB/s)
>Reading package lists... Done
>```
>
>3. Check if it's ok `apt-cache policy php5`
>```php5:
>  Installed: (none)
>  Candidate: 5.6.11+dfsg-1+deb.sury.org~trusty+1
>  Version table:
>     5.6.11+dfsg-1+deb.sury.org~trusty+1 0
>500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main amd64
>Packages
>     5.5.9+dfsg-1ubuntu4.11 0
>500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64
>Packages
>500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64
>Packages
>     5.5.9+dfsg-1ubuntu4 0
>    500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
>```
>
>4. Fine, let's install it `sudo apt-get install php5`
>
>```
>Reading state information... Done
>The following extra packages will be installed:
>  libapache2-mod-php5 php5-cli php5-common php5-json php5-readline
>Suggested packages:
>  php-pear php5-user-cache
>The following NEW packages will be installed:
>  libapache2-mod-php5 php5 php5-cli php5-common php5-json php5-readline
>0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
>Need to get 0 B/5,039 kB of archives.
>After this operation, 20.1 MB of additional disk space will be used.
>Do you want to continue? [Y/n] Y
>```
>
>and then:
>
>```
>Setting up php5-common (5.6.11+dfsg-1+deb.sury.org~trusty+1) ...
>dpkg: dependency problems prevent configuration of php5-json:
> php5-json depends on phpapi-20121212; however:
>  Package phpapi-20121212 is not installed.
>
>dpkg: error processing package php5-json (--configure):
> dependency problems - leaving unconfigured
>No apport report written because the error message indicates its a
>followup error from a previous failure.
>           dpkg: dependency problems prevent configuration of php5-cli:
> php5-cli depends on php5-json; however:
>  Package php5-json is not configured yet.
>
>dpkg: error processing package php5-cli (--configure):
> dependency problems - leaving unconfigured
>dpkg: dependency problems prevent configuration of libapache2-mod-php5:
> libapache2-mod-php5 depends on php5-cli; however:
>  Package php5-cli is not configured yet.
> libapache2-mod-php5 depends on php5-json; however:
>  Package php5-json is not configured yet.
>
>dpkg: error processing package libapache2-mod-php5 (--configure):
> dependency problems - leaving unconfigured
>No apport report written because the error message indicates its a
>followup error from a previous failure.
>No apport report written because the error message indicates its a
>followup error from a previous failure.
>               dpkg: dependency problems prevent configuration of php5:
>php5 depends on libapache2-mod-php5 (>=
>5.6.11+dfsg-1+deb.sury.org~trusty+1~) | libapache2-mod-php5filter (>=
>5.6.11+dfsg-1+deb.sury.org~trusty+1~) | php5-cgi (>=
>5.6.11+dfsg-1+deb.sury.org~trusty+1~) | php5-fpm (>=
>5.6.11+dfsg-1+deb.sury.org~trusty+1~); however:
>  Package libapache2-mod-php5 is not configured yet.
>  Package libapache2-mod-php5filter is not installed.
>  Package php5-cgi is not installed.
>  Package php5-fpm is not installed.
>
>dpkg: error processing package php5 (--configure):
> dependency problems - leaving unconfigured
>No apport report written because MaxReports is reached already
>      dpkg: dependency problems prevent configuration of php5-readline:
>php5-readline depends on php5-cli (=
>5.6.11+dfsg-1+deb.sury.org~trusty+1); however:
>  Package php5-cli is not configured yet.
>
>dpkg: error processing package php5-readline (--configure):
> dependency problems - leaving unconfigured
>No apport report written because MaxReports is reached already
>                              Errors were encountered while processing:
> php5-json
> php5-cli
> libapache2-mod-php5
> php5
> php5-readline
>E: Sub-process /usr/bin/dpkg returned an error code (1)
>```
>
>This error appears every time I try to install it. `apt-get -f install`
>doesn't work until I remove ondrej PPA. Then I need to uninstall
>php5-common explicitly. So, why it depends on php5-json which depends
>on api of 2012 year? Is this a common bug or something wrong with my
>Ubuntu installation? And, of course, how to get rid with this error?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/90

-- 
Ondřej Surý

**Comment by tommiv** [comment]
Thanks for fast reply! Here is it:

```
apt-cache policy php5-json
php5-json:
  Installed: (none)
  Candidate: 1.3.7-1+deb.sury.org~trusty+1
  Version table:
     1.3.7-1+deb.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main amd64 Packages
     1.3.7-1+deb.sury.org~trusty+1 0
        100 /var/lib/dpkg/status
     1.3.2-2build1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

**Comment by tommiv** [comment]
UPD: I've purged every package about php5 I found in /var/lib/dpkg/status until
`cat /var/lib/dpkg/status | grep php5` returns nothing, but no luck for me.

**Comment by oerdnj** [comment]
The API dependency is alright, check the php5-common package that provides it:

```
Package: php5-common
Source: php5
Priority: optional
Section: php
Installed-Size: 1182
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: amd64
Version: 5.6.11+dfsg-1+deb.sury.org~trusty+1
Suggests: php5-user-cache
Provides: php5-mhash, phpapi-20131226
Depends: libc6 (>= 2.14), sed (>= 4.1.1-1), psmisc (>= 22.15-1~), lsof, ucf
Conflicts: php5-mhash
Breaks: php-apc (<< 4.0.0), php-crypt-gpg (<< 1.3.2), php5-json (<< 1.3.1-1~), php5-suhosin (<< 0.9.34), php5-xcache (<< 3.1~), php5-xdebug (<< 2.2.2)
Filename: pool/main/p/php5/php5-common_5.6.11+dfsg-1+deb.sury.org~trusty+1_amd64.deb
Size: 709462
MD5sum: 9a4707d269e6b4fd8ba56890f7cf64a5
SHA1: ca0fc32b3a8b55fe128b62ec2eb5c2e8cfcdecba
SHA256: 2cace417acef20882c739ace75345c34df084f27d469d6bc2c105ae611b6d8c9
Description-en: Common files for packages built from the php5 source
 This package contains the documentation and example files relevant to all
 the other packages built from the php5 source.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
Description-md5: 949c39604ee9b19ceaf6491574a70811
```

I think there's something broken *before* the log snippet you sent in the bug report. I have just installed the same set of packages as you did and everything went fine in my trusty chroot.

**Comment by tommiv** [comment]
Actually, I'm able to install php5-common separately

```
sudo apt-get install php5-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  php5-user-cache
The following NEW packages will be installed:
  php5-common
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/709 kB of archives.
After this operation, 1,210 kB of additional disk space will be used.
Selecting previously unselected package php5-common.
(Reading database ... 88115 files and directories currently installed.)
Preparing to unpack .../php5-common_5.6.11+dfsg-1+deb.sury.org~trusty+1_amd64.deb ...
Unpacking php5-common (5.6.11+dfsg-1+deb.sury.org~trusty+1) ...
Setting up php5-common (5.6.11+dfsg-1+deb.sury.org~trusty+1) ...

Creating config file /etc/php5/mods-available/pdo.ini with new version

Creating config file /etc/php5/mods-available/opcache.ini with new version
```

```
cat /var/lib/dpkg/status | grep php5
Package: php5-common
Source: php5
Provides: php5-mhash, phpapi-20131226
Suggests: php5-user-cache
Breaks: php-apc (<< 4.0.0), php-crypt-gpg (<< 1.3.2), php5-json (<< 1.3.1-1~), php5-suhosin (<< 0.9.34), php5-xcache (<< 3.1~), php5-xdebug (<< 2.2.2)
Conflicts: php5-mhash
```

So I don't believe the problem is here. But php package still fails to install. [Here](http://pastebin.com/0QuZeeHj) is the full log, and looks like problem in php5-json package. Since it works for you (and for my friends as well), where should I dig?

**Comment by tommiv** [comment]
Well, I've download the [.deb package](https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6/+build/7632265/+files/php5-json_1.3.7-1%2Bdeb.sury.org~trusty%2B1_amd64.deb) from your PPA and installed it via `dpkg`. Now apt-get able to install php5 package, it done its job without any errors and `php -i` shows recent version (5.6.11-1+deb.sury.org~trusty+1). Looks like this one resolved, excepting I'll need to maintain new versions of php5-json by hand and I still don't get what the hell it was. Thanks for your help.

**Comment by oerdnj** [comment]
It seems like that your php5-json package is odd, the output should look like this:
```
# apt-cache show php5-json=1.3.7-1+deb.sury.org~trusty+1
Package: php5-json
Source: php-json
Priority: optional
Section: php
Installed-Size: 118
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: amd64
Version: 1.3.7-1+deb.sury.org~trusty+1
Replaces: php5-dev (<< 5.5.0~rc1+dfsg-1~)
Depends: libc6 (>= 2.14), libjson-c2 (>= 0.11-3~), phpapi-20131226, ucf
Breaks: php5-common (<< 5.5.0~rc1+dfsg-1~), php5-dev (<< 5.5.0~rc1+dfsg-1~)
Filename: pool/main/p/php-json/php5-json_1.3.7-1+deb.sury.org~trusty+1_amd64.deb
Size: 18634
MD5sum: 298f0acaf37b1657c2c7223e0e26212c
SHA1: 69f48051c2801814c6dc4010a5cf8d089bf54b00
SHA256: 68a0ad661b11a5c0e3031cab5fb5b5ac99c386720810468b27841cbda6db6198
Description-en: JSON module for php5
 This package provides a module for JSON functions in PHP scripts.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
Description-md5: 97f1a74de9875aa65435fb0690a811f9
```

Could you purge php5 everything php5:

```apt-get --purge remove php5*```

then clean the local cache:

```apt-get clean```

and verify it's really empty:

```ls /var/cache/apt/archives```

**Comment by oerdnj** [comment]
It looks like something pulled a wrong version of php5-json. Perhaps you tried 5.5 before and haven't cleaned up the system before switching to 5.6?

**Comment by tommiv** [comment]
@oerdnj Sorry, looks like we posted at the same time. You're right about odd package, and about 5.5 version (I've installed default one from ubuntu repo, before I realize it's 5.5). I've already tried to purge everything about php5-*, but I didn't run `apt-get clean`. Maybe this is the problem. I'll try it.

**Comment by tommiv** [comment]
Yep, I purged php5-json.deb, then removed php5-* via apt-get, made `apt-get clean` and php5 now installs via apt-get with no errors. Thanks for wasting your time!
