### ISSUE TITLE
PHP 7.1 Issues

### ISSUE THREAD

**Issue by Ruok2bu** [oerdnj/deb.sury.org#900]
PHP 7.1 installs fine but when i try to install any of the modules, most of them install with version 7.2 or 7.0 versions instead of 7.1.

**Comment by oerdnj** [comment]
What makes you think so?

**Comment by Ruok2bu** [comment]
# apt-get install php7.1 php7.1-fpm php-mysqlnd-ms php-memcache php-memcached php-bcmath php-mbstring php-bz2 php-zip php-mysql php-curl php-apcu-bc php-apcu

The following NEW packages will be installed:
  php-bcmath php-bz2 php-curl php-mbstring php-zip php7.0-common php7.0-mysql php7.2-bcmath php7.2-bz2 php7.2-common php7.2-curl php7.2-mbstring
  php7.2-zip
