### ISSUE TITLE
php-mysqlnd-ms installs wrong version

### ISSUE THREAD

**Issue by Ruok2bu** [oerdnj/deb.sury.org#902]
I have Php 7.1 installed and when i try installing php-mysqlnd-ms i'm shown this:

root@***************:/root# apt-get install php-mysqlnd-ms
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libphp5.6-embed php5.6-cli php5.6-common php5.6-json php5.6-opcache php5.6-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  libphp5.6-embed php-mysqlnd-ms php5.6-cli php5.6-common php5.6-json php5.6-opcache php5.6-readline
0 upgraded, 7 newly installed, 0 to remove and 2 not upgraded.

**Comment by oerdnj** [comment]
The mysqlnd-ms extension hasn't been updated to PHP 7 by the upstream developer(s).
