### ISSUE TITLE
php-memcached priority to low

### ISSUE THREAD

**Issue by Hufschmidt** [oerdnj/deb.sury.org#903]
See #259

The current release (`3.0.4+2.2.0-1+ubuntu16.04.1+deb.sury.org+1`) is having the same issue again, namely _memcached_ and _msgpack_ having the same priority.

_memcached_ should be changed to priority 25 again, which would also match the the solution used in the debian stretch php-memcached package.

**Comment by oerdnj** [comment]
Could you please run:
```
apt-get -y install debsums
debsums -e -c php-msgpack
debsums -e -c php-memcached
```
and paste the output here?

**Comment by Hufschmidt** [comment]
```bash
$ debsums -e -c php-msgpack
$ debsums -e -c php-memcached
/etc/php/7.0/mods-available/memcached.ini
```

My first thought was that this came from my modification to the priority value to fix the loading-order, so I created a new clean VM with Ubuntu 16.04:

```bash
$ echo 'deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main' > /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list
$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
$ apt-get update
$ apt-get install php-fpm php-memcached
$ apt-cache policy php-memcached
php-memcached:
  Installed:           3.0.4+2.2.0-1+ubuntu16.04.1+deb.sury.org+1
  [...]
$ cat /etc/php/7.0/mods-available/memcached.ini
; priority=25
extension=memcached.so
; You need to install php-igbinary package to use igbinary serializer
; and php-msgpack to use msgpack serializer
memcached.serializer=php
```

So it seems like the initial issue was probably just a leftover from a previous (ubuntu default-package) installation, I'm terribly sorry... :disappointed:

**Comment by oerdnj** [comment]
No problem, you helped to confirm my theory and a way how to debug it - see #913 :).
