### ISSUE TITLE
Patch php-5.3.9-gnusrc.patch cannot be applied to git sources

### ISSUE THREAD

**Issue by DaveRandom** [oerdnj/deb.sury.org#907]
[This patch](https://sources.debian.org/src/php7.2/7.2.4-1/debian/patches/0026-php-5.3.9-gnusrc.patch/) includes a change to zend_language_parser.c, which is not included in the git sources, thus applying it to a raw checkout of the upstream php-src fails, it can only be applied to a release package or after running bison, which makes it difficult to test.

This can be easily fixed by modifying the patch so that it also makes the change in zend_language_parser.y, such that the change will be propagated to zend_language_parser.c when it is generated/regenerated.

**Comment by oerdnj** [comment]
I would be happy to accept such patch.
