### ISSUE TITLE
php7.2-cli should not silently set default PHP version for cli via update-alternatives

### ISSUE THREAD

**Issue by szel** [oerdnj/deb.sury.org#910]
Summary
----------
Please don't change default PHP version system wide when installing php-VERSION packages or warn the user about the behaviour.

To my understanding - when we can install multiple PHP versions in parallel and if they are so nicely packaged and binaries are so nicely placed - it is the duty of the administrator to configure which version should be set as default.

How this bug was found
------------------------
Last week I had the pleasure of installing ```php7.2-cli``` on Debian Jessie where standard ```php5-cli``` is installed too.

Server had PHP applications still using PHP 5.6 (thus the php5 from Debian) and this was the default PHP version when entering ```php``` command in cli.

To my surprise week later I started to receive some weird reports that some of the applications from command line stopped working.

After further inspection I've found that PHP 7.2 was installed by default for ```php``` command system wide and this ```postinst``` script from ```php7.2-cli``` (if this is the correct place where this isset):
```
if [ "$1" = "configure" ]; then
    for binary in php phar phar.phar; do
        update-alternatives \
	    --install /usr/bin/${binary} ${binary} /usr/bin/${binary}7.2 72 \
	    --slave /usr/share/man/man1/${binary}.1.gz ${binary}.1.gz /usr/share/man/man1/${binary}7.2.1.gz
    done
fi
```

This is what is found on my system after installing ```php5-cli``` and ```php7.2-cli```:
```
# update-alternatives --config php
There are 2 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
 *0            /usr/bin/php7.2   72        auto mode
  1            /usr/bin/php5     50        manual mode
  2            /usr/bin/php7.2   72        manual mode
```

**Comment by oerdnj** [comment]
This is expected behaviour.  The alternatives system pick whatever the best version is available.

**Comment by szel** [comment]
I was under the impression that if you provide so many packages with different PHP versions (that are packaged beautifully btw.) that it is reasonable to assume that we are safe to use them.

Installing newer version of PHP (ie.: for preview) should not silently affect system defaults IMHO.

So the only way to disable this behaviour is to set alternatives to manual mode before installing  packages?
