### ISSUE TITLE
mailparse error due to load order of it and mbstring

### ISSUE THREAD

**Issue by geoffr** [oerdnj/deb.sury.org#913]
The mailparse module gives the following warning when it's ordering is the same as mbstring (20) : 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mailparse.so' - /usr/lib/php/20151012/mailparse.so: undefined symbol: mbfl_convert_filter_flush in Unknown on line 0

This is corrected by making its load order a high number than mbstring, e.g. 30, this worked for me in testing.  Could this be done in the postinst when running the php module enabling?

Thank you

**Comment by oerdnj** [comment]
That's strange. The mailparse priority should be `25`. 

Could you please:
* run this and paste the output: `sed -ne "s/^;[[:space:]]*priority[[:space:]]*=[[:space:]]*\([0-9]\+\)[[:space:]]*$/\\1/p; /^[0-9]\+$/q" /etc/php/7.0/mods-available/mailparse.ini`
* paste the contents of `/etc/php/7.0/mods-available/mailparse.ini`
* run `phpdismod mailparse && bash -x phpenmod mailparse` and paste the output here

Thanks.

**Comment by geoffr** [comment]
the output of the 3 above commands:
1) <empty result>
2) [mailparse]
extension = mailparse.so
3) https://pastebin.com/83SCENfB

**Comment by oerdnj** [comment]
Do you use any provisioning to setup the config files?  Because on my side the file looks like this:
```
; priority=25
extension=mailparse.so
```

I don't think the error is in the package, but in your provisioning.

**Comment by oerdnj** [comment]
You can run: `apt-get -y install debsums && debsums -e -c php-mailparse` to confirm

**Comment by geoffr** [comment]
My humblest apologies, that came from an internally built package for mailparse.  We switched to your repository yesterday and this file was left behind.  Sorry for your time and thank you very much for providing the package

**Comment by oerdnj** [comment]
Ah, no worries, this exercise was helpful to me as well, as I know have more questions to ask when similar question pops up helping me to debug similar issues faster.
