### ISSUE TITLE
php-geoip package missing in jessie Packages file

### ISSUE THREAD

**Issue by PirminTapken** [oerdnj/deb.sury.org#917]
Hi,

we spotted that the package `php7.1-geoip` is missing since yesterday.\
While investigating it seems it's been renamed to `php-geoip` but it is missing from the `jessie` `Packages` file so it's not installable anymore.

Best,
Pirmin

**Comment by Sarga** [comment]
Same issue .

**Comment by shcherbak** [comment]
the same problem (

**Comment by billionaire** [comment]
As i understand it, the question is no longer relevant, because geoip legacy database is no longer available for download.
