### ISSUE TITLE
IGBinary and Redis module compiled with --enable-redis-igbinary

### ISSUE THREAD

**Issue by rvelhote** [oerdnj/deb.sury.org#92]
Hey Ondřej,

Is it possible to have a *php5-redis* package in your repository to be compiled with *igbinary* support? Perhaps using a different package named *php5-redis-igbinary*. This would require you also to package *php5-igbinary* which is available in the Ubuntu repositories but not on your own repository.

Thank you ;)

**Comment by oerdnj** [comment]
@rvelhote Does it use igbinary by default or is that just an option you can enable/disable it at the runtime:
```
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE);       // don't serialize data
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);        // use built-in serialize/unserialize
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);   // use igBinary serialize/unserialize
```

And if compiled with igbinary does it need igbinary to be loaded to work?

**Comment by oerdnj** [comment]
`php-redis_2.2.7-355-g799e0bc+2.2.7-3+deb.sury.org~*+1` with igbinary serializer support has just landed in ppa:ondrej/php. I won't be packaging any new stuff into old non-coinstallable PPAs.

**Comment by migue74** [comment]
Sorry to comment on a closed issue, but how can I enable SERIALIZER_IGBINARY in the php-redis package? I have installed php 5.5 from ppa:ondrej/php but it's not available by default. Thanks.

**Comment by oerdnj** [comment]
`$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);   // use igBinary serialize/unserialize` doesn't work? What does mean "not available by default"?

**Comment by migue74** [comment]
No it doesn't, it gives "Undefined class constant SERIALIZER_IGBINARY". I explainned it wrong: I mean igbinary serializer should be available by setting just that line but it's not working. Igbinary extension is also installed and working as session save handler.

**Comment by oerdnj** [comment]
@migue74 Could you be more specific on the version? I am going to check the build logs.

**Comment by migue74** [comment]
PHP Version 5.5.36-2+donate.sury.org~trusty+1
php-igbinary 1.2.1
php-redis 2.2.7-394-g892f928+2.2.7-2+donate.sury.org~trusty+1

**Comment by oerdnj** [comment]
@migue74 Really just php-igbinary *1.2.1*? Is that from package?

**Comment by oerdnj** [comment]
@migue74 Anyway I found the culprint. I haven't re-enabled the igbinary support after I converted the packaging to the new simplified format.

**Comment by migue74** [comment]
Sorry, got the version from phpinfo(). The full string is 1.2.1-10-ge0e66b9+1.2.1+-2+donate.sury.org~trusty+1.

That's nice! I guess you have to update the package to fix it, right? I'm kinda noob about linux server management :(

**Comment by oerdnj** [comment]
Yep, you have to wait a little bit for `php-redis_2.2.7-394-g892f928+2.2.7-3+deb.sury.org~trusty+1` to be built. Give it couple of minutes (it can be up to an hour).

**Comment by migue74** [comment]
Installed and working! Thank you very much!
