### ISSUE TITLE
libpcre3 fails on armhf

### ISSUE THREAD

**Issue by Yannik** [oerdnj/deb.sury.org#927]
This is the log
```

Get:1 https://packages.sury.org/php stretch/main armhf libpcre3 armhf 2:8.41-1+0~20180714171319.1+stretch~1.gbp97d153 [320 kB]
Fetched 320 kB in 1s (181 kB/s)
Reading changelogs... Done
(Reading database ... 40665 files and directories currently installed.)
Preparing to unpack .../libpcre3_2%3a8.41-1+0~20180714171319.1+stretch~1.gbp97d153_armhf.deb ...
Unpacking libpcre3:armhf (2:8.41-1+0~20180714171319.1+stretch~1.gbp97d153) over (2:8.39-3) ...
E: Sub-process /usr/bin/dpkg exited unexpectedly

```

I'd be glad if this could be fixed.
The platform is a raspberry pi zero w.

**Comment by oerdnj** [comment]
There's no error message.  Could you check apt and dpkg logs in `/var/log`?

**Comment by oerdnj** [comment]
So, are you sure the hardware you are using is at least armv-7a?

**Comment by oerdnj** [comment]
Debian armhf (that's what I am using) specifically requires armv7-a:
https://wiki.debian.org/ArmHardFloatPort#Minimum_CPU_.26_FPU

I guess Raspbian does recompile everything for armv6, but that's not what I am using...

**Comment by oerdnj** [comment]
Honestly, I do use Raspbian on all my RPis at home, but the person responsible for making it `armhf` architecture instead of using `armel` wasn't thinking clearly, as obviously it pretends that you can mix packages from Debian stretch with Raspbian stretch, while you clearly can't unless you are on armv7-a.

**Comment by oerdnj** [comment]
JFTR The RPi architecture support is very well described here: https://wiki.debian.org/RaspberryPi
