### ISSUE TITLE
getallheaders() missing with PHP-FPM

### ISSUE THREAD

**Issue by catalin0608** [oerdnj/deb.sury.org#928]
Hello,

I installed php5.6-fpm from this repo: https://packages.sury.org/php/ on Debian 9 , but on my logs it says that getallheaders() is undefined.
i saw here that bug was solved: https://bugs.php.net/bug.php?id=62596

Any change to have it also in https://packages.sury.org/php/ ?

Thanks and Thanks for all your work :).

**Comment by catalin0608** [comment]
On debian 8 , using php5-fpm, the function works.

**Comment by OlafvdSpek** [comment]
> i saw here that bug was solved: https://bugs.php.net/bug.php?id=62596

For what PHP versions?

http://php.net/ChangeLog-5.php#5.6.37 doesn't mention it for 5.6 yet..

**Comment by oerdnj** [comment]
Packages in the deb.sury.org doesn’t have that patch. PHP 5.6 is going away by the end of the year, so you should be migrating to 7.x anyway, and the function is there.
