### ISSUE TITLE
PHP 7.3?

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#929]
Hi Ondřej,

Is 7.2 or 7.3 planned for Buster?

I was also wondering about security support for 7.0. It ends at the
end of this year, but Debian 9 is supported for longer.

**Comment by oerdnj** [comment]
I was hoping for PHP 7.3, but I need to fill release.d.o transition bug yet.

As for PHP 7.0 - same old, same old - cherry-picking security patches. At least it’s PHP 7.x series.

**Comment by OlafvdSpek** [comment]
Has a transition bug been filed yet?

**Comment by oerdnj** [comment]
It wasn't, but it has been filled now for some while.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906643

**Comment by oerdnj** [comment]
I guess I can close this now.
