### ISSUE TITLE
php7.0 packages won't install

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#93]
It seems that php7.0-common is actually 7.0.0~beta2-2+deb.sury.org~wily+1 (good) but all the other packages depend on 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8 (bad), ie;

    php7.0-curl : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed

However beta3 is due out in a few days on 2015-08-06 so any package fixes are probably better left until then but in the mean time the php7.0 packages cannot be installed (not that I can see).

**Comment by oerdnj** [comment]
php7.0-curl is a cruft that will get removed, use just php-curl.

**Comment by markc** [comment]
Sorry to post after a close but it wasn't for just php7.0-curl. All the modules except php7.0-common seem to depend on the older php7.0-common but it's not in the repo as far as I can see...

```
php7.0-common is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-gd : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-imap : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-intl : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-mcrypt : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-mysqlnd : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-pspell : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-readline : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
                   Depends: php7.0-cli (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-sqlite : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
 php7.0-xmlrpc : Depends: php7.0-common (= 7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but 7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by oerdnj** [comment]
Yes, that's all cruft that archive software should have removed. 

O. 

On August 1, 2015 11:30:42 AM GMT+02:00, Mark Constable <notifications@github.com> wrote:
>Sorry to post after a close but it wasn't for just php7.0-curl. All the
>modules except php7.0-common seem to depend on the older php7.0-common
>but it's not in the repo as far as I can see...
>
>```
>php7.0-common is already the newest version.
>Some packages could not be installed. This may mean that you have
>requested an impossible situation or if you are using the unstable
>distribution that some required packages have not yet been created
>or been moved out of Incoming.
>The following information may help to resolve the situation:
>
>The following packages have unmet dependencies:
>php7.0-gd : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-imap : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-intl : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-mcrypt : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-mysqlnd : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-pspell : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-readline : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>Depends: php7.0-cli (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-sqlite : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>php7.0-xmlrpc : Depends: php7.0-common (=
>7.0.0~beta1-1+deb.sury.org~wily+useatyourownrisk8) but
>7.0.0~beta2-2+deb.sury.org~wily+1 is to be installed
>E: Unable to correct problems, you have held broken packages.
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/93#issuecomment-126890516

-- 
Ondřej Surý
