### ISSUE TITLE
libssl size mismatch

### ISSUE THREAD

**Issue by roedie** [oerdnj/deb.sury.org#931]
When upgrading openssl on Debian Jessie I get the following error:

E: Failed to fetch http://packages.sury.org/php/pool/main/o/openssl/libssl1.0.2_1.0.2o-1+0~20180714172610.1+jessie~1.gbpfee2e2_amd64.deb  Size mismatch
E: Failed to fetch http://packages.sury.org/php/pool/main/libz/libzip/libzip5_1.3.2-1+0~20180714172606.1+jessie~1.gbp053542_amd64.deb  Size mismatch
E: Failed to fetch http://packages.sury.org/php/pool/main/o/openssl/openssl_1.0.2o-1+0~20180714172610.1+jessie~1.gbpfee2e2_amd64.deb  Size mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

apt update & apt upgrade --fix-missing doesn't help. Seems like something went wrong with this build.

**Comment by roedie** [comment]
Any way I can help with this one?

**Comment by oerdnj** [comment]
Is there any proxy between you and the server?

**Comment by roedie** [comment]
No, I have a direct connection from this server. No (transparant) proxy or whatsoever.

**Comment by roedie** [comment]
Drat! Skip this one. There is actually an apt proxy in between which there shouldn't be.

Sorry to bother you.
