### ISSUE TITLE
php-redis build fails for amd64 and i386

### ISSUE THREAD

**Issue by DemonTPx** [oerdnj/deb.sury.org#933]
Hi,

A bugfix has been done in php-redis 4.1.1, which I need, but the latest (successfully) built version for Ubuntu xenial / amd64 is 4.0.0. It seems that after 4.0.0 it failed to compile for amd64, i386 and ppc64el on all Ubuntu versions.

See:
- https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/15281795
- https://launchpadlibrarian.net/384262497/buildlog_ubuntu-xenial-amd64.php-redis_4.1.1-1+ubuntu16.04.1+deb.sury.org+1_BUILDING.txt.gz

Somewhere at the end of the build log:
```
configure: exit 1
Died at /usr/share/perl5/Debian/Debhelper/Buildsystem/autoconf.pm line 77.
/usr/share/dh-php/pkg-pecl.mk:60: recipe for target 'configure-7.3-stamp' failed
make[1]: *** [configure-7.3-stamp] Error 255
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
/usr/share/dh-php/pkg-pecl.mk:45: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
--------------------------------------------------------------------------------
Build finished at 20180819-1421

Finished
--------

E: Build failure (dpkg-buildpackage died)
```

Could you please fix the compilation step?

**Comment by oerdnj** [comment]
This has been fixed now.
