### ISSUE TITLE
php5.6 for buster?

### ISSUE THREAD

**Issue by bodqhrohro** [oerdnj/deb.sury.org#934]
Is it possible to build it against libcurl4? I already have a growing upgrade conflict as newer packages are built against libcurl4, but old ones, such as viber and php5-curl, need libcurl3. I was pointed to your repo, but there are php5.6 packages only for jessie and stretch, built against libcurl3, and none for buster.

**Comment by oerdnj** [comment]
dup of #920, #911 and #879
