### ISSUE TITLE
Bind 9.12 on Debian Stretch is failing during execution systemd startup script

### ISSUE THREAD

**Issue by omigg** [oerdnj/deb.sury.org#936]
Bind 9.12 for Debian Stretch is failing in systemd startup script due to /etc/default/bind file is missing during installation.

Log records:
```
systemd[1]: bind.service: Failed to load environment files: No such file or directory
systemd[1]: bind.service: Failed to run 'start' task: No such file or directory
```

**Comment by oerdnj** [comment]
It should be fixed with the latest release. Please reopen if not.
