### ISSUE TITLE
PHP 7.2.10, 7.1.22 and 7.0.32

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#939]
Builds missing from Debian stretch and Ubuntu xenial at least.

Thanks.

**Comment by DavidGoodwin** [comment]
Ditto - these and others have gone AWOL for me - on Debian Stretch : 

 * libapache2-mod-php7.1 
 * php7.1-dev
 * php7.1-cli
 * php7.1-curl
 * php7.1-bcmath
 * php7.1-sqlite3
 * php7.1-opcache
 * php7.1-xml 
....

**Comment by oerdnj** [comment]
See my comment in #941 for ETA...

**Comment by frankangelone** [comment]
@oerdnj I didn't see PHP version 7.0.32 available in the repository,  I wanted to see if the reason I didn't see it there was because of the [comment you left](https://github.com/oerdnj/deb.sury.org/issues/941#issuecomment-420553923)  on issue #941?

**Comment by webaddicto** [comment]
Seems to work fine now, have successfully updated to php 7.0.32:

```
PHP 7.0.32-1+0~20181001133631.6+stretch~1.gbpcd8588 (cli) (built: Oct  1 2018 13:36:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32-1+0~20181001133631.6+stretch~1.gbpcd8588, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by oerdnj** [comment]
The Debian packages are still building and there was some build failure with PHP 5.6 on Ubuntu 16.04 i386, but most of the packages are built now.

**Comment by frankangelone** [comment]
@oerdnj @webaddicto I'm running Ubuntu 14.04.5 LTS and running the following commands trying to update to PHP 7.0.32:

```
sudo apt-get update
sudo apt-get install php7.0
```
I was still listed on version PHP 7.0.6 after running these commands.  I then tried using the following commands instead, but it didn't make a difference: 

```
sudo apt-add-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.0
```
