### ISSUE TITLE
php-imagick not available for php 7.3

### ISSUE THREAD

**Issue by jackdpeterson** [oerdnj/deb.sury.org#940]
It appears that imagick extension is not yet available for PHP 7.3.

**Expected files:**
/etc/php/7.3/mods-available/imagick.ini. 
/usr/lib/php/20180731/imagick.so

**Actual:**
Both the .so and the .ini files are missing for PHP 7.3.

**Also missing**
The symlinked path ;-).

**Comment by oerdnj** [comment]
7.3.0 isn't out of beta and many extensions just doesn't support it. I will start updating extensions around rc1-rc2.
