### ISSUE TITLE
PHP5.6 builds missing from Debian repo

### ISSUE THREAD

**Issue by carlgarner** [oerdnj/deb.sury.org#941]
It appears that all of the PHP5.6 builds have disappeared from the Debian repo.

Could you make these available again please?

```
Err:1 https://packages.sury.org/php stretch/main amd64 php5.6-mbstring amd64 5.6.37-1+0~20180725093819.2+stretch~1.gbp606419
  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php5.6/php5.6-mbstring_5.6.37-1+0~20180725093819.2+stretch~1.gbp606419_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by verschoof** [comment]
I'm not sure if its related, but I cannot find the 7.1 and 7.2 versions anymore..

**Comment by carlgarner** [comment]
7.2 appears to be here https://packages.sury.org/php/pool/main/p/php-defaults/

The Ubuntu PPA still has the 5.6 packages

**Comment by harmen1994** [comment]
> I'm not sure if its related, but I cannot find the 7.1 and 7.2 versions anymore..

Seems to be related since I have this issue also.

**Comment by bdenizar** [comment]
php7.0 not found ! I can't install php7.0-x package anymore. Please fix this.

![image](https://user-images.githubusercontent.com/1056334/45292457-908dcf00-b4f5-11e8-881a-57750e31874d.png)

**Comment by carlgarner** [comment]
> I accidentally purged the whole repository, so all the packages are rebuilding now.

Is the build process complete or are there some still to come? Waiting on the 5.6 builds for Stretch if that's still in progress?

**Comment by asp24** [comment]
Looks like apt repo index broken. 
```
Package: php-intl
Source: php-defaults (62+0~20180910091332.4+stretch~1.gbp62811c)
Version: 1:7.2+62+0~20180910091332.4+stretch~1.gbp62811c
Architecture: all
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 12
Depends: php-common, php7.2-intl
```

but there is no php7.2-intl record in the Packages file.

**Comment by catalin0608** [comment]
Php7.2 is not present for stretch, in repo :(

**Comment by wwags** [comment]
There are PHP 5.6 packages (some from 11:20), but they're not in the 11:15 Packages file

**Comment by oerdnj** [comment]
The progrese can be seen here: https://jenkins.rfc1925.org

It’s still building the base for packages. Extensions will come after that and last will be arm packages.

**Comment by smotesko** [comment]
Thanks for update. `php-redis` is still not available.

**Comment by wwags** [comment]
PHP seems ok now. Thanks.

**Comment by OttoEdler** [comment]
php-redis is still broken

**Comment by smotesko** [comment]
`php-memcache` is also not available.

**Comment by XMLMike** [comment]
Hello, Getting that php-zmq is missing still. 
would it be possible to get an ETA?

**Comment by dmytroboiko** [comment]
php-pear is also not available.

**Comment by oerdnj** [comment]
There are handful packages that are currently broken (probably due unfinished effort to patch them to build with PHP 7.3).

Unfortunately, I am out of normal Internet access and only with phone until 21st September.

I know this is PITA and I am sorry for that (this is classic example of Friday late evening update as I was trying to finish everything before my departure), but there’s nothing I can do until then.

**Comment by JB1985** [comment]
I am waiting for php7.2-redis and php7.2-memcached too. I hope that will be available soon.

**Comment by haagvivi** [comment]
Package php-amqp is not available.

**Comment by andyrooster** [comment]
The php-zmq package is no longer available in the repository. Will this be added back at some point?

**Comment by GodLesZ** [comment]
`php7.1-memcache` seems to not be available anymore. An `apt-get install` auto-selects `memcached` .

**Comment by oerdnj** [comment]
I wasn’t able to pick my MBP from service on Friday, so I’ll go there on Monday. E.g. I will be recovering from PTO and fixing the packages on Monday afternoon (e.g. tomorrow).

**Comment by dhpowrhost** [comment]
Any updates?

**Comment by MatthiasKuehneEllerhold** [comment]
Just fyi: It seems like the bug from #668 resurfaced, because the deb.sury.org is gone.

**Comment by oerdnj** [comment]
php-zmq is building right now and I started commencing the arm64 and armhf builds.  They take longer to build though.

**Comment by JB1985** [comment]
For PHP7.2 still not work memcached and redis. 

PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20170718/redis.so (/usr/lib/php/20170718/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/redis.so.so (/usr/lib/php/20170718/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20170718/memcached.so (/usr/lib/php/20170718/memcached.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/memcached.so.so (/usr/lib/php/20170718/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by MatthiasKuehneEllerhold** [comment]
Do you have "php-igbinary" installed? Is it a dependency of your "php-redis" (See apt-cache show php-redis)?

**Comment by JB1985** [comment]
Yes. 

 apt install php-igbinary
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-igbinary is already the newest version (2.0.1-1).
php-igbinary set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by oerdnj** [comment]
@JB1985 Your architecture please?

**Comment by JB1985** [comment]
Amd64 Debian 9

**Comment by oerdnj** [comment]
And `apt-cache policy php-igbinary` says what?

I can see that php-igbinary has been built successfully:

https://jenkins.rfc1925.org/job/php_php-igbinary-binaries/4/architecture=amd64,distribution=stretch/

**Comment by JB1985** [comment]
OK, now it works. I updated php-igbinary and php-msgpack successfully.

**Comment by claaslange** [comment]
Looks like 4.1.1-1+ubuntu14.04.1+deb.sury.org+1 of php-redis is still missing. It's listed here: https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=trusty but apt only sees the 4.0.0 version:

```
# apt-cache policy php-redis
php-redis:
  Installed: 4.0.0-1+ubuntu14.04.1+deb.sury.org+1
  Candidate: 4.0.0-1+ubuntu14.04.1+deb.sury.org+1
  Version table:
 *** 4.0.0-1+ubuntu14.04.1+deb.sury.org+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```
