### ISSUE TITLE
Explanation of latest php7.1.20 release on debian repository

### ISSUE THREAD

**Issue by retry** [oerdnj/deb.sury.org#944]
Greetings,

There was recently a new release of php 7.1.20 on debian:
(7.1.20-1+0~20180910100532.3+stretch~1.gbp17c613) over (7.1.20-1+0~20180725103315.2+stretch~1.gbpd5b650)

I can't find any explanation of what this new release is about.  Shouldn't this be a 7.1.21 release to catch up to php.net release of 2018-08-17 ?  Any explanation is appreciated.  Further is there a release notes somewhere for new builds so we can read about what the release addresses?

**Comment by todeveni** [comment]
Just a rebuild of packages.

https://github.com/oerdnj/deb.sury.org/issues/941#issuecomment-419864035
