### ISSUE TITLE
php-memcache does not include php5.6 any more?

### ISSUE THREAD

**Issue by dhpowrhost** [oerdnj/deb.sury.org#946]
In late august i installed a server with php5.6 - php7.2 on debian using your repo. Amongst other packages i installed php-memcache and it worked for all php versions.

Today i installed another server, however for php5.6 it seems memcache is not there any more. only for php7.x. Only memcache**d** is available. Is this a bug?

```
root@phhw-161107:~# dpkg --get-selections | grep php-memcache
php-memcache					install
php-memcached					install

root@phhw-161107:~# ls -alh /usr/lib/php/20131226/ | grep memcache
-rw-r--r--  1 root root 100K Sep 10 16:06 memcached.so
```

**Comment by todeveni** [comment]
Tried looking at other issues?
https://github.com/oerdnj/deb.sury.org/issues/941
