### ISSUE TITLE
PHP-FPM unknown entry 'listen.acl_users'

### ISSUE THREAD

**Issue by AnrDaemon** [oerdnj/deb.sury.org#948]
```
# php-fpm5.6 -t
[14-Sep-2018 20:07:13] ERROR: [/etc/php/5.6/fpm/pool.d/ccenter5.6.conf:13] unknown entry 'listen.acl_users'
[14-Sep-2018 20:07:13] ERROR: Unable to include /etc/php/5.6/fpm/pool.d/ccenter5.6.conf from /etc/php/5.6/fpm/php-fpm.conf at line 13
[14-Sep-2018 20:07:13] ERROR: failed to load configuration file '/etc/php/5.6/fpm/php-fpm.conf'
[14-Sep-2018 20:07:13] ERROR: FPM initialization failed
```

`Ubuntu 14.04`
`PHP 5.6.37-1+ubuntu14.04.1+deb.sury.org+1 (fpm-fcgi)`

According to documentation, acl_users is supported since PHP 5.6.5.

**Comment by oerdnj** [comment]
This is not a bug related to packaging. You need to take it to upstream.

**Comment by AnrDaemon** [comment]
How much upstream? >.< Sorry, but I'm confused.

**Comment by oerdnj** [comment]
Like in bugs.php.net

**Comment by apapsch** [comment]
This bug occurs, for example, in PHP 7.3 as well:

```
04-Nov-2020 13:25:32] ERROR: [/etc/php/7.3/fpm/pool.d/www-data.conf:14] unknown entry 'listen.acl_users'
[04-Nov-2020 13:25:32] ERROR: Unable to include /etc/php/7.3/fpm/pool.d/www-data.conf from /etc/php/7.3/fpm/php-fpm.conf at line 14
[04-Nov-2020 13:25:32] ERROR: failed to load configuration file '/etc/php/7.3/fpm/php-fpm.conf'
[04-Nov-2020 13:25:32] ERROR: FPM initialization failed
```

Please build php-fpm with ACL support.

**Comment by vegnuli** [comment]
> FPM needs to be compiled with `--with-fpm-acl` (depends on `libacl1-dev`) for `listen.acl_users` directive to work.

it seems that someone have honor here! thanks .. lest make then a debina bug agains cos debian is the only distro that has this fails.. here maybe will be made the right taks!

**Comment by oerdnj** [comment]
@vegnuli I'll give you the benefit of doubt and I will ignore the personal attacks both here and in Debian BTS. But stop being rude, you will not accomplish anything by attacking the guy doing stuff for free and in his free time.

**Comment by vegnuli** [comment]
hi @oerdnj  thanks.. in advance but here those nice guys arges well made reasons and you answered rude in fact! so its not so nice  for us.. receiving that kind of responses.. inclusivelly @todeveni  nicelly put how to solve it! .. sorry but this time was different.. 

we will waith for your packages.. thanks in advance for your work.. is difficult migrating big projects.. and those pacakge are lifesavers

**Comment by apapsch** [comment]
You are quite assuming here @vegnuli that @oerdnj acted rudely. His two comments in 2018 might just as well have been two quick remarks on a hurried day, which unfortunately mistook the packaging bug as an upstream bug. I'm assuming as well, but that is the benefit of doubt.

As an aside, when I stumbled on the bug, I looked whether I could create a PR, but I didn't find the package sources on GitHub. I guess I would have to work with Debian packaging infrastructure. That's quite involving for a drive-by contribution.

Thanks for picking it up, @oerdnj!

**Comment by oerdnj** [comment]
> You are quite assuming here @vegnuli that @oerdnj acted rudely. His two comments in 2018 might just as well have been two quick remarks on a hurried day, which unfortunately mistook the packaging bug as an upstream bug. I'm assuming as well, but that is the benefit of doubt.

Well, yes, it looked like an upstream bug and this wasn't a feature request. If it was a feature request I would have acted accordingly.

**Comment by oerdnj** [comment]
> As an aside, when I stumbled on the bug, I looked whether I could create a PR, but I didn't find the package sources on GitHub. I guess I would have to work with Debian packaging infrastructure. That's quite involving for a drive-by contribution.

JFTR the packaging sources are located at https://salsa.debian.org/php-team/php and you can probably fork it on GitHub, I would pick up the patch / commit.

**Comment by vegnuli** [comment]
> You are quite assuming here @vegnuli that @oerdnj acted rudely. His two comments in 2018 might just as well have been two quick remarks on a hurried day, which unfortunately mistook the packaging bug as an upstream bug. I'm assuming as well, but that is the benefit of doubt

this is an offtopic comment (respect the issue), so please minimize @apapsch  comment too if my comment is also minimized! No, @apapsch because if you are a leader of a big project and you have a bad mood it means you can answer grotesquely?

actually the best leader I've noticed to handle this kind of situations is ncopa from the alpine project. . he never "blames anything for anything" ... here those people comment nicely that it's not a bug and that kind of answers like "it works for me" is now a constant in free software projects, with the famous argument of "it's a free project", is not the first time @oerdnj 

reporting problems is a job "per se" and we also take the time to kindly explain the situation in a clear way, and this time the solution was provided in passing ... and not having the repository where the fuck was I going to make the proposed change?

**Comment by oerdnj** [comment]
And welcome to the blocklist...

JFTR the packages with the change have been uploaded to Ubuntu and will build on Debian in time...

**Comment by AnrDaemon** [comment]
Finally…
