### ISSUE TITLE
Can't install PHP 7.2 on Debian 9.5 (Stretch)

### ISSUE THREAD

**Issue by KevinSupertramp** [oerdnj/deb.sury.org#950]
Hi,

Thank you for your work!

I can't install PHP 7.2 on Debian 9.5 Stretch (I'm not sure if it's related to the repo being purged?):

> The following packages have unmet dependencies:
>  php7.2 : Depends: libapache2-mod-php7.2 but it is not installable or
>                    php7.2-fpm but it is not installable or
>                    php7.2-cgi but it is not installable
>           Depends: php7.2-common but it is not installable
> E: Unable to correct problems, you have held broken packages.

> apt-cache search php7.2
> php-all-dev - package depending on all supported PHP development packages
> php7.2 - server-side, HTML-embedded scripting language (metapackage)
> php7.2-xsl - XSL module for PHP (dummy)

Thanks a lot!

**Comment by oerdnj** [comment]
Hi, what’s the output of:

apt-cache policy php7.2 php7.2-cli php7.2-common php7.2-fpm 

?

**Comment by KevinSupertramp** [comment]
Hi @oerdnj ,

Here is the output:

> php7.2:
>   Installed: (none)
>   Candidate: 7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35
>   Version table:
>      7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35 500
>         500 https://packages.sury.org/php stretch/main armhf Packages
> php7.2-cli:
>   Installed: (none)
>   Candidate: (none)
>   Version table:
> php7.2-common:
>   Installed: (none)
>   Candidate: (none)
>   Version table:
> php7.2-fpm:
>   Installed: (none)
>   Candidate: (none)
>   Version table:

Many thanks

**Comment by oerdnj** [comment]
Could you please mention the architecture? armhf and arm64 builds haven’t been started yet.

**Comment by KevinSupertramp** [comment]
It's armhf.

Thank you!
