### ISSUE TITLE
PHP 7.1 Debian Stretch broken after upgrade

### ISSUE THREAD

**Issue by james-coder** [oerdnj/deb.sury.org#952]
Unsure if related to https://github.com/oerdnj/deb.sury.org/issues/941 (PHP 7.1 wiped/rebuilt)

I just did an apt-get update / apt-get upgrade on my Debian stretch (using packages.sury.org/php) and it broke my PHP 7.1 install.

I then tried this as a troubleshooting step. It still gives an error:

```
james@www:~$ sudo apt-get remove php-common php7.1 php7.1-xml php7.1-mbstring php7.1-readline php7.1-zip php7.1-mysql php7.1-opcache php7.1-json php7.1-curl php7.1-ldap php7.1-cli php7.1-fpm php7.1-odbc php7.1-common  php7.1-bcmath php7.1-mcrypt php7.1-gd libapache2-mod-php7.1
```
```
james@www:~$ sudo apt-get install php-common php7.1 php7.1-xml php7.1-mbstring php7.1-readline php7.1-zip php7.1-mysql php7.1-opcache php7.1-json php7.1-curl php7.1-ldap php7.1-cli php7.1-fpm php7.1-odbc php7.1-common  php7.1-bcmath php7.1-mcrypt php7.1-gd libapache2-mod-php7.1
```
...(many lines later that all look normal)...
```
Setting up libapache2-mod-php7.1 (7.1.20-1+0~20180910100532.3+stretch~1.gbp17c613) ...
dpkg: error processing package libapache2-mod-php7.1 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 libapache2-mod-php7.1
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The last version of  libapache2-mod-php7.1 (7.1.20-1+0~20180725103315.2+stretch~1.gbpd5b650) was working perfectly. 

Using `apt-rdepends php7.1`, I found that the package `php7.1` is actually the one that requires libapache2-mod-php7.1 to be installed. Using `dpkg -L libapache2-mod-php7.1`, I can't quite figure out what libapache2-mod-php7.1 provides... Even on my old backups, it says it provides `/etc/apache2/mods-available/php7.1.conf`, but no such file exists. (Or even anything close.)

Can I safely ignore that the libapache2-mod-php7.1 package is now broken? Will it ever be cleaned up so that installing php7.1 doesn't show a broken package now?

**Comment by OlafvdSpek** [comment]
> I can't quite figure out what libapache2-mod-php7.1 provides... 

I'd guess it provides integration with Apache.. 
Is there no log indicating why it failed?

**Comment by oerdnj** [comment]
If you don't use apache2 module, why are you installing it?

There must be more information available in your `/var/log/apt/` logs.

**Comment by oerdnj** [comment]
My guess here is that some "smart" provisioning deleted `/etc/apache2/mods-available/php7.1.conf` and now the installation is broken.  I've see too much of this docker madness...
