### ISSUE TITLE
packages.sury.org appears to be down

### ISSUE THREAD

**Issue by viccherubini** [oerdnj/deb.sury.org#953]
Hi,

I tried getting the apt.gpg file from packages.sury.org and it appears to be down:

![screen shot 2018-09-25 at 11 34 32 am](https://user-images.githubusercontent.com/60762/46028742-00d04f00-c0b7-11e8-9889-1ceaee246b65.png)

Is it possible to restart the server or provide an alternative way to get the gpg file? Thank you!

**Comment by rohanrhu** [comment]
yess we need a solution :/

**Comment by codibit** [comment]
Same here, tried from several locations :-/

**Comment by codibit** [comment]
Back online! :)

**Comment by oac-rbeltran** [comment]
Thank you! It's back online!

**Comment by viccherubini** [comment]
Thank you!

**Comment by oerdnj** [comment]
Yep, the server got stuck on `apt-get dist-upgrade` and I had to perform hard restart
