### ISSUE TITLE
No php packages available on debian jessie armh

### ISSUE THREAD

**Issue by phe-move-elevator-de** [oerdnj/deb.sury.org#954]
Since last week, i can't install any type of PHP (7.0/7.1/7.2) from sury. There are only the meta-package available but not any of the depencies.

**apt-get update** doesn't help.
If I try the command **apt-get install php7.0** I get the following error:

**The following packages have unmet dependencies:
 php7.0 : Depends: libapache2-mod-php7.0 but it is not installable or
                   php7.0-fpm but it is not installable or
                   php7.0-cgi but it is not installable
          Depends: php7.0-common but it is not installable
E: Unable to correct problems, you have held broken packages.**

The same with 7.1 or 7.2.

My system is debian jessie on armh (lemaker guitar).

**Comment by oerdnj** [comment]
Dup of #941
