### ISSUE TITLE
PHP 5.6 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by bsidhu009** [oerdnj/deb.sury.org#957]
Dear Surý,

I'm trying to compile php 5.6 from source on Ubuntu 18.04 getting openssl issues
Please give me hints, How you managed to get this compiled sucessfully

If possible Configure Command and If any patches applied to source 

I will really appreciate your precious time

Thanks,

**Comment by bsidhu009** [comment]
https://bugs.php.net/bug.php?id=76621

[2018-07-14 06:34 UTC] requinix@php.net
It seems OpenSSL 1.1.0 has source changes making it incompatible. Try 1.0.2 or 0.9.8.
https://www.openssl.org/source/

I'm wondering, How you managed to compiled it with latest OpenSSL 

Thanks,

**Comment by oerdnj** [comment]
This is a bug tracker and not user support forum. Sorry.
