### ISSUE TITLE
Ubuntu unable to download PHP5.6 

### ISSUE THREAD

**Issue by alogez** [oerdnj/deb.sury.org#958]
Hello,

I try to install php5.6 on Ubuntu Trusty : 

sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
Then 
sudo apt-get update
And finally : 
sudo apt-get install php5.6

I can't manage to download this : 
E: Impossible de récupérer http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php5.6/php5.6-common_5.6.37-1+ubuntu14.04.1+deb.sury.org+1_amd64.deb  Taille incohérente

Does anybody know how to do it?

Thanks in advance.
Alogez.

**Comment by oerdnj** [comment]
I am afraid this is not a right forum to solve your connectivity issues.

The most common problem is broken proxy in the middle.
