### ISSUE TITLE
Missing modules ini's not reinstalled with Dpkg::Options::="--force-confmiss"

### ISSUE THREAD

**Issue by ahmedm** [oerdnj/deb.sury.org#960]
After I did lots of purging and thorough clean up while updating from 16.04 to 18.04
I found out that 99% of installed modules are missing ini files in /etc/php/7.0/mods-available/*

I get messages like:

```
Not replacing deleted config file /etc/php/7.0/mods-available/mcrypt.ini
WARNING: Module mcrypt ini file doesn't exist under /etc/php/7.0/mods-available
```

I used to just use apt --reinstall -o Dpkg::Options::="--force-confmiss" to get all original configurations back but it's not working with this ppa packages
Even after moving config directory to /etc/php.old I got the directory structure back but without mods-available/* ini's

`apt install --reinstall -o Dpkg::Options::="--force-confmiss" php7.0 php7.0-common php7.0-fpm php7.0-curl php7.0-intl php7.0-cli php7.0-json php7.0-gd php7.0-bz2 php7.0-readline php7.0-mbstring php7.0-mysql php7.0-zip php7.0-xsl php7.0-xml php7.0-geoip php7.0-dev php7.0-opcache php7.0-imap php7.0-curl php7.0-intl php7.0-curl php7.0-cli php7.0-gd php7.0-imagick php7.0-recode php7.0-tidy php7.0-xmlrpc`

good thing I had some backups to get things up and running again

**Comment by ahmedm** [comment]
I had to convince the deb packages it's a fresh install to get all configs created

```
rm -rf /var/lib/ucf/cache/:etc:php*
rm -rf /var/lib/php 
rm -rf /usr/lib/php
```

**Comment by oerdnj** [comment]
You did lots of purging and cleanup, and you complain that stuff got cleaned up?

Your bug report is too vague to take any action...

**Comment by ahmedm** [comment]
I'm not complaining at all :D I'm just reporting that missing configuration are not reinstalled even with Dpkg::Options::="--force-confmiss" that's all

anyway I got everything back in order
