### ISSUE TITLE
Segmentation fault with ssh2.sftp streams in php 7.1

### ISSUE THREAD

**Issue by forsdahl** [oerdnj/deb.sury.org#961]
With latest updated packages from deb.sury.org for debian stretch, php 7.1 segfaults when using ssh2 streams.
The particular use case is using composer with private packages using satis over ssh2, which makes composer segfault when using php 7.1. The problem is probably in the php-ssh2 library, and can be reproduced easily when using ssh2.sftp-streams with file_get_contents (which composer seems to be doing) with php 7.1. With php 5.6 (also from deb.sury.org) the same code works. The following code can be used for testing:
```
$context = stream_context_create(array(
    'ssh2' => array(
        "username" => "username",
        "password" => "password"
    )
));
$content = file_get_contents("ssh2.sftp://exampleserver.com/path/to/file", false, $context);
echo $content;
```

**Comment by oerdnj** [comment]
This has been fixed in php-ssh2 1.3
