### ISSUE TITLE
LMDB support in PHP 7.2+ ?

### ISSUE THREAD

**Issue by stephenreay** [oerdnj/deb.sury.org#962]
As of PHP 7.2, the `dba` extension supports LMDB (https://symas.com/lmdb), however it doesn't seem to be enabled in these builds (i.e. using `--with-lmdb` configure option).

Can this be added please?

**Comment by oerdnj** [comment]
This sounds reasonable. I'll look into it.

**Comment by stephenreay** [comment]
Thankyou!

**Comment by oerdnj** [comment]
Enabled, and it will be included in the next update.
