### ISSUE TITLE
PHP 7.1.23, 7.2.11, 7.3.0RC3

### ISSUE THREAD

**Issue by todeveni** [oerdnj/deb.sury.org#964]
New PHP versions available.

**Comment by nuxwin** [comment]
@todeveni 

As far I known, their is an automatic watching for new releases. @oerdnj need time to refresh patches (if needed).

**Comment by todeveni** [comment]
In that case the automatic release watcher could create a tracking issue, try an automated build and submit results to that issue and close if build && some tests were successful.

#241 #759

**Comment by oerdnj** [comment]
They often require manual intervention to adjust the `debian/patches`.  Usually, when there are patches cherry-picked from git to fix specific patches.  So, as the releases mature they becomes more stable, but in the beginning there's a usually lot of manual intervention.

**Comment by oerdnj** [comment]
And while the manual bump is a work that could be done in a chunks of spare time, writing an automation would require more continuous continuous chunk then 5 minutes here and there.

**Comment by nuxwin** [comment]
@oerdnj Yes, I underdant... I've the same problem with all my debian patches for self-compiled PHP versions... I've a script able to automate the build process but often, I need refresh the patches...

**Comment by todeveni** [comment]
@oerdnj Have you ever thought about open sourcing the actual packaging/build-tree?
AFAIK that's behind closed doors with your own infrastructure for building/Jenkins/deb repo etc.

**Comment by oerdnj** [comment]
@todeveni You mean this?
https://salsa.debian.org/php-team/php

**Comment by oerdnj** [comment]
And the Jenkins for Debian packages is here: https://jenkins.rfc1925.org

I do have a crude custom script for Ubuntu PPAs, but that's more convenience thing than something you can't live without.

**Comment by todeveni** [comment]
Yes, that 🙂
I was just looking under your Github account and saw something pretty old under `pkg-php`.

**Comment by oerdnj** [comment]
I should probably delete that - the Vcs-* links in `debian/control` should point the the correct address.

**Comment by oerdnj** [comment]
JFTR PHP 7.1 and 7.2 could have been updated without manual intervention[*], but PHP 7.3 is:
```
$ gbp-pq-reexport
gbp:info: Dropped branch 'patch-queue/master-7.3'.
gbp:info: Trying to apply patches at '48bc56f6ec262479ff2fa042ef02414107807edf'
gbp:warning: Patch 0048-Allow-to-disable-pcre.jit-when-system-library-is-use.patch failed to apply, retrying with whitespace fixup
gbp:error: Failed to apply '/home/ondrej/Projects/pkg-php/php7.3/debian/patches/0048-Allow-to-disable-pcre.jit-when-system-library-is-use.patch': Error running git apply: error: patch failed: ext/pcre/config0.m4:47
error: ext/pcre/config0.m4: patch does not apply
gbp:error: Couldn't apply patches
```

The `debian/changelog` would just contain spurious entries, but I can workaround this with discipline of using `Gbp-Dch: no` in commit message.

**Comment by oerdnj** [comment]
All new releases are building now.
