### ISSUE TITLE
PHP RC releases - Missing extra version

### ISSUE THREAD

**Issue by nuxwin** [oerdnj/deb.sury.org#965]
@oerdnj 

Good morning,

Could it be possible to provide extra version also for the RC releases? Right now, your PHP 7.3 package doesn't provide it through CLI:

Current behavior:
```
root@jessie:/usr/local/src# php7.3 -v
PHP 7.3.0RC2 (cli) (built: Oct  1 2018 14:58:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0RC2, Copyright (c) 1999-2018, by Zend Technologies
```

Expected behavior:
```
root@jessie:/usr/local/src# php7.3 -v
PHP 7.3.0RC2-1+0~20181001133624.14+jessie~1.gbpa86ce3 (cli) (built: Oct  1 2018 14:58:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0RC2, Copyright (c) 1999-2018, by Zend Technologies
```

Why such request? For our control panel, we provide a plugin that make possible to provide various PHP versions to customers. Those versions can be either self-compiled PHP versions or packaged PHP versions. Our backend make use of the extra version to differentiate packaged versions from self compiled versions.

https://gist.github.com/nuxwin/5cb72980ad81680521db5e445587af22

Thank you.

**Comment by oerdnj** [comment]
Can you send a patch? :)

**Comment by nuxwin** [comment]
@oerdnj 

Of course. I need first figure out why it is not added... Because as I can see, you have the insertion in the prepared-stamp target as for other builds...

**Comment by oerdnj** [comment]
7.3.0 is out, so this will be non-issue for some time.  When there's a patch, feel free to reopen the issue.
