### ISSUE TITLE
Typo in php5.6 source package - php7.0-common instead of php5.6-common (NEWS file)

### ISSUE THREAD

**Issue by nuxwin** [oerdnj/deb.sury.org#967]
While I'm comfortable with github, I don't know how and where send PR for your Debian VCS...

![typo](https://user-images.githubusercontent.com/125594/46920273-005b1200-cfec-11e8-8fbb-00ae9f5b4acd.png)

**Comment by oerdnj** [comment]
I fixed that in the git.  And could you please paste text and not screenshot next time?
