### ISSUE TITLE
Wrongfully uploaded php-defaults from Debian unstable built extensions only for PHP 7.3

### ISSUE THREAD

**Issue by jreason** [oerdnj/deb.sury.org#968]
Hi,

This has happened within the last few hours as my build this morning was fine.

Extracts from build log:

RUN apt-get update && apt-get install -y software-properties-common && LC_ALL=C.UTF-8 add-apt-repository -y -u ppa:ondrej/php && apt-get update && apt-get install -y curl imagemagick nano libapache2-mod-php7.2 php7.2 php7.2-common php7.2-curl php7.2-gd php7.2-mbstring php7.2-mysql php7.2-simplexml php7.2-zip php-imagick php-gettext wget

...

[91mgpg: keyring `/tmp/tmp4dap4slw/secring.gpg' created
[0m[91mgpg: keyring `/tmp/tmp4dap4slw/pubring.gpg' created
[0m[91mgpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
[0m[91mgpg: /tmp/tmp4dap4slw/trustdb.gpg: trustdb created
[0m[91mgpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg: imported: 1 (RSA: 1)
[0mOK
Hit:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
apache2 apache2-bin apache2-data apache2-utils fontconfig fontconfig-config
fonts-dejavu-core ghostscript gsfonts hicolor-icon-theme ifupdown
imagemagick-6.q16 imagemagick-common iproute2 isc-dhcp-client
isc-dhcp-common libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
libargon2-0 libatm1 libavahi-client3 libavahi-common-data libavahi-common3
libbsd0 libcairo2 libcroco3 libcups2 libcupsfilters1 libcupsimage2 libcurl3
libdatrie1 libdjvulibre-text libdjvulibre21 libdns-export162 libedit2
libfftw3-double3 libfontconfig1 libfreetype6 libgd3 libgdbm3
libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgomp1 libgraphite2-3 libgs9
libgs9-common libharfbuzz0b libijs-0.35 libilmbase12 libisc-export160
libjbig0 libjbig2dec0 libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl7
liblua5.1-0 libmagickcore-6.q16-2 libmagickcore-6.q16-2-extra
libmagickwand-6.q16-2 libmnl0 libnetpbm10 libopenexr22 libpango-1.0-0
libpangocairo-1.0-0 libpangoft2-1.0-0 libpaper-utils libpaper1 libpcre2-8-0
libpcre3 libperl5.22 libpixman-1-0 libpng12-0 librsvg2-2 librsvg2-common
libsodium23 libssl1.1 libthai-data libthai0 libtiff5 libwebp6 libwmf0.2-7
libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6
libxext6 libxpm4 libxrender1 libxslt1.1 libxtables11 libzip5 netbase netpbm
perl perl-modules-5.22 php-cli php-common php-pear **php7.2-cli php7.2-json
php7.2-opcache php7.2-readline php7.3-cli php7.3-common php7.3-json
php7.3-opcache php7.3-readline** poppler-data psmisc rename ssl-cert
ttf-dejavu-core tzdata

....

Setting up php-common (1:66+ubuntu16.04.1+deb.sury.org+1) ...
Setting up php7.2-common (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/calendar.ini with new version

Creating config file /etc/php/7.2/mods-available/ctype.ini with new version

Creating config file /etc/php/7.2/mods-available/exif.ini with new version

Creating config file /etc/php/7.2/mods-available/fileinfo.ini with new version

Creating config file /etc/php/7.2/mods-available/ftp.ini with new version

Creating config file /etc/php/7.2/mods-available/gettext.ini with new version

Creating config file /etc/php/7.2/mods-available/iconv.ini with new version

Creating config file /etc/php/7.2/mods-available/pdo.ini with new version

Creating config file /etc/php/7.2/mods-available/phar.ini with new version

Creating config file /etc/php/7.2/mods-available/posix.ini with new version

Creating config file /etc/php/7.2/mods-available/shmop.ini with new version

Creating config file /etc/php/7.2/mods-available/sockets.ini with new version

Creating config file /etc/php/7.2/mods-available/sysvmsg.ini with new version

Creating config file /etc/php/7.2/mods-available/sysvsem.ini with new version

Creating config file /etc/php/7.2/mods-available/sysvshm.ini with new version

Creating config file /etc/php/7.2/mods-available/tokenizer.ini with new version
Setting up php7.2-json (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/json.ini with new version
Setting up php7.2-opcache (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/opcache.ini with new version
Setting up php7.2-readline (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/readline.ini with new version
Setting up libargon2-0:amd64 (0~20161029-1+ubuntu16.04.1+deb.sury.org+1) ...
Setting up libsodium23:amd64 (1.0.16-2+ubuntu16.04.1+deb.sury.org+3) ...
Setting up php7.2-cli (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...
update-alternatives: using /usr/bin/php7.2 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar7.2 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: using /usr/bin/phar.phar7.2 to provide /usr/bin/phar.phar (phar.phar) in auto mode

Creating config file /etc/php/7.2/cli/php.ini with new version
Setting up libapache2-mod-php7.2 (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/apache2/php.ini with new version
Module mpm_event disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
apache2_invoke: Enable module php7.2
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up libpixman-1-0:amd64 (0.33.6-1) ...
Setting up libxcb-render0:amd64 (1.11.1-1ubuntu1) ...
Setting up libxcb-shm0:amd64 (1.11.1-1ubuntu1) ...
Setting up libxrender1:amd64 (1:0.9.9-0ubuntu1) ...
Setting up libcairo2:amd64 (1.14.6-1) ...
Setting up libcroco3:amd64 (0.6.11-1) ...
Setting up libcurl3:amd64 (7.47.0-1ubuntu2.9) ...
Setting up libdatrie1:amd64 (0.2.10-2) ...
Setting up libdjvulibre-text (3.5.27.1-5) ...
Setting up libdjvulibre21:amd64 (3.5.27.1-5) ...
Setting up libwebp6:amd64 (0.6.0-4+ubuntu16.04.1+deb.sury.org+1) ...
Setting up libxpm4:amd64 (1:3.5.11-1ubuntu0.16.04.1) ...
Setting up libgd3:amd64 (2.2.5-4+ubuntu16.04.1+deb.sury.org+2) ...
Setting up libgdk-pixbuf2.0-common (2.32.2-1ubuntu1.5) ...
Setting up libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.5) ...
Setting up libgraphite2-3:amd64 (1.3.10-0ubuntu0.16.04.1) ...
Setting up libharfbuzz0b:amd64 (1.0.1-1ubuntu0.1) ...
Setting up libilmbase12:amd64 (2.2.0-11ubuntu2) ...
Setting up libopenexr22:amd64 (2.2.0-10ubuntu2) ...
Setting up libthai-data (0.1.24-2) ...
Setting up libthai0:amd64 (0.1.24-2) ...
Setting up libpango-1.0-0:amd64 (1.38.1-1) ...
Setting up libpangoft2-1.0-0:amd64 (1.38.1-1) ...
Setting up libpangocairo-1.0-0:amd64 (1.38.1-1) ...
Setting up librsvg2-2:amd64 (2.40.13-3) ...
Setting up libwmf0.2-7:amd64 (0.2.8.4-10.5ubuntu1) ...
Setting up libmagickcore-6.q16-2-extra:amd64 (8:6.8.9.9-7ubuntu5.13) ...
Setting up libnetpbm10 (2:10.0-15.3) ...
Setting up libpaper-utils (1.1.24+nmu4ubuntu1) ...
Setting up libpcre2-8-0:amd64 (10.31-3+ubuntu16.04.1+deb.sury.org+1) ...
Setting up librsvg2-common:amd64 (2.40.13-3) ...
Setting up libxslt1.1:amd64 (1.1.28-2.1ubuntu0.1) ...
Setting up libzip5:amd64 (1.3.2-1+ubuntu16.04.1+deb.sury.org+1) ...
Setting up netpbm (2:10.0-15.3) ...
Setting up php7.3-common (7.3.0~rc3-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.3/mods-available/calendar.ini with new version

Creating config file /etc/php/7.3/mods-available/ctype.ini with new version

Creating config file /etc/php/7.3/mods-available/exif.ini with new version

Creating config file /etc/php/7.3/mods-available/fileinfo.ini with new version

Creating config file /etc/php/7.3/mods-available/ftp.ini with new version

Creating config file /etc/php/7.3/mods-available/gettext.ini with new version

Creating config file /etc/php/7.3/mods-available/iconv.ini with new version

Creating config file /etc/php/7.3/mods-available/pdo.ini with new version

Creating config file /etc/php/7.3/mods-available/phar.ini with new version

Creating config file /etc/php/7.3/mods-available/posix.ini with new version

Creating config file /etc/php/7.3/mods-available/shmop.ini with new version

Creating config file /etc/php/7.3/mods-available/sockets.ini with new version

Creating config file /etc/php/7.3/mods-available/sysvmsg.ini with new version

Creating config file /etc/php/7.3/mods-available/sysvsem.ini with new version

Creating config file /etc/php/7.3/mods-available/sysvshm.ini with new version

Creating config file /etc/php/7.3/mods-available/tokenizer.ini with new version
Setting up php7.3-json (7.3.0~rc3-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.3/mods-available/json.ini with new version
Setting up php7.3-opcache (7.3.0~rc3-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.3/mods-available/opcache.ini with new version
Setting up php7.3-readline (7.3.0~rc3-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.3/mods-available/readline.ini with new version
Setting up php7.3-cli (7.3.0~rc3-1+ubuntu16.04.1+deb.sury.org+1) ...
update-alternatives: using /usr/bin/php7.3 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar7.3 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: using /usr/bin/phar.phar7.3 to provide /usr/bin/phar.phar (phar.phar) in auto mode

Creating config file /etc/php/7.3/cli/php.ini with new version
Setting up php-cli (1:7.3+66+ubuntu16.04.1+deb.sury.org+1) ...
Setting up php7.2-xml (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/dom.ini with new version

Creating config file /etc/php/7.2/mods-available/simplexml.ini with new version

Creating config file /etc/php/7.2/mods-available/wddx.ini with new version

Creating config file /etc/php/7.2/mods-available/xml.ini with new version

Creating config file /etc/php/7.2/mods-available/xmlreader.ini with new version

Creating config file /etc/php/7.2/mods-available/xmlwriter.ini with new version

Creating config file /etc/php/7.2/mods-available/xsl.ini with new version
Setting up php-pear (1:1.10.6+submodules+notgz-1+ubuntu16.04.1+deb.sury.org+1) ...
Setting up php-gettext (1.0.11-2+deb.sury.org~xenial+1) ...
Setting up php-imagick (3.4.3-3+ubuntu16.04.1+deb.sury.org+1) ...
Setting up php7.2 (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...
Setting up php7.2-curl (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/curl.ini with new version
Setting up php7.2-gd (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/gd.ini with new version
Setting up php7.2-mbstring (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/mbstring.ini with new version
Setting up php7.2-mysql (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/mysqlnd.ini with new version

Creating config file /etc/php/7.2/mods-available/mysqli.ini with new version

Creating config file /etc/php/7.2/mods-available/pdo_mysql.ini with new version
Setting up php7.2-zip (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.2/mods-available/zip.ini with new version
Setting up rename (0.20-4) ...
update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
Setting up ssl-cert (1.0.37) ...
Setting up ttf-dejavu-core (2.35-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.4) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.5) ...
Processing triggers for libapache2-mod-php7.2 (7.2.11-1+ubuntu16.04.1+deb.sury.org+1) ...

**Comment by lobsterdore** [comment]
I am seeing this for 7.0 as well, installing php7.0-dev brings in borked bits of 7.3 and results in PECL being unusable, I've noticed this for the php7.0-apcu package as well.

**Comment by gruberro** [comment]
We're having the same issue for our `7.2` packages.

**Comment by rmarchei** [comment]
it seems lots of packages right now don't have PHP <7.3 support, i.e: php-apcu

current version `5.1.12+4.0.11-1+ubuntu18.04.1+deb.sury.org+2`:
```
# dpkg-query -L php-apcu
/.
/etc
/etc/php
/etc/php/7.3
/etc/php/7.3/mods-available
/etc/php/7.3/mods-available/apcu.ini
/usr
/usr/include
/usr/include/php
/usr/include/php/20180731
/usr/include/php/20180731/ext
/usr/include/php/20180731/ext/apcu
/usr/include/php/20180731/ext/apcu/apc.h
/usr/include/php/20180731/ext/apcu/apc_api.h
/usr/include/php/20180731/ext/apcu/apc_arginfo.h
/usr/include/php/20180731/ext/apcu/apc_cache.h
/usr/include/php/20180731/ext/apcu/apc_cache_api.h
/usr/include/php/20180731/ext/apcu/apc_globals.h
/usr/include/php/20180731/ext/apcu/apc_iterator.h
/usr/include/php/20180731/ext/apcu/apc_lock.h
/usr/include/php/20180731/ext/apcu/apc_lock_api.h
/usr/include/php/20180731/ext/apcu/apc_pool.h
/usr/include/php/20180731/ext/apcu/apc_pool_api.h
/usr/include/php/20180731/ext/apcu/apc_serializer.h
/usr/include/php/20180731/ext/apcu/apc_sma.h
/usr/include/php/20180731/ext/apcu/apc_sma_api.h
/usr/include/php/20180731/ext/apcu/apc_stack.h
/usr/include/php/20180731/ext/apcu/php_apc.h
/usr/lib
/usr/lib/php
/usr/lib/php/20180731
/usr/lib/php/20180731/apcu.so
/usr/share
/usr/share/doc
/usr/share/doc/php-apcu
/usr/share/doc/php-apcu/README.Debian
/usr/share/doc/php-apcu/changelog.Debian.gz
/usr/share/doc/php-apcu/copyright
```

Previous version `5.1.11+4.0.11-1+ubuntu18.04.1+deb.sury.org+1`:
```
/.
/etc
/etc/php
/etc/php/5.6
/etc/php/5.6/mods-available
/etc/php/5.6/mods-available/apcu.ini
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/apcu.ini
/etc/php/7.1
/etc/php/7.1/mods-available
/etc/php/7.1/mods-available/apcu.ini
/etc/php/7.2
/etc/php/7.2/mods-available
/etc/php/7.2/mods-available/apcu.ini
/usr
/usr/include
/usr/include/php
/usr/include/php/20131226
/usr/include/php/20131226/ext
/usr/include/php/20131226/ext/apcu
/usr/include/php/20131226/ext/apcu/apc.h
/usr/include/php/20131226/ext/apcu/apc_api.h
/usr/include/php/20131226/ext/apcu/apc_bin_api.h
/usr/include/php/20131226/ext/apcu/apc_cache_api.h
/usr/include/php/20131226/ext/apcu/apc_lock_api.h
/usr/include/php/20131226/ext/apcu/apc_pool_api.h
/usr/include/php/20131226/ext/apcu/apc_serializer.h
/usr/include/php/20131226/ext/apcu/apc_sma_api.h
/usr/include/php/20151012
/usr/include/php/20151012/ext
/usr/include/php/20151012/ext/apcu
/usr/include/php/20151012/ext/apcu/apc.h
/usr/include/php/20151012/ext/apcu/apc_api.h
/usr/include/php/20151012/ext/apcu/apc_arginfo.h
/usr/include/php/20151012/ext/apcu/apc_cache.h
/usr/include/php/20151012/ext/apcu/apc_cache_api.h
/usr/include/php/20151012/ext/apcu/apc_globals.h
/usr/include/php/20151012/ext/apcu/apc_iterator.h
/usr/include/php/20151012/ext/apcu/apc_lock.h
/usr/include/php/20151012/ext/apcu/apc_lock_api.h
/usr/include/php/20151012/ext/apcu/apc_pool.h
/usr/include/php/20151012/ext/apcu/apc_pool_api.h
/usr/include/php/20151012/ext/apcu/apc_serializer.h
/usr/include/php/20151012/ext/apcu/apc_sma.h
/usr/include/php/20151012/ext/apcu/apc_sma_api.h
/usr/include/php/20151012/ext/apcu/apc_stack.h
/usr/include/php/20151012/ext/apcu/php_apc.h
/usr/include/php/20160303
/usr/include/php/20160303/ext
/usr/include/php/20160303/ext/apcu
/usr/include/php/20160303/ext/apcu/apc.h
/usr/include/php/20160303/ext/apcu/apc_api.h
/usr/include/php/20160303/ext/apcu/apc_arginfo.h
/usr/include/php/20160303/ext/apcu/apc_cache.h
/usr/include/php/20160303/ext/apcu/apc_cache_api.h
/usr/include/php/20160303/ext/apcu/apc_globals.h
/usr/include/php/20160303/ext/apcu/apc_iterator.h
/usr/include/php/20160303/ext/apcu/apc_lock.h
/usr/include/php/20160303/ext/apcu/apc_lock_api.h
/usr/include/php/20160303/ext/apcu/apc_pool.h
/usr/include/php/20160303/ext/apcu/apc_pool_api.h
/usr/include/php/20160303/ext/apcu/apc_serializer.h
/usr/include/php/20160303/ext/apcu/apc_sma.h
/usr/include/php/20160303/ext/apcu/apc_sma_api.h
/usr/include/php/20160303/ext/apcu/apc_stack.h
/usr/include/php/20160303/ext/apcu/php_apc.h
/usr/include/php/20170718
/usr/include/php/20170718/ext
/usr/include/php/20170718/ext/apcu
/usr/include/php/20170718/ext/apcu/apc.h
/usr/include/php/20170718/ext/apcu/apc_api.h
/usr/include/php/20170718/ext/apcu/apc_arginfo.h
/usr/include/php/20170718/ext/apcu/apc_cache.h
/usr/include/php/20170718/ext/apcu/apc_cache_api.h
/usr/include/php/20170718/ext/apcu/apc_globals.h
/usr/include/php/20170718/ext/apcu/apc_iterator.h
/usr/include/php/20170718/ext/apcu/apc_lock.h
/usr/include/php/20170718/ext/apcu/apc_lock_api.h
/usr/include/php/20170718/ext/apcu/apc_pool.h
/usr/include/php/20170718/ext/apcu/apc_pool_api.h
/usr/include/php/20170718/ext/apcu/apc_serializer.h
/usr/include/php/20170718/ext/apcu/apc_sma.h
/usr/include/php/20170718/ext/apcu/apc_sma_api.h
/usr/include/php/20170718/ext/apcu/apc_stack.h
/usr/include/php/20170718/ext/apcu/php_apc.h
/usr/lib
/usr/lib/php
/usr/lib/php/20131226
/usr/lib/php/20131226/apcu.so
/usr/lib/php/20151012
/usr/lib/php/20151012/apcu.so
/usr/lib/php/20160303
/usr/lib/php/20160303/apcu.so
/usr/lib/php/20170718
/usr/lib/php/20170718/apcu.so
/usr/share
/usr/share/doc
/usr/share/doc/php-apcu
/usr/share/doc/php-apcu/README.Debian
/usr/share/doc/php-apcu/changelog.Debian.gz
/usr/share/doc/php-apcu/copyright
```

**Comment by acejam** [comment]
I'm also seeing this, trying to install php7.1 packages.

**Comment by rbrecht** [comment]
Got the same problems with:
sudo apt-get install -y php7.2 php7.2-curl php7.2-zip php7.2-intl php7.2-xml php-memcached php7.2-fpm php7.2-opcache php-mongodb

since there is no version for php7.2-memcached and php7.2-mongodb our deployment is broken

**Comment by oestoer** [comment]
Same with PHP versions 5.6-7.2 on Ubuntu 16.04 (Xenial)

**Comment by mbfdias** [comment]
> Since the last published version of the php-igbinary package, the package no longer provides for older/other PHP versions.
> 
> Before
> 
> ```
> Package: php-igbinary
> Version: 2.0.7-1+ubuntu16.04.1+deb.sury.org+1
> Priority: optional
> Section: php
> Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
> Installed-Size: 656 kB
> Provides: php5.6-igbinary, php7.0-igbinary, php7.1-igbinary, php7.2-igbinary, php7.3-igbinary
> Depends: php-common (>= 1:7.0+33~), phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012 | phpapi-20131226, libc6 (>= 2.14)
> Download-Size: 101 kB
> APT-Manual-Installed: no
> APT-Sources: http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
> Description: igbinary PHP serializer
>  Igbinary is a drop in replacement for the standard PHP serializer.
>  Instead of time and space consuming textual representation, igbinary
>  stores PHP data structures in a compact binary form. Savings are
>  significant when using memcached or similar memory based storages for
>  serialized data.
> ```
> After
> 
> ```
> Package: php-igbinary
> Version: 2.0.7-1+ubuntu16.04.1+deb.sury.org+2
> Priority: optional
> Section: php
> Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
> Installed-Size: 167 kB
> Provides: php7.3-igbinary
> Depends: php-common (>= 1:7.0+33~), phpapi-20180731, libc6 (>= 2.14)
> Download-Size: 45.5 kB
> APT-Sources: http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
> Description: igbinary PHP serializer
>  Igbinary is a drop in replacement for the standard PHP serializer.
>  Instead of time and space consuming textual representation, igbinary
>  stores PHP data structures in a compact binary form. Savings are
>  significant when using memcached or similar memory based storages for
>  serialized data.
> 
> This renders the use of older PHP version useless for us (since we use packages that rely on this one).
> ```

same for php-igbinary php-memcached php-msgpack php-xml

**Comment by mareksokol** [comment]
Hey, same issue occurs when trying to install `php-apcu` - parts of php7.3 going to be installed, also package `php7.1-apcu` disappeared

**Comment by oerdnj** [comment]
I uploaded a version of `php-defaults` meant for Debian unstable that makes PHP 7.3 the only supported and default version to the PPA.
Unfortunately, at the same time, I added support for PHP 7.3 to most of the extensions, so instead of failing the extensions have built correctly (except `libvirt-php`, `php-phalcon`, `php-mailparse` and `tideways` extensions).

That said, the good news are that most packages had been fixed and PHP 7.3 is now fully supported (except the files mentioned above) by this repository.

**Comment by acejam** [comment]
@oerdnj Does this mean PHP 7.1 is no longer supported by your PPA? This is going to break a lot of projects for people.

**Comment by oerdnj** [comment]
> @oerdnj Does this mean PHP 7.1 is no longer supported by your PPA? This is going to break a lot of projects for people.

No, I never said that.  PHP 5.6, 7.0, 7.1, 7.2 and 7.3 are supported.  PHP 5.6 and 7.0 will go away some time after the upstream EOLs them.

**Comment by acejam** [comment]
@oerdnj Apologies, I missed the word "unstable".

> I uploaded a version of php-defaults meant for Debian unstable that makes PHP 7.3 the only supported and default version to the PPA.

**Comment by lobsterdore** [comment]
@oerdnj thanks for fixing 👍

**Comment by oerdnj** [comment]
Also I wanted to say sorry for the breakage. I did a great deal of hacking yesterday to fix errors related to cleaning up the `/etc/php/` and `/var/lib/php/` directories and things got mixed up.

**Comment by pascalschoeni** [comment]
@oerdnj thanks a lot 👍
