### ISSUE TITLE
Current php 5.6 version has forced-installed php-cli 7.3.RC

### ISSUE THREAD

**Issue by mpalourdio** [oerdnj/deb.sury.org#969]
Hello,

Today, apt-updating on my work PC (ubuntu 16.04 based), php 7.3RC cli & co installed "themselves".
After uninstalling the 7.3RC packages, I was forced to uninstall misc php 7.3RC packages, including apcu && xdebug. (which I need for 5.6)

As of now, I cannot reinstall them without reinstalling php 7.3RC, and they do not seem compatible with php 5.6 anyway.

Thanks in advance.

**Comment by mpalourdio** [comment]
Oups, same post here at 25 seconds delay https://github.com/oerdnj/deb.sury.org/issues/968

**Comment by oerdnj** [comment]
dup of #968
