### ISSUE TITLE
php7.0 php-gd error

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#97]
This is a FWIW when using php-gd with php7.0 via `php -i` (however Wordpress still works)...
```
php: symbol lookup error: /usr/lib/php/20141001/gd.so: undefined symbol: gdJpegGetVersionString
```

**Comment by markc** [comment]
Another FWIW, no gettext kills a lot of old smarty based apps.

**Comment by oerdnj** [comment]
hmm, I have seen this error before and it's caused by using external gd library. the bug has obviously creeped in again. It's an upstream issue, and perhaps somebody will fix that before full release :).

gettext has been compiled in.

**Comment by alecpl** [comment]
By upstream you mean PHP?
