### ISSUE TITLE
unstable packages in repo

### ISSUE THREAD

**Issue by bschaefer99** [oerdnj/deb.sury.org#974]
Hello,

I just wanted to raise an issue that we experienced today: One of our build servers  (running ubuntu) was set to ensure the latest version of php-xdebug was installed. We noticed this morning that our config-management scripts forced an update:
`puppet-agent[12958]: (/Stage[main]/mymodule/Package[php-xdebug]/ensure) ensure changed '2.6.0+2.5.5-1+ubuntu18.04.1+deb.sury.org+1' to '2.7.0~beta1+2.6.1+2.5.5-1+ubuntu18.04.1+deb.sury.org+1'
`

Currently, we aren't able to run our integration tests due to an error from phpunit:
`
No code coverage driver is available
`

I wasn't aware that there was the potential to receive unstable packages from this particular repo.

**Comment by oerdnj** [comment]
```
$ dpkg-parsechangelog
Source: xdebug
Version: 2.7.0~beta1+2.6.1+2.5.5-1
Distribution: unstable
Urgency: medium
Maintainer: Ondřej Surý <ondrej@debian.org>
Timestamp: 1539604503
Date: Mon, 15 Oct 2018 11:55:03 +0000
Changes:
 xdebug (2.7.0~beta1+2.6.1+2.5.5-1) unstable; urgency=medium
 .
   * New upstream version 2.7.0~beta1+2.6.1+2.5.5
   * Use different versions of xdebug for different PHP:
     + xdebug 2.7.0~beta1 for PHP 7.3.0
     + xdebug 2.6.1 for PHP 7.0, 7.1 and 7.2
     + xdebug 2.5.5 for PHP 5.6
```

**Comment by oerdnj** [comment]
But I think the real issue that you got bitten by was #968.

**Comment by bschaefer99** [comment]
Thanks @oerdnj! I'll search a little more next time.
