### ISSUE TITLE
Support Ubuntu 18.10 (Cosmic Cuttlefish) for the nginx PPA

### ISSUE THREAD

**Issue by DXGLdotinfo** [oerdnj/deb.sury.org#977]
The nginx PPAs (both stable and mainline) currently do not have builds for Ubuntu 18.10.  Will this be fixed soon?

**Comment by nuxwin** [comment]
Why you don't just use LTS version?

**Comment by DXGLdotinfo** [comment]
Do you mean install the version compiled for Bionic until such time Surý cuts a Cosmic branch, and while I am at it stuff in my self-compiled copy of OpenSSL 1.1.1 LTS (while waiting for him to add that to the libssl1.1 package)?

**Comment by nuxwin** [comment]
@DXGLdotinfo 

No, I just meant Ubuntu Bionic Beaver (LTS version). Generally speaking, you should avoid serving PHP applications through non-LTS ubuntu version.

**Comment by DXGLdotinfo** [comment]
This can be closed now, as the PPAs have now been updated to include packages for Cosmic.
