### ISSUE TITLE
Composer doesn't work in Ubuntu 18.04 and PHP 7.1

### ISSUE THREAD

**Issue by saidbakr** [oerdnj/deb.sury.org#978]
The command `composer` does not work when trying to install it like [the official documentation](https://getcomposer.org/download/) . It returns errors about missing PHP required libraries such as:
```
php: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
```
It only works if I use `php composer.phar` or removing it and installing it using `apt-get install composer` with old version.

I initialized [this issue](https://github.com/composer/composer/issues/7730) at the composer's repo and the main feedback states that the problem in PHP configurations. Indeed I did not configure any thing, it is just like what happened in my previous Ubuntu 16.04, I installed PHP from your PPA.

**Comment by oerdnj** [comment]
Packages from this PPA never install anything to /usr/local, don’t mix PPA install and source compilation and you’ll be fine.
