### ISSUE TITLE
courier-0.75 missing systemd service files

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#98]
Testing courier-mta 0.75...
```
Failed to restart courier-mta-ssl.service: Unit courier-mta-ssl.service failed to load: No such file or directory.
Failed to restart courier-imap-ssl.service: Unit courier-imap-ssl.service failed to load: No such file or directory.
```
so I thought they might be in the courier-mta-ssl and courier-imap-ssl packages but trying to install them got me (maybe no longer needed but the systemd service files are missing from the non-ssl packages)...
```
[...]
The following packages have unmet dependencies:
 courier-imap-ssl : Depends: courier-imap (>= 1.3.7-3) but it is not going to be installed
 courier-mta-ssl : Depends: courier-mta (>= 0.75.0.1~) but 0.75.0-1+deb.sury.org~wily+13 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Also these 2 common config dirs are missing...
```
/etc/courier/hosteddomains
/etc/courier/esmtpacceptmailfor.dir
```

**Comment by oerdnj** [comment]
```
/etc/courier/hosteddomains
/etc/courier/esmtpacceptmailfor.dir
```

Where do those belong? I don't remember seeing them in former packages?

I am looking into the dependencies right now.

**Comment by markc** [comment]
_Where do those belong?_

In courier-base because incoming IMAP and POP (and sqwebmail) rely on them for local delivery.

They may not already exist in current packages. Come to think of it my setup scripts probably check for them and create them if they don't exist so that may be why I don't recall having to manually create them for a very long time (hence me thinking they were included in courier-base). However, it would be "nice" if they were included in a package.

**Comment by oerdnj** [comment]
I added the two directories to the courier-base package and added a maintscripts to remove the old sysvr scripts.

I would also welcome somebody writing systemd unit files for courier packages. But it better be someone who uses courier packages on daily basis.
