### ISSUE TITLE
OpenSSL source package - Avoid useless optimized builds

### ISSUE THREAD

**Issue by nuxwin** [oerdnj/deb.sury.org#980]
@oerdnj 

You're providing your own OpenSSL version 1.0.2o at https://packages.sury.org/php/pool/main/o/openssl/

Could you include the following fixes:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759811
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823774

Thank you.

**Comment by oerdnj** [comment]
Same here...
