### ISSUE TITLE
[Feature Request] php-zbarcode

### ISSUE THREAD

**Issue by TuningYourCode** [oerdnj/deb.sury.org#981]
Would be good if you could package https://github.com/mkoppanen/php-zbarcode too :)

If we could support you to implement the build plan just tell me how to.

**Comment by oerdnj** [comment]
I am bit hesitant to package something that has no official release.

**Comment by oerdnj** [comment]
I will package zbarcode when there's official release. Just picking random state of the git doesn't really seem like good ide to package something.

**Comment by TuningYourCode** [comment]
ok, thank you for taking a look at it anyway.

Of course it's understandable for us that you won't package it until there is a proper release cycle etc. for that extension.

We will take a look at doing it our self or replace the extension.
