### ISSUE TITLE
Openssl 1.1.1 package on 14.04 broke bind9 and openssh-server

### ISSUE THREAD

**Issue by mgriego** [oerdnj/deb.sury.org#982]
I updated to the 1.1.1 packages of openssl and libssl just a little bit ago on an otherwise up-to-date 14.04.5 server, and after doing so, the openssh server and bind9 failed to start.  I didn't record the actual error messages, but they were complaining about a missing `libssl_conf.so`/`ssl_conf` module.  If I started the binary with `OPENSSL_CONF=/etc/ssl`, it would work, however this broke my ability to ssh into the server remotely, since this was not set properly in the binary and the ssh server would not start up.  I downgraded back to the 1.1.0h version, and everything is working for now (thankfully this server was not remote).

**Comment by mgriego** [comment]
For the record, I have these two PPAs on that server: 
```
deb http://ppa.launchpad.net/ondrej/apache2/ubuntu trusty main
# deb-src http://ppa.launchpad.net/ondrej/apache2/ubuntu trusty main
deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main
# deb-src http://ppa.launchpad.net/ondrej/php/ubuntu trusty main
```

**Comment by oerdnj** [comment]
Neither OpenSSH nor BIND 9 packages on Ubuntu 14.04 are compiled against OpenSSL 1.1.x.  Neither there's OpenSSL 1.1.1 neither in `ppa:ondrej/apache2` nor in `ppa:ondrej/php`, so I don't know what you are exactly doing, but it feel there's more to the story than you are telling...

**Comment by mgriego** [comment]
And, yet, it did.  I'm familiar with how to use `ldd` to find the linked libraries a binary depends on.

In fact, the system previously had one of your openssl packages installed from that same repo: `openssl_1.1.0h-2.0+ubuntu14.04.1+deb.sury.org+1_amd64.deb`.  When I downgraded, I downgraded back to that.

Currently, the system has both the original `libssl1.0.0` and the `libssl1.1` that came from your packages.  But, the system `openssl` package was replaced with your `openssl` package that's version 1.1.0h.

Here's the log from the upgrade:
```
Log started: 2018-10-27  16:35:41
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading database ... 30%^M(Readin
Preparing to unpack .../libssl1.1_1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1) over (1.1.0h-2.0+ubuntu14.04.1+deb.sury.org+1) ...
Preparing to unpack .../openssl_1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1_amd64.deb ...
Unpacking openssl (1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1) over (1.1.0h-2.0+ubuntu14.04.1+deb.sury.org+1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libssl1.1:amd64 (1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1) ...
Setting up openssl (1.1.1-1+ubuntu14.04.1+deb.sury.org+0.1) ...
Installing new version of config file /etc/ssl/openssl.cnf ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
Log ended: 2018-10-27  16:35:52
```

Everything started working again *without* needing the `OPENSSL_CONF` environment variable as soon as I downgraded that package back to 1.1.0h, which I had to do manually via dpkg.  I initially added the apache2 and php PPAs on 10/6, and that's when openssl 1.1.0h was installed, replacing 1.0.1f from Ubuntu.  libssl1.1 was installed alongside the existing libssl1.0.0, which remained.  The system has worked without issue in that configuration until yesterday when the upgrade to openssl 1.1.1 caused problems.  I can only assume that something in the /etc/ssl setup that was included in 1.1.1 caused issues with libssl1.0.0.  I don't have any other good explanation.  Regardless, there *was* a problem with the upgrade for packages relying on the older openssl that cleared up when  I downgraded.  Note that apache2, which *does* have mod_ssl enabled/working, worked fine, since it's from your PPA and *was* compiled against libssl1.1.

**Comment by edyesed** [comment]
I can echo that installing openssl 1.1.1 from `ppa:ondrej/apache2` destroyed openssh on another customer's machines ( mine ).

**Comment by bernardgardner** [comment]
https://gist.github.com/bernardgardner/ad09a6f46568ba470a642215a66c2a3b

This is the dpkg.log entries from this morning on one of the systems @edyesed is referring to.

**Comment by bernardgardner** [comment]
And another report here - https://www.digitalocean.com/community/questions/ubuntu-14-ssh-stopped-working-after-updating-openssl

**Comment by oerdnj** [comment]
This is just an evil plot to force you upgrade from Ubuntu 14.04 :).

Ok, so the quick fix is to replace just the `openssl` package with the version from Ubuntu, and I am preparing `src:openssl` 1.1.1 package that will include only the libraries and not the tools nor the `openssl.cnf` configuration that's causing the troubles.

I am going to test it if it builds and if it does it should land in the `ppa:ondrej/apache2` repository within couple of minutes.

**Comment by oerdnj** [comment]
The problem should not exist anymore.  That doesn't really help old installations, where people will need to downgrade `openssl` package to the distro version, but the new installations should not be affected.
