### ISSUE TITLE
TLSv1.0 and TLSv1.1 not available with OpenSSL 1.1.1-1+ubuntu18.04.1+deb.sury.org+0.2 in nginx-qa

### ISSUE THREAD

**Issue by Thomas2500** [oerdnj/deb.sury.org#985]
Hello.

To test nginx-qa I installed `nginx-mainline` and `nginx-qa` from your PPA.
After restarting nginx (`1.15.5-0.1+ubuntu18.04.1+deb.sury.org+1`), I tested the connection to nginx with `testssl.sh` which shows me that the server doesn't offer TLSv1.0 and TLSv1.1 any more.

First I enabled all protocols within nginx `ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;` which resulted in offering me TLSv1.2 and TLSv1.3 only.
Removing TLSv1.3 has no effect, it is always active.
Activating only TLSv1.0 and TLSv1.1 with `ssl_protocols TLSv1 TLSv1.1;` provides only TLSv1.3 to clients and not TLSv1.0 and TLSv1.1 as expected.

I have not added any additional configuration to nginx like cipher suites. I installed everything on a new VM with Ubuntu 18.04.

Dovecot from the main Ubuntu repository seems to have the same problem. (TLSv1.2 can be disabled, TLSv1.3 is always active and TLSv1.0 and TLSv1.1 is always disabled)
Postfix seems to work with TLSv1.0, TLSv1.1, TLSv1.2 and TLSv1.3, but TLSv1.3 also can't be disabled.

Thank you very much for your work!

**Comment by oerdnj** [comment]
That would be:

https://salsa.debian.org/debian/openssl/blob/debian/unstable/debian/libssl1.1.NEWS

**Comment by Thomas2500** [comment]
Thank you very much!
Now it works.
