### ISSUE TITLE
PHP broken on armhf (armv6l CPU): SIGKILL Illegal instruction

### ISSUE THREAD

**Issue by Majkl578** [oerdnj/deb.sury.org#988]
I have a Raspbian (Debian Stretch-based) installed on a Raspberry Pi Zero.
Using your PHP repository for Debian, I installed armhf version of PHP (both php7.3-cli and php7.2-cli).

Executing this PHP fails:
```
$ php7.2 -v
Illegal instruction
$ php7.3 -v
Illegal instruction
```

**Comment by oerdnj** [comment]
Yes, you news at least armv7-a for Debian armhf: https://wiki.debian.org/ArmHardFloatPort#Minimum_CPU_.26_FPU
