### ISSUE TITLE
php7.2-imagick armhf

### ISSUE THREAD

**Issue by nachoparker** [oerdnj/deb.sury.org#992]
Hello,

Thank you again for providing `php7.2-redis` for armhf. Maybe you didn't notice this, but trying to install `php-imagick` pulls the `php7.0` dependencies.

I can now provide [NextCloudPi](nextcloudpi.com) images for armhf because php redis is crucial for Nextcloud, but it would be very nice to be able to include imagick as well, because it is used for the gallery.

Thank you in advance!

**Comment by oerdnj** [comment]
It's mostly done.  I have issue yet another rebuild as stretch arm64 build has (randomly) failed, but the armhf should be fine now.

**Comment by nachoparker** [comment]
awesome, again many thanks
