### ISSUE TITLE
libgd3 libpcre3 libssl1.1 openssl packages from deb.sury.org

### ISSUE THREAD

**Issue by hostingnuggets** [oerdnj/deb.sury.org#993]
Hello,

On my Debian 9.5 server I am using PHP 7.1 (FPM) from the deb.sury.org repository in order to have a more modern PHP on Debian 9.5. So far so good it works but today by running `apt-get update` I noticed that there are a few packages updates outstanding which all come from deb.sury.org. Here is the output:

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libgd3 libpcre3 libssl1.1 openssl php-common
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,827 kB of archives.
After this operation, 618 kB of additional disk space will be used.
```

I understand that I need to update php-common from the deb.sury.org repo but what about libgd3, libpcre3, etc. Do I need to update these packages from deb.sury.org too? or can I keep these packages from Debian?

I would rather keep these packages from Debian if possible. If yes how do I do that? I think it has to do with APT pinning or something like that. This would be a good point maybe to add onto the wiki...

The content of my sources.list.d file for sury.list is the following:
``` 
deb https://packages.sury.org/php/ stretch main
```

**Comment by oerdnj** [comment]
Google APT Pinning.  But I am sorry, this is not a user support forum, use something like Ask Ubuntu if you require further help.
