### ISSUE TITLE
openssl 1.1.1 breaks lighttpd 1.4.45

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#995]
> 2018-11-08 18:06:21: (connections-glue.c.126) SSL: renegotiation initiated by client, killing connection 

ii  lighttpd                               1.4.45-1
ii  openssl                                1.1.1-2+0~20181105132532.5+jessie~1.gbp90eb86

Debian 8.11 (Jessie)

https://redmine.lighttpd.net/issues/2912
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913251

**Comment by oerdnj** [comment]
🤷🏼‍♂️ There’s only so much I can do, and I value consistency across repositories more than having everything functional.

I guess disabling TLS1.3 in OpenSSL confit would be a way to solve it. Or upgrade the lighttpd to newer version.

Could you also report that back to Debian? The libssl1.1 in unstable will need versioned Breaks: on lighttpd

**Comment by oerdnj** [comment]
I am not sure what would be the best solution here.  The most sane would be adding: `Breaks: lighttpd (<< 1.4.51~)`, so at least it doesn't break existing systems without prior notice...

**Comment by OlafvdSpek** [comment]
libssl1.1 issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913558

**Comment by oerdnj** [comment]
Yup, I saw that, thanks.

**Comment by oerdnj** [comment]
> I am not sure what would be the best solution here. The most sane would be adding: `Breaks: lighttpd (<< 1.4.51~)`, so at least it doesn't break existing systems without prior notice...

And I just did that, so after a rebuild there will be Breaks on `lighttpd (1.4.51~)`, I understand this is suboptimal, but it's the only thing I can do from here without backporting fixed `lighttpd` package.

**Comment by OlafvdSpek** [comment]
Thanks. 
Why is libssl in the repo though, do newer php versions require it?

**Comment by oerdnj** [comment]
It's not mandatory, but still using OpenSSL 1.1.1 has benefits for TLS connections.

It's also about consistency - I also have apache2 and nginx repositories, and it would create just chaos to have different OpenSSL versions across different repositories.

**Comment by OlafvdSpek** [comment]
True. Would it make sense to offer apache, nginx and php via official Debian backports as well?
